### ISSUE TITLE
Hydrus friendly log files

### ISSUE THREAD

**Issue by AdvancedNeanderthal** [Bionus/imgbrd-grabber#1001]
[Hydrus](https://github.com/hydrusnetwork/hydrus) allows you to import tags from txt files with matching filenames. The current log files that Grabber is able to generate almost work, but it adds all the tags to one line with no separators. Hydrus imports the tags per line, so you end up with one giant tag for stuff like %general% or %all%. Which of course makes sense for filenames, but doesn't work out so well for the text files.

for example if you use something like:
%all:includenamespace,excludenamespace=general,unsafe%
rating:%rating%
%general%

you get:
copyright:something character:char1 character:char2
rating:safe
tag1 tag2 tag3

instead of what hydrus would expect:
copyright:something
character:char1
character:char2
rating:safe
tag1
tag2
tag3

Or even simply separating the tags with commas would at least make it possible to run the txt files through some regex to replace the commas with line breaks.

Maybe there's a way to do all this already and I'm just being a bozo?

JetBoom has made a [script](https://github.com/JetBoom/boorutagparser-server) that does it along side a greasemonkey script, if that is helpful in any way.

**Comment by Bionus** [comment]
Why don't you simply set your separator to "new line"?

Something like this should do the trick:
```
 %all:includenamespace,excludenamespace=general,unsafe,separator=\n%
rating:%rating%
%general,separator=\n%
```

Both `\n` and `\r` are supported IIRC.

**Comment by AdvancedNeanderthal** [comment]
That works perfectly, thank you. I'm a bozo after all, for not seeing that. It's even right next to the namespace stuff I was looking at >.<

I had included %general% separately in an attempt to get it to list after the namespaced stuff. Doesn't seem like it does that though, it doesn't make a difference when importing the tags anyways, so that's fine.

Another quick question. Is there any way to retroactively generate these txt files for images that have already been downloaded? Similar to the "rename existing images" tool?

**Comment by ItsSohma** [comment]
@AdvancedNeanderthal, out of curiosity, what's the point of using the two programs interchangeably? For me, Grabber does everything I'm looking for.

**Comment by AdvancedNeanderthal** [comment]
I use Hydrus for tagging and managing the files I have already downloaded, including non booru related stuff like video and various media. It also allows you to sync with public tag repositories. It actually does have a built in way of downloading from various boorus, but I just prefer Grabber in that respect. Mainly because the Hydrus downloader ignores a lot of namespaces (like rating) and doesn't browse thumbnails, it simply mass downloads everything from whatever tags you feed it.

**Comment by Bionus** [comment]
> I use Hydrus for tagging and managing the files I have already downloaded, including non booru related stuff like video and various media.

Except for the "including non booru related stuff like video and various media" part, wouldn't the rest of the usage be covered by having a local booru fed by Grabber?

Or is the fact that everything is self-contained on the filesystem through files (therefore not locking you with any specific software or booru) an important reason?

Just curious because I've been asked many times to include a booru directly inside Grabber, so I'm wondering if being compatible with Hydrus files would be a "good enough" solution.

Also curious because I definitely should try Hydrus, given how messy is my filesystem.

> It also allows you to sync with public tag repositories

What's a "public tag repositories" if I may ask? :smile:

> Another quick question. Is there any way to retroactively generate these txt files for images that have already been downloaded? Similar to the "rename existing images" tool?

Not currently AFAIK, but that's totally feasible.
I created an issue to track this suggestion, see issue #1008. :+1:

I'll close this one in the meantime.

**Comment by BarryMode** [comment]
I do like the idea of using Grabber, rather than a local booru. For some reason, I really like using the app. But it works fine to use a local booru, and that's what I've done for a long time. The major downside I can see is that the setup time of a locally run board is longer, and I suspect it stumps most casual users.

**Comment by AdvancedNeanderthal** [comment]
> Except for the "including non booru related stuff like video and various media" part, wouldn't the rest of the usage be covered by having a local booru fed by Grabber?

I haven't used a local booru so I couldn't say for sure. As BarryMode mentioned, Hydrus is likely easier to set up for most people. There's an installer and a portable version that you can simply unpack and run. Adding images can be done by dragging and dropping files or folders into hydrus and checking a box to load the tags from txt files, or pull the tags from the filename via regex. You can also set automatic importing on specified folders. A few other possible points that come to mind:

-"[system tags](http://i.imgur.com/ZJwsbiN.png)" so you don't have to rely on tags like "new" or "tagme".
-de-duplicates automatically based on hash (on import: adds any new tags, then ignores the duplicate file) & has a built-in method to find visually similar files
-hotkeys and built in media viewer makes tagging and other tasks fairly quick
-portable. Pair it with a portable install of Grabber and you can travel the WORLD with your collection of cute pics. That's what everyone here collects right? kawaii rating:safe -lewd
-although it's easy to get started, it has a lot of "advanced" features and options as well. https://hydrusnetwork.github.io/hydrus/help/index.html

Again, I've never used a local booru so idk if they also do any of these things.

> What's a "public tag repositories" if I may ask? :smile:

The public tag repositories are essentially just giant user generated pools of tags mapped to files by their hash value. The main one being the one the dev hosts. It can be messy and inconsistent at times, but is nice for just quickly getting some tags on files that don't have any. You're still better off importing your tags directly from where you got the image imo. More info halfway down this [page](https://hydrusnetwork.github.io/hydrus/help/getting_started_tags.html)

> Or is the fact that everything is self-contained on the filesystem through files (therefore not locking you with any specific software or booru) an important reason?

It doesn't necessarily lock you in to the software in the sense that you can export your files exactly as they were (txt files and all) but it does store them in a somewhat non human-friendly way. It renames them to their sha256 value then sticks them in a client_files folder, or wherever you specify. It doesn't remove their extensions or modify them in anyway (aside from renaming them) so worst-case scenario; if exporting fails, you could go grab everything from that folder (then use grabber to re-organize everything :smile:). I'd say that this is an important option to have, but if local boorus also have a decent export option and some sort of way to retrieve files in case of catastrophe, I wouldn't give any extra points to hydrus here.

**Comment by Bionus** [comment]
Thanks a lot for the detailed explanation!
Looks like a really interesting software.

I'll definitely give it a go to see if there's things that could be improved in Grabber based on some Hydrus features, as well as trying to improve the compatibility.

> collection of cute pics. That's what everyone here collects right? kawaii rating:safe -lewd

... right 👀 

> It doesn't necessarily lock you in to the software since you can export your files exactly as they were (txt files and all) but it does store them in a somewhat non human-friendly way. It renames them to their sha256 value then sticks them in a client_files folder, or wherever you specify. It doesn't remove their extensions or modify them in anyway (aside from renaming them) so worst-case scenario; if exporting fails, you could go grab everything from that folder (then use grabber to re-organize everything 😄).

That's quite unfortunate that the files are being moved and renamed.
Even symlinks sound more convenient.
