### ISSUE TITLE
Stuck while downloading large batch

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1002]
Source: Gelbooru.com

### What steps will reproduce the problem?

1. Download a tag with over 100k files
2. Cancel it after 10k images.
3. Resume the batch download. 

### What is the expected behavior? What do you get instead?

Download proceeds normally till the last file. Does not need user intervention to continue.
Download gets stuck after "reportedly" 19000 files are checked and needs the user to click "Skip" for it to continue. Reportedly because the counter always malfunctions.

### How often does this problem occur?

Always.

### What version of the program are you using? On what operating system?

v5.4.2
Windows 10 x64 

### Please provide any additional information below

Picture: http://i.imgur.com/gXW1zPv.jpg

### Problems yet found since this post

- It gets stuck at random pages but the processed file count always consistently has 99x (x being 5-9) at the end. In the log: It tries to find images from who knows where but fails for some reason. It does this till I press "Skip". Evidence: https://drive.google.com/open?id=0B-5SBhsDznYOMTBMNzk5V0ctcHM 

- Sometimes the client gets wild while processing files. The app gets stuck on a single or more files and infinitely loops over the extension list querying the api. These files are nowhere to be found in the list or are marked downloaded. Evidence: https://drive.google.com/open?id=0B-5SBhsDznYOc3oxb0ZHV3cyLUk

- It can be stopped by clicking "Pause" but this introduces a new erroneous behavior instead. The downloads that are being downloaded do get paused but then it starts the waiting ones and continues as nothing happened. At the completion of the page, the remaining files remain and it waits as if its in a paused state. Resuming here will resume the downloads at 1 or 2 KBps thus I have to Skip them nonetheless.

- Crash happens randomly when file count goes above 100k. Dump Files: https://drive.google.com/open?id=0B-5SBhsDznYONjNocTdsQlpncHc

**Comment by brazenvoid** [comment]
New findings:
- It gets stuck after completing a page.
- It gets stuck at definite page numbers which are almost 20 pages apart. The file count being 18999, 37999 and so on.

**Comment by brazenvoid** [comment]
New Findings:

- It doesn't get get stuck at pages almost 20 pages apart.
- It gets stuck at random pages but the processed file count always consistently has 999 at the end. The file count as I have discovered yet: 18999, 37999, 40999

**Comment by brazenvoid** [comment]
New Findings:

- Sometimes the client gets wild while processing files. Even though it gets the file from the first call, it still searches for an arbitrary number of possible extensions with "Image not found". When the image gets fully downloaded and all extensions had not been searched yet, it stops the search. 

- This also happens when a page which has at least one downloadable image, gets completed. It tries to find those images again but fails for some reason. It does this till I press "Skip". It still continues the search but stops when the next page gets loaded.

**Comment by brazenvoid** [comment]
Continued from above. Videos for the findings.

Point 1: https://drive.google.com/open?id=0B-5SBhsDznYOMTBMNzk5V0ctcHM
Point 2: https://drive.google.com/open?id=0B-5SBhsDznYOc3oxb0ZHV3cyLUk

**Comment by brazenvoid** [comment]
New Findings:

- A crash happens randomly. Dumps: https://drive.google.com/open?id=0B-5SBhsDznYONjNocTdsQlpncHc

**Comment by brazenvoid** [comment]
Now it consistently crashes, just like before... my dreams are tarnished yet again...

**Comment by brazenvoid** [comment]
New Findings:

- The app sometimes get stuck on a single file and infinitely loops over the extension list querying the api.
- It can be stopped by clicking "Pause" but this introduces a new erroneous behavior instead. The downloads that are being downloaded do get paused but then it starts the waiting ones and continues as nothing happened.

**Comment by Still34** [comment]
> It gets stuck at random pages but the processed file count always consistently has 99x (x being 5-9) at the end. In the log: It tries to find images from who knows where but fails for some reason. It does this till I press "Skip". Evidence: https://drive.google.com/open?id=0B-5SBhsDznYOMTBMNzk5V0ctcHM

Same thing here. Surprised the issue hasn't been labeled yet. This happens quite regularly with my large batch downloads.

**Comment by brazenvoid** [comment]
Damn, I am getting a real urge to make my own app instead... even though I know, it would be an endeavor...
