### ISSUE TITLE
crash while saving image

### ISSUE THREAD

**Issue by fobear697** [Bionus/imgbrd-grabber#1003]
### What steps will reproduce the problem?
saving images grabber crashes and not responding.

### What is the expected behavior? What do you get instead?
save an image from preview window and does not save and crashes.

### How often does this problem occur?
everytime

### What version of the program are you using? On what operating system?
5.4.2 on win 10

**Comment by Bionus** [comment]
Which source and image did this happen on?
What was your filename?
Could you also share your log file of right after such a crash?
