### ISSUE TITLE
GIF too big won't fit

### ISSUE THREAD

**Issue by Dyllac** [Bionus/imgbrd-grabber#1006]
### What steps will reproduce the problem?
Look for gif that have high resolutions and open them.

### What is the expected behavior? What do you get instead?
The gif should fit to the size of the grabber(height)?

### How often does this problem occur?
Always. On every animated image that's too big

### What version of the program are you using? On what operating system?
Grabber 5.4.2
Windows 10

### Please provide any additional information below
Included a picture of the issue. If anything else is needed, please tell me.
![example](https://user-images.githubusercontent.com/30081867/28556107-c60db918-70c9-11e7-95df-5c1f39db6b26.jpg)

**Comment by Bionus** [comment]
Indeed, I could reproduce the issue locally.
Gifs are currently not resized in the image viewer, which should be fixed.
