### ISSUE TITLE
grabber wont work

### ISSUE THREAD

**Issue by WilluG** [Bionus/imgbrd-grabber#1007]
### What steps will reproduce the problem?
clicking on any fav post or even searching anything.

### What is the expected behavior? What do you get instead?

"no results" it just shows that whatever i do

**Comment by Bionus** [comment]
Which sources did this occur on?

**Comment by dalivingman** [comment]
this seems to happen with any of the sankaku sites at the moment.

**Comment by WilluG** [comment]
Allright, thank you.
It did work eventually but after lots of time and many tries.
:^ )

On 26 Jul 2017 22:30, dalivingman <notifications@github.com> wrote:

this seems to happen with any of the sankaku sites at the moment.

**Comment by WilluG** [comment]
Sankaku complex :^£

On 26 Jul 2017 17:47, Jack Vasti <notifications@github.com> wrote:

Which sources did this occur on?

**Comment by Bionus** [comment]
If it's Sankaku, see issue #997.
It's not really working for anyone at the moment. :smile:

**Comment by WilluG** [comment]
Thank you :^ )
Idk if its an ip problem really but lets hope the Dev work it out.

On 27 Jul 2017 00:31, Jack Vasti <notifications@github.com> wrote:

If it's Sankaku, see issue #997<https://github.com/Bionus/imgbrd-grabber/issues/997>.
It's not really working for anyone at the moment. 😄
