### ISSUE TITLE
Segregation to folders while downloading a batch?

### ISSUE THREAD

**Issue by maslos** [Bionus/imgbrd-grabber#1009]
Sorry for noob question.
Lets say i have a batch of some images and i want a image with tag "a" go to folder named "a" same for image with tag "b" go to folder named "b".
Is this possible? I assume it is withusing correct condiitionals in filenames but how do you set multiple conditions for one batch?
Thank you in advance.

**Comment by Bionus** [comment]
You could use filename conditionals (`<>` stuff) mixed with custom tokens.
Or even more simply use conditional filenames if it works.

With filename conditionals:
```<"a"a/><"b"b/>%md5%.%ext%```

With conditional filenames:
1. * Condition: `a`
    * Filename: `a/%md5%.%ext%`
2. * Condition: `b`
    * Filename: `b/%md5%.%ext%`

**Comment by maslos** [comment]
Thanks alot, also theres an issue with tags that contain "/" (like fate/grand_order), using this tag as condition creates subfolder and output looks like this: "fate/grand_order/file.jpg"

**Comment by maslos** [comment]
After messing with custom tokens and conditionals i feel like theres something wrong when you are trying to give multiple conditions when using any method or mixing false/positive conditions as well and i think all conditions separated by >< are threaten as OR operator.

Whenever i try to make condition like <"tag1" !"tag2" folder/> it will download file to "folder" as long as tag1 is in tag list no matter if i want there a file that dont have tag2.

Also when using multiple <> for file name, for example:
<"tag1" folder1/><"tag2" folder2/><!"tag3" folder3/> i end up with something like this:
../folder1/folder2/folder3/file, (or some random mixes), 

Another issue i got is with custom tokens, if i set multiple tags for one token to be ignored but one tag was a condition to download i also end up with some random folder directories, for example:
<!%token1% "tag1"/><!%token2% %token3%/> i get folder ../tag1/ with files containing stuff from token3.

I cant get conditional filenames to work at all, (maybe some more detailed manual? ^^)
Anyway after messing with random options i see how powerful Grabber has become, really good work.
Thanks alot.

**Comment by Bionus** [comment]
Sorry for the late answer, your comment totally passed under my radar! 😕 

> theres an issue with tags that contain "/" (like fate/grand_order), using this tag as condition creates subfolder and output looks like this: "fate/grand_order/file.jpg"

Thanks, I just pushed a fix for that that will arrive in v5.5.0.

> i feel like theres something wrong when you are trying to give multiple conditions when using any method or mixing false/positive conditions as well

> Whenever i try to make condition like <"tag1" !"tag2" folder/> it will download file to "folder" as long as tag1 is in tag list no matter if i want there a file that dont have tag2.

I actually don't think I have ever tested that, to be honest. I just checked and it indeed doesn't really work properly in the 5.4.x version. It will somehow only consider the first condition.

> i think all conditions separated by >< are threaten as OR operator.

> Also when using multiple <> for file name, for example:
> <"tag1" folder1/><"tag2" folder2/><!"tag3" folder3/> i end up with something like this:
> ../folder1/folder2/folder3/file, (or some random mixes),

They are simply all treated independently: if you have only "tag1", you will get "folder1/folder3/" for example.

> I cant get conditional filenames to work at all, (maybe some more detailed manual? ^^)

It's simply one big `<>` condition. If the `condition` field is found, the filename that will be used is the one provided. Example:

![image](https://user-images.githubusercontent.com/882719/29486536-767b71dc-84e8-11e7-8444-9b81bde2f30c.png)

If an image contains "tag1", it will be saved in "folder1/", if it contains "tag2", "folder2/", etc. If it contains both, it will use the first in the list (in this case, "folder1/").

Actually, what kind of filenaming scheme are you trying to achieve?

>  Anyway after messing with random options i see how powerful Grabber has become, really good work.
> Thanks alot.

Thanks! :smile:

**Comment by Bionus** [comment]
Ok I pushed some changes that should ensure it works properly with multiple and mixed conditions. However, I truly believe you'd be better off with conditional filenames (ass my screenshot above).

Now, given an image has an artist and the tags "tag1 tag2 tag3":

* `<"tag1" "tag2"/>%md5%.%ext%` -> `tag1 tag2/%md5%.%ext%`
* `<"tag1" "tag4"/>%md5%.%ext%` -> `%md5%.%ext%`
* `<"tag1" !"tag4"/>%md5%.%ext%` -> `tag1 tag4/%md5%.%ext%`
* `<"tag1" !"tag2"/>%md5%.%ext%` -> `%md5%.%ext%`
* `<"tag1" %artist%/>%md5%.%ext%` -> `tag1 %artist%/%md5%.%ext%`
* `<"tag1" %nothing%/>%md5%.%ext%` -> `%md5%.%ext%`
* `<"tag1"!%nothing%/>%md5%.%ext%` -> `tag1/%md5%.%ext%`
* `<"tag1"!%artist%/>%md5%.%ext%` -> `%md5%.%ext%`

Note that if you don't want to see the condition in the result, you can prepend it with a `-`:

* `<-"tag1"folder/>%md5%.%ext%` -> `folder/%md5%.%ext%`
* `<-%artist%folder/>%md5%.%ext%` -> `folder/%md5%.%ext%`

**Comment by maslos** [comment]
just want to say thanks for all replys and fixes ^^
