### ISSUE TITLE
How do I login on Rule34hentai.net? 

### ISSUE THREAD

**Issue by Slayer-chan** [Bionus/imgbrd-grabber#1011]
How do I properly login to Rule34hentai? Credentials and Login from the settings doesn't seem to work. Do I need to use cookies? If so, how do I do it?

**Comment by Bionus** [comment]
Here are the login settings for "rule34hentai.net", and, to some extend, all Shimmie boards:

* Type: `POST`
* URL: `/user_admin/login`
* Username: `user`
* Password: `pass`
* Cookie: `shm_session`

![image](https://user-images.githubusercontent.com/882719/28996144-29b094ac-79fa-11e7-9323-f667af68bcba.png)

:warning: However, while testing it out, I noticed an incompatibility problem between some settings, which may make this not work. I pushed a fix which should fix the issue.

BTW, why do you want to log into a Shimmie board?
Is there some restrictions on this one for non-logged accounts?

**Comment by Slayer-chan** [comment]
Thanks for the help and yes. There are some tags and images that you cannot see unless you're logged in.

**Comment by mike911026** [comment]
Thank you really much. Sorry for those dumb question again
