### ISSUE TITLE
Ignoring all images when 2 or more tags are present

### ISSUE THREAD

**Issue by tehkarma** [Bionus/imgbrd-grabber#1013]
### What steps will reproduce the problem?

1. Donwload all images with the "yang-do" tag from danbooru and gelbooru.
2. Download all images with the "yang-do" + "ponytail" tags from danbooru and gelbooru in a separate folder.

### What is the expected behavior? What do you get instead?

1. All images are saved in the "yang-do" folder.
2. All images with the "yang-do" + "ponytail" tags are ignored. Nothing is downloaded.

### How often does this problem occur?

Almost all the time.
Seems to happen when I have a folder with all images from an artist downloaded and try to download images from same artist with additional tags in a separate folder.

### What version of the program are you using? On what operating system?

v5.4.2 on Windows 7 Ultimate 64bit SP1

### Please provide any additional information below
Tried changing download location. Still ignored.
Managed to download after changing the original "yang-do" folder name to something else.

**Comment by Bionus** [comment]
It must come from the duplicate prevention using the MD5 list.
Could it be that it is set to "Don't save" in your settings?

![image](https://user-images.githubusercontent.com/882719/28969765-419fa7d0-7926-11e7-9f47-6c4e5558ca18.png)

**Comment by tehkarma** [comment]
It was actually set to "Don't save". I actually  thought that option was there so it doesn't download an existing file a second time and overwrite it.

But should it still refuse to download files if the original folder and the second folder are not in the same location?

**Comment by Bionus** [comment]
If a file already exists with the same name and directory, it won't be downloaded even if this setting is set to "Save".

This setting only relates to not having duplicates among **all** downloaded files, even if the filename and output directory are different.

**Comment by Bionus** [comment]
And actually, since you already have the file downloaded, you can simply use "Copy" instead of "Save" to not re-download it. :smile:

**Comment by tehkarma** [comment]
I suppose I misunderstood the purpose of that setting entirely.
That could reduce my download times.

**Comment by BarryMode** [comment]
I didn't realize that this setting was for all files, although, I should have since I understand that there's a file with all the MD5 data. I've never tested it, though, as all my files are stored in one folder.

**Comment by Bionus** [comment]
I guess this setting should be made clearer indeed, by renaming it to something like "global duplicates" and adding a second one "same-folder duplicates".
