### ISSUE TITLE
%search% is saving all the tags of the image instead of just the search keywords

### ISSUE THREAD

**Issue by LeinadDan** [Bionus/imgbrd-grabber#1017]
### What steps will reproduce the problem?
Just searching any sort of tags and including %search% in the file name

### What is the expected behavior? What do you get instead?
e.g. searched kanzaki_ranko -comic, has %search%.%ext% as file name
expected result: kanzaki_ranko -comic.jpg
result instead: 1girl 2015 _d bouquet bridal_veil character_name choker church cross dress drill_hair flower grey_hair haruka_natsuki idolmaster idolmaster_cinderella_girls june kanzaki_ranko looking.jpg

### How often does this problem occur?
after the first search/save, always

### What version of the program are you using? On what operating system?
version: 5.4.2
OS: Windows 8.1

**Comment by Bionus** [comment]
I can't reproduce. Could you share your `settings.ini` file?
I see that you :+1: the issue @MasterPetrik, did you have the same problem?

**Comment by MasterPetrik** [comment]
@Bionus meh... I just likeing around -___-

Btw, gonna post some suggestions today...but I'm too lazy -___-

**Comment by LeinadDan** [comment]
where do i find the settings.ini?

**Comment by MasterPetrik** [comment]
right there:
![image](https://user-images.githubusercontent.com/22294259/29103722-01a34f0e-7cca-11e7-930d-1b973adb3e30.png)

**Comment by LeinadDan** [comment]
here ya go
[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/1210408/settings.zip)
