### ISSUE TITLE
multiple download results windows bug

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1024]
multiple download results windows when many batch downloads in one time or from multiple sources.

When some of downloads are finished, results window with current results may appear.
After compleating all downloads results window with true results also appears.

looks like this bug appeared in last grabber version(s)

![image](https://user-images.githubusercontent.com/22294259/29443595-e79c66da-83e1-11e7-91db-7c505e42ea2c.png)

**Comment by Bionus** [comment]
It seems to come from the new "packing" system when using asynchronous downloads. When there are a lot of already existing images, there will be a race condition causing the download to be finished when it's actually not.
