### ISSUE TITLE
Cannot compile on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by purachina** [Bionus/imgbrd-grabber#1026]
Hi there! :smile: I'm having troubles compiling Grabber on Ubuntu 16.04.3 (x64), when I try to run build.sh I got:

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Compiling with SSL support
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindOpenSSL.cmake:370 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!
```

I have fixed it installing the **libssl-dev** package as described [here](https://stackoverflow.com/questions/16248775/cmake-not-able-to-find-openssl). So it is probably a required dependency in order to build it on the current LTS.

Anyways it start to compile now but I got stuck here:

```
.
.
.
[ 93%] Building CXX object gui/CMakeFiles/gui.dir/src/utils/rename-existing/rename-existing-1.cpp.o
[ 94%] Building CXX object gui/CMakeFiles/gui.dir/src/utils/blacklist-fix/blacklist-fix-2.cpp.o
[ 94%] Building CXX object gui/CMakeFiles/gui.dir/src/utils/blacklist-fix/blacklist-fix-1.cpp.o
[ 95%] Building CXX object gui/CMakeFiles/gui.dir/src/utils/empty-dirs-fix/empty-dirs-fix-2.cpp.o
[ 96%] Building CXX object gui/CMakeFiles/gui.dir/src/utils/empty-dirs-fix/empty-dirs-fix-1.cpp.o
[ 96%] Building CXX object gui/CMakeFiles/gui.dir/src/utils/md5-fix/md5-fix.cpp.o
[ 97%] Building CXX object gui/CMakeFiles/gui.dir/src/viewer/zoomwindow.cpp.o
[ 98%] Building CXX object gui/CMakeFiles/gui.dir/src/viewer/detailswindow.cpp.o
[ 98%] Building CXX object gui/CMakeFiles/gui.dir/gui_automoc.cpp.o
[ 99%] Building CXX object gui/CMakeFiles/gui.dir/CMakeFiles/gui.dir/qrc_resources.cpp.o
[100%] Linking CXX executable Grabber
[100%] Built target gui
Can not perform `stat' on 'build/gui/gui': There is no file or directory.

```
Looks like there is a gui folder repeated (idk why) I’m not sure what I should modify from here in order to get it working... :cry: 

The only change I made to the build file was to remove the line where the external ubuntu repository is added as I asked in #1004

**Comment by Bionus** [comment]
Are you building off the `master` branch?
If so, I'd advice either building from the `develop` branch at the moment or at least using its [build.sh](https://github.com/Bionus/imgbrd-grabber/blob/develop/build.sh) file.

It seems a naming inconsistency was introduced: the `mv "build/gui/gui" "release/"` (on the `master` branch) should be `mv "build/gui/Grabber" "release/"`.

I also added the `libssl-dev` dependency, thanks :smile:

**Comment by purachina** [comment]
Yes, I was building from master branch. I just tried to use develop branch and it works well. 

Although it has barely sources and only English lang so I have tried to add Gelbooru to the sources but nothing I do seems to work :confused: 

[Here's a screencast.](https://b.doko.moe/pwevzn.webm)

**Comment by Bionus** [comment]
You must make sure that the settings location contains the "sites/" files. If your "settings.ini" file is in ./release/, then that'll be there. It could also be in "~/.config/Bionus/Grabber/" or your settings directory. You can know the exact location in the first few lines of the log.

**Comment by purachina** [comment]
Weird... I don't really do anything but now it work. 
![this](https://user-images.githubusercontent.com/24848379/29488321-f70b2470-84cd-11e7-9d69-389c4e6eef4a.png)

**Comment by purachina** [comment]
This is weird... If I run "./release/Grabber" it doesn't work but If I go to the folder and run directly ./Grabber it works fine.

**Comment by purachina** [comment]
[Look at this](https://a.doko.moe/qozewy.webm) :confused:

**Comment by Bionus** [comment]
This bug must have been introduced recently. I'll take a look.
Seems like the settings path (first lines of the log) is wrong when starting using "./release/Grabber". Could it be that you have multiple "settings.ini" files?

**Comment by purachina** [comment]
There is only one settings.ini in the release folder
[release.zip](https://github.com/Bionus/imgbrd-grabber/files/1236563/release.zip)

**Comment by Bionus** [comment]
Indeed, it's because Grabber was using the test settings which had the highest priority of settings files.
I just pushed a fix in the `develop` branch, thanks. :smile:
