### ISSUE TITLE
Is there any way to see sample images instead of original images on Image Viewer? (Sankaku Complex)

### ISSUE THREAD

**Issue by Victh** [Bionus/imgbrd-grabber#1027]
I kept getting ip-banned just by browsing images, without any batch downloading. Would be great if there's any way to get sample images when I use Image Viewer so I can browse freely.

Example (SFW): https://chan.sankakucomplex.com/post/show/6281927#image

Sample: https://cs.sankakucomplex.com/data/sample/64/02/sample-6402440927fced72ffaf6db99a71faba.jpg?6281927 -- 92KB

Original: https://cs.sankakucomplex.com/data/64/02/6402440927fced72ffaf6db99a71faba.jpg?6281927 -- 1.7MB

Thanks for the app! It work much smoother than browsing the web,

**Comment by Bionus** [comment]
Not currently.
There is some setting to only _download_ samples but not for browsing. I'll see if it can be added.
