### ISSUE TITLE
Problem with page counter in endless page mode

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1029]
I wanted to create this issue since endless page mode implementation, but was too lazy all this time. 
It was implemented not fully right. 
The problem is in current endless page mode way of pages counting. Considering that endless page mode means only ONE but unlimited page, after loading images from next pages, page counter increases in current version. Still not a problem, right? But!
If you repeat search(press on search button again without changing any settings) or even just close Grabber and open it again with previous session, you will see different results on these tabs, because they will show only images from the last loaded page in endless page mode. It means that without real changing pages by user, page counter changes by it's own in the endless page scroll process, so as result user will be very confused, why repeating his search gives him different results from previous search. Moreover, it's very frustrating - to change page counter to start position after every time when you use endless page mode.

The core feature of the whole endless page mode is the ability to start from N page and show much more results then usual by loading images from the next pages if necessary, but the start point is still N page, and after repeating search should be opened N page and nothing else! That's the idea of the whole mode.

I see two solutions here.   
1. Easyest way: Just not increase page counter when loading results in endless page mode at all.
2. More clever way: Add check of using endless page mode, and if tab in endless page mode, then increase page counter as usual(in current version) and show it in GUI as usual, but not save this number in tab settings, so any tab reload will repeat original search request, and in the process of using endless page mode user also will see how many pages he loaded already. So this way is more convinient for users I guess, but a bit less easy to implement.

**Anyway, I hope that I'm not too late and you will include fix of this problem in 5.5.0.
Also I want to ask you update translations in 5.5.0, so I could update them too.**

**Comment by Bionus** [comment]
But let's say some user is browsing using endless page mode.
Now, in the middle of browsing he has to go for whatever reason, so he closes Grabber.
When he restarts the program with your solution, he will be back to page 1. What if he wants to resume his browsing where he left it?

**Comment by MasterPetrik** [comment]
It's the endless page mode, it works exactly the same as it works on boorus in browser - reload page - start from the beginning. Guys, which prefers to use this mode instead of pages are fully understand that in any case they will lose all progress, and that's how this mode should work, that's how users EXPECT it will work - the same way how it works everywhere. And very bad idea to change somehting in this way of work as you did. Because if users want to stop on the сertain page, they will use pages mode for that. That's how it always worked. 

And even in this situation, if you will implement my second solution, users will see last page counter and may set it manually after reload of the tab.

**Comment by MasterPetrik** [comment]
BTW, I already have at least 3 suggestions to the next patch, will post them later, one about order of the sources in settings, second is about adding more info in preview window and the third is a deep reworking of tabs functional.
