### ISSUE TITLE
Question regarding extensions

### ISSUE THREAD

**Issue by ajhauk** [Bionus/imgbrd-grabber#1035]
### Please provide any additional information below

Hello,

I'm not sure if I'm missing something, but I couldn't find an answer to my question.  Is it possible to filter extensions so that the program only downloads files with a specific file type? For example "gif" from site x.

Help is appreciated.

**Comment by Bionus** [comment]
Not built-in, but most sources use the "animated", "animated_gif", oir "gif" tags for those.
Some also support the "filetype:gif" metatag.

**Comment by ajhauk** [comment]
Thanks for your answer. I tried that before with "webm", which resulted in about 1000 files. Problem is not all webms are tagged as webm on the respective sites. So there are a whole bunch of files you just miss, which is unfortunate. Would you consider adding a function to filter out certain extensions in the future?

**Comment by Bionus** [comment]
I could add a feature in the post-filtering to filter by extension, but not only is that not always possible (if Grabber does not know a file's extension yet), that would also be inefficient for huge amount of results: would you load all pages of the website and then filter out 99.9% of the results to only get webm for example? That would load a lot of stuff and be pretty slow for only a bunch of images.

**Comment by ajhauk** [comment]
Well I can only speak for myself of course, but I would definitely use it, even if it's slow. It'd be a huge help.
