### ISSUE TITLE
Derpibooru characters

### ISSUE THREAD

**Issue by zoameldar** [Bionus/imgbrd-grabber#1040]
First. Thank you for this awesome project. 
Second. It seems rating and characters doesn't work on derpibooru. Only artist tag. Will it be included in the future?

### What steps will reproduce the problem?
Try to use %character% or just click on picture. Only artist tag is different color. 

### What is the expected behavior? What do you get instead?
Character name and rating download correctly after using %character% and %rating%. I get whatever I put in "Options>Save" in my case - unknown.

### How often does this problem occur? On which sources?
all the time. on derpibooru and trixiebooru.

### What version of the program are you using? On what operating system?
5.5.0

### Please provide any additional information below
This program is awesome.

**Comment by Bionus** [comment]
Indeed, I can reproduce.

It actually seems to have been reported months ago without me taking action on it (oops) in issue #699.
I'll take a look and update the tag parser to take those into account.

> This program is awesome.

Thanks! :smile:

**Comment by zoameldar** [comment]
Thank you.
