### ISSUE TITLE
Mark as Viewed doesn't work correctly for Sankaku Channel

### ISSUE THREAD

**Issue by nuerfdeis** [Bionus/imgbrd-grabber#1041]
### What steps will reproduce the problem?
Navigate to the favorites tag
Select chan.sankakucomplex.com as a source
Select an author with new images
Mark all images as viewed
Refresh the same author
### What is the expected behavior? What do you get instead?
Marked images are supposed to disappear. The images stay instead.
Mark as Viewed works for Danbooru but not Sankaku.

### How often does this problem occur? On which sources?
Every time. 
Source is chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
version 5.5.0
Windows 7

### Please provide any additional information below
The log showed errors parsing XML and JSON files:
[20:06:45.749][Warning] [chan.sankakucomplex.com] Error parsing XML file: tag mismatch (6 - 7).
[20:06:45.749][Warning] [chan.sankakucomplex.com] Loading using Xml failed. Retry using Json.
[20:06:45.796][Warning] [chan.sankakucomplex.com] Error parsing JSON file: " 
403 Forbidden 
nginx "
[20:06:45.811][Warning] [chan.sankakucomplex.com] Loading using Json failed. Retry using Html.

**Comment by MasterPetrik** [comment]
#997
See the issue mentioned above for more info, **Sankaku is blocking downloaders.**
So it's pretty normal that it's not work for you.

**Comment by Bionus** [comment]
Yes, that's because their API being broken (as linked by the previous comment), Grabber fallbacks on the HTML source.

And since the HTML source does not provide any date information, which is required for the "mark as viewed" feature. See #1058 for the suggestion to use IDs instead of dates for favorites (which would fix this issue).
