### ISSUE TITLE
Gelbooru images not loading.

### ISSUE THREAD

**Issue by Impervox** [Bionus/imgbrd-grabber#1042]
### What steps will reproduce the problem?
Opening any image with gelbooru source.

### What is the expected behavior? What do you get instead?
It shows me a pixelated version and loads the image.
It shows me a pixelated version and loads forever.

### How often does this problem occur? On which sources?
Everytime.
Gelbooru.

### What version of the program are you using? On what operating system?
Version 5.5.0
Windows 10

### Please provide any additional information below
I was using version 5.1.x but updated because gelbooru's images suddenly all ended with .mp4 format.
After updating this problem started.
I tried with sankakucomplex source which works fine but when I use gelbooru I get this:
![capture2](https://user-images.githubusercontent.com/10777765/29662568-123980a4-88c8-11e7-9373-e190a2555a6f.PNG)

**Comment by Bionus** [comment]
Is there anything showing up in the log?
Are you using any special configuration on your Gelbooru source? (are you logged in, etc.)

**Comment by VulpesJack** [comment]
I'm getting the same issue, nothing special in configs, just tags on the blacklist

![vrekuw](https://user-images.githubusercontent.com/24865767/29691113-b8b3bf7c-8921-11e7-8680-aa8c9a9570fb.png)

**Comment by soudesune** [comment]
Having the same issue since yesterday. I have no problems reaching gelbooru itself through browser, so it's not a server/connection issue. I suppose this simg4 prefix in the Grabber links doesn't work anymore.

![grabber logs](https://user-images.githubusercontent.com/31344395/29710714-2d6fe3c2-899a-11e7-89c9-f3e6a1700f4e.jpg)

**Comment by Aelphais** [comment]
Found a solution: Go to sources and enable secure (https) for gelbooru. It isn't the simg4 part that is the problem, it's the http part.

**Comment by VulpesJack** [comment]
Yep, that seems to have fixed it

**Comment by soudesune** [comment]
Thanks a lot, dude.
