### ISSUE TITLE
Using %all% as file name is usually too long for Windows, how do I fix it?

### ISSUE THREAD

**Issue by fighuass** [Bionus/imgbrd-grabber#1044]
When I download a pic, and I set %all% %md5%.%ext% as file name, it often gets cut off. Windows probably has a file name limit, how do I bypass it?

**Comment by Bionus** [comment]
There's no way around it. 

Windows has filename limits, so unless you use another file system you won't be able to have filenames longer than 260 or 255 characters.

More details: https://msdn.microsoft.com/en-us/library/aa365247.aspx

**Comment by fighuass** [comment]
I see, that's too bad. Why does this feature exist if it doesn't really work, though?

**Comment by Bionus** [comment]
The feature works on other filesystems. Also, you can still store these tags in a database or an external text file.

The software provides the information, it's up to the user to see how he wants to present/use it.
