### ISSUE TITLE
Tag loader first impression

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1046]
A new tool has been added, but with no info what it do and when you need to use it. 
So user need to figure out it manually. 

## Sources

In current state, most of the sources not can be used with this tool:
almost 60% sources returns this message:

![2017-08-25_075523 win7 mastercore](https://user-images.githubusercontent.com/22294259/29821702-8c2e26f0-8cd1-11e7-8805-7652cc233b4e.png)

another 30% sources returns this result:

![2017-08-25_075610 win7 mastercore](https://user-images.githubusercontent.com/22294259/29821796-dbc5fbf2-8cd1-11e7-82d9-01c46fa0e26d.png)

and only 10% sources tells that the tags has been loaded:

![2017-08-26_084413 win7 mastercore](https://user-images.githubusercontent.com/22294259/29821824-f3b00b36-8cd1-11e7-9086-3eba7fbaeec2.png)

## Visualisation

 In process of downloading tags there are no visual signs of progress. 
Loading may take a lot of time.
But without any counter loading looks endless, and user may think that tags loader is broken.

![2017-08-26_082510 win7 mastercore](https://user-images.githubusercontent.com/22294259/29821914-4a6dacbc-8cd2-11e7-8cc9-740eb27cfd69.png)

## So there are some suggestion for you:
1. Add info about this tool in grabber(in help, or directly in tag loader window) to inform users when and how to use it.
2. Add loaded tags counter or something like that.

**Comment by Bionus** [comment]
You can find some basic information regarding this feature in issue #1033 and #995. It's a beta feature for now. I actually only made it for my own use why testing out the tag database feature and see whether it works or not (it does). 

1. Sure, I could create a wiki page and link it on the window. But that's the same for all tools, isn't it?
2. That's technically impossible for most sources, which is why it's like this for now. I can add a counter but no "max" so the bar will never "fill".

**Comment by MasterPetrik** [comment]
New impressions:
1. Window header is wrong
2. After search ends with any result, most of the window's interface moves up and overlayes test.
3. Had no success with adding tags from any source(0 tags loaded), maybe only updating Grabber.exe is not enough and I need to update sone other files from dev branch, or maybe it's hust don't work.
 
![2017-09-21_054622 win7 mastercore](https://user-images.githubusercontent.com/22294259/30676877-1f0866b8-9e91-11e7-8e54-3c0eadece4fc.png)

**Comment by MasterPetrik** [comment]
Btw, can you make tag loading process to not disable main grabber window? 
Because it may need a bunch of time to download all tags(couple of hours), and all this time you can't use Grabber. This is not good, I guess.

**Comment by Bionus** [comment]
> Btw, can you make tag loading process to not disable main grabber window? Because it may need a bunch of time to download all tags(couple of hours), and all this time you can't use Grabber. This is not good, I guess.

AFAIK you can still use the main window, this dialog is not modal (it stays on top for some reason though).

> Also I'm very interested, where tag loader downloads all those tags, I thied to figure it out by myself, but failed, so please ansver.

In the `tags.db` or `tags.txt` file in the settings directory (`sites/source/site.com/tags.db`). The `.db` file is a simple SQLite database, if you want to see the contents you'll need a SQLite viewer, for example http://sqlitebrowser.org/.

> Also in current state you CAN'T check, do you downloaded tags or not, I mean, after downloading tags from some site, you can't see any sigh that now those tags are downloaded. Not a single clue. That's not good.

You're not really supposed to check it, just like you can't check the contents of the MD5 list. When officially used, Grabber will have pre-intalled tag lists (or force a tag update during install), and this tool only used for troubleshooting.

For now, it's only here for debug, as the feature is not fully developed yet (issue #1033).

**Comment by MasterPetrik** [comment]
> AFAIK you can still use the main window, this dialog is not modal (it stays on top for some reason though).

Ooops... you a right, Indeed I can use grabber. Then if it stays on top anyway, you can add a minimize button to addition or instead of currently useless "?" button.
![2017-09-22_165615 win7 mastercore](https://user-images.githubusercontent.com/22294259/30747828-1409b34e-9fb7-11e7-85db-0be42c3043a3.png)

> You're not really supposed to check it, just like you can't check the contents of the MD5 list. When officially used, Grabber will have pre-intalled tag lists (or force a tag update during install), and this tool only used for troubleshooting.

I understand that. But you anyway could make following in tag loader:
When you selecting certain source in the list, tag lader show you current downloaded tag value for this source. I think it will be very informative and not very hard to implement.

**Comment by MasterPetrik** [comment]
Thanks for the improovement of the tag loader
It became much more user-friendly!
Unfortunately now it crashes Grabber in 100% cases instead of working :laughing: 
but it's not so important I guess)))

![2017-09-24_011250 win7 mastercore](https://user-images.githubusercontent.com/22294259/30777618-6d87d1a6-a0c7-11e7-92a1-55371c6ec689.png)

**Comment by MasterPetrik** [comment]
fixed indeed

**Comment by MasterPetrik** [comment]
but the text overlaying tiny problem still take place, but I guess I will not reopen this issue for that.
![image](https://user-images.githubusercontent.com/22294259/30787236-d5c9bb60-a18c-11e7-93e5-ddec7375f59d.png)

**Comment by BarryMode** [comment]
@Bionus, do you mind if I ask for a better understanding of the tag loader? This seems like a really valuable tool, and I'm currently trying it out.

My first question: where are the tags stored? I don't want to accidentally delete them when building new versions of Grabber. If I'm seeing this correctly, it appears to be writing files in the cache directory.

Secondly, is this offline tag database able to match up MD5 with tags? If so, that's amazing which probably makes my process unnecessary.

For my own gallery, I currently download files and then have a separate script generated that will tag the files with all of the tags. This works well, but the tag loader makes me want to try something new. Not sure how I completely missed this feature until now.

**Comment by BarryMode** [comment]
This seems like a cool feature. What does the list of tags in the txt actually do? I mean, I can see that it says it can load tags even if the API fails. Does that just mean that the tags.txt file serves as a backup?

**Comment by BarryMode** [comment]
@Bionus Thanks for answering those. For the most part, I had removed what I had said because I found some of the answers in the comments above and as I downloaded the tags, I learned more about how it was working and what it was doing. Thanks for the info.
