### ISSUE TITLE
Grabber can't handle with restoring many tabs

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1050]
In process of common restoring last sesson with many tabs grabber ends up emergency closed by OS or grabber itself(dunno) with the same typical Windows error message("program has stopped working") every time. But it not crashes! Nothing special in the log, and no crash report window. 

![image](https://user-images.githubusercontent.com/22294259/29929782-1aed9f16-8e75-11e7-8bd0-318e65fa55ab.png)

Same behavior in all Grabber versions, with increasing number of opened tabs increases frequensy of such errors when restore last session. In current state with this tabs list frequensy almost 100%.

Obviously error connected with processor and memory consumption by grabber in process of restoring tabs. 
Maybe you can make an option in settings to not process all tabs in one time while start Grabber( process them one by one also with little delay, or just process only selected tab, and not process other tabs at the start at all? 

### Here is the tabs list:

[tabs.txt](https://github.com/Bionus/imgbrd-grabber/files/1267491/tabs.txt)

It's very important problem for me!

**Comment by MasterPetrik** [comment]
I launched Grabber after all. 
But only because I cut off the internet while it started. :( 
So it's, as I expected, the resources cconsumption problem.

**Comment by MrCrackR** [comment]
So only loading content of tabs that are active would solve it? The same way firefox does it?

**Comment by MasterPetrik** [comment]
> So only loading content of tabs that are active would solve it just like firefox does it?

Well, that's the one of two ways that I suggested.

As a 1928 tabs in a browser user, I can say that firefox can't handle with big amount of tabs, It just loads them one by one, like grabber, and then you found yourself with 100% memory usage and crash.
Chrome-based browsers can easyly handle even 1928 tabs, because of loading only tiny amount of tabs when restoring session. Also they cache not used tabs to reduce memory consumption while it working, so you can easyly use all 1928 tabs without problems.
BTW, IE even can't handle with 40 tabs, lol
For Firefox it's around 200-400 tabs
Before any questions, I have 16GB RAM + 54GB virtual RAM from HDD(special for browsers)

**Comment by Bionus** [comment]
> Obviously error connected with processor and memory consumption by grabber in process of restoring tabs.
> Maybe you can make an option in settings to not process all tabs in one time while start Grabber( process them one by one also with little delay, or just process only selected tab, and not process other tabs at the start at all?

Simply processing them more slowly would still cause the error if it's RAM-related. It would simply crash later on at a random time. The only possible solution of this problem is your second solution, not loading tabs until they are shown.

> I can say that firefox can't handle with big amount of tabs, It just loads them one by one, like grabber, and then you found yourself with 100% memory usage and crash

Which FF version do you use? Firefox 55 greatly improved memory usage and startup times when having lots of tabs, see here: https://metafluff.com/2017/07/21/i-am-a-tab-hoarder/.

<img width="50%" alt="startup" src="https://user-images.githubusercontent.com/882719/30178078-0944f32a-9408-11e7-9d08-d70be5177eb3.png"><img width="50%" alt="memory" src="https://user-images.githubusercontent.com/882719/30178072-05b81d5e-9408-11e7-81b3-223440df7c0f.png">

**Comment by MasterPetrik** [comment]
> Simply processing them more slowly would still cause the error if it's RAM-related. It would simply crash later on at a random time. The only possible solution of this problem is your second solution, not loading tabs until they are shown.

I'm almost sure that it's a not RAM, but processing problem, because when I manually open all these tabs - everything works fine, but if I will close Grabber and open it again, then after some seconds after starting of restoring tabs it will crash, even if it worked even with much more items(many tabs were endless-page scrolled for a many pages)  just a minute ago. So obviously it's a problem of processing all tabs in one time. 

Also you can use my tabs.txt from this topic to self test this tabs set behavior.

Any of both variants of solving is fine for me, implementing both maybe?


> Which FF version do you use? Firefox 55 greatly improved memory usage and startup times

Yes, last time I used Firefox half year ago, so my info can probably outdated) Good to hear that they are improved that part.

**Comment by MasterPetrik** [comment]
@Bionus Please, solve this problem in next nightly, It's too painfull to shut down the internet every time when I start Grabber. :sob:  even little checkbox in settings that forbid to load all tabs exept current tab when grabber starts will be enough, please, it's very important problem for me.

**Comment by Bionus** [comment]
I just pushed a few things, so it should have arrived in the current nightly.

The startup time is still long, but on my computer, even on a debug build, it ended up loading successfully after ~40s. I'm working on some other improvements to reduce the loading time.

**Comment by MasterPetrik** [comment]
Thanks, it works very good for me!
