### ISSUE TITLE
how to only download sample image?

### ISSUE THREAD

**Issue by maxman2103** [Bionus/imgbrd-grabber#1052]
### What steps will reproduce the problem?
how to only download sample image..there is no option to download sampl image only...i tried by going to tools/option/save and disabled "download original image" but it still does not work

i use gelbooru

**Comment by MasterPetrik** [comment]
looks the same issue with https://github.com/Bionus/imgbrd-grabber/issues/949
That's the current answer from dev:
![image](https://user-images.githubusercontent.com/22294259/29998739-77b85566-903b-11e7-823f-da14a1d975fe.png)

**Comment by Bionus** [comment]
> i tried by going to tools/option/save and disabled "download original image" but it still does not work

There's indeed a bug causing original images to still be downloaded even though this checkbox is unchecked. It will be fixed in the next version (for boorus who provide sample urls).

**Comment by MasterPetrik** [comment]
So downloading thumbnails is still impossible?

**Comment by Bionus** [comment]
Yes, because that was not meant in the program in the first place, so it's more than this simple bugfix. While not that complicated, downloading thumbnails would require adding a new column to the download tab tables to select which size to download ("original", "sample", "thumbnail"). I'll update #949 when done. :smile:

**Comment by MasterPetrik** [comment]
> I'll update #949 when done. :smile:

Well, that feature is not so important or needed, better to focus on more important issues first

**Comment by maxman2103** [comment]
I know its not that important...but it is important...so...next update would be nice..but no hurry...take your time

**Comment by MasterPetrik** [comment]
You misunderstood me, dude. Your issue with sample images already solved and fix will be included in the next release. You can even use nightly versin, where it's already implemented.

And I Replied to Bionus about ANOTHER issue about thumbnails, so don't worry about samples.
