### ISSUE TITLE
Switching tabs hotkeys suggestion

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1055]
Grabber, as a kind of booru-browser, have tabs system.
But I figured out that standard way of switching tabs via "Ctrl + Page Up" or "Ctrl + Page Down" isn't working here. So it would be very useful to add these hotkeys to Grabber.

All web browsers and many other tab-related software uses these hotkeys.

**Comment by Bionus** [comment]
:+1:

* `Ctrl + Page Up`: previous tab
* `Ctrl + Page Down`: next tab

**Comment by MasterPetrik** [comment]
That's right.
