### ISSUE TITLE
Conditional filenaming improvement suggestion

### ISSUE THREAD

**Issue by piotrekhenry** [Bionus/imgbrd-grabber#1056]
### What steps will reproduce the problem?
Not a problem.

### What is the expected behavior? What do you get instead?
After analysing the manual page concerning filename formatting and conditional filenaming I understood (and tested) that currently it is only possible to use conditions based on existence (or inexistence) of a tag which (unfortunately) could not allow me to achieve the desired filename template.
What I wanted to do was utilize the %width% and %height% tags integer values to make conditional filenames based on "if the pictures width is greater than 1919 AND the pictures height is greater than 1079 THEN use a filename template containing "HD" ELSE use default filename" logic in order to split HD and above images from lower resolution images. Unfortunately I don't believe this can be achieved with currently implemented conditional logic (at least not without using the javascript file naming option).
Considering there are multiple tags that contain quantifiable numerical values - it could be a great help with image management.

### How often does this problem occur? On which sources?
Not a problem. Sources independent.

### What version of the program are you using? On what operating system?
Windows 7 / Grabber 5.5.0

### Please provide any additional information below
After searching for images containing : the desired tags along with width:1280.. height:720.. (to search only for 720p images and higher resolution I wanted to divide the images into 2 groups based on their resolution.
Example of desired result:
Default filename pattern:
%websitename%\%rating%\%width%x%height% %all% %md5%.%ext%
Conditional logic:
"if the image's resolution is greater or equal 1920x1080"
like: (%width%>1019 %height%>1079 - currently does not work as desired)
Conditional filename:
%websitename%\%rating%\HD\%width%x%height% %all% %md5%.%ext%

**Comment by Bionus** [comment]
So the suggestion would be to implement actual operations in the "Condition" field of the conditional filename? And, to an extent, to filename conditionals (`<` / `>`) for consistency.

![image](https://user-images.githubusercontent.com/882719/30163813-aabeb55c-93da-11e7-9aa1-dc43e46a0b3d.png)

### Current
* `"tag"` -> tag is present in the image
* `%token%` -> token is not empty

### Proposal
Use Javascript in the condition field.
* `"tag"` -> tag is present in the image (kept for backwards compatibility)
* `%token%` -> token is not empty (kept for backwards compatibility)
* `tags.contains("tag")` -> tag is present in the image (new syntax, more explicit)
* `token != ""` -> token is not empty (new syntax, more explicit)
* `token != "" || token2 != ""` -> multiple conditions, "or" operator
* `width > 1920 && height > 1080` -> multiple conditions, "and" operator

Would that be a good solution?

**Comment by Bionus** [comment]
Maybe you can currently already achieve a similar effect using Javascript filenames. Simply as a workaround as it's not as readable as non-Javascript filenames though.

Something like this should produce the correct filename:

```javascript
if (width > 1920 && height > 1080) {
    return websitename + rating + width + 'x' + height + ' ' + all + ' ' + md5 + '.' + ext;
}
return websitename + rating +'\HD' + width + 'x' + height + ' ' + all + ' ' + md5 + '.' + ext;
```

_Note: I didn't try the filename, it may require small modifications._

**Comment by piotrekhenry** [comment]
Than you for your reply.
Unfortunately the javascript provided failed to name anything (both "as is" and with slight modifications).
I guess you could use a basic/advanced conditionals switch to preserve current conditional filenames for backwards compatibility and use advanced for the new suggested stuff.
