### ISSUE TITLE
Chan Sankaku Complex images giving an "Expired Link - Please reload the site" Image instead of original

### ISSUE THREAD

**Issue by Drakonas** [Bionus/imgbrd-grabber#1057]
### What steps will reproduce the problem?
Load any Chan Sankaku Complex image from any search.

I am using a hash key to login with Grabber, and I am unsure if that is required to reproduce. It tests successful.

### What is the expected behavior? What do you get instead?
I expect to see the image from the thumbnail. Instead I get an image with the Sankaku Complex logo that states "Expired Link - Please reload the site".

### How often does this problem occur? On which sources?
This happens on every image from Chan Sankaku Complex.

### What version of the program are you using? On what operating system?
Grabber 5.5.0 on Windows 10 Creator's Update.

**Comment by ashkentou** [comment]
same issue

**Comment by GalangKaluluwa** [comment]
Really hope someone finds a fix on this

**Comment by MasterPetrik** [comment]
Go to https://github.com/Bionus/imgbrd-grabber/issues/997#issuecomment-325124638 issue and read carefully what's written there.

**Comment by Drakonas** [comment]
I apologize. I wish I would have known about this ticket. Damn. That's unfortunate. Well, I guess it's just a waiting game then. Has anyone had success editing the limit parameter in the model.xml?

**Comment by Drakonas** [comment]
MasterPetrik: I apologize. I wish I would have known about this ticket. Damn. That's unfortunate. Well, I guess it's just a waiting game then. Has anyone had success editing the limit parameter in the model.xml?

**Comment by Bionus** [comment]
I'll close this ticket for now, as it seems to be another blocking method from Sankaku Complex, and I'd rather have a single "main" issue about it.

> I apologize. I wish I would have known about this ticket

Don't worry, it's already on the second page of the issues, so it's not obvious. Unfortunately I can't "pin" an issue in Github.
