### ISSUE TITLE
Program crash when attempting to download

### ISSUE THREAD

**Issue by sbobbo** [Bionus/imgbrd-grabber#1062]
### What steps will reproduce the problem?

Open program, do search for "korra", get all, download.

### What is the expected behavior? What do you get instead?

Download them. It crashes instantly

### How often does this problem occur? On which sources?

Every time. Didn't used to.

### What version of the program are you using? On what operating system?

5.5.0. Windows 10

**Comment by MasterPetrik** [comment]
Without any technical info and detailed information about crash appearance, this crash report is almost useless. 
But it will be more useful if you would provide some more info about crashing conditions and upload 
crash fump file, 
restore.igl file, 
settings.ini file,
tabs.txt file,
and log if you can.

**Comment by Bionus** [comment]
As @MasterPetrik said, I need more information to be able to investigate, as obviously it doesn't crash for everyone. :smile:

You have more details about crash reporting here:
https://github.com/Bionus/imgbrd-grabber/blob/master/CONTRIBUTING.md#reporting-crashes
