### ISSUE TITLE
Only a select few sources will work for me.

### ISSUE THREAD

**Issue by Sollidified** [Bionus/imgbrd-grabber#1063]
### What is the expected behavior? What do you get instead?
I expect images to load, but nothing happens.

### How often does this problem occur? On which sources?
Every time I try to search for images on every source except for hijirebe, konachan, paheal, safebooru, and sonohara.

### What version of the program are you using? On what operating system?
5.5.0 on Windows 10.

I've tried logging into a few of the sources but nothing changes.
Here's a log, if it helps:

[main.txt](https://github.com/Bionus/imgbrd-grabber/files/1289092/main.txt)

**Comment by MasterPetrik** [comment]
As I can see, other sources returns "No valid source of the site returned result." message

**Comment by Sollidified** [comment]
I see that, but I have no idea what's causing it or how it can be fixed.

**Comment by Bionus** [comment]
It seems the common point is that all those sources use HTTPS. Do you have any HTTPS source working or a non-HTTPS source non-working?

**Comment by Sollidified** [comment]
Absolutely nothing works using HTTPS. Every source that I listed above only loads anything when not using HTTPS.

**Comment by Sollidified** [comment]
Seems like I found a fix. On issue [#1034](https://github.com/Bionus/imgbrd-grabber/issues/1034), BAquea's solution worked for me, whatever it did.
