### ISSUE TITLE
SANKAKU COMPLEX??

### ISSUE THREAD

**Issue by maxman2103** [Bionus/imgbrd-grabber#1067]
### What steps will reproduce the problem?

batch download does not work...

### What is the expected behavior? What do you get instead?

when batch downloading

### How often does this problem occur? On which sources?

https://chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
5.5.0

### Please provide any additional information below
plz..fix this problem in the next version or tell me is there any way to download batch from chan.sankaku

**Comment by NavinF** [comment]
Known problem. See the main thread: #997

**Comment by MasterPetrik** [comment]
@Bionus recommend to close this issue due to duplicate of #997

**Comment by BarryMode** [comment]
It works fine. The host is just refusing the program.
