### ISSUE TITLE
Bug when redownloading a previously downloaded image

### ISSUE THREAD

**Issue by Aaeeschylus** [Bionus/imgbrd-grabber#1068]
![grabber_2017-09-12_01-09-43](https://user-images.githubusercontent.com/7753205/30304235-9e402282-97ab-11e7-85dd-37b5f2101c9a.png)
### What steps will reproduce the problem?
- Have copy already downloaded enabled
- download some images from a tag (for example, cosplay)
- cancel the download after a bunch have been downloaded 
- restart the download

### What is the expected behavior? What do you get instead?
expected - for the downloader to skip over the already downloaded images (or copy if using a different tag)
instead - downloader freezes on 100%, doesnt complete or move on, and the download speed slowly drops to zero. The downloads never continue until you manually skip, meaning if I were download a lot of images, I would have to sit there and manually click skip every time it happened.

### How often does this problem occur? On which sources?
almost all the time there is a previously downloaded image. the sources are danbooru and gelbooru

### What version of the program are you using? On what operating system?
Im not sure what version it is, but it doesnt say there is an update when updating, so assuming latest. using windows 10

### Please provide any additional information below
here is an example:
[https://puu.sh/xxaGQ/3d6912a289.png](url)

EDIT: Attached the image file instead of the link because it doesnt seem to work

**Comment by MasterPetrik** [comment]
Nope, this is not connected to redownloading images. 
This is Gelbooru only problem. 
Enable HTTPS in gelbooru settings to solve this problem.
more info in https://github.com/Bionus/imgbrd-grabber/issues/1042 issue.

@Bionus , meh, another buplicate issue, https://github.com/Bionus/imgbrd-grabber/issues/1042 in this time. Recommend to close.
