### ISSUE TITLE
Restoring 'Favorites' and 'Kept for later' after a crash

### ISSUE THREAD

**Issue by Dexyne** [Bionus/imgbrd-grabber#1069]
Hello there,

I got some crashes using the program. It's not a big deal actually, but I was wondering if it was possible to restore the recently added favorites and kept for later tags?

Because losing the few of them that I just added is more annoying that the crash itself! xD

So is there something I can do to restore them or do you think it should be possible to upgrade the program to avoid their lost?

Regards.

**Comment by Bionus** [comment]
Indeed, the favorites and "kept for later" tags should be synced every time a new tag is added, instead of only being saved when the program closes to prevent this issue. :smile:

**Comment by Dexyne** [comment]
So it's really how it works? I was not sure if it was really the case that it was save only during the exit of the program. But yeah syncing it when added will be more efficient! 😄
