### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by MrCrackR** [Bionus/imgbrd-grabber#1070]
### What steps will reproduce the problem?
Use the newest version of Raspbian (Stretch), then clone and build:
```
git clone https://github.com/Bionus/imgbrd-grabber.git --single-branch -b develop
cd imgbrd-grabber
./build
```
### What is the expected behavior? What do you get instead?
Successful compilation, but get error
> error: call of overloaded ‘abs(float)’ is ambiguous

### How often does this problem occur? On which sources?
Always. Error occurs on the main branch as well as the develop branch.

### What version of the program are you using? On what operating system?
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1)
QMake version 3.0
Qt version 5.7.1
cmake version 3.7.2
Raspbian (Stretch)

### Please provide any additional information below
![abs](https://user-images.githubusercontent.com/1807632/30299394-c2e30a16-974f-11e7-83ca-7bdaba61f4ff.png)
With some minor adjustments, compilation used to work on Raspbian Jessie.

**Comment by Bionus** [comment]
Oh, it seems to simply be a call to `abs()` that should have been `fabs()`.
Does replacing the function name fix the issue? (commit d70ce47a4d1180421f49d84ea80ef571ac512f38)

> With some minor adjustments, compilation used to work on Raspbian Jessie.

Which minor adjustments were required?

**Comment by MrCrackR** [comment]
> Which minor adjustments were required?
Raspbian Jessie didn't include QtLinguistTools in it's repo, so I had to skip everything related to the languages part in the compilation. Also the **make -j8** didn't work on weak systems like the Raspberry Pi. The best it could still handle was **make -j4**. For some weird reason, this isn't an issue for Raspbian Stretch anymore. It even includes QtLinguistTools.

I just recompiled everything. There is still an issue.
```/mnt/Seagate/imgbrd-grabber/gui/src/ui/QBouton.cpp: In member function ‘void QBouton::scale(const QPixmap&, float)’:
/mnt/Seagate/imgbrd-grabber/gui/src/ui/QBouton.cpp:13:23: error: ‘fabs’ was not declared in this scope
  if (fabs(scale - 1.0f) < 0.001f)
                       ^
make[2]: *** [gui/CMakeFiles/gui.dir/src/ui/QBouton.cpp.o] Fehler 1
```

**Comment by MrCrackR** [comment]
Adding **#include <math.h>** to _/gui/src/ui/QBouton.cpp_ fixed it for me. The Compilation is now working. It's still strange, that it already worked without it for you. The only thing remaining is a deprecation warning, but at least I always tend to ignore these.
![warning](https://user-images.githubusercontent.com/1807632/30619357-3fdf8e9a-9d9f-11e7-8d43-e6aae2e16c7a.png)
