### ISSUE TITLE
Allow comma as a tag separator %all,separator=,%

### ISSUE THREAD

**Issue by BarryMode** [Bionus/imgbrd-grabber#1073]
I was writing a script to apply tags to my downloaded images, and the script requires the tags to be separated by commas. When I did `%all,separator=,%`, it didn't work because it took the comma as a parameter separator rather than my input for the field. I tried cancelling it with a backslash which resulted in the tags being separated by backslashes. I also tried different combinations of using quotes, which led to the tags being separated by quotes xD

I also looked up available metacharacters (ex. \r \n \w \d etc.) hoping there would be something for commas, but there wasn't that I could find.

**Comment by Bionus** [comment]
It's quite surprising this bug never popped up before, given how "basic" is the comma separator. Maybe it can be worked around in the meantime by setting the separator in the options instead, and overriding it in the filename?

**Comment by BarryMode** [comment]
Nice, I didn't even realize there was an option for this. Not sure how I missed it! That worked to just set it here as you said: Options->Save->Filename->Tags separator
