### ISSUE TITLE
Danbooru Rip only pulling in 20 images only

### ISSUE THREAD

**Issue by oristo42** [Bionus/imgbrd-grabber#1076]
What steps will reproduce the problem?

Searching with danbooru as a source. If it matters, I logged in.

What is the expected behavior? What do you get instead?

I should see more than 20 images in the results, but I only get 20 images always. So I only can download 20 images from danbooru

What version of the program are you using? On what operating system?

5.5.0 on Windows 7

**Comment by konecat** [comment]
I've got the same problem and I am on the 4.2.1 (Linux). Which means something in danbooru changed, and it fucked this up.

**Comment by PlekhanovA** [comment]
Same problem here. I'm logged in, I have 5.5.0 on Windows 7. But I can also add that I can change the number of viewing page. So technically I can download all the images but I have to go through every page to add them manually.

**Comment by Kernel-13** [comment]
Same problem here while using 5.5.0 as well (on Win10). But it only happens when searching for 2 or more tags. If it's only one tag there is no problem, but as soon as you add another, it will limit the number of images you can get to 20 (or whatever 'Images per page' you have set up).

**Comment by Bionus** [comment]
You can still override the image count if it's not guessed properly during batch downloads, no? And there's nothing stopping you from using the navigation during browsing (next/previous page).
