### ISSUE TITLE
Files unreadable "We can't open this file."/"this is not a valid bitmap file" chan.sankakucomplex.com

### ISSUE THREAD

**Issue by OrigamiAisaka** [Bionus/imgbrd-grabber#1077]
### What steps will reproduce the problem?
Attempting to download from chan.sankakucomplex.com

### What is the expected behavior? What do you get instead?
All images are saved within the right location but all have a filesize of 154Bytes
Every file is also a .jpg, not sure if that means anything.

### How often does this problem occur? On which sources?
Any time I attempt to download from chan.sankakucomplex.com, may also happen on idol.sankakucomplex.com but haven't checked!

When opened with notepade this is what's displayed.
```html
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### What version of the program are you using? On what operating system?
 Version 5.5.0

**Comment by MasterPetrik** [comment]
Looks like combination of https://github.com/Bionus/imgbrd-grabber/issues/1038 and https://github.com/Bionus/imgbrd-grabber/issues/997 issues, lol

**Comment by Bionus** [comment]
Sankaku has indeed purposedly broken its Grabber integration.
Closing for duplication, see the other issue. :+1:
