### ISSUE TITLE
Loading thumbnails only on 5.5.0 (Fresh install)

### ISSUE THREAD

**Issue by cttf** [Bionus/imgbrd-grabber#1078]
### What steps will reproduce the problem?
With default settings, on any source with any tag using search.

### What is the expected behavior? What do you get instead?
After clicking on thumbnails, images should load the full image, instead the preview shows the thumbnail (low res, pixelated).
Saving the image saves the full resolution image correctly.

### How often does this problem occur? On which sources?
On all sources tested (Danbooru, e621, Gelbooru, Konachan, yande.re)

### What version of the program are you using? On what operating system?
5.5.0, Windows 10 Pro. Version 1511. Without Anniversary or Creators update.

### Please provide any additional information below
This is on a fresh install of the program, not an update.

**Comment by MasterPetrik** [comment]
please, add the log of the programm

**Comment by cttf** [comment]
I figured out what was wrong.
During the initial setup, I set the downloads folder, but at some point the set up of the folder was removed/lost. Once I went back and redid the whole setup process, correctly setting a download folder, everything worked as expected.

May I suggest a warning of some sort for users who accidentally remove the download directory or who don't set it up properly?

**Comment by Bionus** [comment]
What do you mean the download folder? Even if it was removed, it can be changed at the bottom left of the window, or even directly in the settings AFAIK.

![image](https://user-images.githubusercontent.com/882719/30636916-1d22c0cc-9df7-11e7-9905-fd98ca7f5759.png)

Also, by "initial setup", you mean this window?
![image](https://user-images.githubusercontent.com/882719/30636857-e86c7274-9df6-11e7-8acb-f9a626f4fea5.png)

**Comment by cttf** [comment]
Yes, the destination folder. And yes, I also mean that window. 
I did set the destination folder but somehow I must have either pressed ignore by mistake or removed it during the configuration.
