### ISSUE TITLE
Crash after repeating searching many times in short time

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1080]
Used Last Nightly version

1. Use merged mode
2. Do a search request with several sources(10 in my case)
3. Continue to fast pressing "Ok" button to repeat searching several times
4. Get WinCrash 

100% repeatability for me

![2017-09-21_082331 win7 mastercore](https://user-images.githubusercontent.com/22294259/30680740-f8607442-9ea9-11e7-85df-eae4ecf215d6.png)

**Comment by MasterPetrik** [comment]
Looks like the problem is even more bigger. After that type of crash grabber clears last session instead of restore it.

**Comment by MasterPetrik** [comment]
For some reason Grabber rarely crashes the same way by normal repeating search(without click spam).

**Comment by Bionus** [comment]
Yeah, that's because it's caused by a race condition between the previous page loading cancellation and the new search initialization. Some server responses are received in-between, when everything has been cleared but not re-initialized yet.

**Comment by MasterPetrik** [comment]
Looks like it has been fixes in last nightly indeed, thanks
