### ISSUE TITLE
Teach me how to use it for rule34hentai plz

### ISSUE THREAD

**Issue by mike911026** [Bionus/imgbrd-grabber#1083]
Hello there, sorry for interrupting. But I'm new to this kind of thing. I've trying to find a downloader for rule34hentai. But just don't know how to use your grabber or source code stuff. I've read a lot of issue in this grabber. But it none of them actually asks dumb question like mines... I hope u can teach me how to use it and source code. Also about the Shimmie boards and how to use it.

**Comment by Bionus** [comment]
https://github.com/Bionus/imgbrd-grabber/wiki/NewSite#based-on-gelbooru-danbooru-or-shimmie

> 1. Start the program.
> 2. Click on the "Sources" button at the bottom of the window ("Explore" tab).
> 3. Click on the "Add" button at the bottom of the window that just popped up.
> 4. Fill the Url field, and leave "Guess" checked.
> 5. If an error occurs, uncheck "Guess", and choose an imageboard in the list.

Note that Grabber should recognize this source as a Shimmie board automatically.

**Comment by mike911026** [comment]
Thx for the help just a few more question. 1. What is source code used for?? 2. When I'm searching for the image in rule34hentai.net It will tell me to specify the file name in order to download. But what is download isn't image set. It just downloads a single file and for some reason, it will skip a lot of images.

**Comment by Bionus** [comment]
> What is source code used for??

You don't need the source code.

> When I'm searching for the image in rule34hentai.net It will tell me to specify the file name in order to download. But what is download isn't image set. It just downloads a single file and for some reason, it will skip a lot of images. Also, it said that my filename doesn't end by an extension, symbolized by %ext%! You may not able to open saved files

Then why not do as the program says and set the destination folder and filename? Else it won't work.

You have more information on the "Getting Started" wiki page/tutorial:
https://github.com/Bionus/imgbrd-grabber/wiki/GettingStarted#usage

**Comment by MasterPetrik** [comment]
Btw, about questions...
@Bionus , I know that this question is very stupid, but... where I can set Favourites folder?
I remember that I was set it one day, but I tried to find this setting today and failed

**Comment by Bionus** [comment]
> @Bionus , I know that this question is very stupid, but... where I can set Favourites folder?
> I remember that I was set it one day, but I tried to find this setting today and failed

The favorites folder location can't be changed (that was never possible, actually), and will always be in the Grabber settings directory (`C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\favorites`).

**Comment by Bionus** [comment]
Oh maybe you meant the favorites when saving images.
In that case, it's here:

![image](https://user-images.githubusercontent.com/882719/30775474-96a98954-a094-11e7-90fa-9835b775c603.png)

**Comment by MasterPetrik** [comment]
Indeen, looks like I'm blind, thanks)

**Comment by MasterPetrik** [comment]
> Then why not do as the program says and set the destination folder and filename? **Else it won't work.**

Only I see a problem there? Maybe better to set some default values for those fields?

**Comment by Bionus** [comment]
Not really.

For the folder, people who didn't set it before (pretty much nobody, as the program will tell you multiple times) would just ask "where are my files?" instead. And I personally wouldn't want gigabytes of files saved in some random location on my computer (which would likely be "Downloads/Grabber").

For the filename, the default value would be `%md5%.%ext%` (the minimal filename), but people would start downloading with this, then realize they want something more advanced, and either delete everything or need to re-tag all their files. Forcing them to set a value beforehand will have them decide how they want their files saved from the get go.
