### ISSUE TITLE
Suggestion - New icon

### ISSUE THREAD

**Issue by Zekken01** [Bionus/imgbrd-grabber#1084]
I wanted to suggest getting a new icon that is anime related or something like a downloading icon.

**Comment by MasterPetrik** [comment]
You are so original) 
It's very obvious and old suggestion
Didn't we already duscussed about it in https://github.com/Bionus/imgbrd-grabber/issues/859 issue?

![2017-09-24_012134 win7 mastercore](https://user-images.githubusercontent.com/22294259/30777608-fc458a06-a0c6-11e7-9c5a-6b44528555e0.png)

**Comment by brodycas3** [comment]
oh sorry, I looked to see and couldn't find anything. I also forgot since it's been a while.

**Comment by Bionus** [comment]
Well it's always good to have a separate issue to track the progress of single suggestions. :smile:

Does anyone has any concrete suggestions of logos?

**Comment by brodycas3** [comment]
Well, I was thinking that we could possibly have something anime related? I'm not a graphics designer so idk. I was thinking that a 4chan post or something for suggestions would be good.

**Comment by MasterPetrik** [comment]
Try to imagine, how good recognizable will be anime image in 16x16 size) 
And, as icon it should have a well-visible on the any background border.
So most of anime-related images doesn't fits in those contitions.

**Comment by brodycas3** [comment]
I said anime related. it doesn't have to be an anime girl or some shit.
Just something so that people will associate grabber with what it's meant
for.

**Comment by MasterPetrik** [comment]
Meh, ansvering me via email is a bad idea, I'm editing messages many times after posting them, but you don't see those when you ansvering via email(

**Comment by brodycas3** [comment]
I just responded then because that's the tab I had open.

**Comment by Bionus** [comment]
Let's keep the discussion friendly please :smile:

As for the image size, it's not always 16x16. If it is for the top left icon in the window bar, or if you use the "list view" in Windows explorer, but in other places, it's more often 64x64 or 48x48. It will also be used in the homepage, which is also a big part of the identity of the program, where the icon is much bigger, going above 128x128.

Also, those icons can change depending on their size, so the exact design can differ slightly between the very small 16x16 and the bigger ones, as indeed it's harder to fit stuff in it.
