### ISSUE TITLE
Very slow download speeds of 20B/s or less and log has massive spam of image not found

### ISSUE THREAD

**Issue by Chrysphylax** [Bionus/imgbrd-grabber#1086]
### What steps will reproduce the problem?
I'm not too sure I just installed the program and opened it

### What is the expected behavior? What do you get instead?
Expected 1Mb/s+ download speed but getting 20B/s instead

### How often does this problem occur? On which sources?
on chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
5.50 Windows 10

### Please provide any additional information below
my log: https://puu.sh/xHrEq/e19bcc4ec2.png
slow download speed: https://puu.sh/xHrJr/73e7381d2c.png

### EDIT:
I found out that the url of the images the grabber is trying to download from is wrong. If it helps, this is the url that the grabber is using: 

https://cs.sankakucomplex.com/89/2c/892c2dcfda3db5b117f11c57130efc16.jpg

This is the one that works:

https://c.sankakucomplex.com/sample/89/2c/sample-892c2dcfda3db5b117f11c57130efc16.jpg?e=1506312410&m=d8ISnr02_et1Hstd87BDZA

**Comment by MasterPetrik** [comment]
First of all, read this - https://github.com/Bionus/imgbrd-grabber/issues/997
Sankaku is currently not supported in grabber due to their new API

**Comment by Bionus** [comment]
Closing for duplication.

However, it seems Grabber really needs some error detection to prevent spamming servers. Follup in #1097.
