### ISSUE TITLE
Two issues with batch downloading

### ISSUE THREAD

**Issue by githubsmells** [Bionus/imgbrd-grabber#1087]
I was downloading from Gelbooru with version 5.5.0 (windows) when I realized that I wasn't receiving all my images. While the image downloader was progressing, only about a third of the images it said it had downloaded were actually in the folder.
I observed the folder while it was downloading, and 0kb placeholder images would appear for a few seconds, then vanish, over and over.
Then I attempted to download the images using the "get page" button instead of "get all", but I got the same result.
I turned off the program and started it again, downloading the same set of images, again with "get all". But this time I didn't even get to download any images. Instead, it kept downloading pages over and over. It would download page 22/24, then page 23/24, then page 24/24, then page 1/24 and run through the whole 24 again. It looped at least five times like this before I shut down the program.
I have since uninstalled, and reinstalled version 5.4.2 (windows) which is running fine without these issues.

Thank you for your time.

**Comment by Bionus** [comment]
Hello, sorry for the late answer!
Your issue totally passed under my radar.

Could you provide the log? From what you say, the cause of the problem should be easily visible there, so I'll be able to investigate in more detail and hopefully push a fix. :smile:
