### ISSUE TITLE
Sankaku

### ISSUE THREAD

**Issue by WilluG** [Bionus/imgbrd-grabber#1090]
### What steps will reproduce the problem?

clicking images

### What is the expected behavior? What do you get instead?

image not found

### How often does this problem occur? On which sources?

on sankaku all the time

### What version of the program are you using? On what operating system?
latest ver on win7

### Please provide any additional information below

it could be bc the images md5 change constantly now? idk im not the pro here, but this means we cant use grabber anymore to get sankaku right :/

**Comment by Bionus** [comment]
See issue #997 :smile:
