### ISSUE TITLE
Crush when click on Sources!

### ISSUE THREAD

**Issue by jamedom** [Bionus/imgbrd-grabber#1092]

**Comment by MasterPetrik** [comment]
such lazy crashreports can be easily sent to trash can

**Comment by Bionus** [comment]
I will need the log, the crash dump, as well as your various `sites.txt` to investigate.

**Comment by Bionus** [comment]
Closing for lack of update after one month.
Feel free to provide more information if you want to re-open the issue (notably your `sites.txt` files).
