### ISSUE TITLE
Custom tokens aren't being saved properly.

### ISSUE THREAD

**Issue by SwordfishBooks** [Bionus/imgbrd-grabber#1093]
### What steps will reproduce the problem?
1. In Options>Save>Custom token: Click "Add a custom token"
2. In the name field enter "test" (without the quotation marks).
3. In the tags field enter "a b c d" (without the quotation marks; the problem occurs regardless of whether line breaks or spaces are used to delimit the tags).
4.  Click OK to save the token, then click OK to close the options menu.
5. Reopen the options menu.

### What is the expected behavior? What do you get instead?
**Expected Behavior:**
The token "test" will be assigned the tags "a", "b", "c", and "d".

**Actual Behavior:**
The token "test" is assigned the tag "test".

### How often does this problem occur?
100% of the time.

### What version of the program are you using? On what operating system?
Grabber 5.5.1
Windows 7

**Comment by zoameldar** [comment]
Have same issue. In 5.5.0 I had a lot of tags and they came along with 5.5.1 just fine. But when I edit them they just reset to the name of token. Every new token do the same thing.
