### ISSUE TITLE
Question - sankaku

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#1095]
This is not an issue but more of a question, I saw that sankaku was removed from the default sources and I was wondering what the reason behind that was.

**Comment by MasterPetrik** [comment]
That's the reason - https://github.com/Bionus/imgbrd-grabber/issues/997

**Comment by brodycas3** [comment]
Thanks. Sad to see sankaku going all nazi like that

**Comment by MasterPetrik** [comment]
it's becuse of 23 duplicated issues with questions like "why sankaku is еще working?"
P.S.
with this one - 24)))

Also sankaku now is not working on IQDB

**Comment by BarryMode** [comment]
I was glad to see it get removed for that reason. Tired of seeing the repeat issues over and over.

**Comment by brodycas3** [comment]
I was asking why it got removed, not why it stopped working. Still sorta works for me...

**Comment by MasterPetrik** [comment]
well... sankaku is newer worked for me in Grabber due to goverment block anyway, so I don't care)
I forced to view Sankaku only in browser( :cry:
