### ISSUE TITLE
Follow-up question regarding issue #1035

### ISSUE THREAD

**Issue by ajhauk** [Bionus/imgbrd-grabber#1096]
https://github.com/Bionus/imgbrd-grabber/issues/1035

Hello,

I saw you added the feature I suggested  (thanks for that) according to the changelog of the new version, but I can't for the life of me find the option to set the file type. If I wanted to download "webm" files, where would I have to set the option?

**Comment by Bionus** [comment]
You could either use one of the tags provided by the booru you're browsing (`animated`, `webm`...), and/or use the `filetype:webm` post-filter.

Note that using the post-filter will lead to much more page loads, as it will have to load *all* pages, then remove the non-webm images.

**Comment by ajhauk** [comment]
Doesn't work for me. Tested it on rule34hentai.net

Searched for "animated" and added "filetype:webm" to "Post-filtering". It says "No result"

Maybe you can reproduce the problem.

**Comment by Bionus** [comment]
Have you tried using the nightly version with the new [Shimmie model file](https://github.com/Bionus/imgbrd-grabber/blob/develop/release/sites/Shimmie/model.xml)?

It should be working:
![image](https://user-images.githubusercontent.com/882719/32137017-9c12e45e-bc18-11e7-8bff-df72d0ec59d8.png)

Or you could wait for the 5.5.2 release.

**Comment by sillyjungledong** [comment]
Hi there, actually looking for the complete opposite (and kind of a noob) here.. I only want static images, so no gif, webm, mp4.. etc. only jpg/jpeg, or png. Would I be doing `filetype:jpg , filetype:jpeg , filetype:png `and so on?

**Comment by Bionus** [comment]
You could. I would advice searching "-animated" and using the "-filetype:mp4 -filetype:webm" post-filter though, since there are more image types than video types. The "-" at the beginning will invert a search on most sources (and in post-filtering, it works in all sources).

**Comment by sillyjungledong** [comment]
ah cool, thanks! 👍
