### ISSUE TITLE
Crash on trying to open gelbooru pool tab

### ISSUE THREAD

**Issue by herki84** [Bionus/imgbrd-grabber#1099]
### What steps will reproduce the problem?

Open new pool tab, enter id, receive crash,

### What is the expected behavior? What do you get instead?

Expected list of images; get CTD

### How often does this problem occur? On which sources?

Every single time.

### What version of the program are you using? On what operating system?

Grabber 5.5.1 on Windows 7

### Please provide any additional information below

[main.log](https://github.com/Bionus/imgbrd-grabber/files/1344972/main.log)

[e3f5a528-ab3a-4784-8cd1-208ce5d252a0.zip](https://github.com/Bionus/imgbrd-grabber/files/1344975/e3f5a528-ab3a-4784-8cd1-208ce5d252a0.zip)

**Comment by Bionus** [comment]
Indeed, I could reproduce the crash on my end, sorry about that.

I just pushed a fix that should arrive on the nightly version, but if you'd rather wait for the official `5.5.2` release, you can either search on a normal tab using `pool:{id}` on Danbooru or pasting a Gelbooru pool URL `/index.php?page=pool&s=show&id={id}`.

**Comment by Bionus** [comment]
You need the updated model file for Gelbooru 0.2 if you want it to work:
https://github.com/Bionus/imgbrd-grabber/blob/develop/release/sites/Gelbooru%20(0.2)/model.xml
