### ISSUE TITLE
MD5 doesn't work correctly on derpibooru

### ISSUE THREAD

**Issue by zoameldar** [Bionus/imgbrd-grabber#1101]
### What steps will reproduce the problem?
Options>Rename existing images>force md5 calculation; source:derpibooru.org: OK

Download something from derpibooru. Close the program. Search for the same image.

### What is the expected behavior? What do you get instead?
After program done with existing files, there should be changed name on the right side. 
![grabber_2017-09-30_13-12-26](https://user-images.githubusercontent.com/31288278/31045306-14931afa-a5e1-11e7-9559-c0dc8d70cba6.jpg)
There is nothing and filename is not changing. I tested it on other sources, works fine.

After you search manually for the same image instead of "save" button there should be "md5 already exist". 

### How often does this problem occur? On which sources?
Rename is always, but I don't really know on what conditions save button works. Sometime it work just fine.

### What version of the program are you using? On what operating system?
5.5.1; win10 64

**Comment by SwordfishBooks** [comment]
As far as I can tell derpibooru itself doesn't allow searching by md5.
