### ISSUE TITLE
Suggestion - Presets

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#1103]
I was thinking. We should have preset that we can create and set for the sources.  I often switch between them and always find it hard to remember which ones I had set. Presets would eliminate that problem.  Here is an EXTREMELY rough example, 
![bnuxskg](https://user-images.githubusercontent.com/19770864/31087960-fe608e42-a76c-11e7-863b-899774fc4f53.png)

**Comment by Bionus** [comment]
Here's the current interface I came up with and that can be found in nightly:

![image](https://user-images.githubusercontent.com/882719/31579846-91688ce0-b13f-11e7-86de-56b94f1a2bcf.png)

Not the most beautiful, but functional.

**Comment by brodycas3** [comment]
Function > Looks

**Comment by brodycas3** [comment]
One thing I'm concerned about is the amount of white space.
