### ISSUE TITLE
do not download chan.sankakucomplex.com

### ISSUE THREAD

**Issue by acetio2** [Bionus/imgbrd-grabber#1105]
### What steps will reproduce the problem?
when i try to download from chan.sankakucomplex.com do not download

### What is the expected behavior? What do you get instead?
shows that you are downloading but not saving anything in the folder

### How often does this problem occur? On which sources?
every one I try to download from chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
5.5.1 / windows 10

**Comment by Bionus** [comment]
See issue #997, support for Sankaku is currently dropped, and they are blocking the program.
