### ISSUE TITLE
Files delete automatically

### ISSUE THREAD

**Issue by Tsuniox** [Bionus/imgbrd-grabber#1112]
### What steps will reproduce the problem?
I don't know

### What is the expected behavior? What do you get instead?
Downloads , but it deletes it

### How often does this problem occur? On which sources?
Today , sankaku

### What version of the program are you using? On what operating system?
Lastest on windows 7

**Comment by An2ni0** [comment]
[https://github.com/Bionus/imgbrd-grabber/issues/997](url)

**Comment by Bionus** [comment]
Are the saved file valid images before getting deleted?
Or simply empty/error files?
