### ISSUE TITLE
Built in video player

### ISSUE THREAD

**Issue by Zekken01** [Bionus/imgbrd-grabber#1114]
I've been thinking that we should revisit this idea and use this thread for people to voice their comments/opinions on the matter. I would like to know what people think.

I suppose I should start.
I am all for having a video player built in. I am aware of some of the issues like a larger file size. I'm sure there are other problems that could be worked around eventually

**Comment by Bionus** [comment]
I don't have issues with it, but you'd have to install codecs on Windows, or it would only be able to play WMV files.

Some workarounds for this codec issue would be to use QtWebkit, which is a too big dependency just for this (20~30 MB, also see #1107), or use the VLC lib, which while smaller would complicate the build and make it a pain for me to maintain.

**Comment by brodycas3** [comment]
Perhaps the installation of Klite codec pack could be an optional feature in the install for people to opt in to. The basic pack, https://www.codecguide.com/download_kl.htm

**Comment by AsukaLangleyfag** [comment]
Well, https://github.com/wang-bin/QtAV might be a solution. Or as alternative to vlc, libmpv.

**Comment by d-mmmy** [comment]
Would love a built in player tbh. If its too big in size, maybe release it as something optional like a plugin or something? those who want it can have it, those who don't can opt out.

**Comment by BarryMode** [comment]
A built-in video player, to me, is an essential feature that's missing.

**Comment by vampiricwulf** [comment]
In reference to 25d501f: Nothing appears when I enable the built-in player. The thumbnail is missing, but no player actually populates.
