### ISSUE TITLE
Sankaku Complex - program does not fetch images

### ISSUE THREAD

**Issue by WhiteSp1rit** [Bionus/imgbrd-grabber#1115]
### What steps will reproduce the problem?

Trying to download anything from Sankaku Complex

### What is the expected behavior? What do you get instead?

Expected - images to be downloaded.
Instead - program fetches incorrect links to the images which lead to nothing, despite correct links freely available. The only thing it can download is low size preview images. URL listed in the "more details" tab is wrong.

### How often does this problem occur? On which sources?

Every time. 
https://chan.sankakucomplex.com

### What version of the program are you using? On what operating system?

Grabber 5.5.1
Windows 7 x64 bit

**Comment by MasterPetrik** [comment]
this source currently not supported
