### ISSUE TITLE
Crash with pools

### ISSUE THREAD

**Issue by AsukaLangleyfag** [Bionus/imgbrd-grabber#1118]
### What steps will reproduce the problem?
Launch grabber, open New pool tab, press ok, crash!

### What is the expected behavior? What do you get instead?
Opened pool

### How often does this problem occur? On which sources?
Every time I try it

### What version of the program are you using? On what operating system?
Grabber 5.5.1 with site sources from develop branch on Windows 10 Enterprise x64 

### Please provide any additional information below
Crash occurs only if you have New tab. If you don't have it opened, it works normally. 
[dump.zip](https://github.com/Bionus/imgbrd-grabber/files/1398966/dump.zip)
Settings are irrelevant, tried on newly installed app.

**Comment by Bionus** [comment]
Which source did you try to load pools from?

You mention you use the sources from the `develop` branch, and I know that the 4chan source can cause crashes for example.

> Crash occurs only if you have New tab. If you don't have it opened, it works normally.

I'm not sure I understand this. You have to first open a normal tab (without loading it), then open a new pool tab and try to load it?

**Comment by AsukaLangleyfag** [comment]
I've used yande.re, but the problem stayed on stable sources too (i think it started crashing since 5.5.0). As for reproducing, i believe that new tab is opened by default and you'd have to have it opened to reproduce the crash. Next - open new pool tab and press Ok and it crashes. If you close normal tab - it works just fine.

**Comment by AsukaLangleyfag** [comment]
Updated to 5.5.2, bug disapeared. Looks like it's fixed.
