### ISSUE TITLE
Errors During Batch Downloads not being retried.

### ISSUE THREAD

**Issue by rushuna86** [Bionus/imgbrd-grabber#1119]
### What steps will reproduce the problem?

Downloading Batch. An error occurrs. But once batch is done, a popup window appears saying xxx/xxxx errored. Would you like to retry these errors, when you proceed, it will always pop up window saying 0 files have been downloaded.

### What is the expected behavior? What do you get instead?

Load up list of error links and retry them. Possibly output errored links into a text file, error.txt?

### How often does this problem occur? On which sources?

Everytime a network error occurs. Any Source.

### What version of the program are you using? On what operating system?

Windows 10 Pro.
V 5.5.1

### Please provide any additional information below
Is there a way for it to output the error into a log or text file, specifically for errors. Right now I have search through the mainlog and download the error pics manually.

**Comment by Bionus** [comment]
Indeed, it seems network errors (not 404 errors) increased the error counter but were not added to the list of images to retry at the end of the download.

I just pushed a fix, thanks for the info! :smile:
