### ISSUE TITLE
imgbrd-grabber CAN be compiled with raspberry pi 1

### ISSUE THREAD

**Issue by tom5079** [Bionus/imgbrd-grabber#1120]
with plenty amount of SWAP partition, compilation can be completed. I compiled with my raspberry 1 model B+

**Comment by Bionus** [comment]
So I take that what's written here is incorrect:
https://github.com/Bionus/imgbrd-grabber/wiki/Compilation#preparations

Did you run into any issues while building? (other than what's mentioned to comment out some stuff in `CMakeLists.txt`)
Was the memory-slip change necessary for you?

**Comment by tom5079** [comment]
it took quite long (~10min) but build was successful without error. memory-slip change was unnecessary. when I tried to compile without increasing swap partition, I encountered out of memory error. I think it’s because default swap partition size is too small (100MB)

**Comment by BarryMode** [comment]
Curious, can you just use the prebuilt Linux version?

**Comment by tom5079** [comment]
Oh, is there any prebuild version available? I didn’t knew that, I could only found the source code. Let me know where can I get it.

**Comment by BarryMode** [comment]
In releases, some of them have a linux version (not all). Here's one for example: https://github.com/Bionus/imgbrd-grabber/releases/download/v5.5.0/Grabber_5.5.0_linux.zip

**Comment by AsukaLangleyfag** [comment]
You can't. lt's compiled for linux-amd64 target, not armv6sf.

**Comment by BarryMode** [comment]
Gotcha. Still seems worth it to use a Pi this way though. Thanks for sharing. I never would have thought to try this.
