### ISSUE TITLE
Crash on bigger download query

### ISSUE THREAD

**Issue by Waffelparty** [Bionus/imgbrd-grabber#1123]
### What steps will reproduce the problem?
Searched for to_love_ru pictures and tried to download all of them

### What is the expected behavior? What do you get instead?
expected: some minutes of downloads and tons of new pictures.

got: some pictures, a crash and the group folder isnt there. the log says some pictures should be already in the group folder

### How often does this problem occur? On which sources?
everytime on different sources.

### What version of the program are you using? On what operating system?
Grabber 5.5.1 on Windows 8.1 x64 with all Updates installed

**Comment by Bionus** [comment]
How many images were you trying to download, and how many got downloaded successfully?
Also, if you already had a lot of already existing pictures for what you were downloaded, that crash may have been fixed in `v5.5.2`.

> the log says some pictures should be already in the group folder

Can I see that log?
