### ISSUE TITLE
Loading error: Error creating SSL context () (99)

### ISSUE THREAD

**Issue by ELRELR** [Bionus/imgbrd-grabber#1124]
### What steps will reproduce the problem?
Any search through New Tab or New Tab Pool using danbooru or gelbooru will not return any results. Examples are "rating:safe" and "blonde_hair". Searches using behoimi will crash the program. 

### What is the expected behavior? What do you get instead?
Instead of regular search results, no images appear and the error "Loading error: Error creating SSL context () (99)" reoccurs in the log. A log file is attached. 
[main.log](https://github.com/Bionus/imgbrd-grabber/files/1409186/main.log)

### How often does this problem occur? On which sources?
It occurs on every search with the above sources. 

### What version of the program are you using? On what operating system?
I am using v5.5.1 on Windows 10. 

### Please provide any additional information below
All settings aside from default location are at default values. I tried updating OpenSSL as detailed in https://github.com/Bionus/imgbrd-grabber/issues/767. 
Any help you can provide would be appreciated.

**Comment by Bionus** [comment]
http://slproweb.com/products/Win32OpenSSL.html

Which version did you install from there? `1.1.0` or `1.0.2`?
Grabber targets `1.0.2` so using the `1.1.0` might not work.

Also, during the installation, which option did you chose in this screen:

![image](https://user-images.githubusercontent.com/882719/32008635-fff45a02-b9ac-11e7-9ebd-48c308115b33.png)

If you chose the Windows directory, you have to delete the 3 DLLs from Grabber installation directory (else they'll have priority). If you chose the `/bin` directory, you have to replace the ones in the Grabber installation directory by the ones in "C:\OpenSSL-Win32\bin".

**Comment by Bionus** [comment]
You could also try the DLLs from there if the previous don't work:
https://indy.fulgan.com/SSL/

**Comment by ELRELR** [comment]
Switching to 1.0.2 and deleting the 3 DLLs in the Grabber folder worked, don't get results from dan/gelbooru but the others are good enough for me. Thanks for the helpful response and this wonderful program, no longer have to save things one by one!

**Comment by Bionus** [comment]
I see. May I ask which version did you use? I guess `v1.0.2L Light`? Win32 or Win64? (because the one bundled with Grabber is already `1.0.2k`, so it's weird that it wouldn't work)

**Comment by ELRELR** [comment]
I guess that the problem was that I originally installed 1.1.0 Win32 when I'm running Win64.
