### ISSUE TITLE
Changelog window opens too small

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#1126]
![image](https://user-images.githubusercontent.com/19770864/32149260-f9d4354c-bcd7-11e7-9120-907059b9b339.png)

Pretty self explanatory with the title.

**Comment by MasterPetrik** [comment]
![2017-10-30_090233 win7 mastercore](https://user-images.githubusercontent.com/22294259/32163313-fa0fb258-bd6c-11e7-8e94-1b89fa46e470.png)

I guess, such size will be enough.

**Comment by brodycas3** [comment]
Looks great to me.

**Comment by Bionus** [comment]
> @Bionus is this normal, that when I'm on nightly version, I get update message, but when I try to update it sends me to version download page on Github in browser instead of autoupdate?

Yes, nightly doesn't update itself for the moment.
