### ISSUE TITLE
Loading thumbnails from Sankaku instead of full-sized images

### ISSUE THREAD

**Issue by aarqon** [Bionus/imgbrd-grabber#1128]
### What steps will reproduce the problem?
Attempting to open images from chan.sankakucomplex.com

### What is the expected behavior? What do you get instead?
 Loads a thumbnail instead of the full-sized image in the preview window

### How often does this problem occur? On which sources?
All chan.sankakucomplex.com images

### What version of the program are you using? On what operating system?
Fresh install of 5.5.2 on Windows 10

### Please provide any additional information below
One from sankaku: [link](https://user-images.githubusercontent.com/11674341/32256384-b77c9e4a-be7c-11e7-8b06-94b69c8ff455.png) (**nsfw**)
One from e621: [link](https://user-images.githubusercontent.com/11674341/32256399-cf2c270e-be7c-11e7-8bd0-5f77da6b8de7.png) (**nsfw**)

**Comment by CapedBaldy** [comment]
I have the same exact issue. In addition to this, images never download from sankaku even though the program says download complete (the download folder is empy). I tried copying the links in the download window and they are all broken.

**Comment by MasterPetrik** [comment]
This source currently not supported. So you will not get any technical support until site's API will work again. Blame sankaku devs for that.

For details see this issue - https://github.com/Bionus/imgbrd-grabber/issues/997

**Comment by Bionus** [comment]
As MasterPetrik said, Sankaku's developer does not want downloaders to work, and even explicitly asked us to drop the support for it in Grabber, that's why Sankaku doesn't work very well.

You can always try to use the [Nightly version](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly) and the latest [model.xml](https://github.com/Bionus/imgbrd-grabber/blob/develop/release/sites/Sankaku/model.xml) file for Sankaku, as it seems to work with it.

**Comment by Rigabriezi** [comment]
@Bionus I've properly place the new .exe file but I'm not sure what I'm supposed to do with the .xml file. Are you supposed to just drap and drop it into the Grabber file location?

**Comment by MasterPetrik** [comment]
@Rigabriezi obviously place it there XX:\Users\XX\AppData\Local\Bionus\Grabber\sites\Sankaku

**Comment by Bionus** [comment]
Not really obvious but yeah on most systems it will be in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites\Sankaku`.

**Comment by aarqon** [comment]
Is it's not supported, should I go ahead and close this then? I don't know how "official" that workaround is.

**Comment by MasterPetrik** [comment]
well, considering that we already have main sankaku issues threadюююнуыб better to close this issue and\or continue discussion there.
