### ISSUE TITLE
Grabber.exe hangs trying to search from CLI

### ISSUE THREAD

**Issue by aarqon** [Bionus/imgbrd-grabber#1129]
### What steps will reproduce the problem?
Attempting to search from the CLI
e.g.
`grabber.exe -c -t md5:40c2f976c34017f5fd2045afb8de8004`

### What is the expected behavior? What do you get instead?
It should either exit with no response or return a result

### How often does this problem occur? On which sources?
It seems to occur sometimes with e621, rule34.xxx, and chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
5.5.2 on Windows 10

### Please provide any additional information below
I am attempting to call this from a Python script to automate tag scraping, which may be complicating it. Without any debug info it is difficult to tell, but passing grabber the debug flag does nothing.

**Comment by Bionus** [comment]
> `grabber.exe -c -t md5:40c2f976c34017f5fd2045afb8de8004`

If you actually tried to call this, then it won't work. You have to say which sources you want to use. I could reproduce the "freeze and do nothing" when no sources are provided. You also have to say what you want to return, or it will freeze too (or so it seems). Also make sure to quotes most arguments as positional arguments are dropped (source separator is space ` `).

On the other hand, `grabber.exe -c -s "e621.net" -t "md5:40c2f976c34017f5fd2045afb8de8004" --return-images` gave results.

However, given the rest of the issue, it may simply be an error when writing the bug report. In that case, do you have an exact command that "froze" Grabber?

**Comment by aarqon** [comment]
That was the exact command I tried (with several different md5's). I also tried with -rt (and --return-tags) because I am trying to get the tags for a given image/hash where possible. Is --return-images the better way to do that?

**Comment by aarqon** [comment]
Just fyi, the command you gave produces no output with grabber.exe, but does with grabber.com. --return-tags works with neither.
