### ISSUE TITLE
Canceling while adding presset bug

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1131]
1. Go and try to add new preset. Type something in "name" or left it clear. Then press "cancel" button.
![2017-11-02_164228 win7 mastercore](https://user-images.githubusercontent.com/22294259/32329149-2df412bc-bfed-11e7-8b0a-3ff53cfa5807.png)
2. New unnamed preset was added after first preset!
![2017-11-02_164245 win7 mastercore](https://user-images.githubusercontent.com/22294259/32329151-308b2826-bfed-11e7-84ec-30133db2077a.png)

100% repeatability

**Comment by Bionus** [comment]
Indeed, it seems that a preset was added however the popup was closed, thanks! :smile:
