### ISSUE TITLE
Is there a way to download a lot of images from Sankakucomplex?

### ISSUE THREAD

**Issue by arukom** [Bionus/imgbrd-grabber#1133]
It is the bigges site out there and has the most images on almost every tag there is.

What can i do to download big 20k+ tags?

**Comment by MasterPetrik** [comment]
This source currently not supported. Better not to try use it in Grabber.
You probably will not get any technical support until site's API will work again. 
Blame sankaku devs for that. They doing everything to block massdownloading from their site.

For details see this issue - #997

**Comment by arukom** [comment]
ugh, how ridiculous. it almost has twice the pictures amount for everything

**Comment by Bionus** [comment]
As said, Sankaku's developer does not want downloaders to work, and even explicitly asked us to drop the support for it in Grabber, there's nothing much we can do at this point.

I'll close this issue for that reason, you can see the details in the other issue linked above.
