### ISSUE TITLE
some minor text problems

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1135]
1. "connection" text in credentials in source settings typed incorectry and also doesn't have translations
![2017-11-02_132050 win7 mastercore](https://user-images.githubusercontent.com/22294259/32393418-6e28b448-c0ea-11e7-98d9-f9f610264ad8.png)

**Comment by MasterPetrik** [comment]
2. buttons for web servises settings doesn't have translations
![2017-11-03_230304 win7 mastercore](https://user-images.githubusercontent.com/22294259/32393603-362da9bc-c0eb-11e7-8d8c-e67f6e9c0ebc.png)

**Comment by MasterPetrik** [comment]
3. it's a very bad message, any message suggestion from https://github.com/Bionus/imgbrd-grabber/issues/1065 will be better than this.

![image](https://user-images.githubusercontent.com/22294259/32393951-819346ea-c0ec-11e7-880b-9c4edc0a596d.png)

First of all, there in so such thing as "full directory", only full hard drive, also "it seems that..." is bad need more confidence. Second part of the message is bad too, "solve the issue before resuming the download" looks really bad, too unclear what user should do. Much better will be message that tells user to free some space.

I strongly recommend to change this error message to this(or kind of):
> check free disc space value on destination folder's drive, and if it's not enough space, show error message like this "Not enough free space on drive XX, Please free some space to continue downloads" And buttons like "cancel" and "continue".

**Comment by Bionus** [comment]
> it's a very bad message

Indeed, so I just changed it to:

> Not enough space on the destination drive "Drive name (E:)".
> Please free some space before resuming the download.

:+1:
