### ISSUE TITLE
Missing Tag Names, Only Numbers

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#1138]
It doesn't seem to affect all boorus searched, but only some, I think the Gelbooru 0.1 boards tend to be caught out here, but I could be wrong, and I'm not sure what's causing it

**Comment by SultrySamthepennanceman** [comment]
https://imgur.com/a/7m9HJ

**Comment by Bionus** [comment]
Which sources did you use when the problem occurred?

**Comment by SultrySamthepennanceman** [comment]
Pretty much all of them. This has been going on for a while now, so I don't think I'd be able to find which ones give tags and which ones just show numbers but not the actual names for the tags.  Also, behoimi.org doesn't seem to be working for me- it just comes up blank

chan.sankakucomplex.com seems to have this issue where I can't preview image results beyond a thumbnail now, not sure if that's intentional because of how it IP bans people for Dlling too fast.

Also, I ran a blank search on each default Grabber source, and it seems that after 13 or so tags, the numbers seem to show up whilst the page is loading- to note I was around Tentaclerape.net before they showed up on this little test and ending up on the tags window under the list, though small, it clearly piles up with more sources added at this point - I think-

And I may/may not be missing Zerochan.net- at least in the form it appears in when it comes with the program by default as I have wwww.Zerochan.net opposed to what I should have.

Here's a screenshot of the numbers in question appearing during a search Load before the other actual working tags show, and this Is them (I think?) showing up later, just to note this is again, with the default (I think, given the only changes I make to them on my side are the login features)  Sources active and nothing else besides them.

The search was a images per page of 20, auto tag add is 5, and Get more precise tags whilst searching images is unselected. I am using Privoxy, but that's normal, and I only use it because it seems to actually help searches in terms of sites with things in place against multiple site requests-
https://imgur.com/a/bIZDi -During searach
After Search (Not the same numbers but yeah)
https://imgur.com/a/DGJrg

**Comment by SultrySamthepennanceman** [comment]
Also When you've created a Preset and click on the edit preset button, but don't put anything in and cancel the option to edit a preset, it removes the chosen preset's name- that needs fixing.

**Comment by SultrySamthepennanceman** [comment]
https://anonfile.com/OdQcR7c0bb/crashes.7z (Current Crashes filecompressed, might have already given it to you)
newer Crashes file 
https://anonfile.com/N3RdRdc0b2/crashes.7z
