### ISSUE TITLE
rule34hentai 

### ISSUE THREAD

**Issue by trollsasha1** [Bionus/imgbrd-grabber#1139]
rule34hentai does not work. No search result. A few days ago everything was fine.

**Comment by talkopel02** [comment]
same problem for me

**Comment by Bionus** [comment]
Seems they enabled Cloudflare anti-bot system. 🤔

**Comment by lee27** [comment]
T_T T_T T_T

**Comment by Bionus** [comment]
Seems they disabled it again?
I'll be closing the issue since it's back.
