### ISSUE TITLE
Two feature reqests 

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1141]
> You can always try to use the Nightly version and the latest model.xml file for Sankaku, as it seems to work with it.

@Bionus Yep, work a bit, at least for single images from whole page. Looks like preloading neighbour images when opening image in preview breakes them somehow.

![image](https://user-images.githubusercontent.com/22294259/32503083-5fbb9f1e-c3ed-11e7-9764-588b49dc05f4.png)
![image](https://user-images.githubusercontent.com/22294259/32503282-e1cbe040-c3ed-11e7-9720-1b743891e6a2.png)

Considering that, I request some features, not for sankaku, but useful for all sources:
1. Need to add an ability to reload images in preview window from source(better add it to right click menu)
2. Need separated setting for each source, which will  grant\deny preloading additional images when opening image in preview, or setting for each source, which will set number of preloaded additional images when opening image in preview

**Comment by Bionus** [comment]
> Need separated setting for each source, which will grant\deny preloading additional images when opening image in preview, or setting for each source, which will set number of preloaded additional images when opening image in preview

That seems like a very very specific feature. Why do you think it's necessary to differentiate the preload count between sources?

**Comment by MasterPetrik** [comment]
> That seems like a very very specific feature. Why do you think it's necessary to differentiate the preload count between sources?

Well, because source reaction on such things might be different on different sources(like specific behavior of Sankaku), but yeah, seems too specific for now, since it's only about one source for now. So you can ignore this part of the issue.
