### ISSUE TITLE
Files being saved in wrong folders

### ISSUE THREAD

**Issue by Kernel-13** [Bionus/imgbrd-grabber#1143]
### What steps will reproduce the problem?

Loading a .igl file with a big number of batches and clicking 'Download'.

### What is the expected behavior? What do you get instead?

I expect the batches to download in the folders I assigned them.

What I Get: Pictures from Batch A (that should be saved in Folder A) end up being stored in a different Folder B.

### How often does this problem occur? On which sources?

Almost everytime / danbooru.donmai.us

### What version of the program are you using? On what operating system?

Grabber 5.5.2 / Windows 10 x64 v.1709

### Please provide any additional information below

To explain myself better, lets say I have a batch with the tag "artistA" and I select "C:/booru/artistA" as the destination folder, and I repeat the process for artistB, artistC, .... artistZ. Then I save the list.

Whenever I open my save file (an .igl file with more than 180 batches) and click 'Download', it starts downloading the first batch as usual, but after some time it reaches a batch 'artistX' and, instead of saving the pics on "C:/booru/artistX", they end up in another folder.

It also happens when I click on 'Download' after downloading a few selected batches with the 'Download Selected' option.

I tried to replicate this bug with a different save file and different locations. Here is what I did:
- The first time I clicked 'Download' (and the destination folders were new/empty), it downloaded everything without any problems.
- I decided to delete some pics from some folders
- This time, it downloaded the missing pics, but at some point it started downloading pics from a batch in a different location that batch had assigned.
- After downloading each batch with the 'Download Selected' option, I decided to try the 'Download' option again, and at first it was doing fine, skipping pics already saved, but after some time it started misbehaving again.

I already tried reinstalling but it didn't solve it. The only workaround is to download one batch at a time with the 'Download Selected' option, which is a bit tedious.

This problem was briefly mentioned on #1106, but was overlooked.

I can't attach the .igl file that I used for testing, but will attach the log.

[main.log](https://github.com/Bionus/imgbrd-grabber/files/1463049/main.log)

**Comment by MasterPetrik** [comment]
Try to use ```%artist%\%md5%.%ext%``` as default name or just add ```%artist%\``` before your default filename, then it will create a separate folder for each artist and save related images there.

BTW, is there any reason to collecting more than 180 batches?
There are almost 50% images from ypur log already existed. 
Use this checkbox to autoremove compleated sownloads from the list.
![2017-11-11_130256 win7 mastercore](https://user-images.githubusercontent.com/22294259/32688397-ea2fcbc0-c6e0-11e7-9af8-a235f18f5ffb.png)

**Comment by Kernel-13** [comment]
> Try to use %artist%\%md5%.%ext% as default name or just add %artist%\ before your default filename, then it will create a separate folder for each artist and save related images there.

I'm currently using `%character%  %copyright%  %date:format=dd.MM.yyyy%  %id%  %rating%.%ext%`, and saving them in folders that I already had created. Changing the file name at this point would be a bit of a problem, since I would also have to change the filename of the pics I already downloaded.

![capture](https://user-images.githubusercontent.com/25790483/32689140-1dbb2ec8-c6df-11e7-8150-6622065597a0.PNG)

Sure, adding `%artist%/` as a prefix would create a different folder for each batch, but what I want is that the batches download in the folders that I assigned to them.

> BTW, is there any reason to collecting more than 180 batches?
There are almost 50% images from ypur log already existed.

The reason I have that many batches in one file is because I intended to use only 1 save file to update all my folders. That's also the reason why 80% of the pics from the batches already exist.
Also, I think the remove option would only remove the batches that have been completed, but won't prevent Grabber from possibly mess up the folders. I will give it a try tho.

**Comment by Kernel-13** [comment]
I've been doing some more testing, and I've found some interesting things:
- I enabled the 'remove' checkbox, but it ends up crashing when it finishes downloading the batches. This happens when using the 'Download' option.
- The 'remove' option doesn't remove all the completed batches, but only a few. (For example, after downloading 7, only 4 were removed)
- I noticed that the change of folder can also happen in the middle of a batch download, and not only at the start of said batch download.
- I also found that if I choose the 'Download' option right after loading a save file, it will download all batches with no problems. But after this, if I try to download the same batches again (in the same session, using either 'Download' or 'Download Selected'), the problem returns.
- This only happens with my save file, but if I select 4 or more batches (starting with the first batch) and hit 'Download Selected', it will download them, but crash after finishing.

I don't know if these problems are only related to my savefiles, or is a Grabber problem, so I will attach my setting.ini and the log and minidump from the crash, if this is of any help. 


[CrashWhenRemoveEnabled.zip](https://github.com/Bionus/imgbrd-grabber/files/1465168/CrashWhenRemoveEnabled.zip)

**Comment by MasterPetrik** [comment]
> I enabled the 'remove' checkbox, but it ends up crashing when it finishes downloading the batches. This happens when using the 'Download' option.

> The 'remove' option doesn't remove all the completed batches, but only a few. (For example, after downloading 7, only 4 were removed)

Great! Finally someone else who has this problem exept me an one more guy. 
You can see full info about this problem in my investigation in https://github.com/Bionus/imgbrd-grabber/issues/812 issue.

**Comment by Bionus** [comment]
This issue is quite strange but I've heard about similar problems before, so I'll investigate. Thanks for providing that much details and your settings / igl file. :+1:

Totally unrelated, but you know that all your downloads' path/filenames could be simplified, right?
* Path: `C:\Grabber\danbooru`
* Filename: `New folder - %search%/%character%  %copyright%  by %artist% %date:format=dd.MM.yyyy%  %id%  %rating%.%ext%` (`%search%` or `%artist%` btw)
