### ISSUE TITLE
Nightly build is not updating

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1144]
![2017-11-12_220507 win7 mastercore](https://user-images.githubusercontent.com/22294259/32702709-da63ec0a-c7fb-11e7-9986-dae54b82838a.png)

As you can see, in nightly relese still stays old version from 4 november

![2017-11-12_195355 win7 mastercore](https://user-images.githubusercontent.com/22294259/32702711-dfab7c50-c7fb-11e7-845f-7b3ae7ef4983.png)

Is this OK? I'd prefer to test last changes...

**Comment by Bionus** [comment]
Nightly updated.
https://github.com/Bionus/imgbrd-grabber/releases/nightly

> I'd prefer to test last changes

Adventurous :smile:

**Comment by MasterPetrik** [comment]
P.S.
I still interested, where was the problem?
