### ISSUE TITLE
e-shuushuu.net support

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1145]
I suggest you to add e-shuushuu.net as source in Grabber. You did well with anime-pictures, it would be good to add this one too.

pluses:
+rich tag system
### +over 900 000 images
+already supported in IQDB, so it probably have a suitable API
+images has a same md5 which they have on boorus(important for merged results)

minuses:
-this is not a typical booru after all

**Comment by Bionus** [comment]
Indeed, I've taken a look at it a while back and I remember that the only thing stopping it from being added easily is the fact that they don't have an API to search images by a given tag.

One first needs to convert the tags into their IDs before searching (ex: `blonde_hair` -> 169).

With the new tag database system it would be easier to implement, but I'd much prefer a proper API. Do you know which url IQDB uses for searching? Or does it simply use http://e-shuushuu.net/search/similar/?

**Comment by MasterPetrik** [comment]
@Bionus maybe http://e-shuushuu.net/search/advanced/ will help you?
