### ISSUE TITLE
rule32hentai.net there are almost!

### ISSUE THREAD

**Issue by lee27** [Bionus/imgbrd-grabber#1149]
First of all, thank you bionus, maybe, thanks to him I will succeed!
I tried to use Grabber, using the "download" tab I tried downloading the first page of the "the last of us" tag and actually the pictures I download are 49 as in page 1 ........ however, because in these 49 pictures some are replaced by other images that are not on page 1? (I hope you can understand)
and how do I download the images in the same order and with the same names as the original files? (with the various tags)
thanks bionus!
this is the page
https://rule34hentai.net/post/list/The_Last_of_Us/1
THIS SITE IS FULL OF ADS!

**Comment by Bionus** [comment]
I'm not sure I understand.

I just tried to download the first page fort that tag, and Grabber properly downloaded the 49 images of the first page: [image](https://user-images.githubusercontent.com/882719/32861947-c09e58ca-ca56-11e7-89ff-ad5384369d37.png) (**NSFW**).

**Comment by lee27** [comment]
forgive my English (I'm Italian and I'm using a translator)
however, maybe I understand the problem, if I login on the site rule34, I come from different pictures, look!
logged in
![login](https://user-images.githubusercontent.com/20624978/32862570-d1ca53e0-ca58-11e7-8c38-b40e67499bfa.png)
login not done
![logout](https://user-images.githubusercontent.com/20624978/32862579-d8161aa4-ca58-11e7-915c-0898aeb9fd3d.png)
and using the download tab, I download the same images as you downloaded
but how do I download the same images I get by logging in? thanks

**Comment by lee27** [comment]
I read this
https://github.com/Bionus/imgbrd-grabber/issues/1011
but I did not understand what I should do!

**Comment by lee27** [comment]
please, can anyone help me?

**Comment by Bionus** [comment]
You should not put your username and password in the "Login" tab. You're supposed to literally put "user" and "pass" in there:

![image](https://user-images.githubusercontent.com/882719/28996144-29b094ac-79fa-11e7-9323-f667af68bcba.png)

Your username and password are only to be put in the "Credentials" tab (which you correctly did).

With that, I could get the logged-in images: [image](https://user-images.githubusercontent.com/882719/33095249-484add56-cf03-11e7-906b-03adf58f3714.png) (**NSFW**)

**Comment by lee27** [comment]
WORK WORK WOOOORK! thanks bionus Thanks!
last two questions
1) How do I download all the photos of a tag? In the download tab I can only set individual pages
2) How do I download images with their original name? (with the various tags)

**Comment by Bionus** [comment]
> How do I download all the photos of a tag? In the download tab I can only set individual pages

Just increase the "Limit" of your batch download to the number of images you want to download. Or click "Get all", then all pages should be downloaded.

> How do I download images with their original name? (with the various tags)

See https://github.com/Bionus/imgbrd-grabber/wiki/Filename
