### ISSUE TITLE
Where are favourites stored?

### ISSUE THREAD

**Issue by Rigabriezi** [Bionus/imgbrd-grabber#1152]
Unfortunately I believe I have messed up the local files for Grabber so the program will stop responding and crash within 20 minutes of activity. 

So I'd like to save the favourites location and transfer them over to the reinstalled program location.

**Comment by Bionus** [comment]
They're stored in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`.
* `favorites.txt` contains the list of favorites
* `thumbs/` contains the thumbnails for each favorite

So if you want to move them you have to copy them from there. But all installs use the same path so even if you reinstall you shouldn't have to move anything.

**Comment by Rigabriezi** [comment]
Ok thanks. I will copy them from the .txt file.

**Comment by Rigabriezi** [comment]
@Bionus I actually have a question about thumbnails. Some of my favourites don't have thumbnail previews. Is there a reason for that? Do I need to manually add one?

**Comment by Bionus** [comment]
Depending on how you added the favorite, it may not have a thumbnail.
You can set one by opening any image with this tag, then right clicking said tag and select the "Choose as image" action.

**Comment by Rigabriezi** [comment]
@Bionus Thanks. It worked. On a different order. I redownloaded Grabber from the website and Sankucomplex is no longer on the default list of websites. I'm aware that you need to do some extra steps to download from that website now but It seems I can't view any images from that site anymore even after adding it to the last with the proper type.

**Comment by MasterPetrik** [comment]
> Depending on how you added the favorite, it may not have a thumbnail.

And... https://github.com/Bionus/imgbrd-grabber/issues/779 issue. 

> Issue 1: No image in favorites for tags, added from search field directly. Images only added when you add tag to favorites from tag list in preview window.

> So I can suggest a solutions:
> 
> For tags, added from search field, add as image first(or random) image that grabber found for that tag.

**Comment by Bionus** [comment]
> It seems I can't view any images from that site anymore even after adding it to the last with the proper type

Because they're blocking Grabber. As said in some other issue you can try using the `model.xml` from the `develop` branch, it may work there.

I'll close the issue since the initial question was answered.
