### ISSUE TITLE
problem with batch mode (less pictures)

### ISSUE THREAD

**Issue by lee27** [Bionus/imgbrd-grabber#1155]
I have a problem with batch mode, I'm trying to download the entire "the last of us" tag after clicking on "get all" but using batch mode does not download all the images. I tried to add it directly to the "download" tab by setting the image limit to 999999, but download it less!

**Comment by lee27** [comment]
I solved, putting% id% -% all%.% ext%! thanks anyway! (bionus, this gossip is wonderful)

**Comment by MasterPetrik** [comment]
looks completely similar to https://github.com/Bionus/imgbrd-grabber/issues/1148 issue, please read

**Comment by lee27** [comment]
the problem is that of this tag
https://rule34hentai.net/post/list/The_Last_of_Us/63
on every page there should be 49 pictures, so if I do 49 x 63 I should download 3000 pictures, but I download a lot less!
could you try it?

**Comment by MasterPetrik** [comment]
> the problem is that of this tag
> https://rule34hentai.net/post/list/The_Last_of_Us/63
> on every page there should be 49 pictures, so if I do 49 x 63 I should download 3000 pictures, but I download a lot less!
> could you try it?

opened site.
for this tag only 6 full pages found, so 49*6 = 294 + 4 images on 7th page  so 298 in total
all pages after 7th gets "no result" message for me:

![image](https://user-images.githubusercontent.com/22294259/33248106-19166264-d334-11e7-828a-282cea686b6a.png)

When I try to go on the last page with"last" button, it moves me to empty 63th page
![image](https://user-images.githubusercontent.com/22294259/33248155-6971dc3e-d334-11e7-844d-cc8fe922ccf1.png)

so obviously it's some site problem, it shows 63 pages to grabber, and grabber calculates and think that
there are will be 3000+ images.
but on site I found much less.

So I asking you to say, how many images Grabber downloaded after all for you.

**Comment by lee27** [comment]
but wait, have you logged in? because some images "unlock" only if you are registered!

**Comment by MasterPetrik** [comment]
so you don't want to tell how many images Grabber downloaded for you after all?

**Comment by lee27** [comment]
i have logged in, and doing the search in a new tab finds them all, but if i scroll with the previews I crash the program, and even if i get it all, i do not download them all ..... i do not understand the because!

**Comment by Bionus** [comment]
> I made the calculation, if there are 49 pictures on each page and the pages are 63, I have to download 3072 images (using get all), but as you can see from the image download 3049

If you check the log to see if all pages actually give 49 results. For each loaded page, you'll see a corresponding line in the log:
```
[02:01:52.542][Info] [rule34hentai.net][Html] Parsed page https://rule34hentai.net/post/list/The_Last_of_Us/1: 49 images, 1260 total (1260), 63 pages (63)
```
All of them should say "49 images". If they don't, either Grabber fails to parse some image on some page, or rule34 doesn't actually have 49 images on that page. Can you check that? (or at least share your log)

> then after a while I get this message and the downloads stop!

It seems like a problem writing the file to your disk. Either the filename is too long, your drive is full, or something like that. BTW, the download doesn't actually stop after that, it simply pauses to give you time to make some free space, or fix the writing error before resuming.

**Comment by shikiyoku** [comment]
Have very similar issue with rule34.paheal.net
```
Parsed page http://rule34.paheal.net/post/list/id70A70E70D2431076/1: 40 images, 40 total (2), 2 pages (%8)
```
But it should be 140 - two pages.

When I go to the next pages it receives 2 more. But log says something strange:
```
Parsed page http://rule34.paheal.net/post/list/id70A70E70D2431076/2: -1 images, -1 total (-1), -1 pages (%8)
...
Parsed page http://rule34.paheal.net/post/list/id12A12E12D2431076/3: -1 images, -1 total (-1), -1 pages (%8)
```

**Comment by lee27** [comment]
sorry but I have not yet solved the problem
