### ISSUE TITLE
error when downloading

### ISSUE THREAD

**Issue by aoi555** [Bionus/imgbrd-grabber#1156]
### What steps will reproduce the problem?
hi my problem is that when making a download all images say "can not open the file"

### What is the expected behavior? What do you get instead?

he normal thing is that the images are downloaded in the folder, but when they are downloaded the images are not seen in the thumbnail or in the image viewer or in any other program to see images

### How often does this problem occur? On which sources?

always

### What version of the program are you using? On what operating system?

I have grabber 5.5.2 in windows 10

### Please provide any additional information below
the images appear in the capture folder, and according to the program if you download but the images are neither in thumbnails, nor in the image viewer either in photos, photoshop or similar
![captura de pantalla 24](https://user-images.githubusercontent.com/33982872/33233010-7fd29d0c-d1d5-11e7-9cf5-565f37e2dde7.png)

**Comment by MasterPetrik** [comment]
can you please upload somewhere in the net examples of these broken images, to me download them and check what's wrong, because without it hard to determine, where is the problem. 
also uploading log will much help too.

**Comment by MasterPetrik** [comment]
ven now I can say that these images filenames doesn't looks like they named properly, md5 sum should be much shorter(32 letters) so even here I see weirdness

**Comment by aoi555** [comment]
How do I do that?


2017-11-27 9:00 GMT-06:00 MasterPetrik <notifications@github.com>:

**Comment by MasterPetrik** [comment]
Just upload them to your Mega cloud and post here a link

**Comment by aoi555** [comment]
How do I provide them with the information they need to help me?

2017-11-27 10:53 GMT-06:00 MasterPetrik <notifications@github.com>:

**Comment by ravenlord1** [comment]
1) Create an account at a website that provides cloud storage (like mega or dropbox)
2) Upload the picture folder and the log file to the account
3) Reply back here with a link from the cloud account to those files
4) He can click on that link and then look at the files to see what is wrong

**Comment by aoi555** [comment]
I have an account, but ... could you teach me how to do that because I do
not know how

2017-11-27 22:51 GMT-06:00 Raven Lord <notifications@github.com>:

**Comment by ravenlord1** [comment]
Most accounts have an "upload" option.  You can either click on it and direct it to the folders that you want to upload, OR you can open a directory on your PC and just drag the folder from your directory into the target icon in the browser window.

Step1 Get to the homepage
Step2 Create a folder called Grabber
Step3 click on upload
Step4 Select your files to upload
Step5 Drag the files into the folder Grabber
Step6 Right-click on the folder and select Generate link
Step7 Copy the link location and paste it into a message here.

Hope this helps
![step 1](https://user-images.githubusercontent.com/26584049/33304794-29463468-d3c8-11e7-8929-330bd82323fd.jpg)
![step 2](https://user-images.githubusercontent.com/26584049/33304796-296cf6f2-d3c8-11e7-8bd9-0c1293c23e2b.jpg)
![step 3-4](https://user-images.githubusercontent.com/26584049/33304797-298e80f6-d3c8-11e7-80c8-74eba254f2bd.jpg)
![step 5](https://user-images.githubusercontent.com/26584049/33304798-29bcf918-d3c8-11e7-8a9f-988005ee588c.jpg)
![step 6](https://user-images.githubusercontent.com/26584049/33304799-29dbd928-d3c8-11e7-9284-f04d2498709a.jpg)
![step 7](https://user-images.githubusercontent.com/26584049/33304801-29fda9a4-d3c8-11e7-892a-61c2518441b0.jpg)

**Comment by aoi555** [comment]
aaaaaaa already well, thank you very much, well I uploaded some images for
the hour


https://mega.nz/#F!bIh1AZpa!3EJioK581RvLm-hmW1tpMg

2017-11-28 0:10 GMT-06:00 Raven Lord <notifications@github.com>:

**Comment by aoi555** [comment]
hello, days ago I sent you the link that they asked me but I do not know
anything about you or how you can solve this problem

2017-11-28 17:20 GMT-06:00 aoi keidran <aoikeidran@gmail.com>:

**Comment by MasterPetrik** [comment]
As I expected, old problem with saving redirects/error server ansvers as images, huh. Just like in https://github.com/Bionus/imgbrd-grabber/issues/1162

This is what writed in these fake-images:
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body bgcolor="white">
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>nginx/1.10.3</center>
> </body>
> </html>

As you can see, these images doesn't exist on server at all, they are moved somewhere else, so there is no way to watch or download them through their links. This is normal. The problem is that instead of skipping problem images in batch downloading process, Grabber saves error messages as images, so that's the problem.
As temporaty solution I can recommend you to delete all images in Grabber folder, which filesize <2KB

Anyway this issue is a duplicate of https://github.com/Bionus/imgbrd-grabber/issues/1162 and should be closed.

**Comment by aoi555** [comment]
Yes, but the problem is that there are several extensions that do not
download, will that solve?

**Comment by MasterPetrik** [comment]
> the problem is that there are several extensions that do not
> download,

Since I have seen only your downloaded images, I don't have any idea what's happening with not downloaded ones. We need a screenshots of the problem but log file would be even better

**Comment by aoi555** [comment]
ok, and how do I get that?
