### ISSUE TITLE
Gelbooru - No Results

### ISSUE THREAD

**Issue by spork123** [Bionus/imgbrd-grabber#1157]
### What steps will reproduce the problem?
When ever I try doing anything with the source Gelbooru I automatically get back "No Result", yet other sources work fine, and it worked fine the last couple days. I think this started happening after the recent update. I tried tweaking the infos on the "login" tab but it didn't help, maybe I'm an idiot and just don't know how to put it back to default within this tab.

### How often does this problem occur? On which sources?
Happens all the time, with Gelbooru source.

### What version of the program are you using? On what operating system?
I'm using version 5.5.2, on Windows 10.

**Comment by Aelphais** [comment]
Gelbooru has disabled their API. Not sure if it is temporary or not. The exact message is "Search error: API disabled due to abuse."

Apparently they have done it before and reenabled it later on, so they might do so. Also not sure if it is Grabber related or not.

**Comment by MasterPetrik** [comment]
here is the post with gelbooru admin comment about it 
https://gelbooru.com/index.php?page=forum&s=view&id=3873

and one of reasons, why he disabled it, is guys like this:
https://gelbooru.com/index.php?page=forum&s=view&id=3872

also, for IQDB Gelbooru still works well, who knows why...

**Comment by Bionus** [comment]
Well, that's unfortunate, but nothing we can do for now.
Another reason to implement #1023 though.

**Comment by MasterPetrik** [comment]
can we evade API and loading and parsing pages directly?

**Comment by Bionus** [comment]
> can we evade API and loading and parsing pages directly?

Yes but it seems they updated the HTML so the Regex needs to be updated.

**Comment by MasterPetrik** [comment]
> this was answered on a newer forums turns out the cpu on the system running their API died or something.

![image](https://user-images.githubusercontent.com/22294259/33681661-41e9d80c-dad6-11e7-9526-4288f6efb929.png)

@Bionus Looks like Gelbooru API works again, and this was API server CPU overload problem. 
Good news, but still need to implement #1023 faster. Or guys like this(https://github.com/Bionus/imgbrd-grabber/issues/1169) woth his 40000 images downloaded from gelbooru in one try will overload it again soon enough.

**Comment by MasterPetrik** [comment]
also this issue could be closed now.
