### ISSUE TITLE
Derpibooru.org - Problem with showing the content

### ISSUE THREAD

**Issue by lanon44** [Bionus/imgbrd-grabber#1159]
SORRY I SPEAK SPANISH, I'M GONNA TRY TO BE AS CLEAR AS POSIBLE:
### What steps will reproduce the problem?
I made a search in derpibooru.org with the filter "artist:sundown", but the explicit (NSFW) content doesn't show. (I ashamed, don't judge me) anyway...

### What is the expected behavior? What do you get instead?
The expected behavior of the program is that it shows me the content, but i get less than a half of the results, instead of the full and the NSFW content.

### How often does this problem occur? On which sources?
Always on Derpibooru.org

### What version of the program are you using? On what operating system?
v5.5.2, windows 10

### Please provide any additional information below
I think this could be because on this site the setting filter EVERYTHING is not available on the program. Only at "PLUS" on rating but doesn't work. I need to log in on site options or what?

There show you some screenshots:
-Here's is the browser search result (1100 Pictures)
![1](https://user-images.githubusercontent.com/34048146/33347300-05c7958c-d458-11e7-8e76-67166fb87894.png)
-And here the program result (417 Pictures)
![2](https://user-images.githubusercontent.com/34048146/33347341-29c93d28-d458-11e7-8151-ed6ddc3ae2f8.png)

**Comment by Bionus** [comment]
You need to be logged in to access NSFW results on derpibooru.

You have to provide your API key in the "password" field of the source settings' "Credentials" tab:
![image](https://cloud.githubusercontent.com/assets/882719/24560572/95a4e494-1643-11e7-8d8c-0aab7a95c5a0.png)

You can find your API key in your account settings on derpibooru.

**Comment by lanon44** [comment]
I love you and you program, I would donate if i could... :(

**Comment by lanon44** [comment]
Sorry, but i have another problem...

(EDITING THIS COMENT WITH THE PROBLEM)

**Comment by KamillaPup** [comment]
I tried this and it isn't working for me. First off, there is no test button. Also, should the login tab be set to URL? I'm using 6.0.1

**Comment by Siriuson** [comment]
Found a problem. And you solved this problem. I solved the problem with the help of you.
Thanks. That this problem was created. And eliminate this problem.
Sorry for my English. I'm not from here.

Простите за мой английский. Я не местный.
Нашёл проблему. И вы решили это проблему. Я решил проблему, с помощью вас.
Спасибо. Что это проблема была созданна. И устранили эту проблему.
