### ISSUE TITLE
Unable to download the correct filesize on Rule34Hentai & Rule34.XXX

### ISSUE THREAD

**Issue by vector58** [Bionus/imgbrd-grabber#1160]
### What steps will reproduce the problem?
No specific steps.  I can reproduce the problem if I'm searching for a specific tag, all tags, 1 page, all pages.

### What is the expected behavior? What do you get instead?
Grabber will "download" the files, but the filesize is 0 

### How often does this problem occur? On which sources?
All the time. I've tried Rule34Hentai, Rule34.xxx so far.

**update** Just tried a different source (rule34.paheal.net) and it seems that one is running fine.

### What version of the program are you using? On what operating system?
5.5.2 / Windows 10

### Please provide any additional information below
I tried to download using both Rule34Hentai & Rule34.xxx sources and all files ends up having the filesize 0.  I did a few test to make sure if I'm doing something wrong before I decided to submit my issue here.

-Download all pages with tags "3d animated sound"
-Download all pages with only one tag
-Download all pages with no tags

I repeated the same test above using one page instead and still no luck
I also repeated the test on a different computer & location. No luck

Thanks!
![33337080-759613a0-d437-11e7-8796-720416034662](https://user-images.githubusercontent.com/34071973/33461517-6df92e3a-d5f8-11e7-8756-9daa615d8911.JPG)
![002](https://user-images.githubusercontent.com/34071973/33337082-75b1bc9a-d437-11e7-8f23-0a22cba62583.JPG)

**Comment by Bionus** [comment]
What's the contents of your log?
0 KB files definitely sound like some error occurred downloading the image.

**Comment by vector58** [comment]
Here's the log when trying to download with the tags "3d" & "animated"

[log.txt](https://github.com/Bionus/imgbrd-grabber/files/1514893/log.txt)

**Comment by vector58** [comment]
After reading the log, I realize I forgot to turn on https (under Source/Options/General).  I can now download the files with the correct size, but I stumble upon another problem.

Using the tags "3d" "animated", Grabber doesn't download all of the files displayed in the page. 

![001](https://user-images.githubusercontent.com/34071973/33392928-1cbde24a-d503-11e7-8dec-0ba1a96e9b2d.JPG)

![002](https://user-images.githubusercontent.com/34071973/33392969-3889d272-d503-11e7-86b9-b6a9882446b9.JPG)

Grabber is missing the 2nd picture. When I look at the tags on the 2nd picture, they are listed as the following:
"3D, 4ere4nik, Animated, Asari, Mass_Effect, Source_Filmmaker"
![003](https://user-images.githubusercontent.com/34071973/33393124-b7a5fb3a-d503-11e7-9338-7f33669555ba.JPG)

I tried to type in the tag "4ere4nik" by itself on Grabber but it wouldn't pull up any of its contents

**Comment by Bionus** [comment]
Did you put your credentials and login information in the source settings?

![image](https://user-images.githubusercontent.com/882719/33496102-32b31850-d6c9-11e7-87dd-ad5f0e7814d9.png)

![image](https://user-images.githubusercontent.com/882719/33496106-363747d0-d6c9-11e7-8464-28caa5974f70.png)

**Comment by vector58** [comment]
That works! Thanks! 

I had the Credentials tab filled out, but not Login tab. Login tab was set to "Through URL".  What does POST do exactly?

**Comment by Bionus** [comment]
I'll close the issue if it works then :smile:

You can have more information about the login methods here:
https://github.com/Bionus/imgbrd-grabber/wiki/WebsiteLogin#login-methods
