### ISSUE TITLE
source accessibility indicators in sources window

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1161]
Considering big problems(with issues spam) because of sankaku, and expecting same issues spam about gelbooru in the future...
And also because I think that it would be a good idea anyway, I suggest to check accessibility of sources sometimes and show special indicator beside problem source icon. It will show user that this souce is inaccessable right now for some reason. 
If grabber can't get images from this source(for any reason, doeasn't matter why, only result is matter) >> mark this source as inaccessable. And when user will open sources window, show him warning sign beside source icon. Would be good to show text message that that means that site is unaviable for user when he move his cursor on that sign.
A proper sign:
https://www.iconfinder.com/icons/11870/exclamation_icon#size=16
Thats how it should looks:
![2017-11-29_054005 win7 masterco re](https://user-images.githubusercontent.com/22294259/33356450-8e313c8c-d4cd-11e7-9ee0-149b062e848b.png)
Of course if in one of next searches this source will give images again, this sign should disappear.

And write somewhere that if users see this icon, that means problem is not with grabber, but with source accessability, and technical support will not be provided.

**Comment by MasterPetrik** [comment]
no response(

**Comment by Bionus** [comment]
Indeed that's a good idea. :+1:
It would help preventing most duplicates caused by "broken" sources.

>  If grabber can't get images from this source(for any reason, doeasn't matter why, only result is matter) >> mark this source as inaccessable. And when user will open sources window, show him warning sign beside source icon. Would be good to show text message that that means that site is unaviable for user when he move his cursor on that sign.

The problem is it's impossible to determine if a source is broken because of a legit API change (which would require an issue), because the integration is broken in the first place (also need an issue), or if the API/site is down (no issue).

The only legitimate way to do so would be a manual check. So someone (likely me), after seeing an issue type "Gelbooru API down" should check. Then, if the API was turned off like last week, update some URL (either a file on git or a wiki page) that will be later checked by Grabber to display warnings.

**Comment by MasterPetrik** [comment]
> The problem is it's impossible to determine if a source is broken 
because of a legit API change (which would require an issue), 
because the integration is broken in the first place (also need an issue), or
 if the API/site is down (no issue).

In fact, all these cases doesn't require an special issues from random users, who lazy enough to see previously posted same issues and too lazy to write proper description. Otherwise it will not solve issues spam problem.

The main goal of this suggestion is to show user that the problem is not in grabber work, but in source accesability(firewall/gov block/site down/closed API/API changes) - no matter which one is the real reason, - user need to know that grabber is fine, so he can go check his firewall, gov block list, site forum to solve his problem. Because go to Grabber dev with such questions are pointless. Because they are not grabber related anyway.

> The only legitimate way to do so would be a manual check. 

and with this indicator manual check will be easier than ever. You wouldn't need a issues called "sankaku isn't working" on your issue tracker, you will see THE SAME MESSAGE in the your source window, mostly those issues only report that site is unaviable(without reason investigation), but now you will be able to see it directly, without issue tracker as proxie. 
And also only several users qualified enough to find the reason, and this indicator will not stop them from creating an issue, because they want to tell about origin of the problem/suggest a solution, so such usefull issues will continue to appear.
