### ISSUE TITLE
Derpibooru.org - Problem with the downloaded images and quantity.

### ISSUE THREAD

**Issue by lanon44** [Bionus/imgbrd-grabber#1162]
### What steps will reproduce the problem?
1. Go to do my search
2. Put the tag of the artist
3. Finally with my previous problem now fixed, the results are complete (1100 images)
4. Go to "Get this page" then "Downloads" and i download the files.

### What is the expected behavior? What do you get instead?
I expect the download of the 50 images without any problem. Instead i get this:
![3](https://user-images.githubusercontent.com/34048146/33356940-fe53e9d6-d484-11e7-8044-ef2f27941902.png)
Only i get 15 elements and incomplete with the size 185 bytes in all. 

### How often does this problem occur? On which sources?
Always on Derpibooru.org

### What version of the program are you using? On what operating system?
5.5.2 / Windows 10

### Please provide any additional information below
Here i'm trying to download the 1100 images but i get the same result only that the window doesn't close after clicking on OK. And on that try only downloaded 330/330 images and not the 1100 images.
![1](https://user-images.githubusercontent.com/34048146/33356936-f3890cd4-d484-11e7-87e4-fc4a374cfeb9.png)
HERE'S THE LOG: [main.log](https://github.com/Bionus/imgbrd-grabber/files/1512472/main.log)

**Comment by Gaffnet** [comment]
Check those image files in a text editor.  They're probably HTML server error pages that were downloaded by Grabber.

I tried downloading a batch from Derpibooru and got the same result.  

This is what was in the "corrupt image" files I downloaded:

```<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```
What I've found is that any attempt at a batch download using Grabber on Derpibooru yields the above result.  This happens with all batch creation methods. I.e. "Get Page", "Get All" or "Get Selected." 

Images saved individually were saved correctly _most_ of the time during my test sessions, but I did get some 301 errors during individual image saves as well.

> Here i'm trying to download the 1100 images...

I'd recommend exercising some restraint.  It's this sort of thing that will get Grabber banned.

**Comment by lanon44** [comment]
They are not server errors. and yes, we have the same problem.

**Comment by Gaffnet** [comment]
> They are not server errors.

When those server error pages are saved, they're exactly 185 bytes; the same file size as you mentioned.

If you open those failed downloaded images in a text editor, what's shown?

**Comment by lanon44** [comment]
This... 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>

**Comment by lanon44** [comment]
This:
![03a2f1ae50b879c8bf1f774a72cbc57764058430ba14e3219ca5c98f71727f676d4d2030aba399bfffa7fabedecaf93b6ffeed86669b316cb1a714145fece9f6](https://user-images.githubusercontent.com/34048146/33409593-dfe21866-d541-11e7-91e0-a634537ed0a7.png)

**Comment by lanon44** [comment]
This
[1.txt](https://github.com/Bionus/imgbrd-grabber/files/1516308/1.txt)

**Comment by MasterPetrik** [comment]
> They are not server errors. 

You are wrong. That's a server errors indeed, with axactly the same text as @Gaffnet said:
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body bgcolor="white">
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>nginx/1.10.3</center>
> </body>
> </html>


@Bionus old problem with saving redirects/error server ansvers as images, huh.  Just like in https://github.com/Bionus/imgbrd-grabber/issues/1038

**Comment by lanon44** [comment]
So... There's no fix?
