### ISSUE TITLE
Gelbooru no longer works since November

### ISSUE THREAD

**Issue by theHubi** [Bionus/imgbrd-grabber#1164]
### What steps will reproduce the problem?

Whenever an image search is performed, rule34.xxx shows up instantly but gelbooru shows no results

### What is the expected behavior? What do you get instead?

Images load as usual. No images load at all

### How often does this problem occur? On which sources?

Every search on gelbooru only

### What version of the program are you using? On what operating system?

Windows 10 Pro x64 - I've tried 5.3.0, 5.5.0 and 5.5.2

### Please provide any additional information below
I've removed all blacklists, reinstalled the program, removed "added tags", nothing.
I'll try a different PC, but if it has worked for years now, why should it stop.
Know of any changes on gelbooru's side maybe?

**Comment by theHubi** [comment]
Oh. well there you go.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response success="false" reason="Search error: API disabled due to abuse."/>

**Comment by Gaffnet** [comment]
Gelbooru admins disabled the API.

Refer to issue https://github.com/Bionus/imgbrd-grabber/issues/1157

**Comment by MasterPetrik** [comment]
heh... here goes first duplicate of https://github.com/Bionus/imgbrd-grabber/issues/1157

**Comment by MasterPetrik** [comment]
and it's aready working. So this issue can be closed.

**Comment by MasterPetrik** [comment]
and it's not working again...

**Comment by Hrxn** [comment]
Gelbooru API disabled again?

**Comment by Bionus** [comment]
Closing since it works now and was caused by them disabling their API (nothing we can do).
The Regex fallback should work properly in those situations.
