### ISSUE TITLE
Tags in log files missing underscores

### ISSUE THREAD

**Issue by redlightnightlight** [Bionus/imgbrd-grabber#1166]
### What steps will reproduce the problem?
Setup grabber to save all tags to a log file.
Download anything.

### What is the expected behavior? What do you get instead?
Tags like "blue_eyes" are incorrectly saved as "blue eyes" in the log file.

### How often does this problem occur? On which sources?
Afaik every log file.

### What version of the program are you using? On what operating system?
Grabber nightly 385915a3
Windows 8.

**Comment by Bionus** [comment]
Are you sure you have the "replace spaces by underscores" enabled in your settings?

![image](https://user-images.githubusercontent.com/882719/33500750-32b223b2-d6da-11e7-9d81-75215914bc2d.png)

You can also enable it per-filename with the `spaces` or `underscores` options.

**Comment by larry-he** [comment]
Doh! How could I miss that.

**Comment by redlightnightlight** [comment]
Oh. Closed
