### ISSUE TITLE
Increase simultaneous downloads grater then 10 

### ISSUE THREAD

**Issue by satishbabariya** [Bionus/imgbrd-grabber#1167]
Is it possible to download 100 or 1000 simultaneous downloads

**Comment by MrCrackR** [comment]
Possible? Yes, but that would lead to more servers closing their API.
https://github.com/Bionus/imgbrd-grabber/issues/1157
https://github.com/Bionus/imgbrd-grabber/issues/1023

**Comment by MasterPetrik** [comment]
> Is it possible to download 100 or 1000 simultaneous downloads
even if you would do that, you will be almost instantly banned on all these sites due to organaizing DOS attack. 

Abusers like you - the reason why these sites are closing they API for every fair user, for everyone, incuding harmless browser scripts and IQDB. Shame on you!

**Comment by Rigabriezi** [comment]
I can't think of a good reason why you'd want it more than 1. For someone who is not very coding savvy is helps if simultaneous downloads are down to 1 so the order stays the same like it was uploaded. Then I don't have to try to mess with the filename box which apparently I'm terrible at.

**Comment by satishbabariya** [comment]
Thanks
