### ISSUE TITLE
Massive Image Amount issue

### ISSUE THREAD

**Issue by NWCampbell** [Bionus/imgbrd-grabber#1169]
### What steps will reproduce the problem?
Downloading all images from Gelbooru with the tag, Yuri.

### What is the expected behavior? What do you get instead?
Grabs all images and displays a progress bar

### How often does this problem occur? On which sources?
Only once, so far on Gelbooru but I will try to replicate it as soon as this infinite download is done.

### What version of the program are you using? On what operating system?
5.5.2

### Please provide any additional information below
Downloading a massive amount of images seems to go on forever?

The progress bar reached 100% however it is still downloading images past it's total projected files.

Started at 0/25,138 images with my tag search
I'm now at 28,982/25,138, the progress bar is empty with no percentage as it completed when it hit 100% but the lower progress bar goes up to 100% then restarts and keeps downloading images.
I go to the links of each image and they're unique and downloading new ones each time but I think the progress bar should be checked and see if there's some sort of cap on "total images found" when really it's far higher. At this rate I don't know when it will finish.
I'll update when it finishes.

**Comment by NWCampbell** [comment]
So it has progressed through 4 loops of 0% to 100% on the lower progress bar.

Remains "Batch 1" but restarts after 999 back to 1 for the image #

**Comment by NWCampbell** [comment]
[https://www.youtube.com/watch?v=8ZB0SzeRtRo&feature=youtu.be](url)

**Comment by NWCampbell** [comment]
STILL going strong, at 35,000 / 25,000

**Comment by NWCampbell** [comment]
![asstotroutorbasstomouth](https://user-images.githubusercontent.com/22357456/33583263-55a91a3e-d90e-11e7-88cb-6d55249a1786.png)

**Comment by NWCampbell** [comment]
37,000 and still going

**Comment by Bionus** [comment]
So from what I understand of the issue, the initial image count was wrong, as it shouldn't have been 25,138 but a much higher number? Since the download itself completed with no issues.

> So it has progressed through 4 loops of 0% to 100% on the lower progress bar.
> Remains "Batch 1" but restarts after 999 back to 1 for the image #

That's expected, Grabber downloads images by packs of 1,000.
