### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#1170]
Been getting them frequently- Also- clicking Ok once you've selected your sources seems to automatically do a search, which is something that causes a crash with the ammount of soruces I have unless I have tags in the field beforehand.
https://anonfile.com/l7gfj0dcb5/crashes.7z

**Comment by Bionus** [comment]
You mean searching without tags cause a crash, but not searching with tags?

**Comment by SultrySamthepennanceman** [comment]
Both, given my sources- I'd say it'd be an idea in future to slow up how Gelbooru Booru's are loaded into the grabber- which I suspect may be causing the crashes, because Gelboour 0.1 boorus are what make up most of the sources I use- I don't get crashes with certain selection sessions.

I should also tell you that the pre-set settings for chosen sources need a way to be backed up (external file/Export) So you can make a list of all the boorus you use to grant unto others- because I fucked up one once and had to start all over, and so far I've basically got a notepad which has a number of booru sources that fit a niche/genre and I add them to their unique session in grabber going back and forth checking them, and that took forever.

Also, Some more crashes, which relate to this subject- but anyhow may be other stuff in this file.
Happy Holidays! https://anonfile.com/P2nap3dfb6/crashes.7z
