### ISSUE TITLE
Inverted conditionals not working in conditional file names

### ISSUE THREAD

**Issue by SwordfishBooks** [Bionus/imgbrd-grabber#1171]
### What steps will reproduce the problem?
Create a conditional file name that contains an inverted conditional. I used:
%model% !%copyright%

### What is the expected behavior? What do you get instead?
Expected Behavior: The condition will only be applied to pictures that have at least one model tag and no copyright tags.

Actual Behavior: ~~The condition is applied to any picture containing a model tag, regardless of copyright tags.~~
EDIT: The condition is being applied to any image that contains a copyright tag and/or a model tag.

### How often does this problem occur? On which sources?
Every time. ~~On http://behoimi.org. (I haven't tested whether it works on other websites or not)~~. EDIT: It occurs on every site except anime-pictures.net and  zerochan.

### What version of the program are you using? On what operating system?
5.5.2 on Windows 7.

**Comment by Bionus** [comment]
Is ` %model% !%copyright%` the whole thing?
Because you need to use `<` and `>`, for example `<%model%> <!%copyright%>` or `<%model% !%copyright%>` depending on the result you want (multiple conditionals in the same condition mean AND).

**Comment by SwordfishBooks** [comment]
I've tried both of your suggestions, but I'm still having the same problem.
