### ISSUE TITLE
Question: How to assign multiple characters to filename?

### ISSUE THREAD

**Issue by Rigabriezi** [Bionus/imgbrd-grabber#1172]
I looked in the "Introduction" section and I'm still stuck. I can't even get Image Grabber to save more than the first three letters of a characters name let alone have it save the filename with every character that is in the picture. 

Have I messed with the settings or something?  
Edit1: I'm trying to download an image from E621 with 3 different characters in it and I'd like the filename or saved folder to reflect that. 
Edit2:the 3 character limit on filename save has been fixed with a full reinstall w/ appdata wiped
Now all I need is help figuring out to save filenames with multiple characters.

**Comment by Gaffnet** [comment]
You need to have the `%character%` token somewhere in your filename format.  This token handles multiple characters too.

For instance, the filename format of `%md5% %character%.%ext%` will produce a filename in this format:

E.g. `0d89f35db7913f86e6b7ad8793b2ec84 chiyo_masami.jpg`

Or for multiple tagged characters:
E.g. `3e470423e0a16d12fbe0fa6947f71df1 john_smith,takeda_kunitaro,joan_smith.jpg`

Also refer to the *Character Tags* options in Grabber.   The options are self-explanatory:

![grabber_character_tags_options](https://user-images.githubusercontent.com/13587501/33796918-0ed842bc-dccc-11e7-9732-0432d2d0d3de.jpg)
