### ISSUE TITLE
Curious about keyboard shortcuts and image preview adjustments

### ISSUE THREAD

**Issue by berrysoda** [Bionus/imgbrd-grabber#1173]
I looked around but couldn't find anything detailing keyboard shortcuts. I especially can't find anything that says how you can deselect all the images you have selected (via ctrl+click). additionally, is there any way to make the image previews in the search results area larger? I dug through settings but didn't really see anything for this.

**Comment by MasterPetrik** [comment]
> is there any way to make the image previews in the search results area larger?

Grabber didn't make thumbnails itself, it gets them from sites, and it will show it in original scale, for most boorus and other sites thumbnails sizes are 150x150 and Gtrabber shows them as is.

**Comment by Bionus** [comment]
> I especially can't find anything that says how you can deselect all the images you have selected (via ctrl+click).

There's no shortcut for that except de-selecting them manually (you can use range selection with Shift though). Also, adding them to the download list with "Get selected" should clear selection.

> is there any way to make the image previews in the search results area larger? I dug through settings but didn't really see anything for this.

As MasterPetrik said, the 150x150 limitation if from sites. However, there's an "upscaling" feature in the settings to force-resize them to higher resolutions (especially useful on 4K screens).

**Comment by FichteFoll** [comment]
Are there any shortcuts for the image viewer to save or save&close? I noticed you can use spacebar and backspace to navigate, but I haven't found a shortcut to save (or delete) the current image. Being able to browse entirely by keyboard would be neat.

If this is already possible, please add it to the documentation.

**Comment by Bionus** [comment]
@FichteFoll I just added a page listing all keyboard shortcuts, you can find it here:
https://bionus.github.io/imgbrd-grabber/docs/shortcuts.html

If you think some shortcuts are missing (for example for "Save & close" I think it's better to create a new issue (and suggest the keyboard combination you feel would make sense) 😄

**Comment by FichteFoll** [comment]
Thanks, this is a big help. I don't think there needs to be an extra binding for save & close when it's just two actions in one. You can simply press two key bindings.

If I notice something is missing, I'll create a new issue.
