### ISSUE TITLE
Upscaling doesn't work.

### ISSUE THREAD

**Issue by SemifKnight** [Bionus/imgbrd-grabber#1176]
### What steps will reproduce the problem?
A general search like "idolmaster rating:s" with multiple sources like danbooru.donmai.us, gelbooru.com, konachan.com with Merge results unchecked.

In Options>Interface, Upscaling is at 180% and in Interface>Search Results, "Use a fixed-image-width layout" is checked.

I've tried a full uninstall, as well as deleting the C:/Users/Username/AppData/Local/Bionus/Grabber folder contents as well before reinstalling.

### What is the expected behavior? What do you get instead?
The thumbnails are supposed to be resized bigger, but instead, the spaces between the thumbnails get bigger as if to make space for a bigger thumbnail, but the thumbnail sizes remain the same. Except for konachan.com, where they are somehow bigger but still seem to have an upper limit depending on higher Upscaling settings.

### How often does this problem occur? On which sources?

I've only noticed it recently when I tried to change the Upscaling, and so far it always occurs when the Upscaling is on.
Sources I've used: gelbooru.com, danbooru.donmai.us, konachan.com

### What version of the program are you using? On what operating system?
Grabber 5.5.2
OS: Windows 10 Home 64-bit

### Please provide any additional information below
Screenshot: https://i.imgur.com/ZDqStks.jpg
![grabber](https://user-images.githubusercontent.com/34590104/34075820-8ca0dd02-e30d-11e7-8eb8-76fc69d47994.jpg)

(P.S. I changed the username for privacy reasons. Also, the wiki doesn't work?)

**Comment by MasterPetrik** [comment]
Can confirm the problem.

Downscaling to 50% works good, all thumbnails resizes.
![2017-12-16_074020 win7 mastercore](https://user-images.githubusercontent.com/22294259/34075051-6e0ca402-e2cc-11e7-8b3f-22035237f4d5.png)

But upscaling to 200% work bad, only items size in the grid becames bigger, but images do not upscales.
Obviously a bug.
![2017-12-16_074040 win7 mastercore](https://user-images.githubusercontent.com/22294259/34075062-9efead1c-e2cc-11e7-8736-bfe0726ce49d.png)

**Comment by Bionus** [comment]
Yes, I could also reproduce. I'll be fixed in 5.5.3.

> Also, the wiki doesn't work?

Indeed, it seems to have been broken recently. I also pushed a fix.
