### ISSUE TITLE
Need wiki text update

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1177]
![2017-12-16_071528 win7 mastercore](https://user-images.githubusercontent.com/22294259/34075812-2157c63e-e2e3-11e7-97cc-3190a3031b02.png)

### Need to update source list.
**add**
https://anime-pictures.net

**remove** 
ichijo.org
sankaku complex sources
genso.ws

### Need to update languages list
**add**
Spanish
Chinese

**Comment by Bionus** [comment]
I just updated it, thanks. :smile:

Indeed, it was pretty out of date, so I updated it for now. But given most of this page's information is already present on the read me, it seems pretty superfluous to keep it.
