### ISSUE TITLE
Ignore images in a batch download based on the presence or absence of certain tags

### ISSUE THREAD

**Issue by SemifKnight** [Bionus/imgbrd-grabber#1178]
Question/Feature suggestion
For example, I want to download the images with the tags "dress boots" but I want each image to have at least 1 girl in it.
Is it possible for images to only be downloaded if tag 1girl or 2girls or multiple_girls is present? Such that an image with tags like 1boy would be ignored for download IF it didn't have at least one of the other "girl tags" present.
I tried looking in the wiki, but it didn't seem to be covered.

The best I got is something like:
Custom token: %girls_present% (1girl 2girls 3girls 4girls multiple_girls)

And filename: dress boots/%count% %md5% <DELET !%girls_present%>.%ext%

And when the download is finished, searching the files with "DELET" and then deleting them. (This also didn't seem to work for konachan, which didn't use any of the %girls_present% tags according to my test.)

---
Also, how does the "Ignored tags" feature work? The description only says "These tags will not be taken in account when saving image." (Also, I think it should be "These tags will not be taken into account when saving images.")
Will the ignored tags not be put in the filenames or something?

**Comment by MasterPetrik** [comment]
> This also didn't seem to work for konachan, which didn't use any of the %girls_present% tags according to my test.

Different sites uses different tags systems sometimes, but dev already working on merging tags feature, but it's not so easy? so maybe one day it will be solved.

**Comment by Bionus** [comment]
>  For example, I want to download the images with the tags "dress boots" but I want each image to have at least 1 girl in it.

This sounds like a mission for the "post-filtering" feature! It allows to re-search the results returned and only download the images matching it.

In your case, using "%girls_present%" as a post-filter should do the trick (note that "1girl 2girls 3girls 4girls multiple_girls" wouldn't as it would require all those tags to be present).

Unfortunately, tokens are not supported as post-filters in 5.5.2! I'll add them in the next version, so you should be able to use that once released (or using nightly).

> Also, how does the "Ignored tags" feature work? The description only says "These tags will not be taken in account when saving image." (Also, I think it should be "These tags will not be taken into account when saving images.")
> Will the ignored tags not be put in the filenames or something?

Yes. Let's say you have two tags often/always together, for example `fate/stay_night` and `fsn` (a good source would have them as synonyms but let's use this for the example). You could use the "user shorter" copyright feature, but that doesn't work in this case, so you might end up with "multiple" if you use `%copyright%` (depending on your settings). Now, if you ignore `fsn` it won't be saved in the filename, and `%copyright%` will (properly) give `fate_stay_night`.

**Comment by SemifKnight** [comment]
> In your case, using "%girls_present%" as a post-filter should do the trick (note that "1girl 2girls 3girls 4girls multiple_girls" wouldn't as it would require all those tags to be present).
> 
> Unfortunately, tokens are not supported as post-filters in 5.5.2! I'll add them in the next version, so you should be able to use that once released (or using nightly).

Oh, I see.  I think it's why I had to use it in the filename instead. Glad to hear it's going to be in the next release. :)
