### ISSUE TITLE
Question: How do i set yande.re filename like in other boorus? 

### ISSUE THREAD

**Issue by GiRaFa-SM** [Bionus/imgbrd-grabber#1181]
Well, ive been trying some combinations to make files downloaded from other boorus have the same tags than yande.re files... Anyone know how to do this? If its not possible, how to include some important tags (like what that char is wearing and things like this, for quick finding)

**Comment by Bionus** [comment]
What do you mean "yande.re filename"?
Did you check the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) wiki page?

AFAIK yande.re simply uses something like `yande.re %id% %tags%.%ext%`.

**Comment by GiRaFa-SM** [comment]
For example, when you download a pic from yande.re it comes with 1 or 3 tags of what that char is wearing, for example in this one "yande.re 428425 adachi_shingo heels pantyhose sword sword_art_online thighhighs.jpg"
Link for the pic: https://yande.re/post/show/428425
when you download it it keeps the filename.

If you download from danbooru, the original filename has characters, copyright, artist, md5 and extension. What im asking is how can i set Grabber to download the pictures from other boorus with smaller filenames but with important tags, it would be a lot easier find something in a swarm of pictures. 

Keep in mind that if i set %tags% in filename configs in other boorus, i have files with giant filenames and they dont even include all the tags, i imagine thats because yande.re has a smaller repository of tags if compared with danbooru or even gelbooru. 

Thank you.

**Comment by Bionus** [comment]
> but with important tags

Then you would have to define "important tags". If it's all tags from yande.re, you should list them and use them as a custom token (e.g. `%yandere_tags%`).

As for getting the tag list, there's the Grabber CLI, the "tag import" in the "Tools" menu (to generate a local SQLite database that you'll have to read afterwards), or use the yande.re API directly.

**Comment by GiRaFa-SM** [comment]
I did this once and i havent downloaded anything since (it says the yande.re tags repository has 76.000 tags) but after closing the aplication it seems it couldnt find the tags downloaded and im downloading them again.

Well, another question, what filenames do you usually set in your files? I prefer danbooru like filenames, but like i said, its harder to find an specific pic if you have lots of pics in a folder.

**Comment by GiRaFa-SM** [comment]
by "tag import" you mean tag loader? because i havent found that option, and after finishing downloading the tags i set this '%yandere_tags%' on filename settings but no changes/sucess.

Can you give me a light of how do i do this?

**Comment by GiRaFa-SM** [comment]
pls help?

**Comment by TheWizardAlt** [comment]
It looks like the database generation doesn't work for me, I'll manually rip all the tags from yandere and create the setting you need for the config.

Or if you already have the tags, you need to some how copy them into the box in options > save > custom token > add custom token 
name => %yandere_tags%
tags => paste all the yandere tags here OR put just the tags you want from yandere.

Reading your original post, you made it sound like you wanted just clothing items so you could also make 
name => %clothes%
tags => clothing items ie: "leggings socks dress shirt" (ect)

**Comment by GiRaFa-SM** [comment]
I dont have, and even saving in the program seems to not work. 
I have yande.re tags downloaded through another program, but i'm not really sure how should i paste them there...

**Comment by TheWizardAlt** [comment]
yes, so try what I said. Are you trying to literally add all the yandere tags?

**Comment by TheWizardAlt** [comment]
![Custom Token](https://user-images.githubusercontent.com/37279010/37811112-1cf43ad0-2e26-11e8-9daa-c07964cc2119.gif)

**Comment by TheWizardAlt** [comment]
That will make any of those tags show up when you use %clothing_items% in your file name

**Comment by GiRaFa-SM** [comment]
Actually, i wanted one important (easy to identify) characteristic about an image, and looks like yande.re repository is very small, so when we save something from there it aways include one of these tags, it can be clothing, background (most of time its clothing or an accessory). 
like this one: yande.re 428425 adachi_shingo heels pantyhose sword sword_art_online thighhighs

So i guess you're right. Just a question, where i can download all yande.re tags? Downloading through grabber doesnt seems to work, and i have no idea how to download them. 

Srry for this long discussion, maybe its my bad english.
