### ISSUE TITLE
Connection refused using rule34.paheal.net and serious issues resuming session on new computer with backup files

### ISSUE THREAD

**Issue by xecus922** [Bionus/imgbrd-grabber#1182]
### What steps will reproduce the problem?

Issue 1: Use rule34.paheal.net as your source on a fresh install then try viewing a few images using grabber.

Issue 2: Move contents of the backup folder from a previous computer hard drive to a new computer hard drive to the root directory of Grabber (where .exe is located).

### What is the expected behavior? What do you get instead?

Issue 1: The image is supposed to just open in the popup window to view the larger size but instead that stops while the image is loading and a connection refused error is thrown. 

Issue 2: Was hoping to be able to resume my previous session with the tabs and favorites there while browsing rule34.paheal.net but moving my Grabber backup files to the new Grabber folder makes the site unusable and now I'm only able to view the images there if I'm on a fresh Grabber installation with secured connection checked off which I didn't have to do before on a previous version of Grabber.

### How often does this problem occur? On which sources?

Always. Source: rule34.paheal.net

### What version of the program are you using? On what operating system?

Version 5.5.2 on Windows 10 Pro 64-bit

### Please provide any additional information below

So there are two issues here giving me serious headaches trying to use Grabber after installing this crappy Windows 10 OS (was forced to for support of newer intel CPU and to avoid other issues with new hardware support) and building a new PC.

The first issue is that for some reason I'm not able to view images using Grabber from rule34.paheal.net now. I get connection refused errors every time which I suspect to be the site owners themselves blocking connections from programs like Grabber somehow but I hope this isn't the case. 

And the second issue is that while I have my backup files containing my favorites and previous Grabber session tabs from my older computer, I'm not able to import them to a new Grabber installation on my new computer's main hard drive without having rule34.paheal.net ceasing to work. When I place my backup files (from the appdata location on previous hard drive) into the root directory of my new Grabber installation on the new hard drive's root directory (not sure if I should be placing the backup files somewhere else but I read that I can just place those files all in one place and can make Grabber portable anyway) I'm not able to view images on rule34.paheal.net anymore. 

Hope you can help me with this and hopefully this helps you too with making Grabber even better! Thank you so much for having Grabber create backups for our favorites and session tabs as this is extremely important for people like me that keep loads of favorites and session tabs and sometimes we have to move them to a new computer so it's nice to have them in actual files that can be easily imported without running into any software issues, losing the favorites and previous session tabs with the importing process itself. 

I just want to be able to move my favorite tags and session tabs to the newer Grabber installation and browse my favorite imageboards with no issue.

Also here is a screenshot of the connection refused error I get trying to view images on rule34.paheal.net: https://imgur.com/a/4tDNa

**Comment by MasterPetrik** [comment]
seems connected with Connection Refused #1180

**Comment by billsargent** [comment]
I know for a fact that rule34.paheal.net has limits on how fast you can access the site. Too many connections per second results in a temporary block. I learned this when I used perl to rip the entire site a year ago or so. I had to download with 1 connection per second or even sometimes every 1.5 seconds. Its locked down to keep programs like this from copying the site. As of right now, I can't even get a tags list without being locked out of the site.
