### ISSUE TITLE
Toggle for reversing function of left click and ctrl + left click

### ISSUE THREAD

**Issue by SemifKnight** [Bionus/imgbrd-grabber#1183]
## Suggestion:
This was inspired by a similar feature I saw in a puzzle app on Android. It had a toggle to change the long press and tap functions because a user might want to make several long press actions in a row instead of what the tap function regularly does.

*Added a screenshot of the game showing the toggle as well as the icon they used:
![android game long press toggle screenshot small 2](https://user-images.githubusercontent.com/34590104/34607712-c6b7cc0c-f24f-11e7-85b3-dce1131a7dd1.png)

### Reasoning
For Grabber, I use it to download lots of images I like, so that they are ready for viewing in my own time. I prefer to download whole images in batches because of my low-bandwidth connection, and I don't like having to wait for images to load, so the few times I left click on an image is to view the tags. Even more rarely will I left click to view an image in Grabber.

Therefore, a lot more of my left clicks (probably more than 90%) in the Search results are for selecting which images to get for download, rather than viewing them and their tags individually (because of them having to load again and again, very slowly.) This kills the pinky because of having to hold ctrl down for more than 90% of the clicks.

### Description of feature suggestion
The toggle would make the left click behave as if ctrl is held down (for selecting multiple images), and make ctrl+left click behave like a regular left click (for viewing in the Image window.) This is similar to the toggle crouch vs hold crouch options in FPS games. (Guess which one I use, hahaha)

### Mockup
![grabber - invert ctrl lclick mockup 001](https://user-images.githubusercontent.com/34590104/34599873-93870e62-f22f-11e7-9002-d1178f611cf4.png)   
I think it should be in the search results and easily-accessible.
Maybe it doesn't need the word "functions" because it's a bit on the wordy side, already.

---
This toggle might also be able to prevent something that happened long ago, wherein I had a big page with my selection of images, and then I accidentally opened an image (ctrl must've not been pressed) which crashed Grabber and lost my selection.

**Comment by MasterPetrik** [comment]
> This was inspired by a similar feature I saw in a puzzle app on Android. 

well, it's not a good idea to compare PC programms and android apps, they uses completely different GUI.

> Reasoning
> Description of feature suggestion

Your idea is clear enough, adding such function probably will no harm anybody, and don't looks hard to implement, but I totally disagree with your mockup.

> I think it should be in the search results and easily-accessible.

This is very specific function, also your checkbox have too big description, it will be even longer in other languages translations, which is bad. Also it suits bad in this bar. Left side of it is about sources and right side is about getting images. Adding there another coplitely different themed checkbox will only add visual rubbish to the GUI. And moreover you are the first one with such way of using grabber, which means that this function is not so needed for others.

## What's my contrsuggestion:

- Add changing selecting mode checkbox into settings, with proper description
- Add a hotkey for quick switching selecting mode

I guess that will satisfy you?

**Comment by Bionus** [comment]
I have to agree with MasterPetrik here, putting a setting here would take too much space. At best, it could be placed in the "More" area under the search bar but that's it. Even then, that's still a very specific feature, so I'd rather put it in the settings window.

Also, from the description of the issue, I don't even understand why it should be "easily accessible". If more than 90% of your clicks are <kbd>Ctrl</kbd>+<kbd>Click</kbd>, why would you ever disable this feature? By enabling it, less than 10% of the clicks would require <kbd>Ctrl</kbd>, so your pinky should be able to rest.

For the time being, I'll simply add the setting. While adding a hotkey isn't much work, if someone where to do it by accident it would be **very** hard for him to disable it afterwards.
