### ISSUE TITLE
Gelbooru no longer working

### ISSUE THREAD

**Issue by sno0ks** [Bionus/imgbrd-grabber#1184]
### What steps will reproduce the problem?
Just try to search something in Gelbooru and no results are returned.

### What is the expected behavior? What do you get instead?
I should be getting results from Gelbooru. lol

### How often does this problem occur? On which sources?
Gelbooru. Happens every time.

### What version of the program are you using? On what operating system?
5.52. Win8.1 64

**Comment by MasterPetrik** [comment]
meh... another duplicate of #1157

**Comment by Dzenrei** [comment]
Gelbooru downloading still not working?

**Comment by Cantiel** [comment]
it was working for me for a while in the past month but now stopped again, so i guess they re-enabled it for a bit to test things but have it currently dissabled again
