### ISSUE TITLE
Question: I will be f*cked if I move the files from the folder Grabber is saving them?

### ISSUE THREAD

**Issue by BakuDM** [Bionus/imgbrd-grabber#1188]
Currently I am downloading a shit ton of images from yande.re and my SSD will probably run out of space before I finish it, when it happens I will pause the download, move the already downloaded images to my HDD and continue downloading, the question is, Grabber will keep downloading where it stopped or it will be like torrent that will Scan the folder to see what is already downloaded and keep from there? Because if it scans to see what is already downloaded and I moved the images from the folder, it will start downloading everything again?

Thanks for the Grabber btw, you're a genius.

**Comment by BakuDM** [comment]
Thanks for the answer, I will do that.
Another question, if I pause the download, turn off my PC then turn it on again and load the .jgl file to continue downloading, it won't download what I already downloaded right? Because the image counter down there starts from 1/XXXX again and today it downloaded some duplicates images for some reason.

**Comment by Cantiel** [comment]
it will restart from the beginning, but if you set the download directory correctly, it should find and skip all pics that you already downloaded. at least that happens to me when my pc decides to restart for an update while i'm letting it download afk

**Comment by Bionus** [comment]
I also advice to not download directly to an SSD. The writing speed is not necessary for downloading images using Grabber, and as you said depending on how much you download it may get full.

> Grabber will keep downloading where it stopped or it will be like torrent that will Scan the folder to see what is already downloaded and keep from there

If you moved the files to another folder without telling Grabber, it will re-download them again, unless you enabled the MD5 list feature. With this feature enabled, Grabber will keep a list of all downloaded files' MD5s and will not download them again (see "Options > Save > If a file exists globally"). Make sure to update the MD5 list after moving the files though, using the "Tools > MD5 list fixer".

In addition to this feature, if a file with the same name already exists in the destination directory, Grabber will not download the file again.

So you have two options after moving the files:
* Updating the MD5 list (using "Tools > MD5 list fixer"), then keep downloading to the SSD
* Change your destination folder to download to the same folder you moved the files to, on your HDD (note that even with this solution I still advice to update the MD5 list if you want to use this feature)

Also, while the files are not downloaded, Grabber will still restart the download from the beginning. So the images won't get downloaded, but the pages will. It shouldn't be a huge problem if you don't do it that often.
