### ISSUE TITLE
Sankaku search fails after more than 2 exclusion tags

### ISSUE THREAD

**Issue by oddyeus** [Bionus/imgbrd-grabber#1191]
### What steps will reproduce the problem?

Logging into the Sankaku source successfully, then searching with any more than two exclusion tags.

### What is the expected behavior? What do you get instead?

Expected behaviour is for the search to succeed with up to four exclusion tags. Instead, the search reveals 0 results beyond 2 exclusion tags, even when the search would work on the site itself.

### How often does this problem occur? On which sources?

Constantly, on the Sankaku source (perhaps on other sources too, untested).

### What version of the program are you using? On what operating system?

5.5.2, Windows 7 Ultimate

**Comment by Bionus** [comment]
On Sankaku:

> Non-members can only search with up to 2 operator tags at once

That means you have to be logged in to search with more than 2 operator tags. Make sure you put your credentials properly in the source's settings:
https://github.com/Bionus/imgbrd-grabber/wiki/WebsiteLogin
