### ISSUE TITLE
danbooru issue when downloading (some) deleted images

### ISSUE THREAD

**Issue by loitoses** [Bionus/imgbrd-grabber#1193]
### What steps will reproduce the problem?

Trying to download some images from danbooru that were deleted

### What is the expected behavior? What do you get instead?

Grabber attempts to download these images in different formats (png, gif, jpeg, etc) but never realizes that the solution is to add "/cached/" to the url. For example, it attempts to download https://danbooru.donmai.us/data/__kanna_pokemon_drawn_by_kiryu_manzoku__299f3bfafafc09684d6f7f67d05a14b3.jpeg , when the working url is https://danbooru.donmai.us/cached/data/__kanna_pokemon_drawn_by_kiryu_manzoku__299f3bfafafc09684d6f7f67d05a14b3.jpg . Not all deleted images have this problem and I don't know what triggers it (very old images seem to work fine, for example)

### How often does this problem occur? On which sources?

I dont know what triggers it. Its happening with some Pokemon images that are around 5 or 6 years old at least. Havent seen it with older pics (seem to be hosted in a different server) or earlier pics.

### What version of the program are you using? On what operating system?

Version 5.5.2 windows 10. Btw, great job with grabber, helps a lot

**Comment by Bionus** [comment]
I can't reproduce on my end, on Danbooru XML API:
https://danbooru.donmai.us/posts.xml?tags=md5:299f3bfafafc09684d6f7f67d05a14b3

Grabber read the `<file-url>` which is correct for this image, so it's downloaded properly.
Could it be that you are not using the XML (or JSON) API, but the Regex one?
