### ISSUE TITLE
Stoping after 100 images

### ISSUE THREAD

**Issue by Magophl** [Bionus/imgbrd-grabber#1194]
### What steps will reproduce the problem?

Just try to download something

### What is the expected behavior? What do you get instead?

i try to download a tag, download stops after 100 images.
i can close and open the Grabber so it's stops after more 100 images.

### How often does this problem occur? On which sources?

Always, with everything

### What version of the program are you using? On what operating system?

5.5.2 windows 10

**Comment by Bionus** [comment]
Which source are you trying to download from?
Can you upload you IGL file?

**Comment by Magophl** [comment]
I tried every source, it only stops after 100 images with tags using "-" or "_" idk why.
where i can find that IGL file and my log?

**Comment by Magophl** [comment]
I fixed it... i did go to tools > sources and i put the ecxatly numbers of image per page

**Comment by Magophl** [comment]
nope, the same problem again but it's stops in a random number of images.
