### ISSUE TITLE
Sankaku search results bring no images

### ISSUE THREAD

**Issue by dpyne** [Bionus/imgbrd-grabber#1198]
It seems that everytime I would search for anything on Sankaku as a source, i would always get a page 1 of 0(0 of max 0) as a result. This doesn't seem to apply to any other source.

**Comment by Thelockest** [comment]
Just found a fix for it 
1.open sources 
2.click on the one that's not showing anything in this case click sankaku options.
3.Navigate over to the headers tab (for some reason it seems like the one supplied stopped working/)
4.Replace User-Agent value with:Mozilla/4.78 [en] (Windows NT 5.0; U)

**Comment by dpyne** [comment]
Thank you, it seems to have worked.
