### ISSUE TITLE
Grabber Dont Load some Pictures

### ISSUE THREAD

**Issue by sam7045** [Bionus/imgbrd-grabber#1200]
### What steps will reproduce the problem?
grabber dont load any pictures

### What is the expected behavior? What do you get instead?

o dont get some pics

### How often does this problem occur? On which sources?
the problem still exists

### What version of the program are you using? On what operating system?
grabber v5.5.2 on Windows 10 and Windows 2016 Datacenter

### Please provide any additional information below
When I start the program and start looking for pictures, no pictures will ever be found.
![unbenannt](https://user-images.githubusercontent.com/36340071/36065408-8f69f2f4-0e9a-11e8-859a-d5d24009f798.PNG)

**Comment by Bionus** [comment]
Does the log tab say anything?
It's quite surprising that none of those sources would return anything.
