### ISSUE TITLE
Question: How to search by upload date, or only pictures from the last week?

### ISSUE THREAD

**Issue by VimRedPanda** [Bionus/imgbrd-grabber#1201]
Sorry if this is a dumb question, but I've downloaded a lot of a big tag, I'd like to stay up to date on this tag without having to go through all 10,000 images again.

Is there a way to search for posts that have been posted after a certain date, or get rid of posts that were uploaded before a certain date?

If this isn't possible, is there a way I can download images I haven't downloaded before, there are so many images in the tag I search that it takes a long time for imgbrd-grabber to even check if I have it, and I wouldn't want it downloaded again if I decide I didn't like the image and deleted it.

Side note: I already tried the date function next to the search bar and clicked on a date a week ago, but this seemed to ignore the original tag I wrote, and showed images that didn't have the tag.

Sorry for the long post, thanks in advance.

**Comment by Bionus** [comment]
Sorry for the late reply!
It seems my answer didn't send two weeks ago when I wrote it. I'll write it again.

It depends on the source.
* On Danbooru (and deviated sites), you can use the `date` or `age` meta-tags, like `date:>2018-03-06`. Their usage is pretty well documented here: https://danbooru.donmai.us/wiki_pages/43049
* On Gelbooru (and deviated sites), they don't have this feature. You can however use the `id` metatag, like `id>4000000`. You can also find some documentation here (not as good as Danbooru's): https://gelbooru.com/index.php?page=help&topic=cheatsheet
* On other sources, you usually can't.

I'm currently working on a feature that would help keep tags up-to-date in the next version though, so I guess you'll be able to use that when it's out (it will automatically check if there are new images, and if so download them).
