### ISSUE TITLE
Behoimi and idol.sankakucomplex not displaying any results

### ISSUE THREAD

**Issue by ayacchin** [Bionus/imgbrd-grabber#1202]
### What steps will reproduce the problem?
Selecting either behoimi.org or idol.sankakucomplex.com as a source and then searching for any kind of tag.

### What is the expected behavior? What do you get instead?
I get the "No result" message instead of actual results when using said sources.

### How often does this problem occur? On which sources?
Everytime I use both behoimi.org or idol.sankakucomplex.com.

### What version of the program are you using? On what operating system?
5.5.2 on a 64-Bit Windows 7 OS 

### Please provide any additional information below
Other sources such as Danbooru and Gelbooru work as intended and with no issues at all.

**Comment by CaoCaoBeard** [comment]
Bionus stated that the developer of Sankaku Complex is constantly updating their API to prevent programs such as Grabber to perform any mass downloads. So, likely they updated their API again with improved security. 

https://github.com/Bionus/imgbrd-grabber/issues/997#issuecomment-323207320

**Comment by Thelockest** [comment]
Change the User-Agent
1.open sources
2.click on the one that's not showing anything in this case click (insert url name here) options.
3.Navigate over to the headers tab (for some reason it seems like the one supplied stopped working/)
4.Replace User-Agent value with:Mozilla/4.78 [en] (Windows NT 5.0; U)

**Comment by Rezboa** [comment]
Hey this last thing helped me, but they keep changing the API. I guess we should just use their app.
