### ISSUE TITLE
%num% doesn't exists

### ISSUE THREAD

**Issue by DevYama** [Bionus/imgbrd-grabber#1204]
Shown in wiki. Gives the token doesn't exists error.
![screenshot_20180221_211032](https://user-images.githubusercontent.com/26037681/36500012-b07f7e14-174b-11e8-9fcd-a22a7428f4f0.png)

**Comment by Bionus** [comment]
Indeed, it seems not to be in the list of allowed tokens in the filename, even though it works properly (you just have an useless warning).

I'll add it to the list for the next version.
