### ISSUE TITLE
Re-add Sankaku please

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1205]
The admin of Sankaku is incompetent, dishonest and awful at managing a booru. Clearly he's insecure, which is why he demanded it to be removed from Grabber. If he didn't add so much bloat and time-outs on Sankaku, nobody would think about using third-party applications to access his booru.

Please re-add Sankaku to Grabber. Pretty much nobody can stand using Sankaku with a browser for many reasons.

**Comment by GiRaFa-SM** [comment]
DanbooruDownloader works on sankaku though, altho, its a lot slower while loading pages for some reason.
