### ISSUE TITLE
Searching Doesn't Work On Any Website

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#1206]
### What steps will reproduce the problem?

1. Open up Grabber
2. Try to search something

### What is the expected behavior? What do you get instead?

When trying to search up something on any website there are no results and the tag loader shows 0 tags

### How often does this problem occur? On which sources?

All the time, on the latest version on the "releases" page 

### What version of the program are you using? On what operating system?

I am using v5.5.2 on Windows 10 LTSB

### Please provide any additional information below

None

**Comment by Bionus** [comment]
Could you give your log? There might be some useful information in there.

**Comment by jollyjester** [comment]
@Bionus How can I find the log?

**Comment by Bionus** [comment]
It's the last tab in the UI.
Or the `main.log` file in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`.

You must first run the program and do a search for it to be filled with info.
