### ISSUE TITLE
Is there a way to enlarge all search images?

### ISSUE THREAD

**Issue by MorganIsFreeman** [Bionus/imgbrd-grabber#1207]
The images are so small for some of the sites, I have to squint just to make out what they are. Is there anyway to enlarge the search images at all?

**Comment by natanfudge** [comment]
![image](https://github.com/Bionus/imgbrd-grabber/assets/25990014/dcd62ddd-d6f7-47a3-9e41-2c43524d1ec2)
Omfg

**Comment by NS-Clone** [comment]
> ![image](https://private-user-images.githubusercontent.com/25990014/315964847-dcd62ddd-d6f7-47a3-9e41-2c43524d1ec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjA1MzYsIm5iZiI6MTcxMTEyMDIzNiwicGF0aCI6Ii8yNTk5MDAxNC8zMTU5NjQ4NDctZGNkNjJkZGQtZDZmNy00N2EzLTllNDEtMmM0MzUyNGQxZWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE1MTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZWJjZDIyNTUxYjM0NDhjMjE0NzNjMmRhMGU4NjNmMmI4Y2ViYmJhYzYxZGE3NGI2M2Y5ZjY2Yzc5ZDJkY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z6KkVxIDrlcHLbFL2_39fE_l1qgxF0ttUQfT2zNCl7I) Omfg

and usually "This thread is locked"
