### ISSUE TITLE
compilation errors (Linux Mint 18.3)

### ISSUE THREAD

**Issue by chrisrlink** [Bionus/imgbrd-grabber#1208]
### What steps will reproduce the problem?
on a Ubuntu system after "cmake .." compiles make script ok once i try make in build directory i get alot of errors
installed pkgs: openssl cmake qtbase5-dev qtconnectivity5-dev (for qt network) qtmultimedia5-dev qtdeclaritive5-dev 

### What is the expected behavior? What do you get instead?
make completes is whats suppose to happen but i get this:

npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm [ 35%] Building CXX object lib/CMakeFiles/lib.dir/src/downloader/download-query-group.cpp.o
ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sites@ build: `tsc -p tsconfig.json`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sites@ build script 'tsc -p tsconfig.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sites package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p tsconfig.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sites
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sites
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm [ 36%] Building CXX object lib/CMakeFiles/lib.dir/src/downloader/download-query-image.cpp.o
ERR!     /home/chris/imgbrd-grabber/release/sites/npm-debug.log
CMakeFiles/sites.dir/build.make:60: recipe for target 'JavaScript_sites' failed
make[2]: *** [JavaScript_sites] Error 1
CMakeFiles/Makefile2:100: recipe for target 'CMakeFiles/sites.dir/all' failed
make[1]: *** [CMakeFiles/sites.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

i do not recall needing npm in previous builds (same version,development branch)

### How often does this problem occur? On which sources?

every time, development branch

### What version of the program are you using? On what operating system?
using development 5.5.2, currently on linux mint 18.3 but suspect all ubuntu flavors are affected cause I also tried compiling on ubuntu mate 16.04 same problem

**Comment by Bionus** [comment]
> i do not recall needing npm in previous builds (same version,development branch)

Yes, this is because of issue #1175. Sources will be migrated to TypeScript to make it easier for contributors to add new sources without any knowledge of C++ or of Grabber's inner code.

>  npm ERR! sites@ build: tsc -p tsconfig.json

If you go to `release/sites/` and run ` tsc -p tsconfig.json` manually, what output do you get?
What about `./node_modules/.bin/tsc -p tsconfig.json`? (if the previous says "binary tsc does not exist" or equivalent)

Thanks :smile:

**Comment by chrisrlink** [comment]
after installing node-typescript i get and using the above command 

/usr/lib/nodejs/typescript/tsc.js:37290
            var jsonOptions = json["compilerOptions"];
                                  ^

TypeError: Cannot read property 'compilerOptions' of undefined
    at getCompilerOptions (/usr/lib/nodejs/typescript/tsc.js:37290:35)
    at Object.parseJsonConfigFileContent (/usr/lib/nodejs/typescript/tsc.js:37280:22)
    at parseConfigFile (/usr/lib/nodejs/typescript/tsc.js:37572:40)
    at performCompilation (/usr/lib/nodejs/typescript/tsc.js:37584:45)
    at Object.executeCommandLine (/usr/lib/nodejs/typescript/tsc.js:37557:9)
    at Object.<anonymous> (/usr/lib/nodejs/typescript/tsc.js:37893:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

**Comment by chrisrlink** [comment]
also 2nd command yields /usr/bin/env: ‘node’: No such file or directory

**Comment by Bionus** [comment]
You should only need `typescript` (`npm install typescript`), not `node-typescript`.
It should have been installed automatically by NPM (`npm install`) through CMake when you ran `make`.

The error you sent is likely caused by an old `tsc` version bundled in `node-typescript`.

**Comment by chrisrlink** [comment]
oh ok

**Comment by chrisrlink** [comment]
should i delete build and rerun cmake?

**Comment by Bionus** [comment]
If it failed in the first place I doubt it would change anything.

You can however delete `node_modules` in `release/sites/`, then run `npm install`, then `npm run build`. If `npm run build` fails, try `./node_modules/.bin/tsc -p tsconfig.json`.

**Comment by chrisrlink** [comment]
it says /usr/bin/env 'node' doesn't exist

**Comment by chrisrlink** [comment]
on ./node_modules/.bin/tsc -p tsconfig.json

**Comment by chrisrlink** [comment]
found something hang on

**Comment by Bionus** [comment]
It seems `node` is not in your path.

If you used a package manager, maybe it's named `nodejs`. You can create an alias with `ln -s /usr/bin/nodejs /usr/bin/node` (or also `alias node=nodejs`).

**Comment by chrisrlink** [comment]
so far so good got past that error

**Comment by chrisrlink** [comment]
worked thanks
