### ISSUE TITLE
Is there a fix for bulk download bug from Zerochan?

### ISSUE THREAD

**Issue by Valiant77** [Bionus/imgbrd-grabber#1209]
I've looked at other issues pertaining to this and I learned there is no MD5 data present within images on Zerochan and learned it's only Zerochan doing this. However there wasn't any issue threads on bulk downloading from Zerochan. What I am trying to do is download all images from the tag name I have provided in Grabber and when attempting to bulk downloading from Zerochan it only saves one image without any text and never bothers to continue the bulk download. Is there a fix to this as in if there's any other extension method I could use other than the standard MD5 format, or is the only option is to download images one by one. Thanks.

**Comment by Valiant77** [comment]
As a side note there was a Zerochan downloader floating around on the Internet but I've tried to use it and it is completely broken on Windows 10. The program was created 7 years ago (Wowzers, that long ago!) on sourceforge so I expected what I expected from an old program.

**Comment by Bionus** [comment]
There's a fix on the `develop` branch for this issue, but the nightly builds are currently broken so you can't access it without building the software yourself.

Otherwise, why don't you use something other than `%md5%`? While Zerochan doesn't provide an MD5, they provide an unique ID for each image, so you could simply use `%id%.%ext%` instead.

Note that those IDs are only unique for each site, that is image 123 on Zerochan won't be the same as image 123 on Danbooru, for example. So either use `%website%` in your filename as well, or only download from one source at a time in a given directory.

**Comment by Valiant77** [comment]
Thank you for the fast reply! I looked into %id% and it seemed to download a bit more than %md5% did however it only downloaded page 1. Any solutions?

**Comment by Valiant77** [comment]
It seems like one of the tags I was downloading I only managed it to download on Page 1 by mistake so that was an issue on my part. Another tag that's downloading is downloading every single image off that tag from Zerochan. So %id% did the trick. Thank you.

**Comment by Bionus** [comment]
> Thank you for the fast reply! I looked into %id% and it seemed to download a bit more than %md5% did however it only downloaded page 1. Any solutions?

It most likely comes from the download settings. If you added your batch download using the "Get page" button it will get a single page. If you want all results you'll have to add it using the "Get all" button instead.

In any case, make sure the download is set to download more than 1 page. There are 3 columns that control the paging behavior in the "Downloads" tab:
* Page: the first page to download
* Images per page: how many images per page to download, you usually don't need to change this
* Limit (or whatever it's called): the number of images to download before stopping

If your the "limit" column is not high enough, it will stop early without downloading every page.

**Comment by Valiant77** [comment]
Thank you again for providing further information, I already figured out that was the problem.

**Comment by Bionus** [comment]
I'll close the issue then.
Glad I could help :smile:
