### ISSUE TITLE
chan.sankakucomplex.com no results AGAIN

### ISSUE THREAD

**Issue by baraa272** [Bionus/imgbrd-grabber#1211]
### What steps will reproduce the problem?

start pc 
I have ethernet
open grabber
search anything
chan.sankakucomplex.com will always give no results but when i click on it 
chrome open and chan.sankakucomplex.com LOAD fine with all images i want

### What is the expected behavior? What do you get instead?

expected : load images normally 
instead : Always NO RESULTS

### How often does this problem occur? On which sources?

this problem occur only with sankakucomplex

### What version of the program are you using? On what operating system?

5.5.2

### Please provide any additional information below

there was an issue like that before and fixed previous on 4.0 vrsion 
but it looks like its back

NOTE : WHEN i use VPN chan.sankakucomplex.com loads normally in grabber

**Comment by Bionus** [comment]
Sankaku's owner doesn't want Grabber to work on Sankaku, so he's pretty much blocked it, and I won't try to make it work with Grabber as he requested it personnally. So I'll be closing the issue.

However, I know one of Grabber's users suggested some solution to this problem in another issue using the User Agent, you can search for said issue and try its suggestion and see if it works! Other users have reported it to work.

Sorry for that but there's little more I can do, I hardly want to go into a fight with a website owner 😕
