### ISSUE TITLE
No load image from konachan.com

### ISSUE THREAD

**Issue by Nokimo** [Bionus/imgbrd-grabber#1212]
Hello 
I download and opened your program, tried load image from konachan.com and i can't
I get this : 

![screenshot 2018-03-04 11-38-26](https://user-images.githubusercontent.com/37038969/36944673-8450f4ea-1fa1-11e8-95a8-1407a8a3634c.png)

I have Windows 10 and current version v5.5.2. 
Can you help me ?

**Comment by Bionus** [comment]
I can't reproduce here:
![image](https://user-images.githubusercontent.com/882719/36952668-34915586-2013-11e8-8ca3-1e29cb440a36.png)

It seems the program manages to load the page information and tags just fine, and simply fails to load the thumbnails.

What does the log say?

**Comment by Nokimo** [comment]
https://pastebin.com/ejGKiT9g
![a](https://user-images.githubusercontent.com/37038969/36991813-2e0beb0e-20a9-11e8-8db3-9cddf328ee2a.png)
![b](https://user-images.githubusercontent.com/37038969/36991818-3297b112-20a9-11e8-86de-0b8ad171bbca.png)
![c](https://user-images.githubusercontent.com/37038969/36991824-355ba778-20a9-11e8-822b-10fc5e40586c.png)
I have not noticed this before XD

**Comment by Bionus** [comment]
Sounds like an OpenSSL issue.
Are you using Windows 10 x86 (32 bit) or x64 (64 bit)?

Can you try to replace the DLLs in your installation folder by those:
[OpenSSL-Win32-1.0.2n.zip](https://github.com/Bionus/imgbrd-grabber/files/1787156/OpenSSL-Win32-1.0.2n.zip)

And if it still doesn't work, those:
[OpenSSL-Win64-1.0.2n.zip](https://github.com/Bionus/imgbrd-grabber/files/1787157/OpenSSL-Win64-1.0.2n.zip)

And if any of them work, can you tell me which?
You're not the first user to have this issue and it's quite hard to investigate.

**Comment by Nokimo** [comment]
I using Windows 10 x64 and tried both DLLs but nothing has changed. 
https://pastebin.com/PEATuRHX
When you load the page (konachan.com), are you logged in?

**Comment by Bionus** [comment]
Ok it seems those DLLs were built with MSVC 2013, while Grabber is built with MSVC 2015:

```
$ dumpbin /headers ssleay32.dll | grep "linker version"

12.00 linker version
```

While Grabber installs the MSVC redist 2015 during installation, it doesn't install the 2013 version. Do you have it installed on your computer?
You can find it here: https://www.microsoft.com/en-us/download/details.aspx?id=40784

>  When you load the page (konachan.com), are you logged in?

There shouldn't be any relation between both (your error is purely technical).

I hope it'll work this time! :smile:

**Comment by Nokimo** [comment]
Okey it works 👍 
1) I had to install the version: MSVC 2013 x86 ( x64 i have before )
2) I replaced the DLLs in my installation folder " OpenSSL-Win32-1.0.2n.zip " 
And now he's loading pictures from konachan.com and other 👍
