### ISSUE TITLE
New folder for each tag?

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1213]
For example, say I'm downloading 2 different tags, is there a way to automatically create two separate folders for these two tags? Folder X would be tag X and folder Y would be tag Y?

**Comment by Bionus** [comment]
You can do something such as `%search%/%md5%.%ext%`.
See [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) for more details.

**Comment by bluefiberbread** [comment]
would prefer if it wasn't in the filename, is this the only way? I guess I could use a script to remove "search" in the filename

**Comment by Bionus** [comment]
It's not in the filename, it's a subfolder, hence the slash (`/`) character.

**Comment by bluefiberbread** [comment]
ops, missed it. this is exactly what I wanted, thanks :+1:

**Comment by bluefiberbread** [comment]
I have another question

is there a way  to do this automatically? https://puu.sh/zDEoM/041cbfc29c.jpg

%search%_3/%md5%.%ext%
%search%_4/%md5%.%ext%
%search%_5/%md5%.%ext%

**Comment by Bionus** [comment]
Why do you even do this in the first place? What are those numbers for?

**Comment by bluefiberbread** [comment]
I prefer to sort it by age instead of dumping it in one folder

**Comment by Bionus** [comment]
Well there's currently no way to do that.

If you where to use JavaScript however, you could use the [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object and insert the current date in your folder name (but if your download were to span two days they'd be split in two folders).

**Comment by Bionus** [comment]
The next version will include a new `%current_date%` token that might help with that. 👍 

So you might want to use either of these filenames to reach an acceptable result ("sort by age"):
* `%current_date:format=yyyy-MM-dd%/%search%/%md5%.%ext%`
* `%search%/%current_date:format=yyyy-MM-dd%/%md5%.%ext%`

_(choose either depending on whether you want to group by search or by date first)_
