### ISSUE TITLE
Question: Pixiv?

### ISSUE THREAD

**Issue by dabdabdebil** [Bionus/imgbrd-grabber#1216]
So, after usign this amazing program for a bit, I found something annoying, I couldn't have it download from pixiv, it didn't recognise it, now ofcourse the japanese tags thing might be hard to do or whatever, but would it be possible to add a pixiv downloading feature?

**Comment by TheWizardAlt** [comment]
It's been suggested, #917

**Comment by Bionus** [comment]
Indeed, #917 is for adding gallery support, which is required for Pixiv.
Closing for duplication of #738.
