### ISSUE TITLE
Derpibooru Cookies cause Grabber to crash.

### ISSUE THREAD

**Issue by KamillaPup** [Bionus/imgbrd-grabber#1217]
### What steps will reproduce the problem?
1. Go into Cookies of the source Derpibooru
2. Enter in the cookies stored in my browser.
3. Click Confirm
*Program Crashes*
1. Restore session.
*Program Crashes*
I relaunched and all settings were wiped and program runs fine. But I still can't successfully put in any credentials for Derpibooru.
### What is the expected behavior? What do you get instead
Expected behavior is that Grabber copies my browser session using the cookies and allows me to download files without them being 1 KB files.

### How often does this problem occur? On which sources?
Every time after adding cookies to Derpibooru.org. JSON is the listed first source

### What version of the program are you using? On what operating system?
5.5.2 on Windows 10

### Please provide any additional information below

[crashes.zip](https://github.com/Bionus/imgbrd-grabber/files/1801588/crashes.zip)

[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/1801590/settings.ini.txt)

Originally, I started adding the cookies manually because the files would be downloaded with the right filename, but when changing the extension to txt, this is what I saw:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```
I have tried putting in my API key instead of my password into password, I've tried POST method, and I've tried URL method. I was hoping cookies would work, but the program keeps crashing.

I appreciate the love you've put in this program so I don't expect a swift reply or anything. I would just love this to work.

**Comment by Bionus** [comment]
> Program Crashes

I can't reproduce that crash when setting cookies in a source, either on 5.5.2 or nightly.
However, using your API key as password should definitely work.

The issue you're mentioning (HTTP 301 error messages) seem unrelated to your login method though.
Does your log say anything?
Also, do you have SSL enabled on derpibooru? They have a 301 redirect from HTTP to HTTPS.
