### ISSUE TITLE
Pictures from sankakucomplex not loading

### ISSUE THREAD

**Issue by dabdabdebil** [Bionus/imgbrd-grabber#1219]
### What steps will reproduce the problem?

Add it like any other Booru

### What is the expected behavior? What do you get instead?

Get pics when searching for things. Nothing, I only got results once, and that was when searching up "loli" for test purposes, but after that, null
edit: yesterday I deleted sankaku from the sources, and then I was only able to look up "mecha" but nothing else I searched gave results

### How often does this problem occur? On which sources?

All the time. https://chan.sankakucomplex.com

### What version of the program are you using? On what operating system?

v5.5.2 windows 10

### Please provide any additional information below

[main.log](https://github.com/Bionus/imgbrd-grabber/files/1803810/main.log)

**Comment by bluefiberbread** [comment]
how did you add sankaku to grabber?

**Comment by dabdabdebil** [comment]
By the usual means, after pressing source, I pressed the Add button where the list of sources is

**Comment by Thelockest** [comment]
Already solved the problem
https://github.com/Bionus/imgbrd-grabber/issues/1202

**Comment by bluefiberbread** [comment]
not working for me either, I think sankaku's owner restricted any request to sankaku via their API

**Comment by Thelockest** [comment]
Strange still works for me
