### ISSUE TITLE
Issues logging to zerochan.net

### ISSUE THREAD

**Issue by shalola** [Bionus/imgbrd-grabber#1224]
hey i can't login to zerochan.net

![image](https://user-images.githubusercontent.com/37476685/37555994-5bddfc16-29f0-11e8-89de-e7c8f480ff9b.png)
![image](https://user-images.githubusercontent.com/37476685/37555997-6541c850-29f0-11e8-9606-a7a63cd84723.png)

please help me

**Comment by J3loodz** [comment]
dont work on me either
