### ISSUE TITLE
Grabber goes beyond "Image Per Page" limit I had put.

### ISSUE THREAD

**Issue by CascaisPhilosopher** [Bionus/imgbrd-grabber#1225]
**### What steps will reproduce the problem?**
Don't know if this is problem or an actual feature of the program but whenever I type the amount of images per page I want to see, it never shows the amount I typed, instead it goes way beyond (Example: 112 images per page when I had put only 20).

**### What is the expected behavior? What do you get instead?**
It's expected to show only 20 images per page but as I mentioned it shows way more than the value I typed, it seems that the value goes higher when I put a higher number like: 20 Images per page shows 112, 30 images per page shows 166, 40 Images per page shows 224...

**### How often does this problem occur? On which sources?**
In every source and every tag, I tried each source alone to see if one of them was the problem but  every one of them did this.

**### What version of the program are you using? On what operating system?**
Using the lastest release v5.5.2, on Windows 7

**### Please provide any additional information below**
As I said before, I'm sorry if this is an actual thing the program does and not a bug/error. The amount of images that show is not an actual problem, the problem is that when too much images show per page, some of them don't actually load, leaving a whole page blank sometimes.

**Comment by TheWizardAlt** [comment]
Do you have merge results on? Images per page is a per source setting, so divide the images you want to see by the number of sources you have active should give a more accurate amount.

**Comment by CascaisPhilosopher** [comment]
Hello, sorry for not responding it's been busy lately, but yes the problem was that I was using merged results, my bad, now the number of images I selected do appear on the separated sources, so thank you, but one problem still remains and that is the images that don't load, here's a attached screenshot so you can get the idea
![images not loading](https://user-images.githubusercontent.com/37555962/38159908-7befbf14-3489-11e8-890f-01e955558666.png)
