### ISSUE TITLE
Conditional filename need a scroll bar

### ISSUE THREAD

**Issue by AchinXD** [Bionus/imgbrd-grabber#1227]
### What steps will reproduce the problem?
When I add 40 conditions in the conditional filename
![dl](https://user-images.githubusercontent.com/15706006/37871243-06a72260-2fd9-11e8-9b4f-b683038b5976.JPG)

### What is the expected behavior? What do you get instead?
It should have a scroll bar to let me scroll
Cause I want to make every pic in each folder.
So I have to add about 100+ conditions to do this.
### What version of the program are you using? On what operating system?
5.5.2 wlndows10

**Comment by Bionus** [comment]
Indeed. :+1:

However, I feel you could optimize this stuff somehow. This feels like a lot of repetition, opposite of the initial objective of [filename formats](https://github.com/Bionus/imgbrd-grabber/wiki/Filename).

**Comment by AchinXD** [comment]
Cause I want to make every character download in each folder XD.
And I start the batch job by using tag "kantai_collection".
It include many character. So I have to sort them to make my disk in good order.
But I don't how to do that. I just use this dumb way QAQ.
Anyway,I had create each character's folder,and assign the route to every tag.
Thank you for reply and made such good program.
![dll](https://user-images.githubusercontent.com/15706006/37882147-3b5a6942-3090-11e8-8346-83a2f4856ad4.JPG)

**Comment by Bionus** [comment]
You can just use the tag `kantai_collection` in your query then use `%character%/%id%.%ext%` as a filename.

Each `/` means a folder, so it would create files such as:
```
├── intrepid (kantai collection)
│   ├── 123.jpg
│   └── 456.jpg
└── taihou (kantai collection)
    ├── 789.jpg
    └── 012.jpg       
```

**Comment by AchinXD** [comment]
Got it! 
I have set the Character tag to "One file per tag".
So it can generate one folder per tag now.
And thanks again :)
Hope it won't go wrong by downloading 269k pics XD
