### ISSUE TITLE
Derpibooru downloading 0 bytes sized files

### ISSUE THREAD

**Issue by MagikGimp** [Bionus/imgbrd-grabber#1230]
### What version of the program are you using? On what operating system?
v5.5.2 on Windows 10.

### Please provide any additional information below
Hi Bionus. Thank you as always for your fantastic software.
I am using the API credentials as explained elsewhere and previews show up fine but when I add them to the download list they are saved with 0 byte size for some reason. Am I doing something wrong? Many thanks.

**Comment by TheWizardAlt** [comment]
What is your file name set to?

Can you post your log?

**Comment by MagikGimp** [comment]
Hi. Filename is- %md5%.%ext%
Log attached. You can ignore the first part. That's just me setting up, making mistakes and downloading some other pics that caught my eye. As you can see, I cancelled after 5 downloads as it was doing the same as mentioned in my first post.
Thanks.
[log - 31-03-18 01.21.txt](https://github.com/Bionus/imgbrd-grabber/files/1865040/log.-.31-03-18.01.21.txt)

**Comment by TheWizardAlt** [comment]
This is weird but change your filename to %md5:maxlength=8%.%ext% and try again. for some reason that log is showing your filename as huge which might be causing problems.

**Comment by MagikGimp** [comment]
I was thinking that might have been the problem as other sites don't have such long hashes but it didn't work unfortunately. Still showing download speed of 0.00 and all files are 0 length size although it does take a sizeable time before moving on to the next image as though it was downloading something.
Are you able to replicate the problem your end at all?
I did have a crash while changing settings but that might be unrelated. I've uploaded the relevant files below in an archive, or at least I assume these are the right files. When it loads the GitHub support page, Grabber forgets which files it was attempting to attach!
[Crash - 31-03-18 12.43.zip](https://github.com/Bionus/imgbrd-grabber/files/1865439/Crash.-.31-03-18.12.43.zip)

**Comment by TheWizardAlt** [comment]
I'm not sure, mine seems to work (Downloading from derpibooru in general) but I use linux, not windows. I assume it might be something wrong with your setup, but I can't be sure. Maybe wait for Bionus to weigh in. Sorry. 

I'll take a look through your crash log, but mine sometiems crashes on setting changes too so I'm not sure if that is related.

**Comment by Bionus** [comment]
Indeed, it seems the installation was missing some file which should have fixed this problem and forced HTTPS on Derpibooru (commit 15e980fe195cbaf3e26035192479ed524e1890cd).

I'll push a fix so that this file is properly included in the next release. Also, there will be an automatic HTTPS detection so this should not happen again.

Thanks @gabrielwoj for finding out the source of the issue! :+1:
