### ISSUE TITLE
Sankakau Update

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#1231]
Will this change anything? 
Recently received this email.
System said:

Hello {redacted},

The new interface for the site is nearing completion, and we invite you to try it out:

https://beta.sankakucomplex.com/

A worksafe version is also available:

https://white.sankakucomplex.com/

Technically minded users will recognise this as a single page app implementation of the existing native Android app, whilst those of a less technical bent will notice it is a vastly more mobile-friendly and hopefully more useable interface to the site than the legacy PC site.

Once sufficient functionality, polish and performance is delivered, the web app will likely become the default mobile interface for the site, eventually to be followed by a phased desktop migration once everything is completely satisfactory for desktop users as well.

At present, core functionality is largely present and functional, with a few major features still to come. There are of course still many issues to work through - feedback in these areas is greatly welcomed.

As a beta version, functionality and uninterrupted access are not guaranteed, so please be understanding in the event of problems.

'White', filter-compliant and censorship-resiliant versions will be provided on alternative domains at a later date.

Questions or suggestions, complaints or comments, all are welcome - either respond to this mail or just email contact@sankakucomplex.com!

**Comment by Bionus** [comment]
Thanks for the heads-up!
I didn't know they were working on this.

> Will this change anything?

Well, if it replaces the current version of the website, yes.

That will totally break the existing HTML API for Sankaku. And given it's using [React](https://reactjs.org/), it won't be possible to use the current Regex system to replace it. Given their API is turned off, that would effectively mean that there will be no way to download from Sankaku from that point onwards, unless an expensive effort is done in Grabber to support React sources (it's not the first time it was suggested). That effort would be quite expensive as it would require using an actual browser (for example chrome headless or PhantomJS) to render the page, and only afterwards try to get the results.

**Comment by Bionus** [comment]
Moving to #1237
