### ISSUE TITLE
grabber crashes after completing download

### ISSUE THREAD

**Issue by nyxorio** [Bionus/imgbrd-grabber#1238]
### What steps will reproduce the problem?
Use danbooru+gelbooru to search and enabling "Close window after finish download"

### What is the expected behavior? What do you get instead?
The download tracker closes and the grabber clears download queue

### How often does this problem occur? On which sources?
Everytime

### What version of the program are you using? On what operating system?
5.5.2 on Windows 7

**Comment by Bionus** [comment]
Do you have the "Remove" checkbox checked?
If so, possible duplicate of #812, which will be fixed in next version.
