### ISSUE TITLE
Search results not loading/showing up

### ISSUE THREAD

**Issue by CascaisPhilosopher** [Bionus/imgbrd-grabber#1240]
**### What steps will reproduce the problem?**
It's very random but, whenever I search something it has a chance that results won't show up, instead leaving blank spaces which the images should be in. The thing is that it is very random, if I refresh the search newer images can appear, but it also has the possibility that the already appearing images disappear leaving only blank spaces.

**### What is the expected behavior? What do you get instead?**
It's supposed show all the images in the page, but instead I get a blank page with the spaces for the images, or it shows some pictures but then the rest doesn't load

**### How often does this problem occur? On which sources?**
It happens randomly, but on every source and with or without Merge Results on. 

**### What version of the program are you using? On what operating system?**
I'm using v5.5.2 on Windows 7

**### Please provide any additional information below**
I noticed it tends to happen when a big amount of results appear, even if I limit the images per page to a small amount, if the overall results are many, the images tend to not load. Here's a screenshot to understand better what's happening.
![images not loading](https://user-images.githubusercontent.com/37555962/38523545-3fd0767c-3c22-11e8-95ba-ea000c84eaae.png)

**Comment by Bionus** [comment]
Are you using the upscaling feature?
From your screenshot, the images look pretty big.

Also, in your screenshot you seem to be in the middle of the "scroll area". Is there anything below, or is everything white after that?

**Comment by CascaisPhilosopher** [comment]
No, I didn't even touch with the upscaling, I thought the big images where something the program would do normally, and yes after that point I just white, probably the space where the pictures should have been.
