### ISSUE TITLE
Full size images all return "expired" on Sankaku

### ISSUE THREAD

**Issue by dabdabdebil** [Bionus/imgbrd-grabber#1242]
### What steps will reproduce the problem?

[adding sankaku as a source, trying to download any image

### What is the expected behavior? What do you get instead?

to get downloaded images.
while they do download, they don't work

### How often does this problem occur? On which sources?

a ton. Sankaku

### What version of the program are you using? On what operating system?

5.5.2 on windows 10

### Please provide any additional information below

![screenshot_163](https://user-images.githubusercontent.com/25393323/38549352-7b376956-3cbc-11e8-9ae0-08885e71f508.png)

**Comment by Bionus** [comment]
Even though the HTTP Referer header [allows relative URLs](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.36), it seems that Sankaku will block all request with a relative Referer.

I pushed a fix in Grabber that will now send referrers as absolute URLs.

In the meantime, you can simply disable the Referer for images in the Sankaku settings:
![image](https://user-images.githubusercontent.com/882719/38641312-f6a518ca-3dd6-11e8-8cf1-35fc51496d77.png)

Also make sure you have a valid User-Agent set, Sankaku has a UA blacklist IIRC.

**Comment by dabdabdebil** [comment]
> Also make sure you have a valid User-Agent set, Sankaku has a UA blacklist IIRC.

would it be possible to get a working user-agent set? I'm sure it's somewhere. but I don't really want to waste x amount of time on finding it

**Comment by TemerityJest** [comment]
@Bionus 

> In the meantime, you can simply disable the Referer for images in the Sankaku settings

This doesn't seem to change anything, even using a different User-Agent.
