### ISSUE TITLE
Conditional Filename not working?

### ISSUE THREAD

**Issue by NWCampbell** [Bionus/imgbrd-grabber#1244]
### What steps will reproduce the problem?
Setting a Conditional Filename, possibly incorrectly.

### What is the expected behavior? What do you get instead?
If "tag" then %artist%/%tag%%character%%md5:maxlength=5%.%ext%

%artist%/%character%%md5:maxlength=5%.%ext% (even if tag IS THERE)

### How often does this problem occur? On which sources?
Gelbooru, and 100% of the time.

### What version of the program are you using? On what operating system?
Latest version on Windows 10

### Please provide any additional information below
I'm pretty sure I followed directions in the filename section of the wiki
Created a conditional filename looking for a tag and left folder to default and filename to as I desired but it ignores the tag even if the tag does in fact exist.

Perhaps a step by step on how to set it as desired : If "tag" then %artist%/%tag%%character%%md5:maxlength=5%.%ext%

I'll test and see if it works, or report that it doesn't work still?

**Comment by Bionus** [comment]
What is `%tag%` supposed to be?

Since `%tag%` doesn't exist, it will be replaced by nothing when saving, resulting in `%artist%/%character%%md5:maxlength=5%.%ext%` in any case.

Maybe what you want to do is `%artist%/tag %character%%md5:maxlength=5%.%ext%`?

![image](https://user-images.githubusercontent.com/882719/39328298-374d10a6-499b-11e8-8d27-301e16cee523.png)

**Comment by NWCampbell** [comment]
Oh I was just giving %tag% as any general tag that I wanted to distinguish, "flat_chest", "big_oppai", "feet", "austin_powers" whatever I think of.

**Comment by NWCampbell** [comment]
OH! Last question, is there a way to do AND/OR the tags? Say there's BOTH tags present, or just ONE tag present, I would like it to go to the same Filename.

Say "loli" and "flat_chest" as an example, I'd want if it had one or both go to %artist%\loli\%md5%.%ext%
How would I write that conditional?
