### ISSUE TITLE
Question: DNS through proxy?

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#1247]
Does it work? Or does Grabber use system DNS? If no, can you add an option for resolving DNS through proxy (as Firefox remote DNS does it)?

**Comment by Bionus** [comment]
No idea.

Grabber uses Qt for networking, and I could not find any information about this. I guess your best option to know would be to run some sniffer and see whether the DNS resolving is done in the client or in the host when using a proxy.
