### ISSUE TITLE
Problem with tags

### ISSUE THREAD

**Issue by zoameldar** [Bionus/imgbrd-grabber#1248]
### What version of the program are you using? On what operating system?
I use 5.5.2 (S)table and 5.5.2 (N)ightly
Windows10

### What steps will reproduce the problem?
Search image and click or download image:
Derpibooru - (S N) miss/doesn't show all tags in preview and downloading except %character, %artist 
Konachan - (N) when downloading/saving image it miss all tags except %rating
Rule34.paheal - (S N) doesn't recognize tags (missing colors and doesn't download them "save") %character, %artist, %copyright
yande.re - (N) when downloading/saving image it miss tags %character, %artist, %copyright
zerochan - (S N) doesn't recognize tags (missing colors and doesn't download them "save") %character, %artist, %copyright, %rating

Also in Nightly "open in browser" doesn't work.

### What is the expected behavior? What do you get instead?
I would like working tags. But don't know how much is program and how much is a website problem.

### How often does this problem occur? On which sources?
all the time.

### Please provide any additional information below
Trying Nightly from #1246 to be up to date

**Comment by Bionus** [comment]
Thanks for the info!

I pushed a bunch of changes that should fix all those issues. Feel free to try the latest nightly and tell me if they are properly fixed.

> Rule34.paheal - (S N) doesn't recognize tags (missing colors and doesn't download them "save") %character, %artist, %copyright

It's a Shimmie board, so tags are not typed.
Therefore, `%character%`, %artist%`, and `%copyright` will never work.

**Comment by zoameldar** [comment]
>It's a Shimmie board, so tags are not typed.
>Therefore, %character%, %artist%, and%copyright` will never work.
OK understand. Bug was on many sites so I just tested all of them.

I check f547bd6 and everything except derpibooru works perf now.
