### ISSUE TITLE
MSVCR120.ddl is missing

### ISSUE THREAD

**Issue by 123okayokay** [Bionus/imgbrd-grabber#1249]
### What steps will reproduce the problem?

for me, downloading grabber and trying to start it up

### What is the expected behavior? What do you get instead?

for pictures to load correctly and for me being able to download them.

no previews appear, no downloads appear

### How often does this problem occur? On which sources?

every time I try to startitup

### What version of the program are you using? On what operating system?

5.5.2 windows 7

### Please provide any additional information below

I've tried download MSVCR120.ddl both with prgrams, and installing it manually, restarted my laptop over and over again. but nothing

**Comment by Bionus** [comment]
Have you tried installing https://www.microsoft.com/en-us/download/details.aspx?id=40784?
It should fix this problem (HTTPS sources not working).

The next version will automatically install it during installation.

**Comment by 123okayokay** [comment]
okay, so i just downloaded every possible version of c++ and now it'sworking
