### ISSUE TITLE
Add image tags under Tags property of a file (Windows 7+)

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1252]
I recently discovered that, if one adds the tags of an image in the Tags property in the file properties under details tab (file meta), they can be searched and filtered just like on the sites. For example, entering "tag:bodysuit -tag:loli" will do the obvious function and be super fast too.

This can be added under save in settings like a configuration option. Tags are already in store when downloading an image so this doesn't seem like a very big leap over the existing functionality. But a huge boon to those who do not want to lose this function while being offline.

**Comment by baraa272** [comment]
ummmm how do you use it ????? 
where is that feature (External text file) ???

**Comment by Bionus** [comment]
Closing as duplicate, if you have more info about some universal tagging system, I'd gladly implement it.

@baraa272 moved to #1498
