### ISSUE TITLE
Issues when attempting to grab tags from rule34hentai

### ISSUE THREAD

**Issue by nascenza** [Bionus/imgbrd-grabber#1253]
**What steps will reproduce the problem?**
None that are specific or hard to reproduce. Just add any tag and this happens.

**What is the expected behavior? What do you get instead?**
Grabber downloads files however they're all 0KB no matter what.

**How often does this problem occur? On which sources?**
Every time I grab anything from rule34hentai.net

**What version of the program are you using? On what operating system?**
5.5.2 running on Windows 10

**Please provide any additional information below**
Any time I try downloading images from a tag with rule34hentai.net as a source I get 0KB files in return. Not to mention grabber skips files.

I've tried multiple tags. Sometimes only using one, other times using a combo. I've also tried reducing the pages.

I have already put my credentials and login information in the source settings. However when inputting my credentials for an account I -just- made (no email attached, if that's any help) and testing it I get a "Failure" result. Even so, I've tried downloading the files anyway and I get the same exact results - Files with their names and extensions correct, except a lot of them are skipped and ALL of them are 0KB.

I've done this on my desktop, on my laptop, have tried reinstalling the program twice, with no luck.

![grabber_2018-05-05_19-41-11](https://user-images.githubusercontent.com/39012572/39666498-80bf1c2c-509c-11e8-9bb1-eb844b761ea3.png)

![grabber_2018-05-05_19-41-16](https://user-images.githubusercontent.com/39012572/39666499-80e3e9f8-509c-11e8-9529-1201d39051e6.png)

![explorer_2018-05-05_19-41-54](https://user-images.githubusercontent.com/39012572/39666540-2e5c02b4-509d-11e8-949e-aa3b342ff1be.png)

Apologies for my username being blurred out - It's a username I use pretty much everywhere online, and one that people I know in real life also know of.

**Comment by Bionus** [comment]
Is there anything of interest in your log? (are the URLs linked in the log correct?)
Does this issue still occur in the nightly version?

I tried on both 5.5.2 and nightly and had no issues downloading images from this source. Are you trying to download particular tags?

**Comment by lee27** [comment]
well I have this problem, I can not download any more tags, when I start the search I immediately "no result", until the other day it worked well
