### ISSUE TITLE
Image Downloading  Issue in Sankaku

### ISSUE THREAD

**Issue by KaleyMoro** [Bionus/imgbrd-grabber#1255]
### What steps will reproduce the problem?

downloading any image from sankaku 

### What is the expected behavior? What do you get instead?

the image is downloaded but every image is only 154bytes instead of original image size and image cannot be opened.

### How often does this problem occur? On which sources?
everytime I try to download from sankaku

### What version of the program are you using? On what operating system?
I'm using 5.5.2 version of grabber on Windows 10

### Please provide any additional information below
here is the the image of the problem.
![image](https://user-images.githubusercontent.com/39103357/39782851-1c803edc-5333-11e8-867e-27dcdbcfc718.png)

**Comment by cobra88king8** [comment]
Having the same issue, here is what one of the images says 

> <html>
> <head><title>302 Found</title></head>
> <body bgcolor="white">
> <center><h1>302 Found</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>

**Comment by J3loodz** [comment]
same

**Comment by micnorian14** [comment]
This has been an issue for a few months...was the result of a site update in regard to Sankaku's "Beta" website. Most notably it does a fantastic job of absolutely nothing for regular web browsers. From what insignificant amount of coding I've gleaned over the years, this looks like a subtle monkey wrench. But what do I know.

**Comment by Rezboa** [comment]
So, no solution?

**Comment by Bionus** [comment]
This 302 redirect has been fixed in v6.0.0.
If there are more issues with Sankaku, please open another issue. But from what I see it works:

![image](https://user-images.githubusercontent.com/882719/41309000-bdbca32a-6e7d-11e8-9c53-3aa87ce03fe9.png)
