### ISSUE TITLE
Not an issue per-say but a question.

### ISSUE THREAD

**Issue by littlesub1106** [Bionus/imgbrd-grabber#1256]
How do you perform a clean install? After uninstalling and reinstalling I run into the problem that the settings are the under the options of the program. That being said my real issue is that a booru that used to work for me no problem suddenly stopped after I messed with the options and I don't know exactly what triggered this so I just want to start over. Any help on the matter is appreciated, thank you.

**Comment by littlesub1106** [comment]
Scratch this. I found it after doing a search for the term "grabber" through my whole PC.

**Comment by Bionus** [comment]
You can use the shortcut in the "File" menu to open the settings folder.

Otherwise, settings can be found in:
```C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber```
