### ISSUE TITLE
Organize Downloads?

### ISSUE THREAD

**Issue by Gabon05** [Bionus/imgbrd-grabber#1257]
Hi I have a Question. How do you guys organize downloads? I mean Grabber put every picture the same folder, and i cant download different types of pictures, because i cant separate them. Can somebody help me with this? Thanks guys.

**Comment by Bionus** [comment]
Have you checked the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) wiki page?

To organize downloads in sub-folders, you can simply add slashes (`/`) in your filename. Each slash will create a directory level.
