### ISSUE TITLE
Commands not working with NAS

### ISSUE THREAD

**Issue by FrixellFan** [Bionus/imgbrd-grabber#1258]
Hello!

Before I go into it, as I read through the issues, it's possible my problem is specific, so if nobody can give me any directions, that's okay.

### The problem itself, and about the environment in general:

I have a Synology NAS (runs on linux), and one of it's function is to host a booru server for my close friends. I run Zixaphir's gelbooru-fork, which is basically gelbooru 0.1.11, with some extra functions. I also made some adjustments to it, but database-wise, and in general functions it's completely indentical to 0.1.11 (as far as I know). This booru runs for months now, so I know in fact that it's working perfectly. I was trying to set up grabber through the "command" option, following the tutorial, so anything downloaded from gelbooru would be saved instantly into my own booru.

### The initial setup:

Because I'm using the NAS, reaching the database, and the save path itself it's not self-explanatory, but I was planning to fix this with trial and error. At first I could not even connect to my database. Then, I filled in all the necessary data again, being careful that my host should be the local ip for my NAS (wan ip for my friends outside my home network), and that my database actually has a name and password, and of course, different name than in the tutorial.

Then, the tutorial says what to put under the "tag" line, but the program has "tag(before), and tag(after) options. I cannot really grasp what's the difference between them. For now, I'm putting in the command from the tutorial into the tag(after) option. After some trial and error, I haven't got the database connection error in the log.

### The reason I cannot proceed further.

The current behaviour makes me pretty much baffled, because when I start a download now, the program itself freezes. More precisely, it seems like it hangs on something, so I cannot even check what is the problem, I can only force close the program. The problem happens every time. I even tried to change the parameters from the "tag(before)" into the "tag(after)" line, but nothing really changed, the program still stops responding. Because of this, I cannot even check, what was the problem, as I cannot find any log files in the grabber folder itself. If I put in the port number after the host ip, then the program says it couldn't connect to the database, and just proceeds to download normally, without doing anything else. I have a feeling the problem could live with that my database is actually mariadb10.

### What version of the program are you using? On what operating system?

I'm trying with Grabber v.5.5.2, which I'm operating from a windows 10 computer. My NAS runs on a custom linux developed by Synology, and is connected to my local network through a fixed local IP. The router model is a Synology RT2600ac, while the NAS is a DS1817+. My database server is a MariaDB10, and I'm admining it through phpmyadmin.

Any help or insight is appreciated.

Thank you!

**Comment by Bionus** [comment]
> Because I'm using the NAS, reaching the database, and the save path itself it's not self-explanatory, but I was planning to fix this with trial and error. At first I could not even connect to my database. Then, I filled in all the necessary data again, being careful that my host should be the local ip for my NAS (wan ip for my friends outside my home network), and that my database actually has a name and password, and of course, different name than in the tutorial.

Sounds good to me.

> Then, the tutorial says what to put under the "tag" line, but the program has "tag(before), and tag(after) options. I cannot really grasp what's the difference between them. 

If you put your command in the "after" field, it will be executed after the "image" command is run. If you put it in the "before" field, it will be executed before the "image" command. Depending on the booru, they might require to do either of them (never both).

> The current behaviour makes me pretty much baffled, because when I start a download now, the program itself freezes. More precisely, it seems like it hangs on something, so I cannot even check what is the problem, I can only force close the program. The problem happens every time. I even tried to change the parameters from the "tag(before)" into the "tag(after)" line, but nothing really changed, the program still stops responding. Because of this, I cannot even check, what was the problem, as I cannot find any log files in the grabber folder itself.

Sounds like Grabber freezes while trying to connect to your database.
Is there really nothing in your `commands.sql`, `commands.log`, and `main.log` files?

> I have a feeling the problem could live with that my database is actually mariadb10.

Sounds likely as multiple people have successfully used the commands feature with MySQL databases.
I'll still install a MariaDB server and see if I can reproduce the issue.

**Comment by Bionus** [comment]
I just tried using https://github.com/zixaphir/gelbooru-fork and MariaDB on my Windows computer with no issues at all.
Have you tried using nightly?

**Comment by FrixellFan** [comment]
Hello!

Thanks for the reply. I had some time, so started working on the case. I managed to get to the following:

Before trying nightly, I completely reinstalled Grabber, just for the hack of it, ad I never had the aforementioned log files in either folder of grabber (not even the options folder). After a fresh install, things changed, so I will write down what I have managed to do:

Copying the file itself works just fine with the command from the tutorial. Although, a piece of advice here, regarding the blank character: for me, with japanese unicode, alt+255 does not work. Although alt+1061 works just fine. Maybe you can put this small info into the tutorial, as people would know there are 2 different codes for this.

After this, the log files actually started to work, which is nice, because I now know that the problem is really the database connection.

My local image boards runs on the NAS itself, with IP address 192.168.1.19. Because it's mariadb, in the config file, the port for the host line is 3307, not 3306. I'm still getting errors, which looks the following:

If I don't use port number, just 192.168.1.19, then:
[18:48:57.573][Error] Error initializing commands: Can't connect to MySQL server on '192.168.1.19' (10061) QMYSQL: Unable to connect

If I use the 3307 port number too, which also forwarded on my router:
[18:45:19.654][Error] Error initializing commands: Unknown MySQL server host '192.168.1.19:3307' (0) QMYSQL: Unable to connect

As far as I know with my limited knowledge, and looking it up, error code 10061 means the server cannot be reached, and error code 0 is syntax error. Going from this, I guess the right way would be just to use my IP address without the port number. But isn't reaching my database only doable through port 3307 in case of mariadb?

In phpmyadmin, I also checked my user, which has "%" in the host mean, which means any host can access it. I also created a user just for my computer on local network, but still, the same error. Even tried to open the port 3307 on my router, and on the NAS too, just to try it out, no luck. Grabber still tries multiple times, then after a while it gives up (usually around 1 minute), and throws the error. I also tried to change the driver in grabber, still same error.

Now I'm pretty sure though that the problem is with the NAS. Although I cannot really understand why, as my user is created in a way that I can reach it from my local network (I'm using phpmyadmin from my computer to manage my databases), yet, with grabber, I just cannot connect. This is most likely a problem in my part, as I only started learning about databases when I got the NAS half a year ago. The problem is, at this point, after I basically tried everything as I mentioned above, I don't really know why my connection get refused. Of course I will going to try until it works, but if you have any idea, or any tips as you are more experienced with databases, it would be more than welcome by me.

p.s.: For security reasons, my NAS only accessable through https, and every other service also accesses it through secure connection.

**Comment by Bionus** [comment]
> Copying the file itself works just fine with the command from the tutorial. Although, a piece of advice here, regarding the blank character: for me, with japanese unicode, alt+255 does not work. Although alt+1061 works just fine. Maybe you can put this small info into the tutorial, as people would know there are 2 different codes for this.

Actually this part wasn't added by me. The need to have some kind of "blank" character is actually a bug. The commands were passing through the "filename cleaner", which trims folder names: "test /file.jpg" would be replaced by "test/file.jpg". While it's useful for filenames, it's not so much for commands.

I should have solved this in nightly, so a normal space should do.

> After this, the log files actually started to work, which is nice, because I now know that the problem is really the database connection.

That's very weird that they weren't written in the first place, given the logs are the most basic part of the program :thinking_face:

> My local image boards runs on the NAS itself, with IP address 192.168.1.19. Because it's mariadb, in the config file, the port for the host line is 3307, not 3306. I'm still getting errors, which looks the following:
>
> [If I don't use port number, just 192.168.1.19, then:
> [18:48:57.573][Error] Error initializing commands: Can't connect to MySQL server on '192.168.1.19' (10061) QMYSQL: Unable to connect
>
> If I use the 3307 port number too, which also forwarded on my router:
> [18:45:19.654][Error] Error initializing commands: Unknown MySQL server host '192.168.1.19:3307' (0) QMYSQL: Unable to connect
>
> As far as I know with my limited knowledge, and looking it up, error code 10061 means the server cannot be reached, and error code 0 is syntax error. Going from this, I guess the right way would be just to use my IP address without the port number. But isn't reaching my database only doable through port 3307 in case of mariadb?]

Thinking about it, you can't provide a custom port with the current implementation. So whatever you put as hostname, it will still use the 3306 port. And if you try to use "192.168.1.19:3307", it will be rejected as an invalid hostname (trying to connect to host "192.168.1.19:3307" on port 3306).

I've just pushed a fix (3e352cfb4bb113b1453c8cc780aa59cf35b39161) to allow changing the port. It should have landed in the nightly release, so you can give it a try and see if connecting to your NAS works when providing the 3307 port (with the "host:port" format).

**Comment by FrixellFan** [comment]
Hello!

Had some time in my hand, so I tried out the new nightly release (thank you for making the fix). I'm pretty much confused now, because I'm getting a different error. Couldn't ascertain if connection to the database happens or not, because no matter what I try now, I get the error, as attached as the picture. Which is strange, as the driver is added to your program, and it should run. Was trying all kind of combinations again, but it's throwing this error now. After some reading, they would say to add the necessary files, but as I stated, they are indeed added to your program. If I manage to make it work, I will update you, but looks like I hit a wall again.
![wclxw](https://user-images.githubusercontent.com/39170918/40890492-350d04a0-6777-11e8-92a7-92e0bc33675c.jpg)

**Comment by Bionus** [comment]
Could it be that the MySQL DLL in your install folder does not work properly?

You can try replacing the `libmysql.dll` file from the install folder by one of those (start with the x86 one):
* x86: [libmysql-x86.zip](https://github.com/Bionus/imgbrd-grabber/files/2083340/libmysql-x86.zip)
* x64: [libmysql-x64.zip](https://github.com/Bionus/imgbrd-grabber/files/2083339/libmysql-x64.zip)

_(if it works, do tell me which fixed it so I can update the installer to use said DLL)_

**Comment by FrixellFan** [comment]
Hello!

I'm pleased to report that all of those two files work. The entries get into my database, and the file upload works too. The only problem now that I have multiple folders on my booru (not just folder "1" inside the images folder, but multiple ones), and therefore, the image still do not shows itself. This is unrelated to the problem we were discussing, and will see to it that it will work. Hopefully I will manage to find what's wrong with my setup.

For the other problem, thanks for helping to solve it.
