### ISSUE TITLE
Rating:explicit appearing in Rating:safe

### ISSUE THREAD

**Issue by NWCampbell** [Bionus/imgbrd-grabber#1261]
### What steps will reproduce the problem?
Creating a Conditional Filename for a rating tag
rating:explicit --> Filename = %artist%\NSFW\\%md5%.%ext%

### What is the expected behavior? What do you get instead?
If contains the tag "rating:explicit" then put in the NSFW folder
I'm getting rating:explicit put into the SFW folder rather than the NSFW folder.
I do have a conditional for rating:safe --> Filename = %artist%\SFW\\%md5%.%ext%

### How often does this problem occur? On which sources?
I don't even get an NSFW folder, just everything dumped in the SFW folder

### What version of the program are you using? On what operating system?
Latest Version on Windows 10

### Please provide any additional information below
![nsfw in sfw folder](https://user-images.githubusercontent.com/22357456/40027606-a9b83c5e-578f-11e8-922b-75e6927df404.png)

**Comment by NWCampbell** [comment]
Also, I'm getting my SFW tag being applied to NSFW images!!
![sfw on nonsfw](https://user-images.githubusercontent.com/22357456/40030823-8d4c78a2-57a1-11e8-8a85-f73d301fee2c.png)

**Comment by NWCampbell** [comment]
Thank you!

**Comment by deeppomf** [comment]
Better delete these images. They violate Github community guidelines.
