### ISSUE TITLE
No folders are being made when saving a picture

### ISSUE THREAD

**Issue by Kant17** [Bionus/imgbrd-grabber#1264]
### What steps will reproduce the problem?

having it organized 

### What is the expected behavior? What do you get instead?
at 1st all of the settings were reset then 

### How often does this problem occur? On which sources?
it just happened today

### What version of the program are you using? On what operating system?

5.2.2

**Comment by Bionus** [comment]
Could you be more specific?
What's the problem? I just tried saving files with subfolders with no issues.

> at 1st all of the settings were reset then

What's the relation with folders?

> 5.2.2

You mean 5.5.2?
