### ISSUE TITLE
New "meta" tags such as "webm" not read on danbooru

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1265]
### What steps will reproduce the problem?
Set by the post filtering -webm and the source on danbooru. After this just search and you will see that the webm files are still displayed

### What is the expected behavior? What do you get instead?
It will still display and after that download the webm files but I aspect that they would be filtered

### How often does this problem occur? On which sources?
Always on danbooru

### What version of the program are you using? On what operating system?
Tried it on both the nightly and 5.5.2

### Please provide any additional information below
I would like if this could be fixed in the post-filter method or that you can select in the settings to skip webm/mp4 files

**Comment by Bionus** [comment]
Indeed, it would seem that danbooru (recently?) added a new "meta" tag type, which was not properly read by Grabber. "webm" being one of those tags, it could not be used in the post-filtering. I pushed a fix which will be available in the next version, or already in [nightly](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly).
