### ISSUE TITLE
Partial Download from Derpibooru When Using API With More Than 15 Images/Page

### ISSUE THREAD

**Issue by zohgg** [Bionus/imgbrd-grabber#1266]
### What steps will reproduce the problem?

Batch downloading more than 15 images. 

### What is the expected behavior? What do you get instead?

All of the images as specified in the download queue. 

15 images.

### How often does this problem occur? On which sources?

Always on Derpibooru

### What version of the program are you using? On what operating system?

5.5.2 on Win10

### Please provide any additional information below

So, if I try and batch download from Derpibooru, I only get about a third of the images I selected. This can be fixed by going into my Derpibooru settings (on the actual website) and setting the number of images per page back to 15, instead of the maximum, which is 50.

**Comment by KamillaPup** [comment]
I have the opposite problem kind of.. I downloaded 55 images at once from Derpi but it isn't passing on my API key :( so I can't see the mature art.
