### ISSUE TITLE
images don't show at all

### ISSUE THREAD

**Issue by Rottyy** [Bionus/imgbrd-grabber#1269]
### What steps will reproduce the problem?
searching anything

### What is the expected behavior? What do you get instead?

to show images, if not. at least the white box but when I search it'll state like

Gelbooru - Page 1 of 0 (0 of max )

### How often does this problem occur? On which sources?
all of them

### What version of the program are you using? On what operating system?
5.5.2 on W10

**Comment by Bionus** [comment]
Does this also occurs when you disabled merged results mode?
Have you tried on the v6 release?

**Comment by PlanetKiller** [comment]
I can reproduce this, it happens for me. Happens on 7.1.0 (x64).
This happens on any source when you search a new tag\s BEFORE the current results finish loading.
It then prevents images from appearing for that source until the program is re-started.
Changing sources and back doesn't help. 
Either it is still loading the previous search's results, or it is trying to load both search results.
