### ISSUE TITLE
rule34 does not download all photos

### ISSUE THREAD

**Issue by lee27** [Bionus/imgbrd-grabber#1271]
sorry, but because if I do the full batch mode of some tags, I do not download all the images? set everything from the number of photos per page to the number of pages, but in the end I download less and fewer photos

for example, of the life is strange tag, I find 1711 images but in the end I download 1699

**Comment by lee27** [comment]
please, can someone help me? I keep getting the same error, and now after updating, I do not download the videos anymore

**Comment by MrAndre96** [comment]
Well it will filter later on your post search filter. So if it was a large batch, it will not be the exact same amount as it states at the beginning.

**Comment by lee27** [comment]
Sorry, but I did not understand

**Comment by Bionus** [comment]
What tag were you trying to download?

**Comment by lee27** [comment]
"life is strange"  some photos is as if I skip them, as soon as I get home I take a test and place a screen

**Comment by lee27** [comment]
I count in total, 1724 images, but using the batch download I download 945 and then the download stops, as you can see from the screen
http://images2.imagebam.com/51/59/4b/9c7705892694274.png
why? T_T

**Comment by lee27** [comment]
has anyone understood why? sorry if I'm nagging, but I'm also curious!

**Comment by lee27** [comment]
why did you stop helping me? have not you found a solution? T_T

**Comment by TrizzyTrayRogers** [comment]
Did u figure it out im having the same problem
