### ISSUE TITLE
Sometimes a different image shows when clicking on a thumbnail. Intended image is also not the one selected for download.

### ISSUE THREAD

**Issue by SemifKnight** [Bionus/imgbrd-grabber#1272]
### What steps will reproduce the problem?
This only happens sometimes, but the last time it did, I unchecked the "Ignore images containing a blacklisted tag", and then the right image loaded when clicking the thumbnail. The blacklisted tag that seemed to trigger it that time was newhalf. 

### What is the expected behavior? What do you get instead?
The expected behavior when clicking or selecting a thumbnail in the search view is that the image the thumbnail is based on will load, but instead, sometimes a different image loads. This also applies to selecting the images for download. When I "Ctrl + Click" the thumbnail and click "Get selected," the wrong image is what is put in the download list, and the intended image is not.

Re-enactment of the issue behavior:
1.
![001 grabber issue](https://user-images.githubusercontent.com/34590104/41079323-f3b3d986-6a53-11e8-8c75-684da769331d.png)

2.
![002 grabber issue - thumbnail to click](https://user-images.githubusercontent.com/34590104/41079487-89604780-6a54-11e8-905b-2216540539b2.png)

3.
![003 grabber issue - what is loaded](https://user-images.githubusercontent.com/34590104/41079494-8fefee3e-6a54-11e8-9726-8c2fd64adf35.png)

4.
![004 - grabber issue - correct image](https://user-images.githubusercontent.com/34590104/41079523-a715c3ae-6a54-11e8-8de6-43b4850622b2.png)

**Update September 4 2018:** 
Video of this happening, along with the thumbnail stacking bug. The topic of this issue happens in the latter half of the video:
https://youtu.be/a2WAwxODQvM

### How often does this problem occur? On which sources?
It only occurs sometimes, and I usually notice it if I'm a few pages in deep through a search query. Last time it happened was on Danbooru and Gelbooru combined search.

### What version of the program are you using? On what operating system?
Grabber 5.5.2 on Windows 10.

### Please provide any additional information below
I remember this has happened before as well. I'm not sure if it's because of ignored images, or because of problems when loading the thumbnails in the search view, but those are both just guesses.

**Comment by SemifKnight** [comment]
Here is a link to a video of this bug that I also linked in Issue #1408

https://youtu.be/a2WAwxODQvM

**Comment by Axelrhode** [comment]
I also got this issue. I click on a different thumbnail but for some reason, the first image I loaded is the one that gets loaded on the next set of clicks I do. It's also automatically downloaded into my grabber folder
