### ISSUE TITLE
Following downloaded images bug

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1273]
### What steps will reproduce the problem?
Download a batch of images first and after that download it again. You see that it will not follow the downloaded images when they are skipped like in the previous versions.

### What is the expected behavior? What do you get instead?
Following the images even when they are skipped because they already exist

### How often does this problem occur? On which sources?
Always and I guess on every source (tried with konachan)

### What version of the program are you using? On what operating system?
using the latest version 6.0.0 with windows 10

**Comment by Bionus** [comment]
Indeed, only actual downloads are currently being "followed", instead of also following errors and skipped images (from blacklisting or already existing).

I pushed a fix, and I'll release v6.0.1 tonight, thanks for the report! 👍
