### ISSUE TITLE
e621 not loading thumbnails

### ISSUE THREAD

**Issue by chaimao403** [Bionus/imgbrd-grabber#1274]
### What steps will reproduce the problem?
After the search for the author's name

### What is the expected behavior? What do you get instead?

I searched the number of pages

### How often does this problem occur? On which sources?

All the time

### What version of the program are you using? On what operating system?

win7

### Please provide any additional information below

![qq 20180609061305](https://user-images.githubusercontent.com/40075348/41183290-90d64ab0-6bac-11e8-9c38-f447f6a94c0c.jpg)

**Comment by Bionus** [comment]
Indeed, it would seem that e621 is using the DB 2 XML format for their API, which wasn't being taken into account for this DB 1 source.

I pushed a fix, and I'll release v6.0.1 tonight, thanks for the report! 👍
