### ISSUE TITLE
Rule34Hentai: Getting Files with the extension ".Undefined" end of every file

### ISSUE THREAD

**Issue by vector58** [Bionus/imgbrd-grabber#1275]
### What steps will reproduce the problem?
Search any tag or no tags and hit download.

### What is the expected behavior? What do you get instead?
I should be able to download the files with the correct file extension. Instead I get files ending with ".undefined"

### How often does this problem occur? On which sources?
Always. Rule34Hentai 

### What version of the program are you using? On what operating system?
6.0.0  / Windows 10

### Please provide any additional information below
With this new update, the files I download at Rule34Hentai has an extension .undefined instead of webm. I also notice the there is a -1.00 B on the Filesize column in the Batch download window.
 
My filename format
%id% - %all%.%ext%

![capture](https://user-images.githubusercontent.com/34071973/41186658-d0ef143a-6b5f-11e8-8184-1f3d39a6cc76.JPG)
![capture2](https://user-images.githubusercontent.com/34071973/41186659-d0fce984-6b5f-11e8-8f22-e47bb872f0c1.jpg)

**Comment by Bionus** [comment]
Seems like the switch to JavaScript sources caused a few problems here.

I pushed a fix, and I'll release v6.0.1 tonight, thanks for the report! 👍
