### ISSUE TITLE
Grabber reports insufficient space error if destination directory doesn't exist.

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#1276]
### What steps will reproduce the problem?

Queue a Tag for download.
Under the Downloads tab, specify a non-existent destination path under the "Folder" column.

### What is the expected behavior? What do you get instead?

**Expected:** 
Skip the queued Tag item with the non-existent path entirely and display the non-existent destination error message only once.

**What happens:** 
Grabber displays an insufficient space error message dialog for every applicable image under the queued Tag, requiring the user to click "Ok" repeatedly until all the images in the queued Tag item with the non-existent destination path are resolved.

Sometimes Grabber will crash if there are more Tag items left in the download queue.

### How often does this problem occur? On which sources?

This occurs every time a non-existent destination path for a queued Tag item is encountered in the Downloads queue.

### Additional notes

Grabber ignores the "Simultaneous downloads" setting and uses a single download thread to resume the rest of download of the queued Tag that generated the insufficient space error when the user creates the missing download destination path while the download is in progress.  However, any other Tag items remaining in the download queue are completed using the correct number of Simultaneous downloads.

After the queued Tag item is fully downloaded, the "Resume/Pause" and "Skip" buttons don't do anything, the Batch download dialog remains on the screen, and the entire download queue is stopped, forcing the user to click "Close" and restart the download queue in order to complete the rest of the download queue.

### What version of the program are you using? On what operating system?

Grabber 6.0.0
Windows 10 Pro

**Comment by Bionus** [comment]
Indeed, I could reproduce this bug.
It seems that the downloader stopped creating the download directory at some point. I pushed a fix, and I'll release v6.0.1 tonight, thanks for the report! 👍 

I also fixed the issue you mentioned in your "Additional notes", the downloads weren't being completely stopped when a disk error occured.
