### ISSUE TITLE
e621 not loading/working fully?

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#1277]
### What steps will reproduce the problem?

load e621- try it with an account loaded into the settings with https on with 75 images per page selected

### What is the expected behavior? What do you get instead?
Grabber doesn't seem to load any images from the site, or at least, it doesn't get the front-page or images unless you search some tags for it, but there seems to be less or something- I'm not quite sure what it is.

### How often does this problem occur? On which sources?
e621, probably e926 also. 

### What version of the program are you using? On what operating system?

Win7
6.0.0

### Please provide any additional information below
Twentypercentcooler works despite this, with I think uses a similar framework to e621- that said, given the fact that I use accoutn logins for choice numbers of the popular sources loaded into my grabber, whatever changes you made in this update may have done something.

Additionally- I've noticed the sites which are based on Gelbooru 0.1 are actually loading more frequently compared to the prior edition where for some reason, they'd kind of work, but then dwindle due to the ammount being loaded or something along those lines.

I think the addition of more config options may have also affected this on my side.

Does a fresh install with e621 on it work?

**Comment by SultrySamthepennanceman** [comment]
Anyhow, here are my crashes- I've had two today. one from the Nonexistent directory error and another I think from something else- might have been on the previous edition.
Great work as always. 
https://anonfile.com/G0edO0ecb6/crashes.7z

**Comment by SultrySamthepennanceman** [comment]
Also do you have a 'default' preset in the presets bar yet? I just attempted to create a new settings.ini- backing up my old one, and It's got none of my older ones and only loads danbooru on the front page.

**Comment by SultrySamthepennanceman** [comment]
Alright then- It seems something fixed itself, I deleted my settings.ini moved the contencts of [SourcePresets] in the older one to the newer one generated, deleted my wordsc.txt, filenamehistory, main.log, md5s.txt restore.igl, crashes from my crashes folder- and now e621 is working, AND This has seemingly solved https://github.com/Bionus/imgbrd-grabber/issues/1276's problem.

I guess something about the newer files conflicted when they overwrote or merged with the existing ones from the previous edition. 

The tags being a long steam of endless numbers is still and issue though.

**Comment by SultrySamthepennanceman** [comment]
nevermind, it just went back to being the same as before again, despite working.

**Comment by SultrySamthepennanceman** [comment]
So it's something to do with those generated configs at least.

**Comment by SultrySamthepennanceman** [comment]
alright, tried again, this time, removed favorites.json, lastdump.file settings.ini.fl6656 and settings.ini.Uh5300- e621 seems to be working- will add my presets back to the regular newly generated settings.ini now.

**Comment by SultrySamthepennanceman** [comment]
Downloaded from the following sites of e621, rule34.paheal.net rule34.xxx, rule34hentai.net with the tags "animated" and "SFM" and grabbed the first page- C:\Users\USER\Pictures\test -no Error message saying I'm out of space- just have to wait for this to finish, then I'll add the presets.

**Comment by SultrySamthepennanceman** [comment]
Oh right, just to mention- I added my proxy (Privoxy) again to the settings via the programs interface- that doesn't seem to conflict with anything (bar the usual use it has in parsing out sites blocking you for making too many requests, which is normal and why it is useful.)  and get more precise tags while searching images is still active- I usually have it off to account for Gelbooru 0.1 added sources from http://booru.org/top as most of their stuff is tagged, untagged or under different terminology.

**Comment by SultrySamthepennanceman** [comment]
Added my old presets, back- checked e621, rule34.paheal.net rule34.xxx, rule34hentai.net with the tags "animated" and "SFM" Pages loaded correctly, it's fixed.

So it seems anyhow.

**Comment by Bionus** [comment]
Seems to be very related to #1274, which is that the XML source is broken for e621.

I don't know how you managed to fix it on your end though, because there's no way the XML parsing would fix itself. Maybe you changed the source selection order? If you remove "XML" or have "JSON" above it, e621 should work.

![image](https://user-images.githubusercontent.com/882719/41193881-2b72b5b6-6c13-11e8-8dce-4dd931605fb1.png)

> Does a fresh install with e621 on it work?

Nope, it would not work.

> Also do you have a 'default' preset in the presets bar yet?

Not sure I understand this question?

> The tags being a long steam of endless numbers is still and issue though.

Can you elaborate on this?

I don't have this issue on my end, which source are you using? If it's e621, it might be related to the original bug with it, which should be fixed in nightly (soon v6.0.1).

**Comment by SultrySamthepennanceman** [comment]
Also do you have a 'default' preset in the presets bar yet?

Not sure I understand this question?
basically, on the preset's bar on sources, there should be a 'default' preset, which has the default sources that come with the program preselected. 

Anyhow, it fixed itself, e621 works just fine.

**Comment by Bionus** [comment]
>  basically, on the preset's bar on sources, there should be a 'default' preset, which has the default sources that come with the program preselected.

I'm not convinced this would be used by many users.
If necessary, you can manually create this preset. Actually, Grabber doesn't differentiate at all between default and added sources.

> Anyhow, it fixed itself, e621 works just fine.

Well in that case I'll close the issue.
