### ISSUE TITLE
Crashing and not downloading E621.net images

### ISSUE THREAD

**Issue by Rezboa** [Bionus/imgbrd-grabber#1279]
### What steps will reproduce the problem?
Using E621 as a source and downloading via GET ALL

### What is the expected behavior? What do you get instead?
Download the images, instead, it shows no images and errors in the download screen

### How often does this problem occur? On which sources?
Every time I try to download E621

### What version of the program are you using? On what operating system?
Windows 10 on the latest update, forgive me I don't know but today's date is 6-09-2018

**Comment by Bionus** [comment]
Are you using v6.0.0? You can see the version in the "About > Grabber" window.
If you are, you should update to v6.0.1 which fixes e621 (see issue #1274).

**Comment by Rezboa** [comment]
My apologies for not even checking to see if there was a new version available. I was using v6.0.0 and I am downloading the newest version now.
