### ISSUE TITLE
Amount of images/pages not correctly displayed on some sources

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1280]
### What steps will reproduce the problem?
When you have a limited amount of images for a search it will for some sources display a ? for the pages and images. So when there are for example 5 images on a page and you set the max amount of images on a page to 4 it will display on the first page that there are 4/8 (which is the first part of the problem) images and 1/2 pages. But when you go to the next page it will display page 2 of ? and 1 of ? images. When you now click on download all images it will only download 1 image and will not count those on the first page. Here are some screenshots (tested it with the search tropical_liquor rating:safe):
[https://i.imgur.com/KNvZZ56.png](https://i.imgur.com/KNvZZ56.png)
[https://i.imgur.com/GKbVhaS.png](https://i.imgur.com/GKbVhaS.png)
[https://i.imgur.com/4kgtCa9.png](https://i.imgur.com/4kgtCa9.png)
[https://i.imgur.com/wAVYB5U.png](https://i.imgur.com/wAVYB5U.png)

### What is the expected behavior? What do you get instead?
it will display the correct amount of images and pages when on the last page and the correct amount on the first page if there aren't enough images to fill the first limit.

### How often does this problem occur? On which sources?
it occurs everytime and seen it with the sources konachan, yande.re and danbooru

### What version of the program are you using? On what operating system?
i am using 6.0.1 with windows 10

**Comment by MrAndre96** [comment]
For gelbooru you have the issue that it will display on the 3e page by the search tropical_liquor rating:safe the results from page 1 and not like the other 'no result'. Here a screenshot:
[https://i.imgur.com/bYuDFtw.png](https://i.imgur.com/bYuDFtw.png)
[https://i.imgur.com/kl9xQGV.png](https://i.imgur.com/kl9xQGV.png)

**Comment by Bionus** [comment]
Indeed, I could reproduce all those issues.
I pushed a fix, which will be included in release v6.0.2 tomorrow, thanks for the report! 👍

>it will display on the first page that there are 4/8 (which is the first part of the problem) images
> [...]
> and the correct amount on the first page if there aren't enough images to fill the first limit.

Note that sometimes, Grabber does not know the total number of images, and will infer it from the number of pages. In your case, it knows there are 4 images per page, and 2 pages. It will therefore "guess" that there should be around 8 images total.

To make it clearer, I added a "~" symbol when Grabber does this. It will look like "Page 1 of 2 (4 of ~8)".

**Comment by MrAndre96** [comment]
Saw that the following sources rule34.xxx, safebooru.org and zerochan experiencing the same bug as gelbooru.  I tested it with nekopara rating:safe and set the page number to 30. Here are some screenshots:
[https://i.imgur.com/V7W7SqI.png](https://i.imgur.com/V7W7SqI.png)
[https://i.imgur.com/HmMDyMf.png](https://i.imgur.com/HmMDyMf.png)
[https://i.imgur.com/AJQz5dO.png](https://i.imgur.com/AJQz5dO.png)

I also found an intresting bug with the page limit for zerochan. It will ignore it always and stays on 23. Here a screenshot:
[https://i.imgur.com/uqBNJ55.png](https://i.imgur.com/uqBNJ55.png)

**Comment by MrAndre96** [comment]
Also rule34.paheal.net has the same issue as zerochan. With that it isn't able to filter on the amount of results on a page. So it will always have 23 instead of the specified number. (Don't know if they are based on each other or not.)

Als has this source the same issue as in this topic #1281. (Don't know if they are based on each other or not.) Here is a screenshot:
[https://i.imgur.com/iuhuKWu.png](https://i.imgur.com/iuhuKWu.png)

**Comment by Bionus** [comment]
> Also rule34.paheal.net has the same issue as zerochan. With that it isn't able to filter on the amount of results on a page. So it will always have 23 instead of the specified number. (Don't know if they are based on each other or not.)

They're not based on each other, but neither of them allow to override the images per page. For Zerochan it will be up to 24, and for Shimmie usually 70.

> Als has this source the same issue as in this topic #1281. (Don't know if they are based on each other or not.) Here is a screenshot:
> https://i.imgur.com/iuhuKWu.png

I just pushed a fix, thanks! :+1:
