### ISSUE TITLE
e621, not retrieving total number of images/pages.

### ISSUE THREAD

**Issue by modicon** [Bionus/imgbrd-grabber#1281]
### What steps will reproduce the problem?

Use a tag with a large number of pages. Blank works, too.

### What is the expected behavior? What do you get instead?

I expect (where x is a number):
Page 1 of X (20 of X).

Instead:
Page 1 of ? (20 of ???).

Sometimes this, but there is more than 300 images associated with the tag.
Page 1 of 15 (20 of 300)

### How often does this problem occur? On which sources?

Always. Source is e621.

### What version of the program are you using? On what operating system?

v6.0.1
Win 10

### Please provide any additional information below

In the log, it appears to end up retrieving Pages (-1).

I was actually using a fairly old version which worked alright (still does, so I'll stick with that v5.5.2). So I can't say whether this was a problem in v6.0.0.

**Comment by MrAndre96** [comment]
This bug is for more than one source like also for danbooru and zerochan etc. Don't know only if this is a limit set by those websites or if this is a bug.

**Comment by Bionus** [comment]
Indeed, Grabber is not getting the image count anymore for Danbooru XML sources (which e621 is part of).

I pushed a fix, which will be included in release v6.0.2 tomorrow, thanks for the report! 👍

**Comment by sanddudu** [comment]
Just reproduced this bug in 6.0.1 (Source is e621). It seems only happened when you search any keyword begin with an uppercase letter. You could just change all letters to lowercase to fix this, but still, that is a bug.
