### ISSUE TITLE
Crashing when restoring a session with more than one source

### ISSUE THREAD

**Issue by xodiack** [Bionus/imgbrd-grabber#1282]
### What steps will reproduce the problem?

When trying to restore the session with more than one booru source it crashes as it goes to populate the page, from my understanding. If I launch it with no connection it will load the client fine as well as if I only use Danbooru/Gelbooru as the source it will restore fine.

If I disconnect and load the client, then reconnect searching fetches the results just fine. Also the first launch since updating to 6.01 went fine but subsequent ones lead to this problem.

### What is the expected behavior? What do you get instead?

Restoring the previous browsing session

### How often does this problem occur? On which sources?

100% of the time with Danbooru and Gelbooru selected as my sources

### What version of the program are you using? On what operating system?

Grabber 6.01 and W7 64bit

*Happened on 6.02 aswell

### Please provide any additional information below

Crash dump:[7298398b-9651-4bc0-b3be-4a1965f939ee.zip](https://github.com/Bionus/imgbrd-grabber/files/2087551/7298398b-9651-4bc0-b3be-4a1965f939ee.zip)

Some logs with notes for their circumstance:[Logs.zip](https://github.com/Bionus/imgbrd-grabber/files/2095937/Logs.zip)

**Comment by xodiack** [comment]
I added some logs after testing with a clean install, is there anything in those logs that stand out as something I need to fix on my end?

**Comment by Bionus** [comment]
Ok I think I know where it might come from.

And the problem would not come from which sources you choose, but from how many tabs with the same sources you have. The problem doesn't occur every single time, right?

**Comment by xodiack** [comment]
Its not every single time, I'm slowly adding my old settings back into the appdata directory and the culprit folders are Danbooru 2.0 and Gelbooru 0.2. Adding either of these folders causes the behavior I described in the OP to occur.

Its not 100% of the time now that I've been testing it. I don't have Grabber set to restore all my tabs upon loading so if the focused tab 1 loads, going to tab 2 or tab 3 can lead to the same style of crash for me.

**Comment by Bionus** [comment]
So from what you say it crashes as soon as 2 or more tabs are loading at the same time?

**Comment by xodiack** [comment]
The crash happens when a single tab is loading usually when its around 75% on the progress bar. I'm not loading more than one tab at a time unless having multiple sources merged is considered more than one tab.

**Comment by Bionus** [comment]
When transferring the files from your old settings to the new ones, do you also overwrite the `model.js`/`model.xml` files? From the video it seems like not, but I'm asking just to make sure.

Since I couldn't reproduce this crash at all on my end, I added more logging and more debug information to the 6.0.3 release. If you could send me a dump / log file for that version, I'm pretty sure I'd be able to reproduce and fix. 👌 

> I think its my settings for Danbooru and Gelbooru that are the culprit for the crashes, I've set it to throttle slightly to try and be nicer to the servers.

That may be the case, if it causes both loadings to occur at the very same time, some race condition or non-thread safe object might break.

**Comment by xodiack** [comment]
Since returning to default settings on Dan/Gel I was able to use it without a crash last night. On 6.03 now if I go to replicate the crash with my settings added in it leads to a crash of the entire program rather than it catching itself in a crash.

Here is the information the windows crash gives if it is of some help in tracking down the cause:
[6.03_Crash.txt.zip](https://github.com/Bionus/imgbrd-grabber/files/2103827/6.03_Crash.txt.zip)
