### ISSUE TITLE
Question: how are you supposed to update a source

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1284]
### What steps will reproduce the problem?
How are you supossed to update a source when you see by the source list that there is a update for it available? Here a screenshot:
[https://i.imgur.com/G87XqbH.png](https://i.imgur.com/G87XqbH.png)

### What is the expected behavior? What do you get instead?
Well you aspect to have a option somewhere in the options tab for that source to update it or in the options tab for the program to update all sources but couldn't find it anywhere.

### What version of the program are you using? On what operating system?
Well am using 6.0.1 but doesn't really matter with this I guess

**Comment by Bionus** [comment]
You can't. For the time being, it's only an indicator.
The ability to update isn't implemented yet (it will later), because the source system was rewritten for v6.

But I still fixed the issue that Grabber tells there's an update for Anime Pictures even though there isn't.
