### ISSUE TITLE
Not being able to login on Sankaku Complex

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1288]
### What steps will reproduce the problem?
Go to the source list and try to put in your credentials. When you click on test it will always say that it fails althought it has the right credentials. Here is a screenshot: 
[https://i.imgur.com/mzvI78L.png](https://i.imgur.com/mzvI78L.png)

### What is the expected behavior? What do you get instead?
Being able to login when I click on test. What I get instead is a failure message when I try to login.

### How often does this problem occur? On which sources?
Everytime on chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
Version 6.0.1 on windows 10

**Comment by Bionus** [comment]
You can actually login, it's just that the testing itself fails.

It works by trying to load a far away page (by default 100 for Sankaku), considering that anonymous users can't load said page, but logged in users can. But it seems Sankaku updated their page limits and it's now 25 for anonymous users and 50 for logged in users.

You can change the setting here:
![image](https://user-images.githubusercontent.com/882719/41247507-728fd518-6dae-11e8-93ea-21ad3500228e.png)

The default value will be set to 50 in the next version 👍
