### ISSUE TITLE
Sankaku Complex duplicate results on the same page and amount of pages not correctly with the results

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1289]
### What steps will reproduce the problem?
Search for the tag 'tropical_liquor rating:safe' on Sankaku Complex chan and it will diplicate the results. You will see that there are now 8 of 4 results. (This only happens when the page limit is double the amount of the search results.)
There is also a bug when you search 'tropical_liquor -rating:safe'. You will see that there are 20 of 42 results and 1 of 21 pages when you set the images per page to 2. So the number of pages are in this situation not correctly displayed.
Here are some screenshots:
[https://i.imgur.com/QMGTPta.png](https://i.imgur.com/QMGTPta.png)
[https://i.imgur.com/WxrDb1Q.png](https://i.imgur.com/WxrDb1Q.png)

### What is the expected behavior? What do you get instead?
Displaying to normal amount of results on the page and no duplicate and have the image per page correctly affect the amount of images on a page.

### How often does this problem occur? On which sources?
Always on chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
I am using 6.0.1 with windows 10

**Comment by Bionus** [comment]
It seems that the 4 "top" images on Sankaku aren't properly removed when there is only one page of results, so you get the results + the 4 top images (in your case 4 + 4 = 8).
