### ISSUE TITLE
Getting all images will also get images of sources without any results

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1292]
### What steps will reproduce the problem?
Just search with a tag where one of the sources don't have any results with and click on get all. After that you will see that source on your download list which had no results while it shouldn't be there. (At least one of the selected sources need to have results to get it to work)

### What is the expected behavior? What do you get instead?
Only show the sources which had results.

### How often does this problem occur? On which sources?
Always and the source doesn't matter

### What version of the program are you using? On what operating system?
Version 6.0.2 with windows 10 (New bug since 6.0.1 to 6.0.2)

**Comment by Bionus** [comment]
Most likely broken by 9b5fdda777aacb131ebd1253b8178342c0a7cb45, I'll take a look.
