### ISSUE TITLE
Zerochan not displaying results correctly

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1295]
### What steps will reproduce the problem?
When you search for example tropical_liquor with the source zerochan there is a possibillity that you will get nothing back and it will just display a blank page. (On searches where there are no results). Also when you search for example nekomimi it has an error that it doesn't know how many images there are and it will display 100 images instead of the usual 23. Here are some screenshots:
[https://i.imgur.com/12DlBPH.png](https://i.imgur.com/12DlBPH.png)
[https://i.imgur.com/apP8pFo.png](https://i.imgur.com/apP8pFo.png)

### What is the expected behavior? What do you get instead?
Displaying the normal message that there are no results and getting to see how many images there are with a normal amount of images displayed.

### How often does this problem occur? On which sources?
The first problem could sometimes not occur but it does most of the time and the second problem always on the source zerochan

### What version of the program are you using? On what operating system?
6.0.2 on windows 10

**Comment by MrAndre96** [comment]
Could you maybe still look at the problem with the large amount of results for each page with zerochan when you search tags like 'pokemon'

**Comment by Bionus** [comment]
This should have been fixed by f1c81d794b5e2641dd175c80eea3b86dc28c0307 / 987712813cbc68b79cccfb325f0d25faae65028d.
