### ISSUE TITLE
Image count not always displayed correctly when there is only one page

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1296]
### What steps will reproduce the problem?
Search for example 'endless_dungeon' with the sources chan.sankakucomplex.com and yande.re enabled. You will see that chan.sankakucomplex.com doesn't know how many images / pages there are and that yande.re couldn't count the images correctly (There are 2 images and it says 2 of 1). Here are some screenshots:
[https://i.imgur.com/eP6SWh9.png](https://i.imgur.com/eP6SWh9.png)
[https://i.imgur.com/sinupZm.png](https://i.imgur.com/sinupZm.png)

### What is the expected behavior? What do you get instead?
Displaying the correct count of images.

### How often does this problem occur? On which sources?
Everytime with sankaku complex and yande.re (Possible also others)

### What version of the program are you using? On what operating system?
Version 6.0.2 with windows 10

**Comment by Bionus** [comment]
## chan.sankakucomplex.com

I just pushed a few fixes to improve page/image count parsing.

However, note that there are some cases where the page/image count is impossible to determinate:
* No search: Sankaku doesn't give the information of the total number of images on the site.
* More than one tag, and not on the last page: Sankaku only gives the individual tag count, not the number of results returned by a given search. Grabber only knows when it arrived at the last page and the `>>` link isn't a link anymore.


## yande.re

For yande.re image count, it seems to actually be a bug in Moebooru.
Either that or some weird behavior.

There are indeed two posts there, but one ([link](https://yande.re/post/show/300667) **NSFW**) is "held from the index by the poster" and doesn't appear in normal search results, but does appear in the API results (with a `is_held` flag set to `true`). However, even with that being the case, it is still not taken into account in the count for the API (see [link](https://yande.re/post/index.xml?limit=20&page=1&tags=endless_dungeon)): even though there are obviously two results (`<post>`), the count is still set to 1 (`<posts count="1">`).

Grabber always trusts the API, but it this case it's behaving strangely.

I see three options:
* Get the maximum between the image count from the API and the number of results returned by the search. In this case, `max(1, 2)` will give the correct result of `2`.
* Hide posts where `is_held` is set to `true`. While it seems to be a nice way to handle it, given the nature of this program I'm not sure about voluntarily hiding results from the user.
* Do nothing and file a bug report in [Moebooru issue tracker](https://github.com/moebooru/moebooru/issues).

**Comment by MrAndre96** [comment]
I think that it is than the best to do nothing about the strange result by yande.re. Since the cause is now not by grabber but by their API.
