### ISSUE TITLE
Certain post filters aren't getting back any results on gelbooru/danbooru

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1302]
### What steps will reproduce the problem?
When you try to search 'width:1920 height:1080' on gelbooru or danbooru you get back results on your normal search. But when you put the same inside the post filtering you aren't getting back any results.

### What is the expected behavior? What do you get instead?
I aspect that you get the same results by post filtering as by your normal search.

### How often does this problem occur? On which sources?
Always on danbooru / gelbooru

### What version of the program are you using? On what operating system?
Version 6.0.2 with windows 10

**Comment by Bionus** [comment]
That's actually normal.

Post-filtering works by performing the search according to your tags, then filtering the results with your "post-filters". So if you search without any tag and with "width:1920 height:1080" as post-filters, it's likely you won't get any results, as most images aren't 1080p exactly.

However, searching a tag such as "wallpaper" and using the "width:1920 height:1080", I as expected get a few results:

![image](https://user-images.githubusercontent.com/882719/41369391-05f2e02e-6f45-11e8-81cc-4abdd64a92b8.png)

This feature is useful for sources that limit the number of tags you can use for a search, or sources that don't recognize some meta-tags.

**Comment by MrAndre96** [comment]
Ah I see searched before with the tag game_cg but it didn't show up on the first page so thought it was broken
