### ISSUE TITLE
help fix this 

### ISSUE THREAD

**Issue by sinkiller21st** [Bionus/imgbrd-grabber#1304]
problems: 
1ST: selecting sources 
2Ed: favorites been wiped and now don't show up

what happens:
crash 

how often:
every time

witch version:
Grabber_6.0.2

extra info that might help to fix grabber 
scents I updated it from the previous version it gave me nothing but problems I even hade to download 
visual c++ redistributable 64bit version and it still did not work and then I try the 86bit version and it finally came back but it is cos  me even more problems with more crushes and wiping my favorites out 
in grabber I'm very dissatisfied please fix this and send me a working grabber my email is sinkiller21st@gmail.com please contact me and help cos I really loved grabber and used all the time so it hurts me to send and say all these please understand if I got it throw a bad link please send me a working grabber link the links I used was https://github.com/Bionus/imgbrd-grabber   & http://www.softpedia.com/get/Internet/Download-Managers/Grabber.shtml  
I hope you can help

**Comment by Bionus** [comment]
> what happens:
> crash

If you have a crash, please update to 6.0.3, reproduce your crash (if you can) and upload the crash dump from that crash. They can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber/crashes`.

> favorites been wiped and now don't show up

Is there any `favorites.txt` or `favorites.json` file in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`? If so, what do they contain?

**Comment by sinkiller21st** [comment]
my previous grabber before it askt me to update was a  favorites.txt but
thin it turned to a  favorites.json I tried to copy and paste from the
.text to the .json but it would not seave

here are the crash dump files

**Comment by Bionus** [comment]
> my previous grabber before it askt me to update was a favorites.txt but thin it turned to a favorites.json I tried to copy and paste from the .text to the .json but it would not seave

It's normal that favorites were converted from TXT to JSON, that's part of the 6.0.0 update.

> here are the crash dump files

I guess you added them as enclosed files in your email, but that doesn't seem to work with github. You should add them directly from the github UI (and make sure those are 6.0.3 crash dumps).
