### ISSUE TITLE
Sankaku not downloading 

### ISSUE THREAD

**Issue by dabdabdebil** [Bionus/imgbrd-grabber#1307]
### What steps will reproduce the problem?
Setting the source to Sankaku and trying to download an image in any way

### What is the expected behavior? What do you get instead?

To download images
Problems every single time. No matter what I set the download folder to. No matter what I set the links to. There's always a problem 

### How often does this problem occur? On which sources?

All the time. Sankaku

### What version of the program are you using? On what operating system?

6.0.3 windows 7

### Please provide any additional information below

I'm not sure if its supposed to work yet, but if it is, then please tell me anything to try to try to make it work. Because there are images only Sankaku. And Sankaku usually has twice as many

**Comment by jukebox1412** [comment]
Try changing user agent in Sankaku's source to Mozilla/4.78 [en] (Windows NT 5.0; U)
![image](https://user-images.githubusercontent.com/22598492/41495693-3ed082a6-70ea-11e8-82d3-a54265ac031b.png)

**Comment by urain39** [comment]
See https://github.com/Bionus/imgbrd-grabber/issues/1321

**Comment by Bionus** [comment]
>  Problems every single time. No matter what I set the download folder to. No matter what I set the links to. There's always a problem

You should explain your "problems" in more details,; so that they can be fixed.
