### ISSUE TITLE
Graber don't search tag "explicit" on derpibooru

### ISSUE THREAD

**Issue by VanTuz5** [Bionus/imgbrd-grabber#1309]
The program don't search for images with the tag "exllicit". I even entered the data to login the site, but the search result is still empty.

**Comment by zoameldar** [comment]
Derpi is using safe filter as default. You need to open browser, log in, set filter that allow explicit, go to under your account, copy api kay and log in in grabber but instead password use api key.

**Comment by VanTuz5** [comment]
On other sites I must do the same?

**Comment by zoameldar** [comment]
sankaku you need to use rating:explicit. should work fine from start.

**Comment by VanTuz5** [comment]
Nope, he found nothing.

**Comment by zoameldar** [comment]
sankaku is tricky overall because its block you, search in topics here. people have solutions how to get around it.
For easy way around use rule34.xxx or gelbooru. They have almost as many pics as sankaku with less duplicates.

**Comment by Bionus** [comment]
I can't reproduce your problems.
On derpibooru, once I provide my API key, I can search explicit results with no issues:
![image](https://user-images.githubusercontent.com/882719/41810280-555e215a-76fc-11e8-8f85-980d0fc2db22.png)
![image](https://user-images.githubusercontent.com/882719/41810282-5bbaa78a-76fc-11e8-8a87-56e7a61f3b00.png)

> And now problem with rule34.xxx
> "This XML file does not appear to have any style information associated with it. The document tree is shown below.

I don't see how an error shown by a browser is related to Grabber?
