### ISSUE TITLE
Ubuntu build error (Grabber 6.0.0+)

### ISSUE THREAD

**Issue by Babyforce** [Bionus/imgbrd-grabber#1318]
### What steps will reproduce the problem?

Trying to build the software (6.0.0 or above) on Ubuntu 18.04 (Or any other version, I suppose) using both the build.sh and the code to type in the terminal on the wiki.

### What is the expected behavior? What do you get instead?

The software is supposed to build successfully.
Instead, it gives an error, and always the same one.

### How often does this problem occur? On which sources?

It occurs every time I try to build the software, both by using the commands found on the wiki and by launching the build.sh

It also occurs when I either clone the repo and try to build it or directly download the source code from the releases and try to build it.

### What version of the program are you using? On what operating system?

Starting version 6.0.0 of the software and above. It works for the 5.5.2 version though.
Using Ubuntu 18.04

### Please provide any additional information below

`[ 15%] Generating YourLanguage.qm
[ 15%] Built target CrashReporter_translations
Updating '/home/babyforce/imgbrd-grabber-6.0.2/build/languages/YourLanguage.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 840 untranslated source text(s)
[ 15%] Built target General_translations
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
mv: cannot stat 'build/gui/Grabber': No such file or directory
Grabber has been compiled in the release directory. To run it, type './release/Grabber'`

Creating a folder called "Grabber" in the folder doesn't solve anything. I don't know why it does this.

**Comment by FlugelderFreiheit** [comment]
This output doesn't really say what the error is, it just says make failed. Can you try copying the whole output of make.

**Comment by Bionus** [comment]
Very likely a duplicate of #1316.
Is your actual error "no known conversion from 'bool' to 'Site *'" or equivalent?

**Comment by Babyforce** [comment]
Here if you want the entire make output, but it's gonna take a lot of

**Comment by Bionus** [comment]
From what I see it seems that the new 6.0 NPM dependency was not added to the `build.sh` file.
Install NPM and re-run the build and it should fix the error (IIRC it's in package `nodejs`).

**Comment by Babyforce** [comment]
Thanks for you help. After installing nodejs and npm, the make could proceed further. However, I am now having another error, close to the end of the making.
[grabber_6-0-3_error.txt](https://github.com/Bionus/imgbrd-grabber/files/2131227/grabber_6-0-3_error.txt)
What could this be this time?

**Comment by Bionus** [comment]
That's issue #1316.
Make sure to `git pull` to have PR #1319 that fixes this (commit d2f543d81a32a4929ed2ddc93727e6771f82f4b7).

**Comment by Babyforce** [comment]
Thanks a lot for your help, it fixes it. I could make the latest version of the software.
