### ISSUE TITLE
About sankaku JSON API

### ISSUE THREAD

**Issue by urain39** [Bionus/imgbrd-grabber#1321]
See Projects:
    https://github.com/CryShana/Sankaku-Channel-Downloader
    https://github.com/urain39/KngetPy

**Comment by urain39** [comment]
It still works.

**Comment by Bionus** [comment]
Duplicate of #1250?

Any difference between the implementation in those projects compared to Grabber?
The one I saw is headers.

**Comment by urain39** [comment]
I think so, like if you try to download images without 'referer' in headers that you will get this problem, but i still dno't know why it still works on sometimes when i not set it.(may magic yet?)

**Comment by urain39** [comment]
Sorry for my issues, cuz that my English is not well.😥
