### ISSUE TITLE
Get Selected and using %search_1% token.

### ISSUE THREAD

**Issue by xodiack** [Bionus/imgbrd-grabber#1322]
I recently switched to adding %search_1% sometimes for my filename tokens which ends up as follows:

%copyright%/%artist%_%character%_%md5%_(%search_1%).%ext%

Manually saving works fine but I noticed when I use "Get Selected" and then download whatever images I chose later it works off the tag list order from the booru rather than my search. In most cases the files downloaded as a batch end up with, generally %search_1%  being the same as %copyright% rather than the %search_1% I used.

I believe this is more of a suggestion than a bug report, would it be possible to have a field for "Search" added similar to the "Tags" section of the bulk downloading of single images to make use of %search_1%?

**Comment by Bionus** [comment]
Indeed, the search is not saved when adding images one by one.
I still feel this is a bug so I tagged it as such.

I'll try to push a fix for the next release :+1:
