### ISSUE TITLE
[Question] Is there a way to hide existing images in browser?

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1325]
Like the title says, is there a way for grabber to force match all images in the browser with the md5 list?

I presume, it will cost high in terms of CPU but is it even possible?

**Comment by urain39** [comment]
For what? i think you should use the blacklist tags.

**Comment by brazenvoid** [comment]
I can't blacklist images already existing in the default download folder, its like blacklisting thousands of tags. 
Or is there a special tag which the program interprets as hiding the existing images?

**Comment by brazenvoid** [comment]
I think you misunderstood. I only wanted to hide the already downloaded images in the browser. It isn't needed always but most of the times tags are not assigned to new images but the old ones. 

And if such images number over a thousand every time I search, thus finding them out is a great time wasting effort. If the program can do this automatically, either:
1.  Get me only those which are not in the md5 list and with the specified tag group from all retrievable results. OR
2. Have a toggle for hiding those images which are already specified in the md5 list when I browse.

**Comment by urain39** [comment]
I think checking the file size is enough, if the file size is not the same then re-download it.

**Comment by brazenvoid** [comment]
I think you still misunderstand. 

I don't need anything to be re-downloaded. I only need to view and selectively download images which have been assigned tags to match certain tag group.

I think, I'll wait for @Bionus to reply.

**Comment by Bionus** [comment]
So from what I understand, this could be made working by adding a new post-filter meta-tag, such as `status:downloaded` or something. Then you'd be able to set your post-filters to `-status:downloaded` and they'd get hidden.

Would that work for your use-case?

**Comment by brazenvoid** [comment]
Yes, sir! That's exactly what I was thinking!

**Comment by Bionus** [comment]
I just added three meta-tags for post-filtering:
* `grabber:alreadyExists`: if the file already exists in the destination folder for the current filename setting
* `grabber:inMd5List`: if the file is already present in the MD5 list
* `grabber:downloaded`: any of the above

**Comment by brazenvoid** [comment]
Thank you! You are the best!

**Comment by brazenvoid** [comment]
Works great! 

BTW are there any more meta tags currently supported?

**Comment by Bionus** [comment]
Pretty much all Danbooru meta tags (with the same syntax) as long as the booru you're using support them ([cheatsheet](https://danbooru.donmai.us/wiki_pages/43049)).

For Grabber-specific ones, only the three I mentioned (`alreadyExists`, `inMd5List` and `downloaded`).

But if you think more of them could be useful feel free to suggest them.

**Comment by brazenvoid** [comment]
I think the max image age meta can be ported to grabber as a source independent filter. Many of my sites do not have support for it but as all images show a date in browser, I do think, it will not be very intensive.

**Comment by brazenvoid** [comment]
@Bionus The post filters are faulty in the latest nightly. There are instances that I find the "Already Exists" status for images which even have been downloaded in the same session.
