### ISSUE TITLE
[Crash] When multiple big images are downloading in browser

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1327]
### What steps will reproduce the problem?

Open some huge images in browser ~10MB. Or many regular sized images, about 100 or so, it does eventually crash. 

For smaller regular files, the following happens before crash:
1. The first indications are usually picture previews in the browser not getting clear even after getting fully downloaded.
2. Later even the previews are not shown, that's usually interpreted as the program begging for mercy, haha.

### What is the expected behavior? What do you get instead?

Should load all of them regardless of size. Or give a warning about the memory limit approaching or any allocation errors encountered.
Crash happens without any option to gather dump or anything else.

### How often does this problem occur? On which sources?

Always.
It is source independent.

### What version of the program are you using? On what operating system?

v6.0.3
Windows 10 x64 

### Please provide any additional information below

I have a lot of free RAM (16GB in total) and it seems that Grabber though being a 64-bit program has some memory management or allocation issues.

**Comment by Bionus** [comment]
I could indeed reproduce some huge memory leaks when loading big images in the preview window.

While I didn't go up to the crash, given loading a dozen 20MB images made Grabber use 1GB of RAM (even after closing the window), I'm not surprised keeping at it would cause allocation issues and end up in a crash.

**Comment by brazenvoid** [comment]
I think its an amalgamation of said memory leaks and many minor leaks happening in active tabs in the browser. Usually with time, I have about 10-20 multi-source tabs and 40-60 open image windows.

**Comment by brazenvoid** [comment]
Further use has confirmed that the app tries its best to not exceed 1.5GB of RAM usage. But as this control is not based on some beforehand estimation, it has some additional behaviors: 
- As soon as the limit is reached, any new image windows stop showing the image. 
- If there are some images currently being loaded before the limit had been reached, the app compensates that by discarding the image views of already downloaded images. The selection is random and not in a sequence.

**Comment by brazenvoid** [comment]
There is some anomalous behavior of Grabber with memory usage. Images of less than 15MB size can propel it to ~1.2GB. 
In comparison, I had opened 25 images of over 180MB in another Qt based viewer named XnViewMP which consumed ~2.3GB.
