### ISSUE TITLE
Crash when a source takes to long to load

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1329]
### What steps will reproduce the problem?
Pretty hard to reproduce but sometimes when sankaku complex takes to long to load it could create a crash without a crash dump.

### What is the expected behavior? What do you get instead?
Just a message by that source that there was a timeout instead of a crash from grabber.

### How often does this problem occur? On which sources?
It happens most of the time just with sankaku complex since that source sometimes has a long response time.

### What version of the program are you using? On what operating system?
Version 6.0.3 with windows 10

**Comment by Bionus** [comment]
I just tried loading a source which loads infinitely, and didn't get a crash.

Could there be another reason for this crash? (does the memory keeps increasing during the page load for example)

**Comment by MrAndre96** [comment]
Found out that it has to do with the interval. When you for example put every interval for sankaku complex to 8 (So it will crash pretty fast) and search for nekopara it will crash directly. Had put it on other values before since sankaku complex will deny your request without any interval by details with batch download.

**Comment by Bionus** [comment]
Is this crash still relevant since you created #1342?

**Comment by MrAndre96** [comment]
No I made a other topic since the crash was related to that I found out later
