### ISSUE TITLE
Error page numbers / also login causes no images to display at all on ATF Booru

### ISSUE THREAD

**Issue by lolrein** [Bionus/imgbrd-grabber#1338]
### What steps will reproduce the problem?

Add atfbooru.ninja to sources as a danbooru, search a term you want to see.

### What is the expected behavior? What do you get instead?

For search to come up with a result like this ![ss 2018-07-11 at 15 06 28](https://user-images.githubusercontent.com/41102080/42552557-10aef9f2-851c-11e8-9a14-862df2ab869d.png)

instead shows up like image below, and you cannot "download all" as it isnt sure how many pages there are and will only do 1 page. You can however force to page 2, and it will say page 2/?

![ss 2018-07-11 at 15 09 44](https://user-images.githubusercontent.com/41102080/42552666-970177e6-851c-11e8-9d83-523ff1f18f8e.png)

### How often does this problem occur? On which sources?

Always on (atfbooru.ninja)

### What version of the program are you using? On what operating system?

6.0.3 grabber,
windows 10 latest

### Please provide any additional information below

providing login details breaks the grabber from displaying anything search results at all from mentioned booru

**Comment by Bionus** [comment]
Hello!
Sorry for the late reply 😅 

Indeed, I could reproduce this issue on 6.0.3 with aftbooru.ninja (or any other Danbooru 2.0 source), and it should have been fixed in the 6.0.4, with the fix for issue #1331.
