### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by zoameldar** [Bionus/imgbrd-grabber#1340]
I would want to translate the program to my language how can I do that?

**Comment by MrAndre96** [comment]
Here on the wiki page you can see how to translate the program: https://github.com/Bionus/imgbrd-grabber/wiki/Translation

**Comment by zoameldar** [comment]
Yea I already found that, but thx.

**Comment by Bionus** [comment]
> Here on the wiki page you can see how to translate the program: https://github.com/Bionus/imgbrd-grabber/wiki/Translation

Indeed, it says pretty much everything you need to know to translate the program in your language.
If you follow the steps described on that page, you should be able to make a translation in no time. :smile:

**Comment by Bionus** [comment]
I just updated the doc and added Crowdin translations, so I'll close this issue.
If you have further questions, feel free to ask in issue #1676, I'll gladly get additional translations 😄
