### ISSUE TITLE
Crash by a long interval

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1342]
### What steps will reproduce the problem?
When you put by sankaku complex for example each interval to 8s (So it crash fast) and search after that nekopara it will crash directly.

### What is the expected behavior? What do you get instead?
That it wait for that source the amount of time of the interval but I get a crash instead.

### How often does this problem occur? On which sources?
Always and only tried sankaku complex but I guess this can happen with other sources also.

### What version of the program are you using? On what operating system?
Version 6.0.3 with windows 10

**Comment by Bionus** [comment]
1. `current_request = nothing`
2. Request A is sent, `current_request = A`
3. Request B is sent, `current_request = B`
4. Response A arrives, parse the current request (`B`), clear memory: `current_request = nothing`
5. Response B arrives, parse the current request (`nothing`), crashes

Two bugs in one.

Easily reproducible by adding an interval and starting two requests at once (by double clicking "Ok" in the search field for example).

**Comment by MrAndre96** [comment]
@Bionus do you have plans to release 6.0.4 anytime soon or should I just switch over to the nightly version of grabber

**Comment by Bionus** [comment]
It should be released by the end of the week, I still have a few things I need to check first. :ok_hand:
