### ISSUE TITLE
Possible to filter out extensions?

### ISSUE THREAD

**Issue by GeeMack** [Bionus/imgbrd-grabber#1344]
Since people can be quite lazy when tagging their uploads, sometimes searching 'animated' isn't good enough. DanbooruDownloader for example has a feature when batch downloading that allows you to exclude tags. 

Typing 'png|jpg|jpeg' in the 'Filter Extension' field with 'Exclude Mode' ticked will only download images without those extensions for example.

Is this also possible with Grabber?

**Comment by Bionus** [comment]
Yes it's possible.

Depending on the source you use, it can even already be do-able from the search field. For example on Danbooru, you can simply search "some_tag -filetype:png" to remove all PNG images from the results.

If your source doesn't support it directly (or if on Danbooru for example you're limited to few search tags), you can use the post-filtering feature which allows to filter the results. Simply add "-filetype:png" to your post-filter and Grabber will remove all results with a PNG extension.

**Comment by GeeMack** [comment]
Thanks for the reply, seems to be working. Only problem I'm having now is that it's renaming all extensions to .webm which seems fine for gif and mp4, but it breaks swf for example. Is there a setting that could be causing that?

**Comment by Bionus** [comment]
Moved to #1352
