### ISSUE TITLE
how to get veebooru to work?

### ISSUE THREAD

**Issue by madmuffinz** [Bionus/imgbrd-grabber#1345]
I managed to add it, but I do not get results for it.
Do I have to figure out the Type when adding it?

**Comment by Bionus** [comment]
It seems that Veebooru used a custom software to build their website, based off Danbooru mixed with URLs inspired from Shimmie boards and a homepage from Gelbooru. Quite a strange mix.

At the moment I would say that it simply isn't supported.

**Comment by madmuffinz** [comment]
Out of all the source types, Shimmie at least didn't give me the message "No valid source of the site returned result." when I search

**Comment by elitetheespeon** [comment]
> 
> 
> It seems that Veebooru used a custom software to build their website, based off Danbooru mixed with URLs inspired from Shimmie boards and a homepage from Gelbooru. Quite a strange mix.
> 
> At the moment I would say that it simply isn't supported.

If you want to add support for PHP-Booru (the engine the site runs), all of the source can be found at https://github.com/elitetheespeon/PHP-Booru/
