### ISSUE TITLE
Compile Error on v6.0.3 on Raspberry pi

### ISSUE THREAD

**Issue by lucario1001** [Bionus/imgbrd-grabber#1346]
### What steps will reproduce the problem?

Compile on 6.0.3

### What is the expected behavior? What do you get instead?

Compile imgbrd-grabber and run the program. Internal compiler Error
`In file included from /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobjectdefs.h:50:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtCore/qmetatype.h:51,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtCore/qvariant.h:46,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtCore/QVariant:1,
                 from /home/pi/imgbrd-grabber-6.0.3/lib/src/downloader/downloader.h:4,
                 from /home/pi/imgbrd-grabber-6.0.3/lib/src/downloader/downloader.cpp:1:
/usr/include/arm-linux-gnueabihf/qt5/QtCore/qobjectdefs_impl.h:194:6: internal compiler error: Illegal instruction
     };
      ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
lib/CMakeFiles/lib.dir/build.make:254: recipe for target 'lib/CMakeFiles/lib.dir/src/downloader/downloader.cpp.o' failed
make[2]: *** [lib/CMakeFiles/lib.dir/src/downloader/downloader.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Generating moc compilation tests_automoc.cpp
[ 25%] Built target tests_automoc
(node:4378) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

sites@ build /home/pi/imgbrd-grabber-6.0.3/release/sites
 tsc -p tsconfig.json

CMakeFiles/Makefile2:156: recipe for target 'lib/CMakeFiles/lib.dir/all' failed
make[1]: *** [lib/CMakeFiles/lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Built target sites
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
mv: cannot stat 'build/gui/Grabber': No such file or directory
Grabber has been compiled in the release directory. To run it, type './release/Grabber' `

### How often does this problem occur? On which sources?

On 5.5.2 i can't compile either it gives me a segmentation fault.

### What version of the program are you using? On what operating system?

6.0.3, Rasbpian Strech 

### Please provide any additional information below
Use 5.5.2 worked fine before now i can't compile but love your program <3

**Comment by One1One1One** [comment]
Can you do a quick check on the version of g++? Just type `g++ --version`.

**Comment by Bionus** [comment]
From the line
> See file:///usr/share/doc/gcc-6/README.Bugs for instructions.

It would seem you were using GCC 6 to try to build Grabber. However, there are known issues (see issue #1375) with using this version of GCC on the `master` branch or older `develop` references.

I'll close this issue for now, but if you still can't compile the `develop` branch, I'll gladly re-open. :+1:
