### ISSUE TITLE
Suggestion to make wiki text selectable and copyable (and change wiki link behavior)

### ISSUE THREAD

**Issue by SemifKnight** [Bionus/imgbrd-grabber#1347]
### What steps will reproduce the problem?
Hovering the cursor on wiki text shows no change to the cursor which shows that the text can't be copied or manipulated. It would be useful to be able to copy the kanji and other Japanese characters much more easily than having to open a wiki page in an external browser and copying from there. The default behavior of clicking character names is to open a pixiv search for the character (which more often than not is what I meant to do) so it's fine. I don't know about other users though.

Also, clicking a non-character name link opens a new tab in Grabber that doesn't work right:

**1. A search for a character; the wiki is properly shown**
![grabber 01 - with wiki page](https://user-images.githubusercontent.com/34590104/42985736-5714dcb2-8c25-11e8-947e-7acd75b35d64.png)

**2. When a non-character name in the wiki is clicked, it opens a new tab in Grabber that doesn't work right.**
![grabber 02 - non-name wiki link clicked](https://user-images.githubusercontent.com/34590104/42985766-6e07f1b6-8c25-11e8-9a69-7949e9bdf456.png)

**3. Going to a new page refreshes the wiki properly.**
![grabber 03 - going to new page refreshes wiki](https://user-images.githubusercontent.com/34590104/42985794-873a9efe-8c25-11e8-843f-9098171a94c4.png)

The behavior I'm suggesting is to make clicking wiki links open a new tab in Grabber with the referred tag searched, instead of putting the link location like "/wiki_pages/show_or_new?title=purple_eyes" in a new Grabber tab, which does nothing. Or maybe if wikis across boorus are too varied, then scrapping the links except for the character name might be better.

### What version of the program are you using? On what operating system?
Grabber 6.0.3
Windows 10

### Please provide any additional information below
This would be useful since the wiki text is already there, and other users who do not know Japanese would have an easier time by copying the Japanese characters instead of having to find a wiki of the character from an external browser and copying from there. I wouldn't want a built-in browser in Grabber though, since it seems that it will add bloat to the program.

**Comment by Bionus** [comment]
Indeed, it makes sense and it's easy to simply make this text selectable.

About the other problems you mentioned those are bugs I could reproduce, so I pushed a few fixes on the `develop` branch that will land in the next version. :+1:
