### ISSUE TITLE
Headers does not work (almost)

### ISSUE THREAD

**Issue by jadiah** [Bionus/imgbrd-grabber#1349]
### What is the expected behavior? What do you get instead?
I am using HTTP headers, but seems they works only for the first request (when i press ok in search tab), for every next request i am have to proceed these steps "Sources > Options > Confirm > Ok", otherwise without headers, my request meets cloudflare.com and returns "Error loading ... server replied: Forbidden".

### How often does this problem occur? On which sources?
Always.

### What version of the program are you using? On what operating system?
6.0.3, Linux.

**Comment by Bionus** [comment]
Which header are you trying to set?

I can't reproduce this on my end, when I set headers, they are properly inserted on the first call, and also on subsequent calls, for example when the thumbnails load or when I click the ">" (next page) button.
