### ISSUE TITLE
Sankaku "File already exists"

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#1356]
### What steps will reproduce the problem?
Batch download from Sankaku source for the tag kono_subarashii_sekai_ni_shukufuku_wo! (not sure if exact tag is related to the problem)

### What is the expected behavior? What do you get instead?
Graber's search returns ~6800 images, so i expect it to download about the same amount of files
Instead it will download ~6400 and in the log file there will be about 150 similar messages that the File already exist pointing to 1 file (i will attach the image from similiar lines finder)
![default](https://user-images.githubusercontent.com/33357691/43503386-8eaaf68c-9578-11e8-8ce9-dbd592831c43.png)
number on the right side is the number of times this line was on the log

### How often does this problem occur? On which sources?
2 times out of 2 on sankaku, redownloaded just in case. Message in the end said that all ~6800 files already existed on my hard drive

### What version of the program are you using? On what operating system?
Nightly build fba64bb windows 10 x64

### Please provide any additional information below
My wild guess that it either really grabs the same image from many different pages somehow (like they have the "popular" on the first page) or that it resolves different images to the same md5. I could not find in the logs link to the files it tried to download and save under the same name, as in log it was just
> Tags recieved
> File already exists

**Comment by bluefiberbread** [comment]
How did you get Sankaku to work with Grabber?

**Comment by oan22** [comment]
> How did you get Sankaku to work with Grabber?

Under Sources > Options > Headers

add

In "Name" field add User-Agent 
In "Value" field add Mozilla/4.78 [en] (Windows NT 5.0; U)
