### ISSUE TITLE
multiple tags in conditional filename

### ISSUE THREAD

**Issue by oan22** [Bionus/imgbrd-grabber#1359]
[This issue](https://github.com/Bionus/imgbrd-grabber/issues/1310) still seems to exist in 6.0.4.

Grabber refuses to DL something and apply a designated filename if you have more than one tag in the condition field.

**Comment by Bionus** [comment]
Which behavior are you trying to create?
Having multiple tags in the condition corresponds to an OR logical operator.

For example:
![image](https://user-images.githubusercontent.com/882719/43804518-9929f10c-9a9c-11e8-87bb-f1df2d5bfe0e.png)

Will be applied for any of those two ratings.

**Comment by Bionus** [comment]
So from what I understand I can close this issue then 👌 
Discussion about the other bug will continue in the other issue.
