### ISSUE TITLE
With a long interval it could cause a crash and not loading any results when it doesn't crash

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1371]
**Steps to reproduce**

First put on sankaku complex as source and put the interval for it on 8s by the page interval.
After that try to load nekopara for example.
After this most of the time you will first encounter that sankaku complex is offline (like in the image below).
Press now just a couple times OK and you will see that a crash occurs.

(sorry for making a second topic wanted to make it clearer since I thought that you didn't understand it)

**Screenshots**

[https://i.imgur.com/MnBLy00.png](https://i.imgur.com/MnBLy00.png)

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Indeed, I couldn't reproduce your other issue, but this one I can, thanks :+1:
