### ISSUE TITLE
MySql driver not working on dev version

### ISSUE THREAD

**Issue by One1One1One** [Bionus/imgbrd-grabber#1376]
**Bug description**

All of the database drivers seem to be missing on dev versions of grabber. At least the program doesn't seem to find them.

**Steps to reproduce**

1. install current release version
2. install current dev version
3. configure database settings
4. restart program
5. do an action that forces a write operation to the database
6. check either the log tab in grabber or the log file

**System information**

- OS: Windows 7 (x64)
- Grabber version: 6.0.4 (f796836)

**Comment by Bionus** [comment]
It would seems like the `libmysql.dll` provided in nightly does not load properly (version 5.7.12.0) while the one in normal releases loads fine (version 5.7.14.0).

After some investigation, it seems like the nightly DLL is 64-bit while Grabber runs in 32-bit, so it cannot load it. I'll see to have it package the 32-bit DLL instead. :+1:

* Nightly DLL:
![image](https://user-images.githubusercontent.com/882719/44104865-436c02ce-9ff0-11e8-982d-629142be6e48.png)
* Release DLL:
![image](https://user-images.githubusercontent.com/882719/44104920-68ae277e-9ff0-11e8-8900-f2120abbec0c.png)
