### ISSUE TITLE
Pausing not working correctly 100% of the time

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1381]
**Bug description**

There are 2 seperate bugs with pausing inside a batch download. One is when you start downloading and it is getting all the pages (like by sankaku) and click on the pause button. It will now not pause and continue like nothing happend (this will result in a bug when it is finished with downloading since the buttons are still disabled even if you close the batchdownload window). 
The other one is when the batch download is going from one image to the other one (so the first image is 100% downloaded) it will result in a skip instead of a pause.

**Expected behavior**

By the first one you espect it to pause and by the second one also to pause and not skip the image.

**System information**

Windows 10 with the latest nightly version

**Comment by MrAndre96** [comment]
Do you plan on fixing this after the release of 6.0.5?

**Comment by Bionus** [comment]
Not sure. Depends on when I actually release 6.0.5.
This fix might go in 6.0.6, depending on what I do / how much free time I have. But if it's not 6.0.5 it's absolutely 6.0.6 given it's quite the important bug.

**Comment by MrAndre96** [comment]
@Bionus Could you maybe still look at this bug when you have time? It is past the release of 6.0.6xd

**Comment by Bionus** [comment]
I'll give it a try 🙂

**Comment by MrAndre96** [comment]
Didn't expect that there would come a fix for this anymore:o Thanks:)

**Comment by Bionus** [comment]
Well it's marked 7.0.0 so I had to do it 😛
There's actually only one issue left to do before I'm done with preparing that release: #1529
