### ISSUE TITLE
Deploy both 32 bit and 64 bit versions of nightly

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1388]
When you build your application with AppVeyor you create both a 32 and 64 bit version of grabber but only the 32 bit version gets deployed to github. I would like to see if both versions could be deployed instead of just one.

**Comment by Bionus** [comment]
That is technically feasible, but given I currently only make x86 versions for "official" releases, that would mean that I would have to either double-compile everything on my end when making "official" releases (which would be a pain), or have an inconsistency between "official" and "nightly" releases. 🤔 

The only good solution for this would be to have AppVeyor also compile the official releases.

**Comment by Bionus** [comment]
Done. I only tested a few things but didn't notice any difference of behavior between both versions.
https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly
