### ISSUE TITLE
'Get all' could sometimes result in a crash

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1393]
**Bug description**

Sometimes when I click on 'Get all' it could result in a crash but not always. So for example when it crashes and restore it, it will just work normal and not crash after it when I click on 'Get all'. (Which is why I can't yet provide steps to reproduce it and since it isn't generating a crash report I can't provide it).

I would like if you maybe could look inside the code and check what could get a crash like this to happen. (Maybe it is usefull to note that I have multipele sources enabled, used the post filter and restore my previous tabs always when I open grabber)

**Expected behavior**

Not crash and just give the sources which have images by the downloads tab

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Did you add/remove sources before the crash?
Or change the selected ones?

That's pretty much the only thing that might possible pause a problem from what I see in the code, but while fiddling around I couldn't reproduce any crash. 🤔 

> it isn't generating a crash report I can't provide it

Only "official" releases generate crash reports since I can't analyze nightly reports because I don't have their symbol files.

**Comment by MrAndre96** [comment]
No I didn't add or remove sources before the crash or change the selected ones. But also got sometimes a crash just by clicking on 'Download selected'. So I don't know if they are seperate chrases or if certain action behind each other will in the end result in a crash at the end.

**Comment by brazenvoid** [comment]
@Bionus For me, its behavior is a lot like the memory overflow issues, on both nightly and release versions. No crash reports are produced on release version either, it just fades out and process killed. It always happens when I click 'Get All' for the first time in a session after 2-3 hours.
