### ISSUE TITLE
Images Per Page and Columns options just doesn't work.

### ISSUE THREAD

**Issue by AkitoCL** [Bionus/imgbrd-grabber#1395]
Exactly as the title says.
It doesn't work with the Plus icon nor the Options in the menu.

Using 6.0.4

**Comment by Bionus** [comment]
Can you give more information?
The images per page and columns settings work fine from what I see.

![image](https://user-images.githubusercontent.com/882719/44312894-8cdbc080-a3ff-11e8-9375-0d00fc0ea1ed.png)

Note that the "columns" setting only applies to multi-source search, setting how many sources there should be per row, and not how many images appear per line for each source.

If you want to have bigger/smaller thumbnails, you should change the "upscaling" setting in the options. In my case, I have 15px * 15px thumbnails, 10% of the original 150px * 150px images:

![image](https://user-images.githubusercontent.com/882719/44312912-d75d3d00-a3ff-11e8-89b7-708ee60745d5.png)

**Comment by brazenvoid** [comment]
@Bionus The column setting is fine and perhaps a tooltip on hover can further explain its function.

The image per page setting works for most sources, not all. For example, it does not work for rule34.paheal.net

**Comment by Bionus** [comment]
> @Bionus The column setting is fine and perhaps a tool-tip on hover can further explain its function. I also stumbled when I first used it, though I was unsure of its use from the get go.

Indeed, it's true that it might not be obvious that it's about the sources and not the number of images per row. I added a tooltip explicating it.

> The image per page setting works for most sources, not all. For example, it does not work for rule34.paheal.net

Yes, I feel that might be the origin of this issue. Shimmie and Zerochan often don't respect the "images per page" setting. I just created issue #1412 as a possible solution for this.
