### ISSUE TITLE
does not download all images from max range of images

### ISSUE THREAD

**Issue by Tokyo-All-Ready** [Bionus/imgbrd-grabber#1398]
does not view all images by artist or make possible to download

i loaded up one of my favorites (tooo) on gelbooru

it said there were 181 images but it downloaded only 109 total
i dont have any blacklisted tags to filter out images

windows 7 professional 64 bit

**Comment by Tokyo-All-Ready** [comment]
nvm nvm please disregard i figured it out
i had the wrong source website and it was filtering tags
thank you so much for making this program its so awesome

**Comment by Bionus** [comment]
Ok I'll close the issue in that case!

>  thank you so much for making this program its so awesome

You're welcome!  :ok_hand:
