### ISSUE TITLE
The filesize / type can't be found and images aren't loading

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1399]
**Bug description**

When you open a image the filesize / filetype can't be found and the images aren't loaded inside the image viewer

**Steps to reproduce**

Enable for example sankaku complex(with this one the filesize and filetype can't be found with others just the filetype like PNG etc)
Now search for nekopara and click on a image
You will now see that the image isn't loading and that the filesize and type aren't found

**Expected behavior**

You expect that those can be found and that the images are loading

**Screenshots**

[https://i.imgur.com/jmu26KR.png](https://i.imgur.com/jmu26KR.png)
[https://i.imgur.com/RF7JJ03.png](https://i.imgur.com/RF7JJ03.png)
[https://i.imgur.com/7who5v5.png](https://i.imgur.com/7who5v5.png)

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
I think this should be fixed by 19965cb0, can you confirm? (latest nightly, I just pushed it)

**Comment by MrAndre96** [comment]
@Bionus Yeah seems to have fixed it

**Comment by Bionus** [comment]
Thanks again then, both for the report and verification 👍
