### ISSUE TITLE
Is apng loading  slow?

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#1407]
Not the usual bug report so not using the forum, I see you added apng support but I noticed that some of them don't fully load or take an unusual amount of time, I was wondering if was the plugin or the sites just being slow, some load just fine.

**Comment by Bionus** [comment]
Are you talking about the downloading time (green progress bar) or afterwards, the time it takes for the image to show up?

Do you have an example of an image who is always slow to show up?

**Comment by brodycas3** [comment]
the loading bar

**Comment by Bionus** [comment]
Well, APNG files are usually huge, so it's normal for them to download slowly then. 👌
