### ISSUE TITLE
Thumbnails sometimes stack on each other.

### ISSUE THREAD

**Issue by SemifKnight** [Bionus/imgbrd-grabber#1408]
**Bug description**

Thumbnails sometimes stack on each other.

**Steps to reproduce**

Thumbnail Stacking

1. Open grabber and make a search. 
2. Before the search gets completed, click away to another tab.
3. Click back to the previous tab. If the clicking back is done at a certain time, the thumbnails will be stacked on top of each other or otherwise cut off.

This has happened before and possibly in other ways, but this is how it could be reproduced.

**Expected behavior**

Clicking back to a tab should have its thumbnails in a neat array like they usually are.

**Context**

Here are the main.log and settings.ini files: 

* [main.log](https://github.com/Bionus/imgbrd-grabber/files/2345376/main.log)

* [settings.txt](https://github.com/Bionus/imgbrd-grabber/files/2345382/settings.txt)

**Screenshots**

I was also able to make a recording of it happening. Please excuse the wonkyness as it was my first time using OBS. >_<

https://youtu.be/a2WAwxODQvM

Otherwise, here is a screenshot:
![grabber issue - thumbnails stacking](https://user-images.githubusercontent.com/34590104/45013846-27b6da80-b04f-11e8-92bb-e0a5e4454677.png)

**System information**

- OS: Windows 10
- Grabber version: 6.0.5

**Comment by Bionus** [comment]
Ooooooooh I've been looking for the source of this bug for a very long time, without ever having found any way to reproduce it! Thanks a bunch! 😄 

Thanks for the reproduction steps I could find the source of the problem, I'm now working on the fix.
