### ISSUE TITLE
Image in image window won't fully load pictures

### ISSUE THREAD

**Issue by morning-paradigm** [Bionus/imgbrd-grabber#1409]
**Bug description**

When opening any image it starts loading, but remains pixelated even when the progress bar reaches 100%.

The image is displayed correctly after either:
- reopening image window
- navigating to the previous/next image
- changing the focus to another window (another app or the main window of Grabber) 

**Steps to reproduce**

1. Click any image
2. It will load, but won't be displayed fully loaded
3. Open another image and go back to the one loaded first
4. It will be displayed correctly

**Expected behavior**

Image is displayed correctly upon being cached.

**Context**

Part of the log that shows this behavior:

```
[19:26:02.172][Info] Loading image from https://danbooru.donmai.us/data/__anastasia_fate_grand_order_and_fate_series_drawn_by_soyubee__cad2afb4453e292709397a9520a736e3.jpg
[19:26:02.174][Info] Loading and saving image in /var/folders/2y/fxfhl6zj72v707h73947v9d00000gn/T/Grabber/ef9f425a-952c-4a47-a6b6-17e16b2b59c5.jpg
[19:26:02.549][Error] Unable to change the file creation date (2): /var/folders/2y/fxfhl6zj72v707h73947v9d00000gn/T/Grabber/ef9f425a-952c-4a47-a6b6-17e16b2b59c5.jpg
[19:26:02.550][Info] Image received from https://danbooru.donmai.us/data/__anastasia_fate_grand_order_and_fate_series_drawn_by_soyubee__cad2afb4453e292709397a9520a736e3.jpg
[19:26:05.297][Info] Image loaded from the file /var/folders/2y/fxfhl6zj72v707h73947v9d00000gn/T/Grabber/ef9f425a-952c-4a47-a6b6-17e16b2b59c5.jpg
```

* Fresh build, `settings.ini` is untouched
* Reproducible for Danbooru, Gelbooru, Zerochan and Sankaku

**Screenshots**

    
![screen shot 2018-09-06 at 19 56 25](https://user-images.githubusercontent.com/39773982/45159080-081ae000-b210-11e8-8fde-c6b5aa188223.png)

**System information**

- OS: macOS 10.12.6
- Grabber version: 6.0.5

**Additional context**

Wondering if this `[Error] Unable to change the file creation date (2):` has something to do with permissions/the way the app was built. I've built it myself using a `build-mac.sh`, getting this issue on both 6.0.4 and 6.0.5. Older 5.5.0 build (latest available for macOS in releases) works just fine.

**Comment by Bionus** [comment]
Does this happen every time you open an image?
Or as @brazenvoid mentions does it only happen after a while?

I also see in your screenshot that the loading bar did not disappear, is that always the case when this bug occurs?

> Wondering if this [Error] Unable to change the file creation date (2): has something to do with permissions/the way the app was built. I've built it myself using a build-mac.sh, getting this issue on both 6.0.4 and 6.0.5. Older 5.5.0 build (latest available for macOS in releases) works just fine.

Older builds might not work, it might just be that the error message wasn't here (and it was instead silently failing): fba64bbbdefa8bdbb68d2e0ee4c4c25bf3809e9d (change introduced in v6.0.4).

`errno 2` gives me `ENOENT 2 No such file or directory`, which is strange. Maybe some race condition where the program tries to change the date of the file before it's finished saving (from the timestamps in the log, that seems to be the case).

I think it's worth opening an issue about it if you consistently get this message.

> Mine is related to memory leaks. I had reported this before but currently plugging memory leaks is not a priority.

I wonder where you got the information that memory leaks are "not a priority". Any bug, crash, or leak that I can reproduce is usually fixed quickly.

Also:
https://github.com/Bionus/imgbrd-grabber/search?q=leak&type=Commits

**Comment by morning-paradigm** [comment]
Sorry for the late reply.

> Does this happen every time you open an image?

> I also see in your screenshot that the loading bar did not disappear, is that always the case when this bug occurs?

Yes, both happen every single time. The loading bar doesn't disappear unless the image is loaded again.

> Older builds might not work

I mean older builds don't have this issue.
