### ISSUE TITLE
Improvement of tab navigation

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1413]
**Is your feature request related to a problem? Please describe**

1. When having 50+ tabs open, its is difficult to access the last or first tabs.
2. In the same scenario, accessing the downloads tab and then returning could become quite hard.
3. The floating navigation buttons obstruct view. 

**Describe the solution you'd like**

1. Add go to last and first buttons along side the already implemented tab navigation buttons.
2. Add a shortcut in the file or view menus to go to the downloads tab directly.
3. Add a single step back button in downloads tab to return to the previous tab.
4. Make the tab navigation icons non-floating and embed them along side the add new tab button in the fixed area.

**Comment by SemifKnight** [comment]
How about a button that makes a menu pop up, where you could click on which tab to focus on? (Any tab, not just "Download")

I think Firefox used to have a "List all tabs" button, like this one: 
![listalltabsmenu03 png](https://user-images.githubusercontent.com/34590104/45357336-8d2f3c00-b5f8-11e8-82d4-d3ded5ee0202.jpg)
(Reference image is from Akemi Iwaya from howtogeek.com https://www.howtogeek.com/howto/11821/add-a-search-box-to-the-drop-down-tab-list-in-firefox/)

This article features an addon that adds search and scroll bars to make the list easier to use, because the original "List All Tabs" was not scrollable. This would make tabs in the middle of hundreds of them easier to access, too.

**Comment by brazenvoid** [comment]
@SemifKnight I guess it can be an added feature to make navigation easier. 

I mentioned Downloads tab because it is one of the fixed tabs. Same as downloads, there can be a shortcut for the log or favorites too. 

Because I am a developer myself, I try to suggest only those features which can be easier and faster to develop for Jack. I tend to avoid features which may take longer and thus will be pushed to the next major/minor version. 

Out of the 4 enhancements I suggested, only no 3 will require a mild development effort.

**Comment by Bionus** [comment]
Work in progress (mainly an implementation of issue #1094, which is also what @SemifKnight suggested), the number corresponds to the tab count (maybe this count shouldn't include the fixed tabs?):

![image](https://user-images.githubusercontent.com/882719/45371398-c660af80-b5ea-11e8-80b0-534408a14f5d.png)

I feel it solves the original problem (and replaces points 1 and 2, maybe even 3 but that's questionable) without requiring too many buttons while also being more convenient for the user than jumps. What's your opinion @brazenvoid?

> Make the tab navigation icons non-floating and embed them along side the add new tab button in the fixed area.

This can be done, however those are currently the scroll buttons [provided by Qt](https://doc.qt.io/qt-5/qtabwidget.html#usesScrollButtons-prop). Therefore, before replacing them by custom-made ones, I'll have to check how this plays on Linux and MacOS as they might have different styles.

**Comment by brazenvoid** [comment]
- I also think that fixed tabs should not be part of the count. Not showing the count at all, could also be good enough. Who would care for a tab count when one can see the list?
- This solution indeed resolves points 1 & 2.
- Point 3 is disputed because the transition from any tab to a fixed one and back will still have latency inversely proportional to the index position of the unfixed tab.
- If the menu can also scroll through the tabs then handling many tabs would be slightly better. The scroll will make the navigation faster than the click to go to next tab thing but one will still have to scroll and search for the desired tab.
- Ultimate solution could be a search function

**Comment by Bionus** [comment]
> Point 3 is disputed because the transition from any tab to a fixed one and back will still have latency inversely proportional to the index position of the unfixed tab.

Indeed. I'll add a button besides the "+" button that appears after a "jump" (i.e. after this tab selector is used), and when clicked brings you back to the previous tab.

> If the menu can also scroll through the tabs then handling many tabs would be slightly better. The scroll will make the navigation faster than the click to go to next tab thing but one will still have to scroll and search for the desired tab.

It's a normal OS menu, so (at least on Windows) it supports scrolling as well as the Page Up, Page Down, Begin, and End buttons. Typing the beginning of the tab name also focuses it. It can even use columns instead of scrolling if so set-up.

> Ultimate solution could be a tab search box with active search function and matching results showing as links beneath in an overlayed result box... I don't know whether you understood but its like the address bar of a browser which shows results as you type...

Indeed, but I have a feeling the work & support to gain ratio would be pretty bad. 😅

**Comment by MrAndre96** [comment]
Maybe you could add something in that menu so you could easely close tabs when you ctrl + click or something for example

**Comment by brazenvoid** [comment]
Two more suggestions:
- Can you also make it so that tabs do not get duplicated, instead the control switches to the tab with same search parameters? Perhaps this can be made optional.
- Sorting of tabs

**Comment by Bionus** [comment]
> Maybe you could add something in that menu so you could easely close a lot of unwanted tabs when you do ctrl + click or something for example

Done. Middle click will now close tabs in the dropdown.

> Can you also make it so that tabs do not get duplicated, instead the control switches to the tab with same search parameters? Perhaps this can be made optional. Then perhaps a kill duplicate tabs action could also be added.

I don't see how this would be done, given you have to open a tab, enter your query, and select your sources / page number to be able to see if another tab already exists. Then, after you've done all this, the program would close your tab and bring you to another one, which doesn't feel very user-friendly.

> Sorting of tabs

In what order? Alphabetically?

**Comment by flameboii** [comment]
![vivaldi_2018-09-30_12-05-49](https://user-images.githubusercontent.com/8580116/46254215-5aff5480-c4a9-11e8-86f1-78c27df76e3f.png)
It'd be nice to have the option to stack tabs either horizontally, as you currently have it, or vertically, like in the browser Vivaldi.

**Comment by Bionus** [comment]
@flameboii moved to #1438.

Everyone for additional suggestions about tab navigation, please create independent issues so that they can be better individually tracked 😄

**Comment by brazenvoid** [comment]
> > Can you also make it so that tabs do not get duplicated, instead the control switches to the tab with same search parameters? Perhaps this can be made optional. Then perhaps a kill duplicate tabs action could also be added.
> 
> I don't see how this would be done, given you have to open a tab, enter your query, and select your sources / page number to be able to see if another tab already exists. Then, after you've done all this, the program would close your tab and bring you to another one, which doesn't feel very user-friendly.
> 

No, it will not check page numbers. Just the main searched tags. About the behavior, one thing will remain same that is an initial tab will not be opened at all till the search is done. Afterwards, there can be some variations after a match is found;
- Open the existing tab.
- Open the existing tab and position it at the place where the new tab would have been placed.
- Show a confirmation prompt giving choice to the user, like: There is already a tab with this search combination, would you like to switch to it?

> > Sorting of tabs
> 
> In what order? Alphabetically?

Yes, alphabetically. Currently, I have about 403 tabs open so searching/navigation would be easier with it. Also after a crash, the order gets changed, every time.

**Comment by brazenvoid** [comment]
@Bionus The above issue is till there in the release.

**Comment by Bionus** [comment]
@brazenvoid moved to #1447
