### ISSUE TITLE
Improvements to the Favorites System

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1416]
Current system is only based on viewed date. Many other improvements can be made to it:

1. Option to store browsed image md5 in dedicated md5 file associated with each favorite. This will allow precise favorite tracking and allow searching for older images which got tagged later. Currently there is no option to search for newly tagged images anywhere. This can workaround that issue and make us not miss even a single image.
2. Either apply global "Adds" field tags to each favorite or capture those tags as part of the favorite on creation.  
3. Add ability to couple a favorite with preset sources. 
4. Open a favorite in a separate tab instead of the overlay with all the controls of a normal search and the current favorite specific ones.

**Comment by Bionus** [comment]
> 1. Option to store browsed image md5 in dedicated md5 file associated with each favorite. This will allow precise favorite tracking and allow searching for older images which got tagged later. Currently there is no option to search for newly tagged images anywhere. This can workaround that issue and make us not miss even a single image.

You mean kind of like issue #1058, except with a MD5 instead of an ID?

In what way would that help with images that get re-tagged later on?

Also, I don't really understand your last sentence either. You shouldn't miss any image with a date-based system either, unless for some reason two images got sent at the very same (milli)second, and you somehow loaded exactly at the moment between two images.

> 2. Either apply global "Adds" field tags to each favorite or capture those tags as part of the favorite on creation.

I just checked, and global adds are already applied to favorite searches.

> 3. Add ability to couple a favorite with preset sources.

Indeed, that could be useful for some tags that are source-specific. However, it raises the issue if you want to override them temporarily for a given search.

> 4. Open a favorite in a separate tab instead of the overlay with all the controls of a normal search and the current favorite specific ones.

Middle clicking already does that, is that not enough? Or do you want this in order to standardize the way it looks?

**Comment by brazenvoid** [comment]
1. No, what you reference in that issue is simply storing the last image's MD5 as an alternative to the date-time. I meant recording MD5 of all images retrieved from any source for a favorite. The MD5 ensures multi-source elimination of duplicates.

    If a favorite has a dedicated MD5 list for all images browsed then users can track back and see any images which got tagged later. As images can be tagged anytime, this will be a way for users to browse them. This in combination to dynamic page filling feature that you discussed before would be a great boon. 

3. You could apply it simply like when a user opens a favorite, the sources are set to the ones preset for it.  Later the user can modify them as they normally do. No need to enforce them, see them as starting preset sources.

    For this to happen, the next feature is important. That is the source controls being visible in the tab where you are searching the favorite.

4. Using middle-click, opens the standard tag search, not a favorite search with date-time limiting. 

    Keeping the Favorites browser separate will allow users to open multiple favorite searches at a given time. Currently only one can be run and while its open, favorites can't be seen. Perhaps this was built when tabbed browsing wasn't really a thing.

    Having the standard search controls will also help maintain a consistent experience with favorite searching. 

    Perhaps converting the favorite date-time limiting to a post filter would serve as a hack to have normal tag search work for this purpose. Rather than refactoring search and making a new search type.
