### ISSUE TITLE
PixIV Support

### ISSUE THREAD

**Issue by RapthorneLightweaver** [Bionus/imgbrd-grabber#1423]
I'd love to see Pix IV support added to the downloader. It's one of the best sources for original art content online, NSFW and otherwise

**Comment by Bionus** [comment]
See #738 (also partially #917).

I'll be closing this as duplicate, but if you have any info about the API, or if you want to describe your use-case on Pixiv (searching by tag, searching users, downloading users artworks, etc.), please do comment on #738 👍
