### ISSUE TITLE
Tags are not saved in separate log during batch download

### ISSUE THREAD

**Issue by Danimos552** [Bionus/imgbrd-grabber#1428]
**Bug description**

Tags are not saved in a separate log during batch download. This happens *exclusively* during the batch download. If you click on an image manually and then Save, the tags will be there. This bug does not occur on Grabber version 5.5.2.

**Steps to reproduce**

1. Go to Tools --> Options --> Save --> Separate log files
2. Click on 'Add a separate log file' and fill it with desired tokens (%artist%, %character%, %general%, etc)
3. Save the options
4. Choose rule34.xxx from the sources
5. Click get this page
6. Go to Downloads tab and click Download button
7. Once the batch is finished, go to the save folder, open a log file
8. The log does not contain any tags, only the "If empty" replacement specified for each token in the options

**Expected behavior**

The log file should be full of tags. This happens *exclusively* during the batch download. If you click on an image manually and then Save, the tags will be there.

**Context**

All 3 files in the attachment
[main.log](https://github.com/Bionus/imgbrd-grabber/files/2407084/main.log)
[restore.log](https://github.com/Bionus/imgbrd-grabber/files/2407087/restore.log)
[settings.log](https://github.com/Bionus/imgbrd-grabber/files/2407088/settings.log)
I changed extensions of restore.igl and setting.ini to log, cause GitHub nagged that it doesn't support these formats.

**System information**

- OS: Ubuntu 18.04 (64bit)
- Grabber version: 6.0.5

**Comment by Bionus** [comment]
The bug can also be reproduced by right-clicking an image then clicking "Save" in the results list (if it was not opened beforehand).
