### ISSUE TITLE
Excude all favorited tags from search results

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1430]
As the title says. Perhaps a post filter?

**Comment by Bionus** [comment]
There's no way to do that currently, but as you suggest a post-filter can be added, in the same family as the `alreadyExists`, `inMd5List`, and `downloaded` post-filters.

**Comment by Bionus** [comment]
Just added the `grabber:favorited` filter (you'll have to negate it with `-` for your use case).
