### ISSUE TITLE
[Bug/Suggestions] MD5 list storage and tools

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1439]
### Context 

So I have a filtered folder to store the actual collection from the downloaded files. Also separate folders for animated files.

Since a recent update, the MD5 list in storage appears to get updated in the destruction phase of the program and not when the image is downloaded successfully. Because the program crashing is a regular thing for me, this becomes a flaw which otherwise would be an optimization to reduce writes to the disk and avoid the latency penalty. Many times nearly a 1000 images don't get included. Necessitating me to run the tool after each crash.

### Suggestions/Fixes

- Add recursive search to md5 list fixer and maybe to the rename tool as an option.
- Make it so that the md5 storage occurs on each file download. Perhaps this can be added as a setting to preserve functionality for future stabler versions. 
- Make it so that the md5 fixer tool does not make the program go unresponsive when "Force MD5 calculation" is enabled. Usually the UI gets stuck at ~10% progress bar progress, and resumes when everything is done.

**Comment by Bionus** [comment]
> Add recursive search to md5 list fixer and maybe to the rename tool as an option.

AFAIK, the tool is recursive. However, if you use "get md5 in filename", every file has to match the provided filename (including the directory path), so maybe not all of your files match?

**Comment by brazenvoid** [comment]
> 
> 
> > Add recursive search to md5 list fixer and maybe to the rename tool as an option.
> 
> AFAIK, the tool is recursive. However, if you use "get md5 in filename", every file has to match the provided filename (including the directory path), so maybe not all of your files match?

I never use that. It is always set to "Force MD5 calculation"

**Comment by brazenvoid** [comment]
It is quite fine, if it does work recursively, it was more of a question. The other two are the actual problems.
