### ISSUE TITLE
Forward/Previous mouse buttons allow moving beyond the page count

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1441]
**Bug description**

Forward/Previous mouse buttons allow moving beyond the page count. 

**Expected behavior**

Though the request fails with no images found but this should be consistent with disabled Previous/Next Page navigation buttons.

**System information**

- OS: Windows 10 64-bit
- Grabber version: v6.0.5

**Comment by Bionus** [comment]
Indeed! :+1:

In addition to the mouse buttons, simply using the page spinbox allows to go over the page count. I pushed a fix to limit both to the current max page count.

**Comment by brazenvoid** [comment]
Ok, I'll check out the nightly.

**Comment by brazenvoid** [comment]
The fix works!
