### ISSUE TITLE
The new nightlies crash alot

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1443]
**Steps to reproduce**

So the nightlies after 27th September randomly crash on normal actions like: 

**Adding a Favorite**: Opened Grabber and tried adding 4 favorites by first searching them. Crashed on the third.

**Single Source Bulk Download**: Added three single-source bulk downloads for an author. Crashed on the first with download all function. Tried the second, it worked. Tried the third, it crashed. It seems as if it crashes with one bulk download, it will always crash with it. While if another download is added alongside from the same source, it will work. I have tried the crashing downloads on the release version successfully.

**Selected Images Download**: Sometimes even downloading a single image through the selected images bulk download function crashes it. 

**System information**

- OS: Windows 10
- Grabber version: nightly 

I will keep it updated, I know it will be hard to reproduce but once it does, it frustrates me to no end... especially due to #1439

**Comment by brazenvoid** [comment]
So I just loaded Grabber again after the crash after adding a favorite. Apparently it has added it still so the crash happened afterwards.

**Comment by Bionus** [comment]
You need c33716a968a33d58b9a10305d10cf0ef4c10a710
