### ISSUE TITLE
Nightly does not respect page image count for gelbooru

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1444]
**Bug description**

Just as the title says. 

**Steps to reproduce**

1. Search any tag with an image per page setting set at any desired amount. 
2. The search will not respect the setting

**Expected behavior**

It should follow that setting. I have checked the log as well and it does not contain any query variable to request the correct number of images per page. 

For example:
```
[23:55:49.520][Info] [gelbooru.com][Html] Receiving page https://gelbooru.com/index.php?page=post&s=list&tags=naughty_face height%3A%3E%3D1000 width%3A%3E%3D1000&pid=1722
```

**System information**

- OS: Windows 10 64-bit
- Grabber version: Nightly c33716a

**Comment by Bionus** [comment]
I would say it's a coincidence, given loading https://gelbooru.com/index.php?page=dapi&s=post&q=index in a browser returns an error.
