### ISSUE TITLE
All tabs show as "New tab" in the tab selector

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#1447]
From @brazenvoid in #1413:

> A bug has come around with the earlier implementation, I don't know what caused this but now my tab list is always like so:
>
> [New Tab Issue](https://i.imgur.com/sGSAzwg.png)

Version: 6.0.6

**Comment by brazenvoid** [comment]
It sometimes happens from a fresh start. And sometimes corrects itself after a crash.
