### ISSUE TITLE
Reset page number when sources are changed

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1449]
**Is your feature request related to a problem? Please describe**

It happens often that I change sources and I also have to reset the page to 1 before initiating the search.

**Describe the solution you'd like**

The above action should be automated. It already happens when tags are changed. There is no point in expecting anything from the same page number on any other source.

**Comment by Bionus** [comment]
While I agree with the general suggestion, I feel that there is a case where the page number should not be reset: when using multiple sources, and one is removed from the list of selected sources.

So it could be rephrased as "if there is a source selected that wasn't before, reset the page number".

**Comment by brazenvoid** [comment]
Yes, indeed. The other case does not seem to have any logical cases for a reset.
