### ISSUE TITLE
Page number 0 

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1450]
**Bug description**

A search with no results resets the page counter to 0 (On sources on which the new counter/next/forward mouse limitation works.). Any new search with results then also starts with page 0 in the same tab, thus Grabber shows page 1 on both page 0 and 1. 

**Steps to reproduce**

1. Search some tags with no results on a supported source like rule34.xxx
2. Search again with tabs with some results
3. Page counter remains unchanged but Grabber still loads page 1
4. Go to next page
5. Page 1 is loaded again

**Expected behavior**

When a new search is done, it should reset to page 1. 

**System information**

- OS: Windows 10 64-bit
- Grabber version: v6.0.6

**Additional context**

Yes, there are some sources that don't work with the navigation control scheme that you included last time due to my issue. I just found out too while testing this one...

**Comment by Bionus** [comment]
Indeed, with the fix I put the "maximum number of pages" as the page spinner maximum value, but when no images are found, this maximum is 0.

I pushed a fix to have it set at least to 1.
