### ISSUE TITLE
Listing favorites for a Gelbooru 0.2 site?

### ISSUE THREAD

**Issue by KamillaPup** [Bionus/imgbrd-grabber#1451]
I'm trying to list favorites of my user but the usual commands aren't working. When I go to my favorites on tbib.org, the link is http://tbib.org/index.php?page=favorites&s=view&id=xxxxx and I'm not sure how to put that query into Grabber. Is it possible? I tried putting in page=favorites&s=view&id=xxxxx and I didn't get any results.

**Comment by Bionus** [comment]
You can always simply search the URL, but it won't support pagination (i.e. if you have more than 42 favorites, you'll have to add 1 batch download per page number, each with a different URL), as the `{pid}` trick mentioned in issue #516 doesn't work anymore.

**Comment by Bionus** [comment]
Personally, I'd just suggest you to switch to the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly) until `6.1.0` comes out if that feature is important for you. Then, just search `fav:123456`.

If you want to stick to `6.0.6`, what I meant was simply pasting the whole URL in the search field. Grabber should parse the images found on the page properly. But you won't be able to do batch downloads this way (it will only download one page every time).
