### ISSUE TITLE
Gelbooru, "simg4" server, doesn't work

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1455]
Grabber is persistently trying to download images from Gelbooru's "simg4" server, which doesn't work.

example:
https://simg4.gelbooru.com/images/27/6b/276b64ca4cf1d2ba5687b709bb7d1141.jpg (not working)
https://gelbooru.com/images/27/6b/276b64ca4cf1d2ba5687b709bb7d1141.jpg (working)

**Comment by Bionus** [comment]
Are you using the latest version, [6.0.6](https://github.com/Bionus/imgbrd-grabber/releases/tag/v6.0.6), or the previous 6.0.5?

6.0.6 should fix the issue, see #1410

**Comment by bluefiberbread** [comment]
Nope, I am actually using 6.0.5. I've updated Grabber now, and downloading seems to be a bit slower compared to before, but I am not seeing "simg4" in the Gelbooru URLs anymore, so it appears to be working again.
