### ISSUE TITLE
Sankaku source downloads often stop

### ISSUE THREAD

**Issue by Faethair** [Bionus/imgbrd-grabber#1459]
**Bug description**

Downloads, apparently only when using Sankaku as a source, often stop downloading partway through. They continue after a while.

**Steps to reproduce**

**Expected behavior**

Normal downloads as with other sources.

**Context**

Log spams "[Info] Details limit reached (429). New try."

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/2464042/settings.txt)

**Screenshots**

**System information**

- OS: Windows 7 64-bit Ultimate SP1
- Grabber version: 6.0.6

**Additional context**

**Comment by Bionus** [comment]
Yes, that's expected.

Sankaku enforces traffic limits that blocks you from doing any requests for 2 minutes (IIRC) after you do too many of them. If you don't want those to happen, you should set some intervals in the Sankaku source settings, to prevent Grabber from reaching the Sankaku traffic limit:

![](https://cloud.githubusercontent.com/assets/882719/25774030/777aa812-3288-11e7-8579-2d39cacdf314.png)

**Comment by Yaro-Kira** [comment]
Listen, try to make a delay like mine (especially pages). This helped me a lot with sankaku, but very rarely the download can stop at half, then you need to click on the pause and resume.

![Delay](https://user-images.githubusercontent.com/61095746/75248603-82b13400-57e5-11ea-9cc4-d865bb7c2de6.png)
