### ISSUE TITLE
Port to mobile devices

### ISSUE THREAD

**Issue by AkiraSakura** [Bionus/imgbrd-grabber#1466]
Do you plan to port this program to the Android/IOS systems?

**Comment by Bionus** [comment]
I've thought about it a few times, especially given Qt seems to support porting to mobile devices without too big difficulties.

So I think I might do it in the future, but not very soon.

Aren't there already a bunch of apps doing the same thing anyway? (browsing part)

**Comment by AkiraSakura** [comment]
Browsing maybe, but not Group Downloading ^^

**Comment by AkiraSakura** [comment]
I agree, it is convenient to use a computer, but when there is no access to a PC, I would like to do it from mobile devices.

No, no, applications with many packages are non-existent. There is only a single app tied to your website.

**Comment by Amazingduf** [comment]
> 
> Plus, you say there's apps for browsing, do you have any examples? Especially apps that support multiple sources like Grabber.


I've been using [Animeboxes](http://www.animebox.es/) for a very long time, it also supports batch downloading but it's not nearly as good as Grabber, I've been using it just for browsing boorus.

**Comment by Bionus** [comment]
> given Qt seems to support porting to mobile devices without too big difficulties

FYI, I just built Grabber for Android, and after a few bugs here's the result. The UI is horrible but works:

![photo_2018-10-17_02-30-19](https://user-images.githubusercontent.com/882719/47054856-9b064d00-d1b4-11e8-95cf-bf5425cebd97.jpg)

![photo_2018-10-17_02-22-58](https://user-images.githubusercontent.com/882719/47054711-b45ac980-d1b3-11e8-9fc8-70178400dd28.jpg)

Porting it properly would require having separate designs for desktop and mobile, using [QtWidgets](https://doc.qt.io/qt-5.11/qtwidgets-index.html) and [QML](https://doc.qt.io/qt-5/qtqml-index.html) respectively. That would require properly extracting **all** the logic out of "view" files, as well as re-designing and implementing all parts of the UI, which is a lot of work.

**Comment by AkiraSakura** [comment]
@Bionus Hi, how are you doing with the mobile version? (I need it xDD)

**Comment by Bionus** [comment]
Closing in favor of issue #2147
