### ISSUE TITLE
Temp file stored in the same folder if conditional names are used

### ISSUE THREAD

**Issue by Babyforce** [Bionus/imgbrd-grabber#1468]
**Bug description**

When conditional filenames are used to move a file depending on a specific tag to a different folder, the temporary file is kept in the same folder as where the image is saved and is not deleted. Not downloading the file but letting the image load will generate a temp file that will become an image that will stay. Because of this, a lot of duplicates are created, since none of the temporary files are deleted upon leaving the software. The same applies with separate log files. Those files are created even for the temp files and are not deleted, the same way as the temp images. Only tested with Suffix location type:
![grabber_2018-10-13_19-11-28](https://user-images.githubusercontent.com/1695422/46907992-ed790c80-cf1b-11e8-8b75-bc6908dc11ce.jpg)

**Steps to reproduce**

1. Setup a conditionnal name (like this for example)
![grabber_2018-10-13_18-37-53](https://user-images.githubusercontent.com/1695422/46907723-22cf2b80-cf17-11e8-9785-5161c16e3965.jpg)

2. Select an imageboard and load images.
3. Click an image and check the folder it concerns.
4. Save the image.
5. Close Grabber.

**Expected behavior**

The temp files should not be in the same folder as the saved images and should be deleted once Grabber exits (or at least, when they are not in use anymore).

**Context**

Only the save path and the conditional names were modified, the rest was left as is after being created automatically by the software.

**Screenshots**

![grabber_2018-10-13_17-39-07](https://user-images.githubusercontent.com/1695422/46907873-e0f3b480-cf19-11e8-8804-b850b9230eae.png)

**System information**

- OS: Windows 10
- Grabber version: 6.0.6

**Additional context**

If, after viewing a few images the imageboard is changed, it seems like the temporary files from the current session are deleted. It would be a workaround to avoid getting a lot of duplicates, but is not convenient at all.

**Comment by Bionus** [comment]
Indeed, it would seem that the conditional filenames have priority over the temporary directory when loading images in the image view window.

I just pushed a fix, thanks for the detailed very helpful report! 👌 

> If, after viewing a few images the imageboard is changed, it seems like the temporary files from the current session are deleted. It would be a workaround to avoid getting a lot of duplicates, but is not convenient at all.

The fact that the temporary files are not deleted when the program is closed is actually a bug, thanks for pointing it out. Fixing this doesn't seem as trivial, but I'm working on this too :+1:

**Comment by Babyforce** [comment]
Thanks for looking into the bug, and you're welcome, I like being able to participate in the improvement of a software I use often!
