### ISSUE TITLE
How can I log in to Sankaku?

### ISSUE THREAD

**Issue by ElBabe44** [Bionus/imgbrd-grabber#1470]
Hello, I'm new using your program, I have a question in SankakuChannel, it does not let me log in, I get a message that says error, how can I solve that?

![image](https://user-images.githubusercontent.com/44126601/46911239-311f4680-cf1b-11e8-8190-cd0134c62f42.png)

**Comment by Bionus** [comment]
Have you checked the [documentation for login](https://bionus.github.io/imgbrd-grabber/docs/website-login.html)?

You have to hash your password using the button next to the password field ("Cifrar contraceña" in your locale it seems). The password field will then be filled with a hash of your password, which is a 32 characters-long string (ex for "test": "b842ee4b63ff70e4bfb8537593b295a5f95f3710").

![image](https://user-images.githubusercontent.com/882719/47121045-60aeb580-d271-11e8-9d7f-3d95a53e1b0d.png)
