### ISSUE TITLE
Sort %copyright%, %species% and other %var% alphabetically.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1471]
**Is your feature request related to a problem? Please describe**

I'ts not a real problem, but on e621 big batches it's annoying. Sometimes, a lot in fact, it create a lot of folder for the sames species ou copyright. like : https://i.imgur.com/cficBHT.jpg, and it's just with four tags in the capture... Imagine this with a dozen now ! It's a hell lot of folder, sometimes for the exact same species.

**Describe the solution you'd like**

I think a simple solution would be to order tags before creating the folder/file, alphabetically would be fine. maybe we should have this option here : https://i.imgur.com/r857icC.jpg at the end like a check case : "sort tag by alphabet order." for this variable.

**Comment by Bionus** [comment]
Actually, you can already do that using the undocumented `sort` option: `%species:sort%`, `%copyright:sort%`, etc.

But I can see the use of having this directly in the UI, and have it default to ascending name sorting.

**Comment by yami-no-tusbas** [comment]
God u made my day !

https://i.imgur.com/pZ3jCwv.jpg

The last number is the directories count. 🥇
