### ISSUE TITLE
Compile error involking cmake Zorin OS 12 Core

### ISSUE THREAD

**Issue by chrisrlink** [Bionus/imgbrd-grabber#1472]
have an error involking cmake durring first stage of compiling latest build regardless of branch (tend to use development) 

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
INFOCompiling with SSL support
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")  
INFOOpenSSL include dir: /usr/include
INFOOpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Configuring done
CMake Error: AutoUic (lib): The uic executable "" does not exist

notes: I had to compile cmake first cause the repo's one is too old (3.05 if i remember) so i compiled latest/installed it (3.13) Zorin OS 12 is based on Xenial Ubuntu

**Comment by Bionus** [comment]
>  CMake Error: AutoUic (lib): The uic executable "" does not exist

Do you have the Qt 5 libraries installed and the `uic` in your path? If you install "qtbase5-dev", "qtscript5-dev", "qtmultimedia5-dev", "qttools5-dev", and "qttools5-dev-tools" you should build with no issues.

> notes: I had to compile cmake first cause the repo's one is too old (3.05 if i remember) so i compiled latest/installed it (3.13) Zorin OS 12 is based on Xenial Ubuntu

Yeah I really have to lower the minimum CMake version, it's truly a pain, even on Windows or recent Linux versions.

**Comment by L2Huang** [comment]
I got the same error : CMake Error: AutoUic (lib): The uic executable "" does not exist;
I'm building it on Windows and I'm sure I have installed the qt5 libraries and add the uic.exe to PATH;

**Comment by L2Huang** [comment]
I found the solution in:[https://gitlab.kitware.com/cmake/cmake/issues/18630](url)
This issue only happens on CMake version 3.13, so I updated my CMake to version 3.14, now it's all OK.
