### ISSUE TITLE
Page number automatically goes back to page 1

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1474]
**Bug description**

When you go to the next page the number above directly resets itself to page 1

**Steps to reproduce**

First search up results with more than 1 page
Now click on next
When you now click on next you will stay on page 2 and you will see that the page number above is 1

**Expected behavior**

Go to the next page without a issue

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
On which source/search did this occur? I just tried on a few sources with no issues.

**Comment by MrAndre96** [comment]
Hmm I can't reproduce it after reopening grabber. Will comment here again if I find a way to reproduce it

**Comment by MrAndre96** [comment]
@Bionus When you use for example the sources sankaku complex, gelbooru, yande.re, konachan, rule34, danbooru and anime-pictures you will get this bug. When you take either danbooru away or anime-pictures the bug will not appear anymore. So for some reason those 2 sources can't be used together now

**Comment by MrAndre96** [comment]
@Bionus When you use for example the sources sankaku complex, gelbooru, yande.re, konachan, rule34 and anime-pictures you will get this bug. When you take away anime-pictures the bug will not appear anymore. (You will have to click 2 times on next most of the time before you see the bug)

**Comment by MrAndre96** [comment]
@Bionus When you use for example the sources sankaku complex, gelbooru, yande.re, konachan, rule34 and anime-pictures you will get this bug. When you take away anime-pictures the bug will not appear anymore. (You will have to click 2 times on next most of the time before you see the bug)

**Comment by Bionus** [comment]
Indeed, this only happened with multiple sources selected, and when the number of pages was not the same between them (especially when one source didn't have any result at all).

This should have been fixed by commit b63910b3024b80a655d4942167436e468de255b6.
