### ISSUE TITLE
Batch downloading has a bug when it goes to the next batch

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1475]
**Bug description**

When you have downloaded your first batch of images it goes to the second one. (So for example gelbooru has a limit of 500 each time so it happens when you start downloading image 501.) When this happens it will not wait for downloads that are still going on and it seems that it suddenly has 2 downloaders or something instead of one.

**Steps to reproduce**

Just download a large number of images (So it goes to the next batch)
After that you will see suddenly 2 downloaders (Probably a visual bug or something)

**Expected behavior**

That this visual bug or what it is is not there and that it waits untill the image is finished with downloading. (ohterwise you will generate much traffic)

**Screenshots**

[https://i.imgur.com/aomO9KM.png](https://i.imgur.com/aomO9KM.png)

**System information**

Windows 10 with the latest nightly version

**Comment by MrAndre96** [comment]
@Bionus So when I tried to download for example azur_lane on gelbooru and startted to download it, it will be normal untill it gets to the next part (After the first 1000 images and for me for some reason 500). When this happens you will see the 2 download indicators as above in the screenshot

**Comment by Bionus** [comment]
Ah so what you mean is that for the first pack (for some reason for you it's 500, maybe you changed the value of `packing_size` in your `settings.ini` file?), it downloads images one by one, but when it starts downloading the second pack, it will download images two by two? As if you set your "simultaneous downloads" setting to "2"?

In that case, while it's annoying, it's not a _breaking_ bug right? It just downloads faster? (just making sure I properly understand the issue)

**Comment by MrAndre96** [comment]
@Bionus Yeah that is true but it shouldn't be the case I think since it downloads first 1 by 1 and after that 2 by 2 idk if it continues with 3 by 3 etc which could in the end generate a lot of load for a website. For example sankaku already blocks it when there comes some load with 1 by 1 so it will block twice as fast with 2 by 2

**Comment by Bionus** [comment]
> @Bionus Yeah that is true but it shouldn't be the case I think, since it downloads first 1 by 1 and after that 2 by 2 idk if it continues with 3 by 3 etc which could in the end generate a lot of load for a website. For example sankaku already blocks it when there comes some load with 1 by 1 so it will block twice as fast with 2 by 2

Yes, I'm not trying to look down on the issue, just making sure I understood it properly 😄 

It's actually, as you said, a big bug, that could have big consequences, especially on image counting, race conditions, etc. I just pushed a fix (666d6da154c188aff503f5cdba6a0755783f878e). Nightly is broken right now so you'll be able to get it after I fixed the tests!

Thanks (as always 👍) for the report and the additional details!
