### ISSUE TITLE
When you have a image view open and decide to close grabber it will result in a crash

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1476]
**Steps to reproduce**

Open a image view (So just click on a image)
Now just close grabber but let the image view stay open
Now you will see that a crash appears

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Indeed, when fixing some memory leak, I decided to not force-quit the application when closing it. Because of this, it seems image windows are not properly closed when the main window closes (which is the main bug here).

I just pushed a fix, thanks :+1:
