### ISSUE TITLE
Tab softlock on invalid query

### ISSUE THREAD

**Issue by Kuroonehalf** [Bionus/imgbrd-grabber#1477]
Steps to reproduce:
- Open a new tab
- Query using a tag that does not exist on that booru (for example "saidhaiush" on gelbooru)

It will return a "no result" message where the page indicator is set to 0, and the tab is hereby softlocked. You can't manually change the page number. Correcting your query still maintains the page number at 0 with no results and a locked page number input.  The only thing I've found to get it unstuck is to change source to something else.

**Comment by Bionus** [comment]
Indeed, I can reproduce that on 6.0.6.

This seem to be the same issue as described in #1450, so I'll mark this issue as a duplicate. This should therefore be fixed in nightly. 😄
