### ISSUE TITLE
Cannot download an image by ID

### ISSUE THREAD

**Issue by FirstDagger** [Bionus/imgbrd-grabber#1478]
**Bug description**

Cannot download an image by ID

**Steps to reproduce**

1. Go to "Downloads" tab
2. Click "Add"
3. Select chan.sankakucomplex.com
4. Enter ID (e.g. 7256480)
5. Click "OK"
6. Select added Download
6. Click "Download selected"

**Expected behavior**

Data is filled and download is possible

**Context**

[21:43:31.487][Warning] [chan.sankakucomplex.com][Html] Uncaught exception at line 109: TypeError: Cannot call method 'replace' of undefined
[21:43:31.487][Info] Adding single image: 

[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/2507754/settings.zip)

**System information**

- OS: Windows 10
- Grabber version: 6.0.6

**Comment by Bionus** [comment]
I can't reproduce on my end, even with your settings file.
However, your error message checks out with the code, as if it couldn't find the original image URL on the details page 🤔 

* Does this issue occur every time you try to add a download, or only from time to time?
* Or you logged into Sankaku (via Grabber), or anonymous?
* If you open https://chan.sankakucomplex.com/post/show/7256480, do you see the "Original: 500x500 (236.7 KB)" link on the bottom left?

**Comment by FirstDagger** [comment]
1. Almost ALL single downloads do not work, HOWEVER 7247746 works. But still calls

[20:29:06.907][Warning] [chan.sankakucomplex.com][Html] Uncaught exception at line 109: TypeError: Cannot call method 'replace' of undefined
[20:29:06.907][Info] Adding single image: 

2. Yes, same error without logging in.

3. Firefox, yes. Chromium, yes.

I believe however I found what caused my error.

**Steps to reproduce**

1. On a clean install 

2. Click "Options" on the First Start screen and not "Ok"

It closes the First Start screen and NO initial settings are applied.

**Suggested Behavior**

Either keep that First Start window open or apply the setting as if "Ignore" would be clicked.
