### ISSUE TITLE
Generate "official" releases from AppVeyor

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#1479]
Currently, nightly versions are properly built by AppVeyor, and have multiple users using them without issues. Also, releases are currently a pain to do for me as a maintainer, causing long times without releases (in average one month).

Therefore, it should be possible to use AppVeyor to generate "official" releases too.

* [x] When a tag is pushed on the master branch
* [x] Generate a real release (not a "nightly" one)
* [x] Upload the installer to GitHub
* [x] Generate and upload symbol files to GitHub
* [x] Install and enable QScintilla
* [x] Install and enable Google Breakpad

https://www.appveyor.com/docs/deployment/github/#release-every-tag-build

In addition to this, Linux and macOS releases could also be generated from Travis-CI.

⚠️ Depending on which build finishes first, the description might be overwritten by either, so the script should make sure that it only writes release description if the description is empty.

Required for #1388.

**Comment by MrAndre96** [comment]
@Bionus you said that this was required for #1388 but there still hasn't been made a 64 bit version of grabber
