### ISSUE TITLE
Option to download a List of IDs or URLs

### ISSUE THREAD

**Issue by FirstDagger** [Bionus/imgbrd-grabber#1480]
**Is your feature request related to a problem? Please describe**

My problem is that I have a large collection of books from imageboard sites and want to download them without having to copy each ID into Grabber. As it additionally required selecting the site for each image, once would be preferred.

**Describe the solution you'd like**

A button that allows import or paste of a unsorted list of either imageboard image IDs or imageboard URLs into the Downloads area.

The list can look like this:

https://danbooru.donmai.us/posts/2135465?tags=parent%3A2119605+status%3Aany
https://danbooru.donmai.us/posts/2068668?tags=kantai_collection
https://danbooru.donmai.us/posts/1900839?tags=shizuma_yoshinori
https://chan.sankakucomplex.com/post/show/4713784
https://chan.sankakucomplex.com/post/show/4511118
https://chan.sankakucomplex.com/post/show/3562912
https://chan.sankakucomplex.com/post/show/3576077
https://danbooru.donmai.us/posts/2068673?tags=kantai_collection
https://danbooru.donmai.us/posts/2015782?tags=shizuma_yoshinori
https://danbooru.donmai.us/posts/2068672?tags=kantai_collection
https://danbooru.donmai.us/posts/2068677?tags=kantai_collection
https://danbooru.donmai.us/posts/2068680?tags=kantai_collection
https://danbooru.donmai.us/posts/2068681?tags=kantai_collection
https://danbooru.donmai.us/posts/2068788?tags=kantai_collection

Or like this, with an option to select the site they are from:

3576077
3562912
4511118
4713784

Probably the second option as it is easier for you to implement.

**Comment by Bionus** [comment]
> Probably the second option as it is easier for you to implement.

Indeed, in the current state of things, the first one wouldn't be possible to do easily.

> A button that allows import or paste of a unsorted list of either imageboard image IDs or imageboard URLs into the Downloads area.

Actually, if I'm going with the second option, simply adding some `v` button next to the "ID" field, to make it grow into a text area, where you would enter one ID per line, would do what you want, wouldn't it?

![image](https://user-images.githubusercontent.com/882719/47616879-9ef27300-dac2-11e8-98e6-c64431ede325.png)

**Comment by FirstDagger** [comment]
Yes, that would do exactly what I would want it to do. Awesome.

**Comment by Bionus** [comment]
Before:
![image](https://user-images.githubusercontent.com/882719/47619656-bd1b9b80-dae1-11e8-928a-2a053ec47854.png)

After:
![image](https://user-images.githubusercontent.com/882719/47619663-c73d9a00-dae1-11e8-911c-8a56a029de05.png)
