### ISSUE TITLE
it deletes my favorites and save for lattes  

### ISSUE THREAD

**Issue by sinkiller21st** [Bionus/imgbrd-grabber#1481]
**Bug description**

**Steps to reproduce**

**Expected behavior**

**Context**

* Provide your `main.log` file to see if any obvious error occured.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occured during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

![capture](https://user-images.githubusercontent.com/39547304/47570802-0793f100-d905-11e8-8137-e75e57db5a07.PNG)

**System information**

- OS: [e.g. Windows 10]
- Grabber version: [e.g. 6.0.3]

**Additional context**

Add any other context about the bug report here.

i have windows 10 

i have grabber 6.0.5

**Comment by sinkiller21st** [comment]
![capture2](https://user-images.githubusercontent.com/39547304/47571141-db2ca480-d905-11e8-9898-fd3cbb34f38b.PNG)

**Comment by sinkiller21st** [comment]
every so often it deletes its own data all saves all keep for latters and all favorites  and close its self out of no wair

**Comment by Bionus** [comment]
> every so often it deletes its own data all saves all keep for latters and all favorites and close its self out of no wair

Can you define "every so often"?
Does it happen every time you start Grabber? When you add a favorite?

> ![](https://user-images.githubusercontent.com/39547304/47570802-0793f100-d905-11e8-8137-e75e57db5a07.PNG)

It seems you are opening `favorites.txt`. This file is not used since a few versions, favorites are now stored in the `favorites.json` file. Is it also empty?

**Comment by ThatOneGuy696969** [comment]
Hello im also having the same issue, it seem that my favorites are being cleared. I will open Grabber one day and they will be there, then some unknown amount of time later I will open it again and they will be gone. It doesn't seem to happen two sessions in a row. When I add a favorite it saves fine, It also doesn't happen when I save a specific number of favorites as far as I can tell. The favorites.json is filled with "NUL".

**Comment by ThatOneGuy696969** [comment]
> 
> 
> Hello im also having the same issue, it seem that my favorites are being cleared. I will open Grabber one day and they will be there, then some unknown amount of time later I will open it again and they will be gone. It doesn't seem to happen two sessions in a row. When I add a favorite it saves fine, It also doesn't happen when I save a specific number of favorites as far as I can tell. The favorites.json is filled with "NUL".

I also forgot to add I have tried the recent stable version and nightly and the same issue is there.
