### ISSUE TITLE
Latest nightly build missing files with install

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1487]
**Steps to reproduce**

Install the latest nightly version
You get a message that qscintilla2_q5.dll can't be found by which the program can't be opened

**Screenshots**

![https://i.imgur.com/flwY2RE.png](https://i.imgur.com/flwY2RE.png)

**System information**

Windows 10 with the latest nightly build

**Comment by Bionus** [comment]
Sorry, seems like it was caused by #1479, given nightly versions didn't even use QScintilla before.
I just pushed a fix, and the latest nightly should be fixed now. 👌
