### ISSUE TITLE
Grabber doesn't recognize the size by one of the sources

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1489]
**Bug description**

By the source rule34.paheal.net grabber doesn't recognize the size of the image

**Steps to reproduce**

Enable the source rule34.paheal.net
Search for a image
Open the image and you will see that grabber doesn't recognize the size

**Expected behavior**

It will show the size of the image

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Indeed, it seems that not only Grabber fails to parse the image size from the page, it also doesn't properly update the detected size when the image is done loading.

Two bugs in one, so I just pushed two fixes 😄
Thanks for the heads-up 👍
