### ISSUE TITLE
The image window will not minimize / go to the background when you click 'Open in new tab'

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1490]
**Bug description**

When you use the right click on a tag in de image window and click 'Open in new tab' it will open the new tab in the background but the image window will not go to the background like it was before.

**Steps to reproduce**

Search for a image
Use the option "Open in new tab" in the image window
The image window will not go to the background

**Expected behavior**

I expect the image window to minimze or go to the background since you will now not see if the tag has been opened in a new tab untill you minimze it yourself

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Actually the main issue is more that the image window is **always** one top while opened.

I can't believe I've been so busy working on the build system and testing that I didn't notice such an obvious breaking bug 😱

**Comment by MrAndre96** [comment]
Sometimes the most obvious bugs you see at last
