### ISSUE TITLE
Downloading Isn't Working

### ISSUE THREAD

**Issue by VentriloEYEZ** [Bionus/imgbrd-grabber#1491]
Hi, I've had this program for a while and never had this issue. I press "get page" and the pics go into the download tab, but when I press "download all" it doesn't download anything. Please help

**Comment by Bionus** [comment]
Can you tell me which sources does this happen on? And which search? (an `.igl` file would help)

Also, what do you mean "it doesn't download anything"? Does the download window open? Are all images skipped?

The best would be for you to share your log after trying to download, so I can see what's happening.

**Comment by GuyInDogSuit** [comment]
I've tried downloading multiple files at once, and it just skips/ignores a lot of them. If I try to preview it and manually save it, it's all pixelated.

I would attach a log, but I don't know where they're stored.
