### ISSUE TITLE
Hydrus-friendly Image and DB export format

### ISSUE THREAD

**Issue by DonaldTsang** [Bionus/imgbrd-grabber#1492]
**Is your feature request related to a problem? Please describe**

Using Imgbrd-Grabber to download mainstream *boorus faster and Hydrus for niche websites, general image management and IPFS capabilities

**Describe the solution you'd like**

The creation of a new export file structure/format using Zip or others to package all images downloaded from Grabber along with the DB (which can be compressed into a smaller archive) and send it to Hydrus

**Describe alternatives you've considered**

Simple file path with formatted  structure for image and DB location for easy drag-and-drop into Hydrus (that can be coordinated into a new feature in Hydrus for intermediate data transport)

**Additional context**

- [ ] Needs metadata information, including web link, image format, size, dimensions
- [ ] Needs to maintain all tags and meta-categories e.g. reference/copyright, artist, character

**Comment by Bionus** [comment]
AFAIK Hydrus supports the "text file beside the image" format, so you can just use an separate tag file, with a ".txt" suffix and contents set to something like (there's a bunch of issues describing it in more details, such as issue #1001 or #588):

```
rating:%rating%
%all:includenamespace,excludenamespace=general,unsafe,spaces,separator=\n%
```

Or do you really need the ZIP/DB part?

**Comment by DonaldTsang** [comment]
@Bionus right now I am a bit confused with the downloaded image files and I wondered where the tags have went.

**Comment by DonaldTsang** [comment]
@Bionus after testing around with Imgbrd-Grabber, I would like to say that it would be nice to have txt exports as out-of-the-box default.
