### ISSUE TITLE
Slow Duplicates Check

### ISSUE THREAD

**Issue by baraa272** [Bionus/imgbrd-grabber#1497]
**Is your feature request related to a problem? Please describe**
Yes 

when downloading large lists for example 
hatsune_miku on (konachan) will give you  12126 images 
the problem is when i just cancelled the download for (any reason) 
and then search again with same (hatsune_miku) will give me the same count and it will start again normally 
SKIPPING DUPLICATES IS REALLY SLOW 
really i mean it skipping duplicates from the first image is really really slow and if you have 12126 it will take a lot of time before even start downloading because it was checking for duplicates SLOWLY 

**Describe the solution you'd like**

a really fast mechanic to clear duplicates detected from downloads links list

is there anything i missed ?

**Comment by brazenvoid** [comment]
You mean you want to skip already downloaded files?

**Comment by brazenvoid** [comment]
One more thing, the count of images can't be changed as this app is independent of the websites it browses. All the features like black list or downloads are working through this app, the website does not know of these, thus results will have no change.
At maximum, the results can be filtered before full image download to an extent. This differs for different sources.

**Comment by baraa272** [comment]
Thanks
