### ISSUE TITLE
Help with "Tagfile" and hydrus

### ISSUE THREAD

**Issue by baraa272** [Bionus/imgbrd-grabber#1498]
grabber 6.0.6

Tomorrow I'll download 12126 files from konachan 
now i read here before to migrate to hydrus you need %all% and a (Tagfile)
actually %all% is implemented 
my filename is (%search%/%websitename%/%character%/%md5%_%filename%_%all%.%ext%)
is there something i'm doing wrong above?
also when i tried as mentioned in #1223 
 
![image](https://user-images.githubusercontent.com/32843097/48076628-44f25b80-e1ee-11e8-92ad-b6ea1f024ff6.png)
it doesnt work i dont see the txt files 
is there something i'm doing wrong above???

**Comment by Bionus** [comment]
You should use the "suffix" location type with ".txt" as the value.

Also, AFAIK a better text file content is:
```
rating:%rating%
%all:includenamespace,excludenamespace=general,unsafe,spaces,separator=\n%
```

**Comment by baraa272** [comment]
I used it as you actually mentioned 
still theres no TXT files ???????

**Comment by baraa272** [comment]
i used suffix as you mentioned but still i dont see any TXT files ???
![image](https://user-images.githubusercontent.com/32843097/48113587-3fcff380-e264-11e8-96af-1d38294b4e2a.png)

**Comment by Bionus** [comment]
You're only supposed to put the suffix in the field, in your case ".txt".
You don't need to put the whole filename.

**Comment by baraa272** [comment]
![image](https://user-images.githubusercontent.com/32843097/48121019-7f0a3e80-e27c-11e8-85b2-45c44349a7d3.png)

Still no txt files ????????????????????????

**Comment by Bionus** [comment]
You don't have to put quotes...

**Comment by baraa272** [comment]
bigger problem 
its working BUUUUUUUT actually grabber doesnt create files when skipping duplicates 
AM I REALLY forced to redownload 16GB again???????????

**Comment by baraa272** [comment]
anything my brother?

**Comment by Bionus** [comment]
You can also change your "global duplicate" setting to "move", then download them to another folder. In this case, it should create the TXT files without re-downloading the images.

See the second part of my comment on [issue #1484](https://github.com/Bionus/imgbrd-grabber/issues/1484#issuecomment-433702282).

**Comment by baraa272** [comment]
i'm actually confused to bone 
I cant seem to understand what you said

**Comment by baraa272** [comment]
location save : C:\Users\PC\Desktop\Grabber 
16gb location : C:\Users\PC\Desktop\hatsunemikuKONACHAN
filename : %search%/%websitename%/%character%/%md5%_%filename%_%all%.%ext%
can you tell what to do exactly ?

**Comment by baraa272** [comment]
any help brother ?

**Comment by baraa272** [comment]
okay thanks for help i just redownloaded it :(
