### ISSUE TITLE
About MD5 recognition : am I right ...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#150]
I had some strange result while downloading some images, but I think this is because of the ways Grabber work.

using '%search_1%[%artist%] %website% %id% (%copyright% (%character%)).%ext%'
so it will download in separated folders.
on danbooru and gelbooru :
1. I searched for tag sasa_ichi, and choosed 'get all'
2. I searched for tag ssss, and choosed 'get all' (ssss is almost the same as sasa_ichi)
3. start downloading

results :
'ssss' folder is filled with files but 'sasa_ichi' is almost empty, it seems it did not downloaded the files already downloaded for 'ssss'.

As I understand it, MD5 recognition work 'in active memory', not 'depending on folder'.
Thats is absolutely not what I expected, but it is an interesting feature.
but sometime, it can be troublesome, like in this case, with different folders.

we can assume that some peoples would like 1 folder for 'naruto', and another for 'dragon ball'.
some peoples might wish to have images including naruto and dragon ball characters in both folder, while some other would think 'once is enough, I do not want duplicate'

> Original issue reported on code.google.com by `ser...@hotmail.com` on 30 Oct 2012 at 11:37

**Comment by MasterPetrik** [comment]
@Bionus isn't these features already implemented in Grabber? Maybe close it?
