### ISSUE TITLE
No filename tag for idols from idol.sankakucomplex.com

### ISSUE THREAD

**Issue by NielR** [Bionus/imgbrd-grabber#1501]
Any 'idol' tag being present is not saved when using the %artist% or %character% tags. They are also not included in the %general% tag and %all% is too unreliable when there are lots of tags because of the pathlength limitation.
I also tried the %model% (Behoimi specific) and %idol% (non-existant) tags, but those did not work either.

**Comment by Bionus** [comment]
Indeed, it seems it wasn't supported properly.

Instead of creating a new token and duplicating everything in the settings (from the `model` token), I decided to simply use `%model%` for both. 👌
