### ISSUE TITLE
cannot disable md5 list

### ISSUE THREAD

**Issue by Tokyo-All-Ready** [Bionus/imgbrd-grabber#1502]
I want to disable the md5 list for a few artists

so i went and cut md5s.txt from appdata/local/bionus and pasted it to my desktop
it backed up the file
so i did a search of text files by size on computer and found nothing

how do i download and not add md5's to the list?  i dont see any options for that

**Comment by brazenvoid** [comment]
What is the use case here? Like what you are trying to do with which the md5 list is proving a hindrance?
