### ISSUE TITLE
Grabber mis-detecting filetypes when using preload feature (Leads to blurry images in image window)

### ISSUE THREAD

**Issue by yennixsg** [Bionus/imgbrd-grabber#1507]
**Bug description**

When browsing in the Image Window and viewing files that have not been downloaded, with the preloading feature enabled, Grabber will mistakenly cache the file to temp storage with the wrong extension. 

IE: PNG files will be saved as `/Users/yennix/Pictures/furry/booru/65999e0e0a55f4cfa84cf6873fd74e5f.jpg` and vice versa. 

This causes the Image Window to display a pixelated or blurry image. 

Opening the temp file in a different viewer shows the file is uncorrupted and working as expected, but simply has the wrong filetype extension on the end of it's filename. 

If the blurry image is then saved, and the Image Window moves awayfrom and then back to the suspect image, the next time it's displayed correctly after being read from local disk.

Further, when the file is saved, it gets the correct file extension to it's filename. 

**Steps to reproduce**

1. Start a session and ensure that preloading is enabled. Try three preload images.
2. Do a search and open the Image Window
3. Browse until one of the files appears blurry.

**Steps to mitigate**
1. Disable preloading entirely. This makes browsing much slower, but images will always display correctly. 

**Expected behavior**

Preloading should download the files in advance of the current Image Window position, and save to temp storage, displaying the files correctly using the appropriate renderer

**Context**
***Log File***
In the following logfile, Image #2 (`/var/folders/xm/nzgrfgpj0gdcd1v4n2gcst8c0000gq/T/Grabber/75a1def1-c454-4092-ac79-f0190d07fd4f.jpg`)is actually a PNG, but is downloaded as a JPG. When viewed, it appears blurry. 
When it is then later saved (`/Users/yennix/Pictures/furry/booru/dee6c8ca38c71d1e91e3f470ac4a0908.png`) and viewed a second time, it displays correctly. 

[main.log](https://github.com/Bionus/imgbrd-grabber/files/2591645/main.log)

***settings.ini***
[settings.ini.gz](https://github.com/Bionus/imgbrd-grabber/files/2591647/settings.ini.gz)

**Screenshots**
***Screenshot of the first failed load***
![failed_load](https://user-images.githubusercontent.com/35630328/48659740-aec00000-ea4d-11e8-83fe-a1d4711decfe.png)

***Screenshot of the second good load***
This is the same image after clicking the save button, got left or right by one image and then returning to this image. 
![successful_load png](https://user-images.githubusercontent.com/35630328/48659801-65bc7b80-ea4e-11e8-82e9-ac7ec2eb5059.png)

**System information**

- OS: MacOS 10.12.6
- Grabber version: commit 430464b (HEAD -> develop, origin/develop)

**Comment by MrAndre96** [comment]
Yeah happens to me aswell but for me is it faster without preloading so I don't bother with it

**Comment by Bionus** [comment]
Indeed, I could reproduce the issue.

It's quite weird because Grabber properly gets the url with a PNG extension, but still tries to save it as a JPG. I'll investigate and push a fix ASAP. :+1:

**Comment by Bionus** [comment]
Found it! The issue was that all preloaded images had the same extension as the current image. So if you opened a PNG image, all preloaded images would be loaded as PNG, even if they had a JPG URL.

**Comment by yennixsg** [comment]
I'll rebuild and give this a test! Thanks!
