### ISSUE TITLE
Page numbering not correct for one source

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1511]
**Bug description**

By the source anime-pictures the amount of pages is reduced by 1. So for example when you should have 9 pages you only get 8 of them and since you can't go to the next page if the other sources don't have any images, you will not be able to see them.

(I don't know if you want to 'fix' this since it is a bug on their end)

**Steps to reproduce**

Enable the source anime-pictures
Search nekopara
You will see that it has only 8 pages which is correct if you would check the json with the max_pages. But this only counts 1 and above and not the 0 on which it starts.

**Expected behavior**

Display the correct number of pages

**System information**

Windows 10 with nightly version 430464b4

**Additional context**
[https://anime-pictures.net/pictures/view_posts/0?denied_tags=&search_tag=nekopara&posts_per_page=20&lang=en&type=json](https://anime-pictures.net/pictures/view_posts/0?denied_tags=&search_tag=nekopara&posts_per_page=20&lang=en&type=json)
[https://anime-pictures.net/pictures/view_posts/8?denied_tags=&search_tag=nekopara&posts_per_page=20&lang=en&type=json](https://anime-pictures.net/pictures/view_posts/8?denied_tags=&search_tag=nekopara&posts_per_page=20&lang=en&type=json)

**Comment by MrAndre96** [comment]
@Bionus based on the comment I got here: [https://github.com/stalkerg/anime-pictures/issues/81](https://github.com/stalkerg/anime-pictures/issues/81) it seems that max_pages is the last page index

**Comment by Bionus** [comment]
Indeed, from the name "max_pages" and the answer to the issue you posted in stalkerg/anime-pictures, it would be the "last page index" instead of the "page count". And since indexes start at 0 for anime-pictures, that would make "page count = max pages + 1".

I pushed a fix 👌
