### ISSUE TITLE
Strange default setting for Save - Artist tags?

### ISSUE THREAD

**Issue by cyaoeu** [Bionus/imgbrd-grabber#1512]
**Is your feature request related to a problem? Please describe**

I wondered why my files ended up in a folder called "multiple artists" (using %artist%\) but it turns out there's a setting for artist tags and it's set to "Replace all tags by: multiple artists" which to me seems kind of strange. Let's say you had an image with two artists, artist a and artist b, when saved it would turn into "multiple artists" which is neither, so now you have no idea who the real artist is. It's even worse when grabbing lots of different artists where images with several artists just end up in a mess in the "multiple artists" folder (or filenames depending on your naming).

I'm just confused when you would want "multiple artists" instead of either all tags, one tag or several files (one for each artist).

**Describe the solution you'd like**

Set the default setting to all tags (or several files).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Bionus** [comment]
To be fair, pretty much every default value would be wrong for someone. There's no perfect default, and each user should setup everything to their own tastes.

Grabber was (heavily) inspired by the [Danbooru Downloader Firefox add-on](https://web.archive.org/web/20181102055646/https://addons.mozilla.org/en-US/firefox/addon/danbooru-downloader/) (now discontinued), and all defaults have been taken from that add-on.

I understand however that "multiple artists" is quite a useless default, so I'll change it to save all artists instead (same for other things such as copyrights and characters by the way).
