### ISSUE TITLE
When you click open in new tab with a tag which has special characters not the whole tag goes into the new tab

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1513]
**Bug description**

When you want to open a tag in a new tab which has special characters not the whole tag goes into it but only one part of it.

**Steps to reproduce**

Search `watashi_ga_suki_nara_"suki"_tte_itte!` with the source sankaku/danbooru etc (A source which has results for it)
Now click on a image to open the image viewer
After that right click on the `watashi_ga_suki_nara_"suki"_tte_itte!` tag to open it in a new tab
You now see that only `watashi_ga_suki_nara_` has gone to the new tab and that the part after the `"` is missing

**Expected behavior**

Have the whole tag in the new tab instead of only a part of the tag

**System information**

Windows 10 with nightly version 430464b4

**Comment by Bionus** [comment]
Indeed, since the tags are shown as HTML links, it resulted in this:
```html
<a href="watashi_ga_suki_nara_"suki"_tte_itte!">watashi_ga_suki_nara_"suki"_tte_itte!</a>
```

And as GitHub syntax highlighter shows, the middle part breaks. I updated the code to properly encode it:
```html
<a href="watashi_ga_suki_nara_%22suki%22_tte_itte!">watashi_ga_suki_nara_"suki"_tte_itte!</a>
```
