### ISSUE TITLE
Sankaku Annoying Downloads 

### ISSUE THREAD

**Issue by baraa272** [Bionus/imgbrd-grabber#1515]
**Bug description**

downloads from chan sankaku are annoying 
1. Very slow (i mean 50kb from 6MB download speed ) 
2. stopping for while  and then resume after some time 
3. grabber cant determine images count from this site (20 image from ((?)))
I tried changing user agent / tried using VPN / tried logging in (i filled my username and password and test and it gave me SUCCESS is there anything i'm missing ?)
I cant use any other program because grabber have that best tool to generate tags files and i cant detach that lol
any help ?

**Comment by Bionus** [comment]
> Very slow (i mean 50kb from 6MB download speed)

That's part of Sankaku server limitations, to prevent users from mass downloading.

> stopping for while and then resume after some time

When Sankaku detects that you download too much, it will block you for a few minutes, and only return HTTP 429 errors. Grabber detects this and pauses downloads for (IIRC) 3 minutes.

To prevent this, you should put a sensible delay between each download in Sankaku's source settings, I think 1s between images and 3s between pages is enough.

Also, make sure to use only one concurrent downloads.

> grabber cant determine images count from this site (20 image from ((?)))

On which search? Sankaku doesn't usually provide image count information, but Grabber usually at least detects the maximum image count. Can you give an example of search that return "from ?"?

>  I tried changing user agent / tried using VPN / tried logging in (i filled my username and password and test and it gave me SUCCESS is there anything i'm missing ?)

If your login said "success" you didn't miss anything and you logged in properly. But whatever you do, Sankaku will ban your IP for a few minutes and be purposely slow to prevent users from batch downloading its images.

**Comment by MrAndre96** [comment]
@Bionus I think that he meant with the image count that it for example sometimes gives results while the count on grabber and on their own site says 0. A good example could be bunny_ear which has a count of 0 since the official tag sankaku uses is bunny_ears
