### ISSUE TITLE
Konachan tags list issue

### ISSUE THREAD

**Issue by CharonM72** [Bionus/imgbrd-grabber#1517]
**Bug description**

The Konachan website appears to have an issue, where loading the paginated tags list xml document (http://konachan.com/tag.xml?page=1) loads the same page each time. This puts Grabber into an infinite loop, since appending any number to the page will load the same page.

**Steps to reproduce**

1. Open tags loader
2. Choose Konachan
3. Run it
4. Die of old age
1. Open http://konachan.com/tag.xml?page=1 in a web browser
2. Open http://konachan.com/tag.xml?page=20
3. Open http://konachan.com/tag.xml?page=999999999999
4. Cry

Konachan does have a tags list that you can access at http://konachan.com/tag?page=1. It's not an xml, but it does correctly load the tags list. For some reason their xml is broken.

**Comment by Bionus** [comment]
What's interesting is that while the `page` parameter doesn't work, the `limit` parameter does, and setting it to `0` dumps the whole tag list in one single call.

Another strange thing is that the tag listing works for yande.re, which also runs Moebooru.

I'll try to investigate further.
