### ISSUE TITLE
Gelbooru tags list issue

### ISSUE THREAD

**Issue by CharonM72** [Bionus/imgbrd-grabber#1519]
**Bug description**

Grabber downloads image tags from Gelbooru one tag at a time, which takes an incredibly long time to complete. Note that in the progress bar it indicates that it pulls 50 at a time, which is not correct, as the log shows it pulling one at a time (to be sure, I waited until the progress bar indicated over 503,350 tags downloaded, as that is more than the number of tags on Gelbooru, which as of writing is about 503,320).

**Steps to reproduce**

1. Open tag loader
2. Choose Gelbooru
3. Run it
4. Die of old age

**Explanation**

Grabber pulls Gelbooru tags from Gelbooru using the url format https://gelbooru.com/index.php?page=tags&s=list&pid=1. However, the pid here indicates the tag number, not the page number. Grabber increments this by 1 each time it pulls tags. Furthermore, this takes much longer than most other sites anyway because each time it has to load the full page. As Gelbooru has over 500,000 tags, and Grabber only pulls about 2 per second, it will take Grabber about 70 hours to finish pulling every tag. The solution here would be to pull all the tags from the page, increment the pid by 50, and pull all the tags again, as the progress bar suggests is happening.

**Comment by Bionus** [comment]
> Grabber pulls Gelbooru tags from Gelbooru using the url format https://gelbooru.com/index.php?page=tags&s=list&pid=1. However, the pid here indicates the tag number, not the page number. Grabber increments this by 1 each time it pulls tags. 

Indeed, it should start at 0 and go by 50 increments, instead of the current start at 1 and 1 increments. I pushed a fix, thanks! 😄
