### ISSUE TITLE
Crash While Trying to Batch Download Multiple Single Images

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1520]
**Steps to reproduce**

Initiate a batch download with multiple single images.

**Context**

* No errors in logs.
* 3 crash dumps and settings: [Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/2639688/Grabber.zip)

**System information**

- OS: Windows 10
- Grabber version: Latest Nightly

**Additional context**

- Once it crashes with a particular batch of images, it will always crash with them. 
- Even if those images are downloaded through the browser, it will still crash on the batch. 
- It does not always happen.

**Comment by Bionus** [comment]
> Once it crashes with a particular batch of images, it will always crash with them.

Can you share the IGL file of those images that reproduce said crash?

> It does not always happen.

?

**Comment by brazenvoid** [comment]
I cleaned out the igl mistakenly... sorry. The images were from lolicept - rule.xxx, The queue also had images from the same artist from gelbooru but I was trying to download these at the bottom. There were also batch downloads from the same author in the tag batch queue from different sources. 

For the second, it worked fine in the same session for other images before them. Only did it get stuck on the crash state after encountering them.
