### ISSUE TITLE
Hotkey Manager

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1522]
A separate panel in Options to host a hotkey manager so users can set keys as they want. This can be enhanced with multitude of actions which don't even have a hotkey set. 

The idea came to me because I have a gaming mouse with lots of buttons which are really useless for grabber but can be made a boon.

**Comment by Bionus** [comment]
Indeed, that sound like a good idea!
I have to see how hard is it to do in practice however, and which actions could possible be hotkey-able.

Do you have any particular actions in mind?

**Comment by brazenvoid** [comment]
I guess as a start point, just add all the current independent actions in different menus as hotkey actions. Later actions which have buttons like Get Page / Get All can also be added. And perhaps actions like "close all search tabs" or "close tabs on the right" a'la' browser.

**Comment by brazenvoid** [comment]
I don't remember my initial expectations from this feature. But its easy to imagine the potential.

**Comment by Bionus** [comment]
Superseded by issue #2286.
