### ISSUE TITLE
Hypnohub support

### ISSUE THREAD

**Issue by DonaldTsang** [Bionus/imgbrd-grabber#1525]
For hypnohub.net it uses https://code.acr.moe/kazari/myimouto-untouched (a Moebooru PHP clone)

**Comment by cameron79** [comment]
This site works, maybe you are using an old version.

**Comment by DonaldTsang** [comment]
@cameron79 might need a guide on how to set custom websites with known APIs/Servers like Danbooru,  Gelbooru and Moebooru.

**Comment by cameron79** [comment]
Click at "sources" (bottom bar left). Then click "add".

**Comment by DonaldTsang** [comment]
@cameron79 holding this until holiday is over and I can test it

**Comment by Bionus** [comment]
Indeed, as stated above, this source (as well as all other with Danbooru-like APIs) is already supported.

The documentation for adding sources can be found here:
https://bionus.github.io/imgbrd-grabber/docs/sites/
