### ISSUE TITLE
Feature request: Download the batch download futher when you accidentally closed it or relaunch grabber

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1529]
**Is your feature request related to a problem? Please describe**

When you now close the batch download window as far as I know it is impossible to reopen it when you double click on it etc.

**Describe the solution you'd like**

When you double click on it again I would like to reopen the batch download so you can go on from where you left off. I would also like that this is possible when you save the previous session and launch it again. (Since it is already storing your download list maybe it is also possible to store where you was in the batch download)

**Comment by MrAndre96** [comment]
@Bionus When I try the last update it doesn't appear to work? When I close the window and click on 'Download selected' or 'Download' it will just start from the beginning without asking a question to continue

**Comment by Bionus** [comment]
Ah indeed I forgot to push a few commits, my bad. I just pushed them 👍

**Comment by MrAndre96** [comment]
@Bionus Could you maybe look at the build? Think that some tests probably broke or something

**Comment by Bionus** [comment]
Indeed seems like there was an issue with some test's compilation.
Just fixed it, and nightly has been updated.

**Comment by MrAndre96** [comment]
@Bionus It seems that it will say that it start with image x but actually it start with the first image when I tested

**Comment by Bionus** [comment]
It will start at the first non-completed page, but start from the first image of that page (that's a planned improvement to automatically skip those too).

So if you have 200 images per page, you need to download at least 200 images to test this feature.

**Comment by MrAndre96** [comment]
@Bionus Ah I see when it goes to the next page (which seems to be by grabber at default 500) it will go to the next set of images at startup. The miscommunication arises with the count at the left [https://i.imgur.com/BICdqMU.png](https://i.imgur.com/BICdqMU.png) (In this image you see that I started with 532 while it was actually 500). Which will say that it is futher than it actually is. Which is also why I asked this question

**Comment by MrAndre96** [comment]
Seems like I wasn't able to read yesterday about the planned futher improvement...
