### ISSUE TITLE
Restore Session Resets Page No

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1531]
**Bug description**

The recent nightlies can't resume exactly from the page, a tab was left at in the previous session. All tabs get reset to page 1.

**Steps to reproduce**

1. Set Grabber to resume session on startup.
2. Open a tab and search anything. 
3. Go to any page other than the first one.
4. Restart Grabber.
5. All tabs are now reset to page 1.

**Expected behavior**

Grabber resumes the session as it was left when it closed including the page number the tabs were at.

**System information**

- OS: Windows 10 x64
- Grabber version: Nightly c09580fb

**Comment by Bionus** [comment]
I can't seem to reproduce this?

I just tried searching something, closing then re-opening Grabber, and the tab was at the correct page. Does this happen 100% of the time on all sources? 🤔

**Comment by brazenvoid** [comment]
@Bionus yes, it happens all the time regardless of source selected.

**Comment by brazenvoid** [comment]
Somehow got fixed today...
