### ISSUE TITLE
way to seperate Same sex images only or Hetero only

### ISSUE THREAD

**Issue by chrisrlink** [Bionus/imgbrd-grabber#1533]
**Is your feature request related to a problem? Please describe**
no
this is for preference only cause of people's orientation/preference 
**Describe the solution you'd like**
maybe a Radio button(s) left unaltered downloads both 
depending on selection it will automatically add the required tags to filter between straight/gay maybe go even further and do les also 

**Describe alternatives you've considered**

**Additional context**

**Comment by brazenvoid** [comment]
@chrisrlink Perhaps it can be done for some sources but not all have this function. 

Like I hate gay stuff, so I have all the tags leading to it like yaoi and male-focus in blacklist.

**Comment by Bionus** [comment]
Indeed, as stated, depending on the sources that might not be possible.
So I also suggest to use a blacklist if you want to remove gay or hetero images from the results.

If what you want is to **separate** them however, there's a few ways you can do that:
* With a conditional filename, using the tags you want as condition
* With custom tokens, such as `%gay%`, containing all the tags you want, then use them in a filaneme conditional as such: `<-%gay% folder_for_gay_pictures/>%md5%.%ext`
