### ISSUE TITLE
Add an image / Add group dialogs fields/buttons order

### ISSUE THREAD

**Issue by Pernat1y** [Bionus/imgbrd-grabber#1536]
**Is your feature request related to a problem? Please describe**
When I am clicking <tab> button in 'Add an image' / 'Add group' dialogs, fields and buttons order seems a bit inconsistent.

**Describe the solution you'd like**
Rearrange indexes of elements on form.

**Additional context**
Here is current fields and buttons order to make it more clear:
![grabber_fields_and_button_orders](https://user-images.githubusercontent.com/29379145/50345696-ab320400-0538-11e9-9e57-52db45b2b35f.png)

**Comment by Bionus** [comment]
Indeed 👍 

That comes from the fact that those two fields are added programmatically, while the others are made using Qt Designer. I'll see what I can do and try to have them all in the right order for both windows.
