### ISSUE TITLE
Grabber doesn't apply download intervals

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1539]
**Bug description**

Sankaku complex is an annoying one... So i tried to set some delay and less download at a time. And, grabber seems to still make a lot of request at the same time.

**Steps to reproduce**

1. Go to "source"
2. Click on option form idol.sankakucomplex.com
3. Go to "Download" then apply a delay, like 10s for me.
4. Look at the log on any requestion (for exemple : cosplay)

> [13:06:13.120][Info] Loading image from `https://is.sankakucomplex.com/data/7d/6b/7d6bc85a7d76aefa6ef002637bef2981.webm?e=1545739452&m=iYi5w2dihhSMc0tSowEYYg` 10
> 
> [13:06:13.125][Info] File already exists: `E:\Avatars\photo\idol.sankakucomplex.com\public\anon\misc\unknown\anon - explicit - 664136 - 8b98256eb92b8595bb6c195ed1ad98c8.webm`
> 
> [13:06:13.139][Info] Loading image from `https://is.sankakucomplex.com/data/63/4b/634b334c68bbb93605d3164f89809bbf.webm?e=1545739462&m=MEAtC43VHnIGnGSdKiMWsg` 10
> 
> [13:06:13.144][Info] File already exists: `E:\Avatars\photo\idol.sankakucomplex.com\public\anon\misc\unknown\anon - explicit - 666737 - 575918f72cee1a0b2ce3d90266d852c3.webm`
> 
> [13:06:13.157][Info] Loading image from `https://is.sankakucomplex.com/data/04/7f/047f511866b118de4ee9e358f523736f.webm?e=1545739462&m=0CcBK5Y9AEbEXt93ZbB3Ew` 10
> 
> [13:06:13.195][Info] Details limit reached (429). New try.
> [13:06:13.227][Info] Details limit reached (429). New try.

**Expected behavior**

Since I tell grabber to wait 10s between "image", it should only try one image, then wait "10s" before try the next on.

**Context**

* Provide your `main.log` file to see if any obvious error occured.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/2707248/main.log)
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/2707258/settings.ini.txt)

**Screenshots**

main window : https://i.imgur.com/hSww3CT.jpg
Site options : https://i.imgur.com/Fg3MFB0.jpg

**System information**

- OS: Windows 10
- Grabber version: 6.0.6

**Comment by zearmhot** [comment]
Set global max downloads to 1. The individual site one doesn't work at all for me.

**Comment by yami-no-tusbas** [comment]
Seems fixed in the lastest release !
