### ISSUE TITLE
Customizing %model% like other tags.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1541]
**Is your feature request related to a problem? Please describe**

When downloading from http://behoimi.org I noticed a strange issue, the %model% work fine, even with filter on it. But, when there is more than "one" model on the picture, the programe set it to "multiple". I looked into the "tools -> options -> Save -> "tags" " and.... there is no "Model tags" for modifiying the settings like for "character tags", "species tags", etc... 

One of the concerned image : http://behoimi.org/post/show/99443/
The name pattern : photo\%websitename%\%model:sort%\%copyright:sort%\%character:sort%\%model:sort% - %rating% - %id% - %md5%.%ext%
The problem in short : %Model% is replaced by "multiple" when there is more than one, we can't modifiy it.

**Describe the solution you'd like**

Can it be implemented like other tags ? with the "if empty, separator, if more than, etc..." ?

**Describe alternatives you've considered**

For the moment none, I didn't expected this behavior for the program.

**Comment by Bionus** [comment]
Yes, there's no issue with adding a settings page for this tag type. 👍 

In the meantime, you can directly edit your `settings.ini` file, and add the following keys:
```
model_empty=unknown
model_sort=original
model_useall=true
model_multiple=keepAll
model_multiple_limit=1
model_multiple_keepN=1
model_multiple_keepNThenAdd_keep=1
model_multiple_keepNThenAdd_add=" (+ %count%)"
model_sep=+
model_value=multiple models
```

_(edit with what you want to use, you can check the copyright/character/artist/etc. values as reference)_

**Comment by yami-no-tusbas** [comment]
It's working fine, could this mean that I could use this trick for the "Photo_Set" tag too ? like %photo_set% and it will work fine ?

**Comment by GlassedSilver** [comment]
> It's working fine, could this mean that I could use this trick for the "Photo_Set" tag too ? like %photo_set% and it will work fine ?

I'd love to know that as well!

**Comment by Bionus** [comment]
> It's working fine, could this mean that I could use this trick for the "Photo_Set" tag too ? like %photo_set% and it will work fine ?

Not currently, as adding new tokens require an update of the program. I'll try to add `%photo_set%` in the next version though (and after this, yes this trick will work) :+1:
