### ISSUE TITLE
ID paging not working during batch downloads

### ISSUE THREAD

**Issue by zearmhot** [Bionus/imgbrd-grabber#1542]
**Bug description**

Sankaku won't go past 1000 images on nightly build

**Steps to reproduce**

1. Fresh download of Nightly, deleting everything in appdata to ensure defaults
2. Sign in to Sankaku, test says "successful"
3. Try to grab something with 1000+ images (In this case, 2000 images)
4. Downloads first 1000 images, then sits there forever while trying to populate the next 1000 images.
5. Even setting packing_enable=false still produces this issue, it will grab 20 at a time until ~1000 then stop.

**Expected behavior**

Download all images

-------------------------------

Did this same setup on non-nightly (deleting appdata again for default settings), and this does not happen, however the 2nd page seems tends to grab ~20 images, then skip 4 image in a row, and repeats this pattern forever.

**Comment by zearmhot** [comment]
Bionus, you should take a look at this Sankaku downloader. It uses the beta version of the site and somehow does not have any problems, nor does it need any delays. I ripped 2000 images from Sankaku in about an hour with it. Maybe you can look at the code and figure out how to implement something like that in grabber?

https://github.com/CryShana/Sankaku-Channel-Downloader

**Comment by MrAndre96** [comment]
Well it is indeed still using the html API instead if the json API. There is already some code for it but it hasn't been completed. Things such as image count, page count and tag category's are all broken in it.

**Comment by Bionus** [comment]
> Well it is indeed still using the html API instead if the json API. There is already some code for it but it hasn't been completed

It's pretty much complete for a while, as long as you enable the JSON API in the source settings.

> Things such as image count, page count [...] are all broken in it

Those things are not provided by the API, it only returns the image list.

**Comment by MrAndre96** [comment]
@Bionus is there maybe a way between those 2 possible? with the html API for searching and the json API for batch downloading if it is true that it less likely block batch downloading with the new API.

**Comment by Bionus** [comment]
That's what this setting does:

![image](https://user-images.githubusercontent.com/882719/51078898-5871e500-16bd-11e9-9586-187ae9d44d7f.png)

It loads the images from the top-most enabled API, and the details (tags on the left, page numbers, etc.) from the Regex API.

However, that means two HTTP calls to the server for every "browsing" (not batch downloads) search, so I don't know how the extreme limits on Sankaku would react.
