### ISSUE TITLE
Sankaku - skips 4 images at first page

### ISSUE THREAD

**Issue by cameron79** [Bionus/imgbrd-grabber#1543]
**Bug description**

Sankaku shows 4 popular items at the top. These get skipped by grabber at `page-api.cpp:340`. But if you add something like `order:quality` to the query, Sankaku wont show these 4 images.
Thus 4 actual results get skipped. 

**Steps to reproduce**

1. Search for any tag using only sankaku as source.
2. Add `order:quality` to the query.
4. Note that only 16 insetad of 20 images get displayed.

**System information**

- Grabber version: 6.0.6

Maybe instead of telling Grabber how many items to skip, via `ignore/1`, we should tell it how many items are expected.

**Comment by zearmhot** [comment]
Grabber is currently a mess for Sankaku, I tried for days to get it to work right. I suggest using this program until Bionus can get around to using the Sankaku beta API. https://github.com/CryShana/Sankaku-Channel-Downloader/releases

Since it uses the new API, I was able to rip 20,000 images in less than an hour using it. The only downside is that program offers little customization, so we're stuck with basic MD5 filenames.

For best results:
- Launch Sankaku Channel Downloader
- Sign in
- Rip the tags you want using %md5%.%ext% filenames
- Launch Grabber
- Rip everything but Sankaku using the same %md%.%ext% into the same directory as above (it will skip dupes)
- Profit

**Comment by MrAndre96** [comment]
It doesn't skip any images. Those 4 images are the first 4 on the html page which are the most popular of that tag you are searching. So those images will come back at a later page.

**Comment by Bionus** [comment]
> Adding m_images.size() > m_imagesPerPage seems to fix it.

Indeed, this could fix it (taking the last X images of the page, or some other kind of test), however, some sources (namely Shimmie) return a non-fixed number of results, so putting this might break those.

I'll see what can be done 👍
Maybe simply switching to the JSON v2 API might fix this as said in other issues.

**Comment by Cellane** [comment]
I see there was a recent activity regarding this issue, I just wanted to ask: will the proposed fix also address an issue where mass downloading of a tag with many results (> 50 pages of results) ends up not downloading all the files, instead Grabber reports many of the files as "already downloaded" (as if there were duplicate search results, which should be impossible), and that's despite using a MD5 hash for a image file name (thus no collision/duplication should occur)?

If not, I can report that as an separate issue, but it sounds awfully similar to this one.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Cellane** [comment]
Seems to work like a charm, thank you!

**Comment by Cellane** [comment]
One issue that I seem to be having (although it might just be mistake in configuring somehow) with the latest build from the `develop` branch is the inability to mass-download more than 1000 pictures per tag. When browsing the tag and setting the page number to 49, then navigating to pages 50 and 51, everything seems fine, I can see images, I can download them.

However, if I start a download on page 49 and request 60 images (= pages 49, 50 and 51), I can see following warning in the log tab:

```
[23:14:34.424][Warning] [idol.sankakucomplex.com][Html] You need valid previous page information to browse that far
[23:14:34.426][Warning] [idol.sankakucomplex.com] No valid source of the site returned result.
```

This, despite being only a warning, prevents the mass-downloader from proceeding.

By the way, I have a valid of credentials for the Sankaku site in the Sources menu.

**Comment by Cellane** [comment]
@Bionus Apologies for the ping, I was just wondering if you might have any insight about the behaviour described above, if I should submit it as a separate ticket or if you need more information regarding the described issue?

**Comment by MrAndre96** [comment]
@Cellane sankaku has the 4 most populair images for the seached tag above each page. So previously it was implemented that it would skip the first 4 images, but in the case above with order:quality it doesn't have those populair images first so it would now skip those images.

**Comment by Cellane** [comment]
@MrAndre96 I believe the version I compiled from source addressed the “4 popular images per page” issue, as I was able to download results up to page 50 (= 1000 results) without problems nor duplicates. It’s just my download job goes beyond 1000 results, things stop working completely.

**Comment by MrAndre96** [comment]
@Cellane that should be related to this issue here: #1542 for which there is a patch out in the nighly version

**Comment by Cellane** [comment]
@MrAndre96 Ah, I missed that issue! Thanks, let me try that!
