### ISSUE TITLE
Showing The Open Favorite

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1547]
**Is your feature request related to a problem? Please describe**

Currently there is no indication as to which favorite is open in the Favorites tab. If a user opens more search tabs or skips to others or simply comes back to Grabber after some time, there is a strong chance that he will forget the opened favorite. There is no way of knowing which is open unless one opens the link to the source site. 

**Describe the solution you'd like**

Either display the opened favorite in the tab name like "Favorite - [Open Favorite Tags]" or some other way as you see fit.

**Describe alternatives you've considered**

Perhaps a line can be added to the search view of the favorite, showing the searched tags. Still the tab name is much better as user can see it with a glance to the tab list.

**Comment by Bionus** [comment]
Indeed, it could be shown in the tab title and/or the results listing 👍
