### ISSUE TITLE
Saving in 2 different folders based on a condition?

### ISSUE THREAD

**Issue by MemeTroubadour** [Bionus/imgbrd-grabber#1549]
Hello and thank you for your work.

My current filename setting is this : 
`%rating%/%artist%/%copyright%.%character%.%md5%.%ext%`
But instead of having a folder for each of the three possible ratings, I'd like to pool q and e together in one folder. I assume I'd have to use conditionals, but the wiki section on them is somewhat confusing. How can I do this ?

**Comment by Bionus** [comment]
Hello

In this situation, you should use conditional filenames. As a condition, you can use the rating you want to use, and associate it with a different filename from the default. You can use the `rating:...` syntax in the condition. I can't remember however if putting multiple tags in there means "AND" or "OR" (and don't have testing means ATM).

You can also use the `<...>` conditionals syntax, but to be honest it's a pain to use, so I wouldn't advice it.

**Comment by MemeTroubadour** [comment]
Ah, but if I shouldn't use `<...>`, then what syntax should I be using ? 

Thank you.
