### ISSUE TITLE
Downloading pictures in reverse order?

### ISSUE THREAD

**Issue by Latias4Ever** [Bionus/imgbrd-grabber#1561]
Is there any way to download a tag's pictures in reverse order, i.e. the last picture being downloaded first, and the first picture downloaded last? I wanted to download my favourites from one site and keep them in their current order, but because I download the first pictures first I can't sort by Last Created without any future downloads being put at the bottom.

**Comment by Chiaki** [comment]
I'd highly request this feature too! But in my case I want to save\transfer whole *booru with correct post order.
