### ISSUE TITLE
grabber.exe-system error

### ISSUE THREAD

**Issue by sinkiller21st** [Bionus/imgbrd-grabber#1567]
every time I try to install it it says the code execution cannot proceed because MSVCP140.dll was not found

id try to reinstall it 30 times with no progress 

i use windows 10 on pc 
![capture](https://user-images.githubusercontent.com/39547304/51258453-0ad4d100-1978-11e9-92b6-7327a3808053.PNG)

**Comment by sinkiller21st** [comment]
how do I go about fixing this

**Comment by sinkiller21st** [comment]
yes 6.0.6

**Comment by sinkiller21st** [comment]
It say I need MSVCP140.dll what is that and how do I install it properly

**Comment by Bionus** [comment]
Have you tried installing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) first?

**Comment by sinkiller21st** [comment]
do I need to uninstall these 
![untitled](https://user-images.githubusercontent.com/39547304/51292052-769a5680-19d7-11e9-8e5e-454339c8313f.png)

**Comment by sinkiller21st** [comment]
thank you i think i fixed it :) it was hard but i did it
