### ISSUE TITLE
When you click on a suggestion for the correct tag name it will take away '-' by the other tags

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1573]
**Bug description**

When you have for example typed a tag wrong and used '-' with a other tag it will remove the '-' when you click on the correction

**Steps to reproduce**

Search for example 'kimi_no_tonari_de_koishiteru' with the tag  -rating:questionable'
Now you get 'Maybe you meant: kimi_no_tonari_de_koishiteru!' and click on it
Now you see that the '-' is removed from '-rating:questionable'

**Expected behavior**

Not remove the '-' when you correct the tag

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Indeed, good catch 👍

This made me realize how slow this auto-correct is too...
