### ISSUE TITLE
Not saving correctly when using %search% in the filename

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1575]
**Bug description**

When you press save it will now make a folder like this: 'https chan.sankakucomplex.com post index page=1&tags=kimi no tonari de koishiteru!&login=' and when you press 'save as' you will get part of the md5 but not all of it anymore

**Steps to reproduce**

Search a image and try 'save' or 'save as'

**Expected behavior**

Save it correctly

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
What's your filename? `%md5%.%ext%` works fine on my end.

Also, I take that you're trying this on Sankaku?

**Comment by MrAndre96** [comment]
@Bionus mine is %search_1%/%copyright%/%character%/%md5%.%ext%

**Comment by Bionus** [comment]
Yeah that's `%search%` which is broken on restore
