### ISSUE TITLE
[Request] Better Notification when none of the results pass the filters

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1576]
**Is your feature request related to a problem? Please describe**

Currently when no results pass through filters, grabber always sticks the "Possible reasons: too many tags" line under no results. Even if the source site allows near infinity tags or even if the page is not even the last one...

Frankly that reason is misleading in all but one case that is, a new search is performed and the source indeed limits tags. At least the sources I use don't put small limits on tags (Gelbooru and rule34.xxx), I have experimented with nearly 50 tags with them...

**Describe the solution you'd like**

Limit this line to only new searches. Make a better string which leads to a definite conclusion that the applied post filters and blacklisted tags did not produce any results for this page.

**Comment by Bionus** [comment]
Indeed, I think that most "possible reasons" are now totally outdated, and should be updated to factor for the more recent additions such as post-filters and blacklist.

Also, maybe simply showing the number of filtered images (with a way to show them), as suggested in another issue, could also naturally solve this.

**Comment by brazenvoid** [comment]
@Bionus Can you also make it so that the page counter does not hide it self for this reason?
