### ISSUE TITLE
Mass Add Favorites

### ISSUE THREAD

**Issue by AkatsukiiDesu** [Bionus/imgbrd-grabber#1577]
**Is your feature request related to a problem? Please describe**
My favorites somehow got deleted. I was wondering if there was a way we can edit the favorites.json file to mass add them back in?

My favorites somehow got deleted. I was wondering if there was a way we can edit the favorites.json file to mass add them back in?

If not, I can happily add them back in manually.

**Comment by Bionus** [comment]
Hello

Yes, there's no issue with editing the `favorites.json` file yourself, just make sure to have Grabber closed when you do so to avoid having it overwrite your changes. There's however no existing tool to for example give Grabber a list of tags and have it add it to your list automatically.

Here's an example file contents:
```json
{
    "favorites": [
        {
            "lastViewed": "2019-01-31T01:01:01",
            "monitors": [],
            "note": 50,
            "tag": "some_tag"
        },
        {
            "lastViewed": "2019-01-31T01:01:01",
            "monitors": [],
            "note": 90,
            "tag": "another_tag"
        }
    ]
}
```

Where `note` is a number from 1-100 used for sorting favorites by preference, and `tag` the favorite itself.

If you have something like `tag1 tag2 tag3` and want to generate the JSON equivalent above, you can open it in some text editor and replace ` ` (space) by `" }, { "lastViewed": "2019-01-31T01:01:01", "monitors": [], "note": 50, "tag": "`.
