### ISSUE TITLE
e621 doesn't work

### ISSUE THREAD

**Issue by RusFurLover** [Bionus/imgbrd-grabber#1578]
**e621 doesn't work**

Good morning/afternoon/evening. My friend suggested me to use Grabber to download pictures faster. I liked it so much! As I firstly launched the program e621 was working good. I could've saw all the pictures and all... But next day I started Grabber again and now the programm can't see the images. Exactly e621. Other websites are working. The page is absolutely clear. Could you help me, please?

P.S. Sorry if my english is bad.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/2817579/main.log)

**Screenshots**

![1215](https://user-images.githubusercontent.com/47216900/52060158-b0915e00-257c-11e9-9014-0a580739e968.jpg)

**System information**

- OS: e.g. Windows 7
- Grabber version: 6.0.6

**Comment by RusFurLover** [comment]
> 
> 
> **e621 doesn't work**
> 
> Good morning/afternoon/evening. My friend suggested me to use Grabber to download pictures faster. I liked it so much! As I firstly launched the program e621 was working good. I could've saw all the pictures and all... But next day I started Grabber again and now the programm can't see the images. Exactly e621. Other websites are working. The page is absolutely clear. Could you help me, please?
> 
> P.S. Sorry if my english is bad.
> 
> **Context**
> 
> [main.log](https://github.com/Bionus/imgbrd-grabber/files/2817579/main.log)
> 
> **Screenshots**
> 
> ![1215](https://user-images.githubusercontent.com/47216900/52060158-b0915e00-257c-11e9-9014-0a580739e968.jpg)
> 
> **System information**
> 
>     * OS: e.g. Windows 7
> 
>     * Grabber version: 6.0.6

**Comment by Bionus** [comment]
You're getting HTTP 403 responses, could it have been a temporary thing?
Like a temporary ban of your IP from e621's servers?

If you try to access e621 with a browser (Chrome, Firefox, or any other) directly after Grabber showing the error, does it work?

Because the URLs in your log are working fine from my location.

**Comment by RusFurLover** [comment]
My computer's IP isn't banned. I tryied to connect to e621 (right now) by using Firefox and it worked correctly. All's good. 

Earlier i used to use VPN to connect to e621. But now I have clear access to it. I don't use any program and the site is working.

**Comment by RusFurLover** [comment]
Maybe it makes more sense to try to use Proxy (the one that is already in the program)? But I do not know how to use it correctly. If you tell me how to use, I might try. If it won't work I don't know what to do. Maybe next version would work better on my computer.

**Comment by nlboom** [comment]
Hi, I have same issue.
[main7676.log](https://github.com/Bionus/imgbrd-grabber/files/2824538/main7676.log)

**Comment by RusFurLover** [comment]
Hello again. So, I tried to use Proxy to enter "e621" but it still doesn't work. I asked my friend to download your program but even he said that "e621" isn't working. 

I tried different program. Without Proxy I couldn't enter "e621" too but when I used Proxy there it was working. But the main and the biggest minus is that the program can't download the images properly. But your can! So, I really hope you could help me with my issue. I liked your Grabber so much.

**Comment by RusFurLover** [comment]
Good evening.

Now I understood that the program doesn't work in Russia. I tried to find working Proxy IP but no one was working. But now I found it. Thank you a lot for your attention and your program! It's really helpful.

P.S. I will leave working IP here:

Хост (Host): 186.147.237.100
Порт (Port): 56459
