### ISSUE TITLE
Current Search Tab Button Placement Issues On Change of Page

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1580]
I guess, this is perhaps the oldest bug in Grabber and I don't know why anyone has not reported it yet. The cases below will reference a tab named "**Search**".

### Error Scenario

- **Scenario:** The Search tab button is surrounded by tabs and there are some tabs which are not shown but are present on the left side as well. 
- **Action:** The page is changed through the next page button. 
- **Result:** The tab button moves to the right most position.

The issue with this is that viewing multiple search pages along side becomes a chore to reposition the tab navigation bar and opening them rather than just clicking to opening them. The more tabs, the worst the experience.

![error case](https://user-images.githubusercontent.com/8722533/52273102-91bf0d00-296a-11e9-8453-3188963bc3b4.gif)

### Debatable Scenario

- **Scenario:** The Search tab button is shown partially or not at all on the tab navigation bar.  
- **Action:** The page is changed through the next page button. 
- **Result:** The tab button comes into view on the right most position.

I think this functionality can be preserved, if the tab is **not visible at all**. Perhaps users will find it annoying to navigate to the current opened tab button when they went around to see what else they have opened. Or this could also be removed as we do have a drop down showing all opened tabs.

![debatable case](https://user-images.githubusercontent.com/8722533/52273633-3d1c9180-296c-11e9-87cc-a315c88c2739.gif)

### Desired Result For The Error Scenario

- **Scenario:** The Search tab button is visible on the navigation bar. 
- **Action:** The page is changed through the next page button. 
- **Result:** The current position of tab navigation bar does not change and the tab button remains where it is.

![correct case](https://user-images.githubusercontent.com/8722533/52273641-44439f80-296c-11e9-94f9-cf211263cf72.gif)

**Comment by Bionus** [comment]
Nice gifs! 😮

Indeed, the "error case" does not make any sense. There must be some code somewhere that forces some "show tab X on the screen" and generates this side effect. Triggering a search should definitely not move the tab bar in any way, especially when the current tab is already visible.

As for the "debatable case" you mention, I believe that the tab should also remain hidden. That's what Firefox and Edge both do (Chrome just shrinks my tabs), and I believe that the content of a tab should not have any impact on its container (here, the tab bar).

I have no idea either how this was never reported / I never noticed, given it's such an obvious bug 🤷‍♂️

**Comment by Bionus** [comment]
Ok, so after some investigation, unfortunately it's half a Qt bug. That is, when setting the tab's title, the tab bar will always have this strange behavior. 😞 

In order to reduce the annoyance, I'll make sure to only set the tab title when it actually changes.

So:
* If clicking "Search" triggers a tab title change (for example if you changed the tags you search), the bug will unfortunately remain
* If you just click "Next page", or "Search" without changing the tags, the tab bar won't move

**Comment by brazenvoid** [comment]
Yes, that's acceptable. 
Though can't the position of tab bar be made a note of and pointed to again once the title is changed? Maybe the quick change will not really be apparent on screen or perhaps the UI update can be forced to execute afterwards.

**Comment by Bionus** [comment]
I also thought about this, but unfortunately, neither [QTabBar](https://doc.qt.io/qt-5/qtabbar.html) nor [QTabWidget](https://doc.qt.io/qt-5/qtabwidget.html) allow this. 😞 

Maybe if I sub-class them there's a way to override this behavior, but that's not guaranteed either.

**Comment by brazenvoid** [comment]
OK, no issues.
