### ISSUE TITLE
Question about filenames

### ISSUE THREAD

**Issue by GoHoo** [Bionus/imgbrd-grabber#1583]
I simply dont understand what am I doing wrong,how can I make this filename structure to work?
**%websitename%/%search%/%copyright%/%artist%/%character%/%filename%-%md5:maxlength=2%.%ext%**
If I delete :maxlength=2% line or instead of md5 add "id" it starts working,but filename structure above gives error saying my filename is not unique.I tried to increase % but to no avail.

**Comment by Mad-onanist** [comment]
> /%filename%-%md5:maxlength=2%.%ext%
Lets see what we got here:

> %filename%: image filename, as stored on the booru’s server.

> %md5%: the file’s MD5 hash. If not returned by the server, it is generated automatically.

1. md5 is the hash sum of the file, so why dont just use it as filename?
2. You can just write tags and the way to the file to the database. You know? 
3. With 
>>%filename%-%md5:maxlength=2%.%ext%
IMHO name will be too long.
Here is typical way from Gelbooru(just for example):
> /images/b3/2c/b32c42b2b71fff4fe519c69b838ca1af.jpg
Filename(which one has same length as md5 and looks like it it md5, will be summed with md5, so in your way here will be: b32c42b2b71fff4fe519c69b838ca1af-b3.jpg

I suppose this:
> %websitename%/%search%/%copyright%/%artist%/%character%/%md5%.%ext%
which one shall return this: b32c42b2b71fff4fe519c69b838ca1af.jpg
Also IMHO you added too much folders(BTW ), i fine with: %copyright%/%character%/%md5%.%ext%

**Comment by Bionus** [comment]
> I simply dont understand what am I doing wrong,how can I make this filename structure to work?
> **%websitename%/%search%/%copyright%/%artist%/%character%/%filename%-%md5:maxlength=2%.%ext%**
> If I delete :maxlength=2% line or instead of md5 add "id" it starts working,but filename structure above gives error saying my filename is not unique.I tried to increase % but to no avail.

First, note that the message is a **warning**, not an error. You're free to ignore it, you might just possibly sometimes have duplicate filenames for your images (except, of course, for websites that use the MD5 as filename, as in that case `%filename%` guarantees an unique filename).

Given that you use `%md5:maxlength=2%`, the risk is even ever, to the point of being negligible. I'd suggest just ignoring Grabber's warning and downloading stuff anyway. 😄 

> If I delete :maxlength=2% line

That would be the full MD5, which guarantees an unique filename, hence the result.

> or instead of md5 add "id" it starts working

The `%website%` + `%id%` pair also guarantees an unique filename, as a website always have a single image by ID (unless that source is seriously broken)
