### ISSUE TITLE
Save Tags Feature request

### ISSUE THREAD

**Issue by DovahDoVolom** [Bionus/imgbrd-grabber#1585]
This i would guess classifies as a feature request, but i would love for there to be a way for all image tags to be saved in windows properties under the tags option. Now this does create alot more work. To my knowledge png files cannot have tags. In order to have this option either it will only tag downloaded jpg images, or convert png images to jpg and apply the tags. As for other mediums like webm, swf, or gif.

**Comment by Mad-onanist** [comment]
You can(right now implemented in the grabber) put tags in DB, you know?

**Comment by brazenvoid** [comment]
This feature has been requested before and conclusion was that because tag support in windows is insufficient currently, thus, it will be implemented once windows allows all related file types to get tagged.

**Comment by DovahDoVolom** [comment]
Put tags in a DB? So if I had SQL it'll match md5's to tags? How would I set that up?

**Comment by Mad-onanist** [comment]
> Put tags in a DB? So if I had SQL it'll match md5's to tags? How would I set that up?
Yes it can write md5 and tags(and even more!) for each downloaded picture into a Data Base.
Here the link to the official manual:

[https://bionus.github.io/imgbrd-grabber/docs/commands/gelbooru.html](https://bionus.github.io/imgbrd-grabber/docs/commands/gelbooru.html)

By this manual you'll create a local Gelbooru(which one contain DB) on your PC, if you have experience with SQL, you can just create your own DB, and add info into it, by following  instruction. 

Manual is for Шindows, but it works well on GNU\Linux(Arch) too.

**Comment by Bionus** [comment]
As stated by @brazenvoid, adding tags in Windows properties was indeed suggested many times, but given only a handful of formats support them, it's very unreliable.

As you suggest, Grabber could try to convert everything to JPG or some other format that support tags, but I don't think that's a good way to go with this, given most wouldn't want to alter their images.

Some solutions:
* As suggested by @Mad-onanist, you can indeed instead use a local booru setup.
* You could also use Hydrus, which works very well with Grabber, and given that TXT files are searchable by Windows, would also work there.
* Or you could also simply use a TXT external text file, store the tags there, and use Windows search, but it would only show the TXT in the results, opening the actual images from there would be a pain.

**Comment by WasabiWarlord75** [comment]
I'd like to preface my suggestion with I know nothing about programming, but perhaps you could find a way to implement https://github.com/Dijji/FileMeta so Grabber can write tags. FileMeta lets you add tags to  all sorts of file types, and I'm using it for my own image collection.

**Comment by Bionus** [comment]
Closing in favor of the most recent #2258

I did not know about https://github.com/Dijji/FileMeta so thanks for the link!
It seems to be exactly what was necessary for this feature. I'll have a try and see if it can be made to work well with Grabber.
