### ISSUE TITLE
Is it here the way to not download file?

### ISSUE THREAD

**Issue by Mad-onanist** [Bionus/imgbrd-grabber#1586]
Is it here the way to don't download file? I mean, i need only tags per hash, right now - tags loading only on download, but when i trying to write to dev/null - no result(may be i do it wrong?).

**Comment by Bionus** [comment]
There isn't in the UI.
However, with the CLI you can dump the results as JSON without actually downloading the images.

If you're using some pre-built version, you can see the options with `-h` (`--help`), and toggle the CLI mode with `-c` (`--cli`).

**Comment by Bionus** [comment]
Seems like it's only on the nightly version, and only on the CLI executable (`Grabber.com` or just `Grabber` since `.com` has precedence over `.exe`).

```
Grabber --json -t "rating:safe" -s "danbooru.donmai.us"
```

**Comment by Mad-onanist** [comment]
Sorry but i'm a n00b in VCS & GITHub, so i got a question again, is nightly == development branch?

**Comment by Bionus** [comment]
Yes it is.

You can download it here:
https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly

**Comment by Mad-onanist** [comment]
Is it same as "imgbrd-grabber-develop.zip"?
I already compilng it.  :0

**Comment by Spark-NF** [comment]
Yes it's the same as building the `develop` branch from that zip (using cmake then make).

If you're building for Linux, you have to use the file in the `cli` folder if you want to use those new CLI features, not the one in the `gui` folder. It's quite annoying but I planned to have those features available in both projects soon.

**Comment by Bionus** [comment]
Yes it's the same as building the `develop` branch from that zip (using cmake then make).

If you're building for Linux, you have to use the file in the `cli` folder if you want to use those new CLI features, not the one in the `gui` folder. It's quite annoying but I planned to have those features available in both projects soon.

**Comment by Mad-onanist** [comment]
Unknown option 'json'.
In nightly, dev, ast, i compiled them all, no any --json.
Maybe that option works only on M$ Windows?

**Comment by Bionus** [comment]
The `--json` option is definitely present for the `cli` project on the `nightly` branch (don't use the `ast` one it's under development and will 100% crash):
https://github.com/Bionus/imgbrd-grabber/blob/develop/cli/src/main.cpp#L83

Just make sure to use `build/cli/Grabber` instead of `build/gui/Grabber`.

**Comment by Mad-onanist** [comment]
> $ sudo ./Grabber --json -d -t "rating:safe"  -s "danbooru.donmai.us"
[18:33:35.221][Info] Temp directory purged of 0/0 files (0 failed)
No valid source found

And looks loke programm halt then. No CPU usage.

**Comment by Bionus** [comment]
You're supposed to run it from the `release` folder, just like the `gui` version.

If you built the project using `build.sh`, copy the file in "build/cli/Grabber-cli" into "release/" and run it from there.

**Comment by Mad-onanist** [comment]
I changed build.sh that it is not reinstalling any files if they already installed
```
sudo pacman -Syu
  sudo pacman --needed -S "qt" "gcc" "cmake" "libpulse"
```
And used it, with sudo(idunno why).
Now, after copyong the file into /release/ - all work. O_O
Thanks!
