### ISSUE TITLE
MSVCP140.dll still missing despite installation of MSVCP

### ISSUE THREAD

**Issue by akirafujioka129** [Bionus/imgbrd-grabber#1590]
**Bug description**

After installing 6.0.6 and attempting to launch it, I'm greeted with the error message, "The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem."

I have already installed and reinstalled Microsoft C++ Redistributable 2013 and 2015, and the problem persists.

**Steps to reproduce**

1.Install Grabber via Grabber_6.0.6.exe
2. Launch Program Files\Grabber\Grabber.exe
3. See error message

**Expected behavior**

I expected the program to launch.

**Context**

I have no main.log in AppData\Local\Bionus\Grabber.
Assuming that by 'settings.ini' you mean 'innosetup.ini,' the contents are as follows:

[general]
language=en

**Screenshots**

<img width="960" alt="msvcp2015" src="https://user-images.githubusercontent.com/47706303/52908208-cb2f2c80-3236-11e9-8800-6ef30d1eb9
<img width="960" alt="msvcp2013" src="https://user-images.githubusercontent.com/47706303/52908209-d1250d80-3236-11e9-83d0-03a88e7288f5.png">
ad.png">

**System information**

- OS: Windows 10
- Grabber version: 6.0.6

**Additional context**

**Comment by Bionus** [comment]
If you're using the official releases, they are (at least for now) x86.

So from what I see you should need to install MSVC 2015 x86. However, the installer should already do that for you so that's strange. :thinking:

**Comment by Mad-onanist** [comment]
> [https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/msvcp140dll-is-missing-in-my-win-10/1c65d6b0-68b8-4b59-b720-3e6a33038389](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/msvcp140dll-is-missing-in-my-win-10/1c65d6b0-68b8-4b59-b720-3e6a33038389)

**Comment by brazenvoid** [comment]
I have installed all of them that are in existence, in both x86 and x64 flavors. Once I was frustrated with a software throwing such errors that I went on war with them...
