### ISSUE TITLE
Loss of mouse navigation 

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1594]
**Bug description**

The latest nightly does not execute search page navigation through mouse, if pointer falls on an image or the container in which an image is housed (in case of grid layout). 

**Steps to reproduce**

1. Search anything
2. Use mouse buttons to navigate while having the pointer on an image
3. Nothing Happens
3. Now move the mouse to white space in between images, any extreme side or corner of the search window and do the same
4. It works as intended

**Expected behavior**

Regardless where I have my mouse in the search area, the mouse navigation must work.

**System information**

- OS: Windows 10
- Grabber version: Nightly

Rant: Here I was excited that you hammered the snobbish tabs' rise to fame through visual engineering issue (haha), only to stumble on an even more wicked scheme... I guess, hell hath no fury, a tab scorned

**Comment by Bionus** [comment]
I guess that by "mouse navigation", you mean the X1 and X2 buttons on the mouse, to do next page / previous page?

**Comment by brazenvoid** [comment]
Yes, exactly

**Comment by brazenvoid** [comment]
Well I got a lot of buttons on my mouse, suffice to say, all should work that way, if assigned the forward/back functions...

**Comment by MrAndre96** [comment]
Yeah this seems to be the case also tried it just myself. Didn't see this bug before since I just used those UI buttons

**Comment by Bionus** [comment]
Yep, it's definitely caused by 04aa7c6047d7b38ccadf0b1f0ebac948132a0773 (fix for issue #1584). :+1:
