### ISSUE TITLE
chan.sankakucomplex.com problem

### ISSUE THREAD

**Issue by esotericer1** [Bionus/imgbrd-grabber#1596]
when I try to download from chan.sankakucomplex.com, it shows results in the search page(but sometimes do not) and the results are added to the download tab, but all it gets are failure images like this 
![35bfbaa1e585618de33a804118d12277 anonymous](https://user-images.githubusercontent.com/46140170/53543248-64c6da00-3b65-11e9-8438-14cc4a2f333c.png)

Also when I enter chan.sankakucomplex it shows no images, only showing just ads and the site banner, etc. 
I'm not sure whether this is because the site is banning my ip forever or temporarily, or whether because I typed in just my id and pw(not the cookies), or simply because the site is down for some reason. If you can help me with this, it would be greatly appreciated.

**Comment by esotericer1** [comment]
also, when downloading from other sites like danbooru or safebooru seems to be ignoring some files. I wonder whether this is because I downloaded too many files earlier(thus they are banning me and I need to try again later) or I lost my internet connection with them.

**Comment by CharonM72** [comment]
That's weird, I have often had that problem with Sankaku (either showing that error image or just not loading the full image at all, only thumbnail) but not with the other sites. Sankaku works most of the time for me though. I did input credentials, the cookie, and my header into the settings so maybe that has to do with it...

**Comment by tg4f34** [comment]
How to solve this problem?
