### ISSUE TITLE
Nightly 2019-03-01 is not launching

### ISSUE THREAD

**Issue by notacompletemoron** [Bionus/imgbrd-grabber#1600]
**Bug description**

Windows 10 1803. Nightly 2019-03-01, not launching. Keeps coming up with "It seems that the application was not properly closed..." Hit Yes or no, never launches. Doesn't matter if I have nightly installed in a separate folder, or I overwrite 6.0.6, it doesn't work.

I understand that nightly is supposed to have issues. I also understand if this ticket gets closed, with no update.

**Steps to reproduce**

1. Install Nightly 2019-03-01. (Into new folder, btw)
2. Try to open
3. Nothing happens
4. Delete existing settings.ini
5. Nightly opens.

**Expected behavior**

A clear and concise window of Grabber functioning.

**Context**

* Provide your `main.log` file to see if any obvious error occured.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/2957734/main.log)
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
[settings.log](https://github.com/Bionus/imgbrd-grabber/files/2957736/settings.log) < - for 6.0.6

**System information**

- OS: Windows 10 1803
- Grabber version: Nightly 2019-03-01

**Comment by notacompletemoron** [comment]
So, nightly doesn't like the syntax, or SOMETHING, in the 6.0.6 settings.ini.

Hmm.

I have attached the settings.ini from the nightly build.
[settings.log](https://github.com/Bionus/imgbrd-grabber/files/2957766/settings.log)

**Comment by Bionus** [comment]
Indeed, it would seem that the new filename parser treats all `\` characters as escape characters unconditionally, which cause your `%search%\%md5%.%ext%` filename to go into some infinite loop for some reason. 🤔 

Until I push a fix, you can re-use your "old" 6.0.6 settings by simply replacing the `\` by `/` in your filenames in `settings.ini`.

**Comment by notacompletemoron** [comment]
Thank you for the amazing work!
