### ISSUE TITLE
Sankaku tags not categorized

### ISSUE THREAD

**Issue by CharonM72** [Bionus/imgbrd-grabber#1601]
I apologize if this has been mentioned before but it has been annoying me for a long time.

**Bug description**

Tags for images from chan.sankakucomplex are not grouped into category, i.e. copyright, character, artist, etc. This then causes the problem of all images downloaded from chan.sankakucomplex.com being named "misc - unknown - anonymous" with the filename setting of "%copyright% - %character% - %artist%", even when the copyright, character, and artist tags are all present. It also makes it a lot harder to quickly find who is the artist or the character in an image, since the color coding doesn't work.

**Steps to reproduce**

1. Open an image from sankaku
2. Look at its tags
3. Cry
4. Download it
5. Look at its filename
6. Continue crying

**Expected behavior**

The tags should be categorized, with proper coloring in Grabber, and proper file naming.

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
- *There  are no errors.*
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
- *Attached: [settings.zip](https://github.com/Bionus/imgbrd-grabber/files/2964621/settings.zip)*
* If the bug occurred during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.
- *N/A*

**Screenshots**

Correct categorization (from anime-pictures.net):
![image](https://user-images.githubusercontent.com/1299220/54329661-f8c68600-45e8-11e9-96ec-d07def3af782.png)
No categorization (from chan.sankakucomplex.com):
![image](https://user-images.githubusercontent.com/1299220/54329784-9fab2200-45e9-11e9-8b27-002966d4aa5f.png)
The same image as above, on sankakucomplex website:
![image](https://user-images.githubusercontent.com/1299220/54329844-d41ede00-45e9-11e9-9046-986d7c079850.png)

**System information**

- OS: Windows 10 x64
- Grabber version: 6.0.6 nightly (01673194) x64, but it happened in all previous versions that I can recall as well

**Comment by Bionus** [comment]
I can't reproduce on my end, and the fact that it has always happened for you makes it even stranger (as I know it works for some users, be it in nightly or 6.0.6).

* Can you provide your `main.log` file? I'd like to have a look at the generated network calls to see what might be the issue.
* Did you provide your credentials to Grabber? (i.e. are you logged in)

**Comment by yami-no-tusbas** [comment]
I maybe got it. In my setting Sankaku (and Idol.sankaku) where on "json" instead of "html" and whell guess what, no a single tag was recognized. (I may have try json to avoid the "too many request" at a time)

**Comment by CharonM72** [comment]
I'm not having any luck getting Sankaku images to load anymore anyway.
