### ISSUE TITLE
Sankaku giving Error 429 (Too many requests)

### ISSUE THREAD

**Issue by makaragamz** [Bionus/imgbrd-grabber#1606]
Grabber sends Sankaku pages too many requests at short time.

It seems that Sankaku itself has a request limit to avoid overloading, but this doesn't help Grabber, so when it sends requests to download the images, Sankaku bot-detector detects the abnormal amounts of requests and just blocks you temporary.

Steps..

1. Simply download full pages from Sankaku servers.
2. Grabber will stop showing Sankaku pictures for a while and won't download them.
3. Open Sankaku on any browser to see the Error 429 message.

System information

- OS: Windows 10
- Grabber version: 6.0.6

Maybe should add some kind of timer to Grabber? also study more in depth how the limit works in Sankaku pages.

**Comment by Bionus** [comment]
> Maybe should add some kind of timer to Grabber? also study more in depth how the limit works in Sankaku pages.

There already is, you can set it up the the source's settings, in the "Download" tab. 😄
