### ISSUE TITLE
Auto Update downloaded the wrong installer

### ISSUE THREAD

**Issue by urzuse7en** [Bionus/imgbrd-grabber#1608]
I use Windows 7 (x86) and when I opened Grabber and tried to apply the latest update it downloaded the x64 version of the installer. It also installed it and replaced all the files, so when I tried to open Grabber it failed.

Only solution was to manually download and install the x86 version.

**Comment by RinMaru** [comment]
yea it keeps asking to update when its already updated

**Comment by Bionus** [comment]
Indeed, it takes the first asset instead of the most relevant.
I'll have a look and push a fix ASAP.

@RinMaru: moved to #1609
