### ISSUE TITLE
In the latest version, Sankaku is crashing

### ISSUE THREAD

**Issue by esotericer1** [Bionus/imgbrd-grabber#1610]
Hello. In the latest version (7.0.1) whenever I try to download from chan.sankaku(I succeeded in logging in at last) the downloader just crashes. I'm wondering if i'm the only one with this issue.

**Comment by MrAndre96** [comment]
It seems that the batch downloader sometimes now doesn't respond when you click away or something at the beginning (for you this might have leaded to a crash)

**Comment by esotericer1** [comment]
> It seems that the batch downloader sometimes now doesn't respond when you click away or something at the beginning (for you this might have leaded to a crash)

Nope. still crashes.

**Comment by Bionus** [comment]
Is this crash related to batch downloads or downloads from the image window?

**Comment by MrAndre96** [comment]
I think that it was opened for the crash of the image window

**Comment by esotericer1** [comment]
Related to both. When I tried downloading from the image window it shows only sankaku complex logo(as in issue #1596), and when I try batch download the program crashes. I tried getting fix #1611 files(by downloading the zip files and overwriting them over previous files), but to no avail. Hoping my inability to download from sankaku ends with the 7.0.2 version...

**Comment by esotericer1** [comment]
Even in the 7.1.0 version the crash is still persistent....
