### ISSUE TITLE
Downloading an Image from Sankaku sometimes crashing Grabber

### ISSUE THREAD

**Issue by xodiack** [Bionus/imgbrd-grabber#1611]
I attached a video since I feel it better shows the steps to reproduce the crash, especially since in my case I get a windows program crash rather than grabber catching itself crashing. This problem popped up after going onto 7.0.1, 7.0.0 seemed to function fine in relation to Sankaku for me and before that I was on an older nightly release for a while.

Also it may be related to #1610 , though I'm unsure whether to add to that issue or start my own.

**Steps to reproduce**

1. Source set to Sankaku/logged in
2. Search desired tags
3. Download via get selected/opening image panel to save/save and close
4. Crash

Alternative where the crash doesn't occur

3.Right click save the image
4.Open the image panel
5.delete/re-download the image as many times as desired
6.get selected/download also now works
7.Delete from saved image from search
8.Now crash when trying to save from image panel

**Context**

Attached mainlog/settings/restore/video of behavior
[CrashReport_03312019.zip](https://github.com/Bionus/imgbrd-grabber/files/3027327/CrashReport_03312019.zip)

**System information**

W7 64bit, Grabber 7.0.1 64bit

**Comment by urzuse7en** [comment]
Same thing happening here too. Windows 7 (x86), 7.0.1 (it also happens in 7.0.0). It can display the picture but can't download, it instantly crashes Grabber.

**Comment by MrAndre96** [comment]
yeah this seems source specific. didn't see this error before since the option 'save as' works normal. so you could now use that option as a workaround

**Comment by FirstDagger** [comment]
Same thing Windows 10 (64bit) 7.0.1 didn't happen in 7.0.0
