### ISSUE TITLE
Every source is showing "No result"

### ISSUE THREAD

**Issue by Alpha-JinRo** [Bionus/imgbrd-grabber#1613]
Every source is not working anymore since the automatic-update.
It shows for every source:
"Source - No result
Possible reasons: server offline
No valid source of the site returned result."

"main" file is attached (I hope)
[main.log](https://github.com/Bionus/imgbrd-grabber/files/3042870/main.log)

- OS: Win 10
- Grabber version: 7.0.1

**Comment by kluknawa235** [comment]
i have same problem. 

OS:windows 7 x64
7.0.1

in grabber 6.0.6 is all fine

[main.log](https://github.com/Bionus/imgbrd-grabber/files/3049779/main.log)

**Comment by JamesBCrazy** [comment]
I'm now receiving results from sources that were previously showing "no result." Try again?

**Comment by Alpha-JinRo** [comment]
@ JamesBCrazy:
Thanks for your answer, but for me the problem is still the same.

I still got "No result" on every source (Danbooru, Gelbooru, Sankaku (chan), even some that I never used and just tested) and I already tried to change the sources settings in different order etc. and look for other settings, too and still don't get results. 

So I don't have any more ideas to solve this problem by my own

**Comment by Bionus** [comment]
Both of your logs show messages such as:

```
[11:54:13.705][Warning] [Qt][qt.network.ssl] QSslSocket: cannot call unresolved function SSLv23_client_method
[11:54:13.705][Warning] [Qt][qt.network.ssl] QSslSocket: cannot call unresolved function SSL_CTX_new
[11:54:13.705][Warning] [Qt][qt.network.ssl] QSslSocket: cannot call unresolved function SSL_library_init
[11:54:13.705][Warning] [Qt][qt.network.ssl] QSslSocket: cannot call unresolved function ERR_get_error
[11:54:13.705][Warning] [Qt][qt.network.ssl] QSslSocket: cannot call unresolved function ERR_get_error
```

Which means the OpenSSL DLL bundled with Grabber seems to have issues.
* Did you install by yourself, or via the auto-update?
* Did you try reinstalling?
* If that does not work, you can also try installing the x86 version and see if it helps

**Comment by kluknawa235** [comment]
for me, is now all working.

I must reinstall OS. Install latest w10 1809 with updates, and grabber 7.0.1 x64 working now.

**Comment by Alpha-JinRo** [comment]
OK I try it.

Back than I have made the "auto-update"
Than I made a normal install
Than I made the install for this "nighty"-version
Than I made again the normal install
Than I back-upped my userdata and tried it again (etc....)

OK, so the x86 version works.

Maybe the next release of the x64 version will work again for me, too.

Or is there a way to just get a working "openssl.dll" for the x64-Version?

Thanks for the answer and help.

**Comment by jjmoneymoney57** [comment]
My 7.01 64 bit version has all but 1 site return "no result." When I switched to x86, most of them returned images, but there are still 4 sites that return "no result." Reinstalling the 64 bit version doesn't fix the issue. I'm running Windows 10 1809 in case that helps

**Comment by Alpha-JinRo** [comment]
I can confirm the version 7.1.0 is still getting "No Result" as x64-version.

**Comment by MelanieTanaka** [comment]
I reinstalled the latest to do more tests with this app and same issue on x64.

**Comment by MelanieTanaka** [comment]
after changing to x86 I now get regular search results, but favorites show no results at all. It says "possible reasons: all images filtered", I removed all blacklists to be sure (only had lolicon/shotacon in the blacklist) and it still shows no results. I am using only danbooru as a source.
If I click on the link provided for the query, danbooru shows plenty of results.

**Comment by EMPER1O** [comment]
Same issue.

I tried x64 and x86 version.

[main.log](https://github.com/Bionus/imgbrd-grabber/files/3177136/main.log)

**Comment by AkatsukiiDesu** [comment]
Download https://www.microsoft.com/en-us/download/details.aspx?id=40784 and see if that fixes it. I had the same thing and that worked :)

**Comment by EMPER1O** [comment]
> > Same issue.
> > I tried x64 and x86 version.
> > [main.log](https://github.com/Bionus/imgbrd-grabber/files/3177136/main.log)
> 
> Download https://www.microsoft.com/en-us/download/details.aspx?id=40784 and see if that fixes it. I had the same thing and that worked :)

Didn't help.
Tried re-install and Framenetwork, just in case.

oh and yeah, Win7 x64.
