### ISSUE TITLE
UI Stuttering

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1614]
**Bug description**

When downloading multiple files through right click menu, the UI starts stuttering on the 14-15th pic. Right clicking does not initiate any action and UI seems frozen. 

I am experiencing this on a lower spec laptop than my usual one. (2/4T i3, 16GB RAM, 256 GB SSD)
I haven't tried this on my desktop yet.

**Expected behavior**

There should not be any stutter as it was before these recent releases.

**System information**

- OS: Windows 10 x64 1803
- Grabber version: Nightly 5fd4a21d

**Comment by brazenvoid** [comment]
So it manifests with time. Even on my faster system, it does happen eventually. Its like something fills up somewhere and the program just can't function normally anymore. On the faster system, it does not stutter (perhaps due to the dedicate GPU) but is extremely slow in reaction. Like the right click context menu on images takes a full second or more. 

The behavior is not related to CPU use at all it seems, perhaps the RAM? Its always at around ~1.3GB when it manifests. Also it seems that the GC isn't working anymore, once it reaches that level, it never backs down to a more normal usage, even with only few searches open. 

At least a restart restores it to normal state.

**Comment by Bionus** [comment]
Indeed, downloading many images at once causes a stutter because they're all started at once in the same thread instead of downloading them one by one (or following the "simultaneous downloads" setting).

I had to download ~100 of them to see it though 🤔

**Comment by brazenvoid** [comment]
I have already scoured databases of rule34.xxx, gelbooru and rule34.paheal for tags I like. So now I do not do batch downloads anymore, rather I search every 5 or 6 days for each of them for new stuff. Each run results in at least 1-2k new images getting downloaded out of at least 10k+.

This way I encounter this at least once or twice a run, meaning it takes me more than twice or thrice your example to experience it. Obviously its dependent on system configuration.

**Comment by Bionus** [comment]
Hello

Is this issue still occurring? I just tried and couldn't reproduce (unlike last time), very likely thanks to the 44a9c7b78cde618c310bd32093ace941ca85351c change (queueing the downloads instead of running them as soon as the "save" button is clicked).

**Comment by brazenvoid** [comment]
Yeah I haven't encountered this in a while. I'll reopen it if I do.
