### ISSUE TITLE
save on idol./chan.sankakucomplex.com crashes program

### ISSUE THREAD

**Issue by Azzurous** [Bionus/imgbrd-grabber#1617]
**Steps to reproduce**

1. Click on any Image or video from idol./chan.sankakucomplex.com
2. Click on 'save' or 'save and close' ('save as' works)
3. Program Crashes (most commonly closes down instantly but sometimes it 'stops responding')

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/3040988/main.log)

**System information**

- OS: Windows 10
- Grabber version: 7.0.1

**Comment by urzuse7en** [comment]
Duplicate of #1611
