### ISSUE TITLE
QAuth 2 generate button missing

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1621]
**Bug description**

The generate button is missing for sources such as pixiv and twitter to get the consumer key and consumer secret. The button was there before since I was able to get those details for my pixiv account

**Steps to reproduce**

Go to the sources
Check Pixiv
See the login tab

**Expected behavior**

Have besides the test button also the generate button to get those details

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
You can't generate OAuth 2 consumer keys/secrets, you have to get them from the website.
For example, for Twitter it's somewhere on https://developer.twitter.com.

So I don't see which "generate" button you're talking about 🤔

**Comment by MrAndre96** [comment]
Hmm I thought that I remembered some generate button but seems that I was mistaken

**Comment by Bionus** [comment]
I'll add a tutorial in the documentation to explain how to get OAuth tokens as it can be confusing.

**Comment by Bionus** [comment]
BTW, for Pixiv you should stick to the defaults:

consumerKey: `bYGKuGVw91e0NMfPGp44euvGt59s`
consumerSecret: `HP3RmkgAmEGro0gn1x9ioawQE8WMfvLXDz3ZqxpK`

**Comment by MrAndre96** [comment]
@Bionus it does seem that the login details are gone from the UI for pixiv. I have still those settings within my appdata and when I have that file I do see more images than without
