### ISSUE TITLE
Login details missing from the piviv source UI

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1622]
**Bug description**

The login details (as in your account) seems to be missing in the new version. When I remove the settings file (which only contain my login info so not the default setting file) the check by login also seems to fail which otherwise succeed.

**Steps to reproduce**

Check all sources
Go to the piviv source
See if you can find the login details for your account

**Expected behavior**

Being able to see it i the UI again instead of only inside my files

**System information**

Windows 10 with the latest version of grabber

**Comment by Bionus** [comment]
It would seem that the UI does not allow to input your username and password for some reason. The consumer key and secret are properly filled, but since you can't enter your credentials it can't succeed.
