### ISSUE TITLE
When inputting multiple MD5's to download, skip over invalid ones

### ISSUE THREAD

**Issue by GatoExtremity** [Bionus/imgbrd-grabber#1623]
The new feature of inputting several MD5's into the downloads list at once is great, but there's an issue with doing so:

Should one of more of those MD5's be missing from the site (like the image was deleted, or maybe the MD5 is misspelled), the program will stop the process, but not tell you which one of them is the culprit (or even remove the valid MD5's it already went through from the list); requiring you to fine-comb through them until you eventually find the invalid MD5.

This can be rather time consuming when inputting hundreds or even thousands of MD5's for download.

So this my suggestion: Perhaps have the program automatically skip over the invalid MD5's it couldn't add and keep going through the list, notifying the user about which MD5's it couldn't process at the end.

**Comment by Bionus** [comment]
Indeed, it would seem that this was an oversight when I added the possibility to add multiple IDs/MD5s at once. Since it used to only expect 1 ID, it made sense to directly stop when it failed.

I'll push a fix 👍
