### ISSUE TITLE
Crash while loading any full picture

### ISSUE THREAD

**Issue by HanatakeYurii** [Bionus/imgbrd-grabber#1624]
Hi,
I hope this was not reported yet (i searched but not found similar recent issue).
Feel free to correct if I'm mistaken.

**Steps to reproduce**

1. Searching some pics on any site
2. Clicking one of them to view full size
3. A new screen with the image loading, then it crash without a word before finishing

I tried a dozen of times with new version 7.0.1 and it always failed and crashed.
Reverting to 6.0.6, all if fine and working well, no crashes anymore.

For some reason no error appears in main.log else it abruptly ends, like it had no time to add / save more.

Tested on Win 10 fully updated.

**Comment by MrAndre96** [comment]
Could you maybe give some more details? I can just open the image window without any crash (or open in afterwards with double clicking on the image)

**Comment by HanatakeYurii** [comment]
Hi, sorry for the wait. Got a little frustrated of the repeated crashes (and the loose of my download list the first time).

After this whole time I finally tried the new 7.1.1 version and ... it happens again! Everytime I tried to load a pic in full view, the program locks itself then disappears, process included. 

Don't know what to do, couldn't find any crash log or alike.

What I know is:
- the program launch perfectly
- I can do all the search I want on any site
- tabs and download list are successfully loaded
but 
- it freezes then crashes when a pic start loading in full view

System information:
- up-to-date Win 10 with 8Go RAM
- machine is fairly recent (late 2016)
- no particular or similar bugs with other apps, so it seems not to be system side


I might try a clean installation, just in case

**Comment by HanatakeYurii** [comment]
Tried a clean installation, and after some tests I think I got a trail:
It have somewhat something to do with the file naming format:

I used to name files in the previous (6.x) versions:
`<%artist%><!%artist% S %search%>/<%copyright%><!%copyright% -UNK->/%websitename% %id% - <by %artist% - ><%copyright% - ><%character% - ><%all%>.%ext%`
It worked then, but putting this entry seems to cause the crashes.

**Comment by HanatakeYurii** [comment]
Seems that every-time conditional (<%something%>) is involved, name is invalidated and the program crashes trying to load pic.

**Comment by HanatakeYurii** [comment]
@Bionus 
Hi, I don't want to bother but I'm not sure you've seen the updates, so just in case...

**Comment by Bionus** [comment]
Hello!

Sorry I didn't have a stable access to a computer with internet in order to reproduce your issue until today. And indeed, after trying with your filename ` <%artist%><!%artist% S %search%>/<%copyright%><!%copyright% -UNK->/%websitename% %id% - <by %artist% - ><%copyright% - ><%character% - ><%all%>.%ext%`, I'm also getting crashes.

Which means that I'll be able to investigate why it breaks, and push a fix ASAP.
Sorry for the delay 🙏

**Comment by Bionus** [comment]
So, after investigating (and fixing the issue), there were two main issues here:

1. Trailing dashes in conditions (in your example, the `<!%copyright% -UNK->` part) did not get parsed correctly by Grabber, causing your filename to be considered invalid (even though it's valid)
2. Some invalid filenames caused crashes in the "view image" window

I pushed fixes for both issues 👌

**Comment by HanatakeYurii** [comment]
Ow thanks for this, I'm glad you found the source of these issues.

I suppose trailing dashes will be valid again in the next release, doesn't it?

Anyway thanks for your patience and your work ^^

**Comment by Bionus** [comment]
Yes, they'll work again in the next release, or if you don't want to wait, in the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly). :+1:
