### ISSUE TITLE
Download Monitor not saving entered details

### ISSUE THREAD

**Issue by AkatsukiiDesu** [Bionus/imgbrd-grabber#1625]
**Bug description**

On new nightly build, the "download favourites montor" is not saving the details.

Checking the favourites.json file has the info in there correctly.

**Steps to reproduce**

1. Add search to favourites
2. Go to Edit Favourite
3. Select "Monitors"
4. Click "Download" and enter in path/filename details
5. Click OK
6. Go back into the same favourite and the details are cleared

**Expected behavior**

Show the download button as ticked and the path/filename info entered in.

Win 10, latest nightly build

**Comment by Bionus** [comment]
Indeed, but it's only a display issue, the values are properly saved, just not properly shown in the UI. 😄
