### ISSUE TITLE
Is there a way to load several tags at once from a text file or something?

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1626]
If this isn't possible, please make it possible. It would be a great feature.

**Comment by Bionus** [comment]
What do you mean, "load tags from a text file"?

**Comment by bluefiberbread** [comment]
write tags in a text file, load text file in grabber and have it automatically look up those tags with current settings and add it to downloads

**Comment by Bionus** [comment]
That's not possible, for a few reasons, one being that "current settings" don't include the current source or other things. But you can always try to generate an IGL file yourself, it's just JSON after all.

**Comment by bluefiberbread** [comment]
but current settings does include all of that

what about loading tags inside a text file to "favorites" and using "favorites" to search for everything at once?
