### ISSUE TITLE
rename tool not getting tags

### ISSUE THREAD

**Issue by bluegoat25x** [Bionus/imgbrd-grabber#1630]
**Bug description**

trying to get tags (artist, character, etc..) from gelbooru and rule34.xxx and it just returns the default unknown ones, even when you look up the md5 of the images, they do have tags.

**Steps to reproduce**

1. open rename existing images tool
2. try to to rename images that are just %md5%.%ext% to artist-%artist% src-%copyright% char-%character% %md5%.%ext%

**Expected behavior**
I expect to get the tags for images that have them.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/3083607/main.log)

[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/3083621/settings.zip)

**System information**

- OS: Windows 10
- Grabber version: 7.0.1

**Additional context**

E621 and Danbooru seem to work fine.

**Comment by Bionus** [comment]
It would seem that

**Comment by Bionus** [comment]
It would seem that Grabber fails to realize it needs to load the image's details when renaming them. I'll push a fix ASAP 👍
