### ISSUE TITLE
Have favorites also support post-filtering

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1631]
**Is your feature request related to a problem? Please describe**

Currently favorites only search with your normal tags you had given but it doesn't allow you to add post filtering for that favorite.

**Describe the solution you'd like**

Also be able to take the post filtering you used on that page when you add it as favorite or being able to add it later on when it is added.

**Comment by Bionus** [comment]
I see no reason why not. :+1:

> Also be able to take the post filtering you used on that page when you add it as favorite

To be honest, I don't think that's common enough to automatically add it. People might forget they have a post-filter, and later on when they browser favorites, they might be confused as to why some images are missing.
