### ISSUE TITLE
Restoration of igl files with single images in them is broken

### ISSUE THREAD

**Issue by serveral1** [Bionus/imgbrd-grabber#1636]
**Bug description**

Whenever an old session is restored or an igl file is loaded from the Downloads tab, all the unique items that are restored return errors when trying to download them

**Steps to reproduce**

1. Select any source, search for a random tag and get a singular image via the "Get Selected" button.
2. Close and start Grabber again
3. Go to Downloads tab and attempt to start the download of the item

**Expected behavior**

Session to restore and files to download without any issues.

**Context**

[log, restore and settings files](https://github.com/Bionus/imgbrd-grabber/files/3101583/log.restore.and.settings.zip)

**System information**

- OS: Win 7 32bit
- Grabber version: 7.10 x86

**Additional context**

Issue is only present after restoring the igl lists, otherwise, the downloading of any single files _in session_ are unaffected.
Also, batches/groups don't seem to be affected and download correctly after the igl file is loaded.

**Comment by jkaryan** [comment]
For me restoring an .igl with Single Images works (though my 140 images list ended up with grabber.exe taking 4.7 GB of RAM, and an experimental 400 image .igl was going strong at 18 GB of RAM and increasing when trying to load the file before I decided to kill the process. I have 64GB of RAM fwiw), I can use the Download button to start the download and everything functions (and least from Sankaku).

What I can't do however is download single images with "Download selected", that results in the program instantly crashing after it finishes the first file.

OS: Win10 64-bit
Grabber version: 7.10 x64

**Comment by Bionus** [comment]
@serveral1 I can indeed reproduce your bug, which is strange because as said by @jkaryan it doesn't happen with all single images. I'll have a look and push a fix and a new version ASAP.

@jkaryan that's a different issue, so moved to #1641 👌
