### ISSUE TITLE
"Rename" option for "If a file already exists globally"

### ISSUE THREAD

**Issue by jkaryan** [Bionus/imgbrd-grabber#1640]
### Issue:
If you download certain sources/searches often, you tend to get images that have only a few tags added to them, and a day or two later their tag amounts may have double, tripled, etc. If your naming scheme includes the %all% option, you're either going to end up with multiple copies of the same image with just a slight name change, or an outdated name for the file.

### Possible solution:
Add a "Rename" option to the "If a file already exists globally" functionality to update the filename to include the new tags.

Though admittedly I'm not sure if this should work globally, or just within the folder you're currently saving to. If a folder was created originally by downloading from source A, and you later download to a different folder for source B, you might not want the names of any overlapping files to change due to differences in %id% etc.

**Comment by Bionus** [comment]
As long as you don't change your filename and folder settings too often, you can simply use the "Move" option for that.

I'm not sure what difference would the "Rename" option have with it. Because after a file is downloaded, even if it's in the MD5 list, Grabber has no idea what filename was originally used to save it, so there's no way to update the old filename if you changed your settings.

**Comment by jkaryan** [comment]
I thought the "Move" option moves the file from one folder to another?

I rarely if ever change my filenames or folders, the issue comes from the source website adding new tags to a file. So if I for example have my name set to %id% - %all% %md5%.%ext%, and I do a download from the source, I might get a file called

12345 - Tag1 Tag2 Tag3 <md5 here>.jpg

However after a couple of days I do the same download again, and that file is still within the search range (still on the 1st page as an example), but now someone has added tags Tag4 and Tag5 to it.

If use the option "Save" I get both 12345 - Tag1 Tag2 Tag3 <md5 here>.jpg and 12345 - Tag1 Tag2 Tag3 Tag4 Tag5 <md5 here>.jpg in the folder. If I use the option "Don't save" it just keeps the old one. Would "Move" do anything in this situation? Ideally in this situation I'd keep just the original file, but update the name to 12345 - Tag1 Tag2 Tag3 Tag4 Tag5 <md5 here>.jpg.

Since Grabber doesn't seem to download the image again if the tags haven't changed/the name matches, I assumed it did a check for this while downloading, even if it doesn't keep a list of names.

**Comment by Bionus** [comment]
Sorry for the late answer, but yes, in this case "rename" and "move" have the same meaning.

You can just see the "data" as moving to another filename I guess. "Rename" would be confusing as well since it can also move folders.
