### ISSUE TITLE
Loading an .igl file with "Single images" uses up immense amounts of memory

### ISSUE THREAD

**Issue by jkaryan** [Bionus/imgbrd-grabber#1641]
**Bug description**

Loading an .igl file with "Single images" uses up immense amounts of memory, way more than just adding those same pictures onto the list caused originally.

As an example I recorded the following memory usage figures:

55 MB after starting Grabber.exe empty.
63 MB after making a search and adding 20 individual images to the "Single images" list. I saved this list as example.igl, included here [example.zip](https://github.com/Bionus/imgbrd-grabber/files/3114478/example.zip).
644 MB after loading up the example.igl with those same 20 individual images from the above.

By comparison loading up an .igl with multiple "Groups" batches doesn't cause similar issues with memory usage. I got 56 MB RAM used after starting with an .igl file that has 42 Groups batches in it.

With more images you get rapidly increasing amount of memory used. Previously I've seen a 140 image list end up with grabber.exe taking 4.7 GB of RAM, and an experimental 400 image .igl was going strong at 18 GB of RAM, and increasing, when trying to load the file, before I decided to kill the process. I have 64GB of RAM for what it's worth.

**Steps to reproduce**

1. Search images from any source
2. Select a number of images
3. Click "Get selected"
4. Save the resulting download list as an .igl file
5. Open Task Manager and check the current memory usage.
6. Either: Delete all of the pending downloads, click Load, select the .igl file you created, and load it.
 Or: Close down Grabber, restart it, click Load, select the .igl file you created, and load it.
7. Observe Grabber.exe taking up a huge amount of memory in Task Manager.

**Expected behavior**

Loading up an .igl should cause Grabber.exe to use close to the same amount of memory it did when creating the list in the first place, and loading large lists of individual images should be possible without running out of memory.

**Context**

[main log and settings ini.zip](https://github.com/Bionus/imgbrd-grabber/files/3114514/main.log.and.settings.ini.zip)

**System information**

OS: Win10 64-bit
Grabber version: 7.10 x64

**Comment by Bionus** [comment]
Indeed, thanks for spotting that!
It would seem that for each "single image" loaded, Grabber would reload a copy of every site, source, MD5 list, etc. I just pushed a fix 👍
