### ISSUE TITLE
Discrepancy between Pixiv website search and Pixiv Grabber search

### ISSUE THREAD

**Issue by Atulin** [Bionus/imgbrd-grabber#1643]
**Bug description**

Let's take the tag `ギャランドゥ` as an example. On Pixiv I see [172 results](https://www.pixiv.net/search.php?s_mode=s_tag_full&word=ギャランドゥ) of mostly girls.
In Grabber, the very same keyword returns 278 results of mostly man.

No, I do not have **any** tags blacklisted.

**Steps to reproduce**

1. Search for `ギャランドゥ` on Pixiv
2. Search for `ギャランドゥ` in Grabber with Pixiv source

**Expected behavior**

Both searches return the exact same results

**Context**

* [main.log](https://github.com/Bionus/imgbrd-grabber/files/3118917/main.log)
* [settings.zip](https://github.com/Bionus/imgbrd-grabber/files/3118919/settings.zip)

<details>
<summary>Screenshots (NSFW)</summary>

First page in Grabber
![image](https://user-images.githubusercontent.com/11233299/56769419-70273200-67b1-11e9-9fba-fda868509e97.png)

First page in Pixiv
![image](https://user-images.githubusercontent.com/11233299/56769478-9a78ef80-67b1-11e9-9643-afe7678cb2ec.png)
</details>

**System information**

- Win10
- Grabber 7.1.0 x64

**Comment by Bionus** [comment]
What you're seeing are the **logged out** Pixiv results.
If you logout of Pixiv then navigate to https://www.pixiv.net/search.php?s_mode=s_tag&order=date_d&p=1&word=ギャランドゥ, you'll see that those are the same Grabber shows.

You need to log into Pixiv via Grabber to see the same results as a logged in user.
To do so, open the "Sources" window, then click "Options" for Pixiv, and add your username and password in the "Login" tab (you don't need to change the consumer key and secret). After you're done, clicking the "Test" button should show "Success".

**Comment by Atulin** [comment]
Thing is, I am logged in. Or at least I should be, if the `test` button is to be believed.
![image](https://user-images.githubusercontent.com/11233299/56853997-c28e5d00-692f-11e9-8376-86389cfc7350.png)

**Comment by fanboy01** [comment]
I'm having the same issue as Atulin

Pixiv and Grabber results are not matching up.

I already added my login information in Grabber but I'm still seeing the "logout" results.

**Comment by VeggieJay** [comment]
Still same issue on latest version - pixiv login successful but full results not showing

**Comment by Bionus** [comment]
Okay so after investigation, the results are different because the API uses the "Title, caption" search mode by default instead of the "Tag" mode which is the default on the website search (and which you can change in the search settings).

So for OP's example:
- Normal search: https://www.pixiv.net/search.php?word=ギャランドゥ ⚠️ **NSFW**
- Grabber's results: https://www.pixiv.net/search.php?word=ギャランドゥ&s_mode=s_tc ⚠️ **NSFW**

I'll see what I can do for this, bug Grabber currently uses the "works" API which does not allow changing the search mode. Allowing it would require moving to the "illust search" API.

**Comment by Bionus** [comment]
Okay, so I made Grabber follow the default Pixiv search. I also added the `mode:full`, `mode:partial`, and `mode:tc` for choosing between different search modes.

The default is `partial` (Pixiv's default). `tc` switches back to the "works" API which is more complete.
