### ISSUE TITLE
Plain dash '-' in filename condition causes crash

### ISSUE THREAD

**Issue by Frozenkex** [Bionus/imgbrd-grabber#1646]
Sorry for not including all information, but im expecting this issue to be easily reproducible.

This was my filename before - "%copyright:maxlength=32%-<"photoshop"-><"uncensored"->%artist%-%character:maxlength=50%-%general:maxlength=20%-%md5%.%ext%"

since 7.0.0 this filename causes crash when you try to download with it, and program thinks its invalid (or rather it says it isn't unique because it doesnt include md5, even though it does, as if this makes it stop reading it midway).

The issue was the "-" separator i was using in these custom tokens/conditionals like <"photoshop"-><"uncensored"-> , replacing "-" with something else fixed the problem (or removing it), placing "-" before the tag like this : 
<-"photoshop"> works, so it's strange.

**Comment by Bionus** [comment]
Yes, sorry about that.

In the 7.0.0 update, I totally changed the way filenames are read so it may cause crashes because of it. I'll take a look at your example and push a fix ASAP, thanks for the heads-up 😄
