### ISSUE TITLE
Favorite source overwritten by most recent search source?

### ISSUE THREAD

**Issue by Kuroonehalf** [Bionus/imgbrd-grabber#1651]
There's this strange bug with the favorites that I've not been able to properly diagnose, so lemme run through this sequence of events and point out what's weird and maybe you'll be able to figure out what's wrong.

1) Do a random gelbooru search and add to favorites. 
2) Do a new search, this time let's say on danbooru.
(If you go and check the favorite you saved now it will work fine, however...)
3) Close grabber and open it again.
4) If you go to the search you saved, it will show results on danbooru instead of gelbooru. And this will happen for any search that you had saved.

Additionally, it seems that the source option inside a favorite's settings has no effect on what source it queries on.

Is this intended behavior somehow?

ps: I haven't found a place to ask this so I'll drop it in here. Inside a favorite's settings, what is the Note option for? It has no tooltip and it shows in every favorite and I can't make sense of it.

**Comment by Bionus** [comment]
Favorites are currently not linked to any source (they are simply "special" tags).

The "source" setting in a favorite "Monitor" tab only applies to monitoring and not searching. The source that will be used to perform searches in the "Favorites" tab of Grabber is the ones selected in the "Sources" window.

Whether it's good or bad is questionable, but that's currently how it works, hence the behavior you noticed. 👌
