### ISSUE TITLE
I FOUND A SOLUTION TO PUT TAGS AND I SHARE YOU!!!

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#1652]
I FOUND A SOLUTION TO PUT TAGS TO YOUR JPG, Gif, Videos,etc AND I SHARE YOU!!!

hello people, I clarify that I am not a developer or anything like that, I am a grateful person with bionus for developing this great program but also, I have suffered a lot that I can not transfer the tags of the images / videos to their metadata (specifically the Windows XPkeyboards, but it can help you if you need to transfer exif data)

looking for and looking for a good time, how to transfer those tags in those files from the txt file generated by the program when you download such image / video. I have not found any program that allows me to tag "from the program" to those files but if A METHOD that you can transcribe the tags, from which you need to have downloaded these two programs (very light I clarify, almost nothing weigh)
(NOTE: they have to be tagged files, if you want to tag tags that read windows or programs / applications like f-stop gallery that allow it, if they want to tag from the exif metadata, well ... it's possible, but for that you'll need a file explorer that allows you to read and edit that metadata, for example Exif Pilot)

The programs are the following:

*COPY CONTENTS (It is optional if you want to transcribe a part of the txt file, but if you want to transcribe all the content, this program will help you in that.) ---> I recommend that you download version 1.0, later versions will require that you have to pay and there is no way to avoid it, if you want to buy it

*TINYTASK (this is the one we will occupy for work)

(CLARIFY BY THE DOUBTS)
-Before you start, when you have the txt file as an image / video, you have to have configured what content you want to extract and save in that file, for example, separate the tags in different categories through a symbol at the beginning of the name and things like that ---> through creating "a session folder" from the save option with their file names to which you want to add and how you want to separate them for the transfer, for example, characters, artists, copyright, etc.
-Also, I advance to you what is trying to be achieved by doing this procedure, ONLY USING TinyTask, and not operating ourselves=
![a00009](https://user-images.githubusercontent.com/50384359/57408793-fd5c8480-71bc-11e9-9c7a-11132b969064.gif)

well, explaining with sample images

-1:in the folder where you saved your image / video with your txt file, you must open it twice in two file browser and have them separated being next to each other but both must be "open" in view of the screen so that they can be touched both from the mouse, as shown in this picture=

![@1](https://user-images.githubusercontent.com/50384359/57408998-8e336000-71bd-11e9-915e-a168c9f792c3.jpg)

(Note:if you want to transfer exif data, instead of opening it twice from the file browser, you have to open it only once and have open, on the other side, the browser that allows you to edit the metadata you are looking for, like the following sample=![@1-2](https://user-images.githubusercontent.com/50384359/57409044-a30ff380-71bd-11e9-86e6-6eaabf36b88d.jpg) )

-2:according to whether you opened the explorer once or twice to "compare" with one another, you have to take one of them and apply an organization (such as ordering through name, creation date, etc.) and write in the search engine of the browser the output format ".txt" so that only txt files are seen in that browser 
(Note: Yes or Yes there must be only txt files of the Images / videos downloaded in that folder, if by chance in the search engine it leaves, one or more files of Images / videos, edit the name deleting that fragment of ".txt" in its name, if there are too many files to edit them one by one, use a program to rename files in batch), and besides, you have to enlarge the big icons or whatever you want, but the important thing is that the Av Pag / Re Pag functions will be used, using the right click of the mouse in the spacebar of the browser, only using the mouse. ---->https://user-images.githubusercontent.com/50384359/57408793-fd5c8480-71bc-11e9-9c7a-11132b969064.gif

(I recommend that the icons be enlarged as well as that the explorers are reduced if possible, so that when using the Av Pag / Re Pag functions, it allows to pass from one icon to another from that function, as if it were a conveyor belt, later I will explain why I recommend it)

In the other browser, be it from system Sofware or exif editor program, you have to apply the same order of criteria and if possible (name, creation date, etc) but configure so that the browser only shows the files Images / videos that you want to tag, the text files do not have to be, (NOTE: if you have files of different formats that you can add tags, transfer all that content to another folder and open it with the corresponding browser, the important thing is that you do not have to be the txt files that have the same name that you are going to tag inside that folder) 
In addition to this, the browser must also have the enlarged icons if possible in the same way as the browser of the txt files, in order to use the Av Pag / Re Pag functions from the mouse click
(NOTE:in the browser where the files Images / videos are located, if you want to transfer XPkeyboard tags, you have to enable in the browser from the panel option, enable details panel, and adjust the browser so that, when we touch the file to move and you see its details panel, you can touch "On sight" the option to "add a tag" in the details panel =
![@2 0](https://user-images.githubusercontent.com/50384359/57409584-06e6ec00-71bf-11e9-9ec1-21d37ea36aa2.png)

if you want to transfer Exif metadata, in the browser that allows you to add the exif data, it must be visible and with a click, the panel where the blank space is that allows you to add the data that you want to incorporate, if up to this point you understood the method that I explain, then you will realize how you have to configure so that you can add the information automatically, but, I invite you to investigate more of TinyTask)

(This step is very important because with this, it will allow the synchronization of data transfer from one file to another, that is, from the txt file to the image / video file from the browsers, and consecutively another file, and another, and another , and another one, using from the mouse, the functions Av Pag / Re Pag, according to the ascending or descending order that you want to put, all through the tinytask program, later it will be explained how it will work)

-3:Once the browsers are configured, so that you can work with the program, if you arrived at this point, I recommend that you take a screenshot from your pc, to save the template of how you "managed, organized and edited" the sizes of the Browsers , not so much for you to remember as you have to order, but you have to replicate in a basic way, its exact location, size and how you have managed those browser, if left, right, in which part of the monitor you left it , and things like that. That said, I explain to you what it is and how tinytask works

TinyTask is a program that allows you to create automated macros like a robot, that is, it allows you to create "patterns" of mouse pointer movements as your clicks to repeat them in a cycle as many times as you want, it is as if, for example, you had to "move" with the mouse any file, to a folder, then open it and take it out, and you can repeat it by putting it back in its place when you moved it and repeat the cycle over and over, and again, again
Well, in this case, what will serve tinytask is that it allows us to move "manually" that data to the other file we want to add, being more specific, run the option to copy from the mouse the contents of the txt file (but that is simplified faster thanks to the program "copy contents", which allows you to copy all the contents of a txt file, all in a simple click)

Explained to this point, if you have understood the context of all this preparation, now I can apply the method I AM PROPOSING, if you have not understood, at the beginning of the tutorial, I have left an example of Gif image, which basically simplifies to that is what you try to do (search for the part where it says "CLARIFY BY THE DOUBTS")

well, what you have to do is Open the tinytask program, configure the buttons that allow you to "record" and then use the pattern of movements that will then be repeated as an automatic robot (for example, use the "F8") and when you have finished assembling your movement cycle , directly from the button that you configured the engraving option, not clicking the mouse, press it to finish the recording, I recommend that you keep it in the same place where you save your screenshot.
BUT !!, Keep this in mind when you start recording, in which part of the screen you left the mouse cursor in the montitor before starting to record, that is, in which part of the screen when you started to move it for recording, I was previously; this is important for the program to work well because, when you want to resume the process / method afterwards, you have to write down or with an indication, in that screenshot that you took before as a template, where the mouse course was in a principle to accommodate it along with the explorers, because the program works as a function where you put the mouse cursor, the program does not accommodate where you left the mouse cursor for the last time, 

"PATTERN OF MOVEMENTS"

@Touch the browser of the txt files from the title bar
@touch in the space bar right click of options, then left click on the function Av Pag / Re Pag as you want to move, but the important thing is that you can scroll to all the files that are at that moment from the beginning of all the pre-established order until the end (except the first one because we are programming a pattern, so that the other files follow ---> look at the Gif image of the explanation)
@touch in the following file txt right click, then left click on copy contents if you want to transfer all the contents of the file, (OPTIONAL: if you want to move part of the text, or part by part, simply double click left to open, the file txt has to be open on the monitor and program which part to copy for that specific part in the other browser, that's a bit more complex, but once you understand what you can do with tinytask, everyone can take advantage of the virtues of the program to your specific tastes)
@touch the browser where we will transfer the data to the images / videos that correspond to the same name of which, if both folders are organized in the same way, we will make a "reflection of actions" of the previous browser, but this time, of the following way
@touch in the space bar right click of options, then left click on the function Av Pag / Re Pag according to how you want to move
@touch the image / video in question that matches the same name as the txt file to which you "copied" its content,
@in windows case, I do not know if other operating systems happens the same, in your details panel, if you expanded the browser enough to see the option of "add a tag" to not open its properties and add your tags there , touch the option, "add a tag" right click of options, and paste
Once stuck, you give it the option to save and move the mouse cursor from the beginning point when you started to move it

AND DONE!! you already armed your macro to repeat it as many times as you want, so yes, you can not use the computer at least for a few minutes, because tinytask has an option to set the speed of the pattern from normal to fast (and believe me, if you have more than 1000 images to tag with your text files, that doing it by hand takes hours, tinytask does it in minutes, but it does it fast)

This is the method that I share with you, and I hope you understand my explanation (probably not entirely, but at least they have the images to guide you, especially the general idea of the method, of which, as I said before, tinytask is a program with a lot of potential that you can configure for whatever you want)
unfortunately there are no programs or "Imgbrd Grabber" does not have a configuration that allows you to add the tags without much complications, be it XPkeyboards or from its EXIF metadata; I have read previous posts that, at the moment, it is complicated to add tags to the images automatically with a program because there are images like PNG that do not support XPkeyboards, or add Exif data to the images / videos, which is, even more complicated , it will probably have to spend a good time for someone to be encouraged to create a solution to this issue, but at least I want to contribute from me with this "method" that I do not know, if there will be someone who has emerged TinyTask in these forums , because I am not an active user, basically I am someone who takes the time to do all this post, to be able to give a hand to those people who broke their heads or became desperate in not being able to get a solution that many, including me, we have complained about not having to find a way to organize our content without so many folders, or to look for something specific, a type of file, things like that
So good, I hope it serves them, hopefully someone creates a definite solution to these problems that I, for my part, did not find, but I came up with this method to solve the problem for now, cheers!

**Comment by zedrk123** [comment]
leave me your comments if there is something they did not understand, and I will edit the post to understand as best as possible

**Comment by Bionus** [comment]
Hello

That's a very complete tutorial, but I feel that's also very hard to do for most users 😅
Congratulations for managing it in any case, that's the first time I've heard of TinyTask, it's quite interesting!

Have  you  tried using the  new metadata system as an alternative as well?
https://bionus.github.io/imgbrd-grabber/docs/metadata.html

I'll close the ticket since there's no real question, and mark it as documentation 👍
