### ISSUE TITLE
Add/update more local database options/documentations

### ISSUE THREAD

**Issue by GlassedSilver** [Bionus/imgbrd-grabber#1654]
**Is your feature request related to a problem? Please describe**

Right now the documentation refers to MyImouto's github which has since been deleted and hadn't been actively maintained anymore for a while, there are two forks of it both of which are abandoned as well.

As for Gelbooru... Well... 0.2 might never see publication and running 0.1 forever seems less than ideal...

Shimmie is... an eyesore to say the least and at best leaves us at a single technically viable option.

**Describe the solution you'd like**

Adding official Danbooru would be a good start, it's the mothership and keeps chugging along with active development.

Another booru that one may consider is szurubooru, I stumbled upon this one because there's a docker build in unRAID's Docker repo. (Community Apps)

Would be nice to see more options, preferable ones that have docker builds since that seems to be the hot new thing. (still have to warm up to it myself)

**Describe alternatives you've considered**

See above. :)

**Additional context**

I love this application!

**Comment by Bionus** [comment]
Indeed.

At the time I wrote this documentation, Danbooru's source code wasn't easily available, so I coudn't include it. And szurubooru didn't exist.

I'll have to see how easy they are to install, as Danbooru seems to rely on some annoying dependencies, while szurubooru uses Docker which is a pain to use and explain.

> I love this application!

😄

**Comment by GlassedSilver** [comment]
So it's not just me who is a Docker dyslexic... And you are a dev and used to confusing documentation...

Frankly setting up szurubooru in Docker on unRAID was fairly easy in the end, however I still want to dabble in danbooru and see if the "Debian of boorus" might be worthier of my time, in the end I am after all entrusting thousands upon thousand of pictures and other stuff to it and I want to ride the path of active maintenance and support.

If you get to set it up I wouldn't mind taking help from you, because the deployment docs themselves claim to be iffy...

They SEEM alright to me at first glance, however I can already see the unexpected errors that'll take me hours to troubleshoot just because a dependency got updated in the time between documentation and my setup attempt.

Updated as in changing an environment variable or some other bullcrap. :D

**Comment by GlassedSilver** [comment]
> Indeed.
> 
> At the time I wrote this documentation, Danbooru's source code wasn't easily available, so I coudn't include it. And szurubooru didn't exist.
> 
> I'll have to see how easy they are to install, as Danbooru seems to rely on some annoying dependencies, while szurubooru uses Docker which is a pain to use and explain.
> 
> > I love this application!
> 
> 😄

Feel free to follow this thread: https://github.com/r888888888/danbooru/issues/4085

**Comment by Bionus** [comment]
I'll have a look. It seems to me that both heavily rely on docker though, which on one hand is a pain, but on the other means that explaining one also pretty much explains the other 🤔

The other issue being that Docker on Windows sucks (hopefully the next update of Windows fixes that).

**Comment by GlassedSilver** [comment]
Danbooru is optimized for VM/bare metal as far as I understood it.

The Docker config file he talked about was just to explain steps how to set it up, because the file does the thijgs you would otherwise do... If I understood that correctly...

As for Docker in general... Ever thought of setting up a VM with Linux to tinker within? VirtualBox and Qemu have come a loooong way.

**Comment by GlassedSilver** [comment]
> 
> 
> I'll have a look. It seems to me that both heavily rely on docker though, which on one hand is a pain, but on the other means that explaining one also pretty much explains the other 🤔
> 
> The other issue being that Docker on Windows sucks (hopefully the next update of Windows fixes that).

Hey! Two things, firstly sorry for slacking on that German translation so far. I'll get around to work on that very soon, probably this weekend. I've been pretty busy and usually rather tired in my spare time when I had some and sitting at the desk translating is something I actually love to do, but when you're exhausted it's too daunting.

Second thing, good news! It's now EXTREMELY easy and very well documented to setup your own danbooru!

https://github.com/danbooru/danbooru/wiki/Ubuntu-Installation-Help-Guide

I used this guide and it worked perfectly. You don't even need the host-only network I think, at least my booru is setup to serve into my LAN and will happily serve pages to my other devices!

I'm running my VM on KVM (QEMU-based), but Virtualbox is even suggested. So either will work!

With how simple setting up a local danbooru has gotten I think we've just found the most ideal personal booru available.

I heard gelbooru 0.3 is in development and WILL be open-sourced. Well, as much as that's good to hear and that having options is ALWAYS good, I think for now I'm going to not wait around for much longer and finally properly store, tag and scrape my weeb content with the help of danbooru.

Thank you so much for considering this issue and not letting it get stale'd and closed. :)

**Comment by FoxxMD** [comment]
Hey just an FYI [szurubooru](https://github.com/rr-/szurubooru) no longer depends on elasticsearch, it only needs postgres to run now. [The docker-compose process](https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md) has been simplified and is almost one-liner at this point.

**Comment by GlassedSilver** [comment]
> Hey just an FYI [szurubooru](https://github.com/rr-/szurubooru) no longer depends on elasticsearch, it only needs postgres to run now. Additionally you don't need to know anything about that when using [the docker-compose process](https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md) -- which has also been simplified and is almost one-liner at this point.

I am using danbooru not for simplicity, but the feature richness, the vast community support and that I trust danbooru to exist for longer than szurubooru.

I have been running danbooru in a VM for several months now and am a VERY happy camper. I cannot recommend spending the time to deploy danbooru enough!

**Comment by Bionus** [comment]
@FoxxMD Szurubooru took me less than 1h to have running and working with Grabber, so I added the docs here, it's indeed very straightforward:
https://github.com/Bionus/imgbrd-grabber/blob/develop/docs/_docs/commands/szurubooru.md

The only part that took me a while was writing the script to interface the API.

-----

@GlassedSilver Honestly, while I can see why Danbooru is more powerful and why you wouldn't want to move away from it, I still think the setup remains too technical for most users (too many steps).

Using Docker like what Szurubooru does would be much more convenient, but given how much more complex the architecture is, I understand the reasons given by the developer.

I'll try to install one myself and see how easy it is to interface with Grabber, but I'll likely won't go into the details on how to install it if I were to add any docs on it, and leave it to the user.

**Comment by FoxxMD** [comment]
Not sure if that was directed at Glassed or me. I am not using Grabber because I'm hosting my own szurubooru instance and it's really just for memes I personally find and want to archive.

BTW I think you could axe the whole Szurubooru download/installation/run/etc. sections and just include
* note referencing install doc from szuru repo
* the Configuration section (the tag categories seems important)

and then just get straight to the Grabber section. Users should be responsible for prereqs! It's shouldn't be your job to teach them.

**Comment by Bionus** [comment]
> Not sure if that was directed at Glassed or me. I am not using Grabber because I'm hosting my own szurubooru instance and it's really just for memes I personally find and want to archive.

Since you were posting here I thought you were also using Grabber, but oh well. 😅 

> BTW I think you could axe the whole Szurubooru download/installation/run/etc. sections and just include
>
> * note referencing install doc from szuru repo
> * the Configuration section (the tag categories seems important)
>
> and then just get straight to the Grabber section. Users should be responsible for prereqs! It's shouldn't be your job to teach them.

I was actually considering this option, but then I remembered that many Grabber users are surprisingly **not** power users, so even just finding out you're supposed to configure a mounting point for the data storage in Docker might have been too much. Also, the setup mentions a bunch of stuff that could be confusing, such as editing configuration files, which is not necessary to a local installation.

Since in the end setting it up is so totally trivial anyway (big kudos to the devs for that, it's not always obvious), I just put the steps in there. The issue being if those steps change, it'll be out of date (I added a link to INSTALL.md at the top for that reason, but that's not really an optimal solution).

**Comment by FoxxMD** [comment]
That makes sense. Kudos for understanding your audience and going the extra mile for them.

**Comment by GlassedSilver** [comment]
Any update on this issue? o3o

**Comment by Bionus** [comment]
>  Any update on this issue? o3o

Now that Danbooru's install is as straightforward as
```sh
wget https://raw.githubusercontent.com/danbooru/danbooru/master/docker-compose.yaml
docker-compose up
```

I'll add a new page for that then close this issue.

**Comment by GlassedSilver** [comment]
Hooray! :D

Hope this includes support for setups that don't run on the same machine as well. :)

Cheers!

**Comment by Bionus** [comment]
@GlassedSilver are you open to discussing more real time on [the Discord](https://discord.gg/pWnY5eW3rz) (or even by PM: `Bionus#2577`)?
You seem more knowledgeable on Danbooru's API than me, and the API docs are very rough 😅 

If no, do you know how to upload raw files to Danbooru in a Docker instance?

> Will there be a possibility to pass the type of a tag to my local instance?
>
> e.g. there's a new tag on danbooru (official) of the type copyright. if my instance doesn't know this tag yet it will create that tag, but it will be general unless it's passed in the format 'type:tag' e.g.: 'copyright:vocaloid'

Yes, Grabber supports passing tag types together with tags using [includenamespace](https://bionus.github.io/imgbrd-grabber/docs/filename.html#include-namespace-boolean), that's what's being done for [Szurubooru](https://bionus.github.io/imgbrd-grabber/docs/commands/szurubooru.html) for example.

> Also, will it be possible to pass the source as mentioned on the entry I'm copying from?

Grabber does read the source, so you can pass it as-is using `%source%`.
That's also how it's already being done for the Szurubooru integration.

> Bonus if artist commentary and translation could also be passed as passed on the page, but that's something I usually check manually either way if danbooru doesn't show one (usually the commentary is too short to be relevant? idk... Takes no space and I like being thorough)

Grabber doesn't parse this at the moment (because very few sources have this kind of thing), so that won't be possible.

**Comment by GlassedSilver** [comment]
Sorry for getting back to you so late, but I've generally been pretty afaik on GitHub for a while now. I'm mostly back (I think) so I'll pick up on your reply now.


> @GlassedSilver are you open to discussing more real time on [the Discord](https://discord.gg/pWnY5eW3rz) (or even by PM: `Bionus#2577`)? You seem more knowledgeable on Danbooru's API than me, and the API docs are very rough 😅
> 
> If no, do you know how to upload raw files to Danbooru in a Docker instance?

I'd be open to chatting on Discord together about this, no problem!
My danbooru instance is private and non-public, but official danbooru has a testbooru instance that you can target dev shenanigans at! :D 

As for my knowledge about Danbooru's API... I don't know about being more knowledgable, I just run my own instance and access it through its web interface and I know how to maintain, update and fix it. Often times through the invaluable help of the repo community.

That same repo community could possibly assist much better when targetting the API specifically, cause I have never worked with it, but as for anything that may include setting up a local dev instance I might be able to help a bit. :D 

Although these days there's official danbooru docker images you can deploy. Back in my day when I set up my danbooru it was bare metal, VM or the highway if you wanted docs and help! *gnar gnar gnar, swings walking stick*

You kids don't know how good you've got it! *gnar gnar* :D 

However if navigating the API docs is something that may come easier if we both combine our eye ball count that I am most assuredly willing to do, not sure if it will be helpful in the end, but we can try! :D 

As for uploading raws to a danbooru in a docker instance... You don't just toss raws into a danbooru "watched folder" or however you may hope it might work out and it digesting it.

The upload tool through WebUI or the API are the only ways we can go through here as far as I know since those take care of the ingression for the storage manager. Cause files will get some form of treatment, depending on setup options.

Usually that is by hashing the file, renaming it based on the hash and then putting the file into a subfolder path where in groups of 2 characters derived from the hash the file is put on some level of hierarchy.

I think it's like 3 layered, not sure off the top of my hat. So if the hash of the file is idk...

45KC38IZ933298blabla.... then the path would be:

`<folder/mount point of the storage manager root directory>/45/KC/38/45KC38IZ933298blabla.....JPG`

> > Will there be a possibility to pass the type of a tag to my local instance?
> > e.g. there's a new tag on danbooru (official) of the type copyright. if my instance doesn't know this tag yet it will create that tag, but it will be general unless it's passed in the format 'type:tag' e.g.: 'copyright:vocaloid'
> 
> Yes, Grabber supports passing tag types together with tags using [includenamespace](https://bionus.github.io/imgbrd-grabber/docs/filename.html#include-namespace-boolean), that's what's being done for [Szurubooru](https://bionus.github.io/imgbrd-grabber/docs/commands/szurubooru.html) for example.

Sweet! That'll be so much help!

> > Also, will it be possible to pass the source as mentioned on the entry I'm copying from?
> 
> Grabber does read the source, so you can pass it as-is using `%source%`. That's also how it's already being done for the Szurubooru integration.

Oh that's more than wonderful! Joyful times ahead! Ingression of all these many many files I got will be that much simpler and less time consuming! :D

> > Bonus if artist commentary and translation could also be passed as passed on the page, but that's something I usually check manually either way if danbooru doesn't show one (usually the commentary is too short to be relevant? idk... Takes no space and I like being thorough)
> 
> Grabber doesn't parse this at the moment (because very few sources have this kind of thing), so that won't be possible.

Uhm... well as long as the market leader by a long shot has this this seems sensible enough to consider at least, right?

I mean danbooru is the Amazon of boorus. If they got something it's basically automatically relevant. But anyhow, I'll get by without it for now. *knock on wood* :)

**Comment by GlassedSilver** [comment]
Blocked by: #2652

**Comment by Bionus** [comment]
Closing since docs about Danbooru and Szurubooru has both been added.
There's still a small issue with Danbooru but it can be tracked individually.
