### ISSUE TITLE
resizable download list

### ISSUE THREAD

**Issue by Cantiel** [Bionus/imgbrd-grabber#1655]
i was wondering if it would be possible to make the lists in the download tab resizable?
i use the grabber mainly to download large batches of pictures, so my "groups" list tends to become quite long, while the "single images list underneath is always empty.

even in a maximized window, the upper list can only show 12 listed orders, while the lower half of the screen stays unused, so it would be nice if i could vertically resize the lists, similar to the way i can make the left "tags"bar wider or smaller

**Comment by Bionus** [comment]
Indeed, I can see how this can be a problem. I also personally never use "single images" downloads, but it never occurred to me that adding some way to resize it could improve the UI 😄
