### ISSUE TITLE
Feature Suggestion: Default Source Site Options

### ISSUE THREAD

**Issue by frebeee** [Bionus/imgbrd-grabber#1656]
**Is your feature request related to a problem? Please describe**

I'm always frustrated when I'm having download issues that could have easily been fixed by applying settings that I wasn't aware of.

**Describe the solution you'd like**

1. Defaults set for each Source, particularly in the Downloads configuration of each source
2. Show these defaults as "Recommended Settings" so that existing users can be aware of them and change to them after updating Grabber.

**Describe alternatives you've considered**

1. Current - review other GitHub issues to try and find the problem and the best values
2. Intermediate Step - maintain a list of working values for each source in a human-readable file in the GitHub repo

#1606 
#1515

**Comment by Bionus** [comment]
> I'm always frustrated when I'm having download issues that could have easily been fixed by applying settings that I wasn't aware of.

Which settings are you talking about here?

I see both issues you linked are related to Sankaku and indeed they could be made default, so I pushed 0c5342a45293bee895dea37646c318186519f354. Is there something else?

**Comment by frebeee** [comment]
No that's it, thanks for addressing it!

**Comment by frebeee** [comment]
Will leave it for you to close
