### ISSUE TITLE
Feature Suggestion: File Metadata

### ISSUE THREAD

**Issue by frebeee** [Bionus/imgbrd-grabber#1662]
**Is your feature request related to a problem? Please describe**

It would be helpful to turn data about a downloaded item into proper file metadata to help organise files, as a lot of this data is lost due to filename length limitations.

**Describe the solution you'd like**

Be able to populate the metadata fields automatically. The most useful one would be "Tags". Title and Comments would also be helpful. I think these are the most common across different file types. Authors and Subject would also be useful.

This can be controlled by the same customisable method used for Filenames.

**Additional context**

#1652

**Comment by Bionus** [comment]
This issue has actually been requested a few times. I think a few good solutions have been suggested recently so there might  be a way to implement this soon 😄 

Closing in favor of the most recent #2258 to have a single place of discussion
