### ISSUE TITLE
Feature to Turn Off Auto Update

### ISSUE THREAD

**Issue by rushuna86** [Bionus/imgbrd-grabber#1663]
Option to turn off Auto update checks/Notification. Using an older version of Grabber because current has quite a few bugs, and asking for update every start up.

**Comment by Bionus** [comment]
You know this is literally the third setting of the options window right? 😄

![image](https://user-images.githubusercontent.com/882719/57601792-c3450700-755d-11e9-8e26-7c5cc7c47f48.png)

Just change it to "never" and it won't ask for updates anymore.
But I'm not sure about the latest version having that many bugs given the issue board here on Github doesn't have that many 🤔

**Comment by rushuna86** [comment]
Holy crapppppppp I was looking for it like in all the sub menus >.<

Sent from Mail for Windows 10
