### ISSUE TITLE
Looking for translators

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#1676]
Hello! 😄 

I just finished setting up [Crowdin](https://crowdin.com/project/imgbrd-grabber), in order to simplify the translation of Grabber. So I'm now looking for some help for translating Grabber in more languages and updating already translated languages!

-----

## Languages

Mostly done (but needing a few updates):
* German
* Spanish

New:
* Indonesian
* Italian
* Japanese
* Korean
* Portugese

Note that I added those languages because they were the top countries using Grabber, but if you know another language you'd like to translate, feel free to tell me and I'll add it to the list.

## How to help

I updated the [documentation page about translating Grabber](https://bionus.github.io/imgbrd-grabber/docs/plugins/translation.html), so you can see the step-by-step explanations there.

Otherwise, here's a summary: go to [Crowdin](https://crowdin.com/project/imgbrd-grabber), login (you can login using your GitHub account if you so wish), click any language you'd like to translate, then click the "Join" button! (note that you won't see the "Join" button if you're not logged in)

You'll be asked for a short introduction about why you can and want to translate Grabber. Please only ask if you're native or bilingual in that language. Don't forget to tell me which languages you want to translate so I give you the proper access. I'll then review it ASAP and give you the rights to the language, and you'll be able to start translating right away!

Once done, Crowdin's interface is quite trivial to use:

![image](https://user-images.githubusercontent.com/882719/57757877-b7d91380-76f6-11e9-81f4-c68d39932e72.png)

Note that you can still use the old technique of using Qt Linguist, or even [POEdit](https://poedit.net/) if you want or don't like Crowdin.

-----

If you have any additional questions or remarks, feel free to ask here or on [Gitter](https://gitter.im/imgbrd-grabber/Lobby).

Thanks! 😄

**Comment by GlassedSilver** [comment]
Just submitted my application for German. :)

**Comment by Bionus** [comment]
> Just submitted my application for German. :)

Great, thanks! I approved it this morning 🎉

If you have any questions feel free to ask me on [Gitter](https://gitter.im/imgbrd-grabber/Lobby), that's the fastest way to contact me when I'm not asleep (European time) 😄

**Comment by Hissvard** [comment]
Hi, I wouldn't mind working on an Italian translation if it could be useful.
Not sure whether there's a userbase from here.

**Comment by Bionus** [comment]
Hello @Hissvard !

Sorry I didn't see your message earlier. I just added Italian as a possible translation target, so feel free to go Crowdin and start translating a few things. If you feel there's too many things to translate, you don't need to translate everything. What's not translated will default to english. 👍
