### ISSUE TITLE
Source not found on Windows 10. Previous solutions not working

### ISSUE THREAD

**Issue by benjamin-cheung** [Bionus/imgbrd-grabber#1682]
I'm running windows 10. I downloaded the files and ran the .exe file. I went into the source's release folder and copied sites, languages, and words.txt into the "C:/Users/USERNAME/AppData/Local/Bionus/Grabber" folder. That folder already contains a settings.ini file.

I tried running the program from the generated desktop shortcut but I get the same "No source found. Do you have a configuration problem?" error.

I've read #319 and #1461 but it hasn't helped me.

**Comment by ShannonVanshoon** [comment]
I'm also having the same issue, as of installing it today... even though my roommate just installed it and isn't having any problems. :( I'm wondering if it's an issue with the 1703 version of Windows 10, which they're not using right now.
