### ISSUE TITLE
What is the best way to organize tags in a folder with many many Copywrites, artists and characters?

### ISSUE THREAD

**Issue by the612toon** [Bionus/imgbrd-grabber#1687]
I use %artist% %copyright% %character% %count% %date% %md5%.%ext% but am wondering if something is better...

**Comment by Bionus** [comment]
There's no "best" way.

But depending on what you think is most important, I strongly suggest you to create folders. Personally, I use `%artist%/%copyright%/%character%/%md5%.%ext%`, which means that each artist has its own directory, then each artist's gets its image grouped by copyright then character.
