### ISSUE TITLE
Not able to download certain tag from Sankaku Complex

### ISSUE THREAD

**Issue by Reeevu** [Bionus/imgbrd-grabber#1691]
When I try to bulk-download images of an artist, there seems to be some that are left out. I believe extreme_content is not being downloaded by Grabber. It cannot find anything on that tag too so it most likely can't access that tag for some reason. Is there any way to fix this?

**Comment by Bionus** [comment]
Hello,
I can't reproduce this on my end.

* Are you logged in Sankaku via Grabber? (i.e. did you provide your credentials in the "Sources > Sankaku > Credentials")
* Do you have any blacklist set-up in Sankaku?
* Do you have any blacklist set-up in Grabber?

**Comment by Reeevu** [comment]
Hi it seems like the tag toddlercon was the one that was blacklisted in Grabber and not extreme_content. That's probably what I meant in original post.

**Comment by Reeevu** [comment]
Is it possible to be able to download that tag in the future?
