### ISSUE TITLE
Can't get webm filenames

### ISSUE THREAD

**Issue by ayoits0913** [Bionus/imgbrd-grabber#1694]
im using %filename%.%ext%

I get filenames for all files except webm. even if it shows the filename, it only saves the md5

**Comment by Bionus** [comment]
Hello,

Which source are you trying to use for this?
I tried on a few and the filenames were coherent for both static images and WEBM files. 🤔

**Comment by ayoits0913** [comment]
rule34hentai.net

Is %filename%.%ext% correct then?

**Comment by ayoits0913** [comment]
Please let me know if you try that source and experience the same thing. Curious if it's on my end or not. I even did a fresh install, same thing. Tried various webms with all the same outcome. Even when clicking it and seeing the filename, then right click > save it still only saves the md5....

**Comment by ayoits0913** [comment]
??

**Comment by ayoits0913** [comment]
> 
> 
> Hello,
> 
> Which source are you trying to use for this?
> I tried on a few and the filenames were coherent for both static images and WEBM files. thinking

Did you test with that site?
