### ISSUE TITLE
Buggy Grabber

### ISSUE THREAD

**Issue by Axelrhode** [Bionus/imgbrd-grabber#1697]
**Bug description**

Just as the title says, the app is buggy for me. The bugs happen to gelbooru, sankakucomplex, rule34, danbooru, and safebooru (ones I've tried so far). Said bugs are:

1. Loading images after clicking another thumbnail would load the previously loaded image (happens 70% of the time for me). The tags also change to the ones previously loaded, depending on the image it loads. Downloading the image I tried to load from the previous thumbnail would just say that the image already exists, and trying to download the image while it's loading would yield the same result.
![Screenshot (324)](https://user-images.githubusercontent.com/35842812/59149771-8977fb00-8a4c-11e9-969a-91ae2289be65.png)
![Screenshot (323)](https://user-images.githubusercontent.com/35842812/59149774-8da41880-8a4c-11e9-8c26-a1a000e52e3f.png)
![Screenshot (322)](https://user-images.githubusercontent.com/35842812/59149778-94cb2680-8a4c-11e9-9131-5787bb626b2e.png)

2. When downloading bulk images, grabber would say that the images already exist (99% of the images, at that). I checked the folder, none. Only those I saw checked on the download list were there.
The file names are also blank, despite having set the default names with %md5%.%ext%.
![Screenshot (230)](https://user-images.githubusercontent.com/35842812/59149785-b3312200-8a4c-11e9-9da8-2c53efc748f7.png)
![Screenshot (229)](https://user-images.githubusercontent.com/35842812/59149788-c47a2e80-8a4c-11e9-8c2b-bdd50daddccc.png)
![Screenshot (260)](https://user-images.githubusercontent.com/35842812/59149791-c93ee280-8a4c-11e9-91d3-b3eacf6a3bb9.png)

**Expected behavior**
1. I expected that the images being loaded would be the ones I clicked after the switch, but no, it loads the previous image. The same image I loaded would be the one I'll be seeing for the next set of images I try to load. 

2. The first time I tried bulk downloading(which was yesterday), it worked for around 95% the images I tried (source was at Gelbooru and Danbooru that time). Today, I can't even download anywhere near the same percentage.

**Context**

[main, settings, + bug.zip](https://github.com/Bionus/imgbrd-grabber/files/3268737/main.settings.%2B.bug.zip)

**System information**

- OS: Windows 10
- Grabber version: 7.1.1

**Comment by Bionus** [comment]
It seems to me that both of your bugs are linked.

Grabber has an internal MD5 database, so when you save an image, Grabber will make an association "MD5 -> file path". So later on, if the same MD5 is found, it will simply load the image from the file instead of downloading it again.

In your log, it corresponds to:
```
Image loaded from the file `C:/Users/Computer/Desktop/Grabber/.jpg`
```

So the issue here is that Grabber seem to fail to load the MD5 for Gelbooru. I can't see any reason for that from your logs, nor can I reproduce on my end, so I'll investigate more to see what might cause that.

**Comment by Axelrhode** [comment]
It was working fine the first day. I have a bunch downloaded here in batch after I got to know how, but after trying on the succeeding day, it just won't work like before.

I hope a fix will come. Thanks for looking into it

**Comment by Axelrhode** [comment]
Ok so after a few tweaking I did this day, I found out that I had to set the limit to 0. Now, my grabber's not bugging out... All my issues got solved after this thing I did

![image](https://user-images.githubusercontent.com/35842812/60168222-053cba80-9837-11e9-9556-6487adc81c7f.png)
![image](https://user-images.githubusercontent.com/35842812/60168351-3fa65780-9837-11e9-9be4-5cb5d8c15d29.png)
![image](https://user-images.githubusercontent.com/35842812/60168427-66fd2480-9837-11e9-93dc-9de5fb9dee59.png)
![image](https://user-images.githubusercontent.com/35842812/60168482-8005d580-9837-11e9-9797-22e054f971e1.png)
