### ISSUE TITLE
Sankaku Bad Gateway Error not handled properly

### ISSUE THREAD

**Issue by frebeee** [Bionus/imgbrd-grabber#1708]
**Bug description**

[13:11:09.570][Error] Loading error for '(URL) - server replied: Bad Gateway

**Steps to reproduce**

1. Download lots from Sankaku using the recommended/default settings

**Expected behavior**

1. Continuous download until Bad Gateway error
2. Timer waits a reasonable amount of time
3. Downloads resume

**Actual behavior**

1. Continuous download until Bad Gateway error
2. Batch freezes
3. Have to pause and then resume for downloads to continue

**System information**

- Grabber version: 7.1.1

**Comment by ravenlord1** [comment]
Just an FYI, Sankaku servers are slow lately, and sometimes give the same error even with normal browsing.

**Comment by a7hael** [comment]
Hi, I can imagine that to solve the freeze issue, where the "_Details limit reached (429). New try._" resume function is written (image.cpp), something similar ought to be done for the "_Bad Gateway_" (usually with a reference code of 502 for me, but not sure if it gives a httpstatuscode). But maybe it doesn't even need to be specific for that error, just check with a timer if '_set resume time limit_' has been crossed and force resume (if necessary, run the pause/resume sequence automatically).

I use version 7.3.2, I'd prefer to just overwrite the exe with the added/edited few lines of code but I'm new to github. Don't use Qt either. I download the Grabber directory as a zip for crying out loud :). I wonder how to move on from here.

**Comment by a7hael** [comment]
xD I'm this close to rage quitting.
I have OpenSSL installed afaik, I can access it with cmd... I want to use Cmake to generate a solution of the 7.3.2 build for Visual Studio, but it keeps giving me the missing: OPENSSL_CRYPTO_LIBRARY error. If libcrypto.a isn't it I don't know wtf is happening. Every time xD

**Comment by a7hael** [comment]
imgbrd-grabber-7.3.2\src\lib\src\models\image.cpp ; rows 416 to 436 (edited/added lines)

const int statusCode = m_loadDetails->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
	if (statusCode == 429) {
		log(QStringLiteral("Details limit reached (429). New try."));
		loadDetails(true);
		return;
	} else if (statusCode == 502) {
		log(QStringLiteral("Bad Gateway (502). New try."));
		loadDetails(true);
		return;
	}

	// Aborted or connection error
	if (m_loadDetails->error()) {
		if (m_loadDetails->error() != NetworkReply::NetworkError::OperationCanceledError) {
			log(QStringLiteral("Loading error for 502 '%1': %2 ... %3").arg(m_pageUrl.toString(), m_loadDetails->errorString(), statusCode.toString()), Logger::Error);
		}
		loadDetails(true);
		m_loadDetails->deleteLater();
		m_loadDetails = nullptr;
		return;
	}

@Bionus is it possible to do this, would it work? As it is now, doing large batch downloads, would require constant monitoring if there is a gateway error since you'd have to manually reset it. I actually have no clue if that fixes it tho.

Am I the only weird one who does large batches at a time? I'm preparing for the worst xD.
