### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by taskmaster69** [Bionus/imgbrd-grabber#1714]
I'm sorry to put this here I don't really know where else to put it, started a sankaku download with a total count of 2.5k, I set the image limit to 3k but it stopped after 500, and now I don't know how to get the rest of them to download. I tried just setting the page number on the download to the number it got up to but then it just does the first 40 starting from page 1. Any help would be appreciated.

**Comment by Yaro-Kira** [comment]
Login?
