### ISSUE TITLE
Blacklist for Favorites autodownload

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1720]
**Is your feature request related to a problem? Please describe**

When getting favorites automatically, the blacklist does not seems to be used at all.

**Describe the solution you'd like**

Just apply the black list before downloading the image to avoid useless download.

**Comment by Bionus** [comment]
Indeed, it would seem that the blacklist is not applied to favorite monitoring, good catch! :+1:

I'll push a fix ASAP.
