### ISSUE TITLE
Sankaku too many requests

### ISSUE THREAD

**Issue by fluffyjin** [Bionus/imgbrd-grabber#1721]
is there no way to bypass this? its annoying. Thanks for this downloader though

**Comment by Yaro-Kira** [comment]
First - Login. (if not)

Second - Try to make a delay like mine (especially pages). This helped me a lot with sankaku, but very rarely the download can stop at half, then you need to click on the pause and resume.

![Delay](https://user-images.githubusercontent.com/61095746/75249134-aaed6280-57e6-11ea-9120-0663dde08342.png)

**Comment by SvyraCosmix** [comment]
> First - Login. (if not)
> 
> Second - Try to make a delay like mine (especially pages). This helped me a lot with sankaku, but very rarely the download can stop at half, then you need to click on the pause and resume.
> 
> ![Delay](https://user-images.githubusercontent.com/61095746/75249134-aaed6280-57e6-11ea-9120-0663dde08342.png)

Thank you! This really helped, it'll take a week to download the "trap" tag 92,300 files but still better than nothing, kinda peeved that gelbooru only has half that much but sankaku does steal from everywhere but too bad their devs are greedy pieces of shit
