### ISSUE TITLE
I don't get it, and that's what's written on my T-Shirt

### ISSUE THREAD

**Issue by General-Trident** [Bionus/imgbrd-grabber#1722]
I'm dumb as shit and I don't have enough capacity of brain cells to look through all the issues to find the answer to my question. Is it supposed to make folders like this (I replaced the artist' name with number '1' and '2') when downloading every single file, every single time? Put every image file, which is just named with the md5 codes, inside a folder, instead of making the usual like Danbooru always do, i.e.: "doraemon and nobi nobita (doraemon and etc) drawn by ryoga", or maybe simply like "character1, character2, etc. (copyright), artist, md5.ext"

![image](https://user-images.githubusercontent.com/52889250/61186047-cc9c3e00-a68a-11e9-93d6-1e2e88512968.png)

inside it (copyright) -> 
![image](https://user-images.githubusercontent.com/52889250/61186146-39640800-a68c-11e9-95e1-b62b54c6f48e.png)

inside of inside (character's name) -> 
![image](https://user-images.githubusercontent.com/52889250/61186169-74663b80-a68c-11e9-9880-e7e521770210.png)

Thank you.

**Comment by Bionus** [comment]
Hello

Well, it's supposed to do this if your filename is `%artist%/%copyright%/%character%/%md5%.%ext%`.
See https://bionus.github.io/imgbrd-grabber/docs/filename.html

Each `/` in your filename will create a folder. Just see it as Grabber replacing `%artist%` by the actual artist, `%copyright%` by the actual series, etc.
So in your case, it will result in `1/misc/KKK/098f6bcd4621d373cade4e832627b4f6.jpg`

If you want something different, you should change your filename to something else that matches what you want. For "character1, character2, etc. (copyright), artist, md5.ext" as you said, it could be `%character% (%copyright%), %artist%, %md5%.%ext%`. Note that by default if you have multiple artists/copyrights/characters they might be merged, but you can change that in the "Save" section of the settings.

**Comment by General-Trident** [comment]
Mother of Programming, you responded so quick. Unlike some assholes I knew of. You got great future, man.
![IMG_20181009_202803](https://user-images.githubusercontent.com/52889250/61196313-ea53bc80-a6f7-11e9-8b80-2f34038e16d6.jpg)

**Comment by Bionus** [comment]
👌
