### ISSUE TITLE
Sankaku Warning - No Valid Source After 51!

### ISSUE THREAD

**Issue by StarMaster21** [Bionus/imgbrd-grabber#1723]
**Bug description**
I get No valid source of the site returned result after going to page 51. Yes i'm log-in as well. It always happens when going into page 50 or higher, if you go back to page 50 you get it saying: No Result and ect. Also Download that page 50 or higher won't work either.

**Steps to reproduce**

1. Go to page 50 even 60
2. Click on going back to get it
3. You get Error with no Result
4.  Page 50 or higher won't download

**Expected behavior**

**Screenshots**

**System information**

- OS: Windows 10 Build 1803
- Grabber version: [7.1.1 (x64)]

**Additional context**

Add any other context about the bug report here.

Hope my screenshots helps out. 
![SZ](https://user-images.githubusercontent.com/51894983/61497138-2733e380-a984-11e9-9ad3-8b70325a909e.png)

![sz2](https://user-images.githubusercontent.com/51894983/61497139-27cc7a00-a984-11e9-863b-b965c25f4086.png)

[main.log](https://github.com/Bionus/imgbrd-grabber/files/3408682/main.log)

[settings - Copy.zip](https://github.com/Bionus/imgbrd-grabber/files/3408693/settings.-.Copy.zip)

**Comment by jkaryan** [comment]
Yeah, ran into this before, you can work around it by using the "next page" arrow button on the bottom and downloading the images via Get Selected rather than Get this page or Get all.

**Comment by MrAndre96** [comment]
They removed official support for this source
