### ISSUE TITLE
Crash during the e621 download

### ISSUE THREAD

**Issue by nlboom** [Bionus/imgbrd-grabber#1726]
Program crashes when I downloaded images from e621. This happens on stable and nightly release v. v7.1.1.
Here the Crash Dump.
[Grabber_crash_dump.zip](https://github.com/Bionus/imgbrd-grabber/files/3441820/Grabber_crash_dump.zip)

**Comment by Pernat1y** [comment]
e621 is behind Cloudflare now. Not sure on how to fix it (without adding cookies manually).

**Comment by nlboom** [comment]
> e621 is behind Cloudflare now. Not sure on how to fix it (without adding cookies manually).
Можно использовать паблик-прокси. Те что недавно созданные спокойно проходят Cloudflare. Прога избирательно крашится, один тег нормально качает, а другой нет. В креш-дампе всё есть.
