### ISSUE TITLE
Danbooru infinite scrolling does not work when searching with no tags

### ISSUE THREAD

**Issue by Giacomino99** [Bionus/imgbrd-grabber#1728]
**Bug description**

When searching Danbooru with no tags in the search bar infinite scrolling does not work.

**Steps to reproduce**

1. Go to Options
2. Open Interface drop-down menu
3. Click on Search Results
4. Change Infinite Scroll to "Scroll"
5. Click OK to close options
6. Have no tags in the search bar
7. Click Ok to search
8. Attempt to scroll to see more posts
9. Posts do not load - This is the bug

**Expected behavior**

When infinite scroll is turned on posts from Danbooru should load when scrolling.

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/3454413/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/3454417/settings.txt)

I have tried many times to get this to work but can't. I have tried infinite scrolling using several other sources and they all seem to function fine.

And interesting thing about this bug is that it is possible to get Danbooru to load the images with infinite scrolling. If I add a second source (such as Gelbooru), and then do the same blank search, when scrolling to load more images both Danbooru and Gelbooru load the images as expected.

**System information**

- OS: Windows 10
- Grabber version: 7.1.1 (x64)

**Comment by Bionus** [comment]
Indeed, it seems to come from the fact that Danbooru does not provide the total page count when there are no tags, causing Grabber infinite scrolling to think it's reached the last page already.

I'll push a fix ASAP 👌

**Comment by vampiricwulf** [comment]
Using Nightly:
Head: aac11b6
Date: 2020-01-16T19:05:31.0000000Z

I have the same issue with chan.sankakucomplex.com
