### ISSUE TITLE
not an Issue just a question about tabs

### ISSUE THREAD

**Issue by mattiiz** [Bionus/imgbrd-grabber#1729]
is there a way to keep all the tabs open for the next session? For now i have a workaround by closing grabber via taskmanager and it will ask to open all the tabs again the next time i start grabber. I wish this could be a feature. I know about the "restore closed tab" feature. but it only reopens 1 tab at a time. and i have more than 100 tabs open. thanks anyways for the great tool 👍

**Comment by Bionus** [comment]
Hello

In the settings, in the "General" part there should be a "At start" option. If you set it to "Restore last session", it should automatically restore all your tabs and downloads. 👌
Let me know if it works.

**Comment by mattiiz** [comment]
hi. thank you very much. never saw that option. and it works too. thank you!!!
