### ISSUE TITLE
Add Proper Image Ordering/Sorting for Derpibooru

### ISSUE THREAD

**Issue by Astromormy** [Bionus/imgbrd-grabber#1732]
This is being added posted as a feature request since it technically isn't a bug as everything is working exactly as it should.

As it is, you can't use the "Sort by" function found under the "Plus" options when searching for an image from the source Derpibooru. The reason for this, I believe, is due to the way Derpibooru searches for images. Unlike other boorus, it doesn't take namespaces into the search bar. Because of this, using the "Sort by" option, or any of the namespaces, for that matter, under the "Plus" options cause no results to be displayed for the Derpibooru source.

**Comment by Bionus** [comment]
Sure, but note that (as far as I know), Derpibooru only supports sorting by score or by number of comments.

I will add `order:score` / `order:score_asc` / `order:score_desc` and `order:comments` / `order:comments_asc` / `order:comments_desc` support in the next version.

**Comment by Atulin** [comment]
Sorting for Derpibooru no longer seems to work. Adding `order:score` makes it so that there's no results.

**Comment by Bionus** [comment]
Indeed, it would seem that the `sort:` modifier is getting removed from Derpibooru searches. I'll push a fix.
