### ISSUE TITLE
Add tag counts post-filters

### ISSUE THREAD

**Issue by bizefadira** [Bionus/imgbrd-grabber#1741]
**Is your feature request related to a problem? Please describe**

I'm looking for a way to post-filter or blacklist non-empty values for tokens like `%copyright%` (except for `orginals`, but sites like yande.re don't even support said tag). I have read the wiki but I haven't found a way to do this, except for using a filename condition like `-original & (%copyright% != "")`.

**Describe the solution you'd like**

Danbooru has a feature where you can request the number for some specific type of tag, as described [here](https://danbooru.donmai.us/wiki_pages/43049#dtext-n2-3-6). I think it would be an elegant solution to be able to make a blacklist filter like for example `copytags:1.. -original`. Unfortunately, those tag counts don't work on any other website.

**Describe alternatives you've considered**

As of now, I haven't found a solution yet except for using a filename condition to filter these out and saving them in a distinct folder.

**Comment by Bionus** [comment]
> I'm looking for a way to post-filter or blacklist non-empty values for tokens like %copyright%

Have you tried simply using `%copyright%` as a blacklist/post-filter? It should filter results without any copyright tag.

Tokens can be used in the blacklist/post-filter and will be considered as "matching" if the token exists and is non-empty (empty string, 0, no tags, etc.).

> except for orginals, but sites like yande.re don't even support said tag

So the image should be filtered if it has neither the "original" tag nor any copyright tag, from what I understand? In that case, you should just add one line to your blacklist: "-original -%copyright%".

You can imagine the blacklist as a big post-filter, with each line separated by a "OR", and each tag on each line by a "AND".

> I think it would be an elegant solution to be able to make a blacklist filter like for example copytags:1.. -original

It wouldn't cost anything to add a `copytags` token (and others from this family), but I'd be more inclined to do something like `%copyright:count%`.

**Comment by bizefadira** [comment]
Thank you for the fast reply, Bionus!

My apologies, I should have been more clear about what I'm trying to achieve with my blacklist rule. In the end, I want the results to either have the tag "original" or have it an empty %copyright% token. Therefore, my blacklist rule should be `%copyright% -original` instead. Additionally, I'm currently merging the results for 3 sources: Danbooru, Gelbooru and Yande.re.

I did try out the %copyright% token as a blacklist/post-filter, but I had poor results while I was merging those different sources. I've investigated it a little further and it seems like Danbooru is correctly responding to the %copyright% token, while it doesn't seem to work for Gelbooru and Yande.re.

For the latter two sources, it seems like the tag types are not properly loaded while I'm searching. I can see non-original images (I hide the blacklisted images) and when I click on them I can see that it takes about one second to correctly load the tag types. When I close said image again and reopen it, the blacklist rule seems to kick in properly. I've made some screenshots [here](https://imgur.com/a/xorKV1r). Could this be a bug or a limitation the API of the source?

Either way, I still think it would be a great addition to filter based on the number of a specific type of tag. Some token like `%copyright:count%` seems great to me, if possible.

**Comment by Bionus** [comment]
> My apologies, I should have been more clear about what I'm trying to achieve with my blacklist rule. In the end, I want the results to either have the tag "original" or have it an empty %copyright% token. Therefore, my blacklist rule should be `%copyright% -original` instead.

Indeed, it seems that I misunderstood.

|Copyright|Original| |Download|Blacklist|
|-----|-----|-----|-----|-----|
|❌|❌| |✔️|❌|
|❌|✔️| |✔️|❌|
|✔️|❌| |❌|✔️|
|✔️|✔️| |✔️|❌|

So it would seem that the correct blacklist is indeed `%copyright% -original`.

> For the latter two sources, it seems like the tag types are not properly loaded while I'm searching. I can see non-original images (I hide the blacklisted images) and when I click on them I can see that it takes about one second to correctly load the tag types. When I close said image again and reopen it, the blacklist rule seems to kick in properly. I've made some screenshots here. Could this be a bug or a limitation the API of the source?

Indeed, it's a limitation of their API, which doesn't give the full tag information.

You can download Gelbooru's and yande.re's tag database in "Tools > Tag loader" if you want to go around this problem. It'll download all tag information for those sources, therefore properly categorizing them later.

But even without this, blacklisting should still work in batch downloads as it is done **after** loading the full tag information.

> Either way, I still think it would be a great addition to filter based on the number of a specific type of tag. Some token like %copyright:count% seems great to me, if possible.

Indeed, but it won't help your case, if the tags aren't even properly recognized as copyrights in the first place.

Also, I think I spoke too fast, as `%copyright:count%` wouldn't be able to be used in the "condition" syntax. I guess it would look more like `copyright_count:1..` or something like this.

**Comment by bizefadira** [comment]
> You can download Gelbooru's and yande.re's tag database in "Tools > Tag loader" if you want to go around this problem. It'll download all tag information for those sources, therefore properly categorizing them later.

Actually, I did make a tag database beforehand for Yande.re (not for Gelbooru yet), but I doesn't seem to work properly on my end. I've looked into the generated"tags.txt" file and this is a small part of it:

`honihoninosu,-1
claudia_madobe,-1
comta,-1
sowel_(sk3),-1
jericho_(girls_frontline),-1
hakkenden:_touhou_hakken_ibun,-1
black_rabbit,-1
lemoo,-1
takeyuu,-1
mobu-312,-1
amewarashi-1,-1
doll_licca,-1
saber_alter,-1
nopan,-1
saegusa_wakaba,-1
akira_(spectral_souls),-1
joseph_souma_merengue,-1
ren'ai_kyoushitsu,-1
dead_rising,-1
kurusu_rio,-1
h2so4kancel,-1`

It seems like all tags have a tag-type numbered as -1. This is for instance not the case for my tag database of Danbooru (tag-type number goes from 1 to 5 there).


> But even without this, blacklisting should still work in batch downloads as it is done after loading the full tag information.

Yes, I tested the batch downloads and here is everything working as expected.

**Comment by Bionus** [comment]
Oh, then that would mean that the tag API has some issue and didn't load the tag type properly. I'll investigate and see to fix it.

**Comment by bizefadira** [comment]
> Oh, then that would mean that the tag API has some issue and didn't load the tag type properly. I'll investigate and see to fix it.

I did try to build a tag database for Gelbooru today, but I encountered the same issue here. I took a few hours to download the +500.000 tags, but the text file also has -1 for all tags.

As a current work-around, I've copied the tag database of Danbooru into the folder of Gelbooru and Yande.re which seems to help to some extend.

Either way, thanks again for the help up till now.

**Comment by bizefadira** [comment]
I've found out a way to correctly build the tag database for Yande.re:

All I had to do was just copy the "tag-types.txt" generated from danbooru.domai.us in the respective folder, which just contains the following data:
`0,general
1,artist
3,copyright
4,character
5,meta`

After doing this, the tag database was built correctly. Checking the tag database afterwards has the following results now:
`swatty,4
vierzeck,1
hagure_makenshi_to_kyoumei_shoujotai,3
kanou_maki,4
suzuhira_hiro,1
snow_(mar),4
yuusha_ni_narenakatta_ore_wa_shibushibu_shuushoku_o_ketsui_shimashita.,3
asahina_kyouko_(amatsutsumi),4
kuraue_hinata,4`
