### ISSUE TITLE
Downloading comics

### ISSUE THREAD

**Issue by EvilNick3019** [Bionus/imgbrd-grabber#1743]
I was just wondering when downloading from sites like NHentai if there was a way to sort each comic downloaded into separate files for each comic, I have looked around and i cant seem to find a way to do this. Is there a way to do this?

**Comment by NepkoFever** [comment]
For comics, I just use %count%.%ext% for the filename, which gives each file in a download batch an unique filename (01, 02, 03... etc) and automatically makes the file order chronological to the comic. Of course, any following downloads won't have unique filenames though, starting again from 01, so you'd have to change the download folder each time, but that is what you'd likely want to do for comics anyway.
Only thing I find annoying with this method is the fact there's no easy way to copy the doujin names with Grabber, from what I know so far. It takes annoyingly long to type the folder names the exact same as doujin names.

**Comment by Bionus** [comment]
> I was just wondering when downloading from sites like NHentai if there was a way to sort each comic downloaded into separate files for each comic, I have looked around and i cant seem to find a way to do this. Is there a way to do this?

>  Only thing I find annoying with this method is the fact there's no easy way to copy the doujin names with Grabber, from what I know so far. It takes annoyingly long to type the folder names the exact same as doujin names.

Have you tried using `%gallery.name%` and `%gallery.id%`? They should contain the comic's name and ID respectively, allowing you to group them by comic when downloading them.

> For comics, I just use %count%.%ext% for the filename, which gives each file in a download batch an unique filename (01, 02, 03... etc) and automatically makes the file order chronological to the comic. Of course, any following downloads won't have unique filenames though, starting again from 01, so you'd have to change the download folder each time, but that is what you'd likely want to do for comics anyway.

You can also use `%position%` for the relative position of an image in its gallery. Or `%position:length=3%` if you want numbers looking like `001`, `002`, etc.

-----

So for downloading galleries, you can use something like `%gallery.name% (%gallery.id%)/%position% - %md5%.%ext%` as filename.

**Comment by RiabikovR** [comment]
Wish I knew that a bit sooner.
What if I want to download files that contain both galleries and single images?

**Comment by Bionus** [comment]
Then you can do a conditional filename in your settings, with `gallery.name` as condition and your gallery-specific filename as value.

Or you can do a conditional directly in your filename, such as:
```
<%gallery.name% (%gallery.id%)/%position% - >%md5%.%ext%
```

See the filename docs for details:
https://bionus.github.io/imgbrd-grabber/docs/filename.html
