### ISSUE TITLE
No color outline on any image from any source

### ISSUE THREAD

**Issue by ayoits0913** [Bionus/imgbrd-grabber#1752]
I didn't even realize this was a thing until i checked the settings, but no image I've ever seen while using this program has been outlined in any color whatsoever. Windows 10 64bit

**Comment by Bionus** [comment]
Except for the favorites (unless you explicitly search a favorite tag) and blacklisted images (if they are not totally hidden), outlines depend on the information provided by the sources themselves. Mainly parent/children relationships between images.

For example, Danbooru provides such information (except for the regex source).
I just tried and could see outlines for some random Danbooru search.
