### ISSUE TITLE
Konachan has a non-default hash salt

### ISSUE THREAD

**Issue by RiabikovR** [Bionus/imgbrd-grabber#1754]
**Bug description**

According to [https://konachan.com/help/api](https://konachan.com/help/api), konachan's hash salt is "So-I-Heard-You-Like-Mupkids-?--your-password--".

**Steps to reproduce**

1. Go to 'Sources>konachan.com, options>login'
2. Input login credentials
3. Use grabber to retrieve a page from konachan
4. Go to log and get login and password_hash values from logged page links
5. Open browser and go to https://konachan.net/user/home?login=LOGIN&password_hash=HASH

**Expected behavior**

Get logged into account

**Comment by RiabikovR** [comment]
Actually, it looks like every Moebooru site has it's own salt.
It's possible that I'm blind and such option was there all along, but it would be nice to have a separate field for salt or maybe an option to outright use password hash directly.

**Comment by Bionus** [comment]
In that case, I guess I'll have to add another setting to some sources, allowing to change the source's salt (which is currently hard-coded per source type).

> Actually, it looks like every Moebooru site has it's own salt.

I only know konachan.com and yande.re. The former indeed has a different hash, but the latter uses the default, danbooru-inherited one. What other Moebooru source do you know that uses a different hash?

> It's possible that I'm blind and such option was there all along, but it would be nice to have a separate field for salt or maybe an option to outright use password hash directly.

While I wouldn't say you'd be blind for not knowing that, you can simply use the hash as your password and it should work.

Grabber won't hash passwords that already look like a hash.

**Comment by RiabikovR** [comment]
[Sakugabooru](https://www.sakugabooru.com/) is an example that made me notice.

**Comment by Bionus** [comment]
I just pushed a change that allows users to override the salt, in the "Login" tab.
Just change it to what is written in the API docs and it should work 👌

**Comment by RiabikovR** [comment]
Well done!
