### ISSUE TITLE
"Related tags" are grabbed instead of actual image tags on Shimmie 2 boards

### ISSUE THREAD

**Issue by RiabikovR** [Bionus/imgbrd-grabber#1755]
**Bug description**

On Shimmie 2 boards with default composition, where sidebar contains "Related tags", and actual tags are listed under the image, grabber grabs the former.

**Steps to reproduce**

1. Using grabber, lookup an image on https://shimmie.shishnet.org/v2/, for example
2. Note tags
3. Open image in browser
4. Look at the "Related tags" section in the sidebar and at the "Tags" list under the image

**Expected behavior**

Tags listed in grabber match the list under the image

**Additional context**

paheal.net has image tags instead of "Related tags", so everything works fine there.

**Comment by Bionus** [comment]
Note that this only seem to happen *after* clicking an image.

When hovering the thumbnail beforehand, the tags are correct. They are replaced by the "related tags" when the image loads.
