### ISSUE TITLE
Haven't been able to download much of anything in days

### ISSUE THREAD

**Issue by GuyInDogSuit** [Bionus/imgbrd-grabber#1757]
**Bug description**

Grabber hasn't been downloading many images at all. It consistently just ignores most images as if I've either blacklisted one of the tags or already downloaded the images.

**Steps to reproduce**

1. Search for anything.
2. Click on 'Get all.'
3. Tab to 'Downloads.'
4. Click 'Download.'
5. Watch as it downloads nothing and results say most, if not everything, was ignored.

**Expected behavior**

I expected it to download at least 'something.' But usually it's not the case.

**System information**

- OS: Windows 10 Pro x64
- Grabber version: 7.1.1

**Comment by RiabikovR** [comment]
I'm not a developer, but that's a bit vague for a bug report.
There should be a "Log" tab, the rightmost in the tab list. It details the process of downloading images, including what images are already existing, and what tags caused certain images to be ignored.
(If there is no "Log" tab, enable it by going to Tools>Options>Interface>Log and checking "Show log". You may have to restart Grabber after that).
