### ISSUE TITLE
How to run on Mac

### ISSUE THREAD

**Issue by vivin4** [Bionus/imgbrd-grabber#1759]
Hello,

I'm a Mac user and really an extreme beginner at using Terminal, so I had some issues trying to get the grabber work. 

So I downloaded the zip file and have been following Mac instructions. 

I downloaded Xcode, opened Terminal and downloaded Homebrew. I was able to install `brew install qt5` as well.

As for the fourth step, I opened .bash_profile in the Text Editor by using `touch ~/.bash_profile; open ~/.bash_profile` and pasted `export PATH="/usr/local/Cellar/qt5/5.13.0/bin"` (instructions saide version number 5.7.0 but I changed it to the updated version 5.13.0 as suggested -I hope this is correct-). I saved this text file.

But from here on I couldn't do much.

For the "Compiler" step, I did install `brew install gcc` but I don't know how to "use the g++ compiler to compile the program." now.

I searched how to do this, but I'm getting much; do I need to go through downloading "Command Line Tools for Xcode" pkg for this, or is it not necessary? Is there any other step I should take? How do I compile the program?

Am I supposed to use the .sh files here at some point and how?

Can somebody please explain this step to me about how to? 

Because since I can't get through this step, I don't understand much about the last one (Running) either.

I'm so sorry for asking what might be very easy for everyone else, I'm really a rookie here...

Thank you

**Comment by Bionus** [comment]
Hello 🙂 

Have you tried simply running `./build-mac.sh` from the root of the repository?
It should install everything for you, with nice prompts and all. You don't need to run every command manually.

**Comment by Bionus** [comment]
Closing the issue for lack of updates.

Also, there is now another solution for running on Mac, and it's to simply download the DMG file. Currently, it's only available for [nightly releases](https://github.com/Bionus/imgbrd-grabber/releases/nightly) but will land in stable ones in the next update.
