### ISSUE TITLE
Download fails on anime-pictures.net when logged in from non-english speaking countries

### ISSUE THREAD

**Issue by RiabikovR** [Bionus/imgbrd-grabber#1760]
**Bug description**

When logging into an anime-pictures from a non-english speaking country, browser (in this case Grabber) gets assigned a "sitelang" cookie, containing user's two-letter country code.
When visiting any page with said cookie, user gets redirected to a page in corresponding language. This redirect interferes with Grabber grabbing the link to an image.

**Steps to reproduce**

1. Use proxy with an ip of a RU/JP/ZH/ES/DE/FR-speaking country
2. Input your credentials in anime-pictures' site options
3. Look something up
4. Press "Get all button"
5. Go to "Downloads" tab and start the download

**Expected behavior**

Images get downloaded as usual.

**Additional context**

This can be quickfixed manually by adding "sitelang" cookie with value "en" to anime-pictures' source options.

**Comment by stalkerg** [comment]
My website just recognizes browser language for generating sitelang cookie and never tried to check ip or country.

**Comment by RiabikovR** [comment]
That does not change the case for Grabber.

**Comment by Bionus** [comment]
What if you set the `sitelang` cookie manually to `en` in the source settings?
Does that fix the issue? If so, I can add it to the default settings.

I'll also look as to why the correct link can't be found.

**Comment by RiabikovR** [comment]
Yeah, that's exactly what I did.

**Comment by Bionus** [comment]
Oh my bad, it was indeed mentioned at the bottom of the ticket, I guess I missed it sorry 😅 

I'll fix other languages and add the cookie to the default settings ASAP.
