### ISSUE TITLE
Can't run from AUR or install from source

### ISSUE THREAD

**Issue by Faethair** [Bionus/imgbrd-grabber#1761]
**Bug description**
From source: when using `mv "build/gui/gui" "release/Grabber"` I get:
`mv: cannot stat 'build/gui/gui': No such file or directory`

When building from AUR, it installs successfully but I can't launch it from terminal or find it in dmenu.

**System information**

- OS: Manjaro Linux
- Grabber version: 7.1.1 from source, 7.1.1-1 in AUR

**Comment by Faethair** [comment]
Works opening from terminal, but none of the options will stick (for example, the "first launch" menu will always appear, and the destination folder will reset). When launching I get a whole row of:
`QIODevice::write (QFile, "/home/ice/.config/Bionus/Grabber/main.log"): device not open`

**Comment by Faethair** [comment]
Manually creating a blank file at /home/ice/.config/Bionus/Grabber/main.log made the "device not open" message go away, but the matter of settings not saving has remained.

**Comment by Faethair** [comment]
Contents of main.log:
[main.log](https://github.com/Bionus/imgbrd-grabber/files/3562977/main.log)

**Comment by FichteFoll** [comment]
See #1018 regarding settings not being saved.
