### ISSUE TITLE
Can't download from Twitter. Error code 215 'Bad authentication data'

### ISSUE THREAD

**Issue by squaretotopo** [Bionus/imgbrd-grabber#1763]
Can't download from Twitter, no results are displayed no matter what username or keyword is entered in the search field.
When I click on the Twitter link to visit the site, I get the error 215 "Bad authentication data". It seems the api can't be accessed without authentication even if it's public.
I also tried entering my username and password in the login tab within grabber but it fails. Also tried manually adding my internet browser's cookie data and values but nothing works.

OS Windows 10
Grabber 7.1.1 (x64)

[main.txt](https://github.com/Bionus/imgbrd-grabber/files/3577428/main.txt)

**Comment by pencilbook** [comment]
How do you use Twitter on Grabber?
