### ISSUE TITLE
Question: How to strip _(artist) from %search% tag?

### ISSUE THREAD

**Issue by Lovewyrm** [Bionus/imgbrd-grabber#1764]
Sometimes artist names are like common tags, so many sources use the suffix _(artist) to distinguish that.
Since I save everything by artist on my harddrive and I know for myself that the name at the top level is meant to be an artist, I don't need _(artist) in the folder or the filename.

I guess javascript is the key, but I don't know how... therefore I humbly request a spoon with the solution to be jabbed into my face.

**Comment by Bionus** [comment]
I'm not sure I understand.

You say you save by artist, so why do you want to strip this from the `search` token? Shouldn't you save it using `%artist%` and want to strip the `artist` token then?

As for JavaScript, it should be something like (at the beginning of the filename):
```js
if (artist.endsWith(" (artist)")) {
    artist = artist.substr(0, artist.length - 9);
}
```

**Comment by Lovewyrm** [comment]
I just want to remove "_(artist)" from a search if it's there, yes. Thanks.

Imagine if an artist was named "green_hair", which is also a tag for, well, "green hair", then the tag for the artist would be "green_hair_(artist)"
Since I know that the top level folder would be an artist, I don't need "_(artist)".

Stripping it from the artist tag itself isn't reliable since sometimes the tag resolves to "multiple artists", but still connected to the artist I search for.
That's why I make the artists my seach term, as well as the top level folder for all the images of the artist.

Editing your solution for search gave me a segfault,  (valid filename, though) but that also happens for artist, but I'm not sure if that's not due to something I did. I'll look into that later, but yeah thanks so far.

**Comment by Lovewyrm** [comment]
The segfaults happened due to an empty "conditional filename" setting related to question which I forgot about.
