### ISSUE TITLE
Issues logging into Pixiv

### ISSUE THREAD

**Issue by dalekman9999** [Bionus/imgbrd-grabber#1765]
**Cannot log into Pixiv through the program.**

The program is refusing to let me log into Pixiv, When going to connect, it says failure.
**Steps to reproduce**

1. Go to 'Pixiv site options'
2. Click on 'Login'
3. Enter login details 

**Expected behavior** 
To let me log into Pixiv.

Copy from the log when attempting to log in

[02:35:04.212][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"103:pixiv ID\u3001\u307e\u305f\u306f\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u6b63\u3057\u3044\u304b\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","code":1508}}}
[02:35:04.212][Info] [www.pixiv.net] Login finished: failure.

**Comment by Faethair** [comment]
I also have this problem. Copied from my log:
```
[13:41:18.184][Info] [www.pixiv.net] Logging in...
[13:41:19.663][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
[13:41:19.663][Info] [www.pixiv.net] Login finished: failure.
```

**Comment by Bionus** [comment]
> ```[02:35:04.212][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"103:pixiv ID\u3001\u307e\u305f\u306f\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u6b63\u3057\u3044\u304b\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","code":1508}}}```

The error reads as:
```
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
```

In English:
```
103: Check if the pixiv ID, e-mail address and password are correct.
```

Are you sure you provided the correct credentials? i.e. email instead of username.
Did it work before?

-----

> ```[13:41:19.663][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}```

Never saw this error. 🤔 
Same question, did it work before, or is it the first time you try to login on Pixiv with Grabber?

**Comment by dalekman9999** [comment]
I havent tried it before. It was the first time i had attempted to. And it works fine logging in onto the site itself through a web browser, so i cant see it being details. 
Ill get back to you later after reading tbrough that thread, currently busy rn, will read through it in a few hours hope thats ok

**Comment by Faethair** [comment]
> > `[13:41:19.663][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}`
> 
> Never saw this error. thinking
> Same question, did it work before, or is it the first time you try to login on Pixiv with Grabber?
> 
> Could it be related to [upbit/pixivpy#83](https://github.com/upbit/pixivpy/issues/83)?
It used to work, but that was a while ago on an earlier version. I made sure to use email rather than username, and that my details were correct.

**Comment by Bionus** [comment]
> Just to make sure, consumer key should be MOBrBDS8blbauoSck0ZfDbtuzpyT and consumer secret should be lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj, correct?

Indeed.
I could reproduce just now, so I'll start seeing how to fix that 👌

**Comment by andrew-suh** [comment]
I feel I should mention that I only got pixiv to work once I added the phpsession cookie. Unfortunately, it looks like it expires every month. Is this the wrong approach? I have also checked that the consumer key/secret is correct in my settings.

**Comment by Spyridion** [comment]
I want to mention that I only got pixiv to work once I added the phpsession cookie, which expires monthly. Is this the wrong approach? I have also checked that the consumer key/secret is correct in my settings.

**Comment by TogarUshindi** [comment]
Just for the record, login is failing on my end as well.

**Comment by Bionus** [comment]
> Just for the record, login is failing on my end as well.

> I want to mention that I only got pixiv to work once I added the phpsession cookie, which expires monthly. Is this the wrong approach? I have also checked that the consumer key/secret is correct in my settings.

Are you using the [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) version? I just tried and it was working well there.

Remember to use your email as username in the source settings, as Pixiv only accepts email now.
