### ISSUE TITLE
ah shit, here I go again.

### ISSUE THREAD

**Issue by General-Trident** [Bionus/imgbrd-grabber#1769]
I can't tell if it's a bug or it's just me again.
This is my second post. So basically I just moved all the files to my external storage. I didn't move the destination folder, just the files. I don't even know if this is the cause of my problem. I'm simply saying this just in case if it helps and also because it's the last thing I've done after not accessing Grabber for a long time, but the thing is this right here:
![image](https://user-images.githubusercontent.com/52889250/64891653-be739980-d69c-11e9-8072-f84c2878c033.png)

What happened here was that I couldn't access anything anymore. Literally nothing, like everytime I clicked the search button, it gave me blank. I tried to search the "No valid source of the site returned result" log, but the other Grabber users who already posted this issue with the same warning log, all they told me is that this is supposed to happen when you reached more than the past page limit (sorta like if the search result page limit is 5 but you go to page 6 instead). I didn't even get to page 1 lmao. Please help. I appreaciate it.

**Comment by RiabikovR** [comment]
Try copying the links into browser and seeing what it comes up with.

**Comment by General-Trident** [comment]
> 
> 
> Try copying the links into browser and seeing what it comes up with.

the link works just fine. It brought me to a Gelbooru page with Tsuujou Kogeki in it. There's nothing wrong with it. It's still not showing in Grabber tho
