### ISSUE TITLE
Date range for pulling images.

### ISSUE THREAD

**Issue by Anongreen** [Bionus/imgbrd-grabber#1770]
For the search engine date calendar, I can only choose 1 date and it'll pull up what images are uploaded on the site that day.
Is it possible to pull image in a date range like for example 09/02/2019-09/07/2019 rather then picking 1 day at a time so that only images during those period would be pulled up?
If such feature already existed, sorry for the trouble.

PS: Is there like an instructions on how to use this software in detail like how do post filtering work, what does the tools do or etc. I try looking online how to use these but I have zero experience in programming or understanding what they do at all.

Also, thank you for adding sites like nhentai, pixiv, and stuff. The exhentai site came back but I can't seem to pull any images from it.

**Comment by Bionus** [comment]
The UI indeed only allows to pick one date, but you can indeed search date ranges if you want, though it depends on whether the site you search supports it or not (but usually, if it supports one date it supports ranges also).

Grabber follows the Danbooru format for searches, blacklists and post-filtering:
https://danbooru.donmai.us/wiki_pages/43049

So if you want to search a date range, you should do something like `date:2019-09-02..2019-09-07`.

> PS: Is there like an instructions on how to use this software in detail like how do post filtering work, what does the tools do or etc. I try looking online how to use these but I have zero experience in programming or understanding what they do at all.

Not really.
There is the docs, but they aren't very complete: https://bionus.github.io/imgbrd-grabber/docs/

**Comment by Anongreen** [comment]
Thank you!

**Comment by Bionus** [comment]
I clarified all of this in the documentation:
https://bionus.github.io/imgbrd-grabber/docs/search.html

I'll close this issue since the question has been answered 😄
