### ISSUE TITLE
Gallery name tokens always return false in conditionals

### ISSUE THREAD

**Issue by RiabikovR** [Bionus/imgbrd-grabber#1772]
(I'm on a mobile, so won't be able to fill a proper ticket).
Steps to reproduce go something like that:
1. Use a conditional name like ```<%gallery.name%.%gallery.id%/%position%>.%md5%.%ext%```
2. Go grab some galleries
3. Notice files only having unconditional names
4. Invert gallery tags so the name is: ```<!%gallery.name%.!%gallery.id%/%position%>.%md5%.%ext%```
5. Filenames work as intended aside from %position% token, which gets appended even if the image is not in a gallery.

**Comment by Bionus** [comment]
Indeed, it would seem that the conditionals don't support the `parent.token` syntax!
I just pushed a fix, good catch! 👌
