### ISSUE TITLE
Fails to compile on macOS

### ISSUE THREAD

**Issue by elsorino** [Bionus/imgbrd-grabber#1777]
**Bug description**

Compiling grabber does not work on macOS

**Steps to reproduce**

Attempt compile on macOS

**Expected behavior**

Compiles successfully

**Context**

Failed to build imgbrd-grabber.
Last 40 lines of the log file follow.
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/tests.dir/src/auth/auth-test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/elso/imgbrd-grabber/tests/src/auth/auth-field-test.cpp:6:
/Users/elso/imgbrd-grabber/tests/src/catch.h:5:10: fatal error: 'vendor/catch/single_include/catch2/catch.hpp' file not found
#include "vendor/catch/single_include/catch2/catch.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/tests.dir/src/auth/auth-field-test.cpp.o] Error 1
In file included from /Users/elso/imgbrd-grabber/tests/src/commands/sql-worker-test.cpp:6:
/Users/elso/imgbrd-grabber/tests/src/catch.h:5:10: fatal error: 'vendor/catch/single_include/catch2/catch.hpp' file not found
#include "vendor/catch/single_include/catch2/catch.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/tests.dir/src/commands/sql-worker-test.cpp.o] Error 1
In file included from /Users/elso/imgbrd-grabber/tests/src/concurrent-multi-queue-test.cpp:5:
/Users/elso/imgbrd-grabber/tests/src/catch.h:5:10: fatal error: 'vendor/catch/single_include/catch2/catch.hpp' file not found
#include "vendor/catch/single_include/catch2/catch.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /Users/elso/imgbrd-grabber/tests/src/downloader/batch-downloader-test.cpp:4:
/Users/elso/imgbrd-grabber/tests/src/catch.h:5:10: fatal error: 'vendor/catch/single_include/catch2/catch.hpp' file not found
#include "vendor/catch/single_include/catch2/catch.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [tests/CMakeFiles/tests.dir/src/concurrent-multi-queue-test.cpp.o] Error 1
In file included from /Users/elso/imgbrd-grabber/tests/src/downloader/download-query-group-test.cpp:4:
/Users/elso/imgbrd-grabber/tests/src/catch.h:5:10: fatal error: 'vendor/catch/single_include/catch2/catch.hpp' file not found
#include "vendor/catch/single_include/catch2/catch.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/tests.dir/src/downloader/download-query-group-test.cpp.o] Error 1
[ 58%] Linking CXX executable Grabber-cli
1 error generated.
make[2]: *** [tests/CMakeFiles/tests.dir/src/downloader/batch-downloader-test.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 58%] Built target gui_autogen
[ 58%] Built target cli
make: *** [all] Error 2

**Screenshots**

**System information**

- OS: macOS 10.14.6
- Grabber version: Latest dev

**Additional context**
Installing catch2 with homebrew does not fix the problem

**Comment by Bionus** [comment]
Catch2 is loaded as a git sub-module, and can be found in `tests/src/vendor/catch/`:
https://github.com/Bionus/imgbrd-grabber/tree/develop/tests/src/vendor

If you can't find it in your local repo, you should make sure that when you pulled the Grabber sources, you also pulled the sub-modules:
```
git clone https://github.com/Bionus/imgbrd-grabber.git
git submodule update --init --recursive
```

**Comment by elsorino** [comment]
Welp that was my bad, thanks!
