### ISSUE TITLE
Automatically generate MacOS DMG files in Travis

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#1778]
In the same way Windows releases are auto-generated, we could do the same for MacOS, both for nightly releases and official releases.

Thanks to PR #1776, generating DMG files is now much easier.

⚠️ The auto-updater should also be updated accordingly to download the correct files.

**Comment by Bionus** [comment]
You'll find newly-generated DMG files in the nightly release:
https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly

**Comment by elsorino** [comment]
No dark mode integration in these dmgs, `osx_image: xcode10.2` should fix that, but I have no idea if this will make them unusable on versions lower than Mojave. Everything I've tested works perfectly otherwise.

As for homebrew casks, most of them for nightly/dev versions just use auto-updaters
https://github.com/elsorino/homebrew-elso/blob/master/Casks/grabber.rb

**Comment by Bionus** [comment]
> No dark mode integration in these dmgs

I guess that when you say "dark mode", you mean something specific to macOS and not just the crappy dark skin bundled with Grabber right?

> osx_image: xcode10.2 should fix that, but I have no idea if this will make them unusable on versions lower than Mojave.

I'm not very proficient with macOS binaries, but it shouldn't matter here. If the thing was properly done by Apple, it should be conditional to the host OS, not the building OS. I'll add this flag to Travis.

> Everything I've tested works perfectly otherwise.

🎉🎉🎉

I just noticed that I seem to have forgotten to add a symlink to `/Applications` though.

> As for homebrew casks, most of them for nightly/dev versions just use auto-updaters

How do auto-updates work on macOS?
On Windows, we download the installer, close the program, then run the installer. How would that work with a DMG file? Is the only solution to use [Sparkle](https://sparkle-project.org/)?

>  https://github.com/elsorino/homebrew-elso/blob/master/Casks/grabber.rb

Shouldn't this cask be named `grabber-nightly` though? 😄

Talking about casks, do they _have to_ be put in https://github.com/Homebrew/homebrew-cask, or can they be "hosted" in the application owner's repository? Making a PR with every real Grabber update sounds like a pain.

**Comment by elsorino** [comment]
>I guess that when you say "dark mode", you mean something specific to macOS and not just the crappy dark skin bundled with Grabber right? 

Yeah here's a comparison between the two, left is grabber's and right is macos dark

![Screen Shot 2019-09-24 at 23 09 23](https://user-images.githubusercontent.com/30331607/65566362-1a161080-df42-11e9-8ce9-42afe98cff1d.png)

>How do auto-updates work on macOS

Sparkle is what's used 90% of the time for auto-update solutions, I've had a apps just prompt you to check for an update with a link to the download site.

>Shouldn't this cask be named grabber-nightly though? 😄

Yep my bad lol

>Talking about casks, do they have to be put in https://github.com/Homebrew/homebrew-cask, 
or can they be "hosted" in the application owner's repository? 

They can be anywhere, the [main documentation at brew.sh](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) should help

**Comment by Bionus** [comment]
Since auto-dmg generation is done, I'll move tap/cask discussion to issue #1869.
