### ISSUE TITLE
Filter retweets & API keys

### ISSUE THREAD

**Issue by elsorino** [Bionus/imgbrd-grabber#1785]
**Is your feature request related to a problem? Please describe**

At the moment, using twitter often brings in unrelated images due to showing retweets as well as regular tweets.

**Describe the solution you'd like**

Method to filter retweets

**Describe alternatives you've considered**

Don't know of any

**Additional context**

https://gist.github.com/shobotch/5160017 contains some official twitter keys, perhaps one of these should be in by default?

**Comment by Bionus** [comment]
> Method to filter retweets

I just made a commit to add support for two "meta"-tags for Twitter:
* Re-tweets: `retweets:yes` and `retweets:no` (default: yes)
* Replies: `replies:yes` and `replies:no` (default: yes)

> https://gist.github.com/shobotch/5160017 contains some official twitter keys, perhaps one of these should be in by default?

Indeed, thanks for the link!
I added the Android API keys as default. 👍
