### ISSUE TITLE
Folder naming by artistname/tags

### ISSUE THREAD

**Issue by HawkSoul** [Bionus/imgbrd-grabber#1790]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HawkSoul** [comment]
Dear devs
Would it be possible to add this?
For example: %md5%.%ext% is used for file naming
but could it be possible to make this work for folder creation?
for example: C:\Pictures\Sankaku\%tags%
so that when image is downloaded it will be automatically be put in the folder created by tag.

**Comment by Bionus** [comment]
What tags are you talking about?
You can already use `%artist%` in your filename.

Have you seen https://bionus.github.io/imgbrd-grabber/docs/filename.html?

**Comment by HawkSoul** [comment]
Hi Bionus,
thanks for your quick response.
I have tried this tag: %artist%/%md5%.%ext%
and it looked almost like doing what I wanted, but then I saw it creating multiple artist names with some other tags
example: "mool yueguang" is the artist, and the folder of it is created, which is good, but it has also created many other folders/tags(see attachment)
Any way to avoid this?
Sorry if I missed that somewhere in the link you sent.

![Annotation 2019-10-02 090307](https://user-images.githubusercontent.com/56041253/66024195-7b665280-e4f3-11e9-84e0-ddcf82de3a45.png)

**Comment by sbobbo** [comment]
What I do for this is to put %artist% in the filename, but %search% in the foldername.

X_Grabber-%search%-%websitename%\%artist%-%date:format=yyyy-MM-dd%-<%copyright%-><%character%->%md5%.%ext%

https://github.com/Bionus/imgbrd-grabber/wiki/Filename

**Comment by Bionus** [comment]
>  and it looked almost like doing what I wanted, but then I saw it creating multiple artist names with some other tags
> example: "mool yueguang" is the artist, and the folder of it is created, which is good, but it has also created many other folders/tags(see attachment)
> Any way to avoid this?

By default, Grabber takes all artists present on the image and merge them. There are more options to choose from in the settings ("Save > Tokens > Artist" category or something).

For your example, it would seem that your source uses two different orthography for the same artist. To avoid having useless folders like "mool yueguang+mool yuegang", you should mark one of the two as "ignored". This way, it will be treated as a normal tag instead of an artist tag, and disappear from the `%artist%` token. To do so, open an image with the tag, right click the tag and choose "ignore" (with the eye icon beside).

**Comment by HawkSoul** [comment]
> What I do for this is to put %artist% in the filename, but %search% in the foldername.
> X_Grabber-%search%-%websitename%\%artist%-%date:format=yyyy-MM-dd%-<%copyright%-><%character%->%md5%.%ext%
> https://github.com/Bionus/imgbrd-grabber/wiki/Filename

sorry but that is way too complex, I want to keep it simple: folder/artistname/md5.ext
but thx for sharing your settings

**Comment by HawkSoul** [comment]
> and it looked almost like doing what I wanted, but then I saw it creating multiple artist names with some other tags
> example: "mool yueguang" is the artist, and the folder of it is created, which is good, but it has also created many other folders/tags(see attachment)
> Any way to avoid this?
> 
> By default, Grabber takes all artists present on the image and merge them. There are more options to choose from in the settings ("Save > Tokens > Artist" category or something).
> For your example, it would seem that your source uses two different orthography for the same artist. To avoid having useless folders like "mool yueguang+mool yuegang", you should mark one of the two as "ignored". This way, it will be treated as a normal tag instead of an artist tag, and disappear from the %artist% token. To do so, open an image with the tag, right click the tag and choose "ignore" (with the eye icon beside).

then that means I have to watch out for every single tag.
but I wanted Grabber to do it for me. :(
simply put: I copy an artist to grabber, I press download all and grabber will download all the images of that artist in the folder which it creates by the name of that artist/tag.

**Comment by sbobbo** [comment]
> 
> 
> > and it looked almost like doing what I wanted, but then I saw it creating multiple artist names with some other tags
> > example: "mool yueguang" is the artist, and the folder of it is created, which is good, but it has also created many other folders/tags(see attachment)
> > Any way to avoid this?
> > By default, Grabber takes all artists present on the image and merge them. There are more options to choose from in the settings ("Save > Tokens > Artist" category or something).
> > For your example, it would seem that your source uses two different orthography for the same artist. To avoid having useless folders like "mool yueguang+mool yuegang", you should mark one of the two as "ignored". This way, it will be treated as a normal tag instead of an artist tag, and disappear from the %artist% token. To do so, open an image with the tag, right click the tag and choose "ignore" (with the eye icon beside).
> 
> then that means I have to watch out for every single tag.
> but I wanted Grabber to do it for me. :(
> simply put: I copy an artist to grabber, I press download all and grabber will download all the images of that artist in the folder which it creates by the name of that artist/tag.

Dude, just use %search% everywhere you are currently using %artist%. That's all there is to it. It's fully customizable, you don't have to use my exact settings. %search% does "I copy an artist to grabber, I press download all and grabber will download all the images of that artist in the folder which it creates by the name of that artist/tag" exactly.

**Comment by HawkSoul** [comment]
Ok dude 😊 will try that tonight and let you know. Thanks for the help.

**Comment by HawkSoul** [comment]
that seem to do the work 👍 
thanks a lot guys.
