### ISSUE TITLE
Have to constantly restart Grabber to search for tags, pages etc

### ISSUE THREAD

**Issue by pencilbook** [Bionus/imgbrd-grabber#1792]
I have to constantly restart the program to be able to download, search for tags, look through pages etc on Danbooru and Gelbooru. Other sources are most likely affected by this apparent issue but I don't use any other sources. The previous version does not have the same issue.

**Comment by pencilbook** [comment]
pls fix

**Comment by RiabikovR** [comment]
Go to settings and enable logging, try to reproduce the issue, then go to the "Log" tab and tell us what it says there.

**Comment by Bionus** [comment]
Sounds like the same as issue #1762, so I'll move the discussion to there. 👍

**Comment by pencilbook** [comment]
It happens on Gelbooru, Danboru and Yandere for me

In this instance, it didn't load Danbooru. Here's the log https://pastebin.com/7r1W7tfG
