### ISSUE TITLE
How do you download the tags for each image into a file

### ISSUE THREAD

**Issue by skier233** [Bionus/imgbrd-grabber#1793]
I've read through all the settings menu and the wiki and I'm still unclear how I can download all of the available tags for each image and store them in a file(s).

**Comment by HawkSoul** [comment]
Hi do you mean to download all tags in one folder?

**Comment by skier233** [comment]
I mean like you have image1.jpg and then you download tag1, tag2, tag3, etc for that image. I don’t care how they are downloaded whether they all go in one file or one file per image.

**Comment by Bionus** [comment]
Hello,

You said you checked all settings, but have you tried the "separate log files" setting?
It can be found in "Options > Save > Separate log files".

Using one like the one below would save all tags in a TXT file beside the image.

![image](https://user-images.githubusercontent.com/882719/66226401-02295400-e6db-11e9-955e-cded9fe26f42.png)

**Comment by skier233** [comment]
This is exactly what I needed. Thanks! Now I can just parse this data and feed it into my neural network.
