### ISSUE TITLE
%score% token not working on Sankaku

### ISSUE THREAD

**Issue by Gradivus500** [Bionus/imgbrd-grabber#1794]
**Bug description**
Images downloaded from https://chan.sankakucomplex.com/ do not properly use the %score% tag. They will all always have a rating of 0

**Steps to reproduce**
1. Set your file name to include the %score% token
2. Download any images from https://chan.sankakucomplex.com/ using the program (For best results set that as the only source) 
3. Go to the download folder and look at the file name, the rating for every picture will be "0"
4. Verify this is the wrong rating by going to the url where the image is hosted, and check the rating (sankaku uses a 0-5 rating system)

**Expected behavior**
The score should be present in the file name. If it's because sankaku uses a 0-5 score system instead of upvotes, then you could either just only uses numbers 0 thru 5, or apply some form of scalar based on the scores of the other images downloaded during the same session.

**Comment by Gradivus500** [comment]
I just realized I kept saying %rating% but I actually meant %score%

**Comment by RiabikovR** [comment]
Titles have a separate "edit" button, it thould be to the right of the title itself.
I thought that sankaku uses the usual score system as well as five star ratings?

**Comment by RiabikovR** [comment]
Titles have a separate "edit" button, it thould be to the right of the title itself.
I thought that sankaku uses the usual score system as well as five star ratings?

**Comment by Gradivus500** [comment]
If Sankaku does use a traditional rating system that just makes this bug even worse, because it's still not working in grabber.

**Comment by Bionus** [comment]
I was going to close the issue given Sankaku is not supported, but after a quick investigation it seem to come from the fact that Grabber does not support float values for scores instead of a specific bug for Sankaku, so I pushed a fix for that point.

> If Sankaku does use a traditional rating system that just makes this bug even worse, because it's still not working in grabber.

AFAIK, they only use the star-system score.

**Comment by Gradivus500** [comment]
Seeing as how you've committed the change I'm just going to mark this as closed and reopen it if need be after the next release. Thank  you for the insight and the fix!
