### ISSUE TITLE
Why does the %character% tag works only if there are a single character presented?

### ISSUE THREAD

**Issue by Timurama** [Bionus/imgbrd-grabber#1798]
Can't it like name individually every single one of them? If there are more than one the programm would just name it ".group", 
![2019-10-04_03-52-12](https://user-images.githubusercontent.com/50590555/66173718-5d673200-e65a-11e9-83c1-8ab8fdea003f.png)
Is there a way to make it name every character on the image instead of "group"?

**Comment by Bionus** [comment]
Hello,
Have you checked the settings?

![image](https://user-images.githubusercontent.com/882719/66226312-c8584d80-e6da-11e9-97d4-672125da8ad7.png)

**Comment by Timurama** [comment]
> Hello,
> Have you checked the settings?
> 
> ![image](https://user-images.githubusercontent.com/882719/66226312-c8584d80-e6da-11e9-97d4-672125da8ad7.png)

I didn't actually, thx
