### ISSUE TITLE
I'm having some trouble

### ISSUE THREAD

**Issue by justwantittowork** [Bionus/imgbrd-grabber#1799]
Hi, I just downloaded this program, and immediately ran into a rather large issue. Whenever I try to search for something on any booru, it turns up with no results. Is there a reason for this?

**Comment by Gradivus500** [comment]
No one is going to be able to solve your problem because you didn't give us steps to replicate it.

**Comment by justwantittowork** [comment]
Okay, so as a test I selected Danbooru and put in rating:safe. I was meet with this

![image](https://user-images.githubusercontent.com/53221922/66232629-486cbc00-e6b7-11e9-9112-7777a2401565.png)


Really that's all the info I can give because I immediately run into this. everything I've tested results in this...

**Comment by Bionus** [comment]
@justwantittowork what's written in your log tab?

**Comment by justwantittowork** [comment]
![image](https://user-images.githubusercontent.com/53221922/66232841-d21c8980-e6b7-11e9-831f-3dc0c0d30e37.png)

This is what meets me in log

**Comment by Bionus** [comment]
Maybe you can try using the nightly version, the OpenSSL DLL have changed:
https://github.com/Bionus/imgbrd-grabber/releases/nightly

Otherwise, installing MSVC redist usually fixes this issues. I haven't been able to pinpoint which one exactly yet, though. 😞

**Comment by justwantittowork** [comment]
Alright, I'll try the nightly build first. Thanks.

**Comment by justwantittowork** [comment]
Having repaired the 2015 version of MSVC redist has done nothing either, is there a previous version this program uses instead?

**Comment by Bionus** [comment]
You might want to try to install both 2015 versions and both 2013 versions and see if that fixes it.

Otherwise, you can find all releases there:
https://github.com/Bionus/imgbrd-grabber/releases

**Comment by justwantittowork** [comment]
I repaired the x86 version of the 2013, but I'm on an x64. I did just install this on a different computer and it works just fine... I'll either have to use that computer or install a legacy version like you just linked. Thank you for your time and sorry for the confusion...
