### ISSUE TITLE
The %all% tag does not include "_" in tags and only uses spaces

### ISSUE THREAD

**Issue by Gradivus500** [Bionus/imgbrd-grabber#1801]
**Bug description**

When using the %all% tag, tags that normally use an underscore to utilize multiple words in one tag instead user white space. This is a problem because multiple tags are also seperated by white space.

**Steps to reproduce**

Open grabber and put the %all% tag in your file name. 
Add some links to the downloader
Download the files
The files will not utilize and underscores int heir file name

**Expected behavior**

Tags which use an underscore to separate words should also do so in file names. Most (All?) file systems support underscores, so this shouldn't pose a problem.

**System information**

Windows 10
Grabber 7.1.1 (x64)

**Comment by Bionus** [comment]
Hello, have you tried disabling the "replace spaces by underscores" setting?

![image](https://user-images.githubusercontent.com/882719/66378757-73efef00-e9b4-11e9-882a-745db8ccd2e6.png)

You could also use the `underscores` modifier in your filename (`%all:underscores%`).

**Comment by Bionus** [comment]
I updated [the docs](https://bionus.github.io/imgbrd-grabber/docs/filename.html) to mention this modifier:
https://bionus.github.io/imgbrd-grabber/docs/filename.html#underscores-bool

**Comment by Gradivus500** [comment]
Good god I can't believe I missed that. Thanks for pointing it out and HUGE thanks for updating the docs.
