### ISSUE TITLE
How to only download certain file types (only jpg and png)

### ISSUE THREAD

**Issue by skier233** [Bionus/imgbrd-grabber#1805]
How can I only download certain file types (in my case only png and jpg). I'm wanting to download roughyl 600k images for use with training a neural network but I can't use video files and downloading them takes up a lot of space and if they are downloaded I will run out of disk space. So how do I only download the png and jpg files?

**Comment by Bionus** [comment]
You can use post-filters to filter images by extension.

The `filetype` or the `ext` token could be used (they're aliases of each other, and contain the extension). But not that there is no "OR" logic for post-filters, so you'd have to choose one extension, or make the downloads separately.

Just use `ext:jpg` in the post-filter and it should ignore other extensions.
