### ISSUE TITLE
Images not downloading from pixiv

### ISSUE THREAD

**Issue by espeteroOnirico** [Bionus/imgbrd-grabber#1807]
Hi, first time reporting an issue so this may or may not have been solved already. However, I couldn't find anything that solves my specific problem after searching for a bit.
The issue I have is that, after searching for a tag I get the thumbnails from pixiv but whenever I click on a picture it never fully loads and when I try to save it it'll just say "Saving..." forever, I read a few issues saying that you need to be logged in, so I tried that, but I get a failure message despite that. What can I do? Here's some pictures of the log and what happens for clarity.

![image](https://user-images.githubusercontent.com/49562253/67005931-b4015100-f0db-11e9-8e2d-3b20b7c9cd83.png)

![image](https://user-images.githubusercontent.com/49562253/67005992-dabf8780-f0db-11e9-9260-50f943cde1d7.png)

![image](https://user-images.githubusercontent.com/49562253/67006192-60dbce00-f0dc-11e9-8295-344b7dceff0b.png)

When I try to log into pixiv through grabber:
![image](https://user-images.githubusercontent.com/49562253/67006122-2d993f00-f0dc-11e9-8dab-11b100081f82.png)

> [12:45:47.237][Info] [www.pixiv.net] Logging in...
[12:45:48.561][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"103:pixiv ID\u3001\u307e\u305f\u306f\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u6b63\u3057\u3044\u304b\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","code":1508}}}
[12:45:48.563][Info] [www.pixiv.net] Login finished: failure.

**Comment by Bionus** [comment]
Which version are you using?
If you're using [v7.1.1](https://github.com/Bionus/imgbrd-grabber/releases/v7.1.1), there should be a fix (069cd277b6adf8132db9b550014b4248367041b9) in the [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) version.

This looks like the same issue as issue #1807.

**Comment by espeteroOnirico** [comment]
I had 7.1.1, downloaded nightly and it still have the same error. Log says 

> [18:25:39.109][Error] Loading error for 'https://public-api.secure.pixiv.net/v1/works/77407072.json?image_sizes=large': Error transferring https://public-api.secure.pixiv.net/v1/works/77407072.json?image_sizes=large - server replied: Bad Request

**Comment by J3loodz** [comment]
same

**Comment by Bionus** [comment]
Hello, sorry for the delayed answer.
I'll have a look as to why it's still not fixed.

> Also, it may have been a mistake but this is issue #1807 meaning it's not a duplicate

Yeah it was a typo, I meant issue #1765.
But after looking more into it, those two seem different, so this will require a separate investigation.
