### ISSUE TITLE
Suppress tag in filename?

### ISSUE THREAD

**Issue by TogarUshindi** [Bionus/imgbrd-grabber#1810]
Is there a way to suppress a token string from generating a folder or filename? 

Some sites like e621 attribute multiple copyright tags to an image, even though the copyrights belong to the same franchise. imgbrd-grabber creates unique folders based on its unique combinations. e.g:

```
%artist%/sonic_the_hedgehog/
%artist%/sega+sonic_the_hedgehog/
```

"sega" doesn't need to be in there. We all know which company published it. It doesn't need a unique folder.

Additionally, an even more annoying problem is that "source_filmmaker" has been categorized under the "copyright" category on e621 instead of an art tool or medium. It absolutely does not need to generated a unique copyright folder, but that's exactly what's happening. e.g.:

```
artist1/copyright1+copyright2+source_filmmaker/
artist1/copyright1+copyright3+source_filmmaker/
artist1/copyright1+copyright2+copyright3+source_filmmaker/
```

I am not sorting images by the method of production, so this tag can be suppressed entirely.

This is all due to site site-specific sloppy taxonomy, but unfortunately imgbrd-grabber inherited the problem. What are some possible solutions? One way I could deal with this is just not use the `%copyright%` token entirely, but in some cases it could be quite helpful. There is probably a more elegant way of dealing with it that I'm not aware of. Is there already a solution for this?

Here's something off the top of my imagination:

`%artist%/%copyright:suppress=source_filmmaker%/`

I could imagine a "suppress" tag? I know that doesn't exist, but perhaps that might be a solution, unless some clever method can be used existing options?

**Comment by Bionus** [comment]
> Is there a way to suppress a token string from generating a folder or filename?

Yes, it's called "ignore filename". It's quite hidden, as it can only be accessed by right-clicking a tag:
![image](https://user-images.githubusercontent.com/882719/67157069-0e422200-f327-11e9-9d46-1e64cd018b44.png)

Any tag marked as ignore will still appear in the `%all%` token but will disappear from others, as if it were without any specific "type" (such as "copyright"), and instead appear in `%general%`.

**Comment by yami-no-tusbas** [comment]
Maybe this could be in a menu ? It's really usefull in fact ! Like near to the blacklist so we can manually edit it ? (for exemple I use different "ignore" list for e621 and gelbooru and don't want them to mix)
