### ISSUE TITLE
%num:noext%.%ext% creates one file for each filetype in batch download and skips all other files

### ISSUE THREAD

**Issue by NinjaPug7** [Bionus/imgbrd-grabber#1815]
**Bug description**

When %num:noext%.%ext% is used in the filename box, it saves the first file of the filetype as 1.(ext) and skips all other files of that filetype.

**Expected behavior**

I expected what was described in https://github.com/Bionus/imgbrd-grabber/issues/1524 to happen, to number each file, disregarding what filetype they are.

**Comment by Bionus** [comment]
Indeed!

This was caused by the temporary files getting generated during download. I just pushed a fix 👍
