### ISSUE TITLE
missing include - QCryptographicHash

### ISSUE THREAD

**Issue by zrose584** [Bionus/imgbrd-grabber#1817]
`lib/src/models/site.cpp` is using `QCryptographicHash`, but `#include <QCryptographicHash>`  is missing.

gcc produced:
error: ‘QCryptographicHash’ has not been declared

**Comment by Bionus** [comment]
Wow, I can't believe the Unix build was broken for more than one month and I didn't get any notification from Travis.

I just pushed a fix for this file, and the build is green again. Thanks!
