### ISSUE TITLE
Post notifications on Favorites

### ISSUE THREAD

**Issue by str8noobish** [Bionus/imgbrd-grabber#1821]
- **Problem:**

I've been using this program mainly to keep track of the new images my favourite artists post. Thing is, it takes a good amount of time going through my "favorites" tab and clicking on each of their tags to see if there are new posts of their work.

- **Proposed solution:**

I thought of having some sort of **refresh button**:
 
**This button would look into each tag on the "favourites" tab automatically and assign a red dot to those tags in case there are posts that havent been viewed.**

Also, adding a new "sort by" that displays the tags with new posts first (the ones with a red dot) would be great to make them easier to find.

This is a quick example of what it could look like:

![suggestion](https://user-images.githubusercontent.com/11135091/68073654-449d8980-fd8a-11e9-90d0-d9e77b498d52.png)

**Comment by Bionus** [comment]
> I've been using this program mainly to keep track of the new images my favourite artists post. Thing is, it takes a good amount of time going through my "favorites" tab and clicking on each of their tags to see if there are new posts of their work.

Have you tried the "monitoring" feature?

By adding a monitor to your favorite (open the favorite's settings, then you'll see a "Monitoring" tab there), Grabber will automatically check for updates on those searches and add a red circle as you mention. You just need to provide a source and an interval to check.

There's no "manual refresh" feature like the one you suggest. I guess it could be added too?

Note that on startup, Grabber will directly refresh all monitored favorites whose last check was too long time ago, so I doubt it would be very necessary however.

**Comment by Bionus** [comment]
Note that if you leave Grabber open in the background (you can reduce it to the system tray if you enable it in the settings), it can also trigger some Windows notifications each time a new image is posted for one of your monitored favorites.

**Comment by str8noobish** [comment]
OOOH i didn't know about that! I just tried it out on some popular tags and its seems to be working nicely.
Thanks for telling me, i had no idea!
