### ISSUE TITLE
Client-side way to circumvent some tag limits

### ISSUE THREAD

**Issue by Atulin** [Bionus/imgbrd-grabber#1824]
**Is your feature request related to a problem? Please describe**

Some sources limit the amount of tags they allow in a query, which is even more frustrating considering some of them have rather weak tag system and need a lot of filtering to get desired results.

**Describe the solution you'd like**

After Grabber gets all the results the API returned, some additional, client-side filtering can be done, at least to filter out unwanted images. Not sure how it'd look in C++, but basically the equivalent of the following LINQ:
```cs
var unwantedTags = new List<string> { "tag1", "tag2", "tag3" };
var filteredImages = images.Where(i => !unwantedTags.Intersect(i.tags).Any());
```

**Describe alternatives you've considered**

Making a simple Python script to at least handle the removal of images with unwanted tags, I guess ¯\\\_(ツ)_/¯

**Comment by Atulin** [comment]
I guess scratch that, because I can see some options to blacklist tags client-side in the options. Not sure if they work how I'd imagine them to, though, I'll need to try them.

Still, I believe it would be a good idea to have those available per-search instead of globally.

**Comment by Bionus** [comment]
Have you tried using the "post-filter" feature?

It's exactly what you're asking for. Just click the "+" on the side of the search and the field will appear. It has the same format as the search, so to filter a tag, just put `-tag` in the field.

And as you said, the blacklist can also do that, albeit globally.

**Comment by Atulin** [comment]
Well would you look at that, hiding in plain sight. Perhaps changing the icon to one more widely associated with filtering could be considered?

Regardless, this isssue can be considered solved and closed.
