### ISSUE TITLE
Delete already downloaded blacklisted images

### ISSUE THREAD

**Issue by omegarunner1** [Bionus/imgbrd-grabber#1825]
**Is your feature request related to a problem? Please describe**

Generally, the way the downloader works is that it will download anything in your search that has not been ignored or blacklisted. This is fine, as it should be. However, sometimes you get so many results in a single search that narrowing it down gets difficult and when you batch download there may inevitably be images that you wanted to blacklist but didn't know you were downloading until you saw them in your folder. You can go search for those images manually and remove and delete them but, depending on how many unwanted images you download, this could be a very long process.

**Describe the solution you'd like**

I'd like there to be an option, like a checkbox, in the Blacklist setting to delete any downloaded images that were retroactively blacklisted.

Edit: The Blacklist fixer does seems to be a solution, however, generally, it takes too long to operate and that seems to be because it's downloading information. One suggestion I have is to change how the blacklist fixer works. Instead of downloading information, just do a massive number of batched md5 searches and check the tags for any matching images, any matching images that have blacklisted tags will be deleted. And any md5 searches that return nothing will just be skipped. This will speed up the process and allow the removal of images much faster.

**Describe alternatives you've considered**

Just use the same search function that exists within the program, the one used to compare image names against images in the blacklist to delete anything that shows up that you blacklisted after the fact. Since all the functionality is there, just not together, I think it would be a cool feature to add for anyone having trouble with this.

EDIT: Okay, the problem I'm having seems to be that while yes the Blacklist Fixer does gather all the blacklisted images, it can only delete one at a time because the Get Selected Images button will only grab the very last image in the selected range, not all of the blacklisted ones. I think this needs to be fixed.

**Comment by Bionus** [comment]
There should be a tool just to do that in "Tools > Blacklist fixer", you should give it a try. 😄

Note that it is however very slow, as the tags of a given image are not stored, so it needs to re-download them for each image, based on their MD5.

**Comment by omegarunner1** [comment]
Is that what the blacklist fixer does? I couldn't find any documentation on that thing so I wasn't sure what it does.

**Comment by omegarunner1** [comment]
I'm using the blacklist fixer now, I'm waiting for it to finish to see what it does and, if it does what you say, I'll close to issue, if it doesn't or it needs more explanation, I'll edit the issue to request better documentation instead.

**Comment by omegarunner1** [comment]
Okay, I'm currently attempting to use the blacklist fixer and, while it does struggle with huge numbers of images, the bigger problem is that the Get Selected Images button will only grab 1 image, it won't grab all of the images that have blacklisted tags, so I think that needs to be fixed.

And, again, if there is a way to delete blacklisted images with a button press using the blacklist fixer, that's all the more reason to add better documentation.

**Comment by Bionus** [comment]
> Is that what the blacklist fixer does? I couldn't find any documentation on that thing so I wasn't sure what it does.

I just added some better documentation:
https://bionus.github.io/imgbrd-grabber/docs/tools/blacklist-fixer.html

It's still light, but it at least explain the general purpose and limitations of the tool.

> Okay, I'm currently attempting to use the blacklist fixer and, while it does struggle with huge numbers of images

The struggle is because of the (numerous) network requests done to get the tags for each image, to know whether an image is blacklisted or not.

> the bigger problem is that the Get Selected Images button will only grab 1 image, it won't grab all of the images that have blacklisted tags, so I think that needs to be fixed.

Indeed, that's a bug. But you can always do <kbd>Ctrl+A</kbd> or simply select them by mouse, then click to delete them.
