### ISSUE TITLE
Is "booru.allthefallen.moe" supported?

### ISSUE THREAD

**Issue by lollos73** [Bionus/imgbrd-grabber#1826]
**Is your feature request related to a problem? Please describe**

i need just some info

**Describe the solution you'd like**

don't know solution.

**Describe alternatives you've considered**

none

**Additional context**

just to know, the site https://booru.allthefallen.moe is supported? they change site and old trik don't work, can yoi explain me if is my problem? ty for answer

**Comment by iDolmatov** [comment]
Default booru API: https://booru.allthefallen.moe/wiki_pages/1?noredirect=1
You can try custom add site to list.

**Comment by Bionus** [comment]
That's a standard "Danbooru (2.0)" source, so you can add it manually.
https://bionus.github.io/imgbrd-grabber/docs/sites/

Since it's a fork, it won't be recognized automatically with the "Guess" feature, but you can simply enter the site type yourself.
