### ISSUE TITLE
Auto-Completion not working right

### ISSUE THREAD

**Issue by RadicalCardinal** [Bionus/imgbrd-grabber#1827]
Anytime I try to type in a tag, auto-complete never shows it. I never had this problem before nor do I know how to reproduce it. An example would be me typing tags that rule34.xxx would have but they don't show.
![grabber issue](https://user-images.githubusercontent.com/57567567/68531450-2bdc2900-02e0-11ea-8524-3b5cbfa42367.png)

**Comment by Bionus** [comment]
If you go in your installation folder (by default `C:\Program Files\Grabber`), does it contain a `words.txt` file, containing a bunch of tags separated by spaces?

Like this:
![image](https://user-images.githubusercontent.com/882719/68809474-4d386e80-066c-11ea-933c-9b71b6f07303.png)

And if you go to the `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`, does it contain a `wordsc.txt` file? If so, how big is it? (in Kb)

**Comment by RadicalCardinal** [comment]
Yes, I have both text files and they are in their respective locations. as for the wordsc.txt file, it's 0 bytes.

**Comment by Taliruls** [comment]
a quick fix i did was copy all of the text from words.txt and paste them into wordsc.txt, save as "wordsc" overwriting the previous one

**Comment by RadicalCardinal** [comment]
> a quick fix i did was copy all of the text from words.txt and paste them into wordsc.txt, save as "wordsc" overwriting the previous one

Thanks for this, helped solve my problem. (Just wish I would've come back sooner to see this response.)
