### ISSUE TITLE
start downloading from a certain page

### ISSUE THREAD

**Issue by naruhina2016** [Bionus/imgbrd-grabber#1831]
Hi.

I was wondering is there a way to download pictures from a certain page and onwards?

**Comment by Bionus** [comment]
Hello,

It's indeed possible, but the solution depends on what you mean by "onward":
* If you mean "from page N to max page", you can simply set the "Page" value in your batch download to the first page you want to download
* If you mean "from page N to page 1", you have to put the "Page" value to 1, and the "Images limit" value to "N * images per page". For example, if you want to download page 5 to 1 (so 5 pages) on a website with 20 images per page, you have to set "Page" to 1, "Images per page" to 20 (should be automatic), and "Images limit" to 100 (the number of images on 5 pages)
