### ISSUE TITLE
I was AFK when it happened

### ISSUE THREAD

**Issue by MagikGimp** [Bionus/imgbrd-grabber#1833]
Crash dumps attached.

Side note 1: Restarting with restored session (twice) brought back the same old session from weeks ago each time, presumably the previous one to when I used Grabber today?
Side note 2: Some files were saved with creation dates and times from the future. This could be a Windows issue though.

[Crashes - 25-11-19.zip](https://github.com/Bionus/imgbrd-grabber/files/3888641/Crashes.-.25-11-19.zip)

**Comment by MagikGimp** [comment]
Update: Crashes when downloading from e-hentai.
[Crashes - 25-11-19 (2).zip](https://github.com/Bionus/imgbrd-grabber/files/3888659/Crashes.-.25-11-19.2.zip)

**Comment by MagikGimp** [comment]
And another one...
Crashes when trying to add certain sources e.g. Twitter, e/ex-hentai, nhentai and Pixiv.
Wrote dates on some files between 2018 - 2009 and er, 1972. Again, might be Windows, NTFS problems etc. This is a reused drive that was quick-formatted.
[Crashes - 25-11-19 (3).zip](https://github.com/Bionus/imgbrd-grabber/files/3888850/Crashes.-.25-11-19.3.zip)

**Comment by Bionus** [comment]
Hello, I'll take a look at your crash dumps tomorrow.
Which version of the program are you using? Nightly, or 7.1.1?

Is there any pattern as to when the crashes occur?
You mentioned "when trying to add certain sources", but those sources are already there by default. You mean when adding a download from those sources?

> Some files were saved with creation dates and times from the future. This could be a Windows issue though.

Is it only a few hours in the future, or days/years? Might be a timezone issue.

> Wrote dates on some files between 2018 - 2009 and er, 1972

Were the files from 1972 from a specific source?
I also guess that you have the "Keep original creation date" setting on?

**Comment by MagikGimp** [comment]
1. Regular release stream. OK, this is strange. I've just run the program and it's prompted me to update, as it did three days ago. But 7.1.1 was released in May? Please bear that in mind. I'll do more testing.
2. _Sorry, I meant when ticking / checking the boxes next to them. Use one of those sources I listed and Grabber will instantly crash just by clicking OK._ Right, this problem has gone for the time being now I'm actually on v7.1.1.
3. I don't think so.
4. I do have that setting on so that explains some of those. Might be a server-side irregularity?

No more crashes for the time being but I've only tested with like 50 files rather than the 1600 I was leeching before. Strange about the update problem though. It definitely updated, just not to the latest version?
