### ISSUE TITLE
"Loading error: Connection timed out (99)" on every request

### ISSUE THREAD

**Issue by General-Trident** [Bionus/imgbrd-grabber#1834]
I don't know if this is a crash or a bug, but I'll just lay it down here.

[main.log](https://github.com/Bionus/imgbrd-grabber/files/3889210/main.log)

[settings.ini.log](https://github.com/Bionus/imgbrd-grabber/files/3889220/settings.ini.log)

[DxDiag.txt](https://github.com/Bionus/imgbrd-grabber/files/3889293/DxDiag.txt)

![browse page](https://user-images.githubusercontent.com/52889250/69587462-36a0f880-1018-11ea-8cd7-2eae813954de.JPG)
![Log3](https://user-images.githubusercontent.com/52889250/69587464-37398f00-1018-11ea-8a22-b42bbf0f10d3.JPG)
![Log2](https://user-images.githubusercontent.com/52889250/69587465-37d22580-1018-11ea-895a-32d82b5ae862.JPG)
![Log1](https://user-images.githubusercontent.com/52889250/69587466-37d22580-1018-11ea-950a-f84bb264310e.JPG)

**System information**
- OS: Windows 10 
- Grabber version: 7.1.1.

The state of my system and the Grabber:
1) Before, I was using Grabber in a Windows 7. After finished updating to Windows 10, my Grabber doesn't work anymore.
2) My current OS: Windows 10
3) Grabber version: 7.1.1. (both before and after updating Windows)
4) Lots of configurations in Grabber

My issues in question:

1) After putting in the tag(s) in the search bar, the page doesn't show anything, just blank. I've attached both a screenshot of it and the log screen, or maybe you already know how it's supposed to look like? My question is: What just happened?

2) I cut-pasted my destination folder to my external HDD. Did that affect the Grabber.

3) Is there any way I can show you all of my Grabber configurations? LIke a ,txt file or something. Should I return my Grabber configs to default? And how?  I've attached the main.log and system.ini since you asked to, but I don't know what they're supposed to do.

5) Tell me what else to check or if there's anything I missed. I'm completely blind to this kind of thing.

There are many configurations I did to my Grabber (like showing blacklisted tags etc.), but I forgot how many I've had changed. 

I've also tried reinstalling many times up to 10 times, nothing worked. The search page keeps showing blank page.

**Comment by sbobbo** [comment]
Try the 32 bit version, that fixed this for me at one point.
