### ISSUE TITLE
Can't load any images from any source (SSL errors)

### ISSUE THREAD

**Issue by ELECTROHAXZ** [Bionus/imgbrd-grabber#1836]
I can't load any images at all no matter what keywords I use, running Windows 10 Enterprise. I have installed all vcruntimes as suggested in other similar issues. Log --> https://pastebin.com/T80irgP4

**Comment by Bionus** [comment]
Maybe you can try using the nightly version? I just fixed issue #1846 which caused some SSL issues in recent builds, so it should work there:
https://github.com/Bionus/imgbrd-grabber/releases/nightly
