### ISSUE TITLE
Longer filenames than just 260 sign

### ISSUE THREAD

**Issue by basti0704** [Bionus/imgbrd-grabber#1838]
Hey!
I know the normal path limit in Windows is 260 but I edited it so I can have an unlimited filename length. But the program just allows 260 signs. How can I change that? 
Thanks!

**Comment by Bionus** [comment]
Hello

You could directly edit your `settings.ini` file, and modify the `limit` value to something above 260 (make sure to edit the one under `[Save]` and not under `[General]`, as that's another setting). The issue being that it might be reset when you open the settings again 🤔

I guess I should just remove the hard limit of 260 and increase it to 1000, while showing a warning.

**Comment by basti0704** [comment]
Thank you for your quick answer! I'll give it a try. And also thanks for your whole program and effort you do for it :D

**Comment by basti0704** [comment]
I tried it but its like you said. It resets when I open the program but its still in the settings.ini

**Comment by Bionus** [comment]
It resets when opening the program?
That shouldn't be. It should only reset when you open the options window.

How did you know it was reset? (note that you must close the program before editing the settings file)

**Comment by basti0704** [comment]
Yeah that was the thing I meant

**Comment by Bionus** [comment]
Try the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/nightly), it should be fixed there (I increased the limit to 10,000).
