### ISSUE TITLE
Favorites bar seems to have overlapping text

### ISSUE THREAD

**Issue by milordrevan** [Bionus/imgbrd-grabber#1848]
**Bug description**

Favorites list text seems to overlap each other so that nothing is visible.
https://i.imgur.com/kfJR2LS.png

If you hover over it with your mouse, you can see which favorite is under your cursor:
https://i.imgur.com/x4uy5Lx.png
And moving the cursor very slightly will change it. But it seems the list of favorites has their text compressed into a tiny vertical space for some reason.

**Steps to reproduce**

I am not sure how this happened.

I tried fixing it by reducing my number of favorites from 52 to <50 by editing the settings.json file, but this did not fix the issue.

**Expected behavior**

I expect the favorites list to list normally.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/3960162/main.log)

I had to rename settings.ini to setttings.txt to get it to upload here.
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/3960167/settings.txt)

I had to rename favorites.json to favorites.txt to get it to upload here.
[favorites.txt](https://github.com/Bionus/imgbrd-grabber/files/3960164/favorites.txt)

**Screenshots**
https://i.imgur.com/kfJR2LS.png
https://i.imgur.com/x4uy5Lx.png

**System information**

- OS: Windows 10
- Grabber version: 7.1.1

**Additional context**

None

**Comment by milordrevan** [comment]
OK this is weird. I added two more favorites, just to see what would happen, and the favorites list is displaying normally now.

**Comment by Bionus** [comment]
Have you tried resizing the window when this happens?
I'll see if I can reproduce on my end.

**Comment by milordrevan** [comment]
I know how to reproduce now. The width of the favorites window affects this. If one has a specific string in the favorites bar that is longer than can be displayed on one line, it causes the text to display very overlapped as in the screenshots above.
However, if you widen the favorites window, it will display correctly again.
