### ISSUE TITLE
Words file excluded from new install

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1850]
**Bug description**

When I downloaded grabber on my new pc I saw that the auto completion wasn't there. When I checked futher the words.txt file was missing inside my appdata folder. (wordsc.txt is not being filled when the words.txt is missing. once I placed words.txt manually back the wordsc.txt is being filled again)

**Steps to reproduce**

1. Delete your words.txt file (if ofc you have already installed grabber)
2. Download and install the latest grabber

**Expected behavior**

The words.txt file being included in the install

**System information**

Windows 10 with the latest grabber version

**Comment by Bionus** [comment]
This does not happen in recent versions, no idea what happened with this 🤔 
There were multiple big changes for the Windows setup since then, I guess one of those fixed this issue.

**Comment by MrAndre96** [comment]
Nice to see it still being worked on

**Comment by Bionus** [comment]
Yeah I never really stopped working on it, but older issues tend to be forgotten.
Out of sight, out of mind I guess 🤔
