### ISSUE TITLE
Question: Where are tags downloaded to?

### ISSUE THREAD

**Issue by Gradivus500** [Bionus/imgbrd-grabber#1853]
Sorry, I can't label my own report, but this is a question. I'm on windows 10 and used the tag loader feature. My question is, where are those tags saved to? I imagine its just a list of tags in a file but they have to be saved somewhere.

Also while I have you, why does the wiki in grabber only work like, 20% of the time. usually it shows nothing, even when I know there is a wiki entry for that tag. But Alot of the time when it does show a wiki entry, it disappears after a few seconds! By that I mean, I'll enter my tags, push search, a wiki entry will appear and give a description of the tag, then after about 4 seconds it just disappears.

**Comment by Libidine** [comment]
I have the same question.

**Comment by Bionus** [comment]
> My question is, where are those tags saved to? I imagine its just a list of tags in a file but they have to be saved somewhere.

Tags are saved in the directory:
```
C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites
```
Which has a sub-directory per source then per site. At the bottom of the structure, you'll have a `tags.txt` file which is easily readable. Sometimes, it can also be a `tags.db` file in SQLite format.

So for example for Gelbooru, it's in:
```
C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites\Gelbooru (0.2)\gelbooru.com\sites.txt
```

If you're on linux or mac, you can also open the settings directory from the "File" menu.

> Also while I have you, why does the wiki in grabber only work like, 20% of the time. usually it shows nothing, even when I know there is a wiki entry for that tag. But Alot of the time when it does show a wiki entry, it disappears after a few seconds!

Sounds like a bug to me 🤔

**Comment by Gradivus500** [comment]
Thank you for the question response. I've looked into the tags, is it really necessary to download all the tags? Especially if a large number of tags on a given site have 0 images associated with them?

Also as for the bug, what would be the best way for me to collect data on it to give to you?

**Comment by Bionus** [comment]
> Especially if a large number of tags on a given site have 0 images associated with them?

The tag loader only download tags with more than 20 associated images.

> I've looked into the tags, is it really necessary to download all the tags? 

You can also download the already-generated ones here:
https://github.com/Bionus/imgbrd-grabber/releases/tag-databases

>  Also as for the bug, what would be the best way for me to collect data on it to give to you?

The crash reporter should generate a DMP file for you, but the best is to do a screen recording of the process.
Otherwise, just writing down the reproduction steps.
