### ISSUE TITLE
Can't download pixiv images

### ISSUE THREAD

**Issue by basti0704** [Bionus/imgbrd-grabber#1854]
**Bug description**
When I try to download something from pixiv it just won't download.
For example: Tag is "DARLINGintheFRANXX" and it stays at "0/-917"

Screenshot:
![Unbenannt](https://user-images.githubusercontent.com/46086541/71110302-4c44b080-21c7-11ea-8895-7996d1961afe.png)

**Steps to reproduce**

1. Activate only pixiv as source
2. Type "DARLINGintheFRANXX" and go on Ok
3. Click on "Get all"
4. Go to Downloads
5. Click "Download"

**Expected behavior**

I expect that it starts downloading when I click on it.

**System information**

OS: Windows 10
Grabber Version: 7.1.1 nightly

**Comment by Bionus** [comment]
Pixiv integration has been totally renewed in recent versions, so I'll close this ticket 👍
