### ISSUE TITLE
Exclude specific tags from filename

### ISSUE THREAD

**Issue by muhamadrid** [Bionus/imgbrd-grabber#1855]
I cant save %all% tags into folder/file name because windows limit maximum character for naming file and folder.  I just wandering if you guys can add a function to exclude some words from filename. Just example the image has "cute, girl, brown, long" tags, but i wanna prevent "brown and long" words to become filename.

**Comment by sbobbo** [comment]
If you install the latest nightly, change the registry setting HKLM\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled and change the max length setting from "0" to "1000" or "10000" or whatever, you can have longer files names.

Beyond that, there are ways to limit the length of individual tags, along with excluding specific tags from the filename

https://bionus.github.io/imgbrd-grabber/docs/filename.html

**Comment by Bionus** [comment]
You can use the "removed tags" feature:

![image](https://user-images.githubusercontent.com/882719/127707283-43e00e82-f3fb-4fc8-bead-3ec7e79cc143.png)
