### ISSUE TITLE
Saving a Filename including \n cause strange behaviour.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1856]
**Bug description**

If I use 

`%websitename%\non-asian\%copyright%\%character%\%artist% - %rating% - %id% - %md5%.%ext%`

for the filename on a job list. Save it, then reload it, it change to : 

```
%websitename%
on-asian\%copyright%\%character%\%artist% - %rating% - %id% - %md5%.%ext%
```

(the line break is from the string, I didn't add it.)
**Steps to reproduce**

1. Make a job including a \n (like with my "\non-asian\"
2. Save it then reload it.
3. You got the bug !

**Expected behavior**

No interpretting \n when loading a job list ?

**Context**

There is nothing about loading/saving in the log.
[tmp.igl.txt](https://github.com/Bionus/imgbrd-grabber/files/4003620/tmp.igl.txt)

**System information**

- Windows 10
- Grabber version: 7.1.1

**Comment by Bionus** [comment]
Yes, that's because JavaScript filenames allow line breaks (`\n`) but JSON don't allow so there was some overlap. I hacking some basic automatic escaping to the filename saving. :+1:
