### ISSUE TITLE
Sankaku source dissapear after closing Grabber

### ISSUE THREAD

**Issue by CrawlerForever** [Bionus/imgbrd-grabber#1860]
I absolutely have no idea how & why it happens. 

After installing Grabber Nightly (since the main build isn't giving me any online servers for sources) and launching it for the first time, the Sankaku source works fine. But as soon as I close the program and start it again, chan.sankakucomplex.com is gone.

If I try to add it again manually, the loading stops at 10/14, telling me that it's unable to guess site's type, if I'm sure about the url. If I still go through with it, a request for HTTP to HTTPS rediction is asked. A yes or no there don't matter, as I get "no valid source of the site returned result". The only way to "fix" this and make the source works once is by uninstalling and reinstalling. 

Here's a zip with main.log & settings.ini.

[GrabberCrawler.zip](https://github.com/Bionus/imgbrd-grabber/files/4030006/GrabberCrawler.zip)

I have to say also that, while the main Grabber build isn't giving any online server, as least sankaku is still there whether or not I close the program. It doesn't work, but it's still there whatever happens.

I'm on Windows 10. I recently did a rest on my PC to fix some things, I don't know if there could be any links with that. If you never anything else I'll be ready to provide. I'm sorry if it end up being a dumb problem or an easy solution, let's just say me & computers aren't in the best relationship.

**Comment by MightyNumberNine** [comment]
I think sankaku is not longer supported, rip

**Comment by VeggieJay** [comment]
Seems odd, mine was working fine with the nightly builds until it just disappeared

**Comment by needed-a-name** [comment]
I have a similar problem in nightly except both chan and idol sankaku sites are missing from the very first run. This is due to a couple missing files in appdata. Copying them from an install of the last stable release corrects the issue.
The relevant directory is %userprofile%\AppData\Local\Bionus\Grabber\sites\Sankaku
And the missing files are model.js and icon.png
I'm running nightly (aac11b6b) on windows 10.
Unfortunately I don't remember if the appdata path is the same for prior windows versions.

**Comment by CrawlerForever** [comment]
> 
> 
> I have a similar problem in nightly except both chan and idol sankaku sites are missing from the very first run. This is due to a couple missing files in appdata. Copying them from an install of the last stable release corrects the issue.
> The relevant directory is %userprofile%\AppData\Local\Bionus\Grabber\sites\Sankaku
> And the missing files are model.js and icon.png
> I'm running nightly ([aac11b6](https://github.com/Bionus/imgbrd-grabber/commit/aac11b6b96b4b749798f66d06a62699100d6e849)) on windows 10.
> Unfortunately I don't remember if the appdata path is the same for prior windows versions.

I'll keep your comment in mind if everything starts acting up again. I don't know what happened, but I re-installed the stable version, and so far all the websites are working again, sankaku included. I'll stick with the stable version for now I think. Closing thread for now!
