### ISSUE TITLE
Samples downloaded in Anime-Pictures instead of full images

### ISSUE THREAD

**Issue by MightyNumberNine** [Bionus/imgbrd-grabber#1862]
That's Not Really a bug... but when i download some pics in batch download, they are really low quality,that happens only with batch download. here an exemple

Original Pic quality 3.8Mb   (from https://anime-pictures.net/pictures/view_posts/0?denied_tags=&search_tag=rem_(re%3Azero)&posts_per_page=20&lang=en&type=json)

Pic: 3,8Mb png  with single download

Pic: 458 (kinda) kb png with batch download

how i can fix this problem?

**Comment by Bionus** [comment]
Indeed, it would seem that Anime-Pictures changed the download link for full-sized images, so Grabber now always fallbacks to downloading the samples. I'll push a fix to use the proper URL. 👍

**Comment by MightyNumberNine** [comment]
> Indeed, it would seem that Anime-Pictures changed the download link for full-sized images, so Grabber now always fallbacks to downloading the samples. I'll push a fix to use the proper URL.

Oh perfect, thx 
Anyways sorry for my bad English, idk how to use github too xd
