### ISSUE TITLE
Images blurry in preview

### ISSUE THREAD

**Issue by davkms** [Bionus/imgbrd-grabber#1864]
The bug is in the image viewing window the image is blurry, sometimes it fixes when reloading but most of the time it doesnt. The actual image isnt blurry when you check the downloaded image.

Open any image and 90% of the time it is blurry
Its supposed to not be blurry.

This Image shows how blurry it looks in the image viewing window
https://cdn.discordapp.com/attachments/118433598071242753/665180278750314497/unknown.png
This image shows how it actually looks fine.
https://cdn.discordapp.com/attachments/118433598071242753/665180355770449922/unknown.png

**Comment by Bionus** [comment]
I can't reproduce on my end.

The image is blurry during loading, but as soon as it's loaded it's hi-res again. Same thing when the image is already saved on disk.

Can you share the log for when this happens?

**Comment by bugreportbugreportbugreport** [comment]
Did you saved it before it finished loading?

**Comment by davkms** [comment]
> 
> 
> Did you saved it before it finished loading?

yes, it automatically saves when I open it, do you think that might be the issue?

**Comment by bugreportbugreportbugreport** [comment]
Well, to me if I save the image before it loads it stays blurry (Fixed by going to the next image and then back to the previous image). If it autosaves then yeah, I believe we found the problem?

**Comment by Plyro109** [comment]
I've noticed a very similar issue with files that have an incorrect filetype.  ie; The source says it's a .jpg, when the file is actually formatted as a .png.   Could this possibly be the  issue?

**Comment by scb-lab** [comment]
Yeah experiencing same issue. auto-save make the image blurry unless you reload after it finish downloading.
