### ISSUE TITLE
Grabber reports everysite as Offline (Unable to scrape I'm guessing) 

### ISSUE THREAD

**Issue by bugreportbugreportbugreport** [Bionus/imgbrd-grabber#1865]
**Bug description**

Grabber reports everysite as offline

**Steps to reproduce**

1. Start Grabber
2. Search for anything on any source
3. Grabber reports that the server is supposedly offline

**Expected behavior**

Get search results

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/4046087/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/4046100/settings.txt) (Changed to .txt because github doesn't support uploading .ini files)

**Screenshots**

![Annotation 2020-01-10 162141](https://user-images.githubusercontent.com/26037681/72160849-b831c780-33c7-11ea-9ad3-ee1cd7f34f67.png)

**System information**

- OS: Windows 10
- Grabber version: 7.1.1

**Additional context**

It's been like this since the first launch, no idea what I'm doing wrong

**Comment by Bionus** [comment]
Hello, could you try the [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) version and see if it solves the issue? It seems to be an OpenSSL issue that should have been fixed in the `develop` branch which nightly releases base themselves on.

**Comment by bugreportbugreportbugreport** [comment]
Nightly version works as expected, thank you!
