### ISSUE TITLE
3 Questions

### ISSUE THREAD

**Issue by CherryGhostly** [Bionus/imgbrd-grabber#1867]
Good afternoon, first of all I must say: **I LOVE THIS APP**

1.- Is there a way to download images with a resolution limit?
Example: (Height limit = 1000px) so that images that exceed that value end up adjusting to 1000px, since some images weigh up to 20mb.

2.- Is there any way to convert the images that are downloaded in a single format?
Example: (JPG) so that all images .PNG .JPGS. JPEG .GIF ... etc. Become JPG
I know that the `` .PNG '' is usually heavier than the `` .JPG '' and it would help me reduce the weight of each file.

3.- I would like to be able to embed the tags in each image within the properties of the file in Windows.
Example: (properties> Details> Tags = Blue; Red; Green) so you can have them in the metadata of each downloaded image.
I know that for example `` .PNG '' does not allow tags, so my question 2

**Comment by Bionus** [comment]
Hello

Unfortunately, everything you suggested is currently impossible. 😞
Not that it's forever impossible however, (1) and (2) would be pretty easy to achieve.

1. Just to be sure, you're talking about resizing the image after downloading it right? Not only downloading small images?
2. I see the need, but I wonder how you would convert videos into images. Don't convert them, or take the first/middle frame?
3. It was requested multiple times, but as you said many formats do not support embedded tags. That would indeed be alleviated by the question (2), but only if *all* files end up converted to a tag-friendly format (such as JPG).

**Comment by CherryGhostly** [comment]
**Thanks for answering.**

1.- in Gelbooru / Sankaku they show a resized image that is usually between 1000px in height while the original image has higher values; I talk about being able to download that or be able to set a dimension parameter (not the original full size image)

2.- Yes, when you convert a gif to jpg, usually leave the first frame. (I don't know if it's useful, if not, just keep the image extensions)

3.- I think you could add an option in which you can choose:

a.- download the original image (in its original format)

b.- download the image in jpg with its embedded tags

c.- Both options combined where the original file is downloaded and a .jpg version with its embedded tags.

I think it would be the total perfection of this program (although it is already perfect), since I use some managers such as Adobe Bridge to be able to tag them and make search filters with the image bank that I have on my computer.

**Comment by Bionus** [comment]
> 1.- in Gelbooru / Sankaku they show a resized image that is usually between 1000px in height while the original image has higher values; I talk about being able to download that or be able to set a dimension parameter (not the original full size image)

So you want to download the samples then. Have you tried un-checking the "download original images" setting in "Settings > Save"?

> 2.- Yes, when you convert a gif to jpg, usually leave the first frame. (I don't know if it's useful, if not, just keep the image extensions)

The problem remains for MP4 & co. I guess they won't be converted by this. Because an actual conversion would require using ffmpeg or equivalent, which would be possible, but a pain.

> 3.- I think you could add an option in which you can choose:

So you'd have duplicates with option (c)?

**Comment by CherryGhostly** [comment]
1.- Yes, I tried un-checking the "download original images" But even downloading the original image (Full size), I don't know under what concept that rule applies.

2.- Precisely, I think this option would only work for image files. Although I thought about this option mainly due to the fact of reducing the weight of the file and being able to add tags (If it is .jpg)

3.- Yes, the option '' c '' would be a duplicate (The original image + a backup image labeled.jpg)

I would personally use the option '' b '' (I don't need the original format except for specific artists or specific situations)
