### ISSUE TITLE
[Info] Keep MD5 in list upon deletion option 

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1877]
I wanted to know where this option actually causes an effect. 

**Question**

I understand the obvious that it will not delete md5 from the list if I delete the image through the application but what will happen if I delete it outside and the app encounters such a file? 

1. Will it delete the md5 in the list? Will it not? 
2. Does the setting prevent it? 

**Possible Bug?**

Keeping the MD5 in the list makes me unable to save the file again through the application unless I turn that setting off so there are instances I have to turn it off due to lack of force save option. 

Even when the setting just above it, "If the file exists globally", is set to "save", it still does not save.

**Comment by Bionus** [comment]
With this setting, entries in the MD5 list are *never* removed.

So whether you delete the file from the application or from somewhere else, images with the same MD5 will keep being ignored later on since the MD5 "already exists".

> Even when the setting just above it, "If the file exists globally", is set to "save", it still does not save.

Sounds like a bug, I'll have a look.

**Comment by Bionus** [comment]
The MD5 are now removed when deleted from the application, as discussed in issue #1919.

I'll keep this issue open to track the second part, that is "Even when the setting just above it, "If the file exists globally", is set to "save", it still does not save.".
