### ISSUE TITLE
SankakuComplex Deleting Itself in Grabber Nightly

### ISSUE THREAD

**Issue by vampiricwulf** [Bionus/imgbrd-grabber#1878]
**Bug description**

All SankakuComplex sources delete themselves on re-opening the Nightly program.

The files in AppData seem to all still be there, but missing from the actual sources list in the program. Manually re-adding them refuses to find their gallery type.

**Steps to reproduce**

1. Fresh install Grabber Nightly (Nothing in Program Files or AppData)
2. Launch Grabber
3. Close Grabber
4. Launch Grabber
5. All SankakuComplex sources missing

**Expected behavior**

The sources to not be deleted. It does not delete in latest release.

**Context**

I noticed that the Nightly supposedly got a fix for infinite scrolling on sources that do not list page count. I wanted to try it on SankakuComplex, but it did not work when I changed the settings. I tried re-opening the program to find that the SankakuComplex source was missing, tried to reproduce and found the steps above to be the simplest reproduction.

**System information**

- OS: Windows 10
- Grabber version: Nightly
- Head: aac11b6
- Date: 2020-01-16T19:05:31.0000000Z

**Comment by yami-no-tusbas** [comment]
Answer is here : https://github.com/Bionus/imgbrd-grabber/issues/1888#issuecomment-593571950
Pease see : https://github.com/Bionus/imgbrd-grabber/issues/1888 for further information.
