### ISSUE TITLE
Preview mode with sample images

### ISSUE THREAD

**Issue by abbada25** [Bionus/imgbrd-grabber#1880]
I would love this. Gelbooru Image Viewer does this on browser, so it should be possible somehow. 

For people like me who have low internet speed, both downloading and viewing fullsize images are hard. 

And i wonder if Auto Paging is possible?

**Comment by Bionus** [comment]
You can do this with the "Use image samples" setting:

![image](https://user-images.githubusercontent.com/882719/75290434-9f1e9200-5820-11ea-96d4-f30237ed0773.png)

> And i wonder if Auto Paging is possible?

Not sure what you mean by that. If you mean "infinite scrolling" or this kind of thing, there's also a setting for that:

![image](https://user-images.githubusercontent.com/882719/75290498-bcebf700-5820-11ea-8bc1-803d47338122.png)
