### ISSUE TITLE
Clicking on empty space at the end of tags on image preview opens a new empty tab

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1881]
**Bug description**

![Annotation 2020-02-07 132756](https://user-images.githubusercontent.com/8722533/74013178-adaa2400-49ad-11ea-9e59-2bab48991f77.png)

The highlighted area when we do a middle mouse button click on it, opens a new empty tab.

**Expected behavior**

Nothing happens.

**System information**

- OS: Windows 10 x64 1909
- Grabber version: Nightly

**Comment by brazenvoid** [comment]
Well this also happens in the white space between tags... So it is safe to say, it happens in all white space in that container.

**Comment by Bionus** [comment]
Yeah, I noticed that too.
The change I just pushed should fix both 👍
