### ISSUE TITLE
Tag '>_<' doesn't get displayed correctly (shows up as '>_')

### ISSUE THREAD

**Issue by GlassedSilver** [Bionus/imgbrd-grabber#1885]
**Bug description**

See title

**Steps to reproduce**

1. Find a picture using >_< as search term.
2. View meta data

**Expected behavior**

>_< to be displayed

**Context**

If you click the tag in the metadata view it will actually insert correctly as >_< into the search box for a new search. So it must be a display problem only.

**Screenshots**

---

**System information**

- OS: Windows 10 x64
- Grabber version: 7.1.1

**Additional context**

n/a

**Comment by Bionus** [comment]
Yes, that's because the tags are displayed as HTML, so the `<` is being treated as the beginning of an HTML tag. I just pushed a fix 👌
