### ISSUE TITLE
New update crashes on search or when opening a new tab

### ISSUE THREAD

**Issue by sinkiller21st** [Bionus/imgbrd-grabber#1887]
every time I start a search or open a new tab it freezes and closes its self

**Comment by sinkiller21st** [comment]
I'm going to try to reinstall it if it continues  I will let you know

**Comment by Bionus** [comment]
Can you give more details on what you are trying to search?
Such as which sources you are using, as well as the contents of your `main.log` and `settings.ini` file?

_Note that both main.log and settings.ini files can be found in C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber in Windows, and in the installation directory on Linux._

**Comment by sinkiller21st** [comment]
here's the main.log

**Comment by sinkiller21st** [comment]
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4270162/main.log)

**Comment by sinkiller21st** [comment]
settings: IDK witch one you needed so I gave all them to you sorry 

[New Compressed (zipped) Folder.zip](https://github.com/Bionus/imgbrd-grabber/files/4270165/New.Compressed.zipped.Folder.zip)

**Comment by sinkiller21st** [comment]
they looked all the same to me 
sorry

**Comment by sinkiller21st** [comment]
main.log and settings.ini are missing below you will find screenshots of main.log and settings.ini when I open the settings it blank

![2](https://user-images.githubusercontent.com/39547304/76709262-ea1b1f00-66d3-11ea-856c-f0406edd0ffb.PNG) 

![1](https://user-images.githubusercontent.com/39547304/76709260-e8e9f200-66d3-11ea-8971-16a70e5a2904.PNG)

**Comment by RinMaru** [comment]
I looked up Hearlesssoul and all search engines checked. app just crashes each time
