### ISSUE TITLE
Re-add Sankaku again

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#1888]
The Sankaku admin is one of the most, if not the most, pathetic admins out there. We already need to add a delay of 10 seconds to prevent the site from spitting out ban errors and he's implemented a lot of crazy stuff to prevent people from downloading images. The irony behind all of this is that he's regularly hoarding from other boorus and he won't let anyone do it on his own site.

Spite that asshole and re-add Sankaku again, thanks

**Comment by urzuse7en** [comment]
I second this. That site doesn't deserve this treatment.

**Comment by y960** [comment]
I definitely third this, Come on Bionus! Don't give in to these pieces of shit from Sankaku! I know you are far better than this. They completely deserve it and there is no legal way that they can get you over this anyway. For starters, re-add Sankaku and stop accepting/following their requests and move on. I apologize for sounded rude or like a jackass here. But this HAS to be said about this matter.

**Comment by HanatakeYurii** [comment]
To be honest I will not update if Grabber cannot access Sankaku anymore. I try to avoid bulking on it but cannot make it other way for some art.
You could at least make a way to let people add it on their own but not adding it yourself, so it would save you from all the burden as it would be in everyone's hands. (... in fact as anyone can fork this, it's already the case).

**Comment by Bionus** [comment]
I understand how you guys feel but I'm not going to get into fights over this.

However, as suggested above by @HanatakeYurii, you're free to add it to your own local installation of Grabber. You just need the `model.js` file which was provided in older versions. And if you only have the `model.ts`, you can also transform it into JS easily with the TypeScript compiler.

**Comment by pencilbook** [comment]
I will not hold your decision against you. I'm going to assume Sankaku's admin is blackmailing you because he's done it to other people in the past.

**Comment by yami-no-tusbas** [comment]
And we have to put the js file in read only too... else grabber will erase it...

**Comment by baraa272** [comment]
i support this , let the user have an option to get sankaku back

**Comment by pencilbook** [comment]
Old version can't download tags with more than 1000 images now. 
Sankaku's admin is an asshole

**Comment by baraa272** [comment]
> 
> 
> Old version can't download tags with more than 1000 images now.
> Sankaku's admin is an asshole

i can upload sankaku files of the most recent grabber update before it got disabled but it have my logon info information so.....

**Comment by StarMaster21** [comment]
Sankaku takes pics from other places so their don't have right to stop you at all and can't do anything to you since artist community piss off at them for reloading their hardwork onto their website without permission. 

Anyway just wanted to share what i think. I hope you support sankaku being allowed on grabber to download pics still. I don't understand complicated stuff on how to do that move file stuff said above.

**Comment by nhoctu97** [comment]
owner kinda generosity for still let you down from sankaku for first time before it disappear the second time I open. My own solution is that I delete everything from \AppData\Local\Bionus then reinstall since I don't have model.js

**Comment by yami-no-tusbas** [comment]
You can also install a version with it, then go to %appdata%\Local\Bionus\sites\ then put the sankaku folder to "read-only", grabber will not be able to delete it. And for future proofing, create an archive with the sankaku folder and back it up somwhere else. If grabber delete the folder, or you uninstall it wathever, just extract the archive gain, put it to read-only and ther you go.

[Sankaku.zip](Here is my archive, save it somwhere and extract it as said above, don't forget to put reald-only on the folder.)

**Comment by Spyridion** [comment]
What's a good past version that has sankaku? I ask this cause I lost my nightly file that had sankaku.

**Comment by CyrilCommando** [comment]
oh well, time to backdate, seeing as sankaku was the only reason i used grabber

no one's gonna go through the hassle of readding the js to the program folder lol

> What's a good past version that has sankaku? I ask this cause I lost my nightly file that had sankaku.

I use 7.1.1

**Comment by Gandeloft** [comment]
> What's a good past version that has sankaku? I ask this cause I lost my nightly file that had sankaku.

https://github.com/Bionus/imgbrd-grabber/releases/tag/v7.1.1

**Comment by TeKett** [comment]
Even on the newest one it still works on first start of the program. So all you have to do is install and then write protect the folder. Its technically disabled as per request, but disabled does not mean removed.

**Comment by SvyraCosmix** [comment]
> The Sankaku admin is one of the most, if not the most, pathetic admins out there. We already need to add a delay of 10 seconds to prevent the site from spitting out ban errors and he's implemented a lot of crazy stuff to prevent people from downloading images. The irony behind all of this is that he's regularly hoarding from other boorus and he won't let anyone do it on his own site.
> 
> Spite that asshole and re-add Sankaku again, thanks

How do I do the 10 second delay thing?

**Comment by SvyraCosmix** [comment]
I am using version 7.1.1 what's the best setup for being about to download images without getting the whole "slow down" message

**Comment by SvyraCosmix** [comment]
Seriously what kinda "fight" could you have with the site DEV for sankaku, what do they know your address, are they gonna leave flaming doggy dookie on your door step how do they have you by the balls like this at least tell us that much @Bionus I'm begging you tell us how some 2-bit hack of a site dev like sankaku's would push you around like this I really do sincerely want to know

**Comment by CyrilCommando** [comment]
If there's anything I know about developers, there's a 99% chance the sankaku dev is holding literally nothing over Bionus, rather, Bionus simply refuses to support sankaku because the admin was mean to him on the internet.

**Comment by SvyraCosmix** [comment]
> If there's anything I know about developers, there's a 99% chance the sankaku dev is holding literally nothing over Bionus, rather, Bionus simply refuses to support sankaku because the admin was mean to him on the internet.

It's seriously fucking frustrating that sankaku has almost double the content of like gelbooru but downloading them is a pain in the ass, having to add a 6s delay cause the sankaku bastards want you to pay for unlimited downloading, it's bullshit

**Comment by SvyraCosmix** [comment]
PRO TIP FOR SANKAKU
Use the date range in tandem with the score range when searching large results like with the tag animal ears which has 800K+ results 
EXAMPLE:
Use batches of one year and within batches of 100 scores you can use greater ranges just experiment with it

animal_ears date:2018.01.01..2019.01.01 score:0..100 
Then
animal_ears date:2018.01.01..2019.01.01 score:101..200

So on and so forth makes things so much simpler but that's only for people like me who download 100's of thousands at a time xD and I have found that a lot of stuff from sankaku is worth the trouble

**Comment by ARDEACT** [comment]
> > If there's anything I know about developers, there's a 99% chance the sankaku dev is holding literally nothing over Bionus, rather, Bionus simply refuses to support sankaku because the admin was mean to him on the internet.
> 
> It's seriously fucking frustrating that sankaku has almost double the content of like gelbooru but downloading them is a pain in the ass, having to add a 6s delay cause the sankaku bastards want you to pay for unlimited downloading, it's bullshit

I bought the subscription so re-mass download my library and they still restrict you but at a certain point far greater than free. But I'm sure they have their reasons, weak ass servers and internet bandwidth perhaps. I mean, it's good because everyone mass downloading at the same time isn't a good experience for others.

**Comment by MDashK** [comment]
Seems Sankaku downloads just stopped working definitely since a few days ago... Grabber returns 0 results and downloads nothing from there. Maybe my script is outdated, but it worked for months up just a few days ago.

**Comment by ARDEACT** [comment]
> Seems Sankaku downloads just stopped working definitely since a few days ago... Grabber returns 0 results and downloads nothing from there. Maybe my script is outdated, but it worked for months up just a few days ago.

Visit my recent issue thread, Someone compiled a new model.js that works with Sankaku’s site changes.

**Comment by SvyraCosmix** [comment]
> > Seems Sankaku downloads just stopped working definitely since a few days ago... Grabber returns 0 results and downloads nothing from there. Maybe my script is outdated, but it worked for months up just a few days ago.
> 
> Visit my recent issue thread, Someone compiled a new model.js that works with Sankaku’s site changes.

Oh I eventually learned you cam just use the json method to download with no rate limit.
