### ISSUE TITLE
Support for Sakugabooru.com please!

### ISSUE THREAD

**Issue by d-mmmy** [Bionus/imgbrd-grabber#1889]
**Is your feature request related to a problem? Please describe**
Sakugabooru.com returns "no valid source of this website returned a value"
 
or am I doing something wrong? Or is there something I should be doing which I'm not?

**Comment by Bionus** [comment]
1. Make sure HTTPS is enabled in the source settings
2. Make sure you use the `www.` prefix when adding it
3. It seems that they are blocking Grabber's default User-Agent, so you might want to change it in the source's settings to one from a real browser, such as `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0`
