### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by General-Trident** [Bionus/imgbrd-grabber#1890]
**Bug description**

Nothing works.
First time installing, and app directory is not in main drive (Local Disc C:) but in my D: disk instead.

**Steps to reproduce**

1. Go to 'Search'
2. Type tags on Search bar

**Expected behavior**

It shows nothing.

**Context**

[Grabr.zip](https://github.com/Bionus/imgbrd-grabber/files/4271500/Grabr.zip)

This .zip file contains main.log, settings.ini, and my log from first time install to later.

**Screenshots**

![image](https://user-images.githubusercontent.com/52889250/75621945-6b9b8900-5bcd-11ea-9e80-6cd3021cdfa6.png)

**System information**

- OS: Windows 10 64-bit
- Grabber version: 7.2.1

**Additional context**

If no possible solution could be given, please give instruction on how to uninstall the app completely so to re-install with default settings again.

**Comment by Bionus** [comment]
I can see in your logs that all the calls to gelbooru timed out.
> Loading error: Connection timed out (99)

Can you maybe try another source and see if it works?

> If no possible solution could be given, please give instruction on how to uninstall the app completely so to re-install with default settings again.

Just uninstall it from Windows or by running `unins000.exe` in the install folder. Then delete the `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber` folder.

**Comment by General-Trident** [comment]
> Just uninstall it from Windows or by running `unins000.exe` in the install folder. Then delete the `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber` folder.

I've followed your instruction to turn it back to default, install it with Grabber nightly just in case (because it shows error "Server Offline", and this is the result:

![image](https://user-images.githubusercontent.com/52889250/77204475-60c97980-6b25-11ea-9ef6-4a6590d73ef5.png)

No result whatsoever.
Kindly please give me your help for solving on this. Thank you.

**Comment by General-Trident** [comment]
P.S.: here's my log. Tell me if you need anything else to solve this.

[Grabber log.txt](https://github.com/Bionus/imgbrd-grabber/files/4361749/Grabber.log.txt)

**Comment by billsargent** [comment]
The connection timeout thing sounds like your IP might have been blocked by the source. Try acceessing the site directly with a web browser. If you cant, then that is probably the reason. Some of these sites are anal about rapid connections.
