### ISSUE TITLE
Build fails - can't find catch2

### ISSUE THREAD

**Issue by clavinet** [Bionus/imgbrd-grabber#1891]
**Bug description**

cmake2 can't be found during build, even though it's installed on the system (catch2-devel)

**Steps to reproduce**

1. build according to these instructions (breakpad disabled)
https://bionus.github.io/imgbrd-grabber/docs/compilation.html
2. build fails

**Context**

compilation log:
```
In file included from /ramdisk/user/imgbrd-grabber-7.2.1/tests/src/auth/auth-test.cpp:4:
/ramdisk/user/imgbrd-grabber-7.2.1/tests/src/catch.h:6:10: fatal error: vendor/catch/single_include/catch2/catch.hpp: No such file or directory
    6 | #include "vendor/catch/single_include/catch2/catch.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /ramdisk/user/imgbrd-grabber-7.2.1/tests/src/exponential-moving-average-test.cpp:2:
/ramdisk/user/imgbrd-grabber-7.2.1/tests/src/catch.h:6:10: fatal error: vendor/catch/single_include/catch2/catch.hpp: No such file or directory
    6 | #include "vendor/catch/single_include/catch2/catch.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/CMakeFiles/tests.dir/build.make:89: tests/CMakeFiles/tests.dir/src/auth/auth-test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /ramdisk/user/imgbrd-grabber-7.2.1/tests/src/filename/filename-resolution-visitor-test.cpp:5:
/ramdisk/user/imgbrd-grabber-7.2.1/tests/src/catch.h:6:10: fatal error: vendor/catch/single_include/catch2/catch.hpp: No such file or directory
    6 | #include "vendor/catch/single_include/catch2/catch.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/CMakeFiles/tests.dir/build.make:219: tests/CMakeFiles/tests.dir/src/exponential-moving-average-test.cpp.o] Error 1
In file included from /ramdisk/user/imgbrd-grabber-7.2.1/tests/src/filename/filename-print-visitor-test.cpp:4:
/ramdisk/user/imgbrd-grabber-7.2.1/tests/src/catch.h:6:10: fatal error: vendor/catch/single_include/catch2/catch.hpp: No such file or directory
    6 | #include "vendor/catch/single_include/catch2/catch.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

(and lots more instances of the same error)

**System information**

- OS: OS: openSUSE Tumbleweed 20200228
- Grabber version: 7.2.1

imgbrd-grabber 7.1.1 (before the dependency on catch2) builds fine on the same machine.

This sentence
`vendor/catch/single_include/catch2/catch.hpp: No such file or directory`
makes me suspect that the build script is searching for a nonexistent vendored catch2 instead of using the system-provided one.

**Comment by Bionus** [comment]
There's no reason to use a version of catch2 provided by the system since it's just a small c++ header file.

The reason it can't be found is, I guess, that you didn't clone the submodules when cloning Grabber. Usually done using `git clone --recursive ...`. But if you just want to build Grabber, you can also just try to build the `gui` target (using `make gui` instead of just ``make`).
