### ISSUE TITLE
Can't select Translation

### ISSUE THREAD

**Issue by SakurabaKiyoka** [Bionus/imgbrd-grabber#1893]
**Bug description**

**Steps to reproduce**
Ver 7.2.1_x64
Windows 10 Japanese 1909 System
1. Go to 'Tools'
2. Click on 'Options'
3. Click General and Language
4. See only English available

Completely install in new virtual machine.reinstall the program,clean the Bionus Folder in appdata.None work.

**Comment by sanddudu** [comment]
Can you find any translation file under "PATH TO GRABBER/languages"?

**Comment by SakurabaKiyoka** [comment]
> Can you find any translation file under "PATH TO GRABBER/languages"? It's confirmed that these language files are included in the setup script.

yes,i see the languages folder and there's languages.ini and ChineseSimplified.qm,English.qm,and some qm file.

**Comment by SakurabaKiyoka** [comment]
I try run grabber with administrator also but nothing happend.

**Comment by SakurabaKiyoka** [comment]
there's the troubleshoot screenshot.
![err](https://user-images.githubusercontent.com/16064020/76044335-63f92d00-5f9d-11ea-82a7-22b0e53be63d.png)

**Comment by 2greh** [comment]
![Аннотация 2020-03-17 233136](https://user-images.githubusercontent.com/62309142/76898818-76ca0680-68a7-11ea-950e-d3bae2364c61.jpg)
Присоединяюсь  к данной проблеме.

**Comment by Bionus** [comment]
Seems to be caused by #1797 since Grabber is looking for a writable path for the languages, while they could be simply opened in read-only. I pushed a commit which should hopefully fix this issue.

**Comment by iDolmatov** [comment]
Copy folder "languages" from C:\Program Files\Grabber to "c:\Users\Alexey\AppData\Local\Bionus\Grabber\" for solved language load.

**Comment by iDolmatov** [comment]
Don't work in release v7.3.0
![1](https://user-images.githubusercontent.com/19782385/83659922-9981d680-a5dd-11ea-8edd-b87de85d0c23.png)
![2](https://user-images.githubusercontent.com/19782385/83659942-a0a8e480-a5dd-11ea-80ee-a59443b81589.png)
![3](https://user-images.githubusercontent.com/19782385/83659946-a272a800-a5dd-11ea-8c85-b86567a44847.png)
![4](https://user-images.githubusercontent.com/19782385/83659947-a30b3e80-a5dd-11ea-8c2c-e4cd80423e5c.png)

**Comment by 123321mario** [comment]
had the same error, doing [this](https://github.com/Bionus/imgbrd-grabber/issues/1893#issuecomment-615359845) fixed it

**Comment by SakurabaKiyoka** [comment]
> had the same error, doing [this](https://github.com/Bionus/imgbrd-grabber/issues/1893#issuecomment-615359845) fixed it

Yeah,It's works but it's the temporary resolve way only.It should be fixed in sources code.
