### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by uis246** [Bionus/imgbrd-grabber#1894]
#### Quiestions

1. What does `forcedTokens`?
2. Is grabber hashes only md5? If yes, why?
3. Is possible to log parser?
4. Is grabber reuse connections? (AFAIK when redirection - no)

#### Possible bug
`[Info] [hiddenbooru.i2p][Json] Parsed page http://hiddenbooru.i2p/api/posts/search?limit=1&page=1&terms=`%some tags%`: 1 images (1), 0 tags (34),`**`-1 total (-1), -1 pages (-1)`**
Custom parser, based on Danboru one

**Comment by uis246** [comment]
Yes, it doesn't reuse connection on redirect

**Comment by Bionus** [comment]
> What does forcedTokens?

It's a list of tokens that, if present in the filename, will force to load the image's details page. For example, if you don't have the date information in the listing page but is present in the details page, you can add "date" to it and it will load the details page before the download.

> Is grabber hashes only md5? If yes, why?

Yes, only MD5. Why not?

> Is possible to log parser?

What do you mean "log parser"? You can use `console.log` (and other `console.*` functions) to generate logs in JS.

> Is grabber reuse connections? (AFAIK when redirection - no)

I can't 100% guarantee you, but Qt network manager uses 6 connections and reuses them as needed.
