### ISSUE TITLE
Crashing on searching certain things

### ISSUE THREAD

**Issue by DingFandango** [Bionus/imgbrd-grabber#1896]
**Steps to reproduce**

1. Open Grabber (fresh install as well)
2. Search "hyuuga_hinata" as suggested by grabber's auto complete
3. Program crash

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/4299478/main.log)

[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/4299482/settings.zip)

**System information**

- OS: Windows 10
- Grabber version: 7.2.1

**Additional Information**
The crashes seem to only happen looking up certain things, but looking up generic tags such as "big_butt" does not lead to a crash.

**Comment by notacompletemoron** [comment]
Second to say that the underscore is causing a crash.
