### ISSUE TITLE
does not work right 

### ISSUE THREAD

**Issue by sinkiller21st** [Bionus/imgbrd-grabber#1903]
every time I try to use grabber 7.2.1 it crushes. every time I open a new tab or try to go to the next page it stops responding and closes itself. this is my third time retrying to use this version.
I started to use the previous version it works a lot better but has missing tabs, for example, I can type the same thing I want in both but the newer version has more images but, the problem do I want a grabber that has more images but don't work correctly or work correctly but has fewer search results AKA images. 
[Grabber_v7.1.zip](https://github.com/Bionus/imgbrd-grabber/files/4334913/Grabber_v7.1.zip)

for some reason, it won't let me upload the grabber v_7,2,1 so ill upload a screenshot
![Capture](https://user-images.githubusercontent.com/39547304/76708865-9eb34180-66d0-11ea-87b0-6dd875c883fc.PNG)

.HFS+ Private Directory Data_ is empty 
[HFS+ Private Data] is empty

**Comment by sinkiller21st** [comment]
I tried to redownload 3 or 4 times now and it never resolves the issues

**Comment by sinkiller21st** [comment]
I'm using windows 10

**Comment by sinkiller21st** [comment]
I'm using v7,2,1 & Grabber_v7.1

**Comment by sinkiller21st** [comment]
main.log and settings.ini are missing below you will find screenshots of main.log and settings.ini when I open the settings it blank

![2](https://user-images.githubusercontent.com/39547304/76709262-ea1b1f00-66d3-11ea-856c-f0406edd0ffb.PNG) 

![1](https://user-images.githubusercontent.com/39547304/76709260-e8e9f200-66d3-11ea-8971-16a70e5a2904.PNG)

**Comment by sinkiller21st** [comment]
![3](https://user-images.githubusercontent.com/39547304/76709368-9c52e680-66d4-11ea-8443-ae0bbaec0b99.PNG)
![5](https://user-images.githubusercontent.com/39547304/76709369-9d841380-66d4-11ea-8494-f71ce6036b83.PNG)

**Comment by brazenvoid** [comment]
Why don't you uninstall grabber and also remove the "Bionus" folder from:
%APPDATA%\..\Local
(Paste the above in the file explorer's address bar.)

Then only download this installer for windows and install it:
https://github.com/Bionus/imgbrd-grabber/releases/download/v7.2.1/Grabber_v7.2.1_x64.exe

Grabber does not run from the place you store the installer so whatever files in there are irrelevant for reporting issues. 

To get to the Grabbers configuration folder, open grabber and click on "Open options folder" in the file menu. You will find the main.log and settings.ini there.
