### ISSUE TITLE
Crash when middle clicking on specific tags in image views

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1905]
This started happening with the latest release. 

Oddly some tags will always crash the app. Again oddly if same tag is already open in a tab, the crash will not happen and a new tab with the same tag will open correctly.

**Steps to reproduce**

1. Open "skstalker" tag search with rule34.xxx and gelbooru as sources and merged results
2. Open any image
3. Close the search page
4. Middle Click on the stkstalker tag in the image view

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/4345275/main.log)
[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/4345278/settings.zip)

For some reason the app is not producing dumps.

**System information**

- OS: Windows 10 1909
- Grabber version: v7.2.1

**Comment by brazenvoid** [comment]
Crashed on tag: living_sex

**Comment by Bionus** [comment]
Indeed, I could reproduce this in both 7.2.1 and nightly. The steps are very simple:
1. Open an image from any tab
2. Close the original tab
3. Open any tag from the image in a new tab (ex: middle click)

Thanks for the report! I'll push a fix ASAP.
