### ISSUE TITLE
Rule34.xxx - No result

### ISSUE THREAD

**Issue by bloodvladLoL** [Bionus/imgbrd-grabber#1908]
After the update, rule34.xxx stopped working.
rule34.xxx - No result
No valid source of the site returned result.
Login test = Failure.
A clean reinstall did not help.
Does anyone have the same problem?

**Comment by sbobbo** [comment]
It's working fine for me. Try uninstalling, deleting the appdata folder, then reinstalling. 

I also once had similar issues and the 32 bit version worked while the 64 bit version didn't
