### ISSUE TITLE
Add a local filter configuration

### ISSUE THREAD

**Issue by ThankGoshForDucks** [Bionus/imgbrd-grabber#1909]
It would be great to be able to filter out images that already exist in the MD5 database. 
Additionally adding the ability to filter out videos/animated images would be really nice. 

I'd like a local filter option group on the image search-tab interface with the options for filtering by static/animated and filtering out images that have already been downloaded.

**Comment by Bionus** [comment]
> It would be great to be able to filter out images that already exist in the MD5 database

You can use the following undocumented (for now, I'll add some ASAP) tokens for that:
* `grabber:alreadyExists` (already exists on disk)
* `grabber:inMd5List` (already exists in the MD5 list)
* `grabber:downloaded` (already exists on disk or in the MD5 list)

>  Additionally adding the ability to filter out videos/animated images would be really nice.

Have you tried the `ext` token as a filter? Such as `-ext:mp4 -ext:gif`? Or simply ignoring the "animated" tag altogether with `-animated`?
