### ISSUE TITLE
Profile only uses one path for all resources

### ISSUE THREAD

**Issue by Flat** [Bionus/imgbrd-grabber#1910]
**Bug description**

Currently when Grabber loads a profile upon start it takes the first directory it finds as writable and uses that for all files. If the user does not have sources and other resource files in that location it will fail to start.

**Steps to reproduce**

https://github.com/Bionus/imgbrd-grabber/blob/master/gui/src/main/main.cpp#L100

**Expected behavior**

Grabber should use the first writable location for files it can generate and search other default locations such as `/usr/share/Grabber/release` on Linux for sources if they are not located in the `savePath()` location. Profile should try different folder locations and set them as internal variables instead of one root path.

**Comment by Bionus** [comment]
There should be a huge improvement for this in 7.8.0, with the application reading files in the read-only application directory (unless overridden in the settings directory), and writes to the config directory.
