### ISSUE TITLE
Error compiling TS files

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#1913]
Hello Bionus

after noticing that sankaku deletes itself from the source list when closing/reopening grabber, i followed your advice to manually add it,  since i could not find model.js in grabber, 4.0 version( in all new versions is a model.xml) , i tried the ts compiler solution.

I installed npm and through that tsc

WHen i start cmd  and type in tsc and drag then the model.ts from the source code of the newest version into the cmd window it starts compiling but ends up with 21 errors.

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:1:29 - error TS2304: Cannot find name 'IImage'.

1 function completeImage(img: IImage): IImage {
                              ~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:1:38 - error TS2304: Cannot find name 'IImage'.

1 function completeImage(img: IImage): IImage {
                                       ~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:11:22 - error TS2304: Cannot find name 'ISource'.

11 export const source: ISource = {
                        ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:69:38 - error TS2304: Cannot find name 'Grabber'.

69                     const pagePart = Grabber.pageUrl(query.page, previous, opts.loggedIn ? 1000 : 50, "page={page}", "prev={max}", "next={min-1}");
                                        ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:72:39 - error TS2304: Cannot find name 'IParsedSearch'.

72                 parse: (src: string): IParsedSearch => {
                                         ~~~~~~~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:75:35 - error TS2304: Cannot find name 'IImage'.

75                     const images: IImage[] = [];
                                     ~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:91:71 - error TS2304: Cannot find name 'IError'.

91                 url: (query: any, opts: any, previous: any): string | IError => {
                                                                         ~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:93:42 - error TS2304: Cannot find name 'Grabber'.

93                         const pagePart = Grabber.pageUrl(query.page, previous, opts.loggedIn ? 50 : 25, "page={page}", "prev={max}", "next={min-1}");
                                            ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:99:39 - error TS2304: Cannot find name 'IParsedSearch'.

99                 parse: (src: string): IParsedSearch => {
                                         ~~~~~~~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:101:47 - error TS2304: Cannot find name 'Grabber'.

101                     const searchImageCounts = Grabber.regexMatches('class="?tag-(?:count|type-none)"? title="Post Count: (?<count>[0-9,]+)"', src);
                                                  ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:102:38 - error TS2304: Cannot find name 'Grabber'.

102                     const lastPage = Grabber.regexToConst("page", '<span class="?current"?>\\s*(?<page>[0-9,]+)\\s*</span>\\s*>>\\s*</div>', src);
                                         ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:103:32 - error TS2304: Cannot find name 'Grabber'.

103                     let wiki = Grabber.regexToConst("wiki", '<div id="?wiki-excerpt"?[^>]*>(?<wiki>.+?)</div>', src);
                                   ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:106:31 - error TS2304: Cannot find name 'Grabber'.

106                         tags: Grabber.regexToTags('<li class="?[^">]*tag-type-(?<type>[^">]+)(?:|"[^>]*)>.*?<a href="[^"]+"[^>]*>(?<name>[^<]+)</a>.*?<span class="?post-count"?>(?<count>\\d+)</span>.*?</li>', src),
                                  ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:107:33 - error TS2304: Cannot find name 'Grabber'.

107                         images: Grabber.regexToImages('<span[^>]* id="?p(?<id>\\d+)"?><a[^>]*><img[^>]* src="(?<preview_url>[^"]+/preview/\\w{2}/\\w{2}/(?<md5>[^.]+)\\.[^"]+|[^"]+/download-preview.png)" title="(?<tags>[^"]+)"[^>]+></a></span>', src).map(completeImage),
                                    ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:109:47 - error TS2304: Cannot find name 'Grabber'.

109                         pageCount: lastPage ? Grabber.countToInt(lastPage) : undefined,
                                                  ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:110:70 - error TS2304: Cannot find name 'Grabber'.

110                         imageCount: searchImageCounts.length === 1 ? Grabber.countToInt(searchImageCounts[0].count) : undefined,
                                                                         ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:118:39 - error TS2304: Cannot find name 'IParsedDetails'.

118                 parse: (src: string): IParsedDetails => {
                                          ~~~~~~~~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:120:32 - error TS2304: Cannot find name 'Grabber'.

120                         pools: Grabber.regexToPools('<div class="status-notice" id="pool\\d+">[^<]*Pool:[^<]*(?:<a href="/post/show/(?<previous>\\d+)" >&lt;&lt;</a>)?[^<]*<a href="/pool/show/(?<id>\\d+)" >(?<name>[^<]+)</a>[^<]*(?:<a href="/post/show/(?<next>\\d+)" >&gt;&gt;</a>)?[^<]*</div>', src),
                                   ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:121:31 - error TS2304: Cannot find name 'Grabber'.

121                         tags: Grabber.regexToTags('<li class="?[^">]*tag-type-(?<type>[^">]+)(?:|"[^>]*)>.*?<a href="[^"]+"[^>]*>(?<name>[^<]+)</a>.*?<span class="?post-count"?>(?<count>\\d+)</span>.*?</li>', src),
                                  ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:122:35 - error TS2304: Cannot find name 'Grabber'.

122                         imageUrl: Grabber.regexToConst("url", '<li>Original: <a href="(?<url>[^"]+)"|<a href="(?<url_2>[^"]+)">Save this file', src).replace(/&amp;/g, "&"),
                                      ~~~~~~~

Downloads/imgbrd-grabber-7.0.1/imgbrd-grabber-7.0.1/release/sites/Sankaku/model.ts:123:36 - error TS2304: Cannot find name 'Grabber'.

123                         createdAt: Grabber.regexToConst("date", '<a href="/\\?tags=date[^"]+" title="(?<date>[^"]+)">', src),
                                       ~~~~~~~

Found 21 errors.

surprisingly it does not delete itself anymore after  copying the  model,js that was generated after the process  to a clean install, but it does not find any pictures neither, Could that be because of the errors. I used the correct login details neither idol nor chan can fetch any results.

I could try with a model.js but i cannot find it, how old must the version bs, could u maybe  upload a model ts, for people to reintegrate sankaku, or do i need  to do something with the model.xml?

Thnx for your time.

Win 10 
Latest Grabber Version. 7.21
Related case #1888

**Comment by Bionus** [comment]
If there's any error shown, it won't work. At best you can ignore warnings, but not errors.

If you already have NPM installed, you need to download the Grabber repository (either via Git or via a ZIP generated by Github) then go to the `release/sites` directory. Then just run `npm install` then `npm run build` (which is a shortcut for `tsc -p tsconfig.json`), and the JS files for all sources will be generated from the TS files.

**Comment by DraGoran** [comment]
> If you already have NPM installed, you need to download the Grabber repository (either via Git or via a ZIP generated by Github) then go to the release/sites directory. Then just run npm install then npm run build (which is a shortcut for tsc -p tsconfig.json), and the JS files for all sources will be generated from the TS files.

what u mean by that, where can i find it? The Grabber repository, do u mean the source code.zip?

Also what is the model.xml about?

Should i drag in the folder into the cmd???
