### ISSUE TITLE
Opening an image from the results trigger the SQL commands

### ISSUE THREAD

**Issue by HerpToTheDerp** [Bionus/imgbrd-grabber#1914]
**Bug description**

When downloading and importing into a Gelbooru instance, two posts are made and tags are not valid. 

**Steps to reproduce**

1. Followed the GelBooru documentation for Bionus. 
2. Install the QTMySQL drivers (See Issue 1892)
3. Set up connection to SQL server. 
4.. Use the same commands in the Bionus guide. 
5.. Save an image from any source. 

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/4390458/main.log)

* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.

[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/4390482/settings.zip)

**System information**

- OS: Windows 10
- Grabber version: V7.2.1
- Gelbooru version: Beta 0.1.11

**Additional context**

This is a Booru server that is hosted on a different server than the host I am on. I also tried the nightly build with the same issues.

**Comment by Bionus** [comment]
I can see the double `SQL execution of "INSERT INTO posts"` in your log, so I'll investigate why this happens for you.

However, I'm not sure what you mean by "broken tags"? Is it caused by the double insert in the posts? Because the SQL for tags doesn't seem to have any issues?

**Comment by HerpToTheDerp** [comment]
I'm not sure exactly what is causing it but the tags are kind of "phantom" so to speak. They get made and linked to the image, but there's no tag count (amount of images with that tag) and they are all hidden on the booru by default unless you show them. 

I've attached an image, hopefully it helps make sense of the issue. I know how to fix the broken thumbnails I just didn't fix them as a sort of sensor. 

![snip](https://user-images.githubusercontent.com/62727017/77802975-162a8e80-704a-11ea-9459-3227f3760123.PNG)

**Comment by HerpToTheDerp** [comment]
There are no longer two images on the booru when saving in the nightly build however the tag's still have the same issues for me.

**Comment by Bionus** [comment]
Not sure why you say it's related to tags since it's just because the thumbnail was not generated?

Check the bottom part of the tutorial, it's mentioned there:
https://bionus.github.io/imgbrd-grabber/docs/commands/gelbooru.html#thumbnails

You should open `thumbs_fix.php`.

**Comment by HerpToTheDerp** [comment]
Running the thumbnail fix doesn't correct the tag count or put it in the newest image category.

**Comment by Bionus** [comment]
Did you properly add the "tag" command? Because from your settings file it seems like you haven't:
```sql
INSERT INTO tag_index(tag, index_count) VALUES("%tag%", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;
```

**Comment by HerpToTheDerp** [comment]
Just added the tag command back in, it still does the same thing. I'm not sure if this will help but I've included an updated log from when I tested. 
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4429991/main.log)

**Comment by Bionus** [comment]
> Just added the tag command back in, it still does the same thing. I'm not sure if this will help but I've included an updated log from when I tested.

I just checked your log and it contains:
```
[16:21:18.949][Info] SQL execution of "INSERT INTO tag_index(tag, index_count) VALUES("'Steven_Universe'", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;
"
```

I see two main issues here:
* Why is there a line break at the end of your command? (it can be seen by the double quote on a new line) Did you add the commands by editing the INI file somehow?
* The tags are getting escaped but are already in double quotes, so in your database you're having both `Steven_Universe` (generated from adding the image, and without count), and `'Steven_Universe'` with single quotes (generated from the tag command, with a count of 1).

My bad then, you should use the command without the quotes around `%tag%`:
```sql
INSERT INTO tag_index(tag, index_count) VALUES(%tag%, 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;
```

**Comment by HerpToTheDerp** [comment]
That seems to fix the tagging issue (I deleted my config and remade it in the client with the new setting you posted above). Images still don't appear to be showing up in Newest Images, but at least the tags are working now.
