### ISSUE TITLE
A way to blacklist pictures that don't have known artists?

### ISSUE THREAD

**Issue by Enchoseon** [Bionus/imgbrd-grabber#1915]
I only use pictures that have a known artist. Is there a way to hide artist-less pictures from the search results entirely?

**Comment by Bionus** [comment]
Have you tried using `-%artist%` in your blacklist? AFAIK it should work:
* `-` to invert the filter
* `%artist%` to detect if the `artist` token is non-empty

**Comment by Enchoseon** [comment]
So I tried doing what you said using Gelbooru as the source—

> Search: "zero_two_(darling_in_the_franxx)"
> Blacklist: -%artist%
> Result: A **lot** of unrelated pictures gone, still got some unknown artist pictures. Very confused.

—But it didn't work :/

I also tried some more things—

> Search: "zero_two_(darling_in_the_franxx)"
> Blacklist: %artist%
> Result: Nothing changed. If something did, it was so slight I didn't notice it.

> Search: "zero_two_(darling_in_the_franxx) -%artist%"
> Result: Still got pictures without any artist on them. A few things were filtered out, but I couldn't figure out why they were filtered out.
> edit: The "-%artist%" might've removed all pictures with tags that contained "_(artist)" in them. Maybe.

> Search: "zero_two_(darling_in_the_franxx) %artist%"
> Result: Nothing showed up.

—But they also didn't work.

My theory, which is really just an uneducated guess, is that "%artist%" only works on pictures that contain a tag with "\_(artist)" in them, meaning that tags that don't have "\_(artist)" in them aren't recognized correctly, or something.

I haven't tried doing this on other sources yet, but I'll go and try that right now.

**Comment by Enchoseon** [comment]
Okay so I tried using "-%artist%" on other sources besides Gelbooru to see if it worked correctly:

**Danbooru: "-%artist%" works as intended**
> Search: "chike_iii"
> Blacklist: "-%artist%"
> Result: Nothing happened; **this was supposed to happen**.

> Search: "cy_(artist)"
> Blacklist: "-%artist%"
> Result: Nothing happened; **this was supposed to happen**.

> Search: "zero_two_(darling_in_the_franxx) artist_request"
> Blacklist: -%artist%
> Result: Filter worked correctly, only filtered out posts without any artist tag; **this was supposed to happen**.

> Overall: "-%artist%" works correctly in Danbooru.

**Yande.re & Gelbooru: "-%artist%" doesn't work as intended**
> Search: "chike_iii"
> Blacklist: "-%artist%"
> Result: All images filtered out; **this was not supposed to happen**

> Search: "cy_(artist)" for Gelbooru & "miya_(artist)" for Yande.re
> Blacklist: "-%artist%"
> Result: Nothing happened; **this was supposed to happen**

> Search: "zero_two_(darling_in_the_franxx)"
> Blacklist: -%artist%
> Result: Only pictures that had a tag with "_(artist)" in them were kept. Many others were falsely filtered out; **this was not supposed to happen**

> Overall: "-%artist%" does not work correctly in Gelbooru or Yande.re. It appears that "-%artist%" only filters pictures with artists that have a "_(artist)" at the end of them.

**Comment by Bionus** [comment]
That would be because the Gelbooru API does not provide the tag type information. That is, when returning the tags together with the images, it doesn't say which type is each tag (artist / general / character / etc).

A fix would be to use the tag loader to download Gelbooru's tag information:
https://bionus.github.io/imgbrd-grabber/docs/tools/tag-loader.html

Can you try and tell me if it fixes this issue?
