### ISSUE TITLE
Is there a way to force re-download a picture already known (md5)?

### ISSUE THREAD

**Issue by HanatakeYurii** [Bionus/imgbrd-grabber#1919]
Hi,

I think everything is in the title: I have accidentally deleted some pictures, I'm using md5 to avoid duplicates but it prevent me to download them again even if I 'delete' them by clicking multiple time on the 'Save' button ('Save' > 'MD5 already exists' > 'Delete').

Any idea?

**Comment by HanatakeYurii** [comment]
I found a way to go around this but I'm not quite fan of it:
I disabled all options related to duplicates temporarily. 
I works, but it kinda mess up the md5 purpose since I can't know wether a pic is in the md5 list or not, so some are not properly registered.

**Comment by brazenvoid** [comment]
Already reported and identified bug: #1877 

So currently there is no way to make this work unless you disable the keep in md5 even when deleted option.

**Comment by brazenvoid** [comment]
Though you can use the post filter **-grabber:downloaded** to filter out images already existing on disk.

**Comment by Bionus** [comment]
Isn't this issue only caused by "Keep deleted files in MD5 list"?
Because even if the file was already downloaded, if it was deleted on disk, next time you try to save it it will be saved correctly.

**Comment by brazenvoid** [comment]
When that option is enabled, the interface does not delete the md5, even when we click the delete option (the UI auto progresses state to deleted regardless) and that md5 does not allow saving the image. 

So the buttons cycle endlessly: Save ->MD5 already exists ->Delete -> Save -> MD5 already exists ->Delete -> so on

**Comment by brazenvoid** [comment]
Here the delete should force delete the image and MD5 regardless of setting,

**Comment by Bionus** [comment]
> Here the delete should force delete the image and MD5 regardless of setting

I guess it makes more sense than the current behavior so I'll do that.
Then that would fix this issue and the weird cycle you mention in your previous comment.

**Comment by HanatakeYurii** [comment]
brazenvoid got what I wanted to say and is completely right saying:
> Here the delete should force delete the image and MD5 regardless of setting. You may rename it "Force Delete" instead.
Thanks for fixing this Bionus <3
