### ISSUE TITLE
All Derpibooru searches show no results after an API change.

### ISSUE THREAD

**Issue by Wiiplay123** [Bionus/imgbrd-grabber#1924]
**Bug description**

All Derpibooru searches show no results after Derpibooru switched from the old Booru-on-rails backend to their new Philomena backend.

**Steps to reproduce**

1. Make sure "derpibooru.org" is checked in the sources window. (I don't remember if this comes with Grabber by default, but if you don't have it in Sources, add it and set the booru type to Booru-on-rails.)
2. Search for a tag in the search bar that is known to have more than 0 results.
3. Below the search bar it will say "Derpibooru - No result"

**Expected behavior**

The results for that tag appearing below the search bar.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/4423231/main.log)

**Screenshots**

Derpibooru box checked in the sources window:
![2020-04-02 14_40_00-Sources - Grabber](https://user-images.githubusercontent.com/9746793/78294348-deab5e80-74ef-11ea-93f2-a7b74b9ea65d.png)

The lack of search results:
![2020-04-02 14_39_40-Grabber](https://user-images.githubusercontent.com/9746793/78294431-fda9f080-74ef-11ea-956c-dcac5f055a43.png)

**System information**

- OS: Windows 7 SP1 (x64)
- Grabber version: 7.1.1 (x64) and 7.2.1 (x64)

**Additional context**

I first noticed this bug today on 7.1.1 (x64), and updated to 7.2.1 (x64) today in an attempt to fix it, but it still wasn't fixed. https://derpibooru.org/pages/api was last updated 4 days ago, so I'm assuming that's when they dropped their compatability with the old API.

Calls to Derpibooru's search.json now return 400 Bad Request, but my main.log (from 7.2.1, attached above) shows it as "Bad Request (302)" for some reason.

**Comment by dsp2003** [comment]
Can confirm. They actually announced the old API was deprecated and would get dropped within a couple months after Philamena's public release to give people enough time for migration to new API. Guess nobody gave a damn until a roasted rooster bit them in the flank, huh?

**Comment by Bionus** [comment]
For reference:
* API documentation: https://derpibooru.org/pages/api
* Post about migration: https://derpibooru.org/forums/meta/topics/philomena-open-beta-breaking-api-changes
