### ISSUE TITLE
You serious?

### ISSUE THREAD

**Issue by SvyraCosmix** [Bionus/imgbrd-grabber#1938]
How much of a pussy you gotta be to remove sankaku just cause they told you to, tell em to go fuck themselves.

**Comment by Bionus** [comment]
If you have questions about it you have issue #1888

Also, are _you_ serious to create this kind of issue to insult me after all the work I put in this program over the years?

**Comment by SvyraCosmix** [comment]
Very serious, there's no doubt your program is great, but to be pushed
around by a site that could do nothing to you, grow some balls dude.

**Comment by SvyraCosmix** [comment]
My question is...what will you do when more of the big sites find out about
this program, like e621, gel, and derp, and they ask for the same thing.
What then my d00d, all this hard work over the last few years will have
meant nothing, I suggest reinstating chansankaku and show them you wont
stand for it.

**Comment by SvyraCosmix** [comment]
I've been a fan of your program since version 2, I dont want to see it go
to shit.
