### ISSUE TITLE
Creating Files I don't own

### ISSUE THREAD

**Issue by AnonSkunk** [Bionus/imgbrd-grabber#1939]
every folder and file it makes is owned by root, not my user, making it very hard to delete anything or modify anything

**Comment by Bionus** [comment]
How do you start/run the program exactly?

**Comment by AnonSkunk** [comment]
sudo ./Grabber , if I run without sudo I get errors left and right, even when I do run with sudo it keeps freezing after downloading x ammount of images

**Comment by Bionus** [comment]
Well of course if you run it with sudo created files will be owned by root, since that's what sudo does.
Remove the sudo and try to fix the errors instead. If you can't find a solution you can post them here.
