### ISSUE TITLE
pixix unable to load

### ISSUE THREAD

**Issue by jekestar** [Bionus/imgbrd-grabber#1940]
![{PRSMB1VLN`E%DGGB$6RY0H](https://user-images.githubusercontent.com/64252359/80191467-56306180-8648-11ea-9492-f81e53f5053e.png)
Ask for help

**Comment by Bionus** [comment]
That's because you didn't search anything.
I'll push a change so that it shows the newest images (https://www.pixiv.net/new_illust.php) if nothing is entered.
