### ISSUE TITLE
Pixiv Bookmark

### ISSUE THREAD

**Issue by Teemash** [Bionus/imgbrd-grabber#1944]
I found the program very good for downloading images, I had no problems with Gelbooru, I am very grateful to you.
I was wondering if you have plans to add the Pixiv bookmark, I haven't found any program that is simple and practical to use like yours.

Or if you already have, how do I download the images I liked / left in my bookmark?

**Comment by Bionus** [comment]
There was  plans to add support, but since it's easy to add I'll add it in the next release 👌
Syntax will be `bookmarks:USER_ID`.

**Comment by Teemash** [comment]
Dude, thank you very much, how will it work to do the downloades after you add?

Will it be put on the next version "nightly" or "official"?

**Comment by Bionus** [comment]
Not sure what you mean by your question?

The change should already be in the [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) release, and will be in the next "official" release as well, when it comes out.

**Comment by Teemash** [comment]
Sorry, I have mental problems.

Also, I think it has a bug, Grabber doesn't take all of my favorites, it only takes 30 and I can't change the page.

**Comment by Bionus** [comment]
> Also, I think it has a bug, Grabber doesn't take all of my bookmarks, it only takes 30 and I can't change the page. Stay like this https://imgur.com/a/LmVcpKi

Indeed, seems like the pagination for bookmarks is slightly different than for other Pixiv APIs. I just pushed a fix 👍

**Comment by Teemash** [comment]
Thanks for fixing this, so I think I found another bug. When I try to download a lot of images that is my case, "49k of bookmarks", it just doesn't download them all, I managed to download only 1900.

If you can fix it, the bookmarks part will be perfect.

**Comment by Bionus** [comment]
Can you clarify "it just doesn't download them all"?
What happens after the 1900 images? Can you show the log to see if there's any error or warning there?

**Comment by Teemash** [comment]
Said he had downloaded everything, but in reality he only downloaded 1900 out of 49000.
I don't know what happened, I tried to download it again and don't download more than that.

**Comment by Bionus** [comment]
Have you tried setting the "Images per page" to 30 instead of 1000?
The bookmarks API only support 30 images per page.

I'm event surprised you managed to get 1900 images as 30*50000/1000=1500.

**Comment by Teemash** [comment]
Hello again, still buggy, I can't download more than 1000 images anyway, I tried several ways and nothing to get ... :/
Can you try to download them all? If you want to test using my ID it is 27317565

**Comment by Bionus** [comment]
I just tried and could download them with no issues in the Nightly version.
Check your logs and see if there's anything obvious to see there, because it's working.
