### ISSUE TITLE
Custom token always return empty string with e621 and anime-pictures.net

### ISSUE THREAD

**Issue by Max-HR** [Bionus/imgbrd-grabber#1945]
**Bug description**

No matter the content of the custom token or the tags of the image, with e621 and anime-pictures.net, it will always return an empty string.
Tried with other site and the functionality is working as expected

**Steps to reproduce**

1. Create a custom token (here named "test" with the tags "a c e")
2. Put the custom token in the filename (here %md5%-[%test%].%ext%)
3. Set the source to e621 or anime-pictures.net
4. Save an image containing at least 1 of the tags in the custom token (here tags are "b","c","d","e")

Result : The custom token is replaced with an empty string : 
    here 455472b522fd0a1e27aaa91c4033db65-[].jpg

Expected filename : 455472b522fd0a1e27aaa91c4033db65-[c e].jpg

**System information**

- OS:  Windows 10
- Grabber version: Nightly build (released on April 25th 2020) (e621) and v7.2.1. (anime-pictures.net)

**Additional context**
From what I've found, I think that the source of the bug may be linked to the fact that those 2 sites are the only ones whos get their tags (and other meta info) uniquely from JSON files.

**Comment by Bionus** [comment]
I didn't have time to take a look yet but I see you closed the issue?
Did you find the problem?

**Comment by gingeraleeeee** [comment]
I have the exact same problem. (I already submitted a post though, sorry Bionus.)
If you could tell me how you solved it, Max, I would really appreciate it!
