### ISSUE TITLE
Load more than one .igl file when using the load button/Drag and drop .igls to load them?

### ISSUE THREAD

**Issue by AphelionHalcyon32** [Bionus/imgbrd-grabber#1949]
**Is your feature request related to a problem? Please describe**

When loading .igl files via the "Load" button, you can only select one file. If the user has many .igl files they want to load, it becomes tedious loading each one one by one.

**Describe the solution you'd like**

Either: 

- Be able to select multiple files from the files selection window which will then load all of them to the download window. Or;

- be able to drag and drop them from your file explorer to be auto-loaded by the UI. (This only searches an unrelated md5.)

**Describe alternatives you've considered**

Manually loading them using the "Load" button. 

One can of course just:
create tabs by searching > "get all" to load them the the download window for each tab > save a huge .igl file with all the tabs. 

However, some may want an .igl file per search. Or may have more than one huge .igl file. It would be nice to just select them all, and load them into the download UI. Or drag and drop them into the UI (for download) to load them.

**Additional context**

**Comment by Bionus** [comment]
> * Be able to select multiple files from the files selection window which will then load all of them to the download window. Or;
> * be able to drag and drop them from your file explorer to be auto-loaded by the UI. (This only searches an unrelated md5.)

Indeed, both those suggestions make sense so I'll implement both in the next release 👌
I can see how it can be annoying to have to load them one by one otherwise.
