### ISSUE TITLE
Searching Pixiv

### ISSUE THREAD

**Issue by Roshri** [Bionus/imgbrd-grabber#1950]
I was wondering if there was a way for grabber to search pixiv by artist. Or if providing an artist ID it could pull all the artworks from that same account.
so far I could only search by tag, series or character name.
I know that pixiv supports search by user but I can't find a way to replicate it on grabber

**Comment by Bionus** [comment]
It's currently not supported by Grabber. Currently, only search by tags is supported.

But just like how bookmarks (issue #1944) were added quite easily, I guess I can add search by user as well for the next version.

Syntax will be `user:USER_ID`

**Comment by Roshri** [comment]
Tested, working as expected!
That was fast!
Thanks
