### ISSUE TITLE
sankaku and one or two more disappear permanently until i reinstall the program

### ISSUE THREAD

**Issue by TeKett** [Bionus/imgbrd-grabber#1951]
Not sure what is causing it, but after starting the program 2-3 times, doing normal stuff, then just poof, gone. https://prnt.sc/s97qu9 https://prnt.sc/s97rsb

**Comment by fapoverflow** [comment]
#1888

**Comment by TeKett** [comment]
> #1888

technically not disabled tho if it works for like 2 days every time you install the latest version.
