### ISSUE TITLE
Crashes while adding favorites

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1953]
The favorite though is always added correctly despite the crash.

**Case 1 STR:**

After doing multiple searches in the same tab:
1. Add a tag from the search bar as favorite
2. Click back to get to the previous search.

Keep repeating the steps and the app will crash.

**Case 2 STR**

Run a batch download and try to add multiple favorites. The app will randomly crash with one of them.

**Context**

[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/4571634/settings.zip)

The program does not produce dumps for these crashes.

**System information**

- W10 64bit 1909
- Grabber version: Nightly

**Comment by Bionus** [comment]
> *Add a tag from the search bar as favorite
> * Click back to get to the previous search.

I could reproduce this crash and just pushed a fix.

> Run a batch download and try to add multiple favorites. The app will randomly crash with one of them.

However, this one I couldn't reproduce.

Are you also adding favorites from the search bar? Can you reproduce on the latest nightly with the fix 6a5f88ce433324008b8b10492e2c39ed756fc388 for the first crash? (in case they're two symptoms of the same bug)

**Comment by brazenvoid** [comment]
Yes it seems to be a symptom of the earlier crash, haven't encountered the crash since.

**Comment by brazenvoid** [comment]
@Bionus so it is crashing with tag name case issue now.

I already have a favorite: hydrafxx animated height:>=700 width:>=700
I am trying to add: hydraFXX content:video size>700x700

**Comment by brazenvoid** [comment]
Its crashing but it is only occurring for the above query for some reason. I have tried some more and they worked fine. So the issue is not completely fleshed out yet.

**Comment by brazenvoid** [comment]
Happened with the following queries (I will keep updating):
- added: pestilencesfm width:>=700 filesize:>2mb 
- present: pestilencesfm animated width:>=700 rating:explicit

**Comment by Bionus** [comment]
> Happened with the following queries (I will keep updating):
>
> * added: pestilencesfm width:>=700 filesize:>2mb
> * present: pestilencesfm animated width:>=700 rating:explicit

Did it crash as soon as you clicked the "add favorite" option? Or did you do something else at the same time to cause the crash? (such as closing the tab, changing the page, etc.)

And by added/present, you mean the "present" was already one of your favorites, and you tried to add the "added" one?

**Comment by brazenvoid** [comment]
It first goes unresponsive after clicking add and then crashes a few seconds later.

Yes by present I mean, that tag is already present in the favorites list. What I am doing here is adding a r34 paheal tailored favorite while the already present is for danbooru like sites.

**Comment by brazenvoid** [comment]
Got one consistent case!

It is when all of the images get filtered and then you add the favorite. I guess it isn't able to find an image to allocate as pic for the favorite and thus crashes.

**Comment by Bionus** [comment]
> It is when all of the images get filtered and then you add the favorite. I guess it isn't able to find an image to allocate as pic for the favorite and thus crashes.

I can indeed reproduce this, since Grabber tries to get a non-existing first result to set as a thumbnail for the new favorite. I just pushed a fix for this one.

-----

However, I couldn't reproduce the other one. I could add both favorites with no issues. 🤔

**Comment by brazenvoid** [comment]
That's quite fine. I'll report any more cases when I find them. For me this issue is fixed sufficiently.
