### ISSUE TITLE
Wiki / Compilation instructions gone?

### ISSUE THREAD

**Issue by TogarUshindi** [Bionus/imgbrd-grabber#1954]
https://github.com/Bionus/imgbrd-grabber/wiki/Compilation (linked from README.md) seems to be missing. It returns you to https://github.com/Bionus/imgbrd-grabber

**Comment by Bionus** [comment]
The wiki was migrated to the website a while back:
https://bionus.github.io/imgbrd-grabber/docs/compilation.html

**Comment by TogarUshindi** [comment]
I would if I knew how. :)
