### ISSUE TITLE
Add special grabber post filters to autocomplete list by default

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1955]
**Is your feature request related to a problem? Please describe**

Currently to know which filters exist or verify their name for use, I have to find them in the wiki or the issues section. Auto-complete will make this a lot easier.

**Describe the solution you'd like**

Simply make these tags a part of the auto complete list and they must always be in it.

**Comment by Bionus** [comment]
Which post-filters are you thinking about exactly?

The ones starting by `grabber:`? (`alreadyExists`, `inMd5List`, `downloaded`, `favorited`)
Or others as well?

**Comment by brazenvoid** [comment]
yes in the namespace grabber. There are more in that namespace than the 4 you listed.

**Comment by Bionus** [comment]
No, there should be only those 4 (generated in [downloadable.cpp](https://github.com/Bionus/imgbrd-grabber/blob/aeebdaf644b96cce1c85110459c5a9d86bf5f253/lib/src/loader/downloadable.cpp#L48)).
I'll push a change to have them in the auto-complete.
