### ISSUE TITLE
Translating Search Control Tags for Rule34 Paheal

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1956]
Essentially what I request is to make an abstraction layer between the flow of search terms and making the actual request for certain sources which do not follow Danbooru's tag scheme. 

I don't know about other sources but Rule34 is one such source with custom tags which I use extensively. But using it makes my life very hard;
- The control tags, though few are different in syntax.
- It doesn't have namespaced tags for artist/character/copyright etc.
- Only 3 tags are allowed in a search term, limiting possibilities with controlling it properly

So what I have to do is to first scour the tag(s) with Danbooru like sites then change filename scheme and search with rule34, then pick next search term, change filename scheme and start over. 

I have collated all the differences:

[Danbooru Rule34 Search Control Tag Differences.pdf](https://github.com/Bionus/imgbrd-grabber/files/4586977/Danbooru.Rule34.Search.Control.Tag.Differences.pdf)

**Comment by Bionus** [comment]
First, just to clarify, I guess you already know you can just directly use r34's search syntax directly in the search bar with no issues, right?

-----

Then, if I understand correctly, there's a few points here, specific to r34:
* **Tag:** they should be mapped to their r34 equivalent (ex: `user` => `poster`)
* **Equality:** the `:` should be replaced by `=` (ex: `source:...` => `source=...`)
* **Comparison:** the `:` should be removed (ex: `height:>=1000` => `height>=1000`)
* **Range:** not supported so should be split (ex: `filesize:10kb..1mb` => `filesize>10kb filesize<1mb`)
* **Size:** searching for height and width at the same time can be simplified (ex: `height:>=1000 width>=10000` => `size>1000x1000`)

Did I miss anything?

**Comment by brazenvoid** [comment]
Yes I know, what I wanted to do was to achieve merged search results and not exceed their tag limits. That can only be done if there is only one tag scheme to follow.

---

Sorry I should have added descriptions for those opinionated tag types but yes you got all of them correctly. 

Just for exposition, size obviously optimizes when both height and width have the same operators.

**Comment by Bionus** [comment]
Shimmie documentation reference:
https://shimmie.shishnet.org/ext_doc/index

**Comment by Bionus** [comment]
A few things to note from the documentation:

> Metatags can be followed by ":" rather than "=" if you prefer.
> I.E: "posted:2014-01-01", "id:>=500" etc. 

So points 2 and 3 can be ignored.

> user=Username & poster=Username, eg 

> hash=md5sum & md5=md5sum, eg 

So a few items from point 1 can be ignored.
