### ISSUE TITLE
from pixiv downloading only 600x600 pics

### ISSUE THREAD

**Issue by anonanons** [Bionus/imgbrd-grabber#1959]
pixiv downloading only 600x600 pics - pic 1, 2
but if i trying download manually all good - pic 3, 4
win 7, grabber 7.21
![Screenshot_332](https://user-images.githubusercontent.com/57991903/81420189-059d2600-9169-11ea-9cf6-f38681d90efa.png)
![Screenshot_334](https://user-images.githubusercontent.com/57991903/81420196-0afa7080-9169-11ea-9039-7082cc60420d.png)
![Screenshot_335](https://user-images.githubusercontent.com/57991903/81420582-9a078880-9169-11ea-904c-280fc74ecad4.png)
![Screenshot_336](https://user-images.githubusercontent.com/57991903/81420605-a2f85a00-9169-11ea-9692-c2dba14ea964.png)

**Comment by Bionus** [comment]
It would seem that the switch from the Public API to the App API broke this indeed. I just pushed a fix for the next version/nightly, thanks for the heads up! 👍

**Comment by anonanons** [comment]
thx
