### ISSUE TITLE
'Pixiv - No Result' error when adding source

### ISSUE THREAD

**Issue by Unknow0059** [Bionus/imgbrd-grabber#1965]
**Bug description**

I got an error when trying to add Pixiv as a source.
Error:
> Pixiv - No Result
> No valid source of the site returned result.

**Steps to reproduce**

1. Go to 'Sources'
2. Click on pixiv's 'Options'
3. Click on 'Login'
4. Add username and password
5. Click test
6. Get "Success!" result
7. Click 'Confirm'
8. Close 'Sources' window
9. See error.

**Expected behavior**
No error.

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4647801/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/4647805/settings.txt)

**System information**
- OS: Windows 10 Pro 1909 10.0.18363.836 64-bit
- Grabber version: 7.2.1 x64

**Additional context**
If there's some proper sort of way of adding sources then I recommend that a wiki be made.
For context, I have previously added chan.sankakucomplex as a source by ticking the checkbox and it worked without issues, so I expected this, too, to have no issues.

**Comment by AkatsukiiDesu** [comment]
Did you search for anything once you added the source? I can see there is a commit done on April 26 to show newest illustrations if a search tag isn't entered (this is currently only on the nightly branch)

**Comment by Unknow0059** [comment]
> Did you search for anything once you added the source?
Nope. Hadn't.

It works if you search, but not otherwise, which is how the other sources work.

**Comment by Bionus** [comment]
This indeed seem to be a duplicate of #1940

When no tags are searched, there was no search performed before. It should be fixed in the nightly and will also be fixed in the next release. 🎉
