### ISSUE TITLE
Favorites: Rename "Note" field

### ISSUE THREAD

**Issue by FichteFoll** [Bionus/imgbrd-grabber#1969]
>> By the way, what does the "Note" field do or represent? It's not intuitive and not documented.
>
> It's a value from 0 to 100 that you can use for sorting. Can be useful to sort your favorites in whatever way you want.
– https://github.com/Bionus/imgbrd-grabber/issues/1058#issuecomment-632316815

It should be named "sort order" or "priority" or similar instead of an entirely unclear "Note".

**Comment by Bionus** [comment]
I can see that "Note" is not a very clear name, but I don't really see a very good alternative either.

"Sort order" would be incorrect, given the default sort order is name. And "priority" might be confusing as to what is being prioritized.

"Position" could be a good option but I'm not sure about that one either.

**Comment by FichteFoll** [comment]
> given the default sort order is name

I'm not sure I understand that. Do you mean that the sort order is the tuple of `(note, name)`? And because favorites will most likely have the default value of 50 for the note field they get ordered by name?

I still think "sort order" is fitting, or maybe "sort priority". "position" makes sense when sorting ascendingly and `1` is the first.

**Comment by Bionus** [comment]
> I'm not sure I understand that. Do you mean that the sort order is the tuple of (note, name)? And because favorites will most likely have the default value of 50 for the note field they get ordered by name?

No, I mean that the sorting of favorites is just by "Name" by default:
![image](https://user-images.githubusercontent.com/882719/82753833-27351900-9dc9-11ea-986a-1991ab4defd0.png)

So if you call the field "sort order" that would mean that:
* If the user doesn't select it in the "Sort by" select, the user can change the "sort order" of a given favorite without any actual effect
* You'd have "Sort by sort order" which doesn't really make sense

**Comment by FichteFoll** [comment]
> No, I mean that the sorting of favorites is just by "Name" by default:

Oh, I totally missed that UI. Can't believe I never saw this yet, but I also only have 2 entries there currently. I understand what you mean now.

I think "priority" as a name makes sense for the purposes of describing it as a field that can be sorted on. As long as the user doesn't expect additional functionality for it.
