### ISSUE TITLE
Remember source settings for favorites

### ISSUE THREAD

**Issue by FichteFoll** [Bionus/imgbrd-grabber#1977]
**Is your feature request related to a problem? Please describe**

I can't reliably reproduce the issue, but I'll describe what I experience.

It seems that source settings are saved per tab, which makes sense. However, in some occasions, this configuration leaks into the favorites, which absolutely doesn't work for some sources and thus makes the favorite searches return no results until I change the sources back to what they should be (for the favorite).

Related to #1976, because that issue seems to intensify the problem.

**Describe the solution you'd like**

Configure and save source settings per favorite, like you can do for monitoring already. In fact, I believe these two should be the same.

**Comment by Bionus** [comment]
Seems like the implementation included in 7.3.0 had an issue with saving, the selected sources are not being saved properly in the `favorites.json` file, hence only working until the program is closed.
