### ISSUE TITLE
saved searches containing quotation marks don't reopen correctly

### ISSUE THREAD

**Issue by efactor13** [Bionus/imgbrd-grabber#1980]
**Bug description**

searches containing quotation marks omit the quotation marks and everything after them when reopened from favorites or from kept for later

**Steps to reproduce**

1. perform a search containing quotations marks (as would be relatively common when searching ehentai)
2. add the search to favorites or to kept for later
3. reopen the search by selecting it from favorites or from kept for later
4. everything after and including the first quotation mark will have been omitted from the performed search

**Comment by Bionus** [comment]
I can't reproduce the issue on 7.2.1.

1. Search `"test"` on E-H
2. Right click the search field and add to both favorites and keep for later
3. (optional) Restart Grabber
4. Open the favorite => it will show `Favorites - "test"` and do the correct search
5. Middle click the keep for later => it will create a tab with the `"test"` search

Are there additional steps I missed?

**Comment by efactor13** [comment]
issue appears to be resolved as of latest update.
