### ISSUE TITLE
Add keyboard shortcuts to go to next/previous/first/last page

### ISSUE THREAD

**Issue by FichteFoll** [Bionus/imgbrd-grabber#1983]
**Is your feature request related to a problem? Please describe**

Assuming https://bionus.github.io/imgbrd-grabber/docs/shortcuts.html is complete, there are currently no bindings to navigate search result pages with the keyboard. 

**Describe the solution you'd like**

Page Up/Down and Ctrl+Home/End seem like obvious choices.

**Describe alternatives you've considered**

Binding "Escape" in the favorites results view to the "Back" button below would also seem natural (to me).

**Comment by Bionus** [comment]
> Assuming https://bionus.github.io/imgbrd-grabber/docs/shortcuts.html is complete, there are currently no bindings to navigate search result pages with the keyboard.

Well I made it a few days ago, so hopefully it is 😱
The only missing information is about [mnemonics](https://en.wikipedia.org/wiki/Mnemonics_(keyboard)), which I just added (note that it won't appear online until next release).

So indeed there are currently no shortcuts for page navigation.

> Page Up/Down and Ctrl+Home/End seem like obvious choices.

Do you mean <kbd>Ctrl+Page Up</kbd> & co? I see you mention <kbd>Ctrl</kbd> in only one of those shortcuts. And given the results view has scrolling, binding directly the Page Up & Down will result in weird behavior if no other key is added.

**Comment by FichteFoll** [comment]
> And given the results view has scrolling, binding directly the Page Up & Down will result in weird behavior if no other key is added.

I didn't think of this. If page up/down aren't free, then things become a bit more complicated because ctrl+pageup/down are already used for tab navigation (and rightfully so). I also didn't think about endless scrolling, in which case page navigation should probably be disabled?

> I see you mention <kbd>Ctrl</kbd> in only one of those shortcuts.

I suggested Ctrl for Home/End because those actions are descructive in that you lose the page number you were previously at and shouldn't be available so easily, whereas going a single page in either direction is reversible by going in the opposite direction.

---

While we're at it, what about an "active" state in image results view that can be navigated using the arrow keys, selects it for download with Space and opens the image view with Enter? Separate issue?

**Comment by Bionus** [comment]
> I didn't think of this. If page up/down aren't free, then things become a bit more complicated because ctrl+pageup/down are already used for tab navigation (and rightfully so). I also didn't think about endless scrolling, in which case page navigation should probably be disabled?

Haven't thought about tab navigation but indeed.
More naturally, <kbd>Ctrl+Arrow</kbd> should be free AFAIK? Or even just the arrow keys themselves 😅 

> While we're at it, what about an "active" state in image results view that can be navigated using the arrow keys, selects it for download with Space and opens the image view with Enter? Separate issue?

Indeed a good idea, but also a new issue yeah, especially given the work it might require for up/down arrows with the way the thing is currently done.

But an interesting idea that I'd be interested in implementing if there's demand.

**Comment by FichteFoll** [comment]
> More naturally, Ctrl+Arrow should be free AFAIK? Or even just the arrow keys themselves sweat_smile

SGTM.
