### ISSUE TITLE
Rule34.xxx no result

### ISSUE THREAD

**Issue by bloodvladLoL** [Bionus/imgbrd-grabber#1985]
**Bug description**

When I try to find something, it produces 
Rule34.xxx - No result
No valid source of the site returned result. 
When i try to login
Login test = Failure

**Steps to reproduce**

1. Go to 'Sources'
2. Click on 'Check Rule34.xxx then click Ok'
3. Click 'Ok' on top right

**Expected behavior**
Show images

**Context**

* Provide your `main.log` file to see if any obvious error occured.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4705769/main.log)

* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/4705776/settings.txt)

**System information**

- OS: Windows 10 x64
- Grabber version: 7.2.1 7.0.0. 6.0.2 

**Additional context**
I checked different versions of the program, for example 6.0.0 4.0.0 7.0.0 7.2.1 etc. x64, x32.
Exact problem.
I reinstalled all visual c++ redistributable from 2005 to 2019
And of course i deleted the folder in appdata and Program Files before reinstalling.
Sometimes such problems went away over time, so a couple of months ago I created an issue to find out if someone else had the same problem and the person wrote that everything worked for him, but mine was not resolved.

**Comment by Bionus** [comment]
Had you tried visiting the website itself at that time?
I just tested and I see nothing really strange in your settings or logs, and it's working fine here.

Your log says:
> server replied: Service Temporarily Unavailable (403)

So to me it seems that the website was just down for a while?

**Comment by bloodvladLoL** [comment]
I immediately checked if these are problems with the website, it worked as usual. I have this problem for about three months now.I will try to run the program on my laptop as soon as I get it back (1-2 days) and write the result.

**Comment by rngguy** [comment]
I have the same problem since this site start to use cloudflare protection. I found mentions of similar problems with other sites and suggestions to transfer cookies from the browser, but my attempts were unsuccessful.

**Comment by bloodvladLoL** [comment]
After the last update everything worked for me.
