### ISSUE TITLE
Reload 'total' value from batchs on .igl file

### ISSUE THREAD

**Issue by jehutyDev** [Bionus/imgbrd-grabber#1987]
I like a particular group of tags and always end up searching for every tag manually to update the total images from that tag on my local folders, so I was wondering if its possible to add an automatic reloading total value for every tag in a .igl file that would save a lot of time.

**Comment by Bionus** [comment]
I'm not sure I understand what you're trying to do, and what "total" value you're talking about?

If you want to check for new images, can't you just restart the batch downloads, since duplicates will be ignored?

**Comment by anubis-Dev** [comment]
Well the idea is to reuse .igl files which for example I used a month ago and now that file is outdated; specifically the total value I mentioned increased in that period time. I don't know exactly how it works buy I think the process is using that "total" value to decide how many images one tag has.

"batchs": [
        {
            "filename": "%md5%.%ext%",
            "galleriesCountAsOne": true,
            "getBlacklisted": false,
            "page": 1,
            "path": "/girls_frontline/ithaca_m37",
            "perpage": 160,
            "postFiltering": [
            ],
            "progressFinished": false,
            "progressVal": 0,
            "query": {
                "tags": [
                    "ithaca_m37_(girls_frontline)"
                ]
            },
            "site": "gelbooru.com",
            **"total": 100**
        }

In this json object from the igl file the total value was 100 some time ago and now is 160,
however my old igl file don't know that and the only way to update it is to create a new file after searching the wanted tags and saving a new file, this may be an laborious work.

And of course the duplicates should be ignored and only download the new images.

This could be a way to improve the igl files interaction with the app.

I hope I have been clear enough, and as always thanks for your work.
