### ISSUE TITLE
GIFs are being downloaded as ZIP files with every frame separate instead

### ISSUE THREAD

**Issue by markedone66** [Bionus/imgbrd-grabber#1989]
**Bug description**
Sometimes, When trying to download GIFs, they are being downloaded as ZIP files, with every frame of the gif separated instead. Not sure if a bug or feature but i wanna download GIFs as they are

**Steps to reproduce**

1. Enter any tag that finds a gif
2. Click on Search (OK)
3. Select an image
4. download it
5. open the file location
6. See the ZIP folder instead of GIF picture

**Expected behavior**
A gif image

**Context**
My filename script: %copyright%/%search%/artist_%artist%_%md5%.%ext%
no log, the download has no errors whatsoever, shows as normal

**Screenshots**
Closed and deleted the files, if really needed i can try to recreate it exactly and add later.

**System information**

- OS: WIN 10 Pro
- Grabber version: 7.2.1

**Additional context**
-

**Comment by Bionus** [comment]
Are you sure those are GIFs? Sounds like `ugoira` animated images.

Pixiv and Danbooru both have an integrated browser, and Grabber might fetch a GIF "preview", but the actual image is actually a ZIP with one image per frame. Do you have a link to such image that is actually a GIF but downloads as a ZIP in Grabber?
