### ISSUE TITLE
Anyone can help me add sankaku in there manually?

### ISSUE THREAD

**Issue by markedone66** [Bionus/imgbrd-grabber#1990]
I have check out other issues regarding this, more precisely: #1888 and somewhere between the lines i read that the programs is ABLE to download from there, it was just removed from the list by default, for some reason I have nothing to say about. As the author of the program decided to remove it, it shall stay removed and im not gonna beg for readding. It would be rude and i understand him. 

But if theres anyone who managed to make it work manually on his local installation, could you please help this dummy here? :) 
Thanks a lot!

**Comment by yami-no-tusbas** [comment]
1a) Find a version wich can, or go build it from some old source.
1b) go to : https://github.com/Bionus/imgbrd-grabber/issues/1888#issuecomment-607106830 grab my zip, unzip it in "C:\Users\\"your user name"\AppData\Local\Bionus\Grabber\"
2) go into "Grabber\sites" and make Sankaku read only.

**Comment by markedone66** [comment]
> 0 Close grabber !
> 1a Find a version wich can, or go build it from some old source.
> 1b go to : [#1888 (comment)](https://github.com/Bionus/imgbrd-grabber/issues/1888#issuecomment-607106830) grab my zip, unzip it in "C:\Users\"your user name"\AppData\Local\Bionus\Grabber"
> 2 go into "Grabber\sites" and make Sankaku read only.

Thanks Yami !
