### ISSUE TITLE
The new "monitors" tabs bugs and quirks

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1991]
**Bug description**

1st the bugs : 
- ~~When you delete a row, it actually delete another row, like the one upside most of the time.~~ https://github.com/Bionus/imgbrd-grabber/commit/82c3708e9438008b7fa16c0423e71228ab1da3aa
- ~~Same after editing a row, it select the one upper just after editing.~~ https://github.com/Bionus/imgbrd-grabber/commit/82c3708e9438008b7fa16c0423e71228ab1da3aa
- ~~When removing a source : the focus goes on "add" after un-checking a source. (would be better on "ok" I think)~~
- ~~The most left button is "ok", but in the previous windows it is on the right.~~ https://github.com/Bionus/imgbrd-grabber/commit/d3423e3f20d80b8175219f646aad858996930648
- ~~When interval is set to 60m the display fail (show: "0 m")~~ https://github.com/Bionus/imgbrd-grabber/commit/06f8bd14fc59f8270216d8b5798cc5994318506a
- ~~**(update 09/07/20)** When an image hit a tag from blacklist, the monitoring fail to continue and freeze displaying no error message.~~
- ~~**(update 09/07/20** The monitors.json use wrong timestamp, log are on system time, but monitors are two hours earlyier.~~ (Feature, not a bug then 😃 )
- ~~(update 09/07/20** The monitors.json seems to not be updated with correct timestamp in the lasts entries after monitoring is complete.
logs : [main.log](https://github.com/Bionus/imgbrd-grabber/files/4899235/main.log)
for timing comparizon here is monitors.json : [monitors 09.07.20.json.txt](https://github.com/Bionus/imgbrd-grabber/files/4899236/monitors.09.07.20.json.txt)~~

2nd the suggestions :
- A tool to convert "favorites" to "monitors" ?
> Yes it's planned, but since currently the monitors still have a bunch of issues, I just leave the favorites as-is for now.
In the long run, the monitoring feature of the favorites will go away or be more integrated with real monitors.

Take your time, this is not a priority, just a convenience.

- ~~Some more informations columns like : "last checked", "next check", "filename" & "save folder","post-filter". Could be usefull information~~ Seems ok with the ones you added.
- ~~Quick edit like the download tab ? You know, when you can double click to quick edit a field.~~

> Maybe, but I feel like many fields would not go well with it. Only the actual search, the post-filters, and maybe the source (but then you'd have to put the exact source URL, just like in downloads). I feel like just editing it with an UI is more convenient?

You're right, when I was thinking about that I was not accustomed to the new monitors, now it feel ok like it is ! Thx.

- ~~A way to "pause/resume" the monitors ? I mean, all of them at once, for exemple if you only want to download them at night.~~
- ~~The "ok" button always at the same place, the focus on "ok", since you can "cancel" with escape key.~~ https://github.com/Bionus/imgbrd-grabber/commit/d3423e3f20d80b8175219f646aad858996930648

3rd the questions :
- How are notification working ? I got absolutely no notification, the system tray icon only react to right click with the "qui" option. For now I assume they are not implemented since you stated : 
> Add basic monitor tab (issue #1620)

> I'd say it's a bug, since notifications exist for a long time and should be working. They were introduced together with favorites' monitoring.
I just tried and got notifications with no issues. If you're on Windows 10, make sure you don't have the "assistant" blocking notifications.
You might need to enable the system tray icon as they're required by Windows to send notifications.

Still nothing, but could be on my end, will test later in a vm

**System information**

- windows 10
- Grabber version: 7.3.

Thx for the work, the new monitor is good thoses quirk appart !

**Comment by yami-no-tusbas** [comment]
Added some update on the bug side.

**Comment by Bionus** [comment]
> - When you delete a row, it actually delete another row, like the one upside most of the time.
> - Same after editing a row, it select the one upper just after editing.
> - When removing a source : the focus goes on "add" after un-checking a source. (would be better on "ok" I think)
> - When interval is set to 60m the display fail (show: "0 m")
> - **(update 09/07/20)** When an image hit a tag from blacklist, the monitoring fail to continue and freeze displaying no error message.

Fixed 👌 

> - **(update 09/07/20** The monitors.json seems to not be updated with correct timestamp in the lasts entries after monitoring is complete.
> logs : [main.log](https://github.com/Bionus/imgbrd-grabber/files/4899235/main.log)
> for timing comparizon here is monitors.json : [monitors 09.07.20.json.txt](https://github.com/Bionus/imgbrd-grabber/files/4899236/monitors.09.07.20.json.txt)
> - **(update 09/07/20** The monitors.json use wrong timestamp, log are on system time, but monitors are two hours earlyier.

Not sure what exactly you mean.
Dates in the JSON file are stored in UTC. If you see them as two hours earlier, if you're from western Europe that's expected.

> - The most left button is "ok", but in the previous windows it is on the right.
> - The "ok" button always at the same place, the focus on "ok", since you can "cancel" with escape key.

Yes I updated the "Sources" window to have the "Ok" button on the left.

> - A tool to convert "favorites" to "monitors" ?

Yes it's planned, but since currently the monitors still have a bunch of issues, I just leave the favorites as-is for now.
In the long run, the monitoring feature of the favorites will go away or be more integrated with real monitors.

> - Some more informations columns like : "last checked", "next check", "filename" & "save folder","post-filter". Could be usefull information

I added a few, not sure about the others yet.
Note that most will be hidden by default, but you can toggle them by right-clicking on the table's header.

> - Quick edit like the download tab ? You know, when you can double click to quick edit a field.

Maybe, but I feel like many fields would not go well with it. Only the actual search, the post-filters, and maybe the source (but then you'd have to put the exact source URL, just like in downloads). I feel like just editing it with an UI is more convenient?

> - How are notification working ? I got absolutely no notification, the system tray icon only react to right click with the "qui" option. For now I assume they are not implemented since you stated : 
> > Add basic monitor tab (issue #1620)

I'd say it's a bug, since notifications exist for a long time and should be working. They were introduced together with favorites' monitoring.

**Comment by yami-no-tusbas** [comment]
I've updated the first message.

For :

>- (update 09/07/20** The monitors.json seems to not be updated with correct timestamp in the lasts entries after monitoring is complete.
logs : [main.log](https://github.com/Bionus/imgbrd-grabber/files/4899235/main.log)
for timing comparizon here is monitors.json : [monitors 09.07.20.json.txt](https://github.com/Bionus/imgbrd-grabber/files/4899236/monitors.09.07.20.json.txt)

I mean that the last entries it the json file have wrong last-check values. Even with the "UTC thing" they are wrong, the beggining ones are updated fine here is the value : "lastCheck": "2020-07-09T19:50:50Z", this is correct, but the ones at the end of the file (not the same number of entries at each times) get it wrong : "lastCheck": "2020-07-09T15:24:08Z", they are not updated, I don't know why.

For exemple in the last monitoring : 

The firsts entries says : "lastCheck": "2020-07-12T07:46:25Z", "lastCheck": "2020-07-12T07:46:26Z", "lastCheck": "2020-07-12T07:46:30Z", and so on... (this is correct with UTC thing)

(after monitoring is completed and application closed)
>[09:55:34.645][Info] Next monitoring will be in 2997 seconds

So I expect last entries to be something like "lastCheck": "2020-07-12T07:**5X**:**XX**Z",

> The very last entry : "lastCheck": "2020-07-11T18:08:20Z",
> The last good one : "lastCheck": "2020-07-12T07:55:27Z",

In my last monitors.json the last 40 entries have not been updated on "lastCheck", the value is the same as yesterday, but they got monitored, just not updated. (The number of entries not updated seems a bit random too)
[monitors - Copie.json.txt](https://github.com/Bionus/imgbrd-grabber/files/4908195/monitors.-.Copie.json.txt)

**Comment by Bionus** [comment]
> How are notification working ? I got absolutely no notification, the system tray icon only react to right click with the "qui" option. For now I assume they are not implemented since you stated :

I made it so that the checkbox is disabled if the system tray icon is disabled.

> A way to "pause/resume" the monitors ? I mean, all of them at once, for exemple if you only want to download them at night.

There's a big button at the bottom of the monitors tab now.

> (update 09/07/20** The monitors.json seems to not be updated with correct timestamp in the lasts entries after monitoring is complete.

Should be fixed now 👌

**Comment by Bionus** [comment]
> How are notification working ? I got absolutely no notification, the system tray icon only react to right click with the "qui" option. For now I assume they are not implemented since you stated :

I made it so that the checkbox is disabled if the system tray icon is disabled.

> A way to "pause/resume" the monitors ? I mean, all of them at once, for exemple if you only want to download them at night.

There's a big button at the bottom of the monitors tab now.

> (update 09/07/20** The monitors.json seems to not be updated with correct timestamp in the lasts entries after monitoring is complete.

Should be fixed now 👌

**Comment by yami-no-tusbas** [comment]
Yep everything fixed, still no notifications on my end; Could be win10 doing is shit.
Anyway i'll close since everything here is done or solved.
