### ISSUE TITLE
Monitors freeze because of blacklist.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1992]
**Bug description**

TIme to time, the monitoring seem to freeze after adding images to download.

**Steps to reproduce**

Just let it run, times to times it tries to add image to the download queue then, nothing happen anymore. Rebooting the program don't seems to fix it, the only fix I found was to alter last check timestamps in the faulty monitor to have it skipped.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/4728489/main.log)
[settings.ini.log](https://github.com/Bionus/imgbrd-grabber/files/4728492/settings.ini.log)
[monitors.json.log](https://github.com/Bionus/imgbrd-grabber/files/4755191/monitors.json.log)

**System information**

- OS: Windows 10
- Grabber version: 7.3.0

**Comment by yami-no-tusbas** [comment]
There is another log, launched the app today, the monitoring freezed after like on or two minutes
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4729859/main.log)
This is the same settings and monitors from this night. But it froze at another element, it seems to be random, maybe an image not downloading correctly and freezin the app ?

Can the log be more "verbose" ? Like what have been going on whith : 
`[12:07:24.238][Info] Added 1 images to the download queue for monitor 'high_school_dxd' on 'behoimi.org, e621, Gelbooru'`

It always seems to freeze after one of thoses lines.

**Comment by yami-no-tusbas** [comment]
Ok I think I got it, the black list... I just looked the new image from one he failed, they where artist I didn't like. So I thinked "what if it is the black list preventing the download, but the program waiting to download". I removed the black list, re-launch, and seems fine.

I'll monitor if removing the blacklist work for a few day, but the program was stopping multiple times on the same monitor, once I removed the black list, It worked.

**Comment by yami-no-tusbas** [comment]
I confirm, removing the blacklist "solve" the problem, there is definitively an issue then !

**Comment by Bionus** [comment]
Oops, seems like although I saw the issue #1991, I didn't see this one.
I think this is one of the points mentioned there and that were fixed in 7.3.1? Or am I misunderstanding something?

**Comment by yami-no-tusbas** [comment]
Yep my bad, seems fixed by one of the change for #1991
