### ISSUE TITLE
Add page range to download

### ISSUE THREAD

**Issue by ciberweaboo** [Bionus/imgbrd-grabber#1996]
In Pixiv isn't allowed to download more than 30 images per group, i think may be great to put in Page Section: 1-10 and then download 1,2,3,4,5,6,7,8,9,10 pages

**Comment by Bionus** [comment]
Hello, I guess there was a misunderstanding in the original question.
You can absolutely already do that. If you set 30 images/page, and a 300 images limit, then Grabber will already download the 10 pages for you 😄
