### ISSUE TITLE
chan.sankakucomplex.com

### ISSUE THREAD

**Issue by mosesthesmuglord** [Bionus/imgbrd-grabber#1998]
i've added sankakucomplex as a source and then tried dragging and dropping the images in and it doesn't recognize the source or something.  the md5 source codes are in the file names.  and i tested this with the site manually by inputting md5:source code into the sites search engine and it finds it alright.  but grabber still won't recognize it  site server was not offline and they are valid sources.

![Screenshot (31)](https://user-images.githubusercontent.com/66474839/83876637-2f655080-a707-11ea-8565-5eeb6e51b746.png)

**Comment by ponchojohn1234** [comment]
have you got a solution? i don't think were ever getting one here

**Comment by Tumultuous-RGR-SiM** [comment]
I'm not doing what you're doing specifically, but since this is about Sankaku compatibility, I'll share what I know:

From what I understand, there was some sort of problem where the Sankaku site owner bitched at the Grabber dev to stop letting his program access Sankaku. 

Now, Sankaku scrapes most of it's content from other sites, so he has no real leg to stand on in this argument, but he was being such a thorn in the Grabber Dev's side that the Grabber Dev gave in and removed compatibility with Sankaku in the next version.

I forget exactly what I did, but here's the basics: There's some sort of special file that tells Grabber how to access different websites. The file that gave grabber compatibility with Sankaku exists in earlier versions of the program, but was removed from later versions. Installing an earlier version and updating will also cause Grabber to delete this compatibility file, and just using the in-program configuration tool isn't enough to make it work with Sankaku.

What I did was I installed an earlier version of Grabber (version 7.1.1, I think), found the special file(s) that let it be compatible with Sankaku, manually marked those files as Read-Only to stop it from being deleted, and then updated the program. There should be some more specific on this if you keep looking around in the issues (solved and unsolved) with "sankaku" in the search term.

**Comment by SalomonOuroboros** [comment]
> No estoy haciendo lo que estás haciendo específicamente, pero como se trata de la compatibilidad de Sankaku, compartiré lo que sé:
> 
> Por lo que entiendo, hubo algún tipo de problema en el que el propietario del sitio Sankaku se quejó al desarrollador de Grabber para dejar de permitir que su programa acceda a Sankaku.
> 
> Ahora, Sankaku raspa la mayor parte de su contenido de otros sitios, por lo que no tiene una pierna real para sostenerse en este argumento, pero estaba siendo tan agudo en el lado del Grabber Dev que el Grabber Dev cedió y eliminó la compatibilidad con Sankaku en el próxima versión
> 
> Olvidé exactamente lo que hice, pero aquí están los conceptos básicos: hay algún tipo de archivo especial que le dice a Grabber cómo acceder a diferentes sitios web. El archivo que dio compatibilidad grabber con Sankaku existe en versiones anteriores del programa, pero fue eliminado de versiones posteriores. La instalación de una versión anterior y la actualización también harán que Grabber elimine este archivo de compatibilidad, y solo usar la herramienta de configuración en el programa no es suficiente para que funcione con Sankaku.
> 
> Lo que hice fue instalar una versión anterior de Grabber (creo que la versión 7.1.1), encontré los archivos especiales que permiten que sea compatible con Sankaku, marqué manualmente esos archivos como de solo lectura para evitar que se eliminen y luego actualizó el programa. Debería haber algo más específico sobre esto si sigue buscando en los problemas (resueltos y no resueltos) con "sankaku" en el término de búsqueda.



> I'm not doing what you're doing specifically, but since this is about Sankaku compatibility, I'll share what I know:
> 
> From what I understand, there was some sort of problem where the Sankaku site owner bitched at the Grabber dev to stop letting his program access Sankaku.
> 
> Now, Sankaku scrapes most of it's content from other sites, so he has no real leg to stand on in this argument, but he was being such a thorn in the Grabber Dev's side that the Grabber Dev gave in and removed compatibility with Sankaku in the next version.
> 
> I forget exactly what I did, but here's the basics: There's some sort of special file that tells Grabber how to access different websites. The file that gave grabber compatibility with Sankaku exists in earlier versions of the program, but was removed from later versions. Installing an earlier version and updating will also cause Grabber to delete this compatibility file, and just using the in-program configuration tool isn't enough to make it work with Sankaku.
> 
> What I did was I installed an earlier version of Grabber (version 7.1.1, I think), found the special file(s) that let it be compatible with Sankaku, manually marked those files as Read-Only to stop it from being deleted, and then updated the program. There should be some more specific on this if you keep looking around in the issues (solved and unsolved) with "sankaku" in the search term.

Hello, I am doing the same procedure as you, only when I put a label, for example, Nekomimi returns 206,253 results, but when I arrive after 1000 pages, all the remaining files mark them as existing, I already verified the files marked as existing in the downloaded folder and there they are, the remaining pages show them as analyzed and all the URLs were analyzed, the question is ?, are there really only 21,706 files of the 206,253 displayed? Or is there a problem?

**Comment by SalomonOuroboros** [comment]
> I'm not doing what you're doing specifically, but since this is about Sankaku compatibility, I'll share what I know:
> 
> From what I understand, there was some sort of problem where the Sankaku site owner bitched at the Grabber dev to stop letting his program access Sankaku.
> 
> Now, Sankaku scrapes most of it's content from other sites, so he has no real leg to stand on in this argument, but he was being such a thorn in the Grabber Dev's side that the Grabber Dev gave in and removed compatibility with Sankaku in the next version.
> 
> I forget exactly what I did, but here's the basics: There's some sort of special file that tells Grabber how to access different websites. The file that gave grabber compatibility with Sankaku exists in earlier versions of the program, but was removed from later versions. Installing an earlier version and updating will also cause Grabber to delete this compatibility file, and just using the in-program configuration tool isn't enough to make it work with Sankaku.
> 
> What I did was I installed an earlier version of Grabber (version 7.1.1, I think), found the special file(s) that let it be compatible with Sankaku, manually marked those files as Read-Only to stop it from being deleted, and then updated the program. There should be some more specific on this if you keep looking around in the issues (solved and unsolved) with "sankaku" in the search term.

Hello, I am doing the same procedure as you, only when I put a label, for example, Nekomimi returns 206,253 results, but when I arrive after 1086 pages, all the remaining files mark them as existing, I already checked the files marked as existing in the downloaded folder and there they are, the remaining pages show them as analyzed and all URLs were analyzed, the question is? Are there really only 21,706 files out of the 206,253? Or is there a problem?

**Comment by werdck** [comment]
First, this is not really sankaku-compliant, so your speeds are abyssmal I guess?
Are your files all named %md5sum%.%ext%? If not, that could be a problem (non-unique names)
