### ISSUE TITLE
Reloads files from the md5 list

### ISSUE THREAD

**Issue by dkpeld** [Bionus/imgbrd-grabber#2007]
**Bug description**

Hi! Suppose I deleted a certain number of files I do not need, I have an option "Keep deleted files on the md5 list" after a while I upload files by this tag and it downloads everything that I deleted

**Steps to reproduce**

Downloads>add>any tags>download>deleted any files>repeat download>deleted file uploaded

**Expected behavior**

I delete the file, it is in md5 list, the program no longer downloads it

**System information**

- OS: win 7
- Grabber version: 7.3.0

**Additional context**

On version 7.2.1 this bug is missing, he writes that "N files ignored"

**Comment by sbobbo** [comment]
What's "If a file already exists globally" set to?

**Comment by dkpeld** [comment]
UP! On the new version, everything is the same, I do not need deleted files, but he downloads them. How can I update the collection if it downloads everything that I don't need
