### ISSUE TITLE
Defining a folder to scan and create a MD5 list before starting a download

### ISSUE THREAD

**Issue by SMNarutoXD** [Bionus/imgbrd-grabber#2010]
I'm using the grabber to collect a few images form selected characters from different franchises.

filename currently is charactername/rating/charactername+md5+ext

The problem I like to sort my images in a specific way.
This means I'm adding a number of subdirectories and sort the images based on them.

Which basically means I get duplicates.
And I did run a fair number of tests. 

I did set it to "Don't save" for globally and same directory. 
I also did rescan all MD5s a multiple times.

**Describe the solution you'd like**

To the fact that I'm using the tool for 5 days now and I may not have clearly understood its features, so I'm suggesting a feature not reporting a bug.

When I start a download - may it be a "Get All" or "Monitor" I want to define a folder to scan and recalculate the MD5 of all files in all subdirectories and uses this for the download.

Let's downloaded all images of Bluma. Then by my filename above, I will have a subdirectory with the name "Bulma" in my Download folder.
And that directory with the name "Bluma" is the one I define to be scanned before the download.

If it goes through all subdirectories of Bulma and checks the MD5 list which will be created with the to be downloaded images - it should greatly reduce the duplicates and I still can sort.

**Describe alternatives you've considered**

I tried anything I could think of based on the documentation.
I also considered opening an issue type bug as I have the feeling that it just checks the file path and not a saved list of md5. 

Because As I change my filename to not include the rating and hit on all download again - it actually ignores the existing files. If I create a folder named "test" and do the same after moving one image into that folder - it will download only the image I put in the "test" folder.

**Comment by yami-no-tusbas** [comment]
If you move the file outside of grabber (not using the rename existing image tool), you should check the option "_keep deleted files in the MD5 list_" on the "Save" option into the option menu, it'll force grabber to remember that you have already downloaded the image, even if you have moved or deleted it.
![screen](https://user-images.githubusercontent.com/3921598/84561493-3581af80-ad4d-11ea-97f9-ca89b262f696.png)

**Comment by SMNarutoXD** [comment]
That more or less only solves it partly or can be counted as a workaround.

I still think an optional specific scan before would reduce the duplicates greatly when downloading a bulk or when using the monitor.

**Comment by dill-shower** [comment]
This is actual problem
