### ISSUE TITLE
Pixiv not working as expected

### ISSUE THREAD

**Issue by SMNarutoXD** [Bionus/imgbrd-grabber#2011]
**Bug description**

If I run a search multiple pages and hit "Get all" it downloads all pages.
If I do the same with pixiv using a Japanese tag - it sets a limit of 30 images.

**NSFW** https://user-images.githubusercontent.com/66256973/84568495-236d3480-ad80-11ea-9b5a-c355e9be93b8.png

I can increase the limit by checking the tag on pixiv directly - for example 春野サクラ with around 26000 results but it does still not download them all.
I would understand if they were displayed as duplicates or ignored but no - it just behaves strangely.

Currently "Get All" for Pixiv seems to be the same as "Get this Page".
**Steps to reproduce**

1. Open a Search Tab
2. Enable Pixiv with Login
3. Search 春野サクラ
4. Klick on "Get All"
5. Change to the Download Tab
6. Check the list of the Groups it will show an Image per Page and Image Limit of 30
7. Click on Download
8. The result is nowhere close to "Get all" with the other sources

1. Open a Search Tab
2. Enable Pixiv with Login
3. Search 春野サクラ
4. Klick on "Get All"
5. Change to the Download Tab
6. Check the list of the Groups it will show an Image per Page and Image Limit of 30
7. Change the Image limit to something like 30000
8. Click on Download
9.. The result is nowhere close to "Get all" with the other sources

**Expected behavior**

The expected behavior would be for the provided example of 春野サクラ that the grabber would download more than around 0,07 % of the images.

![pixiv1](https://user-images.githubusercontent.com/66256973/84568506-354ed780-ad80-11ea-99ba-24c2819ee43e.png)
![pixiv2](https://user-images.githubusercontent.com/66256973/84568496-27995200-ad80-11ea-8939-e99575d737e5.png)
![pixiv3](https://user-images.githubusercontent.com/66256973/84568520-40a20300-ad80-11ea-8139-aa074cc17a6a.png)

**Comment by SMNarutoXD** [comment]
On a side note: The Monitor does actually download everything.

**Comment by Bionus** [comment]
This should have been solved by the new "all" option for batch downloads introduced by 8760b2288f5a722f5da6875d1e22d8e265fff1cc first in 7.5.0.
