### ISSUE TITLE
Is it possible to set searches to download automatically on every launch ?

### ISSUE THREAD

**Issue by MemeTroubadour** [Bionus/imgbrd-grabber#2018]
Hello, thank you for your work on Grabber.

I use Grabber to regularly download my favorited images from danbooru. I want to know if I can automatize it so that Grabber starts downloading all images from my favorites as soon as I start it.

Is this possible natively ?

**Comment by yami-no-tusbas** [comment]
I think this is the job of the "favorite" as I use them fort his purpose, but hey will be replaced by Monitors in the future :
https://bionus.github.io/imgbrd-grabber/docs/favorites.html

**Comment by Bionus** [comment]
It used to be a feature part of the favorites, but it was indeed replaced by the monitors.

The easiest way to do what you want is to simply do the search in question, then click the "Monitor" button at the bottom of the window. The search will be added to the "Monitors" tab, and will be triggered every X minutes / hours (you can change it in the monitor's settings).

By default, monitored tags are set to both download and trigger a notification.
