### ISSUE TITLE
Skip downloads because file already exists when it doesn't

### ISSUE THREAD

**Issue by NoticeMeHentai** [Bionus/imgbrd-grabber#2019]
**Bug in question**

Whenever I try to download a bunch of files, notably with get page or get all, and then I start downloading, roughly 2/3 or more of the files are skipped "because they already exist" even though it's the first time I get them (I don't even use Grabber that much as to have 400 of 600 images already downloaded). Both options of what to do when file already exists globally and in same directory are set to save.

**Steps to reproduce**
1. Reinstall Grabber using the same directory (7.3). Checked the Users AppData but there wasn't a Grabber folder there.
2. Search the name of an artist as a danbooru tag (e.g.: (NSFW) nanaya_(daaijianglin), ban)
3. Select either Get Page or Get All.
4. Set file directory as 'NSFW/bruh/%artist%/%character%%num%%md5%.%ext%' (I tried different combinations with the same result, I still point it out just in case)
5. Set file save preferences 'If a file already exists globally' and 'If it's the same directory' as 'Save'.
6. Go over to downloads, right click on the first group (the only one), then on download.

**Expected behavior**

In the first artist context, all 600 images are to be downloaded (maybe not the copies or childs I don't know if they're taken into account)

**Context**
Log: 
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4799795/main.log)
Settings:
[settingsCOPY.txt](https://github.com/Bionus/imgbrd-grabber/files/4799802/settingsCOPY.txt)

I don't use Grabber or even search on Danbooru a lot so maybe I missed a step somewhere but as far as intuition goes it should work. 

![Grabber_a6Fwyv8dCl](https://user-images.githubusercontent.com/43136048/85044666-3b80f180-b18e-11ea-8146-8e3e750965e8.png)

Windows 10
Grabber 7.3

EDIT: With the same first artist mentioned, I choose Safe (no), on the plus filter (previously there wasn't anything chosen, it was set as by default), and it has properly downloaded all files. Same when I choose Safe. Thus the problem comes whenever none is chosen, I can't remember which ones it downloads or if it's a mix of both.

**Comment by dkpeld** [comment]
You choose different sources, if on one source you downloaded most of the images by tag, then the rest of the sources can show almost everything as existing.
Example: You have 5 sources, on the first 200 images, on the rest 200+ (say 15 on each), it will download 200 images from the first, download 15 from the rest and as a result only 260 images will be downloaded, and 800 will be skiped

**Comment by NoticeMeHentai** [comment]
When I click on "Sources" there's only danbooru toggled though.
![image](https://user-images.githubusercontent.com/43136048/85067281-b5c26d80-b1b0-11ea-891c-73866bf19170.png)


For further reference in case I ever need multiple sources; I don't think I understand what you said entirely.
Do you mean that it skips because it has exactly the same tags even though they're not the same images?
It cannot be because they're exactly the same images because some of the posts were truly skipped. Like, I had images on the front of the first page that were skipped when I did "Get All" and then "Download".

**Comment by jkaryan** [comment]
You might want to try to running MD5 list fixer, make sure only files that actually exist are on the list.
