### ISSUE TITLE
Crash when trying to download both single and batch downloads 

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2024]
It is self explanatory and a repeat old bug. Just have both single and batch downloads, clicking download button crashes the app.

**Comment by GiovanH** [comment]
I have also been experiencing this bug for a long time, and I haven't had much luck tracking down the cause. There's no crash report prompt, and there aren't any useful statements in the log file. Only, the session gets broken, somehow.

**Comment by GiovanH** [comment]
This seems to be related to having multiple simultaneous downloads enabled? I get crashes with simultaneous downloads set to 2, but with 1 things are much more stable. Also, downloading one file at a time always works, even when simultaneous downloads is set to more than 1.

**Comment by brazenvoid** [comment]
It is something which has been fixed at least two times in my stint with this app but returns after a few weeks. I am not sure what causes it but it is the least annoying thing with this app when it needs to be restarted every hour to function properly.

**Comment by GiovanH** [comment]
This is still a major issue with the latest release.

**Comment by GiovanH** [comment]
This seems to happen with "Download selected" but *not* "Download"

**Comment by brazenvoid** [comment]
I also did experience crashes with download selected lately but its not related to there being both single and batch downloads. As mine happened without batch downloads.
