### ISSUE TITLE
Please using realtive shift for anime-pictures.net

### ISSUE THREAD

**Issue by stalkerg** [Bionus/imgbrd-grabber#2025]
Hello, I am anime-pictures.net owner. 
You must be using relative requests for getting a page with images because without it produces too much load to the server.  
Basically, it how the currently works browser. 
If you have already load page 5 and tried to load page 6 or more you should add to the request query:
```
last_page: 5
last_post_date: 2020-06-05 00:10:12.420566
```

last_post_date is "pubtime" for the latest picture for this page.  Also, it will work if you add to the query `order_by: date` only. 

Without this changes, I will ban the grabber on my site. Sorry.

**Comment by Bionus** [comment]
Hello 😄

Understood, I'll do the change ASAP and publish an updated release in the next few days.
Grabber already supports this kind of thing, so it should be done pretty quickly/easily, I didn't know anime-pictures supported it as well.

**Comment by Bionus** [comment]
Just to clarify, what you are asking is to stop doing this:
> https://anime-pictures.net/pictures/view_posts/5?lang=en&last_page=4&last_post_date=2020-06-24+10:24:33.497874

And instead to do this?
> https://anime-pictures.net/pictures/view_posts/5?lang=en&last_page=4&last_post_date=2020-06-24+10:24:33.497874

**Comment by stalkerg** [comment]
>Understood, I'll do the change ASAP and publish an updated release in the next few days.

Thanks a lot! If you will any problems with API, I will resolve it. 

> And instead to do this?

yes

>What if the user "jumps" from page 0 to page 5? Should I still add the information?

no, it's should working fine, we just start offset from that point.
