### ISSUE TITLE
Find and Download Favorites from Websites

### ISSUE THREAD

**Issue by sterelok123** [Bionus/imgbrd-grabber#2028]
Hi. I want to know if there is a way to download what I have marked as favorites in my accounts on, e.g. gelbooru and rule34 websites. I found this link in earlier issues, stating that I have to just copy the URL link in the search bar, but it doesn't show anything for me:

https://github.com/Bionus/imgbrd-grabber/issues/516

Does the latest version have this function? If yes, what should I do to find and download my favorites from my account in the websites? If not, would you add the feature? I would be grateful if you would reply. Thank you.

Best wishes,

**Comment by FichteFoll** [comment]
On danbooru, you can query for a user's favortes using the `fav:<username>` query, for example. I don't know about the other sites.

**Comment by Bionus** [comment]
The latest version should still allow you to paste URLs to have them parsed, but it's far from ideal.

The best solution is to use the actual search terms:
* Gelbooru supports it in Grabber using `fav:USER_ID`
* Shimmie (used by R34) supports it "naturally" using `favourited_by=USERNAME` or `favorited_by_userno=USER_ID` ([doc](https://shimmie.shishnet.org/ext_doc/index))

**Comment by Bewbman** [comment]
> The latest version should still allow you to paste URLs to have them parsed, but it's far from ideal.
> 
> The best solution is to use the actual search terms:
> 
> * Gelbooru supports it in Grabber using `fav:USER_ID`


Are you sure this works for Gelbooru? No results on mine every time using 'fav:215127' (example not my actual account lol) Thanks for the help

**Comment by Bionus** [comment]
> Are you sure this works for Gelbooru? No results on mine every time using 'fav:215127' (example not my actual account lol) Thanks for the help

You need to be logged in in Gelbooru  to use this syntax.
