### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by Entes1111** [Bionus/imgbrd-grabber#2029]
**Bug description**

Downloads are not working, all downloads return:
[Error] Loading error for 'https://danbooru.donmai.us/posts/0': Error transferring https://danbooru.donmai.us/posts/0 - server replied: Not Found

Same error occurs for other sources as well, such as konachan.
(Pixiv crashes the program though.)

**Comment by Bionus** [comment]
Hello, I can't reproduce what you're seeing.
* What Grabber version are you using? On what OS? Have you tried reproducing on [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly)?
* What's your "Sources" settings?
![image](https://user-images.githubusercontent.com/882719/87872597-3fd14200-c9ba-11ea-8876-234446d257b6.png)
* Can you share your log?
