### ISSUE TITLE
Adding a favorite tag before the image is loaded does not set an image

### ISSUE THREAD

**Issue by FichteFoll** [Bionus/imgbrd-grabber#2031]
**Bug description**

**Steps to reproduce**

1. Open a search result preview
2. Quickly right-click a tag on the preview window and select "Add to favorites"
3. Go to the Favorites tab
4. The favorite is added with no image

**Expected behavior**

The image is set after it has been loaded. Might also occur when changing the image for a favorite later.

**System information**

- OS: Arch Linux
- Grabber version: e46f69f1

**Comment by Bionus** [comment]
Indeed, I could see how this would happen.
I'll have a look to have a fix for the next version 👍
