### ISSUE TITLE
Add "Choose as Image" to favorites results context menu

### ISSUE THREAD

**Issue by FichteFoll** [Bionus/imgbrd-grabber#2032]
**Is your feature request related to a problem? Please describe**

Currently, as far as I'm aware, you can only set a favorite's image from a the image view window and by righclicking the exact tag that you alread favorited. 

**Describe the solution you'd like**

Provide this option in the favorites results tab (i.e. in the Favorites tab, when you select a favorite and then rightclick on an image in the results).

(Low priority.)

**Comment by Bionus** [comment]
> Currently, as far as I'm aware, you can only set a favorite's image from a the image view window and by righclicking the exact tag that you alread favorited.

Pretty much.
The only other place is when manually editing a favorite.

> Provide this option in the favorites results tab (i.e. in the Favorites tab, when you select a favorite and then rightclick on an image in the results).

👍
