### ISSUE TITLE
Ignore Downloaded Images

### ISSUE THREAD

**Issue by omegarunner1** [Bionus/imgbrd-grabber#2033]
**Is your feature request related to a problem? Please describe**

This isn't exactly a problem per se more a quality of life suggestion. I'm sure there are plenty of people who use this software to make sorting through and downloading images easier but there are plenty of us who want to download new images as they show up. This becomes harder if they're sorting through large numbers of images they've already downloaded trying to find the new stuff.

**Describe the solution you'd like**

In the Search Results Section of the Options Menu add a "Ignore Downloaded Images" checkbox that would be more or less the same as the "Ignore Blacklisted Images" checkbox in the Blacklist menu. This could be done either based on a directory search in your downloaded images, or it could be based on the md5 list for downloaded images.

**Describe alternatives you've considered**

The only alternative thing I can think of is placing the button in the additions menu (the one that shows up when you hit + button) in the search results to make it less permanent but it would operate more or less the same way so I don't see why it couldn't be added to the Options menu, or that you couldn't do both anyway.

**Additional context**

This isn't really required. People like me have workarounds for things like this we can use, just having an option to ignore images we've already downloaded in the search results would make sifting for new images a whole lot easier.

**Comment by tehgarra** [comment]
@omegarunner1 

grabber should offer this function. it may be set to save on your settings, but md5s are globally stored per the FAQ at least
i believe the value is set to save by default, and didnt notice this until i started getting duplicates for different tags that had the same md5 filenames
https://bionus.github.io/imgbrd-grabber/docs/faq.html
https://i.imgur.com/XBiHUzU.png

**Comment by omegarunner1** [comment]
Yes, I understand that but when doing a search with the Grabber, images you've already downloaded still show up in the search results inside the Grabber program. I was asking for a built-in function to allow users to ignore already downloaded images if they so choose. To make it easier to just look at the new images.

**Comment by omegarunner1** [comment]
Choose to download or redownload is not the issue, the issue is removing old images from search results so that the new or previously unseen are the only ones the user has to worry about.

**Comment by jkaryan** [comment]
A "Hide downloaded images" for the search results would actually be a cool feature.

**Comment by yami-no-tusbas** [comment]
You can use the filter **-grabber:downloaded** (don't forget the minus (-) before) in your post-filter, you can aply it globally with the "post filter" option in the options menu. The filter in the option will be applied to all queries, it is based on md5. If you put it in the option it'll be added to your downloads and monitors too.

For more information : 

> Special “grabber” token
> 
> A special token is generated by Grabber for images to be used by post-filters. It allows to filter on a few special values:
> 
>     grabber:alreadyExists if an image already exists on disk
>     grabber:inMd5List if an image’s MD5 is already present in the global MD5 list
>     grabber:downloaded if either grabber:alreadyExists or grabber:inMd5List is true
>     grabber:favorited if the image’s tags contain a favorited tag

link : [https://bionus.github.io/imgbrd-grabber/docs/search.html](https://bionus.github.io/imgbrd-grabber/docs/search.html)

Hope this help you.

And don't forget you can ask Grabber in the options to adapt is behavior based on the md5 : 
![Grabber_wLjUiGd7DS](https://user-images.githubusercontent.com/3921598/86324817-6b74ce00-bc3f-11ea-8a27-d60b2eebc13e.png)

"If a file exist globally" ca ben set to "Don't save" to skip already downloaded and existing image. Also I recommend to keep deleteds files in the md5 list to avoid re-downloading image in the future.

**Comment by omegarunner1** [comment]
Okay, I didn't know about that. Now that I've figured out how to use it, I'll go ahead and close this, since the issue seems to be entirely moot.
