### ISSUE TITLE
How to login in pixiv?

### ISSUE THREAD

**Issue by gabrielcesar16** [Bionus/imgbrd-grabber#2035]
What's the correct procedure on logging on with pixiv? I tried putting my pixiv id and password but it fails everytime.
![Annotation 2020-07-02 171129](https://user-images.githubusercontent.com/26472889/86409612-a0107600-bc8f-11ea-8432-379edd1e4300.jpg)

**Comment by Bionus** [comment]
Have you tried using your e-mail instead?
AFAIK Pixiv only accepts those for their API.

**Comment by gabrielcesar16** [comment]
Sorry but same result, it used to work back then, my grabber version is 7.3.0(x64), also i recently changed my pixiv password, don’t know if that’s supposed to play a role on this.    From: Jack VastiSent: 05 July 2020 15:00To: Bionus/imgbrd-grabberCc: Gabriel Cesar; AuthorSubject: Re: [Bionus/imgbrd-grabber] How to login in pixiv? (#2035) Have you tried using your e-mail instead?AFAIK Pixiv only accepts those for their API.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gabrielcesar16** [comment]
> Have you tried using your e-mail instead?
> AFAIK Pixiv only accepts those for their API.

Tried it, didn't work, my grabber version is 7.3.0(x64), it used to work some time ago, also i have recently changed my pixiv password, don't know if that plays a factor into that.

**Comment by gdmb420** [comment]
I had the same problem. I tested my login with the Python3 pixiv-api package login and was able to authenticate and run queries without any difficulty. Also using Grabber 7.3.0 (x64).

I was receiving:
```
No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"103:pixiv ID\u3001\u307e\u305f\u306f\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u6b63\u3057\u3044\u304b\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","code":1508}}}
```
Just as others complain in  #1765 

I suspected grabber might not be handling complex password correctly (long with uncommon characters like quotes, slashes, brackets). After changing my password from one which is long and complex to one which is simple (short with only chars `[A-Za-z0-9]`) I am able to successfully authenticate to Pixiv in grabber. I am not sure if this is a grabber problem or not, but i hope this helps others find a better solution. Obviously it may be security risk to change the password to be intentionally uncomplicated, so do at your own risk.

**Comment by Bionus** [comment]
> also i have recently changed my pixiv password, don't know if that plays a factor into that.

That was very likely the issue. It seems there was a problem with using invalidated refresh tokens, which happens when you change your password. I just pushed a fix! Alternatively, you can also delete your `accessToken` and `refreshToken` in:
```
C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites\Pixiv\www.pixiv.net\settings.ini
```

> I suspected grabber might not be handling complex password correctly (long with uncommon characters like quotes, slashes, brackets). After changing my password from one which is long and complex to one which is simple (short with only chars [A-Za-z0-9]) I am able to successfully authenticate to Pixiv in grabber. I am not sure if this is a grabber problem or not, but i hope this helps others find a better solution. Obviously it may be security risk to change the password to be intentionally uncomplicated, so do at your own risk.

Thanks for the info!
Indeed I could reproduce issues, especially with the `&` and `=` characters in the password, and just pushed a fix. 👍

**Comment by iDolmatov** [comment]
Now worked after yesterday changes? 

`[00:07:11.722][Info] [www.pixiv.net] Logging in...
[00:07:11.722][Info] Updating checkboxes.
[00:07:13.166][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
[00:07:13.168][Info] [www.pixiv.net] Login finished: failure.
[00:07:29.922][Info] Loading results...
[00:07:29.923][Warning] [www.pixiv.net][Json] You need to be logged in to use the Pixiv source.
[00:07:29.923][Warning] [www.pixiv.net] No valid source of the site returned result.`

Similar issue: https://danbooru.donmai.us/forum_topics/18051
