### ISSUE TITLE
Custom token isnt working on some sites

### ISSUE THREAD

**Issue by zoameldar** [Bionus/imgbrd-grabber#2036]
**Bug description**

I have set custom token that place tags in filename and for almost all sites it works, but anime-pictures and e621 seem to ignore it. I'm not counting in doujinshi sites or twitter.

**Steps to reproduce**

1. set whatever custom token like: test _solo glasses female male_
2. put test in filename
3. search for image that contain tag from token
4. try to save
5. see filename

**Expected behavior**

to work like on gelbooru or other sites

**System information**

- OS: Windows 10
- Grabber version: 7.3

**Comment by Bionus** [comment]
Indeed, it would seem there were two separate issues for Anime-Pictures and E621.
I just pushed two fixes for those 👍
