### ISSUE TITLE
Can't find the setting "Download Resized images only" (Need it for Sankakucomplex)

### ISSUE THREAD

**Issue by Greko5** [Bionus/imgbrd-grabber#2039]
Hi and thanks for your very nice downloader,
i would like to know whether it is possible to download the Sample images/Resized images(low resolution) from Sankakucomplex instead of the original big ones. (I need to download a lot of artists and haven't so much space...)

Some time ago i used two other sankaku complex downloaders, but one was blocked and i think your Grabber program is better than my other one, but can't find the setting "download resized images only" setting in your programm, it's very important for me.

In one Programm the Setting was called "Resized only" and in the other programm under Image Size you can choose between sample and Full. (Its Nandaka's Danbooru Downloader)

Would be very nice when you could tell me where i can find it, thank you.

**Comment by yami-no-tusbas** [comment]
There is an option that can help you :

![Grabber_9QVGCPFhlD](https://user-images.githubusercontent.com/3921598/86777262-34e0ee00-c059-11ea-9eef-c2f72d572b73.png)

uncheck it, here is the result on gelbooru : 

![XYcp1ickD8](https://user-images.githubusercontent.com/3921598/86777346-517d2600-c059-11ea-83cb-9a08c47d3413.png)

And the result on idol.sankaku :

(god sankaku is slow...)

The two first are orinals image & original image not checked.
On this board it seems it always donwload originals images...
The last folder is the resized one using grabber resizing (with 2000 in each field, adapt it to your needs).
![p8Od3MZT3P](https://user-images.githubusercontent.com/3921598/86780443-0c5af300-c05d-11ea-9ee2-c589053ae994.png)

![Grabber_h0GwKDbuQP](https://user-images.githubusercontent.com/3921598/86779082-6bb80380-c05b-11ea-93b1-99907ba4a146.png)

Hope this help you !

**Comment by Greko5** [comment]
Thank you it works.

**Comment by yami-no-tusbas** [comment]
Don't forget to close the issue if this has solved it for you.

**Comment by Bionus** [comment]
Thanks for the help @yami-no-tusbas 😄
