### ISSUE TITLE
gelbooru - tag issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#204]
I'm using Grabber 3.2.7, on gelbooru (Gelbooru Beta 0.2.5) it can't recognize tag types like artist, character and similar special tags, so naming with those is impossible.

> Original issue reported on code.google.com by `lolifuta...@gmail.com` on 10 Mar 2013 at 11:41

**Comment by Bionus** [comment]
See issue #270
