### ISSUE TITLE
Sankaku not show all files?

### ISSUE THREAD

**Issue by SalomonOuroboros** [Bionus/imgbrd-grabber#2041]
Hello, I have a question, when I put a label, for example, Nekomimi returns 206,253 results, but when I arrive after 1086 pages, all the remaining files mark them as existing, I already checked the files marked as existing in the downloaded folder and there they are , the remaining pages show them as analyzed and all URLs were analyzed, the question is? Are there really only 21,706 files out of 206,253? Or is there a problem?
I am logged in, the typical ad appears ([Info] Details limit reached (429). New try.), but even so the downloads continue, so I do not know what it is

![Captura de pantallafgfg (33)](https://user-images.githubusercontent.com/67995053/87349312-b930e680-c51b-11ea-9d98-8e8789cf22c6.png)

![Captura de pantalla u(31)](https://user-images.githubusercontent.com/67995053/87277418-d75cff00-c4a7-11ea-9495-677ef328e0f8.png)

**Comment by mastic544** [comment]
I'm not sure this is related but when i try to make sankakucomplex requests it just returns 0 results every time. I checked the link it was using to request images and in browser it returns a sankaku themed 404. Should i make a separate issue request?

Here's the link: https://chan.sankakucomplex.com/pictures/view_posts/0?denied_tags=&search_tag=yuri&lang=en

**Comment by mastic544** [comment]
I'm not sure this is related but when i try to make sankakucomplex requests it just returns 0 results every time. I checked the link it was using to request images and in browser it returns a sankaku themed 404. Should i make a separate issue request?

Here's the link: https://chan.sankakucomplex.com/pictures/view_posts/0?denied_tags=&search_tag=yuri&lang=en

**Comment by vannessqn** [comment]
@SalomonOuroboros hey man how do you making sankaku work mine just no result...
