### ISSUE TITLE
Is there an MD5 blacklist function?

### ISSUE THREAD

**Issue by kCh40s** [Bionus/imgbrd-grabber#2042]
I know that there is a tag blocking function and how it works, but I don't know if there is a function that block images by their MD5.

Imagine that in a certain tag there are several images that I want to download and some others do not. And in that same tag, there are several new images every day that I want to download, but I still don't want certain images to be downloaded so that I don't have to delete them one by one again and again every time an entire tag is downloaded on my computer.

If that function doesn't exist, I would suggest adding it. I think it would be practical, and if you consider of adding it, I also think it would be nice if the user have the option to select if wants that MD5 blacklisted images to be displayed or not in the search results.

Anyway, forgive me for my bad english. I also wanted to congratulate the programmers and collaborators of the project. Grabber is an excellent program and I have been using it for several years and I have never been disappointed with it.

**Comment by yami-no-tusbas** [comment]
Well in fact, there is the option to "keep" deleted files in md5 list, once activated, even if you deleted the file the first time, grabber can ingore it with : (minus) -grabber:inMd5List

As the [documentation ](https://bionus.github.io/imgbrd-grabber/docs/search.html) says : 

grabber:inMd5List if an image’s MD5 is already present in the global MD5 list

You can use it as a global post-filter.

Have you by curiosity tried to add something like "md5:**someMd5**" in the black list, one per line ? Not sure this could even work, i'll try out of curiosity.

**Comment by kCh40s** [comment]
Hell yeah, it really works. I feel dumb for never having tried this once before. I hadn't stopped to think that a token could act like a tag. Makes sense, after all
