### ISSUE TITLE
Remove duplicates without losing only copy? Update filenames for dupes from all providers without deletion?

### ISSUE THREAD

**Issue by TempMonkas** [Bionus/imgbrd-grabber#2043]
Apologies if this is already documented somewhere, but I'm looking to be able to do the following:

- Update existing files with new names as their tags are updated from providers (eg. when an unnamed character becomes named, etc.)
- Use the same naming convention that is currently being used per site (I don't want them all to use tags from a single provider, I want each provider to use their own tags) [As a result I doubt the "Rename existing images" feature will work as that uses a single provider to derive all tags with which to rename files]
- Dupes are allowed across different providers, but NOT within the same provider

My naming convention is: %search%/%websitename%/%date:format=yyyy-MM-dd hh.mm.ss% - %character% - %copyright% - %md5%.%ext%

Currently I have a bunch of dupes due to files having their tags updated, but I'm noticing that some art is actually being removed so I can't simply delete + redownload things, otherwise I'd be losing the files that are deleted from the providers.

So far I've tried a software called dupeGuru, but it's random whether it deletes the dupes with up-to-date filenames or the dupes with old filenames. It does me no good if it deletes the dupes with updated filename since those will simply redownload.

The way I have it set up is I simply run my download list every so often to update my folders with new content. Is there an easier way to go about updating my folders? I couldn't find instructions on how to use "Monitors" so I haven't touched that so far.

**Comment by FichteFoll** [comment]
Related: #2000
