### ISSUE TITLE
Create symlinks/hardlinks for dupes instead of shortcuts

### ISSUE THREAD

**Issue by TempMonkas** [Bionus/imgbrd-grabber#2044]
**Is your feature request related to a problem? Please describe**

In Options>Save, both "If a file already exists globally" and "If it's in the same directory" have an option to "Link". This merely creates a shortcut, which doesn't allow images to be viewed in the same alphabetical order as they're displayed in, nor does it allow images to be copied to other directories for consumption on other devices.

**Describe the solution you'd like**

Instead of shortcuts, create symlinks or hardlinks, so that image viewers as well as windows will treat them as actual files. This will allow image viewers to display them in the proper order, as well as files being able to be copied to other devices.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Bionus** [comment]
Soft links would require changing a bunch of config to have Grabber depend on Vista and above APIs, which is a pain. Plus, they don't bring much more value than shortcuts in most contexts. They also require elevated rights in many instances.

I just pushed a change to allow hard links in addition to shortcuts on Windows and symlinks on UNIX.
