### ISSUE TITLE
where is the lastest nighlty build ?

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2045]
I wanted to test your last commits, but can't find a nightly up to date.

https://github.com/Bionus/imgbrd-grabber/releases/nightly

Is an old version from 2017, is the only solution compiling from source to get the lastest version ?

**Comment by RinMaru** [comment]
I think he/she disabled the binaries. and the build isnt actually from 2017 thats just the date the Nightly tag was created so everytime you download a nightly from there its the most current one

**Comment by yami-no-tusbas** [comment]
> 
> 
> I think he/she disabled the binaries. and the build isnt actually from 2017 thats just the date the Nightly tag was created so everytime you download a nightly from there its the most current one

Yeah, but file inside archive are source file and date of the files are in 2017, I can't build them too. I remember like an nightly setup.exe, not an archive

**Comment by yami-no-tusbas** [comment]
Yeah Nightly is there an up to date ! Ty @Bionus

**Comment by Bionus** [comment]
Yes the nightly was just broken for a few days it seems 😄 
I just fixed it
