### ISSUE TITLE
Problems loading Rule34 Paheal.

### ISSUE THREAD

**Issue by Eneocho** [Bionus/imgbrd-grabber#2048]
I have the latest version of Grabber, every booru works fine, but rule34.paheal.net does not. It never loads anything.

It worked fine on the previous version; what happened?

**Comment by Bionus** [comment]
You'll have to give more information, at least your log and settings file, because it works with no issue on my end, be it the RSS or HTML source:
![image](https://user-images.githubusercontent.com/882719/88053073-86aa6d80-cb5b-11ea-8f64-a5d72530dc85.png)

**Comment by Jdawg496** [comment]
I have the same issue, here is my log showing successful use with danbooru.donmai.us and rule34.xxx but failure with rule34.paheal.net. Log and settings file included.

[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/5545789/settings.ini.txt)
[main.log](https://github.com/Bionus/imgbrd-grabber/files/5545790/main.log)
