### ISSUE TITLE
images saved as TMP. file instead of jpg or png

### ISSUE THREAD

**Issue by zura64** [Bionus/imgbrd-grabber#2049]
**Bug description**

The images downloaded are saved as TMP. files

**Steps to reproduce**

1. Search a tag and click "Ok"
2. Click on "Get all"
3. Go to "Downloads"
4. Click on "Download" or "Download selected"
5. Download starts
6. The images are saved as TMP. files in the destination folder

**Expected behavior**

Images downloaded saved as PNG file or JPG file

**Context**

-It worked well when i used it last time in may 2020
-I updated it to 7.3.0 when i opened it today and this bug happened
-I tried to uninstall everything and download version 7.2.1 again but the bug did not disappear

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/4945173/settings.txt)
i copy pasted the settings.ini into a txt. to be able to upload it here 

**Screenshots**

**System information**

- OS: Windows 7
- Grabber version: 7.3.0 and 7.2.1

**Additional context**

**Comment by Bionus** [comment]
I tried reproducing with the settings you provided, but it saved the files as JPG/PNG, so I guess the issue might be dependent on other factors.

Can you share your log file for when this issue happens?

**Comment by zura64** [comment]
Hi thanks for looking into this.
I downloaded the first page from danbooru to test it, the same thing happens, here is the log:
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4963316/main.log)

**Comment by Bionus** [comment]
Could it be caused by the  "Unable to open file to set creation date" errors you have in your log?
Does disabling the "Keep original creation date" feature "fix" the problem?

**Comment by zura64** [comment]
No, the same thing happened.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/4973955/main.log)
![screenshot](https://user-images.githubusercontent.com/68523291/88429288-5b768700-cdc4-11ea-914b-bcc31db5a2d7.PNG)

**Comment by zura64** [comment]
i updated to the newest update 7.3.1
the problem is still here

**Comment by omegarunner1** [comment]
Is it possible that this glitch is tied to a naming scheme? Because I see that all your images are renamed seemingly for organizational purposes but I've never run into the issue and though I'm not 100% certain the naming is the cause, I do know that I prefer to keep the naming token %md5%.%ext% to help the Blacklist and MD5 fixers work.

**Comment by yami-no-tusbas** [comment]
I had it too on last nightly f3ae6e66 it seems to have to do with permission on windows. For "no" reason the folder was on read only, at least part of it. Deleting the folder (after having moved previous content on another one), then recreate the folder seems to fix it. (with grabber closed while moving the things.)
