### ISSUE TITLE
Installer breaks portable installations

### ISSUE THREAD

**Issue by Hojo-Norem** [Bionus/imgbrd-grabber#2055]
**Bug description**

When Grabber is installed on top of an existing portable installation, the resulting installation breaks with a "No source found" error.  On further investigation, the 'Sites' directory in Grabber's installation directory is deleted and is then re-created in the Users\...\appdata\local\bionus\grabber directory as if it was a non-portable install.

**Steps to reproduce**

1. Install Grabber and then make it portable.
2. Grabber starts properly
3. Install Grabber again, making sure to install into the same directory
3. Grabber fails to start and displays "No source found" error.
4. Explore to %HOMEDRIVE%%HOMEPATH%\appdata\local\bionus\grabber and move/copy the sites directory back into the portable install directory
5. Start Grabber.  It complains about the previous session then starts properly.

**Expected behavior**

The installer detects that it's installing over a portable installation and places all required files and directories into the portable installation directory **and creates no files or directories within appdata**.

**Comment by Bionus** [comment]
Indeed, the `sites` directory is getting deleted for historical reasons.

I won't invest much into trying to have it work really well with portable installs, but I agree that it's not acceptable as this directory contains user settings, so I'll at least remove this logic.

You'll still need to re-copy the files after the update though.
