### ISSUE TITLE
All versions above 7.1.1 crash with "Merge results" on.

### ISSUE THREAD

**Issue by SuperZoops** [Bionus/imgbrd-grabber#2058]
**Steps to reproduce**

1. Install
2. Select all sources.
3. Toggle merge sources
4. search for something

Issue is on 7.2.0 moving forward to the most recent build.
Happens on _both_ Windows and Linux.

**Comment by Xenthio** [comment]
happens on macOS too, hope this gets fixed

**Comment by khasugha** [comment]
also having this issue on windows

**Comment by BgvgB** [comment]
Merging is indeed unstable (and possibly not working anymore). In the mean time, uncheck some sources (ex: twitter, pixiv, the 2 rule34) to not crash.

**Comment by Bionus** [comment]
I could reproduce the crashes on 7.3.2 by selecting all sources (including Twitter, Pixiv, and R34) and searching some random tag. Doing the same on the Nightly version did not cause a crash.

Are you able reproduce the crash on the Nightly version?
https://github.com/Bionus/imgbrd-grabber/releases/nightly
