### ISSUE TITLE
Download list dead in nightly d21116ba (nightly)

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2060]
**Bug description**

Download list dead in nightly d21116ba

**Steps to reproduce**

use nightly d21116ba

**Expected behavior**

normal list.

**Context**

just upgraded toi lastest nightly, the downloading work, just the display and editing of the list don't seem to work.
I tried loading and old list, same, jobs are loaded, the number column diplay, but nothing else.

**Screenshots**

![Grabber_Lc2kIhDJmw](https://user-images.githubusercontent.com/3921598/88509600-bc2edb00-cfe1-11ea-916c-1d2ac6b214a1.png)

As you can see there is "one" group, but no column to display, no error in the logs too. if i launch the download everything download fine.

**System information**

- OS: Windows 10
- Grabber version: nightly d21116ba

**Comment by Bionus** [comment]
Indeed, the upgrade from static table to a table with moveable and toggle-able columns totally broke on "new" installs.
Just pushed a fix

**Comment by yami-no-tusbas** [comment]
Yep work fine after reset settings.ini
Good Job !

**Comment by FichteFoll** [comment]
Single image download list is still dead for me on 17f7348d.
