### ISSUE TITLE
[UI] duplicate "ignored tags" field ?

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2061]
**Bug description**

Seems lik an artifact from development, not a "bug".

**Steps to reproduce**

Go to the setting, there is two "ignored tags" input field, don't know why.

**Expected behavior**

Well having only the big one ?

**Context**

* Main log is not relevant this time.
* [settings.txt](https://github.com/Bionus/imgbrd-grabber/files/4984791/settings.txt) (maybe relevant)

**Screenshots**
Into "General" : 
![Grabber_D2lovElt5C](https://user-images.githubusercontent.com/3921598/88597400-74529700-d067-11ea-99bc-ac13b630d915.png)
Into is own item : 
![Grabber_63vSbHCDfH](https://user-images.githubusercontent.com/3921598/88597586-d7dcc480-d067-11ea-840a-3fbf55a8fb07.png)

**System information**

- OS: Windows 10
- Grabber version: nightly b090ecd5

**Comment by Bionus** [comment]
That's indeed very confusing since they have the same label.
They're actually doing different things, explained in the small text under it.

* The single line one in "General" will contain tags that will not be included in the image *at all*. The tag will be present in neither `%artist%` nor `%tags%`.
* The multi-line one with its own category will simply move the tag from whatever type it is (artist / copyright / whatever) to "general". As such, it won't be found in `%artist%` for example, but still be present in `%tags%`.

I think the first one in general also deserves its own category and a multi-line input, as well as some renaming.
Any suggestion on what they should be called?

**Comment by yami-no-tusbas** [comment]
Is %tags% even existing ? %all% Seems the thing here.
Well as I understand : 

> Ignored tags (General) : does remove the tag from ever showing.
> Ignored tags (category) : does remove tags from everything exept in %all% and %allo% (I assume)

Well maybe it is simple like : 

> Ignored tags (General) -> Removed Tags (since we never gonna see them again) :  a removed tag will show as empty onto a path or filename.
> Ignored tags (category) -> Ignored Tags : Won't show but can still be accessed with %all(o)%

Maybe this should do, and yeah it's own category would make sense, and maybe an toggle option to sync the two ?
But seeing this, I'm asking myself, does it even make sense ? If we don't want a tag to show, it would generaly be for organizing purpose, then, we would't be using %all% that add too much information in a string. After all, %all% does is job correctly in displaying every single tags. 

Ok maybe this make more sense : 

Keep only one "ignored tags", the category one, but under the textfield add a check box like this : 

- [ ] Ignore thoses tags in %all% ? (_If checked the tag will never be shown in a filename, if unckecked using %all% will show the  tags but none the others %variable% _)

For this I'm assuming ppl don't use the two different sets of tags, but well, does it even make sense at the begginning ?

**Comment by Bionus** [comment]
As you say, syncing the two doesn't make sense.

If you're already "removing" the tag, you don't need to "ignore" it as well. As such, your default should be to simply add the tags you don't want to the "removed tags" list.

The "ignored" is for more special purposes, when you want to keep the tag in `%all%` but not in typed tokens. That can be the tags for annoying series where images will have multiple typed tokens meaning the same thing, such as "pokemon", "pokemon_red", "pokemon_blue", etc. You might want to keep all tags but if you use `%copyright%`, it will end up as "multiple" so for this you can use the "ignored" feature.

That's quite niche, but still separate enough to not work with simply a checkbox.
For now I just moved them both to the same settings group, putting "removed" at the top.

**Comment by yami-no-tusbas** [comment]
It seems fine now, making sense. Nice !
