### ISSUE TITLE
"if it's in the same directory"/"Don't Save" not working because md5s.txt is missing entries

### ISSUE THREAD

**Issue by sbobbo** [Bionus/imgbrd-grabber#2062]
**Bug description**

I have the monitor grab a ton of files, and i still backdate my favorites.json to grab images that were missed the first time due to a delay in them being tagged on the relevant sites. I have "if it's in the same directory"/"Don't Save" set and "Keep deleted files in the MD5 list", and yet I the list doesn't seem to include entries it should, so files that have been renamed get redownloaded. I went to md5s.txt and picked a random folder from my moniitor and searched the file. There are 50 files in the folder now that have been downloaded in the last month, but there are only 5 entries in md5s.txt.

What can cause this? Does md5s.txt only keep one entry per md5? Does it only save one md5 per time the program is run, even if it downloaded 2 copes during a run? Does it purge md5s randomly? I think it's one of the first 2, because a spot check of MD5's for the files that are present in said folder but not associated with that folder in md5s.txt actually shows that the MD5s are present in the folder, they are just associated with a different folder. 

I don't know if that made sense, but basically, an image was downloaded to a "final fantasy" folder and a "tifa_lockhart" folder, but the md5 for that image is only in the md5s.txt once, associated with the "tifa_lockhart" folder.

But then i found at least one example of a duplicate md5 entry. Which is why i'm thinking that it may be based on one entry per time the program ran? idk.

**Steps to reproduce**

This would be a pain to reproduce, honestly. I may do some testing on a VM, but maybe download the same file to a few different folders using different tag searches and see if it makes entries for each download?

**Expected behavior**

I want Grabber to not redownload a file to the same folder if the file is present there currently(but renamed), or if it has ever been downloaded to that folder. I actually want some duplicates at times(since i download by character tags, copyright tags, artist tags, and misc tags), so the "if file exists globally" setting doesn't help me any. I guess what i want is for every download of an MD5 to a different folder to get a unique entry in md5s.txt

**System information**

- OS: Windows 10
- Grabber version: 7.3.1 x64

**Comment by Bionus** [comment]
> Does md5s.txt only keep one entry per md5?

Yes. But indeed, with your settings it doesn't make sense, as one MD5 should be able to have multiple locations.
Both "keep deleted" and using "same directory" should allow this.

**Comment by Bionus** [comment]
I just pushed a fix for that, that should allow MD5s to point to multiple paths!
I made a few automated and manual tests with your specific use case, and didn't find any issues.

Just in case, I've had Grabber automatically generate a backup of the MD5 list on the first startup since this change. I wouldn't want anyone getting their MD5 list ruined because of a stupid bug.

You can try it out in the [nightly release](https://github.com/Bionus/imgbrd-grabber/releases/nightly).

**Comment by sbobbo** [comment]
Thank you!
