### ISSUE TITLE
Issues signing into danbooru

### ISSUE THREAD

**Issue by kaliico** [Bionus/imgbrd-grabber#2063]
I'm having issues signing into danbooru, I have a gold account so I'd like to sign in to use more than the standard 2 tags, I enter my username and api key like normal, but when I try to load any page it comes back saying Danbooru-No result. Its happening on both my mac as well as my pc.

**Comment by Bionus** [comment]
Which login method are you using?

AFAIK for Danbooru there are three:
* **HTTP basic**: username and API key, should work
* **Post**: you have to use your username and password, not your API key
* **Through URL**: you have to use your username and password, not your API key

![image](https://user-images.githubusercontent.com/882719/88720602-695e3c00-d125-11ea-8c3d-2bb551f20cd2.png)

I'm personally using API key as you can see above, with no issues.
I can reproduce the "no results" error you see by entering a wrong API key, though.

**Comment by kaliico** [comment]
> Which login method are you using?
> 
> AFAIK for Danbooru there are three:
> 
> * **HTTP basic**: username and API key, should work
> * **Post**: you have to use your username and password, not your API key
> * **Through URL**: you have to use your username and password, not your API key
> 
> ![image](https://user-images.githubusercontent.com/882719/88720602-695e3c00-d125-11ea-8c3d-2bb551f20cd2.png)
> 
> I'm personally using API key as you can see above, with no issues.
> I can reproduce the "no results" error you see by entering a wrong API key, though.
> 
> Make sure you're using "HTTP basic" and the API key you're using is correct, without spaces on either side from a copy and paste. You can also try to restart Grabber and see if it helps.

That fixed it for me, on the mac it doesn't show the http basic for me so that was why it didn't work there, and I had Through URL selected on the pc, so I just swapped it over and its now working fine
