### ISSUE TITLE
Rename tool destination empty.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2068]
**Bug description**

An image is more obvious
![Grabber_nY4sGmEeSr](https://user-images.githubusercontent.com/3921598/89122789-98303580-d4ca-11ea-8337-8c16d03b7380.png)

The right column is empty, it should display the new filename

**Steps to reproduce**

1. Go to 'tool'
2. Click on 'rename existing image'
3. See empty right column

**Expected behavior**

Like before the lazy load modification, displaying the new name for the files.

**System information**

- OS: Windows 10
- Grabber version: nightly 11f77c07 (but the bug is here from more time)

**Comment by Bionus** [comment]
Fixed!
Thanks for the report 👍

**Comment by yami-no-tusbas** [comment]
Good Job !
