### ISSUE TITLE
Keep tab order of the last session

### ISSUE THREAD

**Issue by Demagole** [Bionus/imgbrd-grabber#2073]
Some of us are probably using Grabber just to watch images inside of it and so we open a lot of tabs and have the options "Restore last session " checked.

The problem is, with this option enabled, that the tabs restored are not in the same order as the ones in the previous session closed. They are in some random order.

I'll try to see what I can do to fix this but I really don't know if I'll be able to so i'm posting the issue here.

**Comment by FichteFoll** [comment]
Generally, tab order seems to be preserved for me, but I do have some faint memory of that not being the case at times.
