### ISSUE TITLE
Pixiv - Show the image's upload URL

### ISSUE THREAD

**Issue by Stormghetti** [Bionus/imgbrd-grabber#2076]
I don't have much to explain here. I like to source content, so if I'm about to share an upload with more than one page, I believe being able to copy the upload's URL right inside Grabber would be quite useful. I was thinking it could be shown in the "More details" tab when you inspect the upload, but it could also be a right click option that's specific to Pixiv. Better yet, it could be a global option for images that have listed sources. It'd take less clicks that way.

**Comment by FichteFoll** [comment]
Do you want the source url or the page url? I'd also appreciate a key binding to copy an image's page url or open it in a browser, but it sounds like a quite specific use case to me.

**Comment by Stormghetti** [comment]
Page URL. If adding a key/right-click option for it is too specific, then I'd suggest sticking to my first alternative. Pixiv page URLs should exist within the program, at the very least.

**Comment by Stormghetti** [comment]
No one's looked at this, judging by the lack of interaction. The Page URL in the "Details" tab for images from the Pixiv source still takes you to an error page because it's an _API_ URL and not the actual page URL, so the option to open Pixiv images in a browser is useless unless you meticulously edit the URL to take you to the actual page.

Has there been any progress on that? It seems weird that this is still an issue after two years. I'm not demanding people look into this, but having the page URL take you to an error page is odd.
