### ISSUE TITLE
ctrl+w key binding to close the current tab

### ISSUE THREAD

**Issue by FichteFoll** [Bionus/imgbrd-grabber#2079]
I repeatedly attempt to close tabs in Grabber using ctrl+w, which simply does not work. It's a very common binding to close tabs, much like ctrl+t is to open a new one (or ctrl+n for some), so please add such a binding. 

According to the [shortcuts page](https://bionus.github.io/imgbrd-grabber/docs/shortcuts.html) this binding already exists, but it has never worked for me.

I'm on Arch Linux and using 17f7348d currently.

**Comment by Penguin-Guru** [comment]
I use i3 and get this message when I try to CTRL+W a tab: "QAction::event: Ambiguous shortcut overload: Ctrl+W"

Fixed it by removing the duplicate shortcut. One binds to CTRL+W and the other binds to QKeySequence::close. I assume QKeySequence::close is CTRL+W but have not confirmed that.

https://github.com/Bionus/imgbrd-grabber/blob/master/src/gui/src/main-window.cpp#L188

**Comment by Penguin-Guru** [comment]
Changing the value from QKeySequence::close to QKeySequence::Bold also fixes the issue, so I think that confirms there is some overlap.

Close = 4
CTRL = 67108864
Key_W = 87
