### ISSUE TITLE
Gelbooru No API login selection and POST appears to not work right

### ISSUE THREAD

**Issue by negiworx** [Bionus/imgbrd-grabber#2088]
**Bug description**

When adding an account/login info for gelbooru there is no selection for API Key. also when using the only selection that it gives (POST) the login works when tested but when I try to search it still returns no result, however when going to gelbooru with the same search it has results. There is an API key on my gelbooru account page so I know it supports it but it appears that there are other sites that also only have POST as a login type like gelbooru. Is this something that isn't supported for Gelbooru based sites at this time or is there something else that I'm missing.
**Steps to reproduce**

1. Go to sources
2. Click on Options
3. go to the login tab
4. Login type isn't able to be changed.

**Expected behavior**

The ability to select API as the login type. and see all posts after adding account information. And or all posts showing up when searching for them.

**Context**

I am trying to make it so that all posts even ones that are marked contentious content are downloaded. Without a login, Gelbooru and some other sites won't show that type of content. I'm actually using this software to download many of the preadded sites so that I can use the images for a few different AI concepts I'm working on, and need as many images of various kinds with and without good tagging for them.

**System information**

- OS: Ubuntu
- Grabber version: 7.3.2

**Additional context**

I also tried to find a similar problem in the issues that have been submitted already and wasn't able to find anything that was the same. sorry if I'm just missing something.

**Comment by negiworx** [comment]
I was able to work it out turns out that the problem was a layer 8 problem lol but would still like to know why there is no API key support for the gelbooru types of sites.

**Comment by Bionus** [comment]
Indeed, it seems that a new "API key" login was added recently.

I just pushed an update for the Gelbooru source to allow to use it. You'll just have to select "Through URL" for login, and put your user  ID and API key there to use it.

**Comment by negiworx** [comment]
cool and thanks for the info and update!
