### ISSUE TITLE
Grabber takes 3 times the disk size in RAM for the MD5 database

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#2093]
https://i.imgur.com/CHVpSAr.png

It worked just fine a few days ago. The issue remains after reinstalling Grabber. Latest version. Pls help

**Comment by Xeddius** [comment]
Backup and then delete the settings folder and do a clean reinstall and leave all settings default, if this fixes it then set it up how you like and test more.

**Comment by cyaoeu** [comment]
I had the same issue, my problem was a 200MB md5s.txt in the appdata folder. Deleting that fixed the RAM issue and made the program start up fast again.

**Comment by Bionus** [comment]
I'll see what can be done to improve the memory footprint of the MD5 database.
For it to take 6Go of RAM, I'd say your MD5 database is 2Go. You can see that in:
```
C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber
```

> and made the program start up fast again

This seem to be a separate issue for which I just pushed a fix!
