### ISSUE TITLE
Problem with naming webm and mp4 type of files

### ISSUE THREAD

**Issue by SodaPopin** [Bionus/imgbrd-grabber#2096]
Despite having the name setting to be %filename%.%ext% when downloading, the filenames of every webm files won't follow that but instead be using %md5%.%ext%.
On PNG and other file types, it would go smoothly with their names going something along ### - details.ext but on webms, it's always be a scrambled combination of numbers and letters like 883j7d0ccc1842.webm

**Comment by SodaPopin** [comment]
Forgot to mention, it doesn't work with mp4 files as well

**Comment by Bionus** [comment]
What source does this happen on?
Are you sure the filenames on that site are not actually using the MD5 for their filenames?

**Comment by K-Yas** [comment]
Not sure if its the same for him, but it happens on rule34.paheal.net

**Comment by SodaPopin** [comment]
> 
> 
> Not sure if its the same for him, but it happens on rule34.paheal.net

Yeah, it happens on that site

**Comment by SodaPopin** [comment]
> 
> 
> What source does this happen on?
> Are you sure the filenames on that site are not actually using the MD5 for their filenames?



> 
> 
> Not sure if its the same for him, but it happens on rule34.paheal.net

Yeah, this problem occurs on Rule34 Paheal
