### ISSUE TITLE
Gelbooru downloads samples instead of original file

### ISSUE THREAD

**Issue by sdfs2312** [Bionus/imgbrd-grabber#2100]
When using Gelbooru as a source, sometimes samples are downloaded instead of the original image, leading to some files being lower quality or different format, such as mp4 sample vs webm original. I do not think it is part of the Option, Save, "Download sample on error" because there were no other errors. Other source, like rule34.xxx, would download original file. I would like to get the original file for Gelbooru as well. Thank you.

**Comment by asjf092** [comment]
I made original post (forgot account). Here are example links (warning nsfw) where the sample is much smaller in size and quality than the original file. How can I download original file through Grabber? 
https://gelbooru.com/index.php?page=post&s=view&id=4581336
https://gelbooru.com/index.php?page=post&s=view&id=4316107
