### ISSUE TITLE
Tags separator not working

### ISSUE THREAD

**Issue by General-Trident** [Bionus/imgbrd-grabber#2101]
Please mark this as a question.

![image](https://user-images.githubusercontent.com/52889250/91548005-ec55fa80-e94e-11ea-9776-b82aa6d040a0.png)

In this image, the conditon is applied to tag 'character'. The conditions had been applied to all tags, which is:
Separator: [,] (a comma)
if more than n tags (n = 4): 
 [x] Keep n tags, then add: [n=3] [_(+%count%)]
 
For example, if a file contains multiple names of characters, it will leave kaga_(kancolle),akagi_(kancolle),takao_(kancolle)_(+999). This condition is applied to all tags other than characters.

But sometimes the condition won't work. For example, some image will give the filename "aang katara sokka", without comma included. This happened to all tags, like copyrights, artists, etc. which creates confusion.

Please help on how to make the comma works as a separator. Thank you.

**Comment by Bionus** [comment]
It's not a question but indeed a bug.
When using "Keep n tags, then add", it would seem that the tag separator is being hard-coded to " ":

https://github.com/Bionus/imgbrd-grabber/blob/310089584b5e7c0f62fdc1d4142de21d46635ccb/src/lib/src/models/filename.cpp#L72-L74

I  just pushed a fix to make it use the correct separator.
