### ISSUE TITLE
Gelbooru results different when using internet browser vs imgbrd-grabber

### ISSUE THREAD

**Issue by sdfs2312** [Bionus/imgbrd-grabber#2102]
Using internet browser, go to Gelbooru.com and look up posts without inputting any tags ("browse all posts"). Image A is on page 1 and Image B is on page 3. Use imbrd-grabber (no blacklisted tags) and Gelbooru source, search again without inputting any tags. Image A is on page 1 and Image B is on page 1. Several images between Image A and B are missing when using imgbrd-grabber. Thank you.

**Comment by Bionus** [comment]
I couldn't reproduce, logged in or out, with fringe content enabled or disabled, with HTML or XML API. 🤔 
Every time I got the exact same result in Grabber and the browser.

Do you have a few examples of images that were not being shown in Grabber?
Were they all "fringe content" or something similar?

**Comment by asjf092** [comment]
I made original comment (forgot account). I checked again with browser and Grabber and no problem. I am not sure why problem occurred in the first place. Thank you for checking.
