### ISSUE TITLE
Make Filename Date use YYYY-MM-DD Format, or Have Separate Date Components

### ISSUE THREAD

**Issue by Malkierian** [Bionus/imgbrd-grabber#2103]
**Is your feature request related to a problem? Please describe**

No.

**Describe the solution you'd like**

Having the date used for file naming be MM-DD-YYYY doesn't really make sense, it's arbitrary. However, having the year first is very useful for sorting purposes.

**Describe alternatives you've considered**

Alternatively, separate the components of the date into %year%, %month%, %day% and %time% parameters, so we can customize the naming schemes (I'd love to be able to easily download stuff into %search%/%year%/%month% subfolders).

**Comment by Gaffnet** [comment]
This is covered in the Grabber Wiki under the "[Filename](https://bionus.github.io/imgbrd-grabber/docs/filename.html)" section, "Dates" sub-section. 

You can reformat the %date% token with the "format" option like this: `%date:format=yyyyMMdd%`

A formatted %date% token can be included as part of a filename format in Grabber to automatically create directories and subdirectories upon downloading an image.

As per your example:

`%search%/%date:format=yyyy%/%date:format=MM%/image_name_%md5%.%ext%`
