### ISSUE TITLE
Help with conditional filenaming

### ISSUE THREAD

**Issue by Roshri** [Bionus/imgbrd-grabber#2105]
I'm looking for fanart of some franchises, and the option of "using shortest" for copyright always helps, but only if the %copyright% field is populated with one than more tag.
For example, I'm looking for precure fanart and a lot is only tagged with dokidoki_precure! for example so I'm always renaming folders which can get a bit tedious.

I'm reading through the documentation but I can't quite understand the conditional section.
I want to add a rule that says "if in copyright, dokidoki_precure! change to precure" and so on, but I'm not sure of how to do it or get it to work
This way, using the path "%artist%/%copyright%/%character%_md5.ext" I can get everything in the same folder instead of 18 different folders with precure art.I thought of adding them to the ignore list but if there's only one tag in the copyright namespace then it wouldn't work as intended

**Comment by Bionus** [comment]
I see three main options here:

### Use an inline condition
In your filename, directly use all "precure" tags you can imagine as a condition:
```
%artist%/<"precure" | "dokidoki_precure!"?precure:%copyright%>/%character%/%md5%.%ext%
```
I don't really recommend this as it makes your filename long and hard to read.

### Use a custom token
Put all the tags related to "precure" you can imagine inside:

![image](https://user-images.githubusercontent.com/882719/92304297-014d1200-ef7d-11ea-8404-e47633dd8fea.png)

Then, in your filename, you can use use it in an inline condition:
```
%artist%/<%precure%?precure:%copyright%>/%character%/%md5%.%ext%
```
Use this if your filename doesn't change that much for precure.

###  Use a conditional filename
Put all the tags related to "precure" you can imaging in the "condition" field of the filename.
Then, use whatever filename you want for precure images:

![image](https://user-images.githubusercontent.com/882719/92304078-26408580-ef7b-11ea-8a66-c3a5d2ebfc4b.png)

Use this if you want to change more than just one part of the filename, or even save them in a different location altogether.

**Comment by Roshri** [comment]
Thanks! Now I understood how to use it.
Custom token seems to work fine for now
