### ISSUE TITLE
Immediately write config file changes to disk

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2107]
**Is your feature request related to a problem? Please describe**

Grabber crashes, its a reality that we are used to now but due to the changes to config files management to reduce writes to the disk, though beneficial to an extent does not fit in with the crashing. Hours of work can go down the drain just because the app crashes and all changes wiped.

**Describe the solution you'd like**

An option to disable the writes management and allow immediate writing to the config files. I am thinking of all the configuration files except log.

**Comment by Bionus** [comment]
What config changes do you mean exactly?

The Grabber settings window writes the changes to the disk as soon as it closes. Same thing for source settings.

**Comment by brazenvoid** [comment]
Well to be specific blacklist, downloads etc are the most damaging. As I said, grabber dies or gets stuck due to request locking or I have to force close it from time to time so the write to disk on close doesn't trigger.
