### ISSUE TITLE
[Bug] Text encoding used is incompatible with what sources are using

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2115]
**Bug description**

As title says, there is a conflict of encoding being used with Grabber and sources based on Gelbooru API.

For example, the following tag in rule34.xxx cannot be correctly filtered or displayed by the app:

![Annotation 2020-09-06 121636](https://user-images.githubusercontent.com/8722533/92320434-f658b700-f03a-11ea-8e92-bc2825c63d19.png)

The app displays it like so:

![Annotation 2020-09-06 121901](https://user-images.githubusercontent.com/8722533/92320465-2b650980-f03b-11ea-848e-251e6bc760f3.png)

First it is not detected in images and thus not filtered. 

Oddly if you blacklist this tag and open an image with it, the second time, the app recognizes it as blacklisted. First time it opens it without any reaction.

**System information**

- OS: Windows 10
- Grabber version: Nightly

**Comment by Bionus** [comment]
Hard  to reproduce now that Gelbooru renamed their `pokémon` tags to `pokemon` without diacritics, but this should have been fixed in [v7.6.0](https://github.com/Bionus/imgbrd-grabber/releases/v7.6.0) by 4e233d8968ccddef59162e51d7442f01f40dd486
