### ISSUE TITLE
Images stop loading after reaching the final page on a tag/s and using either back function or navigating to another tag

### ISSUE THREAD

**Issue by EPuigdemont** [Bionus/imgbrd-grabber#2117]
**Bug description**

When navigating the image pages, after reaching the final page when no more images are shown, trying to use the back arrow or clicking on another tag on an image to navigate to the image list of said tag will not load any images, any new tabs will not load images either and the only way to start loading images again is to close and re-open the program.

**Steps to reproduce**

1. Set search to Gelbooru only
2. Use the tag search bar and use the following tag: hololive rating:safe (currently 103 pages)
3. Navigate to the last page using the page search box (jump to page 103)
4. Once on the last page, click on the last image and click on the artist tag (brat) to load the images for the tagged artist
5. The page will remain as the last page of the hololive rating:safe tag (103), clicking on the go to first page multiple times in quick succession will make the page go back to page 1, but no images will load
6. Try to use the tag search bar to search for any tag, no images will load
7. The only way to get images from gelbooru to load again is to close and restart the application
8. Using the sources window and removing gelbooru and setting it to any other will load images again, setting the source back to only gelbooru will not load images again

*The page index will stay at the maximum page count of the previous tag, IE: 103, when attempting to load the images for a tag which has less pages, IE: 10 pages.

It sometimes takes a few tries of browsing the last pages and clicking on a tag to get put on the blank page that won't load any images further. If the current tag's max page number/image count is lower than the new selected tag the issue will not occur.

**Expected behavior**

When clicking on the go to last page button (two arrows, bottom right) on a tag and selecting any other tag the page index should be reset to page 1, loading all the images in page 1 accordingly.

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/5194717/main.log)
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/5194718/settings.ini.txt)

- OS: W10   Version	10.0.19041 Build 19041

- Grabber version: 7.3.2

**Additional context**

I am using a very large image per page number to approximate an infinite scrolling behavior, I suspect the high image count per page causes issues when reaching the last page on a tag, and I don't recall ever having this bug when using default image per page settings.

**Comment by brazenvoid** [comment]
I have seen this issue but for me it has few differences. 

As Gelbooru has a limit of ~23k for search results, I fleece its database with precision (haha) which ends up in 10-20 tag searches, including the most impacting blacklisted tags.

For one it happens when I am searching with long search strings with many tags, then grabber forgets to reset the page count when I change the search string.

Any subsequent queries will then never reset the page count.
