### ISSUE TITLE
How to restore to previous session?

### ISSUE THREAD

**Issue by YukiSakuma** [Bionus/imgbrd-grabber#2118]
I have many tabs open and downloads in the downloads tab BUT I exited Grabber cleanly so when I opened Grabber again it treats it like it's the first time opening it, no last tabs/download, so I found there is an option that when you open Grabber it will open the last session but that's only AFTER the fact. Is there any way to restore it to the previous session where it has my last tabs and downloads? Is there a previous restore session file that still salvageable that has my many tabs/downloads?

**Comment by shiosakun** [comment]
In Options, in "General", there's an option that says "At Start"; by default it says "do nothing", but there's the option "Restore last session". I hope I could help you

**Comment by Bionus** [comment]
> Is there any way to restore it to the previous session where it has my last tabs and downloads? Is there a previous restore session file that still salvageable that has my many tabs/downloads?

Not if you re-opened it, as they would have been overwritten. You can always check in the settings folder but that's very unlikely:
```
C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber
```
* Downloads: `restore.igl`
* Tags: `tabs.json`

**Comment by YukiSakuma** [comment]
Yeah I did check and they have been overwritten, it's really frustrating to have lost it and start over, can I suggest make the "Restore last session" to be default instead in future releases, so any new users wouldn't have this problem.

**Comment by brazenvoid** [comment]
Yes, it is extremely jarring to find out that all your downloads are gone in the next session. Or perhaps just make downloads survive beyond sessions.
