### ISSUE TITLE
Separate images based on it's extension?

### ISSUE THREAD

**Issue by shiosakun** [Bionus/imgbrd-grabber#2119]
Is it possible to separate images while you download it based on it's extension? I mean, for example: If it's png, go to "/PNG" folder. I tried to use the "Conditional filename" function, but honestly I don't know how to use it.

**Comment by Bionus** [comment]
You can just use `%ext%` in your filename to create a directory:
```
%ext%/%md5%.%ext%
```

See the [Filename docs](https://bionus.github.io/imgbrd-grabber/docs/filename.html) for more details.

**Comment by shiosakun** [comment]
and if I want to grab only one speciffic extension? I mean, every image goes to "x" folder, unless it's extension ".png", goes to another. Sorry for the question, being honest, the documentation is way to hard to understand for me u.u
