### ISSUE TITLE
Monitors Tab empty 

### ISSUE THREAD

**Issue by SomeRandomDude870** [Bionus/imgbrd-grabber#2120]
**Bug description**
I would assume that in the Monitors Tab there should be some entries, well there are none. The Textfield is completely empty.
It DOES download searches I have defined in Favorites.
The stop/start button does work.

**Steps to reproduce**
Well, when I add Monitors in the Favorite Tab, nothing gets added to the Monitor Tab. Restart does not change this.

**Expected behavior**

When I add Monitors in the Favorite Tab, I would assume that I will see the monitored searches in the Monitor Tab.

**Context**

There are no errors in the logs.

**Screenshots**

**System information**

- OS: [e.g. Windows 10 Pro
- Grabber version: 7.3.2x64
**Additional context**

Add any other context about the bug report here.

**Comment by Armored-Dragon** [comment]
I would like to add that I also have this issue.

I have only tested this on e621.net

>It DOES download searches I have defined in Favorites.

I don't quite understand exactly what is meant by this. Assuming this means that it is possible to download posts with the search also defined in the "Favorites" page, that also works for me.

**Steps to reproduce**
I have followed "Automatically download a favorite" from [https://bionus.github.io/imgbrd-grabber/docs/favorites.html](https://bionus.github.io/imgbrd-grabber/docs/favorites.html).
Nothing gets added to the main windows "Monitors" tab, and nothing ends up being downloaded.

- OS: Manjaro Linux x86_64 (Distribution release 20.1)
- Grabber version: 7.3.2 (x86)

Something I have noticed is that it will sometimes request unfulfillable requests (response is empty).
I have played with the "monitors.json" and "favorites.json" and found that I could almost get some functionality back with a touch of work. I took one of my favorite's "monitor" object and shoved it into "monitors.json" and it listed itself in the "monitors" tap in-app.


**Files:**
[main(.log).txt](https://github.com/Bionus/imgbrd-grabber/files/5222451/main.log.txt)
[settings(.ini).txt](https://github.com/Bionus/imgbrd-grabber/files/5222452/settings.ini.txt)

**Comment by yami-no-tusbas** [comment]
In fact the Monitor into the favorite, is a leftover from the pas, before the monitoring tab existed. It has been keeped for thoses who had to make the transition.

From now, you're supposed to click on the "Monitor" button in the bottom to add a monitor, then you can right-click it and edit it. And by the way, the documention is not up to date too. Favorite is nothing more now than a way to identify what you like and having a fast way to search them. (with the favorites tabs on the right of the search screen.)

**Comment by SomeRandomDude870** [comment]
lol, there is indeed a Monitor button.
Never saw this one before.
Most likely because I mostly use the Favorite tab to search something. Wish it would be more obvious.
Thanks!
