### ISSUE TITLE
Instance is stuck at 99% 

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#2122]
Grabber will sometimes stop its current instance at 99%. I don't know how to replicate it. There are no issues with my Internet or storage devices. I think it might have something to do with some sources that were taken away because I'm using it. I'm using version 7.3.2.

![1](https://user-images.githubusercontent.com/54746927/92833615-53f15880-f3d9-11ea-8fb9-53f91feb09da.png)

**Comment by pencilbook** [comment]
I think I know why it's happening. When the site doesn't load at all, it'll cause the instance to get stuck at 99%

**Comment by brazenvoid** [comment]
> I think I know why it's happening. When the site doesn't load at all, it'll cause the instance to get stuck at 99%

Perhaps that happened for you but for me when the site does not work, grabber proceeds to complete the whole batch in an instant. I use a VPN to access to these sites without it, they can't be accessed. So this behavior is something that I can simulate with a flip of a button.

**Comment by pencilbook** [comment]
I'm doing it over a VPN too... maybe it happens when our connection drops at coincidental moments as grabber tries to grab the next URL?

**Comment by pencilbook** [comment]
I'm doing it over a VPN too... maybe it happens when our connection drops as grabber tries to grab the next URL and then it stays at 99%?

**Comment by yami-no-tusbas** [comment]
When this happen, the best solution is often to pause the unpause the batch, or else grabber will just stay stuck, it happen when you lost connection on a query, etc.

You can see what happened in the log tab if activated, most of the time you will see that it is stuck on a receiving page or things like that. But pause->unpause work in a lot of cases.
