### ISSUE TITLE
Dropdown Picker Crash

### ISSUE THREAD

**Issue by ObscenityIB** [Bionus/imgbrd-grabber#2129]
**Steps to reproduce**

1. Go to 'Tools'.
2. Click on 'Options'.
3. Click on 'Save'.
4. Click on 'If an image yields multiple files'.
5. Select 'Hard Link'.
6. Click on 'OK'.
7. See mouse wheel spin.
8. Crash.

**System information**

- OS: Windows 10.0.18363.1016
- Grabber version: 7.3.2 x64

**Comment by yami-no-tusbas** [comment]
I have noticed that you just have to wait after changing on of thoses droppick. I you rush, you'll make windows think the app is crash, but it is not, it is just slow.

**Comment by ObscenityIB** [comment]
> 
> 
> I have noticed that you just have to wait after changing on of thoses droppick. I you rush, you'll make windows think the app is crash, but it is not, it is just slow.

i waited 5 minutes after selecting the dropdown before pressing ok
i pressed ok and it spun and crashed again

not froze,  crashed, theres nothing to wait for
