### ISSUE TITLE
Colons Disrupt Blacklisting

### ISSUE THREAD

**Issue by omegarunner1** [Bionus/imgbrd-grabber#2132]
**Bug description**

There's an issue with the Blacklist Function where including any tag with a colon in it, by which I'm referring to this : will cause the blacklist to blacklist every single image in a given booru. So far, I've only tested this on rule34.xxx but I don't see any reason why this wouldn't apply to the others. To be honest, I don't know when this started because this wasn't always the case but this causes a two issues. The first is that every image will be blacklisted, and the second is every image already downloaded will be included in the blacklist fixer.

For regular tags, this is primarily a non-issue. While certain tags that start with : can't be blacklisted this way, that's unavoidable with this glitch but it's also not a huge problem overall. You can sidestep the issue with regular tags by placing an * in place of a : so that it works fine. The issue arises if you want to do a blacklist based on info specific tags like md5:, score:, etc. 

**Steps to reproduce**

1. Go to 'Options Panel'
2. Click on 'Blacklist'
3. Scroll down to 'Add tag with the : symbol in the name.'
4. Load any random search without that particular tag included.

**Expected behavior**

Whatever you searched for should have one of two results: either no images will show up if you enabled "Ignore Blacklisted Images" in the Blacklist tab. Or images should show up as intended if the prior setting has not been enabled but every image will bring up the dialog asking you if you wish to open the blacklisted image.

**Context**

* Provide your `main.log` file to see if any obvious error occured.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occured during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

If applicable, add screenshots to help explain your 
[main.txt](https://github.com/Bionus/imgbrd-grabber/files/5278312/main.txt)

problem.

**System information**

- OS: Windows 7
- Grabber version: 7.3.2, reproducible on 6+

**Additional context**

My settings are not abnormal. I load the maximum number of images per page, I don't use any tokens, I have fairly standardized naming conventions, and I haven't adjusted any settings that don't image image results. I have a huge blacklist but this doesn't seem to affect the problem. It seems the problem only occurs with the : symbol. I have attempted replication with other symbols such as . , ; ', none of these seem to reproduce the error. It seems exclusive to the : symbol. The log file I uploaded is in .txt format due to modification. I removed a huge number of empty space to reduce the file size so that it could be uploaded but nothing of note was removed outside of that.

Upon Testing, this doesn't seem to be an issue on Windows 10.

**Comment by Bionus** [comment]
Do you reproduce the issue on the nightly release as well?

Also, your log seem to be from after re-starting the program as it's quite empty.
After doing a search, it should contain lots of "image blacklisted, reason: XXX" or similar normally.

> Upon Testing, this doesn't seem to be an issue on Windows 10.

I personally can't reproduce, but I'm on Windows 10.
Are you saying that this issue only occurs with Windows 7? That's very strange. I'll see if I have a Win 7 machine somewhere 🤔 

![image](https://user-images.githubusercontent.com/882719/94587978-9cd35900-0283-11eb-99d8-1228d7721857.png)

**Comment by omegarunner1** [comment]
To answer your question, I do not know if this applies to nightly builds as I don't tend to use those. I prefer to use stable releases. Secondly, no this doesn't seem to be a problem on Windows 10. There is another facet to this within the blacklist fixer in which it make register those tags as blacklists that I've also seen on Windows 7, that has not been tested on Windows 10. However, yes, any : whatsoever in the blacklist will produce the issue in Windows 7 it would seem. Windows 10 does not seem to produce that issue, however. Also, the log I posted is incredibly reduced as the full log will not fit onto Github, it's just too large. Here's a google drive link instead. https://docs.google.com/document/d/1ABKn1NCK6Tg-KTQo1W2e44lvpqSm9_R5NEskbW3Dg3A/edit?usp=sharing

Hope this helps a bit.

**Comment by AkatsukiiDesu** [comment]
I was able to reproduce this issue on the latest nightly. All I did was add the following to the blacklist field:

test:

Someone was having issues with the following blacklist: mao_mao:_heroes_of_pure_heart

**Comment by kaizokupuffball** [comment]
I can reproduce this myself on Windows 10. 
Reproduced by adding "ram_(re:zero)" to blacklist.
The tag blacklisted turns red.

**Comment by S0NGER** [comment]
Can confirm this still is happening in the recently released v7.6.1. Brand new installation.

Reproduceable by adding any tag with a colon (`:`) in it. Line turns red. Searches no longer return any results, stating `Possible Reasons: All Images Filtered`.
_**Shown here:** https://user-images.githubusercontent.com/78628049/131439098-7bfe0244-c9ad-4ccc-9014-985f97c04502.mp4_


### **Potential (Client-Side) Fix Found**
doubling the colon (`::`) will give the desired result, so writing `american_dragon:_jake_long` as `american_dragon::_jake_long` will correct the blacklisted tag, turning it black instead of the erroneous red.}


Searching resumes as normal, with the blacklisted tag no longer showing
_**Shown here:** https://user-images.githubusercontent.com/78628049/131439045-ffd55334-7e56-4909-b9b1-bd17bbe9c9e8.mp4_


_I'm not sure if this fix has already been listed anywhere, but as I saw the issue was still open, decided to post it for those like me who were looking for it._

**Comment by omegarunner1** [comment]
Sorry about that, I thought I had closed it but I guess I didn't. Yeah this was corrected a few versions ago so the only way it wouldn't be solved if it broke again at some point. But I haven't seen it so somebody else would have to open.
