### ISSUE TITLE
Load Saved Sources When Selecting Favorites

### ISSUE THREAD

**Issue by flaccidbagel** [Bionus/imgbrd-grabber#2135]
**Is your feature request related to a problem? Please describe**

I'm not entirely sure if this is a feature request or a bug report, but when loading a favorited search, the search is performed with the currently selected sources.

For example, if a favorite is saved from a search with only Pixiv enabled, but you then attempt to load that favorite while you have a different source selected, such as Twitter, the newly opened favorites tab attempts to search on Twitter rather than Pixiv. If you're saving favorites from multiple sites, it becomes somewhat cumbersome to access them all.

**Describe the solution you'd like**

It would be nice if whenever a favorited search is selected, it attempts to load that tab with the sources enabled that it was saved with. 

For example, if I favorite "Pikachu" with Pixiv selected as the source, I would like the program to remember which source was selected. Then, even if I have say, Twitter selected as the source currently, if I click "Pikachu" from my favorites on the left sidebar, I'd like it to perform that search with the Pixiv source. 

**Describe alternatives you've considered**

It appears that this kind of behavior is already present to a degree, as I can select the source to use IN the favorites tab itself. However, this view is a bit awkward, and appears to be more for monitoring only new images instead of browsing all of the images that meet the search criteria. It also appears that this has to be manually set for each favorite, instead of it automatically using the sources selected at the time it was favorited.

**Additional context**

![image](https://user-images.githubusercontent.com/34853221/94769211-801c4b80-037f-11eb-8952-7147b2945169.png)

In this example image, "pikachu" was saved with Pixiv as the selected source. I also selected Pixiv as the source to use for this search in the favorites tab. However, when I click pikachu from my favorites on the left, it opens a new tab and attempts to search on the currently selected sources, Safebooru and Twitter, instead of Pixiv.

**Comment by Bionus** [comment]
Indeed, the feature to edit sources for a given favorite was added after the favorites were introduced, and as such were missing this. It makes sense to use the active source as "default" when adding a favorite, as some tags don't make sense on some sources, so they're linked to their original source.

I just pushed the change 👍
