### ISSUE TITLE
Nightly just rollback 3 years ?

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2136]
https://github.com/Bionus/imgbrd-grabber/releases/nightly

No release anymore...

**Comment by Bionus** [comment]
Yes that's because the build is broken for a while:
https://ci.appveyor.com/project/Bionus/imgbrd-grabber

I'm working on fixing it but haven't had much success

**Comment by yami-no-tusbas** [comment]
Yeah still strange behavior of github I assume, take your time, just wanted you to be aware of the issue.

I mean, ok it's broken, but why regress back tree year prior, and not just at the last "working" nightly, really a strange thing.

Since you're on it, and I know it'll be fixed i'll close this issue.

Continue your good work !

**Comment by Bionus** [comment]
Fixed:
https://github.com/Bionus/imgbrd-grabber/releases/nightly
