### ISSUE TITLE
help with %search%

### ISSUE THREAD

**Issue by srcdecay** [Bionus/imgbrd-grabber#2138]
I just started using this program and I'm having an issue with automatic directory naming.

For save path I have tried `c:\images\%search%` (also search_1, etc) to set my download location to the tag I searched for.  What's happening is it's saving to `c:\images\%search%` rather than, say, c:\images\witch

When naming files, `%character%_(%artist%)_%md5%.%ext%` works great.

I could be missing something obvious.  Any help?  Thank you.

**Comment by Bionus** [comment]
Tokens are only allowed in the "filename" part.

So in your case, you would want to use:
* Directory: `c:\images`
* Filename: `%search%\%character%_(%artist%)_%md5%.%ext%`

If there's a `/` or `\` in your filename, it will create sub-directories automatically.
