### ISSUE TITLE
Download video files as mp4 instead of webm from rule34.xxx

### ISSUE THREAD

**Issue by thrustaway** [Bionus/imgbrd-grabber#2139]
On the site rule34.xxx when viewed in a browser, embedded videos are in the format of webm, though they often suffer from compression and significant loss of quality. If one uses the 'download' button provided by the embedded player, the webm file is played, _**but**_ in the url the file extension can be changed to mp4 instead, and a version is shown with far less compression negatively impacting it. 
If the post's webpage's source is viewed, the html lists both webm and mp4 versions as sources to the video player (not sure if that matters, but it might be useful information).

Grabber currently acquires the compressed webm version if instructed to perform a download, however I imagine the mp4 version would be universally preferred. Is there a way to change this? This is sort-of a feature request, but there might be a way to achieve this within the application already that I'm unaware of.

**Comment by Bionus** [comment]
This comes from an issue on rule34.xxx API side.

For MP4 files, they return the `webm` URL as the `file_url` (i.e. the original file):
https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=video

Gelbooru, on what rule34.xxx is based (they use the same engine), does not have this issue:
https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=video

I'll see if Grabber can automatically detect the `mp4` tag and update the URL manually.
