### ISSUE TITLE
Furaffinity & equibooru doesnt download

### ISSUE THREAD

**Issue by SIREN587** [Bionus/imgbrd-grabber#2142]
**Bug description**

CAnt download anything from the above sites with the latest program version

**Steps to reproduce**

Try to download any search from those sites doesnt work

**Expected behavior**

to download images

**Comment by yami-no-tusbas** [comment]
https://www.furaffinity.net/ doesn't seem to run any supported booru types.
https://equibooru.tk/ seem to be on it's own thing, not supported by grabber.
this https://callista.su/equine/booru/post/list "equibooru" can be added on shimie model, you have to change some referer, site for thumbnail, page for downloading image.

You can always ask Bionus to add support, if possible.
