### ISSUE TITLE
Nhentai, way to reverse search results from oldest to newest

### ISSUE THREAD

**Issue by SvyraCosmix** [Bionus/imgbrd-grabber#2144]
I am on version 7.2.0 all I was wondering is if there is a way to switch the search results from newest to oldest to oldest to newest on nhentai. I am naming them this way:

%count:length=6% - (%gallery.id%) - %md5%.%ext%

and then I do a search for example I'm doing 

trap english -breasts uploaded:>=2193d

I am starting with the oldest doujin first but within the uploaded range 6y and older it'll still download the results from newest to oldest but I just wanna know if there is a way for the program to flip the results from oldest to newest so that it downloads doujin ID:162 then 183 then 198 and so on as an example, oldest to newest.

**Comment by Bionus** [comment]
I don't think their API or website allows this, so Grabber wouldn't be able to do that as is.
The only sorting allowed on NHentai, AFAIK, is "recent" and "popular". 🤔
