### ISSUE TITLE
No results for rule34.paheal

### ISSUE THREAD

**Issue by ZephyrFaiz** [Bionus/imgbrd-grabber#2155]
Recently i had a problem where grabber wasnt able to get or download all the images under a tag from rule34.paheal. But now it just straight up gets nothing from rule34.paheal. If I search up a tag, lets say the artist reit, even though on the site theres a 1000+ images with reit tagged, nothing appears on rule34.paheal, it lists it as 'No result'.

**Comment by Bionus** [comment]
Note that tags are still loaded as shown in issue #2165.
