### ISSUE TITLE
Being able to have different Destination Names for different sources

### ISSUE THREAD

**Issue by KeyboardCoomer** [Bionus/imgbrd-grabber#2156]
Hello, love the software so far and love the robustness of it. Something I've been looking to try and do is have different *Destination Name*'s for when I'm dealing with different sources. 
Some websites have all their images stored in folders, while some are just unorganized image dumps that make the use of %md5% a must-have. Not having the ability to have different *Destination Name*'s for each source, forces users to have to ensure that they don't accidentally download several hundred photos before they realize that their *Destination Name* is wrong.

TL;DR
>Whenever I'm downloading from multiple sources, I would like to be able to have different *Destination Name*s for different sources.

Examples for what I put into the *Name* boxes for differing sources:
>>nhentai.net (or other gallery-based sites)
>>%website%/%search%/%gallery.name%/%filename%.%ext%
>>
>>Everything else
>>%website%/%search%/%artist%/%position%.%md5%.%ext%

I would be fine with using conditional statements, or something similar, to switch between what's being put into the *Name* part of the *Destination* folder, based on different criteria.

But ideally, I would like to have the ability to add additional *Name* boxes below the existing *Name* box, and be able to dictate which source goes to which *Name* box.

**Comment by Bionus** [comment]
I know this is a very late answer, but that can be done pretty easily with conditional filenames.
You can use `website:nhentai.net` as "condition", and then use whatever filename/directory you want for that source.

It also works with in-filename conditionals, but as you said that's much more verbose so I don't recommend it.
