### ISSUE TITLE
downloading as ".tmp" files

### ISSUE THREAD

**Issue by CH4SSEUR** [Bionus/imgbrd-grabber#2162]
**Bug description**

all downloaded images end with "original extension.tmp" extension

example:
 name_of_the_image.jpg.tmp
 name_of_the_image2.gif.tmp

**Steps to reproduce**

1. search for something
2. Click on "get all", "get this page" or "save as" it dosen't matter at the end all downloaded images end with .tmp extension

**Context**
Log, settings and a screenshot in zip file down
[files.zip](https://github.com/Bionus/imgbrd-grabber/files/5462572/files.zip)

**System information**

- OS: [Windows 10]
- Grabber version: [7.3.2]

**Additional context**

its not a big problem for me, i use a programme called "Advanced Renamer" to remove the .tmp extension to all images at once

**Comment by yami-no-tusbas** [comment]
ok I red the logs, first you can try to change permissions on your "`G:\Video\Doujins\Collections\`" folder and ti's subfolders to give write access to the program. Or run the program as administrator right maybe it'll help. I had this problem in the past, the first solution should be the good one. I tried your request on rule 34 for "aidan" and it worked fine on my end using nightly version (but should work on regular too since this seems permission related as log suggest.)

If this solve the problem feel free to close the issue, if not bump it up

**Comment by CH4SSEUR** [comment]
thank you @yami-no-tusbas for the reply 

i tried everything you said plus couple more tricks, sadly nothing worked 
i changed the permissions so anything can write to the folder but the log still says access denied to the folder, 
i even changed the download folder to my SSD, + running the programme as administrator didnt work.

i agree with @yami-no-tusbas that it seems permission related problem, but i dont understand i'm on admin account, i set the folder to full control by the user (read/write/modifications...etc), running the programme as administrator , disabled antivirus and firewall for some reason.
i'm lost i dont know how to fix it any suggestion are welcome.

**Comment by CH4SSEUR** [comment]
i found the problem and fised it
so in the: `options/save/filename` it was like this: `%md5%.%name%`
and in the interface of the programme the name wasn't matching the name in the option it was like this: `%md5%.%ext%`
all i had yo do is change the name in the options to `%md5%.%ext%` and done!
here is a screenshot:
![Screenshot_1](https://user-images.githubusercontent.com/73677364/97732433-d1cb0980-1ad6-11eb-962e-12baaf0177e7.png)

**Comment by Bionus** [comment]
I'm re-opening in case someone else has the same issue.

Glad you found the root cause!
There's definitely an underlying bug as those two settings should either be in sync or totally independent, but seems like they're not. I'll investigate!

**Comment by CUBESSource** [comment]
I'm still getting the TMP issue. Changing both to %md5%.%ext% ain't working.

**Comment by Bionus** [comment]
Do you see anything in your logs?
What are your "commands" settings set to? Seems like invalid commands can cause TMP files not to get renamed properly once the download is finished.
