### ISSUE TITLE
Not downloading correctly on E-Hentai

### ISSUE THREAD

**Issue by SvyraCosmix** [Bionus/imgbrd-grabber#2182]
The problem I am having is when I start a download by gallery name 

%gallery.name% (%gallery.id%)/%position% - %md5%.%ext%

It'll begin creating folders for each comic of course but when clicking into a comic on the website in browser each page by default shows 40 pages then another 40 on page 2 and so on and it does something odd when I set it to download in the program I use this search

furry english yaoi -"western imageset" 

and gives 3000 some results when I select get all and start the download it'll create each folder for each comic of course but will STOP at the 40 limit like on the website then go onto the next comic then after awhile it'll come back to the comic and continue downloading page 2 the next 40 for that comic the problem with that though is it will mess with the position number and double some of them as you will see in the image
![Capture](https://user-images.githubusercontent.com/19334444/99368105-64fa9200-2880-11eb-955f-cf2aff4b8dff.PNG)

**Comment by SvyraCosmix** [comment]
I don't wanna have to go in and sort by date modified and renumber them for every folder, is there a way to fix this or name them another way so this doesn't happen?

**Comment by SvyraCosmix** [comment]
Oh also side note the length parameter %position:length=3% for example doesn't work it's still numbers them 1, 2, 3, 4... instead of 001, 002, 003... like it's supposed to

**Comment by sstabeler** [comment]
One workaround that occurs to me- if not necessarily particularly satisfactory- would be to download each gallery separately, instead of ding a batch download of the search,

**Comment by SvyraCosmix** [comment]
> One workaround that occurs to me- if not necessarily particularly satisfactory- would be to download each gallery separately, instead of ding a batch download of the search,

Ah, one of Captain Obvious's students I see :D

**Comment by SvyraCosmix** [comment]
> One workaround that occurs to me- if not necessarily particularly satisfactory- would be to download each gallery separately, instead of ding a batch download of the search,

But yes that's what I started doing since I started noticing that 80 percent of the doujinshi/comics, like all doujinshi/comics, were trash anyways, lmao

**Comment by sstabeler** [comment]
It might be obvious, but you'd be surprised at how many people overlook the obvious. 

Also, it does actually affect why you are getting the wrong position numbers. the position token gives you the position in the **results list** or **gallery**, so the way to get the position in the gallery actually **is** to download the galleries separately from what I can tell.
