### ISSUE TITLE
Scaling issues (or, HDPI needs more love)

### ISSUE THREAD

**Issue by thany** [Bionus/imgbrd-grabber#2186]
**Bug description**

Grabber needs some more love on HDPI screens.
Since HDPI has been getting more and more popular, and have been for a while in Macs (although this issues is about HDPI on Windows), it would be nice if the UI at least would look usable.

Below is a screenshot from an XPS15 laptop that has a 4K screen zoomed in the display settings to 200%. All other scaling settings are left to their defaults, and the program is not started in any kind of compatibility mode.

![image](https://user-images.githubusercontent.com/152227/99950521-ebc9d600-2d7c-11eb-8fd3-a40fc8c14841.png)

Next is a screenshot of a fresh install in a remote desktop session, again 4K resolution scaled to 200%.

![image](https://user-images.githubusercontent.com/152227/99950597-09973b00-2d7d-11eb-80bb-06bf5773a1f4.png)

I'm not sure why the second looks so different, and so much less usable. I guess I should try some compatibility settings, but then why do I *not* need those in the first scenario?

Anyway, I think some testing will come a long way. And just to remind everyone: you don't neccesarily need HDPI hardware to test for it. You can set any normal-DPI screen to zoom=200%, or any arbitrarily high zoom. It will just look strangely big 😀

**Steps to reproduce**

1. Set zoom to 200%(-ish) in the display settings.
2. Log out and back in, just to be safe. Shouldn't be neccesary, but things looked nicer when I did.
3. Start Grabber.

**Expected behavior**

For a free program, I certainly don't expect a 10/10 designer UI. But it's nice to have readable labels, buttons that aren't too tiny to hit, and properly proportioned windows & layout.

**Context**

* Not attaching `main.log` because it's unlikely to be relevant.
* Not providing `settings.ini` because it was literally installed moments ago, and settings have been left to their defaults completely.

**Some more screenshots**

About:
![image](https://user-images.githubusercontent.com/152227/99951212-005a9e00-2d7e-11eb-867f-5131a1d89228.png)

Settings:
![image](https://user-images.githubusercontent.com/152227/99951260-136d6e00-2d7e-11eb-9a7f-0b8a29c51da3.png)

Sources:
![image](https://user-images.githubusercontent.com/152227/99951281-1ec09980-2d7e-11eb-9173-f10e15b40e43.png)

I think this requires maybe a few small tweaks to fix the most pressing scaling issues. Maybe save the rest for later, when there's more time for GUI fixes.

**System information**

- OS: Windows 10 version 20H2
- Grabber version: 7.3.2

**Comment by thany** [comment]
Just to be clear: you don't neccesarily need a 4K monitor, or other HDPI screen, to test this problem. You can happily set the zoom level of any ol'monitor to something above 100%. Just saying, in case that's the reason this problem hasn't gotten any response.

**Comment by Bionus** [comment]
Should now be solved in [v7.7.0](https://github.com/Bionus/imgbrd-grabber/releases/tag/v7.7.0).
Also see issue #2508 for more details / screenshots.
