### ISSUE TITLE
Rule34 Paheal - Tag with "/" does not work properly in search

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2195]
**Bug description**

On Rule34 Paheal, tags with "/" in between do not work properly; same content is repeated for all pages.

**Steps to reproduce**

1. Search Fate/Requiem
2. Click next
3. Same content will be presented in all the pages

**Expected behavior**

Content is different on all pages. The site works with these fine.

**System information**

- OS: Windows 10
- Grabber version: Nightly

**Comment by Bionus** [comment]
Indeed, seems like some characters need to be encoded for Shimmie:

Shimmie source  code for reference:
```php
/**
 * Kind of like urlencode, but using a custom scheme so that
 * tags always fit neatly between slashes in a URL. Use this
 * when you want to put an arbitrary tag into a URL.
 */
public static function caret(string $input): string
{
    $to_caret = [
        "^" => "^",
        "/" => "s",
        "\\" => "b",
        "?" => "q",
        "&" => "a",
        "." => "d",
    ];

    foreach ($to_caret as $from => $to) {
        $input = str_replace($from, '^' . $to, $input);
    }
    return $input;
}
```
