### ISSUE TITLE
filename confusion

### ISSUE THREAD

**Issue by LungLung798** [Bionus/imgbrd-grabber#2196]
I just downloaded Grabber for my computer but it will not let me download anything due to an issue with the filename. It says "Your filename doesn't ends by an extension, symbolized by %ext%! You may not be able to open saved files.". I don't know what to do to fix this. Please help.

**Comment by AkatsukiiDesu** [comment]
Hi there,

What does your file naming look like? I believe the default is %md5%.%ext%.

**Comment by LungLung798** [comment]
funnily I think i just figured out the issue. Nevermind.

**Comment by brazenvoid** [comment]
1. Open Grabber
2. Open Tools menu
3. Click Options
4. Expand Save option in the left pane
5. Click on Filename
6. Ensure that the filename shown in the Default text box has .%ext% at the end
