### ISSUE TITLE
Can't get to download all the artists from Twitter

### ISSUE THREAD

**Issue by Azuriye** [Bionus/imgbrd-grabber#2197]
So I have like 256 accounts on the monitor tab, I've tried to set the lastCheck date all the way back to the Year 2000 and at the moment I'm running the latest nightly version where retweets:no has been fixed. Problem is that now when I start back the Imgbrd Grabber it fails to download all 256 accounts at most it downloads 161 accounts kept retrying no luck. There's a catch to this every folder I check in has at least 4-5 images if not less. Could it be that there is something got to do with images limit? Totally clueless on why it's behaving like this and so far it's been happening only with the Twitter accounts I've added in the monitor's tab.

**Comment by Azuriye** [comment]
For some reason, when I manually type in the artist name and click Get All and set the Images Limit to 1000 or more it downloads in more pictures compared to 5 or 6, strange.

**Comment by oilpooh** [comment]
Excuse me 

> So I have like 256 accounts on the monitor tab, I've tried to set the lastCheck date all the way back to the Year 2000 and at the moment I'm running the latest nightly version where retweets:no has been fixed. Problem is that now when I start back the Imgbrd Grabber it fails to download all 256 accounts at most it downloads 161 accounts kept retrying no luck. There's a catch to this every folder I check in has at least 4-5 images if not less. Could it be that there is something got to do with images limit? Totally clueless on why it's behaving like this and so far it's been happening only with the Twitter accounts I've added in the monitor's tab.

Did you solve it?

**Comment by Azuriye** [comment]
> Excuse me
> 
> > So I have like 256 accounts on the monitor tab, I've tried to set the lastCheck date all the way back to the Year 2000 and at the moment I'm running the latest nightly version where retweets:no has been fixed. Problem is that now when I start back the Imgbrd Grabber it fails to download all 256 accounts at most it downloads 161 accounts kept retrying no luck. There's a catch to this every folder I check in has at least 4-5 images if not less. Could it be that there is something got to do with images limit? Totally clueless on why it's behaving like this and so far it's been happening only with the Twitter accounts I've added in the monitor's tab.
> 
> Did you solve it?

Not really, I've just scrapped that idea and decided to monitor newer images instead not sure if it's an API limitation from Twitter or whether it's not configured yet properly...
