### ISSUE TITLE
Ratings should be considered tags.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#220]
```
What is your suggestion for the program?

It should be able to set the rating of an image (Explicit, Questionable, Safe) 
as a tag that folders can be named. When I attempt to do so, there is no 
failure report or anything like that, it just pretends it wasn't a token. If it 
can already do that I would appreciate some instructions.

What version of the product are you using? On what operating system?

v3.2.7 Windows
```

Original issue reported on code.google.com by `samrvinc...@gmail.com` on 7 Apr 2013 at 7:20

**Comment by Bionus** [comment]
The problem lies with the detection of the rating itself (you can use the %rating% token in filenames).
Please provide more details on which source and tag you're searching and I'll investigate, but I think it goes for another issue.
