### ISSUE TITLE
Android Version Suggestions

### ISSUE THREAD

**Issue by xodiack** [Bionus/imgbrd-grabber#2201]
**Is your feature request related to a problem? Please describe**

1- Having the save button be at the top of the screen rather than the button makes browsing/saving cumbersome.

2- When reaching the last image of the page 1, scrolling right does not load into the page 2, need to instead back out of the image and then load the next page before returning to the image by image view.
 
3- Some screens the phone's back button will exit the app rather than going back up a level. I so far only noticed this when choosing a source and being inside of its settings/edit window. Then when wanting to back out but having it minimize the application instead.
 
4- Lastly, possibly more a bug than a suggestion, source selection is not remembered upon reloading of the app. 

**Describe the solution you'd like**

1- Moving the menu bar to the bottom of the screen rather than the top, or having an option to choose where you would like it.

2-When on the last image of "page 1" scrolling to the "next image" would instead load "page 2" and bring you to the first image of that page.

3-using the phones back button should instead back you out of the screen rather than minimizing the app. I'm not 100% sure if its closing it entirely in this case or not. So far I've only noticed this on the "edit" screen of the sources. Not to be confused with the screen where you pick which source you currently wish to use.

4-Remember the last selected source, currently mine defaults to Danbooru regardless of what I changed it to or used last.

**Describe alternatives you've considered**

None currently, besides working around the issues/inconveniences described above.

**Additional context**

Grabber 7.3.2 (Android)
Samsung S10e
Android ver 10

Also a question: What does the hd/ld button on do?  I couldn't tell much of a difference when I was messing around with the app yesterday.

**Comment by Bionus** [comment]
1. Done. I added a new setting in "Interface" (off by default).
2. This is too big to be only one point of this ticket. But it's already in the roadmap (see issue #2147), as "infinite scroll / browse"
3. Fixed. I didn't find anywhere other than that window, but I made the back-button handling more generic just in case.
4. Done.

> Also a question: What does the hd/ld button on do? I couldn't tell much of a difference when I was messing around with the app yesterday.

It's to display the original full-size image instead of the "sample" image. You should see the difference if you zoom on the image (pinch / double tap) enough to see artifacts.
