### ISSUE TITLE
add support for Rule34.us

### ISSUE THREAD

**Issue by Thelockest** [Bionus/imgbrd-grabber#2205]
**Is your feature request related to a problem? Please describe**

No

**Describe the solution you'd like**

I would like for Rule34.us, to be added to Supported sites.

**Comment by sstabeler** [comment]
You do know you can just add it, right? It's literally just putting the site URL into the right place. (I know as I've already added to my own sites)

**Comment by Thelockest** [comment]
Tried to add this multiple times did not work. So tell me magic man where is the magic spot.

**Comment by sstabeler** [comment]
Ah, I just looked into it a little more, and I owe you an apology. The issue, it seems, is that rule34.us are using a modified gelbooru 0.1 installation, which is modified enough to make the source not work.  Specifically, from what I can tell the URL isn't valid as an input. I'm not sure offhand how difficult it would be to create a working source for it.
