### ISSUE TITLE
Possibility to set source priority on download list

### ISSUE THREAD

**Issue by Roshri** [Bionus/imgbrd-grabber#2219]
I tend to download all the art from specific artists and I scrape various sources to get all of it since not everything is uploaded everywhere, so I just click download all and that's it. The problem is some sources take longer to download due to traffic limits.

It'd be cool if I could set a global priority to download those sources last. Organizing the download list itself sometimes doesn't work because when I click on move to the bottom in two different items, the first one comes back to its original place, therefore ruining the list's order.

**Comment by yami-no-tusbas** [comment]
A solution could be using monitors, you can setup them one after another, each on a board, of group of boards, then grabber will every "x" time check them and get the new images. Or you can just make a job with the slower boards first, then uncheck them, check the others and add them to the job list, it should work too.
