### ISSUE TITLE
Removed Tags function doesn't work

### ISSUE THREAD

**Issue by Leeiio** [Bionus/imgbrd-grabber#2221]
**Bug description**

I have add a tag "ラブライブ!10000users入り" to the removed tags textarea, but the image filename still have this tag name.

**Steps to reproduce**

none.

**Expected behavior**

It should removed when I use %all% for the filename.

**Context**

none.

**Screenshots**

**System information**

- OS: Windows 10
- Grabber version: 7.3.2 nightly

**Additional context**

none.

**Comment by yami-no-tusbas** [comment]
you should look at : #2061 

> The "ignored" is for more special purposes, when you want to keep the tag in `%all%` but not in typed tokens. That can be the tags for annoying series where images will have multiple typed tokens meaning the same thing, such as "pokemon", "pokemon_red", "pokemon_blue", etc. You might want to keep all tags but if you use `%copyright%`, it will end up as "multiple" so for this you can use the "ignored" feature.

%all% is and will alway give you all the tags, even if ignored, that's what it is expected to do.

**Comment by Leeiio** [comment]
@yami-no-tusbas 
I use `Removed Tags` not `Ignored Tags`. You can have a look at my image.
![screenshot](https://i.loli.net/2021/01/06/bvnCHOYKok6J8lP.png)

**Comment by yami-no-tusbas** [comment]
true, sometimes I forgot thoses are different, sry.

**Comment by Bionus** [comment]
It actually works, but the separator is (was) " " instead of a new line, unlike "ignored tags" right under.
That's because it useds to be a one-line field, but was changed to a multi-line field a few weeks ago.

I just pushed a fix to accept either as a separator.
