### ISSUE TITLE
Only grabbing partial on pixiv

### ISSUE THREAD

**Issue by Wenn12** [Bionus/imgbrd-grabber#2222]
**Bug description**
Not sure if a bug or if Im just using wrong but when i try to grab anything on Pixiv I only get a fraction of the results. 

**Steps to reproduce**

1. Sign into pixiv
2. Search a user with "user:########" 
3. User has ~300 images grabber saves 35

**Expected behavior**

I expected that it would grab more.

**Context**

I couldnt figure out how to attatch settings but they were all default
[main.log](https://github.com/Bionus/imgbrd-grabber/files/5758619/main.log)

**Screenshots**

**System information**

- OS: Windows 10
- Grabber version: Latest

**Additional context**

Add any other context about the bug report here.

**Comment by aymanA123** [comment]
this used to happen to me .

try using this %search%/%position%.%ext% as your filename . and when you want to download from a user don't forget to bump up the max downloads to 1000 .
