### ISSUE TITLE
Cannot download from https://cripple.booru.org/

### ISSUE THREAD

**Issue by Kelhsy** [Bionus/imgbrd-grabber#2223]
I added https://cripple.booru.org/ as a source but it doesn't seem to work and returns as offline.
![error](https://user-images.githubusercontent.com/66084462/103449858-ea15fb00-4cb6-11eb-8763-1722967e4bd5.png)

**Comment by yami-no-tusbas** [comment]
simply add a user agent in the setting of the site, go to options for cripple.booru.org, then Headers, then add, then on name write : "**User-Agent**" and on Value put : "**Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0**" without quotation.
