### ISSUE TITLE
Rule34 Paheal only shows 70 images per page despite it was set to more than that (on Grabber Nightly)

### ISSUE THREAD

**Issue by Glasscrack** [Bionus/imgbrd-grabber#2226]
On the settings, I set the images per page on the source tab to be 1000. Normally on sites like Rule34.xxx, it would show at least 1000 images per page on whatever I'm searching on. On Rule34 Paheal however, it would only show 70.
Does it have something to do with the site itself or not? Currently using Grabber Nightly since I cannot find any sources with the default grabber.

**Comment by Bionus** [comment]
Not all sources allow to customize the number of images per page.
R34.paheal uses Shimmie IIRC, which does not allow it, so the number of results is fixed by the website (usually 42, in this case 70).

**Comment by Glasscrack** [comment]
> 
> 
> Not all sources allow to customize the number of images per page.
> R34.paheal uses Shimmie IIRC, which does not allow it, so the number of results is fixed by the website (usually 42, in this case 70).

Oh well. Thanks for the info
