### ISSUE TITLE
Download all pictures of the searched tag without having to go to different pages

### ISSUE THREAD

**Issue by Glasscrack** [Bionus/imgbrd-grabber#2227]
**Is your feature request related to a problem? Please describe**

Since I've used the program, it's been a hassle to download images on searches that yields more than a thousand pictures. Say I plan to download a tag/character/etc. with 3400 images. Even if I set the sources to show 1000 images per page, I still have to go through 4 pages and even then I have to wait for all images to load or risk having to restart the program since skipping to the next page without completely loading all pictures would make the program unable to load up any pictures at all.
At first, I thought the "Get All" button would do just that but unfortunately, it's not.

**Describe the solution you'd like**

If possible, have the option to download all images from that search with one button (at least with one source site) without having to go through different pages and click "Get Page". Using the example before, instead of having to venture to different pages just to download all of them, I could just click a button and all the images from that tag is now ready to download in the downloads tab.

**Comment by Hi-ImKyle** [comment]
The Get All button is what you want, it just queues the tag for download in the download tab. You just need to start it.

**Comment by Glasscrack** [comment]
> 
> 
> The Get All button is what you want, it just queues the tag for download in the download tab. You just need to start it.

Didn't realized it. Last time I tried it, it didn't download all of the files for some reason. Thanks
