### ISSUE TITLE
proceeding with session does not work if number of pictures exceeds a certain ammount.

### ISSUE THREAD

**Issue by DraGoran4** [Bionus/imgbrd-grabber#2228]
Settings set to "restore late session"

Expected behavior is after exiting grabber, on next start grabber restores session ( then on agreeing to continue where download left off , after clicking on download selected or download all and agreeing to the many images waiting time warning)  grabber continues the download where the program was exited.

Bug is, grabber does not do so, instead grabber shows up a "finished" window after agreeing to continue where to left off and after agreeing to the (you gonna download *number this will take a while) windows , as if the download was entirely completed with the ammount of pictures that was downloaded until now shown as  skipped and no failed downloads or anything, as if the download was sucessful, while actually it was not.

main log before resuming [main.log](https://github.com/Bionus/imgbrd-grabber/files/5775112/main.log)

main log after resuming and settings.ini

[Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/5775123/Grabber.zip)

![grafik](https://user-images.githubusercontent.com/17236196/103756570-d993b680-500f-11eb-88f5-866f2762b822.png)

![grafik](https://user-images.githubusercontent.com/17236196/103756601-e7e1d280-500f-11eb-939e-c6e89aada7c7.png)

![grafik](https://user-images.githubusercontent.com/17236196/103756658-00ea8380-5010-11eb-9f29-6e9c73b3bfb7.png)

![grafik](https://user-images.githubusercontent.com/17236196/103755763-9f75e500-500e-11eb-9e25-7225bbd9e0b3.png)

Clicking pause crashes grabber, clicking  close  , closes the window not crashing grabber, but the program still open with the restored session, which is not able to continue and reproduce the 1st and 2nd and 3d window on agreeing.

After grabber crashed on clicking pause, it restores last session, however when trying to download it starts to download pictures from new,

![grafik](https://user-images.githubusercontent.com/17236196/103758657-c7ffde00-5012-11eb-889f-37087499b048.png)

tag used ; gaping  imageboard chan.sankakucomplex.com
logged in with account.

**System information**
Win 10 64bit Home

Grabber version newest 

**Additional context**

Hard to test the ammount of pictures, however,  the  download where left off option worked when i exited the programm with a lower number of pictures (tested with 10000 pictures) what it looks like with the ? number(cannot determine at what number it does not work)  is shown at screenshot 3, pc shutdown after exiting or not does not affect the programs behaviour, the same problem occured if there is no shutdown between exiting and reopening the program.

**Comment by DraGoran** [comment]
bump
