### ISSUE TITLE
Option to save grouped images into folders

### ISSUE THREAD

**Issue by Autissima** [Bionus/imgbrd-grabber#2230]
**Is your feature request related to a problem? Please describe**

When downloading continuous things I.e. stories and such, it's a bit frustrating that the individual pages get saved all over the place.

**Describe the solution you'd like**

Option to, if an image yields multiple files, save them to a folder with the checksum of the first image

**Comment by Bionus** [comment]
What do you mean "grouped images"?
If you're talking about galleries, you can do that using `gallery.id` and/or `gallery.name` (see [Filename](https://bionus.github.io/imgbrd-grabber/docs/filename.html)).

You can also use filename conditionals (ex: `<%gallery.id%/>`) if your downloads mix "normal" images and galleries.
