### ISSUE TITLE
No results for Rule34 Paheal

### ISSUE THREAD

**Issue by ViolletXIII** [Bionus/imgbrd-grabber#2231]
![teste](https://user-images.githubusercontent.com/77258444/104146328-16adcf00-53a9-11eb-8fb1-3ed34b4dd045.jpg)

I can't load images from Rule34 Paheal, does anyone have a fix?

**Comment by Crimson119** [comment]
same here

**Comment by unithiz** [comment]
Same here, still not working.

**Comment by jamedom** [comment]
me too

**Comment by yami-no-tusbas** [comment]
Any news ? It work in nightly.

> [13:23:00.378][Info] [rule34.paheal.net][Html] Loading page http://rule34.paheal.net/post/list/1
> [13:23:00.698][Info] [rule34.paheal.net][Html] Receiving page http://rule34.paheal.net/post/list/1
> [13:23:00.750][Info] [rule34.paheal.net][Html] Parsed page http://rule34.paheal.net/post/list/1: 70 images (70), 10 tags (10), -1 total (10000), 500 pages (500)

Can we have the logs ?
