### ISSUE TITLE
Add tags to search for specific sources?

### ISSUE THREAD

**Issue by Autissima** [Bionus/imgbrd-grabber#2232]
Very sorry to ask so much recently, if there is a better place to just ask some possibly very idiotic questions, I'd be glad to move there...

Basically, I was wondering if it was possible to automatically add tags to a search for a specific source, f.e. to all tag searches on a source also add the tag "English".

Edit:
I was searching for this feature, but maybe someone else can help me here too, I want to download a collection of images which has a title, and would like to use this title as a folder name they get saved in to.
Like the %md5%.%ext% thing?

**Comment by yami-no-tusbas** [comment]
Knowing wich board your images are from could help us figure out. If you want to add something like english an all your requestion, you may wanna try "post filter", not the best but could work. But it is not source specific. For the title it depend on the boards and what tag type exist there. This sounds like doujins to me, maybe you would have to check a doujin downloader more specific.

**Comment by Bionus** [comment]
Since stale bot re-upped this issue, I just wanted to inform that this feature has been added in recent releases, in the source settings:

![image](https://user-images.githubusercontent.com/882719/213592307-adfb55c7-48ea-4671-87b3-f6053d235367.png)
