### ISSUE TITLE
Will Download Completely Random Files

### ISSUE THREAD

**Issue by Buhdaman** [Bionus/imgbrd-grabber#2233]
I've been using the grabber tool for a bit and just recently I notice that whenever I try to download something it will go and download a bunch of random pictures as well. Like I'll go and download something that only has 95 images and it will give me 400 extra photos and I did it a couple times and they look like they're the same photos each time. It worked like once and I thought it was because I had to download stuff to the same directory as it was installed but after I installed it to like 4 different places it still didn't work. Just found this out now by trying to show a video of it happening, I chose a download folder and it just started automatically downloading to the folder, I have no active downloads and it is still downloading.

https://user-images.githubusercontent.com/61641265/104309677-25bf7a80-5498-11eb-88f5-f44517c13a1e.mp4

I go and look up some random tags and then even before downloading it starts and is at like 200 before I start the 14 image download and when I'm done I have 300 files. (Edit, had to record again but showed the fact that it would start downloading before I even searched anything up. Already turned automatic download off and tried again but still had the same problem)

**Comment by raid-teyar** [comment]
i have the same problem as well

**Comment by yami-no-tusbas** [comment]
Sounds like monitors runnings, the log could be very usefull to help you.

**Comment by raid-teyar** [comment]
for me it doesnt happen very often so im okey

**Comment by yami-no-tusbas** [comment]
Can we have the logs ? Did you solve it by any ways ?

**Comment by theXerun** [comment]
I have the same problem. It downloads random images regardless of what settings I change, only skips blacklisted ones. I tried it on both on the latest nightly and on release with the same result. I'm not sure what could cause it.

Here are my logs:

https://ghostbin.com/paste/LHmI4

**Comment by yami-no-tusbas** [comment]
@theXerun that's because you have set a monitor (by accident I assume) : 

"[14:05:00.154][Info] Monitoring tick
[14:05:00.154][Info] Monitoring new images for '1girl' on 'Gelbooru'"

Go to the monitors tagbs, you should find an entry for 1girl, just right click then "remove" and you should be fine.

**Comment by RinMaru** [comment]
I've had this issue too but not as extreme. I can search for something and I'll find random images saved in my ing folder

**Comment by yami-no-tusbas** [comment]
> 
> 
> I've had this issue too but not as extreme. I can search for something and I'll find random images saved in my ing folder

Have you tried to look if there was a monitor running ? If not, in the option there an atomatic download under option -> save, it's a checkbox. You can uncheck it too.

**Comment by RinMaru** [comment]
It did and I deleted it. Been watching to see if it happens again
