### ISSUE TITLE
Right click save as, no longer processes filename correctly

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2234]
**Bug description**

Right click save as, produces a wrong filename which right click save, batch or single downloads do it correctly. My filename mask is: `%character% - %artist% - %id%.%ext%` which translates to `unknown - unknown - [correct id]` for all right click save as images. This happens for all sources.

**System information**

- OS: Windows 10 20H2
- Grabber version: Nightly

**Comment by yami-no-tusbas** [comment]
This could be the same as #2235 , gelbooru seem to have changed something and tags type don't load, if it was gelbooru you where using I suggest you go check the mentionned issue as I put a temporary fix

**Comment by brazenvoid** [comment]
As I said it is happening for all sources for me. Even Shimmie API sources are presenting the same issue. It corrects itself once I open the preview window and then use save as either from there or by right clicking the item.

**Comment by Bionus** [comment]
I'm surprised you say that this ever worked for sources that do not provide tag information directly (such as Danbooru or E621).
Gelbooru (and Shimmie AFAIK) doesn't, so this should have never worked even before the refactoring (2c9b71bdced1b715934444ed997b6fa22e22ec18).

I'll make a change to make it work (i.e. load detailed tags before opening the "save as..." window when necessary) though.

**Comment by brazenvoid** [comment]
Odd, I only noticed it recently. Regardless, thanks!
