### ISSUE TITLE
Something is slowing me down and make grabber not responsive.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2237]
**Bug description**

My settings.ini is slowing grabber down, don't know why. But after putting it back on a fresh install, the app just lagged a lot, and i can see my settings.ini is heavy compared to a blank one.

I wonder if this can be because of my ignored tag list that seems huge, assuming i'm slowed down while parsing a page, could it be linked ?

**Steps to reproduce**

1. Put my settings.ini
2. Launch grabber
3. Go from snappy Grabber to Wow that's slow Grabber !
4. Nothing seems wrong ion the logs

**Expected behavior**

A snappy grabber whatever my settings are ?

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/5832650/main.log)
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/5832644/settings.ini.txt)
Just loaded gelbooru.com, not even a search.

**System information**

- OS: Windows 10
- Grabber version: Nightly 1fe84600

Add any other context about the bug report here.

**Comment by Bionus** [comment]
> I wonder if this can be because of my ignored tag list that seems huge, assuming i'm slowed down while parsing a page, could it be linked ?

It might absolutely be the case, given a change introduced yesterday that can have a big performance impact (512db1a51f9fa003885df35b7885c9da4340acb4).
I'll try to push a fix ASAP.

**Comment by yami-no-tusbas** [comment]
Ok thanks a lot, I just tested copying settings and yeah, just after putting back the ignore list, it was slowed down ! I appreciate your work Bionus !

**Comment by yami-no-tusbas** [comment]
So I just tested 975102b0 and it was a bad idea, the fix doesn't seems to work in this version. It was somehow faster, but the app is not responding while parsing is occuring, and that's pretty annoying to stop a batch job while UI is lagging.

> [17:53:19.312][Info] Monitoring new images for 'xxx' on 'Gelbooru'
> [17:**53:19.322**][Info] [gelbooru.com][Xml] Loading page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=xxx
> [17:**53:19.898**][Info] [gelbooru.com][Xml] Receiving page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=xxx
> [17:**53:32.426**][Info] [gelbooru.com][Xml] Parsed page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=ijiranaide_nagatoro-san: 20 images (20), 0 tags (190), 597 total (597), 30 pages (30)

In fact if only the UI was not so laggy I wouldn't care, but you cannot do anything while a batchjob is running with that bug/problem.

Good luck working on it !

**Comment by Bionus** [comment]
So what you're saying is that there's an improvement, but it's still slower than before?
Now that's strange 🤔 

I'll have another go and do more benchmarks
How many lines / entries do your "removed tags" list have?

Also, are you sure about 975102b? That's from last year.

**Comment by yami-no-tusbas** [comment]
Yeah I failed the version number, "975102b0" is the right one I'm typing, it's right... github is removing the zero !

So just for comparison : 

Empty ignored tag : 

> [08:49:03.385][Info] Monitoring new images for 'something' on 'Gelbooru'
> [08:49:03.391][Info] [gelbooru.com][Xml] Loading page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=something
> [08:49:03.578][Info] [gelbooru.com][Xml] Receiving page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=something
> [08:49:03.613][Info] [gelbooru.com][Xml] Parsed page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=something: 20 images (20), 0 tags (381), 14075 total (14075), 704 pages (704)

parsing took : **0.035s**

Now with my list : 

> [08:54:45.439][Info] Monitoring new images for 'something' on 'Gelbooru'
> [08:54:45.443][Info] [gelbooru.com][Xml] Loading page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=something
> [08:54:45.622][Info] [gelbooru.com][Xml] Receiving page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=something
> [08:54:46.765][Info] [gelbooru.com][Xml] Parsed page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=something: 20 images (20), 0 tags (348), 4957 total (4957), 248 pages (248)

parsing took : **1.143s**

Well, don't know now it's fine, yesterday it was not, but yeah, seems this is fixed ! Considering I have 799 ignore and removed tag list, this is no bad at all. Only 0.0014s per tag !

I'll close the issue then.

**Comment by yami-no-tusbas** [comment]
I hate to re-open this, but now it is e621 that parse like a snail...

[12:49:26.509][Info] Batch download started.
[12:49:27.928][Info] [e621.net][Json] Loading page `https://e621.net/posts.json?limit=200&amp;page=1&amp;tags=gadget_hackwrench`
[12:**49:30.068**][Info] [e621.net][Json] Receiving page `https://e621.net/posts.json?limit=200&amp;page=1&amp;tags=gadget_hackwrench`
[12:**49:51.616**][Info] [e621.net][Json] Parsed page `https://e621.net/posts.json?limit=200&amp;page=1&amp;tags=gadget_hackwrench`: 200 images (200), 0 tags (1610), -1 total (-1), -1 pages (-1)
[12:49:51.620][Info] [e621.net][Json] Loading page `https://e621.net/posts.json?limit=200&amp;page=2&amp;tags=gadget_hackwrench`
[12:**49:53.776**][Info] [e621.net][Json] Receiving page `https://e621.net/posts.json?limit=200&amp;page=2&amp;tags=gadget_hackwrench`
[12:**50:15.422**][Info] [e621.net][Json] Parsed page `https://e621.net/posts.json?limit=200&amp;page=2&amp;tags=gadget_hackwrench`: 200 images (200), 0 tags (1552), -1 total (-1), -1 pages (-1)

**Comment by Bionus** [comment]
Could it be that your "deleted tags" list is separated by line breaks?
If that's the case, before the change it wouldn't work (only spaces were supported as separators), which would explain why it was fast before.

I'll have a look at optimizations to make it work with thousands of lines, but it shouldn't be that slow (not even 1s), especially for only 800 entries.

> Yeah I failed the version number, "975102b0" is the right one I'm typing, it's right... github is removing the zero !

It's the same. "975102b0" = 975102b0, and that's many months old 🤔

Were you still using [Nightly (Github)](https://github.com/Bionus/imgbrd-grabber/releases/nightly-github)?
I guess I forgot to disable it after moving it back to the "normal" [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly), my bad. I just deleted it 😅

**Comment by yami-no-tusbas** [comment]
Well, that would explain a lot ! Having so much branch is confusing.
Wouldn't be a solution to put the version/built date into the "about menu" ? At least date are more easy to understand than a random number.

So I just downloaded the right version now and... I'm on d0594094

> [10:39:07.400][Info] Monitoring new images for 'something' on 'Gelbooru'
> [10:39:07.407][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [10:39:**07.571**][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [10:39:**42.981**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`: 20 images (20), 0 tags (318), 1003 total (1003), 51 pages (51)

about : 35 seconds

Didn't see on e621, but whater was working for gelbooru is not even working anymore

And something was strange : 

> [10:43:22.161][Info] Monitoring new images for 'little_witch_academia' on 'Gelbooru'
> [10:43:22.175][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=little_witch_academia`
> [10:43:**22.358**][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=little_witch_academia`
> [10:43:23.552][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:24.477][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:25.196][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:25.778][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:26.618][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:27.109][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:27.948][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:28.703][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:29.639][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:30.559][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:31.274][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:32.019][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:32.992][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:33.922][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:34.715][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:35.373][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:35.831][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:36.219][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:36.616][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:38.003][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:43:**38.004**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=little_witch_academia`: 0 images (20), 0 tags (0), 4448 total (4448), 223 pages (223)

about 16 seconds

And yeah, app not responding at all while "filtering" or "parsing"

> [10:47:07.443][Info] Monitoring new images for 'mermaid_melody_pichi_pichi_pitch' on 'Gelbooru'
> [10:47:07.456][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=mermaid_melody_pichi_pichi_pitch`
> [10:47:**07.630**][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=mermaid_melody_pichi_pichi_pitch`
> [10:47:09.728][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [10:47:**30.956**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=mermaid_melody_pichi_pichi_pitch`: 19 images (20), 0 tags (217), 738 total (738), 37 pages (37)

about 23 seconds, it look like the more it filter out, the more fast it is ?

`Could it be that your "deleted tags" list is separated by line breaks?`

and while the app is not responsive I can open the ini so, my **ignoredtags** tags looks like : 

> ignoredtags="tag1\tag2\n... 

and so on. to be honest It's starting to get a little confusing, there is a ignore.txt too with line breaks between tags, so I backuped my lists, erased them from grabber, closed it, deleted files that looked like thoses list, the I put thoses list again with grabber interface, and...

> [11:02:07.617][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=pokemon`
> [11:02:**08.386**][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=pokemon`
> [11:02:34.233][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [11:02:39.189][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [11:02:39.607][Info] [gelbooru.com][Xml] Image filtered. Reason: image is "downloaded".
> [11:02:**39.609**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=pokemon`: 17 images (20), 0 tags (370), 150395 total (150395), 7520 pages (7520)

or 

> [11:07:19.223][Info] Monitoring new images for 'sidonia_no_kishi' on 'Gelbooru'
> [11:07:**19.228**][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=sidonia_no_kishi`
> [11:07:19.386][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=sidonia_no_kishi`
> [11:07:**45.130**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=sidonia_no_kishi`: 20 images (20), 0 tags (331), 285 total (285), 15 pages (15)

So ignore.txt is a list with linebreak but my input was not. In setting.ini ignored tags are like before with \n between them. And don't know where are the "removed" tags to check them.

I can send you thoses list, I directly copied them from grabber interface and putted them to text files. (Ignore list, removed tags list, and blacklist)

**Comment by Bionus** [comment]
I just pushed an optimization, and it ran 200K filters at ~20ms per image. You only have ~1K so it should be virtually instant.

**Comment by yami-no-tusbas** [comment]
Well I don't know, I just put back the ignored tags from the menus and it's no use, mayube it's something else...

> [23:25:23.614][Info] Monitoring new images for 'something' on 'Gelbooru'
> [23:25:23.616][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [23:25:**24.282**][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [23:25:**46.337**][Info] [gelbooru.com][Xml] Image filtered. Reason: image contains "hololive", image contains "hololive".
> [23:25:52.409][Info] [gelbooru.com][Xml] Image filtered. Reason: image contains "fate_(series)".
> [23:25:53.476][Info] [gelbooru.com][Xml] Image filtered. Reason: image contains "hololive", image contains "hololive".
> [23:25:54.646][Info] [gelbooru.com][Xml] Image filtered. Reason: image contains "hololive", image contains "hololive".
> [23:25:**56.807**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`: 16 images (20), 0 tags (303), 250229 total (250229), 12512 pages (12512)

Even with no hits from ignored tags : 

> [23:27:59.715][Info] Monitoring new images for 'something' on 'Gelbooru'
> [23:27:59.718][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [23:28:**00.257**][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [23:28:**23.339**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`: 20 images (20), 0 tags (238), 1240 total (1240), 62 pages (62)

I think I'll screen my settings and try on a fresh install tomorow, btw it was on grabber : "283334ac"

And as soon as I force close it, remove the content of ignoredtags= in my settings.ini : 

> [23:33:52.098][Info] Monitoring new images for 'ninja' on 'e621, Gelbooru'
> [23:33:52.656][Info] [gelbooru.com][Xml] Loading page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [23:33:**52.848**][Info] [gelbooru.com][Xml] Receiving page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`
> [23:33:**53.869**][Info] [gelbooru.com][Xml] Parsed page `https://gelbooru.com/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=something`: 20 images (20), 0 tags (418), 12585 total (12585), 630 pages (630)

So, as said i'll try on a fresh install tomorrow, because this make no senses for me. Maybe another of my settings make things wrong, or it could be the secials characters in the list itself, i'll try with more caution tomorrow.

**Comment by yami-no-tusbas** [comment]
And yeah, after installing everything a new, it work like a charm ! and now grabber is on fae5ec5e . Maybe installing over an existing version sometimes don't work. (like it was still on "283334ac" even after installing the lasted version)

But good job ! It work !

**Comment by Bionus** [comment]
> And yeah, after installing everything a new, it work like a charm ! and now grabber is on fae5ec5 . Maybe installing over an existing version sometimes don't work. (like it was still on "283334ac" even after installing the lastest version)

Don't know why it didn't update, but yeah it was a giveaway.

You can see in the Github thread the version you should have (see on the right):
![image](https://user-images.githubusercontent.com/882719/106337809-743f8800-6292-11eb-8837-01ad9ff0a753.png)

Or any newer version. Although there isn't any new commit right now, it happens when I push a lot of stuff:
https://github.com/Bionus/imgbrd-grabber/commits/develop
