### ISSUE TITLE
Tag filenaming stoped working on Gelbooru, returns "unknown" for colored character or artist tags

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#2240]
**Bug description**

I used %character:underscores% %md5%.%ext% mask for saving pics, but this stopped to work. I tried to use another tags %artist%/%character% but got same result - "unknown" 

Tag list stop to coloring colored tags too (character, artist tags are just black)

**Steps to reproduce**

1. set gelbooru as source in Donwnloads windows and some tag for download
2. set filename %character:underscores% %md5%.%ext% and destionation folder
3. download - see it returns unknown 91027897482734897234safsdfasd.png as filename for every picture and ignores character (green tags) or artis (red tags)  (for example) 

**Expected behavior**
It named files according the filename mask earlier.  %character:underscores% %md5%.%ext% returned correct filename.

**System information**
- Grabber version: 7.3.2

**Comment by Bionus** [comment]
Indeed, Gelbooru changed their tag HTML a few days ago.
You can follow this in issue #2235 !

In the meantime I'll close this as a duplicate 👌

**Comment by uvhat** [comment]
Is there working solution, or wait new builds?

I copied tags list from danbooru as temporary fix to gellbooru folder, many characters and artist are same but....
