### ISSUE TITLE
cli (and gui with --cli) doesn't exit after completing

### ISSUE THREAD

**Issue by InfernalUnderling** [Bionus/imgbrd-grabber#2242]
I'm running commit d8d58a16b62e88cb2a20c8a1f80a5157e00ce12d (from Jan 21st), on a linux distro (Guix System).

running `Grabber-cli --tags 'rating:safe' --sources 'gelbooru.com' --download --max 5` (or --return-images, etc)
will do the appropraite action (e.g. listing the urls, or downloading the images), but then the program doesn't exit, it just sits there in the terminal for as long as I let it.
When downloading, it does report `Downloaded images successfully.`, and the images do exist, but it doesn't exit the program. Using `--return-images` will print the urls, but  also doesn't exit.

Running the gui executable with `--cli` will also download images successfully, but also doesn't exit.

Further, the gui with `--cli` doesn't report success or the urls as the Grabber-cli executable does. I'm not sure if not outputting to the command line from the gui is merely a technical limitation, or an actual bug, however.

[main.log](https://github.com/Bionus/imgbrd-grabber/files/5858842/main.log)
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/5858843/settings.ini.txt)

This problem seems to have been mentioned in issue #2161, but since that issue was mostly about building the cli, I figured I should probably open an issue specifically for the hanging that occurs even when a valid source is specified.

**Comment by Bionus** [comment]
Should be fixed on the `develop` branch, although I just pushed a huge refactoring of the CLI code, so it there might be minor changes here and there. I tested most commands and they were working fine. The public API is unchanged.

Note that this only apply to Grabber-cli, not the "--cli" flag.
The goal of my refactoring is to have them be identical and share the same code base, but as of today they are not, they're copy/pasted (🤮). The refactoring has only been done on the CLI binary (but should arrive to the main one soon).
