### ISSUE TITLE
add support for nozomi.la

### ISSUE THREAD

**Issue by dEN5-tech** [Bionus/imgbrd-grabber#2243]
**Is your feature request related to a problem? Please describe**

no

**Describe the solution you'd like**
I would like for nozomi.la, to be added to Supported sites.

**Comment by yami-no-tusbas** [comment]
You already asked this in march 2020 : #1912 plz don't make duplicate, Bionus may be already working on it, plus, there is alternative fort thoses websites like hdoujindownloader that does the job.
