### ISSUE TITLE
Images downloaded from zerochan aren't named correctly

### ISSUE THREAD

**Issue by Roshri** [Bionus/imgbrd-grabber#2249]
**Bug description**

Tried to switch from some of the boorus to zerochan to get some stuff and when I downloaded the files I saw that it doesn't work with the same tokens as the boorus. %artist% %copyright% and %character% don't work at all since everything was listed as the default for unknown sources.

**Steps to reproduce**

1. Select zerochan as source
2. Search anything and download with preferred naming (mine is `%artist%\%copyright%\%character%_%date:format=yyyy.MM.dd-hh.mm%_%md5%.%ext%`)
3. Check if the file was named properly

**Comment by sstabeler** [comment]
That would be because Zerochan doesn't use the same namespaces as other sites. Mangaka for Artist, for instance. Copyright can be a variety of things, character is the same.

**Comment by Roshri** [comment]
That makes sense, so artist and copyright are out of the picture, I think I can get a workaround by refining searches and then telling grabber to download to a specific directory to keep my naming.
But it is still not pulling character correctly, I only get unknown_md5.ext
But if zerochan is that much different than the boorus then there's probably no workaround for this

**Comment by Bionus** [comment]
There should actually already be some pre-built tag type mappings for Zerochan and a few other sources to work without needing to have to work around them. Those mappings are:
* idol => model
* series => copyright
* mangaka => artist
* game => copyright
* studio => circle
* source => general
* character group => general
* oc => character

However, it would seem that they have been broken in a recent update. I'll push a fix ASAP to solve this.

**Comment by bakuzan** [comment]
Has this regressed?
I using 7.13 and I'm getting the issue.

I have a filename like so: %artist%/%copyright%, %character% [%artist%] %md5%.%ext%
The output is "anonymous" for artist, "misc" for copyright, and "uknown" for character, which is definitely incorrect.
