### ISSUE TITLE
Cannot Download Same Image Multiple Times, or Disabling MD5 List (Continuation of #2210)

### ISSUE THREAD

**Issue by cloudywings2** [Bionus/imgbrd-grabber#2250]
Hello. I had previously reported this issue but was unable to check back before the issue was closed.

**Bug description**

It is impossible to save a copy of the same image to two different sources. This makes it extremely difficult to save batches of overlapping tags. If, for example, you have previously downloaded images for a niche tag, and later attempt to download all the works of an artist, then the artist's works with that tag will be skipped.

**Steps to reproduce**

Search for a tag from any source, such as "1girl."
Download an image from that source to a folder based on that tag. (such as %search%/%md5%.%ext%)
Search for a different tag on the same image, such as "black_hair"
The image cannot be downloaded, and will link to that other image if the Destination Folder button is clicked.
Expected behavior

Two copies of the image should exist.

one in 1girl/%md5%.%ext%
one in black_hair/%md5%.%ext%

@Bionus responded here:
https://github.com/Bionus/imgbrd-grabber/issues/2210#issuecomment-761829280
> Looks like you're using the global MD5 list but actually don't want it.
> I'd suggest setting it to "save" or "copy" instead of "don't save".
> 
> See [How to avoid duplicates](https://bionus.github.io/imgbrd-grabber/docs/faq.html#how-to-avoid-duplicates) in the docs.
> If you already have the setting set to "don't save" but stilll cannot save (can you expand on what exactly it says?), it would be helpful to have your settings file / logs. Feel free to re-open in that case.

Below are my settings, though:
![copy](https://user-images.githubusercontent.com/54580938/106369445-59ffbb80-631f-11eb-9f48-5da039efe25b.PNG)

I believe what I want to do is disable the MD5 list completely. How do I do this? 

Thank you!

**Comment by brazenvoid** [comment]
As far as I know, there is no way you can skip the md5 list. 

Try setting the first two "Copy" options to "Save", considering you have the search string literally in the file name, it wouldn't matter.

**Comment by brazenvoid** [comment]
Setting them to "Copy" also seems error prone, considering only the MD5s will match, not the filenames.

**Comment by cloudywings2** [comment]
> As far as I know, there is no way you can skip the md5 list.
> 
> Try setting the first two "Copy" options to "Save", considering you have the search string literally in the file name, it wouldn't matter.

This seems to have worked. Thank you!
