### ISSUE TITLE
Ability to append MD5 list fixer instead of clear?

### ISSUE THREAD

**Issue by KamillaPup** [Bionus/imgbrd-grabber#2251]
**Is your feature request related to a problem? Please describe**
No

**Describe the solution you'd like**
I would like that the blacklist fixer simply appends the MD5s so having a toggle to append instead of clear would be great. Obviously a duplicate md5 checker would need to happen to compare the existing blacklist.

**Describe alternatives you've considered**
It used to be a TXT file database and I tried using that and setting the custom log file, but it was never generated. (MacOS version)

**Comment by Bionus** [comment]
Are you talking about the blacklist fixer or the MD5 list fixer?

Because I don't see exactly how your  it's related to the blacklist.
And I just tried the MD5 list fixer, and MD5s are already getting appended to the existing MD5 database, it shouldn't replace it. 🤔

**Comment by brazenvoid** [comment]
I guess then the language needs a makeover on md5 list fixer.
