### ISSUE TITLE
MD5 file not clearing

### ISSUE THREAD

**Issue by Nineball-Seraph** [Bionus/imgbrd-grabber#2252]
**Bug description**

After clearing out the MD5 text file/deleting it/running MD5 fix AND after deleting everything from my downloads folder the MD5 file seems to repopulate itself with the MD5s of the files that were downloaded, thus when downloading the same group of images they get skipped.

**Steps to reproduce**

1. Delete everything from my downloaded folder
2. Delete MD5s.txt and md5s.txt.bak
3. Relaunch grabber
4. Search and click 'Get All'
5. Perform download
6. Most of the downloaded files are skipped
7. Recheck MD5s.txt and its been repopulated with MD5 IDs of previously downloaded files (which grabber detects and skips)

**Expected behavior**

All files to be downloaded again.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/5901143/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/5901150/settings.txt)

**Screenshots**

**System information**

- OS: Windows 10
- 7.3.2 x64

**Comment by brazenvoid** [comment]
Frankly not that much required to do it. You just need to:

1. Delete the files
2. Delete the md5s.txt file while grabber is not active
3. Delete the md5s.sqlite if you are on nightly

Do not run MD5 Fixer, it does not empty the md5 list, the language is wrong.

**Comment by Bionus** [comment]
As said by brazenvoid, it looks like you might be deleting the MD5 files before closing Grabber, or without totally closing it.
Make sure Grabber is totally closed before deleting them, otherwise they'll be re-written during the sync when it gets closed.
