### ISSUE TITLE
Gelbooru no longer having specific tags such as "character", "copyright", "artist" etc.

### ISSUE THREAD

**Issue by TempMonkas** [Bionus/imgbrd-grabber#2256]
**Bug description**

Gelbooru no longer has specific tags such as "character", "copyright", "artist" etc. This makes all artists/characters come up as "unknown" now. Is this an issue with Gelbooru itself, or did something simply change on their end and need to be reflected in Grabber?

**Steps to reproduce**

1. Search anything and set the source to Gelbooru
2. Click on any image
3. View the tags. They're all black.
4. Attempt downloading with file naming set to eg. %artist% tag. It will be named to "unknown"

**Expected behavior**

This should behave the same as other sources, getting the artist name and other relevant tags specified, such as with Danbooru, etc.

**System information**

- OS: Windows 10
- Grabber version: 7.3.2 (x64)

**Comment by TempMonkas** [comment]
Just noticed a similar issue specifically for favourites, as noted here: https://github.com/Bionus/imgbrd-grabber/issues/2253 

This issue happens to non-favourites as well.

**Comment by Bionus** [comment]
Yes that one is specific to non-favorites.
But see #2235 for the generic one. I'll mark this one as duplicate 👌 
It should be fixed on the nightly version, and I'll make a new official release soon

**Comment by Tumultuous-RGR-SiM** [comment]
I was popping in here to finally check on this issue. It's been bugging me.

I'm glad to hear it's being addressed. Thanks, Bionus. You do good work.
