### ISSUE TITLE
I can't download tweets from Media page

### ISSUE THREAD

**Issue by kotoykm** [Bionus/imgbrd-grabber#2259]
Hello, when I use grabber for downloading from Twitter it downloads the images from the main page, downloading in the process a LOT of images from other non related people (+10.000 in some cases), I want to download images made by the artist, from "artist_name/media" but I don't know how to make Grabber do that, or if It can

**Comment by Bionus** [comment]
By default, Grabber returns media from retweets and in the user's replies.
If you don't want retweets, you can use `retweets:no` in your search. Same thing with `replies:yes/no`.

See [the documentation](https://bionus.github.io/imgbrd-grabber/docs/sources/twitter.html) for (not that much) more details.
