### ISSUE TITLE
Strange filename time to time with batches.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2260]
**Bug description**

For unknown reason, after doing batches, i found file with strange name and properties, here is some exemples :

```
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt000022e7~~cloire_clover - 4775860 - safe - b184a43baa518d47dadb881181d12e4a.jpg
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt00002330~~dyxm - 4251442 - safe - 48fedf89c68b317b678cce64635cee10.jpg
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt00002444~~hinghoi - 4715207 - safe - 2f9638eb9fb22b183f863c51a27b047c.png
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt000024ff~~jitan777 - 4341223 - safe - 4b1551f9d578bc23ebd3a1ee444cdb8c.jpg
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt00002500~~jitan777 - 4341224 - safe - 338b0149de80a8bb636e17f1f31022bf.jpg
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt0000295a~~kurono_kito - 3773045 - safe - 402da9a8fe08c62fe26389b941663e22.png
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt00002dd1~~sukemyon - 3763392 - safe - 629a6f889b29e031d48fb4c9d7b6406d.png
J:\Avatars\char\astolfo_(fate)\fate_(series)\astolfo_(fate)\~~adt00002df1~~takatun223 - 4401138 - safe - d465545507d83c6178808f30afe18555.jpg
J:\Avatars\char\astolfo_(fate)\fate_apocrypha fate_(series)\astolfo_(fate)\~~adt00002147~~aori_sora - 3923446 - safe - 2ebb3d46ff9b1086cc52f95edbcbfc04.jpg
J:\Avatars\char\astolfo_(fate)\fate_apocrypha fate_(series)\astolfo_(fate)\~~adt000022e4~~citron_82 - 3048550 - safe - 9158c4891d6faa59fd35055b18f591aa.png
J:\Avatars\char\astolfo_(fate)\fate_apocrypha fate_(series)\astolfo_(fate)\~~adt000022f8~~crokase - 3969992 - safe - b9eac8b31596b1a84764cae4ad8f7d84.png
J:\Avatars\char\astolfo_(fate)\fate_apocrypha fate_(series)\astolfo_(fate)\~~adt0000232f~~dr_rex - 4134221 - safe - 806e688cb8dff6f8ba4d4360ccf11948.png
J:\Avatars\char\astolfo_(fate)\fate_apocrypha fate_(series)\astolfo_(fate)\~~adt0000239f~~fou_(ssqseeker) - 5224932 - safe - 9a65327c3215622f90e43970f9b842f0.jpg
J:\Avatars\char\astolfo_(fate)\fate_apocrypha fate_(series)\astolfo_(fate)\~~adt00002400~~google_(asdek18) - 3869335 - safe - 0b33f6467537954050242e0180edbefa.png
J:\Avatars\char\astolfo_(fate)\fate_apocrypha fate_(series)\astolfo_(fate)\~~adt000024e2~~ikegami_akane - 3782728 - safe - 8d525d39949a20f3f31354af4226335c.jpg
```
And I've found 198 hits over 55572 files that I batched, It was some characters from popular series taken on gelbooru.com

Sometimes files are prefixed "`~~adt0000XXXX~~`" and put into "hidden" attribute. If I download for exemple "id:3782728" with graber (fae5ec5e) it's fine (`J:\Avatars\Gelbooru\id_3782728\fate_(series)\astolfo_(fate)\ikegami_akane - 3782728 - safe - 8d525d39949a20f3f31354af4226335c.jpg`). I'm clueless why this happen. It seems to happen only with larges batches, I'll do some more tries in the future to isolate what does it. (have never seen this on monitors for exemple, only on batches)

**Steps to reproduce**

Don't know for the moment, seems a bit random. (I got it with an "astolfo_(fate)" "get all", maybe I can reproduce it)

**Expected behavior**

Not this strange filename neither "hidden" attribute.

**Context**

Will ad log if I can catch it.

**System information**

- OS: [e.g. Windows 10]
- Grabber version: [fae5ec5e] (But I've seen this bug before using nightly in the past)

**Comment by Bionus** [comment]
Do you have any antivirus or similar software running when doing downloads?
Some antivirus might "take control" of the file while scanning it, hence the weird prefix and "hidden" attribute, but for some reason doesn't free the file afterwards. 🤔

**Comment by yami-no-tusbas** [comment]
I use windows default antivirus, I don't download to a synced folder to avoid useless sync and having too much traffic. I had thoses files when using avast too, so it not caused by anti-viruses, the files are fine themself, if I remove the ~~adtxxxx~~ they are perfectly what they are supposed to be. I'll do some more batches today trying to get a log for this. The only program I have that "scan" everything in the background is a tool called "everything", But it is a tool that act as a search database like "find" on linux it should not lock any files.

But first I'll try to reproduce the error, get the log and send them.
