### ISSUE TITLE
Backlisting tags with ":" sign.

### ISSUE THREAD

**Issue by Tirith2708** [Bionus/imgbrd-grabber#2268]
Hi,
I've noticed that blacklisting tags with certain signs (most notably : sign) causes app to stop retrieving any results after search.

**Comment by Bionus** [comment]
Indeed, that's because the  `:` sign is used for "meta-tags" (things such as "rating:safe").
I'll push an update to allow to "escape" those using `::` (and escape them automatically when using context menus).
