### ISSUE TITLE
Slow download speeds on danbooru

### ISSUE THREAD

**Issue by ZooM2198** [Bionus/imgbrd-grabber#2269]
I tried downloading some images off danbooru today and my speed ends up tanking after a certain amount of time, it drops from around 6-7Mbps to 20-30Kbps. I don't know why this is happening but when I used the program around a moth ago everything worked fine. This is on a fresh device as well, so it's not a hardware problem like I thought it might be. My network connection is also stable.

I'm on the latest version. Is it possible the booru API has changed or something, can't think of anything else.

**Comment by Bionus** [comment]
Does it go back to normal speed after restarting the program?
If you go to the website and try to load a big image (ex: `absurdres` tag), does it load fast?
Your IP might be temporary rate-limited by their server.

**Comment by ZooM2198** [comment]
Everything loads fast on the website. If I restart the program it's the same as before; it will start from my usual 7+Mbps speed then after a certain number of files it will slow to a crawl again. I agree with you that it might also be their servers, it's just weird that this has never happened before.
Just ran it now and it got further than when I ran in the morning (33% and then dropped), looks like it's them rate-limiting I guess. They must've updated something because it wasn't happening before and I was downloading 1.5k images at a time.

![slow](https://user-images.githubusercontent.com/39165655/108410186-fe8a6480-721e-11eb-9356-028d7dfc2bd4.png)

**Comment by brazenvoid** [comment]
Perhaps try a proxy or vpn?

**Comment by ZooM2198** [comment]
I tried that but it doesn't make a difference. Dunno what's going on.

**Comment by ZooM2198** [comment]
Update on this thing, tried downloading today and it won't even recognize anything beyond the first page. If you hit the next page button it loads that, but if you click the last page button it just displays the first page. Again, only for danbooru, safebooru works fine and displays page results etc.

![danbooru](https://user-images.githubusercontent.com/39165655/109360048-717a8780-787e-11eb-8bb0-c2463ba57f9e.png)

**Comment by SvyraCosmix** [comment]
Try Gelbooru, its better
