### ISSUE TITLE
Move top/bottom actions of download row context menu swap entries

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2271]
**Bug description**

The actions on right click context menu to move the download top/bottom work in unexpected ways. Both swap the downloads instead of shifting their subsequent downloads up or down.

Like move to top swaps the current top download with the target download instead of shifting the current top download below. Vice versa for the move to bottom.

**System information**

- OS: Windows 10
- Grabber version: Nightly

**Comment by Bionus** [comment]
Those two commands seem to swap rows instead of actually moving them.
I just pushed a fix, but note that you can also simply drag and drop rows now.
