### ISSUE TITLE
Rule34.xxx now downloading larger MP4's instead of smaller WEBM's

### ISSUE THREAD

**Issue by sbobbo** [Bionus/imgbrd-grabber#2273]
I don't know if this is due to a change at the website itself or not, but I have been redownloading some tags and noticed that the filesizes for identical posts (per MD5 & post ID) have very different sizes. This is true for some images, but also for Videos.  For example, ID:4012051 when downloaded previously resulted in a 45MB .WEBM file, but now it's an 80MB MP4 file. This makes my duplicate checks useless, unfortunately.

Any chance this is a Grabber side thing, or is it something the website changed on their end with no way of reverting on Grabber?

**Comment by brazenvoid** [comment]
#2139 

This issue changed this behaviour. The MP4s are bigger but with higher quality than WEBMs. Thus they were opted for as default download extension.

**Comment by brazenvoid** [comment]
A correctly encoded MP4 is always higher quality than a correctly encoded WEBM. It is practically the same thing as people preferring PNG over JPG over WEBP over AVIF for storage/hoarding purposes. 

These newer formats are focusing on compression and adequate one time viewing experience. Essentially sacrificing quality to reduce network bandwidth usage. Though difference between PNG and JPG is relatively hard to differentiate, WEBM vs MP4 is easier. Same with images JPG to WEBP or AVIF is a drastic difference but only if your eye stays on it for longer than an instant.

**Comment by brazenvoid** [comment]
Perhaps a switch to prefer one of the two would be better?

**Comment by brazenvoid** [comment]
What I have observed on rule34.xxx for webm, seems that the encoding scheme behaves erratically:

- mp4 vs much bigger webm: 40mb mp4 vs 80 mb, no difference
- mp4 vs gigantic webm: 1mb mp4 vs 30mb webm, webm is noticeably better.

I guess they went to webm to adhere to web standards, not to optimize web traffic.

**Comment by Bionus** [comment]
As said, the behavior was changed by 648082e0e5fc4aac508fcd37fead6098a7dfa748.
If an image is tagged `mp4` but the file is a `.webm`, it's automatically "fixed" now.

As far as I know the MP4 are the original files, while webm are created by the website, hence why it downloads the MP4.
