### ISSUE TITLE
Video player doesn't display anything

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#2279]
## Log message
```
[20:04:48.138][Warning] [Qt][default] defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
```

##  Workaround
~~Disable the video player in the settings:~~ (causes crashes, see issue #2287)
![image](https://user-images.githubusercontent.com/882719/110251472-dcb01200-7f80-11eb-949b-98858abc4728.png)

**Comment by Tumultuous-RGR-SiM** [comment]
One idea could be to use MPV. It's a simple videoplayer that's multiplatform (at least it has linux and windows versions), and it's very small. I've heard of other programs, like Hydrus, integrating MPV as a built-in video player. It's probably small enough to be slotted into the executable.

**Comment by Bionus** [comment]
A fix is to simply extract this to your install directory: [mediaservice.zip](https://github.com/Bionus/imgbrd-grabber/files/6108161/mediaservice.zip)

> One idea could be to use MPV. It's a simple videoplayer that's multiplatform (at least it has linux and windows versions), and it's very small. I've heard of other programs, like Hydrus, integrating MPV as a built-in video player. It's probably small enough to be slotted into the executable.

If I went third-party I could also directly embed a VLC player since they play  well with Qt, but normally on Windows for what Grabber does DirectShow or the Media Foundation should be enough and simpler to implement.
