### ISSUE TITLE
Using "-" (tiret or dash) make grabber fail for renaming.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2282]
**Bug description**

Using a "-" in the folder name is no good for the renaming tool.

**Steps to reproduce**

Open the renaming tool, make the source a folder like "D:\sync\grabber\artists\1 - ..." (work with sub-folder too)
Then when you press continue Grabber will show 0 results.
Rename the folder for "1  ..." by removing the dash, and grabber see the images.
²Note that the folder you put doesn't have to be the one with the dash, it can be a sub-folder too and grabber will not see it.

**Expected behavior**

Grabber working with or without " - " in the folder name.

**Context**
Log show nothing about folder not found, plus the renaming tool has no log before it's getting the images informations.

**Screenshots**

**System information**

- OS: Windows 10
- Grabber version: c0c375d0 (but should be in grabber 7.4)

**Comment by Bionus** [comment]
Does it work if you replace the `\` in your filename by `/`?
I don't think it would have anything to do with `-` otherwise.

**Comment by yami-no-tusbas** [comment]
Ok step by step, here is my input : 
https://i.imgur.com/lz2jMyy.png
the folder "E:\Artists" contain tree folder : 
https://i.imgur.com/c4HlBka.png
If i press continue : 
https://i.imgur.com/s0TtIMF.png

But if change the folder for exemple : 
https://i.imgur.com/mDGu6Z1.png
Wich is a sub folder of artists : 
https://i.imgur.com/b3uDYDM.png

It's fine, the problem only occurs with directory name, file name are good afaik. I seen you push a fix, so i'll update after t his comment an test again.

**Comment by Bionus** [comment]
Ah yes, that's because your "original filename" didn't contain the directory name here.
You should prepend `%directory%\` or something to your original filename as well.

When extracting the MD5 from the filename, it's checking the **whole** path, so that it would work if the MD5 is a directory name.
So make sure your original filename matches the whole path and not just the actual file name.

**Comment by yami-no-tusbas** [comment]
Oh I see, it work now, still feel a little strange since where there is no "dash" i don't have to specify %directory%\ in the original filename. But yeah adding %directory%\ in the original filename solve it, so you don't wanna use the same separator in your folder name and filename I get it !
