### ISSUE TITLE
Make TamperMonkey script for naming files

### ISSUE THREAD

**Issue by Dramorian** [Bionus/imgbrd-grabber#2285]

**Comment by Bionus** [comment]
Could you elaborate a little bit on what you mean?
Also, JavaScript filenames are already supported if that's what you mean.

**Comment by Dramorian** [comment]
It's great that Grabber has this feature embedded, but I would like to have it in the browser. Sankaku and rule34.xxx send hash only.
Dumb request, I know.

**Comment by Dramorian** [comment]
Also, %сharacter% %copyright% drawn by %artist% %md5%.%ext% is not valid. 
"The %сharacter% token doesn't exist..." it says.

**Comment by Bionus** [comment]
I don't really understand what you mean by that.
Grabber is a software, not a browser extension, so it can't name files on your browser. If you want to download files from some website, why not just load them from Grabber and download from there?
