### ISSUE TITLE
Video Previews Crash Windows Version

### ISSUE THREAD

**Issue by FroggyFriend** [Bionus/imgbrd-grabber#2290]
Grabber Version 7.4.1 x64
Platform: Windows x64, 20H2

When I click on a search result for the "animated" tag, ones that have a green border around them, it loads the preview into a new windows, and when it finishes loading the entire program closes, doesn't happen with GIF files.

* [main.log](https://github.com/Bionus/imgbrd-grabber/files/6124548/main.log)
* [Settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/6124552/Settings.ini.txt)

(Tried reinstalling, didn't fix it.)

**Comment by Bionus** [comment]
> Grabber Version 7.5.1

I guess 7.4.1? 😅 

Thanks for the log, it seems like an issue with the DirectShow player.
Can you try to extract the DLL in this ZIP into your installation directory's "multimedia" folder? [mediaservice.zip](https://github.com/Bionus/imgbrd-grabber/files/6124611/mediaservice.zip)

The result should be something like:
```
├─ multimedia
│  ├─ dsengine.dll
│  └─ wmfengine.dll
├─ Grabber.exe
└─ ...
```

If it still doesn't work, can you try deleting the `dsengine.dll` file? (and only keep the new `wmfengine.dll`  one)

**Comment by FroggyFriend** [comment]
> Can you try to extract the DLL in this ZIP into your installation directory's "multimedia" folder?
Where would that folder be? I'm guessing somewhere near C:\Users\Username\AppData\Local\Bionus\Grabber ?

**Comment by Bionus** [comment]
By default it's this:
```
C:\Program Files\Grabber
```
But if you changed it during installation it might be somewhere else.

**Comment by FroggyFriend** [comment]
> C:\Program Files\Grabber

I don't see a "multimedia" folder but I see one labeled "mediaservice", do i put the DLL into here?

**Comment by Bionus** [comment]
My bad, yes it's called `mediaservice`.

**Comment by FroggyFriend** [comment]
Alright so just try to do what I did before and see if the problem is solved?

**Comment by Bionus** [comment]
Did it work?
Or did that DLL had no effect whatseoever, alone or together with `dsengine.dll`?

**Comment by becky-soda** [comment]
Adding `wmfengine.dll` and deleting `dsengine.dll` fixed the problem for me, at least for the videos I was trying to access.
Just adding `wmfengine.dll` without deleting `dsengine.dll` did not fix the problem, and still causes the crash.

Thanks, Bionus! :)

**Comment by Himither** [comment]
Hi! Just dropping by to say:
I had the same problem (probably?) in the current version 7.10.1 on Windows 10 Home 22H2.

[14:50:51.371][Warning] [Qt][default] DirectShowPlayerService::doRender: Unresolved error code 0x80040266 (IDispatch error #102)

So I went ahead and renamed the "dsengine.dll" in the mediaservice folder to "dsengine.backup", which fixed the problem just like it did for becky-soda back in 2021. 

I didn't install codecs or anything of that sort and the problem pretty much started occuring out of nowhere, so I'm sadly clueless on what could've started it. 
Maybe one of the 17 different Microsoft Visual C++ Redistritbutables is causing this...those have sure stacking up of the last 2 years.

![grafik](https://user-images.githubusercontent.com/13561414/233841142-f0006b30-760d-41fc-a747-70d311aca995.png)

But I guess the important part to note here is, that this fix still works.
