### ISSUE TITLE
Images are offset when clicked on

### ISSUE THREAD

**Issue by hubiemighthavecooltoes** [Bionus/imgbrd-grabber#2292]
Whenever I click an image to zoom in and enter the scroll mode/slideshow mode, the images are always skewed to the left. It would be way better if they were centered. All that empty space to the right looks off.

The images should be centered when you click on them. Or an option for them be centered

*I'm not sure if there already is an option for this, i looked and i didn't see one*

Example
  v v v
https://imgur.com/M9In0k1

**Comment by hubiemighthavecooltoes** [comment]
pc version

**Comment by Bionus** [comment]
There's indeed already a setting for that:
![Uploading image.png…]()

You can change it to center/center to center it both vertically and horizontally.

**Comment by hubiemighthavecooltoes** [comment]
THANKS
