### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by thany** [Bionus/imgbrd-grabber#2295]
**Bug description**

Version 7.4.3 displays an error when it starts, four times to be precise. Every one of them is identical:

**Steps to reproduce**

1. Install 7.4.3
2. Start it
3. Wait about 2 microseconds :)

**Expected behavior**

Should work fine.

**Context**

* Not providing a `main.log` as it is not created.
* Here's my [`settings.ini`](https://github.com/Bionus/imgbrd-grabber/files/6138227/settings.zip).

**Screenshots**

![image](https://user-images.githubusercontent.com/152227/111092293-f24fa980-8535-11eb-84b1-b1c36ae9ec5a.png)

**System information**

- OS: Windows 10
- Grabber version: 7.4.3

**Additional context**

I installed 7.4.3 over the previous version, which in my case is 7.2.1, iirc.

It's also weird that these errors appear halfway beyond the bottom-right of the screen, so a quarter of these error messages is visible before dragging them back.

**Comment by Bionus** [comment]
Indeed. The installer is not installing the correct VC Redist anymore. In the meantime, you can find the correct version here:
* x86: https://aka.ms/vs/16/release/vc_redist.x86.exe
* x64: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by thany** [comment]
Yep, that works. Thanks.

Maybe release a new version that fixes the installer? I imagine I might not be the only Windows user 😀
