### ISSUE TITLE
Android UI Suggestions

### ISSUE THREAD

**Issue by FroggyFriend** [Bionus/imgbrd-grabber#2299]
I've been trying to download images from the app and nothing on the app shows how much progress has been made, so basically a Little Progress Bar that shows that its downloading.

And since the Android version is installed via APKs, you have to go download updates manually, so maybe allow the app to automatically check for updates or add a "Check for Update" buttons on the side menu?

If your already working on any of these then sorry to suggest them again, just wanted to share things I think would make the app easier to use!

**Comment by Bionus** [comment]
Hello

Those are indeed part of the known issues / planned improvements listed in issue #2147 that tracks the overall progress of the Android application.

Namely:
> * [ ] Update checker
> * [ ] Add proper image download indicator

I'm having a hard time progressing on both the desktop and mobile app at the same time so I have to admit there hasn't been much of an improvement on the Android version in a while! I'll invest more time on it soon.

I'll close this as duplicate but don't worry about it 😄
If you see anything not listed in there, feel free to open another ticket!
