### ISSUE TITLE
Audio Issues (Windows)

### ISSUE THREAD

**Issue by FroggyFriend** [Bionus/imgbrd-grabber#2301]
(This is just a copy of the Audio Issue for the Android Version)

On the Windows Version of Grabber, version 7.4.3, whenever you view any animated file that has sound the sound continues to play even after you preview a different video.

I searched a tag that had multiple animated results, and while scrolling through the results a video played, which was nice since I didn't have to click on it, but when I then scrolled to a result that had no sound, the sound continued to play.

Grabber Version 7.4.3 64-Bit
Windows Version 10; 20H2, 64-Bit

**Comment by Bionus** [comment]
Should be fixed by b38ea00934c9263fa62e7ed5888f71485b652ef6 in [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) and soon in 7.5.0.

**Comment by brazenvoid** [comment]
For me no video/audio plays in grabber... my preview windows have always been blank for videos...
