### ISSUE TITLE
Some UI problem

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2302]
Actually I found some UI issue, first is a pretty obvious one for me : 

- When clicking with the middle mouse bouton (wheel), on a tag in the tag list that can be enable by the view menu, I expect the tag I midle clicked on to open in a new tab. Instead it seems to reload my last tab with blank tag. Clicking on a tag on the list actually open a new tab, I feel this to be pretty inituitive as a lot of ppl use middle click to open a new tab while browsing for exemple and simple clic to open in the current tab. I think the best solution could be on user choice, in the interface menu, a check box like "use middle click instead of click to open a new tab when clicking on a tab". And btw, middle clicking anywhere in the list, tag or background, just set the last tab to a blank one (not a new one, because you can go back to it's previous term using the back button)

Then the other UI problem is the ":" when on a tag, not a variable (for instance using ext:webm), make the blacklist go crazy : 

- Let's say we use " pokemon:_the_electric_tale_of_pikachu " as a blacklist tag, the ":" would cause the blacklist to fail and block everything. Any tags using that character cause the blacklist to fail, then grabber will say that every single image on every board, is "filtered".

**Comment by Bionus** [comment]
> When clicking with the middle mouse bouton (wheel), on a tag in the tag list that can be enable by the view menu, I expect the tag I midle clicked on to open in a new tab

Strange, that's how it's supposed to behave. I could reproduce the issue though, definitely a bug somewhere.

> Then the other UI problem is the ":" when on a tag, not a variable (for instance using ext:webm), make the blacklist go crazy :

Yes, as you guessed it's being treated as a variable instead. You can escape the `:` by doubling it, resulting in "pokemon::_the_electric_tale_of_pikachu".

Did you add this tag by editing the blacklist manually? If you right click > blacklist it should escape it automatically 🤔 

I guess a good solution here would be to add coloring to the blacklist field, to make it clearer it's being detected as a variable and not simply a tag.

**Comment by yami-no-tusbas** [comment]
> Did you add this tag by editing the blacklist manually? If you right click > blacklist it should escape it automatically 🤔
> 
> I guess a good solution here would be to add coloring to the blacklist field, to make it clearer it's being detected as a variable and not simply a tag.

No I was using the right-click menu "Blacklist" item, from the image viewer or even the on tags viewer.
and I also see that the taglist on the left (the one from "view"->"tags") doesn't update in real time like the taglist in the viewer.

And i just got another "problem", on the tag viewer (the one form the "view->tags" menu), if you ask for a new windows you get a new instance of grabber, that can make some problem too... (with monitoring, logging, and all sort of stuff). I never used it before, but I tried it now and feel like this a no place in the program, since everything is inside the main window.

And the " : " problem is on the lastest nightly, but I had it from a long time ago already. But since it's a pretty rare occurence I didn't think much of it at the time. But no, the program is not doubling it by default it seems.

**Comment by yami-no-tusbas** [comment]
Seem's to be fixed with comit b276fe9

**Comment by Bionus** [comment]
> And the " : " problem is on the lastest nightly, but I had it from a long time ago already. But since it's a pretty rare occurence I didn't think much of it at the time. But no, the program is not doubling it by default it seems.

I just pushed a fix for this as well. Blacklisting tags with ":" inside will now properly escape them.

As for "open in new window" yeah that's some very old stuff there. I guess it could be removed, or updated to fit the current structure properly (to avoid having multiple monitors in parallel as you said). Seems like no one's using it.

**Comment by yami-no-tusbas** [comment]
Yeah that decision is ultimately up to you, so you decide 👍  When I saw that option i was thinking like a new windows on a web browser, but that doesn't feel usefull with grabber.
