### ISSUE TITLE
Removing a job while the job run, will crash.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2304]
**Steps to reproduce**

1. Set a download list with one entry (at least)
2. Launch the download
3. Delete the job before the download is finished
4. Once the download finish, click ok, enjoy free crash !

**Context**
I was curious to try, the log show nothing, but I assume when the app go to change the stage of the downloaded item in the list, since the item no longer exist, it just crash.
I tested on the lastest nightly, but I assume this would happen on all version.

**Solution**
Maybe froze the download list so at least we don't delete an entry while job is running, but this would prevent to add new job while a job is running... Prevent only the current downloaded row to be deleted ? Not sure this will fix it too, maybe just prevent removing while downloading but letting the option to add more download on the list.

**Comment by Bionus** [comment]
Yes, the "delete" buttons should be disabled. Actually the ones at the bottom of the window are, but since then the right click menu was added, as well as the keyboard shortcut using the Delete key, so I guess those were forgotten 😅
