### ISSUE TITLE
Some rule34.xxx entries can't be downloaded

### ISSUE THREAD

**Issue by Donny-Pandairaz** [Bionus/imgbrd-grabber#2305]
**Bug description**

Various entries from rule34.xxx can not be downloaded and Grabber reports invalid HTML content returned back for the URL in question:

**Example**
https://rule34.xxx/index.php?page=post&s=view&id=3751980
- https://us.rule34.xxx//images/3326/987c800415952074d49b0abbb7585d429523ee89.gif

**EDIT** It would appear that the issue is caused by the "original image" link that Rule34.xxx uses for the direct link to the image on their servers. Some media is effected by the servers appending the page ID onto the link making it unreadable to Grabber. This can be observed if you click the "original image" link on rule34.xxx of affected images/media. Clicking said link will not open unless you open it in a new tab to which you will see that the URL has been appended with "?" following the page ID "3751980".

This then causes the link to be read like so, https://us.rule34.xxx//images/3326/987c800415952074d49b0abbb7585d429523ee89.gif?3751980, to which Grabber can not read and will report that the file doesn't exist.

**System information**

- OS: Linux Mint 20.1
- Grabber version: 7.4.3

**Comment by Bionus** [comment]
I can't reproduce this on my end.

When loading or downloading image 3751980, the GIF is properly shown.
Using the XML API, it's directly loaded since the proper URL is returned by the API ([link](https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=id%3A3751980)).
Using the HTML "API", it sees the "animated" tag so tries the WEBM/MP4 extension before settling on GIF. But in the end, it's properly downloaded.

What are your reproduction steps inside Grabber to get an error?

**Comment by Donny-Pandairaz** [comment]
When searching for (in this particular instance) the artist, Buckethead_ero, go to the second page, select that page downloading. While downloading that page's content you should see that all but one is downloaded. 

The only one not downloaded from that second page is image #3751980. Even when opening the image in Grabber, it shows that it's not found. 

![Screenshot 2021-03-24 161936](https://user-images.githubusercontent.com/30457044/112378629-88659b80-8cbd-11eb-8de8-3611948f4cf5.png)
![Screenshot 2021-03-24 162149](https://user-images.githubusercontent.com/30457044/112378630-88659b80-8cbd-11eb-872b-ac8ccc384856.png)

**Comment by iPathos** [comment]
Using the same search parameters and saving all images that work, I can reproduce this issue using version 7.5.1 (x64).
My Blacklists include the following list, but afaik that doesn't include this image.
yaoi
male_only
gore
scat
futanari
poop
3dcg
death

**Comment by Donny-Pandairaz** [comment]
So, I've been messing around with more of the same artist tag to see if any other programs suffer the same issues with the same exact images, and turns out, they do. Other Booru downloaders have the same exact images missing when trying to download the same artist tag, Buckethead_ero. I can only assume that this has something to with the API or the site itself, but there's nothing that I can see that would cause this problem to begin with other than some sort of invisible post flag.

I don't really know given the usual flags for booru sites will either display the image or not due to them being deleted or not. The files can be downloaded normally through a browser but will otherwise fail to download through any other means that are automated.
