### ISSUE TITLE
Trying to add single images in Downloads tab for yande.re doesn't work

### ISSUE THREAD

**Issue by uematsufreak** [Bionus/imgbrd-grabber#2307]
Whenever I try to download images using the single images portion of the downloads tab from yande.re, every search always fails with a list of legit IDs. It seems removing the "status:any" that's showing in the logs may fix the issue? That is, if it's something you can replicate.

I just know that if I search yande.re manually for something like "id:401372 status:any" it will return nothing, but just "id:401372" will return the desired image.

Thanks in advance. I appreciate all the work that's been put into this.

Edit: To show you a small portion of what the log looks like when trying to add yande.re IDs:

> [21:31:13.753][Info] [yande.re][Json] Loading page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A741618 status%3Aany`
> [21:31:13.890][Info] [yande.re][Json] Receiving page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A741618 status%3Aany`
> [21:31:13.890][Info] [yande.re][Json] Parsed page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id0A741618 status0Aany`: 0 images (0), 0 tags (-1), -1 total (-1), -1 pages (%11)
> [21:31:13.890][Warning] No image found for search 'id:741618 status:any'
> [21:31:13.891][Info] [yande.re][Json] Loading page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A751252 status%3Aany`
> [21:31:14.280][Info] [yande.re][Json] Receiving page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A751252 status%3Aany`
> [21:31:14.281][Info] [yande.re][Json] Parsed page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id0A751252 status0Aany`: 0 images (0), 0 tags (-1), -1 total (-1), -1 pages (%11)
> [21:31:14.281][Warning] No image found for search 'id:751252 status:any'
> [21:31:14.282][Info] [yande.re][Json] Loading page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A751253 status%3Aany`
> [21:31:14.383][Info] [yande.re][Json] Receiving page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A751253 status%3Aany`
> [21:31:14.383][Info] [yande.re][Json] Parsed page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id0A751253 status0Aany`: 0 images (0), 0 tags (-1), -1 total (-1), -1 pages (%11)
> [21:31:14.384][Warning] No image found for search 'id:751253 status:any'
> [21:31:14.384][Info] [yande.re][Json] Loading page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A751310 status%3Aany`
> [21:31:14.484][Info] [yande.re][Json] Receiving page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id%3A751310 status%3Aany`
> [21:31:14.485][Info] [yande.re][Json] Parsed page `https://yande.re/post/index.json?limit=1&amp;page=1&amp;tags=id0A751310 status0Aany`: 0 images (0), 0 tags (-1), -1 total (-1), -1 pages (%11)
> [21:31:14.485][Warning] No image found for search 'id:751310 status:any'

**Comment by Bionus** [comment]
It indeed seems that Moebooru (so yande.re also, using it) does not support `status:any`.
I'll push a fix.
