### ISSUE TITLE
Segfault When Clicking Yes In Prompt.

### ISSUE THREAD

**Issue by Penguin-Guru** [Bionus/imgbrd-grabber#2309]
Segfault after clicking the viewer button to "save" or "save (fav)" without having specified a corresponding filename format. A window appears, prompting yes or no to open the options window. Selecting yes causes the crash, selecting no does not. Operating system is linux. Backtrace as follows:

ThemeLoader()
: QObject(parent), m_path(std::move(path))

OptionsWindow()
: OptionsWindow(profile, new ThemeLoader(savePath("themes/", true, false), this), parent)

saveImageNow()
auto *options = new OptionsWindow(m_profile, parentWidget());

**Comment by Bionus** [comment]
It seem to come from using `this` before `QObject(parent)` has been called.
I'll fix it by simply having the ThemeLoader use the parent as parent for now.
