### ISSUE TITLE
Use a consistent name for the image/viewer/zoom window

### ISSUE THREAD

**Issue by Penguin-Guru** [Bionus/imgbrd-grabber#2312]
It seems like some settings and variables use different names to refer to the viewer/zoom/image window, which is only a little confusing in the U.I. but will likely become more confusing as more features are added that require variables and setting groups. Personally, I like "viewer window", since the "image window" does handle some media that aren't static images. "Zoom window" is a nice name but it's not clear to new users what the "Zoom window" is-- they will have to infer that based on the settings that are presented to them or change some setting and see what happens. This isn't exactly a feature request but more like a suggestion. Most variable names seem to refer to that window as "viewer" but the settings group they are contained within is "Zoom" and in the settings menu it's called "image window". It would be nice to have the window name consistent with the file and directory names too.

**Comment by Bionus** [comment]
I'll go with "ViewerWindow" since as you say, it can show more than just images, such as videos.
Note that there will still be references to "Zoom/" for settings as otherwise it would break backward compatibility. I'll make them use "Viewer/" now however, falling back to the old values.

**Comment by Penguin-Guru** [comment]
Sounds good. :)
