### ISSUE TITLE
Add Inkbunny to Sources

### ISSUE THREAD

**Issue by SvyraCosmix** [Bionus/imgbrd-grabber#2316]
I was just hoping that you wouldn't mind adding https://inkbunny.net/ to the list of sources seems like another good site to add to the growing list. Thank you

**Comment by iszotic** [comment]
I want this site supported too. thx

**Comment by RinMaru** [comment]
yea it would be nice

**Comment by SvyraCosmix** [comment]
Yet it was closed automatically cause bionus just doesn't give a shit lmao

**Comment by iszotic** [comment]
mmm, well after some digging gallery-dl works for inkbunny, but it's nice to have a GUI

**Comment by RinMaru** [comment]
> Yet it was closed automatically cause bionus just doesn't give a shit lmao

He does this for free so be thankful this tool even exists for free. He didn't close it its a bot.

**Comment by SvyraCosmix** [comment]
What "closed automatically" means.
