### ISSUE TITLE
Error loading the image

### ISSUE THREAD

**Issue by Fimte** [Bionus/imgbrd-grabber#2317]
Hey! After a recent update, I ran into the problem that the full image is not loaded from sonohara.donmai.us, I see a preview, they update quickly, but the full image is not loaded or saved. Rolling back to the previous version did not fix the error, and neither did the latest current update.

**Comment by Bionus** [comment]
I can't reproduce on my version, could you share your log file?

If a clean install of an old version does not fix the issue, this might not be Grabber-related. You can try deleting your settings directory before reinstall to perform a clean install:
```C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber```
