### ISSUE TITLE
Tool to add Meta To Existing Files

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2319]
I guess the title says it all. With the addition of this feature, a sync tool is needed to make all existing files up to pace with the new ones.

**Comment by sstabeler** [comment]
Wouldn't you be able to do this exact thing simply by setting Grabber to the "save" option for dealing with files that already exist, then redownloading the file?

**Comment by brazenvoid** [comment]
That will be an extreme waste of resources, not to mention a tremendous burden for the source websites. To do such a thing I will have to tune my download lists to the maximum, thousands of requests will get wasted to find the subset that I have.

Also, I guess you don't know how the APIs behave. The file does not get downloaded with its information, that is a separate operation. The tool will only get the tags and add them to the files, no need to download each file.
