### ISSUE TITLE
Window lagging, Buggy search bar

### ISSUE THREAD

**Issue by Wyterra** [Bionus/imgbrd-grabber#2321]
After downloading the most recent update, Version 7.5.1, Grabber has effectively been broken. I can barely type anything in the search bar and some of the button are almost completely unresponsive or take several seconds to function.

**Comment by Bionus** [comment]
Are you using monitors or favorites automatic download?
The search field wasn't changed recently so there must be something slowing down Grabber in the background. And AFAIK, only monitors run in the background ATM.
