### ISSUE TITLE
Feature request: smoother video player looping

### ISSUE THREAD

**Issue by cyaoeu** [Bionus/imgbrd-grabber#2322]
**Is your feature request related to a problem? Please describe**

The video player doesn't loop smoothly, there's a black screen at the end of the video and a delay before resuming playback from the start. The gif player seems to loop fine.

**Describe the solution you'd like**

Upon reaching the end of a video it should seek to the start seamlessly instead of stopping, switching to a black screen, then playing back after a delay.

**Comment by Bionus** [comment]
I agree, but it seems to be a limitation with Qt video player.
The alternative would be to switch to another video player library, but that's a pain, or use a QML player (with their [flushMode prop](https://doc.qt.io/qt-5/qml-qtmultimedia-videooutput.html#flushMode-prop)), but that's not much better.

**Comment by cyaoeu** [comment]
Apparently QML with video.seek(0) in onStopped: should work but this is not a major issue so if it's not easy to fix it doesn't really matter.
