### ISSUE TITLE
pixiv login stuck on "connection..."

### ISSUE THREAD

**Issue by aymanA123** [Bionus/imgbrd-grabber#2326]
**Bug description**
when I try to log into pixiv using access and refresh tokens it doesn't work it gets stuck on connections and that's it.

after I get the access and refresh token and put them in their place and click 'test' it gets stuck on 'connection...' 
i tried it with different tokens but nothing worked.
it used to work for a while but recently it doesn't.

**Expected behavior**
log in like it used to instead of getting stuck on "connections..."

**Context**
(changed it from .ini to .log since .ini can't be uploaded here)  [settings.log](https://github.com/Bionus/imgbrd-grabber/files/6254903/settings.log)

[main.log](https://github.com/Bionus/imgbrd-grabber/files/6254891/main.log)

**System information**

- OS : windows 10
- Grabber version: 7.5.1

**Comment by Bionus** [comment]
I could indeed reproduce the issue (as well as some issues with infinite login loops, cf ac2eef48 / c852c234 /  b30faeaf).
Seems like they added a captcha protection to their login. Try going to their website and see if there's some Cloudflare or similar "captcha" cookie and add them to Grabber?

_PS: don't share your access and refresh tokens, those are equivalent to a password and can be used to access your account._

**Comment by aymanA123** [comment]
i've tried the PHPSESSID cockie and different vf cockies nothing worked.

**Comment by MiTereKun** [comment]
I've been using it for a year now [github.com/Tsuk1ko/pxder](http://github.com/Tsuk1ko/pxder) through [nodejs.org](https://nodejs.org/). It is updated in a timely manner and has never failed. I use a backup account, but it was not banned and never even kicked out of the system

**Comment by aymanA123** [comment]
> I have been using [github.com/Tsuk1ko/pxder](https://github.com/Tsuk1ko/pxder) through [nodejs.org](https://nodejs.org/) for a year nowI've been using. It is updated in a timely manner and has never failed. I use a backup account pixiv, but it was not banned and never even kicked out of the system

thx i'll use it as a temporary measure until pixiv in grabber is fixed.

**Comment by fanboy01** [comment]
@aymanA123 

If you want to download from pixiv, I recommend using https://github.com/Nandaka/PixivUtil2 instead.

It's another command-line program and you may have to tinker with a bit of settings to get it to work.

Fortunately though, the program instructions and support is in English unlike the programthat  MiTereKun linked above (no offense to MiTereKun or the maker of pxder)

**Comment by aymanA123** [comment]
> @aymanA123
> 
> If you want to download from pixiv, I recommend using https://github.com/Nandaka/PixivUtil2 instead.
> 
> It's another command-line program. Fortunately though, the program instructions and support is in English unlike the program that MiTereKun linked above (no offense to MiTereKun or the maker of pxder)
> np im pretty fluent in japanese that's why i didn't mention anything0
> In this program's config.ini, just put your login info along with a PHPSESSID cookie and you should be good to go.
> 
> I've been using this program for years and I have never once had pixiv ban my account or ip address.

thx for the input, i'll keep that in mind. it's been a while since i used pivivutil. The main reason why i stopped using it is because of grabber how convenient it is to just download and monitor your favorites.

does pixivutil have a monitor system or something similar that i could instead of the monitoring feature that grabber has ?

**Comment by mathus333** [comment]
for me it just says there is no valid source of the site

**Comment by ayoits0913** [comment]
Will this be fixed?

**Comment by aymanA123** [comment]
> Will this be fixed?

it's already been 2 days who knows anymore....

**Comment by Bionus** [comment]
> for me it just says there is no valid source of the site

The only source is their JSON API, which requires login.
So if the login failed, that's the result you get.

>  Will this be fixed?

> it's already been 22 days who knows anymore....

FYI, it's already fixed in [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) for the past 24 days, by the commits I linked in the first comment.

-----

As for Pixiv itself, PR are welcome, but seems like the fix is to simply set a proper User-Agent on the token refresh request, so it should be simple enough.
