### ISSUE TITLE
Download Tags metadata as txt or other formats

### ISSUE THREAD

**Issue by pxssy** [Bionus/imgbrd-grabber#2332]
**Is your feature request related to a problem? Please describe**

Another booru downloader had the functionality to also save tags in a txt named identically to the image, along with the image. With some code, this can be a rather crude but very useful way to search for tagged images. Currently there's no way to actually do this unless you included tags into the names of the images, which is quite unwieldly to say the least, being that most booru just tag as greedily as possible.

**Describe the solution you'd like**

Rip tags from the post while downloading image, save as txt, or maybe a more high tech format in sqlite. All i know is that without even the txt, no metadata is saved currently, and when the post is deleted or booru goes down, all gets lost.

**Describe alternatives you've considered**

Using back that downloader, but its been abandoned for sometime, i doubt it will be fixed. 

**Additional context**

For example https://danbooru.donmai.us/posts/3582852

the txt file could just be a simple one like

> feng\_ze
:o
1girl
ahoge
azur\_lane
bag
baltimore\_(after-school\_ace)\_(azur\_lane)
baltimore\_(azur\_lane)
black\_choker
black\_neckwear
black\_skirt
braid
breasts
brown\_cardigan
brown\_footwear
brown\_hair
buttons
cardigan
cardigan\_around\_waist
choker
cleavage
clothes\_around\_waist
collarbone
collared\_shirt
duffel\_bag
feng\_ze
full\_body
hand\_up
holding
holding\_phone
kneehighs
large\_breasts
loafers
looking\_at\_viewer
miniskirt
necktie
official\_alternate\_costume
official\_art
open\_mouth
phone
pleated\_skirt
school\_bag
school\_uniform
shirt
shirt\_tucked\_in
shoes
short\_hair
short\_sleeves
skindentation
skirt
solo
standing
thighs
transparent\_background
turret
white\_legwear
white\_shirt
yellow\_eyes

**Comment by sstabeler** [comment]
You can actually do this already. Check the options for the "seperate log files" options.

It's also now possible to save the image metadata to the image file, albeit that's a little imperfect, given that if the image is overwritten, so is the metadata. (When I get the chance, I plan to poke around in the code to see if that can be changed)

**Comment by kdoshere** [comment]
![Image](http://puu.sh/HxIVq/db5102fff0.png)

rating:%rating%
%all:includenamespace,excludenamespace=general,unsafe,separator=\n%

**Comment by pxssy** [comment]
Oh i didn't know!

So if i already have the images downloaded, will these be retroactively downloaded, or do i have to get both image and tags again?

**Comment by Bionus** [comment]
Seems like the question was already answered, so I'll close the ticket 😄 

> What does %all% include? Does it always include ambiguous tag stuff like artist, character, copyright, meta, and things that aren't exactly tags like score, mpixels, height, width?

Only tags. Meta-data is not included.

> author and authorid refer to the artist or the uploader to the boorus? I didn't include them my naming scheme because they appear to be empty strings currently.

Author is the uploader. You can use `%source%` if you want to investigate an image's actual source.

**Comment by YukiSakuma** [comment]
Bumping this cause I have some questions, how do you save tags `character:baltimore_(after-school_ace)(azur_lane)` but without 
the "character:" or any "x:" part?

**Comment by sstabeler** [comment]
drop the includenamespace bit if you don't want the namespace, as for the seperator, you want seperator:,%

**Comment by YukiSakuma** [comment]
> drop the includenamespace bit if you don't want the namespace, as for the seperator, you want seperator:,%

Thanks but the comma one won't work here's the output and the code
`6+girlsangryaqua eyesaqua hairaqua`

`
%all:,excludenamespace=general,unsafe,separator=;%
`
but for some reason using semicolon as a separator works but I need to use comma
Am using v7.5.1

**Comment by Bionus** [comment]
`,` is a special character in options since it is used as a separator for the options themselves ("general`,`unsafe").
You need to prefix it with `^` to use it directly.

Something like this should work:
```
%all:,excludenamespace=general,unsafe,separator=^,%
```
