### ISSUE TITLE
Images/Columns per page not respected on new source?

### ISSUE THREAD

**Issue by archivist-in-training** [Bionus/imgbrd-grabber#2336]
**Bug description**

Source; https://shadowcrest.booru.org/ - a board that runs off Gelbooru. To access, header is currently set to Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0.

Images per page set to 250 in the + options and the tools/options/source panel.

Result; 20 images per page, 2 columns.

**Steps to reproduce**

1. Add source, complete with custom user agent.
2. Search images; compare search results to Gelbooru, which displays image/column per page settings.

**Expected behavior**

Grabber displaying requested images/columns per page. Could it be a user-agent-related problem?

**Context**

This isn't an error with the program (I think) but either the board or the user-agent settings. I'm filing this as an issue because I'm curious if it's a known problem, possibly one with a work-around. Regardless, it remains low-priority.

**System information**

- OS: Win 8.1
- Grabber version: 7.5.1 (x64)

**Additional context**

Is there a way to exclude nsfw content when almost no images in the booru are tagged? Haha, probably a dream... Either way, thank you for all of your hard work. I appreciate any responses, but don't sweat it. Best.

**Comment by Bionus** [comment]
This is not an User-Agent issue, it's a Gelbooru 0.1 issue.
Older versions of Gelbooru unfortunately do not support changing the number of images per page, hence the result you're getting.
