### ISSUE TITLE
build.sh: Failed to detect your distribution's package manager.

### ISSUE THREAD

**Issue by whp199** [Bionus/imgbrd-grabber#2339]
building on Fedora 34 x86_64, cloned git repo and ran build.sh
Got this output:
```
$ ./build.sh 
Submodule 'cmake/cotire' (https://github.com/sakra/cotire.git) registered for path 'src/cmake/cotire'
Submodule 'cmake/qt-android-cmake' (https://github.com/LaurentGomila/qt-android-cmake.git) registered for path 'src/cmake/qt-android-cmake'
Submodule 'tests/src/vendor/catch' (https://github.com/catchorg/Catch2.git) registered for path 'src/tests/src/vendor/catch'
Cloning into '/home/eric/bin/imgbrd-grabber/src/cmake/cotire'...
Cloning into '/home/eric/bin/imgbrd-grabber/src/cmake/qt-android-cmake'...
Cloning into '/home/eric/bin/imgbrd-grabber/src/tests/src/vendor/catch'...
Submodule path 'src/cmake/cotire': checked out '391bf6b7609e14f5976bd5247b68d63cbf8d4d12'
Submodule path 'src/cmake/qt-android-cmake': checked out '5a62962dbe35e955374688461784ddb7f757a377'
Submodule path 'src/tests/src/vendor/catch': checked out 'f0dc4d9be078d21ccabcb0798f03c332a153f84f'
Failed to detect your distribution's package manager.

```

**Comment by sisco0** [comment]
Hopefully the new _Pull Request_ (#2340) would fix this. This has been tested under _Docker_ for `fedora:latest`.

**Comment by Bionus** [comment]
That PR should indeed fix this, thanks! 👍

**Comment by bandmaid** [comment]
Same problem on Void Linux with build.sh

`Submodule 'cmake/cotire' (https://github.com/sakra/cotire.git) registered for path 'src/cmake/cotire'
Submodule 'cmake/qt-android-cmake' (https://github.com/LaurentGomila/qt-android-cmake.git) registered for path 'src/cmake/qt-android-cmake'
Submodule 'lib/vendor/lexbor' (https://github.com/lexbor/lexbor.git) registered for path 'src/lib/vendor/lexbor'
Submodule 'tests/src/vendor/catch' (https://github.com/catchorg/Catch2.git) registered for path 'src/tests/src/vendor/catch'
Cloning into '/home/voidbox/Builds/imgbrd-grabber/src/cmake/cotire'...
Cloning into '/home/voidbox/Builds/imgbrd-grabber/src/cmake/qt-android-cmake'...
Cloning into '/home/voidbox/Builds/imgbrd-grabber/src/lib/vendor/lexbor'...
Cloning into '/home/voidbox/Builds/imgbrd-grabber/src/tests/src/vendor/catch'...
Submodule path 'src/cmake/cotire': checked out '391bf6b7609e14f5976bd5247b68d63cbf8d4d12'
Submodule path 'src/cmake/qt-android-cmake': checked out '5a62962dbe35e955374688461784ddb7f757a377'
Submodule path 'src/lib/vendor/lexbor': checked out '44db846ef41d33e20557af985af12c82840003a3'
Submodule path 'src/tests/src/vendor/catch': checked out '958944d27a2d2fb82aa008377bf4f8752f6b848e'
Failed to detect your distribution's package manager.`
