### ISSUE TITLE
Danbooru download hangs up

### ISSUE THREAD

**Issue by DarknestOne** [Bionus/imgbrd-grabber#2341]
**Bug description**
I'm trying to download a tag from danbooru (around 2000 images) and at random intervals download will just hang-up on one image, think for ~5 minutes with progress staying at fixed number, let say 43% (it's random), then it will drop to 0% and download this image and move on with the download untill it hangs-up again (can be in 1 image, can be in 10, can be in 50. Every time this happens in logs I see 
[Warning] [Qt][qt.network.monitor] Could not find the interface for the local address.

Pausing/Resuming the download resolves this with the additional warning in logs
[Warning] [Qt][default] QIODevice::read (QNetworkReplyHttpImpl): device not open

**System information**

- OS: Windows 10 x64
- Latest Release grabber 7.5.1

**Additional context**

I have a gold account at danbooru and logged in it with API key

**Comment by DarknestOne** [comment]
I should probably create a separate issue for this, but I'm experiencing behavior as in ticket #1331 when results return page 1 of ?

**Comment by Bionus** [comment]
>  [Warning] [Qt][qt.network.monitor] Could not find the interface for the local address.

This usually is caused by a proxy breaking in the middle. Although Grabber should be resistant to some extant.
Are you using a proxy?

**Comment by DarknestOne** [comment]
Yes, I'm using a self-hosted proxy on Hetzner servers, since Danbooru is blocked in my country
