### ISSUE TITLE
7.5.1. unable to enter tags

### ISSUE THREAD

**Issue by Wyterra** [Bionus/imgbrd-grabber#2342]
Whenever I try to type anything into the tag search bar, nothing shows up. Typing anything besides numbers will not work, and when I do type in numbers I can only type in a maximum of three things before I can type literally nothing else. Below is a gif of what I explained above. I'm spamming my keys but only the numbers are working, up to a maximum of 3, then I can't type anymore.

https://user-images.githubusercontent.com/81654627/115615385-e4234480-a2bc-11eb-85a0-f74007b0fce4.mp4

**Comment by Bionus** [comment]
Looks like the favorites tab?
In that case, this field is the page number, not some sort of search field.

You should go to (or create) another tab if you want to perform a normal search.

**Comment by gummykage** [comment]
Use a wildcard "*". Some sites for some reason is returning zero results without it.
