### ISSUE TITLE
Conditional file naming

### ISSUE THREAD

**Issue by fusedragon** [Bionus/imgbrd-grabber#2343]
More of a question but is it possible to create conditionals based on counts of say copyrights or characters? For example, if an image has more than 2 copyrights/characters then only save the first 2 copyrights/characters, or replace the portion of the file name with a certain word like "group".

There's the count operator but not sure if it's possible to fit the count outcome into the conditional.

**Comment by yami-no-tusbas** [comment]
It is under options -> save -> tags -> copyright/characters.
Replace "**If more than n tags**" by the number you want, then select replace all by "group", note that if more than will result in for exemple with 3 : "copyright1 copyright2 copyright3 copyright4" will be replaced by "group" as you need more than the number indicated.
![Grabber_21-04-23_16h04m41s](https://user-images.githubusercontent.com/3921598/115883073-abff3b80-a44d-11eb-8677-a6f5e1e23278.png)

If this solve your problem don't forget to close this issue.

**Comment by fusedragon** [comment]
Welp totally missed that, thanks! Also managed to figure out stuff related to folders so gonna close this issue.

**Comment by fusedragon** [comment]
Actually is it possible to do so with conditionals? I would like to save images by folders with artist name (1 artist only), but have file names which display for example 2 artists and +%count%.

**Comment by Bionus** [comment]
Currently, I would say it'd be impossible without JavaScript.
The current filename condition grammar only support boolean logic and the AND / OR operators. I guess it could be possible, but only with a rework of the current filename grammar.

But you could do this with JavaScript conditions, although I haven't measure the performance yet.
Just prefix your condition with `javascript:` and make sure your expression returns a boolean.
Note that it works only using the "conditional filenames" in the settings, it doesn't seem to work directly in filenames (with the `<if?then:else>` syntax).

**Comment by fusedragon** [comment]
Ok thanks, will try and play around with it then.
