### ISSUE TITLE
Negative total in download list cause loading fail.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2345]
**Bug description**

Having a negative limit for the "total" in a download list (.igl) make loading of said list to fail.

**Steps to reproduce**

1. make a download list for e621 (should be the same with other board with no clear image limit given)
2. Save the list, then delete all entries.
3. Load the list from the igl file
4. Empty list, data are in the igl file, grabber just fail on loading them when " **"total": -1** " is in a item.

**Expected behavior**

Load correctly the list.

**Context**

log are still not helpfull here since they only indicate the number of tasks loaded : "[23:18:00.139][Info] Loading 0 downloads", thoses logs really need improvement.

**System information**

- OS: Windows 10
- Grabber version: happens on 6db94190 and b30faeaf, should happen on every recent version.

**Additional content**
The concerned igl file, grabber image limit was "all" on the dispay before saving and will fail to load it proprelly.
[all 621.igl.txt (remove ".txt" before use ;) ](https://github.com/Bionus/imgbrd-grabber/files/6368173/all.621.igl.txt)

**Comment by Bionus** [comment]
Crap how could I have missed that 😅
I  just pushed a fix, thanks for the report.

I also added a bunch of logs in case of errors in the future, since as your said those were severly lacking.

**Comment by brazenvoid** [comment]
I did mention this issue on the commit of the feature. [Commit](https://github.com/Bionus/imgbrd-grabber/commit/8760b2288f5a722f5da6875d1e22d8e265fff1cc)

Regardless, its getting fixed.

**Comment by Bionus** [comment]
> I did mention this issue on the commit of the feature. Commit

I guess I don't get the same notifications for comments on commits directly so I must have missed it.

> Is this commit allowing the image limit to actually be enforced for batch downloads?

Not sure what you meant by that. If you set a limit to 100 and images/page to 200, it should already limit results to 100 for example. The special case being galleries getting counted differently. Is that not the case today?

**Comment by brazenvoid** [comment]
@Bionus No, its fine. it was a question before trying the feature. The second comment was after trying it, haha.
