### ISSUE TITLE
Recent downloading error regarding the unmentionable site

### ISSUE THREAD

**Issue by a7hael** [Bionus/imgbrd-grabber#2346]
**Bug description**

Log tab:

Above all ok
[Warning] ["the unmentionable".com][Html] Uncaught exception at line 116: TypeError: Cannot call method 'replace' of undefined
2 following lines without errors ( "_Loading image from_", "_Loading image details from_" )
[Warning] ["the unmentionable".com][Html] Uncaught exception at line 116: TypeError: Cannot call method 'replace' of undefined
2 following lines without errors ( "_Loading and saving image from_", "_Image received from_" )

**Steps to reproduce**

1. Have settings such that opening an individual image automatically downloads it
2. Enter keywords to the search
3. Open an image from the results
4. Image finishes downloading - gives expired link image
5. Move to Log tab
6. See the above bug description

**Expected behavior**

* No warning
* The sample image or the original instead of expired link image

**Context**

It seems the unmentionable site recently changed how its images are loaded on their site. Before, once you'd click on the image in the browser, it would enlarge the image to its original sizes within the same page. Now it opens the original sized image itself as the page. There was a time many years ago when they already had it this way, but back then I didn't use imgbrd-Grabber. No idea if this is related to the bug and/or the expired link image.

**This is very important**

I logged into the site in the browser, went to the image I had viewed in Grabber and had received the expired link image of. In the browser, by clicking on the image, I'm given the original image, no expired link. When I compare the link that the Grabber used to load the image, the only difference lies at the end of the link:

.jpg?e=1619230187&m=Jed2J8tnxYIreTWdXmMkPw   (not expired - and wont expire ever)
.jpg?e=1619229932&m=lqYiNeu6DaFhEa6YK4IHIg     (expired)

I put the links to a Tor browser and exactly the same results, the one that was expired loads the expired image, the one that wasn't, loads the image - my IP should be different, cookies different and I'm not logged in.
I assume the ?e= number is a timer, query timer and m= could be an id of some sort or the timer value encoded, who knows.
Since it has a timer, I can assume that it gets an OK or NOK as the links are generated.
But I'm not 100% sure because of the warning lines in the Bug description.
If its not about the warning line, then the unmentionable site somehow knows that the image link requests are coming from imgbrd-Grabber. Perhaps its related to the [GAnalytics] cid value, maybe there is another id attached to the image requests from Grabber. Perhaps I need a reinstall to get a different appid or use another version.

**System information**

- OS: Windows 10
- Grabber version: 7.5.1 (x64)

Would appreciate a glance at this or a discussion, any kind of help :D
I call it unmentionable since I've understood there is some sort of a reason why its not supported on imgbrd-Grabber by default.

**Comment by a7hael** [comment]
Ok I think I got a clue what might be happening, but I'm making a big assumption about imgbrd-Grabber.
I'm assuming that the way imgbrd-Grabber gets the final image link from the page code is that it 
1) locates the preview src
2) copies the src value and removes /preview/
3) and doesn't change anything else, which seems to be the reason atm why the original image links imbrd-grabber generates are .jpg even if the real original is .png
     (but I don't know why it recognizes .webm when the previews are .jpg - still leading to expired links though)

**I am suspecting that as the src value is parsed, the final image url that grabber uses will include the same e= and m= values that the preview link had and it seems they really need to match now with the individual request of the original image. - assumption ofc**

On a side note, when I click on the image in the browser (from the 20 images search result page), the selected image opens in a new tab as the sample-image view page. Inside the sample-image page code, the original's link is available and does not expire when copy-pasted.

This puzzle is exciting :D

**Comment by a7hael** [comment]
Another note.
The e= value doesn't change every time I open the image on their website, however it changes when the search list page is reloaded.
So I assume it is a timestamp when the image is queried.
The m= value kept changing every time I

**Comment by a7hael** [comment]
I can rule out the Grabber version to an extent. Tried a couple older versions, They all give the same warning issue and the expired link image.

**Comment by urzuse7en** [comment]
It's their host that causing some slow-downs, you can read more on their forum. Even the paying clowns are angry.

Until it gets resolved the dev put some magic in the cookies and changed some other things too. Give it some day until it recovers, **then** find a solution.

**Comment by a7hael** [comment]
> 
> 
> It's their host that causing some slow-downs, you can read more on their forum. Even the paying clowns are angry.
> 
> Until it gets resolved the dev put some magic in the cookies and changed some other things too. Give it some day until it recovers, **then** find a solution.

Hehe :D thanks for recognizing the unmentionable site.
I follow their forum. But from the dev's comments I don't have as much trust that it is just the host issue or that it will return to what it used to. The dev's post a day ago mentioned that in addition to the "host issues", they are working on something that will solve their speed issues for the future. I think we might need to prepare for creating a new method, unless it still has something to do with the aforementioned Bug description in the imgbrd-Grabber's code. I'm mostly suspecting that the Devs of the unmentionable site are picking out the identifying characteristics of the grabber.

**Comment by Desk5103** [comment]
just read this issue #2333, I fixed it here (temporary dirty solution but works perfectly fine)

1. download the sankaku folder from [here](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826275583) and replace it with the current one in "C:\Users\your uesrname\AppData\Local\Bionus\Grabber\sites"
2. [set the source to json](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826265346)
3. and now to login you have to do [this](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826333230)
4. and ehh something extra, u can [download posts without an interval now](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826560861)
