### ISSUE TITLE
Grabber not retrieving gif/mp4 when source set to Twitter

### ISSUE THREAD

**Issue by Azuriye** [Bionus/imgbrd-grabber#2349]
**Bug description**

When I set to search up for a username that has gif/videos on their account on Twitter it only shows me images instead of gifs/videos. 

**Steps to reproduce**

1. Search up for @5114Ave on Grabber and on Twitter for comparison.
2. You can see on Twitter the content labelled as gif are not to be seen anywhere at all in Grabber. But instead, you'll only see images loaded up in Grabber which is the same as Twitter.
3. Error mentioned from step 2.

**Expected behavior**

To let the user know that grabber actually shows files that are marked as a gif from Twitter and to even load up videos upon searching a username from Twitter via Grabber's search box and making the user download the .gif or .mp4 if an XYZ account is set to monitor.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/75412786/116074985-78b5ea00-a6a3-11eb-8e13-55b4447e4252.png) This is grabber's results.

![Untitled](https://user-images.githubusercontent.com/75412786/116075196-b450b400-a6a3-11eb-9d0b-9e983ed721b2.png) This is twitter's result

**System information**

- OS: Windows 10 64bit
- Grabber version: 7.5.1 - Nightly

**Additional context**

I'm not sure whether grabber is supposed to work like this when previewing images since when I simply leave an account for monitoring I noticed that all content ending with an image extension or a video extension like .mp4 gets downloaded but content that is marked as GIF on Twitter are not getting downloaded...? Although it will be better as a whole if Grabber could at least preview the GIF files and Video's which are there on a user's Twitter account and maybe even download them instead of guessing whether the user's video and gif files get downloaded if I directly hit Get All or setting up a monitor tab for it kind of guesswork which is not really required.

**Comment by Bionus** [comment]
I can reproduce on 7.5.1.

But what's strange is that I'm getting proper results on my developer version:
![image](https://user-images.githubusercontent.com/882719/116321483-6d091700-a7ba-11eb-9916-21400d9433e7.png)

I'll check what are the differences and push a fix.

**Comment by Bionus** [comment]
Weird. When using my  own API key, I get the proper results.
When using Twitter APÏ keys found [there|https://gist.github.com/shobotch/5160017], the API calls do not return details on videos (no `extended_entities` for those).

And I can't really share those because they have rate limits (unlike Twitter's).

**Comment by Azuriye** [comment]
Hmm, maybe it's been like this for a while? I guess nothing can be done other than either forcing users to use their own keys or just ignore it and use the one's Twitter provided. Thanks for the heads-up.
