### ISSUE TITLE
Blacklist not working; Android Bug

### ISSUE THREAD

**Issue by FroggyFriend** [Bionus/imgbrd-grabber#2350]
I was browsing image results and had the tags "blood, death, and gore" blacklisted as separate entries, yet images with these tags still appeared.

Android Version: 9
Grabber Version: 7.5.1 (APK Version)

**Comment by Bionus** [comment]
When you said you "had the tags "blood, death, and gore" blacklisted as separate entries", do you mean on multiple lines?

Each line is one blacklist, where each tag correspond to an "AND" search. So if you only had one line with those three tags, images would need to have all three tags to be blacklisted.
