### ISSUE TITLE
Blacklist not working with accented character tags

### ISSUE THREAD

**Issue by waitingmoon** [Bionus/imgbrd-grabber#2353]
![blacklistgrabber](https://user-images.githubusercontent.com/16256443/116508077-8796d980-a8fb-11eb-893f-d9ae110a1eb8.png)

I added pokémon_(species) to the blacklist, but it is not working. I opened blacklist.txt in AppData with an external editor and fixed the garbled text, but it still does not work.

**Comment by Bionus** [comment]
Indeed, I could reproduce this. It seems to be caused by HTML entities (in this case `&eacute;`) not being in the correct encoding.
