### ISSUE TITLE
Image Not Found

### ISSUE THREAD

**Issue by Xbioes** [Bionus/imgbrd-grabber#2354]
Whenever I try to search for an image on anime-pictures.net the preview is there but whenever I go to save the image, it says that the image is not found and can't be saved as it remains pixilated. I tried to connect to my account to see if that may have been the issue but while it says that its connected by the test, the image still won't be found. Checking the details it says that the rating, author, date, filesize, and source are unknown and prevent it from being downloaded. Is the connection wrong or did I mess something up?
![unknown](https://user-images.githubusercontent.com/83472460/116741978-61853e00-a9bc-11eb-9f73-b7ab38af9554.PNG)

**Comment by Bionus** [comment]
Are you using the latest version?

And did you override the source settings?
![image](https://user-images.githubusercontent.com/882719/118520975-d4bbdd80-b73a-11eb-944e-5fb829e40641.png)

Make sure to use the default ones or at least give JSON priority.
