### ISSUE TITLE
AVG Detects This App As Ransomware

### ISSUE THREAD

**Issue by ArmagdoGaming** [Bionus/imgbrd-grabber#2355]
![image](https://user-images.githubusercontent.com/52860974/116919971-5e0ae480-ac52-11eb-8f0d-846f610a87a7.png)
Every time I try to download anything, I get this. It worked the first time, but this is the second time that I have opened the app, and this problem has started appearing.

**Comment by Bionus** [comment]
Seems like you marked that folder as "protected"?
If you did it yourself you might want to unprotect it then? Or allow Grabber to edit files in there.

https://support.avg.com/SupportArticleView?l=en&urlName=Use-AVG-Ransomware-Protection

**Comment by ArmagdoGaming** [comment]
1. Yes, I tried to download a new image.
2. Is it normal for the folder to be set to "protected" by itself? Because, I have not changed anything about that folder. It was a folder created to put everything downloaded with Grabber in.
3. I just ran a scan on the folder, and everything seems fine. Maybe it's an AVG problem?
Thanks for the help.

**Comment by Bionus** [comment]
> Yes, I tried to download a new image.

So it's strange, maybe AVG also protects from new files  and not only overwrites.

> Is it normal for the folder to be set to "protected" by itself? Because, I have not changed anything about that folder. It was a folder created to put everything downloaded with Grabber in.

No idea. I guess AVG just protects everything by default?

> I just ran a scan on the folder, and everything seems fine. Maybe it's an AVG problem?

Yeah this isn't about viruses, it's just trying to block software from touching your files, not necessarily put a virus or malware in there.
