### ISSUE TITLE
can't get pixiv to work 

### ISSUE THREAD

**Issue by redbullman1232** [Bionus/imgbrd-grabber#2359]
It says {"error":{"user_message":"","message":"Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_request","reason":"","user_message_details":{}}}
ive tried everything and it doesn't work

**Comment by af8662** [comment]
seems that you have to login in to get the results

[try to see this](https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde)
with the python script help, enter your `access_token`and`refresh_token` to log in

I use it to solve the problem and get images successfully
(with a tag like user:USERID or bookmarks:USERID)

**Comment by af8662** [comment]
Well, I later tried to download images by the `Get all` button, but its **NOT** work for me.
It just show `Logging in, please wait...`, and nothing happened.
I can download by Single image, however. (i.e. the `Get selected` button)
