### ISSUE TITLE
Is there someway to safe only a few generic tags from safebooru?

### ISSUE THREAD

**Issue by gummykage** [Bionus/imgbrd-grabber#2360]
When you do the %all% the list of tags is too long. Is there some way to safe a few of the tags?

**Comment by fusedragon** [comment]
You can use custom tokens and add in the tags you want then insert the token into the file name e.g. %bride% %md5%.%ext% where bride is the name of the token.

Not sure if it's a bug but the tags come out without spacing in between though. In the meantime you can add the tags in the file name individually e.g. "bridal_veil" "wedding_dress" %md5%.%ext%

**Comment by Bionus** [comment]
Yes, as stated the best option if you want a "whitelist" of tags for your filename is to use a custom token.
If you want a "blacklist" instead, you can add the tags you don't want to the ignore list (or right click > ignore).
