### ISSUE TITLE
Is there a way to get a post's parent id?

### ISSUE THREAD

**Issue by af8662** [Bionus/imgbrd-grabber#2361]
**Is your feature request related to a problem? Please describe**
No
I can search with a tag like `parent:ID` (e.g. `parent:any` on http://chan.sankakucomplex.com/ )but I can't get this attribute from a post
I have tried to use `%parent%` `%parent_id%` `%child%` etc. None of these seem to work.

**Describe the solution you'd like**
like the patterns I used above, add some tokens that can get the parent attribute of the post.
So I can use a filename format like `%parent_id%-%id%.%ext%`

**Describe alternatives you've considered**
use "conditional filenames" with tag `parent:ID`, but I am not yet familiar with the use of "conditional filenames".
If someone could tell me how to do this with it, i would be very appreciate.

**Comment by Bionus** [comment]
The token in Grabber is `%parentid%`, maybe you can try that.
But note that since Sankaku isn't officially supported, it might not work for this source in particular.

Also, since most images don't have a parent, you might want to use conditionals for it, like `<%parentid%->%id%.%ext%`.
