### ISSUE TITLE
 The sources do not appear

### ISSUE THREAD

**Issue by tevale1216** [Bionus/imgbrd-grabber#2362]
Since the new version the sources do not appear, therefore no image is loaded and neither are the tags.

I've tried placing them manually but it doesn't work for me either.

![Sin título](https://user-images.githubusercontent.com/83770259/117309702-48f7a680-ae48-11eb-9599-10926c48e4ae.png)

**Comment by Bionus** [comment]
Closing as duplicate of #2396
