### ISSUE TITLE
 Searching on pixiv doesn't work

### ISSUE THREAD

**Issue by kikodigo** [Bionus/imgbrd-grabber#2368]
**Bug description**

I was never able to use pixiv as a research source, it always gave an error.
I didn't know the syntax of the search until I found out that it was "User: User_id", even so I still can't find it.
I have several errors in the log

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/6466004/settings.txt)

My main.log have 47mb
![image](https://user-images.githubusercontent.com/84079289/117973133-632afc00-b302-11eb-8063-de10ea5e4b31.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/84079289/117973204-78078f80-b302-11eb-9190-a0a086532202.png)

**System information**

- OS:  Windows 10 20h2
- Grabber version: 7.5.1
![image](https://user-images.githubusercontent.com/84079289/117973299-98374e80-b302-11eb-8eb4-a930dd0cc2bf.png)

**Comment by jack652** [comment]
i can't download from pixiv too

**Comment by mathus333** [comment]
I think you need to login to pixiv through the source options first. But it isn't like gelbooru's, it asks for something called an access code and a refresh code instead of username and password. No idea how to find those

**Comment by 2yr434hgd7fy384** [comment]
You can use the script and follow the instructions [here](https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362) to get an access token and refresh token. Using those as well as the consumer key and secret I already had gave me a successful connection. Annoyingly though it doesn't save the access and refresh tokens when I exit Grabber, so I have to put them in every time I open it.

**Comment by kikodigo** [comment]
I'm sorry, but I didn't understand anything about the tutorial on this link.

> You can use the script and follow the instructions [here](https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362) to get an access token and refresh token. Using those as well as the consumer key and secret I already had gave me a successful connection. Annoyingly though it doesn't save the access and refresh tokens when I exit Grabber, so I have to put them in every time I open it.

**Comment by headandtoes1** [comment]
I did not get anything either.

**Comment by anonn123** [comment]
Same, I didn’t get the tutorial at all. It lost me on like step one. Heck it says open the command menu; where and how? And it gets worse from there

**Comment by Bionus** [comment]
On the latest version you  can just  switch to the OAuth2 PKCE login in Grabber Pixiv settings and just click "Test".

**Comment by kikodigo** [comment]
[13:15:58.774][Info] [www.pixiv.net] OAuth2 HTTP handler listening on port 58923
[13:15:58.774][Info] [www.pixiv.net] Login with OAuth2 via browser https://app-api.pixiv.net/web/v1/login?client=pixiv-android&client_id&code_challenge=vF1m2-hj21_GyagPzvgKC5lYfNz0A6HpWSNxKIb2vlA&code_challenge_method=S256&redirect_uri=http://127.0.0.1:58923/&response_type=code&scope&state=wwYX0GyI
[13:16:22.429][Warning] [Qt][qt.networkauth.replyhandler] Error transferring https://oauth.secure.pixiv.net/auth/token - server replied: Bad Request
[13:17:37.346][Info] Saving sources...
[13:17:37.346][Info] Updating checkboxes.

still not working
