### ISSUE TITLE
how do i make it so if i get the same image multiple times from multiple-imageboard searches, grabber only downloads one of them ?

### ISSUE THREAD

**Issue by jack652** [Bionus/imgbrd-grabber#2370]
how do i make it so if i get the same image multiple times from multiple-imageboard searches, grabber only downloads one of them ?

**Comment by Bionus** [comment]
You should use the MD5 duplicate list:
https://bionus.github.io/imgbrd-grabber/docs/faq.html#how-to-avoid-duplicates

Set it to "Don't save" if you don't want any duplicates.
