### ISSUE TITLE
How to login to pixiv?

### ISSUE THREAD

**Issue by YukiSakuma** [Bionus/imgbrd-grabber#2371]
I just updated my grabber (7.3.2) to latest version because of pixiv they changed their api but now how do you login?
Before it just requires your username and password, but the pixiv login now requires "Access Token" and "Refresh Token" instead. How to get these variables?

**Comment by Bionus** [comment]
If you use Nightly, you can try the "OAuth2 (PKCE)" login which will do a proper login using the Pixiv website.

Otherwise, you can use scripts found online to get this token:
https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde
