### ISSUE TITLE
e621 search throws "no results"

### ISSUE THREAD

**Issue by Yama-K** [Bionus/imgbrd-grabber#2376]
**Bug description**

**Steps to reproduce**

**Expected behavior**
- See search results

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/6548799/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/6548801/settings.txt)

**Screenshots**

![Grabber_7dx8gV8m6S](https://user-images.githubusercontent.com/26037681/119710416-0170a300-be67-11eb-872f-33768e8c3ef6.png)

**System information**

- OS: Windows 10
- Grabber version: 7.5.1

**Additional context**

I'm gonna assume that this has something to do with the captcha on e621
![unknown](https://user-images.githubusercontent.com/26037681/119710818-7e9c1800-be67-11eb-807c-f6a5823d3d45.png)

**Comment by TotemSP2** [comment]
Same. And my site login isn't working either. says
![Grabber_2021-05-27_21-59-35](https://user-images.githubusercontent.com/16230991/119822296-d6558480-bf36-11eb-87e4-e835e0c71e7a.png)

**Comment by lionbaiter** [comment]
definitely due their new captcha. how annoying

**Comment by sbobbo** [comment]
Same here...

**Comment by yami-no-tusbas** [comment]
It is fixed now, issue can be closed, error was on e621 side. You can have bypassed the capcha by validating one on your browser then grabber would have been fine for 1 hour or so.

**Comment by Yama-K** [comment]
Bypassing it by filling the capatcha on the site didn't work before, but I'm closing this as things work now.
