### ISSUE TITLE
Page jumping results in crash

### ISSUE THREAD

**Issue by theraven99** [Bionus/imgbrd-grabber#2379]
Any time I try to jump to a certain page, say from page 1 to page 10. It crashes.

**Comment by Bionus** [comment]
I can't reproduce this.
Do you have more details on how to do so?

What I tried:
1. Start Grabber
2. Search something random
3. Wait for results to load
4. Increase page number to 10
5. Click "search"
6. Results showed up, no crash

**Comment by theraven99** [comment]
Ver. 7.5.1
Sources: 
- api.twitter.com
- danbooru.donmai.us
- derpiboru.org
- e621.net
- gelbooru.com
- rule34.paheal.net
- rule34.xxx
- tentaclerape.net
- www.zerochan.net
- yande.re

20 images per page
1 column 

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/6627857/settings.txt)

Steps were exactly what you did, experienced a crash once more.

**Comment by theraven99** [comment]
Update: I removed api.twitter.com from the source list and DID NOT experience a crash
