### ISSUE TITLE
Token comparing with conditional filename

### ISSUE THREAD

**Issue by Laesx** [Bionus/imgbrd-grabber#2382]
I have been searching for a while and testing with conditional filenames, couldn't get it to work and didn't saw this anywhere so i'll just ask.
Is it possible to do token comparisons with conditional filenames? 
Basically do something like: "If %search1% is not equal to %character%" condition is met and the file gets saved with the set filename and directory.
Also I noticed that you can add conditional filenames but you can't delete the entries
![Grabber_ZS7Jyn71zJ](https://user-images.githubusercontent.com/51269470/121510563-0fd2c900-c9e8-11eb-934a-6f5b8f8d669a.png)

**Comment by Bionus** [comment]
You can do comparison with constant values, but not with other tokens.
Such as `search:some_search` but you can't do `search:%another_token%`. What are you trying to achieve exactly? Maybe there's some simpler alternative.

> Also I noticed that you can add conditional filenames but you can't delete the entries

If you leave everything empty they'll be deleted, but yeah not the best UX.

**Comment by Laesx** [comment]
> What are you trying to achieve exactly? Maybe there's some simpler alternative.

Basically what I wanted to do is: when %search_1% doesn't matches the %character% of the image it would be sent to another folder entirely.
