### ISSUE TITLE
rule34.xxx images don't load in

### ISSUE THREAD

**Issue by ReSon4nce-Tr** [Bionus/imgbrd-grabber#2384]
The thumbnails load but when I click one, the actual full-size image is not being loaded in. Can't save either.

[Screenshot](https://user-images.githubusercontent.com/85695469/121554834-c5b30d00-ca12-11eb-93f6-26a2a57038ba.png) (**NSFW**)

**Comment by tg4f34** [comment]
I have it too, it seems to me that everyone has it

**Comment by RighteousAnger** [comment]
+1 The only way I could properly view or save is when I manually reload the image

**Comment by Demagole** [comment]
![image](https://user-images.githubusercontent.com/60618273/121613483-e011d880-ca5c-11eb-8025-54f279955201.png)
Log Image to further the issue. It probable seems it's not grabber fault but the R34 API.

**Comment by Bionus** [comment]
It seems to be caused by a new Cloudflare ant-bot protection when loading image details.

**Comment by Bionus** [comment]
Note that this seem to only happen on image details pages.

You might want to load the tag database to avoid having to load those, or download the already-generated one here:
https://github.com/Bionus/imgbrd-grabber/releases/tag/tag-databases

A filename not relying on tag types would also solve the issue but is not ideal.

**Comment by Demagole** [comment]
Problem is event tag loader isn't working 
![image](https://user-images.githubusercontent.com/60618273/121786299-46167100-cbbf-11eb-97de-790124281b02.png)
So I guess the only option is to download the existing DB.

**Comment by Bionus** [comment]
Yeah it doesn't work in the latest release, it's been fixed in [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) though.

**Comment by Frostwyn** [comment]
Disabling the html source in the rule34.xxx site options fixed the issues on my end.

**Comment by Bionus** [comment]
> Disabling the html source in the rule34.xxx site options fixed the issues on my end.

Yes, but you might meet issues  with tag types not being properly recognized (e.g. %artist% always being empty/"unknown").

**Comment by Frostwyn** [comment]
> Yes, but you might meet issues with tag types not being properly recognized (e.g. %artist% always being empty/"unknown").

True, I do get that problem instead. It's mitigated a bit for me by using %search% instead and only downloading by artist.

**Comment by Bionus** [comment]
You can also fix this by using the tag database instead.
Although it will only work with tags in said database (the downloadable one only contain tags with more than 100 images).

**Comment by Frostwyn** [comment]
> You can also fix this by using the tag database instead.
> Although it will only work with tags in said database (the downloadable one only contain tags with more than 100 images).

It wouldn't work at first until I copied over a tag-types.txt file from the gelbooru version. Rule34.xxx didn't have one for some reason. Either way, the Rule34.xxx source recognizes which tags are copyright/character/artist now.

**Comment by Valenthyne** [comment]
So, I've been encountering the same issues with this source the past few days, but as of now, images are viewing and saving appropriately. I've tried this on both the release and Nightly versions. I no longer experience the same "Service Temporarily Unavailable" error in the log either.

Are things back to normal for anyone else? It's possible they made some changes behind the scenes and lowered whatever heightened protections were in effect. Opening an image in my browser also no longer shows the bot check splash.

**Comment by hentaiwhite** [comment]
Yeah, currently is back to normal

**Comment by VeggieJay** [comment]
Downloaded nightly and still having issues

**Comment by Bionus** [comment]
This is caused by the Cloudflare protection.
The best solution is to use the tag database that generates much less requests to the protected endpoint. Either download the automatically-generated one, or generate one yourself with the tag loader.

In the meantime, I'll close this issue since Grabber can't go around Cloudflare at the moment.

**Comment by teeber** [comment]
so this is not for imagus? oh fuck, how did i get here...
