### ISSUE TITLE
Add data to images exif

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#239]
**What is your suggestion for the program?**

I would like data information to be stored in the images exif data. This is much better than putting information in the filename.

**What version of the product are you using? On what operating system?**

v3.3.0 windows server 2008

> Original issue reported on code.google.com by `shao...@gmail.com` on 7 Jun 2013 at 9:02

**Comment by Bionus** [comment]
See issue #258
