### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by sxocker** [Bionus/imgbrd-grabber#2392]
![image](https://user-images.githubusercontent.com/30538198/122342681-24402580-cf02-11eb-83c6-ccee949e8be8.png)

**Comment by Dethkiller15** [comment]
Have you tried restarting the program and if not, your computer and seeing if you can connect to those sites normally?

**Comment by Bionus** [comment]
Hello

Can you give more details, such as your logs?
Make sure your proxy settings are correct as well, if you have one.

And as suggested above, check in a browser whether you can access those sites normally.
I'll close the ticket in the meantime.
