### ISSUE TITLE
Suggestion : Indicate the user when a monitors return empty.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2394]
I love monitors, but sometimes they are dumb, the best exemple would be if a tag change on the board level, the monitors will have no result, it should be able to tell it.

exemple with a working tag : 

`[13:00:29.599][Info] [gelbooru.com][Xml] Parsed page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=TAG: 20 images (20), 0 tags (135), 19269 total (19269), 964 pages (964)`

As we see, there is 20 images on the given page, 0 tags, a total of 19269 images in total for this tag, and 964 pages of results, this is fine, and it work. Now let's see a tag that do not work : 

`[13:03:45.562][Info] [gelbooru.com][Xml] Parsed page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=TAG_THAT_DONT_WORK: 0 images (0), 0 tags (0), -1 total (0), 0 pages (0)`

Grabber see that the page return absolute zero, it should warn the user, maybe put the line in red, or where there is a "zZz Icon put an "error" icon ? So the user can see that a monitors has something wrong ? Then the user would be able to test the tags (or combinaison of) and try it on the board(s) to see what went wrong. At least in the log maybe add something like : 

```
[13:03:45.562][error] [gelbooru.com][Xml] Parsed page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=TAG_THAT_DONT_WORK: 0 images (0), 0 tags (0), -1 total (0), 0 pages (0) with no result
[13:00:44.751][Info] 99/103 monitors completed, see logs for errors
[13:00:44.752][Info] Next monitoring will be in 3071 seconds
```

**Comment by Bionus** [comment]
Sounds good. Although showing this in the logs is not user friendly, so I think adding a new column to the monitors table would be better. Those can be hidden anyway.

**Comment by yami-no-tusbas** [comment]
It's alive !

And it work great, I have found : 
1 typo (missing letter)
2 typos (missing space)
2 request error ("tag1 tag2 -tag1" xD)
1 artist (removed from board)
2 artists (that have been renamed)

7 corrections, 1 task less for the joblist Thx to this feature !

Nice work @Bionus !
