### ISSUE TITLE
Support for image boards that accept "next" and "prev" parameters rather than a "page" number

### ISSUE THREAD

**Issue by jamesWalker55** [Bionus/imgbrd-grabber#2395]
**Is your feature request related to a problem? Please describe**

I am attempting to add support for Sankaku Channel, however their new API does not query posts with a page number, but rather some sort of "next" and "prev" identifier:

```json
{"meta":{"next":"2c897e4ccab58194caa5c1d9dc74d4cd","prev":"b392e97402ae595fc69c3dbd77a0a734"},"data":[
```

These identifiers would then be passed as query parameters to get the next/previous page:

```
https://[sankaku channel]?next=2c897e4ccab58194caa5c1d9dc74d4cd&...
```

I took a look at [the documentation](https://bionus.github.io/imgbrd-grabber/docs/sites/source.html) but there is only support for direct pagination. Is it possible to add support for next/prev parameters instead of pagination?

**Describe the solution you'd like**

~In Grabber, the user only goes forward/backwards one page at a time, there is no way to skip pages (as far as I know anyway). Next/prev parameters wouldn't be too different from how pages are handled currently.~ Since Grabber allows jumping to pages directly, I'm not sure how next/prev parameters would be implemented. Perhaps the page control can be disabled for sites that do not support pagination.

**Describe alternatives you've considered**

Maybe the API can be more flexible, allowing site sources to have their own configuration and rules to fetch post data.

**Additional context**

nil

**Comment by Bionus** [comment]
This is actually already supported.

If you look at the documentation, you'll see that a `previous` parameter is passed, giving some information about the previously loaded page:
* The page number
* The max image ID on that page (and max+1)
* The min image ID on that page (and min-1)

Those values allow to support prev/next URL parameters for most sources, as long as there's no page jumping.

There's actually a JS helper function called `Grabber.pageUrl` in `helper.ts` that handles all that, detecting if you are above the page jumping limit (usually page 800 or page 1000), and if so and the previous page is N+1 or N-1, use the max ID or min ID:

```js
Grabber.pageUrl(query.page, previous, opts.loggedIn ? 1000 : 50, "page={page}", "prev={max}", "next={min-1}");
```
