### ISSUE TITLE
No results, tags and sources

### ISSUE THREAD

**Issue by tevale1216** [Bionus/imgbrd-grabber#2396]
No sources and no tags appear, the only font that appears is deviantart, I tried to place the fonts but it doesn't work.

[main.log](https://github.com/Bionus/imgbrd-grabber/files/6703019/main.log)

![Sin título](https://user-images.githubusercontent.com/83770259/123123330-5ecb2600-d40c-11eb-81b4-1d51bab3f1b3.png)

MSI 
Processor Intel (R) Core (TM) i7-10750H CPU @ 2.60GHz 2.59 GHz
Installed RAM 16.0 GB (15.8 GB usable)
System type 64-bit operating system, x64 processor

Windows 10 Home Edition
Version 21H1
Installed on 03/14/2021
OS Build 19043.1052
Windows Experience Feature Experience Pack 120.2212.2020.0

**Comment by Bionus** [comment]
How did you install the program?
Is the `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites` directory empty or almost?

**Comment by tevale1216** [comment]
![Sin título](https://user-images.githubusercontent.com/83770259/123871031-c562af00-d8f8-11eb-8238-751f1897d9f6.png)

**Comment by tevale1216** [comment]
I solved it, uninstall the program and delete the sites folder.

**Comment by Bionus** [comment]
Very strange. Glad you solved it though.
Maybe something went wrong in your previous installation for the sites folder 🤔
