### ISSUE TITLE
Tweets with multiple images cant use %num% 

### ISSUE THREAD

**Issue by kosserYN** [Bionus/imgbrd-grabber#2397]
I use filename is    %id%-img%num% .%ext%
it will be    %id%-img1-4 .jpg
But only the first of the multiple ones will be downloaded
Only use %md5% will download all
Thank you

**Comment by Bionus** [comment]
Are you using simultaneous downloads?
Try setting it to 1 and see if that helps.

Since by using simultaneous downloads, images are saved at the same time, which causes racing issues with %num%, since they're both fighting for the same filename.
