### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2401]
It's pretty simple, log are on local time, it's good, but monitors times are not. My monitoring tabs indicate date like 6/30/21 7:08am. But it's 9:08 in my timezone, the logs are fine. Plus the date format is US, not too bad but quit bugging from time to time. Could the app use system settings for it's displayed time ?

**Comment by Bionus** [comment]
Indeed, I could see this in 3 places, feel free to tell me if there are more:
* The "Last check" column
* The "Last state" column
* The "Last check" read-only field when editing a monitor

**Comment by yami-no-tusbas** [comment]
There is also the Date field in "Details"(https://i.imgur.com/I63yJ5n.png) windows. Obviously the hover information (https://i.imgur.com/cW94XE0.png) use the us date format too.
"last view" on favorite : https://i.imgur.com/9xaz79t.png and the hover information on a favorite too (https://i.imgur.com/Lt74Zfa.png).

I think that's all.

**Comment by Bionus** [comment]
There is indeed a timezone issue with the date field for the image hover and details, but I'm not sure what  you mean about the date format. I guess it's using the system's date format, is your Windows in English?

On my end, dates are showing in French format (day/month/year) in all those places. Date edition fields are in year/month/day format for everyone because those are a pain to localize.

**Comment by yami-no-tusbas** [comment]
Well I just checked, the screen where on windows 10, now i'm on 11 but the problem still exist, the format on my system (https://i.imgur.com/13fGlRd.png) is dan, month, year. But in grabber it is shown as month, day, year, like the us date format. My windows is in french (belgium). Here an exemple, I just added a favorite and the date format is wrong : https://i.imgur.com/w2Xm4dd.png, I don't know why, but for me it has always been like that. Could it be because I have my windows in french, but i added the US language pack, maybe adding the local found by grabber could help ? I mean in the logs, so I know what grabber think my system langage is ?

```
[08:46:51.854][Info] Temp directory purged of 0/0 files (0 failed) 
[08:46:52.544][Info] Software version: 7.5.1.
[08:46:52.545][Info] Software CPU architecture: x64.
[08:46:52.546][Info] Computer CPU architecture: x86_64.
[08:46:52.546][Info] Qt CPU architecture: x86_64.
[08:46:52.547][Info] Computer platform: Windows 10 Version 2009.
[08:46:52.547][Info] Path: C:/Program Files/Grabber
[08:46:52.547][Info] Loading preferences from C:/Users/...
[08:46:52.548][Info] Temporary path: C:/Users/...
[08:46:52.549][Info] Sources found: 22
[08:46:52.549][Info] SSL libraries: OpenSSL 1.1.1k 25 Mar 2021
[08:46:52.561][Info] Setting language to 'English' (C:\Program Files\Grabber\languages\English.qm)...
[08:46:52.589][Info] 22 sources found
```

This make me think, could it be because I set grabber to english ?  Yeah it is... grabber when set to english use english date format, not the system one. That is why my favorites where wrong, and also why it should use system over "langage" one. 
Here is the screen when langage set to french in grabber : https://i.imgur.com/sqkBc7K.png

**Comment by Bionus** [comment]
I see. I'll add a setting to switch between system and app locale in the settings.
It'll be set to "system" by default.
