### ISSUE TITLE
Pixiv login forbidden

### ISSUE THREAD

**Issue by drakkillen** [Bionus/imgbrd-grabber#2405]
[settings.ini.zip](https://github.com/Bionus/imgbrd-grabber/files/6760703/settings.ini.zip)
**Bug description**

when trying to login to pixiv, it opens the webpage as intended and login proceeds but when it tries to pass it to the program the log states " Error transferring https://oauth.secure.pixiv.net/auth/token - server replied: Forbidden"

**Steps to reproduce**

1. login to pixiv
2.accept to let the site open link in the grabber
3. see log for error message

**Expected behavior**
To get client secret and token set into pixiv source to enable useage of pixiv source
[main.log](https://github.com/Bionus/imgbrd-grabber/files/6760701/main.log)

**Screenshots**

https://i.imgur.com/zsTTP84.png screen shoot

**System information**

- OS: Windows 10 
- Grabber version: nightly 004cb7df (7.5.1) x64

**Comment by Bionus** [comment]
Strange. Did you log  in multiple times at once or something? Are you sure of your credentials?
I just tried logging into Pixiv using this method and it worked well.

If you restart your computer and try again, does that change anything?

**Comment by drakkillen** [comment]
yes even after restart,  and i tried with the creds that comes with it and getting the access token and refresh token using this method here: https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde
i get succesful login but when i then try to search i get this error
https://i.imgur.com/ZFWLTp1.png
also server replied forbiden

**Comment by drakkillen** [comment]
i managed to fix the Oauth error i had to add grabber to my firewall excemption, how ever when i search i still get the error i posted above

**Comment by pratyush-007** [comment]
got any way to login or pixiv dead?

**Comment by drakkillen** [comment]
by using the method i stated before yes, but the images wont reach my client as the connection for some reason is forbidden
