### ISSUE TITLE
Tag type for e621 incorrect in preview window.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2406]
**Bug description**

the preview window for the images of e621 don't color correctly, at first metadata tags are orange as expect, but in an instant they go black like normal tags.

**Steps to reproduce**
1 Search for images on e621
2 Click on a result
3 See the fast change in color on tags

Here is video : 

https://user-images.githubusercontent.com/3921598/124516452-f7d14800-dde1-11eb-9080-4c36dcfde586.mp4

**Expected behavior**

Ese the correct color scheme for meta tags and species tags

**Context**

There is no particular log for this, 

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

It change to fast for screen so I uploaded a video

**System information**

- OS: Windows 11
- Grabber version: 7.6.0

**Additional context**

The bug is old, was occuring on grabber 7.5 too and before.
The color of the tags in the over are fine, it just on the preview window.
Also noticed metatag don't work on gelbooru, they should be colored too.

**Comment by Bionus** [comment]
Seems like this only happen for the orange (meta) tags because the tag type ID for metadata tags was missing in the `tag-types.txt` file for E621. I just added it (it was 7). It's not required for the search API because it's written in full letters there ("meta") instead of ID in the details page ("category-7").

As for Gelbooru, it was caused by them using the name "metadata" while Grabber only understood "meta". I added an association.

**Comment by yami-no-tusbas** [comment]
> Thanks for finding both of those issues! And thanks for the very useful video, using rating:safe 😄

It was kinda obvious with thoses boards to use it here 😄 
I'll test thoses change soon, but I'll close the issue for now.

**Comment by yami-no-tusbas** [comment]
THe bug is back, don't know since when, but coloration for species tag is the interface gone. But species are still processed correctly when using %species%. The tag-type seems to be good too, maybe the problem is frome the json returned by the website(e621) here is a part : 

"tags": {
        "general": [
          "ambiguous_gender",
          "anthro",
          "armor",
          "belt",
          "blue_body",
          "blue_eyes",
          "blue_fur",
          "blue_scales",
          "boots",
          "bow_ribbon",
          "claws",
          "clothing",
          "detailed_background",
          "dramatic_lighting",
          "eyebrows",
          "feral",
          "footwear",
          "fur",
          "fur_markings",
          "green_eyes",
          "group",
          "markings",
          "red_eyes",
          "ribbons",
          "scales",
          "whiskers",
          "yellow_eyes",
          "yin_yang"
        ],
        "species": [
          "canid",
          "canine",
          "canis",
          "digimon_(species)",
          "domestic_dog",
          "flamedramon",
          "fox",
          "gaogamon",
          "kyubimon",
          "lagomorph",
          "leporid",
          "mammal",
          "rabbit",
          "rapidmon",
          "reptile",
          "scalie"
        ],
        "character": [],
        "copyright": [
          "bandai_namco",
          "digimon"
        ],
        "artist": [
          "kloudraws"
        ],
        "invalid": [],
        "lore": [],
        "meta": [
          "2019",
          "absurd_res",
          "detailed",
          "hi_res",
          "huge_filesize",
          "signature",
          "watermark"
        ]
      },

Link : or not I can't post a link with my apikey.

I dunno wat got wrong here, but coloration is nice to have.

**Comment by yami-no-tusbas** [comment]
Seems to be solved somehow
