### ISSUE TITLE
Crash when click Ok with all sources check

### ISSUE THREAD

**Issue by NoBooru** [Bionus/imgbrd-grabber#2413]
For details, see the video I uploaded

I've tried the sources one by one and there's no problem opening them, but when I check all the sources a crash occurs.

no crashes in previous versions

Grabber Ver : 7.6.0 (x64)

<details>
  <summary>Video Detail</summary>

https://user-images.githubusercontent.com/87080082/124780536-dfd9ff80-df6c-11eb-818a-e29528cc647c.mp4

</details>

**Comment by Bionus** [comment]
Does it still crash if  you select all sources except for Pixiv?

**Comment by NoBooru** [comment]
> Does it still crash if you select all sources except for Pixiv?
> Also, can you reproduce on the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/nightly)?

i think the problem is Pixiv, I didn't experience any crashes on both Normal v7.6.0 and Nightly ver when Pixiv is not selected.

but on Normal v7.4.3 no crash even Pixiv is selected 

![2021-07-31_022240](https://user-images.githubusercontent.com/87080082/127703375-56333bad-cdac-4760-af33-3815b6d9a35e.png)
![2021-07-31_022251](https://user-images.githubusercontent.com/87080082/127703400-c2afec13-258f-4c99-bd38-68fe383346f3.png)
