### ISSUE TITLE
Training Grabber to notice account name changes within imageboard platforms?

### ISSUE THREAD

**Issue by Azuriye** [Bionus/imgbrd-grabber#2416]
**Is your feature request related to a problem? Please describe**

Let me take Twitter for example I'm not sure if it applies to other imageboard platforms but let's say I scrape an account @Xyez231 for a month or so, I might leave it as it is and let's say suddenly the next day the account has changed it's name to @XYZ1121 I need to take the effort of going through the internet and seeing if the person is under a different alias and as well as lookup Twitter itself to see if someone has changed their name which takes minutes to maybe even hours and sometimes impossible to know if they have changed their name or deleted their account. Now imagine this is a 500-600 monitor list will be really frustrating to check and correct which account is facing this issue. Not only that I need to keep a constant touch on Grabber's logs to know if something is going wrong.

**Describe the solution you'd like**

This all sounds too impossible but maybe training Grabber in such a way where it can identify account name changes in Twitter by noticing if its characters match between its old and new name? Or maybe checking if X images from the old account match X images on the new account? Here X is whether both the images have the same metadata to distinguish them? Or maybe if it's possible for Grabber to open up all the images from the old account and maybe understand the pattern and see if it matches any of the accounts on Twitter? maybe once it finds relations with the account it can give the user a prompt suggesting a list of combination usernames showing that these account names could possibly be the new account's name? 

**Describe alternatives you've considered**

No alternatives so far. 

**Additional context**

Take this with a pinch of salt, I feel like this might be too much for Grabber to do all by itself since Grabber was only made to scrape images from said user account's and if an error does come it's up to the person to correct it or leave it as it is. But maybe if it's possible or something could be done about this issue it will surely be nice to have a feature for people who want to just set the monitor list and forget about it and if in case the account name changes the user can receive a prompt that such a thing has happened and maybe even see possible combinations of the new account's username but again it sounds too impossible to implement such a feature for Grabber since even though I've mentioned some solutions there can always be flaws about it and there can't really be a definite way to identify if a user has changed their name or not or if the account itself is deleted so it's basically up to the person to correct it. But all I can do is hope that it might be possible one day.

**Comment by yami-no-tusbas** [comment]
Grabber has a way to correct that, the renamming tool, I don't know if ti work for twitter, plus you have to save md5 in your filename. But with it you can run in one pass all your folders, then take not of what have changed (update your monitors.), and it will update all your files with new artists name.

**Comment by Azuriye** [comment]
> Grabber has a way to correct that, the renamming tool, I don't know if ti work for twitter, plus you have to save md5 in your filename. But with it you can run in one pass all your folders, then take note of what have changed (to update your monitors.), and it will update all your files with new artist/author name.

Hmm about this, I haven't tried it yet but it sparked some sort of issue co-related to this thread's topic if I for example have the old account folder name and the person changed his account name to something else Grabber won't combine both the folders into one since it thinks those two are different account name folders where in reality both of them are the same except the person changed his/her username to something else entirely. Maybe the renaming tool which you're talking about might help in this case but I haven't known about this issue until now nor have I tried to actually use the renaming tool.

**Comment by Bionus** [comment]
I understand where you're coming from, but I feel this is not really possible easily, and would be pretty much out of scope for Grabber. If Twitter had some way to "link" to the replacement account sure, but that's not the case, and if it were you could even do it manually without much worries.

Renaming tool shouldn't help much in your case since there's no link between the old content and the new one, unlike other sources where you can just load an image's MD5 / ID and get the updated data.

I'll close at "won't fix" but it's more like impossible / out-of-scope 😞
