### ISSUE TITLE
can't rename from md5 to server filename

### ISSUE THREAD

**Issue by typhoon71** [Bionus/imgbrd-grabber#2417]
When renaming from md5 to filename the files don't get renamed.

**Steps to reproduce**

1. Go to yande.re and search for somenthing
2. use a destination filename pattern like %md5%.%ext%
3. wait till some files are downloaded

4. click "tool", then "rename existing images"
5. use "%md5%.%ext%" as origin filename and "%filename%" as destination filename
6. let it download the data

**Expected behavior**

In the "the following images will be renamed" list there should all images should be listed with the filenames being changed from md5 to the (server) filename.
Important: if %filename% is used as the detination filename pattern when downloading from Yande.re (point 2) the file will be saved something like as  yande.re 12345678 tags.png - so files aren't saved by md5 (I guess).

**System information**

- OS: [Windows 7 SP1 x64]
- Grabber version: [7.6.0]

- Settings.ini (zipped cause .ini is not allowed): [settings.zip](https://github.com/Bionus/imgbrd-grabber/files/6810799/settings.zip)

**Comment by typhoon71** [comment]
will ad .cfg and logs later, right now I can't attach files to the post - also current logs would be too big and not to the point

**Comment by yami-no-tusbas** [comment]
Just tested I can confirm Grabber doesn't use the data sent from the board when %filename% is the destination.

My settings : 
![UmfC4Pt8rI](https://user-images.githubusercontent.com/3921598/126858642-cf5060e0-349e-4c2f-9352-45686fb7694c.png)
and the result (I censored the thumbnails) : 
![Grabber_211TAeqaP6](https://user-images.githubusercontent.com/3921598/126858902-501d7585-6bc7-4ecf-9069-9e5db9cffa92.png)

Grabber should use the image board data as the reference for the filename, but use another value.

**Comment by Bionus** [comment]
Indeed, there was a recent update that added special `%directory%` and `%filename%` tokens for the renamer tool, but I guess I forgot that "filename" is already a valid token, so it was being overwritten. 😞 

I'll rename them to "old_directory" and "old_filename" to prevent this.
