### ISSUE TITLE
very slow download

### ISSUE THREAD

**Issue by CH4SSEUR** [Bionus/imgbrd-grabber#2418]
**Bug description**

* when i try to open or download one or multiple images, its a very slow download (between 50 and 70 kb/s download speed) and my internet speed is 10mb/s
* it feels like something is limiting the download speed
* this started to happen recently (like a week ago)
* i tried a bunch of things to fix it but nothing works (tweaking firewall stuff, disabling antivirus, flush DNS, changing DNS....etc)
* i noticed a weird thing when i activate a vpn then deactivated it the next minute or so the download speed goes up then it slows down again
* i didnt find any connectivity options to tweak in grabber options menu except proxy settings (if i missed something please let me know)
* all other programs that i use to download are fast

**Expected behavior**

download speed somewhat close to the internet speed

**Context**
mai log file: [main.log](https://github.com/Bionus/imgbrd-grabber/files/6816533/main.log)
Settings file (changed ext to txt): [settings.txt](https://github.com/Bionus/imgbrd-grabber/files/6816543/settings.txt)
igl file (compressed): [downloads example.zip](https://github.com/Bionus/imgbrd-grabber/files/6816571/downloads.example.zip)

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/73677364/125631806-1618eb2c-aee6-431d-bc9f-7b1f8c6e2f91.png)
![Screenshot_2](https://user-images.githubusercontent.com/73677364/125631817-ed89f874-ab1e-4822-be66-32536e645e69.png)

**System information**

- OS: Windows 10
- Grabber version: 7.6.0

**Additional context**
* is it possible that my ip got blacklisted?
- Edit: i think i found the problem, its only slow when downloading from Gelbooru, Rule34 and others seems to work fine so i think i got blacklisted from Gelbooru so it has nothing to do with the program

**Comment by Basilisk88** [comment]
i have the same problem with rule34.xxx

**Comment by CH4SSEUR** [comment]
@Basilisk88 since when it started? and do you use rule34 a lot?

**Comment by Basilisk88** [comment]
@CH4SSEUR it started 4 or 5 days ago. and I usually run it every two or three days

**Comment by CH4SSEUR** [comment]
@Basilisk88 my problem is sovled, i didnt use gelbooru for 2 or 3 days and its fixed, i'm guessing its an IP blacklist/limitation of some sort
