### ISSUE TITLE
Batch download error from Pixiv to the directory that doesn't exist.

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#2419]
**Bug description**

When i try to download to the directory that doesn't exit i get error:

```
---------------------------
Error
---------------------------
An error occurred saving the image.
M:\nonexist_folder\dfasdfasdfasfa.jpg
Please solve the issue before resuming the download.
---------------------------
OK   
---------------------------
```

I need to create this folder and only after this downloading from Pixiv will work. Usual downloading from imbs just create new directories and doesn't require to create directories manually.

**Steps to reproduce**

1. set to "folder" field path to nonexistent folder
2. try to batch download from pixiv
3. get error 
4. create required folders -> download works 

**Expected behavior**

batch downloading create required folders automatically

**Comment by Bionus** [comment]
Thanks for the report, I could indeed reproduce this issue! 👍 
I just pushed a fix that should land in nightly soon, and later in the next version.
