### ISSUE TITLE
Adding a button to force a refresh on Monitored sites

### ISSUE THREAD

**Issue by gummykage** [Bionus/imgbrd-grabber#2420]
**Is your feature request related to a problem? Please describe**

Not an actual problem, just sometimes I plan to shut the app down earlier than the planned monitor time for instance to save power it would be nice to just do a quick refresh and shutdown.

**Describe the solution you'd like**

Maybe add a button that allows a quick refresh =D

**Describe alternatives you've considered**

I've just lowered the time to 1 min to force a refresh, but re-inputing the times is kinda tedious, especially if you have a decently large list.

**Additional context**

**Comment by Bionus** [comment]
Alright, I just added a new button to do this.
Hopefully it'll solve this issue for you once it lands in Nightly!

**Comment by gummykage** [comment]
Thank you soooooo much Bionus =D <3 <3 <3

**Comment by gummykage** [comment]
This button works perfectly Thank you so much! You have no idea the level of usefulness this is lol. Power bills are murdering me these days and I have grabber running on my main rig lol. Now I can update copy over what I want to my phone or other computer and turn off my 1200 watt power guzzler lol. <3
