### ISSUE TITLE
Is there a way to have tags in file name?

### ISSUE THREAD

**Issue by VanishingBlaze** [Bionus/imgbrd-grabber#2425]
Wondering if the files can be saved with tags for sorting reasons

**Comment by Bionus** [comment]
Yes, see [https://bionus.github.io/imgbrd-grabber/docs/filename.html]
You just  need to add `%tags%` in your filename.

**Comment by VanishingBlaze** [comment]
Had to replace tags with all and it worked, but I'm getting hit with the character limit now. Any way to bypass that?

**Comment by Bionus** [comment]
You can increase Windows' filename limit then increase it in Grabber.
Or you can use metadata instead: https://bionus.github.io/imgbrd-grabber/docs/metadata.html

**Comment by VanishingBlaze** [comment]
Gpedit is suppose to incase my file limit, but when I got to incase it above about 350 it get error when trying to download
