### ISSUE TITLE
No tags, not showing total number of images and download only preview images for deviantart.com.

### ISSUE THREAD

**Issue by Dippa96** [Bionus/imgbrd-grabber#2428]
Hi
If I try to download from deviantart.com, for example by downloading wlop images (username:wlop), tags are not shown (both in the tags box and in the details of images) and the total number of images is not shown (you only see it when you start the download). 
![Grabber_deviantart com_1](https://user-images.githubusercontent.com/87908995/126876538-da20491e-60f4-4c0f-900c-3767a9010c6f.PNG)

The other big issue is that downloaded images are of lower quality than the originals (both resolution and size). With Grabber you can download only preview of the image from deviantart.com.
For example, the image 660491742 downloaded with Grabber is 1164x687 72.4 KB, while if downloaded from the site (https://www.deviantart.com/wlop/art/Ash-660491742) it is 1447x854px 272.14 KB.
![Grabber_deviantart com_2](https://user-images.githubusercontent.com/87908995/126876920-29901b72-a59e-40b9-8c9d-1b60a8732dae.PNG)

I don't know if I'm the only one with these issues.
Since I only encountered these issues for deviantart.com, I think this is a bug.

I load main.log, settings.ini and model.js of deviantart.com (AppData\Local\Bionus\Grabber\sites\DeviantArt\model.js); (both settings.ini and model.js are as .txt, because i can't load them as .ini and .js)
[main.log](https://github.com/Bionus/imgbrd-grabber/files/6872865/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/6872870/settings.txt)
[model.txt](https://github.com/Bionus/imgbrd-grabber/files/6872873/model.txt)

I hope these issues can be resolved soon, as they persist from v7.4.0 (since deviantart.com source is added to Grabber).

System information:
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.40 GHz
Ram 16,0 GB
System type 64-bit operating system, x64 processor
Windows 10 Pro
Version 21H1
OS Build 19043.1110
Windows Feature Experience Pack 120.2212.3530.0

Grabber_v7.6.0_x64

**Comment by Bionus** [comment]
> tags are not shown (both in the tags box and in the details of images) and the total number of images is not shown (you only see it when you start the download).

Yeah that's because the RSS API does not provide this information. I pushed an update to add the HTML "API" that should fix this.

> The other big issue is that downloaded images are of lower quality than the originals (both resolution and size). 

Seems like the image their RSS API claims to be the full-size one isn't. I also pushed a fix for this, thanks 👍
