### ISSUE TITLE
Download "finishes" when it hasn't download all files

### ISSUE THREAD

**Issue by VanishingBlaze** [Bionus/imgbrd-grabber#2430]
Trying to download around 12,000 images from an artist, but it only downloads around 1,600 images before it acts like the task is complete. And these aren't already existing files.

**Comment by gummykage** [comment]
Version you're using, screenshots, where and what artist? Did you check the logs if you were banned?

**Comment by VanishingBlaze** [comment]
I think I'm using version 7.5.1 and the artist name is gaden

**Comment by yami-no-tusbas** [comment]
The board with the most of his image seems to be gelbooru, and it is only 1564 images. So you need to send the logs and the board where Grabber tell you there is 12k results, because only about 1600 images seems good to me.
