### ISSUE TITLE
Dark mode is not working correctly

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#2434]
**Bug description**

When I use dark mode (QDarkStyleSheet) a lot of buttons are unresponsive and the layout is incorrect. Also the tags are black which is not really readable on a dark theme 

**Steps to reproduce**

1. Go To the interface settings and change the theme
2. Just try some things like opening a new tab or the Plus button etc
3. You will see that you need a lot of presses for it te respond which would not happen in the light theme

**Expected behavior**

That the dark theme would work as well as the light theme

**Screenshots**

[Video to explain the issue](https://i.imgur.com/5ZJGV7X.mp4)

**System information**

- OS: Windows 10
- Grabber version: Latest nightly version

**Comment by Bionus** [comment]
Seems to be caused by [QTBUG-86587](https://bugreports.qt.io/browse/QTBUG-86587)
Only happens in Qt 5.15.1 which is the version currently used by Grabber. Will need to bump to 5.15.2.
