### ISSUE TITLE
Create and check folders

### ISSUE THREAD

**Issue by phantazum** [Bionus/imgbrd-grabber#2435]
Is there some way to have this create a folder when I do a new download? Lets say I regularly do two searches and downloads, one for School_uniform and another for exposed_collarbones. Now I dont want these together, I want them in separate folders. So if the folder did not exist it would create the folder for School_uniform then download the files in to that folder. If the folder did exist, It would download the files and skip the files that already existed there in that folder. This would all be taking place in the master directory that I set. Perhaps Im just missing it but I have looked all through the settings and I cant make this happen and it just seams like an obvious feature that I am missing.

Amazing program btw.

**Comment by Bionus** [comment]
Hello

You can just use something like `%search%/%md5%.%ext%` as filename and it will do different folders for each search.
You can see more details here: https://bionus.github.io/imgbrd-grabber/docs/filename.html

**Comment by phantazum** [comment]
I thought so. I knew I was just missing it. Thank you.
