### ISSUE TITLE
%directory% does not work anymore.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2437]
**Bug description**

%directory% does not work anymore.

**Steps to reproduce**

Use the renamer with theses settings : ![image](https://user-images.githubusercontent.com/3921598/128360920-1d53c4a9-1ada-48ad-a093-442708112c42.png)

I got this : ![Sans titre](https://user-images.githubusercontent.com/3921598/128361469-66158693-301d-429e-a041-5c017908a41e.jpg)

**Expected behavior**

The same name into the origin, and destination field. %directory% was supposed to store the path of the file, I worked by the past, but doesn't.

**Context**

Logs does not have information for the rennaming tool.

**System information**

- OS: Windows 11 21H2
- Grabber version: Nightly 7b129b87 (Just checked in ad68aae9, don't work either.)

**Comment by Bionus** [comment]
It's been renamed to `old_directory` and `old_filename` to prevent collisions with existing tokens.
See issue #2417. It was for `%filename%` but since I had to rename one I just renamed both.
