### ISSUE TITLE
Cannot read property 'full' of undefined

### ISSUE THREAD

**Issue by thany** [Bionus/imgbrd-grabber#2442]
**Bug description**

Can't download from derpibooru, because every downloading file errors with:
```
[13:46:35.044][Info] Loading image from https://derpicdn.net/img/view/2021/8/9/2674316.png 1
[13:46:35.044][Info] Not enough information to directly load the image (from blacklist: 0 / from file url: 0 / from filename tags: 1/1)
[13:46:35.044][Info] Loading image details from https://derpibooru.org/api/v1/json/images/2674316?key=<redacted>
[13:46:35.185][Warning] [derpibooru.org][Json] Uncaught exception at line 145: TypeError: Cannot read property 'full' of undefined
```

Redacted my API key, but otherwise it's a literal copypaste of a sequence of log entries that occur for each and every download. Not a single file is saved, even though it's "only" a warning.

On the search tab, thumbnails and fullsizes display fine, so it *is* capable of downloading them, just maybe not in batches or something.

**Steps to reproduce**

1. Set the only source to be derpibooru
2. Make sure to login on derpibooru using an API key
3. Download any selection of images
4. Notice how every download is skipped and is marked with a grey `?`
5. Open the log and see the errors appeared like above

**Expected behavior**

It just works.

**Context**

* Provide your `main.log` file to see if any obvious error occured.
    * See above.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
    * [Here you go](https://github.com/Bionus/imgbrd-grabber/files/6968147/settings.zip).
* If the bug occured during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.
    * Save button meaning `File->Save download list`, I assume? 🤨 If so, [here it is](https://github.com/Bionus/imgbrd-grabber/files/6968161/derpibooru.zip).

**System information**

- OS: Windows 10 21H1
- Grabber version: 7.6.0

**Comment by thany** [comment]
On a side note, you can't verify this with a redacted API key, but I promise the "image details" URL returns seemingly valid JSON when I add my API key back in.

**Comment by thany** [comment]
Same problem for Ponerpics, which I just added with the "Guess" option and entered my API key.

**Comment by Bionus** [comment]
Indeed, seems like a recent update broke the parsing of the image details.
I just pushed a fix.

> Same problem for Ponerpics, which I just added with the "Guess" option and entered my API key.

They're using the same engine, so yeah they'll share the same bugs.
