### ISSUE TITLE
old_directory token bug

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2444]
**Bug description**

it's fusing directories

**Steps to reproduce**

use image renamer with thoses parameters : 
folder : some path including sub_folder.
origin filename = `%old_directory%\%artist% - %id% - %rating% - %md5%.%ext%` (work also with %directory% for some reason)
destination filename = `%old_directory%\%artist% - %id% - %rating% - %md5%.%ext%`

and you get this : 
![Sans titre](https://user-images.githubusercontent.com/3921598/129105590-302c9eeb-2c16-4f0b-9686-74fc2a6dbdbf.jpg)

**Expected behavior**

Like the old time, respect the folder structure.
Update : `%old_directory:unsafe%\%artist% - %id% - %rating% - %md5%.%ext%` as output solve the problem, but this does not feel right.

**Context**

* No revelant log.

**System information**

- OS: Windows 11
- Grabber version: ad68aae9

**Comment by Bionus** [comment]
>  Update : %old_directory:unsafe%\%artist% - %id% - %rating% - %md5%.%ext% as output solve the problem, but this does not feel right.

Yes it's because you have multiple directories, and because of an issue in the code, `%old_directory%` was getting cleaned (just like how tags are), causing "A\B" to be replaced by "A_B".

I'll push a fix 👍
