### ISSUE TITLE
Possible reasons: server offline (I have already tried both proxy and cookie settings.)

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#2447]
**Bug description**

Hello?
I started using Grabber a week ago.
At first, I added "furry.booru.org" to the sources, and the program worked well then.
But when I checked yesterday, the message "Possible Reasons: server offline" appears and is not being searched.
I've tried all the known methods, but there's still a problem, and the program isn't working today either...

I've tried proxy, DNS bypass, installing Microsoft visual C++, reinstalling the program, and setting up cookies, but there's still a problem....

However, when I accessed "furry.booru.org" in chrome, I found that Cloudflare appears. Is it related to this?

**Steps to reproduce**

1. Go to 'favorites'
2. Click on 'sources'
3. Click on 'add'
4. trying add 'furry.booru.org'
5. See error

1. Go to 'new tab'
2. searching 'keywords'
3. see error (possible reasons:server offline)

**Expected behavior**

As was the case a week ago, the source was added and searched on the "https://furry.booru.org" site.

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/6989177/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/6989178/settings.txt)

**Screenshots**
![11](https://user-images.githubusercontent.com/71244615/129498340-d5120c7a-fe81-4f32-8508-9be2ecb51182.png)
![22](https://user-images.githubusercontent.com/71244615/129498343-0a749179-1454-4ac3-be9e-bc6cd14659eb.png)

**System information**

- OS: Windows 10
- Grabber version: 7.6.0 (x64)

**Additional context**
I have already reinstalled the program after deleting it, and I have installed all of Microsoft visual C++ 2013, 2015, 2019 x64, x86. But the problem still continues.

**Comment by SvyraCosmix** [comment]
Dude seriously, E621.net is a way better furry site just use that one and guess what, it's already on the list!

**Comment by followflower90** [comment]
> Dude seriously, E621.net is a way better furry site just use that one and guess what, it's already on the list!

That's right! I already know! Unfortunately, however, some of the illustrations that are not in E621 remain only at furry.booru.org. TT

So.... I'm desperately hoping for furry.booru.org as well.

**Comment by yami-no-tusbas** [comment]
```
[13:47:10.104][Error] [furry.booru.org][Html] Cloudflare wall for 'https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0'
[13:47:10.104][Warning] [furry.booru.org] No valid source of the site returned result.
```

Again it's cloudflare error, you need user agent, you can set it in the source settings. You will need a user-agent in the headers, a cookie clearance cookie, and maybe a login.

Well, there is something else, I can confirm even with a login, a user agent, and a cloudflare cookie, I still get the same error. I noticed the url on my browser as an argument with some cloudflare related things : 
`&__cf_chl_jschl_tk__=...` (look lik a token) Maybe grabber now need to send thoses too, seem annoying.
