### ISSUE TITLE
Grabber CLI is not returning images from Danbooru | Grabber 7.6.0 (Windows)

### ISSUE THREAD

**Issue by KohaiMomomiya** [Bionus/imgbrd-grabber#2448]
**Bug description**

Grabber CLI is not returning images from Danbooru, returns no output or command documentation.

**Steps to reproduce**

1. Open PowerShell:
2. Run the following command:
& 'C:\Program Files\Grabber\Grabber.exe' --cli --tags "age:0d..1d" --sources "danbooru.donmai.us --rc"

**Expected behavior**

List of images from source that has the selected tags or count of found images when using option "--rc" (--return-count)

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/6995871/main.log)
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/6995870/settings.ini.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/2092838/129665171-4d7940a1-bf34-4a34-a6e3-3be3d20d042c.png)

**System information**

- OS: Windows 10 Pro, version 21H1
- Grabber version: 7.6.0

**Additional context**

Other options, such as --version seem to be working.
A quick check at the output generated in the main.log file shows the URL generated by CLI is changed during parsing, resulting in an invalid URL that is sent to the source (i.e. danbooru). This can be tested by putting the URLs before and after parsing in a web browser.

![image](https://user-images.githubusercontent.com/2092838/129641666-9974497f-8d52-4f6a-961c-e34daabd4482.png)

https://danbooru.donmai.us/posts?limit=20&amp;page=1&amp;tags=age%3A0d..1d -> Before parsing. Shows expected results.

![image](https://user-images.githubusercontent.com/2092838/129642155-d2518051-b68d-4165-a1c7-4ea5cbc3ccb1.png)

https://danbooru.donmai.us/posts?limit=20&amp;page=1&amp;tags=age0A0d..1d -> After parsing. Invalid query.

![image](https://user-images.githubusercontent.com/2092838/129642172-e8610442-5bf0-4b7d-92af-2e3981cba0de.png)

**Comment by Bionus** [comment]
This is actually caused by the program not being able to count pages on danbooru's website anymore.
It can be seen in GUI mode as well by the fact that that very same search says "Page 1 of ? (20 of ?)".

I'll push a fix to Danbooru's page parsing in HTML.
