### ISSUE TITLE
Tags recheck

### ISSUE THREAD

**Issue by MurakumoMobiusFF** [Bionus/imgbrd-grabber#2451]
Is it possible to let the program recheck already completed batches/tags for new stuff instead of re-adding tags?

**Comment by SvyraCosmix** [comment]
Lmao closing and reopening a new case wont make bonus check faster. Just keep a document of the tags you've downloaded and keep track of when you last downloaded by date of the images ID number

**Comment by yami-no-tusbas** [comment]
No it is not, you can use the monitoring function for this. Add you tags as monitors set them correctly and Grabber will only take the new images from your monitors. You can avoid duplicate too using "-grabber:downloaded" as a post-filter in your monitors so Grabber won't donwload an image twice (assuming you use "keep md5(s) of delete files" too).

**Comment by Bionus** [comment]
As answered, the best solution is indeed the monitors.
You can also just not delete your batch downloads and re-run them every now and then.
