### ISSUE TITLE
Extended Blacklist Conditions

### ISSUE THREAD

**Issue by Hi-ImKyle** [Bionus/imgbrd-grabber#2453]
**Is your feature request related to a problem? Please describe**

Not really a problem. Situation is site has a `male` tag, say we have 3 images, 
- Tags: male
- Tags: male male/male
- Tags: male female

I want to see the `male female` one but not the `male male/male` OR `male` one. I see that the blacklist has a "AND" feature but adding `male male/male` only blacklists images with `male` and `male/male`, but I still see just `male`, if I add `male` to the blacklist I no longer see the `male female` posts which removes a lot of the results I want to keep. Sorry if you don't get that. I can try to explain more in a different way just ask.

**Describe the solution you'd like**

Some way of saying don't blacklist this "set" of tags if a tag exists
`male ^female` = blacklist all posts that have the `male` tag but not the ones with `male` and `female`. I understand adding `^` to the start of a tag may exist within the sites tags, I was thinking some obvious divide character or phrase to make it so you don't need the `^` which could conflict.

**Describe alternatives you've considered**

Suck it up and see gay stuff.

**Additional context**

Site in question is e621, but obviously the conditions could work on all sites if implemented as or better than I explained, fingers crossed.

Edit: 

I can't seem to find anything on this but using the blacklist `male -female` seems to do what I want, I do apologise for only just noticing this. Can you confirm if this works as a "Unless" operator?

**Comment by SvyraCosmix** [comment]
Exactly just stop being straight also if you just download the tag male/female you're most likely not gonna see any male/male except very few where like the girl is in front a guy behind here and a guy behind that guy. So yeah suck it up xD

**Comment by Bionus** [comment]
> male ^female = blacklist all posts that have the male tag but not the ones with male and female. I understand adding ^ to the start of a tag may exist within the sites tags, I was thinking some obvious divide character or phrase to make it so you don't need the ^ which could conflict.

Have you tried using `-` for negation, such as `male -female`? I think it should do what you want.

> I can't seem to find anything on this but using the blacklist male -female seems to do what I want, I do apologise for only just noticing this. Can you confirm if this works as a "Unless" operator?

Didn't see your edit initially, so yes I confirm that it's indeed a negation operator.
So "A -B" will indeed be true if A is present and B is absent.

You actually have an introduction of the syntax in the docs:
https://bionus.github.io/imgbrd-grabber/docs/search.html

**Comment by Hi-ImKyle** [comment]
Ah, I wasn't aware the syntax for it was in the search bit. I think I just ignored that page because it didn't say Blacklist. I apologise for not checking everything before making the issue. 

But thank you for clearing that up.
