### ISSUE TITLE
View downloaded images through application

### ISSUE THREAD

**Issue by pingas37** [Bionus/imgbrd-grabber#2456]
**Is your feature request related to a problem? Please describe**

I have downloaded a multitude of images and videos through this application, but overtime I have had trouble finding specific ones when browsing through my collection. The service certainly does give a wide variety of options to choose specific paths for downloads to go to, and these downloads can be organized in a broad sense this way such as by artist or copyright.

However, I like to have my downloads organized in a way that I can pull up any certain number of tags at once and it will retrieve any images associated with those tags. I currently cannot do this, as when I browse I can only view images associated with a certain copyright, or a certain character in a folder hierarchy. I don't think what I want can be accomplished through a normal file viewer on a machine, which is why I would like to suggest the proposed solution below.

**Describe the solution you'd like**

I think it would be incredibly useful if there was another tab that operated in a similar way that the favorites tab is formatted, only it browsed the files that you downloaded on your device. For example, if I wanted to look at all downloads that contained the tag "1girl", I would have no way of doing so through my device currently. The feature described above would greatly benefit in the appreciation and viewing of the images that I have downloaded, as I would be able to select any tag that I wanted to and it would pull up all of the images that I have already downloaded.

An alternative idea would be a tab that looks exactly like the default search bar, where you can search for any number of tags. Once the query has been entered, a search beings for finding all of the downloads on your device that match the criteria. The result would then looks similar to a normal search, just instead of finding images from websites it would find images on your device.

**Describe alternatives you've considered**

I have written a couple python scripts that iterates through my downloaded files and calls to API's of websites that I have added to my sources within the Booru Downloader application. These tags would then be added to specific metadata of the image. This eventually became a clumsy way of doing things, and have since disregarded the idea. I still have the scripts, and they could be useful to further illustrate what I am trying to accomplish.

**Additional context**

I do not have any at the moment. Anything to further illustrate my point can be provided upon request. Thanks for reading!

**Comment by Tumultuous-RGR-SiM** [comment]
I also have an interest in this, and have been asking in the Hydrus support thread on it. I still have to look in to exactly _how_ to get Hydrus to recognize the sidecar / external log files.

I've been saving log files with a particular formatting (not your example syntax here) for a while, but there are definitely images that don't have sidecar files. Is there a way to tell Grabber to go and make sidecar files for the older images that it has downloaded?

**Comment by lx30011** [comment]
> ```
> rating:%rating%
> %all:includenamespace,excludenamespace=general,unsafe,spaces,separator=\n%
> ```
Just curious, is there any reason why you convert underscores to spaces in the external log file? I haven't used hydrus yet, but I imagine it would result in wrong tags once imported?

**Comment by Bionus** [comment]
> Tagspaces is the most like what is needed but its .json sidecar files seem too convoluted to implement Grabber with them

It might take some work but it's definitely possible to have Grabber save sidecar files as JSON, depending on the JSON format. I'd suggest using a JavaScript filename for those since there's a convenient `JSON.stringify()` function in there.

> Just curious, is there any reason why you convert underscores to spaces in the external log file? I haven't used hydrus yet, but I imagine it would result in wrong tags once imported?

They also use `\n` as separator, which means "line break".
So there would be one tag per line, with no underscores, so no problem importing in that case. But yes indeed if you use a space as a separator and remove the underscores you'll have a hard time afterwards separating the tags 😅
