### ISSUE TITLE
Token Option/Modifier to exclude specific pulled tag from filename / condition

### ISSUE THREAD

**Issue by Furglitch** [Bionus/imgbrd-grabber#2458]
**Is your feature request related to a problem? Please describe**

Not related to a problem, just an ease of use idea. Wanting to be able to remove tags pulled from tokens

**Describe the solution you'd like**

For example, let's say I download a bunch of images on e926 with the "pokemon_(species)" tag and wanted to get the species of pokemon in the filename, so I use %species% but the "pokemon_(species)" tag gets added since it falls under that category.
The user could add a modifier to exclude a certain tag from the file name, like below
`%species:!tag="pokemon_(species)"`
or
`%species:tag=!"pokemon_(species)"`

**Comment by SvyraCosmix** [comment]
You could just use a program that removes a string of text from a list of file name I did it before but now I cant remember how

**Comment by Bionus** [comment]
Have you tried using the "ignored" or "removed" tags setting?
"ignore" will make the tag fall back to the default category, while "remove" will make it not appear in the filename.
