### ISSUE TITLE
Pictures saved are sorted in folders in a seemingly random order

### ISSUE THREAD

**Issue by qorl555** [Bionus/imgbrd-grabber#2460]
Usually when I save pictures via the browser, they show up in the order I saved them, right? I right click, pick "sort by date modified/created" and I'm good, the newest is at the very top left corner of folder. With pictures saved with the grabber, via "save as" or batch download, they seem all jumbled up. I could save picture A at 2pm, pic B two hours later, and B is at the bottom of a folder and A is somewhere halfway up and 200 rows higher, despite files still being sorted in the way I mentioned. I just don't see the logic in which they arrange themselves. I tried every "sort by date xx" option in the rightclick menu. Is there some way for the grabber to save pics in a way that would replicate the behaviour of "newest saved to HD is at the top"?

**Comment by Bionus** [comment]
By default, Grabber keeps the original file's creation date.

If you don't want this behavior, you should uncheck this setting:
![image](https://user-images.githubusercontent.com/882719/131869679-d86efdad-3a4c-4d16-9afa-155048ef31f6.png)

**Comment by qorl555** [comment]
That's so much better, thank you for the help! :)
