### ISSUE TITLE
Deviantart image download error

### ISSUE THREAD

**Issue by CashOver** [Bionus/imgbrd-grabber#2463]
**Steps to reproduce**

Would like to say that when I download deviantart images either per page or complete, there is a change in both the size and definition of the images, I would like to know if you could fix this error

I would like to notify you that this error is occurring from the Grabber 7.6.1 version

**Comment by Bionus** [comment]
Hello
Do you have an example of an image that does not get downloaded properly?

**Comment by CashOver** [comment]
![0000000](https://user-images.githubusercontent.com/90059760/132415964-8fbe0c20-0609-4d6f-9c0f-bb72f3e89853.PNG)

**Comment by CashOver** [comment]
This was the download I made on deviantart

**Comment by CashOver** [comment]
the site is like this after
![0000001](https://user-images.githubusercontent.com/90059760/132416337-5ed79388-7af6-492a-bd6b-8af05761020f.png)
