### ISSUE TITLE
Crash when no sources are selected

### ISSUE THREAD

**Issue by ASGNeoN** [Bionus/imgbrd-grabber#2468]
Pretty much what the title says, might I also add, if you have pixiv or deviantart as sources and you open up the program it will crash

**Comment by Bionus** [comment]
Hello

On what version of the program are you seeing this crash?
I just tried and couldn't reproduce a crash, even with no source selected.
Maybe you could share your log file? Cf the "main.log" part of [CONTRIBUTING.md](https://github.com/Bionus/imgbrd-grabber/blob/master/CONTRIBUTING.md#reporting-bugs)

Same thing for Pixiv/DeviantArt, no crash even without login information.
