### ISSUE TITLE
"rating:" option does not work on Pixiv

### ISSUE THREAD

**Issue by TouhouJevil** [Bionus/imgbrd-grabber#2470]
**Bug description**

Rating options not working, don't matter which option is used, it's just outright ignored be it safe, questionable or explicit.

**Steps to reproduce**

1. Click on Plus.
2. Click on Rating Box.
3. Choose any of the options.
4. See how the image results aren't changed.

**Expected behavior**

Rating option to work and actually change the results of the images.

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occurred during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

**System information**

- OS: Windows 7
- Grabber version: Grabber_v7.6.2

**Additional context**

Add any other context about the bug report here.

**Comment by Bionus** [comment]
Hello

Pixiv does not support to filter by R18/safe using their app API (the one used by Grabber).
Even their own app does not support this, although their website does. So until they implement it the "rating:" filters will be ignored by Grabber for pixiv:
> [Warning] [www.pixiv.net] Unsupported modifier removed from search: rating:safe

I still just pushed a  fix for re-adding support for rating post-filters instead, as those should be supported!
