### ISSUE TITLE
Instant crash with tentaclerape.net source selected or too many sources

### ISSUE THREAD

**Issue by poisenbery** [Bionus/imgbrd-grabber#2472]
**Steps to reproduce**

1. Go to 'Sources'
2. Enable tentaclerape.net
3. Search for any tag
4. Program crashes

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/7206234/main.log)

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/7206239/settings.txt)

Happens consistently on a fresh install of the program. I'm using Windows 10 64 bit

Windows 10
Grabber Version Grabber_v7.6.2_x64.exe
**Additional context**

Originally, I was crashing when I selected all sources. Once I investigated 1 by 1, I found that tentaclerape.net source was causing consistent crash in program.

**Comment by poisenbery** [comment]
Apparently this happens with more than just tentaclerape.net

IF you enable too many sources, the program crashes.

**Comment by Bionus** [comment]
Moving discussion to #2518
In the meantime, you should not enable Pixiv unless you log into it
