### ISSUE TITLE
Unknown CTD starting from 7.6.0 onward

### ISSUE THREAD

**Issue by dotuser** [Bionus/imgbrd-grabber#2475]
**Steps to reproduce**

Attempting any search at all on Windows 10 Build 21H1 (x64) appears to crash instantly.

Crashes with both x86 and x64 builds.
Tried with a fresh install as well.

**Context**

[settings - Copy.txt](https://github.com/Bionus/imgbrd-grabber/files/7214005/settings.-.Copy.txt)
[main.log](https://github.com/Bionus/imgbrd-grabber/files/7214003/main.log)

**System information**

- OS: Windows 10 64bit BUILD 21H1
- Grabber version: 7.6.*

**Additional context**

Reverting to 7.5.1 no longer has the issue, but that version appears to have other issues and I'd like to be current.

**Comment by Bionus** [comment]
Moving discussion to #2518
In the meantime, you should not enable Pixiv unless you log into it
