### ISSUE TITLE
Per site blacklist

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2476]
**Is your feature request related to a problem? Please describe**
Not a problem, but let say I want to blacklist "sketch" on e621 who has a lot of them, but not on gelbooru, it will not work since grabber as "one" blacklist for all website.

**Describe the solution you'd like**

Something like a modificator to tell Grabber that this entry is for a specific site, like "e621:sketch" ?

**Describe alternatives you've considered**

I don't think there is way with grabber right now to do that, exept on post-filter for monitors, but this is no practical.

**Comment by Bionus** [comment]
> I don't think there is way with grabber right now to do that, exept on post-filter for monitors, but this is no practical.

Well you're looking down on Grabber a little then 😎 _(also I wasn't sure it would work either until I tried it out 😅)_
If you just want this for a few tags (instead of having a huge different blacklist per website), you can already do so with:
```
website:e621.net sketch
```

Since multiple tags on the same line will cause a "AND" condition, it means that it will be blacklisted if the `%website%` token contains "e621.net" AND the tag "sketch" is present.

**Comment by yami-no-tusbas** [comment]
The documentation need so much update to reflect all of that, but its really amazing ! Good work Bionus !

**Comment by yami-no-tusbas** [comment]
Hmm, strange thing here, it worked for sketch lika charm, but not for : 
>`website:e621.net animal_humanoid`

because if I look for "bovid_humanoid" some shows up, like id : `2957141` with as animal_humanoid and bovid_humanoid and should be blacklisted, I'm on d2db88f6 right now. Don't really know why it's not working, both bovid and animal_humanoid where in my ignore list, but it should not impact blacklisted tags. Yep just double checked the firsts lines in black list are : 

>website:e621.net sketch
>website:e621.net monochrome
>website:e621.net animal_humanoid

looking for bovid_humanoid, or even cat_humanoid shows result wich have the animal_humanoid tag, but should have been blacklisted. The strange thing is, that it work for some tag... like : 

>[13:05:32.080][Info] Image #2956079 ignored. Reason: "website:e621.net sketch".
>[13:05:32.082][Info] Image #2955608 ignored. Reason: "website:e621.net monochrome".

So I'll mark  this as a bug.

**Comment by Bionus** [comment]
That was quite hard to reproduce 😅

Do you, by any chance, have `animal_humanoid` in your "removed tags" list? If so, it seems to be removed **before** the blacklist is taking effect for some reason. I'll work on a fix.
If not, no idea what could be causing that 🤔

**Comment by yami-no-tusbas** [comment]
> 
> 
> That was quite hard to reproduce 😅
> 
> Do you, by any chance, have `animal_humanoid` in your "removed tags" list? If so, it seems to be removed **before** the blacklist is taking effect for some reason. I'll work on a fix. If not, no idea what could be causing that 🤔

Yeah it was in my removed tag list, I did not think about that, nice catch ! yeah it make sense now, if it is removed before blacklist parsing it could not be caught !
