### ISSUE TITLE
Some color in monitor tab

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2478]
**Is your feature request related to a problem? Please describe**

Sometime a monitors fail, or don't work as expected. There is a column that indicate the last state, but when you have hundreds of monitors, it is a bit hard to find the one who fail.

**Describe the solution you'd like**

Put the line in red if for exemple there was no result (total : 0)
Put the line in orange if something seems wrong (like described in #2477)
Or maybe an icon to replace the "zZz" that would cath the eye ?

I know the problem is that, on the next tick thoses information could be lost, so maybe have the user to reset them manually by editing the item ? I know editing a monitors reset the status, so maybe the program could skipp any monitors with error until the user fixes them ?

**Describe alternatives you've considered**

reading one by one the lines or ordering by line.

**Comment by Bionus** [comment]
I added icons just now as I'm not a big fan of highlighting full rows:

![image](https://user-images.githubusercontent.com/882719/141860153-27056bed-8b56-4f0a-9bba-ee0116f53228.png)

The green/red should be eye-catching enough I believe. What do you think?

**Comment by yami-no-tusbas** [comment]
Yeah it's fine ! Color is working, especially red and green since they are used everywhere for danger and "ok" indication.
