### ISSUE TITLE
Monitors tabs, sorting by Last state error

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2479]
**Bug description**
If you sort by last state, the numbers are non-human ordered. 
![4dkNrAskVL](https://user-images.githubusercontent.com/3921598/134540438-c813b6c2-f16a-400e-a0c6-838845dcb9b4.png)

**Steps to reproduce**

Just click on "last state" column in the monitors tabs.

**Expected behavior**

2 to be after 1, not 10 😄 
Thx !

**Comment by Bionus** [comment]
It's because it's actually human-sorted, just for the whole text. So 10 goes after 1 😄 
I'll split this column in 3 so that you can sort by whatever option you want.

**Comment by yami-no-tusbas** [comment]
That's ok for me !
