### ISSUE TITLE
authorid token does not exist

### ISSUE THREAD

**Issue by heywolf15** [Bionus/imgbrd-grabber#2480]
Cant put %authorid% on filenaming
it says %authorid% token does not exist

![shag3KX3M0](https://user-images.githubusercontent.com/34807171/134649242-16067b35-25e7-4fbc-a13c-e4df7cedc0da.png)

- OS: Windows 10
- Grabber version: 5.15.2

**Comment by Bionus** [comment]
Hello

It shows as not existing but it does. You can ignore the warning as long as you're using one of the sources that support it (Danbooru 2.0 sources, E621, Pixiv, Philomena).
I will push a fix to not trigger this warning for this token.
