### ISSUE TITLE
Grabber downloads random images from derpibooru every few seconds

### ISSUE THREAD

**Issue by RudolfShmitler** [Bionus/imgbrd-grabber#2483]
Whenever I have the application open, the log shows an image from derpibooru being downloaded. I haven't used derpibooru ever I don't think, I had it on before but after turning it off it seems to continue the downloading.

**Comment by SvyraCosmix** [comment]
Are you sure you didnt set something from derpibooru to be monitored?

**Comment by Bionus** [comment]
Since indeed sounds like a monitor issue.

Check the "monitors" tab and delete the monitors there. Could also be a favorite.
I'll be closing this issue in the meantime.
