### ISSUE TITLE
Can't download or view images from posts with many images (gallery) on Pixiv . 

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#2485]
**Bug description**

Batch download ignores posts with many images on Pixiv.

Search can see these posts, but can't open them - clicking on preview for this post in search -> an empty tab without images opens and writes "Pixiv - No images"

**Steps to reproduce**

1. Login to pixiv with grabber (used 7.6.2)
2. Enter any user:user_number in search tab, find one with post with many images
3. try to click on post with many images or try to download it
4. get message "Pixiv - No images" in new tab where should be few images, batch download of posts with many images will be ignored

**Expected behavior**

search tab should open page with inner images from post, 
batch download should download all images from all posts

**Context**

log output when trying to open post with many images in search tab (I replaced page id by 'xxxxxxxx'):

```
[18:12:10.626][Info] Loading results...
[18:12:10.626][Info] [www.pixiv.net][Json] Loading page https://public-api.secure.pixiv.net/v1/works/xxxxxxxx.json?image_sizes=large
[18:12:11.751][Warning] [Qt][qt.network.monitor] Could not find the interface for the local address.
[18:12:12.699][Info] [www.pixiv.net][Json] Receiving page https://public-api.secure.pixiv.net/v1/works/xxxxxxxx.json?image_sizes=large
[18:12:12.700][Error] [www.pixiv.net][Json] Loading error: Error transferring https://public-api.secure.pixiv.net/v1/works/xxxxxxxx.json?image_sizes=large - server replied: Not Found (203)
[18:12:12.700][Warning] [www.pixiv.net] No valid source of the site returned result.
```

**System information**

- OS: [e.g. Windows 10]
- Grabber version: 7.6.2

**Comment by uvhat** [comment]
No any answer for several months about broken galleries download.

Well, it seems author drops support for pixiv.

**Comment by Bionus** [comment]
Indeed, seems like they deprecated the "public-api" endpoint recently, which was used to fetch galleries and image details.
I'll push an update to use the "app-api" endpoint instead.

**Comment by Bionus** [comment]
Should be fixed in [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) by cc882aa35548f697ba0849a28b281f6912ba0bdb, seems like I put the duplicate issue in the commit message instead of this one 🤔

**Comment by uvhat** [comment]
This fix works, thanx. I compiled this to js and replaced gallery and parse blocks in pixiv model.js

**Comment by Edszx** [comment]
Posts with multiple images work now in 7.7.0, but the images downloaded are 1200px resizes, not the originals, this doesn't happen for individual images (the ones that are not part of a post with multiple images).
