### ISSUE TITLE
how do you apply a tag blacklist to the bulk download feature ?

### ISSUE THREAD

**Issue by jack652** [Bionus/imgbrd-grabber#2486]
how do you apply a tag blacklist to the bulk download feature ?

**Comment by Bionus** [comment]
You can just set your blacklist in the settings. See the [docs](https://bionus.github.io/imgbrd-grabber/docs/search.html).
Then the blacklist will be applied everywhere, including the batch downloads (unless of course the download's "get blacklisted" setting is set to "true").
