### ISSUE TITLE
Downloading Censored tags on Danbooru

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#249]
```
via the Better Better Booru userscript 
(https://github.com/pseudonymous/better-better-booru), censored tags like 
'shota' and 'loli' can be viewed on non-gold/platinum accounts. It would be 
nice to have this feature.
```

Original issue reported on code.google.com by `duckthro...@gmail.com` on 20 Jul 2013 at 7:08

**Comment by FredericaBernkastel** [comment]
I think, this feature is broken. Im trying various sources (XML/JSON), but still no results for the censored tags.
Please check it!

**Comment by Bionus** [comment]
It's because they updated their APIs a few months ago and removed this bug.
