### ISSUE TITLE
Favorites/Monitor triggered on program launch even when interval hasn't passed.

### ISSUE THREAD

**Issue by sbobbo** [Bionus/imgbrd-grabber#2490]
I am on 7.6.2. I have a large number of tags favorited, and my favorites.json file has every tag set with intervals of 86400, 259200, and 158400. So 24 hours minimum.

All of a sudden on these newer versions, I have noticed that when Grabber launches, no matter how long it has been since the last time it autodownloaded all the tags, it will start autodownloading all of the tags. It acts like I haven't run the program in multiple days. If I let it run, and it updates the favorites.json file with the "lastCheck" for all the tags, and then i immediately close the program when it finishes and relaunch it, it does all of them all over again. This did not happen on older versions of grabber, so something likely changed when it comes to the monitor running that is triggering this to occur.

**Comment by sbobbo** [comment]
Hmm, maybe this is related to  #2401?

I just noticed the setting "Use system locale for dates and numbers." Maybe this is the problem, like its reading the date wrong in one spot and always assuming its been forever since the last run.

Also, just noticed that if i de-select that setting and hit OK and then re-open settings, it shows selected again...

**Comment by sbobbo** [comment]
Doesn't seem to be related to that setting, at least not on the face of it. If i change useSystemLocale in settings.ini to false and re-launch, it still immediately starts downloading everything.

**Comment by Bionus** [comment]
It was caused by the "check now" button that was "on" on startup for some reason. 👍
