### ISSUE TITLE
don't know if this belong here

### ISSUE THREAD

**Issue by naruhina2016** [Bionus/imgbrd-grabber#2492]
Hi,

I have a question is it really impossible to download pictures from sankaku complex?
If not how can i download it faster its really going so slow
I am using version 7.1.1

Thanks in Advance.

**Comment by SvyraCosmix** [comment]
Here's a quick video of someone telling me how

**Comment by Bionus** [comment]
Hello

As @SvyraCosmix rudely said, Sankaku isn't officially supported in Grabber, but multiple people suggested alternatives to install it on the latest version, such as the `model.js` file linked above, or multiple ones in the other ticket.

Make sure to update to the latest version before that though.

**Comment by naruhina2016** [comment]
can someone please send me the link again its expired or it wont let me join

**Comment by Bionus** [comment]
The discord link can be found in the website's header:
https://bionus.github.io/imgbrd-grabber/

**Comment by naruhina2016** [comment]
> The discord link can be found in the website's header: https://bionus.github.io/imgbrd-grabber/

i mean the one that svyra sended

**Comment by naruhina2016** [comment]
i did where to go next?

**Comment by SvyraCosmix** [comment]
![Uploading Screenshot_20211017-101508_Discord.jpg…]()

**Comment by naruhina2016** [comment]
ok i download it now what?

**Comment by SvyraCosmix** [comment]
Look at the video I sent

**Comment by SvyraCosmix** [comment]
Go to appdata, bionus, grabber, sites, sankaku, just paste and replace the file
