### ISSUE TITLE
Grabber CLI not returning images or their tags from Danbooru | Grabber 7.6.2

### ISSUE THREAD

**Issue by KohaiMomomiya** [Bionus/imgbrd-grabber#2494]
**Bug description**
Grabber CLi is not returing images (--return-image, --ri) or their tags (--return-tags, --rt) from Danbooru.

**Steps to reproduce**

Use the following commands with the Grabber CLI:

grabber --sources "danbooru.donmai.us" --tags "tag1 tag2 ..." --ri
grabber --sources "danbooru.donmai.us" --tags "tag1 tag2 ..." --rt

**Expected behavior**

Return URLs for each result when querying images with --return-images/--ri
Return tags for each result when querying images' tags with  --return-tags/--rt

Results should be similar to the documentation: 
https://bionus.github.io/imgbrd-grabber/docs/cli.html#get-images
https://bionus.github.io/imgbrd-grabber/docs/cli.html#get-tags

**Context**

"main - ri.log" is the main log file generated when using the flag "--return-images, --ri"
"main - rt.log" is the main log file generated when using the flag "--return-tags, --rt"

[main - ri.log](https://github.com/Bionus/imgbrd-grabber/files/7316521/main.-.ri.log)
[main - rt.log](https://github.com/Bionus/imgbrd-grabber/files/7316522/main.-.rt.log)
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/7316523/settings.ini.txt)

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

![Screenshot 2021-10-09 165434](https://user-images.githubusercontent.com/2092838/136675702-4001085d-cc9e-467b-b228-c801dd3ec539.png)

![Screenshot 2021-10-09 165523](https://user-images.githubusercontent.com/2092838/136675701-e300b0a5-50a0-4e60-b0e0-b918282f4594.png)

**System information**

- OS: Windows 11 Pro - Version 21H1 - OS Build: 22000.194
- Grabber version: 7.6.2

**Additional context**

Queries with Grabber GUI are not affected.
Queries to return image count (--return-count, --rc) are not affected (fixed in #2448).
![Screenshot 2021-10-09 170444](https://user-images.githubusercontent.com/2092838/136675829-7c23e03f-66e8-41ba-9e38-75197bb87d01.png)

**Comment by KohaiMomomiya** [comment]
Hello @Bionus 
Thanks for the reply.  Didn't know the --max argument was needed, since it was not mentioned in the documentation. 

I tried following your recommendation (get the image count beforehand) but no dice.
See the screenshots below:

![Screenshot 2021-10-09 192539](https://user-images.githubusercontent.com/2092838/136678015-26cdcf04-e896-44c3-8533-1dbf7a15b2ef.png)
![image](https://user-images.githubusercontent.com/2092838/136678223-909c2b82-3b3a-41cf-ac7e-eae20bb0fda4.png)

Also tried to use some parameters based in the documentation:
![Screenshot 2021-10-09 193944](https://user-images.githubusercontent.com/2092838/136678258-f58ce797-7d3b-453e-bcde-3d3fc4fb429c.png)

**Comment by Bionus** [comment]
You're still not using `--max` in any of your screenshots though.
As for your `--return-tags` call (which does not need `--max`) it's likely because you're using more than 2 tags on Danbooru without providing premium credentials.
