### ISSUE TITLE
No results when searching for tags on Rule34.xxx

### ISSUE THREAD

**Issue by haro1721** [Bionus/imgbrd-grabber#2496]
Expected URL to resolve: https://rule34.xxx/index.php?page=post&s=list&tags=<insert tags here>

Imgbrd-Grabber tries to resolve: https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=pool%3A1%20<insert tags here>

I'm not sure this is intended behavior.

**Comment by Tiffys** [comment]
There was an announcement yesterday:

> We added a dedicated server for API queries! To have it working we'll need all tools and discord bots who user our API to switch to the new hostname. All API queries should go to https://api.rule34.xxx/ 
> The queries themselves stay the same. 
> 
> If you're a dev or are using our API: Please update the hostname. I tried doing a 301 redirect with query string but apparently node-fetch and request ignore redirects by default. I'll give it a few days before setting up the redirect again.
> 
> If you're a user and happen to be in discord server specifically for a bot: please tell the team to update the hostname to api.rule34.xxx or copy/paste this message.  If the bot has any 'r34' function, its likely using our API.

Bionus will need to update it with the new API.
