### ISSUE TITLE
don't know if this belong here part 2

### ISSUE THREAD

**Issue by naruhina2016** [Bionus/imgbrd-grabber#2499]
Hi,

I have a questiion isi it really impossible to download pictures from sankaku complex?

If not how can i download it faster its really going so slow

I am using 7.6.2 now 

Thanks in Advance.

ps: i did not realized that people were replying until now sorry.

**Comment by Bionus** [comment]
Hello, please don't create duplicate issues.
Closing in favor of #2492 2492
