### ISSUE TITLE
Application Crashes On Any Search

### ISSUE THREAD

**Issue by Ikazuchi-san** [Bionus/imgbrd-grabber#2502]
This always happened without fail on my PC. From the time i've installed it, it never worked.
Whenever i do any search on the program, it starts loading the results, then it crashes right away.

===================================================================================
The following is my main.log file:

[20:56:21.085][Info] Temp directory purged of 0/0 files (0 failed)
[20:56:21.433][Info] Software version: 7.6.2.
[20:56:21.434][Info] Software CPU architecture: x64.
[20:56:21.434][Info] Computer CPU architecture: x86_64.
[20:56:21.434][Info] Qt CPU architecture: x86_64.
[20:56:21.434][Info] Computer platform: Windows 10 Version 2009.
[20:56:21.435][Info] Path: `C:/internalHD2/programs/Grabber`
[20:56:21.435][Info] Loading preferences from `C:/Users/Schwarzen-Regen/AppData/Local/Bionus/Grabber/settings.ini`
[20:56:21.436][Info] Temporary path: `C:/Users/Schwarzen-Regen/AppData/Local/Temp\Grabber`
[20:56:21.436][Info] Sources found: 21
[20:56:21.436][Info] SSL libraries: OpenSSL 1.1.1l  24 Aug 2021
[20:56:21.473][Info] Setting language to 'English' (`C:\internalHD2\programs\Grabber\languages\English.qm`)...
[20:56:21.475][Info] 21 sources found: anime-pictures.net (Anime pictures), api.twitter.com (Twitter), behoimi.org (Danbooru), danbooru.donmai.us (Danbooru (2.0)), derpibooru.org (Philomena), e-hentai.org (E-Hentai), e621.net (E621), exhentai.org (E-Hentai), gelbooru.com (Gelbooru (0.2)), hijiribe.donmai.us (Danbooru (2.0)), konachan.com (Moebooru), nhentai.net (NHentai), rule34.paheal.net (Shimmie), rule34.xxx (Gelbooru (0.2)), safebooru.org (Gelbooru (0.2)), sonohara.donmai.us (Danbooru (2.0)), tentaclerape.net (Shimmie), www.deviantart.com (DeviantArt), www.pixiv.net (Pixiv), www.zerochan.net (Zerochan), yande.re (Moebooru)
[20:56:21.509][Warning] It seems that Imgbrd-Grabber hasn't shut down properly last time.
[20:56:22.526][Info] Updating checkboxes.
[20:56:22.527][Info] [anime-pictures.net] Logging in...
[20:56:22.527][Info] [api.twitter.com] Logging in...
[20:56:22.527][Info] [api.twitter.com] Login finished: success.
[20:56:22.528][Info] [gelbooru.com] Logging in...
[20:56:22.528][Info] [www.pixiv.net] Logging in...
[20:56:22.528][Info] [www.pixiv.net] Refreshing OAuth2 token...
[20:56:22.529][Warning] [www.pixiv.net] Cannot refresh OAuth2 token without a refresh token
[20:56:22.529][Info] [www.pixiv.net] Login finished: failure.
[20:56:22.529][Info] [www.zerochan.net] Logging in...
[20:56:23.024][Info] [www.zerochan.net] Login finished: failure.
[20:56:23.397][Info] [anime-pictures.net] Login finished: failure.

===================================================================================

From here is my settings.ini file:

[General]
last_check_for_updates=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x87q\x4\xa2\x45s\0)
crashed=false
whitelistedtags=
add=
globalPostFilter=
globalPostFilterExplicit=false
whitelist_download=image
limit=20
columns=1
source_1=xml
source_2=json
source_3=regex
source_4=rss
tagsautoadd=10
start=restore
hidefavorites=20
autodownload=false
hideblacklisted=false
showtagwarning=true
showwarnings=true
getunloadedpages=false
invertToggle=false
confirm_close=true
send_usage_data=true
check_for_updates=86400
tempPathOverride=
preloadAllTabs=false
keyAcceptDialog=Ctrl+Y
keyDeclineDialog=Ctrl+N
downloadblacklist=false
ignoredtags=
resizeInsteadOfCropping=true
thumbnailUpscale=1
autocompletion=true
useregexfortags=true
infiniteScroll=disabled
infiniteScrollRememberPage=false
theme=Default
tagsposition=top
preload=0
slideshow=0
resultsScrollArea=true
resultsFixedWidthLayout=false
imageCloseMiddleClick=true
imageNavigateScroll=true
imagePositionImageV=center
imagePositionImageH=left
imagePositionAnimationV=center
imagePositionAnimationH=left
imagePositionVideoV=center
imagePositionVideoH=left
imageBackgroundColor=
serverBorder=0
serverBorderColor=#000000
borders=3
language=English
useSystemLocale=true
firstload=false
reverse=false
sites=anime-pictures.net, api.twitter.com, behoimi.org, danbooru.donmai.us, derpibooru.org, gelbooru.com, hijiribe.donmai.us, safebooru.org, sonohara.donmai.us, www.deviantart.com, www.pixiv.net, www.zerochan.net, yande.re
state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\0\0\0\x1+\0\0\x2X\xfc\x2\0\0\0\x2\xfc\0\0\0\x1a\0\0\0\x8c\0\0\0\x32\x1\0\0\x17\xfa\0\0\0\0\x2\0\0\0\x4\xfb\0\0\0\x1a\0\x64\0o\0\x63\0k\0_\0i\0n\0t\0\x65\0r\0n\0\x65\0t\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x1a\0\xff\xff\xff\xfb\0\0\0\x12\0\x64\0o\0\x63\0k\0_\0w\0i\0k\0i\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x1a\0\xff\xff\xff\xfb\0\0\0\x10\0\x64\0o\0\x63\0k\0_\0k\0\x66\0l\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x1a\0\xff\xff\xff\xfb\0\0\0\x1c\0\x64\0o\0\x63\0k\0_\0\x66\0\x61\0v\0o\0r\0i\0t\0\x65\0s\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x1a\0\xff\xff\xff\xfb\0\0\0\x16\0\x64\0o\0\x63\0k\0O\0p\0t\0i\0o\0n\0s\x1\0\0\0\xab\0\0\x1\xc7\0\0\0\xa3\0\xff\xff\xff\0\0\x2\xb7\0\0\x2X\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\xcb\0\0\0\xa4\0\0\x5\xb3\0\0\x3<\0\0\x1\xcc\0\0\0\xca\0\0\x5\xb2\0\0\x3;\0\0\0\0\0\0\0\0\a\x80\0\0\x1\xcc\0\0\0\xca\0\0\x5\xb2\0\0\x3;)"
batchSplitter="12,12"
mergeresults=false

[GAnalytics]
cid=74b79150-af96-4d2d-b48c-6a4cf18e1c23

[Save]
path=
filename=
automaticretries=0
downloadoriginals=true
samplefallback=true
replaceblanks=false
keepDate=true
headerDetection=true
separator=" "
noJpeg=true
path_real=
path_favorites=
md5Duplicates=save
md5DuplicatesSameDir=save
keepDeletedMd5=false
multiple_files=copy
filename_real=
filename_favorites=
artist_empty=anonymous
artist_sort=original
artist_useall=true
artist_multiple_limit=1
artist_multiple_keepN=1
artist_multiple_keepNThenAdd_keep=1
artist_multiple_keepNThenAdd_add=" (+ %count%)"
artist_sep=+
artist_value=multiple artists
artist_multiple=keepAll
copyright_empty=misc
copyright_sort=original
copyright_useall=true
copyright_multiple_limit=1
copyright_multiple_keepN=1
copyright_multiple_keepNThenAdd_keep=1
copyright_multiple_keepNThenAdd_add=" (+ %count%)"
copyright_sep=+
copyright_value=crossover
copyright_multiple=keepAll
copyright_useshorter=true
character_empty=unknown
character_sort=original
character_useall=true
character_multiple_limit=1
character_multiple_keepN=1
character_multiple_keepNThenAdd_keep=1
character_multiple_keepNThenAdd_add=" (+ %count%)"
character_sep=+
character_value=group
character_multiple=keepAll
model_empty=unknown
model_sort=original
model_useall=true
model_multiple_limit=1
model_multiple_keepN=1
model_multiple_keepNThenAdd_keep=1
model_multiple_keepNThenAdd_add=" (+ %count%)"
model_sep=+
model_value=multiple
model_multiple=keepAll
photo_set_empty=unknown
photo_set_sort=original
photo_set_useall=true
photo_set_multiple_limit=1
photo_set_multiple_keepN=1
photo_set_multiple_keepNThenAdd_keep=1
photo_set_multiple_keepNThenAdd_add=" (+ %count%)"
photo_set_sep=+
photo_set_value=multiple
photo_set_multiple=keepAll
species_empty=unknown
species_sort=original
species_useall=true
species_multiple_limit=1
species_multiple_keepN=1
species_multiple_keepNThenAdd_keep=1
species_multiple_keepNThenAdd_add=" (+ %count%)"
species_sep=+
species_value=multiple
species_multiple=keepAll
meta_empty=none
meta_sort=original
meta_useall=true
meta_multiple_limit=1
meta_multiple_keepN=1
meta_multiple_keepNThenAdd_keep=1
meta_multiple_keepNThenAdd_add=" (+ %count%)"
meta_sep=+
meta_value=multiple
meta_multiple=keepAll
MetadataPropsysExtensions=jpg jpeg mp4
MetadataPropsys\size=0
MetadataExiftoolExtensions=jpg jpeg png gif mp4
MetadataExiftool\size=0
limit=0
simultaneous=1

[Sources]
Types=icon
Letters=3
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3!\0\0\0\xc7\0\0\x4]\0\0\x3\x1a\0\0\x3\"\0\0\0\xed\0\0\x4\\\0\0\x3\x19\0\0\0\0\0\0\0\0\a\x80\0\0\x3\"\0\0\0\xed\0\0\x4\\\0\0\x3\x19)

[Log]
show=true

[Monitoring]
startupDelay=0
enableTray=false
minimizeToTray=false
closeToTray=false
headerState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\t\xe0\x1\0\0\0\x4\0\0\0\a\0\0\0}\0\0\0\x6\0\0\0}\0\0\0\x5\0\0\0}\0\0\0\b\0\0\0}\0\0\x2q\0\0\0\t\x1\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0}\xff\xff\xff\xff\0\0\0\x84\0\0\0\0\0\0\0\t\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\0\0\0\0)

[Batch]
end=0

[ImageSize]
maxWidth=1000
maxWidthEnabled=false
maxHeight=1000
maxHeightEnabled=false

[WebServices]
1\name=IQDB
1\url="https://iqdb.org/?url={url}"
1\order=1
2\name=SauceNAO
2\url="https://saucenao.com/search.php?db=999&url={url}"
2\order=2
3\name=Google
3\url="https://www.google.com/searchbyimage?image_url={url}"
3\order=3
4\name=TinEye
4\url="https://www.tineye.com/search/?url={url}"
4\order=4
5\name=Yandex
5\url="https://yandex.ru/images/search?rpt=imageview&img_url={url}"
5\order=5
6\name=waifu2x
6\url="http://waifu2x.udp.jp/index.html?url={url}"
6\order=6

[Zoom]
singleWindow=false
showTagCount=false
viewSamples=false
scaleUp=false
useVideoPlayer=true
showVideoPlayerControls=true
showGifPlayerControls=true
tagOrder=type
Shortcuts\keyQuit=Esc
Shortcuts\keyPrev=Left
Shortcuts\keyNext=Right
Shortcuts\keyDetails=D
Shortcuts\keySaveAs=Ctrl+Shift+S
Shortcuts\keySave=Ctrl+S
Shortcuts\keySaveNQuit=Ctrl+W
Shortcuts\keyOpen=Ctrl+O
Shortcuts\keySaveFav=Ctrl+Alt+S
Shortcuts\keySaveNQuitFav=Ctrl+Alt+W
Shortcuts\keyOpenFav=Ctrl+Alt+O
Shortcuts\keyToggleSlideshow=Space
Shortcuts\keyToggleFullscreen=F11
Shortcuts\keyDataToClipboard=Ctrl+C

[Main]
Shortcuts\keyQuit=Ctrl+Q
Shortcuts\keyFocusSearch=Ctrl+L
Shortcuts\keyCloseTab=Ctrl+W
Shortcuts\keyNewTab=Ctrl+T
Shortcuts\keyPrevTab=Ctrl+PgDown
Shortcuts\keyNextTab=Ctrl+PgUp
Shortcuts\keyBrowseSave=Ctrl+O

[Coloring]
Colors\artists=#aa0000
Colors\circles=#55bbff
Colors\copyrights=#aa00aa
Colors\characters=#00aa00
Colors\species=#ee6600
Colors\metas=#ee6600
Colors\models=#0000ee
Colors\generals=#000000
Colors\favorites=#ffc0cb
Colors\keptForLater=#000000
Colors\blacklisteds=#000000
Colors\ignoreds=#999999
Fonts\artists="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\circles="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\copyrights="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\characters="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\species="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\metas="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\models="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\generals="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\favorites="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\keptForLater="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\blacklisteds="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"
Fonts\ignoreds="MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0"

[Margins]
main=10
horizontal=6
vertical=6

[Proxy]
use=false
useSystem=false
type=http
hostName=
port=0
user=
password=

[Exec]
tag_before=
image=
tag_after=
SQL\driver=QMYSQL
SQL\host=
SQL\user=
SQL\password=
SQL\database=
SQL\before=
SQL\tag_before=
SQL\image=
SQL\tag_after=
SQL\after=

[SourcePresets]
size=0

[Downloads]
Groups\headerState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5\xdc\0\0\0\f\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0}\xff\xff\xff\xff\0\0\0\x84\0\0\0\0\0\0\0\f\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\0\0\0\0)
Uniques\headerState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4\xe2\0\0\0\n\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0}\xff\xff\xff\xff\0\0\0\x84\0\0\0\0\0\0\0\n\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\0\0\0\0)

[Favorites]
order=name
reverse=false

**Comment by casey-mcgee1** [comment]
I am also having this same problem. I currently have tried uninstalling/re-installing to no avail. Whenever I search anything, such as "Saber", for example, it just crashes and when I try to re-launch it the program asks me if I want to continue to a previous session. Wither way (yes or no) I get the same result if I search for any image again. Comment to bump. :) Love this program and want to get back to using it.

**Comment by Bionus** [comment]
Moving discussion to #2518
In the meantime, you should not enable Pixiv unless you log into it
