### ISSUE TITLE
Make the program more compatible with 4K screens

### ISSUE THREAD

**Issue by SvyraCosmix** [Bionus/imgbrd-grabber#2508]
If you look at the image some of the text and the tabs dont scale up and theres no setting to change this
![Screenshot 2021-10-21 134516](https://user-images.githubusercontent.com/19334444/138369976-1487b8a8-ddfc-4f0a-af98-7f655b5262ae.png)

**Comment by Bionus** [comment]
Now it should already look much better on high-DPI screens, especially on Windows (on macOS it was already fine).
No idea about Linux though.

I'm sure there's still some quirks here and there, so feel free to point them out. 👍 

## Before
### 100%
![image](https://user-images.githubusercontent.com/882719/142065020-69a4f74a-4e66-4a39-bed2-719c7eaf839b.png)

### 200%
![image](https://user-images.githubusercontent.com/882719/142065192-a15d92c8-75db-4ad5-af13-155abb87f58f.png)

## After
### 100%
![image](https://user-images.githubusercontent.com/882719/142065354-8c6924e4-447d-4610-8fac-83737a98ca21.png)

### 200%
![image](https://user-images.githubusercontent.com/882719/142065291-8254f8f4-9af5-427c-aeef-86437ef75a8a.png)
