### ISSUE TITLE
compile error when building from develop branch on manjaro

### ISSUE THREAD

**Issue by silverhikari** [Bionus/imgbrd-grabber#2512]
when trying to compile on manjaro using the source from the develop branch, it ends with a compile error from lld.
```
/usr/bin/ld: ../lib/liblib.a(filename.cpp.o): in function `Filename::path(QMap<QString, Token>, Profile*, QString, int, QFlags<Filename::PathFlag>) const [clone .localalias]':
filename.cpp:(.text+0x67d8): undefined reference to `QString FilenameExecutionVisitor::variableToString<int>(QString const&, int, QMap<QString, QString> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [gui/CMakeFiles/gui.dir/build.make:1475: gui/Grabber] Error 1
make[1]: *** [CMakeFiles/Makefile2:382: gui/CMakeFiles/gui.dir/all] Error 2
```

**Comment by mkg20001** [comment]
On nixOS we needed this patch https://raw.githubusercontent.com/NixOS/nixpkgs/71f7a9cf2774fffbd6eb19729f6db46c9f689dcc/pkgs/applications/graphics/imgbrd-grabber/variableToString-instantiation.patch to get it working

Not sure what causes us needing that patch

**Comment by silverhikari** [comment]
it seems that patch fixed the problem i was seeing and it finishes building.

**Comment by Bionus** [comment]
Strange, I don't see why
```
template
QString FilenameExecutionVisitor::variableToString<int>(const QString &name, int val, const QMap<QString, QString> &options);
```

Is not simply getting caught by this just a few lines below
```
template <typename T>
QString FilenameExecutionVisitor::variableToString(const QString &name, T val, const QMap<QString, QString> &options)
```

Looks like the exact same with T=int
And this only on some compilers 🤔

Well glad you got it working anyway
