### ISSUE TITLE
New search won't show results when any of the thumbnails from previous search wasn't loaded

### ISSUE THREAD

**Issue by Desk5103** [Bionus/imgbrd-grabber#2515]
### Bug description

**When you search something and do another search in the same tab before waiting for all the thumbnails to load, the later search will stuck at "Loading page \`source url here\`"**

For an example, if you search 'A' and again search 'B' (in the same tab) before all the thumbnails from search 'A' loads, search 'B' wont show any result at all.

There are no specific sources that this issue is unique to, it will work on any source afaik. (I tested some sources and all gave the same results)

### Steps to reproduce

**1. Search anything that gives results.** 
**2. Wait till the loading statuses of the thumbnails show up in the tab.** 
**3. Then before all the thumbnails loads do another search in the same tab.**
**4. You can see the new search won't show any results.**

(at 1st step empty search is ok too, if all the thumbnails loads instantly it won't work, in 3rd step its ok if there's some of the thumbnails that are loaded btw, if there's any of the thumbnails that are currently loading issue will reproduce)

**Expected behavior**

Well of course the expected behavior is the new search should show some response in the window.

**Context**

Guess this might help in some way to debug the problem. [main.log](https://github.com/Bionus/imgbrd-grabber/files/7466745/main.log)

here's a part of the log,
```ruby
[15:12:45.667][Info] Loading results...
[15:12:45.667][Info] [rule34.paheal.net][Html] Loading page `http://rule34.paheal.net/post/list/1`
[15:12:46.492][Info] [rule34.paheal.net][Html] Receiving page `http://rule34.paheal.net/post/list/1`
[15:12:46.518][Info] [rule34.paheal.net][Html] Parsed page `http://rule34.paheal.net/post/list/1`: 70 images (70), 10 tags (10), -1 total (50000), 500 pages (500)
[15:12:47.677][Info] Loading results...
[15:12:47.680][Info] [rule34.paheal.net][Html] Loading page `http://rule34.paheal.net/post/list/asd/1`
```
as u can see in the second search, it gets stuck at `"Loading page"`

**System information**

- OS: Windows 11 (21H2 OS Build 22000.132)
- Grabber version: 7.6.2 (x64)

**Comment by Desk5103** [comment]
It seems you need to have at least **40** set to **images per page** to reproduce this bug. `(Tools > Options > Sources > Images per page)`

And I have 100 set to that option, so better just set it to 100 when trying to reproduce.

**Comment by brazenvoid** [comment]
Same as #2111

**Comment by brazenvoid** [comment]
@Bionus As a workaround, can you make the page loading progress bar to not end till all thumbs are loaded? 

There is no indication even if subsequent loading is queued for the thumbs. At least we can make a more informed decision about closing a tab.

**Comment by Bionus** [comment]
Yes after some more investigation it seems to be an issue with the networking code, where if a request was aborted before it's even started, it would lock one of the simultaneous download slots and never releasing it. I'm working on a fix.

Not sure which progress bar you're talking about though? You mean the greyed out buttons?

**Comment by brazenvoid** [comment]
> Yes after some more investigation it seems to be an issue with the networking code, where if a request was aborted before it's even started, it would lock one of the simultaneous download slots and never releasing it. I'm working on a fix.
> 
> Not sure which progress bar you're talking about though? You mean the greyed out buttons?

There is a progress bar at the bottom in search tabs which comes up. I assume, it shows the initial source hits for the page as the number of steps equals the number of sources. Nowadays we have such fast connections that it only comes up for an instant.
