### ISSUE TITLE
Crash to desktop when I try and download anything

### ISSUE THREAD

**Issue by sadfoihg** [Bionus/imgbrd-grabber#2517]
**Steps to reproduce**

1.Start grabber
2. click any preview image (which would normally open it and start a download)
3. crash

Alternatively
1.Start grabber
2.select any image
3. hit "get selected"
4. navigate to "downloads"
5. hit download
6. crash

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
* [main.log.txt](https://github.com/Bionus/imgbrd-grabber/files/7507292/main.log.txt)
*
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* [settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/7507287/settings.ini.txt)
*
* Provide the crash dump that was linked by the Crash Reporter tool.
* There was no crash dump offered by any tool. Best I got was when running it from terminal, this is the output on termination
 `Segmentation fault (core dumped)`

**System information**

- OS: PRETTY_NAME="Pop!_OS 21.04"
ID_LIKE="ubuntu debian"

- Grabber version: 7.6.2, tar.gz version

**Additional context**

Yeah I dunno really what I should add here, whenever there's something like a download I get a very unceremonious crash.

**Comment by sadfoihg** [comment]
Have further tried it by building it myself, same results.

**Comment by Bionus** [comment]
Try to disable the  Pixiv source, it is known to cause issues on the latest release if you didn't login.

**Comment by Bionus** [comment]
Moving discussion to #2518
In the meantime, you should not enable Pixiv unless you log into it
