### ISSUE TITLE
r34 API changed

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#2519]
There was an announcement yesterday:

> We added a dedicated server for API queries! To have it working we'll need all tools and discord bots who user our API to switch to the new hostname. All API queries should go to https://api.rule34.xxx/ 
> The queries themselves stay the same. 
> 
> If you're a dev or are using our API: Please update the hostname. I tried doing a 301 redirect with query string but apparently node-fetch and request ignore redirects by default. I'll give it a few days before setting up the redirect again.
> 
> If you're a user and happen to be in discord server specifically for a bot: please tell the team to update the hostname to api.rule34.xxx or copy/paste this message.  If the bot has any 'r34' function, its likely using our API.

**Comment by Bionus** [comment]
I'll update the default endpoint, but I don't think it'll impact users that update.
I'll see what can be done about that.
