### ISSUE TITLE
failing to load my favorites properly.

### ISSUE THREAD

**Issue by paperclaw** [Bionus/imgbrd-grabber#2520]
When I open up one of my favorited tags this gets added before the tag and can not be deleted

_**Shell Dlg 2'; font-size:8pt; font-style:normal; font-weight:400; text-decoration:none;">**_

I could only use the highlight and cut command to get rid of it to load the tag.

**Comment by Bionus** [comment]
Strange, could you share your `favorites.json` file?
It'd be interesting to see if it's there as well.

Does this also happen when you search/middle click the favorite (to open it in a new tab)?
If you search this favorite tag in a normal tab, does it get colored pink? (or an image with this tag)

**Comment by paperclaw** [comment]
i use the windows version so i do not know where to find that file or its related form. it does happen when i search tags and middle click(text and image). the text does show up pink 90% of the time.

**Comment by Bionus** [comment]
You can find this file here:
```
C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber
```

**Comment by paperclaw** [comment]
i had a look using the find function and could not find the Shell Dlg 2'; font-size:8pt; font-style:normal; font-weight:400; text-decoration:none;">

i thick it my be do to having 200+ faves (or the file having 3900+ lines.

**Comment by Bionus** [comment]
Yes it's normal that you can't find this, but it could be caused by something else from that file.
If you don't feel like sharing it here, you can also send it to me on Discord (Bionus#2577) or by mail (bio.nus@hotmail.fr) 👍

**Comment by paperclaw** [comment]
if you had not noticed i sent the file to your email.

**Comment by paperclaw** [comment]
Just letting you know the Shell Dlg 2'; font-size:8pt; font-style:normal; font-weight:400; text-decoration:none;">   Bug is still there after I updated. I don't know if you worked on it at all. So just wanted you to know just in case there was some thing that i missed that fixed it.

**Comment by paperclaw** [comment]
it is still giving me the same guff, but only with the large number of favorites. when I star with a empty favorites .json it seem to not be a problem. Might try with a empty and re favoriting many tags to see when it starts to give guff.
