### ISSUE TITLE
Multiple characters always saved as group rather than character 1 character 2 etc

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#2524]
Currently I have it set up like `%character%/%character:separator=spaces%_%id%.%ext%` and the problem is it's not putting multiple character names. %character% isn't doing character1 character2 it's doing character1 or group. If it's ever more than 1 character it just puts it in "group". It makes sorting an absolute nightmare.

Am I doing something wrong? How do I fix this behavior?

**Comment by Bionus** [comment]
Hello, this is expected behavior, which you can change in the settings, in the "Save" section ("Tags > Characters").
Just set it to "keep all tags" if that's the behavior you want.
