### ISSUE TITLE
How to rename files?

### ISSUE THREAD

**Issue by TeKett** [Bionus/imgbrd-grabber#2527]
It just says "unable to detect md5 file", for each file it finds based on the original filename.

**Comment by Bionus** [comment]
Did you read this page: https://bionus.github.io/imgbrd-grabber/docs/tools/image-renamer.html ?
You need to have the MD5 (or the ID for some sources) in the fillename in order for Grabber to be able to rename the files.

**Comment by TeKett** [comment]
> Did you read this page: https://bionus.github.io/imgbrd-grabber/docs/tools/image-renamer.html ? You need to have the MD5 (or the ID for some sources) in the fillename in order for Grabber to be able to rename the files.

I do have that no idea why it didnt work. It started to randomly work after a while but i decided to just scrap and redownload instead.
