### ISSUE TITLE
spaces=spaces

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#2528]
In file naming scheme I had "%character:separator=spaces%_%id%.%ext%" and it doesn't add " " between names. They end up looking like "cloud strifespacestifa lockhart_3908031" with literally the word "spaces" written out.

How am I supposed to make it actual spaces?

**Comment by Desk5103** [comment]
Just use ' ' not the word "spaces", like this `%character:separator= %_%id%.%ext%`

**Comment by Bionus** [comment]
Exactly, you'll need to put an actual space for it to work 😄
