### ISSUE TITLE
"Download images containing blacklisted tags" not working for monitor

### ISSUE THREAD

**Issue by TeKett** [Bionus/imgbrd-grabber#2531]
Since i saw that you can still download images containing blacklisted tags, i expected that i could use the blacklist to exclude artists/tags, i already have as monitors, from showing up when i search to avoid dupes, but apparently it doesn't work that way? The monitor doesn't download blacklisted tags.

**Comment by Bionus** [comment]
Make sure that the monitor's "download blacklisted" is set correctly, as monitors have their own setting, just like batch downloads, as to whether blacklisted images should be downloaded.

![image](https://user-images.githubusercontent.com/882719/144518592-6469ceb3-e10f-4c47-bb3e-f0ad11de48de.png)
