### ISSUE TITLE
Highlight images that have already been downloaded

### ISSUE THREAD

**Issue by jamesWalker55** [Bionus/imgbrd-grabber#2532]
**Is your feature request related to a problem? Please describe**

When browsing images in grabber, there is no way to know whether an image has already been downloaded without clicking on the image. This makes it very slow when revisiting previous searches to download new images, and I have to click on every image to check if the image is already downloaded.

**Describe the solution you'd like**

Some kind of indicator that an image is already downloaded from the main window. (In the image window, this is indicated by the "Download" button which changes to "Already exists" if the image exists.) Or maybe an option to hide downloaded images?

**Comment by Desk5103** [comment]
You can use `-grabber:downloaded` in post filtering

something like this,
![image](https://user-images.githubusercontent.com/72625865/144756523-e5e7af4c-c476-4ef7-8808-35fa8f09febe.png)

**Comment by jamesWalker55** [comment]
I didn't know that, thanks.

There's more filters on this page which is really useful: https://bionus.github.io/imgbrd-grabber/docs/search.html
