### ISSUE TITLE
Rename existing image - blank preview

### ISSUE THREAD

**Issue by Glizzyist** [Bionus/imgbrd-grabber#2534]
When using the rename existing image tool to rename any amount of files and selecting **rule34.paheal.net as the source for the renaming** the preview will show a blank space at the top of the list instead of an actual image that should be renamed and the log states:
> [Warning] [Qt][default] QPixmap::scaleHeight: Pixmap is a null pixmap
> [Warning] [Qt][default] QFile::rename: Empty or null file name

And the end result is that none of the selected images get renamed. From what testing I've done this only seems to happen with the aforementioned site when used as the source.

![screenshot](https://user-images.githubusercontent.com/96061312/145856552-f8366e35-f8bc-40ac-8aa6-dd9195382486.png)

- OS: Windows 10 64-bit
- Tested on Grabber version: 7.6.2 64-bit & 7.5.0 64-bit

**Comment by Bionus** [comment]
I just pushed a fix.

However, note that using the renamer tool for Shimmie sources might not work very well, as single images parsing doesn't return as much information compared to the listing page. That's actually the initial cause  of this bug, as the MD5 was not returned, causing the impossibility to match the original image to the new one.
