### ISSUE TITLE
The score, date and rating tokens do not work when saving a file from a search using gelbooru's fav:XXXXXX

### ISSUE THREAD

**Issue by Korigamesan** [Bionus/imgbrd-grabber#2536]
I tried to save files from a search using the favorite tag on gelbooru (fav:XXXXXX) and the **score, date and rating** tokens don't work. For normal searches it works fine.

Do I need to configure something for them to work?

**Comment by Bionus** [comment]
I just pushed a fix for 4 tokens (score / rating / author / date), but note that the "fav:" query uses Gelbooru's HTML parsing, rather than their XML API, and as such will usually give inferior results.
