### ISSUE TITLE
'Open in browser' opens a wrong link with api.rule34.xxx domain

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2537]
**Bug description**

'Open in browser' opens a wrong link with `api.rule34.xxx` domain instead of just `rule34.xxx`. So it shows an empty page.
![image](https://user-images.githubusercontent.com/4707112/146705224-b145190d-d2bf-438d-9304-4e3d6053250d.png)

**Steps to reproduce**

1. Set source to 'api.rule34.xxx'
2. Perform searching
3. Perform right mouse click on any image
4. Select 'Open in browser'

**Expected behavior**

Browser opens a link with 'rule34.xxx' domain (i.e. https://rule34.xxx/index.php?page=post&s=view&id=5464703 )

**Context**

* `main.log` [main.log](https://github.com/Bionus/imgbrd-grabber/files/7742297/main.log)
*  `settings.ini` [settings.zip](https://github.com/Bionus/imgbrd-grabber/files/7742301/settings.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/146704862-510beea1-3b53-4fb1-a08a-d6c9b8ff52b5.png)

**System information**

- OS: Linux 5.10.84-1-MANJARO
- Grabber version: imgbrd-grabber-git v7.6.2.r128.46db5730-1 (git version from [AUR](https://aur.archlinux.org/packages/imgbrd-grabber-git) )

**Additional context**

It may be connected with this commit https://github.com/Bionus/imgbrd-grabber/commit/f7ce172382079559b457fd8b470af75bf9b97923

**Comment by Bionus** [comment]
Yes it's definitely related to that change. I made a hotfix for now. 👍
