### ISSUE TITLE
Make saving the single Separate Log file per folder to the same directory with other images.

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#2539]
Hi.

I use Separate log for creation **single** file per folder with lines containing %all% and %path% tokens for every image in folder using "Unique" or "Path and filename" Location type.

The issue is that I should change directory in Separate log configs to new directory every time manually for new batch downloading, this is really annoying. 

Is here any option for using %old_directory% or %directory% or whatever in the "path" or "folder" input in the Separate Log config? Or can you add option to store single log file to current download directory? I know i can use save separate log file for every image on the same location with same filename with "suffix" Location type option, but this is not what I want, I search a way to store tags in single file per folder with images.

**Comment by Bionus** [comment]
Hello

> Is here any option for using %old_directory% or %directory% or whatever in the "path" or "folder" input in the Separate Log config?

There is one for the contents of log file (`%path%`) but there isn't currently for the filename itself. I guess it could be added for the filename part as well.

**Comment by uvhat** [comment]
> There is one for the contents of log file (`%path%`) but there isn't currently for the filename itself. I guess it could be added for the filename part as well.

%path% insert full path of file, with filename and extension.

I thought about something like %folder% or %directory% that paste Folder or directory only. Or just option to save single separate log file to current download folder for "Unique file" or "Path and filename" Location types.

**Comment by uvhat** [comment]
<img width="973" alt="log_folder1" src="https://user-images.githubusercontent.com/31294363/147395117-6432e94d-b3a1-41af-8f62-d4d044f49492.png">

As example.
