### ISSUE TITLE
Parentheses don't work if they're not the first expression of a condition and expressions with many operands don't work

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#2540]
I trying to set a simple inline  condition for filename (in the batch download table):

what I want to get:

```
If (   kiss & 2girls |  kiss & 3 girls | yuri ) {
    print("yuri")
}
```

so it is like 
              (A and B) or (A and D) or (E)  
equation

Trying to do same with complex condition:

<("kiss" & "2girls") | ("kiss" & "3girls") | "yuri" ?yuri >%character:underscores% %md5%.%ext%

got

```

---------------------------
Error
---------------------------
An error occurred saving the image.

Please solve the issue before resuming the download.
---------------------------
OK   
---------------------------

```

and  log message:

`[Error] No path could be generated for filename: '<("kiss" & "2girls") | ("kiss" & "3girls") | "yuri" ?yuri >%character:underscores% %md5%.%ext%'`

The only working case after some transformation is:
<("2girls" | "3girls")&"kiss"|"yuri"?yuri >%character:underscores% %md5%.%ext%

this works as suspected, _so i guess here is something brooken when trying to set "(" after "|"_

Then I'm trying to not use parentheses  ( assuming "&" has higher priority above "|" ):
<"kiss" & "2girls" | "kiss" & "3girls" | "yuri" ?yuri >%character:underscores% %md5%.%ext%

works, but wrong: this will save "yuri" for any image with "kiss" tag. So, the second condintion "kiss" & "3girls" ignore "&" and whole equation works like:

A & B | A | D | E
but should be
A & B | A & D | E

So here is 2 issues: something wrong with priority of boolean operations and using "(" after "|" cause an error.

**Comment by uvhat** [comment]
Actually, every () after first | or & cause and error, example:


```
<"kiss" | ("2girls" &"3girls") ? yuri >
<"kiss" & ("2girls" &"3girls") ? yuri >
<"kiss" | ("2girls" |"3girls") | ? yuri >
<"kiss" & ("2girls" |"3girls") ? yuri >
```

`[Error] No path could be generated for filename: '<"kiss" | ("2girls" &"3girls") ? yuri >%character:underscores% %md5%.%ext%'`

```
---------------------------
Error
---------------------------
An error occurred saving the image.

Please solve the issue before resuming the download.
---------------------------
OK   
---------------------------

```

**Comment by Bionus** [comment]
Actually, it seems that parenthesis don't work unless they're at the very beginning of conditions.
Good catch, seems like that's a case I missed when writing the parser and the tests.
I'll push a fix ASAP 👍

**Comment by uvhat** [comment]
Please take a look on boolean opeartion priority too, i mean if use  A & B | C & D | E & F (it works now as A & B | C | D | E | F )

**Comment by Bionus** [comment]
Indeed, there was an issue on that side as well.
I just pushed another fix, now it should properly parse as `((("a" & "b") | ("c" & "d")) | ("e" & "f"))`.

I'm checking other edge cases in the meantime, but feel free to point them out if you find anything as well.
