### ISSUE TITLE
Tag list has tiny text

### ISSUE THREAD

**Issue by slyguy65** [Bionus/imgbrd-grabber#2541]
I ran the program on a 4k display, moved it to 1080, now the tag list is impossible to read. Even a system restart hasn't fixed it.

**Comment by Bionus** [comment]
What version are you on?
Have you tried the [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) release, which contains a recent fix for 4K font sizes?

**Comment by slyguy65** [comment]
> What version are you on? Have you tried the [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) release, which contains a recent fix for 4K font sizes?

I have not, I will give that a shot
