### ISSUE TITLE
Questions about filename when character tags are more than one

### ISSUE THREAD

**Issue by jyf0000** [Bionus/imgbrd-grabber#2542]
I want to name my file with one of these character tags.
![_~}T3MK}$HR%MP$ONYS976J](https://user-images.githubusercontent.com/23413784/147407834-6feaed5d-cf63-4c35-9ace-f4378a0a6d81.png)
Acutally I need is this part:
![`QXBAWT19J E}AT} `151RX](https://user-images.githubusercontent.com/23413784/147407871-cb23cdc4-5624-4c5a-9b1b-f6a978fec02e.png)
Is there any way?

**Comment by Bionus** [comment]
You can set this in the settings:
![image](https://user-images.githubusercontent.com/882719/147409093-56592a38-b749-4f70-a5dc-50511543d01e.png)

Just use "Keep 1" as in the screenshot above.

**Comment by jyf0000** [comment]
> You can set this in the settings: ![image](https://user-images.githubusercontent.com/882719/147409093-56592a38-b749-4f70-a5dc-50511543d01e.png)
> 
> Just use "Keep 1" as in the screenshot above.

Thanks. I'll try. :)
