### ISSUE TITLE
constantly crashes on startup

### ISSUE THREAD

**Issue by kayden1940** [Bionus/imgbrd-grabber#2543]
![us](https://user-images.githubusercontent.com/82050470/147411226-524b6770-6627-43d6-8b96-ff39152a9df2.png)

os: windows 10 x64

**Comment by Bionus** [comment]
How big is your `md5s.txt` file in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`?

**Comment by kayden1940** [comment]
1.03gb

**Comment by kayden1940** [comment]
it's work again after removing it, guess I was too horny I broke the software

**Comment by Bionus** [comment]
You can try deleting it, it should solve your problem.
