### ISSUE TITLE
New Update ? No save button

### ISSUE THREAD

**Issue by Coolz69** [Bionus/imgbrd-grabber#2546]
Cant save , no save buttons .

**Comment by adem4ik** [comment]
![image](https://user-images.githubusercontent.com/4707112/147559307-5317aebe-20dd-4bc2-b19d-9d809a4f4442.png)

**Comment by Bionus** [comment]
Does it solve the issue if you open the settings window and just click "ok"?

**Comment by Bionus** [comment]
Did you update the program or install from scratch?

**Comment by Kuroonehalf** [comment]
I had this happen too. Upon closing the viewer window and opening a new one the buttons are back.

**Comment by Bionus** [comment]
> I had this happen too. Upon closing the viewer window and opening a new one the buttons are back.

Only once then, the first time you started the program after the update? 🤔

**Comment by Kuroonehalf** [comment]
> 

Yeah only the first time. Just tested restarting the program and they show up fine.

**Comment by Coolz69** [comment]
I've tried all of that, all i get now is a small horizontal blue rectangle at the bottom of the picture nothing else.
The little triangle does have an upside-down T on it though ?

**Comment by monmidav2020** [comment]
Update. Bug. Restart. Bug. 
Settings - interface - Dark theme - its alive!
change theme back to default it work

**Comment by Coolz69** [comment]
Once i changed to dark is was there , then i changed back to default and it works now !!
Thanks Guys !!
