### ISSUE TITLE
grabber pixiv

### ISSUE THREAD

**Issue by jpsantos665** [Bionus/imgbrd-grabber#2547]
why is there the option to download pixiv images when this option never works?
not only in imgbrd-grabber but in several other similar programs

**Comment by uvhat** [comment]
try to use pixiv_auth (python util) to extract Access key an Refresh key.

you should insert only access key, leave refresh key empty, filling refresh token will crash grabber.

**Comment by Bionus** [comment]
I'm not sure I understand the question, but as long as you're able to get the auth tokens (either directly in Grabber via  the PKCE OAuth mode or another program), Pixiv should work fine.

**Comment by uvhat** [comment]
> either directly in Grabber via the PKCE OAuth mode 
for some reasons this doesn't work, I have to use another ways to get access keys.
