### ISSUE TITLE
How do i language filter on e-/exhentai?

### ISSUE THREAD

**Issue by TeKett** [Bionus/imgbrd-grabber#2554]
I know i can use the "Language:" filter but it doesnt work well and isnt even a thing unless the work has specifically been translated. You can filter in your account settings and that one works much better since its not related to the tags, but it is not included when searching on the grabber. Is that a cookie thing, if so does someone know which one i should copy?

Oh and is it possible to only save the MD5 in order to reduce dupe downloads? As e-hentai temp bans if it detect you are downloading via third party means.

**Comment by Bionus** [comment]
Have you tried logging in to E-H via the source's settings?
If you have some language filters set in your account, they should apply in Grabber as well as long as you login.

> Oh and is it possible to only save the MD5 in order to reduce dupe downloads? As e-hentai temp bans if it detect you are downloading via third party means.

I don't understand the question. MD5 is already saved/used to avoid downloading duplicates.
