### ISSUE TITLE
Idol Sankaku

### ISSUE THREAD

**Issue by arthuritalo** [Bionus/imgbrd-grabber#2556]
Its possible use the source https://idol.sankakucomplex.com on grabber ?

**Comment by yami-no-tusbas** [comment]
Short answer : No.
Long answer : https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-822632831

**Comment by Bionus** [comment]
Indeed, Sankaku is not supported by default, although some users gave alternatives in the thread linked above.
Closing as there's already enough discussion on it, you can discuss in the other issue if you wish.
