### ISSUE TITLE
Just started today, but when Monitor refreshes gelbooru...

### ISSUE THREAD

**Issue by gummykage** [Bionus/imgbrd-grabber#2557]
Started today, but whenever a monitor starts scanning gelbooru for anything it seems to scan the entire collection of pages.

![image](https://user-images.githubusercontent.com/9695713/147916843-07e65b2f-75b4-41ab-8bd3-2091689064ee.png)

**Comment by DHG-Dav** [comment]
same problem here, and it doesn't download anything, 
![image](https://user-images.githubusercontent.com/95366910/147926189-b8323a59-0d2f-47fe-bb38-52ec8050de98.png)
Danbooru, rule34xxx, tbib doesn't have any issue. Gelbooru API is responding, maybe they changed the format of something ?

**Comment by gummykage** [comment]
Bionus is on it! Closing.
