### ISSUE TITLE
Gelbooru

### ISSUE THREAD

**Issue by arthuritalo** [Bionus/imgbrd-grabber#2559]
![image](https://user-images.githubusercontent.com/11094457/147936877-95e2c5bb-d8b7-444e-9f1b-528a7ab3d64b.png)

**Comment by phantazum** [comment]
Exactly the same thing here. Worked yesterday.

**Comment by theXerun** [comment]
Same problem
Clicking on the hyperlink next to "No result" takes me to a pretty normal looking XML document though.

**Comment by gummykage** [comment]
Actually if you select 1000 images per page, you get this error also:

![image](https://user-images.githubusercontent.com/9695713/147939025-e7eeea02-a9e7-44a0-be95-649aafdb8dd7.png)

**Comment by JohnSmith00000000** [comment]
https://mobile.twitter.com/gelbooru/status/1477788287599325184

**Comment by JohnSmith00000000** [comment]
Looks like gelbooru updated their API 
https://twitter.com/gelbooru/status/1477788287599325184

**Comment by gummykage** [comment]
Thank you Bionus for looking into this /bow

**Comment by PapaBones** [comment]
Updated to the latest version, still experience the issue with no results. Do I need to change something with the sources or something similar?

**Comment by worldemar** [comment]
Still reproducible on 7.7.1 and nightly from 2022-jan-12

**Comment by worldemar** [comment]
Note: to resolve issue a file `~/.config/Bionus/Grabber/sites/Gelbooru (0.2)/model.js` has to be updated. It should happen normally. But in case you have this issue persist, make sure this file is definitely from newer version.

One way to do this is move `~/.config/Bionus` somewhere and allow Grabber to generate configs. Then compare this file to one your config.

**Comment by msanchezdev** [comment]
@worldemar what if I never had a `~/.config/Bionus` folder?
