### ISSUE TITLE
IP temporarily banned.

### ISSUE THREAD

**Issue by Moizevitch** [Bionus/imgbrd-grabber#2563]
Hi! 

Congratulations on the program! 

Two tips: 
1- It would be nice to insert the Tumblr link, as there are many artists who post their work there. 

2- I am sending the images to illustrate the problem. It would be nice if the program used some type of VPN or simply masked the IP, because some problems I saw in the issues section this is probably what is happening. It happened to me! I looked for Devious3D, a wonderful artist and look at the result! 

Well, that's it! 
Thanks!

![bug](https://user-images.githubusercontent.com/80647507/148052923-3175b764-bf77-44f1-a5cd-190e287f33aa.png)
![bugg](https://user-images.githubusercontent.com/80647507/148052959-94a4c8ef-2730-430c-a726-18b73ac75a68.png)
![buggg](https://user-images.githubusercontent.com/80647507/148052993-f40dfba8-73f0-4a7e-9858-0ce2ad8d3e29.png)

**Bug description**

**Steps to reproduce**

**Expected behavior**

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occurred during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

**System information**

- OS: [e.g. Windows 10]
- Grabber version: [e.g. 6.0.3]

**Additional context**

Add any other context about the bug report here.

**Comment by gummykage** [comment]
Put a delay on page loads, and don't download more than 1 pic at a time. Set threads to 1 for that source.

**Comment by Moizevitch** [comment]
Hi @gummykage! 

Thanks for your attention. 

The only thing I did in options was to demarcate the place to save the images and the amount of simultaneous downloads. 

The download went to 10, as 1 was too slow. 

Even with 10, it was slow sometimes, and it has nothing to do with the amount, I noticed that. 

If I go back to 1 simultaneous download, theoretically this problem will no longer occur? 

I'll try it, grateful for the tip.

**Comment by gummykage** [comment]
I used to get banned all the time also, after slowing it down I haven't since. Zerochan is another source I slow the page loads to 5 seconds in between and 1 image at a time (it's slow but at least you can open more instances of grabber). While you are testing use ProtonVPN to keep your own ip from getting banned.
