### ISSUE TITLE
Gelbooru: No result

### ISSUE THREAD

**Issue by TheSonic03** [Bionus/imgbrd-grabber#2564]
Only sources from gelbooru say: "No result". 
This appands afther i update the app directly from grabber. It worked before.
I tried to use my account in the login options from grabber (the test button says: "Seccess!"), but it does't work. I also tried to reinstall the application.

**Comment by yami-no-tusbas** [comment]
see #2559 
A fix is on the way, another fix is on the discord.

**Comment by Bionus** [comment]
As said above, closing as duplicate.
You can temporarily use the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/nightly) or wait for the next release that should arrive soon.
