### ISSUE TITLE
[Bug] [Pixiv] Grabber downloads WEBP images from Pixiv Galleries with JPG ext.

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#2566]
**Bug description**

Pixiv made something wierd with Galleries, and Grabber takes as source an URL to the WEBP versions of images from Galleries, BUT saves it with JPG extension.

WEBP is very nasty format and default or mobile viewers shows WEBPed JPGs too dark or refuse to display images with this format.

**Steps to reproduce**

Try to download anything from gallery with grabber - check that real format is WEBP (open image with notepad and find WEBPVP8 extension notes.

Real original or sample images from pixiv galleries saved through browser have link to original posted extension (jpg, png)

SINGLE images (not from Galleries) are saved normally with usual extension and internal format (jpg) from normal original URL. Issue persist for galleries only.

**Expected behavior**

Grabber should download usual formats from correct links, not from WEBP links. Or convert WEBP to JPG properly. 

**Screenshots**

<img width="1073" alt="webp issue" src="https://user-images.githubusercontent.com/31294363/148349540-5670017b-d578-4ff7-82a1-d0a39a161abf.png">

**System information**

Grabber 7.7.0, 7.6.3 nightly

**Comment by Bionus** [comment]
Should have been fixed by 8e5071156cf2405578bd1cf8917b16c4f8a5337f in 7.7.1
