### ISSUE TITLE
no save options

### ISSUE THREAD

**Issue by sinkiller21st** [Bionus/imgbrd-grabber#2568]
when opening an image to view there is no button to save such as save as or save this image will show what I mean. hope you can help and think you for your time. p.s imagbrd-grabber v7.7
![Capture](https://user-images.githubusercontent.com/39547304/148625119-8afda837-2ea4-469f-87c4-650de7c9d8bd.PNG)

**Comment by gummykage** [comment]
I had this issue, if you go into settings and play with the Interface buttons toggle all of them off and then on it will work again.

![image](https://user-images.githubusercontent.com/9695713/148689006-9f65886e-2acb-4b86-91be-61705613d2b6.png)

**Comment by sinkiller21st** [comment]
think you ill give it a try now :)

**Comment by sinkiller21st** [comment]
think you it worked :) 👍
