### ISSUE TITLE
Tag-Color-Problem with Gelbooru (and Sankaku Complex) in Version 3.4.1, too

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#257]
So I think everyone knows the problem/bug, after opening a few pictures there are no colors for artist, copyright, characters... and when you save the pictures these tags aren't in the filename...

PS: Sankaku Complex has no tag-colors, too

> Original issue reported on code.google.com by `alpha-ji...@live.de` on 24 Aug 2013 at 8:28

**Comment by Bionus** [comment]
See issue #270
