### ISSUE TITLE
[Feature Request] Add Support for Slushe

### ISSUE THREAD

**Issue by flaccidbagel** [Bionus/imgbrd-grabber#2574]
Good evening.

Figured I'd put this out as a feature request. Looking to add support for downloading galleries from Slushe. The site is adult oriented in nature, so fair warning:

[https://slushe.com/](https://slushe.com/)

Looks like it has its API publicly available, so it gives a starting place for something to work with as well:

[https://slushe.com/api](https://slushe.com/api)

**Comment by Bionus** [comment]
Closing as duplicate of #2421
Thanks for the link for the API docs, seems like I missed it last time!
