### ISSUE TITLE
Storing image information in metadata/exif

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#258]
An often asked for feature is a way to store the tags information from downloaded images.

what about Metadata stored inside the file?
most modern images viewers handle such infos, and you can even use them to  search files.

would it be possible for a future version of grabber to use such a feature?
If so, can grabber update the already downloaded images with infos from the different boorus?
does metadata change the MD5 of a file? (I suppose it does)
If Jpg, PNG, and gif support metadata, we are quite safe as for the compatibility issues (and flash files?)

The other possible option, is that grabber would create html booru type of files, for hard drive search.

> Original issue reported on code.google.com by `ser...@hotmail.com` on 25 Aug 2013 at 2:17

**Comment by David-Wells99** [comment]
Requesting this too. I just convert the PNGs to TIFFs and GIFs to MP4s, which support tagging. I don't mind doing that if it means I can tag my files.

**Comment by Bionus** [comment]
Closing in favor of issue #2258 and issue #2081.
