### ISSUE TITLE
Quick question on "images limit" in dl queue 

### ISSUE THREAD

**Issue by Triramama** [Bionus/imgbrd-grabber#2580]
When I send a collection for downloading Grabber checks how many images that collection has and writes it down in the "images limit" tab in the queue, does this number literally limits the download process so it wouldn't go past it no matter what? So if there's, for example, happens to be more images falling under my specified search on the server than what written down in grabber, it means that grabber won't download more pictures when the number of downloaded files meets the number in "images limit"?

**Comment by Bionus** [comment]
Yes, that's right.
You can edit it to "all" in the downloads tab and it will keep going until there's nothing left but it might not work on all sources.
