### ISSUE TITLE
Tag loader is broken in 7.7.1

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2582]
Here is a follow up to #2239 

I tried to use the tag loader on gelbooru to update the database, but it said "loop detected" and stopped after about 20k tags. It looks like on gelbooru.com you can not go beyond the page 20000 or it'll loop back to page 1 even if there is more tags. Maybe it's still good to stop after 20k pages since the tags beyond  this point are under 287 tags. Or maybe there is a way to laod all tags anyways, maybe by the API.

**Comment by Bionus** [comment]
I'm not sure I understand the issue. After finding a loop (i.e. after some page Gelbooru loops back to page 1), the loading stops. It's expected and there's no way around it, so I'm not sure what's the issue exactly 😅

**Comment by yami-no-tusbas** [comment]
well put it simple, the issue is that using the loader bundled with the app, doesn't work with gelbooru using lastest release, it detect a loop and stop before the end.
