### ISSUE TITLE
add ratios support to wallhaven search

### ISSUE THREAD

**Issue by xEyad** [Bionus/imgbrd-grabber#2586]
**Is your feature request related to a problem? Please describe**
Currently i'm not interested in any images with non-landscape resolution. so i need a way to filter other ratios out

**Describe the solution you'd like**
implement this part of the api where you can add ratios to the query params. in the grabber interface either let me write this directly in the search field next to tags (example: ratios=16x9,1x9) or simply give me an option even in post filters and i will adapt. also, whatever the implementation i need to be able to save it in monitor data

**Describe alternatives you've considered**
i have tried to use order:landscape but it didn't do anything.. i thought about just ignoring last few pages that doesn't follow that option but it didn't work

**Additional context**
api docs link: https://wallhaven.cc/help/api
example search with ratios: https://wallhaven.cc/search?categories=001&purity=010&ratios=16x9,1x9&topRange=1M&sorting=toplist&order=desc

**Comment by xEyad** [comment]
hello, i'm glad that this feature is finished. may i ask how to use it?

**Comment by Bionus** [comment]
Hello, you can just use `ratio:4:3` as on other sources (with either `:` or `x`).
For multiple ratios, you can put ratio multiple times (`ratio:3x4 ratio:4:3`) or use a comma (`ratio:3x4,4:3`).
