### ISSUE TITLE
question: can I prioritize a site over another in "merge results"?

### ISSUE THREAD

**Issue by bahari15** [Bionus/imgbrd-grabber#2587]
Basically I use both danbooru and sankakucomplex while browsing boorus, but grabber always prioritize danbooru in merge results over sankaku, how do I reverse that and make it prioritize the latter in merge search results?

**Comment by Bionus** [comment]
Hello

There's currently no way to prioritize merged results.
The current logic is to prioritize the one whose image's tags are better typed, i.e. has the highest percentage of known tags.

**Comment by bahari15** [comment]
> Hello
> 
> There's currently no way to prioritize merged results. The current logic is to prioritize the one whose image's tags are better typed, i.e. has the highest percentage of known tags.

In what part of the settings is it?
