### ISSUE TITLE
 Gelbooru stops at 25,000 images

### ISSUE THREAD

**Issue by Kelhsy** [Bionus/imgbrd-grabber#2588]
I'm trying to download a tag that has around 200,000 images but the program just "finishes" when it downloads 25,000 images. I never had this problem before but now I did a fresh install on a new system after not using the program for a year.

**Comment by junofall** [comment]
For me that limit seems to be 21,000 for a given tag. I've tried to manually force it to continue by specifying the download at page 22 with 1000 images per page but it returns finished even though there's around 180K remaining.

**Comment by sstabeler** [comment]
That's a Gelbooru thing, not a Grabber thing. Essentially, Gelbooru has a cap on how deep you can actually go inot a search's results, which corresponds to 25k images. There are workarounds if you check the Gelbooru forum.

**Comment by maslos** [comment]
Hello, does this workaround works on your own gelbooru favorites? I can go to the first page no problem but Grabber downloads only around 20k photos.
