### ISSUE TITLE
Incorrect width of images from rule34.paheal.net

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2590]
**Bug description**

Grabber shows incorrect width of images from rule34.paheal.net inside popup and preview during loading

**Steps to reproduce**

1. Select rule34.paheal.net as a source
2. Search for any image
3. Hover the mouse cursor on the result
4. Open preview

**Expected behavior**

Correct width (i.e. for my screens it should be 563x496 http://rule34.paheal.net/post/view/4829644 )

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/151663310-ff1df663-5eef-49f9-8b05-934a7289ae6d.png)
![image](https://user-images.githubusercontent.com/4707112/151663341-bd806822-65ef-4ad2-bbfc-ea71d67cbf3e.png)

**System information**

- OS: Windows 10 x64 / Manjaro Linux
- Grabber version: 7.7.1

**Comment by Bionus** [comment]
I could reproduce and just pushed a fix.
However, when testing I only saw very thin image in the image window during loading? It was showing at the proper size after finished loading.
