### ISSUE TITLE
Danbooru: How to download parent only posts?

### ISSUE THREAD

**Issue by YukiSakuma** [Bionus/imgbrd-grabber#2592]
I don't want duplicates/variations. I want to download parent posts only.
I could do this in the search but I am already searching multiple tags and I am only a free user. Any other ways?

**Comment by Bionus** [comment]
I guess it's Danbooru? In that case, you can just use `parent:none` according to [their cheatsheet](https://danbooru.donmai.us/wiki_pages/help:cheatsheet).

For a Grabber-specific answer, parent IDs are stored in the `%parentid%` token, so you can use `-%parentid%` **as a post-filter** (note that there's an issue with the `%parentid%`  token currently, solved by 03a8d2c7f3b96613d5657cf5081d93000198f9ad in [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly)).
