### ISSUE TITLE
Api.Rule34.xxx appears to be broken

### ISSUE THREAD

**Issue by temptemp033** [Bionus/imgbrd-grabber#2596]
Seems api.rule34.xxx is broken. Could possibly be because of new captcha upon loading site?

**Comment by Bionus** [comment]
I can't reproduce currently, was it temporary?

Do you have any log of when this happens? If there's a "Cloudflare wall" error message, there's nothing that can really be done as it means Cloudflare's blocking you.
You can try logging into the website via Grabber's source settings, but it's not guaranteed to work.

**Comment by brazenvoid** [comment]
Yes it is cloudflare blocking access.
