### ISSUE TITLE
Possibility to copy tag by Ctrl+C in the preview dialog

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2601]
**Is your feature request related to a problem? Please describe**

Currently there is the only way to copy tag in the preview dialog — it is by using right mouse click menu.

**Describe the solution you'd like**

It would be useful to be able to copy a tag by selecting it and by pressing Ctrl+C shortcut.

**Describe alternatives you've considered**

None.

**Additional context**

![image](https://user-images.githubusercontent.com/4707112/153385354-5715b01f-b541-495f-9014-ec234adba1ed.png)

**Comment by Bionus** [comment]
That's likely because you have the shortcut for "Copy image data" bound to "Ctrl+C" and it prevents you from copying text. I just updated the default shortcut to use "Ctrl+Shift+C" instead, but you might want to change it in your settings 👍
