### ISSUE TITLE
If-then statements/Customs Tokens within Custom Tokens

### ISSUE THREAD

**Issue by Crimson666999** [Bionus/imgbrd-grabber#2604]
Is it possible to place if-then statements within a custom tokens as creating multiple tokens for specific if-then replacements can get rather long and confusing when it comes to listing out the filename  for example if I want to specifically list ranged weapons within a filename among tons of other if-then statements, but I also want to have all these tags under one token as well so that they are automatically sorted in either alphabetical order, or order of appearance.

Though some site use <3, for situations in which a heart is present in the image and other commonly used characters such as >_<. That the program uses for the if-then statement, so why not use rarely used alt code characters (ex. altcodeunicode.com/ ) to represent an if-then statement within a custom token as a possible solution, I tend to use the characters associated with mathematics as dividers for multiple tags within my filenames.

**Comment by Bionus** [comment]
I'm not sure I understand your question.

If you want to use a custom token for ranged weapons, you can just create one in the custom tokens settings then fill it with all the ranged weapons you can think about, and give it a name like `ranged_weapons`. Then, you can use it in your conditionals with something like `<%ranged_weapons%?something>` (or even just directly `%ranged_weapons%` without conditionals).

Can you give an example of what you're trying to achieve/simplify?

**Comment by Bionus** [comment]
In that case no, that's not possible. Custom tokens can only contain a list of tags, and will only contain the subset of those tags that were found in the image. They can be used in conditions, but they can't _contain_ a condition.
