### ISSUE TITLE
Broken links on bionus.github.io/imgbrd-grabber/

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2605]
**Bug description**

There are some broken links at [bionus.github.io/imgbrd-grabber/](https://bionus.github.io/imgbrd-grabber/) inside Customize & Organize sections.

**Steps to reproduce**

1. Open https://bionus.github.io/imgbrd-grabber/
2. Go to Customize or Organize sections
3. Click on [Themes](https://github.com/Bionus/imgbrd-grabber/wiki/Themes), [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename), [Shimmie](https://github.com/Bionus/imgbrd-grabber/wiki/Shimmie), [Gelbooru](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru), [MyImouto](https://github.com/Bionus/imgbrd-grabber/wiki/MyImouto), [Commands](https://github.com/Bionus/imgbrd-grabber/wiki/Commands) links

**Expected behavior**

I guess it should be some links from https://bionus.github.io/imgbrd-grabber/docs/ , i.e. https://bionus.github.io/imgbrd-grabber/docs/plugins/theme.html for Themes

**Context**
NA

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/154913527-edb9093f-50e1-4aca-88ea-e5ae936c494e.png)

**System information**

NA

**Additional context**

NA

**Comment by Bionus** [comment]
Wow, thanks for catching that. This must have been broken for a very long time given the wiki was disabled years ago 😱
