### ISSUE TITLE
download from list of md5's / console commands

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#261]
I was thinking about redownloading all my images with grabber, so they are more manageable and searchable.
I've got a whole bunch of pics and it would be a pain to copy the md5-hash(filename is the md5 usually) manually each time into the search box.

It would be handy if you could pass a list of md5's and it would batch-download them all.
(Getting the list is not the issue here, I'm making a script to parse them from my image folders)

Another idea that would work out the same is for there to be a console command to download with grabber. That way I could just use a script to loop over my md5-list and pass it into the command.

running v3.4.1 on Win7

> Original issue reported on code.google.com by `nrillae...@gmail.com` on 1 Oct 2013 at 11:24

**Comment by Bionus** [comment]
Console commands exist for a while now, feel free to use them. They are documented on the [ConsoleUsage](https://github.com/Bionus/imgbrd-grabber/wiki/ConsoleUsage) wiki page.

As for automatically re-download images, see issue #344.
