### ISSUE TITLE
Pixiv animated pictures (Videos, Gif, etc) becomes Image File

### ISSUE THREAD

**Issue by Kukuru97** [Bionus/imgbrd-grabber#2610]
https://user-images.githubusercontent.com/100615360/156036921-be090c99-d30c-4b26-9946-8223c1da5c79.mp4

in browser Video/Gif works, but in Grabber Video/Gif becomes Image File (JPG/JPEG/PNG) 

Grabber ver 7.7.1
Windows 10 21H2

**Comment by GlassedSilver** [comment]
Pixiv animations (usually?) are so-called ugoira. [[explanation]](https://danbooru.donmai.us/posts?tags=ugoira)

tl;dr: custom format, it's not a video nor a gif. If Grabber were able to get proper support for this, especially if transferring from say Pixiv or official Danbooru to a personal Danbooru instance, that'd be super awesome!

For portability and simple uses a download of the Pixiv-provided converted version should/could be offered as well in my humble opinion. :)

**Comment by Bionus** [comment]
AFAIK they already download properly as ZIP and show as MP4 in the preview.
Although for Pixiv it's a little bit more complicated since they don't provide the metadata in the details page.

**Comment by uvhat** [comment]
> AFAIK ugoira already download properly as ZIP and show as MP4 in the preview for Danbooru. Although for Pixiv it's a little bit more complicated since they don't provide the metadata in the details page.

Here is pretty simple solution :

usual image url looks like:
https://i.pximg.net/img-original/img/2020/10/30/22/04/35/85334976_ugoira0.jpg

ugoira zip url:
https://i.pximg.net/img-zip-ugoira/img/2020/10/30/22/04/35/85334976_ugoira1920x1080.zip  or 600x600 for preview 

So, here is very simple and dummy but working solution for downloading ugoira zip from pixiv:

in model.js add this lines after `var img = parseImage(data, false);` in the end of `details: {` block:

```
 if(/ugoira0/.test(img.file_url)){
    var zip_file_url = img.file_url;
    zip_file_url = zip_file_url.replace("img-original", "img-zip-ugoira");
    zip_file_url = zip_file_url.replace("ugoira0.jpg", "ugoira1920x1080.zip");
    zip_file_url = zip_file_url.replace("ugoira0.jpeg", "ugoira1920x1080.zip");
    zip_file_url = zip_file_url.replace("ugoira0.png", "ugoira1920x1080.zip");
    zip_file_url = zip_file_url.replace("ugoira0.webp", "ugoira1920x1080.zip");
    img.file_url = zip_file_url;                      
 }
```

zip is basic 0001 0002 0003 etc frames, so it is possible to convert to gif using full color methodics (slice to 16x16...32x32 64x64 blocks per one 256-color pallete and merge to one full/true color gif file) or mp4/webm using ffmpeg.

**Comment by GlassedSilver** [comment]
you could also inspect danbooru's scraper code logic to see how danbooru handles it.

Keep in mind though for any conversions that they should be optional imho and that generation has to take into account that ugoira's have per-frame timing. gifs don't have that iirc, but proper video containers do support VFR of course.

**Comment by Bionus** [comment]
Thanks a lot for that @uvhat, I didn't know Pixiv provided already-made ZIP files.

I just updated the source code to download the ZIP properly and show the first frame as preview on Pixiv. The unfortunate part is that those ZIP don't contain the metadata so can't really be converted "as-is".

As for converting to video (via `ffmpeg` for example), that's another beast that I believe is kinda out of scope of this specific issue. I think I remember someone opening an issue for that already but I couldn't find it just now.
