### ISSUE TITLE
paheal keeps popping up with an error when i try to download anything

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#2611]
![image](https://user-images.githubusercontent.com/88627878/156048244-12e72f68-8211-46f8-9c05-a96628805bd2.png)
![image](https://user-images.githubusercontent.com/88627878/156048304-3ff2a11e-a5b8-4543-8750-ed977ad80cb1.png)
only happens on paheal, rule34.xxx works fine but paheal doesnt

**Comment by Bionus** [comment]
Hello, is there any log accompanying the error in the log tab? (or in the `main.log` file)
