### ISSUE TITLE
Conditional Filenames Don't Work Consistently

### ISSUE THREAD

**Issue by flaccidbagel** [Bionus/imgbrd-grabber#2612]
**Bug description**

Some tags simply don't seem to function properly when using conditional filenames. It doesn't seem to affect all of my tags, but many are affected, there are times where new folders are created despite having existing files, from a previous download, in the proper folder.

**Steps to reproduce**

Warning, tag is obviously going to get porn (rule34.xxx).

Insert conditional save location for liza_(artist) to save to folder E:\Artists\Liza\R34Booru:
[Filenames]
0_cond=liza_(artist)
0_fn="%date:format=yyyy-MM-dd.hh-mm-ss%-%md5%.%ext%"
0_dir=E:\\Artists\\Liza\\R34 Booru

**Expected behavior**

All images found when searching via tag "liza_(artist)" on R34.xxx saves to E:\Artists\Liza\R34 Booru.

**Context**

I removed the settings file and completely recreated the entry to see if that had any effect, with no change. Settings file extension changed to .txt for uploading purpose only.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/8190048/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/8190049/settings.txt)

**Screenshots**

When attempting to open the download directory for a new image, this displays:

![Grabber_dc2y4tlB3V](https://user-images.githubusercontent.com/34853221/156869469-dda13eb5-2950-4e00-9a0f-2662d74ea4b1.png)

Once created and saved, opening that folder instead shows it was saved as "liza_(artist)" rather than under the "Liza" folder.

![explorer_yuZhsrEBy4](https://user-images.githubusercontent.com/34853221/156869601-7eb593b9-0ed9-4fe5-b1d8-645051fa61f9.png)

As displayed, that is the search tag, rather than the conditional filename created for it:

![Grabber_cRaxnRTZh3](https://user-images.githubusercontent.com/34853221/156869630-337e1314-e532-4355-9913-d120fb5f63a4.png)

**System information**

Windows 10
Grabber 7.7.1

**Additional context**
As stated, this seems to affect many tags. I've also seen strange behavior for a couple of tags I have favorited with "-manual", to remind myself to manually search through them and download individual images. For example, if "-manual Cat" was favorited, I'd have a conditional filename with the same tag set to save the file to "E:\Artists\Cat\R34 Booru". This was used just so I could quickly keep track of which artists I wanted to scrape, versus which ones I wanted to manually go through and save individually. While this seemed to work previously, I now have MANY files saving to these folders despite having actually matching conditional filenames (in fact, every single artist I have favorited has a conditional filename to save to a folder with their name, sometimes with an additional alias in parentheses as well).

**Comment by Bionus** [comment]
Indeed, that would be because the `_(artist)` suffix is getting stripped on those tags, and because rule34.xxx does not have proper tag types. I guess this issue only occurs on artist tags, and not other tags?

I just pushed a fix for that 👍

**Comment by flaccidbagel** [comment]
Good evening. Not to Necropost, but I finally came back to this, and just updated to 7.8.0. Right now, I'm getting the same exact behavior as before, where attempting to save images with _(artist) appended ignores the conditional file path.

One thing of note is that the tag in question in the example "liza_(artist)" is categorized as an artist tag on rule34.xxx as well. Not sure if that helps or not. I do appreciate you taking a look at it.

**Comment by Bionus** [comment]
Yes, I guess I fixed something but there was actually another thing.

From what I can see, the `lisa_(artist)` is being parsed as `lisa_ OPEN_PARENTHESIS artist CLOSE_PARENTHESIS` rather than one big tag. Which doesn't really make sense in this context.

To prevent this until I make the parser a little bit smarter, you can use quotes around the tag, like `"lisa_(artist)"`. I guess escaping the parenthesis might work as well but that's ugly, like `lisa_^(artist^)`.

**Comment by flaccidbagel** [comment]
Ah, gotcha. That being said, for some reason I never thought to use quotes around the tag term. I'll give that a spin next time I boot this up, as that'd definitely be a valid workaround for me as well.

**Comment by Bionus** [comment]
Just pushed a fix. I also updated the docs to advice using double quotes when using tags with special characters, as otherwise it can cause issues 👍

**Comment by flaccidbagel** [comment]
Awesome. Thanks again.

Just tested it with quotes and that took care of it as well. Think this can be closed out.
