### ISSUE TITLE
:length= dosen't pad out %score%

### ISSUE THREAD

**Issue by Rithmere** [Bionus/imgbrd-grabber#2616]
**Bug description**

Adding %score:length=5% to the file path results in default %score% behavior

**Steps to reproduce**

1. Search any image from sources that have scores
2. Enter %score:length=5% %md5%.%ext% into the name box under destination
3. Press save below
4. download an image by either method
5. Note the image has no leading zeros

**Expected behavior**
Expected: 00025 00003 00340
I'm getting: 25 3 340

I wanted to sort the files by score in the OS file browser but I need padding for that to work properly. it works with other numbered tokens like %count% and %id%

**Context**

I changed settings to .txt to upload
[main.log](https://github.com/Bionus/imgbrd-grabber/files/8238688/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/8238689/settings.txt)

**System information**

- OS: [e.g. Windows 10]
- Grabber version: [e.g. 7.71]

If I'm missing something or if anyone has a workaround I'd love to hear it.

**Comment by Bionus** [comment]
Indeed, that's due to it being stored as a string, not an integer, because some sources have score as a decimal (1.5 etc) instead of a round number. I just pushed a fix to handle this appropriately.

**Comment by Rithmere** [comment]
It works perfectly now thanks a ton!
