### ISSUE TITLE
lolibooru.moe tags/description disappear 

### ISSUE THREAD

**Issue by Kukuru97** [Bionus/imgbrd-grabber#2620]
when the image is opened, the description/tag appears, but when the image is loaded, the description/tag disappears and displays only the "+" description/tag. 
![Screenshot 2022-03-18 150143](https://user-images.githubusercontent.com/100615360/158964795-7e5bafbf-cfab-4a7f-bc4d-de144fa56265.png)
Screenshot image is opened

![Screenshot 2022-03-18 150157](https://user-images.githubusercontent.com/100615360/158964904-8873ef35-36aa-4281-8399-c3a1e6d43948.png)
Screensho image is loaded

OS : Windows 10 20H2
Grabber ver : 7.7.1
Sites problem : lolibooru.moe
Main log file : [main.log](https://github.com/Bionus/imgbrd-grabber/files/8302870/main.log)

**Comment by Bionus** [comment]
Hello, it seem to be cause by this board being detected as a Danbooru board while it's a Moebooru board.
You should delete it from your "Sources" window then add it again by selecting "Moebooru" manually in the list.
