### ISSUE TITLE
Pixiv not downloading all images

### ISSUE THREAD

**Issue by Kazserah** [Bionus/imgbrd-grabber#2621]
I can login just fine and view all the images from the creator, but when actually downloading, it only grabs 60-something instead of 200+ images that's actually there.. happens every time. Tested "get all" vs getting each page on their own. Nothing seems to work

**Comment by uvhat** [comment]
Maybe it is linked with https://github.com/Bionus/imgbrd-grabber/issues/2567 Check what images are not loading - "illusts" or "manga". If not loaded images are "manga" type you can try to update grabber and model.js for pixiv.

**Comment by Bionus** [comment]
Do you have an example of such a creator where Grabber doesn't find every file?
And as uvhat said, make sure to use 7.7.1 or higher since there was a Pixiv fix in there.

**Comment by Kazserah** [comment]
After a clean 7.8.0 install it seems to work fine now
