### ISSUE TITLE
Javascript filenaming: gallery.name and gallery.id tokens don't work

### ISSUE THREAD

**Issue by uvhat** [Bionus/imgbrd-grabber#2623]
The gallery.name and gallery.id tags are not working when using javascript filenaming.

Grabber returns "Error in Javascript evaluation:<br/>ReferenceError: gallery is not defined"

Is there any way to get gallery id and name?

**Comment by Bionus** [comment]
Does it work with `%gallery.id%` and `%gallery.name%`?

I just tried on E-H on Nightly and my test filename was working fine:
```js
javascript:gallery.id + ' - ' + gallery.name + ' - ' + md5 + '.' + ext
```
What source are you using?

Note that `gallery` is indeed undefined when not downloading a gallery image, so you'll need some conditionals here if you want to use this filename everywhere, for example something like:

```js
javascript:(gallery ? gallery.id + ' - ' + gallery.name + ' - ' : '') + md5 + '.' + ext
```

I indeed noticed a bug when validating the filename in the "..." filename window in the settings, saying:
> You script contains error, are you sure you want to save it?

But it worked anyway.

**Comment by uvhat** [comment]
i'm trying it on pixiv.

"javascript:gallery.id + ' - ' + gallery.name + ' - ' + md5 + '.' + ext " is working on N-H and E-H.

and %gallery.id% and %gallery.name% don't work now on pixiv

i used %gallery.id%_%gallery.name%\%all:underscores,maxlength=50% %filename% %md5%.%ext% and similar filenames earlier for getting id and name and this worked.

But anyway, just ID and NAME works, maybe it changed and i did't notice this... I think the issue could be closed...

**Comment by uvhat** [comment]
`so you'll need some conditionals`

Oh. is seee...

%gallery.id%_%gallery.name%%all:underscores,maxlength=50% %filename% %md5%.%ext%

actually works because %gallery.id% and %gallery.name% was undefined but returns empty chars, so it worked and creates new folders for galleries on Pixiv. 

In JS i relly need to check is gallery is actual gallery before. Thanks, i understand these all...

**Comment by uvhat** [comment]
hm, actually, i got same error:

**Comment by uvhat** [comment]
well, it works for pixiv as:
'javascript: ( typeof gallery == "undefined" ? "single" : "gallery" ) + " " + md5 + '.' + ext '

**Comment by Bionus** [comment]
Anything with `gallery.XXX` won't work if it's undefined. You have to use `typeof !== undefined ? ...` (or maybe  `gallery ? ...`). Not sure if `gallery !== undefined ? ...` would work but I guess not.

**Comment by uvhat** [comment]
Thanks, i got it. 
`typeof gallery == "undefined" ?` is working, simple `gallery ?` is not, it could be closed.
