### ISSUE TITLE
7.8.0 install hanging

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#2625]
**Bug description**

7.8.0 install hangs while extracting themes\QDarkStyleSheet\img\checkbox_checked_disabled.png

Also I had to end task it at that point and it shows I have 7.8.0 now but I'm not sure what files should've been installed after that which now aren't.

**System information**

- OS: Windows 10 Pro
- Grabber version: 7.8.0 (pending)

**Comment by Bionus** [comment]
Strange, I can't reproduce this at all. Is the file already existing and read-only or something similar?
In any case, the themes are at the very end of the installation so you shouldn't have missed anything during the install.

**Comment by Bionus** [comment]
The `themes` directory is here and not in the install directory for what it's worth:
```
C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\themes
```

**Comment by Bionus** [comment]
I believe you can start InnoSetup with the `/LOG` parameter to see what's up:
https://jrsoftware.org/ishelp/topic_setupcmdline.htm#LOG

Does it say anything? Where are you trying to install Grabber? Because as you said, it might not respect long paths.
