### ISSUE TITLE
Could not open file [path] for writing: Error 5

### ISSUE THREAD

**Issue by TheKoakuma** [Bionus/imgbrd-grabber#2634]
**Bug description**

Continuation of issue #2523, but now error spits out on log

After adding the new source to Grabber the error is shown on log (prints attached) and the new source doesnt persists after closing the app

**Steps to reproduce**
- Go to Source
- Click on add
- Add the custom source
- Go back to main screen
- Search something to see that it works
- Close Grabber (doesn't matter if closes on back button then exit or if closes opening the recent apps then throw to side)
- **Check log  (Menu>Log) for the error**
- Reopen Grabber
- Go to sources
- See that the custom source just vanished
- If you try searching something without selecting a new source, the app crashes

*Expected behavior**

The new source should persist after closing the app

**Screenshots**

Please refer to issue #2523, as the steps on video (except checking logs) are exactly the same

![Screenshot_2022-03-30-23-28-03-932_com.bionus.grabber.jpg](https://user-images.githubusercontent.com/24434339/160965237-6d6a0fc4-4b63-404a-bcf5-973839809bf8.jpg)
![Screenshot_2022-03-30-23-28-12-519_com.bionus.grabber.jpg](https://user-images.githubusercontent.com/24434339/160965257-8ddcd4e1-26a7-4bed-b78b-21c9ce9dfaf3.jpg)

**System information**

- Device: Xiaomi Redmi Note 10 5G
- OS: Android 11 MIUI 12.5.4.0
- Grabber version: 7.8.0
- No root, No custom rom, No unlocked bootloader

**Comment by Bionus** [comment]
Strange, it's failing to write a file to the application's private directory.
Did you install the application on an SD card or something?

Can you try the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/nightly) and tell me if there's any more information in the logs? (I just added a little bit more details to the error)

Did you give write permissions to the app? (although it shouldn't need them for this folder and should ask them on startup)
You can maybe also try to uninstall the app/clear the data completely before re-installing it, maybe that could help.

**Comment by TheKoakuma** [comment]
Apparently worked after a full uninstall and reinstall
