### ISSUE TITLE
[Android] Perform search on pressing Enter inside search field

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2637]
**Is your feature request related to a problem? Please describe**

Currently if you press Enter on Android keyboard it will perform new line action. This is quite useless for a search field.

**Describe the solution you'd like**

It would be more usefull to start searching on pressing Enter (same logic as on PC version of Grabber)

**Describe alternatives you've considered**

N/A

**Additional context**

![image](https://user-images.githubusercontent.com/4707112/161122847-fcdd8cba-71a7-480c-a172-445757dcc64b.png)

**Comment by Bionus** [comment]
Which keyboard are you using?
I tried on Swiftkey and couldn't reproduce, the enter key was properly triggering the search 🤔 

And it should indeed be handled after checking the code, although a bug can't be ruled out:
https://github.com/Bionus/imgbrd-grabber/blob/eb7c8ca2eeaf1815076e5131437e4af47ddede8a/src/gui-qml/src/components/SearchEdit.qml#L15-L24

**Comment by adem4ik** [comment]
Ah, sorry. You're right. It was Emoji Keyboard. There is no such problem in Gboard/Swiftkey/Yandex keyboards.
