### ISSUE TITLE
Crashes whenever I click on an image

### ISSUE THREAD

**Issue by vylette89** [Bionus/imgbrd-grabber#2639]
Every time I click on an image the program crashes.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/8399446/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/8399455/settings.txt)

**Comment by Bionus** [comment]
Does disabling the "built-in video player" in the settings solve this issue?
You might have an incompatible video player DLL somewhere in your path that Grabber tries to load for some reason.

**Comment by Ironnhawk** [comment]
I am also getting this error, Ill see if I can find logs. Im running on Windows 11
