### ISSUE TITLE
Tagger Error

### ISSUE THREAD

**Issue by ItJustFox** [Bionus/imgbrd-grabber#2640]
**Bug description**

If an image has in title any word.s in japanase (or Kanji / 焰 \) the tagger (Exif tools) will not be able to put the tag.s on the image

**Steps to reproduce**

1. Open Grabber 
2. Go to tools > Option > Save > FileName
3. set Default to `%websitename% %id% %filename% by%author%.%ext%`
4. DL any image with a japanese author name from **_PIXIV_**
5. See the Tag.s not here :>

**Expected behavior**

Our image with the tags ?

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occurred during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

`[22:38:38.321][Error] [Exiftool] FileName encoding not specified. Use "-charset FileName=CHARSET" No matching files`

**Screenshots**

^

**System information**

- OS: Windows 10 / 11
- Grabber version: Latest

**Additional context**

I like you, plz help me

**Comment by Bionus** [comment]
This is an exiftool error, what are your exiftool settings?
There must be something up there, because while there's an issue with UTF-8 encoding in exiftool tags (issue #2647), that should turn them into "?", not an explicit error.

**Comment by Railline** [comment]
> This is an exiftool error, what are your exiftool settings? There must be something up there, because while there's an issue with UTF-8 encoding in exiftool tags (issue #2647), that should turn them into "?", not an explicit error.

i have the same problem, maybe you can force exif to put tags before the rename of the file ?

**Comment by Bionus** [comment]
@Railline What problem do you mean, the one in the original post? "FileName encoding not specified"? What's your exiftool/filename settings? I've never seen this, could it be that your filename itself contains UTF-8 characters or something?

**Comment by Railline** [comment]
> @Railline What problem do you mean, the one in the original post? "FileName encoding not specified"? What's your exiftool/filename settings? I've never seen this, could it be that your filename itself contains UTF-8 characters or something?

on my rename sentence i use %author% i download on pixiv, some user have a japanese character in there name, and when i download they file, grabber rename they, and exif try to put tag in metadata but exif can't find the file because japanese character are not in UTF-8
