### ISSUE TITLE
Change behavior of "Copy Link" action so it puts HTML-Encoded Link into Clipboard

### ISSUE THREAD

**Issue by HayateLaTech** [Bionus/imgbrd-grabber#2643]
Issue is that if someone wants to copy the URL of a site that uses spaces in their URLs, they'll end up with a butchered link in their clipboard, making it unnecessarily difficult to paste it in applications like Discord.
(basically, all spaces must be manually replaced with %20 etc.)

My Idea would be to change this line:
https://github.com/Bionus/imgbrd-grabber/blob/eb7c8ca2eeaf1815076e5131437e4af47ddede8a/src/gui/src/viewer/viewer-window.cpp#L482

so that the Link that'll be put into the clipboard will be html-encoded so spaces will be turned into %20 and so on.

The function that can encode URLs in QT would probably be
https://doc.qt.io/archives/qt-4.8/qurl.html#QUrl-2

Thanks! ❤️

**Comment by Bionus** [comment]
Indeed, that makes sense to return a proper compliant URL when using this context menu action 👍
