### ISSUE TITLE
Separate log files are not produced when using the image renaming tool

### ISSUE THREAD

**Issue by GreenZanbato** [Bionus/imgbrd-grabber#2646]
I was told on the discord that this should be considered a bug.
Normally when separate log files are set up in the options, downloading an image will create an adjacent text file with the same name (and whatever you told it to log). When using the image renamer tool along with that option it will rename those log files, but it will not generate new ones for images that do not have them yet.

Thanks for all your work on this program, hopefully this is an easy fix.

**Comment by NEO-SPECTRUMAN** [comment]
also there is need ofline renaming
using this separated txt file
in same time is necessary to rename this txt file too
