### ISSUE TITLE
When saving the %source:unsafe% tag to a local danbooru instance it should not convert underscores in the filename to spaces.

### ISSUE THREAD

**Issue by GlassedSilver** [Bionus/imgbrd-grabber#2652]
**Bug description**

Basically refer to our chat we just had on Discord :) (or see title :P)

**Steps to reproduce**

1. Go to Options
2. Click on Commands
3. Enter the string to use a local danbooru instance to send posts to, make sure to use the %source:unsafe% tag
4. Hit okay and save an image. In the log you will see that the source will be passed with underscores converted to spaces.

**Expected behavior**

Unsafe to not alter anything in any direction. :)

**Context**

we had a chat about this :)

**Screenshots**

**System information**

- OS: Windows 10
- Grabber version: 7.8.0 (x64, latest nightly)

**Additional context**

n/a

**Comment by Bionus** [comment]
I added a new `raw` option that does not touch the value at all. So you should use `%source:raw%` instead 👍 
I also updated the docs to match.
