### ISSUE TITLE
Open new browser window with the page if you just posted to a personal booru by saving

### ISSUE THREAD

**Issue by GlassedSilver** [Bionus/imgbrd-grabber#2656]
**Is your feature request related to a problem? Please describe**

Not really a problem, but I like to make sure an asset got submitted to my configured personal Danbooru instance after saving.

Also, to make some manual edits to the post if needed. Saves clicks and is a good visual aid it actually passed! :)

**Describe the solution you'd like**

See title

**Describe alternatives you've considered**

More agony, more pain, more clicks. /s :P

**Additional context**

n/a

**Comment by Bionus** [comment]
I updated the [danbooru.js](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/develop/docs/_docs/commands/danbooru.js) file, you can use this one which should support this feature.
Make sure to read the new docs as well that explains how to enable it and install the necessary dependency: [danbooru.md](https://github.com/Bionus/imgbrd-grabber/blob/develop/docs/_docs/commands/danbooru.md#open-new-images-in-browser).
