### ISSUE TITLE
Grabber 7.8.0 do not open

### ISSUE THREAD

**Issue by lucas-04** [Bionus/imgbrd-grabber#2659]
./Grabber: error while loading shared libraries: libQt5MultimediaWidgets.so.5: cannot open shared object file: No such file or directory

that's all i know '-'

**Comment by Bionus** [comment]
Is it using the AppImage file? I just checked and it  should contain `libQt5MultimediaWidgets.so.5`.
If it's the `tar.gz` version, you're expected to install the lib dependencies by yourself. On Ubuntu/Debian, AFAIK that's the `libqt5multimediawidgets5` package, or ` libqt5gui5`.

**Comment by lucas-04** [comment]
the two formats. The AppImage just nothing happens when clicked and the .tar.gz this error happens

**Comment by lucas-04** [comment]
https://user-images.githubusercontent.com/95548091/163389488-f1586c7d-ecfd-41bc-bce9-0a12ff74f95d.mp4

**Comment by Bionus** [comment]
Strange. Does it have the executable bit?
If you start it from the console, do you see any log in there maybe? 🤔

**Comment by lucas-04** [comment]
> Strange. Does it have the executable bit? If you start it from the console, do you see any log in there maybe? thinking

![image](https://user-images.githubusercontent.com/95548091/163391109-8b61151e-3ec3-4232-8b5a-360c529c0989.png)
This?

**Comment by Bionus** [comment]
I mean the `chmod +x Grabber_v7.8.0-x86_64.AppImage`
Might not be necessary depending on the distro I guess

**Comment by lucas-04** [comment]
![image](https://user-images.githubusercontent.com/95548091/163392534-240f551d-63c2-4d7b-8c81-7f641cf0602a.png)
works. Strange, I've never needed to do this with other AppImage

**Comment by Bionus** [comment]
You can usually do this by right-clicking the file and editing the properties.
Downloading files remove the chmod metadata, so personally I've always had to do that 🤔

Some file explorers are "smart" and automatically make AppImage files executable on double click, but I guess it depends on many factors.

Since it works now, I'll close the issue 😄

**Comment by lucas-04** [comment]
I had forgotten that I changed the ubuntu desktop enviroment, Lubuntu's file manager doesn't do this by default, unlike kubuntu's file explorer.

I feel kind of stupid now😕 

Anyway, thanks😄
