### ISSUE TITLE
Keep n tags seems to be ignored.

### ISSUE THREAD

**Issue by gummykage** [Bionus/imgbrd-grabber#2662]
Update: Tried nightly also cannot limit number of tags resulting in huge filenames.

**Bug description**

Keep n tags seems to be ignored for deviantart images (the one i'm currently testing). I cannot limit the number of tags saved into filename as a result.

Summary:
Token tags returns empty
Token all and allo returns all tags
Keep n tags seems to be ignored.
Happens on gelbooru and deviant art (the ones i've tested

**Steps to reproduce**
deviantart search any artist

1. Options -> Save -> Tags -> Keep n tags -> 1
2. Attempt to safe image with filename with token <tags> = empty, <all> = all tags unable to limit tags even when all are set to "Keep n tags = 1".

**Expected behavior**
One tag from the category is saved, not all.

**Context**
Deleted all settings, and started with default, set keep n tags on all options under:
Tags
Image size
Artist
etc.
all to "1"

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

**System information**

- OS: Windows 10 Latest
- Grabber version: 7.8.0 x64

**Additional context**
![image](https://user-images.githubusercontent.com/9695713/163819274-56dbb582-aee5-4a04-a831-c5b232bac628.png)

Add any other context about the bug report here.

**Comment by gummykage** [comment]
![image](https://user-images.githubusercontent.com/9695713/163824584-f5e06651-587a-4773-872d-53fa763f8360.png)
(7.6.2)

![image](https://user-images.githubusercontent.com/9695713/163824609-b172ac1b-b9fb-417a-af06-447203444a1f.png)
(7.8.0) and Nightly was tested also.

Seems settings got a bit jumbled up.

I'm using all:maxlength=15 to limit how many tags from deviant art is saved in the file name, is there a way to save 1-2 tags only or delimit how many by spaces?

**Comment by Bionus** [comment]
Hello, indeed the settings pages are a little bit shaken, but I'm not sure what you mean about the "keep n tags" not working.
Are you trying to use it for "general" tags, which don't have this feature available?

**Comment by gummykage** [comment]
The latest update fixed all the issues.
