### ISSUE TITLE
Memory leak on start-up

### ISSUE THREAD

**Issue by KeyboardCoomer** [Bionus/imgbrd-grabber#2665]
**Steps to reproduce**

1. Install Grabber on alternative drive
2. Go to grabber folder
3. Click on grabber.exe

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/8526163/main.log)

* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
(won't let me upload settings.ini for some reason)

**Screenshots**

![image](https://user-images.githubusercontent.com/73509970/164342891-7569693d-7af1-460a-9152-6a502cbd8b2d.png)

**System information**

- OS: Windows 10
- Grabber version: v7.8.1

**Additional context**

When trying to boot up the program, it won't load and I can see that it consumes all my computer's ram.

**Comment by Bionus** [comment]
How big is your `md5s.txt` file in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`?
You can also see issue #2491 that seem similar to yours.

I'll just copy my reply from there since it should be the same solution:
> Hello, have you been using Grabber for a long time?
> If so, you might be using the old MD5 database version that uses TXT files.
> 
> You can see that by checking in:
> ```C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber```
> 
> If there's a (big) `md5s.txt` file in there, you should either (after closing Grabber):
> * Delete it (global duplicate detection will be reset)
> * Delete it then re-generate it in the new format using the "MD5 fixer" tool (in Grabber's "Tools" menu)
> * Convert it to SQLITE via the "MD5 database converter" (in Grabber's "Tools" menu)
> 
> If that doesn't fix it, I'll need more info such as your logs.
> Otherwise, in most cases clearing the whole settings directory and re-installing should solve the issue.
