### ISSUE TITLE
Nothing is loading

### ISSUE THREAD

**Issue by Stevenador1** [Bionus/imgbrd-grabber#2666]
Anything I look up just starts a loading loop, but the bar doesnt progress, its just the sweeping stripe. Im not sure whast exactly is going on but this is started after the latest update

**Comment by Bionus** [comment]
Have you tried doing a clean install?
Like deleting (or moving away) the contents of `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` somewhere else and re-installing the last version?

**Comment by Stevenador1** [comment]
It seems to be an issue that fixed itself, I have poor internet and it seems that when it gets too poor it prioritizes certain things over others.

**Comment by Bionus** [comment]
Well I'll be closing the issue then, glad it worked out 😄
