### ISSUE TITLE
Showing no result when using Gelbooru as source

### ISSUE THREAD

**Issue by Cinaburger** [Bionus/imgbrd-grabber#2668]
Hi
When I search for images using Gelbooru as the source, it shows no result
If I use rule34.xxx, for example, it works normally. This started a couple weeks ago, I did not change the program in any way. I just updated to version 7.8.1 (x64) and the issue persists

![image](https://user-images.githubusercontent.com/104244412/164876050-de1ac9a5-0c68-4c0e-9100-f01f33de07cc.png)

**Comment by kuri7** [comment]
I too have the same problem. Updating also didn't fix anything.

**Comment by Cinaburger** [comment]
Sadly didn't work :(
Did you modify Grabber in any way at all? I haven't changed any settings from default, is there a super obvious button I'm missing maybe

![image](https://user-images.githubusercontent.com/104244412/165989679-26c1ef7a-19f1-445e-a82a-7c09c23b46f7.png)
![image](https://user-images.githubusercontent.com/104244412/165989822-9398fd3b-e1bd-4ea1-856f-8b05f57a2880.png)

If I click the sources, I can see that it is still searching and finding the images, but grabber still isn't showing them
![image](https://user-images.githubusercontent.com/104244412/165989965-62c11cd7-92c2-4d80-96ec-8793e9853313.png)

**Comment by Racer46** [comment]
I think deleting the config folder might help. In both arch and windows I used fresh, unmodified installs

**Comment by Cinaburger** [comment]
Sorry for what's probably an obvious question, but where do I find the config folder? I'm not very literate in these types of things

**Comment by Bionus** [comment]
Have you tried deleting the `sites` folder in the settings directory after updating to 7.8.1? (as suggested above)
```
C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber/sites
```

There has been a recent fix for Gelbooru but since 7.8.0 the sites files are now in Program Files on Windows instead of AppData.

**Comment by Cinaburger** [comment]
> Have you tried deleting the `sites` folder in the settings directory after updating to 7.8.1? (as suggested above)
> 
> ```
> C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber/sites
> ```
> 
> There has been a recent fix for Gelbooru but since 7.8.0 the sites files are now in Program Files on Windows instead of AppData.

That fixed it! Thank you
