### ISSUE TITLE
Adding single images via MD5 list timeout workaround

### ISSUE THREAD

**Issue by xodiack** [Bionus/imgbrd-grabber#2685]
**Is your feature request related to a problem? Please describe**

Semi-problem related. I collect MD5's that error out when downloading to try again at a later date or on a different source. I then add them back in via the "add" button for single images and using the MD5's to make a list.

Currently if my network drops out when parsing the pasted list, I'll need to restart from the top of the list. Would it be possible to have the "add an image" window to remove line by line as it parses the pasted MD5 list?

**Describe alternatives you've considered**

Currently I'll go ahead and download and compare/remove duplicates from my text list but it can be tedious depending on my connection quality.

![image](https://user-images.githubusercontent.com/36218702/168489976-f12628c7-5c5f-4f60-a78b-8a39a3db95f0.png)

**Comment by Bionus** [comment]
So from what I understand, what you'd like is for the "Add an image" window to remove the MD5 from the field as soon as an image is added to the download queue?

I'm not a big fan of editing user inputs. Wouldn't it be more efficient for the "Add an image" window to skip all images that are already added to the download list?

**Comment by xodiack** [comment]
Yes I think that would work better, skipping matching md5's already in the download list would work and achieve the same result.
