### ISSUE TITLE
im kinda stupid but, how do i use search pools i am VERY stupid

### ISSUE THREAD

**Issue by PixelPale** [Bionus/imgbrd-grabber#2694]

**Comment by Bionus** [comment]
Depends on the source, really.

For most "traditional" boorus, you just need to use "pool:POOL_ID", like "pool:18845":
![image](https://user-images.githubusercontent.com/882719/170999580-b8d41827-740b-4a95-876e-c6d74d771d3f.png)

You can also use the "pool tab" from the "file" menu, which pretty much does the same thing:
![image](https://user-images.githubusercontent.com/882719/170999674-e74ea90c-a3b9-41e2-8b98-b0ccac317096.png)
