### ISSUE TITLE
crashes when saving any tag to favorites

### ISSUE THREAD

**Issue by silverhikari** [Bionus/imgbrd-grabber#2695]
**Steps to reproduce**

1. Go to any image
2. right click on a tag
3. click on add to favorites
4. crash

**Context**
https://paste.ee/p/mgtLs (main log and settings)
i do not know how to provide the core dump
**System information**

- OS: Manjaro/Linux
- Grabber version: git commit: 3689d9bab3b48a5ef4be4c29d7357feb2f7bdfed

**Comment by silverhikari** [comment]
after making a new Grabber folder and trying it seems to add it fine so it seems to be a problem with how it deals with older favorites file from older grabbers

**Comment by silverhikari** [comment]
after comparing the two i originally thought it was caused by the new addition of the sites tag added to the newer favorites but not in the older favorites that was causing the older favorites file to cause the crash. but even after attempting to repeat the problem by removing the sites from a new favorites, and trying to added a new tag to the altered favorites to see if it causes the crash the tag is still added succesfully

**Comment by Bionus** [comment]
Hey 👋 

So from what I understand, you made a clean install then restored your settings from a previous install, then this problem occurred? Could it be that your old `favorites.json` file contained a favorite with a site you didn't add to your new setup yet?

If so, I can indeed reproduce the crash.

**Comment by silverhikari** [comment]
yes this seems likely to be the case even though i did not add any sites that did not come included in the base installation, i have noticed some sites have changed names which could be the cause. though i have fixed the problem for myself by creating a new favorites and re-adding them manually
