### ISSUE TITLE
Crash when the download storage is disconnected

### ISSUE THREAD

**Issue by IlluminatiWave** [Bionus/imgbrd-grabber#2696]
Problem:

When you are doing a massive download of images to an external storage (USB, or external hard drive as is my case), and this for some reason gets disconnected (in my case due to having an external box with a defective sata controller). The program first sends an error that it cannot download. When you reconnect the external storage, and hit the continue button, the program freezes and no longer responds afterwards (you have to close it from the task manager).

It also happens if you manually disconnect the external storage while doing the bulk download.

---

Windows 11 25120 (insider)
Grabber 7.8.1

**Comment by Bionus** [comment]
I just tried on an USB key, unplugging the key in the middle of a batch download (while a file is being downloaded), and while I got an error, resuming the download after re-plugging the key did work. Did you notice this happening only on a specific storages or at a special part of the file download? Is your external storage accessed via network or directly plugged into the computer?
