### ISSUE TITLE
Gelbooru ad page breaks tag recognition

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#270]
For instance, on gelbooru, there's an artist called m_nyanyan. Search and download went fine, but with %artist%\ in the filename, the images all ended up in the 'anonymous' folder.

I seem to recall the underscore causing some trouble a while back. Perhaps simply substituting a regular dash - when outputting to filename would solve this? :3

You've been busy, and very glad gelbooru works again in the version. Thanks so 
much for your sustained and consistent efforts <3 <3

> Original issue reported on code.google.com by `PhotonB...@gmail.com` on 15 Nov 2013 at 1:52

**Comment by Bionus** [comment]
Gelbooru removed their intermission ads end of 2016.
