### ISSUE TITLE
Some text isn't translated

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2705]
**Bug description**

Russian and French are fully translated on crowdin. But there are a few untranslated places in both languages.

**Steps to reproduce**

Here is the list:
1. Image window - buttons and their popups
![image](https://user-images.githubusercontent.com/4707112/172270438-a07d5b5c-3a58-4dec-b394-480fb48b6671.png)
2. ~Main window - Search (or new tab) - "Ok" button near the search field~
![image](https://user-images.githubusercontent.com/4707112/172270586-e94dc2fd-3260-43f9-b874-0156b8d2c545.png)
3. Options - Interface - Main Window - Shortcuts
![image](https://user-images.githubusercontent.com/4707112/172270961-a4e6553b-1ed7-4609-95b2-c9f0fd692b24.png)
4. Options - Interface - Image Window - Buttons
![image](https://user-images.githubusercontent.com/4707112/172271120-39cacc5b-6d10-408e-b438-54c926311e1b.png)
5. Options - Backup - Restore a backup
![image](https://user-images.githubusercontent.com/4707112/172271899-455e08fa-2518-4dc7-8d8d-78012e07191e.png)
6. Image window - Error loading the image. (it is translated on crowdin 6 months ago)
![image](https://user-images.githubusercontent.com/4707112/173842247-53c869b2-f3d8-40e7-abf1-bc1185487780.png)
7. Check "Merge results" in the main window - Activate a few sources - Search -> Multiple sources (it is not presented on crowdin)
![image](https://user-images.githubusercontent.com/4707112/175698402-7f7552a4-711a-4392-9e99-2da7e8bb5640.png)

**Expected behavior**

Full translation.

**Context**

N/A

**Screenshots**

See above.

**System information**

- OS: Windows 10
- Grabber version: 7.9.0

**Additional context**

Some of this text is presented on crowdin, some isn't.

**Comment by NEO-SPECTRUMAN** [comment]
А что есть русские которые не понимают Ok Load/Save? :rofl:

**Comment by Bionus** [comment]
I will have a look at the other points, but for the second one, the "Ok" button is just translated as "Ok" currently in the Russian translation. You can see that [by searching "O&k" in Crowdin](https://crowdin.com/translate/imgbrd-grabber/18/en-ru?filter=basic&value=0#q=O%26k) (the `&` is for mnemonics).

**Comment by adem4ik** [comment]
> I will have a look at the other points, but for the second one, the "Ok" button is just translated as "Ok" currently in the Russian translation. You can see that [by searching "O&k" in Crowdin](https://crowdin.com/translate/imgbrd-grabber/18/en-ru?filter=basic&value=0#q=O%26k) (the `&` is for mnemonics, so Alt+K works).

Oh, thank you, fixed!

**Comment by adem4ik** [comment]
I've added item #6.

**Comment by adem4ik** [comment]
@Bionus I've added point 7. Let me know if this workflow isn't fine for you. I can make separate issues if you need.

**Comment by Bionus** [comment]
@adem4ik it's totally fine with me either way 👌 Given each point is quite small it's fine to do it this way
Thank you for doing such in-depth proofing. I admit I'm using the program in English so it's easy to miss some translations 😓

**Comment by Bionus** [comment]
Now all points should be solved in nightly, is that correct?

**Comment by adem4ik** [comment]
Checked on (aeecbc74):

1. Buttons - partially, mb it needs translation update/sync.
![image](https://user-images.githubusercontent.com/4707112/178880781-877e6955-3d9b-4e50-bdfa-4a8ef178a61d.png)
2. Fixed
3. Fixed
4. Fixed
5. Fixed
6. Fixed
7. Fixed

**Comment by adem4ik** [comment]
Everything is translated now in https://github.com/Bionus/imgbrd-grabber/commit/e95197c40aa88b36e301b4748acd64bef88d41fd 
![image](https://user-images.githubusercontent.com/4707112/179001048-492b9d3e-2d30-487c-8d70-f2d069ab7d0a.png)
