### ISSUE TITLE
Download progress bar overlaps tags positioned to the left side of image window

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2714]
**Bug description**

If the tag list is positioned to the left side of image window, download bar will overlap it.

**Steps to reproduce**

1. Set Options > Interface > Image window > Tag list position = Left
2. Open any big picture or video with lots of tags
3. Watch to the download progress bar

**Expected behavior**

Tags shouldn't be overlapped by download progress bar

**Context**

N/A

**Screenshots**
![2022-06-09_07-37](https://user-images.githubusercontent.com/4707112/172759512-77c8f62e-d3b6-4d29-8e14-31c892de5d96.png)
![2022-06-09_07-32](https://user-images.githubusercontent.com/4707112/172759517-45a027e1-9033-4bd7-9728-5131781a1e37.png)

**System information**

- OS: Manjaro KDE Linux, Windows 10 x64
- Grabber version: 7.9.0

**Additional context**

It doesn't seem too noticeable on Windows, but it looks ugly in KDE.

**Comment by Bionus** [comment]
Makes sense. I always use tags on top so I didn't really notice that. It overlaying the image is by design (to avoid it jumping when the bar disappears), but on top of the tags is pretty ugly.
