### ISSUE TITLE
[iphone] Nozomi.la not playing videos. 

### ISSUE THREAD

**Issue by Shredhhead15** [Bionus/imgbrd-grabber#2719]
when i try to play a video on nozomi.la, it doesn’t play. at first nothing shows up but after a few seconds, only the tags appear, no video. 

**Steps to reproduce**

1. Go to nozomi.la
2. type video and sound, or just sound.
3. click any video

it should show a video player of some kind with a play button to start it. 

- OS: IOS.

**Comment by Bionus** [comment]
Hello 👋 

Are you on the proper issues tracker?
Grabber does not support nozomi.la, and there is no iPhone / iOS version.

**Comment by Shredhhead15** [comment]
i’m not sure. i googled “why is nozomi.la not playing videos on iphone” and found a chat log on this website. but non of the solutions people gave helped me.

**Comment by bokh-h** [comment]
Hey, did you ever find a solution to this problem? I’m encountering the same issue and your post is the ONLY result in google search. I have no other reference for why this is happening.

**Comment by Shredhhead15** [comment]
no unfortunately

**Comment by bokh-h** [comment]
Thanks

**Comment by Santironazero1507-hub** [comment]
> Hey, did you ever find a solution to this problem? I’m encountering the same issue and your post is the ONLY result in google search. I have no other reference for why this is happening.

Hi everyone. I just had the same problem and the only "solution" i found to it was changing browser (i'm on android so i don't know if this works on iphone sorry), in my case i was originally using OperaGX, then i copy-pasted the link too google chrome and reloaded the page a few times, after the 3rd reload the video started playing.
I haven't tried but if you have the problem in google, maybe using opera, brave or any other browser could solve it... well, partially. I hope it helped.

P.D: I'm sorry if my writing is strange, i haven't learned english so well yet.
