### ISSUE TITLE
Crash on clicking any image or video

### ISSUE THREAD

**Issue by jitsuCM** [Bionus/imgbrd-grabber#2721]
So, I'm getting crashes on clicking any image or media. I didn't had this before on old 7.2 (i believe it was that version). I got this in the log file:
**[19:03:29.318][Error] [Qt][default] Cannot mix incompatible Qt library (5.12.0) with this library (5.15.2)**

So I started to dig deeper to find which qt library it's trying to use. Clearly all the libraries in the Grabber directory are proper 5.12.0 version. That's the callstack I got on crash:
![image](https://user-images.githubusercontent.com/8429517/174128960-17ddd5b5-9d3f-43b4-bbcc-683d648e1520.png)

Notice anything odd, or strange? Lemme help:
![image](https://user-images.githubusercontent.com/8429517/174129064-08566577-5d56-45c8-9bfb-ccbea41f779d.png)

So i ran to see where the module comes from, and BAM:
![image](https://user-images.githubusercontent.com/8429517/174129195-8b1b09c2-ce0c-47cd-87a4-cc51966f056f.png)

And there is *NO* Qt5Svg.dll in grabber install. Is it supposed to be there? When it's missing, does it just try to use different renderer?

Well it turns out that if Qt5Svg is found anywhere on the path, it *will* try to use, regardless of version. Maybe Svg renderer should be included with Grabber? I have no idea about the implications of that, though.

**System information**
- OS: Win 10
- Grabber version: 7.9.0 x64

**Comment by Bionus** [comment]
Strange, I was not aware of a dependency on Qt5Svg, but indeed it seems to be there after doing a few checks.
I'll include it in the Windows installer from now on, thanks for noticing that and investigating it in such detail! 😄

**Comment by jitsuCM** [comment]
Awesome, thanks :D
