### ISSUE TITLE
[safebooru, danbooru] Incorrect names given to ratings

### ISSUE THREAD

**Issue by scoliono** [Bionus/imgbrd-grabber#2723]
**Bug description**

Safebooru and Danbooru rating descriptions shown on the websites do not match the abbreviations given in the API. Grabber takes this value directly from the API, potentially affecting the save location of images.

**Steps to reproduce**

1. Search `id:4054397` on Safebooru
2. Click 'Details'
3. Rating shows as 'questionable'

1. Search `id:5450477` on Danbooru
3. Click 'Details'
4. Rating shows as 'g'

**Expected behavior**

In both cases, the rating should show as 'general' like it does on both websites:
https://safebooru.org/index.php?page=post&s=view&id=4054397
https://danbooru.donmai.us/posts/5450477

I suggest adding a setting that configures how ratings in each booru's API get mapped to a `%rating%` value. The current categories seem to be pretty unreliable anyway. For instance, [Gelbooru](https://gelbooru.com/index.php?page=forum&s=view&id=5646) just made a new 'general' rating and renamed 'safe' to 'sensitive'.

**System information**

- OS: Arch Linux
- Grabber version: 7.9.0

**Additional context**

According to the Safebooru [api](https://safebooru.org/index.php?page=dapi&s=post&tags=monika_(doki_doki_literature_club)&q=index), 'q' means 'general' and 's' means 'safe'

**Comment by Bionus** [comment]
On safebooru, the rating is incorrect because their API returns "rating=q" for this image:
https://safebooru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=id:4054397
I guess it's not all very ironed out yet on their end.

I'll fix the "g => general" mapping at least.

**Comment by Bionus** [comment]
> According to the Safebooru [api](https://safebooru.org/index.php?page=dapi&s=post&tags=monika_(doki_doki_literature_club)&q=index), 'q' means 'general' and 's' means 'safe'

It doesn't really make much sense, given "q" is an already existing shortcut for "questionable". Is this Safebooru-specific? 🤔
