### ISSUE TITLE
Tags in Metadata only working using '%md5%.%ext%' Filename

### ISSUE THREAD

**Issue by Ariskapp9** [Bionus/imgbrd-grabber#2725]
Is there any way to have Grabber add tags to the 'IPTC:Keywords' metadata field without having the filename only be `%md5%.%ext%`? If I define anything other than this in the filename it wont add the tags, `%search%/%md5% - %rating% - %date:format=yyyy•MM•dd%.%ext%` is my desired filename.

**Comment by Bionus** [comment]
Could it be because of `•` in your filename? Have you tried without it?
Because there's no need to have your filename be `%md5%.%ext%` for metadata to work.

Also, are you using the Windows Property System or Exiftool? I guess the latter given you mentioned "IPTC:Keywords"?

**Comment by Ariskapp9** [comment]
> Could it be because of `•` in your filename? Have you tried without it? Because there's no need to have your filename be `%md5%.%ext%` for metadata to work.
> 
> Also, are you using the Windows Property System or Exiftool? I guess the latter given you mentioned "IPTC:Keywords"?

Yeah, it was the unicode bullet point that was messing it up.
