### ISSUE TITLE
How to open?

### ISSUE THREAD

**Issue by piss12121111** [Bionus/imgbrd-grabber#2730]
version 7.9.0
Not seeing any way to open it
on windows 11

**Comment by Bionus** [comment]
By double clicking on it? 😅 

On Windows, just install it with the .exe if you didn't already:
https://github.com/Bionus/imgbrd-grabber/releases/tag/v7.9.0

The installer will generate a desktop shortcut, otherwise you can open it from wherever you installed it, by default Program Files.
