### ISSUE TITLE
No longer able to download massive batches (21,000+ images)

### ISSUE THREAD

**Issue by Toadman45** [Bionus/imgbrd-grabber#2731]
Specs: Windows 11, Grabber version 7.9.0 x64, amd ryzen 3600, amd radeon 589x 8gb, 16gb of ram

Problem:

I'm trying download massive batches(60,000+ images) of my favortie franchises only for it to stop and "finish" once it reaches 21,000 images. This happens with gelbooru(I only use gelbooru due its massive database, so idk if this happens with other sources). I had no problem doing this with the older versions.

Attempted Fixes:

- Rollback to older version - I tried rolling back, but the previous versions are too buggy, it doesn't load or process gelbooru images and it crashes when going to the download page
- Re-download - It just skips all existing files and still stops at 21,000, not bothering downloading the rest
- Clean Re-Install and restarting computer - Tried it, doesn't work 

Screenshot of log: 

![Grabber 6_25_2022 7_40_16 PM](https://user-images.githubusercontent.com/108201798/175795344-2bdce226-7849-48e2-9ae8-978065982bd0.png)

**Comment by brazenvoid** [comment]
Gelbooru does this from time to time, its normal.
