### ISSUE TITLE
Sankaku broken 7.9.0 and onward

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#2733]
chan.sankakucomplex.com doesn't work in 7.9.0 or the nightly. For instance, trying to look up the tag harydraws will show no results despite on the left side where it shows tags listing 571 under harydraws. Though oddly looking without any tags it'll show some of the stuff recently added, though not all. I'm guessing tags or something somehow got broken with 7.9.0 and greater. I'm guessing the fact that it nuked model.ts with no actual warning that was going to happen before updating. Though my sankaku folders in sites in my appdata have been read only for years now and weren't changed, so I dunno.

The nightly zip build is missing a lot of files as well like qscintilla2_qt5.dll and many others - one from a lower version has to be used.

The installers are also still hanging for me on one of the last stages, trying to install some png - just hangs forever. Have to end task it. It's done this for the past several versions and I know I've reported that before. File: C:\...\Bionus\Grabber\themes\QDarkStyleSheet\img\checkbox_checked_disabled.png

As a little update I tried reverting to 7.8.1 with the archive and then the exe over top of it, that did not fix it. I'm guessing something 7.9.0 did when updating may have deleted some important files or something needed for properly loading tags there, probably in appdata.

**Comment by Bionus** [comment]
Sankaku isn't supported, so I can't really help here. Maybe someone on the Discord might be able to help? Maybe the Sankaku devs changed something on their end, breaking the old model file.

Although after checking I noticed an unrelated bug causing "null" URLs to get called, and fixed it, it won't really help your case.

> The nightly zip build is missing a lot of files as well like qscintilla2_qt5.dll and many others - one from a lower version has to be used.

Indeed, good catch. The ZIP release was only added recently and there's key differences in how it's generated so there's still a few things to iron out. I'll add the QScintilla DLL to it. Also, the nightly already has a few changes for it, if you want to try it out. What other DLL is missing? That's the only I noticed after double-checking.

> The installers are also still hanging for me on one of the last stages, trying to install some png - just hangs forever. Have to end task it. It's done this for the past several versions and I know I've reported that before. File: C:...\Bionus\Grabber\themes\QDarkStyleSheet\img\checkbox_checked_disabled.png

Never seen this. Is the directory too long that it can't be written? Does the installer logs say anything?

**Comment by Tiffys** [comment]
> Never seen this. Is the directory too long that it can't be written? Does the installer logs say anything?

Well I have long file paths enabled so rather than 260 characters it should be 32,767 max which I kinda suspect the installer isn't attempting. Not sure where the installer log is though. I have reported that particular issue before though, it's been around a good long while.

> What other DLL is missing? That's the only I noticed after double-checking.

Not sure. I didn't make any notes aside from this report so I really don't remember.

**Comment by Bionus** [comment]
> I have reported that particular issue before though, it's been around a good long while.

Moving discussion to #2625 then.

> Not sure. I didn't make any notes aside from this report so I really don't remember.

Alright. Do tell me if you see anything else, but I think it should be fine in nightly.
