### ISSUE TITLE
'Report an issue' should redirect to issues/new/choose

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2734]
**Bug description**

'Report an issue' from Help menu redirects to https://github.com/Bionus/imgbrd-grabber/issues/new , so a user can't select issue type. And also he won't have a standard form for issues.

**Steps to reproduce**

1. Start Grabber
2. Click on menu Help -> Report an issue

**Expected behavior**

'Report an issue' should redirect to https://github.com/Bionus/imgbrd-grabber/issues/new/choose

**Context**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/176387998-13032f1c-c8b4-4074-9ac2-7a7872724028.png)
![image](https://user-images.githubusercontent.com/4707112/176388142-b7c749b8-a897-4334-8156-a12b033fbd0c.png)

**System information**

- OS: Windows 10 
- Grabber version: 7.9.0 - nightly (262e8f93)

**Additional context**

N/A

**Comment by Bionus** [comment]
Makes sense, and would likely lead to better reports 👍 
That's actually already the case on the Android version, dunno why I didn't change it on desktop as well
