### ISSUE TITLE
Cant click restore button

### ISSUE THREAD

**Issue by kwekewk** [Bionus/imgbrd-grabber#2737]
**Bug description**

restore button is greyed out can't be clicked

**Steps to reproduce**

1. Go to 'Option'
3. Click on 'ackup'
4. See restore greyed out

**Expected behavior**

I've never done a restore, but I think the grabber should open a new window to browse the previous backup files

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/9031365/main.log)

**Screenshots**

![Screenshot (61)](https://user-images.githubusercontent.com/101484315/176962347-a642a001-f977-475c-af05-fab7a34416de.png)

**System information**

- OS: windows 10
- Grabber version: Nightly - ba8a806f

**Additional context**

Add any other context about the bug report here.

**Comment by Bionus** [comment]
That would be expected. This button is disabled because it's not implemented yet. I am still working on this, but I just wanted to at least provide the option to create backups first. If necessary, you can restore them by unzipping them in your settings directory while the program is closed.

**Comment by z-impi** [comment]
This button is still disabled. 
The backup button works but is useless unless the restore button is working.
Any updates on this?
(Same issue)
