### ISSUE TITLE
Support for Mastodon websites

### ISSUE THREAD

**Issue by EquestRiley** [Bionus/imgbrd-grabber#2739]
Can you add support for Mastodon and it's adjacent websites like Pawoo and Baraag?

Here's some documentation provided by another user: 
Source code: https://github.com/pixiv/mastodon/tree/pawoo
Documentation on Mastodon's API: https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md

**Comment by Bionus** [comment]
Makes sense. Are Pawoo and Baraag the most used Mastodon instances? Or are there others?

**Comment by Bionus** [comment]
I put the list of the instances with 20K+ users from here as a base (+baraag since it wasn't in it for some reason even with 50K users): https://instances.social/list/advanced#min-users=20000

As usual, new ones can still be added manually.
