### ISSUE TITLE
AppData/Local/Bionus folder is not deleted during uninstallation process

### ISSUE THREAD

**Issue by Azurac** [Bionus/imgbrd-grabber#2745]
**Bug description**

During the uninstallation you are asked whether you want it to completely uninstall...
After uninstallation the folder in AppData/Local remains untouched.

**Steps to reproduce**

1. Install
2. Uninstall

**Expected behavior**

The folder Bionus and all its content should not be present within the AppData/Local directory.

**System information**

- OS: Windows 10
- Grabber version: 7.9.0

**Comment by Bionus** [comment]
Hello, that's expected in case someone wants to just move the install directory or keep their settings for later.
I'll add a setting to choose between deleting it or not in the next version.
