### ISSUE TITLE
Search using Username/Artist on Pixiv 

### ISSUE THREAD

**Issue by Kukuru97** [Bionus/imgbrd-grabber#2746]
Can we get search using username/artist on Pixiv ?

I want to download an image from artist/user on pixiv, but when I search for it using the username/artist name it doesn't show up, I have to download it through the character tags and it's very annoying. So can we get a search using username/artist name on Pixiv?

Thank you.

**Comment by Frosty704** [comment]
search with their id  e.g
user:25855728

**Comment by Kukuru97** [comment]
> search with their id e.g user:25855728

![Screenshot 2022-07-12 114539](https://user-images.githubusercontent.com/100615360/178410574-562c858c-e490-4233-a5c5-5373dfdac6ba.png)


same, no result

**Comment by Frosty704** [comment]
you need to enter user: as well, not just the number

**Comment by Bionus** [comment]
As said by @Frosty704, you need the `user:` prefix, as in "user:12378747".
You can see the documentation here: https://bionus.github.io/imgbrd-grabber/docs/sources/pixiv.html
