### ISSUE TITLE
Unknown CMake command "qt_create_translation"

### ISSUE THREAD

**Issue by 09eragera09** [Bionus/imgbrd-grabber#2749]
**Steps to reproduce**

1. Git clone latest
2. Do `./build.sh`

**Expected behavior**

Grabber should compile successfully and without issues

**Context**

Running ./build.sh causes the script to crash, with the error of

> CMake Error at gui-qml/languages/CMakeLists.txt:14 (qt_create_translation):
>  Unknown CMake command "qt_create_translation".

**System information**

- OS: Ubuntu 20.04.4 LTS
- Grabber version: Git clone as of 14/07/2022 00:00 IST

Output and Error logs attached
[CMakeError.log](https://github.com/Bionus/imgbrd-grabber/files/9105793/CMakeError.log)
[CMakeOutput.log](https://github.com/Bionus/imgbrd-grabber/files/9105795/CMakeOutput.log)

**Comment by 09eragera09** [comment]
As far as I can tell, they have all been successfully installed and are already the latest version.

![image](https://user-images.githubusercontent.com/13760504/179028842-8b9a80ee-38e2-45b9-ae82-a41f8b61e0c9.png)

**Comment by mstraughan86** [comment]
I had this issue, solved it with `qmake --version` which indicated to me that my Anaconda environment actually was overwriting my system installed version.

**Comment by RustyHorns** [comment]
> I had this issue, solved it with `qmake --version` which indicated to me that my Anaconda environment actually was overwriting my system installed version.

How did you solve it from that command? 
It give me this but, don't understand what to do next.
`QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
`
