### ISSUE TITLE
[Regression] Search field allows to paste a text with formatting

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2752]
**Bug description**

Search field allows to paste a text with formatting (see the screens below). It seems like a regression in compare with the stable version 7.9.0.

**Steps to reproduce**

1. Copy any formatted text (i.e. from any web site)
2. Paste it into the search field

**Expected behavior**

Text is pasted without formatting.

**Context**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/178914561-4e624b0d-1d20-4e8d-b642-dfcf4f8ec0fc.png)
![image](https://user-images.githubusercontent.com/4707112/178915091-e3c0c7ba-51dd-48b3-94cd-e17e2a81a29d.png)

**System information**

- OS: Windows 10
- Grabber version: latest nightly (aeecbc74)

**Additional context**

v7.9.0 doesn't have that issue.

**Comment by adem4ik** [comment]
Might be related to this fix https://github.com/Bionus/imgbrd-grabber/commit/bd623544b68a399e8add17fd99d9a2cadcc33c8c of https://github.com/Bionus/imgbrd-grabber/issues/2738

**Comment by Bionus** [comment]
The problem was always there, it was just hidden because stuff was getting some magic re-formatting before.
Good catch, I pretty much never paste stuff in there 😅
