### ISSUE TITLE
gelbooru data pulls are empty 

### ISSUE THREAD

**Issue by Arucard707** [Bionus/imgbrd-grabber#2757]
gelbooru shows content is available and Grabber shows gelbooru recognizes content is available within the Tags screen, but the image previews (Downloads previews ) show there is no result and therefore there is no option to download. I have checked a few other sites within sources and they provide results and previews as intended.  I have tried a variety of searches within gelbooru and they are all the same results. This started a couple days ago, most likely when 7.91 was released and somehow interfered with 7.90, after update to 7.91 it still occurs.  

I have provided examples with the same search as an example. Please let me know if any additional data is needed. 

![Screen Shot 2022-07-17 at 11 43 44 PM](https://user-images.githubusercontent.com/76802537/179457448-61d99d0a-f405-427b-be65-8c5a9e650faf.png)
![Screen Shot 2022-07-17 at 11 44 02 PM](https://user-images.githubusercontent.com/76802537/179457452-a1ceb2ff-7d12-4bdb-b371-33708c99d6b4.png)

**Comment by xDaSkLox** [comment]
Can confirm the same.  Happened right after updating and have been reinstalling and adjusting settings to try and fix it with no success.

**Comment by HanatakeYurii** [comment]
Same her. The log gives me:
`[12:23:15.364][Warning] [gelbooru.com][Xml] Search error: We have exceeded maximum queries per day for anonymous usage. Yukkuri Shiteitte ne! :&lt;
[12:23:15.366][Warning] [gelbooru.com] Loading using Xml failed. Retry using Html.`

It reacts as if I was not logged in. When I test my credentials, I get 'Success', but that doesn't change anything.

It it a Grabber defect or should we change something?

**Comment by ikhlaz** [comment]
It's not just Gelbooru. 
Rule34.paheal and Rule34.xxx turns up empty too.

**Comment by lx30011** [comment]
Same issue here

**Comment by Arucard707** [comment]
I kept getting the same thought around max amount of downloads, since the queries were working then they stopped. Is this a gelbooru or an incorrect user logging issue from Grabber. Could Grabber automatically clear and restart that user every X amount of times or each time for that matter ?

**Comment by Bionus** [comment]
Does this also happen on 7.9.0? 🤔

**Comment by CH4SSEUR** [comment]
> Does this also happen on 7.9.0? Or is it 7.9.1 specific? 🤔

same problem for me happen on 7.9.1
tbh i thought gelbooru updated their api or something

**Comment by Hojo-Norem** [comment]
I'm getting this too.  I can't remember exactly what version I was on (Probably the one just before 7.9.0), but I was getting the problem with that version.  It didn't feel like it started instantly to me either, more like Gelbooru access slowed down something fierce until it just up and quit with 'No Results'.

I upgraded to current to see if that would fix the issue...  no success.

I will say that I don't log into Gelbooru, I pretty much never have.

**Comment by HanatakeYurii** [comment]
@ikhlaz
> It's not just Gelbooru. Rule34.paheal and Rule34.xxx turns up empty too.

Those are working for me, I only have a problem with Gelbooru. Maybe try a clean install if you have problems with other sources.

I have to add after the error message in the logs which seems linked ti XML query, Grabber tries HTML but returns no error and no images so far.

**Comment by Arucard707** [comment]
I was checking in older problem tickets and it seems like it kicks things out from time to time , but what's odd to me is that the issue states "We have exceeded maximum queries per day for anonymous usage" which would imply that after 24-48 hours of non usage it should allow normal functions, but it doesn't seem to be resetting even after the program has been off for X amount of time ... curious what cache isn't being flushed or what timer isn't being reset

**Comment by Atulin** [comment]
```
[04:46:03.472][Warning] [gelbooru.com][Xml] Search error: We have exceeded maximum queries per day for anonymous usage. Yukkuri Shiteitte ne! :&lt;
[04:46:03.472][Warning] [gelbooru.com] Loading using Xml failed. Retry using Html.
```

from what I figured out, Gelbooru now requires the API key and user ID on every request. Username and password seem to be not quite enough

**Comment by Arucard707** [comment]
Can we either extend the limit of the API Requests manually or is that something within Grabber that is fixed? also what login will it need if the username and password isn't enough ?

**Comment by Atulin** [comment]
The workaround currently seems to be switching login method to URL, and providing the API key and user ID you can find in Gelbooru options. It does need an account.

**Comment by Arucard707** [comment]
So I got it working with the API access at the bottom of the options on Gelbooru but who know how long that will hold. Hopefully the api holds without issue

**Comment by Triramama** [comment]
i would like it pointed out if im missing something here. I entered the numerical user id like it appears on gelbooru , and entered the api line and nothing still works for me

**Comment by Dprasni** [comment]
> So I got it working with the API access at the bottom of the options on Gelbooru but who know how long that will hold. Hopefully the api holds without issue

Could you add more detail here ?
I'm also trying it but i am not having luck, it might help if you share how you did it or what you edited where, blurred pics could also help 
:)

**Comment by NEO-SPECTRUMAN** [comment]
> Does this also happen on 7.9.0? Or is it 7.9.1 specific? 🤔

this is ~~up~~ down to 5.5.2

**Comment by Atulin** [comment]
@Dprasni 
Here's where to find the credentials:
![image](https://user-images.githubusercontent.com/11233299/179890894-3b2bc731-95d0-432a-bcff-0ed3de5000a6.png)
And here's where to use them and how to set up the login:
![image](https://user-images.githubusercontent.com/11233299/179891118-c5c18b9e-e6e9-4fe5-9f1e-b5816f3df456.png)

**Comment by Arucard707** [comment]
Hey @Dprasni 
@Atulin beat me to it lol, Butonce you sign into Gelbooru website , and in the settings page at the very bottom, you will see a code like in the first picture, you have to break down the whole code as Atulin shows very well. You will have to input those specific characters in both areas to work. Grabbers sources (Pic 2) is in the lower left hand corner of the search page when you are looking for something . Then the rest is save and restart grabber for the credentials to take effect. (at least that's what I did )

**Comment by HanatakeYurii** [comment]
I don't get why but Gelbooru is working again on my side without doing anything.
Seems something is happening on their end.

**Comment by Hojo-Norem** [comment]
Same here.  Still not logged in.  Now working.

That being said, I did notice that while this was happening, yande.re wasn't updating as in there hadn't been any new posts.  As soon as Gelbooru started working, so did new posts start appearing on yande.re.

Probably just a coincidence.

**Comment by HanatakeYurii** [comment]
> Probably just a coincidence.

Maybe not, I know multiple sources are replicating their content by fetching them on other sources, like Gelbooru is fetching from Danbooru. It's fairly possible that Gelbooru was also unavailable for Yande.re .

**Comment by NEO-SPECTRUMAN** [comment]
> Gelbooru is working

5.5.2 works again

**Comment by Arucard707** [comment]
My best guess is in the issue itself: "We have exceeded maximum queries per day for anonymous usage"
The per day usage must have reset and allowed access again ... now where it is and where it was referencing ie Danboru or donna... is unknown but possibly relevant. My best guess is it will happen again eventually but the time when it does will be sporadic

**Comment by NEO-SPECTRUMAN** [comment]
> : "We have exceeded maximum queries per day for anonymous usage"

but web interface is full worked

**Comment by xDaSkLox** [comment]
I also just noticed the total images per page not being the correct number.  I have mine set to 1000, but it only shows 100 per page.  In some cases, it will even show an incorrect page number count (e.g.  page 3 of 1).

**Comment by brazenvoid** [comment]
Gelbooru has limited access to anonymous usage, it is a two way restriction:
1. Maximum downloads per search is limited to 100. 
2. Total anonymous requests has a limit per 24 hours.

As already deciphered by previous comments, one now needs to have an account and use the user and API keys with each API request to make it work. 

I have seen that grabber is sending user_id as username instead of the numeric ID as per the API how to in gelbooru. 

But for now it seems they have blocked API access for even authenticated usage.

**Comment by brazenvoid** [comment]
If only gelbooru offered a paid subscription and hassle free usage, I would take it up any day,

**Comment by brazenvoid** [comment]
Found this in gelbooru FAQ:

**Q: My program that uses the Gelbooru API stopped working suddenly. What changed?**
A: Make sure that you are sending your login cookies when accessing the API. We no longer allow anonymous access to the API.

**Comment by Bionus** [comment]
Seems like their API is available for anonymous usage again, so I'll close this issue.
However, in general I'd recommend logging into any source you're using  to prevent this kind of issue from popping up.
