### ISSUE TITLE
Can't download batch of more than 100 pics from gelbooru

### ISSUE THREAD

**Issue by AvenNyan** [Bionus/imgbrd-grabber#2761]
Can't download batch of more than 100 pics from gelbooru when click get all

1. Searck for author (squchan for example)
2. Click on "Get all" button
3. Go to downloads (that say that there 378 images for download)
4. Click "Download" button

And... Download window say that queue is only 100 pics
Tested with danbooru, works fine, but with gelboory only 100 pics
![изображение](https://user-images.githubusercontent.com/109649930/179914193-678156b6-8cc1-42ee-92dc-107f20b038ca.png)

**Comment by vnbrk** [comment]
The same thing happens to me both on the stable and nightly builds, plus crashing when batch downloading from tags with +100 pictures in them.

**Comment by Arucard707** [comment]
I have been experiencing a similar issue with Gelbooru and may be related, if I select a set that has over 1000 it will take the first 100 of the pages and then go to the next one. For example I requested one set that had 3780 , it downloaded the first 100  but removed 1000 from the total list and eventually I received 300 with it stating it downloaded -178 photos as well which looks like a simple calculation error. 

Please see if if you experience the same issue with a data pull that is more than 1000 images

**Comment by AvenNyan** [comment]
I found a temporary solution now. Just set "Image per page" to 100 and it download all. But obviosly it need to set "100" in every batch manually (maybe there are option to set default value)

**Comment by HeroBaskan** [comment]
bump

**Comment by Sophignon** [comment]
Bump. Still an issue.
