### ISSUE TITLE
Get all button working incorrectly for gelbooru

### ISSUE THREAD

**Issue by jehutyDev** [Bionus/imgbrd-grabber#2765]
**Bug description**

Using the gelbooru option the "Get all" button is working incorrectly, download just a partial amount of images on download list and download counter works incorrectly,
same partial download behavior ocurs on monitor and with any tag 

**Steps to reproduce**

just try to download any tag with several pages and check the behavior on the download window pop up
the same behavior happens on the monitor tab if you check the log tab

**Expected behavior**

the correct amount of images*pages to be downloaded; its correctly downloading 100 pages per request just as the api allows but just for the first pages then it just ignores the existend amount of pages and images, all this works correctly with others servers

**Context**

I noticed this happen on gelbooru after trying to download a tag then changed the page number on the download list and the behavior just seems incorrect every aptempt changing the page (manually changing to page 1, 2, 3 etc) its not like I downloaded thousands of images but it appears not to be an ip ban maybe I'm  doing something wrong and I'm only one with this issue

**System information**

- OS: linux mint
- Grabber version: tested on 2 versions (7.8.1 and 7.9.1)

**Comment by xDaSkLox** [comment]
I can also confirm downloading using "Get All" will only download 100 images (tested using a tag with 500+).

On a related note, setting the number of images to anything higher than 100 defaults to 100 images being loaded when viewing.  I have tested with 50 (works), 101, 500, and 1000 (last 3 results loaded 100 images).

OS: Windows 10
Version: 7.9.1

**Comment by Bionus** [comment]
Indeed, they changed the max number of images per page from 1,000 to 100. I pushed a fix but until the release you can just override the "images per page" value (in batch downloads) to 100 instead of the automatically generated value.

**Comment by jack652** [comment]
same hapens to me even tho i set the "images per page" value in the settings to 100
