### ISSUE TITLE
using tags freeze program and have to kill to exit the program

### ISSUE THREAD

**Issue by silverhikari** [Bionus/imgbrd-grabber#2766]
**Bug description**
when typing a tag(this happens even if you do not press enter to search through tags just inputting the tag and hitting space afterwords), the program freezes and has to be kill with commandline to stop running(and on kde sometimes complete freeze the desktop requiring to switch terminals to kill)

**Steps to reproduce**

1. go to search bar
2. input tag
3. press space
4. freeze

**Expected behavior**

the program heads to the right tag search results or you can input more tags

**Context**
i have tried this with both a clean make from source and from a new default grabber config folder, and this problem continues to happen. i have also tried several diffrent source and it seems to happen to all of them

logs:https://paste.ee/p/tWwRO

**System information**
- OS: Manjaro
- Grabber version: git-develop current

**Comment by Bionus** [comment]
What tag were you trying to type?
Was it part of your favorites or kept-for-later tags?

**Comment by silverhikari** [comment]
i tried this with both a tag from favorites and a random tag both had the same problem

**Comment by silverhikari** [comment]
just built 7.9.1 master branch from source code and tested that it does not seem to have the problem

**Comment by Bionus** [comment]
Alright, I could reproduce by having an empty "kept for later" list. I guess the same issue would happen if you don't have favorites, since it would generate this regex for highlighting: `(?: |^)()(?: |$)`, which matches everything in an infinite loop.
