### ISSUE TITLE
Webm files not saving

### ISSUE THREAD

**Issue by otis626** [Bionus/imgbrd-grabber#2767]
I understand that only mp4 files are allowed to be saved to my iPad. However, at least make it easier, or at the very least, make it possible to properly upload webm files to a different cloud/storage service. When I tap the “share” button, I get a list of options of where to send it and one of them is Google Drive. However, when try to upload it to Drive, it saves it as an unopenable file. I even tried editing the name of the file by adding the .webm extension, but when I try to open it later, I get a message stating that the file is unsupported. Please fix this issue quickly or at least let me know a way to save webm file from the iOS Sankaku app. Thanks in advance.

P.S. I’m glad to see more content is available.

**Comment by Bionus** [comment]
Are you on the correct issue tracker?
Grabber doesn't have an iOS / iPad app, unless you compiled it yourself?
