### ISSUE TITLE
Update to r34.us

### ISSUE THREAD

**Issue by kryptic-x** [Bionus/imgbrd-grabber#2773]
Just tried using the TS file posted a bit a go and even messing with it i cant seem to get images to load despite the site being recognised.

**Comment by Bionus** [comment]
You cannot use TS files as-is, they must be compiled to JS first.
I don't know what TS file you're talking about, but if it's from the `develop` branch, you can just use the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/nightly).
