### ISSUE TITLE
Windows zip don't open

### ISSUE THREAD

**Issue by lucas-04** [Bionus/imgbrd-grabber#2774]
![image](https://user-images.githubusercontent.com/95548091/182143000-d14d5cc2-5de6-499f-b159-43c4d44ba89b.png)

Is there some configuration I have to do to use it or is this a bug?

**Comment by Bionus** [comment]
Indeed, for some reason Github actions isn't bundling the "sites" directory in the ZIP release, making it not work.
Closing as duplicate of #2707, but thanks for the reminder as it slipped out of my mind 😅
