### ISSUE TITLE
Change the date/time format for the "%date%" tag.

### ISSUE THREAD

**Issue by Proxor1999** [Bionus/imgbrd-grabber#2775]
For most people who sort files by date, it is much more convenient to use the following format:
**"YYYY-MM-DD HH.MM.SS"**
![Screen_00](https://user-images.githubusercontent.com/70063590/182337747-ab14e87d-bcb3-4380-ae69-8689d9d76417.PNG)
Please change the format of the "date" tag to this standard. Or add the ability to manually configure. **Displaying seconds will also be useful and important.**

So far, when setting the "use system locale for dates and numbers" parameter, even when setting the native system date / time format in windows, 
![Screen_01](https://user-images.githubusercontent.com/70063590/182334656-36d66c4d-c7d8-4344-8626-e0d410c23503.png)
the program ignores the setting and adds a standard tag in the file name (in the form: "MM.DD.YYYY HH.MM"). 
![Screen_02](https://user-images.githubusercontent.com/70063590/182334683-a7ecb18c-c099-4588-80ca-e931da6cd97c.png)
![Screen_05](https://user-images.githubusercontent.com/70063590/182340924-86c6b289-e5b1-499d-8d02-28519e7eb044.PNG)

At the same time, on Rule34.xxx site the date format is: "YYYY.MM.DD HH.MM.SS"
![Screen3](https://user-images.githubusercontent.com/70063590/182335003-f6c2f34a-cd6f-4f1d-9d45-92155a769ecd.PNG)

If you uncheck this option in the program settings, it will still be restored.
![image](https://user-images.githubusercontent.com/70063590/182336761-99ed1036-af27-4afc-b7b9-dea09d9b6896.png)

**Comment by Bionus** [comment]
The "use system locale for dates and numbers" is only used for the interface in the program, not the filename.

For changing the format of the `%date%` token, you should use the `format` token option:
```
%date:format=yyyy-MM-dd%
2001-05-21
```
See [the docs](https://bionus.github.io/imgbrd-grabber/docs/filename.html#format) for reference.

If not specified, it will use `MM-dd-yyyy HH.mm`, whatever the original source's date format is.
