### ISSUE TITLE
Can't not load current tag after add an tag to blacklist

### ISSUE THREAD

**Issue by rieniter** [Bionus/imgbrd-grabber#2776]
**Steps to reproduce**

1. Search an tag
2. Click on random Image to Open an Detail Windows
3. Right-Click to an Tag on Detail Windows just opened, choose "Open new tab", the grabber now Loading this new Tab (but incomplete) then close this tab
4. Back to Detail Windows, Select and add an tag to Black List
5. Press Enter to refresh current Searching tag in step 1
6. Bug: The grabber now not loading anymore (keep "Enter" to refresh but still not load", must close grabber and re-open to reload

**System information**

- OS: [e.g. Windows 10]
- Grabber version: 7.9.0 (x64)

**Comment by Bionus** [comment]
> the grabber now Loading this new Tab (but incomplete) then close this tab

What do you mean by "incomplete"?

I just tried going through this flow and didn't meet issues. Are you using "Ignore images contained a blacklisted tags" in your settings? And did you blacklist the tag you were searching or another one? (maybe all results were filtered?)
