### ISSUE TITLE
md5 record unable to auto delete after removing group

### ISSUE THREAD

**Issue by Pil0tXia** [Bionus/imgbrd-grabber#2777]
**Bug description**

The md5 records in md5s.sqlite are unable to be auto deleted after removing download group although I didn't enable "Remain deleted images' md5s" option.

**Steps to reproduce**

I have 2 PCs to manage danbooru images, and the folder paths on these PCs are different.
1. download all my favorite images on PC1
2. copy C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber to PC2
3. use navicat to correct the path in md5s.sqplite. Replace all the paths records on PC1 with the paths on PC2
4. correct the save path and path_real in settings.ini
5. add a new favorite image, than download all the images on PC2
6. we can see that previous images are skipped and only 1 image is saved
7. remove the group in download tab.
8. we can see that the path record of the new image is still in md5s.sqplite
remember to apply and refresh in navicat.

**Expected behavior**

The md5 records in md5s.sqlite should be auto deleted after removing corresponding download group.

**Context**

Here are the files needed on PC1 and PC2:
[PC1.zip](https://github.com/Bionus/imgbrd-grabber/files/9254064/PC1.zip)
[PC2.zip](https://github.com/Bionus/imgbrd-grabber/files/9254059/PC2.zip)

**System information**

- OS: win11
- Grabber version: 7.9.1

**Comment by Bionus** [comment]
> The md5 records in md5s.sqlite should be auto deleted after removing corresponding download group.

I think there's a misunderstanding here. The MD5 files in the file are not deleted when you delete a download group.

They are pretty much never removed, unless Grabber tries to download an image, a matching MD5 is found but the file does not exist anymore and "keep deleted files in the MD5 list" is off.

**Comment by Pil0tXia** [comment]
Alright i get it. The md5 records will be deleted the next time. Thank you.
