### ISSUE TITLE
two issues with grabber + gelbooru installed on localhost

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#278]
I set up a localbooru on my pc using the guide here:

https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru

Although it works, when I use grabber to save an image, the tags it posts to my localbooru get all the underscores converted to spaces.

For example, for an image with a single tag of "very_long_hair", the tag will get converted into 3 separate tags: "very" "long" "hair"

The second issue is that all images posted to my localbooru by grabber end up being hidden and I'm always having to click the hidden posts button to make them show up

> Original issue reported on code.google.com by `jon...@yahoo.com` on 4 Jan 2014 at 4:13

**Comment by Bionus** [comment]
You could totally use something such as: `cmd1 & cmd2`

For example:
```
C:\Windows\System32\cmd.exe /C copy "%path%" "C:\wamp\www\gelbooru\images\1\%md5%.%ext%" & i_view32.exe "C:\wamp\www\gelbooru\images\1\%md5%.%ext%" /resize=(150,150) /aspectratio /resample /convert="D:\Sites\gelbooru\thumbnails\1\%md5%.%ext%"
```
