### ISSUE TITLE
No source found error.

### ISSUE THREAD

**Issue by Sicanpanda35** [Bionus/imgbrd-grabber#2783]
**Steps to reproduce**

1. Go to 'Grabber Folder'
2. Click on 'Grabber.exe'
3. See error

**Context**
Every time i try to run Grabber.exe it gives the error in the screenshots part.
I can't upload my settings.ini file here. Forgive my ignorance.

**Screenshots**

![Grabber Error](https://user-images.githubusercontent.com/110964978/183833365-0b0ab7e1-8f25-46d4-bb27-a9875c65ce7a.jpg)

**System information**

- OS: Windows 11 x64 21H2
- Grabber version: 7.9.1

**Additional context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/9297428/main.log)

**Comment by Sicanpanda35** [comment]
Nvm i fixed it. By the way how do you delete the post?

**Comment by Bionus** [comment]
Yup, it seems the sources are not present in the ZIP release for some reason.
See issue #2707 for reference, I'll be closing this one 👍
