### ISSUE TITLE
[Mastodon/Pawoo] Error while trying to login

### ISSUE THREAD

**Issue by Tenome** [Bionus/imgbrd-grabber#2786]
**Bug description**

Logging in via OAuth2 produces an unknown client error. I might've logged in wrong though since I haven't added a new site in a long time and don't remember anything about OAuth2. You put your regular login information into the fields, and then Grabber gets the keys when it opens the website to authenticate it? Or am I supposed to get the consumer key/secrets somehow?

`Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`

**Steps to reproduce**

1. Enter email and password into OAuth2, hit Test
2. Pawoo opens up, shows that I'm signed in, but rejects the authentication.

**System information**

Windows 7, Grabber 7.9.1.

**Comment by Bionus** [comment]
> You put your regular login information into the fields, and then Grabber gets the keys when it opens the website to authenticate it? Or am I supposed to get the consumer key/secrets somehow?

Yes exactly 😄 

I just updated the docs to explain how: [link](https://github.com/Bionus/imgbrd-grabber/blob/develop/docs/_sources/mastodon.md)
You need to have cURL or equivalent installed. Note that some user has reported that the login is not working for them for some reason 🤔

**Comment by Bionus** [comment]
Yup my bad, I don't know what cat walked on my keyboard to add "shrc" (I guess I was editing my `.bashrc` file at the time?) but the correct link is "https://pawoo.net/api/v1/apps":
```
curl -X POST -F "client_name=Grabber" -F "redirect_uris=http://127.0.0.1/" https://pawoo.net/api/v1/apps
```
