### ISSUE TITLE
Is -grabber:inMd5List working properly? (Pixiv)

### ISSUE THREAD

**Issue by Tenome** [Bionus/imgbrd-grabber#2787]
**Bug description**

Grabber doesn't seem to be excluding images that are already in the md5 sqlite database when searching. Am I using the filter wrong or something? -grabber:downloaded didn't work either (even if I use it as a regular filter, in which case it should show only the image I downloaded). It's like the MD5 file isn't being referenced at all when searching. 

Perhaps it's just Pixiv that isn't working properly with these filters? I tried Gelbooru and the post-filter seems to work fine. Deviantart doesn't seem to work with the filter either.

**Steps to reproduce**

1. Download an image from Pixiv with MD5 in the filename, keep in the same folder that I downloaded to
2. Confirm that the md5s.sqlite file updated with the MD5 (b319c9f05e751d6cbcf78d1cfcd6d138 in this case)
3. Search using "-grabber:inMd5List" as a post-filter
4. Image I just downloaded that's in the MD5 sqlite still shows up in the search results.

**Expected behavior**

Don't want to see images I already downloaded

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/9363304/main.log)
Keep deleted file in MD5 list: True
If file already exists globally: Save

**System information**

Windows 7
Grabber 7.9.1

.

**Comment by Tenome** [comment]
I think I might've found out why it's not working. For some reason, Pixiv and Deviantart's downloaded images don't actually get registered as Saved. If you keep the window open and right click, it'll give you the option to Delete, showing that it was indeed saved. However, if you refresh the search, the same image will say Save, as if you didn't already download it. Here's a log file with Gelbooru (seems to be working as intended), and Pixiv/DA (not working as intended).

[main.log](https://github.com/Bionus/imgbrd-grabber/files/9363897/main.log)
.

**Comment by Bionus** [comment]
I believe that would be because Pixiv's API does not return the MD5 when listing results, so Grabber has nothing to match the MD5 database against. It works on save because after downloading the image Grabber will calculate its MD5, but before that it doesn't 🤔

**Comment by Tenome** [comment]
What about just using the URL for Pixiv/DA since downloaded/MD5 doesn't seem to work?

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.
