### ISSUE TITLE
GelBooru 0.11 Beta Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#279]
**What is your suggestion for the program?**
Gelbooru 0.11 downloading support should be added to Grabber, as 0.2 is still 
in closed beta.

**What version of the product are you using? On what operating system?**
3.4.1/Windows 7

> Original issue reported on code.google.com by `epicspyninja` on 6 Jan 2014 at 3:17

**Comment by algufronirachel-creator** [comment]
Mikadono
