### ISSUE TITLE
when using the "rating:" tag, there are no gelbooru results

### ISSUE THREAD

**Issue by jack652** [Bionus/imgbrd-grabber#2790]
**Bug description**

when i use the "rating:" tag in the tags search, there are no gelbooru results

**Steps to reproduce**

1. use a rating tag like "rating:safe"
2. click "ok"
3. no gelbooru results

**Expected behavior**

it should show every gelbooru image that has the "safe" rating and matches the other tags

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/9411385/main.log)
[settings.ini](https://anonfiles.com/neNed258y7/settings_ini)

**Screenshots**

![image](https://user-images.githubusercontent.com/48365199/186295262-f82622e9-e38a-4f39-9024-118e9c8b5755.png)

**System information**

- OS: w10
- Grabber version: 7.9.1

**Comment by Bionus** [comment]
Hello, the `rating:safe` option has been renamed to `rating:sensitive` by Gelbooru and Danbooru when they introduced the new `rating:general` option.

See this [Gelbooru forum post](https://gelbooru.com/index.php?page=forum&s=view&id=5646) for reference.
