### ISSUE TITLE
Non-translatable strings

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2791]
**Bug description**

Some strings are not available for translation on crowdin.

**Steps to reproduce**

1. Downloads tab - Resume popup dialog `Some downloads were started but not finished. Do you want to continue from where you left off?`
![image](https://user-images.githubusercontent.com/4707112/186329334-44c49f5f-2e17-42a1-ae1a-e6b449532c88.png)
2. Settings - Save - Conditional filenames
![image](https://user-images.githubusercontent.com/4707112/186329630-d453ec94-afab-4b4d-a429-0a87f3d8d329.png)

**Expected behavior**

Strings are available for translation on crowdin.

**Context**

N/A

**Screenshots**

See above.

**System information**

- OS: Windows 10
- Grabber version: latest nightly https://github.com/Bionus/imgbrd-grabber/commit/612550ac63a7cdf70532305d651cd34298942855

**Additional context**

N/A

**Comment by Bionus** [comment]
Indeed. I try to update strings from time to time but it's easy to forget. And updating them all the time are annoying because of line numbers changing causing a new huge Crowdin PR 🤔
