### ISSUE TITLE
Possible Bug or Error on Users Part

### ISSUE THREAD

**Issue by makoto-kokoroki** [Bionus/imgbrd-grabber#2793]
I seem to be unable to load certain sources and am met with this when attempting to do any search. ![Screenshot_20220826-004658.jpg](https://user-images.githubusercontent.com/79054137/186824125-c5e5e008-67bf-4b81-bbf3-4d0ec58e7f22.jpg)

**Comment by Bionus** [comment]
Which source is that?
And does it happen on all sources or only that one?

**Comment by makoto-kokoroki** [comment]
This happens with the e-hentai/ex sources in regards to that particular screenshot. Even when using login info in the POST fields. The others I did not mention that just won't seem to load are slushe, njie.info, reddit, pixiv, and nhentai. It's likely a user error on my part as I do not know if there is extra steps involved with using those sources. But all the other sources load fine when I do a search, so, I am not sure.
