### ISSUE TITLE
[Site Request] Newgrounds Art

### ISSUE THREAD

**Issue by Tenome** [Bionus/imgbrd-grabber#2794]
Newgrounds has an art gallery like DeviantArt, etc. feature that's fairly popular. Would it be possible to add that? It supports searching via tags, by username, etc.

https://www.newgrounds.com/art

**Comment by Bionus** [comment]
Do they have an API or something similar?
If yes should be pretty straightforward to add.

**Comment by Tenome** [comment]
> Do they have an API or something similar? If yes should be pretty straightforward to add.

They have some APIs listed, not sure if it's what you need.
https://www.newgrounds.com/wiki/creator-resources/

**Comment by Tenome** [comment]
Any luck?
