### ISSUE TITLE
how to put computer's date in filename?

### ISSUE THREAD

**Issue by mmoisall** [Bionus/imgbrd-grabber#2795]
my source site imagefile don't have their date (site: booru.sugall.com)

so when I use   %date%   it just become empty

I want to put 'my computer time' or 'time when the image posted on the site'
How do I do that?

imagefile has no other information when downloaded from the site
![2795](https://user-images.githubusercontent.com/99416891/187047156-fe302508-b5c2-4a4e-8f4d-25081e7652c5.png)

![화면 캡처 2022-08-28 053651](https://user-images.githubusercontent.com/99416891/187047145-ce7a6f76-f582-4c5e-a628-3e83e8e73b71.png)

**Comment by Bionus** [comment]
Hello 👋

You can use `%current_date%` instead of `%date%` to use the current date instead.
If you want to do something like "if the date is provided, use it, otherwise use the computer date", you can use `<%date%?%date%:%current_date%>`.

**Comment by mmoisall** [comment]
![6](https://user-images.githubusercontent.com/99416891/187047774-3d6b9129-121e-4ad0-af72-a629a00f6521.png)
