### ISSUE TITLE
Changing %current_date% to yy.MM.dd hh.ss (question)

### ISSUE THREAD

**Issue by mmoisall** [Bionus/imgbrd-grabber#2796]
I originally use   `%date=yy.MM.dd hh.ss%`   in filename. (so I can sort files by name)

Some site has no date in the imagefile information, so I decided to use current date instead.
And I tried `%current_date=yy.MM.dd hh.ss%` but it didn't work. (it just become blank)

![화면 캡처 2022-08-28 195219](https://user-images.githubusercontent.com/99416891/187070394-f2ffbedd-5171-46dc-b15d-104d90cad9d0.png)
If I want to get filename like this from current date, what should I do?

**Comment by Bionus** [comment]
I don't think you were using `%date=yy.MM.dd hh.ss%` but `%date:format=yy.MM.dd hh.ss%` (cf the [filename docs](https://bionus.github.io/imgbrd-grabber/docs/filename.html#format)).
And the equivalent would be `%current_date:format=yy.MM.dd hh.ss%`, which should work.
