### ISSUE TITLE
Grabber not downloading all the images

### ISSUE THREAD

**Issue by AkzhanArdaki** [Bionus/imgbrd-grabber#2802]
After installing the program I have chosen Gelbooru as download source. I logged into my account and searched for artist under the name "atdan". App gave me 631 images. I added them all to download (screenshot 1). But when I start downloading process it only downloads 100 (screenshot 2) and finishes with this 100 files. So, how can I download all 631 images?

I also trying different artist under the name "yuuji_(and)" with 1811 images found. When I try to download them all app only downloading 911.

![Grabber_8KNhnTggU4](https://user-images.githubusercontent.com/83055846/189716670-13964e2f-49c7-4bc3-bd69-5c1c9c273838.png)
![Grabber_vDmLa36RXF](https://user-images.githubusercontent.com/83055846/189716685-e84d5ede-e3e5-46ee-a891-6bb314a2b1d9.png)

**Comment by mittski** [comment]
@IGraysonI I'm running into the same issue, could you post what your solution was?

**Comment by IGraysonI** [comment]
> @IGraysonI I'm running into the same issue, could you post what your solution was?

Sorry, I don't remember. Its way a year ago
