### ISSUE TITLE
Please can any help me on how the exiftool works for grabber?

### ISSUE THREAD

**Issue by Ammoswift** [Bionus/imgbrd-grabber#2803]
Seriously I downloaded a put in the appdata folder for grabber and NOTHING. Can anyone please help me?

**Comment by GameCharmer** [comment]
Put it in the folder where grabber.exe is located

**Comment by Bionus** [comment]
You should put it where Grabber can find it.
As suggested above, it could be in Grabber's install folder, but it could also be anywhere in your `%PATH%`.
