### ISSUE TITLE
It is impossible to download more than 100 photos at the same time

### ISSUE THREAD

**Issue by G1TL3R** [Bionus/imgbrd-grabber#2804]
**Bug description**

It is impossible to download more than 100 photos at the same time, although I have added more than 600 photos to the downloads

**Steps to reproduce**

I write tags in the search for the Gelbooru site, click download everything, go to downloads and click download, only 100 out of 600 are downloaded

**Expected behavior**

All 600 photos should have been downloaded

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/9593309/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/9593311/settings.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/104305297/190891438-7cffbdcc-28da-407d-a9fa-3dc6b91af670.png)
![image](https://user-images.githubusercontent.com/104305297/190891357-a71bafad-a04e-4c15-9ae2-b27bd9d15c80.png)

**System information**

- OS: [Windows 10 pro]
- Grabber version: [7.9.1]

**Additional context**

Please help fix this problem, the last time everything worked fine, it was a long time ago, but nevertheless

**Comment by Bionus** [comment]
You should set the "images per page" to 100 on Gelbooru.
See issue #2765 for more info.
