### ISSUE TITLE
can anyone help me I'm having problems with grabber V7.9.1 

### ISSUE THREAD

**Issue by sinkiller21st** [Bionus/imgbrd-grabber#2806]
every time I boot it up the images are showing larger then normal and when clicking one one of these images it starts to load then grabber shuts down I tried reinstalling it and redownloading it but nothing works I had to downgrade it to grabber grabber V7.2.1 can anyone help me

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.

**Comment by Bionus** [comment]
What do you mean by "larger than normal"?

Could it be that you changed the "upscaling" setting in the "interface" settings?
![image](https://user-images.githubusercontent.com/882719/196035428-6bfe81ad-cecb-418b-8e4d-ef806bc1bb8c.png)

Unless you have a 2K/4K screen, I wouldn't really recommend putting it above 100%.

**Comment by sinkiller21st** [comment]
I had it to its default settings

**Comment by sinkiller21st** [comment]
sorry for the late reply

**Comment by sinkiller21st** [comment]
its default setting was 120 I lowered it to 100 and when it made the image smaller but I'm still having a problem clicking an image to pop up to view it still crashes
