### ISSUE TITLE
Images in MP4 format and slow speed

### ISSUE THREAD

**Issue by kevinRAM99** [Bionus/imgbrd-grabber#2807]
**Bug description**

I go from having a speed of 20 mb/s to 30 kb/s, this happens when the image link changes to video-cdn3, I don't know if I did something wrong or gelbooru has those links.

**Steps to reproduce**

1. Normal download from Gelbooru

**Screenshots**

![image](https://user-images.githubusercontent.com/110026884/192009524-7668d374-d5e3-43d7-bd7f-350c3f7c6c01.png)

**System information**

- OS: Windows 10
- Grabber version: 7.9.1

**Additional context**

When copying the links and entering them to jdownloader, the download speeds up to 250kb/s in jd

sorry if this issue has been posted earlier

**Comment by Bionus** [comment]
Doesn't that sound more like an issue with Gelbooru servers if they're slow only on this server?
Grabber does not choose the servers, they're returned by Gelbooru's API. What search are you doing that causes this?
