### ISSUE TITLE
Sankaku

### ISSUE THREAD

**Issue by Reberebe** [Bionus/imgbrd-grabber#2808]
It's been a while since Sankaku stopped working on the app, 
I'm mainly writing this to ask if there are any plans on bringing it back to imgbrd-grabber? 

Thanks for the hardwork, the program is great, I love being able to have my images with tags as metadata
Sadly many of the things that are uploaded in sankaku aren't in the other boorus and is such a pain to have some images without metadata, 
I know Sankaku has been making their site worse and worse, nerfing everything to strong arm its users into paying for their subscription and that some recent change was the cause for it to stop working with the grabber, anyhow as I mentioned I'm mainly just asking if it is in the future plans (so I can pull the bandaid and kill any hopes for it - also if anybody know any alternative for extracting metadata from it, haven't been able to find anything even near to this grabber), 
again thanks for the great work and such an useful tool.

**Comment by Vixal** [comment]
I uploaded a updated model file here : https://github.com/Bionus/imgbrd-grabber/issues/2770#issuecomment-1203156797
Replace your existing file with that one, then go to sources and click options next to sankaku. Go to sources and set source to Json. Then go to login and set login to oauth and fill in your sankaku username and password. You need an account for json to work.

**Comment by BOBBOB123123** [comment]
> 

Does this make all the images show up? Is there anyway to make all images show up? Most tags seem to have a significant amount of imgs missing when trying to browse in grabber.

**Comment by NEO-SPECTRUMAN** [comment]
significant amount of imgs on sankaku is for premium users only...

**Comment by Vixal** [comment]
> > 
> 
> Does this make all the images show up? Is there anyway to make all images show up? Most tags seem to have a significant amount of imgs missing when trying to browse in grabber.

Some extreme content, sankaku premium and content that is illegal in some nations gives null url in json. I dont think there is a way to show them with json.
Could maybe be workarounded by loading details from regular html with regex, but thats not in the model file I linked.

**Comment by TeKett** [comment]
You need to be logged in to see contentious_content. While they keep reducing access to the website, they seams to have opened up the api, so you can now do slower searches again without getting paywall blocked and search 100 images per page.

**Comment by Jorge9811** [comment]
> I uploaded a updated model file here : [#2770 (comment)](https://github.com/Bionus/imgbrd-grabber/issues/2770#issuecomment-1203156797) Replace your existing file with that one, then go to sources and click options next to sankaku. Go to sources and set source to Json. Then go to login and set login to oauth and fill in your sankaku username and password. You need an account for json to work.

this aint working

518 results for daki_(kimetsu_no_yaiba) in chan.sankakucomplex.com and 0 in grabber

i got https://github.com/Bionus/imgbrd-grabber/issues/1888#issuecomment-607106830 and then added the models from your post

what do?

**Comment by Reberebe** [comment]
First of, thanks for the reply and apologies for taking so long
was just trying to replace the model but inside the sites folder there isn't any "Sankaku" folders for me to replace the model with,
While in the grabber application chan.sankaku remains selected and my login info remains there from the past
So I'm wondering what the folder name inside the "Sites" folder in the grabber installation should be called for me to put the model.js inside 
Thanks again

**Comment by TeKett** [comment]
Copy of my own files, they are set to read only, remember to login.
[Sankaku.zip](https://github.com/Bionus/imgbrd-grabber/files/9754767/Sankaku.zip)

**Comment by Jorge9811** [comment]
> 

thanks this wrks

**Comment by Reberebe** [comment]
you absolute madlad, I can't thank you enough 
Thanks, Thanks, Thanks

**Comment by Bionus** [comment]
> I'm mainly writing this to ask if there are any plans on bringing it back to imgbrd-grabber?

No such plans at the moment, but there are third-party / edited model files that exist (such as the one above) that can be used to add it yourself. If someone has the energy, a [source registry](https://bionus.github.io/imgbrd-grabber/docs/sites/source-registry.html) could also be created to add support for it more easily.

Since the original question was answered, I'll close the issue 👍

**Comment by Magidog** [comment]
TeKett thank you so much

**Comment by KuroiMatoO** [comment]
Can you please explain what do I need to do with this zip file? I tried to put its content inside Grabber/sites but nothing changed.

**Comment by Reberebe** [comment]
> Can you please explain what do I need to do with this zip file? I tried to put its content inside Grabber/sites but nothing changed.

The contents from the Sankau (folder - zip) go in 
C:\Users\YOURUSERNAME\AppData\Local\Bionus\Grabber
you can modify the file so it has your username and password or login each time directly from grabber

**Comment by Zwilliam** [comment]
I did all the above and still it says no results, did sankaku change something at some point? Thread seems dead but hoping to be able to grab images

**Comment by Oleksandrigo** [comment]
Upd model js for Sankaku
[Link_PASTEBIN](https://pastebin.com/5nPXcecA)
fixed crooked tags, because they were parsed through regex, which doesn't really want to work.

**Comment by TeKett** [comment]
> Upd model.js for Sankaku [Link_PASTEBIN](https://pastebin.com/5nPXcecA) fixed crooked tags, because they were parsed through regex, which doesn't really want to work.
> 
> full folder [Sankaku.zip](https://github.com/Bionus/imgbrd-grabber/files/15205245/Sankaku.zip)

Do yours fix idol? Since the one i got still works fine for me for chan

**Comment by Oleksandrigo** [comment]
> Do yours fix idol?

I don't know what their new api is now.

**Comment by TeKett** [comment]
It should be iapi, it still loads the pages in grabber, just not the images.

**Comment by Reberebe** [comment]
Thank you for the update King

**Comment by knightnova** [comment]
> > Upd model.js for Sankaku [Link_PASTEBIN](https://pastebin.com/5nPXcecA) fixed crooked tags, because they were parsed through regex, which doesn't really want to work.
> > full folder [Sankaku.zip](https://github.com/Bionus/imgbrd-grabber/files/15205245/Sankaku.zip)
> 
> Do yours fix idol? Since the one i got still works fine for me for chan

thank you for the update, it would be better if someone can fix the idol

**Comment by JFMugen** [comment]
> Upd model.js for Sankaku [Link_PASTEBIN](https://pastebin.com/5nPXcecA) fixed crooked tags, because they were parsed through regex, which doesn't really want to work.
> 
> full folder [Sankaku.zip](https://github.com/Bionus/imgbrd-grabber/files/15205245/Sankaku.zip)

Weird, it works on portable but doesn't work when you install the program

**Comment by eduardomozart** [comment]
Hello guys,
I would like to thanks @Oleksandrigo and  for sharing those files with us. It seems that the URL Login method doesn't seems to work anymore (only with JSON).
I've been working today on a gist that restores partially the functionality of HTML parsing and it's available at: https://gist.github.com/eduardomozart/feb4bbef30a47db1439d3ea9c03f28e0
As the URL Login method doesn't work anymore, it means you'll need to set the cookies manually. Simply right click the page > **Inspect element**, go to **Security** and creates the ``PHPSESSID`` and ``_sankakuchannel_session`` cookies on Grabber (copy it's value and name to there).
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/517742c3-a3de-46a3-b52c-9da6aa69e690" />
<img width="627" alt="image" src="https://github.com/user-attachments/assets/dcb99065-d74d-4ceb-bee1-de64ba8fc8b7" />
Also remember to set the source as **HTML** (default) on **Sources** tab.

**Comment by TeKett** [comment]
I cant see the PHPSESSID on my end on any browser, and from your image i guess it only lasts a few days before you need to get a new one? Getting HTML working is needed since the API seems to not serve all images anymore.

I when i try it grabber gets redirected to the premium popup. I'm guessing it shows since it can't serve ads, as it shows up on Chromium where i'm using blockers, but not on Firefox where i dont use blockers.

**Comment by eduardomozart** [comment]
Hello @TeKett,
I've updated my original comment with more info about my environment. For some reason, reloging again on Sankaku didn't set the ``PHPSESSID`` cookie, but I was able to browse Sankaku without using the ``_sankakuchannel_session`` cookie only. Even without the cookies set, I was able to list Sankaku content.
<img width="1441" alt="image" src="https://github.com/user-attachments/assets/6fbb0b8c-59ee-4504-ad47-7d9e60497c93" />
I believe that they keep their API because chan.sankakucomplex.com uses it on JS side to list the posts search (and I believe on other pages functions).
Can you provide a print screen of the issue you're facing? I have Sankaku Free and I was able to login and browse just fine on Grabber.

**Comment by TeKett** [comment]
Right, seemed to just be a quadruple whammy on my part and i didn't notice it since i have exclusively used grabber for a few years, the premium redirect was because i was using to many tags, since i forgot you cant use more then 3 tags on html. and apparently my filters was filtering out literally every single image on every page when searching without tags. Didnt know there was that much censored, ai, and animated posts. And i forgot that it only shows 25 images per page, and includes the 10 popular posts on the first page so my numbers didn't match what i had set. And the images i thought i could not see on JSON was due to the images was tagged using ai and had the wrong tags.

All in all, me dum dum, and thank you

**Comment by eduardomozart** [comment]
Yes, I opened an issue at #3362 about the missing Size attribute. It's not available on HTML without accessing the post page first, but it's available on JSON. If you remove the height limitation on your query I believe your search would work as expected.

**Comment by Oleksandrigo** [comment]
I've kind of fixed the ID.
In fact, just made a array to get the real id
https://gist.github.com/Oleksandrigo/82788d373a15475bf5e205b1bb1e516b

**Comment by Reberebe** [comment]
@eduardomozart  @Oleksandrigo  Thanks guys for the hard work, I tried to implement the updated model,
also just updated to 7.13 
I copied the cookie information on grabber, 
so it allows me to search and open the images, I can search, open images, download images, their metadata is there, 
is only the previews for the search results that are not loading (they show a red X) 
Is there something I'm doing wrong or I can do to see the previews?
Thanks again a lot for the updated model

**Comment by eduardomozart** [comment]
Here it's working just fine. Depending on the tags you're searching for, you may need to go to My account > Settings > Blacklist settings on Sankaku and change your Tags Blacklist to "i_just_want_limited_visibility_unblocked".

**Comment by Reberebe** [comment]
Thanks for your quick answer, 
My bad, I failed to change it to HTML, 
After changing sources to HTML  I'm getting "NO results" when I search for something 

As seen in  
![Image](https://github.com/user-attachments/assets/160295f9-c9bd-43a4-acaf-dfcfe9d41c0d)
Changed Sources to HTML,
Have my Login info (with "Success!" appearing when I do the test) 
And pasted the cookies as instructed 

But I'm still getting the Red X as thumbnails 
![Image](https://github.com/user-attachments/assets/84d08109-789c-4c8c-917c-cc5f8365a14b)
Both for Json and HTML 
This time I restarted Grabber when I did the change in case it helped when changing between HTML and JSON

(By the way the model.js I'm pasting in C:\Users\MyUser\AppData\Local\Bionus\Grabber\sites\Sankaku

**Comment by TeKett** [comment]
Sankaku has changed the format on their thumbnails, you need to get the plugin for AVIF files [qt-avif-image-plugin](https://github.com/novomesk/qt-avif-image-plugin/releases/download/v0.8.7/qavif.dll) and place it inside of the the grabber imageformats folder. Note that, last time i checked, not all thumbnails had been converted to the new format, and all the old thumbnail urls are access denied

**Comment by Oleksandrigo** [comment]
> Thanks for your quick answer, My bad, I failed to change it to HTML, Although after changing to HTML the issue persists
> 
> •Changed Sources to HTML, •Have my Login info (with "Success!" appearing when I do the test) •And pasted the cookies as instructed As seen in ![Image](https://github.com/user-attachments/assets/160295f9-c9bd-43a4-acaf-dfcfe9d41c0d)
> 
> But I'm still getting the Red X as thumbnails ![Image](https://github.com/user-attachments/assets/84d08109-789c-4c8c-917c-cc5f8365a14b) Both for Json and HTML This time I restarted Grabber when I did the change in case it helped when changing between HTML and JSON
> 
> (By the way the model.js I'm pasting in C:\Users\MyUser\AppData\Local\Bionus\Grabber\sites\Sankaku

https://github.com/Bionus/imgbrd-grabber/issues/3345

**Comment by Reberebe** [comment]
@TeKett @Oleksandrigo  
Thank you guys so much for the replies and information,
I don't think I would've been able to find that on  my own,

For some reason I tried the one posted in your link @TeKett  (V0.8.7)
and got the same result (I pasted it in  C:\Program Files\Grabber\imageformats)

Then Tried the one from the thread itself pointed by @Oleksandrigo (V0.8.3)
and now it works!!!

Thanks a bunch (again) guys 
@TeKett  @Oleksandrigo @eduardomozart 
for the answers, models and updates 
you guys are big brained 
is much appreciated

**Comment by TeKett** [comment]
Seem like `capi-v2` has been changed, as it no longer works and gives access denied for me since a few days ago. HTML is still working. I would be nice if someone could figure out if the api can me made to work again, since the HTML is very limiting

**Comment by Oleksandrigo** [comment]
The sankaku guys decided to migrate to another api sankakuapi.com
I had a little trouble because for some reason the previews came off at first, but everything seems to be ok.
As always in setting.ini change to your user and password.

[Sankaku.zip](https://github.com/user-attachments/files/19184452/Sankaku.zip)

**Comment by dejikonyo** [comment]
Is there an issue with idol.sankakucomplex. I keep on returning no results despite using the latest settings.

**Comment by Reberebe** [comment]
> The sankaku guys decided to migrate to another api `sankakuapi.com` I had a little trouble because for some reason the previews came off at first, but everything seems to be ok. As always in setting.ini change to your user and password.
> 
> [Sankaku.zip](https://github.com/user-attachments/files/19184452/Sankaku.zip)

Thanks for sharing!!!!
I was out of town when you sent this, had to format recently, so I'm just trying to get Grabber back in place, so I appreciate this a lot !

**Comment by Erebeon** [comment]
I've dropped the above sankaku folder in the grabber sites folder, I've added my username and pass to the ini file. Have set the source to html and login to Oauth, replaced the cookies text in the sankaku folder with my own cookie that includes the session id and have added it to the cookie interface inside grabber. I've also added the capi-V2 header. Yet still "No Result" and the test button to connect returns failed. What am I missing? 

In the log I get this;
[06:02:13.115][Info] [chan.sankakucomplex.com][Html] Loading page https://chan.sankakucomplex.com/post/index?page=1&tags=monster&login=xxx&password_hash=xxx&appkey=xxx
[06:02:13.540][Info] [chan.sankakucomplex.com][Html] Receiving page https://chan.sankakucomplex.com/post/index?page=1&tags=monster&login=xxx&password_hash=xxx&appkey=xxx
[06:02:13.540][Error] [chan.sankakucomplex.com][Html] Loading error: Connection closed (2)
[06:02:13.541][Warning] [chan.sankakucomplex.com] No valid source of the site returned result.

Any idea how I could troubleshoot this?

**Comment by Oleksandrigo** [comment]
> [@Erebeon](https://github.com/Erebeon) The `html` search engine isn't mantained by [@Oleksandrigo](https://github.com/Oleksandrigo), if you want to use it please check comment [#2808 (comment)](https://github.com/Bionus/imgbrd-grabber/issues/2808#issuecomment-2585533484)

added support html parse (thank @eduardomozart)
#[https://gist.github.com/Oleksandrigo/e45b22d353b2921a3d330941d0a0ae1f](model.js)

**Comment by Jorge9811** [comment]
> The sankaku guys decided to migrate to another api `sankakuapi.com` I had a little trouble because for some reason the previews came off at first, but everything seems to be ok. As always in setting.ini change to your user and password.
> 
> [Sankaku.zip](https://github.com/user-attachments/files/19184452/Sankaku.zip)



> > I've dropped the above sankaku folder in the grabber sites folder, I've added my username and pass to the ini file. Have set the source to html and login to Oauth, replaced the cookies text in the sankaku folder with my own cookie that includes the session id and have added it to the cookie interface inside grabber. I've also added the capi-V2 header. Yet still "No Result" and the test button to connect returns failed. What am I missing?
> > In the log I get this; [06:02:13.115][Info] [chan.sankakucomplex.com][Html] Loading page https://chan.sankakucomplex.com/post/index?page=1&tags=monster&login=xxx&password_hash=xxx&appkey=xxx [06:02:13.540][Info] [chan.sankakucomplex.com][Html] Receiving page https://chan.sankakucomplex.com/post/index?page=1&tags=monster&login=xxx&password_hash=xxx&appkey=xxx [06:02:13.540][Error] [chan.sankakucomplex.com][Html] Loading error: Connection closed (2) [06:02:13.541][Warning] [chan.sankakucomplex.com] No valid source of the site returned result.
> > Any idea how I could troubleshoot this?
> 
> added support html parse (thank [@eduardomozart](https://github.com/eduardomozart)) [model.js](https://gist.github.com/Oleksandrigo/e45b22d353b2921a3d330941d0a0ae1f)

how to use this successfully?

i downloaded and uncompressed sankaku.zip into a Sankaku folder

replaced its model.js with the Apr 19 one

dropped the folder in Grabber's sites folder

booted up went to sources > idol.sankakucomplex.com > options > login types my username and password and when i click test the program says Failure

is this working anymore or?

also every search result has a red cross instead of a thumbnail but then i click any and the contents actually work?

is that intended?

vvvvvvvvv

> > But I'm still getting the Red X as thumbnails ![Image](https://github.com/user-attachments/assets/84d08109-789c-4c8c-917c-cc5f8365a14b) Both for Json and HTML This time I restarted Grabber when I did the change in case it helped when changing between HTML and JSON
> 
> [#3345 (comment)](https://github.com/Bionus/imgbrd-grabber/issues/3345#issuecomment-2562031953)

thanks that worked dropped qavif6.dll in grabber's imageformats folder and now the thumbnails show up fine

the credentials problem persists tho and thast sucks because a lot of videos are hidden if you dont log in to a account

**Comment by TeKett** [comment]
Idol hasn't worked for years, and i dont think anyone will bother to make
it work unfortionetly, since nobody uses it. It barely get any image
uploads, its like an image a day or so, gelbooru has some amount of photos
on it. If you want photos i'd suggest e-hentai instead (Not Grabber), or
exhentai if you know how to access it. All the images are in original
quality, so no risk getting 100kb compressed 4k images (why do people
upload those). The cosplay tag; and expunged with filter for real_porn. You
can download mayraids master script in order to filter out favorited
galleries.

**Comment by Darkwolflair** [comment]
> is this working anymore or?

Yes, it's working fine now. Just consider updating the user-agent to the latest one, and place the right dll (qavif6) file into your folder for thumbnails.

**Comment by Jorge9811** [comment]
> > is this working anymore or?
> 
> Yes, it's working fine now. Just consider updating the user-agent to the latest one, and place the right dll (qavif6) file into your folder for thumbnails.

> > booted up went to sources > idol.sankakucomplex.com > options > login types my username and password and when i click test the program says Failure

> > thanks that worked dropped qavif6.dll in grabber's imageformats folder and now the thumbnails show up fine

> > the credentials problem persists tho and thast sucks because a lot of videos are hidden if you dont log in to a account
