### ISSUE TITLE
Sankaku Error: [Json] Uncaught exception at line 9: TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by VeggieJay** [Bionus/imgbrd-grabber#2822]
**Bug description**

Using the most recent model.js file for Sankaku, certain searches/pages/downloads fail and give the following error:

[Warning] [chan.sankakucomplex.com][Json] Uncaught exception at line 9: TypeError: Cannot read property 'name' of null
[Warning] [chan.sankakucomplex.com] No valid source of the site returned result.

Sometimes pages load, sometimes they do not. Sometimes results for pages 1-5 load, but page 6 will not. 

Additionally, downloads are inconsistent. Sometimes Get All functions correctly, sometimes it downloads only the first 100 images, or sometimes it completes with 0/0 downloaded.

**Steps to reproduce**

1. Run a search, examples "dead_or_alive animated" or "dead_or_alive see-through"
2. Try to navigate pages 1-6+ until it fails.
3. Also try Get All -> Download and check for behavior

**Expected behavior**
All pages to load and all downloads to complete

**Context**

Using the updated model.js file for Sankaku. Using JSON oauth 2. Behaved correctly until recent weeks

[main.log](https://github.com/Bionus/imgbrd-grabber/files/9843574/main.log)

(Redacted the 100 downloads but they functioned correctly )

**Screenshots**

![image](https://user-images.githubusercontent.com/52065198/197319884-0b286e37-6876-48da-b08e-ac83b4c58a84.png)
![image](https://user-images.githubusercontent.com/52065198/197319049-1e570d0b-39f7-4911-9bda-c3076a88ab30.png)
![image](https://user-images.githubusercontent.com/52065198/197320268-25739a29-3afd-4f36-a22b-2a36d8e2bca9.png)
![image](https://user-images.githubusercontent.com/52065198/197319106-eff60a38-60aa-4d08-aa29-3650b9b5e73e.png)

**System information**

- OS: Windows 10
- Grabber version: 7.9.1 nightly (4fa548d3) (x64)

**Comment by Bionus** [comment]
Seems like replacing
```js
img.author = img.author.name;
```
By  something like
```js
if (img.author) img.author = img.author.name;
```
in your model file should solve the issue?
