### ISSUE TITLE
Adding Model File to Linux AppImage?

### ISSUE THREAD

**Issue by TogarUshindi** [Bionus/imgbrd-grabber#2825]
How can I add a model file to Grabber if I'm using the AppImage?

There was a suggestion to use a model file to fix Sankaku, but where do I place it if ~/.config/ is not being used? Or is there a way to tell Grabber to use models external to the AppImage?

**Comment by Bionus** [comment]
I'm not sure what you mean by "~/.config/ is not being used"?

Even if you use the AppImage version, Grabber will still store the `settings.ini` (and others) somewhere. Exactly where is written in the log file or accessible via the "File" menu. There, just create a "sites" directory (although usually there's already one if you ever edited any source) and put the source directory there.
