### ISSUE TITLE
downloading not starting from 1st page to get content

### ISSUE THREAD

**Issue by kkort2022** [Bionus/imgbrd-grabber#2831]
downloading not starting from 1st page to get content

when I download a list with let's say 20'000 images how to make Grabber start from for example 11'000/20'000 not from 1/20'000 ?

**Comment by Bionus** [comment]
You can change the "Page" value in the downloads list.
If you have "images per page" set to 100 and you want to start at 11000, then you'd need to start at page 110. 👍
