### ISSUE TITLE
Danbooru Not Returning Searches

### ISSUE THREAD

**Issue by xodiack** [Bionus/imgbrd-grabber#2832]
**Bug description**

Danbooru will not return results if searched from a new tab after loading Grabber. If I leave the search "hanging" and close/re-open grabber when it resumes to the tab it will load the results. After doing so, future searches of that exact manner will return results.  I also tried a new API key but same behavior.

**Steps to reproduce**

1. Open Grabber , Have "Danbooru" as a source, search "tag1"
2. The search will show the loading bar continuously
3. Close Grabber, Re-open, "tag1" results will now load.
4. Can repeat the process with "tag2" , as long a there is no active search polling Danbooru "tag1" and "tag2" will return their 1st page (sometime 2nd) results.
5. "tag1tag2" will not work either unless closing/reopening as in the other steps. (I assume cache related or something like that?)

**Expected behavior**

Results to load in when searched, around Oct 23rd when I last used Grabber behavior was normal with results showing after 2 seconds or so.

**Context**

Log and settings attached.
[info.zip](https://github.com/Bionus/imgbrd-grabber/files/9944244/info.zip)

**System information**

- OS: W10 (Version	10.0.19044 Build 19044)
- Grabber version: 7.9.1

**Comment by Bionus** [comment]
Strange, definitely a bug somewhere although I can't reproduce it.
Did you set "Max simultaneous downloads" to 1 in your Danbooru source settings?

**Comment by xodiack** [comment]
I was notified via email so did some trouble shooting, came here and saw your edit and tried again. Changing danbooru to '1' donwload did not change the behavior as far as I could tell (unless I was being throttled and on cooldown) but when I changed the global simultaneous downloads to '1' things seemed to start working correctly.

Here's the log + my comments while running it, if anything looks off. I'll leave it on -d to maybe catch it if it acts up in the future. My comment lines are prefixed with ";;@@"

[Troubleshoot.zip](https://github.com/Bionus/imgbrd-grabber/files/10008622/Troubleshoot.zip)
