### ISSUE TITLE
Flatpak support (Linux)

### ISSUE THREAD

**Issue by Yumae** [Bionus/imgbrd-grabber#2837]
**Is your feature request related to a problem? Please describe**

The AppImage and AUR packages are good options for distributing the program in Linux but there is an issue with each. AppImage has no simple automated update mechanism and the AUR package is obviously only for Arch Linux. Also some niche linux distributions dont ship with all the dependencies needed for AppImages to work while on the other hand Flatpak guarantees that the software will run everywhere because it ships with every single dependency required by the program to run. Flatpak also provides a simple method for the end user to update the app by just running `flatpak update` in a terminal or using a GUI like KDE Discover or GNOME's software app (forgot what it was called).

**Describe the solution you'd like**

Add Grabber to [Flathub](https://flathub.org).

**Describe alternatives you've considered**

AppImage and AUR are great alternatives and the better ones when you want to save space. However the Linux community is slowly but surely gravitating towards Flatpak as the dominating software distribution system so having Grabber there would ensure that more users discover this wonderful program in a convenient and easy to use app store that is supported on every linux distribution.

**Additional context**

Flathub is a software distribution platform for Linux that provides Flatpak packages for hundreds of programs, games and emulators. The unique thing about Flatpaks is that they come with every dependency they need, which means that they can run on practically every single Linux distribution without the need to compile your software for every snowflake package format out there. Just a single Flatpak is enough for everyone to be able to use the application.

**Comment by Yumae** [comment]
> I have to admit I'm not familiar at all with flatpak.
> 
> The advantage you mention (self-contained) can already be found in AppImages, and while you mention they're not auto-updatable [they actually can be](https://docs.appimage.org/packaging-guide/optional/updates.html), I just didn't set it up for Grabber (but that's a good suggestion, [just implemented it](https://github.com/Bionus/imgbrd-grabber/commit/5bc13b018116a294ef0305eb6c119ad23156131f)), although I'm not sure how widespread the support is.
> 
> What are the necessary steps for me to provide a flatpak? I've read [this](https://docs.flatpak.org/en/latest/first-build.html) and other docs, but am unclear as to who is building what in the end. The repository/manifest seem to provide only building instructions? (also, the manifest reminds me of AUR a little)
> 
> Do I pretty much just have to write a manifest and open the PR on flathub's repository? What about binaries/updates?

Unfortunately i am not a developer myself so i don't have the answers but this page should have the information you need https://github.com/flathub/flathub/wiki/App-Submission

**Comment by Yumae** [comment]
I'm pretty sure that they don't have a problem with adult content considering https://flathub.org/apps/details/com.katawa_shoujo.KatawaShoujo and https://flathub.org/apps/details/io.github.hydrusnetwork.hydrus are there. The description for the Katawa Shoujo page says that it contains adult material and in the case of Hydrus it can be used to download from many sites with adult content like Grabber so it should be fine.

**Comment by Bionus** [comment]
https://github.com/flathub/flathub/pull/3741

**Comment by Yumae** [comment]
Thanks! I look forward to testing it.
