### ISSUE TITLE
Space as Separator?

### ISSUE THREAD

**Issue by younyokel** [Bionus/imgbrd-grabber#2843]
Hello, I couldn't find a way to use a comma and a spacebar for a `:separator=` as an option of `%character%` particulary, giving me `charactercharacter` output (`character+character` by default). I tried the quotes, but they didn't work. I may have missed something but if it's not implemented, I just let this be here.

**Comment by Bionus** [comment]
Hello, the escape character for special characters such as  the comma is `^`.
So you should be able to do `%character:separator=^, %` 😄

**Comment by younyokel** [comment]
Oh thanks!
