### ISSUE TITLE
Grabber Post-Filtering: Making Advanced Searches Possible Without Additional API Interfacing 

### ISSUE THREAD

**Issue by Yallo250** [Bionus/imgbrd-grabber#2847]
@Bionus First post here so thanks for imgbrd-grabber. It works great.

To be as concise as possible, I either 1: Don't understand how post-filtering is supposed to work or 2: Am suggesting change to it which would allow very specific search _without._ having to deal with complicated API stuff. I believe it's the latter.**

Currently, Grabber can only retrieve several tags at a time due to site-placed restrictions. However, it can retrieve all tags simultaneously. **Suggestion:** Allow advanced Boolean Logic, done locally, to filter 
tags. 

For example:
**Search for:** Cat
**Post-Filtering Tags:** (Fluffy AND **-**White) AND (FileType:.webm OR FileType:.mp4)
1. Retrieve all images and tags as usual for the tag "Cat"
2. Apply blacklist as usual; eliminate blacklisted images from the results/further filtering
3. Client computer locally filters image tags to display files with tags indicating a Video of Fluffy cats that are not White, without querying sites.

**I'm not sure how post-filtering works, my bad if I've misunderstood it and you can already do this. I'm taking a bit of a stab in the dark saying this, but it seems like the blacklist already works on a local basis? Would it be overly complicated to expand the blacklist function to support Boolean filters?

**Comment by Bionus** [comment]
Hello 👋 

I'm not sure about your exact use case but that's indeed what post-filtering does (filtering images "post" loading): first load the images using the search input, then remove the blacklist + all images not matching the post-filter.

It's documented [here](https://bionus.github.io/imgbrd-grabber/docs/search.html) and it _should_ support parenthesis, "&&" and "||" for complex filters, although I did not try it in a while. Have you tried using those instead of "AND" and "OR"?

**Comment by Yallo250** [comment]
I've only gotten post-filtering to work once or twice. To my memory, every time I try to use it, even if I type into the post-filter only 1 tag that I've verified has images in common with the primary search tags, the search results just come back empty. Absolutely nothing.

(I'm still tweaking my filename syntax, so I'm sure it's possible I'm misusing it.)

**Comment by Bionus** [comment]
Indeed, post-filters right now do not support parenthesis or anything, just basic tag or token filtering. Switching to bug report as it ought to be consistent with other conditionals.
