### ISSUE TITLE
Ability to disable the filter count

### ISSUE THREAD

**Issue by crickled** [Bionus/imgbrd-grabber#2853]
**Is your feature request related to a problem? Please describe**

Sometimes, you just don't want to know how many images you just filtered. Gelbooru does not describe this stat, and is better for it.

**Describe the solution you'd like**

Some sort of toggle in the settings that would disable all texts about how many images were filtered, or at least does not display the number of filtered images, whether this be per page or total downloaded.

**Describe alternatives you've considered**

I looked around the settings, and couldn't find anything like this.

**Comment by Bionus** [comment]
Are you talking about this?
![image](https://user-images.githubusercontent.com/882719/206854687-c72b1cb3-3753-474a-937f-75901317d16a.png)

Sorry to ask bluntly, but why does it matter to show it or not? 😅
Wouldn't hiding it make it more confusing, especially when _all images_ are filtered and it says "no results"?

**Comment by crickled** [comment]
Well, if you're asking if it'd be confusing or not, I'm just requesting if it'd be a toggle. I know that it would totally make troubleshooting much harder if that stat wasn't displayed, but if you're asking why I'm requesting a toggle, it's a little specific. Personally, I really hate to do a search on an artist and see like one third of their stuff get filtered from my blacklist. For me, knowing this kind of makes things harder for me. I filter the images I do for a reason, so seeing that they were there at all is a negative for me. Sometimes, you just really don't want to know. I know this is a fairly selfish request, but I at least hope you're able to kind of understand where I'm coming from when I ask about it.

**Comment by crickled** [comment]
Just wanted to note, checked this with 7.10.0. , and the count still appears after a download is completed. Otherwise, works great. Thanks!
