### ISSUE TITLE
Ex-Hentai Not Parsing Images

### ISSUE THREAD

**Issue by DiffPerson** [Bionus/imgbrd-grabber#2854]
**Bug description**

When selecting a set from the search page, no images are displayed.

**Steps to reproduce**

1. Select "ex-hentai.org" as source.
2. Hit enter on blank search.
3. Select any set displayed.
4. Error should be noticed (missing images).

**Expected behavior**

Images should appear when selecting image set.

**Context**

* main.log provided
* settings are default minus adding login information (uninstalled and reinstalled as a potential fix)
* no error message is displayed

**Screenshots**
Search Screen
![Capture1](https://user-images.githubusercontent.com/97133965/206867041-15e88923-1088-42c1-8292-4912221b60b8.JPG)
Image Set Screen
![Capture2](https://user-images.githubusercontent.com/97133965/206866857-c400d00c-e565-4f25-8f0a-1191fe555291.JPG)

**System information**

- OS: Windows 10
- Grabber version: 7.9.1

**Additional context**

None.

**Comment by Bionus** [comment]
Are you using the "large" display mode for images in gallery pages?

**Comment by Bionus** [comment]
I could produce with the "large" thumbnails for galleries and pushed a fix 👍
Hopefully that's the issue you were facing 😄
