### ISSUE TITLE
Zerochan.net non categorized tags (characters/copyright etc)

### ISSUE THREAD

**Issue by Silkye** [Bionus/imgbrd-grabber#2863]
**Bug description**

Zerochan tags aren't being parsed. Tried it while logged in and logged out

**Steps to reproduce**

1. Click on "sources".
2. Only enable "Zerochan" in the sources.
3. Click "ok".
4. Search anything.
5. Click on any of the images appearing on screen.
6. Check the tags.

**Expected behavior**

Parsed (coloured) tags that allows me to save images properly with filenames.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/10263543/main.log)
(Can't upload settings as a .ini file)
[settings - Copy.txt](https://github.com/Bionus/imgbrd-grabber/files/10263541/settings.-.Copy.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/86803417/208550136-10d2ff03-2bee-4cd2-a545-3838dfcb8de5.png)

**System information**

- OS: [W10 version 2009]
- Grabber version: [7.10.0]

**Additional context**

What it should look like
![image](https://user-images.githubusercontent.com/86803417/208550233-03ff268b-3575-492c-92cd-6b3d0840bec2.png)

**Comment by Bionus** [comment]
Indeed, it seems they changed the way they display image tags on their details page.
I'll push a fix ASAP.
