### ISSUE TITLE
restriction on viewing galleries e-hentai

### ISSUE THREAD

**Issue by aqpaqp** [Bionus/imgbrd-grabber#2865]
hello, tell me how to bypass the restriction e-hentai (This gallery has been flagged as Offensive For Everyone. Due to its content, it should not be viewed by anyone.) because of this, it does not open in the grabber
![1](https://user-images.githubusercontent.com/121206621/209035235-c9e7e42a-0302-4468-89a8-0e1ecb167ebe.JPG)
when you select the "Never Warn Me Again" option, the site creates cookie 
![2](https://user-images.githubusercontent.com/121206621/209035431-81811836-8100-4f8e-bf02-9d719b229b01.JPG)
I'm trying to add them to the Site options 
![3](https://user-images.githubusercontent.com/121206621/209035652-ee405bd6-39de-4872-a142-44951bd0344b.JPG)
but I can't get anything

example gallery "irotenya 1KO"

**Comment by Bionus** [comment]
> I'm trying to add them to the Site options

Why not just use `nw` in the name, and `1` in the value, since that's what's showing in your screenshot?
![image](https://user-images.githubusercontent.com/882719/210078043-4646f46e-601d-44ae-8630-01b89894cbfa.png)

From what I can see, it should work.

**Comment by aqpaqp** [comment]
I tried every combination I could think of
![1](https://user-images.githubusercontent.com/121206621/210126568-0f65c9c4-6cb7-4483-ab62-a18fa5e6afa1.JPG)
nothing works
