### ISSUE TITLE
Danbooru server is offline

### ISSUE THREAD

**Issue by devilbutterfly** [Bionus/imgbrd-grabber#2870]
**Bug description**

**Steps to reproduce**

1. Go to "new tab"
2. Click on '.sources'
3. Scroll down to 'danbooru.donmai.us'
4. search anything 

**Expected behavior**

Server is offline

**Comment by 09eragera09** [comment]
See #2826 for a temporary fix.

**Comment by snow9874** [comment]
It didn't work for me

**Comment by squiglybob13** [comment]
This issue is back. I tried the user-agent fix but no luck.

https://i.imgur.com/TfpS8OZ.png
