### ISSUE TITLE
Store all tags (AND source site information) to metadata of image as EXIF data in downloaded images?

### ISSUE THREAD

**Issue by teward** [Bionus/imgbrd-grabber#2875]
**Is your feature request related to a problem? Please describe**

I'd like to see a way to store tag data for a given image in its exif metadata. This makes it easier to index all tags for a *specific file* rather than having separate files *just* to store the tag sets per image, especially if we download/store by hash sums.

**Describe the solution you'd like**

For this section and example, I am going to use the following example set.  I have an image downloaded from Danbooru.  It's a relatively safe Genshin image, and for brevity sake has a subset of tags of `["blue_hair", "solo", "1girl"]`  The configured server URL is `danbooru.donmai.us`.

There are several things defined in the IPTC standards for Artwork (via IPTC Extension Schema under the XMP schema) and IPTC version 1.4 (which uses other formats as well incorporated into them) which work for tags and source data.

For tags, this would be a prime usage of the "Keywords" option - which per IPTC standard says to use Dublin Core namespace tag of Subject.  Subject is a list of strings.  It's defined in XMP spec for the tag as `dc:subject`.  Therefore, this list would be comprised in the example of individual string objects "blue_hair", "solo", and "1girl".

For image source, this gets a little trickier, but we *could* theoretically use the `photoshop:Source` metadata.  This would link to the actual image source URL before it's downloaded, so that we know where it was downloaded from.  That way, for the example, we'd use the Danbooru page link, which links to the direct page of the image on Danbooru.

This allows EXIF-capable tools to sort on existing tags.  Using `dc:subject` and `photoshop:Source` are tags that're already well known (Photoshop even recognizes `dc:subject` and keywords heh) for systems to look at.

This also allows someone to go into a specific image and use its metadata for the purpose it was intended for, rather than having to have extra files to hold that information or complex database setup for crossreferencing.

**Describe alternatives you've considered**

The only alternative available is specified here: https://github.com/Bionus/imgbrd-grabber/issues/2800 - and it requires using "external log files" of a sort to store the tag data in the list and store additional files.  While storing this is useful for post-processing programs, we may want to 

**Additional context**

This is being used as an alternative to #2800 - this also is potentially a separate handling approach for this that is more "image metadata compatible" and can be expanded upon for use in galleries or other album tools which can look at EXIF data.

**Comment by Bionus** [comment]
Hello 👋 

Did you check [this page](https://www.bionus.org/imgbrd-grabber/docs/metadata.html) about metadata?
It explains how to write to a file's metadata, using either the Windows Property System (only if you're on Windows) or Exiftool.

From my understanding, it should allow you to do what you want?

**Comment by teward** [comment]
> Hello 👋 
> 
> Did you check [this page](https://www.bionus.org/imgbrd-grabber/docs/metadata.html) about metadata?
> It explains how to write to a file's metadata, using either the Windows Property System (only if you're on Windows) or Exiftool.
> 
> From my understanding, it should allow you to do what you want?

This would do exactly what I'm after however some documentation is sparse :P

Do the docs contain a list of % delimited arguments that are compatible with this function?

**Comment by Bionus** [comment]
What do you mean? All tokens work with this, just like [in filenames](https://bionus.github.io/imgbrd-grabber/docs/filename.html).
