### ISSUE TITLE
include tag in the filename?

### ISSUE THREAD

**Issue by CEO1234567890** [Bionus/imgbrd-grabber#2877]
I want to be able to add a character to the file name, not to a new folder
For example, **%character%/%md5%.%ext%** would give something like **"54252452589624.jpg"** in a folder with the characters name
Instead, I want to be able to download a file named e.g. **"joe_55235252359.jpg".**

I haven't found any way to do this in the documentation

**Comment by NegusGit** [comment]
try replacing the "/" sign with space, the "/" sign indicates the directory you want the file to be placed. hope that helps

**Comment by CEO1234567890** [comment]
nah I tried removing it and using javascript syntax too, seems like it just doesnt work

**Comment by Bionus** [comment]
Are you sure you tried `%character%_%md5%.%ext%` as suggested above? Because it would work.
