### ISSUE TITLE
Batch download for ugoira format downloads only the first frame

### ISSUE THREAD

**Issue by bgilc** [Bionus/imgbrd-grabber#2881]
**Bug description**

Batch download for ugoira format downloads only the first frame. So single jpg file is downloaded.

**Steps to reproduce**

1. Search for some ugoira files on pixiv. This user for example: user:16274829
2. Use get this page/get all and then download selected/download all
3. Inspect the downloaded files

**Expected behavior**
All files should be downloaded as ZIP so I would have all frames and not only the first frame.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/10347315/main.log)

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/10347325/settings.txt)

**System information**

- OS: Windows 10 x64
- Grabber version: 7.10.0 x64

**Comment by Bionus** [comment]
Interesting. It happens only for batch downloads, but works well for downloads triggered from the viewer window.
