### ISSUE TITLE
Allow to set defaults for monitors in global settings

### ISSUE THREAD

**Issue by 09eragera09** [Bionus/imgbrd-grabber#2882]
**Is your feature request related to a problem? Please describe**

The monitoring settings menu is way too limited. And enabling tray options makes all monitors notify by default with users having to manually change that on a per monitor basis

**Describe the solution you'd like**

Allow users the ability to set their own defaults for monitors, including notification settings. 

**Describe alternatives you've considered**

Manually doing it by hand for every monitor....?

**Additional context**

**Comment by VeggieJay** [comment]
+1 here, I have a ton of monitors and it would be great to be able to set the default interval
