### ISSUE TITLE
A lot of red "X"

### ISSUE THREAD

**Issue by lilthigh** [Bionus/imgbrd-grabber#2887]
![2023-01-09 15_04_04-Window](https://user-images.githubusercontent.com/42845509/211308815-d573d007-1a5e-4880-b675-c6829eb942cb.png)

I don't have problems with network, no vpn or proxy, no blacklist, no folder already exist. but when I close download tab and re-download it, it randomly successfully saved, what the reason behind this random issue, and how to fix it.

**System information**

- OS: [e.g. Windows 10]
- Grabber version: [e.g. 7.10.0]

**Comment by Donny-Pandairaz** [comment]
This isn't an issue with Grabber. It's a problem with the site as various links, images, and content has broken links or suffer from weird server problems.
