### ISSUE TITLE
e621 self-uploads from artists not properly parsed

### ISSUE THREAD

**Issue by pikaflufftuft** [Bionus/imgbrd-grabber#2890]
When I click on the image to preview it in a larger resolution for the first time, I see the artist tag. But when the full-resolution image begins to load, it disappears. The artist tag is also not saved in the separate log file. There is no issue in saving the artist tag to the separate log file with other posts. 
I am using Grabber 7.10.1 (x64) on Windows 10 Home. Not running on a virtual machine.

I am browsing through e621.net.

I notice this usually occurs with posts with the 'conditional_dnp' tag.
See the following image

![image](https://user-images.githubusercontent.com/122342122/211478982-3a455510-7ac0-4c55-a1d3-bf39c126f25c.png)

These are the tags when I first open the image:
![image](https://user-images.githubusercontent.com/122342122/211476922-f3330a90-3b55-4d2d-bcd1-ed7ce49572f5.png)

The artist tag disappears a few seconds later:
![image](https://user-images.githubusercontent.com/122342122/211479929-f6d1dcca-95a7-4df9-98ec-6e52870dc347.png)

main.log attached:
[main.log](https://github.com/Bionus/imgbrd-grabber/files/10379802/main.log)

settings.ini (renamed file ext with .txt because github doesn't support .ini)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/10379850/settings.txt)

**Comment by Bionus** [comment]
Indeed, seems to come from this new checkmark here:
![image](https://user-images.githubusercontent.com/882719/211621663-89e2371a-de62-4c99-8548-e9d9f0410364.png)

Pushing a fix now.
