### ISSUE TITLE
[Andoid] Text inside update popup should be wrapped

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2896]
**Bug description**

Text inside update popup isn't wrapped, so it is not suitable for reading.

**Steps to reproduce**

1. Install older version of Grabber (i.e. 7.10.0)
2. Check for updates

**Expected behavior**

Text inside update popup is wrapped.

**Context**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/212492676-64e85dd8-7d92-4f1f-8062-c847df48d136.png)

**System information**

- OS: Android 12
- Grabber version: 7.10.0 (must be the same in 7.10.1)

**Additional context**

N/A

**Comment by Bionus** [comment]
Just pushed a fix, thanks!

![image](https://user-images.githubusercontent.com/882719/212499480-318f3be2-7f35-477f-b47d-5d7d05b6dd32.png)
