### ISSUE TITLE
nhentai not working due to cloudflare wall

### ISSUE THREAD

**Issue by DemoTou** [Bionus/imgbrd-grabber#2901]
nhentai does not load.
In Browser the website works normal and adding cookies to Grabber also does not help.
Also tried a clean reinstall, also did not help.
The following message shows up in the logs when trying to search nhentai:
![p6XDLD6](https://user-images.githubusercontent.com/123521351/214454837-96c4a4fd-6288-4584-ad42-e238fc24e11e.png)

**Comment by DemoTou** [comment]
It now gives an actual error message
![iVYTztt](https://user-images.githubusercontent.com/123521351/216225653-e837cda0-f012-4c48-8498-30bff89b1872.png)
![GNTtFKI](https://user-images.githubusercontent.com/123521351/216225660-a678f69f-9d97-4311-80ef-efcf9360f1f5.png)

**Comment by DemoTou** [comment]
works again when adding cf_clearance cookie and user-agent.

**Comment by VeggieJay** [comment]
> works again when adding cf_clearance cookie and user-agent.

just did this too, this is the fix

**Comment by kagami777** [comment]
> > works again when adding cf_clearance cookie and user-agent.
> 
> just did this too, this is the fix
> 
> edit: according to somebody else, this worked for them with the user agent from firefox but not from chrome

What am I supposed to be putting for the user agent? Because when I copy paste what I'm told is the user agent: Mozilla/5.0 (Windows NT x.y; rv:10.0) Gecko/20100101 Firefox/10.0
It doesnt do anything to fix the NHentai - No results, Possible reasons: server offline message and when I go back in to the cookies to check on it the value for the cf_clearance cookie is cut off as: Mozilla/5.0 (Windows NT x.y

**Comment by VeggieJay** [comment]
> > > works again when adding cf_clearance cookie and user-agent.
> > 
> > 
> > just did this too, this is the fix
> > edit: according to somebody else, this worked for them with the user agent from firefox but not from chrome
> 
> What am I supposed to be putting for the user agent? Because when I copy paste what I'm told is the user agent: Mozilla/5.0 (Windows NT x.y; rv:10.0) Gecko/20100101 Firefox/10.0 It doesnt do anything to fix the NHentai - No results, Possible reasons: server offline message and when I go back in to the cookies to check on it the value for the cf_clearance cookie is cut off as: Mozilla/5.0 (Windows NT x.y

cf_clearance cookie goes under cookies
user-agent goes under headers

**Comment by kagami777** [comment]
> 
> cf_clearance cookie goes under cookies user-agent goes under headers

so what value should go beside cf_clearance?

**Comment by VeggieJay** [comment]
the cf_clearance cookie value

do you know how to find cookies (f12)

**Comment by kagami777** [comment]
> the cf_clearance cookie value do you know how to find cookies (f12)

No...
