### ISSUE TITLE
Wrong latest version on the site

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2902]
**Bug description**

The site https://www.bionus.org/imgbrd-grabber/ shows version v7.10.0, while the latest is 7.10.1

**Steps to reproduce**

1. Open https://www.bionus.org/imgbrd-grabber/

**Expected behavior**

"Free download - v7.10.1"

**Context**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/215052007-2cd260e1-a594-4009-b653-6c9cf7333c59.png)

**System information**

N/A

**Additional context**

N/A

**Comment by Bionus** [comment]
Indeed, the issue is that the website is updated on merge but not when I publish the release. I just refreshed it, thanks 👍
