### ISSUE TITLE
Plus' window is hiding on pressing Cancel while selecting image

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2903]
**Bug description**

Plus' window is hiding on pressing Cancel while selecting image. 

**Steps to reproduce**

1. Start Grabber
2. Click on 'Plus' button
3. Click on 'Image' button
4. Click on 'Cancel' without selecting any image

**Expected behavior**

Plus' window should be kept shown.

**Context**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/215053139-3b485e0a-9079-4024-b5aa-8123bfd859e8.png)

**System information**

- OS: Windows 10
- Grabber version: v7.10.1

**Additional context**

N/A

**Comment by Bionus** [comment]
Good catch 👍 
This window was created and didn't get updated for a long time, I guess an update is well overdue for it.
