### ISSUE TITLE
Monitor "Copy to downloads" adds based on default numbering order instead of current sorting

### ISSUE THREAD

**Issue by VeggieJay** [Bionus/imgbrd-grabber#2921]
**Bug description**

If you sort monitor columns to something besides their default order and right click -> "Copy to downloads", it will add the monitor that would normally be in that # slot when you "reset sorting" instead of the monitor that you actually selected.

**Steps to reproduce**

1. Go to Monitors
2. Sort with any column, Search/Source/Interval etc so that monitor 1 is no longer in the first slot
3. Right click monitor in the first slot -> "Copy to downloads"
4. Go to Downloads, the added downloads should be monitor 1 instead of the item that you actually selected

**Expected behavior**

The item that you selected should be added to Downloads

**System information**

- OS: Windows 10
- Grabber version: Nightly eff25a0d

**Comment by Bionus** [comment]
Indeed, I can reproduce that, just pushed a fix. Thanks for the heads-up 👍
