### ISSUE TITLE
Not all images downloading

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#293]
**What steps will reproduce the problem?**

1. Search a tag that has a lot of pictures, somewhere over 200
2. Click Download all
3. download them

**What is the expected output? What do you see instead?**

In my search, there were about 300 images, so you would expect it to download 
about 300, but it only downloads 150

**What version of the product are you using? On what operating system?**

Windows version 3.4.1, on Windows XP

> Original issue reported on code.google.com by `SegaRetr...@gmail.com` on 8 Apr 2014 at 12:59

**Comment by Bionus** [comment]
Without more details, especially about the source you were using, I cannot investigate. I'll reopen it if you give me more details, but I think the more recent versions of the software must have fixed this issue.
