### ISSUE TITLE
Group/Lock the Monitors tab with Favorites/Downloads/Log at the top of the tab-selection dropdown menu

### ISSUE THREAD

**Issue by VeggieJay** [Bionus/imgbrd-grabber#2930]
**Is your feature request related to a problem? Please describe**

It would make it a bit easier to find the monitors tab quickly when many tabs are open

**Describe the solution you'd like**

Group the monitors tab with the other 3 main tabs in the selection dropdown menu so that it's always easy to access

**Describe alternatives you've considered**

Don't know of any aIternatives for this particular change but it's not critical

**Additional context**

![Untitled](https://user-images.githubusercontent.com/52065198/222982694-f8517d9c-4e4c-4f6e-863b-262acfb1921b.png)

**Comment by Bionus** [comment]
Makes sense, it should have been there in the first place anyway 😄
