### ISSUE TITLE
Are the OAuth2 credentials built into Grabber correct? I can't access twitter api with built in OAuth2 credentials

### ISSUE THREAD

**Issue by nikoharo** [Bionus/imgbrd-grabber#2941]
I want to use them to develop some small programs similar to Grabber

**Comment by nikoharo** [comment]
import tweepy

consumer_key = "3nVuSoBZnx6U4vzUxf5w"
consumer_secret = "Bcs59EFbbsdF6Sl9Ng71smgStWEGwXXKSjYvPVt7qys"
auth = tweepy.AppAuthHandler(consumer_key, consumer_secret)

api = tweepy.API(auth)

try:
    user = api.verify_credentials()
    print(f"Authenticated as {user.name}")
    search_results = api.search(q="python", lang="en", count=10)
    for result in search_results:
        print(result.text)
except AttributeError:
    print(f"Error: {e}")

**Comment by nikoharo** [comment]
I used Grabber's built-in OAuth2 credentials to access the twitter api was denied
![213123](https://user-images.githubusercontent.com/96216203/227767340-7632f8f3-91ab-40bf-9ed9-00bd70917746.png)

**Comment by nikoharo** [comment]
@Bionus

**Comment by Bionus** [comment]
Those OAuth credentials are Twitter for Android ones I got from [here](https://gist.github.com/KohnoseLami/580d0f2d7f1784e9352649260d921df9).
I don't think they still work though, I believe they've been broken for a while.

You should use your own, but AFAIK they stopped applications.
