### ISSUE TITLE
[Android] 'Share image' button doesn't work

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2943]
**Bug description**

Pressing on 'Share image' button doesn't give any reaction.

**Steps to reproduce**

1. Search for something
2. Open any image
3. Tap on 'Share' button

**Expected behavior**

Some kind of a dialog with the share options.

**Context**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/229484969-6be3ffbc-60f1-4a15-99db-75ef5a42ac1d.png)

**System information**

- OS: Android 11
- Grabber version: 7.10.1 as well as latest nightly build from [here](https://github.com/Bionus/imgbrd-grabber/releases/nightly)

**Additional context**

Afaik this button worked in some older releases.

**Comment by Bionus** [comment]
Interesting, it indeed used to work so I'm not sure what's up with that. Good catch 👍
