### ISSUE TITLE
Request/Question: Set the log filename same as the image filename

### ISSUE THREAD

**Issue by micky2be** [Bionus/imgbrd-grabber#2946]
**Is your feature request related to a problem? Please describe**
- Fist problem
Partially my fault on the follow.
I'm using a filename such as `%artist%/%copyright%-%character%(%num:length=2%).%ext%` for my images.
But when images have different extension the `num` value will be updated differently than the log file which as a fixed extension.
Aka `%artist%/%copyright%-%character%(%num:length=2%).txt`

- Second problem
I just want to avoid changing filename format in two different places when you simply want the same.

**Describe the solution you'd like**
Create a new token such as `saved_as` to be used in the log filename template.

**Alternative**
Change the logic of `%num%` to not include the file extension

**Comment by micky2be** [comment]
Finally found the option within `Location type`.
Might need some documentation about that ;)

**Comment by micky2be** [comment]
The extension is still an issue IMHO

**Comment by Bionus** [comment]
Why not simply use the "suffix" setting for the TXT file?
Then it would automatically re-use the image's filename and append whatever suffix you want to it, in your case `.txt`.
