### ISSUE TITLE
Feature Request - A list of files/links already downloaded to 'tag' and to check future downloads against

### ISSUE THREAD

**Issue by dadadies** [Bionus/imgbrd-grabber#2949]
So i am batch downloading and with some of the files I end up deleting them after I confirm delete or not. The things is ill do other batches and it might download the same files again, apparently if i have deleted the file. So the idea is to have a list of files/links I can check my downloads against to see if I have already downloaded, or if they exist, or maybe the ability to tag them as 'do not download', and so on. This is a good use for my case but it might be useful for other cases and just having this additional feature would be really nice. Thank you. I had another 'issue' but i forgot what it was.

**Comment by Bionus** [comment]
Hello, have you tried enabling the "keep deleted files in MD5" list setting in the options?
Grabber does keep a list of all downloaded images internally, but by default will check if the file still exists on disk before deciding not to re-download it. By enabling this setting, the file will be skipped even if it was deleted or moved.

**Comment by dadadies** [comment]
That sounds perfect it give it a go.

**Comment by dadadies** [comment]
Thank you it worked perfectly it seems. I have too many files to confirm exactly but its skipping now. My internet connection is Psiphon and it is horrible so i get disconnection a lot so this helps whenever i need to restart the downloads. Thank you for your work. I wish i could thank you more.

**Comment by Bionus** [comment]
Glad to hear it worked! 🙂
Closing as resolved then.
