### ISSUE TITLE
Whitelist version of "Removed Tags" for filename

### ISSUE THREAD

**Issue by scrumpyman** [Bionus/imgbrd-grabber#2953]
**Is your feature request related to a problem? Please describe**

There are only a few dozen tags I want to include in filenames, but if using %all% they will probably be cut off, and trying to blacklist all tags except those few is ridiculous.

**Describe the solution you'd like**

Whitelist version of Removed Tags for filename.

**Describe alternatives you've considered**

Javascript naming, seems pretty useless.

**Additional context**

I had also added this feature for myself in the old DanbooruDownloader program back in 2015 or so, I wonder why it's again a blacklist functionality for filename tag removal. I don't see much use for a blacklist when there are so many possible tags and limited filename length.

**Comment by Bionus** [comment]
You can use custom tokens, which are made exactly for that. Just put all the tags you want in that token, and when using it only the intersection of the custom token's tags and the image's tags will be used.
