### ISSUE TITLE
[Question] Monitor to check if images actually downloaded

### ISSUE THREAD

**Issue by gotr3k** [Bionus/imgbrd-grabber#2954]
Was playing around with the monitor option and noticed that if internet connection drops while the monitor is running it will try to download from artist, fail and mark as finished. After internet returned and monitor started downloading again it only downloaded new images after the period of the last check even though last time it didn't download anything since there was no connection. Is there a way to enable checking for such cases? Like for example there is a md5s.sqlite already there so the program can get imagelist for a monitored tag, check it against the md5s.sqlite and then download everything that's not in the database.
Might also be the case that there is already a solution for this but I didn't manage to find it.

**Comment by Bionus** [comment]
This sounds like a bug, as a monitor should also check images from a previous run if it failed, and only update the "success datetime" on actual success.

Do you notice the same behavior on the nightly version? This is an issue I noticed happen on 7.10.1 but should be fixed in nightly.

**Comment by gotr3k** [comment]
> This sounds like a bug, as a monitor should also check images from a previous run if it failed, and only update the "success datetime" on actual success.
> 
> Do you notice the same behavior on the nightly version? This is an issue I noticed happen on 7.10.1 but should be fixed in nightly.

Will test it out as soon as possible. And yes, was using the v7.10.1 so that's probably been fixed in the nightly
