### ISSUE TITLE
Request/Question: Or conditional in the search bar

### ISSUE THREAD

**Issue by ArnauLeinster** [Bionus/imgbrd-grabber#2955]
I wish search for either of 2 tags, in other words make an or statement in the search itself, if this is has been implemented, how is it done? If it is not implemented, how hard would it be to implement?

**Comment by Bionus** [comment]
This depends on the source. Whatever is put in the search bar is passed as-is to the source, so some support it, some don't. On some, you can do `tag1 OR tag2`, on others `~tag1 ~tag2`.

In any case, it's not a feature on Grabber's side but rather on the source you're using :)
