### ISSUE TITLE
How to fetch  Art from a deviantArt artist, really I need your help kek

### ISSUE THREAD

**Issue by NegusGit** [Bionus/imgbrd-grabber#2957]
What are the search tokens I'm able to use in DeviantArt.
I'm trying to search a specific artist in grabber w/ DeviantArt as the source to download their art.
artist name is "Akamoriart".
any help please

**Comment by Bionus** [comment]
Grabber uses either the RSS feed or the search field from DeviantArt to perform searches, so you would do it the same way you do there. For RSS the prefix is `by:`. Like `by:username`.
