### ISSUE TITLE
Pixiv

### ISSUE THREAD

**Issue by tevale1216** [Bionus/imgbrd-grabber#2960]
The pixiv source doesn't seem to work.

When I do a search in pixiv it does not give me results.

**Comment by Bionus** [comment]
1. Did you try the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/nightly)?
2. Are you logged in to Pixiv in Grabber? (be it by manually entering the tokens or using the PKCE login mode)
3. Otherwise, can you show your logs? They must have warnings/errors about the login issue.

**Comment by tevale1216** [comment]
1.- If the poor thing and has the same problem.
2.- Yes, I tried but the page just stays blank and in grabber it just says "connecting".
3.-
![Sin título](https://github.com/Bionus/imgbrd-grabber/assets/83770259/6a24f7d2-bcc5-412c-a429-1a68329375e4)
