### ISSUE TITLE
Nightly wont start, qscintilla2_qt5.dll missing

### ISSUE THREAD

**Issue by nosdregamon** [Bionus/imgbrd-grabber#2961]
**Bug description**

I downloaded the latest portable windows nightly .zip form
https://github.com/Bionus/imgbrd-grabber/releases/nightly
and starting it, I'm greeted with the message that it can't  start, because qscintilla2_qt5.dll  is missing.

**Steps to reproduce**
0. Download Grabber_nightly_x64.zip, or Grabber_nightly_x86.zip
1. Extract
3. Click on 'Grabber.exe'
4. See the error

**Screenshots**

![image](https://github.com/Bionus/imgbrd-grabber/assets/1910987/98725e67-57ed-4d99-96d5-6f8f9471606b)

**System information**

- OS: Windows 10
- Grabber version: Nightly, April 2023

Can someone point me in the right direction to install the missing library?

**Comment by Bionus** [comment]
Interesting that it happens for nightly but not for the normal release, although neither of them have it 🤔
