### ISSUE TITLE
What symbols need to be added before and after the blacklist label?

### ISSUE THREAD

**Issue by sai4x4** [Bionus/imgbrd-grabber#2969]
Do I need to add any symbols before and after the blacklist label? For example: ai_generated, what symbols need to be added before and after? What symbols need to be used between the two blacklists?
I typed in the tag directly, but I couldn't find it in the search.

**Comment by Bionus** [comment]
You just need to write the tag as-in in the blacklist for it to be blacklisted.
One tag per line. If you put multiple tags on a single line, both will need to be present in the image for it to be considered as blacklisted.

You have more information here:
https://www.bionus.org/imgbrd-grabber/docs/search.html#blacklist
