### ISSUE TITLE
Ability to manually run one or more selected monitors

### ISSUE THREAD

**Issue by VeggieJay** [Bionus/imgbrd-grabber#2971]
**Is your feature request related to a problem? Please describe**

With a very large list of monitors, it might be nice to be able to manually select ones to run rather than just saying "Start" and having it go through the whole list

**Describe the solution you'd like**

Ability to select multiple monitors (ctrl+click), right click and "Run now" or something to that effect. Possibly another "Run Selected Monitors" button at the bottom if that is something that would be good for usability

**Describe alternatives you've considered**

This wouldn't be an issue if I didn't have so many monitors

**Comment by Bionus** [comment]
Good idea and pretty easy to implement. I'm not a big fan of adding yet another button, so I'll just add a right click action for now as you suggested 👍
