### ISSUE TITLE
Unable to search using kemono.party source

### ISSUE THREAD

**Issue by ahykono** [Bionus/imgbrd-grabber#2977]
**Bug description**

Unable to search using kemono.party source, it returns no result while on the website it works just fine (searching for posts)

**Steps to reproduce**

Simply start the application and try to search something on kemono.party

**Files**

My log file, [main.log](https://github.com/Bionus/imgbrd-grabber/files/11668498/main.log)
As for settings, [settings.txt](https://github.com/Bionus/imgbrd-grabber/files/11668483/settings.txt) • (default from installation)

**Screenshots**

![image](https://github.com/Bionus/imgbrd-grabber/assets/74881934/9f76b96e-2052-496b-bcdb-ce15970da790)

**System information**

- Occurs on Windows 11 
- Grabber version is 7.11.0 (Latest)

**Comment by Morpheen** [comment]
Same issue here
