### ISSUE TITLE
Preloading images

### ISSUE THREAD

**Issue by ok123188712222312** [Bionus/imgbrd-grabber#2979]
My only feature request is to make it preload images before i go to them for example i clicked on a tag and i start going to the next images by the keys i have to wait for about 1 second for it to load (bad internet) so basically just make a option to preload the images before clicking on them. and if thats not possible its okay

**Comment by Bionus** [comment]
Hello 👋 

There's already a feature to pre-load the next/previous images in the preview window.
It can be found in Settings > Interface > Image window > Preloading 👍
