### ISSUE TITLE
[Meta: Devel] Developing additional Sources without Full Recompile?

### ISSUE THREAD

**Issue by teward** [Bionus/imgbrd-grabber#2982]
Is there a way to add extra sources and handling for sources without having to go through a recompile of the entire software?  Trying to make a few modifications to sources that are *not* in Imgbrd-grabber and want to allow those sources to be tested *without* recompiling every time I make a revision.

I see "remote source registries" but am not sure if that's a solution or if that's not the proper approach to this type of approach

**Comment by Bionus** [comment]
You don't need to compile Grabber to edit or create sources, they're JS files, as described here:
* https://www.bionus.org/imgbrd-grabber/docs/sites/source.html
* https://www.bionus.org/imgbrd-grabber/docs/sites/source-example.html

The official ones in the repository use TypeScript so you need to compile the sources themselves, but you don't need to compile Grabber / C++ for that. And if you're editing your local sources, they're already compiled to JavaScript anyway.

**Comment by teward** [comment]
Check, that answers the question so far, thanks!
