### ISSUE TITLE
Grabber not installing on my pixel 7 pro device

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#2983]
When I try to install it it give me an error

![image](https://github.com/Bionus/imgbrd-grabber/assets/127690613/b89fe50e-a681-41b6-944d-fd76b5dfb889)

**System information**

- OS: [Google Pixel 7 Pro Android 13]
- Grabber version: 7.11.0

**Comment by Bionus** [comment]
What CPU does your smartphone have? Is it not an ARM one?

**Comment by Ex-ray1337** [comment]
> What CPU does your smartphone have? Is it not an ARM one?

It's an arm base phone
![Screenshot_20230617-223304.png](https://github.com/Bionus/imgbrd-grabber/assets/127690613/38728b6a-0280-435f-9b4b-f56250c39f68)

**Comment by Ex-ray1337** [comment]
Will it be fix in the next update just wondering?

**Comment by Akihlia** [comment]
Hi, I also have this issue on my Pixel 7. I heard that the Pixel 7 phones can only install 64-bits apps. @Bionus Is the release of the app a 32-bit build ?

**Comment by Bionus** [comment]
Yes the APK is currently a 32-bit one.
The next major version and the nightly after the next minor version will support both, however.

**Comment by Ex-ray1337** [comment]
> Yes the APK is currently a 32-bit one.
> The next major version and the nightly after the next minor version will support both, however.

Alright
