### ISSUE TITLE
Add support for image post-processing

### ISSUE THREAD

**Issue by gotr3k** [Bionus/imgbrd-grabber#2984]
**Describe the solution you'd like**

Add option to execute command line operations on images after downloading in the GUI version. For example if I want all images to be in .webp format and tagged then after downloading a custom command would be called that converts it to desired filetype then applies everything else like tagging. Not necessarily just for converting purposes but general post processing command calling would be useful. 

That being said another suggestion would be to add option in the settings to automatically convert images to a certain filetype.

**Describe alternatives you've considered**

Been managing to do a workaround using CLI version and custom script which does image post-processing then converts them to desired filetype but that's far from an elegant solution version.

**Comment by Bionus** [comment]
Could you clarify wow this would be different from the existing "Commands" system, which allows to run any command/executable before/after an image is downloaded?

![image](https://github.com/Bionus/imgbrd-grabber/assets/882719/561b989e-5391-4d9a-a53e-34e6a866de30)

**Comment by gotr3k** [comment]
> Could you clarify wow this would be different from the existing "Commands" system, which allows to run any command/executable before/after an image is downloaded?

Really sorry, no idea how i didn't see this option. This is exactly what i wanted, though i do have some questions. If i were to convert image to a different format using this method would it be saved as such in the md5s.sqlite or would just the original hash/path of the image?

**Comment by Bionus** [comment]
Only the original path would be saved to the database. Although if you set the "keep deleted images in MD5 list" setting it wouldn't really matter.
