### ISSUE TITLE
After hibernation pixiv search fails until app restart

### ISSUE THREAD

**Issue by bgilc** [Bionus/imgbrd-grabber#2985]
**Bug description**
After hibernation pixiv search fails until app restart.

**Steps to reproduce**

1. Start Grabber.
2. Search pixiv, example: user:16274829
3. Hibernate computer for the night. Wake it up from hibernation during next day.
4. Grabber should still be running. Open the the previously open tab with pixiv search. Try the search again.
5. Restart the app try that pixiv search again.

**Expected behavior**
I'm guessing a token becomes invalid due to time and lack of activity. Since this isn't permanently broken and restart fixes it I would suggest changing app logic to detect the situation and silently refresh the token or whatever is causing the issue.

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/11792980/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/11792986/settings.txt)

**System information**

- OS: Windows 10 x64 polish locale
- Grabber version: 7.11.0 x64

**Comment by sstabeler** [comment]
As far as I am aware, it's more that periodically the token becomes invalid pretty much no matter what- fortunately, you don't actually need to restart Grabber to get the search to work, you just need to test the login using the "OAuth2 (Refresh Token)" option in the dropdown, not Oauth2(PKCE) and it will refresh the token. It's what the option is there for.

**Comment by bgilc** [comment]
From the user perspective it doesn’t really matter. User needs to do a extra step that should be handled by the app transparently. It’s bad user experience. Not app breaking but still doesn’t feel right.

**Comment by Bionus** [comment]
The issue is more than the hibernation breaks Qt's timers, because the program is already set to automatically refresh tokens before expiration. Grabber should detect expired tokens before usage as well and directly refresh them.

**Comment by bgilc** [comment]
With 7.11.2 there is still problems with this. This time even multiple hours of hibernation wasn't even needed. I did a pixiv search, left grabber running. Repeated same search after like 1-2h and first attempt failed, second one was successful.

[18:13:33.191][Error] [www.pixiv.net][Json] Loading error: Error transferring https://app-api.pixiv.net/v1/user/bookmarks/illust?offset=0&filter=for_ios&image_sizes=small,medium,large&user_id=3478401&restrict=public - server replied: Bad Request (302)
[18:13:33.192][Warning] [www.pixiv.net] No valid source of the site returned result.
[18:13:33.370][Warning] [Qt][default] QObject::connect: No such signal OAuth2Login::basicRefresh()
[18:13:36.062][Info] Loading results...
