### ISSUE TITLE
Android: Infinite scroll toggle setting ignored

### ISSUE THREAD

**Issue by voodoochiledev** [Bionus/imgbrd-grabber#2987]
**Bug description**

Infinite scroll on Android stays enabled regardless of changing toggle in settings

**Steps to reproduce**

1. Go to 'Settings -> Interface'
2. Uncheck box 'Infinite scroll'
3. Go to search results and continue scrolling down
4. Scrolling continues loading under "infinite scroll", and see inconsistent loading behavior when switching pages

**Expected behavior**

Once the first page reaches the end, it should stop loading further pages until pressing the button to advance pages

**Context**

* No mention in logs when this toggle is changed in settings
* Additionally see the other (possibly related) issues in logs that have been noted, such as issue #2978
* The page switch buttons do function, but the thumbnails displayed seem incorrect and out of order due to trying to frontload everything into the first page

**System information**

- OS: Android 13
- Device: Pixel 4a 5g
- Grabber version: 7.11.0

**Comment by Bionus** [comment]
Indeed I could reproduce and pushed a fix, thanks for the heads-up 👍 

> the thumbnails displayed seem incorrect and out of order due to trying to frontload everything into the first page

Not quite sure what you mean by this though?
