### ISSUE TITLE
Rule34.us pagination issues

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2990]
**Bug description**

There area odd pagination issues with rule34.us based searches. For example:

1. On the first page, the last page shows 0. 
2. On second page it starts to show the last page number.
3. On the second last page, the last page number changes to current page - 1. Thus last page becomes inaccessible.
4. But if you use the last page button instead of going to second last page, it does go to the last page and it does have content, not in the second last page.

**System information**

- OS: Windows 10
- Grabber version: 7.11.0

**Comment by Bionus** [comment]
Indeed, it would seem they started using a `<b>` tag instead of links for the "current page", leading to some parsing issue.

**Comment by amir32** [comment]
Pagination issues can be quite frustrating when navigating websites. It's essential to have smooth and efficient pagination for a better user experience. Speaking of which, if you're into online tools and calculators, you might find [fusioncalculator.com](https://fusioncalculator.com/) interesting. It's a fun Pokémon Fusion Calculator that allows you to create unique Pokémon combinations.

While it may not directly address the topic of this post, improving user experience and website functionality is something we all strive for in our own ways. Feel free to check it out if you're looking for something engaging to do online!
