### ISSUE TITLE
Why is Qt5NetworkAuth used?

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [Bionus/imgbrd-grabber#2991]
...i tried to build/backport grabber...
Why is Qt5NetworkAuth / OAuth  used? Can't it be simple disabled?
Can't you tell when was this module first appeared? Qt 5.10?

**Comment by Bionus** [comment]
AFAIK it was introduced in 5.8, and it's required in order for the OAuth flows to work (used for example by Pixiv).
