### ISSUE TITLE
Windows scaling causes crash when clicking on an image

### ISSUE THREAD

**Issue by LewisStewartOG** [Bionus/imgbrd-grabber#3006]
Windows scaling causes crash
-Fresh Install Latest 64 exe
-Windows 10, Scaling set to 150%, 1920x1080 resolution 
open grabber > click on any image causes grabber to crash
-Lowering scaling to 100% or using lower res fixes the issue
-other parts ui is also unusable options specifically goes infinitely off screen.

Its a minor issue. my problem is my screen needs to be at 150% or at least 125% scale otherwise everything is unbearably small. Figure id tell you anyways.

**Comment by Bionus** [comment]
Interesting.

Note that it does **not** happen in 1440p, even in 200% scaling. I had to test on a 1080p monitor, and it indeed crashes 🤔
