### ISSUE TITLE
Can't download samples from Danbooru anymore

### ISSUE THREAD

**Issue by Hatrask** [Bionus/imgbrd-grabber#3007]
**Bug description**

Pretty much what the title says.

Edit 2023-07-16: Just tested version 7.10.1 and it still works fine there.

**Steps to reproduce**

1. Go to Options
2. Uncheck 'Download original images'
3. Fetch something from Danbooru

**Expected behavior**

The expected behavior would be to get the image that is displayed when you open a post, usually a downscale of whatever the original image uploaded was. Their filename also has a '__sample' string right before the md5 hash.

**System information**

- OS: Windows 10
- Grabber version: 7.11.1 x64

**Comment by Bionus** [comment]
Indeed, there seem to be an issue where it always loads the full image even when it's supposed to load samples. I'll push a fix soon.
