### ISSUE TITLE
Grabber saving files without my permission

### ISSUE THREAD

**Issue by RobynNyx** [Bionus/imgbrd-grabber#3008]
**Bug description**

Grabber is saving images by itself. 

**Steps to reproduce**

1. Open any image
2. Save image, or don't
3. Scroll through the images, open other tags, just use the program as normal
4. At some point, Grabber is now saving files at 'random'. There is too many from too many potential tags for me to check if there is an order/system to it's behavior. 
6. To stop it from saving files, which it will just keep doing, you close grabber. 

Otherwise grabber will just keep saving images/gifs/files, just anything and everything. I've had to delete a 5gig folder after using the program once. 

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/12063553/main.log)

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/12063573/settings.txt)

I couldn't upload a .ini file so I changed it to .txt

**Screenshots**

![image](https://github.com/Bionus/imgbrd-grabber/assets/139678238/9344bcd5-5d33-49d0-ab08-9082e646aeae)

Out of the 161 images, I only downloaded 5. 

**System information**

- OS: Windows 10 Pro, build 19045.3208 x64-based processor
- Grabber version: 7.11.1

Thanks in advance, program is awesome otherwise.

**Comment by Bionus** [comment]
Weird, I've never heard of this kind of behavior. I checked your settings and you don't have auto-download enabled, nor a whitelist.
Could it be that you have a monitor running?

**Comment by RobynNyx** [comment]
Could you explain what a monitor is? All I know a monitor is as a screen.

**Comment by Bionus** [comment]
I'm talking about the monitors tab:
![image](https://github.com/Bionus/imgbrd-grabber/assets/882719/42a237c1-6a42-4da9-9a09-8bce93738931)

**Comment by RobynNyx** [comment]
Yeah, I have that one open. Am I not suppose to?

**Comment by Bionus** [comment]
Well if you have 17 monitors set to auto-download new images when they are posted, it's not surprising that you have images downloaded in the background 😄

**Comment by RobynNyx** [comment]
Well whoops haha. Thanks for the help, sorry that it was entirely my fault, though aces for figuring it out so quickly
