### ISSUE TITLE
"This video has been restricted" message on rule34.us

### ISSUE THREAD

**Issue by EkeeIsBae** [Bionus/imgbrd-grabber#3035]
**Bug description**

Playing a video on rule34.us source shows "This video has been restricted. Streaming video from Cloudflare's basic service is a violation of the Terms of Service. please visit cfl.re/tos to learn more." The problem doesn't exist on the actual website.

**Steps to reproduce**

1. Go to sources and selected rule34.us a source and search for videos
2. Click on ok or search
3. Scroll down to any video
4. See error "This video has been restricted..."

**Expected behavior**
Assuming that I should be able to see the video since it works on the actual website.
Expected to click on the video and for the video to begin to play

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/12484139/main.log)

**System information**

- OS: Windows 10
- Grabber version: 7.11.2 (x64)

**Additional context**
The links when plugged directly back into a browser show the restricted error, but if you change the img2 part at the beginning it plays the video like normal. So I'm guessing it's something with that.

Add any other context about the bug report here.

**Comment by Bionus** [comment]
Indeed, seems to be caused by using the `img2` sub-domain instead of the `video` one 🤔

**Comment by weeaboo92** [comment]
how can i fix this :(
