### ISSUE TITLE
Image size "max height" doesn't seem to check for height, but for width

### ISSUE THREAD

**Issue by HavelockVimes** [Bionus/imgbrd-grabber#3038]
Setting the "max height" option to any value will resize images as if I'd set the "max width" option instead. There seems to be no current way to resize based on height, because of this bug.

The option I mean is in tools - > options - > save - > image size - > check the box to the left of "max height", and set it to 512

That should resize images to be of a max height of 512, but instead images had varied heights and exactly 512 width.

(Incidentally, the width option is working as intended; checking either box resizes pictures by width, as if only the width box had been selected)

**Comment by Bionus** [comment]
You are indeed correct, it seems that the "max height" was being used as a "max width" instead 😓 
Just pushed a fix.

**Comment by HavelockVimes** [comment]
Thanks for the quick fix!

Em qua., 20 de set. de 2023 às 12:41, Jack Vasti ***@***.***>
escreveu:
