### ISSUE TITLE
Improve thumbnail quality on searches

### ISSUE THREAD

**Issue by thgdorns** [Bionus/imgbrd-grabber#3039]
Some sources have better thumbnails available, but Grabber is still getting lower quality versions from them.

For instance, anime-pictures.
This is what Grabber gets: https://cdn.anime-pictures.net/previews/bc1/bc1a471d8b17c52d00e683bf2f828733_sp.png
This is what the website displays on their page: https://cdn.anime-pictures.net/previews/bc1/bc1a471d8b17c52d00e683bf2f828733_cp.png.avif

Another example, aibooru
What grabber gets: https://cdn.aibooru.space/preview/8d/8f/8d8feae1e7d0660c18c6848b969646ed.jpg
Max thumb size on the site: https://cdn.aibooru.space/720x720/8d/8f/8d8feae1e7d0660c18c6848b969646ed.webp

Setting thumbnail size to 200% on Grabber is wielding subpar quality compared to the website, please fix.

**Comment by Bionus** [comment]
Indeed, that makes sense.

> Another example, aibooru

This source does not seem to provide those sizes in their API response: https://aibooru.online/posts.json
Unlike for example Danbooru, which has a `media_asset` value in their JSON response: https://danbooru.donmai.us/posts.json
It's actually surprising given it seems to be based on Danbooru.

Same remark for Anime-Pictures, actually. For now I implemented the base logic and added support for Danbooru (plus the sources already returning medias' exact size).

**Comment by thgdorns** [comment]
Dunno if this is helpful. Aibooru stores the thumbnail size option as a cookie named post_preview_size; the highest value for it is 720.
