### ISSUE TITLE
Allow to filter results by "number of tags"

### ISSUE THREAD

**Issue by HavelockVimes** [Bionus/imgbrd-grabber#3040]
I use the program mostly to get images to train image training programs with, and while I manually add tags to almost every picture I get, filtering to get pictures with a certain minimum number of existing tags would quicken the process considerably.

**Comment by Bionus** [comment]
Indeed, I guess it could be nice to do something like `%tags:count%:>5` in post-filters, similar to `numtags:>5` in some sources.
