### ISSUE TITLE
Is there a way to apply different blacklist rules for each site/source?

### ISSUE THREAD

**Issue by regurafan** [Bionus/imgbrd-grabber#3044]
I have a question:

`gelbooru.com` is the source I usually use and i use the blacklist to filter images that I have already viewed using a tag and an id filter e.g.:

  `demon_girl id:<=9000000`

Now I want to visit the source `api.rule34.xxx`. 

How can I apply my filter `demon_girl id:<=9000000` only to the source gelbooru.com?

- I tried `site:gelbooru.com demon_girl id:<=9000000` but it keeps blocking images from api.rule34.xxx
- I also tried `source:gelbooru.com demon_girl id:<=9000000` but it keeps blocking images from api.rule34.xxx but it doesn't block anything in any of the sources.

**Comment by Bionus** [comment]
Well you were almost there, the token is called `website`, not `site` or `source` 😅 
Using `website:gelbooru.com demon_girl id:<=9000000` should do the trick 👍

**Comment by regurafan** [comment]
Perfect, it worked, thanks.
