### ISSUE TITLE
Anime-Picture Json Error

### ISSUE THREAD

**Issue by Surfy3994** [Bionus/imgbrd-grabber#3045]
Bug description

unable to see the search results

Steps to reproduce

Launch the Software 
type any keyword or not in the search bar 
see results

anime-pictures.net does not show anything 

log report a "Json Failed" :

[Error] [anime-pictures.net][Json] Loading error: Erreur inconnue (0)
[Warning] [anime-pictures.net] Loading using Json failed. Retry using Html.

no error in HTML but no results either, so no way to have a look 

System information

OS: Windows 11 Pro 22621.2361
Grabber version: 7.11.2 (x64)

Many thanks for your work !! keep going ;)

![Grabber_cn6j9kIYDq](https://github.com/Bionus/imgbrd-grabber/assets/146398969/c5366aab-d453-4103-b473-375bd17ccd57)

**Comment by Bionus** [comment]
Indeed, seems like they changed their API, instead of being in `/pictures/view_posts/` it's in `/api/v3/posts` now.
Just pushed a fix 👍
