### ISSUE TITLE
Do not download a file if its hash is in a specified list

### ISSUE THREAD

**Issue by SeaN0X** [Bionus/imgbrd-grabber#3046]
I am constantly downloading images to process them on my project, but later i need to delete these images so it doesnt take a lot of space on my computer. the problem is that grabber doesnt have a option to not re-download these images (as i know).

And also, when we re-start the download, we can't really keep going by where we stopped if we dont have the original files.

File check:

A good and easy to implement feature would be to include a checkbox and a input with a custom txt file path, so that for every file downloaded, grabber would check if the file hash is in this list, if so, dont download it, if not, include the file hash in the list.

Well, that's it. tia.

**Comment by Bionus** [comment]
Hello 👋 

Did you check the documentation about duplicate files, notably the part at the very bottom about deleted files?
https://www.bionus.org/imgbrd-grabber/docs/duplicate-files.html

If you enable the "Keep deleted files in the MD5 list" it won't re-download files that were downloaded in the past, even if they've been deleted from your computer in the meantime.
I believe that should solve your issue.
