### ISSUE TITLE
sort:score doesn't work on some sites

### ISSUE THREAD

**Issue by Hydrochicken** [Bionus/imgbrd-grabber#3048]
Sorting works on the websites but does nothing in Grabber. Particularly rule34.us and rule34.paheal.net
Latest version 7.11.2

**Comment by Bionus** [comment]
Just pushed a fix, thanks for the heads-up!
Note that rule34.us is based on Gelbooru and as such, uses `sort:score`, while rule34.paheal.net is based on Shimmie which uses `order:score` instead.
