### ISSUE TITLE
you have not selected a backup format

### ISSUE THREAD

**Issue by kirarock** [Bionus/imgbrd-grabber#3050]
hi, 
when trying to download it tells me:
you have not selected a backup format
Have you fixed this or please?

**Comment by Bionus** [comment]
Hello 👋

What do you mean by "backup format"? There's no such thing. If it's about the filename, you indeed need to set one up before using the program. Maybe you might want to check the docs to get an idea on how to get started?
https://www.bionus.org/imgbrd-grabber/docs/

**Comment by kirarock** [comment]
hello,
Well I had to reinstall grabber because it didn't recognize the name of the file %md5%.%ext%

THANKS
