### ISSUE TITLE
Add an option to save a frame from a gif or video file as an image

### ISSUE THREAD

**Issue by ricky01-star** [Bionus/imgbrd-grabber#3051]
It would be a cool feature and helpful for training.

**Comment by Bionus** [comment]
I don't think it's really in the scope of Grabber to do so.

If you want to use the videos or animations/gif downloaded by Grabber for ML training, why don't you just extract the frames on your side directly? `ffmpeg`, for example, allows to do this very easily.

**Comment by ricky01-star** [comment]
Alright, I see thank you for your response
