### ISSUE TITLE
Tag separator in text file, and functionality toggle

### ISSUE THREAD

**Issue by TeKett** [Bionus/imgbrd-grabber#3055]
There's multiple options for separating tags in the file name, but i cant find any that work for separating tags in text files. Iv not updated in couple months or so since i don't want to fix what ain't broken or risk losing anything, but searching didn't give any relevant results about this.

Is there a way to separate the tags? It default to space, so at least i can run notepad++ through all the files and change it to a comma and space.

I also don't want to use this feature all the time for my regular massive list of monitors, only at specific times for specific downloads. Currently i have to stop my monitors, make my settings for the text file, download the images, then delete the text file settings, and turn my monitors back on.

**Comment by Bionus** [comment]
Hello 👋 

You could simply use the `separator` option on whatever variable you are using for tags. For example:
```
%character:separator=---%
character1---character2
```

Cf https://www.bionus.org/imgbrd-grabber/docs/filename.html#separator-string

**Comment by TeKett** [comment]
Tried it, did not work, still only does a space
`%allo:separator=,%`

**Comment by Bionus** [comment]
The comma is the separator for options, like in `%character:separator=---,sort%`.
If you want to use it literally, you can use `^,` (which I agree kinda sucks :thinking:)

**Comment by TeKett** [comment]
Tried `%allo:separator=^,%`, still don't work
![Screenshot_36](https://github.com/Bionus/imgbrd-grabber/assets/64377023/61ecd1e2-57f7-4a5c-ba67-934e005049e5)
Still only spaces
![Screenshot_37](https://github.com/Bionus/imgbrd-grabber/assets/64377023/7b3f47f4-9e5a-42dc-a144-0e92cb624c11)
