### ISSUE TITLE
e621: support "lore" tag category

### ISSUE THREAD

**Issue by feffy380** [Bionus/imgbrd-grabber#3059]
**Is your feature request related to a problem? Please describe**

e621 has a `lore` tag category with id=8 (see https://e621.net/help/api under Tags > Categories). Grabber doesn't recognize this category, so it can't be used in filenames or when saving tags to log files.
Additionally, even though they show up as general tags in the interface (no color highlighting), they do not get included in the tag list unless you use `%all%`.

**Describe the solution you'd like**

Lore tags should be accessible as `%lore%` similar to other categories.

**Describe alternatives you've considered**

The only alternative is to use `%all%`, which sacrifices the ability to arrange/filter tags by category

**Comment by Bionus** [comment]
Fine by me 😄 
Surprised nobody requested it earlier, given it seems those were added back in 2020.
