### ISSUE TITLE
comma separated tag files?

### ISSUE THREAD

**Issue by eurotaku** [Bionus/imgbrd-grabber#3064]
how do you use a comma as a separator for tags in separate log files, best followed by a space? %all:separator=, % doesn't work, %all:separator=,%, both don't separate the tags at all, the example in the help section with '---' does work, though. why no comma?

**Comment by Bionus** [comment]
Hello 👋 

Comma is indeed a bit annoying because it's the options separator as well (like in `%variable:option1,option2%`), you should be able to use ^, to "escape" it. I'm considering better options but for now that should work

So it would look something like `%all:separator=^, %`.
