### ISSUE TITLE
tokens to save both the creation and download date of files.

### ISSUE THREAD

**Issue by regura-fan** [Bionus/imgbrd-grabber#3066]
In a log file I save data from the files I download. I keep the *"keep the file creation date"* option enabled (for the %date% token to return this information) but I would also like to save the information about the date the file was saved. Is there any additional token that returns the date I saved the file?

**Comment by Bionus** [comment]
Hello 👋 

You should be able to use the `%current_date%` token to achieve that.
It contains the time when the image started downloading.
