### ISSUE TITLE
"Download sample on error" Question

### ISSUE THREAD

**Issue by Triramama** [Bionus/imgbrd-grabber#3068]
This is an option in the "save" tab, what does it do exactly? I'm pretty sure if a file download failed during a batch download it gets marked as so and the user is prompted to redownload those failed images in the end of the sequence, do you mean to tell me it redownloaded only samples all the time it has been on instead of original pics?

**Comment by Bionus** [comment]
It is as the name implies: when an image's full size file returns a 404 error, Grabber can fallback to trying to download the sample image instead, if this setting is enabled.
