### ISSUE TITLE
[Question] How many tags on the blacklist can it handle? Will it accept >500 tags? For rule34 specifically

### ISSUE THREAD

**Issue by suminohana** [Bionus/imgbrd-grabber#3069]
So, I'm planning on testing this out, but if I can get an answer beforehand it will save me some time. In sum, rule34xxx has a limit to how many tags you can put on the blacklist. I'm not sure of the exact number but it's definitely capped at something like 100 or so. I have a huge list of artists and tags I don't wanna see - something like 600 different tags. Will Grabber work correctly with that amount of tags in the blacklist?

**Comment by Triramama** [comment]
Grabber's blacklist doesn't depend on the image host's blacklist, you don't have to worry about that. As for how well your tags on grabber will work with each site, usually there shouldn't be problem, _usually_.  I have over 2000 blacklist entries, there are artists names as well many image IDs, it works without a hitch, and I don't think the blacklist even has a limit. I tried loading rule34xxx with them and it looks fine. However if I try to go rule34.us the site breaks and images refuse to all, it all depends.

**Comment by suminohana** [comment]
That's great to hear @Triramama. I'll close this issue then. Do you not have issues loading huge blacklists on rule34xxx? I get a message saying the tags couldn't be loaded or something.

**Comment by Triramama** [comment]
If you want advice, you need to say exactly what message you get.
If you can't load anything, there might be arguments in your blacklisted tags that make the search unusable, try searching it by removing chunks to narrow it down to the exact one or few, I had big headache with that when I left date stamps consisting of several numbers with dots and forgot about it completely, had to review the blacklist to eliminate it.

**Comment by Bionus** [comment]
There indeed isn't any limit to how many blacklisted tags you can set in Grabber, although I don't believe there was a lot of optimizations done to it either, so it might slow down if you have too many.

If you want to target a single site for a given tag, you can always use `website:test.com some_tag` as a blacklist line.

**Comment by suminohana** [comment]
> If you want advice, you need to say exactly what message you get. If you can't load anything, there might be arguments in your blacklisted tags that make the search unusable, try searching it by removing chunks to narrow it down to the exact one or few, I had big headache with that when I left date stamps consisting of several numbers with dots and forgot about it completely, it made sites dead unresponsive, had to review the blacklist to eliminate the issue.

I get the following message when I load my entire tag list: 

"Your tag blacklist in your browser differs from the one registered on your account. This is the blacklist currently saved in your browser, it will be replaced with the one above if you save:
"

Then it shows me the previous tag list.
