### ISSUE TITLE
What does "remove" checkmark on download window do?

### ISSUE THREAD

**Issue by Triramama** [Bionus/imgbrd-grabber#3070]
I just noticed it's been turned on for me the whole time. wtf, what does it remove?
![image](https://github.com/Bionus/imgbrd-grabber/assets/97356540/878332c3-63aa-450e-bc40-f25b5a7dde1f)

**Comment by Bionus** [comment]
It removes the batch download from the downloads tab once it's finished downloading.

**Comment by Triramama** [comment]
I was trying to find this option in the settings, gee, i don't want the dl queue to get cluttered so it is very useful, but sometimes I needed it off. Thanks for the help Bionus!

**Comment by Triramama** [comment]
Btw "remove" checkbox isn't awfully descriptive of its exact function, no offense. A mouse hover tip wouldn't be bad.
