### ISSUE TITLE
Alert in Nightly builds when there's a new version available?

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3080]
Could an alert be added in the Log in Nightly builds when there's a new version available?
Like a quick check of [Nightly Release](https://github.com/Bionus/imgbrd-grabber/releases/nightly) in the background and if the build used is different than the one available to download then show an alert in the Log that a new [Nightly Release](https://github.com/Bionus/imgbrd-grabber/releases/nightly) is available to download.

**Comment by Bionus** [comment]
There's actually already an update checker for the program, and it supports nightly releases. Although it would seem there is a small bug currently that makes it always detect some "master" update, which isn't good. I just pushed a fix 👍

**Comment by ProtagNeptune** [comment]
I'm still on [c2af666](https://github.com/Bionus/imgbrd-grabber/commit/c2af6663aba075c03041a6869b7ba8af4139f5a5) and didn't get the update to [ee53ebb](https://github.com/Bionus/imgbrd-grabber/commit/ee53ebb1978522bb6ae22d9e86c5b72092a28ed0)?

**Comment by ProtagNeptune** [comment]
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/7e4f1bf3-07ce-4f7f-b77a-b8a78c1575a1)
