### ISSUE TITLE
Videos reestricted on Rule34.US

### ISSUE THREAD

**Issue by Carrolito** [Bionus/imgbrd-grabber#3083]
**Bug description**

As the title says it seems that all types of videos downloaded from the Rule34.US source are restricted by the Cloudfare service (both .mp4 and .webm), other sources seem to work fine.

**Steps to reproduce**

1. Select Rule34.US source
2. Search for any tag containing videos
3. Select a video, the whole page or the whole tag and add it to the download queue.
4. Start downloading
5. The downloaded videos will appear with a watermark by cloudflare, I will put a picture below.

**Expected behavior**

That videos downloaded from any tag on Rule34.US do not have this restriction. 

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/13984275/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/13984292/settings.txt)

**Screenshots**
![2024-01-18 21_37_28](https://github.com/Bionus/imgbrd-grabber/assets/31100223/6169a1b3-282a-41c3-bffd-a362f01853ad)
![2024-01-18 21_37_09](https://github.com/Bionus/imgbrd-grabber/assets/31100223/2e236fff-5b19-4f31-8672-00b76c14bb11)

**System information**

- OS: Windows 10 pro 19045.3930
- Grabber version: 7.11.2 x64

**Additional context**

I have seen that sometimes there is a source that can not download files completely and I usually have some files that can not be downloaded because of some error, if the tag is thousands then it can be a few hundred images with error but I am not sure if it is rule34.us as I use r34.xxx, r34.us, r34.paheal, sankaku and kemono with mixed sources.

**Comment by Bionus** [comment]
Interesting, I could not reproduce this by downloading the first page of the "video" tag in there.
The files got downloaded properly, and there's no watermark on them. Does it happen on every single video file for you, or only some? Are you logged into that source in Grabber?

**Comment by Carrolito** [comment]
It happens to me with all the videos from the r34.us source, even in the video player inside grabber, I'm not sure if it's normal but I don't see any option to login in that source, it's empty, I tried to do it by cookies with session_id and the value but it didn't work.

I don't think it's related to this problem but I have noticed that some sources cause errors when downloading files and then they fix themselves, right now it's happening with kemono.party but it's usually with r34.us or r34.paheal too, I'm starting to believe that my installation has something wrong.

![2024-01-20 20_31_41](https://github.com/Bionus/imgbrd-grabber/assets/31100223/f3e237b4-bf4c-4097-9341-06b79993970d)
![2024-01-20 20_46_31](https://github.com/Bionus/imgbrd-grabber/assets/31100223/aad00135-ef19-4626-94c5-6b4863944f03)

**Comment by Carrolito** [comment]
Oh it seems that R34.US is also having errors, it doesn't find files to download even though it lists them, I wonder if it's a cloudflare thing.

**Comment by Bionus** [comment]
It seems to only happen when accessing videos from `img2.rule34.us` (or similar), which goes through CloudFlare, instead of `video.rule34.us` which goes straight to the servers.
