### ISSUE TITLE
Can't load Anime-pictures 

### ISSUE THREAD

**Issue by hatimurni** [Bionus/imgbrd-grabber#3089]
Choose anime-pictures as sources but page wont load, even after change app setting 

* 
**System information**

- android 11
- Grabber version: [7.11.2]

**Additional context**

Hope u guys will fix this

**Comment by Bionus** [comment]
Yes, the fix should be present in the [nightly release](https://github.com/Bionus/imgbrd-grabber/releases/nightly). Marking as duplicate, but feel free to reply on the other thread if anything doesn't work for that source on that release as well.
