### ISSUE TITLE
Convert image types upon download

### ISSUE THREAD

**Issue by Infaera** [Bionus/imgbrd-grabber#3091]
PNG images are sometimes ridiculously large and don't allow tags to be saved within itself.
Thus, an option to convert specific filetypes (PNG -> JPG) upon download to allow tags and save space.
(Maybe also alter the 'Already Saved' feature in the image viewer to only check the hash instead of the whole filename)

**Comment by a84r7a3rga76fg** [comment]
Why not JXL? It's faster and lossless.

**Comment by Infaera** [comment]
> Why not JXL? It's faster and lossless.

How would I go about using this?
