### ISSUE TITLE
blacklist border color change

### ISSUE THREAD

**Issue by b1nezer** [Bionus/imgbrd-grabber#3095]
blacklisted tags have black border around them.
is there way to change border color to red color for it to stand out on dark theme background?

![Grabber_jLBCi7OG0v](https://github.com/Bionus/imgbrd-grabber/assets/53691301/341500c2-f2ff-4910-a2d6-3a6bb2f7fede)

**Comment by Bionus** [comment]
It's currently not possible but that's a good idea 👍
