### ISSUE TITLE
This video has been restricted. Streaming video from Cloudfire's basic service is a violation of ToS

### ISSUE THREAD

**Issue by LTGM** [Bionus/imgbrd-grabber#3101]
I left download overnight and noticed that in the folder there's like thousand if not more short 'empty' videos that say:
![cfe](https://github.com/Bionus/imgbrd-grabber/assets/29736559/c7980158-cc8f-4f67-8382-fe8a2e4c1e64)

1. enter any tag
2. select all resources
3. wait for the tag to be completed/downloaded
4. there is a chance if there's many videos of that tag, you will encounter at least dozens of them after some time, I suspect they might be from ex-hentai or whatever this site with sad panda is (this is probably (my guess!) their attempt/block from people to mass-download stuff)

Sorry for not being too specific (I already deleted everything but few things I was looking for).
I really think that this is a common issue for many other people too, so if they can assist me to fill this properly (share your logs or maybe you did some testing/you know how to fix that) it would be much appreciated!

**Expected behavior**
Enter a tag, download videos properly

**Screenshots**
![cfe](https://github.com/Bionus/imgbrd-grabber/assets/29736559/7b945991-6ba4-4130-a624-cf9c442bb251)

**System information**
- 10
- 7.11.2

**Comment by lawietold** [comment]
This always happens when trying to download videos from _rule34.us_ using Grabber.
It has been like this for months.
