### ISSUE TITLE
Copy all tags, with namespaces?

### ISSUE THREAD

**Issue by UnlimitedArk** [Bionus/imgbrd-grabber#3109]
Is there any way for the copy all tags function to also get the namespaces? In the past i used boorutagparser for this but after coming back to it i noticed it doesn't work anymore for danbooru and other alternatives don't get the namespace fields, so i was wondering if grabber could do it? (i use this function to get tags from similar/sample images for stuff that's not in the boorus, to tag them in hydrus)
Would be handy since i use grabber the most at the moment, but i'm not sure if it's possible

**Comment by Bionus** [comment]
Makes sense, I can add that to the context menu 👍
