### ISSUE TITLE
Change %date% format to YYYY-MM-DD

### ISSUE THREAD

**Issue by sdal** [Bionus/imgbrd-grabber#3127]
My reason for this is that with DD-MM-YYYY the %date% token makes no use. By adding %date% in the name I assume that I would need to sort images by, let's say, character's name AND date. And with dd-mm-yyyy after sorting files by name i would first get (in Windows at least) pictures of one day of one month of every year possible, then next month of every year and so on. It would hardly help with looking for a picture by upload date. But with YYYY-MM-DD there will be a logical order (again, at least in Windows).
![image](https://github.com/Bionus/imgbrd-grabber/assets/12368365/911b1a5d-fd1c-4dfa-af81-d178156be279)
Probably time format would also need to be flipped, but from my experience it's not that critical.

**Comment by Bionus** [comment]
Hello 👋 

Have you checked the [date formatting docs](https://www.bionus.org/imgbrd-grabber/docs/filename.html#dates)?
You should be able to use `%date:format=yyyy-MM-dd hh.mm%` to achieve what you need 👍 

Otherwise, it uses your system's locale settings for date formatting by default.

**Comment by sdal** [comment]
My bad, sorry. Thanks a lot!
