### ISSUE TITLE
Missing and incorrect metadata using exiftool

### ISSUE THREAD

**Issue by user0382906** [Bionus/imgbrd-grabber#3130]
**Bug description**

I have noticed several metadata errors in downloaded images while trying to process (sort and tag) files. If I were to guess the error rate might be as high as 5%, but I haven’t officially counted anything. The log files provided are from a clean install and the errors still persists.

**Steps to reproduce**

I have grabber set up to apply the following metadata downloaded files:

**Title**: ⦗%copyright%⦘_#%character%__%rating%_[%website%_%id%_©%artist%_%date:format=(yyyy-MM-dd)]%
**Subject**: ©%artist%;⦗%copyright%⦘;#%character%;*%rating%;Ξ%general%
**CreateDate**: %date:format=yyyy-MM-dd hh:mm:ss,unsafe%
**DateTimeOriginal**: %date:format=yyyy-MM-dd hh:mm:ss,unsafe%
**Creator**: ©%artist%
**Copyright**: ⦗%copyright%⦘
**Source**: %md5%
**Description**: #%character%
**ImageDescription**: %score:length=10%
**XPComment**: *%rating%

All tags are separated with a ; and the corresponding special character “;Ξ” , “;©” , “⦘;⦗” and “;#”.
**Filename**: “%search:spaces%/%website%_%id%_%md5%.%ext%”.

**Safe for work image examples (provided below convert "Downloadable Image Errors" to .igl)**

Ex. Image with blank metadata fields. Exiftool does write metadata to this image using terminal commands, but Grabber leaves it blank.
yande id:628701

Ex. Image with incorrect “Creator” tag. There are several cases where Grabber does not overwrite existing metadata.
gelbooru id:7621020

Ex. Image with missing “Title” and “Keywords”, the other fields were added. 
gelbooru id:4074286

Grabber was able to output sidecar files with the correct metadata for each example.

**System information**

- OS: Windows 10 and macOS 14
- Grabber version: 7.11.2
- Exiftool version: 12.76 and 12.82

**Feature Request**

This is a difficult issue to fix for individuals that have already downloaded images with incomplete metadata. It would be nice if there was an option or checkbox in Grabber's renaming tool to correct the metadata for existing images according to the presets in settings. 

Currently, the only way to fix this is to delete and redownload the images with errors. I some cases I have already deleted unwanted images from artist folders and I will have to go back and delete the unwanted content again if I have to redownload everything. Thanks. 

[Downloadable Image Errors.txt](https://github.com/Bionus/imgbrd-grabber/files/14940256/Downloadable.Image.Errors.txt)

[settings [Save] part only.txt](https://github.com/Bionus/imgbrd-grabber/files/14940448/settings.Save.part.only.txt)

**Comment by Bionus** [comment]
Hello 👋 

That's a very clear bug report, so first, thanks for that 😄
The download file was especially helpful.

----------

> Ex. Image with blank metadata fields. Exiftool does write metadata to this image using terminal commands, but Grabber leaves it blank.
> yande id:628701

I can indeed reproduce, and when downloading it I'm also getting this error log:
```
[21:05:31.566][Error] [Exiftool] Error: [minor] IFD0 pointer references previous IFD0 directory - .../id 628701/yande.re_628701_c089063f5fb0f9c3b38b77c35f314f8c.png
```

> Exiftool does write metadata to this image using terminal commands, but Grabber leaves it blank.

Are you using `-m` in your command, that would ignore such minor error?
Maybe I could update Grabber to do the same. 🤔 

> Ex. Image with incorrect “Creator” tag. There are several cases where Grabber does not overwrite existing metadata.
> gelbooru id:7621020

Couldn't reproduce (the artist is indeed tiv, [link](https://gelbooru.com/index.php?page=post&s=view&id=7621020)):
```
exiftool "id 7621020/gelbooru.com_7621020_97219a48011c2330128c9894f4a6e1fb.jpg" | grep Creator

Creator                         : ©tiv
```

> Ex. Image with missing “Title” and “Keywords”, the other fields were added.
> gelbooru id:4074286

Couldn't reproduce either (data looks correct, [link](https://gelbooru.com/index.php?page=post&s=view&id=4074286)):
```
exiftool "id 4074286/gelbooru.com_4074286_9ff686f7069f71f26b21fa94bee3e93d.jpg"| grep -E "Title|Subject"

Subject                         : ©hoshizaki reita, ⦗darling in the franxx⦘, #zero two (darling in the franxx), *sensitive, Ξ10s, Ξ1girl, Ξ d, Ξblunt bangs, Ξblurry, Ξblurry foreground, Ξbreasts, Ξdepth of field, Ξeyeshadow, Ξfangs, Ξgreen eyes, Ξhairband, Ξhand on own hip, Ξhorns, Ξjacket, Ξlong hair, Ξlong sleeves, Ξlooking at viewer, Ξmakeup, Ξmedium breasts, Ξnecktie, Ξopen mouth, Ξorange necktie, Ξpink hair, Ξreaching, Ξreaching towards viewer, Ξred jacket, Ξshirt, Ξsignature, Ξsmile, Ξsolo, Ξstanding, Ξupper body, Ξwhite shirt
Title                           : ⦗darling in the franxx⦘_#zero two (darling in the franxx)__sensitive_[gelbooru.com_4074286_©hoshizaki reita_(2018-01-27)]
```

--------

What data did you actually get for the 2 Gelbooru images instead of the correct metadata?
Was there anything in your Grabber logs after writing the images with invalid metadata?

**Comment by Keyeson** [comment]
Another thing that can cause the missing metadata I've found are files with the wrong extension. Gone through a good bit of my booru stuff and haven't seen any, but that isn't to say that aren't any saved with the wrong extensions there. Seems to be much more common on sites that deal with manga like NHentai and Ehentai. Have encountered it on the SFW manga aggregates like Mangadex as well just seems like some translation groups/translators incorrectly save the files as PNG when the image is encoded as a JPG.

As an example NHentai id:505041 should give this error
`[Error] [Exiftool] Error: Not a valid PNG (looks more like a JPEG)`

Honestly though you can just download a bunch of galleries and you are pretty likely to find one that has mislabeled/wrong extensions.

Haven't tried fooling around with the CLI of Exiftool to see if it would tag it if I adjusted the options, but as far as I can see there are no tags on it when it gives that error. Also honestly I have some old image/manga viewers I use that don't like it when things have the wrong extension so it would be nice if there was an option to correct mislabeled extensions.

**Comment by user0382906** [comment]
Update 7.12.2 added the ability to clear existing metadata. I went thru and tested some problematic images and I haven't noticed any problems. This issue can be closed. Thanks. 😄
