### ISSUE TITLE
The "Copy to downloads" menu option in the Monitors tab doesn't keep the order when copying to the Downloads tab.

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3136]
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/f26c892b-d781-4b27-8117-974d61e79947)
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/009ef0c4-ece9-48d5-b965-13f58af44722)
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/ad18e6a4-b19e-4de4-8d7a-7b1563581c5a)

**Comment by Bionus** [comment]
Indeed, just pushed a fix 👍
