### ISSUE TITLE
Change "Automatic re-download" to "Retry failed downloads" to make the feature easier to understand.

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3138]
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/6e5e3a73-1c8f-4076-879b-26b07ef1e09f)

**Comment by Bionus** [comment]
Updated to be clearer indeed, thanks for the suggestion 👍 

![image](https://github.com/Bionus/imgbrd-grabber/assets/882719/4a84ebb7-4056-4269-bdb0-5c92cb17eedd)
