### ISSUE TITLE
Being able to Maximize the "Batch download" windows.

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3139]
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/02317c37-1657-4d63-96cf-02085b1e6f04)

I like to have the batch download windows on another monitor so it would be nice if I could maximize it rather than manually resize it every time I restart Grabber.

**Comment by Bionus** [comment]
Makes sense 👍
