### ISSUE TITLE
Details loaded even for images already in the MD5 list

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3140]
When you batch download and it gets a URL *with the md5 already in it* why should it need to load the details if the file already exists on the md5 database and in the hard drive with the Path/Folder/Filename?
It keeps throwing `[Info] Details limit reached (HTTP 503). New try.` and slow the batch download by pointlessly loading details when it's just not needed, *the file already exists* so it should just start the next download on the list.

**Comment by solipsis-project** [comment]
There are situations where a user may want to load the details, even if the md5 is already in the database and the file is already on the hard drive at that path.

For instance, I have database hooks that run for each image that insert that image's metadata into a custom DB. If I download the same file from different sources, I don't want that process to be skipped: I want my custom DB to have a separate entry for each source that contains the file.

I'm still learning how to use Grabber, but I'm worried that skipping loading details when an image is already in the md5 list might skip these DB commands, and I want to make sure that won't happen.

**Comment by Bionus** [comment]
@solipsis-project in those cases, you can simply set your download settings always download the file. But today, the file will be skipped anyway after loading the details, and the SQL commands won't run. This is just an optimization.

**Comment by ProtagNeptune** [comment]
@Bionus Nope, [c6b22e2](https://github.com/Bionus/imgbrd-grabber/commit/c6b22e2baafe7f1c93bafe85734036b3751c987e) didn't fix it so I'm guessing that my metadata setting is still somehow forcing it to load the details even though it's already in the MD5 list and on the disk.
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/159dd9cd-28e2-4cab-b30c-c05bc71a8b2f)
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/ed6a956b-ef62-4126-be65-29109f8a8d93)
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/5b96f4bf-390b-4fcc-a3bc-413ba5cdc573)

**Comment by Bionus** [comment]
Seems to be because of the "same dir" MD5 setting. Pushed a second fix, sorry about that 👍

**Comment by ProtagNeptune** [comment]
Yep, [70073d6](https://github.com/Bionus/imgbrd-grabber/commit/70073d6fd9e8f6d2c0ae792a0a4ef475b0038812) fixed this bug for me. 👌
