### ISSUE TITLE
GIF and MP4 saved as JPG on R34 Paheal

### ISSUE THREAD

**Issue by Irarius** [Bionus/imgbrd-grabber#3142]
if it can, can someone expain how i get it to do that?

**Comment by lolbroek-droid** [comment]
i'm pretty sure it does it automatically if there are any

**Comment by Irarius** [comment]
so far it doesnt

**Comment by Irarius** [comment]
r34 paheal

**Comment by Irarius** [comment]
okay it actually does it just doesnt add the .gif or .mp4 at the end
which is strange, is there an  option to change that then?

**Comment by Bionus** [comment]
Seems like a bug caused by their file URLs that don't have an extension. I'll push a fix.

**Comment by Irarius** [comment]
cool

**Comment by lolbroek-droid** [comment]
to be honest idk what causes it to do that.
i just use it for api.rule34.xxx

**Comment by Irarius** [comment]
i just realized you are german aswell 
hallo

**Comment by lolbroek-droid** [comment]
Hai

**Comment by Irarius** [comment]
where do i have to put thise new lines of code though
cant find the exact folders in the grabber folder
