### ISSUE TITLE
Android Crash when Searching

### ISSUE THREAD

**Issue by FroggyFriend** [Bionus/imgbrd-grabber#3163]
**Bug description**
When searching with any tag, the app crashes.
App does not crash when searching without tags.

**Steps to reproduce**
1. Open App
2. Input anything into search tab
3. Click either the search icon or enter button on keyboard

**Context**
Unsure of where to find `main.log` on Android, will provide if I can find it or be told where to look, whichever comes first.

**Screenshots**
Video attached showcases the error in action.
https://github.com/Bionus/imgbrd-grabber/assets/80283974/2a397585-2593-4d1f-ab05-df1b91e2b2a9

**System information**
- OS: Android 14
- Grabber version: 7.12.2

**Additional context**
Android automatically offered to clear the Cache, which did not fix the issue, clearing app data did not fix the issue either.

Search function worked as of 3 days ago of this report being made.

**Comment by Bionus** [comment]
Weird, it's searching fine on Android + Gelbooru for me. Is that the only source it happens on? 🤔 

> Search function worked as of 3 days ago of this report being made.

Did you update the app over that period?

**Comment by FroggyFriend** [comment]
> Did you update the app over that period?
Not that I can recall, but I think I can close this issue as the problem has seemingly solved itself, without any user input.

It must've just been some System issue that has since self-corrected, thank you for taking the time to look into this though!
