### ISSUE TITLE
about "tags in TXT files"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#317]
I just discovered that now we can save tags list within a txt file along with the images.

I have a few question regarding this new option (is it that new?)

- I tried to see if this txt tags files was compatible with any image viewer that I know, but it seems it is not. Do you know if there is such a program?
- I already downloaded tons of images without this option. Would it be possible to have an easy way to update already downloaded images in folders with tags list from the web?

(I have a few more question, but I'll restrain ;) )

> Original issue reported on code.google.com by `ser...@hotmail.com` on 9 Jul 2014 at 5:39

**Comment by Bionus** [comment]
See issue #258
