### ISSUE TITLE
Both 93dd930 & b043373 failed building for Linux, MacOS, and Windows... 😕

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3194]
- 93dd930 - [fix: get file extension from header when enabled (fix #3158)](https://github.com/Bionus/imgbrd-grabber/actions/runs/9236026837)
- b043373 - [feat: allow to customize format conversion timeout (fix #3185)](https://github.com/Bionus/imgbrd-grabber/actions/runs/9353711237)

**Comment by ProtagNeptune** [comment]
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/b0bcc684-3bdb-45bb-b2b6-9e4a20404487)
https://github.com/Bionus/imgbrd-grabber/commits/develop

**Comment by Bionus** [comment]
Just pushed a fix that should fix the build. But you don't need to tell me about those, I already get notifications whenever a build fails 😄

**Comment by ProtagNeptune** [comment]
It was fixed by 66e4a30.
