### ISSUE TITLE
[Exiftool] Error: [minor] Will wrap JXL codestream in ISO BMFF container for writing

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3213]
Solution: Use the `-m` option to ignore the minor error and allow ExifTool to wrap the JXL codestream in a BMFF container.
Source: [How to add a comment to a JPEG XL image? - exiftool.org](https://exiftool.org/forum/index.php?topic=15677.0)

**Comment by Bionus** [comment]
Do you have an example file / URL on one of Grabber's source where this can be reproduced?

**Comment by ProtagNeptune** [comment]
This is for literally any images converted to jxl.

**Comment by ProtagNeptune** [comment]
Without the `-m` it doesn't change the metadata of the JXL files.

**Comment by ProtagNeptune** [comment]
> This is for literally any images converted to jxl.

![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/d00dac4a-93e1-4178-b08a-0915eb5bfb20)

**Comment by ProtagNeptune** [comment]
It's now working fine with the https://github.com/Bionus/imgbrd-grabber/commit/fef4a9405dee2fb5110dbc569339be2cfe487588  nightly build.
