### ISSUE TITLE
Existing file skipping is broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#323]
**What steps will reproduce the problem?**

1. Downloading images from a booru.
2. Downloading the same tag again from the same booru after restarting the Grabber. 

**What is the expected output? What do you see instead?**

The option for not saving the existing files is on. But the program redownloads about 1/5 of the existing files. The new files have the same md5 but different extension. Like 9574a31f...34be06d.jpeg and 9574a31f...34be06d.png

**What version of the product are you using? On what operating system?**

Grabber 3.5 and Win 7 32bit

**Please provide any additional information below if necessary.**

The filename structure used is %md5%.%ext%

> Original issue reported on code.google.com by `Alkal...@gmail.com` on 18 Jul 2014 at 8:24

**Comment by Bionus** [comment]
Just a note: all this behavior will change depending on your duplicate settings. The program keeps in memory all saved images as well as their MD5s, so if you want absolutely zero duplicate (or want to save bandwidth or whatever), you can say so in the settings, in the "Save" part.

As for the original issue, I could not reproduce on neither Danbooru or Gelbooru. But indeed, if the remote server changed the file in the meantime or if you try to get the same file from multiple sources, the extension can change (but it should be pretty rare).

Feel free to reopen if it still happens, and please tell me which source and search you used.
Thanks
