### ISSUE TITLE
This application may not be able to support Windows 8.1 anymore.

### ISSUE THREAD

**Issue by UlyssesDominicus** [Bionus/imgbrd-grabber#3261]
**If you are experiencing errors such as 

d3d12.dll missing in your system (d3d12.dll is a component for windows 10/11)
api-ms-win-core- something something

Then, this could signal that this application may not be able to support Windows 8.1 users anymore. Not sure about windows 7...

v7.11.2 is the only usable latest version for Windows 8.1 users.**

**Comment by Bionus** [comment]
That's correct, Grabber uses Qt6 which does not support Windows 8.1, as it's been EOL for a while now.

It's not easy to support both new system/Qt versions with new features and fixes, while keeping supporting old systems whose APIs are often very different, hence this decision.
