### ISSUE TITLE
Viewer window buttons dissapeared

### ISSUE THREAD

**Issue by Triramama** [Bionus/imgbrd-grabber#3272]
I don't know what i did but there's no more menu buttons on viewer i couldn't find the shortcut that undoes this, help?
![image](https://github.com/user-attachments/assets/ca61a24d-89c1-4470-a2d5-98b2e54ac9df)

**Comment by HayateLaTech** [comment]
same bug here - going into the settings and switching the interface theme to something else fixes this temporarily, but upon starting grabber again, it'll go back into not showing the buttons.

**Comment by HayateLaTech** [comment]
https://github.com/Bionus/imgbrd-grabber/issues/3071 it is fixed in nightly

**Comment by Bionus** [comment]
Yup, this is the same as #3071 so I'll close as duplicate.
I'll try to make an official release ASAP since it's a recurring issue for many users.
