### ISSUE TITLE
Why do pixiv video are saved with a zip archive with images inside

### ISSUE THREAD

**Issue by Triramama** [Bionus/imgbrd-grabber#3307]
So like i was saying there are some videos hosted on pixiv but grabber saves those as frames and puts them inside of an archive, comparatively Powerful Pixiv Downloader saves them as webm, can't grabber be rewritten to save them as gif or webm too? 
example of video on pixiv: NSFW warning https://www.pixiv.net/artworks/120938422
pixiv saved this video as a zip archive with 141 frames that took size of 11mb
![2024-10-15 19-33-44 120938422 07-27-2024 22 26 ラビットホールLive2D PAGE-4 R-18 うごイラ ラビットホール 初音ミク バニーガール VOCALOID VOCALOID](https://github.com/user-attachments/assets/778cc363-0344-4573-98e7-7b66290bd81c)
Pixiv downloader extension saved the same video as webm sized 6mb

**Comment by Bionus** [comment]
Hello 👋 

This is because those are not videos, but ugoira files:
https://www.pixiv.help/hc/en-us/articles/235584628-What-are-Ugoira

You can enable automatic conversion of ugoira in the "format conversion" part of the settings if you prefer, but the original files on Pixiv are indeed images.
