### ISSUE TITLE
How and where do I put blacklisted tags?

### ISSUE THREAD

**Issue by Wataterp** [Bionus/imgbrd-grabber#3309]
Very noob question but I genuinely do not know where to input blacklisted tags. I saw a blacklist.txt in the options folder and tried putting my blacklisted tags there but it didn't seem to work. I saw a screenshot from 2018 of a blacklist popup window, but that's from a really old and outdated version of Grabber so that's useless. I am tweaking out because I'm an idiot and can't find the options button to find the blacklist option.

**Comment by Bionus** [comment]
Hello 👋 

You can directly put your blacklisted tags directly in the settings, in the "Blacklist" part.
