### ISSUE TITLE
[Question] Post date for Rule34xxx

### ISSUE THREAD

**Issue by AldebaraanMKII** [Bionus/imgbrd-grabber#3311]
My question isn't about a issue with the program. It's about how the program fetches the post date from Rule34xxx. So feel free to close it if you don`t want to answer it. 

When i use the this
https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&json=1&limit=1000&pid=200
to get a response from the API, none of the items in the content have the date the file was posted. So how does Grabber get that info?

**Comment by CyrilCommando** [comment]
`change` is a unix epoch timestamp. I'm guessing it just gets that.

**Comment by AldebaraanMKII** [comment]
Nevermind. It seems you need to scrape the html for each post ID because the dumbasses at Rule34xxx do not send that data through the API like Gelbooru does.
