### ISSUE TITLE
Can't start up because of libqscintilla2.so.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#332]
```
Hi, Grabber won't start up when running the executable. The only output from 
the terminal is "error while loading shared libraries: libqscintilla2.so.8: 
cannot open shared object file: No such file or directory".

I've tried symlinking the libraries to the directory Grabber is in, as well as 
version .8 in the lib and lib64 folders.

I'm using Grabber 3.2.6 for Linux. I'm on Fedora 20 with KDE, kernel 3.15.10.
```

Original issue reported on code.google.com by `rubberbu...@gmail.com` on 21 Aug 2014 at 3:15

**Comment by Zhigalin** [comment]
Same problem here

**Comment by Bionus** [comment]
Did you try compiling it (as it's the common way on Linux) using the build.sh script?
It's also explained in more detail on the [Compilation](https://github.com/Bionus/imgbrd-grabber/wiki/Compilation) wiki page or the home page readme.

It should install all dependencies and compile it. You'll just then have to run it, and by default QScintilla shouldn't be a requirement.
