### ISSUE TITLE
please add support for ja.gelbooru.com

### ISSUE THREAD

**Issue by Triramama** [Bionus/imgbrd-grabber#3321]
I don't think it would be very hard to do, this is just gelbooru but with tags in japanese, i would really like to save images with japanese tags

**Comment by yami-no-tusbas** [comment]
Just go to sources, then "add" put the url : "ja.gelbooru.com" and let Grabber guess, it'll work. You may need to add you login credential for the API to work.

**Comment by Bionus** [comment]
Yes, it's a Gelbooru source so you can add it whenever yourself 👍 

Although it doesn't look like their API returns Japanese tags, but that's on them:
https://ja.gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=rating%3Ageneral

**Comment by Triramama** [comment]
it returns them for me i even saved a picture with japanese tags, but a lot of them are untranslated
![image](https://github.com/user-attachments/assets/3cf2d94b-d3b6-4b40-8b74-1e40c69b5c35)
