### ISSUE TITLE
tags downloaded by seperate log files do not contain certain characters

### ISSUE THREAD

**Issue by Hugs288** [Bionus/imgbrd-grabber#3326]
my tag file context: %artist%, %character%, %copyright%, %general:separator=^, %

it works fine except colons are replaced by space for some reason

example: silver wolf (honkai star rail) instead of silver wolf (honkai: star rail), etc etc

edit: also question mark

**Comment by Bionus** [comment]
Hello 👋 

By default, variables are escaped to fit into a filename. On Windows, that means removing some characters such as `:`, `/`, or `?`.
You can use the [`:unsafe` option](https://www.bionus.org/imgbrd-grabber/docs/filename.html#unsafe-bool) on variables to avoid that.
