### ISSUE TITLE
Filename %all% (still download the file, but remove some tags on it)

### ISSUE THREAD

**Issue by Yasakikondo74** [Bionus/imgbrd-grabber#3334]
I encounter this issue while trying to download files. 
It's a not a problem but more of an annoyance, it is possible to download images/videos with all the tags but removing some tags before saving the file?

Could you add in something like a blacklist, but for blacklisting words instead of not installing the images/videos?

I tried to use registry editor to remove the naming files cap, but it doesn't seem to work
I'm not talking about the author, character, or artist tags

**Comment by Bionus** [comment]
Hello 👋 

You can already do this in the settings, here:
![image](https://github.com/user-attachments/assets/13deaeca-824a-4fce-b033-10cb81d2f4c3)

Just set the tags you don't want in the list and they won't appear in `%all%`.
