### ISSUE TITLE
Adding support for avif image thumbnails.

### ISSUE THREAD

**Issue by stinomichael** [Bionus/imgbrd-grabber#3345]
**Is your feature request related to a problem? Please describe**

Trying to use a website that uses avif file type for thumbnails (e.g. Sankaku now), all results show as red X's.

Tested with the model.js from https://github.com/Bionus/imgbrd-grabber/issues/2808#issuecomment-1274557322
and searching : md5:e13a7846d263293155191bf7d027658d

The log gives the error:
[Error] One of the thumbnails is empty (https://v.sankakucomplex.com/data/preview/e1/3a/e13a7846d263293155191bf7d027658d.avif?e=1734886901&expires=1734886900&m=iPkPMLfw70uL5_7xShFdeQ&token=We3xmjAWHGHh5nGlwvZ0xUP2iKaOYPCdBGEcCuSvNDE).
Following the link does lead to a working image in Firefox.

**Describe the solution you'd like**

Adding a way for the program to display an avif file for the search result thumbnails.

**Describe alternatives you've considered**

I did see another issue with image previews not working in jpegXL format, and attempted to add a avif plugin dll from (https://github.com/novomesk/qt-avif-image-plugin) to the imageFormats folder, but to no avail.

**Additional context**

At this time I am unsure if any avif file will work in the image preview window, as I have not come across any previews or full images  in this format.

**Comment by Rivan2** [comment]
Try this version of the plugin
https://github.com/novomesk/qt-avif-image-plugin/releases/tag/v0.8.3

**Comment by stinomichael** [comment]
> Try this version of the plugin https://github.com/novomesk/qt-avif-image-plugin/releases/tag/v0.8.3

That works perfectly for me! Thank you!

**Comment by TeKett** [comment]
> Try this version of the plugin https://github.com/novomesk/qt-avif-image-plugin/releases/tag/v0.8.3

How does this work? I tried both files and put them next to the grabber.exe, but it doesn't seem to work.

**Comment by Oleksandrigo** [comment]
> > Try this version of the plugin https://github.com/novomesk/qt-avif-image-plugin/releases/tag/v0.8.3
> 
> How does this work? I tried both files and put them next to the grabber.exe, but it doesn't seem to work.


must be moved to the imageformat folder
