### ISSUE TITLE
Support sources: e-shuushuu.net and minitokyo.net

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#355]
**What is your suggestion for the program?**

If you can add the sites below into imgbrd, that would be quite awesome. I also wish you great luck into this small application because it helps many graphic users in the world!
- ~~http://e-shuushuu.net/~~
- ~~http://www.mg-anime-renders.net/~~ (down)
- http://www.minitokyo.net/

**What version of the product are you using? On what operating system?**

4.0.3

> Original issue reported on code.google.com by `KevinLou...@gmail.com` on 28 Dec 2014 at 6:47

**Comment by Bionus** [comment]
For e-shuushuu.net, see issue #483.
This issue will be centered on minitokyo.

**Comment by Frozenkex** [comment]
I hope this does get added, minitokyo is much better than any site (afaik) if you are specifically looking for official artwork or scans

**Comment by MasterPetrik** [comment]
http://www.minitokyo.net/ is a bad source. Very different site engine. Not standard and very poor tag system. Not able to view or download original images to not registered users.

**Comment by BarryMode** [comment]
More sources is generally a good thing, but imo since there's primarily one developer, it's better to focus on a few sources, than to have so many that you can't keep up with them all.

**Comment by Bionus** [comment]
As stated in the comments, minitokyo isn't very good, and e-shuushuu is discussed in issue #1145.
So I'll close this one.
