### ISSUE TITLE
Search result broken on some titles Grabber 4.0.5 (zerochan.net)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#363]
**What steps will reproduce the problem?**

1. Searching "Atelier escha & logy" Or "Atelier Escha and Logy"
2. clicking next page 

**What is the expected output? What do you see instead?**

i expect to see 20 images per page but it only displayed 8 and when i go to the next page the pictures are the same with the first page also when i click get all and download the images it only generated 8 links and downloaded just that 8 links.

**What version of the product are you using? On what operating system?**

Grabber 4.0.5

**Please provide any additional information below if necessary.**

Other title such as "blood lad" don't have the same problem
The result shows page 1 of 11 (8 of 83) but only generates 8 picture 
My search is set on zerochan.net
Image per page is set to 20 and number of columns is set to 1 (default configuration) tried changing it but problem persist
sources is set to RSS>XML>JSON>Regex

> Original issue reported on code.google.com by `princeba...@gmail.com` on 15 Jan 2015 at 1:22

**Comment by Bionus** [comment]
This is due to Zerochan returning an invalid RSS feed for this search, because of the `&` character in the tag. Unfortunately, there is little I can do about this.

As you can see here:
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.zerochan.net%2FAtelier%2520Escha%2520%2526%2520Logy%3Fs%3Did%26xml%26p%3D1
```
This feed does not validate.
line 4, column 24: XML parsing error: <unknown>:4:24: not well-formed (invalid token)

<title>Atelier Escha & Logy - Zerochan Anime Image Board</title>
                     ^
```
