### ISSUE TITLE
gelbooru tag search no results

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#365]
```
gelbooru tag search "no results". What I do wrong?

How to download from gelbooru by tag7
```

Original issue reported on code.google.com by `assaulov...@gmail.com` on 21 Jan 2015 at 6:28

**Comment by Bionus** [comment]
Could you provide more details?
Gelbooru works well on my end and I have been reported the same by some other users.
I'll reopen then.
