### ISSUE TITLE
crashes on downloading images

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#370]
```
What steps will reproduce the problem?
1.search some tags on gelbooru
2.pressed get all
3.and then download all

What is the expected output? What do you see instead?
it crashes after about 900 (about 9000 to go).

What version of the product are you using? On what operating system?
V4.0.5 on Windows 8.1 Pro

Please provide any additional information below if necessary.
also i have found out that it fills up my ram memory to about 2 gigs (my system 
has 8 gb)

```

Original issue reported on code.google.com by `ugurduyg...@gmail.com` on 1 Mar 2015 at 1:53

**Comment by theHubi** [comment]
I just updated from 3.5 (no crashes whatsoever) to 4.1. Crashes everywhere, what the hell is going on?
If you click download all, crashes. Download selected (like 10 images), crashes.
That basically makes the whole program unuseable. Back to 3.5 I go.

**Comment by Bionus** [comment]
Which system?
Which source?
Which search?
Which download? (.lnk file?)

**Comment by theHubi** [comment]
Here's a "log" of the crashes (I sent you 3 crash reports before btw, I dunno why it stopped asking me).
Still running Windows 7, could replicate the same thing on Windows 8 though.
https://drive.google.com/file/d/0B4qnAW9zCJYLUlR6MVlkRlZCaEE/view?usp=sharing
Here's the whole process multiple times. It's 32 Megabytes in size.

**Comment by Bionus** [comment]
Version 4.1.3 should fix this issue.

While I reproduced the crash you show here using 4.1.2 it's gone on 4.1.3 (185 images properly downloaded). I also updated the translations, feel free to tell me if any is still missing.

**Comment by theHubi** [comment]
Crash documented and posted in new issue.
