### ISSUE TITLE
Use Pool ID?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#371]
```
It would be nice to have things downloaded by pool name for image sets like 
books.
%poolid%\%filename%-%md5%.%ext% something like that which puts all the images 
into one folder rather than "artist"

I am using the windows version.

```

Original issue reported on code.google.com by `maverynt...@gmail.com` on 1 Mar 2015 at 3:02

**Comment by Bionus** [comment]
A `%pool%` token will be added in 4.1.7 and will contain the pool ID if found in the search (in the `pool:ID` format). It does not consider the real image's pools (multiple pools, or image accessed by other means).
