### ISSUE TITLE
Pools tab not working

### ISSUE THREAD

**Issue by geezer13** [Bionus/imgbrd-grabber#384]
When I query the pools tab I get nothing. Clicking the no result tab for the term "fast" gives me this blank page: http://danbooru.donmai.us/posts.xml?login=&password_hash=&limit=40&page=1&tags=pool:1%201823 - removing the 1%20 (space) from the pool tab fixes this.

**Comment by Bionus** [comment]
It would seem that you are mixing the tag field with the pool ID select box.
The pool ID has to be directly on the right of the source selector.
The order is: source, pool ID, tags, page number.

![pool](https://cloud.githubusercontent.com/assets/882719/7221355/4a01c642-e6e8-11e4-9547-5b53075be955.png)
