### ISSUE TITLE
[v4.1.1] Issues with the results, "+" bar and frequent crashes.

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#385]
![viojqgv](http://i.imgur.com/vIOjqgv.png)
_v4.1.1_

As you can see, the additional booru's I've added result in the results pages looking like this overlapping one another something silly, could do with being part of a scroll bar menu so all the results can be spaced out with the pre-loaded Images showing up according to the dimensions the users have set without worry for this.

And on the "+" section, the sources are so numerous they overlap one another to the point where they cannot be seen.

I remember bringing this up back on the Google Code site you used for Imaged board grabber, but ti seems you only got round to sorting out the Sources (Thank god, it's a godsend by the way)

Additionally, I seem to be getting frequent repetitive crashes in the latest release, that often occurs during or after I add a new Booru to my Sources menu in the program, it sometimes occurs on multiple search results also.

**Comment by Bionus** [comment]
>  As you can see, the additional booru's I've added result in the results pages looking like this overlapping one another something silly, could do with being part of a scroll bar menu so all the results can be spaced out with the pre-loaded Images showing up according to the dimensions the users have set without worry for this.

Well I didn't expect someone to make searches with more than 9 sources (which can be still visible using 3 columns, leading to a 3x3 grid).
I'll add a "scrollbar" setting to enable it in the search results in an upcoming version.

> And on the "+" section, the sources are so numerous they overlap one another to the point where they cannot be seen.

A scrollbar has been added there as of version 4.1.3 (commit e6f457eaa6e6c75b853ea99fc07bd60f35bff301).

> I remember bringing this up back on the Google Code site you used for Imaged board grabber, but ti seems you only got round to sorting out the Sources (Thank god, it's a godsend by the way)

Yes, I also believe that here is way more convenient that Google Code, which will be shut down soon.
Your issue should still be around though, if you remember the title, even if it will be marked as authored by @GoogleCodeExporter.

> Additionally, I seem to be getting frequent repetitive crashes in the latest release, that often occurs during or after I add a new Booru to my Sources menu in the program, it sometimes occurs on multiple search results also.

Are you talking about issue #390?
If so it's fixed, however if you mean something else do you mind providing some more details?
