### ISSUE TITLE
downloading issue

### ISSUE THREAD

**Issue by three5** [Bionus/imgbrd-grabber#386]
What steps will reproduce the problem?
1  search for tag on yande.re, gelbooru, zerochan (example: hanyuu).
2  pressed get all.
3  download all.

What is the expected output? What do you see instead?
download window opens; then downloading begins but it stops on first pic (0%). the list of pics creating without problems; I can get links and open any pic in browser etc. if I try to close the window, I get a crash:

Sorry
Grabber encountered a problem and crashed.

What version of the product are you using? On what operating system?
v4.1.1; v4.1.0. Windows 8.1

Please provide any additional information below if necessary.
i used it for 6 months without any troubles. before this issue I didnt open program for 4 weeks or so.

**Comment by imgbrd** [comment]
i have a very similar problem. wiped windows because of a rootkit, reinstalled imgbrdgabber, now it doesnt download a thing. win 8.1, newest version used. downloading a single file through the image itself isnt a problem, any form of batch just doesnt download a thing.

**Comment by SultrySamthepennanceman** [comment]
I've been getting this too, it recently started to occur After I installed the new version, not the old nor any that I have added to the sources bar are downloading, it either crashes or stays at 0% indefinitely until a crash.

**Comment by Bionus** [comment]
This should have been fixed by the latest 4.1.2 release.
https://github.com/Bionus/imgbrd-grabber/releases/tag/v4.1.2

Please check it out and tell me if you still experience this issue.
