### ISSUE TITLE
Cannot login to any source "impossible de tester" error message

### ISSUE THREAD

**Issue by qazxswedcxzaqws** [Bionus/imgbrd-grabber#388]
Everything else is working fine I just cannot log in to any imageboard/source through the application, the images I want to download require me to log in, please help :frowning:.

**Comment by Bionus** [comment]
Which board are you trying to login to?
The "impossible de tester" message ("unable to test" in English) only means that the program cannot ensure that the connection will be successful. Most boards cannot be tested any other way than trying for yourself to access protected images (for example Danbooru).

**Comment by CrimsonKirie** [comment]
I get the same problem, I've entered my danbooru username and password but I get no results for any searches. If I leave my user details off then I can search so it's something to do with the login

**Comment by Bionus** [comment]
@CrimsonKirie did you make sure to use the "choujin-steiner--PASSWORD--" syntax when hashing your password through the source settings ? I just tried and could search just fine.
