### ISSUE TITLE
Nothing is downloaded 

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#389]
Using Latest version, for whatever reason nothing now downloads, I've reinstalled it fresh without any added booru's, and even then it still fails to download anything, I'm either greeted with a crash, or an endless batch download screen stuck on the first item.

You can however, view the images found in search just fine, It's just that I can no longer download any.

**Comment by Bionus** [comment]
This should have been fixed by the latest 4.1.2 release.
https://github.com/Bionus/imgbrd-grabber/releases/tag/v4.1.2

Please check it out and tell me if you still experience this issue.

**Comment by theHubi** [comment]
I have to say, sometimes (haven't tested it with 4.1.3 yet) the reason why I got errors while downloading is that Grabber could not create the folder to save the images in. But after restarting Grabber it always worked. Weird.
If that's what you're referring to, yeah it should be fixed.
