### ISSUE TITLE
Frequent crashes around the addition of sources & sources not working 1st time when added

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#390]
Using Version 4.1.2

Seem to be getting frequent crashes when operating with the Add Booru feature, namely when I Click on the 'OK' button on the sources window after adding something to it.

Doesn't happen all the time, but it's pretty jarring if you've had a session open or the like.

Best steps to re-create this is to do what I've been doing to get It:

Open up the sources window, manually add sources (Guess function rarely ever works you see) from http://booru.org/top (Most included are Gelbooru version 0,1 Boorus with a few variants) and deselect your chosen sources to search with save for the one you've just added and click okay and search something with it.

If you did it right, you get a working new source, but at some point between getting the source and adding it in this process, there tends to be a crash during this process, or sometimes though you selected the correct source, it isn't added properly, so you have to delete it and add it again.

Asides from that, thanks for fixing the DL issue, was starved of content for an age.

Edit, seems to occur mostly when you switch windows WITH the sources window open of Grabber.

Edit:I've noticed one of the problems is, It seems when making a transition from one window to the sources window state, for instant, the scroll bar is not present,  and all the sources are bundled together in an instant, before the scroll bar comes in,

It's too quick to capture a screen shot of, but you'll probably see it when you recreate the issue or when opening up the sources window.

**Comment by Bionus** [comment]
Did you make sure *not* to include the http or https when you added it?
Taking the link you gave at an example, "http://rule34.xxx/" would need to be added as "rule34.xxx"

I agree that should however be removed automatically if someone put it, so I'll remove the http:// and trailing slash it in the next update.

I also managed to get the crash you're talking about, so I'll check this one out too. Seems like there's a problem with some indexes.

**Comment by SultrySamthepennanceman** [comment]
Thanks man. also, you need to add a scroll bar to the search results page when you get round to it, because mass sources reduces the page to mere blue pixels.

**Comment by Bionus** [comment]
This should be fixed with the 4.1.3 version (commit 1094ca1c02b2e44ed75b883e7cb30a8ae420062c).
