### ISSUE TITLE
Add WebM support

### ISSUE THREAD

**Issue by RaceDriverMIKU** [Bionus/imgbrd-grabber#393]

**Comment by Bionus** [comment]
I believe WebP is already supported as long as you have the "qwebp.dll" DLL in your "imageformats" folder (found in the installation folder). Unless you're using a very old version or deleted it manually, it should still be there.

As for webm, it's planned to be integrated in a short future. :)

**Comment by RaceDriverMIKU** [comment]
um......my contury censors gelbooru,danbooru and im using tor,so im not sure,anyway it's not visible,i gonna try again

**Comment by RaceDriverMIKU** [comment]
e62,one of not censored,and WebM is not visible,comformed file is downloaded,and after downloading open WebM file manually as MPC-HC,it plays fine
Windows 8.1 industry embeded 64bit
Grabber 4.1.3

**Comment by RaceDriverMIKU** [comment]
While i testing,I found viewing images on zerochan have issue
tag:Animated
Image link:http://www.zerochan.net/555536
Une erreur inattendue est survenue lors du chargement de l'image (203).
http://s3.zerochan.net/Rkroca.full.555536.jpeg

but in detail window it's link is http://s3.zerochan.net/Rkroca.full.555536.jpg
and i set view original image in viewer

Thank you Bionus.

**Comment by Bionus** [comment]
> e62,one of not censored,and WebM is not visible,comformed file is downloaded,and after downloading open WebM file manually as MPC-HC,it plays fine

The problem with webm is that unlike other file types (even gif) they are not images but videos. The whole treatment is different, and require codecs which are not present by default on Windows (who only bundles the WMV codecs).
One option would be to install them at installation (in the same way as it installs the MSVC dependencies) but that would be a burden for the end-user.
Another would be to depend on libVLC (https://wiki.videolan.org/LibVLC_SampleCode_Qt) which would them be quite a lot of work.

> While i testing,I found viewing images on zerochan have issue

I see, thanks for pointing it out. The link should actually be http://static.zerochan.net/Rkroca.full.555536.jpg (and not http://s3.zerochan.net/Rkroca.full.555536.jpg)
Seems like all images are accessible through http://static.zerochan.net/ while thumbnails and samples are on other servers.
I'll take a look.

**Comment by SultrySamthepennanceman** [comment]
Could you get Rulle34hentai.net to work with grabber?

It used too, but I guess the site became to foreign to be recognized by the sources choices panel.

**Comment by micnorian14** [comment]
rule34hentai has webm files - imgbrd grabs them correctly just...with a .jpg extension. Easily fixed with a quick .bat file that reads
ren*.jpg *.webm
cut and paste those sweet sfm animation cakes back in the anon pile and sort it out.

**Comment by Bionus** [comment]
Followup in issue #495
