### ISSUE TITLE
[v4.1.3] Sources Being kept for new installs

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#394]
So uh, the hours I spent adding sources manually (Like pages 1- god knows what from the Top booru list all in my grabbe) Just got scattered.

Is there any way to prevent this for future updates, either manually on my side, or just making sure everything isn't erased on a new installation?

It'd be nice to have this software installed as either an update to an existing version rather than a fresh install you see.

Also, Just letting you know that with as many sources as I had added (Like almost everything for every booru that wasn't a mindless image dump without tags) you do get slowdown on search. Possible to look into optimizing against lag or something in future updates I guess.

**Comment by Bionus** [comment]
Manually, if you go to
```
C:\Users\Nicolas\AppData\Local\$USERNAME$\Grabber\sites
```
And then you can backup all the "sites.txt" files which contains the list of all the sources.
You can also add many sources at once in the same way.

This file should however not be overwritten on a new install, so I'll investigate this.

> Also, Just letting you know that with as many sources as I had added (Like almost everything for every booru that wasn't a mindless image dump without tags) you do get slowdown on search. Possible to look into optimizing against lag or something in future updates I guess.

You mean like a normal search, not a download, with only a few sources enabled? If you enable them all it's pretty normal it will get slower the more sources you have. If it's a constant count of enabled sources though, it's not normal.

**Comment by theHubi** [comment]
So far my sources were also deleted/overwritten with every update. But I suppose I can copy sites.txt and rename it into sites.backup to do this manually then.
Same thing is with favorites from previous versions and "kept for later" tags. But I suppose these are not as important.

**Comment by SultrySamthepennanceman** [comment]
I've only ever been getting the source removal, and have never lost my
favorites tags set henceforth, I think you might ave found something.

**Comment by SultrySamthepennanceman** [comment]
Just to note, I've been having the source reset since I could actually add
sources, so yeah.
