### ISSUE TITLE
How to compile this?

### ISSUE THREAD

**Issue by Spaghetti-Cat** [Bionus/imgbrd-grabber#396]
Hello, I'm trying to compile this under linux but I can't find any Makefile. The linux binaries on your website are for 64-bit only, which I can't run.

**Comment by Bionus** [comment]
The whole process is described on the Compilation wiki page :
https://github.com/Bionus/imgbrd-grabber/wiki/Compilation

tl;dr
```
sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
sudo apt-get update -qq
sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qtscript5-dev qtmultimedia5-dev libpulse-dev
sudo apt-get install qt5-default qttools5-dev-tools
qmake Grabber.pro
make
```
The four first are for the Qt dependencies, the fifth (qmake) to generate the Makefile(s) from the .pro file, and the last one the make.

Feel free to ask here if you run into any issue, or just to tell me if everything went ok :smile:

**Comment by Spaghetti-Cat** [comment]
Thanks for your help. I didn't even realise there was a wiki, usually there's a link to documentation in the README.

Anyway, I built it successfully, but when I run it an error message pops up saying "Aucune source n'a été trouvée. Auriez-vous un problème de configuration ? Essayez de réinstaller." (Even though I removed French and Russian translations from `Grabber.pro`). If I run with `Grabber -d` the same dialog displays but there's no debug output on STDOUT.

I guess it can't find any "sites". I looked in the code and I think it searches for sites in the "sites" directory. So tried copying `release/sites` to where `Grabber` is, but that didn't help.

Am I supposed to have a `settings.ini` file somewhere? It's not generated when I run `Grabber`.

**Comment by Bionus** [comment]
Indeed, that's something I forgot to explain in the wiki.
The "languages" and "sites" directories, as well as a "setting.ini" (can be empty, run `touch settings.ini` to generate it) file must be alongside the Grabber binary (you can also copy the "words.txt" file if you want auto-completion). Everything can be found in the release folder.

**Comment by Spaghetti-Cat** [comment]
There! Now the program starts. Thank you :) This looks like a very nice program.
