### ISSUE TITLE
Languages Not Showing

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#402]
I think this is another OS X specific thing. It seems that pretty much everything is working, but I can't seem to get the list of languages to load, nor can I change the language from the settings ini.
![](https://cloud.githubusercontent.com/assets/5648875/8494601/023e8808-212c-11e5-9d49-05054f7a0d15.png)

When I click the down arrow, there are no languages to choose. Any idea why? I played with `optionswindow.cpp` to see if changing the directory would help, but it didn't seem to change anything. Not sure why they wouldn't just load right up. If there's a way to completely bypass this and default the langauge to English, I'd be completely satisfied with that as well. I think it's just failing to find the files and so it uses the default French.

**Comment by barryanders** [comment]
Update: I changed `QDir(qApp->applicationDirPath()+"/languages")` to `QDir(savePath("/languages"))` and now I got them to show up. It did not, however, change the language.

![]()

**Comment by Bionus** [comment]
That's a possible fix, but wouldn't it also be possible to bundle the languages with the binary file? Putting the "languages" folder beside the executable would theoretically make `QDir(qApp->applicationDirPath()+"/languages")` find it, even in an app bundle, wouldn't it?

I'll change the folder for all platforms to savePath() just in case (as well as update the Windows installer as well).

**Comment by barryanders** [comment]
The official binary is at `Grabber.app/Contents/MacOS/Grabber` but I thought that `QDir(qApp->applicationDirPath()` would be the folder where `Grabber.app` was rather than just `Grabber`. I went ahead and tried putting the languages folder in with `Grabber` and that didn't fix it either. I will keep experimenting though, as your original code should work just fine I would think.
