### ISSUE TITLE
Image Command is a Blank Line in Commands.sql

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#403]
While setting up a LocalBooru, I noticed the image part of the commands setting is not showing up in the generated commands.sql file. I'm using:
`INSERT INTO posts(creation_date, hash, image, height, width, ext, rating, tags, directory, active_date) VALUES(NOW(), "%md5%", "%md5%.%ext%", %height%, %width%, ".%ext%", "%rating%", " %all% ", "1", "20110619");`

The tags and the file update command are all there. Just the `INSERT INTO posts` is a blank line instead of writing the command.

**Comment by Bionus** [comment]
Indeed, I also get
```
SQL execution of "."
```
Instead of the normal command that should come up. I'll investigate and come back here ASAP when I know the reason (and upload an update if necessary).

**Comment by Bionus** [comment]
It should have been fixed by that last commit.

Note that the wiki also missed one of the commands you have to set (in the "Commands > Image" setting):
```
copy "%path%" "/your/path/to/gelbooru/images/1/%md5%.%ext%"
```

**Comment by barryanders** [comment]
Awesome, thanks so much. It's working now. It's all running flawlessly. No crashing at all.
