### ISSUE TITLE
%all% tags have no separator.

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#404]
I really think this will be the last thing I run into but I noticed that %all% displays the tags with no spaces inbetween each one. Again, not sure where to go to fix it, but I'm sure it would be easy, right? I tested 3.4.1 and didn't see the same problem. I thought it might be in image.cpp but nothing I'm trying is working.

**Comment by Bionus** [comment]
I could reproduce this, but only in the context of the commands (%all% in filenames is working fine).

Also, in the image.cpp file, the place where the contents of %all% is decided (as well as all other tokens) is [line 641](https://github.com/Bionus/imgbrd-grabber/blob/master/source/image.cpp#L641):
```c++
replaces.insert("all", QStrP(details["alls"].join(" "), ""));
```
With details["alls"] being a list containing all the tags. There's no real reason for it to not contain spaces.
Sorry for the messy code, I wrote a lot of this a

I'll investigate again, this one issue looks pretty strange as it only happens for commands.

**Comment by Bionus** [comment]
This should now be fixed.

Note that you might want to use %allo% instead of %all% to make sure of the tag separator as well as the use of the underscores in the tag names (unlike %all% which might contain tags with underscores replaced by spaces, depending on your settings).

I updated the wiki accordingly.

**Comment by barryanders** [comment]
It's fixed for sure, and thanks for the tip on %allo%. I just ran into it because I was experimenting with Gelbooru and discovered that something was really off with the tags after executing a recent download. You mentioned that your code was messy, but I wouldn't know the difference as I'm not very familiar with C++. I know it's an excellent language, I just don't personally have much experience with it.
