### ISSUE TITLE
New Windows snapshot or release?

### ISSUE THREAD

**Issue by MightyBirdy** [Bionus/imgbrd-grabber#405]
When I tried to compilem, qtcreator refused to recognize that there are .ui files in the ui dependency, so I was wondering when there would be a prebuilt .exe available of the latest version. Thanks!

**Comment by Bionus** [comment]
I don't really see why you would need a snapshot as there's been only 11 (very specific) commits since the 4.1.4 version, but [here it is](http://www.bionus.fr.cr/imgbrd-grabber/downloads/Grabber.exe).
