### ISSUE TITLE
Bizzare leftovers

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#407]
For some reason or the other, I seem to be getting .exe files and .com files when I DLL things.

Not too sure why.

**Comment by Bionus** [comment]
Hello,

Does this happen on every download? (batch & normal)
Is the .exe some real application or just gibberish?
Is this the same on all boards?

**Comment by SultrySamthepennanceman** [comment]
Sometimes I get a .exe for DLLs, .Com as a .exe, it's bizzare.

You'd just have to DLL a few things till you get it, I'm afraid.

Sorry I couldn't be any more helpful than I usually am.

**Comment by Bionus** [comment]
Should have been fixed a few versions ago, forgot to close the issue.
