### ISSUE TITLE
Grabber v4.1.4 incorrectly reports all files as existing when using "Get Selected"

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#408]
When using the "Get Selected" function on any image board to generate a download list, Grabber incorrectly reports all files in the list as already existing even if the files don't exist on the drive or have never been downloaded before so no MD5 checksum has been previously stored.

Things I've tried:

- Restarting Grabber on every download attempt.

- Changing the Options -> Save -> "If file already exists" to "Save" has no effect.

- Switching image board sources, also tried using only one source.

- Using %md5%.%ext% or %md5%_%filename%.%ext% as filename formats.

- Deleted md5s.txt from "\AppData\Local\Bionus\Grabber\"

- Doing a fresh installation of Grabber v4.1.4, including deleting the entire contents of the "\AppData\Local\Bionus\Grabber\" directory.

**Comment by Bionus** [comment]
What's the contents of your log file ? (especially the urls, it's located in "Appdata/Local/Bionus/Grabber/main.log")
This problem can happen when image data is not properly fetched and all filenames are detected as ".jpg" (instead of "some_md5.jpg").
Does all sources have this issue or only a specific one?

**Comment by Gaffnet** [comment]
> What's the contents of your log file ?

Here's the contents of my [main.log file](http://pastebin.com/LzR5EaH0).

> Does all sources have this issue or only a specific one?

This bug happens with all sources, whether I have just one selected or multiple sources selected.

Thanks for looking into this.

**Comment by Bionus** [comment]
Thank you for the log, I can see this only happens when downloading images one by one right? (using the Ctrl+click then "Get selected")
I'll fix it ASAP, being in the middle of a Win10 update I have to reinstall all my tools, I'll publish a pash as soon as it's done, it shouldn't take too long.

**Comment by Gaffnet** [comment]
> , I can see this only happens when downloading images one by one right? (using the Ctrl+click then "Get selected")

Yes, that's right.  Ctrl+Click then *"Get selected"* results in the "file already exists" error.

Images selected via *"Get this page"* and *"Get all"* download without any problem.

> I'll publish a pash as soon as it's done, it shouldn't take too long.

Thank you!  I very much appreciate your work!
