### ISSUE TITLE
Can't install 4.1.4 on win 10: Internal Error:ExtractTemporaryFile: Thefile "" was not found.

### ISSUE THREAD

**Issue by maslos** [Bionus/imgbrd-grabber#409]
title
Am missing something? I got Visual C++ 2013 Redistributable installed.

**Comment by Bionus** [comment]
Did you install the x86 version? Even if your system is 64 bits, Grabber is a 32 bits application.
The reason for this issue is that Microsoft update the URLs to the MSVC redistribuables, that's why the installer can't find them anymore.
I added a warning on the release page.

**Comment by maslos** [comment]
Ye it worked.
Thank you.

**Comment by Bionus** [comment]
Why reopen if it worked?
I'll close for now, feel free to reopen and add some information if the issue remains.
