### ISSUE TITLE
Endless DLL Hell

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#410]
Sometimes for some of the sources I'm using, it get's stuck on a download, ceasing the entire operation because of that single file.

Is there any way to implement a workaround for future updates, such as being able to go to the source to aquire it manually, or simply avoid said erronous DLL?

It semes to happen for tags that have large entries under them on the bigwig sources.

**Comment by SultrySamthepennanceman** [comment]
Actually wait, it seems to be stuck on DLLING a wweb or a jpg, and the extension for it keeps switching back and forth as if it can't decide what it wants.

What is even going on here?

**Comment by blinky89** [comment]
This is the same issue as the one I just wrote a sec ago.

**Comment by Bionus** [comment]
Let's move to the newest report, issue #411.
I'll look into this ASAP! Sounds pretty critical to me :S
