### ISSUE TITLE
Grabber won't skip images that no longer exist.

### ISSUE THREAD

**Issue by blinky89** [Bionus/imgbrd-grabber#411]
Occasionally an image will be removed from paheal, but the thumbnail is still there. This makes the batch download stall on a file called thumb that cycles through extensions infinitely. If you could make it skip these automatically or maybe add a right click option on the batch download screen to skip the current image, that would be great!

**Comment by Warriors-Blade** [comment]
Is that what is causing grabber to stall at a certain number all the time?

**Comment by Bionus** [comment]
That would also explain issue #410.
I'll look into this ASAP, as it's a pretty critical bug if you can't download anymore just because of a buggy image (actually it should already give up after trying all extensions, but seems like it doesn't).

**Comment by Bionus** [comment]
Closed in 4.2.0 (issue #448).
