### ISSUE TITLE
Imageboard timeout

### ISSUE THREAD

**Issue by blinky89** [Bionus/imgbrd-grabber#412]
Some websites will temp ban you when you repeatedly connect over and over in a short period of time. Maybe you could add an option to wait after every set number of images have been downloaded.

**Comment by Bionus** [comment]
Do you have an example of such website so that I can reproduce, implement and test such feature? :smile:
I have [yande.re](https://yande.re) in mind which blocks simultaneous downloads, but it's not connections (as long as you keep it under 5, it won't block you).
