### ISSUE TITLE
Can't Next Page when search keyword enter nothing

### ISSUE THREAD

**Issue by MoeLin** [Bionus/imgbrd-grabber#414]
when i enter nothing to search,the page is display as 1 of ? , and the next page button is disabled,
but the version 3.x can next page.
Ver 4.1.4

**Comment by Bionus** [comment]
Indeed, I can reproduce this issue on [behoimi.org](http://behoimi.org).
Which source did you use?

**Comment by MoeLin** [comment]
konachan.com

**Comment by Bionus** [comment]
In that case it's fixed in 4.1.5 as well (currently uploading).
