### ISSUE TITLE
update 4.1.5 from 4.1.4 lost Qt5WinExtras.dll

### ISSUE THREAD

**Issue by MoeLin** [Bionus/imgbrd-grabber#415]

**Comment by Bionus** [comment]
I didn't notice it was required.
I just uploaded a second release which includes this file, sorry for the inconvenience.

You can find it here: [Grabber_4.1.5_2.exe](https://github.com/Bionus/imgbrd-grabber/releases/download/v4.1.5/Grabber_4.1.5_2.exe)
