### ISSUE TITLE
Crash on page 2 of pool

### ISSUE THREAD

**Issue by geezer13** [Bionus/imgbrd-grabber#417]
on page 2 of pool:1536 (not a pool tab, yes I know it's not the "right" way to view pools) the program crashes to desktop. Because I have session restore enabled, it crashes again on restart. I'm using 4.1.5 on Windows 10.

**Comment by Bionus** [comment]
Which source are you testing this on? I just tried on danbooru with no issues on version 4.1.7, using "pool:1536" and page 2.

The "crash on restart" will hopefully be fixed too (it allows you not to restore the last session in case of a previous crash).
