### ISSUE TITLE
Image search results and downloads not functioning correctly with certain sources.

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#422]
Grabber shows a single image result when using gelbooru.com and zerochan.net as sources.  And turning off "Merge Results" will show the normal amount of image thumbnails but the exact same image thumbnails are shown for nearly all subsequent pages.

The "chan" and "idol" sankakucomplex sources don't display any image results.

With tentaclerape.net, when images are queued using the "Get selected" function, the image thumbnails are downloaded instead of the full size images.

I was using Grabber v4.1.6, and then tried the recently posted hotfix version of Grabber and the model.xml provided [in this thread.](https://github.com/Bionus/imgbrd-grabber/issues/421)

Tried a completely fresh installation of Grabber, deleting all Grabber-related files, then using the hotfix Grabber and xml file with no luck.

**Comment by Newspeak0404** [comment]
For me, i can able to search normally on gelbooru but they are just downloaded as thumbnails, not full images and sankaku does not work at all even doesn't show the results or thumbnails

**Comment by Bionus** [comment]
@Newspeak0404 see issue #421

**Comment by Bionus** [comment]
All of these issues should have been fixed in the 4.1.7 release, feel free to tell me if there are still problems.

**Comment by ExiledLife** [comment]
Not sure if this is related. Trying to view an image from sankaku complex returns an error in another language with error 203.
