### ISSUE TITLE
application downloads less pictures than results shown

### ISSUE THREAD

**Issue by miniwabestcat** [Bionus/imgbrd-grabber#424]
using Grabber 4.1.7
searching for tags on gelbooru.com nets you the correct amount of results, but when downloading (the task created by clicking on "get all") it retrieves less pictures

http://imgur.com/a/jLkQz **NSFW**

in the first picture you can see i get 1041 results, but then when downloading (second picture) i get only 252 pictures

edit apparently this happens on every source

**Comment by Bionus** [comment]
Did you make sure to set the images/page to 42?

The recent problems with Gelbooru blocking its API currently forces us to set this value manually.
While I'm working on the next version which should set it to 42 automatically, if you want to get all images you'll have to set it in the table after clicking "get all".

**Comment by miniwabestcat** [comment]
yes i tried with 42 and still get less pictures than results

**Comment by Warriors-Blade** [comment]
I have the same issue, I checked the xml and it is set to 42.

They really don;t want us to have any convenience eh?

**Comment by HanabishiRecca** [comment]
Just set images per page to 100 or less, this temporary fix the problem.
