### ISSUE TITLE
Grabber crashes with more than 20.000 images at once

### ISSUE THREAD

**Issue by theHubi** [Bionus/imgbrd-grabber#427]
I know you've optimized Grabber to run on very low-end hardware, but it seems more and more bugs are showing up for people with higher-end hardware (in this case me).
If Grabber has to download more than 20.000 images, it starts, loads all the pages and dies before downloading a single image.

It also seems the "Download Selected" button gets more and more buggy:

1. Downloading more than 20.000 images via "Selected" button crashes Grabber
2. Using "Selected", closing the batch-window and then pressing selected again does not open the Batch-window anymore.
3. Maybe it's just me, but did you make Grabber to not go above 300MB RAM? Cause I think a cache overflow is the problem here.

*P.S: Still working on learning C++, Bionus, but work's pretty busy right now. I hope I can finish the basics this year still.*

**Comment by Bionus** [comment]
> Downloading more than 20.000 images via "Selected" button crashes Grabber

You mean the "Download selected" button or "Get selected" button? I'm guessing the latter as performance-wise it's quite hard on the system. In that case, how did you get 20.000 images in there? Did you Ctrl+click them all?

> Using "Selected", closing the batch-window and then pressing selected again does not open the Batch-window anymore.

This time I guess you're talking about "Download selected" though. I just tried to start a selected download, close the batch window and press the same button again with no issue? Did you have a lots of pending batches at that time or anything special that could help me reproduce the crash?

> Maybe it's just me, but did you make Grabber to not go above 300MB RAM? Cause I think a cache overflow is the problem here.

No, I didn't put any RAM limit on the program, it's just that now it pretty much never requires more than a few hundreds mo of RAM to function now.

**Comment by theHubi** [comment]
I was talking about the "Download selected" button in both cases.
I've been messing around with the files a bit and think I have found the reason:
If there is a previous install of Grabber that has not been removed completely, so there's one or two files lingering around somewhere, they interfere with the newer version's batch downloader.
If I go from a fresh install of 4.1.7, the issue does not show up.
So this issue might already be solved since the new 1.7.

Since Grabber is finally running inside my Qt, I'll play around a bit and see if I can give you some pinpoint locations on bugs if I find some.
