### ISSUE TITLE
Build on Arch Linux: recipy for target 'crashhandler.o' failed.

### ISSUE THREAD

**Issue by Tmplt** [Bionus/imgbrd-grabber#430]
I'm trying to compile this on an Arch Linux system. I have installed what is required to generate a makefile with `qmake Grabber.pro`, but when I run make I get the following error:

```
source/crashhandler.cpp:13:53: fatal error: client/linux/handler/exception_handler.h: No such file or directory
  #include "client/linux/handler/exception_handler.h"
                                                     ^
compilation terminated.
Makefile:1169: recipe for target 'crashhandler.o' failed
make: *** [crashhandler.o] Error 1
make: *** Waiting for unfinished jobs....
```
However, there is no `client/`..? I tried to mirror the `apt-get` commands for `pacman`, but none of the commands downloads anything to the working directory (the project's folder), right?

**Comment by Bionus** [comment]
The google-breakpad dependency seems to be missing from your system.
The easiest way to get it working is to simply get rid of it: just remove or comment the
```
CONFIG += use_breakpad
```
line in Grabber.pro and re-run qmake & make.

You can also try to download and configure breakpad but that's really not worth the work. :smile:

**Comment by Tmplt** [comment]
Thank you, that worked.
