### ISSUE TITLE
[Request] Option to make the image viewing area black or very dark instead of pure white.

### ISSUE THREAD

**Issue by Warriors-Blade** [Bionus/imgbrd-grabber#432]
I attempted to see if there was a way to make the image viewing area black/dark and have had no luck.

Could we please have a option to do so?

It is quite hard to see due to getting snowblind.

**Comment by Bionus** [comment]
What do you mean "viewing area"?
Currently the program is as close to the standard Windows look&feel as it could be.

Would your suggestion be to add an option to have a theme such as this?
https://github.com/ColinDuquesnoy/QDarkStyleSheet

![theme](https://raw.githubusercontent.com/ColinDuquesnoy/QDarkStyleSheet/master/screenshots/QDarkStyle%20example%201.png)

**Comment by Warriors-Blade** [comment]
Sorry I forgot to mention I only use windows in High Contrast Black since normal windows hurts the eyes.

Grabber is mostly in black in this mode except where the images are displayed when you search , its in the inner square.

https://imgur.com/efxfYgr

**Comment by Bionus** [comment]
I see. I guess I forced a background color by mistake at some point, cancelling the high contrast mode. I'll remove this background or find a way to also set a high contrast background in the 4.1.8 update.

Sorry for this :)
