### ISSUE TITLE
Options crash

### ISSUE THREAD

**Issue by HanabishiRecca** [Bionus/imgbrd-grabber#434]
Program crashes every time when applying options.

**Comment by Bionus** [comment]
What do you mean "applying options"?
You mean when you press the save button in the settings window? What operating system are you on?

**Comment by HanabishiRecca** [comment]
Yes, every time pressing OK in options window. Changes saved but program crashes. Win10

**Comment by ItsSohma** [comment]
I saw @MasterPetrik mention in another issue that it was no longer relevant so I may go through some of these and leave a note saying the same.

This one seems no longer valid for the current version.

**Comment by Bionus** [comment]
Yes, given it was never reproduced and is more than 2 years old, I believe it could be closed indeed. :+1:
If the issue persists in the last version, feel free to re-open or comment here with more information.
