### ISSUE TITLE
Redownloading existing

### ISSUE THREAD

**Issue by HanabishiRecca** [Bionus/imgbrd-grabber#435]
Batch from gelbooru redownloading most of existing files.
Mask %md5%.%ext%

**Comment by Keyarose** [comment]
If the redownloaded files have different extensions this is probably the same as issue #425

**Comment by HanabishiRecca** [comment]
Yes, seems the same.
Additional issue appears when program doesn't see difference between jpg and jpeg exts.
I think program must force rename .jpeg extension to .jpg

**Comment by Bionus** [comment]
>  I think program must force rename .jpeg extension to .jpg

Indeed, but I don't think any source serves JPEG files though? (and when trying to "guess" the extension, JPG is tried first)

> as a temporary fix, looks like if set "If a file already exists" option to "Don't save", existing image will be "ignored" in batch.

Yes, but by doing that you're also giving up on the possibility of having two times the same file in different directories.
