### ISSUE TITLE
Error 203 when viewing images from chan.sankakucomplex.com

### ISSUE THREAD

**Issue by ExiledLife** [Bionus/imgbrd-grabber#437]
If you click on an image it opens up the image and does not display anything except the tags and the buttons at the bottom and it an error pops up with error code 203.

**Comment by konecat** [comment]
I just noticed that and I know what's the problem.

Program wrongly thinks images are at c.sankakucomplex.com while in reality they are in cs.sankakucomplex.com. It also wrongly assumes all extensions are .jpeg when in reality they are .png or .jpg.

This needs a correction, let me see if I can do a quick-fix myself.

**Comment by Bionus** [comment]
Indeed, the fix that was done a while ago was to replace `i.sankakucomplex.com` by `is.sankakucomplex.com` which are actually the paths for [idol.sankakucomplex.com](https://idol.sankakucomplex.com/).

You can fix that by editing the `model.xml` file for Sankaku and replacing
```
/i.sankaku->/is.sankaku
```
By
```
/.sankaku->/s.sankaku
```
Which will make the correct replacement.

**Comment by oldfan13672** [comment]
Dear Bionus,
I found the source code of the project and find the model.xml file which I replaced with the replacements you suggested. I am unsure though of how to use the model.xml file to replace the faulty chan.sankaku file. Please help as I would greatly appreciate it.

**Comment by Bionus** [comment]
@oldfan13672 you're not supposed to get the source code. The `model.xml` file you have to edit is located at :
```
C:\Users\%username%\AppData\Local\Bionus\Grabber\sites\Sankaku
```
