### ISSUE TITLE
sankaku complex

### ISSUE THREAD

**Issue by NoobIV** [Bionus/imgbrd-grabber#439]
![error](https://cloud.githubusercontent.com/assets/15866183/11175868/d39cb54c-8c15-11e5-9e9c-6726e5e9b0df.png)

sankaku not download any image, or download miniature, please how to fix it D:

**Comment by Bionus** [comment]
You cannot set the images/page on Sankaku to anything else than "20" for the moment. They just keep adding and adding more security, and block any request giving them a different limit.

I'll try to use their new API (the one they use for their Sankaku Black app) and include it in a future release. For the moment, you can just force the "Images per page" value to 20 and it should do the trick for the regex source.

*PS: I haven't seen such Windows style in a while. Is that a real 2000 or a theme?*

**Comment by NoobIV** [comment]
is Windows 1996 ( ? , is a high performance Windows 7 , sorry do not know how do regex source trick
and sorry for my bad english

**Comment by Bionus** [comment]
You just have to set the "Images per page" value on the table to "20" for Sankaku Complex downloads.
It's set to "200" in your screenshot.

**Comment by NoobIV** [comment]
i put in 20 image por page and download in miniature :S

**Comment by NoobIV** [comment]
![1c](https://cloud.githubusercontent.com/assets/15866183/11232104/17ccc774-8d8e-11e5-9389-d07b4455cb78.png)

**Comment by Bionus** [comment]
This should have been fixed in the 4.1.8 release.
