### ISSUE TITLE
Please help with the chan.sankaku errors

### ISSUE THREAD

**Issue by oldfan13672** [Bionus/imgbrd-grabber#440]
Hello Bionus,
I have tried to use the grabber for downloading from chan.sankaku, and when I click on image previews I get an error 203. I know you have posted fixes for source code, but I do not understand how to use those as a novice to github. I would appreciate it if you could incorporate the fixes for chan.sankaku into a separate version like Grabber_4.1.8 or such. This seems to be a fairly common issue on the forums now and most of us lack knowledge for extensive coding. Thank you for your help and I hope this works for everyone. Here is a screenshot of what happened by the way. 
![image](https://cloud.githubusercontent.com/assets/15882032/11202785/2a895e30-8ca9-11e5-90f9-4c9be8c22ccb.png)

**Comment by Bionus** [comment]
Hello, the fixes are not for the source code but directly in your settings files as stated in issue #437. Ass for your screenshot, see issue #439.

For the 4.1.8, I'm working on it and it should fix the most common Sankaku errors and a few other bugs.

I'm closing this issue in the meantime as it's a mix of the two mentioned above, feel free to elaborate on these.
