### ISSUE TITLE
R34.Paheal downloading Thumbnails

### ISSUE THREAD

**Issue by reikitsune** [Bionus/imgbrd-grabber#442]
for some reason grabber is downloading the thumbnails instead of the original files from Rule34.Paheal. Everything else is downloading fine. Currently using 4.1.7 on Windows 7 since 4.1.8 doesn't want to install.

**Comment by Bionus** [comment]
> since 4.1.8 doesn't want to install

What do you mean? What happens when you try to install 4.1.8?

**Comment by barryanders** [comment]
I can confirm running into the thumbnail issue wit this specific website. I'm using 4.1.4.

**Comment by reikitsune** [comment]
It doesn't start the instill process. However, I can see that it is running via Task Manager. 4.1.7 installer is still working tho.

**Comment by Bionus** [comment]
@reikitsune it seems that the file got corrupt when I uploaded it yesterday. I'll reupload it in a few hours, sorry about that.

But since the thumbnail issue has not be fixed by it, I'll investigate it too.

**Comment by Bionus** [comment]
@barryanders it seems that the `|` is not working properly in this case, I'll fix this for the 4.1.9 release this week-end, thanks for the info :D

**Comment by barryanders** [comment]
Nice work. It's always fun to dig through source code.
