### ISSUE TITLE
Using the date token to bypass Sankaku page limit

### ISSUE THREAD

**Issue by oldfan13672** [Bionus/imgbrd-grabber#444]
I was investigating the chan.sankaku source again and found something very interesting.

It seems that non-registered users can view up to 100 pages of any tag, Registered users (cost is free) can view up to 1000 pages of any tag.

Each chan.sankaku page has 14 images per page. That is why when I was downloading images I was only able to download a maximum of 1400 images, because I was a free user and 100*14=1400. Technically speaking with a registered account you could download 14000 images, but there is another bypass for that.

In the standard downloader per page (auto-paging off) should be like this for the tag breasts "https://chan.sankakucomplex.com/?tags=breasts&page=2". The problem with this tag is that there is, even with a registered account a maximum of 14000 images, while the tag "breasts", for example, yields over one million results. I have found a way to bypass all of these for the chan.sankaku channel. Now the current download system for chan.sankaku downloads based on tags and page numbers. But due to restrictions in that form of indexing, the downloader encounters errors.

Instead of showing all results with using page numbers, you can use the search function date:"dd.mm.yyyy" Using this function bypasses view all page limits. Here is the tag "breasts" with the date function in use, and all statistics remain the same except for the date for any tag. The will change depending on the wish of the user, but to download all images found by the tag, date must be used.                                                                                                                https://chan.sankakucomplex.com/?tags=breasts+date%3A20.11.2015&commit=Search

Using date and tags feature for obtaining page numbers and images will overcome the limitations imposed by using only the tag (including necessity for an account). Everything inside quotes is dynamic and everything outside is static.

Thank you for your time and hard work, and I hope this observation helps and can be used to improve.

**Comment by SvyraCosmix** [comment]
Found this out myself too xD
