### ISSUE TITLE
Program doesn't run on Mac OS

### ISSUE THREAD

**Issue by threefcata** [Bionus/imgbrd-grabber#445]
I've successfully compiled the program following the steps in the Mac section in the wiki. Especially I've copied the folders to /Library/Application Support/Bionus/Grabber. However, the program still doesn't run, when I click 'Grabber.app' in the release folder, it pops up a dialog that says

 "Aucune source n'a été trouvée. Auriez-vous un problème de configuration ? Essayez de réinstaller."

I suspect this is the "source not found" message, however I'm confused why it still pops up.

Any suggestions?

Thanks.

**Comment by barryanders** [comment]
I actually just discovered that you don't have to put anything in the Application Support folder. You do, however, have to put the files inside `grabber.app/contents/MacOS/`.

It will work if the files are in the right place. They are put with the Grabber.app file by default in the release folder because on Windows, the files have to be with the Grabber.exe file. But on OS X, they have to actually be inside the app. You can see an example below.
![screen shot 2015-11-28 at 3 40 52 pm](https://cloud.githubusercontent.com/assets/5648875/11454046/96dc4836-95e6-11e5-8707-dd6d11436d5b.png)

**Comment by Bionus** [comment]
Thank you @barryanders!
I have to admit that it's the kind of issue I can't really help unfortunately not owning a Mac. I'll try to install a VM though. ^^

I also saw that you already updated the wiki, thanks for your work!

**Comment by threefcata** [comment]
Thanks! Now it works!

**Comment by GlassedSilver** [comment]
I must be missing something, I can't find anything in the wiki for Mac deployment. :/

**Comment by barryanders** [comment]
https://github.com/Bionus/imgbrd-grabber/wiki/Compilation#os-x
I wrote these instructions.

You will also have to fix a couple of errors that are Mac related only so haven't been added to the source. I'll go ahead and publish it so you can just cherry pick it.
```
git remote add upstream https://github.com/barryanders/ig.git
git fetch upstream
git cherry-pick 1f09303
```

**Comment by Bionus** [comment]
@barryanders don't you want to make a pull request? I'll gladly merge it :)
What kind of mac-related issues were there?

I'll also update the readme to link to your instructions in the wiki :smile:

**Comment by GlassedSilver** [comment]
Cool, that was quick... Just one question: could you provide binaries as well?
I've compiled things before, but I like keeping my Mac lean and don't want to install a bunch of runtimes and obviously whoever works on the code has to come up with a binary eventually anyways.

Just asking nicely, please don't shoot. :)

**Comment by Bionus** [comment]
I don't own a Mac (I tried to install a VM a while ago without success) and don't know much about Mac packages, so I'm afraid I can't currently provide such binaries.

**Comment by GlassedSilver** [comment]
I meant Barry :)

**Comment by Bionus** [comment]
Well I would definitely add Mac downloads to the release page if Barry were to provide them, but I don't really want to bother anyone to recompile and send me binaries every time I make a new release. :smile:

**Comment by GlassedSilver** [comment]
Was merely asking nicely... If Barry feels like it, cool. If not, oh well. :)

**Comment by barryanders** [comment]
[Grabber.app.zip](https://github.com/Bionus/imgbrd-grabber/files/143583/Grabber.app.zip)
This should work out of the box without downloading anything else.

**Comment by GlassedSilver** [comment]
Thanks! :)

**Comment by barryanders** [comment]
That's version 4.2.2. Can't promise that I would stay on top of releases, but I guess I don't mind here or there.
