### ISSUE TITLE
The %rating% token no longer works

### ISSUE THREAD

**Issue by Falord** [Bionus/imgbrd-grabber#447]
This a odd issue since I've check back to version 4.1.5 and it still produces the correct tokens of Safe, Questionable and Explicit from sources that actually use ratings properly. But in later version and the current 4.1.9 for me it produces the token of Unknown from any sources.

I have 4.1.5, 4.1.8 and 4.1.9 installed at the same time and only version 4.1.5's %rating% works as expected. Hope this is not a problem only I'm having with this token. Awesome work those far I must add on this program.

**Comment by Bionus** [comment]
Indeed, I also get only "unknown" by using %rating% on Gelbooru or Danbooru. Strange nobody reported it sooner if it's as you say a 4 versions old bug. Thanks for the info ^^

I'll try to get it fixed for the 4.2.0 version, which should be released in only a few days.
