### ISSUE TITLE
Downloader stuck trying to find correct extension

### ISSUE THREAD

**Issue by oldfan13672** [Bionus/imgbrd-grabber#448]
I am downloading a large batch in particular, and I noticed that on one link the grabber keeps looking for  the correct extension in a loop. The log states that "Image not found. New try with the extension ____", trying the .gif, .jpeg, .swf, .webm extensions infinitely. There is no type of error protocol either so I think that the downloader may be stuck on this for some time.

![https://i.gyazo.com/1aad4e91da86a4b5c004beacafa76927.gif](https://i.gyazo.com/1aad4e91da86a4b5c004beacafa76927.gif)

**Comment by Bionus** [comment]
Indeed, seems like this image is non-existant on the server for some reason, and the program fails to stop after trying every possible extension.

The image in question:
http://rule34.xxx/index.php?page=post&s=view&id=1231815

I'll fix this for 4.2.0, thanks for the info :)

**Comment by oldfan13672** [comment]
No problem, I should be the one thanking you for your devotion to this project and the great amount of time this saves for image collectors and savers.
