### ISSUE TITLE
Where exactly IS the download page/button?

### ISSUE THREAD

**Issue by AngelLilly** [Bionus/imgbrd-grabber#449]
I had to reinstall my windows and didn't save the installer since I thought I'd just get it back from here, but I can't find the download absolutely anywhere and it's driving me insane.

**Comment by Bionus** [comment]
Its here:
[https://github.com/Bionus/imgbrd-grabber/releases](https://github.com/Bionus/imgbrd-grabber/releases)

You have to click "Releases" from the home page. You can also just click the version number in the readme, also on the home page, to access the latest release.
