### ISSUE TITLE
Folder creation bugs

### ISSUE THREAD

**Issue by Falord** [Bionus/imgbrd-grabber#450]
This one, I'm not sure if anyone else has every had this bug happening or even know that it can. I'm using Windows 8.1 and a Window 7 and I found on both that clicking on the "Destination Folder" for a location that has not been created yet and asking it to create the folder, well create an error and the text of this error is not in English in version 5.1.4 - 5.1.9. Same goes for if the folder your downloading a batched job to doesn't exist, it well not create it, but it well still download all the image 100%, then red them out. 

The real problem starts when you use the "Save" or "Save and close" option when you click on a viewed image for a folder that doesn't exist. It well create any "Folder" you choose. Even hard to deleted ones, the system wouldn't let you make normally. 

To re-create this error. Just create Folder destination with a SPACE at the end or just a space and that folder (e.g. "/funny /", "/ /" or "/ / / /funny /" or to be more specific to the programs destination Folder option "C:/Users/Name/Downloads/ARTISTS/test1 /") well be created as long as it doesn't already exist. This folder well report itself when you’re trying to delete it as "Could not find this item". This folder cannot be renamed and cannot be moved. If you somehow manage to rename this folder (I use a CMD command) before removing all files in the folder, all images in that folder well become inaccessible/un-viewable and the folder cannot be delete even with the CMD command I found on a Microsoft help page for space in folder problem in my experience. 

This is CMD command that removes the folders that I found.

rd /s "\\?\D:\bad\folder\path "

example: rd /s "\\?\D:\Sharedata\folder1\folder2 " - note the space after folder2  as per the space in the folder name.

Hope this is just a run of the mile error encountered with programs running on windows. Since this doesn’t actually make the program not work and you can easy remember to check for spaces before using the ‘Save’ option in program for a new folder.

**Comment by Bionus** [comment]
Just to be sure, the folders in question are the ones set **manually** in the options right? Not ones generated with filenames such as "%artist% /%md5%.%ext"?

I'll check both to be sure, thanks for the report :)
