### ISSUE TITLE
mp4 support

### ISSUE THREAD

**Issue by Aelphais** [Bionus/imgbrd-grabber#451]
Some sites, namely Sankaku Complex, host mp4 files. Grabber will only grab the sample image as per the download sample on error checkbox. Any possibility for mp4 support?

**Comment by Bionus** [comment]
Indeed.
Have you run into any other extensions that was not properly downloaded?

**Comment by Aelphais** [comment]
I don't think so. I was doing a bulk download and randomly clicking the ones that had finished. Only noticed one file that was a tiny resolution on accident. Took a minute to figure out why. I'll be sure to let you know if I do find any others though.
