### ISSUE TITLE
no images showing for uberbooru.com

### ISSUE THREAD

**Issue by LazyVidya** [Bionus/imgbrd-grabber#452]
whenever I search a tag with Grabber using uberbooru (runs danbooru v2), no pictures show up and it says "uberbooru.com - Page 1 of ? (20 of ?)"

It seems that https://uberbooru.com/posts?tags=help%3Aapi might have a solution, but I don't really know what i'm doing, so the answer could be obvious to someone like you who knows what they're doing.

Thanks for the help!

**Comment by Bionus** [comment]
I can reproduce the "page 1 of ?" issue, since this source does not give the last page information right away (so the "get all" button works but the display shows "?").

As for the "no pictures show up", I can't reproduce, the thumbnails show up fine for me, even during searches.
