### ISSUE TITLE
linux filenames not working

### ISSUE THREAD

**Issue by andycontrib** [Bionus/imgbrd-grabber#453]
Had no issues with this on windows but the filenames seem to be ignored entirely when actually downloading.

`_%date%_%md5%.%ext%` or anything else outputs the `%md5%.%ext%` default filenames.

in addition, the folder field is ignored when adding a search to the downloads tab, defaulting to `.` every time. It can still be manually changed but this is definitely a bug.

To be clear, the Name is added when using the Get all button, but the folder is not and when actually downloading, the Name is ignored

Running version 4.2.0 and QT 5.2.1 on Linux Mint 17.2

**Comment by Bionus** [comment]
So you're saying that whatever your filename and folder are, it will use `%md5%.%ext%` and `.`?

And when you change both manually in the batch download tab, only the folder is changed properly, and the filename used is still `%md5%.%ext%`?

**Comment by Bionus** [comment]
I can't reproduce your filename issue, but I can reproduce the folder one (batch downloads always added in `.`).

I also noticed that when saved, the filenames get awfully cut at their beginnings, stripping more than their 10 first characters. I'll check that out.
