### ISSUE TITLE
Still downloading only 42 images from gelbooru

### ISSUE THREAD

**Issue by HanabishiRecca** [Bionus/imgbrd-grabber#455]
Still downloading only 42 images from gelbooru in latest relase

**Comment by Bionus** [comment]
What do you mean "only"?
Do you have any screenshot (or .igl) of a batch download that gets only 42 results?

And if you want to have another images/page value (for consistency with other sources for example) you have to login into Gelbooru first.

**Comment by HanabishiRecca** [comment]
Logging in didn't help.
As example, screenshot: http://screenshot.su/img/1c/67/17/1c67171ed3325df2aeea95f37201630d.jpg
If I setting 1000 images per page, it downloads up to 42/1000 images.
If setting 100 images per page - 420/1000.
etc.
Only if set 42 per page - it will download all 1000/1000.
http://screenshot.su/img/d4/ef/d3/d4efd3de1016594987e821f254db6255.jpg

**Comment by Bionus** [comment]
Are you sure the login was successful? When you click the "Test" button, do you get a success message?

Logged in users can use any images/page value they want, up to 1000. Non logged in users are forced to always use 42.
And this totally matches your example. I just tried and I could download 1000 images with a single page.

**Comment by HanabishiRecca** [comment]
Yes ![http://screenshot.su/img/7d/60/c1/7d60c13b656f71821a5d983bff219329.jpg] (http://screenshot.su/img/7d/60/c1/7d60c13b656f71821a5d983bff219329.jpg)

**Comment by HanabishiRecca** [comment]
Fixed by disabling "Use default sources", works well only when Source 1 is XML.

**Comment by Bionus** [comment]
Did you change the sources in the general settings before?
By default it's XML > JSON > Regex > RSS.

I guess if you indeed put the Regex source before XML you'd get this result even when logged in indeed. ^^
