### ISSUE TITLE
"You did not specify a save folder" Errors

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#456]
I've noticed since I upgraded to 4.2.0 that there is something happening with the destination folder. It comes up with a dot and if I try to download, I get this error:
![screen shot 2015-12-15 at 8 59 23 pm](https://cloud.githubusercontent.com/assets/5648875/11830910/43f03006-a36f-11e5-8adc-a8e9232fec6f.png)

This is, of course, predictable given that there is not save folder set, however, every time I try to set one, it doesn't seem to be saving it. Here's an example of the error I get when I try to download from a website after setting a destination folder:
![screen shot 2015-12-15 at 9 01 39 pm](https://cloud.githubusercontent.com/assets/5648875/11831704/a061544e-a376-11e5-92a3-a9c4b917fbe6.png)
While Grabber currently shows the destination folder I chose, if I restart the program, it reverts back to a dot.

I tried editing the settings.ini but it just kept reverting it to a dot for some reason.

**Comment by Bionus** [comment]
If you set the batch download destination folder manually in the table before a download does it allow you to download the batch correctly ? Does the log say anything useful? (I guess not)

I'll try to see where it comes from and push a fix to develop asap. Seems like some folder check is not working properly.

**Comment by barryanders** [comment]
Yes, that did work. I didn't realize you could do that.

**Comment by Bionus** [comment]
Well that's just a temporary solution until I fix the issue but at least you can still use the program in the meantime ^^

It's useful when you have many downloads and they don't all have the same settings.
