### ISSUE TITLE
md5 list fixer is only scanning 100 files

### ISSUE THREAD

**Issue by MadClown** [Bionus/imgbrd-grabber#458]
Whenever I use the md5 list fixer it will only scan up to 100 files and then finish. I checked the md5 file in the Grabber settings folder and it for sure didn't scan all the files.

I'm using 4.2.0.

**Comment by Bionus** [comment]
What filename are you using to import the files?
Is it a simple one such as "%md5%.%ext%" or does it contains sub-directories like in "%artist%/%md5%.%ext%" ?

**Comment by Bionus** [comment]
I just checked and the list indeed seems to stop at 100/n. But actually it properly checks all files, the "100" is actually the completion percentage (my bad).
That will be fixed in the next update, thanks.

**Comment by MadClown** [comment]
I just checked again and you're right, it does scan properly, it's just the percentage that's not right. I must have checked the backup md5s file I created before using the md5 list fixer. Sorry for the mistake there.

**Comment by Bionus** [comment]
Well that was my mistake in the first place to show a stupid indicator such as "percent / total". :smile:
