### ISSUE TITLE
Not accessing Gelbooru

### ISSUE THREAD

**Issue by AnEpicBeard** [Bionus/imgbrd-grabber#461]
I just downloaded the program a few days ago, got everything set up, downloaded lots of images, had a good time.  Restarted my computer because of another install and now at the very least gelbooru will not work as a source.  Sometimes works on the first search but then consistently doesn't work for any thing else.  Uploaded an image that displays what the program displays once you try to search.  My friend is experiencing the same problem (downloaded at the same time)  running the current version.  Have tried uninstalling, restarting, and deleting the files in the roaming folder for a true clean reinstall.  The second image is of danbooru and gelbooru, danbooru still loads on every search.  I did update to .Net framework 4.6 but that was the only major update I did to my system between the initial install and the appearance in the bug.

![gelbooru no can has](https://cloud.githubusercontent.com/assets/16676890/12282580/1bfd3f76-b96d-11e5-8c73-ac24351dffa4.png)
![danbooru gelbooru](https://cloud.githubusercontent.com/assets/16676890/12282770/b83a5e0e-b96e-11e5-95cb-4b3a3754b1b6.png)

**Comment by Keyarose** [comment]
There is an easy fix for this.  Once it stops working open gelbooru in any browser and try to view any image.  It should send you to a wait an view ad page, once the timer is done continue on to the image.  Grabber should then be able to access gelbooru again.  I'm not sure how they track  who has seen the ad page but it seems to reset every day. So if you use Grabber again the next day you have to view it again.

**Comment by AnEpicBeard** [comment]
Ok, thank you for the quick responce

**Comment by Bionus** [comment]
@AnEpicBeard did it fix your issue?
If so, I'll try to find a way to load this advertisement page automatically for the next version, or some workaround.

**Comment by Ketchup901** [comment]
This happens for me as well (and probably everyone else too), if you could add login support for Gelbooru, users could disable intermission ads in their Gelbooru user preferences, so they never have to view an image in a browser.

**Comment by Bionus** [comment]
@Ketchup901 login support for Gelbooru has been added a few versions ago, and I strongly advise using it when using Grabber. You can enter your credentials in the Source settings for Gelbooru.

**Comment by AnEpicBeard** [comment]
@Keyarose yeah it did thanks again, didn't even cross my mind as a possibility.  Love the program.

**Comment by Ketchup901** [comment]
@Bionus Oh wow, I had no idea, thank you very much!

**Comment by Bionus** [comment]
Gelbooru removed their intermission ads end of 2016.
