### ISSUE TITLE
More convenient "Save As" function (request)

### ISSUE THREAD

**Issue by Synchestra** [Bionus/imgbrd-grabber#462]
Love the program, but one thing that annoys me somewhat is that the "save as" function uses Grabber's install directory as the default folder. It would be great if it defaulted to the either the user's favorites folder or just the last used folder.

**Comment by Bionus** [comment]
> It would be great if it defaulted to the either the [...] last used folder.

Indeed, it would be a good idea, as it must be quite bothersome to browse to another folder every time.
