### ISSUE TITLE
Uberbooru Error

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#464]
Not too sure why, but in some cases, I've noticed whenever I download from this source in either batch of single selecte downloads, when it comes for it's turn to be downloaded from, a new download window opens on the existing tallied one, sometimes followed by a crash.

It doesn't happen all the time, but it seemed unqiue, so yeah.

https://uberbooru.com/

**Comment by Bionus** [comment]
So at one point you end-up with two windows containing the link list, speed, pause button, etc. ?
If so that's very strange, especially if linked to one source in particular. I'll check it out, thanks :)
From memory Uberbooru didn't work at all in previous versions though?
