### ISSUE TITLE
e621 no longer working and other bugs

### ISSUE THREAD

**Issue by Falord** [Bionus/imgbrd-grabber#465]
As simple as the title. It shows the number of pages and images under a tag, but no longer shows the images or allows you to download from it. Hope this isn't just me having this issues, because my windows 7 pc also has the same problem.

On another topic quick. Some bugs i've encountered while using grabber.

1. To make grabber crash, use the "Get all" button on any page twice, head to the "Downloads" tab and try to delete the second copy. So far it's has a 100% crash rate for me.
2. For some reason I some how made my favorites permanent. Some no longer update and/or can't be deleted in program. I think my program that cleans up my system now and then (Advanced SystemCare) did something.
3. The first image of every page from rule34.paheal.net source becomes the featured image in preview once you click on it or trying to download the image.

Hope this information proves usefull.

**Comment by arholoke** [comment]
Same here, e621 not working; attempting to download a page just downloads a file named ".net" that contains the source code of e621's homepage. It was working fine on 2/3 and stopped working on 2/4.

**Comment by Bionus** [comment]
I'll see about e621 when I come back next week. They must have updated their website.

1. Indeed, thanks for reporting :)
2. What do you mean can't be updated? Does this also happen when you run the program as administrator?
3. I don't quite understand this one. If there is a repeating image on every page it can be removed in a source's options, but I don't think that's the issue you're mentioning here?

**Comment by Falord** [comment]
Lets see. 
2. Yes even running under administrator mode I can't remove these favorites. When I try to delete them, all thats removed in program by using the delete option is the thumbnail and is replaced with an red 'X'. Most of them can still be deleted normally. But one thing I've notice is the two that I still have that won't delete both have () in there names. Two I've yet to delete a manual way are carrot_(artist) and nighthawk_(circle). After some time, the carrot one stopped allowing the "Mark as viewed" to work.

3. Is a little more odd than you would think. On the actual website (not in program), there's an image that is classed the "Featured image" on browsing any tag. It's always in the left corner under the "Navigation" bar. (In program) The problem is, if you search anything from this sources (rule34.paheal.net) the first image on the page your on, be it page 1 or 69, well be the featured image. During batched downloads from here, it well download the featured image at most once since it was the first image in the batch and ignore the image it replaced. 

Easy way to test this last one is to load this source up and search anything and try the first image in preview. It well not match the thumbnail.

**Comment by Bionus** [comment]
As for your second issue regarding favorites, could it be that they contain parenthesis? If yes, it should be fixed soon (see issue #474).

As for the other one, I could reproduce so I'll try to fix it too for the next update.
