### ISSUE TITLE
Session restore issues and a couple other things

### ISSUE THREAD

**Issue by arholoke** [Bionus/imgbrd-grabber#466]
1_._ Every time I open Grabber, whether using an *.igl file or not, the "the application was not properly closed for its last use" popup appears. When trying to load an *.igl file, if I select Yes, it lists the pages fine. But if I choose No, it doesn't load properly. I've had some issues with it listing the first page correctly, but then start putting \n in front of the tags for following pages. I can't quite tell what exact scenario causes this. When it happens, it seems all the pages are listed twice, first ones with \n, and then the ones that I'm guessing were actually loaded from the file:

![image](https://cloud.githubusercontent.com/assets/17095558/12866095/42c708d4-cc7e-11e5-8679-fd4b7d4f6d76.png)

I've had some other issues with this that I'm having a hard time reproducing consistently, but I'm hoping that they get resolved if the "last use" popup appearing gets fixed, as I think that that abnormal behaviour may be the root of those issues.

2_._ It's my opinion that the "Do you want to start without restoring your last session" verbiage is a bit confusing (I also always used to choose No for this, but I think since version 4.2.0 I have to choose Yes for my *.igl file to load properly. I didn't notice if the wording changed since then). Simply "Would you like to restore your previous session" makes more sense to me.

3_._ Unrelated to my other problem, in addition, when restoring the previous session, Grabber keeps my search terms and page number, images per page, and number of columns options, but disregards the sites I had selected (resetting to just "beh"). I don't really use this feature, but I noticed it was happening, so I thought I'd point it out.

4_._ I just noticed in the options, under Save, for "If a file already exists," I have it set to "Save," but when I download images, Grabber tells me that some already exist, and I know that those ones were definitely not downloaded again. Is this wrong or am I just confused?

5_._ Finally, occasionally I will download an entire page of images with a high page number (e.g. 200) that I would assume none of which are already downloaded. Very consistently, though, Grabber will tell me that out of the 320 images, some already exist (maybe between 1 and 20, usually; I can't test right now since e621 downloading currently isn't working). I think it would be nice to be able to view that list of already-existent images so I can check it myself, as seeing this makes me feel like the program isn't working correctly in that way.

**Comment by Bionus** [comment]
The fact that your application thinks it hasn't been properly closed every time is the most disturbing. How do you usually close it? If you use the red cross, Alt+F4 or File>Quit there should be no issue. Internally there's a value set when you start the program and another one when it closes. In case of a crash, the program wouldn't have been closed properly and the value would remain at the "starting" state.
Is your "settings.ini" file writable? (not read only or in some write-protected location) You can check easily by changins another setting in the options.

1. That's strange, as if your IGL file gets corrupted or something. I'll check out that no error has been added in the format in the latest versions.
2. I changed the format to properly follow your settings. If by default you restore the last session and there's a crash, it will ask whether you want to not restore it. If you don't, it will ask to restore it. Answering "no" will therefore always use your settings while "yes" will do the opposite.
3. Strange too as it should be also stored in memory. I'll double-check.
4. Are you talking about batch downloads or normal downloads when you click on an image thumbnail then click "Save"?
5. Good suggestion. If you believe the already saved images is wrong you can also delete the "md5.txt" file (or empty it) which pretty much remembers everything you downloaded along with their MD5 to prevent duplicates.

**Comment by arholoke** [comment]
I always close the application normally using any of those methods. I just tried changing a setting and it did reflect in the settings.ini file, so I think we should be fine there.

4*.* Batch downloads.

Thanks!

**Comment by Bionus** [comment]
Points 1 to 4 are done. Point 5 moved to issue #919
