### ISSUE TITLE
EXIF tagging

### ISSUE THREAD

**Issue by ToastInMouth** [Bionus/imgbrd-grabber#467]
Hi, is there any way to import the tags from a booru into the image's EXIF tag data? I just find md5 filenames really hard to sort through.

I think there might be a way to do it through some crazy bash scripting, but I'm definitely not competent enough to code one. Unless someone else here is willing to write one real quick.

Maybe there could be a quick feature to tag EXIF data if you have an optional library for it? Sorry if this is the wrong place to request this.

**Comment by ToastInMouth** [comment]
Nevermind, I read a previous issue in which it was noted that EXIF only supports jpg images, and that XML would be impractical to implement or something. Sorry for the bother.

**Comment by Bionus** [comment]
There indeed exists a previous issue on it (issue #258 and some others), and I'm currently working on adding EXIF support. As stated in that issue and reminded here, it's only supported on JPG (and some PNG viewers) so enabling this feature will mean that all downloaded images will have to be converted to JPG.
