### ISSUE TITLE
Some tags wrongly return huge image count 

### ISSUE THREAD

**Issue by Spaghetti-Cat** [Bionus/imgbrd-grabber#469]
Version: 4.2.2
Platform: Arch Linux 32-bit

On the Gelbooru website the "queen's_blade" tag is listed to have ~11,315 images. But if I search for the tag in the Grabber, with Gelbooru being the only source, it tells me there are 188,160 images. This is also what the following invokation returns:

```
$ Grabber -c -t "queen's_blade" -s "gelbooru.com" --return-count
188160
```

Interestingly if I use the `-n` switch it returns an even bigger number!

```
$ Grabber -c -t -n "queen's_blade" -s "gelbooru.com"  --return-count
56627760
```

Another tag with this problem is ":>=" for which Grabber returns an image count of 54600 instead of "3209".

Using the numbers above:
188160/11315 = 16.6
54600/3209 = 17.0

So why are the counts being multiplied by 17?

PS: Huge thank you for this powerful program, double thank you for the linux port, and triple thank you for the CLI :)

**Comment by Bionus** [comment]
So this only occurred for you with these two cases? Other tags worked properly? If so it must come from the special characters contained in them.

The fact that there is a 17 ratio and that the -n changes the result even thoigh there is only one source is especially strange.

I'll check that out when I come back.

**Comment by Spaghetti-Cat** [comment]
Yes, tags like "alia" (91 images) and "assisted_exposure" (1819 images) get the correct count.

I should mention that the wrong count is also reported in the GUI when I search for the tag, not just the CLI.
