### ISSUE TITLE
[Request] Middle click close tab, forward/back mouse button for next/prev page

### ISSUE THREAD

**Issue by herpaderphurr** [Bionus/imgbrd-grabber#470]
Would it be possible to implement a "middle click the tab to close it" function like many web browsers have? Being able to use a mouse's forward/back buttons for navigation to next/previous pages of a tag would be nice too, though that's a lot more minor. 

Also, thanks Bionus! Developing and maintaining something like Grabber seems like really hard work.

**Comment by Bionus** [comment]
Hello, sorry for not replying sooner, and thanks for the suggestions.
As for the "middle click the tab to close it" feature, it will be indluded in the next update, it's indeed pretty handy. As for the two others features, it sounds like a good idea but I'm not sure it will be do-able for the next update (or at all, I'll have to check it out).

**Comment by Bionus** [comment]
Well that was easier than expected. Your three suggestions should be included in the next version. ^^

> Also, thanks Bionus! Developing and maintaining something like Grabber seems like really hard work.

You're welcome! It is indeed, but it's also a fun thing to do so I don't mind. Especially since it's now starting to be used (and appreciated). :smile:
