### ISSUE TITLE
Can't remove favorites with brackets in the name

### ISSUE THREAD

**Issue by herpaderphurr** [Bionus/imgbrd-grabber#474]
I can't remove certain favorites, and it seems like it's just those with brackets ( ) in the name. 

I've tried multiple methods of removal: from the image's tags, from the search box when I search from the artist (both these methods seem like they work, and right clicking again lets me choose "Add Favorite" instead of "Remove Favorite" as a context action, but then I check my favorites tab and the tag is still there). Also, I tried from the favorites tab itself. 

Trying to delete a favorite will remove the associated image, but not the favorite itself. 

(If anyone else has the same problem, the workaround is to edit favorites.txt in %localappdata%\Bionus\Grabber)

**Comment by Bionus** [comment]
Indeed, thanks for the report.
It will be fixed in the next version, hopefully all favorites will be able to be deleted correctly then.
