### ISSUE TITLE
chan.sankakucomplex.com failure

### ISSUE THREAD

**Issue by devilwar93** [Bionus/imgbrd-grabber#477]
Hello , reported that from the page 101 on, and any tags leaves no download or display anything, either let me do a massive download, I hope you can help me in that problem, or me proportions necessary settings for that page , thanks

**Comment by devilwar93** [comment]
hello

**Comment by Bionus** [comment]
Hello,

Did you check issue #471? A fix will be included in the next update or you can update the model file manually (see my comment on that other issue)
Note that you need a Sankaku account to access pages further than 100.

**Comment by Bionus** [comment]
Fixed for a while, so I'm closing this issue.
If you want to go further than page 50, note that you'll need a Sankaku account until issue #444 is implemented.
