### ISSUE TITLE
 Can't add image to a favorite with a forward slash in the name

### ISSUE THREAD

**Issue by herpaderphurr** [Bionus/imgbrd-grabber#478]
If I have a favorite with a forward slash in the name, e.g. "mel/a", viewing a picture with that tag and selecting "Choose as image" in the context menu does nothing.

**Comment by Bionus** [comment]
Indeed, thanks for informing me. Seems like this context menu option wasn't passing through the filename validation step.
It will be fixed for next version. :smile:
