### ISSUE TITLE
Tag Result shown different number in gelbooru

### ISSUE THREAD

**Issue by Plasticated** [Bionus/imgbrd-grabber#481]
![1](https://cloud.githubusercontent.com/assets/17470036/13314229/ff01473e-dbde-11e5-8f62-0dc83a898972.png)
![2](https://cloud.githubusercontent.com/assets/17470036/13314232/00f17d16-dbdf-11e5-8973-3df7e9e844e5.png)
I tried to search for the answer but failed.
it doesn't happen to just one single tag. some of the tags too affected. 
the tag result which show the no of page and no of images aren't correct.

**Comment by Bionus** [comment]
Indeed, thanks for the info. The counting was indeed off (by a 42 ratio) on Gelbooru based boards because they base their paging on PIDs.

It will be fixed in the next release:
![gelbooru-hat](https://cloud.githubusercontent.com/assets/882719/13335145/c1ec1618-dc0f-11e5-8a0a-f4d15d1d5d8d.png)
