### ISSUE TITLE
Crashing When downloading over 10000 files?

### ISSUE THREAD

**Issue by AJKproductions** [Bionus/imgbrd-grabber#484]
Previously today, i download 10000 images (by setting the limit to 10000) and later i wanted to continue downloading the rest of images, with the same tag, so i increased the limit to 20000. But then it crashed. It got all the page urls, but when it tires to download all the pages, it crashes. Any help?

**Comment by Bionus** [comment]
Which source did you try to download from?
When you say "It got all the page urls, but when it tires to download all the pages" you mean images right? Did it crash right after the end of loading the images' urls? (right after the first loading bar filled up)

I'll try to reproduce this when I get home.

**Comment by AJKproductions** [comment]
The source i download from is e621. And it gets all the pages (which i assume means it goes onto the site and gathers all the static image urls), then when it goes onto actually downloading the images it crashes. From the main log file, it looks like it recognises about half the previously downloaded images, but then it just gives up and crashes. Would you like me to upload the log?

**Comment by Bionus** [comment]
Let's move the discussion to #547 (sorry for an old update, I'm currently looking into these kind of crashes)
