### ISSUE TITLE
the 4.3.0 does not completely fix the issue of tag result shown

### ISSUE THREAD

**Issue by Plasticated** [Bionus/imgbrd-grabber#485]
the result will have the same issue as previously once using the login in gelbooru option which is needed for us to prevent the "gelbooru - no result" coz of the intermission ads. without the login. it works fine.

**Comment by Bionus** [comment]
I'm not sure I understand what you mean. Are you saying that when logged in, you still get the intermission ads, leading to a "No result" error?
I'll check but using the XML source when logged in shouldn't lead to this.

**Comment by Plasticated** [comment]
the login feature is causing the no of page and no of picture shown result inaccurate. once you login and start searching tags on gelbooru and press next page. the show result of page/pic will go completely off in numbers.

**Comment by Bionus** [comment]
Fixed in three ways in recent versions:
* Gelbooru removed their intermission ads end of 2016.
* Gelbooru updated their API to include the post count.
* If the count is not found, it will be fetched using the "get detailed tag information" setting (in "Sources").
