### ISSUE TITLE
4.30 issues

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#492]
For starters, almost all downloads I've been making recently have resulted on the program crashing if I try to download something, suceed, then exit the program normally, and the crash Prompt window I get when I exit is never in english, Infact, I think it's a different language than the last versions crash window which was still foreign to me.

Rule34.Phaeal.net seems to either be not working, and it also seems to constantly show results from this source when I search tags with little results, like for some reason I will get results from Phael.net that have nothing to do with the tags I searched, and when I add the page to my downloads when this occurs Phael comes with, but it clearly shows an obscenly high images limit which makes it apparent that the download will crash if I download from the errorneous Phael source on downloads.

Lastly, the Help then Project website link on the tool prompts me to close firefox instead of opening the site up in a new tab, and this also happens for clicking the site links on Report an Issue and about grabber.

**Comment by SultrySamthepennanceman** [comment]
Also, the source adding seems to derive from what you put in the search bar and not what you actually searched, so if you click "get all" after putting in and searching a tag it wil show up as blank in the downloads page.

**Comment by Bionus** [comment]
> For starters, almost all downloads I've been making recently have resulted on the program crashing if I try to download something, suceed, then exit the program normally, and the crash Prompt window I get when I exit is never in english, Infact, I think it's a different language than the last versions crash window which was still foreign to me.

Which crash window is that? Is it not this?
![crashreporter](https://cloud.githubusercontent.com/assets/882719/13548818/1577cf08-e2f9-11e5-8939-b223caa3a967.png)

> Rule34.Phaeal.net seems to either be not working, and it also seems to constantly show results from this source when I search tags with little results, like for some reason I will get results from Phael.net that have nothing to do with the tags I searched, and when I add the page to my downloads when this occurs Phael comes with, but it clearly shows an obscenly high images limit which makes it apparent that the download will crash if I download from the errorneous Phael source on downloads.

I'm not sure I quite understand. Do you have an example of such tag that returns the wrong images? I just tried on a fresh version with some random tags and all of them generated the good results/downloads.

> Lastly, the Help then Project website link on the tool prompts me to close firefox instead of opening the site up in a new tab, and this also happens for clicking the site links on Report an Issue and about grabber.

Which OS are you using? This link uses [QDesktopServices::openUrl](https://doc.qt.io/qt-5/qdesktopservices.html#openUrl) which itself uses Windows' internal methods. Does only Grabber have this issue when opening links? Does it also happen when you click links in the image results?

> Also, the source adding seems to derive from what you put in the search bar and not what you actually searched, so if you click "get all" after putting in and searching a tag it wil show up as blank in the downloads page.

By source adding, do you mean this?
![sourceadd](https://cloud.githubusercontent.com/assets/882719/13548885/c0de5c94-e2fa-11e5-9983-c6650a96be21.png)
If so I'm not sure I understand.

**Comment by SultrySamthepennanceman** [comment]
Also, there seems to be some sort of bizzare featured_image erorr where a thumbnail shows a picture but instead of being able to look at it when you bring it up, it takes you to the featured image of a particular Source, normally Phael.

This was in the other version too, bu I forogt ot mention it, but basically everytime the image was brouhgt up I got a picture of Lola bunny's exposed beaing heart being fucked.

**Comment by SultrySamthepennanceman** [comment]
![2016-03-04 19_05_43-grabber crash reporter](https://cloud.githubusercontent.com/assets/12085184/13548970/56b39bd2-e2f4-11e5-8cc9-08f46d54ac1d.png)
This is what I get when the Download then exit crash occurs.

I'm using Windows 7 Home Edition. Currently using firefox as I type this. (Waterfox is my deault, though this shouldn't change anything)

As for finding the featured image error, you'd probably want to search a total of 2 tags, have merge results on, and click through the thumbnails until you end up with something that clearly isn't what was shown in the thumbnail.

Sorry, the Source addign thing is where if you search a tag in the search bar, backspace the stuff you put in the search bar, then click get all, the stuff added to "downloads" will appear blank and it shows that the stuff added to "downloads" comes from what's in the search bar as of current and not from what you actually searched

**Comment by SultrySamthepennanceman** [comment]
As for the example tags that cause my foreign text crash windows here.
[New folder.zip](https://github.com/Bionus/imgbrd-grabber/files/159955/New.folder.zip)

Give me a minute to find the featured image search error.

**Comment by Bionus** [comment]
For the featured image, you just have to set the "always ignore" to 1 in the source's settings, that should fix it.

**Comment by Bionus** [comment]
For the featured image, you can replace Shimmie's `model.xml` by the one [here](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/develop/release/sites/Shimmie/model.xml) and it should fix the issue.

**Comment by HellPol** [comment]
Hello. It does not work on Sankaku Complex. When you try to find pictures, writes no result.
Thank you for the program

**Comment by SultrySamthepennanceman** [comment]
Ah, just found out what the askign t oclose browser error was.

It seems that Grabber will open the site up in a new tab ONLY on the browser you have set as your default, and not the one you currently have open and are using.

Which is why it was asking me to close down firefox, because waterfox was my default.

**Comment by SultrySamthepennanceman** [comment]
OH GOD

FAVORITES OPEN ON THE FAVORITES PAGE CAUSING A HUGE MESS, IT DOESN'T OPEN IN A NEW TAB WHEN YOU CLICK A FAVORITE 

DEAR GOD
![2016-03-06 21_21_03-grabber](https://cloud.githubusercontent.com/assets/12085184/13557136/7ebb6b76-e3e1-11e5-8acb-f8f307840ac9.png)

I'M PRETTY SURE THIS WAS UNINTENTIONAL GIVEN THAT CLICKING GET ALL GIVES ME THIS ON DOWNLOADS USING IT THIS WAY

![2016-03-06 21_21_03-grabber](https://cloud.githubusercontent.com/assets/12085184/13557140/a6a86544-e3e1-11e5-8030-15588cc11639.png)

If it isn't, then you know, fix it, but it is kind of neat.

**Comment by SultrySamthepennanceman** [comment]
![2016-03-06 21_22_39-grabber](https://cloud.githubusercontent.com/assets/12085184/13557179/4508a956-e3e2-11e5-8f3e-2296c5f94f37.png)

Whoops, duplicate

**Comment by Bionus** [comment]
I'm pretty sure it's always been this way though?
Left clicking favorites on the favorites tab show the results for that tag since last time, on the same tab.

**Comment by Bionus** [comment]
But in your screenshot it doesn't look very convenient though, since you have a lot of favorites. I'll add a scrollbar and a split pane.

**Comment by SultrySamthepennanceman** [comment]
Eh? sicne when? Whenever I clicked on a favorite on the favorite menu it'd open a new tab with my favorited tag that it searches for me, now I get this little window that opens up on the favorites tba itself with my search, and clicking "get all" seems to give me the links on downloads but they are all coming up as zero, compared to when I search the tag normally, so it migh tnot be working or there's something I'm not used to here.

Also, Just got a session crash and I couldn't help but notice It can't seem to recover my lost session.

I've tried it about 5 times but it doesn't seem to kick it, I even waited for some of them to see if it was that odd crahs where I have to wait on the recovery menu then press yes to get back my lost session but to no avail.

This is the second time I've pretty much lost a session.

**Comment by Bionus** [comment]
Pretty much since I added the favorites tab :smile:
However, the "Get all" button should work, I'll check it out.

If you haven't restarted without crash, the last session is stored in the "restore.igl" file in "%localappdata%/Bionus/Grabber". How did you get the program to crash?

**Comment by SultrySamthepennanceman** [comment]
I have a 2.1Gb folder of crashes, hold up.

**Comment by Bionus** [comment]
You only need to upload the last ones, or the ones of various sizes. Most of them must be the same I guess. :)

**Comment by phantom-zwei** [comment]
greetings, look've been using your app for a long time, but in recent versions have noticed that the search has stopped working, it does not go beyond the first page after the second page change displays the message "no result" and about any label and site. I have tried uninstalling the program, reinstalling. and follows the same result.
![screenshot_1](https://cloud.githubusercontent.com/assets/17708800/13578463/e85365d0-e476-11e5-82bf-6ef0052283cc.jpg)

**Comment by Bionus** [comment]
@phantom-zwei if it only happens on Gelbooru, I guess it must be the ads page. Did you try logging in or just clicking the blue Gelbooru link? It should open the ad page in your browser and then Grabber should work fine again. If it also happens on other sources, could you upload or paste your `main.log` file here?

@SultrySamthepennanceman while reworking the favorites tab I think that you never saw this feature because you may have your "hide favorites" setting set to a low value. This settings hides the favorites if the number of results is above it. So every time you loaded a page the number of results was above it, therefore hiding the favorites.

**Comment by phantom-zwei** [comment]
Clicking on the blue link, go to the page opening the default browser,
and if .. about everything, sankaku, gelbooru, danbooru, rule34, etc ..

ah .. and I do not see the file in the directory main.log grabber

**Comment by SultrySamthepennanceman** [comment]
Also, I found a new bug on a fresh install.

Clicking "Options" doesn't go back to the window that prompts you to put in
the deault grabber settings which set the naming scheme for download
images, file directory etc... on a new installation, it exits it and puts
you on Grabber without providing you the option of choosing the defaults
meaning you'd have to reinstall to get them to show up again.

Just to reword it, when you install grabber (After having wiped it from
program files and from Appdata) (So basically a fresh installation of
Grabber) and that window comes up prompting you to set the reccomended
defaults, clicking the options menu brings up the programs options so you
can manually set things for hte program, but it exits that default settings
window so you can't go back to it after clicking "options" which is
counterproductive, (and probably not intentional) because you can't choose
those defaults, and because you may have gone to "options" to see what it
is, or to add something like a proxy then go back to the window to confirm
your defaults before using the program.

Also, default Sources button for source window when?

**Comment by SultrySamthepennanceman** [comment]
I seem to have encountered a problem with the usage of the restore session option being set in grabber if the session itself is what causes the crash.

Basically, I've set in options for the program to start with previous session, but that session causes a crash, and so I get an infinite loop of never being able to access grabber because it just crashes, and I can't seem to figure out how to change this option so I start with a fresh new session that  won't send the program into infinite crash limbo.

Help.

**Comment by Bionus** [comment]
Could you please send me your current `settings.ini`, `tabs.txt` and `restore.igl` files?
It will help me pin down the reason of your crash.

Afterwards, you can delete (rename if you don't want to lose information) them one by one to see if it fixes it:
- `tab.txt` contains your currently open tabs
- `restore.igl` contains your saved download sessions
- `settings.ini` contains all your settings (I don't advice deleting this one directly, you may not want to lose your config)

**Comment by SultrySamthepennanceman** [comment]
[tabs.zip](https://github.com/Bionus/imgbrd-grabber/files/170522/tabs.zip)

**Comment by Bionus** [comment]
Thanks, I can indeed reproduce with this. When loading Grabber with these, I can't even click the "Do you want to start without restoring your last session?" and directly gets unresponsive. After some time, I could click "no" then when loading the "Downloads" tab, it would get unresponsive for a while again.

I believe that it comes from your tremendous amount of batch downloads and sources.
I'll investigate to see where this lag comes from and try to get rid of it.

What's the reason for you to constantly have so many batch downloads? (maybe this could be prevented by some feature I could add?)
18,000 batch downloads really is a lot.

**Comment by SultrySamthepennanceman** [comment]
Long story short, I'm currently in the process of adding EVERY BOORU EVER to this.

Or at least, I'm in the process of adding all the ones found on The booru project.com and have made it up to page 7.

However, I'd like to point out the program seems to have an issue with adding Shimmie based boards, which I've recently discovered and am currently investigating (Listing the ones that don't work more or less) I'll get back t oyou on it later, as I'm not quite there yet and it's something I've been saving.

Also, is the program 64bit? you might want to make that so, (did I ask this before ages and ages back? I forgot.)

**Comment by Bionus** [comment]
Adding every booru should not be a problem (maybe some slow initial loading time, a few seconds more, and slow loading for the "sources" window), but what about the 18K batch downloads?

No, the program is not 64bit because that would mean I have to make it both 32 and 64bit (to support all users) and for now I don't really want to support both at the same time, and there wouldn't be much to gain.

**Comment by SultrySamthepennanceman** [comment]
I'm fairly sure some of the files (It's always fucking Phael) is the default value it returns as a retardedly high number when it shows up as a result on a search yet actually has no results to give from the tag searched.

So yeah, it's prbably not 18k like you think.

Anyhow, deleted the restore.igl, everythings fine, and it's not the first time I've had a bad search that resulted in crashes, it's just that it looped as a result of me having the restore session option set in the program's options like I said.

**Comment by Bionus** [comment]
No, by 18,000 I meant that you had 18,000 unique batch downloads, not images. If I were to start the download and get all the images it would be something like 400,000 images (which is not a problem if it were from only one download).
This resulted in Grabber generating 18,000 lines in the batch downloads table, and 18,000 progress bars (which I assume it didn't like so much, as I had the same issue before).

> Anyhow, deleted the restore.igl, everythings fine, and it's not the first time I've had a bad search that resulted in crashes, it's just that it looped as a result of me having the restore session option set in the program's options like I said.

In the next update it shouldn't happen, I'm working on a fix so that the window happen before anything else and saying no won't reload the "restore.igl" file.

**Comment by SultrySamthepennanceman** [comment]
![2016-03-12 20_33_29-options - grabber](https://cloud.githubusercontent.com/assets/12085184/13725170/dae82394-e891-11e5-845c-550f2b9e4e7f.png)

Seems to be a problem with random lines endign up in different lanaugages, you've probably heard this loads o ftimes with crash windows, but I don't think I've ever noticed it here before.

**Comment by Bionus** [comment]
Yeah, it's a new setting that I forgot to translate. It's to keep the original file creation time.

Before, if you downloaded a file that was added to a booru on the 2010-01-01 on the 2016-03-12, it would be downloaded and marked as "Created on the 2016-03-12". If you check this box, images will be saved as "Created on the 2010-01-01".

**Comment by SultrySamthepennanceman** [comment]
![2016-03-14 00_13_22-error - grabber](https://cloud.githubusercontent.com/assets/12085184/13732511/75a983b0-e97c-11e5-9e19-a5556a0f346e.png)

I seem to be getting a number of these on my searches frequently, and they're all in non english.

Not too sure why, search somethign big with merge results on and click aroudn until it shows up I guess, I used Derivative_work for mine, but it's happened before.

**Comment by Bionus** [comment]
It says that it could not load the image and got an HTTP 499 error code.
According to [Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes?oldformat=true), it can be caused by an antivirus, or an unstable connection (connection lost during loading).
Does it always happen on the same board? (uberbooru)

**Comment by SultrySamthepennanceman** [comment]
Not too sure, never paid attention to it, sometimes it happens to images I want to preview, sometimes it goes away after reloading a page.

**Comment by SultrySamthepennanceman** [comment]
Yeah, I think it was Uberbooru that often gives this window.

In other news, It's prett ymuch certain at this poitn, at least for me that the regular recovery of crashed session does not work, and yo uhave to manually get it back up via going to the "restore.igl" in Bionus/Grabber folder, I've been frequently having less and less sessions the program does not restore after a crash.

Additionally, in the event of a session that crashes on using the "Download" option, and using a workaround where you use "download selected" for the individual links until you find the problem, I've noticed if you do this then try to save the session after a sucessful download it seems to crash.

What I used was the tag "worms", Get all, then began to download them, which resulted in a crash, so I used Download selected instead for these, which worked, then when I moved onto Gelbooru, It crashed.

Attemtping to do this again, but instead using download selected on Gelbooru worked fine, and the same crash happened in reverse with the links prior.

Repeating the first "download selected" choice then trying to save the session as the .igl also causes a crash.

![2016-03-17 12_11_14-grabber](https://cloud.githubusercontent.com/assets/12085184/13845672/68dc22ae-ec39-11e5-8624-82d56b15e7b5.png)

But yeah, fix the restoring of sessions because it no longer works automatically, yet is still possible through the .igl file that is made in Bionus/Grabber in most cases.

**Comment by SultrySamthepennanceman** [comment]
Adding a new source to Grabber automatically selects all sources as active on completion, which when combined with a large ammount of sources causes slowdown.

Larger sized searches for tags that have many submissions/potential results results in utter crashes wheras tags with less submission/combined tags that provide more results give more, there is a possibility of searched sources beign ignored after a cerain point, but that may be due to lack of tags on the more niche booru's.

I've recently been adding Shimmie sources to my sources, and have noticed that only some of them work, wheras other do not for some reason, with the only thing I can note that they have in common is that most of the one's that don't work all (i think) don't have that homepage with the search bar (The difference between a booru's first page with the search bar then when you're on the booru and the address bar says the " booru's address/posts"

Additionally, I've added so many sources that the program now crashes on either merged or singular searches, which you said wouldn't happen even with that many sources added.

How do I give you my sources so you can replicate this?


Shimme sources I've had no luck with adding.
http://skycow.us/shimmie/
http://www.tentaclerape.net/ (works???)
http://angelhq.net/post/list
http://gallery.burrowowl.net
http://furry.booru.org/
http://booru.touhouradio.com/post/list
http://www.prequeladventure.com/fanartbooru/ (shows Tags, no results)
http://wh40kart.im/ -Works but thumbnails galore (Might have something to do with the fact it has that Homepage screen that isn't on booru/post/list if I were to guess.)
http://booru.showderp.com/post/list
https://www.fluffybooru.org/ (works)
https://www.bittersweetcandybowl.com 
https://www.atfbooru.ninja/
https://whatistheexcel.com/wooobooru/ (Working???)

http://booru.my-hi.me/
http://karabako.net/
http://thedoujin.com
https://lolibooru.moe/
