### ISSUE TITLE
WebM "semisupport" no longer working in 4.3.0

### ISSUE THREAD

**Issue by micnorian14** [Bionus/imgbrd-grabber#495]
After updating to 4.3.0 imgbrd-grabber no longer downloads webms as .jpg files (which I didn't mind using a quick script to rename)

I know WebM isn't officially supported anyway but it was good enough for me. It now downloads the ~60kb preview .jpg instead of the direct WebM. I would like to think I can use a different manner of source type (like json or xml first) but I am timing out meow. 

PS - I can only ever download the first 42 images of any author? I have to manually change the batch queue to the next page to get 42 more.

**Comment by Bionus** [comment]
Which source did this happen on? From what you said (42 images) I believe it must be Gelbooru.

> I know WebM isn't officially supported

It is, as well as possible formats (swf, mp4, etc.), and I just successfully downloaded a bunch of webm as .webm files (directly using %ext%) from 4.3.0. I tested on Gelbooru, Danbooru, and Sankaku.

As for what you say about the 42 images, of course you can download more, you can download all of them at once if you wish (that's pretty much what this tool has been initially created for after all).
When you click "get page", it will only download the first page, but you can either click "get all" to get all the results of the search or manually change the "Images limit" setting for your download in the Downloads tab.
From what you say, it sounds like you have both "Images per page" and "Images limit" set to 42, hence the 42 results. Just set the "Images limit" to something like 420 to get the first 10 pages of results.

**Comment by Bionus** [comment]
Another reason for your 42 results bug on Gelbooru might be the intermission ad page. Either open the page manually once to unblock your IP or login to Gelbooru in the sources settings.

**Comment by Rektis** [comment]
I think micnorian14 was specifically referring to rule34hentai.net. 
imgbrd grabber downloads WebMs on rule34hentai.net, which runs Shimmie 2, as a JPEG thumbnail of the first frame. 

In this ticket (https://github.com/Bionus/imgbrd-grabber/issues/393) he claims that it was possible to rename the correctly downloaded WebMs, that were renamed to JPEGs, back to WebMs and get a working file, but this isn't possible in 4.3. In 4.3, it doesn't download the WebMs correctly for me either. IIRC, it also didn't work for me on that site in previous versions of imgbrd-grabber.
Image formats download fine, though.

**Comment by Bionus** [comment]
Indeed, I totally missed that comment for some reason. Had I known about it, I would have fixed it sooner.
I'll look at this issue with rule34hentai.net, thanks.

**Comment by Rektis** [comment]
Alright, only one problem left: It's grabbing the full WebM data correctly, but the extension is wrong (JPEG instead of WebM).
