### ISSUE TITLE
Can't save images at all, javascript tokens incorrect

### ISSUE THREAD

**Issue by hamc09** [Bionus/imgbrd-grabber#497]
I've used this great program before with no problems on a previous machine, but when I installed 4.3.0 on this one, I couldn't get the program to save any images no matter what I did. Running Windows 10, 64-bit. I uninstalled it and I guess it left its config files behind, so when I installed 4.2.0 instead the settings were all there, and it all worked perfectly.

That was using just `%id%.%ext%`, though. What I'd like to do is actually use the javascript naming method, but the tokens the program tells me are valid are apparently not. I'm trying to use this string:

`search_1 + ' - ' + ( "0000000" + id ).slice(-7) + ' - ' + copyright + ' - ' + character + ' by ' + artist + '.' + ext`

In 4.3.0, the program tells me when I try to save this that `search_1` is invalid. In 4.2.0, it's fine. However, the `copyright`, `character`, and `artist` tokens are all unrecognized in both versions and cause images to fail to even load when you click on the thumbnail, much less save.

Sorry if I'm missing some documentation somewhere, but the link the program gives to learn more about the javascript filenaming just leads to the front page here, and my searches for javascript all pulled up old closed issues from 3.*.

**Comment by Bionus** [comment]
Javascript is (very quickly) explained on the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) wiki page, but I doubt it'll be of any help for this case.

For your case, indeed, I added javascript filename validation in 4.2.2, so if you get a previous version it won't tell you that there is an error. However, in 4.3.0, feel free to ignore it and try it yourself if you feel that it's a bug (like this case).
Your javascript filename is indeed valid, it's just the validator that does not know of some tokens for some reason (fixed now).

Here's a fixed version that should fix both your issues (use with a 4.3.0 installation):
[Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/170954/Grabber.zip)

**Comment by hamc09** [comment]
All fixed! No errors and things save as they should, no fuss. Thanks for getting back to me so quickly!
