### ISSUE TITLE
Private Help

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#499]
Well I understand when I get annoying Bionus but for some reason it is still not working.

I tried to be sure to change the pass and hash it, the result is the same, my pass was 1111111.

I dont exactly understand where the option "get blacklisted" is, although i must tell i did not blacklist any tags at all, neither on sankaku nor on grabber.

I think there is now only 1 solution left, you have to help me over teamviewer or skype, as my ideas are ultimately run out now. It is not a problem if i have to wait, aslong you can help me on fixing it.
My Account is fresh so i also didn´t change any options or blacklisted / favorised anything.
when i try ot get the feet tag it shows me still the same number.

Tell me when you could help me or in general if you have any other suggestions.

Thank you

**Comment by Bionus** [comment]
See my email.

**Comment by Bionus** [comment]
Seems like my email can't get through.

> Answering here instead of Github.
> Sure, we can TeamViewer some time next week-end I guess.
> I'll free myself one hour or two to look into your issue.
> What timezone are you in?

Please continue by mail though. :smile:

**Comment by DraGoran** [comment]
i sended you a Mail tell me if you recieved it ^^

**Comment by Bionus** [comment]
I did but it seems you didn't get mine though.
I tried to send it a few times with no success.

**Comment by Bionus** [comment]
Feel free to try out v4.4.0 which fix many Sankaku issues and adds throttling.

For Sankaku, you should use 3s/page, and 180s/failure. With this, you should never hit their limit and slowly but surely download everything (maybe need some limit for images too).
Another option is to just use 180s/failure and hit the limit every 40 or so images. Instead of getting images one by one, it downloads a bunch at once, then stops for 3 minutes.

**Comment by DraGoran** [comment]
as i said i have problems with my e-mail i kind of consider to get g-mail or gmx, however yeah will try and report to you for things^^

**Comment by DraGoran** [comment]
well now its the problem it downloads all pages but only downloads 2000 images on idol.sankakucomplex.com tag search : feet,  , 3385 pictures all in all, i checked option download pictures containing blacklisted tags, hashed and typed in my account info and tried it with the suggested options  with 180 s failure or 180 s failure and  3s page.

if E-mail not works, how about just type in your teamviewer data here so i will connect with you and give you pass and id for the session to administrate my pc, that should be a safe way without getting intruders, i have this weekend time, just tell the timespan , atleast if you still feel for it to help or can save time for me.
