### ISSUE TITLE
'Please solve the issue before resuming the download.' error and crash

### ISSUE THREAD

**Issue by insciq** [Bionus/imgbrd-grabber#500]
What i doing to reproduce bug:
1. Source: gelbooru. Note: I getting this bug NOT only when source is gelbooru, sometimes i got this with other sources
2. Use credentials to login to gelbooru. (but i guess it's doesn't really matter)
3. Name is `%rating% %general%_%md5%.%ext%`. This bug appears ONLY if i use `%general%` in name, but i guess `%all%` will cause this too.
4. Save settings looks like: ![http://i.imgur.com/dEWY9WR.png](http://i.imgur.com/dEWY9WR.png).
I tried other configurations but it didn't help
5. Searching for `nakano_azusa`, `Get all` and `Download`.
6. And getting error ![screen](http://i.imgur.com/7z3nIES.png) After i few times click 'Ok' program crashes (and yes there's suggestion to send logs, but paths are wrong).
I use english localization, but error seems translated by my system, so translated russian text is `Cannot find specified file`.  
Main.log file on pastebin [http://pastebin.com/BpZMsTne](http://pastebin.com/BpZMsTne)
OS: Windows 10 Corporate. 
C++ libs i've installed  
![http://i.imgur.com/iK5vhcC.png](http://i.imgur.com/iK5vhcC.png)

**Comment by Bionus** [comment]
I can't reproduce at all, even after a few thousands images downloaded with your settings, no error.

This is a system error that happens on file write. The few reasons for this to happen is a full disk or an invalid path. %general% and others are properly escaped. Why did you set the "Max length" in the settings? An invalid max length can lead to this issue (the filename not being cropped properly and leading to a full path size of more than 256).
Did you try without setting it?

If it still happens, here's a version that also show the failing file path to check manually if the path is really invalid: [Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/175016/Grabber.zip)

**Comment by insciq** [comment]
Well, problem was in FAT32 file system on my HD, and sure, i have a lot free space on the disk.  
I just downloaded 8k images from gelbooru on NTFS and all ok.  
For some reason FAT32 don't work properly with long filenames, but with short it's ok.

**Comment by Bionus** [comment]
You're welcome. :smile:
I'll look into it though, FAT32 should have the same limits as NTFS for filenames, and if they don't Grabber should support it.

**Comment by PlanetKiller** [comment]
You deleted or moved a file that was previously logged as downloaded. Not the program cannot find it. You have it set to ignore downloaded files, right? San
me happened to me, so how do we delete rhese log files that save which files have been downloaded?

**Comment by Bionus** [comment]
Indeed, that sounds like a possible explanation.
I'll investigate further on this track, since it shouldn't case an error but fail gracefully (if a file that was (re)moved is accessed by Grabber, it must be also removed from the MD5 list, not throw some obscure error).

**Comment by cmdrkotori** [comment]
Got this on Linux, turns out it wasn't trimming the filename somewhere.

Add this to line 1862 of mainwindow.cpp (using develop branch) to fix this issue
```

            // sanitize file length
            QFileInfo fi(path);
            path = fi.path() + "/" + fi.completeBaseName().left(245) + "." + fi.suffix();


```

(I also had to link the develop build against scintilla with `-lqt5scintilla2` instead of `-lscintilla2`. Using Ubuntu 15.04 fwiw.)

**Comment by Bionus** [comment]
I added your fix for Linux, I still have to add some UTests to ensure it properly works though.

> (I also had to link the develop build against scintilla with -lqt5scintilla2 instead of -lscintilla2. Using Ubuntu 15.04 fwiw.)

Yes, the dev branch did not include the neat PR #552 which fixes libs on unix.
