### ISSUE TITLE
Problem with Bulk Download 

### ISSUE THREAD

**Issue by randomhunterdude** [Bionus/imgbrd-grabber#501]
The issue I am having is whenever I try to download in bulk, it doesn't download all of the images. An example of this is with as109 (an artist on gelbooru) who shows to have 1045 posts but when I go to download, it only tries to download 964 images. For some reason the number of images in the top left can fluctuate from 1045 to 964 depending on the amount of images displayed per page and the thumbnail size. 

Screenshots:

Tags Tab
[capture](https://cloud.githubusercontent.com/assets/17836674/13760456/99a3e7aa-ea09-11e5-9645-e2b75d75bb98.PNG) (NSFW)
[capture](https://cloud.githubusercontent.com/assets/17836674/13761076/d0ad64bc-ea0c-11e5-8a99-a3cc74957fb3.PNG) (NSFW)

Downloads Tab 
![capture](https://cloud.githubusercontent.com/assets/17836674/13760328/0183a15e-ea09-11e5-957f-bd73695478f6.PNG)

Any help would be greatly appreciated!

**Comment by Bionus** [comment]
Hello,

That's because Gelbooru doesn't know how to properly count images (if I remember properly it actually includes deleted images). If you check that tag manually, there's only 23 pages of 42 images with the last one having 40 images:
http://gelbooru.com/index.php?page=post&s=list&tags=as109&pid=924

`22 * 42 + 40 = 964`

**Comment by randomhunterdude** [comment]
Ok thank you!

**Comment by Axelrhode** [comment]
Right now, for me, it actually doesn't even download all images and says it already exists. It's not even named right too.

![Screenshot (260)](https://user-images.githubusercontent.com/35842812/59149618-0a81c300-8a4a-11e9-899e-6fec615ffe96.png)
![Screenshot (230)](https://user-images.githubusercontent.com/35842812/59149619-0a81c300-8a4a-11e9-98eb-444ab74fe6fb.png)
![Screenshot (229)](https://user-images.githubusercontent.com/35842812/59149620-0b1a5980-8a4a-11e9-832d-0f77eff43cdf.png)
