### ISSUE TITLE
Rule34.paheal is downloading thumbnails again

### ISSUE THREAD

**Issue by ArcanumBerg** [Bionus/imgbrd-grabber#504]
Having googled a similar issue, it seems like it has been brought up and apparently resolved/closed in November. However, recently this issue started cropping up for me again. Downloading from rule34.paheal.net results in thumbnails. Having checked the links from the batch download window, they appear to be as following:

`https://rule34.paheal.net/_thumbs/{md5}/thumb.{ext}`

Replacing _thumbs with _images and keeping the rest of the link the exact same shows the full-sized image. I've checked model.xml for Shimmie, and the Image referer appears as such:

`<Image>/_images/{md5}.{ext}|/_images/{id}.{ext}</Image>`

This issue appeared about a month ago on an older version of the Grabber. I have updated to 4.3.0, and did wipe all information in the %appdata%/Local/Bionus folder, thus getting all the updated model.xml files. Nothing helped, and the issue persists.

Noteworthy is that manually opening a file from Rule34.paheal and using the "Save" button does save the proper, high-resolution image.

EDIT: In Issue #442, it was pointed out that deleting everything after the | should help. It does not.

**Comment by Bionus** [comment]
I can indeed reproduce on 4.3.0, and not on 4.4.0.
So it should be fixed on the latest version. Do you confirm?

**Comment by ArcanumBerg** [comment]
Yep, working as intended in 4.4.0. Also works on other sites with the Shimmie board type.
