### ISSUE TITLE
Crashes on searching the Tag "Church" Missing file? v4.4.0

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#507]
So  I keep getting crashes on the Tag Church for some reason (Non merged view) and when ti crashes, the Crash window doesn't show up and it say's I'm missing a .dll file required for it to show up.

I've tried reinstalling the program but this issue seems to persist.

**Comment by SultrySamthepennanceman** [comment]
![2016-03-30 15_13_34-crashreporter exe - system error](https://cloud.githubusercontent.com/assets/12085184/14145149/a5339d30-f68a-11e5-97e4-f17b2cc9ea52.png)

**Comment by Bionus** [comment]
Seems like the crash reporter has not been recompiled for a while indeed and still uses some old runtimes. It's a shame for a crash reporter to crash though. :smile:

It's not missing a DLL but some Visual Studio C++ Redistributable (I don't remember which though, it's been a while). I'll recompile it and check the "church" issue.

**Comment by Bionus** [comment]
Indeed, it seems like I didn't compile the crash reporter for a long time and it still requires some old Visual C++ Redistributable (the ones installed when Grabber installs are not old enough).

I'll check the "Church" issue and recompile the reporter with updated requirements.
