### ISSUE TITLE
Warning dialog when closing the application.

### ISSUE THREAD

**Issue by Falord** [Bionus/imgbrd-grabber#508]
This is just something been bugging me. If you have multiple tabs open in grabber or a download running, shouldn't it have the option to give you a warn that your about to close the application instead of instantly closing the moment you click on the 'close' button? This would be a nice addition to grabber.

**Comment by Bionus** [comment]
Indeed, there could be a security popup to prevent cancelling downloads or closing multiple tabs.
I'll add it right away.
