### ISSUE TITLE
rule34hentai.net WebMs downloaded with JPEG extension

### ISSUE THREAD

**Issue by Rektis** [Bionus/imgbrd-grabber#509]
#495 fixed WebM data not being downloaded at all on rule34hentai.net (only some thumbnail of the first frame was downloaded), but now WebMs are downloaded as JPEGs. 

You can rename the JPEGs back to WebMs and they work fine, but this is not a feasible solution for batch downloading.

**Comment by Bionus** [comment]
My bad, this issue seems to come and go.
It should be fixed in the next update though, but feel free to tell me if it isn't.

I wish that website didn't return the webm files even with the ".jpg" extension. :smile:
