### ISSUE TITLE
%artist% token not working for chan.sankakucomplex

### ISSUE THREAD

**Issue by Nomahd** [Bionus/imgbrd-grabber#510]
Hi,

The %artist% token sometimes works and sometimes fails and returns the default (anonymous) for images from chan.sankakucomplex. I've tested this a few times and noticed it is not consistent as sometimes an image is properly named in a download session while other times the image cannot find the artist tag and returns anonymous. These are images I've made sure actually have an artist tag on the website.

I've also throttled the download by 1s/image and allowing max 1 simultaneous downloads.

**Comment by Nomahd** [comment]
Just leaving a quick update, other tags seem to fail as well.

**Comment by Gaffnet** [comment]
I'm having this issue as well using Gelbooru.

The filename format I'm using is this:

`%md5% (%rating%) artist-%artist% src-%copyright% char-%character%.%ext%`

However, the tags are all empty if I generate a download list using any of the batch downloading functions.  I.e. Images specifed with "Get Selected", using "Get This Page" or "Get All" etc...  

The tags are only correctly assigned if I open an image in its own Grabber window and use the Save or "Save And Close" functions.

**Comment by Gaffnet** [comment]
Updating my post.

All tags are now appearing as empty and the previously mentioned temporary solution of opening an image in a Grabber window and using the Save or "Save and Close" functions to correctly populate tags no longer works.

**Comment by Bionus** [comment]
Seems related to #608 and should therefore also be fixed in v5.0.0.
