### ISSUE TITLE
Documentation on Commands/Database feature?

### ISSUE THREAD

**Issue by aarqon** [Bionus/imgbrd-grabber#511]
I would like to start using the database feature to track my tags, but I can't find any documentation on it.
What do each of the fields do? What are we expected to put in them? Does this feature even work right now?

I have tried to at least make a test database, but Grabber isn't making one, or even logging that it is trying. There also isn't an option anywhere to explicitly turn this feature on, so it's either disabled or on by default.

What do?

**Comment by Spark-NF** [comment]
It's actually covered on [this wiki page](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru) as an example on how to set it up for a local Gelbooru.

What are you trying to accomplish exactly?
If you want to use a custom DB as long as the tables structure doesn't change too much you should adapt easily from it.

The database commands are executed in this order (for a batch download):

```
before()
for each image
    for each tag
        tag()
    image()
after()
```

Database commands are enabled as soon as you put your database login information in the settings (but I admit adding an "enable/disable" checkbox could be nice).

**Comment by Bionus** [comment]
It's actually covered on [this wiki page](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru) as an example on how to set it up for a local Gelbooru.

What are you trying to accomplish exactly?
If you want to use a custom DB as long as the tables structure doesn't change too much you should adapt easily from it.

The database commands are executed in this order (for a batch download):

```
before()
for each image
    for each tag
        tag()
    image()
after()
```

Database commands are enabled as soon as you put your database login information in the settings (but I admit adding an "enable/disable" checkbox could be nice).

**Comment by Bionus** [comment]
Closing since it's answered in the [wiki](https://github.com/Bionus/imgbrd-grabber/wiki/Commands).

Feel free to comment if you have additional questions.
