### ISSUE TITLE
--user and --password command line options seem to go nowhere

### ISSUE THREAD

**Issue by himselfv** [Bionus/imgbrd-grabber#512]
`grabber --help` declares --user and --password options, but when I use those, it does not seem to make any difference.

Instead, grabber always uses pseudo / pass saved from GUI.

How to reproduce:
```
grabber.com -s "danbooru.donmai.us" -t "banned_artist" --return-images -i 10 -m 10 --user [username] --password [password or hash]
```

Expected result: image links (only visible on danbooru to logged in users).

Actual result: nothing.

User name and password collected from the command line seem to get sent to `Downloader::Downloader()` constructor and stored in `m_user` and `m_password` fields. It does not seem that anything ever uses those fields.

If this is meant to be not implemented yet, I'm okay with that (setting the credentials from GUI works for me), all I'm asking is to document this - add a note to the command line help "(not implemented, set credentials from GUI)" or something like that to spare people the confusion.

**Comment by Bionus** [comment]
> If this is meant to be not implemented yet, I'm okay with that (setting the credentials from GUI works for me), all I'm asking is to document this - add a note to the command line help "(not implemented, set credentials from GUI)" or something like that to spare people the confusion.

It's more like a previously-existing feature which disappeared by mistake when I did the CLI rewrite a while back. I'll add them back in the next version, in the meantime as you said you can user the GUI, even though impractical.
