### ISSUE TITLE
Guessing the extension from tags breaks animated_png

### ISSUE THREAD

**Issue by himselfv** [Bionus/imgbrd-grabber#513]
There's such a thing as animated png which is annotated with tags `animated animated_png`. Latest changes in Grabber make it report this as webm.

Example (SFW): https://danbooru.donmai.us/posts/2250159?tags=animated_png

This is the offending code in image.cpp
```
if ((hasTag("gif") || hasTag("animated_gif")) && ext != "gif" && ext != "webm" && ext != "mp4")
{ setFileExtension("gif"); }
else if ((hasTag("webm") || hasTag("animated")) && ext != "gif" && ext != "webm" && ext != "mp4")
{ setFileExtension("webm"); }
```

The result:
```
grabber.com -s "danbooru.donmai.us" -t "animated_png" --return-images -i 10 -m 10
https://danbooru.donmai.us/data/c189044c5f5f20831f5cabf7c22ebeb8.webm
https://danbooru.donmai.us/data/408534763436faf7ef7a96dca95186bd.webm
...
```

(When you click on such an image in GUI, it is reported as "unable to load (md5).mp4", since GUI tries .mp4 once .webm fails)

Obvious quick fix: 
```
if ((hasTag("gif") || hasTag("animated_gif")) && ext != "gif" && ext != "webm" && ext != "mp4")
{ setFileExtension("gif"); }
else if (hasTag("animated_png") && ext !="png" && ext != "gif" && ext != "webm" && ext != "mp4")
{ setFileExtension("png"); }
else if ((hasTag("webm") || hasTag("animated")) && ext != "gif" && ext != "webm" && ext != "mp4")
{ setFileExtension("webm"); }
```

Though I wonder if (at least some types) of server answer should be trusted more than tags? E.g. if XML query tells us this is "avi", and the tags say "webm animated", shouldn't Grabber just stick with avi? (The example specifically chosen so it would fail atm). It seems more likely that the server knows better and the tag is just not precise, than that this is really webm somehow named and filed as avi and someone bothered to notice and tag that.

I imagine this was done because of less reliable ways of querying (HTTP) where you only know extension of the sample and it might differ from the original one. Maybe there's a way to tell if the source is reliable and skip this (if this was the only reason)?

**Comment by Bionus** [comment]
> (When you click on such an image in GUI, it is reported as "unable to load (md5).mp4", since GUI tries .mp4 once .webm fails)

Indeed, the fallback order seems wrong in the zoom window (it fallbacks properly to PNG during batch downloads).

> Though I wonder if (at least some types) of server answer should be trusted more than tags? E.g. if XML query tells us this is "avi", and the tags say "webm animated", shouldn't Grabber just stick with avi? (The example specifically chosen so it would fail atm). It seems more likely that the server knows better and the tag is just not precise, than that this is really webm somehow named and filed as avi and someone bothered to notice and tag that.
> 
> I imagine this was done because of less reliable ways of querying (HTTP) where you only know extension of the sample and it might differ from the original one. Maybe there's a way to tell if the source is reliable and skip this (if this was the only reason)?

That should have been the case indeed, the original idea was to only try to guess the extension if it is not the same as the thumbnail (the one the full url is usually guessed from). It was originally only a last line of defense for some sources that do not have any way of getting the real extension (and sometimes even allow downloading images with the wrong extension, resulting in WEBM downloaded JPG).

On "reliable sources" as you call them (gelbooru / danbooru), that path should not be reached at all and the fact that it is is definitely a bug: danbooru directly gives the real extension (with its XML source at least, in the `file-ext` field), and on gelbooru the full image path is taken directly from the image's page (`ImageUrl` in the `model.xml` file), or with the XML source directly in the result (with its `file_url` field).

I'll fix that and also add the "animated_png" check for non reliable sources. :smile:
