### ISSUE TITLE
How to download your own favorite list from gelbooru?

### ISSUE THREAD

**Issue by maslos** [Bionus/imgbrd-grabber#516]
Is there a command or something?

**Comment by Bionus** [comment]
Not for the moment, though it's been requested once before. It could be added though.
On danbooru, one can use "fav:usename", but it doesn't work on gelbooru.

**Comment by Bionus** [comment]
In latest versions, you can simply copy and paste the URL in the search field, and the images will be loaded.

For favorites on gelbooru, that would be `http://gelbooru.com/index.php?page=favorites&s=view&id=1&pid={pid}`.

Make sure to replace the ID with the ID of the user whom you want to downloads the favorites. Make sure to force the images per page of your download to 50, too.

**Comment by maslos** [comment]
sory for late reply, holy shit man, thanks alot, it took only a year but it works finally :D

**Comment by maslos** [comment]
Well, it works, at least partialy. Out of around 30k favorites on my gelbooru account, Grabber managed to get only around 16k? I set 50 images per page, both in Source options/downloads and on download list itself.
