### ISSUE TITLE
Merged Results not working?

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#518]
I mean sometimes it doesn't show anything because of too many sources due to the images displayed on result  being so small you can't show them, but it seems this time around, for precise tags that would give results to me even with the ammount of sources I have do not show.

At first I thought it was my tags, but then I searched again without merged images and results came up fine, so I think merged results is broken somehow.

Also, I don't think you fixed the issue of "get all" getting all pages but listing the download que takes the name name from the search bar, and not the search.

E.G search car, click get all then backspace on car so it's not in the search bar and click get all, and you'll notice it coressponds to the search bar and not the actual search you made, which messes up the download if you made this mistake.

Also I think the new update ate my Username and passwords for login to the boorus i've added, is there a possibility of this not happening in the future?

Can we get a default sources button for the sources window? with many sources, it becomes a pain to manually click every one off when you want to say, make a search for something that a source will affect because ofthe nature of the booru it belongs to.

A default button to that window would be of good use, and later on, something to set presets for the sources you want to use for a search I.E select all but Booru's that have SFW content

**Comment by Bionus** [comment]
I believe this issues comes from the fact that before displaying merged results, Grabber waits until all sources have finished loading, and in your case, having so many sources, one of them takes too long to load or fails in some way.

> Also, I don't think you fixed the issue of "get all" getting all pages but listing the download que takes the name name from the search bar, and not the search.

I never indeed, but it's been fixed now (commit ce4c586bb9c7cf4ec9967e62b0847ee48eb5a127).

> Also I think the new update ate my Username and passwords for login to the boorus i've added, is there a possibility of this not happening in the future?

It should not have happened indeed.
You're saying the source was still there, but the credentials have been reset?
Did it happen on all of them, or only some? (that is, behoimi, sankaku and gelbooru only)

> Can we get a default sources button for the sources window? with many sources, it becomes a pain to manually click every one off when you want to say, make a search for something that a source will affect because ofthe nature of the booru it belongs to.

> A default button to that window would be of good use, and later on, something to set presets for the sources you want to use for a search I.E select all but Booru's that have SFW content

I created a dedicated issue for it, see issue #524.
