### ISSUE TITLE
The option Max length in the Save tab is not working

### ISSUE THREAD

**Issue by Falord** [Bionus/imgbrd-grabber#522]
I guess it suppose to shorten the lenght of the filename, if it is greater than the number (by characters or words!?) entered into the "Max lenght" area from the short description it has underneath it. But I have tried it at '1' and it still well not shorten the names of any image I've saved. 

Found this out after trying to move some items to a portable harddrive and got the warning that the filename is to long to move to the destination because of windows filename size limit. Times like this makes me wish I didn't use so many custom tokens to cover so much or that were was a re-tag mode in grabber.

**Comment by Bionus** [comment]
Indeed, by default Grabber tries to fit as much as possible in the filename (default is 260 on Windows). If you try to move it to a subfolder or somewhere with a longer base path you'll hit this wall.

So if you indeed want to have some room maybe you should indeed set it to some lower value such as 240. 1 is way too low and risks you getting filenames such as "C:\.jpg" whatever the actual filename is (which may often lead to file write errors).

After I publish the update fixing this issue during the weekend, you should try higher values such as 100 for your tests.
