### ISSUE TITLE
Missing DLL error

### ISSUE THREAD

**Issue by aarqon** [Bionus/imgbrd-grabber#525]
Trying to run 4.5.0 on Windows 10 and I get an error on start saying that the program cannot start because Qt5WebKitWidgets.dll is missing from the computer.

I have tried running both normally and as administrator with no change.
Previous versions worked fine.

**Comment by Synchestra** [comment]
Same here, and if you download a copy of that .dll file and try running it, it asks for several more Qt5-related .dll files

**Comment by Cotihero** [comment]
Having same issue. Maybe it wasn't compiled with it?

**Comment by Warriors-Blade** [comment]
I am also experiencing the same issue, any way to op out of the needed closed source addition made to 4.5.0?

**Comment by Bionus** [comment]
There's indeed a bunch of dependencies missing, my bad.
I could add all those misssing dll to fix this issue but that would be more than 20mo, so I'll refrain and just disable the video playing feature for now in the 4.5.1 update.
I'll find a workaround to not depend on so many things and add a fix.

> any way to op out of the needed closed source addition made to 4.5.0?

That would be impossible, especially for DLL dependencies, unless you compile it yourself and remove the "webm_support" in `Grabber.pri` (which is what I did for 4.5.1).

**Comment by barryanders** [comment]
I had no problems using 4.5.0 on Mac, of course I'm sure that's because I had to build it which means I have all the dependencies.

**Comment by Cotihero** [comment]
The libraries on Mac aren't separate from the application.
