### ISSUE TITLE
Folder hierarchy in the filename option is broken

### ISSUE THREAD

**Issue by Drakonas** [Bionus/imgbrd-grabber#530]
In 4.5.1 the ability to use backslashes (\) in filename schemes is gone. Example:
        %search%\%artist% - %character% %md5%.%ext%

This worked in 4.4.1. Now Grabber simply saves all the images as if %search%\ is ignored.

**Comment by Drakonas** [comment]
I can confirm that forward slashes (/) don't work either.

**Comment by Bionus** [comment]
Confirmed.
As it's blocking, I changed the status of the 4.5.1 update and am working on a fix right away.
