### ISSUE TITLE
can't install imgbrd-grabber on fedora

### ISSUE THREAD

**Issue by Cryptosodomy** [Bionus/imgbrd-grabber#532]
Hi man , i first tryed by just installing the same package ( what was inside the build.sh was for debian so i tryed as far as i can )
but it did not work so , can you explain me how can i download it for Fedora ? ( I've tryed it on windows and it was very good so , i will be kinda sad if i can't get it there :c )
Thanks !

**Comment by Bionus** [comment]
I believe the whole apt-get part can be replaced by using `yum` can't it?

I don't know what exactly the packages are named though. Seems to be `qt5-qtbase` and `qt5-qtbase-devel`. If it doesn't work you can try `qt-devel` but I think that's for Qt4.

Once Qt5 is installed, the rest is the same:

```sh
qmake Grabber.pro
make
mv gui/Grabber release/Grabber
touch release/settings.ini
```

**Comment by Cryptosodomy** [comment]
Re , so i compiled the program and all seem to work well but now i got this : 
And i can't find the Grabber folder or anything to run it..
so i hope you can help me 


( Salut , j'ai vue que tu etais français mais j'ai quand même fait un message au cas ou quelqu'un aurait le même problème donc j'ai tout fait qmake , make , et à mv ça me met qu'il n'y à pas de fichier Grabber , quand je fait touch après ça marche mais aucune trace du fichier a ouvrir pour ouvrir le programme ou quoi que ce soit , voilà )

**Comment by Flat** [comment]
You'll need to run Grabber from the release subdirectory of the source. e.g. 
```
cd imgbrd-Grabber/release
./Grabber
```

**Comment by Bionus** [comment]
From what I just tried on my VM, it is (using `dnf` and `x86_64` packages), you'll need (maybe I forgot some):
- `qt5-qtbase`
- `qt5-qtbase-devel`
- `qt5-qtmultimedia-devel`
- `qt5-qtscript-devel`
- `qscintilla-qt5`

You'll also need `gcc-c++` (confusingly named package for `g++`) for the compilation.

The whole process is:

```
sudo dnf install -y qt5-qtbase qt5-qtbase-devel qt5-qtmultimedia-devel qt5-qtscript-devel qscintilla-qt5-devel gcc-c++ --best
qmake-qt5 Grabber.pro
make
mv gui/Grabber release/Grabber
touch release/settings.ini
```

Then the executable should be present in the `release` directory (along settings and other files).

*Note that I had some issue with QScintilla (see issue #546) when compiling so I disabled it.*
