### ISSUE TITLE
[MAJOR] Pulling multiple images broken (buttons do nothing for getting multiple images)

### ISSUE THREAD

**Issue by Drakonas** [Bionus/imgbrd-grabber#533]
When attempting to click Get All, Get Selected, or even load the same images afterwards, Grabber attempts to load a URL like such:

        http://rule34.xxx/index.php?page=dapi&amp;s=post&amp;q=index&amp;limit=20&amp;pid=0&amp;tags=kerasu

This should be:

        http://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=kerasu

Umm.. this needs fixing ASAP.

**Comment by Bionus** [comment]
What are you talking about?
The log contains escaped URLs for formatting purposes, but the actual loaded url is not.

I just tried downloaded a batch of images from `rule34.xxx` with the tag `kerasu` and had no issues, all images downloaded properly.

**Comment by Drakonas** [comment]
odd. the program does nothign for me when I try... Maybe I need a fresh install. :/

**Comment by Drakonas** [comment]
I tried a fresh install by uninstalling, deleting the Local Appdata\Bionus folder, and reinstalling... The Get all, get selected, and get page buttons still do absolutely nothing.. nothing even shows up in the logs. Any ideas?

**Comment by Drakonas** [comment]
I am on Windows 10. Would that have anything to do with it?

**Comment by Hrxn** [comment]
Other programs running in the background? 3rd-party firewall, or virus scan, for example?

**Comment by Drakonas** [comment]
I use Avira Antivirus. I also have an adblock running on my Router, but that shouldn't affect anything, I don't think.

**Comment by Flat** [comment]
Did you click the actual start download button after clicking get all?

**Comment by Drakonas** [comment]
... I didn't notice the Downloads tab. I feel like an idiot.. thanks everyone... I'm going to go crawl in a hole now.... ugh.
