### ISSUE TITLE
[Bug] English not being translated in many parts of the UI

### ISSUE THREAD

**Issue by Drakonas** [Bionus/imgbrd-grabber#535]
I dug into the code of the English.ts, and it shows that most (Actually I think all) of the program should be translated... but I see lots of French and lots of English in the actual program. Any ideas?

Screenshots:
![CodeForfilenamewindow.cpp](https://dl.dropboxusercontent.com/u/3907397/img/atom_2016-06-08_23-58-29.png)
![filenamewindow.cpp](https://dl.dropboxusercontent.com/u/3907397/img/Grabber_2016-06-08_23-52-57.png)
![conditionalfilename](https://dl.dropboxusercontent.com/u/3907397/img/Grabber_2016-06-08_23-55-05.png)
![OptionsAreFine](https://dl.dropboxusercontent.com/u/3907397/img/Grabber_2016-06-08_23-56-30.png)
![RenameExistingImages](https://dl.dropboxusercontent.com/u/3907397/img/Grabber_2016-06-08_23-57-18.png)

**Comment by Flat** [comment]
Same issue here. I don't see any unclosed tags or anything either.

**Comment by barryanders** [comment]
I've had this problem before. Don't remember the issue exactly but I can tell you that it should be something you can change on your end. Have you set the language in settings? Otherwise, you may be able to define the language in your settings.ini file. There's a chance that this is a problem with the source but not likely.

**Comment by Drakonas** [comment]
My language is set to English in the GUI, and language=English is in the Settings.ini... I see the text in the source should be English, but it isn't selecting the English text properly.

**Comment by Flat** [comment]
There seems to be an issue in the code for this box, and I would imagine something similar to the other  missing translations.

```
QString::arg: Argument missing: Symboles disponibles : <i>%artist%</i>, <i>%general%</i>, <i>%copyright%</i>, <i>%character%</i>, <i>%all%</i>, <i>%filename%</i>, <i>%ext%</i>, <i>%rating%</i>, <i>%website%</i>, <i>%md5%</i>.<br/><br/><i>%artist%</i> : tags de nom d'artiste<br/><i>%general%</i> : tags d'image génériques<br/><i>%copyright%</i> : tags de copyright, en général le nom de l'anime/manga<br/><i>%character%</i> : tags indiquant quels personnages sont présents sur l'image<br/><i>%all%</i> : tous les tags<br/><i>%filename%</i> : nom du fichier sur le serveur, en général une chaîne alphanumérique<br/><i>%ext%</i> : extension de l'image<br/><i>%rating%</i> : Questionable, Safe ou Explicit<br/><i>%score%</i> : le score de l'image<br/><i>%website%</i> : url du site de l'image<br/><i>%websitename%</i> : nom du site de l'image<br/><i>%md5%</i> : code unique de l'image, composé de 32 caractères alphanumériques<br/><i>%id%</i> : identifiant de l'image sur un site donné<br/><i>%search%</i> : tags de la recherche<br/><i>%search_n%</i> : n-ième tag de la recherche<br/><i>%date%</i> : date d'ajout de l'image au format dd-MM-yyyy HH.mm<br/><i>%date:format%</i> : date d'ajout de l'image au format donné<br/><br/>Vous pouvez aussi utiliser les structures conditionnelles. Pour plus d'informations, cliquez <a href="%s">ici</a>., https://github.com/Bionus/imgbrd-grabber/wiki/Filename
```
Unfortunately I don't know enough about QT to fix it myself.

**Comment by Drakonas** [comment]
I'm wondering if it's the %date:format%

**Comment by Bionus** [comment]
> There seems to be an issue in the code for this box, and I would imagine something similar to the other  missing translations.
>
> ```
QString::arg: Argument missing: Symboles disponibles : <i>%artist%</i>, <i>%general%</i>, <i>%copyright%</i>, <i>%character%</i>, <i>%all%</i>, <i>%filename%</i>, <i>%ext%</i>, <i>%rating%</i>, <i>%website%</i>, <i>%md5%</i>.<br/><br/><i>%artist%</i> : tags de nom d'artiste<br/><i>%general%</i> : tags d'image génériques<br/><i>%copyright%</i> : tags de copyright, en général le nom de l'anime/manga<br/><i>%character%</i> : tags indiquant quels personnages sont présents sur l'image<br/><i>%all%</i> : tous les tags<br/><i>%filename%</i> : nom du fichier sur le serveur, en général une chaîne alphanumérique<br/><i>%ext%</i> : extension de l'image<br/><i>%rating%</i> : Questionable, Safe ou Explicit<br/><i>%score%</i> : le score de l'image<br/><i>%website%</i> : url du site de l'image<br/><i>%websitename%</i> : nom du site de l'image<br/><i>%md5%</i> : code unique de l'image, composé de 32 caractères alphanumériques<br/><i>%id%</i> : identifiant de l'image sur un site donné<br/><i>%search%</i> : tags de la recherche<br/><i>%search_n%</i> : n-ième tag de la recherche<br/><i>%date%</i> : date d'ajout de l'image au format dd-MM-yyyy HH.mm<br/><i>%date:format%</i> : date d'ajout de l'image au format donné<br/><br/>Vous pouvez aussi utiliser les structures conditionnelles. Pour plus d'informations, cliquez <a href="%s">ici</a>., https://github.com/Bionus/imgbrd-grabber/wiki/Filename
```

Where did you get this warning?
I never saw it, but by seeing it now I can tell what's the problem (and fix it), but only for that one window.
It's because `%s`, `%d`, `%i` and some others are tokens for Qt translator, printf-style.

Ass for the others, I'll check them out thanks to the screenshots, but it seems likely to be on-by-one issues (and not some global bug that will fix them all at once).

**Comment by Flat** [comment]
>Where did you get this warning?

It was printed in the terminal.

I also looked into the translate files and noticed there's a string missing for the checkbox "Demander confirmation avant la fermeture de la fenetre" under thee General Options. I couldn't find the string in QTranslate either.

**Comment by Drakonas** [comment]
This doesn't seem to have fixed the problem. ![newscreenie](https://dl.dropboxusercontent.com/u/3907397/img/Grabber_2016-07-02_15-45-42.png) I just built from the latest source.

**Comment by Bionus** [comment]
I beg to differ.
Are you building the `develop` branch and running it from the `release` folder?

![123](https://cloud.githubusercontent.com/assets/882719/16542350/c4b6a88c-40a4-11e6-8e78-8f692f941cf1.png)

**Comment by Drakonas** [comment]
Derp. I neglected to look at which branch the commit was... sorry. -.-

**Comment by Drakonas** [comment]
Well would you explain this then? lol. ![newscreen](https://dl.dropboxusercontent.com/u/3907397/img/cmd_2016-07-02_17-24-27.png)

**Comment by Drakonas** [comment]
https://dl.dropboxusercontent.com/u/3907397/img/Grabber_2016-07-08_21-41-41.png fixed :D
