### ISSUE TITLE
How do conditions function? and more questions

### ISSUE THREAD

**Issue by ThisManzzz** [Bionus/imgbrd-grabber#536]
1. When I add conditions to my filename (eg: %artist%<, "weapon">.%ext%), it always writes down "weapon" without quotes into the filename.
![filename "weapon"](http://puu.sh/pore8.PNG)
I got it to work by adding custom tokens and writing it out like this: %artist%, %weapon%.%ext%. I don't know if this is the intended behaviour though. also commas don't work when using conditions
![custom token](http://puu.sh/ponoW.png)

2. Also "Tags separator" option isn't working in the "Save" section of the options. Neither is the "Replace spaces with underscores" option.
![tags+underscore](http://puu.sh/porGU.png)
**EDIT**: Tags separator works when using custom tokens or %all% with multiple tags.

3. Custom tokens don't work in the "whitelist" section of the "General" section of the options.
![whitelist](http://puu.sh/ponsU.png)

4. One more thing; when using "Conditional filenames", can we make it so a blank entry for the "filename" section uses the default filenaming process?
![example](http://puu.sh/ponct.png)

Will add more if I find them.

**Comment by Bionus** [comment]
1. Fixed by commit b603f6e3080da9582fc35ff8ceb71a2dcea15874, thank you. I'm not sure what you mean by "also commas don't work when using conditions" though.

2. The tag separator works for pretty much all tags groups (artist, character & co. have their own setting though, so it's mainly for %all% and customs). As for "Replace spaces with underscores", it's for within the tags, for example "game cg toosaka rin" will become "game_cg toosaka_rin" (much more explicit if you have multiple tags).

3. Indeed, it's currently plain text (only accepts tags, no groups, like "tag_1 tag_2 tag_3"). Would it be useful to add support for groups? ("%artists%")

4. Why not

**Comment by ThisManzzz** [comment]
Hello, thanks for the reply!

1. "Commas don't work when using conditions," I just didn't know how to word my question. I meant I didn't know how to use commas when a tag in the filename isn't present. Look at the picture.

2. Thanks fam.

3. It would be useful to add support for custom tokens or groups. Also when saving files in folders, custom tokens or groups such as %artists% should make a new folder for its respective artist.

Ex. "D:\Pictures\Booru\Artists\Kerasu" if the artist is kerasu. And using the same naming scheme, save an image as "...\Artists\Animeflux" if the artist is animeflux.
In both cases, the folder name to save the images in is: "...\Artists\%artists%". %artists% being a custom token with artist names.

4. Using the default filename is sometimes useful without having to write it out. Only for blank entries though. Say something like "a blank entry uses the default file naming scheme".

**Comment by Bionus** [comment]
> Also when saving files in folders, custom tokens or groups such as %artists% should make a new folder for its respective artist.
Ex. "D:\Pictures\Booru\Artists\Kerasu" if the artist is kerasu. And using the same naming scheme, save an image as "...\Artists\Animeflux" if the artist is animeflux.
In both cases, the folder name to save the images in is: "...\Artists\%artists%". %artists% being a custom token with artist names.

That's already the case, if you use `Artists/%artists%/%md5%.%ext%` as a filename.
Note that you can use one (and only one for the moment) custom token as a condition, so you could do something such as:
- Condition: `%artists%`
- Filename: `%artists%/%md5%.%ext%`
- Folder: `Artists`

4 was done in commit ffe8ade83aff6e04f7f236e55ae465531a1e783a.
