### ISSUE TITLE
[Request] Saving webm

### ISSUE THREAD

**Issue by Blocki92** [Bionus/imgbrd-grabber#537]
Many imageboards and boorus like [Sankaku Complex] (https://chan.sankakucomplex.com)
are supporting webm and it is really anoying if you download them only the low res thumbnail of it gets downloaded as jpeg
It would be awesome if webm could be supported too!
So i hope, downloading webm will be added too...

**Comment by micnorian14** [comment]
What version are you running? Make sure you have an updated version of Grabber. WebM support has been iterated upon and made fully functional thanks to the big cheese himself. (thanks)

PS - if anyone smart sees this: Are you able to get Grabber to use credentials on Rule34hentai.net? You can't search/download rating:e tags without using your login - but my nothing works in the Login tab!!!

**Comment by micnorian14** [comment]
What version are you running? Make sure you have an updated version of Grabber. WebM support has been iterated upon and made fully functional thanks to the big cheese himself. (thanks)

PS - if anyone smart sees this: Are you able to get Grabber to use credentials on Rule34hentai.net? You can't search/download rating:e tags without using your login - but nothing works in the Login tab!!!

**Comment by Bionus** [comment]
Indeed, while what micnorian14 said is true (webm support has been added and was working with no issues up to now) it seems to be giving up again and downloading samples instead once more.
I'll fix and update as soon I have have some time to do so.

As for login on r34, have you tried
- POST
- /user_admin/login
- user
- pass
No idea about the cookie though.

**Comment by micnorian14** [comment]
Thank you for confirming the issue so quickly! The login settings you mentioned worked: I can now search and download rating:e tagged posts! 

PS - I still have an issue with rule34hentai.net batch jobs not processing more than one page worth (42)
What's even weirder is changing the images-per page or image limit values do nothing. I have to manually change the starting page in the job to process the next page of (42) posts (this has always been a present but I never bother)

If I can't figure it out on my own by tomorrow I'll start a new issue with more info and detailed logs, etc. I just don't want to bug you for simple stuff :)

**Comment by Uriei** [comment]
In rule34.xxx it just downloads the thumbnail
