### ISSUE TITLE
Add imageboard "lolibooru.moe"

### ISSUE THREAD

**Issue by Kaxyn** [Bionus/imgbrd-grabber#538]
I'd love you a lot if you could add lolibooru.moe as an option.

**Comment by TheWallsPlayer** [comment]
I second this. :')

**Comment by Bionus** [comment]
Have you tried adding it as a normal Danbooru board?
I just tried and browsed and downloaded some images successfully.

**Comment by TheWallsPlayer** [comment]
Oh wow, I just tried that and it worked. :)

All the same though, you might want to add it as a source by default, in case users don't know how to do that. The software is unable to determine which type of imageboard lolibooru.moe uses by guessing, as well.

**Comment by Bionus** [comment]
I'm not sure about adding it as a default source since it's contents can be considered illegal in many countries.
But I could make Grabber recognize it automatically as a Danbooru board.
