### ISSUE TITLE
Add a %count% token

### ISSUE THREAD

**Issue by Kaxyn** [Bionus/imgbrd-grabber#539]
Not sure if this is already a feature but I can't find a way to do this.
I want the names of my pictures to start from the number 1 and increment by 1 for each file.
So perhaps a %count% could be added or something.

**Comment by Bionus** [comment]
There used to be a suggestion like this (issue #433) which I had started to implement (don't try to use it though, it won't work).

On the long run, the objective was to have, with the `%search%_%num%.%ext%` filename, something such as:
```
glasses_001.jpg
glasses_002.jpg
glasses_003.jpg
girl_001.jpg
girl_002.jpg
girl_003.jpg
```

The logic is that for a new image, we take all images matching (for example `glasses_*.*`), find the one with the highest number (here `003`), increment it then replace `%num%` with that number, giving `glasses_004.jpg`.

Would that do?

**Comment by Kaxyn** [comment]
As all the images I'm getting have random names, tags, etc. I was thinking just something basic like 1, 2, 3, 4, 5 (incrementing +1 with each file downloaded) as the file name. Would your concept still work here if I just used %num%.%ext%? Also would it be able to not have the 001 and just start with 1?

**Comment by Bionus** [comment]
if it was a global counter, deleting all images and starting again would not reset the counter.
Isn't that problematic? When (or where) should the counter reset?

And while the first folder will have images starting with 1, others will start with much higher values.

**Comment by Kaxyn** [comment]
It would reset once the mass download is complete. If you pause and resume it will continue counting where it left off. If you stopped and restarted then it will overwrite.
