### ISSUE TITLE
Filename problems

### ISSUE THREAD

**Issue by TheWallsPlayer** [Bionus/imgbrd-grabber#540]
Hey! Sorry for being a bother, but if someone could please help me with this, that would be great! :3

How would I go about saving pictures with names that are ordered chronologically, inside a folder labeled as whatever the tag for those images is?

**Comment by Bionus** [comment]
It's doable easily with some filename such as:
`%tags%/%date%.%ext%`

However, almost all images have different tags, so you'll hardly have more than one image per folder using this.

Maybe you should instead use something such as:
`%artist% %copyright% %character%/%date%.%ext%`

(see the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) wiki page)

**Comment by TheWallsPlayer** [comment]
Thanks for replying, and thanks for that link to the wiki, I couldn't find it before.

What I mean, though, is to simply save images in a folder with the name of whatever tag(s) I used to search for those images. Is there a way I can do this automatically, or would I have to create a folder manually each time?

**Comment by Bionus** [comment]
As written in [the wiki](https://github.com/Bionus/imgbrd-grabber/wiki/Filename#available-tokens), you can use `%search%` and `%search_1%`, `%search_2%`, `%search_3%`, etc. :smile:

`%search%` contains your whole search while `%search_n%` contains the nth tag of your search.

**Comment by TheWallsPlayer** [comment]
Oh, nice. Thanks for the help! :P
