### ISSUE TITLE
Quicker Image preview crashes?

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#542]
I seem to be getting a Crash around opening around the 6th image to preview on my results screen.
Often this would happen if I opened peview images too fast one after the other, but now the program does it even when I do it slowly

To test it, open images one by one and minimize them until you get the crash I guess.

it seemed to occur with animated images, so do a search for "animated" and see if that's the cause.

**Comment by Bionus** [comment]
I can indeed reproduce on animated images, but it seems to come from the integrated video player. I'll keep looking to see if it also happens on "normal" static images, but I haven't yet got a crash with them. Have you?
