### ISSUE TITLE
Downloading Starcraft tag

### ISSUE THREAD

**Issue by Herkules97** [Bionus/imgbrd-grabber#543]
I can download the starcraft tag from all websites just fine, if I exclude paheal.net.. for some reason page 6 I think, from that tag crashes the app.. The website is also just slow in general, crashing with any tag, not all pages makes it crash, just some and when you use "get all" that makes it hard..
Don't know where my log is, not in the main folder or sub folders.

**Comment by Bionus** [comment]
I'll investigate and see if I find something. If it's reproducible by downloading starcraft from paheal that *should be* fixable with no big problems.

The `main.log` file can be found in `%LOCALAPPDATA%/Bionus/Grabber` (`C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`).

**Comment by Herkules97** [comment]
So I try for like the 10th time after just downloading every other website's "Starcraft" tag again, for some reason now all the sites had more images to download than 2 hours ago >.< This is really strange. I'm currently at 197/673 and no crashing, don't know why it works now and not the other times. I do not start Grabber with admin rights, which might fix future problems, not sure. It may very well be paheal itself, since it is often slow, not working or straight up offline for hours.

**Comment by Herkules97** [comment]
Main.log seems to only keep the log for the most recent download, which won't help

**Comment by Herkules97** [comment]
[Main.txt](https://github.com/Bionus/imgbrd-grabber/files/324580/Main.txt)
Maybe it do show the crash one, not sure.

**Comment by Herkules97** [comment]
I'm curious why half of the images don't get downloaded and they say they're duplicates, in what way are they checking that? By filename? I saw that it was through md5, so that means it's a certainty that every single "duplicate" is actually the same photo?

**Comment by Herkules97** [comment]
I just realised I can download one time, then download to the same photo again to see if more images are downloaded.

**Comment by Herkules97** [comment]
The after-report is really weird, Says I downloaded 399 files successfully to a folder with 923 before the download and 923 after. I can safely assume the report is always wrong and will just download same set a few times just to see if I get more out of it. I now realise that the different download results, amount of photos, might be linked to the search, since I started the latest download with the same search results as last time.. But still strange why it doesn't take with every photo on sites.. Maybe it can only search for a limited amount of photos on each website..

**Comment by Herkules97** [comment]
Ok, going to stop updating and give up, the reports are always false, tho I tried different things, for some reason the 937 now is stuck on always downloading 923, maybe the sites often delete and add photos and that's why the downloads can vary in amount? The issue that it crashes doesn't happen very often, it was probably something wrong with the site when it crashed on every try. Will try to keep it open for an hour or two.

**Comment by Herkules97** [comment]
Found an Issue that was closed, sometimes it happens, I want to download from paheal because downloading from all sites just crashes the program after a while, but when I check paheal to search on and Get All, it only downloads 70 images, the 70 from the first page.. Not sure what fixed it in the issue since no fix was posted and it was closed. Only one was to put the number of images per page to 20 but that doesn't do anything.. Will try different things, might also be one of those things that fixes itself randomly and pops up randomly. Will edit if anything worked. Don't want to do a new issue if I already have this one, but maybe I'm supposed to.
