### ISSUE TITLE
4k screen compatibility issues

### ISSUE THREAD

**Issue by noname2x** [Bionus/imgbrd-grabber#548]
When using Grabber with a 4k screen (225% scaling), Grabber mostly looks alright. However, image results from a search are tiny and close to unseeable. I'm guessing this is because image thumbnails are not appropriately scaled. Any fix for this would be greatly appreciated!

**Comment by Bionus** [comment]
You're saying the thumbnails are not upscaled so they remain at their default max size of about 150x150? I don't have any 4K screen at my disposition, could you send a screenshot to make sure I understood properly the issue? :smile:

**Comment by noname2x** [comment]
Here's a screenshot:

![4k scale](https://cloud.githubusercontent.com/assets/20175172/16494491/80b2a2ce-3eb7-11e6-9c52-881dc07bedc9.png)

Yeah, the thumbnails display at 150x150, and since 4k screens have ridiculous pixel densities, the thumbnails appear tiny as a result.

**Comment by Bionus** [comment]
The next version will have a new setting, "upscale" (in the "interface" settings) to set the initial image upscaling.
