### ISSUE TITLE
Limited to 1000 pictures  on Sankaku

### ISSUE THREAD

**Issue by Issho-san** [Bionus/imgbrd-grabber#549]
Hello,

My problem is that when I try to download all images (from Sankaku), I only get 1,000 images, even when the artists or the tags have much more.

How to fix this problem?

---

Bonjour.

Mon problème réside dans le fait que lorsque je télécharge l'entièreté des images (je télécharge que sur sankaku) je ne reçois que 1000 images, alors que parfois, les artistes ou certains tag en contiennent bien plus.

Comment régler ce problème ?

**Comment by Flat** [comment]
Can you please post your main.log file by attaching it to your comment? You should be able to download more than 1000 images. Make sure to check the log for any usernames, passwords or other personal data you need to remove before uploading.

I don't speak French sorry, but I've attached google translated for you.

Pouvez-vous s'il vous plaît poster votre fichier main.log en l'attachant à votre commentaire? Vous devriez être en mesure de télécharger plus de 1000 images. Assurez-vous de vérifier le journal des noms d'utilisateur, mots de passe ou d'autres données personnelles dont vous avez besoin pour retirer avant de le télécharger.

Je ne parle pas français désolé, mais je me suis attaché google traduit pour vous.

**Comment by Bionus** [comment]
Sankaku is indeed limited to 1,000 images for non-authenticated users.

You have to create an account on Sankaku (if you don't have one) then put your credentials in the "Credentials" tab in Sankaku's source settings. Don't forget to hash your password.

---

Sankaku est en effet limité à 1,000 images pour les utilisateurs non inscrits.

Il faut d'abord créer un compte sur Sankaku (si ce n'est pas déjà le cas) puis mettre ses identifiants dans l'onglet "Identifiants" des options de Sankaku. Et ne pas oublier de hasher le mot de passe.

**Comment by Issho-san** [comment]
Merci, ça fonctionne :+1:
