### ISSUE TITLE
Current code failing build on fatal error because of missing google-breakpad source files

### ISSUE THREAD

**Issue by Drakonas** [Bionus/imgbrd-grabber#554]
I thought these were removed from the requirements. The instructions in the wiki state to comment out a line to disable breakpad, but said line no longer exists. I have no experience with QT, and I've gotten as far as the below screenshot, but I'm stumped and can't get the libeay32.lib to be recognized. I really want the new translation fix. Do you have an estimate on the next release build? I'm not asking for a date, but if it's any time soon I might as well simply wait for you to build it.

![libeay32.lib](https://dl.dropboxusercontent.com/u/3907397/img/cmd_2016-07-01_23-38-11.png)

I am using Visual Studio 2013.

I am also using this mirror of 2011 breakpad straight from Google Code. https://github.com/AlekSi/google-breakpad-mirror Correct me if I need to use the latest.

**Comment by Bionus** [comment]
`libeay32` is actually OpenSSL.

As all Grabber dependencies, you can either disable it (losing all ability to access HTTPS websites) by removing the `use_ssl` configuration, or install it (the most common install location is `C:/OpenSSL-Win32`, but if you change it make sure to change the `Grabber.pri` file too.

```
# SSL
use_ssl {
    win32 {
        LIBS += -L"C:/OpenSSL-Win32/lib" -llibeay32
        INCLUDEPATH += C:/OpenSSL-Win32/include
    }
    unix {
        PKGCONFIG += openssl
    }
}
```

As for google-breakpad, it doesn't give much so feel free to disable it (it's only used to catch crashes and generate dump files), but if you have it installed and working already might as well keep it.

**Comment by Drakonas** [comment]
Appreciate it. I'll do this when I get home from work. I'm not at all familiar with dependencies in QT. I'm more used to building on Linux where I apt-file search and apt-get install -dev packages. Lol. I've never really built things on Windows.

**Comment by Drakonas** [comment]
le sigh. I didn't know you moved everything to Grabber.pri. Your wiki instructions says to look in Grabber.pro.
