### ISSUE TITLE
Individual image preview won't load after cached

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#557]
I've noticed that if you click an image, close that window, and then click it again, it doesn't reappear. By the way, nice feature showing "file already exists"!
![screen shot 2016-07-02 at 2 11 44 pm](https://cloud.githubusercontent.com/assets/5648875/16542080/ee8143ca-405e-11e6-94d4-cae3bed55a34.png)

**Comment by Bionus** [comment]
Seems to happen only when an image was either in the cache or saved on the hard drive ("file already exists").
