### ISSUE TITLE
Built in Booru

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#558]
Is there any way you can get a built in booru? i would like to be able to download images and have the tags for them added to the booru is that alot to ask?

**Comment by brodycas3** [comment]
i meant so you can view the pictures in you downloaded in the downloader and have them retain their tags and everything
sorry i wasnt specific enough

**Comment by brodycas3** [comment]
kind of like this https://hydrusnetwork.github.io/hydrus/
but its built in

**Comment by Bionus** [comment]
I'm not really sure about this.

I believe it should better be left to another software, such as picasa or a local Gelbooru. Browsing and downloading have many different features to implement (re-tagging, editing, resizing, more advanced search, indexing, etc) and I believe having it stored outside and browsed in a local booru (which is easily feasible, see [here](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru)) be a better idea.

What I thought before was to allow to "search" such local booru the same way we can browse distant ones, but I don't think it would be wise to add a full featured booru directly inside the software (unless it's just something really basic, which is not what is asked here).

**Comment by brodycas3** [comment]
it dont need to be advanced, but i didnt know how advanced tags are

**Comment by barryanders** [comment]
It would be quite an effort to use Grabber locally. It takes a little more know-how, but you can do your own local board, as already mentioned. More details are available in the wiki detailing 3 separate board types. I've really enjoyed using [Shimmie](https://github.com/shish/shimmie2) in the form of a local board, as I feel is just a bit cleaner than Gelbooru and it also has a few different themes including one that mimics the look of Gelbooru 2.0.

**Comment by barryanders** [comment]
I have a local board (shimmie) installed and tried adding it back into Grabber. Everything about it seemed to work which means if you're willing to go through the trouble of making your own board, importing the images into it as described in the docs, then all you have to do is add it as a source and you can use it directly in Grabber as was requested. Although for me, the images didn't show up. Probably a minor thing. The tags were all there, it just said `no result`. I will play around with the XML and see if I can get something to work with it.
