### ISSUE TITLE
[Request] Tab shortcuts

### ISSUE THREAD

**Issue by noname2x** [Bionus/imgbrd-grabber#559]
Hi. I really like that some shortcuts mimic browser tab shortcuts (e.g. Ctrl + T opens up a new tab). I was wondering if other tab shortcuts can be implemented as well? Namely, Ctrl + W to close an open tab, and  Ctrl + L to move the cursor to the search bar at the top. I think it would add a lot.

Thanks!

**Comment by Bionus** [comment]
Why not :+1:

**Comment by Bionus** [comment]
By the way, the official "close tab" shortcut on Windows seems to be `Ctrl+F4` which is already implemented. But it's often asked to also add `Ctrl+W` so I'll put both.
