### ISSUE TITLE
Jump to current download

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#560]
I was wondering if you can make a button that lets users jump the the current downloading image

![https://gyazo.com/95a2f656ed7f292febb48701766abd9f](https://i.gyazo.com/95a2f656ed7f292febb48701766abd9f.png)

**Comment by Bionus** [comment]
I can add a checkbox that can make the scroll follow the downloads when checked.
Would that be good enough?

**Comment by brodycas3** [comment]
That would be amazing
Thankyou
