### ISSUE TITLE
"Too many input files specified" error on compilation in Windows when the directory has spaces

### ISSUE THREAD

**Issue by Drakonas** [Bionus/imgbrd-grabber#561]
```
    moc: Too many input files specified: 'Studio' '2015/Projects/imgbrd-grabber-develop/tests/"' 'Studio' '2015/Projects/imgbrd-grabber-develop/tests"' '..\src\aboutwindow.h'
```

![Screenie](https://dl.dropboxusercontent.com/u/3907397/img/cmd_2016-07-08_21-12-31.png)

I thought your latest commit would fix this, but it doesn't seem to have fixed it. That or there was another entry like it.

**Comment by Drakonas** [comment]
I looked through that command and found this:
        -I"X:/Documents/Visual Studio 2015/Projects/imgbrd-grabber-develop/tests/%ProgramFiles(x86)%/Microsoft SDKs/Windows/7.1A/Include"

**Comment by Drakonas** [comment]
Spaces in the directory name causes it... not sure if you want to fix this.

**Comment by Bionus** [comment]
Indeed, I also remember running into this issue before, but I'm not sure whether this in fixable directly from Grabber's .pro file or if it comes directly from `qmake`.

I'll make some quick tests to see if it's actually just forgotten quotes in the pro file or if there's really nothing I can do.

**Comment by Drakonas** [comment]
I tried adding double quotes in the Grabber.pro and it didn't help.

**Comment by Bionus** [comment]
Well, since quotes didn't fix it and the official position of Qt is "don't use spaces in your project's path", I'll have to close this issue, unfortunately.

**Comment by the-nose-knows** [comment]
@Bionus can you point me to the location where Qt claims this?

**Comment by Bionus** [comment]
Can't find the link, and I don't really remember where I saw that, soryr.
Is the issue still happening, even though the project switched to CMake?
