### ISSUE TITLE
Unable to download from atfbooru

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#562]
Im unable to download more than the first page in http://www.atfbooru.ninja/ (**NSFW**)   Running Danbooru v2.103.1:I6.1

![image](https://cloud.githubusercontent.com/assets/19770864/16864776/7dc8742c-4a2d-11e6-9910-094df90a058a.png)

**Comment by Bionus** [comment]
I just tested and could load all pages with no issues (it used the XML source, which is the default).
The only problem I ran into is that it didn't detect the source type automatically but I could set it manually to Danbooru 2.0.

As for your screenshot, follow-up in issue #565. Even though the last page number could not be loaded, you can still load the other pages, make sure to set the images limit in the download tab if you want to download more pages.

*ex: images per page = 20, images limit = 2000 will download the first 100 pages.*
