### ISSUE TITLE
Grabber not getting total images from Danbooru

### ISSUE THREAD

**Issue by lllllllllllllllllllllllll** [Bionus/imgbrd-grabber#565]
Every other booru seems to work fine, but when trying to get a tag from danbooru it shows as "Page 1 of ? (30 of ?)" pic related http://i.imgur.com/LUacLlC.png

While this is fine if you want to just browse, it cannot download everything of a tag. It will only download the current page when trying to get all.

**Comment by Bionus** [comment]
Indeed, that's an annoying issue as it prevents one from downloading all in one click.
Until a fix is published, you can however manually edit the "images limit" value to the number of images before starting a batch download, so that it gets them all.
