### ISSUE TITLE
Using Ctrl + Shift + Left in the search bar highlights the wrong text

### ISSUE THREAD

**Issue by larry-he** [Bionus/imgbrd-grabber#566]
Ctrl + Left works fine. But when Ctrl + Shift + Left is used, what's highlighted is not the text group to the left of the cursor but the space immediately to the left of the correct group.

Here's an example:
tag1 tag2|[<-- cursor is here]
intended behavior:
After pressing Ctrl + Shift + Left, tag2 gets highlighted.
actual behavior:
The space between tag1 and tag2 gets highlighted.

I'm interested in fixing the issue myself and making a pull request so, for now, don't bother fixing this issue.

**Comment by Bionus** [comment]
Strange, as all those things are supposed to be managed directly by the original `QTextEdit::keyPressEvent` implementation (see [textedit.cpp#L194](https://github.com/Bionus/imgbrd-grabber/blob/develop/src/ui/textedit.cpp#L194)).

If you want to investigate and fix the issue by yourself, then I won't look into this issue for now.

**Comment by larry-he** [comment]
Small update: After some further testing, turns out Shift + Left and Shift + Home doesn't work. The former does the behavior described above, and the latter selects everything.

As for actually solving the problem, I haven't made any progress, but I'll keep at it for now.
