### ISSUE TITLE
[Feature Request] New browsing functionality

### ISSUE THREAD

**Issue by noname2x** [Bionus/imgbrd-grabber#568]
After searching a term in Grabber, when an image is clicked on, it'd be really cool if the left/right arrows could scroll through the images that came up. Perhaps clicking enter or something would save that image to the given folder. It could even pre-load the next few images ahead of time so that hitting an arrow to go to the next one could be instantaneous.

I know that Grabber is currently a download tool more than a browsing tool; although I think I'd use this feature more than downloading them all.

**Comment by barryanders** [comment]
I think this was already requested, or at least a similar functionality with left and right arrow keys on the keyboard.

**Comment by Bionus** [comment]
Yes, that was issue #506. But there's here some new suggestions (pre-loading, saving shortcut).
I believed it to be out of scope but if that many request it I guess I'll add it.

Feel free to complete the existing issue before closing this one @noname2x.
