### ISSUE TITLE
Unlisted booru type

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#570]
Im unable to get https://lolibooru.moe/ to load because it uses MyImouto 1.0.8

**Comment by Falord** [comment]
? I got lolibooru.moe to work. I just started guessing for myself which type worked. I found that just normal 'Danbooru' worked. If still not work, delete the previous attempts and try again.

**Comment by Bionus** [comment]
Yeah, [MyImouto](https://github.com/myimouto/myimouto) is a clone of [moebooru](https://github.com/moebooru/moebooru) which itself is a fork of [Danbooru](https://github.com/r888888888/danbooru).

And they seem to be both compatible with the Danbooru source. If that changes in the future, it should be quite easy to add a new source for them. Until then, you can just use Danbooru as a booru type for their boards.
