### ISSUE TITLE
one tag per line in sidecar tag text file.

### ISSUE THREAD

**Issue by AreFinstad** [Bionus/imgbrd-grabber#573]
could we have an option for the %all% key too use one line per tag? that way we could use namespaces and so on + no no namespace tags with the import function of the Hydrus Client. ( https://github.com/hydrusnetwork/hydrus )

me and some of my friends love your program with how stable it is and just smooth it is. but we also love Hydrus as a manager (downloads are just not there yet sadly). 
so it would be great if you guys had an option like this for your sidecar files.

also note, would it be possible too have the tags too use its namespaces aswell?
like character:charactername or something? all the while splitting up all tags on a line each.

or else we would have too make our own, which we can i guess. like so:

creator:%artist%
series:%copyright%
character:%character%
idol:%model%
booru:%website%
%all% (with line splitting)

final notes. i notice alot of the namespaces of sites just arnt here at all. anyway we could add those ourselfs somehow. keep each booru up-to-date and so on.
there is just soo many namespaces over all the sites, being able too add our own namespaces that the program knows would be great. they are usually numbered i think.

**Comment by AreFinstad** [comment]
seems we got it too work when editing the settings.ini file manually without actions from the UI.

we used the setting "separator=\n" and that split up the tags in general. 
we then removed the empty namespace values and then changed the separate text file settings too:
"creator:%artist%
series:%copyright%
character:%character%
idol:%model%
filename:%filename%
%all%"

all seems too work now with this change, atleast for the times it only has one character/artist/series/idol and so on.
it seems too fail when there is more than one, placing the tags after eachother on the line selected. making this hole hydrus import thing kinda not work for me XD
would need too be one line per for those tokens if possible.

but official support would be great too now!


comment on custom namespaces/tokens.
i noticed that its a "bit" of a pain too make those as it wont grab namespaces itself or use what the site has.

most sites and boorus got the namespaces/tokens split up in id's on the site. why not let us write those in instead of manually placing one tag in the namespace.

it would just do this automatically from the site no matter what if a system like this was used.
then again im just seeing how hydrus does it and i would love for things too be smoother in your program aswell.

**Comment by CloudyChess** [comment]
To expand on AreFinstad's custom namespace / token request, booru's like e621 have a species tag/namespace that does not get parsed successfully by Grabber. In order to have Grabber understand that this is a species namespace a user would have to make a custom token and then add _every_ possible tag under that namespace. That's over 6,000+ possible entries. 

If Grabber could have an option to look for HTML text/code for tags when you go to make a custom token this would be a huge help for booru's that have special/custom namespaces. For example, Grabber could look for the HTML Li class named tag-type-species (for e621) and give anything it finds a species namespace using species:%species%.

**Comment by Bionus** [comment]
Why not, for version 4.7.0 that includes some changes to filenaming mechanics.
Note that in the meantime you can still use JavaScript to do pretty much anything.

As for the additional namespaces (is that Hydrus wording?), it's coming for a later version, more like 4.8.0, as it requires some bigger changes in the current code.
