### ISSUE TITLE
update token list in the wiki

### ISSUE THREAD

**Issue by AreFinstad** [Bionus/imgbrd-grabber#574]
new user here and i want too get the most out of the program, seems your wiki isnt fully up-to-date with latest tokens for filenames, tags and so on.

could you guys update this please?

its also out of date in the help window for filenames aswell.

noticed that you added %url_page% , %url_file% and so on.... maybe there is more, i dont know as they are not listed in the wiki.

**Comment by Bionus** [comment]
Indeed, sorry about that. :smile:
I'll add information about other tokens right now.

https://github.com/Bionus/imgbrd-grabber/wiki/Filename

**Comment by Bionus** [comment]
Done.
