### ISSUE TITLE
Can't login to derpibooru

### ISSUE THREAD

**Issue by reikitsune** [Bionus/imgbrd-grabber#576]
I followed the this guide minus the hashing because it's not in the current version (4.5.3) (https://github.com/Bionus/imgbrd-grabber/issues/494) and still can't login. Not sure if I did something wrong, or if it's the site itself with the program and it having a API feature.

**Comment by CloudyChess** [comment]
I can't seem to get Grabber to log into any booru. If I use the Credentials tab I get 'unable to test' when I enter my login info. If I go to the login tab and enter in my info and either the login url or the site's url I get 'failure'. I'm not quite sure how to use the cookies tab or the cookies line on the login tab so I haven't been able to test that. 

What is the correct settings/procedure we should have for Grabber in order to get it to login?

**Comment by Bionus** [comment]
> I followed the this guide minus the hashing because it's not in the current version (4.5.3) (#494) and still can't login. Not sure if I did something wrong, or if it's the site itself with the program and it having a API feature.

There's no need to login to Derpibooru to access their API. As long as you put the JSON source before others, you shouldn't have any issue downloading stuff.

However, explicit results will be filtered out. If you want to see them in Grabber, you have to put your Derpibooru API key (you can find it [here](https://derpibooru.org/users/edit)) in the password field of the credentials tab.

> I can't seem to get Grabber to log into any booru. If I use the Credentials tab I get 'unable to test' when I enter my login info. If I go to the login tab and enter in my info and either the login url or the site's url I get 'failure'. I'm not quite sure how to use the cookies tab or the cookies line on the login tab so I haven't been able to test that.
> 
> What is the correct settings/procedure we should have for Grabber in order to get it to login?

Most sources pass the login information in the URL (for example, Danbooru with the `pseudo` and `password_hash` fields), which makes it impossible to test if the login information is correct. This "Test" button is here for other kinds of login, such as Gelbooru, where the program has to send a POST request to the server first, then store the login cookies.

So for most sites, you can just put your credentials, hash them if necessary, and "see if it works" (seeing normally blocked images on Danbooru, for example).
