### ISSUE TITLE
Non merged results getting frequent crashes

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#578]
It mostly seems to happen withthe larger more populated tags searched, bu tanyway, how do I give you my sources and crash logs again?

**Comment by Bionus** [comment]
Sorry, I totally missed this issue.

If it still happens on the last version, yes I'd like to at least see the logs, and if possible one of the dumps for that crash. :smile:

Just after a crash, just upload the `main.log` file and the latest `dmp` file from the dumps folder. They are both located in "C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber".
