### ISSUE TITLE
Viewer isn't showing picture when it is opened for the second time.

### ISSUE THREAD

**Issue by Shir01** [Bionus/imgbrd-grabber#580]
Hello.
When the same picture is opened in Grabber's viewer twice it stops being displayed. Here is how it looks:

**First click on the image**
![0a677ab6b0](https://cloud.githubusercontent.com/assets/882719/17703573/77446002-63d2-11e6-8193-f1a97ab1d579.png)

**Second click on the same image**
![0a6789b75c](https://cloud.githubusercontent.com/assets/882719/17703588/89f8ed8a-63d2-11e6-98a7-0542505183cf.png)

Though it seems the image is in the cache as it can be successfully saved from the empty viewer window.

**Comment by Bionus** [comment]
Hello,

It seems to be the same issue as described in issue #557, which is fixed in develop.
I haven't released a new version in a while and this issue is pretty important, so I'll release a new version soon to fix this issue, sorry for the inconvenience. :smile:
