### ISSUE TITLE
Problem with flash (.swf) extension being miss labeled as mp4

### ISSUE THREAD

**Issue by Falord** [Bionus/imgbrd-grabber#585]
This problem only seems to happens on the e621 sources and cause the files in question to not download, but instead show up as an error. To reproduce this, just try to download any flash based animation. Some may download, but many won't.

![problem](https://cloud.githubusercontent.com/assets/16067703/17726143/e68442ce-641e-11e6-9750-66efb0e26254.png)
"Copy link to clipboard" shows the incorrect extension.

**Comment by Bionus** [comment]
Indeed, I could reproduce and I pushed a fix yesterday. It will be included in the next update.
Thanks for the report :smile:
