### ISSUE TITLE
Batch download window

### ISSUE THREAD

**Issue by AldebaraanMKII** [Bionus/imgbrd-grabber#587]
Just a minor suggestion: Could you please add a minimize/maximize buttons to the Batch download window?

![http://i.imgur.com/drdPmzx.png](http://i.imgur.com/drdPmzx.png)

That's the only "issue" i had so far. Everything else is working perfectly.

**Comment by Bionus** [comment]
Why not indeed.
Just note that you will still only be able to run one batch download at a time.

**Comment by AldebaraanMKII** [comment]
Thank you!

**Comment by Bionus** [comment]
I'll close the issue when a version including the feature is released. 😄
