### ISSUE TITLE
Missing MSVCP140.dll error with Grabber 4.6.0

### ISSUE THREAD

**Issue by arukom** [Bionus/imgbrd-grabber#589]
### What steps will reproduce the problem?

when i open the programm

### What is the expected behavior? What do you get instead?

i get a window that says im missing MSVCP140.dll

### What version of the program are you using? On what operating system?

windows 7

**Comment by Bionus** [comment]
Thanks for the report, I uploaded a fix. You can get it from the same release:
https://github.com/Bionus/imgbrd-grabber/releases/tag/v4.6.0

This can also be fixed by installing the VS redistribuable 2015 manually:
https://www.microsoft.com/en-us/download/details.aspx?id=48145
