### ISSUE TITLE
Is chan.sankaku limited to 20 000 pictures?

### ISSUE THREAD

**Issue by arukom** [Bionus/imgbrd-grabber#590]
cant seem to go over 20 000 pictures with sankaku (except i didnt even try with other sites yet)
i do have an account already

**Comment by Bionus** [comment]
That would mean 1,000 pages of 20 pictures. I know that there is a limit to browsing further than page 100 (which is properly handled during batch downloads), but I don't know anything about the 1,000th page.
You say you have an account, did you enter the credentials in the source's settings?

If yes, could you upload your main.log file after a batch download that "stopped" at 20,000 pictures?

**Comment by arukom** [comment]
i saw the (number)/20000 and cancel and tried again, it stayed the same. i didnt bother to download it when im missing pictures. thats kinda weird though, i did go over 20k once.. sometimes it works sometimes it doesnt.

**Comment by arukom** [comment]
https://mega.nz/#!otdF0bZI




________________________________
Von: Jack Vasti <notifications@github.com>
Gesendet: Mittwoch, 24. August 2016 15:05
An: Bionus/imgbrd-grabber
Cc: arukom; Author
Betreff: Re: [Bionus/imgbrd-grabber] Is chan.sankaku limited to 20 000 pictures? (#590)


That would mean 1,000 pages of 20 pictures. I know that there is a limit to browsing further than page 100 (which is properly handled during batch downloads), but I don't know anything about the 1,000th page.
You say you have an account, did you enter the credentials in the source's settings?

If yes, could you upload your main.log file after a batch download that "stopped" at 20,000 pictures?

-

**Comment by Bionus** [comment]
Follow-up on issue #602.
