### ISSUE TITLE
Grabber won't start up after updating to 4.6.0

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#595]
error 0xc000007b when trying to startup.
![error](https://cloud.githubusercontent.com/assets/17685263/18024912/444a0bf2-6bd4-11e6-9849-2c714b25c5c1.png)

VC redist installed.

**Comment by Flat** [comment]
There are a couple things you can do to try to solve this error
1. Reinstall Grabber
2. Reinstall the VC Redistributable
3. Check your windows files for errors. Launch cmd.exe as administrator and run ```sfc /scannow```

For more detailed steps you can try reading http://www.techcrises.com/how-to/how-to-fix-error-code-0xc000007b-in-windows-7-8-8-1/

**Comment by Bionus** [comment]
Maybe you downloaded the old 4.6.0 installer which did not include the VC redist downloader. You can try reinstalling **from the latest download**, and if it doesn't works do what Flat suggested in his post.

**Comment by elreymu** [comment]
Tried all of that but none of that worked.

This error doesn't show up in any other application or games i have, only happens with grabber 4.6.0 and up.

**Comment by elreymu** [comment]
I already solved this so please close this issue, so here is what i did.

Dependency walker showed up a lot of ms-api missing files but i actually have them in system32, so i manually copied all of them and downloaded the rest and placed them in the grabber folder.
It was a tedious process but it works now
