### ISSUE TITLE
[Develop] Commands: %path% no longer expands

### ISSUE THREAD

**Issue by Flat** [Bionus/imgbrd-grabber#596]
### What steps will reproduce the problem?
Use ```%path%``` in your Image field of Commands

### What is the expected behavior? What do you get instead?
```%path%``` expands to the full path of the saved image, instead ```%path``` is expanded to ""

### What version of the program are you using? On what operating system?
Develop- cdc4a3771f294e90711a95bb37747ac8c42502f6 Linux

### Please provide any additional information below

Working on looking through the diffs between master and develop to diagnose the issue; have not yet found any changes to Commands.cpp that would warrant this error however.

**Comment by Flat** [comment]
According to ```git bisect``` 3c2908538b2156ebf6d7abdc65f2d1a84b732311 is the first commit that breaks this.

**Comment by Flat** [comment]
#600 will fix this specific issue by reverting the code changes that cause %path% not to expand, however this will also cause the FilenameTest::testPathEmptyDirs() test to fail, seems to be something to do with %test% not expanding to nothing, which also makes %path% expand to nothing when it shouldn't.

**Comment by Bionus** [comment]
Indeed, as said in PR #600, I instead pushed commit dd9f3c9 (hope you don't mind).
Since it's on develop I'm closing the issue as well.

**Comment by Flat** [comment]
Don't mind at all! After all my "fix" was a little hacky and just reverted changes instead of fixing the actual problem. Cheers!
