### ISSUE TITLE
chan.sankaku tag types not loading on time causing wrong filenaming. (any version)

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#597]
I download images by character folder using the character tag.
I have noticed when downloading from sankaku it saves the files to the "unknown" folder instead of the character's name folder.

But after i wait for a while (sankaku takes longer to load than other boorus) and see the tags change color and then click save, then it saves it to the character's name folder.

Looks like the tags types are not loading right on time.
This happens aswell for the batch download.

Can you add an option to let grabber "wait for tag type to load" ?
So it downloads the image only after all the tag types are loaded to avoid files being named incorrectly.

**Comment by Bionus** [comment]
Indeed, that's pretty problematic, especially if it happens on a big source such as Sankaku.
I'll upload a fix that makes the program wait in next version.
