### ISSUE TITLE
Suggestion: Extra field specifically for MD5 search

### ISSUE THREAD

**Issue by noname2x** [Bionus/imgbrd-grabber#599]
Hi. I find myself searching by MD5 fairly often. I would love a search box adjacent to the current one (perhaps splitting a small part of it) and making it specifically for md5 searches, by putting an 'md5:' before whatever's searched in there.

Thanks!

**Comment by Bionus** [comment]
Why not, but not by default.
Personally using the program with a small window, having the search field cut in half would be problematic. I'll add a setting to do so however.
