### ISSUE TITLE
Grabber replaces forward slash sign with backslash sign when it passes command to an application.

### ISSUE THREAD

**Issue by Shir01** [Bionus/imgbrd-grabber#601]
### What steps will reproduce the problem?
1)Enter an appropriate command containing forward slash sign in the "Image" box in the "Commands" section of the options.
2)Start image download.
3)Check log.

### What is the expected behavior? What do you get instead?
Grabber is expected to pass a command to an application as it is, without any modifications, with the exception of variables(%all% for example). But for some reason it replaces forward slash with backslash. 
The command that is set in the "Image" box:
`curl -F "user[name]=User" -F "user[password]=1234" -F "post[tags]=%all%" -F "post[rating]=%rating%" -F "post[file]=@%path%" localhost:9000/post/create`
Command execution part from the log:
```
[05:45:45.108] Execution of "curl -F "user[name]=User" -F "user[password]=1234" -F "post[tags]=1girl artist name bangs blurry bokeh brown hair chromatic aberration close-up depth of field eyes closed face guweiz hair over eyes highres lips long hair nose original realistic scarf solo sunlight swept bangs text upper body watermark" -F "post[rating]=safe" -F "post[file]=@C:\476\c2519761d59bed31ea588976200c4359.jpg" localhost:9000\post\create"
[05:45:45.529] Images download finished.
[05:45:46.738] Batch download finished
```
As you can see the original "localhost:9000**_/_**post**_/_**create" was replaced with "localhost:9000**_\_**post**_\_**create", thus cURL is unable to upload an image to the imageboard.

### What version of the program are you using? On what operating system?
Windows 8.1 9600
Grabber 4.6.0

P.S. By the way where can I find full list of variables(%path%, %all% etc) that Grabber accepts? It seems that only some of them are mentioned in WIKI(Available tokens).

**Comment by Bionus** [comment]
Indeed, pretty problematic.
I'll start working on a fix.

> P.S. By the way where can I find full list of variables(%path%, %all% etc) that Grabber accepts? It seems that only some of them are mentioned in WIKI(Available tokens).

All of them but `%path%` are in this list. `%path%` is mentioned in the Commands wiki.

**Comment by Shir01** [comment]
@Bionus 

> All of them but %path% are in this list. %path% is mentioned in the Commands wiki as it can only be used in that context.

Thanks for the information. There is one more thing I would like to know, is it possible to somehow exclude several tags from variable %allo%? You see, Myimouto and Moebooru both seem to support tag types(**_general, artist, copyright, character, circle, faults_**), for example **_artist:_**guweiz **_copyright:_**kill_la_kill **_character:_**matoi_ryuuko etc, and I want to pass them to cURL. But when I use %allo% I am unable to specify types for the tags that need them and if I try to use something like "post[tags]=artist:%artist%  character:%character% %allo%" artist and character tags will be duplicated with general type and and with specific type. And if it is not possible it would be great if you could implement such a feature in the future.  Plus it would be great if there were more variables without removal of forbidden symbols, afaik as it is now there is only %allo%.  Without this, variable %character% in case of a character with the name consisting of more than one word will be passed as two words divided by space to cURL, and during import this two words will be treated as two different tags.

Also, I noticed that Grabber sometimes adds symbols that shouldn't be there to the tags when variable %allo% is used. 

`curl -F "user[name]=User" -F "user[password]=1234" -F "post[tags]=>_ 1girl animal_ears black_panties blonde_hair bunny_ears elbow_gloves eyes_closed flat_chest gloves gradient gradient_background guweiz hairband highleg highleg_panties hug kantai_collection lips long_hair midriff miniskirt nose panties rensouhou-chan shimakaze_(kantai_collection) skirt smile striped striped_legwear thighhighs underwear yellow_eyes" -F "post[rating]=safe" -F "post[file]=@C:\00\01b39bd2012ba5e6f2e371108e4e9965.png" localhost:3000\post\create`

In the example above before the tag batch begins there is ">_ " (right angled bracket, underscore, space), and this sequence of signs made it impossible to import the picture.  Is it normal? This picture can be found by entering two tags - guweiz and kantai_collection in Grabber when gelbooru.com is chosen as the source.

**Comment by Flat** [comment]
In the 4.7 Release Bionus has added adittional tag options. Once that is released you will be able to use ```%all:includenamespace,unsafe%``` to properly use tag types. As for the >_ tag there, what source are you using? I haven't seen that issue myself.

**Comment by Bionus** [comment]
> There is one more thing I would like to know, is it possible to somehow exclude several tags from variable %allo%?

The `%all%` variable does not contain duplicates. However, depending on your settings, it may or may not use different separators or underscore settings. If you are set-up properly (keep underscores and with a ` ` separator), `%all%` and `%allo%` have the same behavior, except that `%all%` does not contain duplicates.

Another option would be to wait for the `includenamespace` and `unsafe` options (coming in 4.7.0, see the Filename wiki page) if MyImouto supports tag format "artist:guweiz copyright:kill_la_kill character:matoi_ryuuko".

>  Without this, variable %character% in case of a character with the name consisting of more than one word will be passed as two words divided by space

There's a setting to keep underscores in tags (instead of replacing them by blank spaces) in the option, called "Replace blanks by underscores" (in the "Save" category).

> In the example above before the tag batch begins there is ">_ " (right angled bracket, underscore, space)

This looks like the `>_<` tag, except the right eye is missing for some reason, I'll investigate.

> this sequence of signs made it impossible to import the picture

How so? Is MyImouto failing to create the image or cURL doesn't process the query? (I suppose it's the former)

**Comment by Shir01** [comment]
@Flat 

> As for the >_ tag there, what source are you using? I haven't seen that issue myself.

I am using gelbooru.  There is a direct link to the picture in Bionus's post above. And here is how it looks imported to local Gelbooru:
![2016-08-31_024941](https://cloud.githubusercontent.com/assets/20873590/18111119/b72b7a1c-6f25-11e6-94e7-de9c27014465.png)
And when you click on this tag Gelbooru can't find anything (standard message "Nobody here but us chickens!").



@Bionus 

> %all% and %allo% have the same behavior, except that %all% does not contain duplicates.

 Do I understand correctly that %allo% can contain duplicate tags and %all% can not? 

> Another option would be to wait for the includenamespace and unsafe options (coming in 4.7.0, see the Filename wiki page) if MyImouto supports tag format "artist:guweiz copyright:kill_la_kill character:matoi_ryuuko".

Great! 
Yes MyImouto supports the tag format above. AFAIK, its supported tag types are: **general, artist, copyright, character, circle, faults**.

> There's a setting to keep underscores in tags (instead of replacing them by blank spaces) in the option, called "Replace blanks by underscores" (in the "Save" category).

Thanks, I will carefully read the manual.
