### ISSUE TITLE
so is there any way to get past  the 1,000th page on sankaku?

### ISSUE THREAD

**Issue by arukom** [Bionus/imgbrd-grabber#602]
i think i did sent my main log file 2 weeks ago, but isnt there a way to get past the thousandth page still?

**Comment by arukom** [comment]
okay, apparently you can do it by setting the date and downloading by date.

but whenever i try to download this tag: date:2013-01-01..2014-01-01 love_live!_(series) 
(which are 3k pictures) after i click "get all" it only gets 20 pictures...

**Comment by Bionus** [comment]
By using the date, you mean the same as in suggestion #444?
I can't test on chan.sankaku as it's blocked in France, but I don't see why that search wouldn't work. I'll check on idol.sankaku tonight to see if I can reproduce.

**Comment by arukom** [comment]
basically the search shows my "page 1 of ? (20 of ?)" 

normally when i click on get all it does "get all" but on this search with the date it only gets 20.

**Comment by Bionus** [comment]
I just pushed a fix that allows logged in users to go past page 1,000 without any hack.
It should be included in the next update, so when it's out downloads should work properly.

**Comment by arukom** [comment]
oh! thanks a lot man
