### ISSUE TITLE
Question about filenames and tags

### ISSUE THREAD

**Issue by Omallis** [Bionus/imgbrd-grabber#603]
Hey, I tried looking all over for an answer to this but I really couldn't find anything. I'm sorry if you've answered this before but how do I get the image grabber to properly name files like if I downloaded them from danbooru. For example the image downloaded straight from the site would be named

"kiso and tenryuu (kantai collection) drawn by orqz - 20fe79072a1928a0bd22d02cc8501532"

and through the image grabber it's:
"20fe79072a1928a0bd22d02cc8501532"

I tried a separate danbooru downloader and used %originalFilename% but the best I got was this, still not quite right:
"__kiso_and_tenryuu_kantai_collection_drawn_by_orqz__20fe79072a1928a0bd22d02cc8501532"

Any help would be greatly appreciated. I can't quite figure this out and I checked the wiki but couldn't find anything for this specific issue. Thanks for your time man.

![untitled](https://cloud.githubusercontent.com/assets/22080325/18357476/1eb723da-75bf-11e6-97d9-3dcf70966ea0.png)

**Comment by Flat** [comment]
use```%filename%``` as seen here https://github.com/Bionus/imgbrd-grabber/wiki/Filename

**Comment by Omallis** [comment]
Hey I can't believe I didn't see that earlier. However what extension should I be using after that? Because when I tried %filename%/%md5%.%ext%  It just did the same thing as before and put it in a named folder while the file remained just a bunch of numbers. 
![untitled 4](https://cloud.githubusercontent.com/assets/22080325/18379276/a0b0c85c-763f-11e6-8fb7-843f4bc7a055.png)

**Comment by Omallis** [comment]
Update: Ok so I was messing around with it and I tried removing the forward slash "/" from "%filename%/%md5%.%ext%"  so it was just "%filename%%md5%.%ext%" and this improved the results but it's still not quite a match. There's no parenthesis "()" or "-" in the filename. 
![untitled5](https://cloud.githubusercontent.com/assets/22080325/18379895/d50f7258-7642-11e6-8257-a76997bbc51c.png)

**Comment by Bionus** [comment]
Indeed, that's normal. Note that returning  "__kiso_and_tenryuu_kantai_collection_drawn_by_orqz__20fe79072a1928a0bd22d02cc8501532" would also be correct, it's the actual filename on the server.

For example: https://danbooru.donmai.us/data/__asashimo_kiso_maya_and_tenryuu_kantai_collection_drawn_by_kaga3chi__a068761d1c3a23069b1f2a124e0933be.png

Grabber replaces the underscores by spaces (can be disabled) but the original filename is actually pretty ugly. Danbooru just does some real time renaming when you click the download button (through the `download` html attribute of the `a` element and some javascript).

So, from here you have three options:
* Re-create the filename using the %character% and other tags
* Use the Grabber default version of the filename (without underscores)
* Keep the underscores by changing your settings or using %filename:unsafe% (version 4.7.0)

Unless there is a need to update the program and add a new token for this "fake filename"? It's up to debate, I don't think it's necessary, but maybe for people with an already existing collection, it could be a good way to match their already existing files.

**Comment by Omallis** [comment]
Thank you very much for responding, I'm learning a lot about this. I've spent the past few days trying to figure out the intricacies of the booru sites and the image grabbers.  

As you said while it doesn't seem like a big deal, for people like me who have been saving pics for a long time and adding to their archive, and where organization is key to locating everything, it would be ideal to keep the file naming consistent with how danbooru renames the files through the download button. 

Honestly the whole reason I'm looking into mass image grabbers like this is because saving and renaming files individually is consuming too much time in my life, yet I'm one of those guys who has severe OCD and when they see a beautiful piece of art, or a fine pair of tiddies I can't turn away haha. It's a predicament. The constant fear of missing an amazing picture on my timeline keeps me glued to twitter and takes so much time. I just wanna get the whole archive and complete my collection so I don't have to worry about it anymore lol. 

I tried messing around and recreating the naming system with tokens but %character% seems to include the copyright so if you put %copyright% after it you get a double over, but it doesn't include crossover copyrights, and if there is more than one character it has the copyright in parenthesis after each character name, making a really bloated and ugly filenaming system. Like so: 
"kiso (kantai collection)+tenryuu (kantai collection) drawn by orqz - 20fe79072a1928a0bd22d02cc8501532"

(or with the copyright) 
"tenryuu_(kantai_collection) (kantai_collection yoru_no_yatterman) drawn by torichamaru - 677364b"

**Comment by Bionus** [comment]
So I believe what you're asking for is indeed the "fake" filename danbooru generates when clicking the "download" button?
If so, I'll try to include this in the next update.

**Comment by Omallis** [comment]
Thanks a lot man, it would mean a lot to me. I appreciate you taking the time to consider it and explain all this to me. I hope you have a good one!  

Should I click "close and comment" or leave this open for future reference?

**Comment by Omallis** [comment]
Thank you so much man, bless your heart =')

**Comment by Bionus** [comment]
AFAIK, in latest versions, using `%filename%` on Danbooru returns the correct name as long as you're using the XML or JSON source.

**Comment by SweetKawaiiPanienka** [comment]
I'm also trying to get that "fake" file name which I get when clicking on "download" on danbooru. 
But I'm still getting:
__artemisa_bell_ashcroft_and_ellen_mira_mathers_date_a_live_drawn_by_tsunako__e97987facf4dd88711cbc7b45d901d6d.jpg
instead of:
artemisa bell ashcroft and ellen mira mathers (date a live) drawn by tsunako - e97987facf4dd88711cbc7b45d901d6d.jpg 
even when I set the only source as XML or JSON. 
Name: %filename%.%ext% 
Do I need to do anything more?
