### ISSUE TITLE
gelbooru pools don't seem to work

### ISSUE THREAD

**Issue by herki84** [Bionus/imgbrd-grabber#604]
Searching for a pool id on gelbooru yields "No result" instead of the expected pool.
That happens when trying the regular tab with pool:<id>as well as in the the pool tab.
![gel-grab-1](https://cloud.githubusercontent.com/assets/22115520/18410013/ac457db2-7756-11e6-8416-588b61d2f14c.png)
![gel-grab-2](https://cloud.githubusercontent.com/assets/22115520/18410014/ac477ec8-7756-11e6-947a-e55cad803b16.png)
Relevant part of the log:
```
[12:57:50.689] Loading results...
[12:57:50.692] Loading page http://gelbooru.com/index.php?page=pool&amp;s=show&amp;id=44207
[12:57:50.814] Parse
[12:57:50.818] Receiving page http://gelbooru.com/index.php?page=pool&amp;s=show&amp;id=44207
```

If I'm doing something wrong here, please let me know.

**Comment by Bionus** [comment]
At first glance, it would seem that they changed their HTML for the pool page, as the URL is correct (and you're not doing anything wrong).

I'll investigate and find a fix ASAP, thanks for the report!
