### ISSUE TITLE
Crash Log:

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#606]
I meant to give this to you earlier, but here's my Crash log and my sources which I use.

*Linked removed by @Bionus*

**Comment by Bionus** [comment]
Thanks, it'll help investigate the causes of the crash.

Note that you should not upload your site `settings.ini` files, so I removed the link just in case. These files may contain your hashed passwords for said sites.

*PS: you can also edit your other issue. So I'll close here, follow-up on issue #605*

**Comment by SultrySamthepennanceman** [comment]
Wait did you download what you needed or not?

**Comment by Bionus** [comment]
Yes, I did. I downloaded the files I needed before removing the link.
