### ISSUE TITLE
Add shortcut to select an array of files and another to directly save an image

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#610]
My suggestion is to make it so you can hold Shift to select multiple images at the same time, just like you can do in windows to select files.

My other suggestion is to have another shortcut so you can directly download an image by clicking on the thumbnail (For example Shift + Right click,  or just by pressing the middle mouse button)

**Comment by Bionus** [comment]
The first suggestion is already done, except it's the `Ctrl` key. Just select the images you want, then you can click "Get selected" and they'll be added to the batch download tab (bottom part).

As for the second suggestion, why not. It could even be mixed with the first to allow direct download of all selected images with the current filename and directory settings.

**Comment by elreymu** [comment]
I actually already know about the Ctrl key shortcut, the one i am talking about is a variation of that.
The difference with the Shift one is that you select a range of files instead of one.

Try to test that with any group of files in windows to see what i mean.

It's useful because it saves a lot of time when you want most images of one page but there are a couple of them that you don't want to download, instead of clicking every image one by one each page.
