### ISSUE TITLE
Trouble with Setup [Win10]

### ISSUE THREAD

**Issue by collanity** [Bionus/imgbrd-grabber#611]
### What steps will reproduce the problem?
During start a setup file

### What is the expected behavior? What do you get instead?
I want to install but I get an error "Runtime Error (at 29:206)"

### What version of the program are you using? On what operating system?
from 4.5.3 to 4.7.0 under Windows 10

### Please provide any additional information below
Sory for my bad english. Have no trouble before 4.5.3. Try it launch on another PC and get error also.
Is suspected because of the language (I'm russian).

**Comment by Bionus** [comment]
Does it also happen if you pick "English" at the beginning of the installation?

**Comment by collanity** [comment]
I have no to choise language at the begining. =(
Other times (before i have error) english have set as default. Without select language.

**Comment by Bionus** [comment]
I see. Then can you run the installer with the `/log=errorlog` parameter, then upload the log here?

To do so:

1. Create a shortcut to the installer: right click (on the installer) > create shortcut
2. Open the properties of the shortcut: right click (on the shortcut) > properties
3. Add the parameter at the end of the "Target" field: the result should be something like "C:\Users\Username\Desktop\Grabber_4.7.0.exe /log=errorlog"
4. Run the installer (it should fail with the error you posted above)
5. Post the content of the `errorlog` file here

Thank you!
I'll also try to investigate further tonight.

**Comment by collanity** [comment]
Done as told. After add key "/log=errorlog" installer showed a window to select language o____O
During installation has been downloaded "Microsoft Visual C++ 2015 Update 3 Redistributable". Setuo has done! Strange it. All the same attach the log file.

**Comment by Bionus** [comment]
So as guessed, it's the embedded russian translation that causes this error. I'll see what I can do, but I may just remove it if it doesn't work. Thanks for the report, and glad you could install the program in the end. :smile:

**Comment by jeobits** [comment]
yo lo instale el programa con  

1. el idioma en ingles  y
2. Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24210

 en un pc de **win 10   64bits** y
funciono

**Comment by jeobits** [comment]
I install the program

1. in English language and

1. Microsoft Visual C ++ 2015 Redistributable (x86) - 14.0.24210

a pc 64bit and Win 10
it worked
