### ISSUE TITLE
Rename Existing Images feature does not populate certain tokens with any values.

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#612]
### What steps will reproduce the problem?

Using the **Rename Existing Images** feature with the following settings:

- Either **"Get md5 in filename"** or **"Force md5 calculation"** turned on.
 
- Original filename field:  

 **`%md5%.%ext%`**
 
- Destination filename field: 
 
 **`artist-%artist% src-%copyright% char-%character% %md5% (%rating%).%ext%`**

- Source field:  **gelbooru.com**

### What is the expected behavior? What do you get instead?

(Using this example image: http://gelbooru.com/index.php?page=post&s=view&id=2928342 )

**Note:**  Under Grabber **Options -> Save -> Artist tags, Copyright tags and Character tags** I've entered the text "`unk`" for all their **"If empty"** fields to denote unknown/unspecified artist, copyright or character tags.

Filename of the existing image as saved on hard drive:

**`973655f2beb806b348cc3cef90238ba3.png`**

New filename should have been:

**`artist-annnna src-kantai_collection char-wo-class_aircraft_carrier 973655f2beb806b348cc3cef90238ba3 (safe).png`**

Instead, this filename is the result:

**`artist-unk src-unk char-unk 973655f2beb806b348cc3cef90238ba3 (safe).png`**

It appears Grabber is unable to correctly populate these specifc tokens with the correct values.

Grabber is still able to correctly populate the **`%tags%`** token as well as at least one Custom Token I specified.

### What version of the program are you using? On what operating system?

Grabber v4.7.0
Windows 10 Pro 64-bit

**Comment by Bionus** [comment]
I can indeed reproduce that issue.
I'll start working on it right away and push a fix tonight, which should be included in the next release. Thanks!
