### ISSUE TITLE
Adding/changing a thumbnail for a Favorite bookmark creates a duplicate Favorite bookmark

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#614]
### What steps will reproduce the problem?

1. Create or use an existing Favorite bookmark.

2. Under the **Favorites tab**, right-click on that bookmark to bring up the **Edit A Favorite** window

3. Click the **Browse** button and select an image for the thumbnail, then click OK.

### What is the expected behavior? What do you get instead?

Expected behaviour: Favorite bookmark's thumbnail would be updated with the newly selected thumbnail.

Actual result: The Favorite bookmark thumbnail is updated with the newly selected thumbnail, then a duplicate Favourite bookmark is created.

### What version of the program are you using? On what operating system?

Grabber v4.7.0 (commit a18dc84)

Windows 10 Pro 64-bit

### Please provide any additional information below

- The duplicate Favorite bookmark persists between program shutdowns.

- Deleting either of the two bookmarks will delete both the duplicate and the original bookmark.

- Bug is reproducible by editing the thumbnail of any favourite tag under the Favourites tab.

**Comment by Bionus** [comment]
Strange bug indeed. While fixing issue #615, I also fixed this.
The fix should be included in the next release. Thanks for the report! :smile:
