### ISSUE TITLE
Deleting a tag marked as Favorite doesn't remove that tag's Favorite status under Search tab

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#615]
### What steps will reproduce the problem?
1. Create or use an existing Favorite bookmark.
2. Right-click bookmark to bring up **Edit A Favorite** window.
3. Press the **Delete** button.
4. Go to the **Search** tab and type in the tag whose Favorite entry you just deleted under the Favorite tab.
### What is the expected behavior? What do you get instead?

**Expected behavior:** 

The tag that was formerly a Favorite would no longer have Favorite status if it's searched for again under the Search tab.

**Actual Result:** 

Under the **Search tab**, the Tag whose Favorite bookmark that was just deleted is still coloured to indicate that it's a Favorite.

Since Grabber still considers the Tag to be a Favorite, the **Right-Click on tag -> Favorites -> + Add** function is not available.
### What version of the program are you using? On what operating system?

Grabber v4.7.0 (commit a18dc84)

Windows 10 Pro 64-bit
### Please provide any additional information below

This bug occurs if the steps outlined above are performed within the same session and a Tag's incorrect Favorite status does not persist between shutdowns.

**Comment by Bionus** [comment]
Indeed, the list of favorites is loaded for each tab separately on creation, instead of being shared from a global perspective.

Since I'm currently in a rework-frenzy on this program, I'll include a fix in the new profile system coming up next release, thanks for the report! I totally didn't notice this small issue. :smile:
