### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#616]
Can you add arrows that allow us to scroll through the images after we click on one and the ability to right click an image and copy it to the clipboard.

**Comment by Bionus** [comment]
What do you mean arrow and scrolling?
Something like what suggested in issue #568?

**Comment by Bionus** [comment]
What do you mean arrow and scrolling?
Something like what suggested in issue #568?

**Comment by brodycas3** [comment]
Yes exactly like that issue.

**Comment by Bionus** [comment]
Let's keep it there then. :smile:
