### ISSUE TITLE
Memory leak during batch download closes a crash

### ISSUE THREAD

**Issue by Zekken01** [Bionus/imgbrd-grabber#618]
### What steps will reproduce the problem?

Downloading everything from gelbooru with the explicit tag
### What is the expected behavior? What do you get instead?

Its expected to download, crashes after a random number.
### What version of the program are you using? On what operating system?

Win 10
Latest version

**Comment by brodycas3** [comment]
I think its happening while its downloading the pages.

**Comment by notacompletemoron** [comment]
Mine craps out when downloading over 500.

**Comment by lllllllllllllllllllllllll** [comment]
This is an ongoing issue. Posted a bunch of times before. 

What we know is, it crashes when downloading fairly large number of images, say 80k or more. The crash can happen at any time during the download, either at the page part or during actual image download. If a very large number of images are being downloaded it will most likely not even get past the page downloading stage. It's probably some kind of memory allocation issue

For now you should just try getting 70-80k images at a time, or test however many you can download and post here again with crashdumps so we can get a better idea of whats going on, if that number isnt the same for everyone.

**Comment by brodycas3** [comment]
Since i can upload rar but not 7z here is a link to my dump file.

https://obscuredfiles.com/?file=NdPiOxbA

**Comment by Bionus** [comment]
Yes, I'm actually currently investigating this issue, trying to reduce the memory leaks of the program.
The conclusion from the other issues was that it was caused by memory leaks, causing an over-use of RAM leading to the program crash. I couldn't see other reasons of such random crashes.

**Comment by brodycas3** [comment]
Sounds like windows vista.

**Comment by brodycas3** [comment]
maxes out around here then it goes down to 500mb
 http://i.imgur.com/vGkuhbo.png

**Comment by Bionus** [comment]
Sorry for the inconvenience! I just uploaded [version 4.8.3](https://github.com/Bionus/imgbrd-grabber/releases/tag/v4.8.3). Please tell me if it fixed your issues, so that I can know if I still have to investigate or not.

> it was at 88mb before I captured [then] maxes out around here then it goes down to 500mb

Memory should go up during page download and image preparation, then slowly down as images get downloaded. There shouldn't be issues as long as you don't go above 100,000 images for now (feel free to prove me wrong).

**Comment by brodycas3** [comment]
Well rip, didn't get past first pic.

[grabber crash.zip](https://github.com/Bionus/imgbrd-grabber/files/526093/grabber.crash.zip)

**Comment by Bionus** [comment]
> Well rip, didn't get past first pic.

Does it always happen or only for > 100K pics download? Because as I said, that's likely to be the current upper limit on 4.8.3. I couldn't manage to get any crash myself, but I didn't try downloads of more than 20,000 images yet.

**Comment by Bionus** [comment]
So I'll leave this issue open until there is a smarter progressive memory allocation for pages and image initial storage.

Copy and pasted from issue #630.

## Download of 2,000 images

* Before download: 21.5 mo
* Beginning of the download: 86.1 mo
* End of the download: 112 mo
* After download: 69.8 mo

10 pages and 2,000 images took 65 mo to store in memory (32 ko per image).
Each image downloaded "leaked" 13 ko.
In the end, 45 mo were leaked.

## Download of 20,000 images

* Before download: 17.4 mo
* Beginning of the download: 458 mo
* After 1,000 images: 487 mo
* After 3,000 images: 506 mo
* After 5,000 images: 508 mo (down from some peaks at 550 mo)
* After 6,000 images: 470 mo
* After 8,000 images: 471 mo
* After 10,000 images: 383 mo
* After 15,000 images: 378 mo
* After 18,000 images: 311 mo
* End of the download: 359 mo
* After download: 239 mo

100 pages and 20,000 images took 440 mo to store in memory (22 ko per image).
In the end, 220 mo were leaked.

What can be easily noticed is that except for the initial storage in RAM of the images' data, the download itself did not need much more even though we had 10 times more images. The further in the download we were, the less it ate RAM (even getting some back each time it recycled the already downloaded images).

In conclusion, there shouldn't be issues as long as you don't go above 100,000 images for now (after which the storage itself of the data will eat all your RAM).
