### ISSUE TITLE
File token name changes????

### ISSUE THREAD

**Issue by randomhunterdude** [Bionus/imgbrd-grabber#619]
### What steps will reproduce the problem?

Whenever I try to download a file with %date:yyyy.MM.dd.hh.mm.ss%_%md5%.%ext% as the file name, it says the %date:yyyy.MM.dd.hh.mm.ss% token does not exist and will not be replaced 

### What is the expected behavior? What do you get instead?

I'm used to getting file names that look like this ex:
2016.05.05.23.49.57_9ec958ea28f66d27bb79074105d297bc

But now they look like this:
04-05-2016 23.49_9ec958ea28f66d27bb79074105d297bc

### What version of the program are you using? On what operating system?
Version 4.7.0 on windows 10

### Please provide any additional information below
I'd like to resolve this issue so I can go back to using the old file names that i'm used to, seeing as how I save things in order and if I suddenly switch over to this new format, things will get out of order. Thanks for any help I can get!

**Comment by Bionus** [comment]
Hello,

The syntax for these kind of token "settings" have changed with the 4.7.0 update, to allow for more flexibility.
It's explained in the [Filename wiki page](https://github.com/Bionus/imgbrd-grabber/wiki/Filename#options)
Now, you have to use:;
```
%date:format=yyyy.MM.dd.hh.mm.ss%
```
instead of the previous:
```
%date:yyyy.MM.dd.hh.mm.ss%
```
Sorry for the change! I guess I didn't make it clear enough in the release notes.

**Comment by randomhunterdude** [comment]
Oh ok thanks! I'm sure the release notes were clear!! I probably just didn't read them through thoroughly!!

**Comment by randomhunterdude** [comment]
Oh okay thanks, however, I changed it to this:
%date:format=yyyy.MM.dd.hh.mm.ss%_%md5%.%ext%

Still giving me the error though.... so im probably doing something wrong like not using the proper format for something. Sorry for all the hassle :/ when its probably completely straight forward!!

On a sidenote, how do you exactly delete saved file names in the drop down menu?

**Comment by Bionus** [comment]
The error is actually just a warning, if you use the format it will still work.
The warning will be removed in next version.

> On a sidenote, how do you exactly delete saved file names in the drop down menu?

You can't from the UI currently, but you can always delete or edit the `filenamehistory.txt` in the settings folder (File > Open settings folder).
