### ISSUE TITLE
Tag Delimiter Crash

### ISSUE THREAD

**Issue by Siegen** [Bionus/imgbrd-grabber#622]
### What steps will reproduce the problem?

1. Set the general tag delimiter to any character (ie. ";").
2. Save an image with that character in one of its tags.

### What is the expected behavior? What do you get instead?
Save should work. Instead, client crashes every time you try to save that image.

### What version of the program are you using? On what operating system?
4.7.0, Windows 10 64bit

### Please provide any additional information below
This has been driving me nuts for a while and I finally tracked it down. It works for all of the delimiters I've tried and the images save perfectly fine once you set the delimiter to something else. I noticed that a few tags have shit like ";b" or ":>" that can choke grabber if those contain your delimiter.

I suspect this was also the cause of a few bulk downloads that crashed grabber.

**Comment by Bionus** [comment]
At what point does it crash exactly?

I just tried reproducing with no success: I set the general delimiter to `;` then saved some random image containing the `;D` tag with the `%all%.%ext%` filename, and nothing happened. Same thing trying to batch download 200 of them.

The only result was files with `...;;d;...` inside their filenames which seems to be the appropriate behaviour.

**Comment by Siegen** [comment]
Ah, sorry, it appears to crash when the %all:includenamespace% token is in the Image Command field. It seems to happen regardless of how the token is present. ie. even if it's wrapped in quotation marks; whether it's being passed as an argument or just printed all by itself; etc.

**Comment by Bionus** [comment]
Ok, I could reproduce then, I'll fix this for next version.
It indeed comes from the new `includenamespace` option.

In the meantime, as a temporary fix, you can use another separator that is not likely to appear in a tag, such as `¤` or `§`.
