### ISSUE TITLE
Grabber sets incorrect namespace of the tags while downloading images from Gelbooru.

### ISSUE THREAD

**Issue by Shir01** [Bionus/imgbrd-grabber#624]
@Bionus 
Hi. I don't know if it is a problem of the Grabber or maybe something is wrong with Gelbooru, but I would really appreciate if you could investigate the issue. The description is below.

### What steps will reproduce the problem?
1. Open Grabber, check Gelbooru in sources
2. In options set naming variables like this "%all:includenamespace,separator= ,unsafe%" for any purpose, I am using it in commands section to import pictures to MyImouto imageboard.
3. Type in "guweiz" without quotation marks  in the search box, click "Get this page" and start download.

### What is the expected behavior? What do you get instead?
It is expected that variables will be replaced with correct namespaces, but instead Grabber replaces everything with "unknown:". 

**Here it is how it looks in log file:**

`Execution of "curl -F "user[name]=User" -F "user[password]=secret" -F "post[tags]=unknown:1girl unknown:arm_up unknown:asymmetrical_bangs unknown:bangs unknown:bare_shoulders unknown:black_hair unknown:expressionless unknown:female unknown:gradient unknown:gradient_background unknown:green_eyes unknown:guweiz unknown:hand_in_hair unknown:looking_at_viewer unknown:original unknown:parted_lips unknown:solo unknown:upper_body" -F "post[rating]=safe" -F "post[file]=@C:/00/bcd4bdf936f2afd1f1eec1dcd990b080.jpg" http:/localhost:3000/post/create"`

**End result:**

![2016-10-04_090645](https://cloud.githubusercontent.com/assets/20873590/19064722/c8e9f5a0-8a17-11e6-96a7-c945487bd3c1.jpg)

### What version of the program are you using? On what operating system?
Grabber 4.7.0
Windows 8.1 9600 x64

**Comment by Bionus** [comment]
You don't have to ping me with @Bionus, I get a mail for every new issue anyway. :smile:

As for the issue, it's indeed a bug with Grabber, as it wasn't downloading the images' details (where the namespaces can be retrieved) even when the `includenamspace` option was present. I fixed it in commit 61987e1, so it should be fixed in the next release.

Thanks for the info, I totally didn't think about this case.

**Comment by Shir01** [comment]
OK, Thanks. :smile:
