### ISSUE TITLE
Custom tokens from the previous version not working/deleted when installing version 4.8.0

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#626]
### What steps will reproduce the problem?

Install version 4.8.0, then go to custom tokens and there will be none, however if you open settings.ini all of your custom token you had in your previous version will be there but just not working.
But
If you create a new custom token at this point from grabber, it will erase/replace all the custom tokens in settings.ini with your new token and won't be recoverable.

(Luckily i had a backup for that)

Update:
This will happen every single time when opening grabber, even new custom tokens made within this version of grabber won't work (they will appear in settings.ini but won't work and will be overwritten if you make new tokens)

**Comment by Bionus** [comment]
Thanks for the quick report!
I just pushed a fix and uploaded v4.8.1 that includes it. Sorry about that, thanksfully you had a backup. 😄
