### ISSUE TITLE
Tags in SQL-Queries

### ISSUE THREAD

**Issue by MrCrackR** [Bionus/imgbrd-grabber#628]
### What steps will reproduce the problem?
Enable log, enable database option, use following query for tag:
`INSERT INTO tag_index(tag, index_count) VALUES("%tag%", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;`
### What is the expected behavior? What do you get instead?
Successfull query in the log, like:
`SQL execution of "INSERT INTO tag_index(tag, index_count) VALUES("some_awesome_tag", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;"`
Instead I get:
`SQL execution of "INSERT INTO tag_index(tag, index_count) VALUES("", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;"`
### What version of the program are you using? On what operating system?
Grabber 4.8.1 on Windows 7 (x64)
Previously worked correctly on Grabber 4.7.0
### Please provide any additional information below
It's not only %tag%, that is not working anymore. It's the same with %type% and %number% I am using on my heavily modified Gelbooru. The exact query I have to use is:
`INSERT INTO tag_index(tag, type, number, index_count) VALUES("%tag", "%type%", "%number%", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;`

I also have two questions:

1. Is there a way to use the recently in MySQL inplemented field type JSON to store the tags contained in %allo% in the database command for image?

2. Is %type% for single tags  the same as the :includenamespace is for %all% and %allo%?

**Comment by Bionus** [comment]
> Is there a way to use the recently in MySQL inplemented field type JSON to store the tags contained in %allo% in the database command for image?

How should the data be formatted? I never heard of that field. From the "tag_index" name, aren't you using Danbooru?

> Is %type% for single tags the same as the :includenamespace is for %all% and %allo%?

Yes it is.

I would also advice against using `%allo%`, as I will soon remove it since it can be made using the `unsafe` option now.

**Comment by MrCrackR** [comment]
For a simple demo let's assume that the table posts looks like this:
`uid | tags`
then the query would be:
`INSERT INTO `posts` (`tags`) VALUES ('[\"here\", \"are\", \"more\", \"awesome\", \"tags\"]')`
With JSON in MySQL you can finally search inside complex data structures like arrays and objects without having to do the parsing of a string (like these tags, that are separated by spaces) inside the client program. JSON works with MySQL 5.7+.

JSON support is just a suggestion I would find very convenient.

It's the [gelbooru fork](https://github.com/zixaphir/gelbooru-fork/) I'm rewriting.
