### ISSUE TITLE
Rename Existing Images function crashes when processing an image that's non-existant on the remote site.

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#629]
### What steps will reproduce the problem?

My test procedure:

1) Downloaded five images from gelbooru.com.  My download parameters were tag "_scenery_" and "_rating:safe_".

2) Renamed the images to a sequential ascending numerical filename.  E.g. 0001.png to 0005.png

3) I created a new image so that it can't be found on gelbooru.  I did this by altering one of the downloaded images slightly (upscaled image) to change its MD5 value.  There are now six images to check. E.g. 0001.png, _0001a.png_, 0002.png to 0005.png.

4) Used Rename Existing Images function with the following settings:
- Force MD5 Calculation - ON
- Origin Filename - Left at default global value, also tested with blank entry.
- Destination filename - `artist-%artist% src-%copyright% char-%character% %date:format=yyyyMMdd% tags-%all% %md5:maxlength=12% (%rating%).%ext%`  
- Source: gelbooru.com

5) Proceeded with the rename process and Grabber crashes.

6) I removed the new image that I altered (0001a.png, the one that doesn't exist on gelbooru) and ran the Rename procedure again.   The result is that all files were successfully renamed.
### What is the expected behavior? What do you get instead?

Expected all files to be renamed according to the specified filename format.  

Result: Grabber crashes when it tries to process the image file that exists locally but doesn't exist on Gelbooru.
### What version of the program are you using? On what operating system?

Windows 10 Pro 64-bit
Grabber v4.8.2 (https://github.com/Bionus/imgbrd-grabber/commit/2b44de27486a69df8f3f1e7a58821b1df3b03213)
Grabber v4.8.1 (https://github.com/Bionus/imgbrd-grabber/commit/38900045103906f989544dd2b3d1b42353eb9600)
### Please provide any additional information below

I also ran this test with Rename Existing Images set to obtain the MD5 value from the filenames and the result was the same: crashes when processing a file that doesn't exist on the remote booru site.

**Comment by Bionus** [comment]
> Expected all files to be renamed according to the specified filename format

But how would Grabber be able to rename that unknown image, if its MD5 changed?

From what I understand from your issue, `0001.png`, `0002.png`, `0003.png`, `0004.png`, `0005.png` should be renamed, while , `0001a.png` should keep its name (since it can't be found).

**Comment by Gaffnet** [comment]
> But how would Grabber be able to rename that unknown image, if its MD5 changed?

Changing the MD5 was just a way to force Grabber to attempt to process an image file that exists locally, but not remotely on the source site.    I could have accomplished the same thing by copying any random image file from my hard drive that doesn't exist on the source site and force Grabber to process it.  

So basically when Grabber attempts to process the image file but fails to find that image file on the source site, Grabber crashes rather than report/ignore the discrepancy.
