### ISSUE TITLE
Retry on error code 429 is too fast

### ISSUE THREAD

**Issue by MrCrackR** [Bionus/imgbrd-grabber#632]
### What steps will reproduce the problem?
Download a lot of pictures from sources, that only return a few images per page (for example sankakucomplex). After some time you will get the following errors:
`[02:06:18.055] Limit reached (429). New try.
[02:06:18.066] Limit reached (429). New try.
[02:06:18.067] Limit reached (429). New try.
[02:06:18.112] Limit reached (429). New try.
[02:06:18.133] Limit reached (429). New try. [...]`
### What is the expected behavior? What do you get instead?
A simple sleep of a few seconds after getting the error should be enough. I don't think that retrying 30 times per second will be beneficiary for the continuation of the requests when the server wants us to slow down a bit.
### What version of the program are you using? On what operating system?
Grabber 4.8.3 on Windows 7 (x64)
### Please provide any additional information below
I know this is not a severe problem but I assume that it will be fixed with just 3 more lines of code.

**Comment by Bionus** [comment]
Did you try changing the default error throttle from something other than 0s in Sankaku settings?

**Comment by MrCrackR** [comment]
I've never seen that setting before. I'm sorry for such a bother.
