### ISSUE TITLE
%md5% truncates to 2 digits

### ISSUE THREAD

**Issue by aarqon** [Bionus/imgbrd-grabber#634]
### What steps will reproduce the problem?

Downloading images as usual seems to cause the issue.
### What is the expected behavior? What do you get instead?

My name scheme is %md5%.%ext%
I should be getting the full md5 hash with the original image extension appended.

Instead it returns the first 2 characters of the hash, appends the extension, and saves that.

E.g.:
[01:42:44.733] Image received from http://img.rule34.xxx/images/1989/7afd2f926ef40f964975d2089f841b1e.png
[01:42:45.538] Saving image in M:\bryan\Pictures\cake\7a.png

The image then appears in my folder named as such.
It is occasionally also truncated to a single character.
### What version of the program are you using? On what operating system?

Just updated to 4.8.3, on Windows 10.
### Please provide any additional information below

![capture](https://cloud.githubusercontent.com/assets/11674341/19339108/ed41c952-90e6-11e6-8a82-83830a07dee1.PNG)

**Comment by aarqon** [comment]
This has the secondary effect of preventing some new images from loading:
![capture](https://cloud.githubusercontent.com/assets/11674341/19382095/49add6da-91c4-11e6-9ebe-e613c1d8df3a.PNG)

Just figured you'd want to know they were interacting this way.

**Comment by aarqon** [comment]
Problem still exists as of 4.9.1

**Comment by Bionus** [comment]
Can't reproduce in any way.
Did you change the "limit" setting in some way? Does it also happen with the default settings?

**Comment by aarqon** [comment]
I don't know what was wrong, but this doesn't happen anymore!

**Comment by Bionus** [comment]
Well that's a good thing. Strange, though.
Feel free to re-open if it starts again.
