### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#638]
### What steps will reproduce the problem?

Try to log in to chan.sankakucomplex.com through options in Credentials tab. Related to issue #494 but "Hash a password" button (the solution at the time) is no longer present. "Unable to test" remains.
### What is the expected behavior? What do you get instead?

Expect ability to login. Unable to test.
![Image of credentials](http://i.imgur.com/nF7kSB8.png)
No "Hash a password" button present.
### What version of the program are you using? On what operating system?

4.8.3, Windows 8.1 Pro x64

**Comment by Bionus** [comment]
Did copying and pasting the new Sankaku files fix the issue? (like for issue #637)
Or is the "hash password" button still absent?

**Comment by Tiffys** [comment]
Copying & pasting the new Sankaku files made the "hash password" button appear, and it is able to hash, however upon clicking Test the result is still "Unable to test"

**Comment by Bionus** [comment]
Yeah, that's currently "normal" for sources such as Sankaku where the login cannot be tested.
I guess I'll remove the button in these cases (and implement more login test procedures).

**Comment by brodycas3** [comment]
why can't you test login for sankaku?

**Comment by Bionus** [comment]
It's technically possible, but not implemented in the program.
Because of the way Sankaku login works is by adding the (hashed) credentials directly through the URL, while the login tester is made to test form-based logins (such as Gelbooru's).
