### ISSUE TITLE
Grabber trying fileextensions endlessly

### ISSUE THREAD

**Issue by BigBrainAFK** [Bionus/imgbrd-grabber#639]
I recently tried loading some stuff of gelbooru and I noticed that the grabber got stuck at this link:

http://simg4.gelbooru.com//images/f1/dd/f1dda4ef7b352725f9fbca4a200cb0e2.gif

The grabber then just endlessly tries grabbing that pic with every extension and ofc never finishes.

There should be a stop after 1 cycle trough the extensions.

**Comment by Bionus** [comment]
Indeed, downloading that images go jpg, png, gif, jpeg, webm, swf, mp4, jpg...
I'm checking it oujt
