### ISSUE TITLE
Application was unable to start correctly

### ISSUE THREAD

**Issue by throw395583** [Bionus/imgbrd-grabber#640]
### What steps will reproduce the problem?

Installed to default location with "Run as administrator", tried to run program with and without "Run as administrator".
### What is the expected behavior? What do you get instead?

Error window saying "Application was unable to start correctly (0x000007b). Click OK to close the application."
### What version of the program are you using? On what operating system?

Tried 4.8.2 and 4.8.0. Running on Windows 7 home edition.
### Please provide any additional information below

Dependency walker says Grabber.exe is missing GPSVC.DLL and IESHIMS.DLL.

**Comment by Bionus** [comment]
During the program's installation, were you prompted to download and install the VC redist 2015 package?
Is your system 32 bits or 64 bits?

**Comment by throw395583** [comment]
I was prompted to install that, didn't see any errors. After I deleted the Grabber folder and installed 4.8.0 I didn't get that prompt. System is 64 bit.

**Comment by Bionus** [comment]
Must have come from the fact that the latest versions changed the required MSVC version.

Seem to come from a corrupted or misinstalled MSVC redistribuable:
https://www.bitdefender.com/support/how-to-solve-error-message-%22the-application-was-unable-to-start-correctly-(0x000007b)-click-ok-to-close-the-application%22-1106.html
