### ISSUE TITLE
Crashes when trying to rename a large amount of images

### ISSUE THREAD

**Issue by ItDK** [Bionus/imgbrd-grabber#641]
### What steps will reproduce the problem?

Use the Rename Existing Images function on a directory with a large amount of images (Don't know the specifics, 71 images worked but 163 caused crash). 
### What is the expected behavior? What do you get instead?

To rename all images and not crash.
### What version of the program are you using? On what operating system?

4.8.3
Windows 10 Current
### Please provide any additional information below

All images were from E621.net, not sure if that matters, but it seemed important to mention

**Comment by Bionus** [comment]
Could it be related to issue #629?
Is there any image in your folder that was deleted from e621 or that didn't come from there? Causing the image to be not found and unfortunately crashing, as described on the other issue.

**Comment by ItDK** [comment]
I don't believe so. As far as I remember all the images were part of the same batch, and the %website% tag in the filenames shows that they're all from E621.

**Comment by Bionus** [comment]
> Edit: I've been further renaming and It seems to only happen with certain folders of images and doesn't actually correlate with the amount of images renamed.

Which images/folders cause the crash then? Do you have a E621 ID or MD5 for one? (or direct link to E621)
Could they be missing from E621 and therefore be linked to that other issue?

**Comment by ItDK** [comment]
It mainly does happen with folders that have a large amount of images and it would make the most sense if it were related to E621 no longer having the file. I'm not entirely sure what file would be causing it, the folders it tends to happen with have a a hundred+ images so it's kind of difficult to test the integrity of them all. 

It's probably better to just assume that it correlates with the other issue though. The site constantly deletes and reuploads photos so it's actually incredibly likely that that's actually the case.

**Comment by Bionus** [comment]
In that case, I suppose the easiest way to confirm or infirm it would be to try again with the updated version (4.9.0) when it gets released this week-end.

*PS: sorry for the tardiness of my answer, I was quite busy the past few weeks.*

**Comment by Bionus** [comment]
I just uploaded the new 4.9.0 version, I hope it will fix your problem.

**Comment by ItDK** [comment]
Renaming is going on without a problem, consider the issue to be solved. Thank you and I really love your program.

**Comment by Bionus** [comment]
I'm closing it then.
And thanks, I'm doing my best :smile:
