### ISSUE TITLE
Not downloading all pics?

### ISSUE THREAD

**Issue by BigBrainAFK** [Bionus/imgbrd-grabber#645]
### What steps will reproduce the problem?
1. start grabber
2. set the sources to gelbooru
3. search for "lolicon -furry -futanari"
4. click "get all"

### What is the Problem?
It doesnt download all 109000+ pictures but only the first 20034 pics (at least it always does for me)

It counts the pages and the pictures correctly but downloads only the first 477 pages (and yes 20034 / 42 [pics per page] is exactly 477) 

Idk if thats how its supposed to be but i wanted to load all 109 thousand pictures not only the first 1/5 of it.

**Comment by Bionus** [comment]
Indeed, it seems that Gelbooru does not allow browsing more than 20,000 images.
See http://gelbooru.com/index.php?page=forum&s=view&id=1549 for more info

I'm looking if I can include a fix in the next version.
In the meantime, you can use the "solution" described in the thread above, even if quite tedious. Or refine your search more.

**Comment by Bionus** [comment]
It should be fixed if you replace your Gelbooru `model.xml` file (it's located in "sites/Gelbooru (2.0)" in your settings folder) by this one: [model.xml](https://github.com/Bionus/imgbrd-grabber/blob/e21e4df5d2b47ebd82529965b073da0d272dbadc/release/sites/Gelbooru%20(0.2)/model.xml).
The fix will also be included in next version (the model file will be updated when installing the update).

**Comment by BigBrainAFK** [comment]
I replaced the model.xml but uh now it shows the amount of pics (around 110 thousand) as the page amound.

http://puu.sh/s772j/17bbe0272a.png
