### ISSUE TITLE
URI shown as relative and can't open

### ISSUE THREAD

**Issue by xxzc** [Bionus/imgbrd-grabber#646]
### What steps will reproduce the problem?

![bug](https://cloud.githubusercontent.com/assets/905467/19687717/31006a32-9a8c-11e6-8d24-833f59159cdb.png)
Open image detail, click More detail, page.

The error says it can't open browser for the URI specificed.
### What version of the program are you using? On what operating system?

Version 4.8.3 commit 1e24b8a3d17b9aec60f934dc0bd345f77d54a139 Archlinux

**Comment by Bionus** [comment]
Indeed, I can reproduce this.
Seems like the site domain is not being properly added in this URL, thanks for the ticket!
