### ISSUE TITLE
Favorites border missing

### ISSUE THREAD

**Issue by ayyu** [Bionus/imgbrd-grabber#648]
### What is the expected behavior? What do you get instead?

Having a tag favorited doesn't give it the usual border. 
Favorite a tag, then see if it has a favorite border. Is there a new option somewhere to enable this again?
### What version of the program are you using? On what operating system?

Using version 4.8.3 on Windows 10.
Just upgraded from 4.7, where they used to work. RIP.
### Please provide any additional information below

See attached screens, e.g. favorited artist tag "souji", image on bottom left doesn't have the border any more.
![kantai](https://cloud.githubusercontent.com/assets/11494813/19824767/60c2ccb8-9d40-11e6-932c-593fc41b244e.PNG)
![souji](https://cloud.githubusercontent.com/assets/11494813/19824768/60c33d7e-9d40-11e6-8906-b2ffeea9591a.PNG)

**Comment by Bionus** [comment]
Indeed, it seems they disappeared in the last versions.

However, just for information, in your screenshot it's normal that there's no pink border around all images, since the favorite border is disabled for tags that are in the search (else, all images would be in pink, which doesn't help much).

**Comment by ayyu** [comment]
You're right, I should have specified more clearly. Just missing the border on the favorited tags that aren't in the current search.

**Comment by Bionus** [comment]
It will be fixed in the next version that will arrive this week-end, thanks for the info!
I don't have many favorites myself so I didn't notice. :smile:
