### ISSUE TITLE
Saving on the popup produces empty files

### ISSUE THREAD

**Issue by ayyu** [Bionus/imgbrd-grabber#649]
### What steps will reproduce the problem?

Click on any image, then try to Save or Save and Close.

Trying to save images by selecting, then downloading still works.
### What is the expected behavior? What do you get instead?

Image should be saved normally, instead I got an empty file (0 bytes).
### What version of the program are you using? On what operating system?

4.8.3 on Windows 10
![spooky ghosts](https://cloud.githubusercontent.com/assets/11494813/19824819/e0f0243a-9d40-11e6-8ef5-6e3e8462aaf2.PNG)

**Comment by Bionus** [comment]
I see a 0 byte file, could it be the same problem as issue #630 ?
If so, the fix will be included in the next release, which should arrive some time his week.

**Comment by ayyu** [comment]
yup, duplicate issue!
