### ISSUE TITLE
Single download issue

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#650]
### What steps will reproduce the problem?
Downloading a single file.

### What is the expected behavior? What do you get instead?
The downloaded files are corrupt? have no size. http://i.imgur.com/1eNMxt9.png

### What version of the program are you using? On what operating system?
4.8.3 on win 10

**Comment by Bionus** [comment]
I see a 0 byte file, could it be the same problem as issue #630 ?
If so, the fix will be included in the next release, which should arrive some time his week.

**Comment by brodycas3** [comment]
I'm pretty sure its own separate issue, Sorry.

**Comment by brodycas3** [comment]
Yeah looks like its right.

**Comment by Bionus** [comment]
In that case, let's move the discussion there.
The release should arrive this week-end.
