### ISSUE TITLE
Crash when adding new source

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#653]
### What steps will reproduce the problem?
Adding a new booru.

### What is the expected behavior? What do you get instead?
Crash

### What version of the program are you using? On what operating system?
4.9.0, Windows 10

### Please provide any additional information below
Ya dun goofed.

[Crash.zip](https://github.com/Bionus/imgbrd-grabber/files/574178/Crash.zip)

**Comment by Bionus** [comment]
Confirmed, working on a fix.

**Comment by brodycas3** [comment]
thankyou
