### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#654]
### What steps will reproduce the problem?

Only loads one one image. happens on other boorus too. here is a nifty gif with all the info and tags I'm using, http://i.imgur.com/MZ2yiHN.gifv

### Please provide any additional information below
If this isn't enough info comment and ill give more.

**Comment by Bionus** [comment]
But isn't there only one result for that search? [Link](http://atfbooru.ninja/posts?utf8=%E2%9C%93&tags=rumia+baby&ms=1) **NSFW**

**Comment by brodycas3** [comment]
oh, there is. But why when you click the empty spaces it shows the same thing. Why doesn't it show the image in the first slot?

**Comment by Bionus** [comment]
> oh, there is

I can't see them when browsing the website, and I believe it's the same for Grabber. Is there something special to do to see them? I even tried with a free account and there was still only one result for that search.

![image](https://cloud.githubusercontent.com/assets/882719/20199312/ea257ba4-a7a9-11e6-994d-d6fb266d47f1.png)

> But why when you click the empty spaces it shows the same thing. Why doesn't it show the image in the first slot?

Could you elaborate? I'm not sure I understand. Are you talking about the fact that the clickable area for an image in Grabber takes as much space as possible horizontally? In the current version, clicking anywhere in that area will open the image:

![image](https://cloud.githubusercontent.com/assets/882719/20199419/8535801c-a7aa-11e6-85e5-014cfc266fe1.png)

**Comment by brodycas3** [comment]
Why does it have this space? That's what made me think there were
more images.
http://i.imgur.com/R3HTH3m.png

**Comment by brodycas3** [comment]
Yeah that's pretty much what ihe issue is. It was making me think there were unloaded images

**Comment by Bionus** [comment]
Will be fixed by switching to the layout mode described in #883.
