### ISSUE TITLE
Crash when trying to login or change settings for Sankaku

### ISSUE THREAD

**Issue by zxhakuz** [Bionus/imgbrd-grabber#656]
### What steps will reproduce the problem?
1. click Sources
2. click options for chan.sankakucomplex
3. click download
4. change max simultaneous downloads to 1
5. click confirm

OR
1. click Sources
2. click options for chan.sankakucomplex
3. click credentials
4. click confirm

### What is the expected behavior? What do you get instead?
expected to save settings, program crashes instead

### What version of the program are you using? On what operating system?
release 4.9.1. Tried with both Ubuntu 16.04 and Windows 7

**Comment by Bionus** [comment]
Confirmed, working on a fix.

A temporary fix is to fill all the boxes in the "sources" tab of the Sankaku settings window (it crashes when there's an empty box).
