### ISSUE TITLE
Trying to add a shimmie site and it won't list any results.

### ISSUE THREAD

**Issue by MaxSnoBunnie** [Bionus/imgbrd-grabber#658]
### What steps will reproduce the problem?
When i add [Link](http://www.arrbooru.website/post/list/1) **NSFW**  no results are found. even if i select shimmie, yet the other shimmie site works fine. [Link](http://tentaclerape.net/post/list/1) **NSFW**

### What is the expected behavior? What do you get instead?
expected images to appear, none are shown.

### What version of the program are you using? On what operating system?
version 4.9.1 on windows 7 x64

### Please provide any additional information below
Any further information needed just ask.

**Comment by Bionus** [comment]
I updated the Shimmie model to work on this source.

You can find the updated file here: [model.xml](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/bac6c4d32260e1f68bd572ec5f7c8083a0a13787/release/sites/Shimmie/model.xml)
Replace the one located in `%localappdata%/Bionus/Grabber/sites/Shimmie` with it, restart Grabber and that source should work.

**Comment by MaxSnoBunnie** [comment]
thank you so much
