### ISSUE TITLE
Deleting Groups Causes the Group and Batch Numbers to be Different. Attempting to Download Certain Groups Causes Crashes.

### ISSUE THREAD

**Issue by ItDK** [Bionus/imgbrd-grabber#660]
### What steps will reproduce the problem?
Highlight a group—preferably in the middle of other groups—and use "delete selected" option. 

### What is the expected behavior? What do you get instead?
When deleting groups, group and batch numbers should have the same number. When downloading, the group number doesn't refer to the differing batch number to the right of it; it instead downloads from the batch number that is identical to it, if said batch still exists. (That's probably poorly explained, image below may help)

### What version of the program are you using? On what operating system?
4.9.1 (it's occurred on all past versions as far as I remember)
Windows 10 64bit

### Please provide any additional information below
![image](https://cloud.githubusercontent.com/assets/22891422/20220183/89907252-a7fa-11e6-877f-0ac1d36b5213.png)
Deleted Group/Batch 4 and 6 in the photo. Group number automatically updates but Batch number stays the same.

Groups 1, 2, and 3 download normally.

Attempting to download groups 4 or 5 result in nothing happening—no download window opening or crash—but attempting to download 6 causes a crash.

Group 7 downloads Batch 7 (Group 5), Group 8 downloads Batch 8 (Group 6),.. and so on.

**Comment by Bionus** [comment]
Issues confirmed!
Thanks for the well-detailed report, I'll start working on a fix right away. :smile:

**Comment by ItDK** [comment]
No problem. It was such a situational bug that I assumed no one else would ever find it. I had fun typing up everything and adding a picture... I'm practically a professional now :P
