### ISSUE TITLE
Can't manage to specify images per page for http://meme.booru.org/

### ISSUE THREAD

**Issue by beigexperience** [Bionus/imgbrd-grabber#661]
App crashes if images changed from sources tab. Changed manually in the .ini file, doesn't seem to have an effect on the images per page on the download tab. 

Can you add meme.booru.org? Seems to be a derivative of  Gelbooru Beta 0.1.11  but slightly different.

**Comment by Bionus** [comment]
I couldn't get a crash when using the source.
Browsing and downloading worked as expected:

![image](https://cloud.githubusercontent.com/assets/882719/20242603/936a9ad8-a934-11e6-9084-d7529083dbc9.png)

About changing the images per page for this source, it seems to just not be supported by Gelbooru 0.1.11 on which meme.booru.org is based on.
