### ISSUE TITLE
atfbooru.ninja can not be guessed and will not show image no matter what type.

### ISSUE THREAD

**Issue by kiingkiller** [Bionus/imgbrd-grabber#662]
i tried every type but every time when i hit enter it says zero images.

**Comment by Bionus** [comment]
The type guessing is included in issue #655, and will be fixed next version.
As for which type it is, I tried to add it just now as a Danbooru 2.0 board and could use it properly?

![image](https://cloud.githubusercontent.com/assets/882719/20242619/6efa90c6-a935-11e6-818b-4472b3549aa8.png)

**Comment by kiingkiller** [comment]
i'll do a clean reinstall and try again.

**Comment by Bionus** [comment]
All's good then, I'm closing the issue.
As for the "cannot guess" part, feel free to follow the status of #655. 😄

**Comment by brodycas3** [comment]
Actually, I'm pretty sure it was able to guess it for me.
