### ISSUE TITLE
Display nothing while exist pic file on local disk

### ISSUE THREAD

**Issue by MoeLin** [Bionus/imgbrd-grabber#663]
### What steps will reproduce the problem?
while the picture file is already exist on my local disk, click the pic list on the program will dispay nothing on the new window

### What version of the program are you using? On what operating system?

4.8.3

**Comment by Bionus** [comment]
I believe this issue has been fixed in 4.9.x.
Have you tried updating to the [latest version](https://github.com/Bionus/imgbrd-grabber/releases/latest)?

**Comment by MoeLin** [comment]
oh,sorry. I am really don't know it has been updated to 4.9, 
It has been fixed in 4.9 ,thank you!

**Comment by Bionus** [comment]
No problem, I'm closing this issue then. 😄
