### ISSUE TITLE
%species% token request

### ISSUE THREAD

**Issue by ItDK** [Bionus/imgbrd-grabber#666]
Would it be too difficult to add a token for the species? I'm not entirely sure if other boorus use any sort of species tags but it's common place on E621 and would be amazingly helpful.

Issue #666. I think it's a sign.

**Comment by Bionus** [comment]
It wouldn't be difficult depending on how cleanly I implement it.
If I do like the other tag type tokens, it could be pretty easy.

Is there anything more I need to know about this token?

* Name: `Species`
* Class: `species` (`tag-type-species`)
* ID: 5

**Comment by ItDK** [comment]
Not that I'm aware of. Looks like good work as per usual.

**Comment by Bionus** [comment]
There should be some basic support for it in 5.0.0a1.
All that's left is to add the settings tab in the options window (planned for the final release), feel free to try that new version.

**Comment by ItDK** [comment]
Thank you
