### ISSUE TITLE
Check for updates and auto-update

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#668]
Idk if I put requests here but I was wondering if you could make it so we don't have to redownload the installer to update. Kinda like how MultiMC updates without having to open the browser even.

https://multimc.org/
https://github.com/MultiMC/MultiMC5/

**Comment by Bionus** [comment]
I haven't tried MultiMC, so I don't know exactly how it manages updates.

One thing that could be added to Grabber with little work however would be:
* Automatic check for updates at start (with configurable interval in the options)
* Download button when there's an update to automatically download and run the installer (but you will still have to close Grabber and go through the installer's steps)
