### ISSUE TITLE
When searching, "&" will encode as "%26%26" instead of "%26"

### ISSUE THREAD

**Issue by sanddudu** [Bionus/imgbrd-grabber#671]
### What steps will reproduce the problem?
Search "&" with any source.

### What is the expected behavior? What do you get instead?
"&" should encode as "%26" instead of "%26%26"

### What version of the program are you using? On what operating system?
latest dev

**Comment by Bionus** [comment]
Bug reproduced.
Example of incriminated tags: `tiger_&_bunny`, `puzzle_&_dragons`, `panty_&_stocking_with_garterbelt`.

**Comment by sanddudu** [comment]
Well, I was searching "puzzle_&_dragons" too, LOL.
