### ISSUE TITLE
Allow to use Windows proxy settings

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#672]
In my country sankaku, konachan and etc. are blocked( that issue https://github.com/Bionus/imgbrd-grabber/issues/556 ), so I use auto proxy in Windows settings, but Grabber, I guess using his own proxy settings, but looks like there are only manually proxy configuration avilable... but I am using auto configuration script
So I think you need to add proxy auto configuration option, like it can be done in Windows proxy settings.

for exampe i need to use http://antizapret.prostovpn.org/proxy.pac

picture is not mine, but you can see that in Windows you can use autoconfiguration:
![](https://i.stack.imgur.com/ysOG9.png)

**Comment by Bionus** [comment]
Seems like using [QNetworkProxyFactory::setUseSystemConfiguration](https://doc.qt.io/qt-5/qnetworkproxyfactory.html#setUseSystemConfiguration) on program initialization could allow the use of the system-wide proxy settings.

I'll make some tests and try to come up with a patch to directly use Windows' proxy, which in your case is configured using a script.

**Comment by MasterPetrik** [comment]
![image](https://cloud.githubusercontent.com/assets/22294259/20506598/3cb33482-b066-11e6-8b40-eb9264927cc7.png)
and yep, directly use Windows proxy settings will be optimal

**Comment by MasterPetrik** [comment]
any proggress?
