### ISSUE TITLE
Russian translation troubles

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#675]
I'm going to update russian translation, but some moments are still unclear.

**first** of all I tried to use your Tranlation Tool from archive from https://github.com/Bionus/imgbrd-grabber/issues/657, and get error:
_This application failed to start because it could not find or load the Qt platform plugin "windows"
in ""_
just like in https://github.com/Bionus/imgbrd-grabber/issues/657, so I used your solution and it worked, but i think that you still need to update your archive with Tranlation Tool becouse the latest version looks like still lissing some dlls in archive.

As you know, in release 4.9.1 russian translation file is filled with bunch of franch text https://github.com/Bionus/imgbrd-grabber/issues/657, so I downloaded compiled exe version of the develop branch from https://github.com/Bionus/imgbrd-grabber/issues/664 and latest language files(whith that new languages.ini) so looks like untranlated strings in RU version now finally in english, but not everywhere:
![22112016_123141_mastercore](https://cloud.githubusercontent.com/assets/22294259/20519265/4672597e-b0b3-11e6-9f77-82f59c620958.png)
moreover crash report window is in french too:
![21112016_231052_mastercore](https://cloud.githubusercontent.com/assets/22294259/20519311/79cf804e-b0b3-11e6-8bfe-80a7128f6f3f.png)
all of this take place in last version of lang files directly from github source

**Comment by Bionus** [comment]
First, thanks a lot for this!
I know that quite a few Russian speakers use the program, and I was quite saddened by the state of the Russian translation, especially after the 5.0.0 update. 😅 

> just like in #657, so I used your solution and it worked, but i think that you need to update your archive with Tranlation Tool.

Indeed, I forgot to update the translation tools zip file. I'll upload the updated version tonight.

> and latest language files(whith that new languages.ini)

You mean you based your translation off [this file](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/develop/languages/Russian.ts) then?

> but not everywhere

If the issue in the main program is only in the log messages (and not some part of the UI), thanks for informing me, those should be in English so I'll translate them for the next release.
But note that you don't need to translate those, they should stay in English (or else I won't understand anything when someone sends me their logs).

> moreover crash report window is in french too

Yes indeed, the translation files are separate for the Crash Reporter.
I'll send you the links to the English-based `YourLanguage.ts` file for the Crash Reporter tonight too (in 8 hours). There isn't a lot of text in it but it's currently all in French so I'll just have to make a quick change to it.

**Comment by Bionus** [comment]
The translation file for the CrashReporter can be found here:
https://raw.githubusercontent.com/Bionus/imgbrd-grabber/develop/CrashReporter/languages/YourLanguage.ts

I updated the wiki accordingly. I also uploaded the translation tools including the windows platform DLL.

**Comment by MasterPetrik** [comment]
Please check https://github.com/Bionus/imgbrd-grabber/pull/678  The Russian translation file for the CrashReporter, tell me if something wrong with it.

**Comment by Bionus** [comment]
Moving discussion to #678.
