### ISSUE TITLE
zerochan login

### ISSUE THREAD

**Issue by actuallygodzillla** [Bionus/imgbrd-grabber#677]
is there any way to login on zerochan while using the grabber?
I ask because some images aren't view-able if you're not logged in. ;;

**Comment by Bionus** [comment]
It seems that the default Grabber's login configuration for zerochan, which used to work until now, has been broken by some update from Zerochan.

The login post request now requires two additional fields:
- ref=ref
- login=Login

I'll push an commit to add support for these two fields, that should be included in version 5.0.0.
