### ISSUE TITLE
losing download place

### ISSUE THREAD

**Issue by actuallygodzillla** [Bionus/imgbrd-grabber#683]
application stops working when I pause the download for more than thirty minutes and try to resume it. when i try to re-download the selection, it takes me straight back to the first image and loses it's place. is there a way to have it pick up where it stopped downloading?

**Comment by Bionus** [comment]
> when i try to re-download the selection, it takes me straight back to the first image and loses it's place. is there a way to have it pick up where it stopped downloading?

If you re-download all, it will just waste some time checking all images and downloading all pages, but it won't actually re-download the images (unless you changed the default settings).

**Comment by actuallygodzillla** [comment]
no, I don't.

**Comment by Bionus** [comment]
Moving to the more recent #872.
