### ISSUE TITLE
%count% isn't working in log files, and some tokens not working in batch downloads

### ISSUE THREAD

**Issue by redheadanon** [Bionus/imgbrd-grabber#684]
### What steps will reproduce the problem?

I used a small search with some animated to help refine my log parameters, so I searched "mazinkaiser" on chan.sankakucomplex.com (about 50 results, 5 are animated). But the counter wasn't working at all. I tried removing the length=6, but that didn't fix the problem.
My log file parameters:
| %count:length=6% | %md5:length=10% | .%ext:length=5% | <"animated" .%ext%>
And the count is stuck at 1:
![log file broken counter](https://cloud.githubusercontent.com/assets/24195182/20650989/fb8a482c-b4a9-11e6-89c6-61914dc46044.PNG)

And when using "download all" or "download page" I get a similar issue with filenames dropping artists, copyright, model, and character tags. Note that I have no issues with individual downloads, and the counter works fine with filenames.
My filename parameters:
<"animated"/>%count:length=6% - <%rating% - ><Artist=%artist:separator=+% - ><Copyright=%copyright:separator=+% - ><Model=%model:separator=+% - ><Character=%character:separator=+% - >%md5%.%ext%
 
![filenames](https://cloud.githubusercontent.com/assets/24195182/20651010/73c8ee10-b4aa-11e6-8af0-2da0ef913cb2.PNG)

I basically get "count - rating - md5.exe", and animated files do get sorted properly.

I got the same results on Gelbooru with "violet_eyes" and download all

### What version of the program are you using? On what operating system?

v4.9.1 on windows 7

**Comment by Bionus** [comment]
Indeed, it seems there is a problem with the `%count%` token except for filenames.
I'm working on a fix, thanks for the report. :smile:

It will be included in the 5.0.0 release.
