### ISSUE TITLE
Preloading images

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#685]
You said we can enable image preloading in the settings but I cant find it.

**Comment by Bionus** [comment]
In the options window, under the "Interface > Image window" category:

![image](https://cloud.githubusercontent.com/assets/882719/20683253/892aea2c-b5ab-11e6-8d32-c6fae4ce7b13.png)

Set it to 1 to preload the next and previous image. 0 (the default value) will disable preloading.
