### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#687]
### What steps will reproduce the problem?
resizing of the window
### What is the expected behavior? What do you get instead?
resize of the window working strange to search results in new version, images just dissapears and nothing after that can return programm to normal showing of results
### What version of the program are you using? On what operating system?
5.0 Win 7 x64

### Please provide any additional information below
![29112016_143759_mastercore](https://cloud.githubusercontent.com/assets/22294259/20708747/764fb4fe-b642-11e6-84dd-f93a07428896.png)
![29112016_143848_mastercore](https://cloud.githubusercontent.com/assets/22294259/20708748/78d54018-b642-11e6-9a6b-b82069fc70e5.png)

**Comment by Bionus** [comment]
Weird indeed. I'll check that out.

I have a question though: how did you get the result of your first screenshot?

> ![image.png](https://cloud.githubusercontent.com/assets/22294259/20708747/764fb4fe-b642-11e6-84dd-f93a07428896.png)

Where's the title (source link and image/page count) of the first line, as well as all the other images? According to your second screenshot, you had much more sources and results. It looks as if you have the scroll enabled, but no scrollbar?

**Comment by MasterPetrik** [comment]
I deleted Grabber, and installed it again, all options are default, when you search 1 source or 2-3 resizing work, but if you checked all sources search then after displaying results you will resize window, or turn it fullscreen/windowed and turn to previous condition, results will be broken and all images will be dissapeared(in fact not, but it will be too tiny that visually will not be show, but still clickable for preview)

And I searched with emoty search request, just pressed "Ok" button and grabber displayed me some images, but I'm checked that on some search requests and get the same result

> Where's the title (source link and image/page count) of the first line, as well as all the other images? According to your second screenshot, you had much more sources and results. It looks as if you have the scroll enabled, but no scrollbar?

Well, until you try to resize the window, you can scroll results with mouse wheel, but even then I don't saw any scroll bars appears, I thought that is odd, but I don't know is this a bug or normal work, but after resizing and dissapearing all images, after that scroll dont work at all(maybe its because all results now fits in window, when images almost-disappeared)

I recorded a video where you can see what steps will reproduce problems caused by resizing
https://youtu.be/DqWG36ffikM

**Comment by Bionus** [comment]
I see what's happening very clearly thanks to your video, thanks. From what I see, it seems like the thumbnails behave as if it's disabled while the layout itself behaves like a scroll area.

I can't seem to reproduce though, can I see your `settings.ini` file? While unlikely, I'll also check it on W7. Do you have "Use a scroll area for results" setting enabled in your "Interface" settings?

Note that if you have it disabled, the expected behavior is the one at the end: very small almost invisible images (ass in previous versions). If it's enabled, you should have only what's at the beginning, with a scrollbar though.

**Comment by MasterPetrik** [comment]
> Do you have "Use a scroll area for results" setting enabled in your "Interface" settings?

it was disabled.
I confirm that when I  enabled it all works correct and scroll bar appears. But looks like all that situation when its disabled still have is an unexpected behavior and need to be fixed...

and if you still needed, my settings.ini in turned to .txt
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/622813/settings.txt)
