### ISSUE TITLE
Save button in preview window issue

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#689]
### What version of the program are you using? On what operating system?
5.0 win7 64
problem with wrong text on the "Save" button in preview window after using it and moving to the next preview image, and next image and next... until you close the window
![29112016_193949_mastercore](https://cloud.githubusercontent.com/assets/22294259/20719589/7b083a86-b66d-11e6-9834-283cff05cf0e.png)
![29112016_193958_mastercore](https://cloud.githubusercontent.com/assets/22294259/20719606/8759c17e-b66d-11e6-81fd-15868b8de460.png)
![29112016_194008_mastercore](https://cloud.githubusercontent.com/assets/22294259/20719611/8cf1edf0-b66d-11e6-9737-bd423e7b5882.png)

**Comment by Bionus** [comment]
If I understand correctly, the issue is that the text is not reset to "Save" after we change the image using the arrows right?

**Comment by brodycas3** [comment]
Yup that's correct. I also have this glitch.
