### ISSUE TITLE
Save button in preview window: deleting file improvement

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#690]
How it works now:
you press "save" button and  image saves in folder, text on button turns into "saved!" and if you press it again text turns into "file already exist" and from this moment button becomes completly useless

How it can be improved:
you press "save" button and  image saves in folder, text on button turns into "saved!" and if you press it again text turns into "delete" and if you press it you can delete this image (if you changed your mind or missclicked or whatever) and if you press it and delete an image, then button turns again into "save" button

**Comment by Bionus** [comment]
I don't see any reason why not.

**Comment by MasterPetrik** [comment]
If this function would be in grabber 5.2.0, it could partially solve https://github.com/Bionus/imgbrd-grabber/issues/794 by deleting "ignored" images and re saving them into the right place. 
So I guess, this functional should be added to grabber as soon as possible, because now there are no way to somehow delete a single images saved via preview. And this function is very needed.

**Comment by MasterPetrik** [comment]
please, add this function... It's so needed >_< 

In current garabber you have only one way to delete image, saved via preview - by pressing "Destination folder" in preview window, then you need to find this image in the folder and only then delete it manually. For each image.

**Comment by barryanders** [comment]
Cool idea. Just so long as it is clear whether or not you already have the image.
