### ISSUE TITLE
Need a little tags scroll bar fix

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#692]
if tags doesn't fit in window in "tags on the left" mode then vertical scroll bar appears, ok. But scroll bar itself taking some width, so there are becoming less place for tags, and horizontal scroll bar appears, well I think something wrong with that. Looks like it can be easily fixed by increasing tags area width with scroll bar width value when vertical scroll bar appears, so horizontal scroll bar will not showing

![30112016_073016_mastercore](https://cloud.githubusercontent.com/assets/22294259/20739873/98d2b976-b6cf-11e6-8664-b0a86bd32fbd.png)
![30112016_073026_mastercore](https://cloud.githubusercontent.com/assets/22294259/20739874/9cfaa39c-b6cf-11e6-98f0-0ccda251c04b.png)

**Comment by Bionus** [comment]
Indeed, it can be fixed by adding the width of the scrollbar when it's displayed. I'm surprised no one ever reported this issue before, since it must have been here since forever.
