### ISSUE TITLE
Batch download window suggestion

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#695]
Why there are no so useful and obvious option "open destination folder"?
P.S.
Does anyone use "open CD-tray" option О_о? 
P.P.S.
What means "follow downloaded images" option? I do not understand what it is doing 
![30112016_145014_mastercore](https://cloud.githubusercontent.com/assets/22294259/20768833/789afc0a-b750-11e6-96ba-509c8eb4a414.png)

**Comment by Bionus** [comment]
It could be added indeed.

>  Does anyone use "open CD-tray" option О_о?

"Open CD tray" can be useful when doing really big downloads, and totally ignoring the computer in the meantime. But seeing how CD trays are becoming less and less useful, it's gonna be removed eventually.

>  What means "follow downloaded images" option? I do not understand what it is doing

It will automatically scroll the images list to follow the downloaded images.

**Comment by MasterPetrik** [comment]
> But seeing how CD trays are becoming less and less useful, it's gonna be removed eventually.

meh. This is so funny function(

> It will automatically scroll the images list to follow the downloaded images.

Get it, very useful. It will be hard to translate this caption in russian -___-

**Comment by brodycas3** [comment]
I would like an open destination folder but it would be nice if it were here instead, http://i.imgur.com/gQ5SGpd.png

I was thinking about opening an issue about it but I decided not to until I saw this post.

**Comment by Bionus** [comment]
> Please, consider that %search% \ %md5% . %ext% that kind of script, that creates folders for each search request can be set, and every search can create from one to several folders, so common "destination folder" path will be bad idea. Better choice here is to open folder where last image of the batch download has been saved, it will be optimal solution.

Opening the last folder won't be optimal either. What if the image path is "%id%/%md5%/image.%ext%" ? The last destination folder would be pretty useless. I understand your usecase though. A better option would be to open the deepest common folder for all downloaded images.

So if your filename is "%search%/%artist%/%id%/image.%ext%", and you search artist "enami_katsumi", the opened folder would be "C:/Path/enami_katsumi/enami_katsumi/" and not "C:/Path/enami_katsumi/enami_katsumi/123/" or "C:/Path/".

> I would like an open destination folder but it would be nice if it were here instead, http://i.imgur.com/gQ5SGpd.png

I could add a button, but isn't there already a link in the "File" menu or using the "Ctrl + O" shortcut?

**Comment by brodycas3** [comment]
What?

**Comment by MasterPetrik** [comment]
> So if your filename is "%search%/%artist%/%id%/image.%ext%", and you search artist "enami_katsumi", the opened folder would be "C:/Path/enami_katsumi/enami_katsumi/" and not "C:/Path/enami_katsumi/enami_katsumi/123/" or "C:/Path/". And if you search something like "rating:safe" that returns multiple artists, it would be "C:/Path/rating:safe/".
Looks good, I think it will be better indeed, but still need to try it by myself, if it will be added.

> What?

In main Grabber window If you press "Ctrl + O" shortcut you will exactly open your current destination folder

**Comment by brodycas3** [comment]
But that's obscure knowledge.

**Comment by Bionus** [comment]
I find it pretty well-displayed IMHO.

![image](https://cloud.githubusercontent.com/assets/882719/20805423/e1366244-b7f6-11e6-9a4b-13a28e2a4619.png)

I'm afraid that having too many things directly accessible directly might clutter the interface, while this compromise of a link in the menu + shortcut doesn't seem that bad.
