### ISSUE TITLE
Suggestion: custom image viewer support option

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#696]
At now in you double click on image in preview window, it rescales to fullscreen and sown on the black background, in this mode you can do noting with image so this mode looks like almost completely useless, but you can add an option king of "dblclick on prevew open image in default programm" and if you doubleclick on image it will be opened in associated with this extension programm (photoshop or some custum image viewer for example) and all of this programs has much more tools then simple black screen and can provide more comfortable view.

![30112016_231306_mastercore](https://cloud.githubusercontent.com/assets/22294259/20770000/39efd6a6-b755-11e6-91af-312fe9c3ee40.jpg)
you can also open full pic, its really big -___-

**Comment by brodycas3** [comment]
I would also like it so you can right click an image have a menu pop up and
copy it to a clipboard. It saves the hassle of having to open in the
browser and copy it from there.

**Comment by Bionus** [comment]
Could be useful indeed, since Grabber's viewer is very basic.

> At now in you double click on image in preview window, it rescales to fullscreen and sown on the black background, in this mode you can do noting with image so this mode looks like almost completely useless

It's useful for seeing the image bigger I guess, as well as for slideshows.

> but you can add an option king of "dblclick on prevew open image in default programm" and if you doubleclick on image it will be opened in associated with this extension programm (photoshop or some custum image viewer for example) and all of this programs has much more tools then simple black screen and can provide more comfortable view.

Note that if the image was not saved, and you open it with an image browser, the image will be located in some temporary directory, alone. So you won't get any navigation feature from the other viewers unless you save the image.

> I would also like it so you can right click an image have a menu pop up and copy it to a clipboard. It saves the hassle of having to open in the browser and copy it from there.

Copy what exactly? The image? Or are you talking about the tags context menu?

**Comment by brodycas3** [comment]
I'm talking about copying the image.

**Comment by MasterPetrik** [comment]
> Note that if the image was not saved, and you open it with an image browser, the image will be located in some temporary directory, alone. So you won't get any navigation feature from the other viewers unless you save the image.

There are all not for better navigation, but for better viewing/editing, its Ok to view image from Temp folder, its not a big deal,  for example in FastStone Image viewer you also see full image on black background, but you can cut/rescale it, resize it change image format, and after all save wherever you want,  and if you mind to use photoshop... hehe. So its all for that  purpose. User better know itself, what programm will be better for him for viewing)  But if you already pressed "save" button, of cource must be open exactly saved image but not temp image.

> Copy what exactly? The image? Or are you talking about the tags context menu?

Well they are both useful, maybe when you rightclick on the tag space you will find "Copy tags to clipboard" option, and when you rightclick on the image you will find "Copy image to clipboard" option. It will be very logical, I guess.
