### ISSUE TITLE
addictional buttons to "+" mode

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#697]
Clipboard functions requested in https://github.com/Bionus/imgbrd-grabber/issues/696 may also be added as a buttons and fill some empty space in "+" mode like this:
P.S.
It will be very logical if caption in all "+" buttons in Grabber turns to "-" when +mode is enabled as on pic 3 for example

![01122016_044050_mastercore](https://cloud.githubusercontent.com/assets/22294259/20779191/edcf8c92-b783-11e6-895b-2065c980dce6.png)
![01122016_050534_mastercore](https://cloud.githubusercontent.com/assets/22294259/20779283/8795062c-b784-11e6-9162-47e4517fbc15.png)
![01122016_044055_mastercore](https://cloud.githubusercontent.com/assets/22294259/20779285/8d5dfd8e-b784-11e6-8edb-faf2edcf47a6.png)

**Comment by brodycas3** [comment]
Yeah, but would it be able to have the option to copy the image or the post link to the clipboard?

**Comment by MasterPetrik** [comment]
there are no need any buttons for copying any links. Because to one image related many links, and yes, all of them you can see in "More details" and you can copy any of them to clipboard by right click menu, or directly open links in your browser by left click, Maybe "Copy link location" caption need to be changed to "Copy to clipboard" but anyway it all work.  
![02122016_054544_mastercore](https://cloud.githubusercontent.com/assets/22294259/20821359/ea6a6066-b852-11e6-9a3a-95b81edcdaa3.png)

**Comment by Bionus** [comment]
The empty space indeed could be filled with two additional buttons. However, I'm not sure if it should be these two.

From an UX point of view, wouldn't these two actions better be located in the context menu (on right click). Right click on the tags > copy all tags, right click on image > copy image. And maybe a shortcut on "Ctrl + C". Wouldn't that be more natural than a button, as it's the way it's done on Windows and most other OSes?

**Comment by MasterPetrik** [comment]
> The empty space indeed could be filled with two additional buttons. However, I'm not sure if it should be these two.

Indeed. It was just an example, its not a final request, of course that kind of buttons looks odd, forget about buttons for now, .

> From an UX point of view, wouldn't these two actions better be located in the context menu (on right click). Right click on the tags > copy all tags, right click on image > copy image. 

I thought about it, and, to be honest, I almost created new request about these right click actions, but now it will be logical to continue our discussion in this tread. So I guess this is exactly what we need but with a little correction: it should be - **Right click on the tag > copy that current tag**, this will be more useful, and native.

So sum up the subtotals of this tread requests:

1. Caption in all "+" buttons in Grabber turns to "-" when +mode is enabled

2.   in "More details" in right click menu"Copy link location" caption need to be changed to "Copy to clipboard"

3. Add right click actions for copying image, and tags:

- Right click on image > copy image
- Right click on the tag > copy tag

3. No additional buttons needed for now.

**Comment by brodycas3** [comment]
sounds great
