### ISSUE TITLE
Can't grab dates from certain sites

### ISSUE THREAD

**Issue by Marracas** [Bionus/imgbrd-grabber#700]
It seems that grabber cannot get the dates from posts in:

1. sankakucomplex (all)
2. gelbooru.com
3. rule34.paheal.net
4. tentaclerape.net
5. zerochan.net 

When told to save with %date%:

- Sankakucomplex, Gelbooru, Paheal, Tentaclerape.net does not write anything
- Zerochan.net gives "Browse Upload Subscribed Login Register" instead of a date

Posts in Sankakucomplex, Paheal, Tentaclerape.net, and Zerochan does not have the date posted directly in the page. It has the estimate date (X minutes/hours/days/months/years ago) written directly the page, but it has the actual (YYYY/MM/DD HH:MM) time as the alt-text on the estimate date
![att1](https://cloud.githubusercontent.com/assets/24316427/20835145/85cdaed2-b8cb-11e6-90ce-db8d8e9b881e.png)

Is this being looked at? Possible to fix?

Thanks in advance

**Comment by Bionus** [comment]
Indeed, some sources only give the date information on the image's page.

I'll look into it and find a fix for the sources that give the date information (which seems to be the case for all of those you noted).

**Comment by maskkulin** [comment]
Will there be a fix? It worked with Nandaka's Danbooru Downloader, I just switched from this poor program

**Comment by Bionus** [comment]
> this poor program

You mean Nandaka's or Grabber? From what I remember Nandaka's program wasn't that bad?

And yes, there will be a fix in v5.1.0 due for very soon, tomorrow if nothing bad happens.

**Comment by maskkulin** [comment]
that's wonderful, thanks for your insanely quick reply! Yeah it's overall a good program but it doesn't work well with Sankaku Channel and he ignores my cries for help
