### ISSUE TITLE
Fullscreen Slideshow won't show next image or gif if the current image is an animated gif

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#702]
When playing an animated gif in slideshow it won't display the next image, but when you press Esc it shows the next gif that was suppposed to be playing. (It actually skips to the next image but doesn't displays it)

Also i suggest an option specifically for animated posts (gifs,videos,webm) that makes the slideshow wait for the entire gif to finish playing before displaying the next one.

For example if you set the delay to 2 seconds and the gif is 4 seconds long it will skip to the next image after the gif is finished playing (4 seconds)
But if you set the delay to 10 seconds but the gif is 4 seconds long it will only skip after 10 seconds, but if the option is disabled then it would skip the gif no matter if it finished or not.

**Comment by Bionus** [comment]
> Also i suggest an option specifically for animated posts (gifs,videos,webm) that makes the slideshow wait for the entire gif to finish playing before displaying the next one.
> 
> For example if you set the delay to 2 seconds and the gif is 4 seconds long it will skip to the next image after the gif is finished playing (4 seconds)
> But if you set the delay to 10 seconds but the gif is 4 seconds long it will only skip after 10 seconds, but if the option is disabled then it would skip the gif no matter if it finished or not.

This is already the case (or at least should be). The timer to the next image only starts after the gif/video has finished playing. So if your video is 10s long and your interval 10s, it will take 20s to go to the next image.

**Comment by elreymu** [comment]
I guess this has something to do with the gif not finishing loading.

I suggest making the interval timer start when the current image is finished loading.
