### ISSUE TITLE
Restoring last session window must be always on top

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#705]
First of all, all save/restore session system works unstable in v5.0
Frequently after restore tabs, tabs in fact don't restoring. This bug https://github.com/Bionus/imgbrd-grabber/issues/694 shows pretty often, and after that in 50% cases if you will try to restore session, grabber will just immediately crashed. It will also frequently crashed after normal close-open-restore grabber situstions.

But this is more suggestion post then bugreport, so let me explain:
Here is the typical situation - You using grabber while exploring some booru site in your browser, you close/crash grabber. You try to open it again(for example through the shortcut in the Start menu) So you pressed a shortcut(browser still is full screen) and waiting Grabber to start... and nothing. You pressing shotrcut again, again waiting... and nothing. So whats the problem? Well, if you will minimize your browser you will see two beautiful crash-restore windows behind it. They are not displaying on the taskbar, so you cant even imagine that grabber is really launched. Moreover looks like this window displayed even if you dont open any tabs but just crashed grabber in last time, so you will be not expecting to see this window anyway...
![06122016_205244_mastercore](https://cloud.githubusercontent.com/assets/22294259/20937459/23bba5d4-bbf8-11e6-9cff-a07d7aaedab2.png)
This is very annoying so 
# I strongly recommend to make this window status is "always on top" and maybe show it in taskbar too. Thats all.

**Comment by brodycas3** [comment]
yeah that's a god idea, you have no idea now many times that was there for
days

**Comment by SultrySamthepennanceman** [comment]
Additionally, there seems to be an even bigger delay for crash-recovery on Grabber than before as I've noticed that no matter what, some searches I've made simply have not returned me to where I left off when I searched using the v5.0 grabber, it used to be a shirt wait after the window showed up then yes on recover then I'd get my session restored, but now it simply doesn't seem to be working at all anymore.
