### ISSUE TITLE
Crash on search

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#706]
### What steps will reproduce the problem?
Search Drow tag and get all, then search Dark_elf Blue_skin

### What is the expected behavior? What do you get instead?
Wanted results, got crash

### What version of the program are you using? On what operating system?
v5.0.0 win7

### Please provide any additional information below
*large ammount of sources.

**Comment by sinkiller21st** [comment]
I have the same problem but it with every search I do no matter what it is
