### ISSUE TITLE
restore last tab function

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#708]
I think if Grabber have a tab system, will be logical to add a funtion to restore last closed tab(like it uses in browsers)
It can be added in "File" menu, or it can placed in right-click menu on the tabs bar, I think it will be very native for users
![11122016_223415_mastercore](https://cloud.githubusercontent.com/assets/22294259/21082983/0a1a41ea-bff8-11e6-8b15-ba7469b2148d.png)

**Comment by barryanders** [comment]
If this is going to be implemented, may as well add a shortcut too. Pretty much every browser has a shortcut of `ctrl+shift+t` on Windows or `cmd+shift+t` on Mac to restore the last closed tab.

**Comment by Bionus** [comment]
Agreed on both.
I don't think I'll add it to the tab context menu though, only ion the "File" menu for starters.

**Comment by MasterPetrik** [comment]
Well, that's better then nothing)
