### ISSUE TITLE
Sankaku giving wrong file extensions (Image not found)

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#709]
The thumbnail shows up but the image itself won't load
When trying to download a GIF the log displays it as a SWF
When trying to download a JPG the log displays it as a MP4 and then displays Image not found

With gelbooru or other boorus it works fine as intended.

**Comment by Drakonas** [comment]
I can confirm this. !(https://dl.dropboxusercontent.com/u/3907397/img/Grabber_2016-12-15_05-23-23.png)

**Comment by Bionus** [comment]
Reproduced here too.
Only apply to "chan.sankaku" not "idol.sankaku".

I'll start working on a fix right away.

**Comment by brodycas3** [comment]
Could you push an update for this? It's very annoying.

**Comment by Bionus** [comment]
You can update your `model.xml` file with [this one](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/0621bed01c04f2fa18f532d20617f8aa118d7de3/release/sites/Sankaku/model.xml), it should fix the issue until the next release.

**Comment by brodycas3** [comment]
Where is it located?

**Comment by Hrxn** [comment]
On Windows?
`C:\Users\<USER>\AppData\Local\Bionus\Grabber\sites\Sankaku`

**Comment by Drakonas** [comment]
Someone is too anxious for naughty bits... Thanks for fixing this Bionus. Confirmed working.

**Comment by decipher90** [comment]
confirmed working, thanks
