### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#711]
Why does it take so long for this to load? Sometimes it never loads.

http://i.imgur.com/XZPJiDn.png

**Comment by brodycas3** [comment]
a lot of the time it never loads

**Comment by Bionus** [comment]
Which source/image/extension?
Could you provide the log file?

If the source is Sankaku, see issue #709.

**Comment by brodycas3** [comment]
Yeah, that seems to be it.
