### ISSUE TITLE
Empty folders fixer: is it generally works?

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#714]
..I don't think so.
I'm not found any information about this function on Grabber wiki, but I guess it is suppose to do something with empty folders in main folder. Well, it does nothing at all. "Continue" button doesn't looks functional, as well as "cancel" button(you can't close window by pressing it).

![17122016_220407_mastercore](https://cloud.githubusercontent.com/assets/22294259/21289100/f89c042e-c4a4-11e6-9499-282e673c1d5e.png)

What this function suppose to do? Delete empty folders or what?  
Anyway it doesn't work.

**Comment by barryanders** [comment]
I don't know what it's for either, but I've never questioned it since I haven't needed it. Should you ever need to delete empty directories, here's a nice solution :)

There's always an exe: http://www.jonasjohn.de/red.htm

or if you just need a quick command, try these. Should eliminate all empty subdirectories.

Batch:
`for /f "delims=" %d in ('dir /s /b /ad ^| sort /r') do rd "%d"`

Bash:
`find . -type d -empty -delete`

**Comment by MasterPetrik** [comment]
Thanks, for advice, but I yet writed a tiny delphi programm for this, and this is not a problem for me now.

The Problem is, that Empty folders fixer doesn't do anyhing. That's the problem.

**Comment by Bionus** [comment]
Indeed, it's supposed to remove empty folders that appear after a long usage of the program, both really empty and broken-empty (un-removable folders on windows without retorting to the command line). It was added so long time ago it must have broke during one the various updates.

Not sure whether I should make it work again, or just directly remove it though. Argument to remove it is that they are plenty of alternatives, and argument for keeping it would be that none of them are that accessible, and that after a while using Grabber there will definitely be a bunch of empty folders to remove.

**Comment by MasterPetrik** [comment]
better to repair this function, because this is not a big deal, i guess, and why not? I bet users will not go and install another programm to do this, more likely they will do it manually.  
This is a really useful tiny  function, so please FIX THE FIXER XD and don't remove it.

**Comment by barryanders** [comment]
The way I have used Grabber, I don't have an empty folders issue and can't foresee it happening. Guess it depends on how people use it.

**Comment by MasterPetrik** [comment]
For example, you using gragger with this pattern% search %% md5%.% Ext%
you set some search request, find bunch of images and download some of them, so in your download folder will appears many folders with some (2-7 for example) images, sometimes you open them and move images somewhere else, so folder becomes empty ... Yeah, i know that i can do that manually, but why not do this automaticly? This is very useful function, besides you can paste there any other path and delete empty folders there. So please fix it.
