### ISSUE TITLE
Error messages improvement

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#715]
Can it be possible to decrypt error code from error message to understandable message?

![17122016_041306_mastercore](https://cloud.githubusercontent.com/assets/22294259/21289175/3822c0ea-c4a7-11e6-8cfa-2b80688708e3.png)

Because I know that for example in Delphi using winAPI you can get standart error message from error code on your language using **GetLastError** function with **SysErrorMessage** function to do this. 
Kind of:
x:integer;
...
x:=GetLastError;
...
ShowMessage(SysErrorMessage(x))

Could it be that in your programm language might be similar function to do that?

**Comment by Bionus** [comment]
In that case, that's the HTTP status code.
In your case, a permanent redirection that should have been handled by Grabber but failed for some reason.

**Comment by MasterPetrik** [comment]
I'm Understood. Then I guess If you can't do something with that, you can close the issue.
