### ISSUE TITLE
Crash when changing from non-merged to merged during image-loading

### ISSUE THREAD

**Issue by Drakonas** [Bionus/imgbrd-grabber#716]
### What steps will reproduce the problem?
1. Turn off Merged Results.
2. Search something with a good number of images. 
3. Turn on Merged Results while the images are loading.

### What is the expected behavior? What do you get instead?
The program should work properly or catch the change of loaded images.
Instead the program crashes.

### What version of the program are you using? On what operating system?
5.0.1 on Windows 10 64-bit latest as of date.

### Please provide any additional information below
This can be reproduced both with and without Sankaku model.xml fix.

[Main.log](http://pastebin.com/8k7e21A0)
[Dumpfile](https://dl.dropboxusercontent.com/u/3907397/release/2495ce73-465e-4878-aa3e-09f922e3d0c2.dmp)

**Comment by Bionus** [comment]
Indeed, that's quite easily reproducible, I didn't think about this possibility of merging them in the middle of the loading, thanks!

**Comment by Drakonas** [comment]
my pleasure.. excited to see the 5.1.0 milestone closing in. ^^ I'm surprised nobody noticed this bug before.
