### ISSUE TITLE
Bug: Images displacements in search results grid.

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#718]
i faced with this bug many times, but now I can clearly reproduce it

Summary:
Win 7 64 Grabbr v 5.0.1
all results grid settings are default

[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/659763/settings.txt)

some images in some search results displaced and overlayed over other images, moreover some places for images in result grid are empty for some reason 
![19122016_020417_mastercore](https://cloud.githubusercontent.com/assets/22294259/21297616/2e2bf280-c594-11e6-8f20-f0a0d5a74de6.png)

## here, I recorded all process:
# https://youtu.be/kZf-9Nm5hmU

**Comment by MasterPetrik** [comment]
still appears in 5.2.3

**Comment by MasterPetrik** [comment]
![image](https://cloud.githubusercontent.com/assets/22294259/24164808/c4e86e04-0e7f-11e7-97aa-2ec67925b669.png)
I think, you should investigate it.

**Comment by MasterPetrik** [comment]
all I know, that this bug appears not only in the one source, but in any source, very randomly. And all images overlays other images woks with preview correctly. For example if you try to open top image "layer" by clicking it, in preview you will open exactly this image, and if you will do it with bottom image "layer", it will also correctly open exactly this image. 
So I guess, the problem is in results showing method. Need investigation.

**Comment by MasterPetrik** [comment]
still often appears in 5.2.4
Looks like this happends only in normal results mode, I never seen it happend in merged results mode.

**Comment by barryanders** [comment]
When I use blacklisted tags, it removes the image and leaves a blank spot where the image would have been. That looks like what's happening in your screenshot.

**Comment by Bionus** [comment]
This is very likely caused by the presence of a source with a different number of images per page in your results. Can it be reproduced with sources that all have exactly 20 images per page?

**Comment by MasterPetrik** [comment]
> When I use blacklisted tags, it removes the image and leaves a blank spot where the image would have been. That looks like what's happening in your screenshot... except you don't have blacklisted tags in your settings. 

It happens and if you search with blacklisted tag, and if you just search without even using a blacklist. So I don't think that this is connected somehow to this bug.

> In that case, maybe the image link is broken so it just leaves a blank box.

No. This isn't blank space instead of images in grid, this is displacement. Missed images are shown overlayed by another in another area of grid. So, images are just OK. and if you try to click on them where they placed, they will be opened in preview correctly. But if you click on blank space, you will get nothing. So obviously there are problem with grid filling, not with the images.

> This is very likely caused by the presence of a source with a different number of images per page in your results. Can it be reproduced with sources that all have exactly 20 images per page?

Sorry but I can't surely reproduse it to check your supposition. But it happend and with sources with and 20 images per page and for sources with different number of images per page.

**Comment by MasterPetrik** [comment]
still appears in 5.3.0. Alpha
![2017-05-13_051439 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26021728/97287fd6-379c-11e7-99c4-9d053853ddb5.png)

**Comment by Bionus** [comment]
I did not forget this issue, I read it, investigated quickly and could not reproduce at the time.

Let's not forget I'm the only developer working on this and I have limited time, so I beg your understanding. I have to prioritize issues: the ones I can reproduce and fix quickly or the critical ones take priority. And when I can't reproduce issues, what happened in this thread occurs: I push a fix but in the end it doesn't fix anything.

**Comment by MasterPetrik** [comment]
Looks like this bug occurs time by time, non constantly. Maybe it happens while connection problems to sites or something, because re-search in most cases fixes the grid

**Comment by Bionus** [comment]
Does the log show anything during the times this happens?
If there's a network issue or a server rejection, it should write something.

I keep trying to reproduce but have not yet had any success.

**Comment by MasterPetrik** [comment]
Anyway it's sucks to investigate non-regular bug that you can't force reproduse)
P.S.
will post some bugreports for 5.3.1 soon

**Comment by MasterPetrik** [comment]
What can I say... This issue is not appearing anymore, so it can be considered as fixed.
But, it's not the end of displacement issue!
In the new grid system appears new displacement bug. It's appearing conditions are very rare, It happens to me only twice for all time, and it's fixes by reloading tab, so it's not causes any serious problems and now I don't really care about that, but as tester, I should report this strange behavior.

![2017-09-24_210524 win7 mastercore8](https://user-images.githubusercontent.com/22294259/30844672-bc082e2a-a298-11e7-98b8-9689cfa6edce.png)

Look at this screenshot, loaded 143 images, but it's placed to only 40 slots grid, and all other images that don't fit in grid just overlayed first image. Since this issue about displacement, I decided to post it here.
