### ISSUE TITLE
WebM don't worked

### ISSUE THREAD

**Issue by cyb3rm4n** [Bionus/imgbrd-grabber#721]
### What steps will reproduce the problem?

Open any webm video on lolibooru/other site

### What is the expected behavior? What do you get instead?

tags only

### What version of the program are you using? On what operating system?

5.0.1

### Please provide any additional information below

Program can't play webm

**Comment by MasterPetrik** [comment]
maybe its because it is not a mediaplayer, but an image viewer?

**Comment by MasterPetrik** [comment]
# Bionus, if you read this -  I can suggest a solution:
if user opens an webm / mp4 / whatever video in preview window, just show thumbnail image of this video from site in the center of the preview window (maybe 200% upscale thumbnail), with play button painted on it, if you press to this preview image video will opens in default programm for it on user OS (MPC, Windows media player, etc). it can solve all the problems with codecs or inserting player directly in grabber, will not be so hard to code and will be very clear, I guess.

Kind of this (open image in full screen):
![26122016_065813_mastercore](https://cloud.githubusercontent.com/assets/22294259/21475190/7e185310-cb39-11e6-84f2-8246fa77333e.png)

**Comment by brodycas3** [comment]
I think the player should be built into grabber because *As I try to dodge the because I see all your god damn open tabs*

**Comment by Bionus** [comment]
If you want to play WebM videos in Grabber, you need to install the codecs: https://tools.google.com/dlpage/webmmf/

> Bionus, if you read this - I can suggest a solution

I always read everything :smile:

As for your suggestion, it's a good alternative to install-in the codecs (especially since they don't work very well with Qt).

**Comment by cyb3rm4n** [comment]
dont wored for me on lolibooru
![image](https://cloud.githubusercontent.com/assets/1812907/21483328/0073cef8-cb89-11e6-8e9a-28bcd15ab1f5.png)
WebMMF codec is installed.

**Comment by MasterPetrik** [comment]
> As for your suggestion, it's a good alternative to install-in the codecs (especially since they don't work very well with Qt).

> dont wored for me on lolibooru
> WebMMF codec is installed.

Well, me too.
Bionus, as you can see Current way isnt work properly and better way is to give this work to prof. media players. All of them can play webm, mp4, and will do it more fast, and with more options then any inside-Grabber mediaplayer. Just as images, download webm to Temp folder and then open it with default player in user OS. Easy and effective! I garantee, that users better open video in they favourite media player then in something else.

**Comment by MasterPetrik** [comment]
moreover, by remobing video player from grabber you can solve https://github.com/Bionus/imgbrd-grabber/issues/542 and other possible bugs with it :)
