### ISSUE TITLE
Copy image to clipboard issue/enhancment

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#722]
I copied an image to my clipboard and tried to paste it into discord but it doesn't work. I can't do it with any file from the grabber but I can do it with images from google. Can you make it work however google does it?

**Comment by brodycas3** [comment]
Because that's the only reason i wanted the copy feature.

**Comment by MasterPetrik** [comment]
I can confirm that images doesnt copy from right click menu. You cant paste it from clipboard.
P.S.
This is not "suggestion", this is a "bug" post

**Comment by Bionus** [comment]
> This is not "suggestion", this is a "bug" post

Pasting them as files in Windows explorer doesn't work either?

**Comment by MasterPetrik** [comment]
well, it works this way, but I think that the case was: copy image to clipboard to paste in programms, like paint or photoshop or skype. Pasting images in explorer is not as useful as ability to paste it to Paint and edit it, or to paste it to skype and send it . And grabber it is not work this way(
