### ISSUE TITLE
Downloading WEBM problem

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#724]
All downloaded webm videos are saved as .zip archive filled with bunch of frames in .jpg insted of one .webm file

for example webm with md5: **25b48c3adf74f61f7afe37836fa4ee7f** 
or bath download for search request: **barikiosu**

As you can see, this is comletely useless bunch of trash, and not an every user will be able convert it in something animated.

**Comment by Bionus** [comment]
That's because these files are not webm but `ugoira` (`うごイラ`), which is a stupid zip frame-by-frame animation format.

cf https://danbooru.donmai.us/wiki_pages/55658

**Comment by MasterPetrik** [comment]
But I guess, that you understand that user didn't expect to obtain .zip archive insted of animation. What he should do with this zip? Why in browsers its turns to webm?

**Comment by Bionus** [comment]
That's because Grabber doesn't download samples unless you set some setting for it (but then it will always download samples), it downloads the original images, which in this case is a ZIP (in the details window, the URL field). Since getting webm is lossy, users usually don't want that, even if ZIPs are inconvenient (somehow like downloading JPG instead of PNG because it saves space).

I could always add a setting to always download samples for them though.

**Comment by MasterPetrik** [comment]
compairing with JPG and PNG is incorrect. JPG and PNG - both graphical formats, but ZIP and WEB are completely different, first is a pack of frames, and second is video, JPG and PNG you can freely convert to each other, In case with ZIP and WEBM you cant convert it by common user means. When user downloads image he dont care jpg it or png because he will see his image anyway, so he dont care. But when he download ANIMATION he expects to see animation, not a bunch of jpg in ZIP archive, he expecting GIF or WEBM, or mp4 but not a archive with images that he cant turn into animation

**Comment by Gaffnet** [comment]
I used Grabber v5.0.1 to download the file mentioned in the original post from danbooru.

Grabber actually downloaded and saved it _correctly_ as a .webm file.  I verified this by looking at the file header, compared it to other .webm files, then ran a utility called "TrID" which identifies file formats and fixes wrong file extensions.

The actual problem in this particular case is not that Grabber downloaded a ugoira archive, but rather that Grabber saved that .webm file from danbooru with a .zip extension.

**Comment by Gaffnet** [comment]
I used Grabber v5.0.1 to download the file mentioned in the original post from danbooru.

Grabber actually downloaded and saved it _correctly_ as a .webm file.  I verified this by looking at the file header, compared it to other .webm files, then ran a utility called "TrID" which identifies file formats and fixes wrong file extensions.

The filename format I used for the test is: `%md5%.%ext%`

The actual problem in this particular case is not that Grabber downloaded a ugoira archive, but rather that Grabber saved that .webm file from danbooru with a .zip extension for some reason.

**Comment by Bionus** [comment]
@Gaffnet indeed, it seems that some kind of "support" was added with issue #514, but only for the image window (and as you say, saving the webm with the zip extension). For batch downloads, the full zips are downloaded.

**Comment by Gaffnet** [comment]
Ah, yes, I see.  Forgive the confusion.  I must have saved the test animation via the display window.

**Comment by Bionus** [comment]
No problem. I just pushed a fix, so in next version ugoira images will download as webm in both batch download and image window.

**Comment by MasterPetrik** [comment]
The problem with webm and ugoira is much bigger.
I downloaded the files mentioned in the original post from danbooru:webm through the link and zip through the grabber or browser(and manually renamed zip to webm)
![image](https://cloud.githubusercontent.com/assets/22294259/21597232/272504d4-d158-11e6-93ab-3583c105466b.png)
Looks like original UGOIRA format can be played via media players(I used MPC) as video, and it's his native feature, BUT! Sample WEBM framerate and UGOIRA framerate are completely different! in sample webm its 0:07s and in UGOIRA its 0:02s, this is very important part!  UGOIRA format cant set framerate by itself! User must set it manually when he upload his animation to danbooru, so site will do sample webm with right framerate automaticly.

IN TOTAL:
User watches the sample, he want to download WEBM, but he download lossless UGORIA WEBM with wrong framerate. You can try it by yourself. I repeat: user wants do download video, that he just watched, but UGOIRA video is not that video, with wrong framerate and its size weight 300% of sample.

## HERE IS THE SOLUTION:
1. Download sample video by default.
2. Add an option to the settings - "download original for WEBM" or "download UGOIRA instead of WEBM" or "download lossless webm" or something like that.
