### ISSUE TITLE
155 o Filesize and "non" existing images

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#725]
### What steps will reproduce the problem?

So far i downloaded from tag "christmas".

1.Loading the images by tag "christmas" on "sankakucomplex.com"
 
 First problem accours when going to the last page (1446 pages)

2. Next problem accours when pressing "Get all" or " Get Page " and afterwards "Download" or "Download selected"

### What is the expected behavior? What do you get instead?

1. The error " No Result  Possible Reason: page to far

2. It loads all the pages but instead of downloading the full size pic it downloads pictures with 155 o  filesize description.
 The pictures seem to be samples and usually are around 105 x 100 etc.
Surprisingly some pictures download fullsize without any problem.

I also can´t download the pictures manually , it shows up the thumbnail after tag search by pressing on the thumb shows up no picture, nor does it let me save the picture , instead of that it stays on "saving..."

Another problem is, some pages end up " *files not found on the server, though when i check on sankaku they are all fully avaible aswell as the original image etc.

### What version of the program are you using? On what operating system?

I use the newest Grabber version 5.0.1

Win 7 Home Premium Service Pack 1

### Please provide any additional information below

I am logged in in Sankaku with my Account.

I use https secured connection in the settings.

Here an additional picture.

![sankakufs](https://cloud.githubusercontent.com/assets/17236196/21533826/02037232-cd5f-11e6-807b-82beeff66e13.png)

[mainlog.txt](https://github.com/Bionus/imgbrd-grabber/files/676427/mainlog.txt)

**Comment by LordOfLA** [comment]
So did some digging - you need to edit the model.xml file in AppData\Local\Bionus\Grabber\sites\Sankaku

Edit the line: 

<ImageReplaces>/preview/->/&amp;.sankakucomplex->is.sankakucomplex</ImageReplaces>

Replace with:

<ImageReplaces>/preview/->/&amp;.sankakucomplex->s.sankakucomplex</ImageReplaces>

Enjoy downloading images again.

**Comment by DraGoran** [comment]
nope still the same

**Comment by DraGoran** [comment]
next problem

grabber is crashing while it is in the download process of the pictures

here is all data you need

[model.txt](https://github.com/Bionus/imgbrd-grabber/files/682244/model.txt)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/682245/settings.txt)
[settings2.txt](https://github.com/Bionus/imgbrd-grabber/files/682246/settings2.txt)

**Comment by Bionus** [comment]
So the fix is the same as for issue #709 then?

**Comment by Bionus** [comment]
This should be fixed in 5.1.0, feel free to re-open if you still have the same issue.
