### ISSUE TITLE
Keep same session restore message even when auto-restore is enabled in the settings

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#726]
Sorry for CapsLock, but this little window makes me crazy: 

![29122016_014202_mastercore](https://cloud.githubusercontent.com/assets/22294259/21533789/69f00b8e-cd6f-11e6-8937-a4358e8264a0.png)

In all other programms similar windows means "do you want to restore your last session?"
But here, I don't know why, text means "do you want to NOT RESTORE your last session?" and selected "yes" button. Here the situation: Grabber crashed, again:) You want to quick returns to search, you expect standard restore bla-bla-bla window, and you automaticly skipping it by pressing enter or, traditional press "yes" button expecting to restore your last session, and...!%^&*@$&@!!! All opened tabs erased, and you cant bring them back. 

I'm sure, that I am not the only one who faced with this problem.

So please do this:
change window meaning to "Grabber crashed bla-bla-bla. Do you want to restore your last session?"
and set focus on button "yes"
This will be more common and will not cause misunderstanding.

THIS IS REALLY IMPORTANT ISSUE,  so much tabs lost... so much ...please stop it >_<

**Comment by brodycas3** [comment]
Yes this is annoying. Its like your trying to confuse is with this.
