### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by andycontrib** [Bionus/imgbrd-grabber#735]
Trying to run grabber alongside gelbooru. Commands are just running at all. 

### What steps will reproduce the problem?
I tried each in the Options>Commands>Image text box (not the Database commands)
- `cp %path% /path/to/images`
- `touch /home/user/testfile.log`
- `nmap -p 8080 localhost` (just to test if file operations werent allowed)

Then downloaded some gelbooru images, nothing appeared to show up after each use case

### What is the expected behavior? What do you get instead?
I should have seen the images in the given folder or `touch` should have just made a file. Instead nothing appears to happen

### What version of the program are you using? On what operating system?
- Running arch linux
- arch equivilant of packages - `qt5-base qt5-tools qt5-script qt5-multimedia libpulse`
- I compiled from the source code v5.0.1

### Please provide any additional information below
one strange thing was in the `build.sh` file it says `mv "gui/Grabber" release` but gui it is in `gui/build/release/Grabber`

log from running
```
propsReply "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
nmReply "Method \"GetDevices\" with signature \"\" on interface \"org.freedesktop.NetworkManager\" doesn't exist\n"
"Object path cannot be empty"
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
QIODevice::read (QNetworkReplyHttpImpl): device not open
"Unexpected reply signature: got \"\", expected \"a{sv}\""
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1972, resource id: 4195180, major code: 40 (TranslateCoords), minor code: 0
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
"Unexpected reply signature: got \"\", expected \"a{sv}\""
```

**Comment by Bionus** [comment]
It seems a bug makes it that you have to restart the program to have the commands apply to new downloads. I'll try to fix this for the next release.

In the meantime, you have to restart Grabber after changing your commands settings, sorry about that.

**Comment by andycontrib** [comment]
good to know I can still use them! I just discovered `touch` will never work, but `cp "%path" "/folder/path/"` with quotes worked after a restart
