### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#736]
### What steps will reproduce the problem?
Downloading from the tag "Lich" under Merged results with a Proxy such as Privoxy on.

### What is the expected behavior? What do you get instead?
A crash at around 140-ish pictures DLLed

### What version of the program are you using? On what operating system?
5.0.1

**Comment by Bionus** [comment]
Does this only happen with a proxy and with merged sources? (or maybe you can't try without one anyway)
Is there anything special visible in the logs?
