### ISSUE TITLE
Center images in image window

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#742]
Allow images to be Centered instead of along the side of the image viewer.
Do this instead,
![p0k8oy3](https://cloud.githubusercontent.com/assets/19770864/21964645/065da484-db1e-11e6-9191-bcbe40bcea85.png)

**Comment by MasterPetrik** [comment]
I cant fully agree with you. 
Yes, option to Center images in Preview will be good, but if it will be optional, because I prefer classic image window because it similal to Booru~ sites preview pages

**Comment by brodycas3** [comment]
What booru has its image on the left?

**Comment by MasterPetrik** [comment]
sankaku, gelbooru, danbooru, safebooru, yande.re etc.

**Comment by MasterPetrik** [comment]
well, you can use tag-to-the-left mode in grabber too

**Comment by brodycas3** [comment]
I would just rather have my images centered

**Comment by Keith94** [comment]
I would also prefer centered images; Firefox and many image viewers have this by default.

**Comment by MasterPetrik** [comment]
In that case, can you please do a separete position settings for images and for video?
It will be very convinient and also solve https://github.com/Bionus/imgbrd-grabber/issues/777 issue

Something like that:
![2017-02-21_225143 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23197463/9da18bc8-f8d1-11e6-9f59-d8ec083e8f5d.png)

**Comment by Bionus** [comment]
So something like (v5.2.1):

![image](https://cloud.githubusercontent.com/assets/882719/23331896/40b71b8a-fb6f-11e6-9a66-16ec028cb768.png)

* Image = static image
* Animation = GIF or other playable animation
* Video = thumbnail to open the video

**Comment by MasterPetrik** [comment]
looks great, thanks!
