### ISSUE TITLE
How to change Date Time Format?

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#743]
Now that dates are finally working I want to change it to dd-MM-yyyy but I just can't find the option n_n

**Comment by Bionus** [comment]
Hello,

Did you check the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename#dates) wiki page?
There's documentation on how to change the filename date format.

In your case something like:
```
%date:format=dd-MM-yyyy%
```

**Comment by maskkulin** [comment]
whoops
