### ISSUE TITLE
Batch Download is messing up the filename + questions

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#744]
### What steps will reproduce the problem?
When I download the images it comes out like this, despite the fact that the pics contain the required information, it is not included in the filename. It only works if I save the pics per hand
https://puu.sh/tocbh/dd2bfd8d31.png

Also I have another question: 
What is the default max length?
Is it possible to change the Images limit so that one can download a bunch of pics in one go?

**Comment by Bionus** [comment]
What filename are you using, and which source are you downloading from? (+ which API)
The `main.log` could help identify the problem, too.

> What is the default max length?

You mean filename max length? It's limited by Windows (I assume that's the OS you're using), and the rules are pretty complex. In short, 260 characters. You can customize it in Grabber's options, but you can't go above this limit anyway.

> Is it possible to change the Images limit so that one can download a bunch of pics in one go?

Why not? Just edit the batch download table, changing the value. You can also change the "Images per page" value depending on the source you're using to make less page requests. For example, on Danbooru you could increase the images per page to 200 and change the image limit to 2000 to download 10 pages of 200 images (2000 images total).

**Comment by maskkulin** [comment]
My filename is %copyright:separator=+% - %artist:separator=+% - %character:separator=+% - %date:format=dd.MM.yyyy% - %id% - %md5%.%ext%
I am downloading from Sankaku Complex
As tag I use yuri

**Comment by maskkulin** [comment]
Hey it works with Danbooru! It doesn't work with Gelbooru and Sankaku complex (I only tested those). So maybe the problem is not caused by me? Can you fix it?

**Comment by Bionus** [comment]
Indeed, it's broken when you use parameters in your filename tokens.

As a temporary fix, you can set your tag separator in your settings to `+`, then use the `%copyright% - %artist% - %character% - %date:format=dd.MM.yyyy% - %id% - %md5%.%ext%` filename format, it should work.

**Comment by maskkulin** [comment]
> As a temporary fix, you can set your tag separator in your settings to `+`

this is how my filename was at first and if I'm not mistaken the separator is set to `+` at default. Like you said, it works like this, but the tags are not getting separated with `+`.
You mean this option right? https://puu.sh/toHaW/2914b00e8f.png
Look it doesn't work https://puu.sh/toHn5/3edfa5c98c.png

**Comment by Bionus** [comment]
> You mean this option right? https://puu.sh/toHaW/2914b00e8f.png

It should have been indeed, so in the end here's another issue with the last update! Thanks for the info, seems like these "Separator" options for tag types don't work, so you'll have to use the "Tag separator" one in the options.

Sorry for the double workaround, I'll publish the 5.1.1 soon that should fix this.
