### ISSUE TITLE
zerochan problem

### ISSUE THREAD

**Issue by kml213** [Bionus/imgbrd-grabber#752]
I recently downloaded the newest version of grabber and when I try to search using zerochan, it says that there were no results found.

**Comment by Bionus** [comment]
Do you have any more details?
The `main.log` file, for example?

Does this always happen or only when searching a tag? Are you logged in? Which source is first in your settings, RSS or Regex?

**Comment by Bionus** [comment]
Closing for lack of updates, feel free to reopen and give more information.
