### ISSUE TITLE
Exclude tags not working

### ISSUE THREAD

**Issue by Ausarr** [Bionus/imgbrd-grabber#753]
### What steps will reproduce the problem?

Put a minus sign to exclude tags from the search. Watch it disappear as we start to type the word we want excluded

### What is the expected behavior? What do you get instead?

As an example, expected behavior is to see a "-censored" tag in the search tag bar to then have censored images excluded from the results. What I get instead is that the minus sign disappears, so the tag search is only "censored", meaning the search results will show censored images.

### What version of the program are you using? On what operating system?

v5.1.0 and Windows 7 pro

### Please provide any additional information below

If I first type "censored", then put the minus sign in the front, the word "censored" becomes red.

**Comment by MasterPetrik** [comment]
isnt your bugreport fully duplicate https://github.com/Bionus/imgbrd-grabber/issues/745 issue? Looks like it already fixed and will be released in next patch

**Comment by Ausarr** [comment]
Oh yeah. I thought it was weird to have this exclude tag bug (since I believed it was common use), so I looked for 'exclude' in the search and found nothing. Then I took a quick glance at the new issues, but somehow my eyes skipped this one. Sorry fo any trouble.

**Comment by Bionus** [comment]
Indeed, this bug was introduced in last update and will be fixed in the next release next week.
I'm closing this issue, follow-up on the original one.
