### ISSUE TITLE
reverse image search GUI improvement

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#754]
> Added SauceNAO, IQDB and TinEye reverse image search (issue #723)

![image](https://cloud.githubusercontent.com/assets/22294259/22180380/b6104538-e07f-11e6-8f9f-b4f5f563bde1.png)

Good work! 
Maybe then you will add google image search too?

here is google url for that:
**http://www.google.com/searchbyimage?image_url=**

And... if you don't mind add yandex image search too, you can try it, it's very powerful tool.
here is the yandex url for that:
**https://yandex.ru/images/search?rpt=imageview&img_url=**

And.... if you don't mind completely then you can add waifu2x service for upscale anime images.
here is the waifu2x urls for that for every grabber lanuage, would be great if link would be chosen by grabber language settings:

English - **http://waifu2x.udp.jp/index.html?url=**
Franch - **http://waifu2x.udp.jp/index.fr.html?url=**
Russian - **http://waifu2x.udp.jp/index.ru.html?url=**
Chinese - **http://waifu2x.udp.jp/index.zh-CN.html?url=**

And place IQDB if first place in the list because it's most powerful and popular service among them.

I guess that is how it should looks:
![2017-01-22_084918 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22188302/e3981a8a-e124-11e6-9324-fefd6a7e1bb3.png)

P.S.
I guess that not very convinient to each time open preview window and only then revers search.
So it will be very useful to add this rightclick menu to all results window too.

that is what I mean:
![2017-01-22_155621 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22185587/9248dc08-e0f9-11e6-8236-8e2ca5e3ec0d.png)

**Comment by MasterPetrik** [comment]
Maybe it will be a good idea to add in rightclick menu an ability to search THIS image md5 in new grabber tab. 
It will help to, for example, find another copy of untagged image on other boorus and find the same image but with, for example, an artist tag to search it directly in grabber.
![2017-01-22_084918 win7 mastercore4](https://cloud.githubusercontent.com/assets/22294259/22394819/d26e1ca8-e53b-11e6-94ee-5d230ce74b5d.png)

**Comment by brodycas3** [comment]
Good suggestion but make sure the waifu link is the English one XD

English: http://waifu2x.udp.jp/index.html

**Comment by MasterPetrik** [comment]
Thanks, I fixed the link. I hope the site saves the language choice.

**Comment by Bionus** [comment]
Not sure I get the point of the waifu2x?

**Comment by MasterPetrik** [comment]
looks like Yandex search doesnt work for some reason.

**Comment by brodycas3** [comment]
Waifu2x Doesn't belong in this. All it does is upscale images with great quality.

**Comment by MasterPetrik** [comment]
waifu2x is a unique site that can remove jpeg artifacts and upscale images using the power of Deep Convolutional Neural Networks. 
If you think that image, that you found via search in Grabber have a jpeg artifacts or very low resolution for you to save, you can open it in waifu2x, upscale it and then save. So its very powerful tool for these situations.
