### ISSUE TITLE
Bizarre tag specific Crash

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#758]
### What steps will reproduce the problem?
Merged View, Results set to 25 per page, Search: Ogami

### What is the expected behavior? What do you get instead?
Being able to open up the thumbnailed images for preview, instead the program freezes in entirety, and crashes, though no report window comes up, I can still restore the session however, and repeat the process.

### What version of the program are you using? On what operating system?
5.1.0

### Please provide any additional information below
Doesn't seem to happen with anything else, so I've not the foggiest of what causes this crash in particular.

**Comment by MasterPetrik** [comment]
I can't reproduce your crash. 
In merge results we don't know from what site was image, crashed your grabber, but you could see the source in details in preview... I don't think that your information is enough to figure out where is the problem. Looks like you can't reproduce it too.
