### ISSUE TITLE
Sankaku Complex exclude tags not working

### ISSUE THREAD

**Issue by jackx2323** [Bionus/imgbrd-grabber#760]
### What steps will reproduce the problem? What do you get instead?

I search one, two, three tags with no problem in Sankaku Complex, but when I want to exclude a tag (a hyphen at the beginning of the tag) it doesn't work. The tag that I want to exclude turns red, but Grabber gives me results WITH that tag. I hope I explained myself well.

[Example](http://i.imgur.com/qei7Gmw.png)

### What version of the program are you using? On what operating system?

Grabber 5.1.0 and Windows 8.1

**Comment by MasterPetrik** [comment]
Isn't your bugreport fully duplicate #745 and #753 issue? Looks like it already fixed and will be released in next patch

**Comment by Bionus** [comment]
Indeed, this bug was introduced in last update and will be fixed in the next release next week.
I'm closing this issue, follow-up on the original one.

**Comment by jackx2323** [comment]
OK
