### ISSUE TITLE
Bug: doubleclick on image in preview window sometimes dont work

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#763]
That's it.
Sometimes after opening preview window if you doubleclick on image expecting to open it externally... you will get nothing. Just no any result of doubleclicking. If you will go to next/previous image in same preview window, doubleclick will do nothing too. But if you close preview window and open it again all will work properly. 

Win7 64 Grabber last version

I tried to reproduce this manually many times but can't find conditions causing this. But I face with this issue very often though. So take a look please.

**Comment by Bionus** [comment]
Seems to be caused by images found in MD5 list but moved/deleted in the meantime.
