### ISSUE TITLE
Enhancement: Focus on image when open destination folder

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#766]
After saving image in Preview window, when you press "Destination folder" should not just open this folder, but open this folder AND focus on that image, otherwise it is pointless try to find that image in folder with tons of pics...
![2017-02-04_193531 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22619988/74289ee8-eb12-11e6-9fc0-84df16973e55.png)
## How it works now:
![2017-02-04_193631 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22619990/7c86d3ca-eb12-11e6-8c80-0778c4277755.png)
## How it should work:
![2017-02-04_193616 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22619989/78072d9a-eb12-11e6-8034-6ccca46b9777.png)

**Comment by brodycas3** [comment]
I agree, This is how chrome does it when you select open folder.

**Comment by MasterPetrik** [comment]
Not all work properly. Need to reopen with "bug" label.
new version of grabber, win7 64.
I faced with an unexpected behavior: if image in preview window "ignored" then when you press "Destination folder"  looks like that it open your windows profile folder with focus on "my documents" folder  instead of folder with file.

**Comment by Bionus** [comment]
What do you mean "ignored"?

**Comment by MasterPetrik** [comment]
![image](https://cloud.githubusercontent.com/assets/22294259/22626772/6d7caada-ebc6-11e6-8d82-6f6277f769d0.png)
i mean this situation.

**Comment by MasterPetrik** [comment]
Here I get a some issues with this in 5.2.0

with empty search request after saving image via preview window, it saves well in right folder, but when you press "destination folder" button in preview window, insdtead of folder with focused image in it, grabbr just opens your windows profil folder -_____-
