### ISSUE TITLE
SSL Isue

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#767]
### What steps will reproduce the problem?
searching any tag at  any sankaku site ( idol.sankakucomplex, chan.sankakucomplex) 

### What is the expected behavior? What do you get instead?
cannot find any results , no previews, no pages 

shows 

[20:53:01.815] Loading page http://chan.sankakucomplex.com/post/index?login={edited}&password_hash={edited}&appkey={edited}&limit=20&tags=fairy&page=1
[20:53:07.862] Loading error: Error creating SSL context ()
[20:53:07.863] Loading using Html failed. Retry using Json.
[20:53:13.865] Loading error: Error creating SSL context ()
[20:53:13.866] Loading using Json failed. Retry using Xml.
[20:53:19.856] Loading error: Error creating SSL context ()
[20:53:19.856] No valid source of the site returned result.

in log file

### What version of the program are you using? On what operating system?

5.1.1

Windows 10

### Please provide any additional information below

It also shows on all sankaku headers following

Name: User-Agent
Value: SCChannelApp/2.0.1(Android;black)

the issue might have to do with the header

attachements:

[settingsgrabber.txt](https://github.com/Bionus/imgbrd-grabber/files/753247/settingsgrabber.txt)
[settingssankaku.txt](https://github.com/Bionus/imgbrd-grabber/files/753248/settingssankaku.txt)
[model.txt](https://github.com/Bionus/imgbrd-grabber/files/753251/model.txt)

Tried to make grabber work on sankakucomplex for someone who is running windows 10 as operation system.

Microsoft C Redistrutables are installed
Goldendict is installed

**Comment by Bionus** [comment]
Does replacing the OpenSSL dlls (libeay32.dll, libssl32.dll, ssleay32.dll) by the latest version from [here](https://slproweb.com/products/Win32OpenSSL.html) fix the issue?

**Comment by DraGoran** [comment]
no it did not, i tried both, win 64 and win 32

**Comment by Bionus** [comment]
It seems installing [MSVC redist 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784) might fix the issue.
Maybe you can give it a try?
