### ISSUE TITLE
Yande.re score:>50 "Get All" - crash

### ISSUE THREAD

**Issue by Fillyosopher** [Bionus/imgbrd-grabber#768]
### What steps will reproduce the problem?
Searching "score:>50" on yande.re, hitting Get All, going to the download page and hitting "Download", waiting for 20 minutes.

### What is the expected behavior? What do you get instead?
I would expect it to continue downloading without interruption.  What happens is a crash after 20 minutes, or about 100 pictures.  the number of pictures does not seem consistant.

### What version of the program are you using? On what operating system?
This same error happened with both 5.0.1 and 5.1.1 .  Win 8.1 Enterprise.

### Please provide any additional information below
Provided are DMP files form the last 4 crashes and my settings.
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/757598/settings.txt)
[baaeb835-3e69-43d6-874e-5cb64f9ecc66.txt](https://github.com/Bionus/imgbrd-grabber/files/757600/baaeb835-3e69-43d6-874e-5cb64f9ecc66.txt)
[bc71254e-a3d9-4076-9e71-943dbb02c3c1.txt](https://github.com/Bionus/imgbrd-grabber/files/757602/bc71254e-a3d9-4076-9e71-943dbb02c3c1.txt)
[d2f491e0-dc04-4c94-b005-f2ea0acd2569.txt](https://github.com/Bionus/imgbrd-grabber/files/757601/d2f491e0-dc04-4c94-b005-f2ea0acd2569.txt)
[d2018b0f-59ce-48c0-89f2-34787248366f.txt](https://github.com/Bionus/imgbrd-grabber/files/757603/d2018b0f-59ce-48c0-89f2-34787248366f.txt)

Apologies for not having other testcases, I'll try other things over the next few days.  It only started crashing like this 2 days ago, prior to that I've used it to download 12000 off yande.re without incident.

**Comment by Fillyosopher** [comment]
Okay, I double-checked that it wasn't being interrupted by my hydrus client importing some of the just downloaded images while it was downloading others. It also hasn't crashed when I do ten pages at a time using the "get this page" button, so I suspect it isn't some bad image format or something.  I'm using "score:>50 date:<2015-12-16" as the search now so as not to be downloading those images that did download properly in the past.  I tried a smaller "get all" on e621.net and didn't have the crash.

**Comment by Bionus** [comment]
It sounds a lot like a RAM issue. For big downloads, Grabber first download all pages, and keep all image results in memory, with their information (tags, date, author, etc.). For your search, we get more than 80,000 images, which can result in up to 800MB of RAM only to store the results (~10KB per image).

The fact that you say it's random and don't happen when doing smaller batch downloads seem to confirm this. I'm currently making optimizations to reduce the program's memory footprint. But in general, it's better to keep the downloads to smaller sizes, sorry. As you saw, Grabber should not have any issues downloading up to 50K images, or 20K if you wanna be safe (or depending on your available RAM).

**Comment by barryanders** [comment]
Why not just download individually. You have a lot more control that way over the kind of content you get.

**Comment by Fillyosopher** [comment]
Hmmm, that's a definite possibility.  I'll watch my RAM closely the next chance I get to download and report back if that was the issue.

**Comment by Bionus** [comment]
Should be fixed by v5.2.0.
