### ISSUE TITLE
better favorite fonction, "quick update" image folder button?!?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#77]
I tought about this a while ago:

what if there was somekind of tool to search automatically new images in a list of favorites tags?

exemple:
- I have downloaded all the images about naruto, dragon_ball, saylor_moon on some boorus.
- since I am very interested in those images types, I put those 3 tags are in my "quick update" list.
- any time I open grabber another day, I simply click the "quick update" button, and grabber will search and download new images in the appropriate folder for each tags.
- that way, grabber user is happy to always have the up to date, freshest images for each of his point of interest.

_PS: i am not interested in naruto dragon ball or saylor moon, it was just for the exemple, ok? this is important to note!_

> Original issue reported on code.google.com by `ser...@hotmail.com` on 1 Mar 2012 at 8:15

**Comment by Bionus** [comment]
Done with monitors, first for favorites in 7.1.0, and more properly with 7.3.0.
