### ISSUE TITLE
Crash when trying to open preview

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#770]
### What steps will reproduce the problem?
1. MD5 search "25b48c3adf74f61f7afe37836fa4ee7f"
2. trying to open preview from sonohara.donmai.us
2. CRASH

### What is the expected behavior? What do you get instead?
Crash of Grabber instead of opening preview.

### What version of the program are you using? On what operating system?
tested from 5.0.0 to 5.1.1 win7 64

### Please provide any additional information below

![2017-02-07_174930 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22696094/ef2a1af2-ed5d-11e6-8951-23bcd9576719.png)

**Comment by MasterPetrik** [comment]
can confirm that crash still appears in 5.2.0 and still 100% repeatable
P.S.
 5.2.0 alpha is very unstable, it's clever decision not to release it yet.

**Comment by Bionus** [comment]
I couldn't reproduce it myself when testing. Is this image already saved on your hard drive? Is there anything in the log that could explain this crash?

What do you mean 5.2.0 is unstable?
I did a lot of tests without issues yesterday. I'll gladly make fixes and push the 5.2.1 tonight or tomorrow.

**Comment by MasterPetrik** [comment]
well, I used 5.2.0 only a couple of minutes but already found a several different crashes and other bugs)

**Comment by MasterPetrik** [comment]
> I couldn't reproduce it myself when testing. Is this image already saved on your hard drive? Is there anything in the log that could explain this crash?
No, image doesn't saved on hard drive. Nothing unusual in log after displaying results, but after trying to open preview from sonohara.donmai.us result immediate crash, so I can't see changes in log. 
here is the info about crash:
https://drive.google.com/open?id=0B3SK4Pf9wsnmYWxyNEJsOW5Hb00

**Comment by Bionus** [comment]
Indeed, it seems the released version had differences with the one I was using for testing, I'll check that out and push another 5.2.1 pre-release, sorry.

**Comment by MasterPetrik** [comment]
can you please check, is crash reporter window and restore session window have "always-on-top" status? 
Because for me they are not always-on-top, is that a normal behavior? 
![2017-02-19_211311 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23104955/850efa72-f6e8-11e6-9327-e66ffab392c8.png)
![2017-02-19_211329 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23104957/884cb8c8-f6e8-11e6-8950-6277959915b7.png)

**Comment by Bionus** [comment]
Thanks for the log, I get it now. I'll fix it in next patch.

**Comment by Bionus** [comment]
BTW, if you have examples of problems you have with 5.2.0, I'm all ears.

**Comment by MasterPetrik** [comment]
better post it here or create issues for each problem?

**Comment by Bionus** [comment]
Better create one issue for all, like "5.2.0 issues".
