### ISSUE TITLE
file name would be to long for destination folder

### ISSUE THREAD

**Issue by naruhina2016** [Bionus/imgbrd-grabber#771]
### What is the expected behavior? What do you get instead?
i,m getting an error that says file name would be to long for destination folder.
So how can i move pictures without renaming it or using any winrar file?

**Comment by MasterPetrik** [comment]
I guess you can place your download folder closer to the root directory of the local drive:
for example:
move from 
**C:\\something\something else\more something\idunno\somwhere here\Grabbed**
to
**C:\Grabbed**
will surely solve your problem
