### ISSUE TITLE
Enhancement: enlarge tiny thumbnail in preview and delay it

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#772]
Current thumbnail situation in Preview window is very uncomfortable. 
Everywhere these thumbnails appears while original image loading.
Its very frustrating to see how every time thumbnails appears in a second and became big image, especially when you going to the next image in preview.
These thumbnail  is are very confusing feature. 

## But there is a good solution for this situation:

1. DO NOT show thumbnails if original loaded fast(loading time less then 1-1.5 sec)
2. If image still downloading, show thumbnail, enlarged to original image size. ( The conversion of thumbnail to the original image will not be as sharp as it be in current version).

## NOW
![2017-02-05_165810 win7 mastercore -](https://cloud.githubusercontent.com/assets/22294259/22717822/4b1ec6a0-edae-11e6-8ea5-3064bcced646.png)
## HOW IT COULD BE
![2017-02-05_165810 win7 mastercore7 -](https://cloud.githubusercontent.com/assets/22294259/22717825/50324626-edae-11e6-993d-75ff3914d66c.png)
## COMPARE WITH LOADED ORIGINAL IMAGE
![2017-02-05_165819 win7 mastercore -](https://cloud.githubusercontent.com/assets/22294259/22717826/536221c2-edae-11e6-84f8-cc69e5303335.png)

**Comment by Bionus** [comment]
> DO NOT show thumbnails if original loaded fast(loading time less then 1-1.5 sec)

You can't guess how long the loading will take for such small durations. And if you display it after 1s, what if it takes 1.00001s to load? You'd have the same issue. Only having the thumbnail at the right size seem enough.

> If image show thumbnail, enlarged to original image size

Why not. :smile:

**Comment by MasterPetrik** [comment]
will add another suggestion for some minutes, dont log out

**Comment by MasterPetrik** [comment]
> You can't guess how long the loading will take for such small durations. And if you display it after 1s, what if it takes 1.00001s to load? You'd have the same issue. 

well, no. this suggestion is for only one purpose - for scrolling images in preview window, when you press ">" button many times you will see many blinking thumbnails every second, this is not good. especially when preloading enabled, original images already saved on PC, but thumbnails will appears for 0.01 s every time and disturb you. so 1 sec delay will be optimal and will solve this problem.

**Comment by Bionus** [comment]
In that case not showing the thumbnail at all if the image has already been loaded seems like a better option than adding some timer, isn't it?

**Comment by MasterPetrik** [comment]
yep that will work, but if you have a fast internet your new images will download very fast around 0.1-1s but you will still see useless(because all you will see will be just a blink) thumbnail, and it will disturb you anyway.
