### ISSUE TITLE
429 Too many requests

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#775]
Can you invent an option to delay the download, like every 5 seconds a pic will be downloaded. I don't know if that would actually be faster than just to ignore this 429, but it's worth a try ?

**Comment by Bionus** [comment]
This option is already available and is called "Throttling" in a source's settings page. :smile:
You can set the interval between each page, image, and how long to wait after a 429 error.

**Comment by maskkulin** [comment]
thanks. I looked into it and there's one unrelated setting I don't understand https://puu.sh/tVv8T/086a8602fe.png what does that mean?

**Comment by Bionus** [comment]
That's the number of images that will be ignored at the beginning of the first page.

In the case of Sankaku, they always add the "top 4" pictures on the first page. With this setting, they get ignored.

**Comment by maskkulin** [comment]
I see. 
You mean the interval options right? What does Interval (details) mean?

**Comment by maskkulin** [comment]
Hm it doesn't seems to work, what am I doing wrong? https://puu.sh/tVAdq/0cad726fe6.png
https://puu.sh/tVAiZ/7d2287801c.png
