### ISSUE TITLE
Favorites issues

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#779]
Favorites function is a very good idea. But still exist some issues.

Issue 1: No image in favorites for tags, added from search field directly. Images only added when you add tag to favorites from tag list in preview window.

Issue 2: Images in favorites search results part of page are so tiny that I barely can see them
![2017-02-11_184856 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22855080/dc788fee-f08a-11e6-8364-f9ebb2620b2c.png)

![2017-02-11_112407 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22855048/70c09382-f08a-11e6-9501-5a3d77cbe4ff.png)

So I can suggest a solutions:
1. For tags, added from search field, add as image first(or random) image that grabber found for that tag.

2. Change search results page mode to scrollable results page as it did in other grabber tabs.

Moreover, I want to discuss with you uselessness of non scroll search results mode, I guess it is no needed in grabber anymore, because mode with scrolling is better in all situations, and I doubt that somebody uses it at all. Maybe you should completely remove that mode from grabber? Because we have a better alternative.

**Comment by Bionus** [comment]
> Moreover, I want to discuss with you uselessness of non scroll search results mode, I guess it is no needed in grabber anymore, because mode with scrolling is better in all situations, and I doubt that somebody uses it at all. Maybe you should completely remove that mode from grabber? Because we have a better alternative.

I just made the scroll setting enabled by default. However, I don't plan to remove the old mode because it doesn't cost much to keep it technically-wise, and I, for one, use it. :smile:

**Comment by MasterPetrik** [comment]
>  I don't plan to remove the old mode because it doesn't cost much to keep it technically-wise, and I, for one, use it.
Understood.
Can't wait for new version of grabber... so many changes

**Comment by Bionus** [comment]
> Can't wait for new version of grabber... so many changes)

So many new bugs. :smile:
