### ISSUE TITLE
is this possible?

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#781]
is it possible to show a specific tag in the filename, only when the image has the tag.
Like I want all images that do have an incest tag, that they show it in the filename.
So when a pic has the tag it should look like this:
original - niliu chahui - original character+tokisaki mio+tokisaki asaba - incest - 21.01.2017 - 5824978 - 7a0d927af08f879858961d267e36b743
and when it doesn't have the tag, it should just ignore it:
original - niliu chahui - original character+tokisaki mio+tokisaki asaba - 21.01.2017 - 5824978 - 7a0d927af08f879858961d267e36b743

**Comment by Bionus** [comment]
There's two options for this. You can add a "Conditional filename" in the settings, with the "incest" tag as a condition, and the filename you want as value. Or you can use tag conditionals directly in your main filename, with something that looks like: `%artist% - %copyright<- "incest"> - %date%`. Everything between the brackets will only get inserted if the "incest" tag is found.

You should read the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) wiki page for more details.

**Comment by maskkulin** [comment]
I don't get it. What should I put in the condition field and what in the filename field?

**Comment by maskkulin** [comment]
thanks it works, I forgot to update the group
