### ISSUE TITLE
bug: wrong favorites tags color in search field

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#783]
### What steps will reproduce the problem?
1. I change tag color for favorites.
2. In preview window color changes well, but in search field it still default and I can't change its color.

### What is the expected behavior? 
Obviously color should be the same in all parts of GUI and should be able to change correctly.

### What version of the program are you using? On what operating system?
5.1.1 win7 64

### Please provide any additional information below

![2017-02-15_032636 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22955761/04fa5c58-f32f-11e6-95d3-a26a80faeb49.png)

![2017-02-15_032551 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22955757/01f403b0-f32f-11e6-9167-d5b1364b925d.png)

**Comment by Bionus** [comment]
Does it work after restarting Grabber?

**Comment by MasterPetrik** [comment]
Yes, this is still default color, no matter what I am doing.
