### ISSUE TITLE
What is the best way to download 100,000 files without Grabber crashing?

### ISSUE THREAD

**Issue by the612toon** [Bionus/imgbrd-grabber#784]
Is it even possible? I'm new to this program... Is there a way to download them all without it crashing?
Like I'm trying to get all loli images on Gelbooru but all that keeps happening is Grabber Crashing.

**Comment by barryanders** [comment]
I'm guessing this is a RAM issue which is detailed over here as well: https://github.com/Bionus/imgbrd-grabber/issues/768

**Comment by the612toon** [comment]
I think the devs should find a way to make Grabber get download a infinite amount of files...

I found a solution to the problem I'm having but I have to do it manually by setting my image limit to 25000, image per page to 20 (To keep track of what page I'm on), and I need to manually up my pages by 1250 each time I'm done downloading the image limit.

Suggestion: It would be cool if the developers made a "Safe Get All" button where it checks as many pages as your computer can handle and then after it's done downloading those pages, Grabber automatically gets the next X amount of pages until you reach the end of the Get All. (Sorry if that makes no sense)

**Comment by barryanders** [comment]
I haven't bulk downloaded anything in over a year, but is it possible to download a list of links in the GUI without the files? If so, you could probably get the entire list of links and then download them through the command line or something like that. You might even be able to use Grabber's CLI to do something like this. I haven't dug into though to give you more info.

**Comment by Bionus** [comment]
Should be fixed by v5.2.0 (see #785).
