### ISSUE TITLE
Can't install imgbrd-grabber in Debian 

### ISSUE THREAD

**Issue by Cryptosodomy** [Bionus/imgbrd-grabber#787]
### What steps will reproduce the problem?
For debian : 
sudo apt-get install qt5-qmake qtbase5-dev qtdeclarative5-dev qtscript5-dev qtmultimedia5-dev libpulse-dev
sudo apt-get install qt5-default qttools5-dev-tools
qmake Grabber.pro
make
mv gui/Grabber release/Grabber
touch release/settings.ini

So the first problem was that gui/Grabber didn't existed ( instead they are a gui.pro ) 
so i did go to /gui/build/release and finded a file named Grabber
so i moved it to release/Grabber 

### What is the expected behavior? What do you get instead?

Then , i suppose that i only have to go in /release and run grabber.desktop ( make it executable ) and it should work ?
I also tryed it on Fedora tbh and there is the same problem. ( with the guide you make for Fedora ) 

### What version of the program are you using? On what operating system?

Debian 9 Stretch : The last source avaiable
Fedora 25 : The last source avaiable

### Please provide any additional information below

Maybe you could update the compilation tutorial ? It don't seem to universally work for linux... 
Thanks !

**Comment by Bionus** [comment]
> So the first problem was that gui/Grabber didn't existed ( instead they are a gui.pro )
> so i did go to /gui/build/release and finded a file named Grabber
> so i moved it to release/Grabber .

Yes, it was moved from gui/Grabber to gui/build/release/Grabber in a previous commit, and has been fixed in the README.

> Then , i suppose that i only have to go in /release and run grabber.desktop ( make it executable ) and it should work ?

Shouldn't you directly run the Grabber executable file that you just copied from the gui/build/release folder instead?

**Comment by Cryptosodomy** [comment]
"Shouldn't you directly run the Grabber executable file that you just copied from the gui/build/release folder instead?"
Well i did , but it ask me to run with an app. its marked as an sharedlibraries

**Comment by Cryptosodomy** [comment]
Ok it worked. 
You can close it :)

**Comment by Bionus** [comment]
> Ok it worked.
> You can close it :)

What did you do to make it work? (so I can update the readme and wiki)

**Comment by Cryptosodomy** [comment]
I just did the good mv 

mv gui/build/release/Grabber release/Grabber
After that all worked well.
Just update that everywhere ( like comp wiki , readme... ) it should do the trick  !

**Comment by Bionus** [comment]
Closing because the doc has been updated.
