### ISSUE TITLE
Separated settings for each tab and other tab enhancements

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#789]
Current situation, where all tabs uses the same settings for all have a lot of problems.
Here a few examples of problems, caused by "same settings for all" situation:
1. You opened 5 normal mode tabs, and then you opend 6th tab with merge results mode...
...after reopen grabber ALL 6 tabs will be in merge results mode.

2. You opened one of these 6 tabs and go to page 2 of search results...
...after reopen grabber ALL 6 tabs will be opened at their page 2.

3. Your 1st tab have search only on gelbooru, 2nd tab only on sankaku and konachan, 3rd tab on all sources and you then you open 4th tab with only zerochan search...
...after reopen grabber All 4 tabs will be only zerochan search.

4. When you close grabber, you had focus on 4 tab of 6, when you reopened it focus changes to 1st tab.

5. After reopening grabber tabs, no matter how they was sorted, changes to default tab order, so the meaning of ability to change tab order is lost.

**Comment by MasterPetrik** [comment]
So I suggest:
1. Separate settings(current page, sources, etc) for every tab.
2. Remember, what tab is focused, and focus on it after open grabber again.
3. Remember tab order and sort tabs according to it after open grabber again.

**Comment by Bionus** [comment]
Here it is, 5.2.0 will serialize the "tabs.txt" information in JSON (instead of plain text format), and will do the 5 points you mentioned. :smile:

**Comment by MasterPetrik** [comment]
Excellent!
