### ISSUE TITLE
Auto updater maintains new version text after update is complete

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#792]
### What steps will reproduce the problem?

Updated the program with the built-in updater.

### What is the expected behavior? What do you get instead?

This is in About Grabber.
![screen shot 2017-02-18 at 8 59 55 am](https://cloud.githubusercontent.com/assets/5648875/23094137/d276e3fa-f5b8-11e6-9a8d-5386699a66a9.png)

I used the automatic update feature which appears to work really well (although the progress bar was a little jumpy). **Grabber still alerts that there is a new version, even though 5.1.1 has been installed.** I don't mean the popup on start, I mean the text in About Grabber as pictured above. I assume this is a completed feature and if so that's great for updating.

### What version of the program are you using? On what operating system?

Assuming the update worked, it says 5.1.1.

**Comment by MasterPetrik** [comment]
I Can't reproduce this. Grabber 5.1.1 Win7x64 My about window looks normal. Maybe it appeas not for all?
![2017-02-18_180624 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23094175/1c46bcde-f605-11e6-9a37-cd6ce3add967.png)

**Comment by Bionus** [comment]
Same here, maybe it's Mac specific?
I'll pop my VM later to check on the macOS version.

**Comment by barryanders** [comment]
I ran the updater with the 5.2.1 release and here's what I got after reopening it. I have no idea if it actually updated and the version is wrong, or if it did nothing.

![screen shot 2017-02-25 at 10 00 23 am](https://cloud.githubusercontent.com/assets/5648875/23332565/5d0019e6-fb41-11e6-9349-b34a6e98f1a7.png)

**Comment by Bionus** [comment]
Thinking about it, doesn't the updater download the Windows installer then run it?
And in that case it wouldn't update anything, which would explain this issue.

You can check if you're in 5.2.1 by going to the settings and see if the "Interface > Image window" part looks like this (but I doubt it):
![](https://cloud.githubusercontent.com/assets/882719/23331896/40b71b8a-fb6f-11e6-9a66-16ec028cb768.png)

**Comment by barryanders** [comment]
Ah, ok, it's not updating. That's good to know! I suppose this can be closed then since there's an answer. It's just simply not implemented for Mac.
