### ISSUE TITLE
Freeze when restoring tabs with system-wide proxy enabled

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#793]
> While I made a lot of tests before the release, if something do not get restored properly, please open an issue (enclosing the backup of these two files), and I'll make investigate and push a ASAP.

not sure that will be reproduceable, but when I try to restore these tabs, favorites tab shows at first
![image](https://cloud.githubusercontent.com/assets/22294259/23106501/68904344-f6ff-11e6-80b0-b8e82311ecd0.png)
then grabber freezes. 
Of course when restart if I try to restore these tabs again, all the same. Freeze.
![image](https://cloud.githubusercontent.com/assets/22294259/23106504/73c578b0-f6ff-11e6-8ada-f96e3f8ef1f9.png)

here is my tabs.txt file:
https://drive.google.com/open?id=0B3SK4Pf9wsnmYWxyNEJsOW5Hb00

**Comment by MasterPetrik** [comment]
I used stopwatch and calculated that freeze continues ~3 min after that freeze finishes and grabber finally starts working properly with loaded tabs.

**Comment by MasterPetrik** [comment]
hmm, I guess I figured out where was the problem, it was caused by using system proxy settings, but freeze even then is not a very good excuse.  
![image](https://cloud.githubusercontent.com/assets/22294259/23106772/89665b22-f703-11e6-8c64-308d86b3f4d5.png)

**Comment by Bionus** [comment]
Is it still slow after start with the system-wide proxy settings enabled? Or only during start?

**Comment by MasterPetrik** [comment]
with the system-wide proxy settings enabled only images loads a bit slowly but no more freezes anymore. But when restoring tabs with the system-wide proxy settings enabled there are alvays ~3m freeze

**Comment by MasterPetrik** [comment]
You can try it by yourself. here is my auto configurated proxy - http://antizapret.prostovpn.org/proxy.pac
Just try it on your windows proxy settings, I guess result will be the same
![image](https://cloud.githubusercontent.com/assets/22294259/23106871/1426ce94-f705-11e6-9cac-d0df6d544603.png)

**Comment by Bionus** [comment]
It seems to be caused by the Windows API which is actually **very** slow (as you can see) when getting the proxy information the first time for each URL (https://bugreports.qt.io/browse/QTBUG-10106, https://bugreports.qt.io/browse/QTBUG-27136).

I'll see what I can do but if the problem lies with Windows, I'm not sure there's anything I can actually do except for something like not opening the window at all, waiting for the proxy settings to be loaded then finally start Grabber.

**Comment by MasterPetrik** [comment]
Understood. Well, anyway the problem is not a big waiting time, but FREEZE in all that time. I guess freeze  is unnormal in any case, But I will understand you if you will not fuck up with all that mess. 
P.S.
Maybe you will share your proxy srver settings to me? Would be great)

**Comment by Bionus** [comment]
> Understood. Well, anyway the problem is not a big waiting time, but FREEZE in all that time. I guess freeze is unnormal in any case, But I will understand you if you will not fuck up with all that mess.

Yes, freezes are not normal. It's caused by the Windows API. There's a way to not have it freeze, but then what should the program do in the meantime? It can't use any network, that's why I suggested just showing some useless waiting window before showing the main window.

> Maybe you will share your proxy srver settings to me? Would be great)

I don't use proxies. I only have an alternative DNS because all censorship in France is DNS-based.

**Comment by MasterPetrik** [comment]
well, if nothing to do with it, I guess you can close the issue then, 
All I can suggest is to add some info, that we figured out in this topic to proxy settings page(there are bunch of blank space anyway)
I guess that's all what we can do.
![2017-02-20_002838 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23107269/e72d17ee-f70a-11e6-84c1-2fd6489f24f0.png)
P.C.

> I don't use proxies. I only have an alternative DNS because all censorship in France is DNS-based.
So soft... In Russia they uses almost all types of block in one time: IP block,  DPI, DNS, even blocks entire https sites only for one page.
Only proxy, TOR, SSH and VPN works... for now.
