### ISSUE TITLE
"Ignored" system issues

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#794]
![image](https://cloud.githubusercontent.com/assets/22294259/23120897/45661478-f76f-11e6-914b-875f68ac821c.png)
I guess that "ignoring" system isn't works properly, but I don't know how exactly it should work. So I don't know, is this a bug or feature. I didn't find this info in Grabber wiki.
Can you please explain me how this system work? why images becames ignored? What's wrong with image, that tagged "ignored"?

**Comment by Bionus** [comment]
It's what happens when you set the MD5-based duplicate behavior to "don't save" / ignore.

**Comment by MasterPetrik** [comment]
Then please tell me about MD5 list structure. Is there only MD5 stored or MD5+filepath or what?

**Comment by MasterPetrik** [comment]
How often md5s updates? Does it somehow check his relevance?

**Comment by Bionus** [comment]
A new line is appended to the list when a new file is saved. When the same MD5 is found later, if the first file has been moved or removed, the line is removed.

This way, it's guaranteed that it only says "Ignored" when another file with the same MD5 actually exists at the time of the download.

You can force a full MD5 refresh using the "MD5 list fixer" in the tools menu.

**Comment by MasterPetrik** [comment]
![2017-02-20_131917 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23139744/0114efe2-f7bf-11e6-8f9f-3795898be1ac.png)

Then I could report about very strange behavior of md5s list. Somehow "ignoring" system send me false alarms, and I can't save sertain fresh images from booru, that I 100% not downloaded. Searching in download folder by its md5(downloaded names = md5) failed.

**Comment by Bionus** [comment]
But is this image's MD5 in your `md5s.txt` file?
If it is, there should be a filename beside it, does this file actually exist?

If it's not there, could you send me your `md5s.txt` file + which file are you trying to download? (better send it by mail) I'll investigate on my end in the meantime.

**Comment by MasterPetrik** [comment]
here the example:
1. I use MD5 fixer(force calculation) and completely refresh MD5 list
2. I open list file, look inside, all lines sorted by folders, and all lines looks normal, good.
_This list I uploaded in "md5s after closing grabber.txt" - (I just switched code to unicode)_
3. Then I try to save from preview some image. It "ignored". Ok, I get md5 from image details, open md5s.txt again and search in it... nothing. But grabber still tells me "ignored".
4. Then I close Grabber and look in md5s.txt... 
Ho-ho! What we got here! All lines now sorted by MD5, some strange lines appeared in the list, and now I can find "ignored" md5 sum in it. I just show you this line:

> 2265d6c0f7c63eb0053ef5f4c302156fC:\Users\MasterPetrik\AppData\Local\Temp\webm rating_safe\2265d6c0f7c63eb0053ef5f4c302156f.webm

It's very strange because default downloads folder is "C:/Users/MasterPetrik/наГРАБленное/", so normal lines look like this:

> 024eaa0b92fb67df6a5384a465fba816C:/Users/MasterPetrik/наГРАБленное/rating_safe/024eaa0b92fb67df6a5384a465fba816.jpg

And it's a big question why images saved not in default downloads folder appears in the list if after refresh there are has been nothing unusual like this, So how you can explain this addition?
see more in (md5s after closing grabber.txt)
that's not all yet! Some lines have strange in  "/" and "\" usage:
![2017-02-20_231933 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23140583/81c64f74-f7c3-11e6-80ca-17c9698ae64f.png)
And all these strange things appears in md5s.txt file after closing grabber.

I tested this many times and always get a constant result.

You can look at full  original files below:
1. md5s after refresh.txt
2. md5s after closing grabber.txt
https://drive.google.com/open?id=0B3SK4Pf9wsnmYWxyNEJsOW5Hb00

**Comment by Bionus** [comment]
Ah, that's because when you double click an image that wasn't saved yet, it will make a temporary copy in your temporary folder. Seems like it's also writing to the MD5 file, even though it shouldn't. I'll fix this in next update.

**Comment by MasterPetrik** [comment]
And how you explain that some  lines have strange in " / " and " \ " usage?

Btw there are another bug with "ignored" images:
![2017-02-20_131917 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23142019/d27e0612-f7ca-11e6-8d2f-889d1d4a19e8.png)
When you press "destination folder" button when image is ignored instead of opening folder with this image(from md5s list path obviously) opens windows profile folder.

**Comment by Bionus** [comment]
> And how you explain that some lines have strange in " / " and " \ " usage?

`\` and `/` are the same in Windows.

**Comment by MasterPetrik** [comment]
> \ and / are the same in Windows.

I know, but WHY this happening?
