### ISSUE TITLE
Search crash

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#795]
### What steps will reproduce the problem?
Search Castlevania on a nonmerged search with Images per page at 20, using Scroll area for results

### What is the expected behavior? What do you get instead?
Freeze,  then Crash on search

### What version of the program are you using? On what operating system?
5.1.1 win7

**Comment by Bionus** [comment]
How many sources did you use?
What's the last few lines of your log files? (maybe something interesting's there)
How long did it freeze before crashing?
If you don't click anything (to not trigger the Windows white overlay for unresponsive programs) and just leave Grabber alone, does it loads with success? (albeit with a long waiting time)
