### ISSUE TITLE
Bug with already existed images preview

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#796]
If you try to open already downloaded image in preview, only thumbnail appears, original image isn't loaded, if you switch to next\previous image and then go back then original image will be loaded properly. So this bug appears only when you opening preview window for already existed images.
100% repeatable.

win 7 64, 5.2.0

![2017-02-21_003925 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23142880/45ce2e68-f7cf-11e6-9783-263cfb91bbfa.png)

P.S.
heh, I'm feeling like I am professional software tester, so many bugreports)

**Comment by Bionus** [comment]
> heh, I'm feeling like I am professional software tester, so many bugreports)

Indeed, thanks! It's a great help to improve the program's quality :smile:

**Comment by MasterPetrik** [comment]
And something else.
hmm... I don't want to create a separate issue for so tiny problem, but I guess that mouse wheel scrolling is working... upside down.

**Comment by MasterPetrik** [comment]
And something else.
hmm... I don't want to create a separate issue for so tiny suggestion, but I guess it will be good Idea to start search via pressing enter key. Because in current grabber you only can do it with mouse.
![image](https://cloud.githubusercontent.com/assets/22294259/23330644/043916fa-fb64-11e6-9794-72b28c3c31c6.png)

**Comment by Bionus** [comment]
You can already start the search by pressing enter from the search field though.

**Comment by MasterPetrik** [comment]
Oh, I see. I was confused with 1 seconds dealay between pressing the button and getting results.  Newermind then.

**Comment by MasterPetrik** [comment]
And something else.
hmm... I don't want to create a separate issue. Very needed function, especially for bugreports is ability to copy image md5 sum from details window. In current version when you need file md5, you should rewrite it manually or copy file name from temp folder. Both ways are terrible.

**Comment by Bionus** [comment]
> hmm... I don't want to create a separate issue

Even if it's only a one line issue, or only even a title, it's more convenient to have a separate issue. It's better for tracking, or people to follow them. And this way I can close one without closing the other (let's say I fix the original issue here but not your last suggestion, I can't close this issue since it contains both).

> Very needed function, especially for bugreports is ability to copy image md5 sum from details window. In current version when you need file md5, you should rewrite it manually or copy file name from temp folder. Both ways are terrible.

Indeed, I'll make all those fields selectable by mouse in 5.2.1. :+1:

**Comment by MasterPetrik** [comment]
Thanks.
I have a question about Github. Can I theoretically open my issues, closed by you? 
P.S.
Looks like I posted  all bugs and suggestions that I had, except two related with merge results and image position displaying. So you almost can relax)

**Comment by Bionus** [comment]
> I have a question about Github. Can I theoretically open my issues, closed by you?

No you can't. But you can either create a new issue and reference the old one using #ISSUE_ID, or simply comment on the closed issue and I'll re-open it if necessary.

> Looks like I posted all bugs and suggestions that I had, except two related with merge results and image position displaying. So you almost can relax)

🎉

**Comment by Bionus** [comment]
BTW I hope you don't take wrongly when sometimes I don't comment on your issues and directly fix them, it just means it's already clear and no questions are needed, and all I could say would be "Indeed, will be fixed in next release" or something. :smile:

**Comment by MasterPetrik** [comment]
Yes, I understand that, I just look, marked my issue or not and everything becomes clear)
