### ISSUE TITLE
Reuse image preview window

### ISSUE THREAD

**Issue by Keith94** [Bionus/imgbrd-grabber#798]
Hi!
I'm new to this program, really impressed so far.

I'm looking for a way to always "replace" the current instance of the image preview, rather than opening a new window each time.

### What steps will reproduce the problem?
1. Search something in the main window
2. Click various image results

### What is the expected behavior? What do you get instead?
Expected: Clicking an image opens in the existing window, replacing previous image. Or maybe it gets added as an additional "tab" in the preview window

Actual: New window is opened for each image, results in having to close too many windows

**Comment by MasterPetrik** [comment]
well, it's a very good idea to add that option to grabber, I myself think about it too, looks like it is very important for some users.
