### ISSUE TITLE
Destination folder button in preview window doesn't work properly in some cases

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#801]
5.2.0 for saving filenaming I use "%search%\%md5%.%ext%" 

![image](https://cloud.githubusercontent.com/assets/22294259/23213187/058b9c76-f91b-11e6-90db-1e7c523b8b70.png)
There are many situations, when Destination folder button in preview window doesn't work at all. In most of all grabber just opens your windows profile folder instead of normal right folder.
Here is a couple examples:

## Not work with empty search request
![2017-02-22_163306 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23213969/21d6a1f2-f91e-11e6-9709-4fb78e4581d8.png)

With empty search request after saving image via preview window, it saves well in right folder, but when you press "destination folder" button in preview window, instead of folder with focused saved image in it, grabber just opens your windows profile folder

## Not work with ignored images
![2017-02-20_131917 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23142019/d27e0612-f7ca-11e6-8d2f-889d1d4a19e8.png)

When you press "destination folder" button when image is ignored instead of opening folder with this image(from md5s list path obviously) opens windows profile folder.

**Comment by MasterPetrik** [comment]
> Not work with empty search request
Still not work, reopen please.

**Comment by Bionus** [comment]
I can't reproduce though, using the filename format you gave. I load the results without putting any tag, open some image, save it then click "destination folder" and it opens correctly. Even if I don't save the image it still opens the right folder.

**Comment by MasterPetrik** [comment]
I figured out where was the problem.
with filename mask "%search%\%md5%.%ext%" and empty one of tokens, for example with no search request it becames "\%md5%.%ext%" so the filepath for downloaded files will contain "//" and thats why destination folder doesn't work.
![2017-02-27_021039 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23344983/565f24a4-fc97-11e6-9c18-4da1e09576d4.png)

So i can suggest a solution not only for empty search request, but for every empty tokens in any part of filename:
Check the and remove excess "/" in filenames before writing in md5s list.

**Comment by Bionus** [comment]
So you mean your filename was actually `%search%/%md5%.%ext%` then? So with a search, it would become `C:/mydir/my_search/md5.jpg`, and without `C:/mydir//md5.jpg`? In that case, I can indeed reproduce the issue you describe.

**Comment by MasterPetrik** [comment]
> So you mean your filename was actually %search%/%md5%.%ext% then?
Yes, you get it right. l dont know why github hide "/" in text, maybe that is the cause of your confusion. Sorry. In my last message I wrote a text, then made a screenshot and post screenshot instead of text only because of it. -____-
