### ISSUE TITLE
derpibooru.org - many images missing from download

### ISSUE THREAD

**Issue by xiveslestian** [Bionus/imgbrd-grabber#802]
When adding downloads, I will get about half of what I see when I use the website
for examle i use "score.gte:500" as a search term - on the website i get 16515 images, on the grabber - about 4000. also sometimes i can't see the number of pages in the results

I put the API Key in the credentials and can see explicit stuff in grabber, but many files are missing from download.

**Comment by Bionus** [comment]
Indeed, it gives 3837 images instead of much more.
However, by calling the API manually at https://derpibooru.org/search.json?key=API_KEY&page=1&q=score.gte%3A500&nocomments=1&nofav=1, it says the total number of images is 15632, not 16515?
