### ISSUE TITLE
Suggestion: displaying image position in search results in preview window

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#803]
Important: This siggestion is about image position in non merged results mode!
## Current state
Not a single clue, which image is displayed right now, but instead of it useless "grabber" text.
![2017-02-25_151845 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23331614/a760f986-fb7a-11e6-8678-d9a33c95e7b6.png)

## How it could look
will be a good idea to display image position and site, where it is found.
![2017-02-25_163349 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23331617/ab3313dc-fb7a-11e6-8229-e37c31a46809.png)

It also will help to investigate https://github.com/Bionus/imgbrd-grabber/issues/698 issue.

**Comment by Bionus** [comment]
Indeed, the source and position could be useful, both in merged and non-merged.
As for the "Grabber" thing, it's added automatically for some reason, but I'm not sure there's much gain to remove it.

**Comment by MasterPetrik** [comment]
> Indeed, the source and position could be useful, both in merged and non-merged.

well... about merged results... I will post separate issue about it later.

> As for the "Grabber" thing, it's added automatically for some reason, but I'm not sure there's much gain to remove it.

Yes, "Grabber" thing is not a problem now, but if you gonna show there another info, string will be too long, I guess. 
Moreover, programm Name usually stands at the first place, isn't it?

BTW, what purpoise of "Image" part? In current state there are not very true info, because even when displayed video, it still says "Image"...

P.S.
v5.2.1 looks great, thanks!
 https://github.com/Bionus/imgbrd-grabber/issues/718 is still rarely appears.
