### ISSUE TITLE
Auto-update on macOS and Linux

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#804]
Currently, it still downloads the Windows executable and run it (issue #792), which does not make sense.

If there is no easy way to auto-update the program (without an external binary, that is), the auto-update feature should be replaced by a "Do you want to open the downloads page?" popup.

**Comment by Bionus** [comment]
Should [Sparkle](https://sparkle-project.org/) be added? Seems like a lot of work for little gain.

**Comment by barryanders** [comment]
Looks like a cool framework, but yeah, probably not worth it.
