### ISSUE TITLE
PNG and GIF format does´t work :( 

### ISSUE THREAD

**Issue by futahri** [Bionus/imgbrd-grabber#806]
### What steps will reproduce the problem?

while download

### What is the expected behavior? What do you get instead?

http://imgur.com/a/S1tZ7

this happen when i try open a png or gif in any program

### What version of the program are you using? On what operating system?

5.2.1 Windows 7

### Please provide any additional information below

this happen on all sources
jpg, jpeg and webm is ok

**Comment by Bionus** [comment]
Can you upload one of those broken files and share the link?
Is this for batch download or download after clicking an image in the results?

**Comment by futahri** [comment]
http://www.mediafire.com/file/vcq366vt5k6t196/86ace16e106952d360c8785e4892deaa.png

batch download

**Comment by Bionus** [comment]
Ok, thanks a lot, it's pretty critical so I'll push an update this afternoon. :smile:

**Comment by futahri** [comment]
thanks ;)
