### ISSUE TITLE
Batch broken in 5.2.1

### ISSUE THREAD

**Issue by HanabishiRecca** [Bionus/imgbrd-grabber#807]
Batch download just broken in 5.2.1. It always shows 1000 pictures (same as the limit number) and doesn't work properly.
Rolled back to 5.1.1 - all is ok.

**Comment by Bionus** [comment]
Did you try to finish the batch download?
Images are now downloaded by packs of 1000.

**Comment by HanabishiRecca** [comment]
@Bionus, it downloads and replaces already existing images =\

**Comment by Bionus** [comment]
Yes, it download the first pack of 1000, then go on to the next pack. If the images are downloaded what's the problem? If you want to download 2000 images, it will first download the first 1000 then the following 1000.

**Comment by HanabishiRecca** [comment]
@Bionus, i mean 5.1.1 (and earlier) skips existing images. Now 5.2.1 don't.

**Comment by Bionus** [comment]
Does this happen on all sources? I just tried to start a download, stop in the middle, restart then start the same download, and it properly skipped the first (already existing) images:

![image](https://cloud.githubusercontent.com/assets/882719/23341082/917b80ec-fc41-11e6-9e35-909f7e608589.png)

Is your "If a file already exists" setting set to "don't save"?

![image](https://cloud.githubusercontent.com/assets/882719/23341090/af7d7654-fc41-11e6-9813-03890c7677e9.png)

**Comment by HanabishiRecca** [comment]
@Bionus, i tried on gelbooru.
