### ISSUE TITLE
Images are saving on default root folder and Downloads Tab Folder

### ISSUE THREAD

**Issue by jehutyDev** [Bionus/imgbrd-grabber#811]
### What steps will reproduce the problem?
Download several images in a tab and set a different folder from the default

### What is the expected behavior? What do you get instead?
Images should save in Downloads tab folder specified folder column

### What version of the program are you using? On what operating system?
5.2.2 On Linux Mint x64

**Comment by anubis-Dev** [comment]
It seems like it works well when you are just downloading 1 tag

**Comment by Bionus** [comment]
> It seems like it works well when you are just downloading 1 tag

It's strange given the two should be totally unrelated.

So if I understand correctly, you have a global "Folder" setting, add some batch download, then change the folder setting for this particular batch download. However, after starting this download, the images get in the old folder instead of the new one?

Does restarting just before starting the download "fix" the issue?

**Comment by anubis-Dev** [comment]
sorry i haven't determined exactly what happened, but I now noticed a pattern, images are saving in the folder I edited from the batch downloads list but only jpg images and the png images are saving in the global folder.

**Comment by anubis-Dev** [comment]
This image have the .IGL contents with my search:


![igl-file](https://cloud.githubusercontent.com/assets/26052283/23349230/7bf903f2-fc6e-11e6-9b33-68d188480682.png)

**Comment by anubis-Dev** [comment]
Well I now can reproduce exactly what happen, with a .igl container with the search, its in fact saving png files in global folder and jpg files in batchs path.

{
    "batchs": [
        {
            "filename": "%md5%.%ext%",
            "getBlacklisted": false,
            "page": 1,
            "path": "/path/to/grabber-5.2.2/data/galko",
            "perpage": 20,
            "site": "chan.sankakucomplex.com",
            "tags": [
                "galko"
            ],
            "total": 54
        }
    ],
    "uniques": [
    ],
    "version": 3
}


P.S. I have deleted my previous comment it wasn't necessary to post an image.

**Comment by Bionus** [comment]
So from what I understand, with the previous IGL file, you get PNG images saved in your default folder (for example `/path/to/grabber-5.2.2/data`) and the JPG in `/path/to/grabber-5.2.2/data/galko`?

There should be absolutely no relationship between extension and directory. I don't have any unix available, but once I get one I'll take a look as this issue does not seem to happen on Windows.

What does the `main.log` file says? The `settings.ini` file would also help, as maybe some unrelated setting might cause this behavior.

**Comment by anubis-Dev** [comment]
settings.ini

[General]
add=
autocompletion=true
autodownload=false
batch="100,100,100,100,100,100,100,100,100,100"
blacklistedtags=
borders=3
check_for_updates=86400
columns=1
confirm_close=true
crashed=false
downloadblacklist=false
firstload=false
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\0\0\0\0\x1c\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\x37\0\0\a\x7f\0\0\x4\x37\0\0\0\0\x2\0\0\0\a\x80)
getunloadedpages=false
hideblacklisted=true
hidefavorites=20
ignoredtags=
imageCloseMiddleClick=true
imageNavigateScroll=true
imagePositionAnimationH=left
imagePositionAnimationV=center
imagePositionImageH=left
imagePositionImageV=center
imagePositionVideoH=left
imagePositionVideoV=center
language=
last_check_for_updates="@Variant(\0\0\0\x10\0%\x80\xe5\x4q\xd4;\xff)"
limit=20
linksLastDir=/home/anubis/Documents/apps/grabber-5.2.2/IGL
mergeresults=false
preload=0
resizeInsteadOfCropping=true
resultsScrollArea=true
reverse=false
serverBorder=0
serverBorderColor=#000000
showtagwarning=true
showwarnings=true
sites=0000000100000000000
slideshow=0
source_1=xml
source_2=json
source_3=regex
source_4=rss
start=none
state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\0\0\0\0\xee\0\0\x3\xee\xfc\x2\0\0\0\x2\xfc\0\0\0\x13\0\0\x1\xbe\0\0\0q\x1\0\0\x19\xfa\0\0\0\0\x2\0\0\0\x4\xfb\0\0\0\x1a\0\x64\0o\0\x63\0k\0_\0i\0n\0t\0\x65\0r\0n\0\x65\0t\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x13\0\xff\xff\xff\xfb\0\0\0\x12\0\x64\0o\0\x63\0k\0_\0w\0i\0k\0i\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x13\0\xff\xff\xff\xfb\0\0\0\x10\0\x64\0o\0\x63\0k\0_\0k\0\x66\0l\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x13\0\xff\xff\xff\xfb\0\0\0\x1c\0\x64\0o\0\x63\0k\0_\0\x66\0\x61\0v\0o\0r\0i\0t\0\x65\0s\x1\0\0\0\0\xff\xff\xff\xff\0\0\0W\0\xff\xff\xff\xfb\0\0\0\x16\0\x64\0o\0\x63\0k\0O\0p\0t\0i\0o\0n\0s\x1\0\0\x1\xd7\0\0\x2*\0\0\0\x87\0\xff\xff\xff\0\0\x6\x8c\0\0\x3\xee\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
tagsautoadd=10
tagsposition=top
thumbnailUpscale=@Variant(\0\0\0\x87?\x80\0\0)
useregexfortags=true
whitelist_download=never
whitelistedtags=

[Batch]
details=true
end=1
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x3\x65\0\0\x1\x31\0\0\x5X\0\0\x2\xa9\0\0\x3\x65\0\0\x1L\0\0\x5X\0\0\x2\xa9\0\0\0\0\0\0\0\0\a\x80)
remove=false
scrollToDownload=true

[Coloring]
Colors\artists=#aa0000
Colors\blacklisteds=#000000
Colors\characters=#00aa00
Colors\circles=#55bbff
Colors\copyrights=#aa00aa
Colors\favorites=#ffc0cb
Colors\generals=#000000
Colors\ignoreds=#999999
Colors\models=#0000ee
Colors\species=#ee6600
Fonts\artists=",9,-1,5,50,0,0,0,0,0"
Fonts\blacklisteds=",9,-1,5,50,0,0,0,0,0"
Fonts\characters=",9,-1,5,50,0,0,0,0,0"
Fonts\circles=",9,-1,5,50,0,0,0,0,0"
Fonts\copyrights=",9,-1,5,50,0,0,0,0,0"
Fonts\favorites=",9,-1,5,50,0,0,0,0,0"
Fonts\generals=",9,-1,5,50,0,0,0,0,0"
Fonts\ignoreds=",9,-1,5,50,0,0,0,0,0"
Fonts\models=",9,-1,5,50,0,0,0,0,0"
Fonts\species=",9,-1,5,50,0,0,0,0,0"

[Exec]
SQL\after=
SQL\before=
SQL\database=
SQL\driver=
SQL\host=
SQL\image=
SQL\password=
SQL\tag_after=
SQL\tag_before=
SQL\user=
image=
tag_after=
tag_before=

[Log]
show=true

[Margins]
horizontal=6
main=10
vertical=6

[Proxy]
hostName=
port=0
type=http
use=false
useSystem=false

[Save]
artist_empty=anonymous
artist_multiple=replaceAll
artist_multiple_keepN=1
artist_multiple_keepNThenAdd_add=" (+ %count%)"
artist_multiple_keepNThenAdd_keep=1
artist_multiple_limit=1
artist_sep=+
artist_useall=false
artist_value=multiple artists
automaticretries=0
character_empty=unknown
character_multiple=replaceAll
character_multiple_keepN=1
character_multiple_keepNThenAdd_add=" (+ %count%)"
character_multiple_keepNThenAdd_keep=1
character_multiple_limit=1
character_sep=+
character_value=group
copyright_empty=misc
copyright_multiple=replaceAll
copyright_multiple_keepN=1
copyright_multiple_keepNThenAdd_add=" (+ %count%)"
copyright_multiple_keepNThenAdd_keep=1
copyright_multiple_limit=1
copyright_sep=+
copyright_useshorter=true
copyright_value=crossover
downloadoriginals=true
filename=%md5%.%ext%
filename_favorites=
filename_real=%md5%.%ext%
headerDetection=true
keepDate=true
limit=0
md5Duplicates=ignore
noJpeg=true
path=/home/anubis/Documents/apps/grabber-5.2.2/fanarts/data/
path_favorites=
path_real=/home/anubis/Documents/apps/grabber-5.2.2/fanarts/data/
replaceblanks=false
samplefallback=true
separator=" "
simultaneous=1
species_empty=unknown
species_multiple=keepAll
species_multiple_keepN=1
species_multiple_keepNThenAdd_add=" (+ %count%)"
species_multiple_keepNThenAdd_keep=1
species_multiple_limit=1
species_sep=+
species_value=multiple

[SaveLog]
activate=false
file=
format=%website% - %md5% - %all%

[Sources]
Letters=3
Types=icon

[Textfile]
activate=false
content=%all%

[Zoom]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\xa7\0\0\0\x9c\0\0\x5\xe5\0\0\x3\xf1\0\0\x1\xa7\0\0\0\xb7\0\0\x5\xe5\0\0\x3\xf1\0\0\0\0\0\0\0\0\a\x80)
plus=false

**Comment by anubis-Dev** [comment]
well, I have not had that problem again, after some time to use grabber but I stop use chan.sankaku maybe that can help?
