### ISSUE TITLE
Suggestion - Flat icon

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#815]
![9jvs0gd](https://cloud.githubusercontent.com/assets/19770864/23381383/3c137706-fd0c-11e6-98eb-c96137e19d24.png)
Replace the little green and red images with flat green ones to make it look better.

![red green](https://cloud.githubusercontent.com/assets/19770864/23381967/7e7fd1dc-fd0e-11e6-80e5-adac7284ea0a.jpg)

**Comment by MasterPetrik** [comment]
![original2 rgb noise_scale level1 x2 000000 rgb noise level3](https://cloud.githubusercontent.com/assets/22294259/23384991/68b17b1c-fd5e-11e6-8b73-b809a63a4272.jpg)

**Comment by brodycas3** [comment]
IDK, it just looks weird. it looks like its trying too hard.

**Comment by brodycas3** [comment]
It's not like you can tell what it is when its so small.

**Comment by MasterPetrik** [comment]
> Replace the little green and red images with flat green ones **to make it look better**.

...just for you on Win 10. For example the same window on my win 7:

![image](https://cloud.githubusercontent.com/assets/22294259/23385174/6121bcee-fd5f-11e6-8880-0ba200a1f9e0.png)

And gradient icons looks fits fine in that GUI.

I just want you to show that your vision is not the only one. Look how the same window displays on different OS, only win 8, 10 uses flat design and even Mac interface uses non fully flat design, and all previous windows and even Mac still uses gradients. 
And why flat icons are better then nonflat? For example I  like current icons, and I guess that flat icons it's not beautiful, it's  just primitive.

# Grabber on Windows 7
![2017-02-28_023745 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23385132/1c8a717a-fd5f-11e6-90b4-ba9b407aad79.png)

# Grabber on Windows 10
![40b71b8a-fb6f-11e6-9a66-16ec028cb768](https://cloud.githubusercontent.com/assets/22294259/23385147/2c097a60-fd5f-11e6-8a52-418359979c7a.png)

# Grabber on Mac
![15de5414-fb42-11e6-99be-1fe2002e20ba](https://cloud.githubusercontent.com/assets/22294259/23385142/25ecc984-fd5f-11e6-981a-15d88ba2ec55.png)

**Comment by MasterPetrik** [comment]
@brodycas3 maybe #817 solution will satisfy you?

**Comment by brodycas3** [comment]
I'll close this since yours is better.
