### ISSUE TITLE
Suggestion - New status icons

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#817]
in #815 issue @brodycas3 told me:

> IDK, it just looks weird. it looks like its trying too hard.
> It's not like you can tell what it is when its so small.

And I look at current icons again. And it really looks weird. 
Unfortunately making icons flat will not solve the problem.

I will try to explain current problems and suggest my solution.
Current status icons problems:
1. it's a circles, just a colored circles. Not very informative form for user, thats why it sometimes looks weird.
2. Coloring. Wrong coloring. Looks very odd because of non standard colors. Moreover all used colors are too dark and depressive.
![green - 7](https://cloud.githubusercontent.com/assets/22294259/23386667/d6e68d84-fd68-11e6-9688-1f2cc36b215a.png)
Green - ok, success. 
Blue - is it really blue color!? what it means? is it good or bad sign? We don't know from icon. 
Red - ok, failure. 
Black - what should that supposed to be? I don't know.
Blue and black colors are not common colors for displaying statuses.
So the coloring + same icons for different states make user confused.
3. Too much blur.

So I suggest three things:
1. Change colors.
2. Make icons brighter and sharper.
3. Make different icons for different status.

## Current look
![6121bcee-fd5f-11e6-8880-0ba200a1f9e0](https://cloud.githubusercontent.com/assets/22294259/23386387/21c1170e-fd67-11e6-8c80-3d6cb0360e2f.png)

I made some research and as result made sample for example to replace old icons with more brighter, sharper and informative icons:

![green -](https://cloud.githubusercontent.com/assets/22294259/23387236/80bfe956-fd6c-11e6-8fd2-3c6261848c2f.png)
![green - 2](https://cloud.githubusercontent.com/assets/22294259/23387243/85948d06-fd6c-11e6-8d3e-7af5ef425cf4.png)

Feel free to use them, here is the completed 16x16 icon png files with alpha channel:
Green
![galka2](https://cloud.githubusercontent.com/assets/22294259/23387460/b5733134-fd6d-11e6-9435-d5b591f25f7e.png)
Blue
![galka3](https://cloud.githubusercontent.com/assets/22294259/23387464/bd367a48-fd6d-11e6-990a-2b86a41b8584.png)
Red
![18808-cross-vector](https://cloud.githubusercontent.com/assets/22294259/23387468/c4f93cc0-fd6d-11e6-90e1-23706bd05442.png)
I don't replaced black icon, because I don't know it's purpose. So please tell me what status indicates blue and black colors in current version and then I will be able to complete icon set. 

## Sample of my variant
![2017-02-28_024036 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23386395/26f308ae-fd67-11e6-94dd-9184218b09ba.png)

**Comment by brodycas3** [comment]
That is very good

**Comment by Bionus** [comment]
> I don't replaced black icon, because I don't know it's purpose. So please tell me what status indicates blue and black colors in current version and then I will be able to complete icon set.

Red = failure
Green = ok
Blue = downloading
Black = waiting / unknown status

**Comment by Bionus** [comment]
BTW, since Grabber is using the [Fugue icon](https://www.iconfinder.com/iconsets/fugue) set for all its icons until now, maybe it'd be a better match to also use them here?

![](https://cdn2.iconfinder.com/data/icons/fugue/icon/tick.png)
![](https://cdn2.iconfinder.com/data/icons/fugue/icon/cross.png)

On a more global point of view, I have to agree that only having round icons is not very clear, and I totally agree with the suggestion to replace them.

> Too much blur.

They're not blurred unless you scale them up though?

**Comment by MasterPetrik** [comment]
> They're not blurred unless you scale them up though?

lets see again: 
![green -](https://cloud.githubusercontent.com/assets/22294259/23387236/80bfe956-fd6c-11e6-8fd2-3c6261848c2f.png)
![green - 2](https://cloud.githubusercontent.com/assets/22294259/23387243/85948d06-fd6c-11e6-8d3e-7af5ef425cf4.png)
even nonscaled icons has a blured edges and texture, This is clearly seen in comparison.

> Black = waiting / unknown status

It's a very bad idea. These statuses are completely different. They need separate ststus icons.


> BTW, since Grabber is using the Fugue icon set for all its icons until now, maybe it'd be a better match to also use them here?

I guess there are exist some difference between icons and status icons. Icons should illustrate some action or menu item, status icons in our case should show status of operation. 
so we don't need blur and shadow in the downloads list, we need big, well seen icons with sharp edges(imho)

![galka2](https://cloud.githubusercontent.com/assets/22294259/23404783/dcf36ac6-fdc7-11e6-8798-a324604671f0.png)
![68747470733a2f2f63646e322e69636f6e66696e6465722e636f6d2f646174612f69636f6e732f66756775652f69636f6e2f7469636b2e706e67](https://cloud.githubusercontent.com/assets/22294259/23404787/e288607c-fdc7-11e6-85fc-a2b572b2347f.png)

![18808-cross-vector](https://cloud.githubusercontent.com/assets/22294259/23404804/fa19fa2a-fdc7-11e6-9384-45681015e6ef.png)
![68747470733a2f2f63646e322e69636f6e66696e6465722e636f6d2f646174612f69636f6e732f66756775652f69636f6e2f63726f73732e706e67](https://cloud.githubusercontent.com/assets/22294259/23404819/0ecc0d28-fdc8-11e6-93d7-d0b2e7647206.png)

even if you remove shadow these icons still will be too small for that.

**Comment by MasterPetrik** [comment]
> Red = failure
> Green = ok
> Blue = downloading, so i'm not sure a tick icon really fits?
> Black = waiting / unknown status

I can suggest new set of icons:
![543 -](https://cloud.githubusercontent.com/assets/22294259/23484787/85df4854-fee9-11e6-8efc-5d5dea718919.png)

Red = failure 
(big bright red cross that every user will notice)
![18808-cross-vector](https://cloud.githubusercontent.com/assets/22294259/23484809/9f920ac0-fee9-11e6-9129-c63ef88218df.png)

Green = ok 
(big bright green sign, that will satisfy any user)
![green](https://cloud.githubusercontent.com/assets/22294259/23484825/aad2f548-fee9-11e6-8e44-41bb364bdd81.png)

Yellow instead of Blue = downloading
(very common form for downloading something. defferent color will help to not confuse user)
![old-go-up56](https://cloud.githubusercontent.com/assets/22294259/23484844/bd12a82a-fee9-11e6-9f73-70b0b7628942.png)

Light-blue = unknown status 
(I like the idea of "?" sign, color or model itself can be changed if you don't like it)
![w512h5121386955379faq4](https://cloud.githubusercontent.com/assets/22294259/23484864/d8e1e764-fee9-11e6-9855-e2dd6fbde8a1.png)

Black = waiting 
(I tried hard to find an image that will illustrate wait condition. This is the best of all variants, that I can imagine -____-)
![sleep160076](https://cloud.githubusercontent.com/assets/22294259/23484887/fd802464-fee9-11e6-96e2-b6da06d9d76d.png)

As for me, I think that "wait" status is very uncertain. instead of single "wait" status will be better for understanding  separate it to some more specific statuses.

**Comment by MasterPetrik** [comment]
## I think it looks very good:

![26f308ae-fd67-11e6-94dd-9184218b09ba](https://cloud.githubusercontent.com/assets/22294259/23485396/4a46d99e-feec-11e6-9b3a-7e1bf85dce41.png)

**Comment by MasterPetrik** [comment]
If you don't like this variant, I can do another one.

**Comment by Gaffnet** [comment]
I like this suggestion.  Using completely different icons to represent status is more comprehensible at a glance.  Additionally, completely different icons for each status is considerably more helpful to any users who have some form of color blindness.  [1 in 12 men and 1 in 200 women in the world](http://www.colourblindawareness.org/colour-blindness/) have a degree of color blindness.

> Black = waiting.  (I tried hard to find an image that will illustrate wait condition. This is the best of all variants, that I can imagine -____-)

Standard icons that have been used to represent waiting status have been an hourglass, stop or wristwatch or clock face.  Ellipses (three periods: ... ) have also been used to represent waiting status.

Or perhaps use some sort of animated "spinner" .gif.  ![small_spinner_50](https://cloud.githubusercontent.com/assets/13587501/23551035/2b3305f4-ffe2-11e6-91a5-0cd96b635ed5.gif)

**Comment by barryanders** [comment]
I definitely like the idea of making the icons representative of what is happening so you don't have to know what each color means. Good contribution. As for the variations above, I think they are similar enough that if it's easier to stick with the same icon set, then it makes sense to me to just do that @Bionus. No reason to switch it out for slightly different versions if you already have an icon set with a similar appearance.

**Comment by MasterPetrik** [comment]
> Standard icons that have been used to represent waiting status have been an hourglass, stop or wristwatch or clock. Ellipses (three periods: ... ) have also been used to represent waiting status.

my opinion here is: "waiting" status is uncertain and must be replaced with some other more specific statuses, for example "do nothing" status and "paused" status.

> Or perhaps use some sort of animated "spinner" .gif? 

this is not "waiting" sign, this is sign of loading or doing something, moreover it is not an icon at all. It is just a cheap replacement of proggress bar.

> As for the variations above, I think they are similar enough that if it's easier to stick with the same icon set, then it makes sense to me to just do that @Bionus. No reason to switch it out for slightly different versions if you already have an icon set with a similar appearance.

Ok, I  get similar images from already used icon set, removed shadows and made it a bit brighter and bigger.

## ok
original Fugue-icon-set icon 16x16
![68747470733a2f2f63646e322e69636f6e66696e6465722e636f6d2f646174612f69636f6e732f66756775652f69636f6e2f7469636b2e706e67](https://cloud.githubusercontent.com/assets/22294259/23566062/58b6eb60-0061-11e7-8666-16d682b0a9fa.png)
reworked Fugue-icon-set icon 16x16
![final green](https://cloud.githubusercontent.com/assets/22294259/23566069/60d7dc50-0061-11e7-93a0-0c6bdf735b3e.png)
old variant:
![green](https://cloud.githubusercontent.com/assets/22294259/23566080/68b4b1d2-0061-11e7-88e3-e302b991e1e0.png)
Well, revorked Fugue icon set icon looks much better now, even better than my first variant.

## Failure
original Fugue-icon-set icon 16x16
![68747470733a2f2f63646e322e69636f6e66696e6465722e636f6d2f646174612f69636f6e732f66756775652f69636f6e2f63726f73732e706e67](https://cloud.githubusercontent.com/assets/22294259/23566191/e9e1001c-0061-11e7-8374-50ed98438083.png)
reworked Fugue-icon-set icon 16x16
![final red](https://cloud.githubusercontent.com/assets/22294259/23566197/f06a8142-0061-11e7-8c23-8e5bd66a2f25.png)
old variant:
![18808-cross-vector](https://cloud.githubusercontent.com/assets/22294259/23566207/f59b9d4a-0061-11e7-9b90-cbbc3a29233e.png)
Well, revorked Fugue icon set icon looks much better now. Compare to my first variant I can't say which of them is better.

## Downloading
old variant:
![old-go-up567](https://cloud.githubusercontent.com/assets/22294259/23568021/d9f718f0-0069-11e7-80ed-6118db510e56.png)
reworked Fugue-icon-set icon 16x16
![1488592176_arrow-24706](https://cloud.githubusercontent.com/assets/22294259/23568110/37e20bc8-006a-11e7-9c6d-45d0a52b2cfc.png)
Well, revorked Fugue icon set icon looks much better now, even better than my first variant.

## Unknown status
old variant:
![w512h5121386955379faq4](https://cloud.githubusercontent.com/assets/22294259/23568432/8201d368-006b-11e7-8575-7ac001c9ea0e.png)
I didn't find suitable icon in Fugue-icon-set, So I made new variant by myself in Photoshop 16x16
![w512h5121386955379faqty6i8](https://cloud.githubusercontent.com/assets/22294259/23569421/375c70fc-0070-11e7-835e-d275395f5576.png)


## Waiting
As for waiting icon, I found the only one icon from Fugue icon set that can particulary illustrate it:
![1488586320_ui-progress-bar](https://cloud.githubusercontent.com/assets/22294259/23566398/bed01a88-0062-11e7-8797-09233cd51154.png)
looks like paused download, i guess that may work... maybe

# Old variant
![26f308ae-fd67-11e6-94dd-9184218b09ba](https://cloud.githubusercontent.com/assets/22294259/23569522/bb41b45e-0070-11e7-8814-002c6d5f3d8f.png)

# New variant
![26f308ae-fd67-11e6-94dd-9184218b09ba67](https://cloud.githubusercontent.com/assets/22294259/23569537/c48d3d08-0070-11e7-95e0-1c52d7db7d2b.png)

I used Fugue icon set icons as you told me. 
reworked  Fugue icon set icons:
![final green](https://cloud.githubusercontent.com/assets/22294259/23569617/2c51222e-0071-11e7-89e3-51f8429351e0.png)
![final red](https://cloud.githubusercontent.com/assets/22294259/23569620/30f76a36-0071-11e7-9de5-67a797fab2d8.png)
![final blue](https://cloud.githubusercontent.com/assets/22294259/23569625/35ebe6ca-0071-11e7-8aa8-7940eab351da.png)
My icons:
![question](https://cloud.githubusercontent.com/assets/22294259/23569655/66fc1ba4-0071-11e7-9085-024ac518b778.png)
I guess this will satisfy you?

**Comment by brodycas3** [comment]
WoW, Good work.

**Comment by Bionus** [comment]
Indeed, these are great!

But actually, that "unknown" icon is also used for the "pending" icons (just added downloads that are not yet started for example), so I'm not sure a question mark really fits this message.

You suggested ![](https://cloud.githubusercontent.com/assets/22294259/23484887/fd802464-fee9-11e6-96e2-b6da06d9d76d.png) for "pending" status before, so maybe that can fit. I gotta admit that it's quite hard to represent this state.

**Comment by MasterPetrik** [comment]
> But actually, that "unknown" icon is also used for the "pending" icons (just added downloads that are not yet started for example), so I'm not sure a question mark really fits this message.

Yes, this is a problem. But not an icons problem, it's a wrong - to mark "just added downloads that are not yet started" with same icon for unknown status, becuse this status is quite definite - "nothing happand yet". And it's completely not the same with "unknown" and shouldn't be marked with unknown sign. 
...But you can think about it in future, and now just change icons as is. I guess is not such a big problem after all.

And please, tell your opinion in these issues:
https://github.com/Bionus/imgbrd-grabber/issues/831
https://github.com/Bionus/imgbrd-grabber/issues/837
https://github.com/Bionus/imgbrd-grabber/issues/790

**Comment by barryanders** [comment]
I like the z's for pending :D

**Comment by barryanders** [comment]
Small note: I noticed that the dark mode issue (#813) revealed that the current icons do not have a transparent background.

**Comment by MasterPetrik** [comment]
Indeed. I noticed that too, but I guess it's not a big deal since new suggested icons have alpha channel in it. 
It only remains to add them to the program, heh...
