### ISSUE TITLE
Not Loading All Images for Gelbooru

### ISSUE THREAD

**Issue by bd42589** [Bionus/imgbrd-grabber#818]
When looking up tags in Gelbooru, it sometimes doesn't seem to load all of them. I gets results like "Gelbooru - Page 1 of ? (42 of ?)" than say "Gelbooru -  Page 1 of 10 (42-420)". It seems to only happen with two or more tags, and I don't have any problems accessing Gelbooru through my browser.

**Comment by qazxswedcxzaqws** [comment]
I think the 1 of ? happens when there is only 1 page.

**Comment by bd42589** [comment]
I don't think that's the case, if I put the same tags directly into the site I get several pages.
