### ISSUE TITLE
Suggestion: Subfolder organization menu

### ISSUE THREAD

**Issue by qazxswedcxzaqws** [Bionus/imgbrd-grabber#819]
The addition of an options menu that allows the user to sort downloaded files into new folders automatically. For example it could sort all the files by %rating% into separate folders after downloading:
>downloads/rating_safe/
>downloads/rating_questionable/
>downloads/rating_explicit/

Or you could do more than one sort e.g. "%rating%%ext%" would mean:
>downloads/rating_safe/png/
>downloads/rating_safe/jpg/
>downloads/rating_safe/gif/

This would be a great feature as you have to use advanced software or do this manually at the moment.

**Comment by Bionus** [comment]
You can already do this, just set your filename to `%rating%/%ext%/...`. Each `/` will generate one additional level of sub-folders. And if you want to rename existing files, there's a tool in the "Tools" menu to do so (but it's slow).

**Comment by qazxswedcxzaqws** [comment]
Oh I see, sorry about that. The description in my filename options menu is missing so I have never been able to click the link at the bottom and have just been reading the tokens off the wiki. I think the reason it's bugged for me might be because of a custom windows theme i'm using so I never issued a bug report on it. The question mark button also does nothing for me.

Here is a picture if you are curious:
![image](https://cloud.githubusercontent.com/assets/12595180/23397044/a44a54a4-fde6-11e6-8e18-3609bf58968f.png)
Thanks!
