### ISSUE TITLE
Image ID corrupted when restoring a download session after a crash.

### ISSUE THREAD

**Issue by Gaffnet** [Bionus/imgbrd-grabber#823]
### What steps will reproduce the problem?

Grabber generates a blank or random single character as the image ID instead of the proper numerical image ID when restoring a previous download session after a crash.

Using the restored download queue with the corrupted image IDs will cause a crash.

![grabber_random_image_id](https://cloud.githubusercontent.com/assets/13587501/23463223/c59ca832-fe5e-11e6-9cc9-c8a82ddba6da.png)

### What version of the program are you using? On what operating system?

Grabber v5.2.2
Windows 10 Pro

**Comment by Bionus** [comment]
Let's move to #824 as it's the same issue.
