### ISSUE TITLE
Source Question

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#825]
I've seen on my Linux machine when I built it, it had more sources like 4chan. How come they don't get added when I update?

![image](https://cloud.githubusercontent.com/assets/19770864/23483363/9a974538-fea0-11e6-857c-059d43b2cd26.png)

**Comment by Bionus** [comment]
Because it doesn't work so I don't include it in the releases. :smile:

**Comment by brodycas3** [comment]
I downloaded it from the release section though

**Comment by Bionus** [comment]
Because the Linux packaging isn't as advanced as the Windows one, and also includes unnecessary stuff for now. It gets everything in the `release/` folder, while the Windows setup is limited to some files.

**Comment by brodycas3** [comment]
ok
