### ISSUE TITLE
Some questions about GUI translation

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#827]
1. what does this string means?
![image](https://cloud.githubusercontent.com/assets/22294259/23487526/ba9a6750-fef7-11e6-8cd6-79966169ae7e.png)

2. what is "pools"? and "pool tabs"?

3. "Species" tag type. What does it mean?

4. rating conditions(safe/explict/ero) doesn't translated
![2017-03-02_033942 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23487890/2e666c7c-fefa-11e6-83e9-2f973f400be8.png)

**Comment by Bionus** [comment]
> 1. what does this string means?
> ![image](https://cloud.githubusercontent.com/assets/22294259/23487526/ba9a6750-fef7-11e6-8cd6-79966169ae7e.png)

You can ignore it, it shouldn't be here. It's the translation of the percentage on some progress bar I guess. `%p` will get replaced by the percentage value, and `%` is the percent value. It's what decides that there's a "25%" displayed near progress bars.

See [QProgressBar::format](https://doc.qt.io/qt-5/qprogressbar.html#format-prop) for more info.

> 2. what is "pools"? and "pool tabs"?

To browse pools on various imageboards. Pools are kind of galleries.
https://danbooru.donmai.us/pools

> 3. "Species" tag type. What does it mean?

That's for species/races of characters, usually for furry imageboards. I don't know if any other board than e621 use it at the moment.

> 4. rating conditions(safe/explict/ero) doesn't translated

I'll add this option in the next push then. :smile:

**Comment by MasterPetrik** [comment]
Thanks. Now all clear. I updated Russian translation to last version.

> rating conditions(safe/explict/ero) doesn't translated
> I'll add this option in the next push then. :smile:

I guess you can close the issue after you doing that.

**Comment by MasterPetrik** [comment]
actions in rightclick menu in detauls window are not tranlated
![image](https://cloud.githubusercontent.com/assets/22294259/23583883/cd31d97c-0161-11e7-8562-a0d6653a2313.png)
