### ISSUE TITLE
Problem with eye 

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#831]
I tried to add some tag to blacklist and then I saw this... 
![2017-03-04_031834 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23573801/ce1d7bda-0089-11e7-8ad9-a766fe1531ff.png)
WTF IS THIS!? a nut?  an apple seed?  a smooth stone? I don't know until...
...until i saw that:
![2017-03-04_031827 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23573804/d16bfe1a-0089-11e7-91d2-7759b8557d63.png)
Oh! An eye! it was a closed eye! But how I should get it if I not seen an opened eye before?

I mean that this closed eye icon is a very stupid and not clear thing.

I went to check Fugue Icons set.  And you know what?

I found a much better icons for that case there:
![1488609167_eye--minus](https://cloud.githubusercontent.com/assets/22294259/23574015/6937a798-008b-11e7-8d06-485a6c6720a8.png)
![1488609171_eye--plus](https://cloud.githubusercontent.com/assets/22294259/23574017/6c0cf4dc-008b-11e7-94a2-e6788284439b.png)

so I suggest you to replace it.

P.S.
in that case what "ignore" means? is it means adding to blacklist? If no, then I suggest you to add an function to adding tag in Blacklist in this menu.

**Comment by brodycas3** [comment]
LOL WTF IS THAT!!!!

**Comment by Bionus** [comment]
>  WTF IS THIS!? a nut? an apple seed? a smooth stone? I don't know until...

It's not obvious indeed.

>  in that case what "ignore" means? is it means adding to blacklist?

Ignoring tags mean that they won't appear in the filename. If your image has two tags, "tagA" and "tagB", if you add "tagA" to your ignore list and save your file with the `%all%.%ext%` filename, the result will be something like `tagB.jpg`.

> I found a much better icons for that case there:
> ![1488609167_eye--minus](https://cloud.githubusercontent.com/assets/22294259/23574015/6937a798-008b-11e7-8d06-485a6c6720a8.png)
> ![1488609171_eye--plus](https://cloud.githubusercontent.com/assets/22294259/23574017/6c0cf4dc-008b-11e7-94a2-e6788284439b.png)

While I agree that the closed eye is not obvious at all, this would look like adding the tag to some kind of "watch list", which is not exactly the feature here. I admit I didn't check icon sets for a while, so I wonder if there's anything around that would be clear at first sight.

**Comment by MasterPetrik** [comment]
> this would look like adding the tag to some kind of "watch list"

no, it wouldn't, because this icon is kind of standard icon for show\hide something. Moreover if user doesn't know about any watchlist in programm, he definitely won't think about it. So this is OK.

> Ignoring tags mean that they won't appear in the filename. If your image has two tags, "tagA" and "tagB", if you add "tagA" to your ignore list and save your file with the %all%.%ext% filename, the result will be something like tagB.jpg.

it is not obvious that these tags are ignored ONLY in filename, in most cases if you see "ignore" you  expect COMPLETE ignore, - in search results in first place, of course. So you tell me that Grabber have TWO different ignore-like options - ignoring and blacklisting.
Is it so nesessery to have two similar-look functions? 
Does someone use only ignoring function?

**Comment by MasterPetrik** [comment]
>  I suggest you to add an function to adding tag in Blacklist in this menu

I bet that blacklisting function is much more popular then current ignoring function. So it is very strange that we have quick ignoring function here and don't have quick blacklisting function here. 

You know, there are much more users, which are not uses tags in filenaming, so quick ignoring function will only confuse them, because they could сonfuse ignoring with blacklisting(as I did).  

**So better will be to show  quick ignoring function in this menu ONLY if user have tags-includeing filenaming. Because for all others it will be useless anyway. To prevent misunderstanding. And of course add an function to adding tag in Blacklist in this menu.**

**Comment by barryanders** [comment]
LOL! That closed eye icon is funny. Some eye lashes would help people understand it better.
