### ISSUE TITLE
Any kind of batch download causes a crash.

### ISSUE THREAD

**Issue by Nogooduser** [Bionus/imgbrd-grabber#832]
### What steps will reproduce the problem?

All I've done is get a few of images (less than 100 in most cases) and then press "download" and the entire program crashes instantly. "Download selected" does the same. Even if I do it with a single image, if I use the batch download function it will crash.

### What is the expected behavior? What do you get instead?

No crashes. Instead the program immediately shuts itself down as soon as I press "download".

### What version of the program are you using? On what operating system?

v5.2.2
Win 7 64-bit

### Please provide any additional information below

This only started happening after the most recent update. I thought maybe it was Microsoft Visual C++ that was the problem (I recently had some issues with it) so I did a re-install of that but nothing changed. I tried uninstalling and re-installing grabber but the problem persists. Running as administrator changes nothing as well.

Downloading images individually works fine. I have no clue what to do at this point so I'm reaching out to you in hopes of finding some answers.

**Comment by Bionus** [comment]
Can you share your `main.log` file right after such crash?
Do you sue a source in particular, or does this happen on every source?

**Comment by Nogooduser** [comment]
Tried a few other sources (I was mainly using gelbooru before) and the exact same thing happened.

I apologize for asking what might be a really dumb question but where is the main.log file? I couldn't find it in either the program folder or in my appdata folder.

**Comment by Bionus** [comment]
It's in `C:\Users\USERNAME\AppData\Local\Bionus\Grabber`.
Make sure to send the one after a crash, since it's emptied every time you start the program. :smile:
I'll investigate and see what problem there could be. Do you have any special settings/filename, or are you using the defaults?

**Comment by Nogooduser** [comment]
Right, I'm dumb and was only looking under roaming.
Here's the file: https://www.dropbox.com/s/oz479z4edbkm797/main.log?dl=0
It was taken right after a crash.

As far as I know I haven't made any special changes.

**Comment by Nogooduser** [comment]
Would just like to report that, with the most recent update, batch downloads are once again working as intended. Not sure if you ever found the underlying cause but either way happy to see it's all up and running now!

**Comment by Bionus** [comment]
> Edit: It seems I was too hasty. Tag downloads work fine, but selecting images and downloading them still crashes the entire program. Ah well.

So only single image downloads (at the bottom of the "Downloads" tab cause a crash?
In that case it looks like issue #850 might be describing the same problem.

I'll work on it for the next update, sorry about that. I didn't pay much attention to single image downloads in the last one.

**Comment by Nogooduser** [comment]
Yep, exactly as you said. I haven't tested it as extensively as the other user did but the gist of the problem is that downloads from the bottom tab crash the program. For me 90% of the time it just shuts itself down and nothing ends up popping up, sometimes I get a windows crash report but either way it crashes. This goes for every source as well. Hope it can be fixed.
