### ISSUE TITLE
Preview window background changing

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#837]
Current Preview window background is not optimal.
I don't know why you prefer (240,240,240) grey color, but for example search results list uses classic white (255,255,255) color, but preview window still uses grey... And considering that very big amount of images has white backgroung, they looks a bit worse now then they may be on the white background.
## A simple example:
![2017-03-09_063036 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23734758/4a64d3bc-0492-11e7-8f11-19ac58dde9c7.png)
![2017-03-09_063036 win7 77mastercore](https://cloud.githubusercontent.com/assets/22294259/23734762/4fa1ed10-0492-11e7-903c-5164b882488f.png)
There is a bit but important differense between these backgrounds. You cant see the edges on white background. I bet that users would prefer white bg because of it.

## Current color:
![2017-03-09_061043 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23734635/6261806a-0491-11e7-8981-114a38ca514b.png)

## More suitable background:
![2017-03-09_061043 win7 ma7stercore](https://cloud.githubusercontent.com/assets/22294259/23734652/818b566e-0491-11e7-8426-cee83b32d269.png)

## Maybe someone prefers another colors...
![2017-03-09_061043 w77in7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23734660/9a13bf8c-0491-11e7-9de0-73f75d964b90.png)

So I suggest to make an option to change Preview window background color in options.
...or at least make it white.

**Comment by Bionus** [comment]
I don't "prefer" light grey, that's just the default background color. And the problem with setting it white by default is that themes won't work anymore (ex: #432).

I guess an option to change it could be added in the settings though, but wouldn't that duplicate issue #813 in some way?

**Comment by MasterPetrik** [comment]
> I don't "prefer" light grey, that's just the default background color. And the problem with setting it white by default is that themes won't work anymore (ex: #432).
> 
> I guess an option to change it could be added in the settings though, but wouldn't that duplicate issue #813 in some way?

Both #432 and #813 are centered in changing all GUI colors, so, they talks about THEMES or skins, or darkmode, anyway they talks about changing all colors.

My suggestion is only about images background in preview window, even not in all window, but at least in image-area. And not becuase of I prefer another colors or somethimg, but because of almost 50% of all images have white bg, and better is not to see edges as I shown in top of this topic. Many other image viewers have an option to set background color for images(FastStone Viewer for example), without any other color customisation, because in this case It is  really important.
