### ISSUE TITLE
Constantly Crashing When Downloading

### ISSUE THREAD

**Issue by Akibaku** [Bionus/imgbrd-grabber#840]
### What steps will reproduce the problem?
Downloading batches. Also sometimes "download selected"

### What is the expected behavior? What do you get instead?
Downloading instead of crashing

### What version of the program are you using? On what operating system?
5.2.2, Windows 10

**Comment by Bionus** [comment]
A few question to better identify the problem:
1. Could you send me the IGL file of what you tried to download? (you can click the save button in the downloads tab to generate one)
2. Does this happen on every source, 100% of the time?
3. Does it crash directly or after a few images?
4. Does the "downloading pages" step complete?
Thanks! :smile: (and sorry about the crashes)

**Comment by selftitledgames** [comment]
Actually I think I figured it out. It looks like the program does not like external HDs, using my internal works fine. Thanks!

**Comment by Bionus** [comment]
Well, it should not have been a problem in the first place.
You mean you installed the program on an external hard drive, or were you trying to save downloaded files there?

**Comment by selftitledgames** [comment]
I installed the program on the internal and was trying to save the files on the external.

**Comment by Akibaku** [comment]
Nope, still having the problem when everything is still on the same drive. It doesn't happen every time, but there also doesn't seem to be any pattern necessarily. It crashes after downloading some of the files. And I'd like to send the IGL but it's not supported here, where can I do that?

**Comment by Bionus** [comment]
You can zip it or change the extension to "txt" or something else github accepts, I'll change it back after I get it. Since it seems random, can you also send me your `settings.ini` file? You can find it in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`.
