### ISSUE TITLE
Blacklist Formatting & Wiki-Page Add-In

### ISSUE THREAD

**Issue by FluffyBirdz** [Bionus/imgbrd-grabber#842]
I looked through the wiki, and couldn't find a page or section that had anything to do with the blacklist formatting.
Is it possible to block an image if it has two specific tags instead of blocking both?
For Example: Blocking Images tagged "rating:explicit female" instead of blocking All explicit, and/or all images with females.

**Comment by Bionus** [comment]
There's no such option at the moment, blacklist currently only support single tags.
That could be added in a future version though.

**Comment by MasterPetrik** [comment]
BTW, about blacklist\whitelist\ignored options, you calls it "list" but now it's a just a string of tags, and with many tags added it will become hard to operate these "lists", so would be logical switch current "string" option to real "list" option as it should be.

It would also will help to operate complex tags as Topic starter requested.
For example, taglist with rule: one string - one item, it can be single or complex item:

Blacklist.txt:
photo
rating:explicit female
webm
white_background

and every item can be read as separate tag rule, for example:

1. Grabber get image tags 
2. It compares it with blacklist items
3. for item like "rating:explicit female" it search for "rating:explicit" tag, and if it finds it, then search for "female" tag, and if it finds it too then image removes from results, but if image doesn't contain ALL tags from unit, it will be shown. 

I guess, it will be not so hard to implement.
