### ISSUE TITLE
Derpibooru 3+ tags search fails

### ISSUE THREAD

**Issue by Fillyosopher** [Bionus/imgbrd-grabber#844]
### What steps will reproduce the problem?
- Add the API_KEY to the password field in derpibooru's options
- Input a search with 3 or more tags as you would expect.  For example: "faves.gte:250 upvotes.gte:350 explicit animation"
- Alternate option, input 3 or more tags formatted for proper derpibooru searching.  For example: "faves.gte:250 AND upvotes.gte:350 AND explicit AND animation"

### What is the expected behavior? What do you get instead?
I expect that Grabber would load the page
> https://derpibooru.org/search.json?key=HEkmp3xZorgfgyNJzCNq&page=1&q=faves.gte%3A250+AND+upvotes.gte%3A350+AND+explicit+AND+animation&nocomments=1&nofav=1

on one of those two inputs.  This page has an image list as you'd expect.

What happens instead is that Grabber loads
> https://derpibooru.org/search.json?key=HEkmp3xZorgfgyNJzCNq&page=1&q=faves.gte%3A250+upvotes.gte%3A350+explicit+animation&nocomments=1&nofav=1

or it loads
> https://derpibooru.org/search.json?key=HEkmp3xZorgfgyNJzCNq&page=1&q=faves.gte%3A250+AND+upvotes.gte%3A350+explicit+animation&nocomments=1&nofav=1

Neither of these pages have any images, so it displays nothing.  It also suggests, incorrectly, that the user may have put in too many tags.

### How often does this problem occur?
This problem occurs for any series of three or more AND separated tags with the derpibooru source.

### What version of the program are you using? On what operating system?
Grabber 5.2.0
Windows 8

### Please provide any additional information below
It looks like Grabber is removing repeated tags from searches even when they are important.  It did the same with OR tags, removing any after the first.  To solve this, either 
1. allow 'AND' repeats in the search bar
2. have derpibooru searches automatically put AND tags between individual tags (downside being you lose OR)
3. include a place for the user to force a specific URL load that bypasses the search bar.

**Comment by Bionus** [comment]
I didn't know some boards required to use `AND` separators. Is it only derpibooru or are there others like this? I'll change the behavior to not remove duplicates in the next update. As for adding `AND` automatically, if `OR` is also allowed that doesn't sound very good to force the behavior.

**Comment by Fillyosopher** [comment]
I agree, not allowing OR isn't a good option, I was just throwing out ideas.

Also, I tried out the other boards for multiple tag searching, except ichijou and capi.sakurachan which were down.  of them, only Zerochan has a problem with multiple space-separated tags.  "Singing Hatsune_Miku" pulls up
> http://www.zerochan.net/singing hatsune miku?s=id&xml&p=1
instead of
> http://www.zerochan.net/Singing%2CHatsune+Miku?s=id&xml&p=1
To search multiple tags on that site, you have to comma separate.  "Singing,Hatsune Miku" and "Singing,Hatsune_Miku" pull up the correct page.
