### ISSUE TITLE
Trouble with using %filename%

### ISSUE THREAD

**Issue by amped330** [Bionus/imgbrd-grabber#845]
I'm trying to exactly match the filename I would get from simply right clicking and downloading from the site.  %filename%%md5%.%ext% is what I'm using. 

right clicking and saving gives: __fubuki_kantai_collection_drawn_by_minosu__23d36b216c1a3f4e219c4642e221e1a2

but the result I get from the grabber is:
_fubuki_kantai_collection_drawn_by_minosu_23d36b216c1a3f4e219c4642e221e1a2

Is there a way to add an extra underscore before the filename and before the md5 part?

**Comment by Fillyosopher** [comment]
Perhaps `_%filename%_%md5%.%ext%` is what you are looking for?.

**Comment by amped330** [comment]
Ok, _%filename%_%md5%.%ext% successfully adds one before the filename but the one in the middle before the md5 part is still missing.

__fubuki_kantai_collection_drawn_by_minosu_23d36b216c1a3f4e219c4642e221e1a2

**Comment by Bionus** [comment]
Actually this looks more like a bug to me, where `_` might be considered spaces, and double spaces get removed.
I'll take a look tonight and if so push a patch that will be included in next update.
