### ISSUE TITLE
Issue with themes

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#849]
When using a custom theme there doesn't seem to be a way to disable it without deleting it.
It only shows my Dark Mode and has no Default option. 
![image](https://cloud.githubusercontent.com/assets/19770864/24170102/213f396e-0e56-11e7-8fae-09693565a646.png)

**Comment by Bionus** [comment]
Did you delete the `Default` folder that was in `themes`?

**Comment by brodycas3** [comment]
I may have. Can you reupload it for me?

**Comment by Bionus** [comment]
You can find it directly on Github here:
https://github.com/Bionus/imgbrd-grabber/tree/master/release/themes
