### ISSUE TITLE
Crash on Single Image Downloads

### ISSUE THREAD

**Issue by Fillyosopher** [Bionus/imgbrd-grabber#850]
### What steps will reproduce the problem?
click 'Delete All' on downloads
Select a photo from either e621 or danbooru and click 'Get Selected'.
Goto Download page and click 'Download All' or 'Download'

### What is the expected behavior? What do you get instead?
The download screen comes up and immediately crashes.  This crash varies in form.  Sometimes the crash handler is run.  Sometimes the program hangs until Windows reports it as not responding and must be ended manually.  Sometimes the program freezes immediately and windows asks if I'd like to close it.  Sometimes the program freezes immediately and an memory error is thrown, such a
![image](https://cloud.githubusercontent.com/assets/6576295/24174756/bd5ab19a-0e68-11e7-9911-9e1614d0fcfb.png)

### How often does this problem occur?
This happens every time I attempt a download an item(s) from 'Single Images' that does not include an item(s) from 'Group'.

Tests:
- (nothing to download) -> 'Download All': **Crash**
- 1 'Single Image' -> 'Download All': **Crash**
- 5 'Single Image' -> 'Download All': **Crash**
- 5 'Single Image' -> 'Download Selected': **Crash**
- 1 'Group' -> 'Download All': _Fine_
- 1 'Group' -> 'Download Selected': _Fine_
- 2 'Single Image' + 1 'Group' ->'Download All': _Fine_
- 2 'Single Image' + 1 'Group' ->'Download Selected': _Fine_ or **Crash**. Crashes if no item(s) from 'Group' is selected.

### What version of the program are you using? On what operating system?

Windows 8.1 Enterprise 64-bit
I had just updated to Grabber 5.2.3 when i noticed this problem.
I reinstalled 5.2.3 and continued to have the problem.
I reinstalled 5.2.2 and continued to have the problem.

### Please provide any additional information below
https://drive.google.com/drive/folders/0B2wmptU5SqameHdYS2lGSU83Z1E?usp=sharing
Since this site won't let me attach ZIP after claiming it would, the above folder contains crash reports from testing this issue and my settings.ini

This might be a copy of #832 , but I'm not certain.

**Comment by Bionus** [comment]
Indeed, I can reproduce the crash with the steps you described, so I'll work on a fix and include it in the next release. I'll try to push the update before the end of the week (I usually push them on Saturday), as a crash is always a pretty high priority fix.

Thanks for the detailed bug report, I'll be able to fix the problem much faster thanks to it. :smile:

*PS: it indeed seems to be the same issue as #832, but you give additional information, so we can keep both issues.*
