### ISSUE TITLE
Gelbooru is broken

### ISSUE THREAD

**Issue by the612toon** [Bionus/imgbrd-grabber#853]
**Edit: looks like my problem has been solved... I dunno why this happened but it looks like it solved itself.**

### What steps will reproduce the problem?
Install Grabber, make Gelbooru the source.

### What is the expected behavior? What do you get instead?
Gelbooru says there is as many pages as there is images
It's not bulk downloading, It will freeze on downloads, not even crash 
Grabber isn't using the %date% filename at all

### How often does this problem occur?
All day... today...

### What version of the program are you using? On what operating system?
Grabber 5.2.3, tested on Windows 10 and Windows 8

**Comment by Bionus** [comment]
Why close the issue? Did you manage to fix your problem?

**Comment by larry-he** [comment]
It seems like Gelbooru's API was down, but it's working now.
