### ISSUE TITLE
can not test source logins

### ISSUE THREAD

**Issue by ROdoka** [Bionus/imgbrd-grabber#856]
### What steps will reproduce the problem?

hitting the test button on the credentials tab of a source

### What is the expected behavior? What do you get instead?

I suppose I should get a "successful" instead of " unable to test"

### How often does this problem occur?

everytime

### What version of the program are you using? On what operating system?

5.2.3

### Please provide any additional information below

beside that, the sources window width could be bigger, I see only half of the "Options" buttons :)

**Comment by Bionus** [comment]
Depends on the source, but most the "unable to test" ones use URL logins (by passing the username and hashed password directly in the URL), and it's impossible to properly test if the login works or not with that system. One option would be to simply remove the "Test" button for those sources though.

Let's take Danbooru as an example, there's no real way to check. One could check premium accounts with a 3-tags or a "forbidden" tag search, but for normal accounts, it's not that easy (unless I missed something actually).

For Sankaku for example, it's the same system but they have different max page limit for logged in users, so Grabber checks by doing a search at page 50 and see if there's an error message. Another option could be trying to connect to the JSON API which is reserved to logged in users.

Which source exactly were you mentioning in this issue?

**Comment by ROdoka** [comment]
ah, thanks for the background information :)

the sources, that don't work, are zerochan, both rule34 sites, e621.net and chan.sankakucomplex
only gelbooru returns a success

so I suppose e621 won't work because of danbooru

**Comment by Bionus** [comment]
Closing because now the "Test" button is not shown anymore for sources that do not have a configured way to test logins.
