### ISSUE TITLE
md5 repeating

### ISSUE THREAD

**Issue by amped333** [Bionus/imgbrd-grabber#860]
Hopefully this is just something simple that I'm missing but I'm trying to duplicate the filename I would get from right clicking and selecting download on danbooru.  

`%filename%%md5%.%ext%` is what I'm using to name the files, but since the image md5 is included in danbooru's filename it ends up putting the md5 twice at the end of the name.  

For example I get
```
__fubuki_kantai_collection_drawn_by_minosu__23d36b216c1a3f4e219c4642e221e1a223d36b216c1a3f4e219c4642e221e1a2
```

insted of
```
__fubuki_kantai_collection_drawn_by_minosu__23d36b216c1a3f4e219c4642e221e1a2
```

It seemed like `%Filename%.%ext%` would give me what I was looking for but I get a warning say this isn't a valid option.

**Comment by Bionus** [comment]
> It seemed like %Filename%.%ext% would give me what I was looking for but I get a warning say this isn't a valid option.

It's just a warning, as long as you understand what it says, you can safely ignore it and keep downloading, nothing bad will happen. :smile:

The solution for you is indeed to use `%filename%.%ext%`.

**Comment by Bionus** [comment]
In addition, this warning is also invalid for Danbooru's filename, as their filenames already include the file's MD5 and are therefore unique.

**Comment by amped333** [comment]
Ok, I ignored the warning and used %Filename%.%ext% but it wipes the filename completely leaving me with only .jpg after a blank name.  

Here's a screenshot of the result. https://i.imgur.com/YdJJ6JV.jpg

**Comment by Bionus** [comment]
It should be a small F, `filename` instead of `Filename`.

**Comment by amped333** [comment]
It automatically capitalizes when I click save.

**Comment by amped333** [comment]
Is there way to stop it from doing that?  %filename%%md5%.%ext% lets %filename% have a lowercase f just fine but the moment I remove the %md5% part it forces the capitalization. %Filename%.%ext%

**Comment by Bionus** [comment]
You should be able to edit it manually can't you? It's a Windows select box so it shouldn't forbid it. Else you can always clear the filename history by deleting the `filenamehistory.txt` file that can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`.

**Comment by amped333** [comment]
Manually deleting the filename history file like you recommended is what ended up working.  Thanks!

**Comment by barryanders** [comment]
> Bionus: It should be a small F, filename instead of Filename.

> amped333: It automatically capitalizes when I click save.

That succession of comments made me lol

**Comment by Mccranky83** [comment]
I'm using macOS so I did a roundabout search and figured that since it counted as an user-specific setting, the  filenamehistory.txt was probably stored in ~/Library/Preferences. In this case, it's actually in ~/Library/Preferences/Bionus/Grabber
