### ISSUE TITLE
Bug with preview window background changing

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#861]
Here I am, and fresh bugs from 5.2.4!

when you change preview window background to another color, this bug will be clearly seen.
I'm telling about little standard-grey-colored vertical line next to tags area, that appears when you opens preview window. If you will go to next\previous image, it will dissappear. but if you will close window, and open any image in preview again, it will appears again...

![2017-03-26_045119 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24328326/3ecb5944-11ef-11e7-8076-be3994162383.png)

![2017-03-26_045212 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24328327/425fc414-11ef-11e7-85f1-e7c9afecf421.png)

### How often does this problem occur?
100% repeatability for win 7

### What version of the program are you using? On what operating system?
5.2.4

P.S.
can I somehow remove this  annoying message from the page? I read it 3 times already.
![image](https://cloud.githubusercontent.com/assets/22294259/24328313/b4730206-11ee-11e7-9a66-7748a0dccd61.png)

**Comment by Bionus** [comment]
> can I somehow remove this annoying message from the page? I read it 3 times already.

I don't think you can

**Comment by Bionus** [comment]
> can I somehow remove this annoying message from the page? I read it 3 times already.

I don't think you can

**Comment by MasterPetrik** [comment]
BTW, I guess it will be better make default color for preview window  #ffffff - white, it's much better for images.

**Comment by MasterPetrik** [comment]
Here is another bug with preview window backgroung appears with custom themes.

1. Change theme to some custom theme
2. Change background color( to yellow for this example)
3. In preview window you will see colored vertical line next to tags area(1) as it described above.
4. Also you will see, that background of window changed to yellow, but background of image area still colored in another color(2). 

In default theme this isn't happening.


Possible solutions:
1. Make image area background color depended from window bg color
2. Make image area background invisible

## Changing background color
![image](https://cloud.githubusercontent.com/assets/22294259/24863628/50429328-1e0a-11e7-9030-90d020cf0d5d.png)
## Theme: Dark Orange
![2017-04-10_162741 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24863771/dd29e282-1e0a-11e7-96b0-d5b6474621ce.png)
## Theme: DarkQT
![image](https://cloud.githubusercontent.com/assets/22294259/24864186/10a9aa7e-1e0c-11e7-94dc-969eea702a64.png)
## Theme: Default
![image](https://cloud.githubusercontent.com/assets/22294259/24864160/f8bdcd6e-1e0b-11e7-887d-de74702d9d55.png)

**Comment by MasterPetrik** [comment]
I guess, you can fix both problems for 10 minutes, maybe you can add it to 5.3.0?

**Comment by Bionus** [comment]
> I guess, you can fix both problems for 10 minutes, maybe you can add it to 5.3.0?

I already tried to fix this, and didn't succeed after 30min investigations, so...
Depends whether I have some free time before releasing 5.3.0.

**Comment by MasterPetrik** [comment]
The problem with image area color
### Fixed in 5.3.0
![2017-05-21_155254 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26284228/1399a696-3e3f-11e7-82ed-81c216f5a2d4.png)
### Come back in 5.3.1
![2017-05-21_160204 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26284234/454195fa-3e3f-11e7-9f6c-b718e1d2da96.png)

**Comment by Bionus** [comment]
Damnit. I even checked, but now that I remember it was a big image so I didn't notice 😓

**Comment by brodycas3** [comment]
@MasterPetrik 
> P.S.
can I somehow remove this annoying message from the page? I read it 3 times already.
![](https://cloud.githubusercontent.com/assets/22294259/24328313/b4730206-11ee-11e7-9a66-7748a0dccd61.png)



You can get rid of that message if you use Ublock Origin, 
![2017-05-21_10-25-50](https://cloud.githubusercontent.com/assets/19770864/26284735/1726965e-3e10-11e7-8ccc-66c3d2bc00ed.gif)

**Comment by Bionus** [comment]
This bug seems to only apply to the black theme, which forces some background color.
This does not happen with the default one.

**Comment by Bionus** [comment]
> You can get rid of that message if you use Ublock Origin,

I wish more issue posters read it, though. :smile:
