### ISSUE TITLE
Deleting files function need rework\bugfix

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#865]
Some problems with https://github.com/Bionus/imgbrd-grabber/issues/690 realization. 
There is a bug, - you cant delete ignored images.

If you opening  saved image in preview window, button text is "delete" and pressing it will delete image. 
But if you opening  ignored image in preview, button text will be 'ignored!" and pressing it will do nothing. So you can't delete ignored images now, in 2.3.4.

![2017-03-28_011317 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24384259/32514a48-136b-11e7-8fd1-34eb2be6c97c.png)

![2017-03-28_011346 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24384261/3670133e-136b-11e7-9be9-2cfab786fa99.png)

# Visualisation of wrong work delete function:
![2g](https://cloud.githubusercontent.com/assets/22294259/24384744/cab76fa8-136e-11e7-8891-4241af7be239.png)

But if you just change "ignored" button to "delete" button, it will be not fully correct. Because in that case, same button with same text "delete" will be showing both for saved and ignored images. And you will have no clue to differs them, because in previous versions only button caption showed you is this image saved or ignored.

# That is the originally expected right behavior from https://github.com/Bionus/imgbrd-grabber/issues/690:
![default](https://cloud.githubusercontent.com/assets/22294259/24384739/c39a74ae-136e-11e7-928a-16225892d3b9.png)

So this how I suggest to solve that problem and how this function should really works:

If you opening saved image in preview window, button text is "Saved" and pressing the button will change text to "delete" and pressing it will delete image. 
If you opening ignored image in preview, button text is "Ignored" and pressing the button will change text to "delete" and pressing it will delete image. 
If you opening new image in preview window, button text is "Save" and pressing the button will change text to "Saved" and pressing the button will change text to "delete" and pressing it will delete image. 

Yes, it will require more work for implementation, but I'm sure that this is the best way to make it convinient.

**Comment by Bionus** [comment]
While the "Ignored" thing seems to indeed be a bug, adding an additional click to show the "Delete" button seems like it would totally hide the feature and users won't even know it's here until they accidentally click the button.

If you really want to show "Saved!" or "Deleted!", it could be shown for 1 second before being replaced by "Delete" / "Save", even if I doubt it really adds anything. But hiding the feature sounds strange.

**Comment by MasterPetrik** [comment]
> If you really want to show "Saved!" or "Deleted!", it could be shown for 1 second before being replaced by "Delete" / "Save", even if I doubt it really adds anything. But hiding the feature sounds strange.

As "Saved" status I mean also "already existed" status. And I dont even have an idea about any "deleted" status, it's pointless, the problem is not here. I told nothing about something like that.
As I said, the problem is - in current state you are unable to differ "saved" and "ignored" images, as you could do that in previous versions, instead of it button for both statuses will display "delete" text, so you will not know, would it delete saved or ignored image?

> While the "Ignored" thing seems to indeed be a bug, adding an additional click to show the "Delete" button seems like it would totally hide the feature and users won't even know it's here until they accidentally click the button.

Seriously? In current and all previous versions, if you you wanted to know, "is this image ignored?" you needed to click "save" button and only then it text changes to "ignored". This is not a very convinient system with same way as "an additional click to show the "Delete" button"(c), but in current state you need to do an additional click to show the "Ignored" button, and nobody complained about that. 
So you no need to worry about that. Deleting function exist only in last version, and there is still time to change the way it works. On the other hand, users get used to see "saved" and "ignored" text on this button many-many versions, and you can describe this moment in changelog and wiki, there are much more complex and unobvious things in grabber for user understanding, and I bet eveb new users very soon will fint that delete function, because sooner or later but they anyway will press this buttun more then 1 time, and then they will understand all deleting system, because, in fact, it's not to hard to remember. (Not more hard then realize how to see ignored status in current versions, hehe)

**Comment by Bionus** [comment]
So let's rephrase my question then, why do you need to differentiate "Saved", "File already exists" and "Ignored" states for? (as it seems to be the main issue here)

Before, the states were (sorry, I don't have any graphic skills):
* Non existing images: "Save" -> "Saved!"
* Existing for the current filename: "File already exists"
* Existing somewhere in the MD5 database: "Save" -> "Ignored!"

Now, they are:
* Non existing images: "Save" -> "Delete" -> "Save"...
* Existing for the current filename: "Delete" -> "Save"...
* Existing somewhere in the MD5 database: "Delete" -> "Save"...

I'm not sure which state exactly you're willing to bring back. I fail to see the use to separate once more "File already exists" and "Ignored!" as they both pretty much mean the file is already present on the computer. Separating "Saved!" and the other two could make sense to know whether the image was there before, or if it was just downloaded. But in that case, an option would be:

* Non existing images: "Save" -> "Saved!" -> "Delete" -> "Save"...
* Existing for the current filename: "Delete" -> "Save"...
* Existing somewhere in the MD5 database: "Delete" -> "Save"...

And separating the MD5/filename "already existing" files could just mean changing the text of the delete button, without adding another hidden step which may not be obvious:

* Non existing images: "Save" -> "Saved!" -> "Delete" -> "Save"...
* Existing for the current filename: "Delete (exact)" -> "Save"... (or "File already exists. Delete?")
* Existing somewhere in the MD5 database: "Delete (md5)" -> "Save"... (or "Ignored! Delete?")

(for example)

> Seriously? In current and all previous versions, if you you wanted to know, "is this image ignored?" you needed to click "save" button and only then it text changes to "ignored". This is not a very convinient system with same way as "an additional click to show the "Delete" button"(c), but in current state you need to do an additional click to show the "Ignored" button, and nobody complained about that.

Just because the previous system was bad doesn't justify replacing it to something that, even if better, is still not very good: clicking a non-"call to action" button (in this case "Saved!", "File already exists", or "Ignored") doesn't sound very obvious to new users.

**Comment by MasterPetrik** [comment]
> Before, the states were (sorry, I don't have any graphic skills):
Now, they are:

All correct. I will even draw it for you)
![2gf](https://cloud.githubusercontent.com/assets/22294259/24432742/e41567de-142c-11e7-884f-85ebaff4d445.png)

> why do you need to differentiate "Saved", "File already exists" and "Ignored" states for? (as it seems to be the main issue here)

Indeed. It is very important, where exactly saved image is. For example first you just searched some boorus with empty search request and saved random images. Then you search some artist and saving his images that you liked, but you see that one of images "ignored", but you rather place this image to artist folder, so you clicking on "ignored" button and to change it to "delete" and delete image from wrong folder and saving it again by pressing "save" button in current download folder. Similar situations appears very often, and very important to know where are image saved.


> And separating the MD5/filename "already existing" files could just mean changing the text of the delete button, without adding another hidden step which may not be obvious:
> (or "File already exists. Delete?")
> (or "Ignored! Delete?")

1. Question sentense very bad looks in regular interface
2. Too many text. will not fit for small window:
![image](https://cloud.githubusercontent.com/assets/22294259/24432719/b89db066-142c-11e7-9d52-1353938269d1.png)

![default](https://cloud.githubusercontent.com/assets/22294259/24384739/c39a74ae-136e-11e7-928a-16225892d3b9.png)
How I suggest to organize it:
- Non existing images: "Save" -> "Saved!" -> "Delete" -> "Save"...
- Existing for the current filename: "File already exists" -> "Delete" -> "Save"...
- Existing somewhere in the MD5 database: "Ignored!" -> "Delete" -> "Save"...

This variant have a bunch of pluses compare to your variants:
- Much informative then only "delete" state variant
- Easy to discover, users dont like to read guides and wiki, but they like to pressing everywhere, and they already know that way with click for changing button state already have been used in Grabber(for ignored state), so this is not a problem.
- For all states way are the same, easy to understand and remember.
- +works for small window size
- Does not contain unnecessary info on the button(compare to "all text in one" variant)
- Impossible to accidentally delete an image(it's really important, mostly for ignored images, but even for "already existed" images accidentall deleting and saving again will break download date)

**Comment by barryanders** [comment]
Would this be easier to just separate save/delete button and ignore/reconsider(unignore)?

**Comment by MasterPetrik** [comment]
> you could also consider removing the close button as there is an X in the corner of the window.

No-no-no! This button is also "Save and close button", and these two buttons are VERY useful, I'm so glad that they exist in grabber, I'm using it almost 5-10 times for each session.

> Would this be easier to just separate save/delete button and create a new button for ignore/reconsider(unignore)?

If you separete these buttons, it will cause following problems:
1. To many buttons(as you said) and, as result, problems with small preview window because of that
2. You able to accidentally delete an image(it's really important, mostly for ignored images, but even for "already existed" images accidentall deleting and saving again will break download date)
3. 95% time you will not use "Delete" button, so it will be take place in the buttons bar all the time. Moreover, If image isn't saved yet, this button will be completely useless and will be just take place, It's not optimal solution.
4. If user dont use ignoring images function at all, then separated ignore\unignore button will be useless for him and will only take place.
5. Moreover, If user disabled clone checking via md5s list, this button will be uselss too.


There are exist some users, who never delete saved images via grabber(they search and delete in download folders manually), for them separate button will be useless too. 

Morever, obviously users don't use deleting function for every saved image, but in other hand, they use saved\already existed\ignored captions to differ ALL saved images. That's why in GUI differ saved images function must prevail on deleting function.

**Comment by barryanders** [comment]
Yeah, I oversimplified their function. Didn't realize the underlying complexity.

**Comment by MasterPetrik** [comment]
@Bionus any final decision about this issue? users still can't delete ignored images, it's kind of sad(

**Comment by MasterPetrik** [comment]
@Bionus any final decision about this issue? users still can't delete ignored images, it's kind of sad(

**Comment by Bionus** [comment]
![grabber save](https://user-images.githubusercontent.com/882719/28752453-15b24cae-7520-11e7-9e3f-6519b91dab45.png)

**Comment by MasterPetrik** [comment]
Mostly looks good.
A few questions about your schema:
How "Saving..." is turning to "moved" and "copied" ? How can it be and what does that mean?

**Comment by BarryMode** [comment]
I'm guessing it means if you allow a duplicate to be redownloaded, then depending on your preferences, it will overwrite the original (saved), copy to a new folder (copied), or move the already downloaded image to the new folder (moved).

**Comment by MasterPetrik** [comment]
At first I thought the same, but look:
![28752453-15b24cae-7520-11e7-9e3f-6519b91dab45](https://user-images.githubusercontent.com/22294259/29104221-dde7f59e-7ccc-11e7-8ac2-a0ed8d6b4cd9.png)
It can't "copy" or "move" nothing because saving starts after DELETING existed files, so nothing can be moved or copied anymore, just "saved". That's why it looks strange...

**Comment by Bionus** [comment]
Indeed, that might be an impossible case as file will definitely need not to exist to be in the "Save" step.

**Comment by BarryMode** [comment]
Oh yeah, I was wrong because if he file already exists, then it appears that saving is not an option.
