### ISSUE TITLE
Crash on complete

### ISSUE THREAD

**Issue by Jakkun** [Bionus/imgbrd-grabber#866]
### What steps will reproduce the problem?
Download a batch of files. The remove box is checked.

### What is the expected behavior? What do you get instead?
Expect the program to finish the download, pop up the completed notification box, and clear downloaded files from list. Instead the application crashes roughly when it finishes downloading everything.

### How often does this problem occur?
Just about every time.

### What version of the program are you using? On what operating system?
5.2.4 is what I just installed I believe, it has done this for the last several releases. Windows 10.

### Please provide any additional information below
I'm not sure if this is still the case, but in the past if I finished a download without it crashing, it would crash when I tried adding new pictures to the queue. I rarely have the chance to test that anymore since it crashes on completion.

I'm saving to an external HD, the program is installed in program files on C.

**Comment by MasterPetrik** [comment]
Your issue is complete duplicate of https://github.com/Bionus/imgbrd-grabber/issues/812 so...

**Comment by Jakkun** [comment]
I just tested that out, It does seem that unchecking that does fix the issue. I guess it is a duplicate.
