### ISSUE TITLE
Keyboard shortcut request for individual image window

### ISSUE THREAD

**Issue by BarryMode** [Bionus/imgbrd-grabber#867]
On the individual window for images, if I press `cmd+w`, it closes the search tab rather than closing the individual image window. To me, it would make sense that it would close the window rather than the tab (although it's fine to close the tab if the window isn't open).

**Comment by barryanders** [comment]
Appears to be the same situation when preferences window is up, but I thought I would mention in case it's a window by window thing (probably not). The shortcut closes the tab rather than the preferences window.

**Comment by BarryMode** [comment]
I just checked my open PRs and realized this was still open so I decided to reverify that this is still happening since it has been a really long time. As it turns out, it is. I know. Not surprising.

**Comment by Bionus** [comment]
What are you trying to say? 😄 

Not only this issue is one of the lowest priority, but I can't reproduce it easily, not having a macOS machine myself. And working on things that you can't reproduce is asking for problems.

PRs are however welcome.

**Comment by BarryMode** [comment]
> What are you trying to say? 😄
Really, I was just hoping that since it had been a while that the OS updates or QT updates would have changed/resolved the behavior.

> PRs are however welcome.
I would love to do a PR if I can figure out how to do this.
