### ISSUE TITLE
Bug for resaving a deleted image, only occurs when not exiting the window

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#868]
### What steps will reproduce the problem?

1. Save an image
2. Leave the window
3. Go back into the window.
4. Delete the image.
5. Save it again. You get a zero byte file.

If you close this window first and then go back in and save, it downloads as expected. It only gives a zero byte if you delete and resave without leaving the window.

### What is the expected behavior? What do you get instead?

Download the file.

### How often does this problem occur?

As described above, every time.

### What version of the program are you using? On what operating system?

grab 5.2.4, macos 10.12

### Please provide any additional information below

Love this feature to delete on page. Comes in handy.

**Comment by Bionus** [comment]
I can't reproduce this, by deleting the image from hard drive then opening the image or just deleting it from the window using the delete button, when I click "Save", it saves with the right content. Do you have special settings that might cause that?

**Comment by barryanders** [comment]
I have **If file already exists** set to **don't save**, I have some blacklisted tags, and I have an image command for Shimmie.

**Comment by Bionus** [comment]
I could reproduce, actually you need to reload the page before re-opening the window to have the bug appear the first time.

Steps to reproduce:

* Save an image
* Leave the window
* **Reload the page**
* Go back into the window.
* Delete the image.
* Save it again. You get a zero byte file.

**Comment by barryanders** [comment]
I don't even remember how I found this issue and the steps to reproduce it are pretty unlikely for the user to ever perform, however, somehow I managed to do it xD glad you figured it out.
