### ISSUE TITLE
Why are some of the images smaller on certain websites?

### ISSUE THREAD

**Issue by TheGho7t** [Bionus/imgbrd-grabber#869]
Sorry if this has already been answered or this is....ABSURDLY obvious because I'm great at pointing out such things smh, but I can't figure out why images on, say, chan.sankaku are INCREDIBLY small and then I look at zerochan and they're MASSIVE.

Examples are here on the bottom. I also honestly just wanted to say this is BY FAR the coolest thing I HAVE EVER USED! This is a life saver. I wasted my time on websites FAR too much and I thank you for all the work everyone has put into this. Really awesome stuff.

![2017-03-30 21_03_06-grabber](https://cloud.githubusercontent.com/assets/26805531/24532169/54c678c8-158c-11e7-9287-9fd0b3980e18.png)
![2017-03-30 21_03_21-](https://cloud.githubusercontent.com/assets/26805531/24532168/54c5efa2-158c-11e7-9d7e-b58735d264aa.png)

**Comment by MasterPetrik** [comment]
I can guess that thumbnails images has defferent resolution depending of type of site, where are they from.  Usually all booru sites on same engine has same thumbnail size and images per page number. Looks like the most common type is 150px150p thumbnails and 20 images per page. But sites on another engine may have their own parameters(like yande.re with giant thumbnails or zerochan with 100 images per page)

I hope Bionus will correct me if Im'mistaken in something.

**Comment by TheGho7t** [comment]
OH OKAY I got it my bad that, actually makes a lot of sense. Thank you very much for the quick response as well.

**Comment by Bionus** [comment]
It's exactly as MasterPetrik said.

Note that if you have a huge screen (4K or something) and find the thumbnails too small, there's a thumbnail upscale setting to make them bigger. :smile:

**Comment by MasterPetrik** [comment]
As the issue already closed, I want to ask some related questions:
1. Where is this thumbnail upscale setting?
2. Is there some setting in grabber to set images per page number for merged results?
