### ISSUE TITLE
Crashing repeatedly

### ISSUE THREAD

**Issue by ivaskaj** [Bionus/imgbrd-grabber#870]
### What steps will reproduce the problem?

Search for and download a tag.  Any tag.  Any source.

### What is the expected behavior? What do you get instead?

Program should download all images as ordered.  Instead, it crashes repeatedly.  There is no way to recover from where it left off; when I re-open the program, all downloads show the green check mark, indicating that they are successfully downloaded.  

### How often does this problem occur?

Every single time I use the program.

### What version of the program are you using? On what operating system?

5.2.4

### Please provide any additional information below

Problem occurs regardless of how many files I'm downloading or the number or sources I'm downloading from.  It has an uncanny ability to crash within minutes of me leaving the computer unattended, regardless of how long I've been sitting here babysitting it.  Tonight, I searched for a tag, and 160,000 results from 17 different boorus were found.  I sat here for 2 hours watching.  I left the house, and when I returned, many hours later, only 200 more photos were downloaded than I had when I left, and the program had crashed.  It must have crashed within minutes of me leaving.

**Comment by ivaskaj** [comment]
I decided to undo the settings I'd customized to see if it would fix the problem, and that seemed to help.  I had added tags to the ignored tags list under general options, and had tried to enable external logging in attempt to be able to determine where the downloads stopped when the program crashed.  The external logging does not work at all, by the way.  The browse button does nothing, and manually entering the path to the log doesn't work either.  The program did crash before I made those changes, but not as often.  Downloading more than 10,000 images at a time is still pretty much impossible.  Every morning when I wake up, I'm greeted by the crash notification box.  I'm using Win10 x64, by the way.  Alienware PC, Core i7, 16GB of RAM.

**Comment by Bionus** [comment]
Could you share your `settings.ini` (`C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`) as well as the `.igl` file of the download that causes the program to crash after only 200 pictures downloaded?

> There is no way to recover from where it left off; when I re-open the program, all downloads show the green check mark, indicating that they are successfully downloaded.

You should be able to re-start them, and it shouldn't download already existing images.

> had tried to enable external logging in attempt to be able to determine where the downloads stopped when the program crashed

External logging is something else entirely, if you want logs, the `main.log` is in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`.

>  The external logging does not work at all, by the way. The browse button does nothing, and manually entering the path to the log doesn't work either.

Indeed, I'll push a fix for that, didn't notice this regression.

> The program did crash before I made those changes, but not as often. Downloading more than 10,000 images at a time is still pretty much impossible

So you mean that with ignored tags as well as external logging, you crash after ~200 images, but without after ~10,000?

**Comment by SultrySamthepennanceman** [comment]
I've since changed it, but here's two of them (I had one on a VTRoot folder from a sandbox utility, so it might be older and more relevant to what you're after. ) 
1. (current) 
https://anonfile.com/uetfz3cfb9/settings.ini
2. (old)
https://anonfile.com/yftaz8c0b1/settings.ini

**Comment by SultrySamthepennanceman** [comment]
.Can't give the .igl though as this was ages ago.
