### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by baozi403** [Bionus/imgbrd-grabber#871]
How can I log on to derpibooru.org。
If I'm not logged in，i cant download R18 pictures.

**Comment by Bionus** [comment]
You can just get your API key from your user settings, and use it as your password in Derpibooru's "Credentials" tab:

![image](https://cloud.githubusercontent.com/assets/882719/24560572/95a4e494-1643-11e7-8d8c-0aab7a95c5a0.png)
