### ISSUE TITLE
Hi it download thumbnails  in most sites

### ISSUE THREAD

**Issue by angaratosurion** [Bionus/imgbrd-grabber#873]
### What steps will reproduce the problem?

i just type " rias_gremory for example and press ok and next getall

### What is the expected behavior? What do you get instead?
No to now have small  thumbnails

### How often does this problem occur?

everytime

### What version of the program are you using? On what operating system?

5.2.4 Windows 10 Pro 64bit

**Comment by MasterPetrik** [comment]
Hmm... your grabber downloads thumbnails images instead of original ones in betch downloads, am I correct?

**Comment by angaratosurion** [comment]
yeah but download and big ones ..

**Comment by MasterPetrik** [comment]
then you should describe remaining information, and get us more details, we don't know your grabber version, your OS, frequensy of this bug etc. Please, follow Bugreport rules if you want to solve the problem.

**Comment by maskkulin** [comment]
good I'm not the only one

**Comment by angaratosurion** [comment]
Application Version 5.2.4
Os Version Windows 10 64bit Pro
the log  :

[main.txt](https://github.com/Bionus/imgbrd-grabber/files/887893/main.txt)

**Comment by Pika256** [comment]
I will confirm this issue.
Grabber v5.2.4
Windows 7 64-bit Ult

**Comment by Bionus** [comment]
From your log file, it seems like the `/thumbnails/` is being replaced by `//` instead of `/images/`, while `thumbnail_` is being properly removed (Gelbooru). You can try to change the API order to put XML before regex, that should solve the problem until the update.

Issue #843 mentions Sankaku. Is there any other source causing problems?

**Comment by sergalbutt** [comment]
Any of the *.booru.org websites seem to only download thumbnail images as well.
