### ISSUE TITLE
Extracting tag information

### ISSUE THREAD

**Issue by larry-he** [Bionus/imgbrd-grabber#874]
I want to have tags of the images I download written to a csv in this format:

md5, listoftags

Do you have any ideas on how I can do this? I'm open to coding this up myself. Just need guidance on what files I would need to change.

**Comment by barryanders** [comment]
Preferences > Commands > Image

Write this:
```
%md5%, %all%
```

It will output per image to a file called console.log and from there, you can rename it to a csv file.

**Comment by Bionus** [comment]
You could also use the "separate log" option that will append a format to a given file every time an image is saved:

![image](https://cloud.githubusercontent.com/assets/882719/24721417/9bce85cc-1a40-11e7-9e52-b63db447f85a.png)

Note that the "Browse" and "..." are broken in the current version though.

And the same as Barry said, maybe you could use TSV instead, or semicolon-separated (excel and most tablers actually support opening CSV with semicolons or tabs instead of commas as separators).

**Comment by barryanders** [comment]
Hey, I didn't know about the logging. That's good to know about!

**Comment by larry-he** [comment]
This looks promising. Will the log work for images already saved? So if Grabber attempts to download an image and doesn't download it because a copy already exists, will the log be updated?

**Comment by Bionus** [comment]
No it won't. In order to prevent the same data from being written twice to the file, it's only written when the image is saved.

**Comment by larry-he** [comment]
Would you happen to know what files I would need to change so it will save regardless of whether the image already exists? A feature like this is something only I would want so I don't think it's worth your time to implement.

**Comment by Bionus** [comment]
I'll add it when doing #875. However, if you feel like recompiling everything, you can edit the [image.cpp](https://github.com/Bionus/imgbrd-grabber/blob/master/lib/src/models/image.cpp#L899:L913) file.

The part in question is:
```cpp
if (m_settings->value("SaveLog/activate", false).toBool() && !m_settings->value("SaveLog/file", "").toString().isEmpty() && !basic)
{
	QString savelogFormat = m_settings->value("SaveLog/format", "%website% - %md5% - %all%").toString();
	QStringList cont = this->path(savelogFormat, "", 1, true, true, false, false, false);
	if (!cont.isEmpty())
	{
		QString contents = cont.at(0);
		QFile file_tags(m_settings->value("SaveLog/file", "").toString());
		if (file_tags.open(QFile::WriteOnly | QFile::Append | QFile::Text))
		{
			file_tags.write(contents.toUtf8() + "\n");
			file_tags.close();
		}
	}
}
```

It's currently inside a `!f.exists() && (md5Duplicate.isEmpty() || whatToDo == "save")` condition, you can simply take it out, just before line 950 for example. Then it'll be always applied, whatever the save result is. But you may end up with duplicate entries.
