### ISSUE TITLE
Feature Idea: add plus button for multiple file logs

### ISSUE THREAD

**Issue by ItsSohma** [Bionus/imgbrd-grabber#875]
#874 got me thinking about the uses of external logging and file generation. The feature idea that I have is simply to allow for multiple files to be generated. Perhaps a + button that lets you add additional files and formats. Definitely not a priority, just an idea.

Reference:
![screen shot 2017-04-06 at 2 13 26 pm](https://cloud.githubusercontent.com/assets/5648875/24771458/4565e16a-1ad3-11e7-96d3-c49001cadf0d.png)

**Comment by Bionus** [comment]
Can I ask you what would you use it for? And if there's multiple of them, should they be conditional just like filenames? (cf. conditional filenames where a filename will be enabled if a given tag is present in the image, or if a %token% is not empty)

**Comment by barryanders** [comment]
Honestly, I don't know what it would be used for, and is certainly not a priority of any kind. Feel free to not even do it. I have one log that outputs the lines needed to import into Shimmie. I had the thought, then, well what if I wanted to make a separate file list with image file names and source urls or something like that in case I needed to find the originals again. There's a lot of potential outputs here. In fact, if you made the name of the log file %md5%, you could output one file per image. That might already be possible. Anyway, I don't currently think I would currently have a specific use as the local board with Shimmie is sufficient in my opinion.

On a different note, in the future, I could see using the program over using a local board if it had the ability to view already downloaded images, which would be really cool btw. I suppose technically I can do this if I add the source of my local board back into Grabber... hmm, I'll try that lol

**Comment by Bionus** [comment]
> In fact, if you made the name of the log file %md5%, you could output one file per image. That might already be possible.

It's possible yeah, using the "separate text file" option, that create a "%filename%.txt" file for every image saved. Your suggestion sounds more elegant though, and allows to merge both features into one, which is a good thing in my mind: there are too many settings that many ppl don't know what they do. I really should add some doc.

> On a different note, in the future, I could see using the program over using a local board if it had the ability to view already downloaded images, which would be really cool btw. I suppose technically I can do this if I add the source of my local board back into Grabber... hmm, I'll try that lol

If it's a Shimmie it's indeed possible. Reminds me of issue #558 though.

**Comment by barryanders** [comment]
Yes, it is kind of like issue #558. I'll post over there about it.
