### ISSUE TITLE
Is there a simple way/simpler way to make most of the background black and the text white?

### ISSUE THREAD

**Issue by TheGho7t** [Bionus/imgbrd-grabber#876]
I was messing around with it tonight here for, well about an hour actually. I'm pretty good at picking stuff up very fast, but I got myself pretty stumped with changing some of the text, well actually most of the text.

Here's where I got. I only know how to edit the Widget, PushButton, TextEdit, and Label xD

![2017-04-08 02_53_31-greenshot](https://cloud.githubusercontent.com/assets/26805531/24826548/9cf41954-1c06-11e7-80cb-4cc80b372e42.png)

Any help appreciated but I don't want to deter from actual problems or way more important issues, just was curious to be honest.

Thanks!

**Comment by TheGho7t** [comment]
I also just realized that it is CSS. Can I do it like normal CSS? I hadn't tried it, and honestly I would mess around with it more but I'm getting too sleepy at this point.

(By normal CSS, if this helps because I honestly don't even know what "normal CSS" would be, is like on MAL. Like this for example:

#searchBox {
    width: 128px !important;
    margin-left: 1px;
}

I loved messing around with MAL but dang that's some confusing stuff sometimes)

**Comment by Bionus** [comment]
I don't know what "MAL" is but yeah, it's pretty much normal CSS.

You can find the full reference here (there are minor changes):
https://doc.qt.io/qt-5/stylesheet-reference.html

The easiest way would be something in the lines of:
```css
* {
    background-color: black;
    color: white;
}
```

But that seems a little bit extreme.

Did you check how other themes were made for Qt? I know there's a few dark themes out there, such as:
https://github.com/mervick/Qt-Creator-Darcula
https://github.com/ColinDuquesnoy/QDarkStyleSheet
https://github.com/EClaesson/QTDark
http://tech-artists.org/t/release-qt-dark-orange-stylesheet/2287#post14381

**Comment by barryanders** [comment]
Thanks for the theme references.

**Comment by MasterPetrik** [comment]
Do you know any non dark QT themes?

**Comment by barryanders** [comment]
Here's one: https://github.com/MartinBriza/adwaita-qt

**Comment by TheGho7t** [comment]
Oh sorry. To Bionus: MyAnimeList, MAL for short. It uses CSS for the anime and manga lists that each person has.

Thanks you EXTREMELY much for the themes there, I'll check these out in a little bit! That should work perfectly for me. I just wanted something less brighter so I can look at my pictures at night better.....

That sounds was worse when you include it with my photo here. I'll be able to mess around better too after I look at these. Thanks again!

**Comment by MasterPetrik** [comment]
BTW, did Bionus made font for tags lists in grabber a little bigger? I liked the old size.
Is there any setting for it's size? 
**The new one:**
![2017-04-08_220635 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24832464/d468816e-1cb9-11e7-909b-ed376113b687.png)
**The old one:**
![2017-02-25_160813 win7 mastercore 8](https://cloud.githubusercontent.com/assets/22294259/24832466/d7cbbd30-1cb9-11e7-9d5c-870e3ea54945.png)

**Comment by TheGho7t** [comment]
Okay so one more thing real quickly.

The orange theme you had on your suggestions there, perfect. Works perfect, exactly what I'd want, but the text for the Favorites isn't changed. Is there a way to change the color for that text?



![2017-04-08 17_31_05-greenshot](https://cloud.githubusercontent.com/assets/26805531/24832611/2b2f1028-1c81-11e7-8a1c-eab17c2d632c.png)

**Comment by Bionus** [comment]
You mean you want the favorites text to be black?

The favorites are not QLabel, they are QAffiche (custom Grabber UI class). So:

```csss
QAffiche {
	color: black;
}
```

Your theme is black text on dark grey/maroon background? 😱

**Comment by MasterPetrik** [comment]
The orange theme is great, indeed, saved it too.

BTW, why there are so much cross in your favourites?
Did you know that if you add tag to favourites from some image preview page, then this image will be icon of this tag in your favourites.

See? Much better!
![image](https://cloud.githubusercontent.com/assets/22294259/24832684/c31fc300-1cbd-11e7-8784-e9956c055d18.png)

for @Bionus btw, this imageless favourites reminds me about https://github.com/Bionus/imgbrd-grabber/issues/779 issue, where I suggested you a way to add thumbnails to favourites, when you adding it from search field.

**Comment by TheGho7t** [comment]
Okay now that WORKED HOWEVER, and I'm really sorry LOL, but I wanted the Favorites text on the left side to be orange. Which actually, that helped by the way a lot. 

Uh do you mean clicking a photo, right click the tag and hit "add to favorites" on said photo, Petrik? Honestly I don't mind as I don't really look at that favorites spot that much, but that's a neat little thing if that's the case.

This spot:

![2017-04-08 18_02_08-grabber](https://cloud.githubusercontent.com/assets/26805531/24832785/804fa8ac-1c85-11e7-87e5-bcc1f8ae4d68.png)

**Comment by Bionus** [comment]
It's not possible for the moment, as these are HTML links, and they are not stylable by Qt stylesheets (only widgets are).

**Comment by barryanders** [comment]
> It's not possible for the moment, as these are HTML links, and they are not stylable by Qt stylesheets (only widgets are).

Ah, that explains why not all of my styles were working. Can you make heads or tails of that adwaita theme or is it something else?

**Comment by TheGho7t** [comment]
Aw darn alright, thanks for letting me know and for the help!

**Comment by MasterPetrik** [comment]
@Bionus the question has been answered, I guess. Should you close the issue?

**Comment by BarryMode** [comment]
Wow, this feels recent but it was 5 months ago.
