### ISSUE TITLE
Progressive merged results processing enhancement

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#877]
## Problem: Too long waiting until loading results
Current main problem here. But I can suggest a solution - progressive loading search results.

Current way of working:
Loading all sources info and processing all of it and only then showing results.
We all understand, that this isn't optimal. User don't like to wait so many time, espessially when non-merged results are loading much faster.

Progressive results loading.
here and below "show" word will mean displaying images from search results in search results grid.  

1. user make a search request for merged results on bunch of sites.
2. grabber sends GET requests for every site from the list.
3. after getting FIRST answer from first ansvered site, grabber Immediately show images from results page of this site in results grid, but do it progressively. For example, first answer was from gelbooru, grabber got info about 20 images from 1 page of results. Grabber shows first image and saves its md5 to search md5 list(empty at start), then shows other 20 images, one by one, check every next image with md5 list before showing this image. If this image have different md5 compare to md5 list, then show this image and add it's md5 in list too. If same md5 exist in list already, then NOT show this image and go to the next. 
4. After adding to results grid images from first ansvered source, Grabber may already get some answers from other sources. Would be logical to make a md5 list of images from these sources in same time, when you shows first source images. Then when showing of first source images will be complete, grabber could progressively compare md5 from next source with md5 already existed in the list, one by one for every image from this source, check every next image with md5 list before showing this image. If this image have different md5 compare to md5 list, then show this image and add it's md5 in list too. If same md5 exist in list already, then NOT show this image and go to the next. 
5. Do the same with all remaining sources.

This way of displaying results have a BIG advantage compare with current way: almost Immediately after pressing "search" button user get first unique results, and he can watch them, without waiting of loading remaining results. New images will be added to the grid progressively, so  no need to wait. 
Yes, I know that processing sources one by one will require a bit much time for all results loading compare to current way, but user will don't care about it if he will already watch images from results.

  

BTW, there is small problem with progress bar too:
![image](https://cloud.githubusercontent.com/assets/22294259/24824987/69ab0040-1c1e-11e7-995e-be6c94867cfc.png)
Every time progress quickly goes to 70-80% and then almost stops for a couple of seconds. Of course I'm understand why this happends. But I'm sure that you can improve this part too.

**Comment by Bionus** [comment]
The issue with this suggestion is the way images are displayed on the results list of Grabber. They're shown on a square grid. And to know the size of the grid, you have to know how many images you will show:

* 25 images -> 5x5
* 50 images -> 8x7
* 100 images -> 10x10

That's the main point that make this issue more complicated than it seems. To this there's two main options I had considered at the time I thought about this issue:

* Using a flow layout instead of a grid
✔️ quite fast to implement (https://doc.qt.io/qt-5/qtwidgets-layouts-flowlayout-example.html)
❌ changes the way images are displayed: they'll be left aligned on the left size, leaving possible blank space on the right side
❌ hard to put breakpoints on when the images should resize instead of adding a line break
* Have an automatically resizing grid, that whenever new images arrive or the window is resized, changes its number of columns accordingly
✔ 100% retro-compatible with the current grid display
❌ not obvious to implement (risk of added bugs)
❌ forces to move images around when an event occurs

I'll try to give a try to the automatically resizing grid, I'm not a big fan of the flow layout.

> BTW, there is small problem with progress bar too:
> ![](https://cloud.githubusercontent.com/assets/22294259/24824987/69ab0040-1c1e-11e7-995e-be6c94867cfc.png)
> Every time progress quickly goes to 70-80% and then almost stops for a couple of seconds. Of course I'm understand why this happends. But I'm sure that you can improve this part too.

Is that the progress bar at the bottom of the window? If so, it simply show the number of sources loading. So if you have 5 sources, 4 are very fast and 1 slow, it will quickly go to 80%, then wait until the last source finished loading and then finally 100%.

**Comment by MasterPetrik** [comment]
You seem to be reading my thoughts.
I almost finished sapareted feature request right about grid modes. Wait a coulpe of minutes and I'l post it.

> If so, it simply show the number of sources loading. 

Got it. no more questions

**Comment by MasterPetrik** [comment]
> The issue with this suggestion is the way images are displayed on the results list of Grabber. They're shown on a square grid. And to know the size of the grid, you have to know how many images you will show:
> 
> 25 images -> 5x5
> 50 images -> 8x7
> 100 images -> 10x10

If image size will be constant(yeah, 150x150), then you will easyly fill all rows progressively. And if you don't know final amount of images... 
wouldn't be logical to create dynamic array of merged results images. 
and while filling it with original processed images also add them to the grid. Then if you will resize Grabber window, you will easyly reorganize rows with new amount of images in a row just by geting info from current images array and refill rows. You will need just to check grid area width sometimes and change amount of images in a row.
so for example, changing amount of rows and number of images in a row depending of window size: 
for small window    20 images - 4x5
for middle window 20 images - 5x5
for big window       20 images - 8x3
as it happends in browser window with search results when you resinzing window.
So you won't need to predict images amount in merged results mode anymore!

> :x: changes the way images are displayed: they'll be left aligned on the left size, leaving possible blank space on the right side

I see. But I guess there are easy way to handle it, here is the example: 

X varible: your results area width is 1044px
constant: images width is 150+2 px border = 154 px per image
constant: space between images is 16 px (8 to the left and 8 to the right)

so before filling results area with grid, you are just do follow calculations:
1044 div 170(154+16) = 6 - it will be 6 images rows.
then 1044 mod 170 = 24 px - free space, that we need to handle

**Now you have 2 ways:**

1. centering grid area
then 24 div 2 = 12 px - we adding it at the left and ringht side of the grid, as result sentering all grid.
And final grid plan will be:
{12-[8-[2-[150]-2]-8]-[8-[2-[150]-2]-8]-[8-[2-[150]-2]-8]-[8-[2-[150]-2]-8]-[8-[2-[150]-2]-8]-[8-[2-[150]-2]-8]-12}=1044 px

2. incrising space between images
then 24 div (6-1) = 4 px - amount of px that need to be added between images
in this case, 24 mod 5 = 4 px - will be blank space at the right side if list, in any case in will be not very big number, not more then 20 px, I guess, so user will not notise this.
And final grid plan will be:
{[8-[2-[150]-2]-8]-4-[8-[2-[150]-2]-8]-4-[8-[2-[150]-2]-8]-4-[8-[2-[150]-2]-8]-4-[8-[2-[150]-2]-8]-4-[8-[2-[150]-2]-8]-4}=1044 px
If length of free space < images in row number, then just add all this space to the right of grid. Because it will be unnoticable for user anyway(for example for area resolution 1920p, max right to grid space addition can't be more then 10 pixels anyway.  

So you even don't know amount of images in search results, but you already made a grid for it!

after any resizing of window you just repeating this procedure and refill grid again. Sounds easy, isn't it?
