### ISSUE TITLE
Font size setting for tags lists

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#879]
BTW, did Bionus made font for tags lists in grabber a little bigger? I liked the old size.
Is there any setting for tag font size? Maybe you need to add it, It can be a part of preview window customisation settings.

**The new one:**
![2017-04-08_220635 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24832464/d468816e-1cb9-11e7-909b-ed376113b687.png)
**The old one:**
![2017-02-25_160813 win7 mastercore 8](https://cloud.githubusercontent.com/assets/22294259/24832466/d7cbbd30-1cb9-11e7-9d5c-870e3ea54945.png)

**Comment by Bionus** [comment]
I definitely didn't change that. Mine look like this, which match your "old one" screenshot:

![image](https://cloud.githubusercontent.com/assets/882719/24832613/8efb948c-1cb3-11e7-9420-eca75c3f836d.png)

It seems like you changed the font or the font size in your tag font settings:

![image](https://cloud.githubusercontent.com/assets/882719/24832633/f88b7c46-1cb3-11e7-9f6d-5371d0e7cd34.png)

**Comment by MasterPetrik** [comment]
well, I never did not notice font settings buttons before -___-
Thanks, I fixed the size.

> It seems like you changed the font or the font size in your tag font settings

But I'm never tuched font settings buttons before, but font size somehow changed from 8 to 10!
Could switching CSS themes cause this?

**Comment by Bionus** [comment]
> But I'm never tuched font settings buttons before, but font size somehow changed from 8 to 10!
Could switching CSS themes cause this?

No idea, maybe the theme changes the font size, but somehow I doubt it. No idea here. I know that moving the `settings.ini` from another computer can totally cause this though. Or changing Windows theme.
