### ISSUE TITLE
Blocking Direct Links

### ISSUE THREAD

**Issue by PronMaster** [Bionus/imgbrd-grabber#880]
I run a adult and non adult version of my site but people can still direct link videos on my site though my filter of blocking adult videos from the main part of the site how can I block this? Example would be www.samplesite.com/image/55644 how can I block direct links or redirect them back to the main image page when they try and go to the direct link?

**Comment by MasterPetrik** [comment]
Hmm... how is this question related to Grabber?

**Comment by Bionus** [comment]
Closing because I don't see how this is related to the program.
Feel free to comment and give more details.
