### ISSUE TITLE
Fixed grid mode

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#883]
# WARNING~ VERY LONG POST!

## First of all. Take a look at current search results grid:

![2017-04-11_031839 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24924191/9b41608c-1efc-11e7-9403-7edd87abda81.png)

Different number of images in a row and very different thumbnails size for some sites. Moreover, all images in a row are center-aligned. This grid system is svery different compare to classic fixed system. 

The current system is causing some problems too:

- Different number of images in a row make more dificult to compare image rows from different sources. 
- Results from some sources are smaller then the others, and as result, less visible to view.
- Results from some sources are much bigger then the others,  
- Too different space between images from different sources.
- Not everyone prefers center-alignment.
- And finally, current mode causing situations like this:

![2017-04-03_043451 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24926505/789eac6c-1f04-11e7-9139-52d10ae1a309.png)

Fixed grid mode can solve all these problems. 

- It's fully predictable(main advantage)
- You can easy compare results from different sources, because all rows has the same number of images and all images has the same sizes. 
- Left-alignment is a classic way of showing results almost on every boorus

## Here is comparing two modes with same number of results from same sites:  

![hrey](https://cloud.githubusercontent.com/assets/22294259/24924468/9429f04c-1efd-11e7-829e-25ebe03e7bc8.png)

So I suggest you to add Fixed grid mode to grabber.
## Fixed grid mode means following changes:

1. All images in a rows must me aligned to the left.
2. All thumbnails has the same fixed size(150x150 is the most common one, but you can make it changable). All thumbnails with different sizes must be auto resized to this size in results grid.
3. All thumbnails in results for every source must follow the same rules: same space between images, sam images number in the rows. Number of images in the row must can be changed by resizing window. Good example of it is Sankaku site, It can show 20 images page as 5 images in a row for small window and as 8 images in a row for wide window.  

### wide window

![image](https://cloud.githubusercontent.com/assets/22294259/24927016/34d85e72-1f06-11e7-99ee-8afd8e3fdbdb.png)

### small window

![image](https://cloud.githubusercontent.com/assets/22294259/24927060/4a994eba-1f06-11e7-8656-06987291ebe6.png)

# Merged results mode
And one more thing. Fixed grid mode is perfect fits for the merged results mode, besause it shows different images from different sites in one grid, so they anyway need to follow same rules. And using Fixed grid mode for that will solwe all problems connected to displaying merged results. And it will perfectly work with Progressive merged results processing, suggested erlier.

**And once again, for guys, who think, that I suggest to replace current grid with fixed grid, I'm repeat:
I'M SUGGEST AN ADDITIONAL MODE, I DON'T SUGGEST ANY CHANGES IN CURRENT GRID MODE HERE.**

**Comment by barryanders** [comment]
I don't really have a preference, however, I'll just throw this in there anyway.

Let's say you were going to go with a fixed grid. If you don't want to force cropping at 150x150, you can always scale the image to be 150px high if it's tall or 150px wide if it's fat and then have a bounding box that remains 150x150 to keep the grid on track.

**Comment by Bionus** [comment]
1. Wouldn't that mode cause a lot of blank space between images, since most of them are not perfectly square?
2. Wouldn't that make sense for this to be the default behavior when using scrollable results ? Since you're already agreeing to scroll, that doesn't really make sense to have 10x10 images instead of 5x20 vertically (5 = window width / column width).

> Let's say you were going to go with a fixed grid. If you don't want to force cropping at 150x150, you can always scale the image to be 150px high if it's tall or 150px wide if it's fat and then have a bounding box that remains 150x150 to keep the grid on track.

That could fix the white space problem, at the cost of cropping the image. However, most images are already bounded at 150x150 pixels server-side, so that would imply to scale them up to then crop them.

> And it will perfectly work with Progressive merged results processing, suggested erlier.

That one's already on its way to fixed land. :smile:

*PS: the grid items are already left aligned, with their contents centered. So that'd be more:*

![image](https://cloud.githubusercontent.com/assets/882719/24928040/484d68f8-1f01-11e7-8f99-a0eb5b02dd4b.png)

**Comment by MasterPetrik** [comment]
> however, I'll just throw this in there anyway.

Not sure that I can translete it right. I just don't get it. :(

> That could fix the white space problem, at the cost of cropping the image. However, most images are already bounded at 150x150 pixels server-side, so that would imply to scale them up to then crop them

Cropping? What? I never even mentioned that, I'm telling about rescaling, without cutting something. Oh come on! Just look at any booru results grid, all images rescaled to 150x150, and there are no users, who have problems with it. So use EXACTLY same grid system, which already uses on almost all boorus will be very native for users(espesially for new users), than current system. Thumbnails from zerochan and yande.re can be easyly rescaled to 150x150 box.

> Wouldn't that mode cause a lot of blank space between images, since most of them are not perfectly square?

Well, look at any classic booru: is there too much blank space between images? I think, not. But in current mode there are TOOOOO MUCH SPACE between images sometimes, so obviously here fixed grid mode is prefered.

![2017-04-03_043451 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24928657/d548bf8c-1f0b-11e7-9cd5-fda6f92d437e.png)
![2017-04-11_230919 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24928718/1b711be4-1f0c-11e7-8c5a-6d65b9cb4e2b.png)

> Wouldn't that make sense for this to be the default behavior when using scrollable results ? Since you're already agreeing to scroll, that doesn't really make sense to have 10x10 images instead of 5x20 vertically (5 = window width / column width).

I don't think, that I fully understood you. You asking about using fixed grid mode as default way of showing results? I don't know here. Many Grabber users like current system. But I can suggest you an intresting solution. You can make an preferring mode settings in first-grabber-setting dialog, and set fixed grid mode as default mode there. Then new users, who expecting to see booru-like grid will see in grabber common for them view, and old Grabber users, who accustomed to current mode will notice nothing and will continue use current mode, but will can change it anytime manyally in settings. 


> PS: the grid items are already left aligned, with their contents centered. So that'd be more:

PS: Nice paint work, dude) You showed it more correct. And my IMHO that this way of filling rows is the ugliest way ever. Just an opinion)

**Comment by MasterPetrik** [comment]
And one more important thing! 
In fixed grid mode little  free space between the images should not be clickable, as it done on booru sites:

![2017-04-11_222906 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24931192/139dffc8-1f15-11e7-9e4a-6d5cc1757366.png)

**Comment by barryanders** [comment]
I think my description was misunderstood most likely due to language the barrier. I know you didn't mention cropping, I was just describing the alternative to cropping. What I described above was exactly what is pictured in the post above made by @Masterpetrik and ultimately I don't care how it's handled like I said before. Maybe you could allow the user to decide how they want the grid to function.

**Comment by barryanders** [comment]
Your image regarding clickable areas has the fixed grid like how I described it with one difference. The wider images are aligned to top (which I actually like better). That's a perfect example, and maybe the user should be able to decide how they want the display to be in preferences.

**Comment by MasterPetrik** [comment]
Btw, about fixed grid mode constants.
I'm analized booru sites and found their grid structure very good
I suggest you to make fixed grid mode with following constants, to make grid more booru-like:
constants: 
images width is 150 px
frame area is 2 px (1 to the left and 1 to the right, 1 to the bottom 1 to the top)
space between images in row is 16 px (8 to the left and 8 to the right) but i guess that this is too much.
I guess is 10 px (5 to the left and 5 to the right) will be enough.
so every image will fill 170px = [8-[2-[150]-2]-8]
or 164px = [5-[2-[150]-2]-5]

frame area - 2px width invisible border around any booru image. It can be colored in yellow, green or another color. for example, if booru has 2 same images, but one of them is PNG and the other is JPG then they will have this border and it will be colored different. So it can be useful in grabber too.




> That's a perfect example

Because of it, all boorus uses this variant)

> maybe the user should be able to decide how they want the display to be in the program options.

I thought, I wrote clear about it in first post:

> **And once again, for guys, who think, that I suggest to replace current grid with fixed grid, I'm repeat:
> I'M SUGGEST AN ADDITIONAL MODE, I DON'T SUGGEST ANY CHANGES IN CURRENT GRID MODE HERE.**

**Comment by brodycas3** [comment]
I hate having options, after a while there are too many to keep track of.

**Comment by barryanders** [comment]
@brodycas3 I understand disliking a lot of options if they cause significant problems or if the program won't work without tediously setting everything just right. Also if the menus are very cluttered I wouldn't like it either. I don't think Grabber has any of these problems though. It works out of the box. The only setting you really have to set is the output directory and the source.

Customization is always a plus in my opinion so long as it's structured well. I'm guessing this one would end up in the interface category which has a lot of things, but you don't have to touch any of them to use the program.

**Comment by Bionus** [comment]
> Cropping? What? I never even mentioned that, I'm telling about rescaling, without cutting something. Oh come on! Just look at any booru results grid, all images rescaled to 150x150, and there are no users, who have problems with it. So use EXACTLY same grid system, which already uses on almost all boorus will be very native for users(espesially for new users), than current system. Thumbnails from zerochan and yande.re can be easyly rescaled to 150x150 box.

I was answering barryanders.

> Well, look at any classic booru: is there too much blank space between images? I think, not. But in current mode there are TOOOOO MUCH SPACE between images sometimes, so obviously here fixed grid mode is prefered.
>
> ![2017-04-03_043451 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24928657/d548bf8c-1f0b-11e7-9cd5-fda6f92d437e.png)
>
> ![2017-04-11_230919 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24928718/1b711be4-1f0c-11e7-8c5a-6d65b9cb4e2b.png)

My point was that there are other options to fix the spacing problem, such as capping the height and width of images, without always *forcing* it.

> I don't think, that I fully understood you. You asking about using fixed grid mode as default way of showing results? I don't know here. Many Grabber users like current system.

I'm not sure that many users like the current system. It just so happens that most sources return 20 images per page, so it makes sense to show them on a 5x4 grid. I'm not that sure that users who use zerochan wouldn't prefer having a 5x20 grid rather than the current 10x10 grid. If you already have your results scrollable, it does not make sense to have many images on a single line (current layout). Since you already agree to scroll, might as well have all images clearly visible.

> And my IMHO that this way of filling rows is the ugliest way ever. Just an opinion

That's also the most basic way. If you make a grid with two images, the total width will be divided by 2, with each image centered inside their cell.

>  In fixed grid mode little free space between the images should not be clickable, as it done on booru sites:

That's already the case (as said in issue #884.

> Your image regarding clickable areas has the fixed grid like how I described it with one difference. The wider images are aligned to top (which I actually like better). That's a perfect example, and maybe the user should be able to decide how they want the display to be in the program options.

Noted, I'll add alignment options when I do it then (same as the ones for the image window).

> I hate having options, after a while there are too many to keep track of.

Me too, that's why I'm trying to have as few of them as possible (unlike a few years back when I kept adding dozens of them), but sometimes that's simply unavoidable.

**Comment by MasterPetrik** [comment]
> I hate having options, after a while there are too many to keep track of.

Hmm... you answered this on my post with description of grid mode constants?
Anyway you are wrong here.
Because there are only two ways of building your GUI:

1. Many options. Many functions. 
If you making really powerful programm with many functions, you obviously will have many different options. This is software for expiriensed users, who really need all these functional. They can easyly set up software for their needs. This way uses most of specific software, anв almost all opensourse projects(for example look at some other programms with similar functional, Hidrus Network for example, they all have a lot of options too, and this is normal).

2. Very simple options, poor functional.
This way uses software developers, who develpe software for inexpiriensed users. so their options doesn't contain specific functions, there are no customisation, and list of options is very poor and simple. For example, you can compare options from Paint(very poor and simple) and for example any spesific soft, like Photoshop(many options, many functions). That happens, because inexpiriensed users doesn't use specific functions. And this way is good only for inexpiriensed users.

But! Grabber doesn't have problems with too many options. As @barryanders said, even without visiting settings window inexpiriensed user can easyly use grabber. And experiensed users can use it rich customisation, naming, and DB-connecting potentials. If you are not need some options, there is very selfish to suggest remove some of them. If you don't need it, just don't use it, very easy, isn't it?

Moreover, clever customisation is always a plus for any user-friendly programm. Moreover, rich customisation options is the one of main killer features of grabber. And this is right way of thinking.

**Comment by MasterPetrik** [comment]
> That's already the case (as said in issue #884).

Nope. Here it is a part of describing fixed grid mode. There it is suggestion to flow grid mode, I'm specially separated it. Because there are different implementation of it. Here it's just a obvious 150x150 clickable squares, and for flow grid clickable size and form is a debatable question.

> Me too, that's why I'm trying to have as few of them as possible 

Then you can remove unscrollable results mode, nobody use it anyway, you can even ask anyone, or make a voting, heh. Because anyway all its advantages have scrollable mode.


> YOU: Wouldn't that mode cause a lot of blank space between images, since most of them are not perfectly square?

> ME: Well, look at any classic booru: is there too much blank space between images? I think, not. But in current mode there are TOOOOO MUCH SPACE between images sometimes.

> YOU: My point was that these are other options to fix the spacing problem, such as capping the height and width of images, without always forcing it.

Don't get me wrong, by there examples I don't critisize flow grid mode, or suggest you to do something with blank space in it. I think this is a part of flow grid conception) I'm only answered you to part, where you worried about too much blank space in fixed grid mode. I just showed examples of even bigger blank spaces areas in current mode, showing you that this woulsn't be a problem. Just an answer. Nothing more.

**Comment by Bionus** [comment]
Some tweaks to do, but the basics are here:

![image](https://cloud.githubusercontent.com/assets/882719/25020082/6045f032-208d-11e7-9288-8e43f012773f.png)

**Comment by MasterPetrik** [comment]
I know that this isn't topic of this thread, but I think, if you already decided to improve results grids in 5.2.5, will be good to do also this:

I guess that not very convinient to each time open preview window and only then revers search.
So it will be very useful to add this rightclick menu to all results in results grid window too.

that is what I mean:
![2017-01-22_155621 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22185587/9248dc08-e0f9-11e6-8236-8e2ca5e3ec0d.png)
connected with https://github.com/Bionus/imgbrd-grabber/issues/754

**Comment by Bionus** [comment]
> Looks good. Can you store "min. space between images in a row" value somewhere in options ini file, or even make an option is settings?

It's already been there for a while:

![image](https://cloud.githubusercontent.com/assets/882719/25024857/0557fdf6-20a0-11e7-8a8d-f06663a1b12b.png)

Note that "margin" may be misleading, to clarify it's the space between two columns/rows.

> I guess that not very convinient to each time open preview window and only then revers search.
> So it will be very useful to add this rightclick menu to all results in results grid window too.

As you said it's already in issue #754, I just haven't decided whether and how to do it.
I don't forget open issues, don't worry. I often go back to "old" issues to check their state, and I have a prioritized backlog of issues to solve. :smile:

**Comment by barryanders** [comment]
Looks great.
