### ISSUE TITLE
imgbrd-grabber multiple instances intended? 

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#885]
I'd like to download more things with this at the same time, so wanted to ask if multiple instances are possible. I know you can just start the program twice, but I ask just in case I don't want to fuck something up. I already tried to install it on another hard drive, but it doesn't let me choose a folder, I can only update it.

**Comment by Bionus** [comment]
There shouldn't be any problem for downloading.

However, note that when Grabber closes, it saves its settings, the opened tabs, favorites, etc. So if you change any settings, it's the last closed Grabber that will save, others will get overwritten.

If you want to be sure, you can always make Grabber portable. See here:
https://github.com/Bionus/imgbrd-grabber/wiki/PortableVersion
