### ISSUE TITLE
Can't seem to figure out how to download missing images

### ISSUE THREAD

**Issue by markuscostner** [Bionus/imgbrd-grabber#887]
### What steps will reproduce the problem?
Tried batch downloading an entire booru that I added, apparently it runs on gelbooru 1.0, the booru says it has 27000+ images but my downloads finished at only 26k+. More than 1000+ images not downloaded.

### What is the expected behavior? What do you get instead?
Expected behavior: Download majority of all 27000+ images total currently in the booru when I leave the tag space empty on batch downloading.

What I get: Apparently grabber didn't download the child posts and only parent images. You know, the ones that say "This post has child posts. Child posts are often subsequent pages of a doujinshi, or minor variations of the parent post.".

### How often does this problem occur?
This is my first time using grabber so I'm sorry if I'm reporting this wrong. I don't know how or what to do about this.

### What version of the program are you using? On what operating system?
I'm using Grabber 5.2.4 on Windows 8.1.

### Please provide any additional information below
I can selectively download child posts of certain parent images if I enter their link but I can only do that for the parent images I know about. I want to be able to download ALL parent/child posts from whatever booru I'm archiving but I don't know what specific parameters to enter to download hidden images like that. I was expecting leaving the tag box empty so that it downloads everything but I guess I haven't quite figured this out. What do I do?

**Comment by Bionus** [comment]
Grabber currently does not support downloading an image's children images. There's no way around except making a complex update to Grabber. There's been a WIP to add support to gallery-images but it's not ready yet.

**Comment by markuscostner** [comment]
damn... that's the only thing grabber's missing. Thanks for the reply anyway. Guess it's back to figuring out Bulk Image Downloader for me.
