### ISSUE TITLE
Error during Install 

### ISSUE THREAD

**Issue by Alkatrax** [Bionus/imgbrd-grabber#888]
When I try to install THE GRABBER He tells me that I have to install vc_redist.x86, but I already installed and after starting the download appears to me this screen 

![cattura](https://cloud.githubusercontent.com/assets/27574704/25065979/2409a116-221a-11e7-82cb-8e068fac5e66.PNG)

**Comment by MasterPetrik** [comment]
Did you tried reinstall Microsoft Visual C++ 2015?

**Comment by barryanders** [comment]
Not actually a problem with Grabber, just a dependency issue. This is what you want: https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by Bionus** [comment]
The next version includes an updated dependency installer version that fixes this issue.
