### ISSUE TITLE
Installation problem : Drive or UNC ... not accessible

### ISSUE THREAD

**Issue by AJKproductions** [Bionus/imgbrd-grabber#889]
### What steps will reproduce the problem?
The problem occurs when i try and install the software, for the first time. I might want to add that it does not prompt me for a installation location. 
The exact dialog is " The Drive or UNC share you selected does not exist or is not accessible. Please select another ", then it closes. 

### What version of the program are you using? On what operating system?
I am using version  5.2.4. and here is my system specs

![capture2](https://cloud.githubusercontent.com/assets/6739892/25084148/f066347a-2352-11e7-8b2a-cd748e222a44.PNG)

### Here is the error
![capture](https://cloud.githubusercontent.com/assets/6739892/25084094/addf4df8-2352-11e7-80d1-881e522709bc.PNG)

**Comment by Bionus** [comment]
Is your system missing the "Program Files" folder for some reason? Or did you customized its location in some way?

Running the installer with the `/DIR="x:\dirname"` command-line argument should bypass this error by forcing the install directory you want. By default it's `%ProgramFiles%/Grabber` I believe, but it doesn't seem to work on your system. :smile:

**Comment by AJKproductions** [comment]
The "Program Files" folder, on my C drive, is present and i have installed quite a lot of programs into it, so it's not that. However I did try passing the arguments to the program, which made it install properly. So it is now fixed. It might be work mentioning that I installed it somewhere else, rather than the "Program Files" folder.

**Comment by Bionus** [comment]
I'll be closing the issue then (there's nothing I can do on my end, if there's a bug it's on InnoSetup's side).

For others that may have the same issue:
* Make sure there is enough space on your hard drive
* Ensure the installer has write access to your drive (you can give it admin rights to be sure)
* You must have the "Local" profiles enabled on that computer
* Uninstall Grabber if it's already there

If nothing works, running the installer with the /DIR="x:\dirname" command-line argument should bypass this error by forcing the install directory you want.

**Comment by CalosChen** [comment]
> Is your system missing the "Program Files" folder for some reason? Or did you customized its location in some way?
> 
> Running the installer with the `/DIR="x:\dirname"` ([doc](http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline)) command-line argument should bypass this error by forcing the install directory you want. By default it's `%ProgramFiles%/Grabber` I believe, but it doesn't seem to work on your system. 😄

Thank you, mine is working now, this is the solution!
