### ISSUE TITLE
Tags for Sankaku Complex are (mostly) in Japanese

### ISSUE THREAD

**Issue by Nogooduser** [Bionus/imgbrd-grabber#891]
### What steps will reproduce the problem?
I don't recall it ever being like this (or maybe I hadn't noticed it before, not sure) and only noticed it after the most recent update.

I believe it might have something to do with my non-Unicode settings being set to Japanese, so perhaps that is the root cause.

### What is the expected behavior? What do you get instead?
The tags should be displaying in English like they do in other sources ([example from Gelbooru](http://image.prntscr.com/image/a687459386704dabbc76ab768db95480.png)) but instead they show up in Japanese ([example from Sankaku Complex](http://image.prntscr.com/image/0fcd36778d5e43809494d5ca0600411d.png))

On the Sankaku Complex Website the tags display fine in English as well, it's only in Grabber that they turn into Japanese.
Note: On Internet Explorer, the issue persists, but on Chrome or Firefox it doesn't. Coincidentally, Internet Explorer is also in Japanese in a bunch of other areas, again due to my non-Unicode settings.

### How often does this problem occur?
Whenever I'm browsing anything from Sankaku Complex.

### What version of the program are you using? On what operating system?
Version 5.2.4 on Windows 7.

### Please provide any additional information below
As I mentioned above, I have my non-Unicode language set to Japanese. This is because I often run software that requires such settings to be enabled. I know this setting can often interfere with other programs (how many drivers have I had to install in Japanese by now...), hence why I'm mentioning it.
The thing is, if it was really interfering with Grabber, I would expect ALL tags to be in Japanese, but only Sankaku Complex is being affected.
However, I have the Grabber language set to English, which theoretically should correct this problem, but it doesn't, so I'm not sure what to do.

If this is a known bug then I apologize, but I didn't see anyone bring this issue up so far (probably because most people don't have their non-Unicode set to Japanese).

I don't really bring this up as a bug that's preventing me from enjoying the app by the way, since I can read Japanese just fine myself, but if people's non-Unicode settings are interfering with Sankaku Complex in Grabber then it might be relevant to look into it.

Thanks for the attention.

**Comment by Bionus** [comment]
It comes from your system settings indeed, as you guessed.

The solution is to set the `Accept-Language` header to `en-US,en;q=0.8` in the source settings:

![image](https://cloud.githubusercontent.com/assets/882719/26269290/db259802-3cf3-11e7-833c-fb05800dc72f.png)

This will be done by default in next version. :smile:
