### ISSUE TITLE
Request, Add this theme as a built in dark mode.

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#892]
I was thinking that you could add [this theme](https://github.com/ColinDuquesnoy/QDarkStyleSheet) as a built in dark mode for people to use. The problem with just taking the CSS it that it's missing a few icons and I'm sure this would save people from having to manually create a dark mode theme.

![image](https://cloud.githubusercontent.com/assets/19770864/25134327/47582e4e-241d-11e7-9c33-48db310382f9.png)
![image](https://cloud.githubusercontent.com/assets/19770864/25134360/5a808854-241d-11e7-9780-f964f63e083f.png)

**Comment by Bionus** [comment]
I'm not a big fan of the theme myself, but there's not that many free Qt CSS around, so I could give it a try, as well as allowing to add resources to themes (which seem to be the issue here).

**Comment by brodycas3** [comment]
Sounds great. <3

**Comment by brodycas3** [comment]
@Bionus How is this coming along?

**Comment by brodycas3** [comment]
Cant wait

**Comment by brodycas3** [comment]
@Bionus Will this possibly be in the v5.3.0 release?

**Comment by Bionus** [comment]
Depends on the level of complexity required to add the icons without changing Grabber's build steps.
