### ISSUE TITLE
5.2.4 doesn't load images and doesn't create new folders on NAS through local network.

### ISSUE THREAD

**Issue by olpas** [Bionus/imgbrd-grabber#894]
### What steps will reproduce the problem?
1) Install 5.2.4 in 7/8/10 connected to NAS (as example \\\nas4free)
2) Downloads -> Add new Group with destination folder like \\\nas4free\files\images\sometag (new folder) and try download it.
3) Try find this folder on NAS after downloading - no folder, no images.
4) Try create this folder manualy and download images again - no images.

### What is the expected behavior? What do you get instead?
Should create new folder, should download images to existed folders on NAS.
5.2.2 works fine with any NAS and PC in local network, no problems.

### How often does this problem occur?
5.2.4 (and possibly 5.2.3 bug), always. 

5.2.2 works fine with any NAS and PC in local network, no problems.

### What version of the program are you using? On what operating system?
5.2.4, Win7 and Win10.

**Comment by Bionus** [comment]
Is there any error message in the log or anything special that happens except for the images/folders not saving?

**Comment by olpas** [comment]
No, it just usual "-number- files donwloaded sucsessful" message after downloading, 0 ignored, skipped, not founded e.t.c, no error messages, same to 5.2.2 message window, but 5.2.4 actually does nothing on NAS conected to PC or my laptops, it can save files only on PC storage.
I'm using 5.2.2 now, it works with LAN and NAS fine.

**Comment by Bionus** [comment]
Responsible commit: e03665565c6942f2524464cb978cb568be216ab9

**Comment by olpas** [comment]
Got new infromation abou this bug - V,5.2.3 and 5.2.4 just create new folder on C with same name as C:\nas4free\files\images\somefoldername and download all files to it, it uses network path \\nas4free\files\images\somefoldername as PC storage path.
