### ISSUE TITLE
Not grabbing all

### ISSUE THREAD

**Issue by Wenn12** [Bionus/imgbrd-grabber#895]
### What steps will reproduce the problem?
Get tags for anything with more than 500 images ie tag "hashimoto_takashi"
click get all
download

### What is the expected behavior? What do you get instead?
Download a full set of images only get 1st 500
When you try to look at all the pages It shows nothing after page 25

### How often does this problem occur?
When ever i try to download more then 500 images

### What version of the program are you using? On what operating system?
4.6.0 on windows 10

**Comment by Bionus** [comment]
Which website does this happen on?
Plus is there any reason you're using a 9 month-old version?

**Comment by MasterPetrik** [comment]
>  is there any reason you're using a 9 month-old version?

True.
I recommend you try to download v5.1.1, because in newer versions there are still some errors with new batch downloading algorithm
https://github.com/Bionus/imgbrd-grabber/releases/tag/v5.1.1

**Comment by Wenn12** [comment]
Yeah about that I just found the new version of your program I was only ever able to find the one I was using when I searched for this program. I haven't tried to use the lastest one with more than 500 images yet but I've noticed that this one doesnt put the photos in the correct spot for example If i have it set to go to "F:\Tag\Dragon" half will end up in "F:\Tag" and the other half will go into "F:\Tag\Dragon" Im sorry for my poor grammer and spelling it is really late for me
