### ISSUE TITLE
Is there a way to make Grabber download images that already exist in different folders?

### ISSUE THREAD

**Issue by the612toon** [Bionus/imgbrd-grabber#896]
If I have a file in F:\Images\RinKagamine and am downloading images to F:\Images\HatsuneMiku it will ignore the files that are in F:\Images\RinKagamine.

Is there a way to make Grabber only ignore images if it exists in the destination folder?

**Comment by sergalbutt** [comment]
`Tools > Options (Ctrl+P) > Save`
Change the option in the drop-down box beside *If a file already exists* to ***Save***

**Comment by the612toon** [comment]
Grabber will ignore images that already exist in the same folder then?

**Comment by Bionus** [comment]
Yes, those will still be ignored, as long as they have exactly the same filename (they won't get overwritten).
That setting only applies for the MD5 list which prevents to have duplicates in different folders.
