### ISSUE TITLE
Request: Generate custom filenames for 'save as' dialogue

### ISSUE THREAD

**Issue by Synchestra** [Bionus/imgbrd-grabber#897]
I think it would be pretty convenient if, when opening single images and using the 'save as' function, Grabber would automatically generate your custom filename into the 'file name' field. This would be much faster than setting the destination folder, selecting one or two images, and using 'get selected', or typing a custom name manually.

Basically, instead of generating this:
![untitled1](https://cloud.githubusercontent.com/assets/16811614/25399401/ee2e035a-29b4-11e7-8ca4-31f0938e5f22.png)

It could generate this:
![untitled2](https://cloud.githubusercontent.com/assets/16811614/25399400/ee29b78c-29b4-11e7-9e27-c926b45616f0.png)

Would this be possible?

**Comment by barryanders** [comment]
Excellent idea.

**Comment by Bionus** [comment]
I see no problem or difficulty in implementing that, so why not.

But why do you use "Save as" instead of directly "Save"? It sounds like there is another underlying issue here that forces you to change the folder you save images to every time.

**Comment by barryanders** [comment]
Ok, so I'm making an attempt to understand the source. Does this do this? I haven't tested it, I just wanted to know if I was on the right track here.

gui->src->viewer>zoomwindow.cpp

As is:
```
QString filename = m_image->fileUrl().toString().section('/', -1);
```

Updated:
```
QString filename = m_settings->value("Save/filename").toString();
```

**Comment by Synchestra** [comment]
I use "save as" because I find it faster to do it that way than to change the destination folder on the left everyone time. Typically, I just change the destination folder for batches.

**Comment by brodycas3** [comment]
That's the same for me

**Comment by Bionus** [comment]
Are your filenames various enough that using a complex filename or conditional filenames not options?
If I allowed quick access to multiple filenames from the image window, would that help? Like there's currently 2 filenames available, the default one and the "favorites" one. I could re-design this part to allow more filenames to have quick access.

**Comment by Bionus** [comment]
BTW, how come <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> doesn't work and no one told me? :scream: I'll fix that too

**Comment by Synchestra** [comment]
I use the same filename format for all booru stuff, so there's no issue there. I'm sure that would be a useful feature as well.

**Comment by Bionus** [comment]
> I use the same filename format for all booru stuff, so there's no issue there. I'm sure that would be a useful feature as well.

Just to make sure, but you know you can make the program save in different folders using `/` characters in the filename right?

Maybe you already know and your folder structure does not allow automation, and in that case that's unfortunate, but maybe there's still some way to make it less painful (unless you don't save that many images and in that case the cost/benefit ratio would be too high).

> Making an attempt here... I haven't tested this and I have no idea if this is going to work or not, as I'm still waiting on the program to build. If it works, though, I'll commit it.
> 
> gui->src->viewer>zoomwindow.cpp
> 
> Line 921 as is:
> 
> ```QString filename = m_image->fileUrl().toString().section('/', -1);```
> 
> Line 921 updated:
> 
> ```QString filename = m_settings->value("Save/filename").toString();```
> 
> Edit: it definitely changed the filename, although not as intended. test_%md5%.%ext% outputted test_%md5%.%ext%.png so clearly I borrowed the wrong piece of code from your saveFileNow function (or I may have not included enough code). Not sure how to make the tags evaluate so I give up for now.

Indeed, that won't work.

While `m_settings->value("Save/filename").toString()` gives you the user's current filename (including tokens), it won't "apply" the current image to it (replacing the tokens by the image's data).

To do so, you have to use the `Filename` class, and use the public `path` method to apply it to some image. It will then give you the full expected image paths.

The issue being that an image can yield multiple paths (some settings generate multiple files for a single image), so here you have to transform this "list of image paths" into a single path. Taking the first result works.

The next issue is that this path may contain `/` if the user has a filename generating sub-directories, but we only want the filename here, so we have to remove everything before the last `/`.

```
QString filename = m_image->fileUrl().toString().section('/', -1);
```

Becomes:
```
Filename format(m_settings->value("Save/filename").toString());
QStringList filenames = format.path(m_image, m_profile, lastDir);
QString filename = filenames.first().section(QDir::separator(), -1);
```

Effectively fixing the problem exposed in this issue.

The resulting code is not very long, but not easy to get out unless you already know the classes' names and methods.

**Comment by Synchestra** [comment]
> Just to make sure, but you know you can make the program save in different folders using / characters in the filename right?

Yeah, I thought about trying something like that, but I don't think my folder arrangement would really allow for it, as I make the folders myself with proper capitalization and spacing and whatnot. Plus, they're nested into subfolders labeled 'A', 'B', and so on based on the first letter of the artists' names.

>  (unless you don't save that many images and in that case the cost/benefit ratio would be too high).

I do save rather a lot of images, but I don't know if there's a way to accommodate a folder structure like mine that wouldn't be a headache, so it's no worry.
