### ISSUE TITLE
Immediate crash upon startup

### ISSUE THREAD

**Issue by ayyu** [Bionus/imgbrd-grabber#899]
### What steps will reproduce the problem?

Crashes immediately upon trying to start

### How often does this problem occur?

Every time I try to open Grabber

### What version of the program are you using? On what operating system?

5.2.4 on Windows 10

### Please provide any additional information below

Last version that starts without crashing is 5.2.2

**Comment by Bionus** [comment]
Strange as many others didn't get this issue.

Let's see a few things:
* Could you share your `main.log` file?
* Do you even see the "start without restoring the last session" window?
* Can you try to backup then remove your `restore.igl` as well as your `tabs.txt` files?
* Same thing for the `settings.ini` file.
* If that fixes the problem, could you also share those files so I can reproduce (and then push a fix)?

Thanks and sorry for the inconvenience :smile:

**Comment by ayyu** [comment]
screenshot: ![image](https://cloud.githubusercontent.com/assets/11494813/25552032/367b748a-2c5d-11e7-9c69-c99a51fa842b.png)

log file
[main.zip](https://github.com/Bionus/imgbrd-grabber/files/965827/main.zip)

Deleting the settings.ini file worked. Removing the other two didn't change anything.

Thanks

**Comment by Bionus** [comment]
Without the previous `settings.ini` file I won't be able to reproduce, but from the fact that the log file is empty when the program crashes, it seems that the initial settings file was either corrupt or locked.
