### ISSUE TITLE
Export Tags to XML

### ISSUE THREAD

**Issue by NekoSnowy** [Bionus/imgbrd-grabber#900]
I don't know if this is a great suggestion, but I would like to suggest expanding the separate text file feature to export a xml file with a custom naming format. Due to the character limitation on file names, and the limited support of metadata on files, there's no effective way to store tags. Which is why I use a program that restores the old Windows XP feature of giving all file types the ability to have infinite metadata through the use of NTFS alternate data streams. 

The program also allows you to import metadata from an xml file into a file's alternate data stream using this naming scheme for the xml file.

_filename.ext.metadata.xml_

The inside of the xml file looks like this.

```
<Metadata>
	<Storage Description="SummaryInformation" FormatID="{F29F85E0-4FF9-1068-AB91-08002B27B3D9}">
		<Property Name="System.Keywords" Id="5" Type="VT_LPWSTR | VT_VECTOR" TypeId="4127">
			<Value>2017; &lt;3; anthro; blush; canine; cute; duo; eevee; eyewear; glasses; lying; mammal; nintendo; pokémon; semi-anthro; senz; simple_background; video_games; wings; wolf</Value>
		</Property>
	</Storage>
</Metadata>
```
Of course this being an xml file, tags that use reserved characters have to be converted into a html entity form. A tag such as <3 is stored as `&lt;3`

**Comment by Bionus** [comment]
So from what I understand, what you would like is:

- [ ] Customize the suffix of the "separate text file" feature, currently `.txt` but in your case `.metadata.xml`
- [ ] Add an way to html-escape tokens in the text file content

Did I forget anything?

_PS: what's that program's name?_

**Comment by NekoSnowy** [comment]
Yeah, seems about right. 

And the program's name is filemeta and is currently hosted on codeplex. But given the fate of that, the developer is working to export it to a different platform.

**Comment by barryanders** [comment]
This won't help with XML but if all you need is JSON, then you can use the programs log option.

**Comment by Bionus** [comment]
Actually a problem with XML is that it is not compatible with [filename conditionals](https://github.com/Bionus/imgbrd-grabber/wiki/Filename#conditionals).

So I guess the end result filename will have to look somewhat like this (with escaped `<` and `>` signs):

```
<<Metadata>>
	<<Storage Description="SummaryInformation" FormatID="{F29F85E0-4FF9-1068-AB91-08002B27B3D9}">>
		<<Property Name="System.Keywords" Id="5" Type="VT_LPWSTR | VT_VECTOR" TypeId="4127">>
			<<Value>>%all:unsafe,htmlescape,separator=; %<</Value>>
		<</Property>>
	<</Storage>>
<</Metadata>>
```

Unfortunate, but working.

**Comment by NekoSnowy** [comment]
So the xml tags will be outputted to the file content with << >>? That is unfortunate as the xml tags wouldn't be parsable in that state when attempting to import, but I have a program that can find and replace text across multiple xml documents, so not a big deal as long as everything else is outputted correctly. I appreciate your effort, this will make the process of applying metadata directly to files much easier~ (=^ェ^=)

**Comment by Bionus** [comment]
No, they will be outputted with `<` and `>`. It's just that you have to "escape" them in the filename or else they'll be parsed as conditionals.

You can see the unit test validating the behavior here:
https://github.com/Bionus/imgbrd-grabber/blob/develop/tests/src/models/filename-test.cpp#L202-L206

**Comment by NekoSnowy** [comment]
Oh, that's pretty cool, thanks for showing me~
