### ISSUE TITLE
grabber don't work on some webs

### ISSUE THREAD

**Issue by betoe** [Bionus/imgbrd-grabber#901]
### What steps will reproduce the problem?
When I look for images on webs like SankakuChannel, Yande.re, Gelbooru.

### How often does this problem occur?
Always

### What version of the program are you using? On what operating system?
5.2.4 on Windows 10

### Please provide any additional information below
this is the log
[20:23:09.619] Loading page https://yande.re/post/index.xml?login=&password_hash=&limit=20&page=1&tags=original
[20:23:09.877] Loading error: Error creating SSL context ()
[20:23:09.878] Loading using Xml failed. Retry using Json.
[20:23:09.879] Loading error: Error creating SSL context ()
[20:23:09.880] Loading using Json failed. Retry using Html.
[20:23:10.095] Loading error: Error creating SSL context ()
[20:23:10.095] No valid source of the site returned result.

**Comment by ravenlord1** [comment]
I had the exact same problem.  Here is what worked for me:

First, I removed 
    libeay32.dll
    libssl32.dll
    ssleay32.dll
 from the Program Files x86/Grabber directory

Second, I installed this implementation of OpenSSL: http://slproweb.com/products/Win32OpenSSL.html (I got 1.0.2k 32-bits); I confirmed in C:\Windows\SysWOW64 if libssl32 and libeay32.dll were available or not; in my case they were after installing 1.0.2k

Third, I restarted Grabber and it now worked perfect.

Maybe this will work for you too.

**Comment by Bionus** [comment]
@ravenlord1 That's strange, I didn't know there's such a difference with the 1.0.2h bundled with Grabber.

Didn't replacing the ones in Grabber's install directory suffice (instead of removing it and putting the new ones in your Windows directory)?

**Comment by ravenlord1** [comment]
I didn't have to manually add them to the windows directory.  It was automated with the Win32OpenSSL install.  So basically I just removed the old dlls from Grabber and then ran the install for OpenSSL.  I just checked the windows folder to make sure that the new dlls got added, and they did.  Since I was planning to add OpenSSL anyway this was the easiest way for me.

**Comment by Bionus** [comment]
I'll bundle the 1.0.2k OpenSSL dlls in next version.
