### ISSUE TITLE
Detected gif/png/webm images ignore job destination path when exclude tag is "-gif" "-png" or "-webm"

### ISSUE THREAD

**Issue by micnorian14** [Bionus/imgbrd-grabber#904]
### What steps will reproduce the problem?
Attempt to download a batch of images that includes jpg/webm/png from any board. Set destination in left pane to drive\folder\subfolderjob123\ add the tag "-gif" or "-png" then add the job. Do this again for a new job but in a different subfolder. Begin processing all jobs.

### What is the expected behavior? What do you get instead?
job1 drive\folder\subfolder1\images.jpg, images.png, videos.webm
job2 drive\folder\subfolder2\images.jpg, images.png, videos.webm
job3 drive\folder\subfolder3\images.jpg, images.png, videos.webm
instead
job1 drive\folder\subfolder1\images.jpg, videos.webm (ok)
job1 drive\folder\subfolder3\images.gif, images.png (not ok)
job2 drive\folder\subfolder2\images.jpg, videos.webm (ok)
job2 drive\folder\subfolder3\images.gif, images.png (not ok)
job3 drive\folder\subfolder3\images.jpg, images.gif, images.png, videos.webm (ok)
(note some sites don't bother tagging posts gif/png so those will be ignore -gif/-webm tags)

### How often does this problem occur?
Every time the log tab shows that bionus is guessing the extension of the file on the server, and you leave a subfolder typed into the location pane that isn't where the current job is supposed to be downloading into. If you start the program from a job list then the default folder will be where all gif/png get dumped. If you add the jobs one after another, the problem will occur using the last queued job folder. 

### What version of the program are you using? On what operating system?
5.2.4 on Win10x64

### Please provide any additional information below
Using the left pane of the program I can change the destination path even while in the middle of processing the job queue and the gif/png files will suddenly start downloading into that folder. This is an issue as I keep finding several artist's gif/png in the last artist's job I queued. This is because the last location I set in the destination pane was being used for any gifs/png that were found in the last dozen jobs. To note: I am trying to exclude gifs with some searches as there are superior quality (and not outrageously large!!) webm versions. For the time being the best I can do is blacklist the "gif" tag, which helps on some sites.

**Comment by micnorian14** [comment]
Issue was not reproducible after restart. Go figure.

**Comment by Bionus** [comment]
This looks a lot like issue #811, so there must definitely be a latent issue here that "randomly" occurs.
