### ISSUE TITLE
Website Konachan

### ISSUE THREAD

**Issue by Siickest** [Bionus/imgbrd-grabber#905]
### What steps will reproduce the problem?
Be able to add the site.

### What is the expected behavior? What do you get instead?
Is the Url Incorrect?

### How often does this problem occur?
Everytime I try

### What version of the program are you using? On what operating system?
5.2.4 and Windows 7 x64 bit

### Please provide any additional information below
None

**Comment by Bionus** [comment]
Well it just means it can't guess which source it it.
But konachan is in the sources of the default installation, and it's a "Moebooru" site, so you can just select it manually.
