### ISSUE TITLE
Grabber result non-results

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#906]
### What steps will reproduce the problem?
Searching largely populated tags like Gnoll, Gnoll, Tribal, Hyena Tribal, and other tags

### What is the expected behavior? What do you get instead?
It seems in some cases the tag tab fills up with tags but the images are not loaded on the page and the get functions do not let me download any images, becuase they havn't loaded or shown up.

### How often does this problem occur?
Frequently. It's occurred with other searches too, but It's becoming more and more common as of late.

### What version of the program are you using? On what operating system?

5.2.4

### Please provide any additional information below
Here is an anonfiles of my crash log, I hope it helps I've also been having trouble with gettign search results to show when not using my Proxy, Privoxy in any view, but I think that's just down to the ammount of sources I use. https://www.anonfiles.cc/file/10158ad0c915617b858efe4fa411e289

**Comment by Bionus** [comment]
Are you using merged results when it happens?
And does the UI freezes during that time?
Does all your sources return results for those searches, or just a small % of them? (like 80% without results and 20% with)

**Comment by SultrySamthepennanceman** [comment]
Nah, seemingly it searches and gets the results, but the images don't show (Not loaded?) and there Get all, Get selected and get this page options are inert, so you can't get any images or anything.

Even shows the tags for the searched results, but there isn't anything up to grab.

As for me using merged results, yes, not like I have a choice given the frequency of crashes I have when I don't use it with the amount of sources I have.

**Comment by Bionus** [comment]
Ah I get it. Since you're using merged results, the program waits for *all* the sources you selected to load before showing the results.

This behaviour will change in next version with issue #877 implementation.

**Comment by MasterPetrik** [comment]
@Bionus this issue can be closed now

**Comment by Bionus** [comment]
Indeed :smile:
