### ISSUE TITLE
Noob Questions - What those blue marks mean in download status tab?

### ISSUE THREAD

**Issue by csverona** [Bionus/imgbrd-grabber#908]
### What steps will reproduce the problem? 
 - Downloading Images from sanakaku complex by downloader - with ANY tags

### What is the expected behavior? What do you get instead?

 - When I excute download sequence, I get intact images with some kind of image which is just symbol of that site.
Intact images are marked with green circles, but these junk images are marked with blue circles.
(Also, all these junk images have same filesize - except names defined by MD5) 
Proportion of these images are not constant and differ depending on the tags.
(At least 50%, In some cases, it goes over 90%)

### How often does this problem occur?
It occurs whenever I start downloads.

### What version of the program are you using? On what operating system?

At first I used latest version of the downloader - then problem occured.
I reinstalled 5.1.1 but this problem hasn't been solved yet =(
(Windows 7 Home Premium K - 32 bit)

### Please provide any additional information below

Sorry for my poor english - I need help T.T

I tried to upload log and ini files with ZIP, but I cannot enclose ZIP file,

[01:07:08.178] Loading image from https://cs.sankakucomplex.com/data/b2/ed/b2ed3c0f8c8cb8f88cccfb8e18c02e2b.jpg 1
[01:07:08.301] Image received from https://cs.sankakucomplex.com/data/b2/ed/b2ed3c0f8c8cb8f88cccfb8e18c02e2b.jpg 1

These are download logs for intact images.

[01:07:09.024] Loading image from https://cs.sankakucomplex.com/data/3d/7a/3d7ac38f765336227ebc8df178990282.jpg 1
[01:07:09.038] Image received from https://chan.sankakucomplex.com/redirect.png 1

And these for junk files

I deleted ini file, but nothing changed

![2b54aab0edfb9a455a3c1aecf7e1506a](https://cloud.githubusercontent.com/assets/28488365/25774027/122e653a-32c3-11e7-80a7-5a3b2a170efc.png)

ㄴ junk image file

**Comment by csverona** [comment]
Here are log and ini files

**Comment by csverona** [comment]
I tried to upload log and ini files with ZIP, but I cannot enclose ZIP file

**Comment by Bionus** [comment]
What blue marks are you talking about? Could it be those?

![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/v5.1.1/resources/images/colors/black.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/v5.1.1/resources/images/colors/blue.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/v5.1.1/resources/images/colors/red.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/v5.1.1/resources/images/colors/green.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/v5.1.1/resources/images/colors/black.png)

They have been changed in the latest version though:

![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/master/resources/images/status/pending.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/master/resources/images/status/downloading.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/master/resources/images/status/error.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/master/resources/images/status/ok.png) ![](https://raw.githubusercontent.com/Bionus/imgbrd-grabber/master/resources/images/status/unknown.png)

As for the images that get downloaded, it is this?

![redirect](https://cloud.githubusercontent.com/assets/882719/25774016/3816327c-3288-11e7-943a-665c9dcd1c38.png)

Have you tried logging into Sankaku using a free account there to see if anything changes? Note that Sankaku has lots of restrictions on their API that can block you temporarily if you make too many requests too fast, so you could try to increase the interval between image downloads in Sankaku's source settings:

![image](https://cloud.githubusercontent.com/assets/882719/25774030/777aa812-3288-11e7-8579-2d39cacdf314.png)

**Comment by csverona** [comment]
I read that some sites require login for cancel restriction - Yeah I tried before I start downloading but there was a bit of error, so I ignored.

Maybe that could be one solution. I'll try again and tell you whether problem is solved

Thank you for support! =D

**Comment by csverona** [comment]
Ok. Now the proportion of intact file is much more higher (7/20 to 17/20), But there are still some files not downloaded correctly... What should I do for next? Version Upgrade?

**Comment by csverona** [comment]
Now Perfectly works with latest version, Thank you so much! =D

**Comment by brodycas3** [comment]
hmm, People seem to not close issues when they are resolved
