### ISSUE TITLE
Is it possible to have "if doesn't contain" conditions?

### ISSUE THREAD

**Issue by Impervox** [Bionus/imgbrd-grabber#910]
I looked at the wiki and I saw that you can add conditions that add text  if the image contains a tag from a custom token? Is it also possible that it adds additional text if an image doesn't contain any tags from a custom token? I'd like it to have "None" if it doesn't have any of the tags.

**Comment by Bionus** [comment]
That is currently not possible but not very hard to implement, I'll add it it next release. :smile:

**Comment by MasterPetrik** [comment]
Looks like next release will be very not soon.

**Comment by Bionus** [comment]
@MasterPetrik [Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/991149/Grabber.zip)

**Comment by Bionus** [comment]
In 5.3.0, to do so you'll just have to prefix your conditions with a exclamation mark `!` symbol.

Example:
```
<image does not contain the tag !"tag1"><!"unknown" is not one of the image tags> %md5%.%ext%
%md5% -<!%artist% no artist>.%ext%
```

**Comment by MasterPetrik** [comment]
Not to forget to add this info in Grabber wiki

**Comment by Bionus** [comment]
Good call, I just updated it: [Filename - Inverting conditions](https://github.com/Bionus/imgbrd-grabber/wiki/Filename#inverting-conditions)
