### ISSUE TITLE
Reduce the number of times Grabber takes focus

### ISSUE THREAD

**Issue by angaratosurion** [Bionus/imgbrd-grabber#911]
is it possible to make the applciation to not try to get focus when updates or anything occures ? thanks

**Comment by MasterPetrik** [comment]
> anything occures
hmm...

**Comment by angaratosurion** [comment]
yeah .. it just popups and get's the focus of the keyboard everytime ... even if it downloads teh failed images ..

**Comment by Bionus** [comment]
Which cases exactly poses problems, except the one you mentioned? (which I believe is "Errors occured during the images download. Do you want to restart the download of those images?")

BTW you can set Grabber to automatically re-try failed images without your input at the end of downloads:

![image](https://cloud.githubusercontent.com/assets/882719/26227931/df76db3c-3c35-11e7-8578-dd46d1fbed01.png)
