### ISSUE TITLE
Slow image scrolling

### ISSUE THREAD

**Issue by Zekken01** [Bionus/imgbrd-grabber#912]
### What steps will reproduce the problem?

After scrolling through about 50 or so images (estimated) going to the next image gets slowed down. It eventually gets to the point to where I need to reopen grabber.

### How often does this problem occur?

Every time. almost

Sometimes resolves its self.

### What version of the program are you using? On what operating system?

v5.2.4 Win 10

**Comment by Bionus** [comment]
Scrolling in the image window, or the in tab results?
If it's in the image window, does closing the window and re-opening it fix the slowness?
What part is slow exactly: the time to load the next image, the interface, something else?

**Comment by brodycas3** [comment]
Yeah, closing and reopening does fix it. The part that gets slow is the
loading of the next image. Almost like its freezing.
