### ISSUE TITLE
Same images on different pages in merged results mode

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#913]
### What steps will reproduce the problem?
for example:
1. search something with merged results enabled.
2. download some(better all) images from page1 via preview window
3. go to the page2
4. open preview mode and see that some images have "delete"  button instead of "save" button, which means that these images are 100% clones of images from page1, not just visually similar.

### What is the expected behavior? What do you get instead?
I'm expecting not to see same images in MERGED(how ironic) MODE on other pages.

### How often does this problem occur?
100% repeatability with any conditions

### What version of the program are you using? On what operating system?
all versions with merged results mode, even in 5.3.0 alpha

### Please provide any additional information below
With this issue all merged results mode idea becames ruined, because in fact it not really merged.

P.S. can I post isdies from 5.3.0 alpha?

**Comment by brodycas3** [comment]
Can confirm 150%

**Comment by Bionus** [comment]
Well, on page 2 it only merges all pages 2 from all your sources, it doesn't take into account the results from page 1. So if some image is on source A's page 1, it can appear on source B's page 2.

Doing something else would mean remembering what happened on previous pages. It's feasible if you do page 1 > next > page 2 > next, etc. but if you directly open page 100, Grabber can't possibly load 99 pages just to hide results from the previous pages.

That's the reasoning for why it has not been done (yet), even though I totally agree. And the solution that says that if you don't start at page 1 just don't ignore previous page's images (current behaviour) would mean that there are different results if for example you restart the program in the middle of your search.

> P.S. can I post isdies from 5.3.0 alpha?

Yeah you can if there's anything you found. :+1:

**Comment by MasterPetrik** [comment]
> Doing something else would mean remembering what happened on previous pages. It's feasible if you do page 1 > next > page 2 > next, etc. but if you directly open page 100, Grabber can't possibly load 99 pages just to hide results from the previous pages.

You got the problem from nowhere... There is no problem at all. You just need to build a md5 list for each merged request, and from first page(1 or 99 doesn't matter) fill it with md5 of unique images, for second page just check md5 from list for each image to prevent duplicates. Order of pages doesn't matter. You don't need to download in the list md5 from skipped pages, this is really no needed.   

For example:
Load page 4 - fill md5 list with img md5 from this page.
Load page 8 - add to md5 list img md5 from this page after comparing with existed in the list md5.
Load page 1 - add to md5 list img md5 from this page after comparing with existed in the list md5.
so after that we will have a unique md5 for each shoved page, no matter, what it's number

**Comment by brodycas3** [comment]
That's what I was thinking but I didn't know how to explain.

**Comment by Bionus** [comment]
> You got the problem from nowhere... There is no problem at all. You just need to build a md5 list for each merged request, and from first page(1 or 99 doesn't matter) fill it with md5 of unique images, for second page just check md5 from list for each image to prevent duplicates. Order of pages doesn't matter. You don't need to download in the list md5 from skipped pages, this is really no needed.

Which means that depending on the order of the pages you load, you get different results, which is exactly what I was saying.

In your example, if I follow what you say (4 > 8 > 1) the results of page 1 will be different that if I directly load page 1.

**Comment by Bionus** [comment]
Just to make it clear: my point is not that this feature shouldn't be implemented because of the problem I mentioned. :+1:

I just bring it up because implementing this suggestion will create this "seemingly unpredictable" behaviour, which may however still be preferable to the current one. I believe all pros and cons should be examined in case someone has some solution for this problem, or in case someone one days wonders why its results change depending on the order pages load. :smile:

That also changes the way MD5s have to be stored to make the "unique" filter. Currently, we take all the images, if they're not in the MD5 list we show it and add its MD5 to the list, else we ignore it. By considering previous MD5s, a more global list have to be kept as well as on which page though MD5s were found: else re-loading a page would make all its images ignored as their MD5s are already on the list. That list should also be cleared every time the selected sources or search changes.

**Comment by MasterPetrik** [comment]
> you get different results

As I said in Endless page mode topic, merged results is a bunch of images, you can't expect stable order from it;
Different results you will get anyway, because some sourse on some pages couldn't give you images, or there are has been added\removed some images for this tag on sertain sourses, so results will be different again. And you can add\remove some sourses too, this will cause changing results too.

So results will not be constant anyway. So order in it doesn't matter.

> That also changes the way MD5s have to be stored to make the "unique" filter. 

You will need to built more complex MD5 list system anyway. Because current md5 list is a too much simple, it works for little md5 amount in the list, but with big amount of MD5 in the list  it will be very bad and slow.
 I mean that you need to make MD5 list as DataBase file with diffetent lists in it, according to first md5 character. So it will be 16 lists inside[0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F], so when you get new md5, you can use it's 1 char to search only in list of MD5 which started with this char. So it will make MD5 comparing almost 1600% faster and use in 16 times less memory for it. If list fo one of first chars became too big, then auto separate it to new 16 sublists according to second char... etc.
But that's for global MD5 list. Looks like separate suggestion)

What about temp md5 list for each merged search result, after closing tab it should be deleted, and for new merged search it will be created again.

**Comment by Bionus** [comment]
> So results will not be constant anyway. So order in it doesn't matter.

The order will indeed differ depending on which page loads first, but not only is it fixable (by sorting the results according to some critera or simply sorting them by source), it's I believe a smaller issue than having different results altogether.

>  But that's for global MD5 list. Looks like separate suggestion

Indeed, and a very good one for people having big MD5 lists (good memory-wise, given the current structure is already O(1) fast, being an hash map). Note that a the "database" you're suggesting is called a `trie`, a structure used for example to give suggestions in phone books or dictionaries.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Trie_example.svg/1200px-Trie_example.svg.png" width="300" height="281" />

**Comment by barryanders** [comment]
Oh nice, you committed a fix for this already. That was fast.

**Comment by Bionus** [comment]
I'm doing my best to have the version ready for this week-end :smile:

I'll also see if I can get the results sorted, because getting inconsistent results depending on the order sources load isn't a very good thing.
