### ISSUE TITLE
scrolling Issue

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#915]
### What steps will reproduce the problem?

scroll on the tag list

### What is the expected behavior? What do you get instead?

To not scroll to next page when you reach the bottom of the tags

### How often does this problem occur?

100%

### What version of the program are you using? On what operating system?

v5.2.4

### Please provide any additional information below

http://i.imgur.com/P2udycd.gifv

**Comment by MasterPetrik** [comment]
hmm.. for me all works well... strange

**Comment by Bionus** [comment]
@MasterPetrik  it happens when you scroll the tag list on the left of the image window. When you reach the bottom but keep scrolling, it will change images (as if you scrolled when having the mouse on top of the image).
