### ISSUE TITLE
Arch: No /example Folder

### ISSUE THREAD

**Issue by ROMSY-SAN** [Bionus/imgbrd-grabber#918]
### What steps will reproduce the problem?
Ok, just tried to run:
$ mkdir ~/.Grabber
$ cp -r /usr/share/Grabber/example/* ~/.Grabber/

### What is the expected behavior? What do you get instead?
expected: copy example to ~/.Grabber/

instead: cp: cannot stat '/usr/share/Grabber/example/*': No such file or directory

### How often does this problem occur?
 well everytime since there is no example Folder

### What version of the program are you using? On what operating system?
latest via Arch (used yaourt to install)

**Comment by ROMSY-SAN** [comment]
sorry my fault... cp -r /usr/share/Grabber/* ~/.Grabber/ was the right command to use it...

**Comment by Bionus** [comment]
Is this copy even necessary?

The latest version of Grabber should also looks for those files directly in `/usr/share/Grabber`.
