### ISSUE TITLE
Allow to customize the list of available "Web services" in the context menu

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#920]
Currently only contains SauceNAO, Google Images, Yandex, etc.

It could be a good thing to add some page in the settings to be able to add any source you want, somehow like the ["Image Search Options" Firefox plugin](https://addons.mozilla.org/en-US/firefox/addon/image-search-options/) does (but in a more basic way).

### Allow to define
* Icon
* Name
* Url template

**Comment by MasterPetrik** [comment]
good idea.

make sure that you will be to user not to neseseryly set icon, and if icon wasn't set, show the icon of the site from the URL
