### ISSUE TITLE
Didnt add the dark theme on update

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#921]
When I updated to the latest version it didn't add the theme.

**Comment by Bionus** [comment]
Indeed, my bad.
I just updated the 5.3.0 installer, the theme should be there.

**Comment by brodycas3** [comment]
Still not there, 
![image](https://cloud.githubusercontent.com/assets/19770864/26278497/bab4c8a6-3d69-11e7-84af-f0cc657f1f90.png)

**Comment by Bionus** [comment]
Did you reinstall and re-download the installer?
I tried with the latest installer to do a clean install, the theme was there.

**Comment by Bionus** [comment]
If you still don't get it for some reason, you can get it here too: [QDarkStyleSheet.zip](https://github.com/Bionus/imgbrd-grabber/files/1016415/QDarkStyleSheet.zip)

**Comment by brodycas3** [comment]
I only update, I don't do a reinstall.

**Comment by brodycas3** [comment]
Perhaps that is something that should be fixed.

**Comment by Bionus** [comment]
It was already. Installing with the latest installer includes the theme. Cf 94ffc0142e8375ba4682002b85b1876c3e17a841
