### ISSUE TITLE
Empty names bug in "save as..." Dialog for Zerochan images

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#925]
### What steps will reproduce the problem?
![image](https://cloud.githubusercontent.com/assets/22294259/26286963/abe50c30-3e79-11e7-9412-2e6d740775d8.png)

If you select image in results grid and try to "save as" it, in dialog window its namebox will be empty.

But, if you open image in preview before that and only then select this image in results grid and try to "save as" it, in dialog window its namebox will be filled with correct name.
https://drive.google.com/open?id=0B3SK4Pf9wsnmMjVxSlhyOUNNdW8

### What is the expected behavior? What do you get instead?
expect to see in save as dialog default name of file according to grabber naming rules(same name that file will have if it will be just autosaved)

### How often does this problem occur?
100% reproduseable

### What version of the program are you using? On what operating system?
5.3.2 win7

### Please provide any additional information below

trying to "save as" new image:
![2017-05-21_204353 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26287001/622aa84c-3e7a-11e7-87a7-be5bd0c446d0.png)

trying to "save as" already opened in preview image:
![image](https://cloud.githubusercontent.com/assets/22294259/26286135/391239de-3e66-11e7-8f1c-5401378a483e.png)

**Comment by brodycas3** [comment]
I can also confirm this.

**Comment by MasterPetrik** [comment]
@Bionus I don't think that this is hard to fix it, or I'm wrong?

**Comment by MasterPetrik** [comment]
@Bionus looks like I fugured out how to reproduce it, it seems that it's happen only with images from Zerochan. I tried separated search and other sources exept Zerochan really works correct with "save as" from grid. 

So please try it and tell me about your result.

**Comment by Bionus** [comment]
That is because Zerochan does not provide the images' MD5. Therefore, the only way to have it is to actually download the image and calculate the MD5, which is done for batch downloads, but in the "Save as..." case, the image is not loaded yet.

One solution would be to download the image **before** asking for the image location, then move the downloaded file, but that's quite a weird behaviour.

**Comment by MasterPetrik** [comment]
> One solution would be to download the image before asking for the image location, then move the downloaded file, but that's quite a weird behaviour

Well, you can do it only in cases if Grabber is failed to get naming info from the site, and anyway there should be some default name for the "save as" option for these cases when grabber cant provide correct filenaming, for example set default name like "search request" + "datetime line of numbers". I guess it would be not bad variant, it gets info for naming only from grabber and it's pretty unic for using as default one.
something like "mintsu_(ichi--kun)20170808022932.jpg"

**Comment by MasterPetrik** [comment]
@Bionus maybe fix it in 5.5.2?
