### ISSUE TITLE
Batch downloads insert apostrophes before and after every database input

### ISSUE THREAD

**Issue by Aelphais** [Bionus/imgbrd-grabber#927]
### What steps will reproduce the problem?
"Get all" batch downloading from Sankaku Complex with the 'overwatch' tag, though any tags work as well as sourcing Gelbooru.

Settings for insert are set to this:
http://i.imgur.com/T4Mmg64.png

Which look right as far as I can tell.

### What is the expected behavior? What do you get instead?
Expect no apostrophes. However, database currently looks like this:
http://i.imgur.com/rXux5N5.png

### How often does this problem occur?
Every time since upgrading to 5.3.x line

### What version of the program are you using? On what operating system?
Grabber 5.3.2
Windows 10

### Please provide any additional information below
Can't think of anything else that might help. If you need more information, let me know.

**Comment by Bionus** [comment]
Oh, that's because you don't need to add double quotes around your fields in the SQL commands any more, everything gets escaped now since version 5.3.0 (cf issue #864).

I'll update the doc to reflect that.

**Comment by Bionus** [comment]
Now that I think about it, it seems this will be a problem for the "%md5%.%ext%" field. I'll add a way to disable that and push an update.
