### ISSUE TITLE
Nothing happening when clicking Get all

### ISSUE THREAD

**Issue by SWymanOF** [Bionus/imgbrd-grabber#928]
### What steps will reproduce the problem?
I'm trying to grab images tagged love_live!, and while the program is displaying them - clicking get all doesn't download anything.

### How often does this problem occur?
Every single time.

### What version of the program are you using? On what operating system?
5.3.2 on Windows 10

**Comment by Bionus** [comment]
You have to go to the "Downloads" tab after clicking "Get all" and stat the downloads from there.

**Comment by MasterPetrik** [comment]
I thought about that too, maybe you need to make auto opening downloads tab after pressing "get this page" "get all", I guess it will be more obvious for all users.

**Comment by SWymanOF** [comment]
Ah, ok. I just figured get all would... get all.
