### ISSUE TITLE
Get All only downloads the first page of results from paheal

### ISSUE THREAD

**Issue by bootyfunker** [Bionus/imgbrd-grabber#929]
### What steps will reproduce the problem?
Click get all and download.

### What is the expected behavior? What do you get instead?
Expected to get all images.

Only get first page (70 images). In other cases with results spanning over more pages it will download half of them and just say it's done.

### How often does this problem occur?

Every time.

### What version of the program are you using? On what operating system?

5.3.2

Windows 10

### Please provide any additional information below

Using get all, it will only download the first page of results, but using get this page and going through the pages manually works and it will download all images for each page.

This problem only seem to affect rule34.paheal.net.

**Comment by bootyfunker** [comment]
Actually Get All seem to be missing a lot of images for several sources in comparison to manually using Get This Page for every page of results.

**Comment by Bionus** [comment]
Indeed, it seems that you have to force the "Images per page" value to 70 for paheal prior to starting the download.

**Comment by bootyfunker** [comment]
Tried forcing 70 images per page in the downloads. It works much better, but I found it still misses some images.

**Comment by Bionus** [comment]
What's the proportion of "missing" images?
Can you give an example of a download where some images go missing?

**Comment by Bionus** [comment]
Note that the issue was closed automatically.
If the problem is still here when setting the images per page to 70 I'll of course re-open it. :smile:
