### ISSUE TITLE
Change autoupdate work order

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#932]
Current autoupdate steps order is a bit strange. Grabber launches along with update message, so you NEED to close grabber if if you want to update. Then why you open full grabber along with this message at all?

![image](https://cloud.githubusercontent.com/assets/22294259/26457839/2e68ac04-417a-11e7-9d79-5e2177c66127.png)

Current way of work:
1. New version avilable
2. Open Grabber
3. Grabber openes
4. Meanwhile new update message shows
5. You press update
6. Grabber ask you to close it for update
7. Grabber closes
8. Instalation starts

Logical way of work:
1. New version avilable
2. Open Grabber
3. New update message shows BEFORE launching grabber
4. You press update
5. Message closes
6. Instalation starts

Grabber will be launched only if you refuse update.

**Comment by Bionus** [comment]
BTW, that also means that since Grabber does not do the update check in background, it will take a little longer before the window actually opens (the time to check if an update is available).

**Comment by MasterPetrik** [comment]
> BTW, that also means that since Grabber does not do the update check in background, it will take a little longer before the window actually opens (the time to check if an update is available).

well, you still can check for updates when grabber is launched and ask for update on the next opening of Grabber, so there are won't be any delay before Grabber start.

**Comment by ItsSohma** [comment]
That's a good way to avoid the delay but it would put everybody behind the update by one launch. Not really a big deal though.
