### ISSUE TITLE
Minor Bug: Downloaded image number versus total count missmatch

### ISSUE THREAD

**Issue by Aelphais** [Bionus/imgbrd-grabber#934]
### What steps will reproduce the problem?
Search a set of unrelated tags. Not exactly sure what else. Sometimes it works, sometimes it doesn't. I am personally searching Sankaku Complex, not sure if other sites cause the same issue.

### What is the expected behavior? What do you get instead?
I set a few tags on separate "grab all" downloads and download them all at once in the batch download. Everything appears normal except the total images is lower than it should be. It downloads all images I want properly, so I assume it is just a visual bug. Pulling the wrong variable or something.

I think this image explains it better than I can:

http://imgur.com/a/UoSAh

Though the total download in the image matches the last tag's total count, I am not sure that it is the issue. I am almost certain that I've seen it wrong with other numbers.

### How often does this problem occur?
Fairly sporadically, but somewhat often as well.

### What version of the program are you using? On what operating system?
5.3.3
though I've noticed it in previous versions as well
Windows 10

### Please provide any additional information below
Sorry if that was a bit of a messy description. I've noticed it before but since everything is downloaded fine, I've never actually bothered taking screenshots of it.

**Comment by Bionus** [comment]
> Sorry if that was a bit of a messy description

Knowing it only happens when downloading multiple unrelated downloads and having a screenshot already helps :+1:

I'll take a look to see what might cause this.
