### ISSUE TITLE
Question about images borders colors in search results grid 

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#935]
Can you give me info, what means different colors of borders of images?

![2017-05-26_164944 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26497234/6d253cd2-4233-11e7-92dd-ca74d21c03c8.png)

I need it for my probably next suggestion.

**Comment by Bionus** [comment]
* Some tag is blacklisted: #000000 (black)
* Some tag is in the favorites: #ffc0cb (pink)
* Image has a parent: #cccc00 (yellow)
* Image has children: #00ff00 (green)
* Image has "pending" status: #0000ff (blue)
