### ISSUE TITLE
Batch downloading from Sankakucomplex causes crashes

### ISSUE THREAD

**Issue by bootyfunker** [Bionus/imgbrd-grabber#937]
### What steps will reproduce the problem?
Downloading a bunch of images from any Sankakucomplex source (chan or idol).

### What is the expected behavior? What do you get instead?
Expecting to get the images, crashes in the progress.

### How often does this problem occur?
Can't say it occurs every time for sure, but very often.
Reducing the maximum simultaneous downloads to 1 (from 10, which works fine with other sources) seem to mitigate the issue.

### What version of the program are you using? On what operating system?
5.3.3
Windows 10

### Please provide any additional information below
Unrelated issue: tentaclerape.net sometimes comes up in the batch download listing even though there are no images in the search results, which causes the batch downloader to crash if you don't remove the tentaclerape download from the list before starting.

**Comment by Bionus** [comment]
If this only happens with simultaneous downloads, it must be caused by Sankaku's anti-download security. They don't allow simultaneous downloads and have pretty strict download rates.

I'll take a look and try to reproduce.
