### ISSUE TITLE
NO results from paheal (http vs https)

### ISSUE THREAD

**Issue by bootyfunker** [Bionus/imgbrd-grabber#938]
### What steps will reproduce the problem?
Searching for images on paheal with https disabled (which is default).

### What is the expected behavior? What do you get instead?
Expect to get image results when searching, but with the https option unchecked (which is the default), paheal does not load.

### How often does this problem occur?
Seems to be an issue all the time now.

### What version of the program are you using? On what operating system?
5.3.3
Windows 10.

### Please provide any additional information below
Enabling https in the source makes it work again, but downloads won't work. **It seems paheal has switched to https but the images are still in http links.** Maybe there's a way to use https for searching and http for downloading?

**Comment by Bionus** [comment]
I have no problem loading paheal using the default non-HTTPS settings.
Loading [http://rule34.paheal.net/](http://rule34.paheal.net/) **NSFW** in my browser also works (actually, both HTTP and HTTPS work on their website, except that as you said images are always over HTTP).

Maybe it was a temporary issue?

**Comment by Bionus** [comment]
Closing for lack of update and reproducibility.
Feel free to re-open and provide some more information if the problem persists.
