### ISSUE TITLE
Drag-n-drop links for MD5 search 

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#943]
# Suggestion\enhancement
Drag and drop MD5 search(https://github.com/Bionus/imgbrd-grabber/issues/764) works well, thanks for adding it, but now it works only with FILES, so, if you, for example, want to search some image from browser, you need to save it in the folder and only then drag-n-drop it to grabber. So it would be very good if Grabber could support links too, and you could drag-n-drop images directly from browser to grabber.

1. Get link via drab-n-drop
2. Determine it as link and check it's original
3. Download original to temp folder
4. Calculate MD5 of the file(even no need to check is this an image or not, because it doesn't matter for MD5)
5. Open new tab with MD5 search

![2017-06-06_045345 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26810412/3d4e4f46-4a74-11e7-8564-f45807d376f3.png)

**Comment by Bionus** [comment]
Indeed, I see no reason to not do it.

I'm not sure how browsers actually drop images however, such as the action in your screenshot. Seems like they give both the URL and the image data.
