### ISSUE TITLE
Downloading favorites from rule34.xxx

### ISSUE THREAD

**Issue by redfoutos** [Bionus/imgbrd-grabber#945]
### What steps will reproduce the problem?

copy and paste the URL of the "favorites" page
https://rule34.xxx/index.php?page=favorites&s=view&id={myid}&pid={pid}

### What is the expected behavior? What do you get instead?

As expected, the pictures are displayed but they are not tagged correctly. For some reason, they all
have the tags displayed on the left side of the first "posts" page. 

### How often does this problem occur?

Everytime

### What version of the program are you using? On what operating system?
v5.3.3 win 8.1

### Please provide any additional information below
Sorry if it's a messy description, i wanted to include pictures but many tags are nsfw.

**Comment by Bionus** [comment]
Indeed, I could reproduce on my end: the tags are shown for a short while then quickly replaced by the tags of the first page of image listing. I'll work on a fix and include it in the next release.

> Sorry if it's a messy description, i wanted to include pictures but many tags are nsfw.

You can put link to NSFW pictures if you mark them as such, for example with **NSFW** (`**NSFW**`). As long as they don't show up automatically when someone opens the issue it's all right. :smile:

**Comment by kiccd4g** [comment]
https://rule34.xxx/index.php?page=favorites&s=view&id={myid}&pid=0
https://rule34.xxx/index.php?page=favorites&s=view&id={myid}&pid=*

no result
