### ISSUE TITLE
Favourites grid enhancements

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#948]
# Current grid mode 
Current favourites grid has many problems, already fixed in search results grids. 
## 1
![2017-06-10_065805 win7 mastercore](https://user-images.githubusercontent.com/22294259/26999755-3ef06db4-4daa-11e7-8fcd-9c974f128693.png)
## 2
![2017-06-10_065814 win7 mastercore](https://user-images.githubusercontent.com/22294259/26999758-41e7d57a-4daa-11e7-9a28-94613165fbdc.png)
## 3
![2017-06-10_065819 win7 mastercore](https://user-images.githubusercontent.com/22294259/26999759-449213d0-4daa-11e7-9dc9-7cb4c5658de4.png)
## 4
![2017-06-10_065825 win7 mastercore](https://user-images.githubusercontent.com/22294259/26999760-4736c752-4daa-11e7-8aee-33ef7a27f59a.png)

### This is not the only problem with this grid, she second problem is clickable image areas sizes.
# Wrong scaling process in one image:
![2017-06-10_063852 win7 mastercoreh](https://user-images.githubusercontent.com/22294259/26999941-e0589570-4dad-11e7-838f-1f65301ed663.png)

# What to do:

So as you see, there are same problems as for search results grid. And to fix it, needed:
1. Change Favourites grid mode to fixed mode
2. Change current clickable areas resize rule from "fixed space between images, resizable clickable area" to "fixed space for clickable area, resizable space between images" 
![2017-06-10_063852 win7 mastercorehsdf](https://user-images.githubusercontent.com/22294259/26999985-d973c38c-4dae-11e7-87f0-323a55f8cb24.png)

**Comment by Bionus** [comment]
> Change current clickable areas resize rule from "fixed space between images, resizable clickable area" to "fixed space for clickable area, resizable space between images"

I don't quite get this part. If the favorites are switched to the fixed-width layout, the red and green squares from your screenshot will be the same, won't they?

**Comment by MasterPetrik** [comment]
meh... all issues already closed by two hours, but still no update in releases -___-

**Comment by Bionus** [comment]
Did you even check? I published a release 2 hours ago...

**Comment by MasterPetrik** [comment]
my bad, I checked via Last release page -___- and via about grabber window -___-
