### ISSUE TITLE
Use of slashes "/" as separators for Copyright/Species/Character/etc

### ISSUE THREAD

**Issue by Lorhelei** [Bionus/imgbrd-grabber#950]
### What steps will reproduce the problem?

Using / ot \ as a separator for Copyright

### What is the expected behavior? What do you get instead?

i would like to make an embedded folders for more than one copyright tag, but instead, it just puts a blannk space ' '

### How often does this problem occur?

everythime

### What version of the program are you using? On what operating system?

5.3.3 on Windows 10

### Please provide any additional information below

I know that it's because how slashes are interpreted, but there is a way to bypass that? I dont know how to use the filenaming by Javascript for conditiionals and can't get the "regular" expression to work with slashes used as separators.

**Comment by MasterPetrik** [comment]
looks like you use it wrong, for example, I use "%search%\%md5%.%ext%" and all works

**Comment by Lorhelei** [comment]
@MasterPetrik Literally studied the page xD. I think I don't explain myself very well. I have this expression for file naming: "___%rating%</!%search_1% /Other/%copyright%></%search_1%>/%artist%<_%copyright%><_%character%>-%md5:maxlength=8%.%ext%__  "

This works if I'm looking for a specific things (used search) it will use _search 1_  as a folder, else it will create a folder named _Other_  and put inside another folder for _copyright_  tags.

For example, if I looks for _pokemon_ . Inside the _rating_  will be _pokemon_  folder and inside the image in question. 

But if I find a _pokemon_  pictures by looking on the main page it will create the _Other_  folder and inside a _Nintendo_  folder and then the picture inside.

But I'm looking to is for grabber create _"rating/Other/Nintendo/pokemon/image"_ 
Instead of:
_"rating/Other/Nintendo+Pokemon/image"_ 

Since it has more than one Copyright tag, it separate it with a + or whatever you use, and since copyright doesn't have a way to select specifically one tag of them (like search 1 2 3) I can't use the filenaming method. But in the copyright section, the separate character can't be "/" to force it to create another folder. "/, ", \" since this characters are not allowed.

Thanks for the reply btw!

**Comment by Bionus** [comment]
Now that's what I call advanced usage of the filenaming feature :smile:

Indeed, the tags merging is done **before** forbidden characters are removed. And `/` is a "forbidden" character because we wouldn't want tags such as `fate/stay_night` to create a new folder. The solution is to change the code and remove forbidden characters **before** merging tags. This way, even if the separator is "forbidden" as in your case it won't be replaced by a space.

However, with what you want to do, you could have one copyright in different places, with different depths. Even more so as tag order is not really guaranteed. Let's say you have "Mario Nintendo", "Nintendo Pokemon", "Pokemon Pokemon_X", "Nintendo Pokemon Pokemon_X", it will result in this tree:
- Mario
  - Nintendo
- Nintendo
  - Pokemon
    - Pokemon_X
- Pokemon
  - Pokemon_X

**Comment by Lorhelei** [comment]
Oh you are right, i didn't think in the order. What a problem. I had it restringed to "if more than 1" tags in copyright but as you said, it will make a mess. Maybe with a "if less than" and "if more than" then can be restringed to the use of two folders and no more, and in case that there is more tags, then it will use the "Crossover" folder but i think that there is no way to do that yet right? I didn't found it. And even in that case, the order will still be messed up (pokemon/nintendo | nintendo/pokemon)

The only think i can think of is the use of "if" statement or customs rules like "if more than 1 copyright and one of them is nintendo then put nintendo first" but that will be a nonsense for literally everything that's not nintendo xD. Not including that diferent pages has diferents ways to put copyrights. (Like danbooru that uses pokemon, pokemon sm, pokemon x as part of the copyright)

I'll try with custom tokens and see what can i do. btw i couldn't find info about the "conditional filename" option in the filenaming wiki thou.

Thanks for the reply! I'll experiment a little more with the naming and the options and see if i can get a better configuration. Also what an incredible work you do here by the way! I really think this could be the ultimate app for image collectors as myself. Thank you a lot!

**Comment by Bionus** [comment]
> Maybe with a "if less than" and "if more than" then can be restringed to the use of two folders and no more, and in case that there is more tags, then it will use the "Crossover" folder but i think that there is no way to do that yet right?

Isn't it already feasible though?

![image](https://user-images.githubusercontent.com/882719/27246341-3512fe6e-52f1-11e7-9a47-11133f3080bc.png)

> Not including that diferent pages has diferents ways to put copyrights. (Like danbooru that uses pokemon, pokemon sm, pokemon x as part of the copyright)

If you use the "Use shortest if possible", any copyright which is another copyright with something appended (example: `pokemon_x` = `pokemon` + `_x`) will be removed, only keeping the shortest copyright.

> And even in that case, the order will still be messed up (pokemon/nintendo | nintendo/pokemon)

Usually tags are sorted alphabetically. It's not enforced by the program though. I could add a `sort` option to force it.

> I'll try with custom tokens and see what can i do. btw i couldn't find info about the "conditional filename" option in the filenaming wiki thou.

Well it's not very complicated, so let me explain here: the condition can be either a `tag` or a `%token%`. In your case, you could use `%search_1%` as a condition to generate your filename:
* With `%search_1%`: `%rating%/%search_1%/%artist%<%copyright%><%character%>-%md5:maxlength=8%.%ext%`
* Default: `%rating%/Other/%copyright%/%artist%<%copyright%><%character%>-%md5:maxlength=8%.%ext%`

It's just a convenience to not use <> conditions in some basic situations. In your case, it just makes it more complicated. It can be useful if for example you want to treat some images differently depending on some tag, and don't want to ruin your filename for it. Let's say you want to have "Nintendo"-tagged images in a totally different location from other files, you can use the "Nintendo" as a condition to change both the filename and path for these images.

> Thanks for the reply! I'll experiment a little more with the naming and the options and see if i can get a better configuration. Also what an incredible work you do here by the way! I really think this could be the ultimate app for image collectors as myself. Thank you a lot!

If you really want to do something complicated, you could always invest some time converting your filename to JavaScript. Then you'll be able to do whatever you want. As long as you know JavaScript of course.

**Comment by Lorhelei** [comment]
Thanks so much for let clear the "Shortest if possible" I thought it works on some other way. I will make some test with the "if more than" and then try to learn some Javascript. 

Thanks again for the help!
