### ISSUE TITLE
downloading glitch???

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#952]
### What steps will reproduce the problem?
I'm not sure, If you need logs I'll upload them.

### What is the expected behavior? What do you get instead?

Download the selected site first. Nothing is downloading... also says its downloading from another site instead...

### How often does this problem occur?

idk, This just happened now.

### What version of the program are you using? On what operating system?

Win 10, latest version as of this post.

### Please provide any additional information below
![zjsj6h9](https://user-images.githubusercontent.com/19770864/27257396-cf392ade-53a2-11e7-8de5-38850fa8ba85.gif)

**Comment by brodycas3** [comment]
[Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/1082854/Grabber.zip)
My settings and log.

**Comment by ItsSohma** [comment]
Nice gif.

**Comment by Bionus** [comment]
Sorry I totally didn't see this issue pass by! :confused:

It also seems to be the same as #1022. Let's move the discussion to there as it's the most recent one. And indeed, a great gif there :+1:
