### ISSUE TITLE
Bug with md5 search results showing

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#955]
![image](https://user-images.githubusercontent.com/22294259/27264991-d992f580-5494-11e7-809a-71c43a23859c.png)

### What steps will reproduce the problem?

1. Start any md5 search with multiple sources and without merging
(for example md5:0675fb2a58740ee74aa1f70e6793b9b6 from video below)
2. See how results grid blinks like crazy

### How often does this problem occur?
Looks like it happens with any md5 search request in 100% cases

### What version of the program are you using? On what operating system?
5.4.0.a

### Please provide any additional information below

Here is the video of the process:
https://drive.google.com/open?id=0B3SK4Pf9wsnmaXotdUlYQThEcmM

**Comment by MasterPetrik** [comment]
still take place in 4.2.0

**Comment by MasterPetrik** [comment]
@Bionus looks like rewoked grid in nightly version fixed this bug.

**Comment by Spark-NF** [comment]
Great to hear!
That proves that the reworked version is indeed much more stable than the older one. :tada:

**Comment by Bionus** [comment]
Great to hear!
That proves that the reworked version is indeed much more stable than the older one. 🎉

**Comment by MasterPetrik** [comment]
@Bionus don't be so happy, I almost completed a issues report about the new one)
