### ISSUE TITLE
Blacklisted Images showing in image viewer

### ISSUE THREAD

**Issue by VulpesJack** [Bionus/imgbrd-grabber#957]
### What steps will reproduce the problem?

Add tags to blacklist, open a result from the grid next to a blank space, press the direction arrow that corresponds to that space.

### What is the expected behavior? What do you get instead?

The image viewer should jump to the next image in the grid, instead, it loads images with blacklisted tags/

### How often does this problem occur?

Any time the image viewer is used

### What version of the program are you using? On what operating system?

5.3.3 on Windows 10

### Please provide any additional information below

![mjwrjr](https://user-images.githubusercontent.com/24865767/27411917-e1c2e822-56e8-11e7-80b9-955ad7df41d8.png)
![nwngan](https://user-images.githubusercontent.com/24865767/27411923-e9b2b990-56e8-11e7-8554-f8d5df50b08f.png)

**Comment by Bionus** [comment]
Indeed, such images should be skipped from the image cycling, good catch :+1:

**Comment by MasterPetrik** [comment]
Is that means that in current Grabber results grid exists some empty spaces, where blacklisted images are placed?

**Comment by Bionus** [comment]
@MasterPetrik yes, in the current implementation (which I'm planning to change) blacklisted images either have a black border or are simply "hidden" (i.e. empty space instead of the thumbnail).
