### ISSUE TITLE
Endless page mode broken for multiple source merged results

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#958]
From issue #886

> implemented not only for one-source mode, but for multiple source merged results too

> It work for one source results.
It work for one source merged results.
And even there I found at least one crash-bug and one other problem...(I will make separate issues)
But it completely don't work with multiple source merged results. Nothing.
No button in button mode, nothing when scroll in scroll mode.
So it work as normal pages mode with no signs of changes.

**Comment by MasterPetrik** [comment]
there are exist some important bugs in 5.4.0.a I will report them at the evening, please, don't release update until that

**Comment by Bionus** [comment]
@MasterPetrik are the two bugs you just reported (#960 and #961) those you mentioned here?
Since I was planning to do the 5.4.0 release today or tomorrow. :smile:

**Comment by ItsSohma** [comment]
Once your new release comes out, I'll check it out. I was holding off on the alpha.

**Comment by Bionus** [comment]
I'll make sure to include the macOS (and linux) build then :smile:

**Comment by ItsSohma** [comment]
Thanks, although If you don't want to, I'll just build it. I'm surprised you recognized me since I changed my username.

**Comment by MasterPetrik** [comment]
@Bionus this is bug, that I mentioned thttps://github.com/Bionus/imgbrd-grabber/issues/964

**Comment by Bionus** [comment]
@ItsSohma: Well it's building automatically on Travis so I just have to upload the build I receive on my server when the Travis build ends, so that's pretty easy for me. And I recognized you because it also updated your previous participation on other issues, notably #875 that I implemented for 5.4.0 :smile:

@MasterPetrik: I'll check it out before making the release then.
