### ISSUE TITLE
Recent updates area in Favourites tab not showing when hidden

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#961]
### What steps will reproduce the problem?
1. hide Recent updates area in favourites
2. click left mouse button on any favourite
3. recent results will be loading(I see filling progressbar appears) but Recent updates area still hidden, it is not showing automaticly when you clicking on favourites 

### What version of the program are you using? On what operating system?
5.4.0.a

**Comment by Bionus** [comment]
Reproduced, only applies with merged results.
