### ISSUE TITLE
Sankaku no longer seems to work

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#962]
### What steps will reproduce the problem?
I think this is unique to me, but for whatever reason, my  access to chan.sankakucomplex.com no longer works, and when I went to check out the site itself, I found that for whatever reason I'm banned by I.P address. Now I've no idea how this happened or what could have occurred to warrant it, other than possibly searches made using grabber have somehow resulted in me being considered a DDOS element in some manner.

I really don't know how to dela with this, I can't access the site in remotely any fashion right now, grabber or otherwise.

**Comment by MasterPetrik** [comment]
I doubt that problem is caused by grabber, but anyway use proxie or VPN for now, it may help

**Comment by naruhina2016** [comment]
i think it does have something to do with grabber because every time i use it for sankaku and when its done its stops working i get banned like him it happens every time after downloading pictures

**Comment by Bionus** [comment]
Sorry for the late reply for this issue. 😕 

Yes, for Sankaku you have to use throttling in the source settings if you don't want to be temporarily banned for over-usage. You can find the settings page here:

![iroao77wqqsmejuew3lwrzyqmtepsybqlfaquugmbk75rgjxbxl0yxadndynxcgtlm9bg-0j9grrg0ijzeuxtp5z4ipu7isdd7_pr6k9k_udc4qywyp9w_r7ul89u1jmsrbhukyhjjjuo3txucmvhd6mqdr3pxwwow s0-d-e1-ft](https://user-images.githubusercontent.com/882719/29486757-f9a1fbda-84ed-11e7-9868-7a49528d3327.png)

Setting it to at least 1s per image and something like 4s per page should do the trick and prevent these bans.
Note that Sankaku is blocking Grabber currently, so it wouldn't help that much anyway (see issue #997).
