### ISSUE TITLE
Endlessmode page selector problem + bugs with page info

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#964]
### What steps will reproduce the problem?
1. Open new tab
2. Use one source image search
3. Turn on endless page mode(button variant in my case)

FOR MERGED MODE:
4. turn on merged mode
5. get first page of results
![2017-06-25_014133 win7 mastercore](https://user-images.githubusercontent.com/22294259/27512510-65bff1e2-594b-11e7-977c-f38d5e58c3bf.png)

6. scroll via wheel\button all possible pages
![2017-06-25_014147 win7 mastercore](https://user-images.githubusercontent.com/22294259/27512512-6bad4596-594b-11e7-9a9e-bb6cafd9406b.png)

7. As you can see it shows that loaded not N page, but N+1 page of N pages, of course this page is empty
8. when you try to repeat search, it will show you this:
![2017-06-25_014209 win7 mastercore](https://user-images.githubusercontent.com/22294259/27512519-c79336ae-594b-11e7-9b60-07330d7da7f2.png)

And you will see no images on the page! That's because when you scroll pages in scroll mode, page number also increases, so when you loaded all results page number goes to first page with no results, and this page number remains after repeating of the search, so you get no results for valid request.

FOR NONMERGED MODE:
4. turn off merged mode
5. get first page of results
![2017-06-25_014232 win7 mastercore](https://user-images.githubusercontent.com/22294259/27512712-123cab20-5953-11e7-9e74-f97edc6dc209.png)

6. scroll via wheel\button all possible pages
![2017-06-25_014248 win7 mastercore](https://user-images.githubusercontent.com/22294259/27512713-17294e04-5953-11e7-890e-2a31d429db17.png)

7. As you can see it shows that no results found! but you see a bunch of results at the same time!
It's obviously not normal. It's another bug.
8. when you try to repeat search, it will show you this:
![2017-06-25_014257 win7 mastercore](https://user-images.githubusercontent.com/22294259/27512716-1ec4cecc-5953-11e7-92f1-748c009b87fe.png)

And you will see no images on the page! That's because when you scroll pages in scroll mode, page number also increases, so when you loaded all results mage number goes to first page with no results, but, comparing to merged mode it shows that there is no results at all.

### What is the expected behavior? What do you get instead?
I'm expecting to not increase page number in scroll mode, this is causes all these troubles, and this is should not happen. Page number should be always the same, that was when scrolling started. So if you made search for page 4 and started endless scroll mode, after reload tab page should be still 4, that's how it supposted to work.
And there should not be cases like "page 3 of 2" or button "see more results" on the last page with images, pressing on it causes only it's disappearing -____- 

### How often does this problem occur?
100% repeatability

### What version of the program are you using? On what operating system?
5.4.0.a

### Please provide any additional information below
here is the video of the process
https://drive.google.com/open?id=0B3SK4Pf9wsnmZUl3alRmNzk2Rkk

**Comment by Bionus** [comment]
* [x] One source, merged
* [x] One source, non-merged
* [x] Multiple sources, merged
* [ ] Multiple sources, non-merged
