### ISSUE TITLE
Can't Delete Grabber.exe for reinstall.

### ISSUE THREAD

**Issue by Hazardine** [Bionus/imgbrd-grabber#971]
I'm just tried installing 5.4.0 from 5.2.4. but every time it couldn't replace the Grabber.exe. So I decided to just uninstall the old version and install the new, but it couldn't delete the Grabber.exe. I tried myself but it keeps saying I need administrator permission to do so, but I'm the administrator!!! 

The install error was specifically, MoveFile failed; code 183, shot of it below.
![error capture window](https://user-images.githubusercontent.com/29720842/27568770-9d903826-5ac1-11e7-8bc5-3bbbb32c7ee3.PNG)
Shot of the access denied window.
![error 2 capture window](https://user-images.githubusercontent.com/29720842/27568809-d07fdd68-5ac1-11e7-8e11-b02abcabaadd.PNG)

**Comment by ItsSohma** [comment]
Classic fix is to "Take Ownership". You can easily add this option to the start menu by running [this script](https://www.tenforums.com/attachments/tutorials/140165d1497841908-add-take-ownership-context-menu-windows-10-a-add_take_ownership_with_pause_to_context_menu.reg)

Just download it and open it, then right click on Grabber.exe and select "Take Ownership." You should be able to do anything to it after that.

If you find that you no longer want this option in the context menu, you can [remove it with this script](https://www.tenforums.com/attachments/tutorials/140164d1497841908-add-take-ownership-context-menu-windows-10-a-remove_take_ownership_from_context_menu.reg)

---

[Source](https://www.tenforums.com/tutorials/3841-add-take-ownership-context-menu-windows-10-a.html)

**Comment by Hazardine** [comment]
Just tried it, still can't delete the grabber.exe with the same requiring permission from Admin.

**Comment by ItsSohma** [comment]
In that case, try this tutorial: https://www.techwalla.com/articles/how-to-delete-files-that-need-administrator-permission-on-windows

**Comment by Hazardine** [comment]
Still didn't work, got this new error.
![error the third](https://user-images.githubusercontent.com/29720842/27569313-f8cd2bba-5ac4-11e7-8471-255126488a3c.PNG)

**Comment by Hazardine** [comment]
Fixed now, just had to restart.
