### ISSUE TITLE
Updating grabber through the program instead of manually downloading from github deletes the download history?

### ISSUE THREAD

**Issue by YukiSakuma** [Bionus/imgbrd-grabber#977]
### What steps will reproduce the problem?
It seems when updating grabber through the program rather than manually downloading the update from github.

### What is the expected behavior? What do you get instead?

The "Downloads" tab which contains the history of tag image pages that you have downloaded or plan to download vanished after updating.

### How often does this problem occur?

This is my first time encountering this the last time I updated I manually downloaded the update through github

### What version of the program are you using? On what operating system?

current v5.4, windows 7 x64

**Comment by Bionus** [comment]
The "history" format changed a few versions ago, but Grabber should be able to read both the old and new formats, I'll take a look.

Which version did you update from?

**Comment by YukiSakuma** [comment]
I updated from Grabber_5.4.0a1

**Comment by MasterPetrik** [comment]
@YukiSakuma is this problem still occurs after updating? (to 5.5.0 for example)?

**Comment by YukiSakuma** [comment]
Sorry for late reply, I only recently updated to 5.5.1. It seems the problem was resolved.
