### ISSUE TITLE
Crash After Completing Multiple Batch Downloads

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#980]
### What steps will reproduce the problem?

- Download images in multiple batches. At least one should have over 2000 images.
- Keep your search tab open and keep browsing it, from time to time.
- After sometime, 5 or 6 searches: CRASH
- Restart app, download tab wrongly shows all batches completed downloading.
- Initiate download for all batches again.
- After receiving the notification of completion of all batches, click OK: CRASH
- If nothing happens, click on the downloads tab: CRASH
- Restart app: CRASH

### What is the expected behavior? What do you get instead?

Should have returned to the currently open tab. Crashed instead. 
Now it crashes on every launch.

### How often does this problem occur?

I have used the program for the first time, thought of it as a life saver but now it is just stuck crashing on launch. Can't do anything.

### What version of the program are you using? On what operating system?

v5.4.0

---

Please guide me in removing the session files as even reinstalling it, doesn't sop it from crashing. I can't upload the crash dumps, stupid git, can't even process a zip with no compression...

**Update 1:** I have deleted the folder in AppData\Local to make the app work again through a reinstall. I'll see, if I can reproduce this problem yet again. I hope god has mercy on me, I see enough bugs in my professional life...

**Update 2:** It has something to do with the settings. I'll mix and match to see which setting is causing the app to crash.

**Update 3:** Crash on launch cause: Show Log Unchecked in settings.

**Comment by brazenvoid** [comment]
**Update 2:** It has something to do with the settings. I'll mix and match to see which setting is causing the app to crash.

**Comment by Bionus** [comment]
So from what I understand from your updated message, the actual crash cause was hiding the log in the settings? If so, I can indeed reproduce that disabling the log tab actually causes a crash on starup!

Thanks a lot for your incremental investigation, it helps a lot, I'll be able to fix this in no time thanks to it :+1:

**Comment by brazenvoid** [comment]
Frankly, the app is very prone to crashing while downloading images. The following are the ones I have noticed frequently throughout the day while downloading image:

- App crashes randomly when you initiate a new search. But it does crash soon enough. Some deleted batch references also come back after the restart.
- Download an already partially downloaded batch after a crash.
- Change theme.

For reference, some crash dumps: https://drive.google.com/open?id=0B-5SBhsDznYOUjh1Z3MzRDF5RjQ
