### ISSUE TITLE
[Request] Named Tag Groups

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#981]
It would be very helpful, if we can have named tag groups which could be added to a search through a drop down in the menu bar or in the context menu of the search bar.

Currently, I keep these tag groups in a text file and manually copy paste them for each search query. Such filters allow me to further filter the search depending on content.

**Comment by Bionus** [comment]
Can you give a few examples of such "tag groups"?
I'm not sure I quite understand the point of having something like that.

**Comment by brazenvoid** [comment]
For example: 
1. If I am searching for official art images of a certain series, I would have a tag group called "Official Art" with tags like: width:>=1920 height:>=1080 -photoshop 
2. But the above setting will change, if I am looking for touhou images where the photoshop tag will be dropped in favor of solo and the resolution tags will have lower values.
3. I have a meticulous regiment to scour a series/character with groups of tags applied one after another. This way the downloads have the least amount of undesirables, making my life easier.

**Comment by Bionus** [comment]
I understand then.
I guess a feature like that could be added in a future version. :smile:

**Comment by brazenvoid** [comment]
Thank you.
