### ISSUE TITLE
[Crash] Downloading a big batch with similar results

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#986]
### What steps will reproduce the problem?

- Set to not download when a file exists.
- Download a batch with more than 15000 images from Gelbooru.
- Download a similar batch with many of the same images.
- If first page only contained existing images, it will crash on the second page.

Example:
kantai_collection rating:safe width:>=1920 height:>=1080
kantai_collection rating:safe width:>=1080 height:>=1920

### What is the expected behavior? What do you get instead?

Download proceeds normally.

### How often does this problem occur?

Always

### What version of the program are you using? On what operating system?

v5.4 
Windows 10 x64

### Please provide any additional information below

Debug Files: https://drive.google.com/open?id=0B-5SBhsDznYORzJoeHF0NEJMbGM

**Comment by brazenvoid** [comment]
In the new version v5.4.1, the download completes on the second page. The program shows multiple download completion boxes and crashes. 

Debug: https://drive.google.com/open?id=0B-5SBhsDznYOSkNuYlhfTlJ1UUE

**Comment by Bionus** [comment]
Indeed, I could reproduce that issue on 5.4.1.
It should be fixed in 5.4.2. :+1:

**Comment by Bionus** [comment]
I just published the 5.4.2 version that should fix this crash.
Please tell me if the problems persist :smile:

**Comment by brazenvoid** [comment]
Well it does not crash anymore but it now also downloads those images which are not present in the folder but present in the md5 file. Previously it didn't, is it now expected behavior?

They are not in the folder because I deleted them. This makes downloading updated sets hard.

**Comment by brazenvoid** [comment]
@Bionus

Well it does crash but only if I have already done some huge downloads through the app. Thus doing a restart after every 3-5 downloads is a good workaround, I'll post a crash separately, if I encounter it again.

**Comment by brazenvoid** [comment]
#996 Now this happens instead of a crash...
