### ISSUE TITLE
Can't login to sankaku anymore

### ISSUE THREAD

**Issue by gitgood135** [Bionus/imgbrd-grabber#988]
After i install the program on a new computer, test login always returns failure. And no image can be loaded at all. Don't know if they've changed anything or it's just me.

Tried loading images from other sources, some can be loaded some have the same problem.

**Comment by gitgood135** [comment]
Finally be able to login by using proxy
New problem arises after installed 5.4.2 though, downloaded images can't get original date (even after configured so), and download window don't show the files' size.

Btw may i ask if there's any way to increase the thumbnail size? Using Upscaling make it seems kind of jaggy

**Comment by dalivingman** [comment]
hey im having the same issue but i cant seem to find a tutorial on proxy settings. would you you be able to inform me how to set up the proxy settings? or atleast direct me to a tutorial cuz i cant seem to find one. it would be very helpful

**Comment by gitgood135** [comment]
i'm not having this issue anymore, so at this point i'm not sure if the proxy really fixed it or it's just some temporary error at the time
anyway in case you still need it, go to option>proxy then try different proxies (search for free proxy site on google) until you success, after that it's okay to disable proxy option.

**Comment by gitgood135** [comment]
actually it may has smthing to do with the web servers options, i've tried to change it and now i can't login anymore

**Comment by gitgood135** [comment]
fixed again with proxy, but this time i has to keep the proxy on otherwise it won't work. The speed sucks most time though, and still having issue with download window and original image date

**Comment by dalivingman** [comment]
so i found this site: https://free-proxy-list.net/
what do I put for host? the proxy servers ip? also for ones that say no for https, do i then switch the Type to socks in grabber?
