### ISSUE TITLE
no more search results

### ISSUE THREAD

**Issue by mistamal** [Bionus/imgbrd-grabber#989]
### What steps will reproduce the problem?
applying the usual filters on rule34hentai doesn't yield results any longer ("no results"). Also the application crashes when trying to apply "favorites" filters.

### What is the expected behavior? What do you get instead?
Search results should appear as intended.

### How often does this problem occur?
Every time since 24 hours ago.

### What version of the program are you using? On what operating system?
version 5.4.1 on windows 8.1.

**Comment by Bionus** [comment]
It seems to be caused by some code snipped in their website that stops the page loading after 32KB. I'll see what can be done on Grabber's end to prevent thiss.

**Comment by Bionus** [comment]
It seems to work now, so I'll close the issue.
