### ISSUE TITLE
Quick click crash

### ISSUE THREAD

**Issue by Dyllac** [Bionus/imgbrd-grabber#990]
### What steps will reproduce the problem?
When loading a page, clicking next page and then previous/next page quickly before the page loads crashes the Grabber

### What is the expected behavior? What do you get instead?
It should load the next/previous page but crashes instead.

### How often does this problem occur?
If I click too fast. Always.

### What version of the program are you using? On what operating system?
Grabber 5.4.1
Windows 10 x64

### Please provide any additional information below
I was able to reproduce the crash easiest with e621 and gelbooru, but if I insisted on other sources they crashed as well.
I'll leave the 3 files in case it helps.
[Crash Bug Report.zip](https://github.com/Bionus/imgbrd-grabber/files/1139526/Crash.Bug.Report.zip)

**Comment by Bionus** [comment]
Thanks for the info!

Indeed, when changing page very fast, there's some invalid pointers called when the requests finally completes. The issue will be fixed in the 5.4.2 version. :+1:
