### ISSUE TITLE
Downloaded image count going above the total image count

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#991]
### What steps will reproduce the problem?

Download anything with some blacklisted tags. Source: gelbooru.com

### What is the expected behavior? What do you get instead?

Download count never goes above total image count

### How often does this problem occur?

Always

### What version of the program are you using? On what operating system?

v5.4.1
Windows 10 x64

### Please provide any additional information below

The following example is for a search with only one page, i.e. the total files counter shows the total image count.
http://i.imgur.com/YRQzdWU.jpg

**Comment by Bionus** [comment]
So this only happens with blacklisted images?
But said blacklisted images are still not downloaded, right?
I'll investigate and see if I can reproduce on my end. :smile:

**Comment by brazenvoid** [comment]
Well I always have a huge blacklist so that's why I mentioned it. Yes, those images don't get downloaded,
