### ISSUE TITLE
A few minor problems with 5.4.1 on a fresh install

### ISSUE THREAD

**Issue by Zzzyyzzyxx** [Bionus/imgbrd-grabber#992]
Hello,

I encountered a few problem once I installed the last update of Grabber (5.4.1) on my brand new computer.
Grabber has never been installed on that machine, so it's completely new and fresh install.

After the installation, I changed option to my liking and was confronted with unexpected behaviors : 

General : At Start : Restore last session
When I restart Grabber, The tabs and searches are not restored, only 'Favorites', 'Downloads' and 'Log' are there. The download list is also restored.

Save : If a file already exist : Don't save
If I download pictures from multiples sources, Grabber will download every images from every websites, even when the MD5 is identical.

Save : separated log files
I wish to create a different Txt file for every image downloaded containing all the tags related to that image. This feature seem to have changed from the previous version of Grabber on the way it is included in the option. But whatever I tried until now, I get no Txt files in the same folder with the same names as I used to with older versions of Grabber. Here is how I defined the values :
Name : Tags Txt
Location type : Suffix
Suffix : 
Text File content : %all%

Thanks for all the excellent updates and your hard work.

YMI

**Comment by Zzzyyzzyxx** [comment]
And Also, Grabber does not ask for confirmation when closing while the option is checked.

**Comment by Bionus** [comment]
Wow, "YMI" as in "serize" from the Google Code era? if it isn't someone I haven't seen in a long time! I believe you're still in the "about" window.

I didn't know you were still following the project after all this time! :smile:

> General : At Start : Restore last session
> When I restart Grabber, The tabs and searches are not restored, only 'Favorites', 'Downloads' and 'Log' are there. The download list is also restored.

I couldn't reproduce this one. With the option activated, a tabs.txt file got created (as well as the other restore files) and loaded on next startup, showing my old tabs.

> Save : If a file already exist : Don't save
> If I download pictures from multiples sources, Grabber will download every images from every websites, even when the MD5 is identical.

Indeed, I could confirm just now. Actually, it seems to hide an ever bigger bug introduced in 5.4.1 that also breaks the separate log file feature.
I'll take a look and release an update once I get a fix.

> Save : separated log files
> I wish to create a different Txt file for every image downloaded containing all the tags related to that image. This feature seem to have changed from the previous version of Grabber on the way it is included in the option. But whatever I tried until now, I get no Txt files in the same folder with the same names as I used to with older versions of Grabber. Here is how I defined the values :
> Name : Tags Txt
> Location type : Suffix
> Suffix :
> Text File content : %all%

Yes, the text file setting has been revamped in the 5.4.0 update to merge two features into a more powerful single one.
I believe the issue you have here is that you didn't set any suffix. From what I understand, since you want to generate a .txt file alongside your images, you should add .txt in the "Suffix" field.
But as I said above, I'm afraid the feature may also be broken by the bug from point (2).

> Thanks for all the excellent updates and your hard work.

Still trying my best after all this time :+1:

**Comment by Zzzyyzzyxx** [comment]
Oui, c'est bien ce YMI ;)
Still using Grabber from time to time
but Why would I report bug if I don't find any? 

About the 'General : At Start : Restore last session' bug : 
The tabs.txt file is there in the option, but in previous versions of Grabber, the saved tabs would immediately open. With this version 5.4.1, it takes more than 50 seconds (I counted them) before those tabs are opened. It seem quite abnormal compared to previous versions I knew, and as I saw no tabs open, I really thought they would never open and were lost.
before tabs open, I have this in the Log:

[14:49:25.401][Info] New session started.
[14:49:25.401][Info] Software version: 5.4.1.
[14:49:25.401][Info] Path: C:/Program Files (x86)/Grabber
[14:49:25.402][Info] Loading preferences from C:/Users/YMI/AppData/Local/Bionus/Grabber/settings.ini
[14:49:25.421][Info] Translating texts in English...
[14:49:25.422][Debug] Loading sources
[14:49:25.425][Info] No site for source Gelbooru (0.1)
[14:49:25.429][Info] %n source(s) found: behoimi.org (Danbooru), capi.sankakucomplex.com (Sankaku), chan.sankakucomplex.com (Sankaku), danbooru.donmai.us (Danbooru (2.0)), derpibooru.org (Booru-on-rails), e621.net (Danbooru), gelbooru.com (Gelbooru (0.2)), hijiribe.donmai.us (Danbooru (2.0)), ichijou.org (Danbooru), idol.sankakucomplex.com (Sankaku), konachan.com (Moebooru), rule34.paheal.net (Shimmie), rule34.xxx (Gelbooru (0.2)), safebooru.org (Gelbooru (0.2)), sonohara.donmai.us (Danbooru (2.0)), tentaclerape.net (Shimmie), www.zerochan.net (Zerochan), xbooru.com (Gelbooru (0.2)), yande.re (Moebooru)
[14:49:25.429][Warning] It seems that Imgbrd-Grabber hasn't shut down properly last time.
[14:49:26.502][Info] Loading 5 downloads
[14:49:26.509][Info] Updating settings for tab "Favorites".
[14:49:26.509][Info] Updating checkboxes.
[14:49:26.510][Info] Logging into chan.sankakucomplex.com (chan.sankakucomplex.com)...
[14:49:26.511][Info] Logging into Danbooru (danbooru.donmai.us)...
[14:49:26.512][Info] Logging into e621.net (e621.net)...
[14:49:26.513][Info] Logging into Gelbooru (gelbooru.com)...
[14:49:26.514][Info] Logging into ichijou.org (ichijou.org)...
[14:49:26.515][Info] Logging into rule34.paheal.net (rule34.paheal.net)...
[14:49:26.516][Info] Logging into rule34.xxx (rule34.xxx)...
[14:49:26.516][Info] Logging into xbooru.com (xbooru.com)...
[14:49:26.560][Debug] End of initialization
[14:49:47.703][Info] JSON error reply: "Anonymous users can only view 25 pages of results, sign in to view more!"
[14:49:47.703][Info] Loading using Json failed. Retry using Html.
[14:50:27.863][Info] Logging into chan.sankakucomplex.com (chan.sankakucomplex.com) finished (failure).



About 'Save : separated log files'
I did not knew what 'suffix' could be, so I left it blank. Should it not be called 'extension' instead?
I added '.txt' to the suffix variable, but no txt files.

Thanks

PS : what is JSON that seem to take so much time to connect and might be the cause of delay in appearance of tabs?

**Comment by ItsSohma** [comment]
> PS : what is JSON that seem to take so much time to connect and might be the cause of delay in appearance of tabs?

JSON is a format for storing data kind of like XML, but is generally faster. It shouldn't cause a delay unless there's a lot of it.

**Comment by Bionus** [comment]
> About the 'General : At Start : Restore last session' bug :
> The tabs.txt file is there in the option, but in previous versions of Grabber, the saved tabs would immediately open. With this version 5.4.1, it takes more than 50 seconds (I counted them) before those tabs are opened. It seem quite abnormal compared to previous versions I knew, and as I saw no tabs open, I really thought they would never open and were lost.
> before tabs open, I have this in the Log:

It seems that it even took around 60 seconds. Thankfully we can see from the log the exact cause of the issue. It must be that you have Sankaku enabled in one of your tabs (or in your sources), causing Grabber to try to log into it before loading the tabs (Grabber first logs into all activated sources to ensure there's no "no results" page in case your tabs contain restricted searches).

In this case, as ItsSohma said, it seems that the JSON login request to Sankaku timeouted after 30s, causing Grabber to re-try in HTML (Regex) mode, which also timeouted after 30 more seconds (total: your measured 60s). Maybe Sankaku is blocked where you are? (or maybe Sankaku blocked you for over-use, I know they're quite extreme on their securities)

> About 'Save : separated log files'
> I did not knew what 'suffix' could be, so I left it blank. Should it not be called 'extension' instead?

The problem with "extension" is that you can choose a non-extension as suffix, such as ".info.xml" for import in some specific programs (Hydrus for example). I prefer having a name as inclusive as possible.

> I added '.txt' to the suffix variable, but no txt files.

Yeah, it's cause by the same bug as point (2). The [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly) should include the fix. I'll try to make a new "real" release ASAP however, as it's a very important bug IMHO.

**Comment by Bionus** [comment]
I just published the 5.4.2 version that should fix the external file and duplicate MD5 issue.
Please tell me if these problems persist :smile:

As for the loading time, did disabling Sankaku fix it?

**Comment by Zzzyyzzyxx** [comment]
I tried to run the new version,
but was unable to make Sankaku work correctly, and tried to fix that for about 1 or 2 hours, maybe.
and then checked the issue board and saw it was a common problem for everybody...

Is there an easy fix available anytime soon for that evil website?
As I wished to experiment the new grabber with it.
If no, once I have a bit a free time, ill try to see if the issue I met are still there without this infamous site.

thanks. a+.

**Comment by Bionus** [comment]
Yes, Sankaku is blocking Grabber, you can see issue #997.

As said there, I'm not really willing to bypass it this time, as Sankaku's owner is obviously doing it purposedly. If you want to try however, you can always edit Sankaku's `model.xml` file yourself. :smile:
