### ISSUE TITLE
Wrong "getting started" link during first launch

### ISSUE THREAD

**Issue by SweetKawaiiPanienka** [Bionus/imgbrd-grabber#994]
### What steps will reproduce the problem?
1. Install the app (version 5.4.1).
2. Start it. First launch window should appear.
3. Click on "getting started" link.

### What is the expected behavior? What do you get instead?

Page with 404 error.
The link points to https://bionus.github.io/imgbrd-grabber//wiki/GettingStarted instead of https://github.com/Bionus/imgbrd-grabber/wiki/GettingStarted

### How often does this problem occur?

Every time when displaying first launch windows

### What version of the program are you using? On what operating system?

5.4.1
Windows 10

**Comment by Bionus** [comment]
Indeed, after I created the website, seems like the link is off.
I'll update that in next version, thanks! :+1:

It's unfortunate the new users of the past month couldn't access this page given how useful it can be.
